### ISSUE TITLE
API EtherpadLiteClient and HTTPS

### ISSUE THREAD

**Issue by kingmook** [ether/etherpad-lite#1053]
I've been working to implement Etherpad-Lite via HTTP with API calls to great success. My challenge now is to implement via HTTPS.

Using Nginx for proxy passing I am able to directly access https://myurlhere.com:9000/api (gettings the lovely Cannot GET /api). Perfect.

When I then use this url for "new EtherpadLiteClient" no connection can be made. The connection will work when i use my non SSL fallback (http://myurlhere.com:9001/api). 

Do you think this is a problem with my Nginx setup (taken generally from the https proxy tutorial) or does the Etherpad-Lite API not do HTTPS?

**Comment by flotho** [comment]
Hi, 
Maybe a little old but this could sounds the same problem as #2754 , am I right?
