### ISSUE TITLE
/admin does not work when using reverse proxy

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#1074]
I wanted to add some plugins. Did not work.

Server errror log shows:

```
user admin not found: /admin
user admin not found: /error/HTTP_UNAUTHORIZED.html.var
```

Version  4296518

**Comment by flotho** [comment]
Hi @Lucas-C which version of Apache do you use?

**Comment by Lucas-C** [comment]
Sorry, I can't tell : I don't use Apache anymore. I moved to Nginx.
