### ISSUE TITLE
Pad name length is limited to 50 chars... that's maybe not enough.

### ISSUE THREAD

**Issue by vaab** [ether/etherpad-lite#1116]
Here's the function in `node/db/PadManager.js`

```
exports.isValidPadId = function(padId)
{
  return /^(g.[a-zA-Z0-9]{16}\$)?[^$]{1,50}$/.test(padId);
}
```

Why 50 chars ? I'm hitting the limit in applications as OpenERP, while I guess that they could try to make page identifier much smaller, 50 characters could seem a little small in general for application embedding etherpad and generating long identifiers. 

Why not `256` ? this would settle down those issues on this topic for a time and fall on a power of two.

I quickly glanced at my sqlite database .schema and it tells me that size doesn't matter ;)
Didn't check the other database schema so I don't know if there are some hard written limitation in their schema.

And BTW, could someone clarify what is the first optional part of the regexp matching `g.[a-zA-Z0-9]{16}\$` ?

**Comment by fooness** [comment]
This bug is pretty much real and happens all the time when using Etherpad integration widgets in Matrix / Element https://element.io/ …

**Comment by flancian** [comment]
Hello from the future! I've hit this limit :)

https://stoa.anagora.org/p/a-signaling-mechanism-that-opens-communication-in-explicily-designated-channels returns 'such a padname is forbidden'.

Perhaps we could first just raise the limit to 100 safely? That seemed like a better default based on post 3 by @vaab. Happy to send a PR if needed.

**Comment by webzwo0i** [comment]
100 would be too aggressive. Long keys usually are: `pad:padName:revs:123456`. I've regularly seen revisions beyond 100k. 100-18 probably works for most of the instances... I'll probably won't accept a PR that only includes increasing the limit, but there needs to be research, which supported databases use what max length and if it can be increased easily.

Also there is a need for a migration script if we need to change the database schema, which is something I don't feel very comfortable to run automatically after an update.

If people feel hacky, they can increase the limit as described in this issue :-)
