### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by miniminime** [ether/etherpad-lite#1140]
Hello everyone,

I did search for a plugin/feature where the users could in addition to the name of the pad also provide a passphrase to encrypt the whole text. That way I could ignore the whole ACL question/issue altogether.

As my search wasn't successful: Did I look in the wrong corners? If not, would you accept this idea as a feature request?

**Comment by JohnMcLear** [comment]
@GreatGrandMasterB you can move this forward using this: https://www.bountysource.com/issues/1371899-encryption
