### ISSUE TITLE
Syntax Highlighting Plugin

### ISSUE THREAD

**Issue by itguy51** [ether/etherpad-lite#121]
I would think that there is an opportunity to push Etherpad Lite to more people by adding a syntax highlighting module for the users that are going to operate this in a programming environment. I think the major issue (By looking at the code) is how to apply the CSS styles invisibly, because the whole iframe contents are pushed up to the server. If this is possible, I would be willing to debug it.

**Comment by beppe9000** [comment]
is this plugin used on any public etherpad instance?
