### ISSUE TITLE
Auth rfc -- how about this?

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#1211]
_During the auth meet-up in October, I had an idea, that I'd like to rescue from the pad now and expose it to all the critical minds bustling around in here ;). The original contents live at http://beta.etherpad.org/p/ep-auth-conference_

Ok, so there are two things we should tackle separately: http auth and per pad auth (aka socket.io auth)
# HTTP Auth
## the existing authenticate/authorize hook pair

... is only suitable for static http resources like `/admin/plugins`.

Each hook is called with the request object, and registered hook callbacks are called one at a time until one is found that returns a non-empty list. When a method is found that returns non-empty list, the fist item of the returned list is used to determine if access is granted / authentication succeeded (it should be true/false).
## How it works

A request comes in:
1) Try to just access the thing using authorize (checks session cookie for example)
2) If authorize fails, try to authenticate (e.g. using already supplied credentials HTACCESS, or by redirecting to a login page)
3) If authentication succeeds, try to access the thing again
4) If all els fails, give the user a 401 to request new credentials (this should be done in one of the hooks actually, not by epl itself!)

If authentication/authorization succeeds, the contents are delivered to the user, so there's no going back once you granted access to a user using _http_ auth. So, http auth is useful for static content only but it's certainly not very useful for "per pad" authentication (since all pads share the same html and you should also be able to kick users!).
# Per pad auth

First up: Socket.io != Http
Socket.io doesn't provide cookies (nor any other http functionality) along with it's messages. This is because it might not be using http at all, but flash sockets or real websockets. Socket.io thinks in connections.(currently, we assume, that a specific connection is a specific user, but this causes some problems as described in #753).

Now, let's get to my idea:
- Client
  - Sends the sessionID along with every request
  - if unauthenticated: message to client (displays a message); plugins will be notified.
  - if authorization fails: message to client (displays a message); plugins will not be notified
  - plugins may take actions to request a users credentials (e.g. display some login screen, if the user is unauthenticated)
- Server
  - s.io Authenticate hook
    - ties a connection to a user (actually confirming that the user with that sessionID was logged in before)
    - called once (or more times -- until the user is can be authenticated) per socket.io connection
    - plugins hook into this -- or, do they actually need to? (see *note1)
  - s.io Authorize hook
    - checks whether the user tied to the connection is allowed to access that pad
    - called on each socket.io message
    - plugins hook into this

*note1:
The question is, whether we still want require people to use our own session management (like, we hardcoded the way our session cookie is read and sent to the server via socket.io to be checked against a certain list of sessions).
We could ditch our current session implementation completely and require people to create their own system for setting a sessionID on the client and letting the socket.io server know which one it's communicating with, but I don't think there's much to be gained from that approach.
another approach would be to simply require people to interact with _our_ session management for logging in a user and leave the rest to us (like setting and transfering the sessionID and checking, whether a user is logged in). Plugins would still be able to fully control the login process and pad access.

**Comment by JohnMcLear** [comment]
Dropping this as we're not baking auth into Etherpad, we're letting plugins handle auth.  So far it's worked well and we have a lot of support for different mechanisms.
