### ISSUE TITLE
Add date to chat-msg

### ISSUE THREAD

**Issue by t3k4y** [ether/etherpad-lite#1285]
First: Thank you for your work!

It would be very helpful to see at which day a chat-message is sent. 
- Maybe a timestamp when hovering time? 
- Or a date-line inserted when changing day and there is a msg this day?

**Comment by JohnMcLear** [comment]
Help us help you: https://www.bountysource.com/issues/1371882-add-date-to-chat-msg

**Comment by Dhwty** [comment]
I think this plugin might address this issue: https://www.npmjs.com/package/ep_chatdate

It appears to add the date to the timestamp on chat messages.
