### ISSUE TITLE
Inconsistency in API return values

### ISSUE THREAD

**Issue by Gared** [ether/etherpad-lite#1306]
There is an inconsistency in the api http://etherpad.org/doc/v1.2.0/#index_ispasswordprotected_padid.
The function "isPasswordProtected" returns something like "{code: 0, message:"ok", data: {passwordProtection: true}}"
but the function "getAuthorName" returns something like "{"code":0,"message":"ok","data":"test"}".
It is both valid json, but in the first case the value in data is an array and in the second case it is only a string.
I would prefer a return value like "..."data":{authorName:"test"}}" in the second case to be consistent.

**Comment by JohnMcLear** [comment]
No need to fix this really it's not ideal but it's well documented.  https://etherpad.org/doc/v1.8.0-beta.1/#index_client_side_hooks
