### ISSUE TITLE
API: Add possibility to delete last revision

### ISSUE THREAD

**Issue by disy-mk** [ether/etherpad-lite#1419]
We should have a possibility to remove the last revision. That could be used to implement another request, namely #383

**Comment by JohnMcLear** [comment]
Move this forward at https://www.bountysource.com/issues/1371867-api-add-possibility-to-delete-last-revision

**Comment by JohnMcLear** [comment]
https://etherpad.org/doc/v1.8.0-beta.1/#index_restorerevision_padid_rev
