### ISSUE TITLE
pad.collabClient is null

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#1471]
When I open a pad running latest develop, i can observe the following error in my console:

```
TypeError: pad.collabClient is null
pad.collabClient.setChannelState("CONNECTED");
```

**Comment by iwkse** [comment]
Hi, I'm having the same issue. I'm using a plugin which uses etherpad API [0] and I get this error. I'm using latest GIT version, I've test both on Firefox and Chromium.
Do you have any idea?

[0] https://github.com/cetra3/etherpad-alfresco/issues/1
