### ISSUE TITLE
OPERA: Opera shows two indentations when hitting tab key

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#1508]
Search for 

```
// This stops double enters in Opera but double Tabs still show on single tab keypress, adding keyCode == 9 to this doesn't help as the event is fired twice
```

 in ace2_inner.js

**Comment by JohnMcLear** [comment]
Fixed in Opera.

**Comment by JohnMcLear** [comment]
Bug still exists in Opera.

**Comment by JohnMcLear** [comment]
Closing as opera is practically dead.

**Comment by slel** [comment]
Reported the bug Opera using their bug report wizard at

    https://help.opera.com/en/computer-bug-wizard/

Their bug tracking does not seem to be public.
In their bug tracker the bug now has this ID: DNAWIZ-104726.

**Comment by JohnMcLear** [comment]
Awesome thanks.
