### ISSUE TITLE
Allow wider range of colours

### ISSUE THREAD

**Issue by jeff-h** [ether/etherpad-lite#151]
The colours available in the user colour picker don't go very close to white at present. It would be nice to be able to choose lighter colours, which would allow greater contrast on the text. It does conversely allow you to choose quite dark colours which ultimately can be quite difficult to read.

It's possible my computer's gamma comes into play — I'm using OS X, which has lighter default gamma than Windows (not sure about Linux) so on Windows I would expect this issue to be even more noticeable as the same colours will appear even darker.

**Comment by gulaschskanone** [comment]
@0ip take a look at [ep_brightcolorpicker](https://www.npmjs.com/package/ep_brightcolorpicker) and feel free to improve that

**Comment by gulaschskanone** [comment]
Need help: The plugin mentioned above discards the colors chosen so the next visit it does not have colors. Does anyone know how colors can be chose persistently?

**Comment by gulaschskanone** [comment]
solved
