### ISSUE TITLE
Allow linking to specific line numbers

### ISSUE THREAD

**Issue by aendra-rininsland** [ether/etherpad-lite#1520]
It doesn't seem like there's currently any way to link to specific line numbers in an Etherpad -- this would be useful for large transcripts of discussions, and probably wouldn't be that difficult to add. 

Please let me know if this doesn't exist and I'll consider writing a patch. Thanks!

**Comment by dcht00** [comment]
Update: This works.
You just need to add "#L123" (for line 123) at end of your pad URL.

Note it only works when you load the pad initially - not on an already open pad.
