### ISSUE TITLE
Some API endpoints change data with GET rather than POST

### ISSUE THREAD

**Issue by Miserlou** [ether/etherpad-lite#1521]
This is poor API design as it introduces a potential security vulnerability.

I'd suggest this be changed some time in the future, but not without a heads up as it will break all of the client libraries. :(

**Comment by JohnMcLear** [comment]
@anttiviljami -- Any chance #3786 could resolve this please?

**Comment by anttiviljami** [comment]
I mean sure, but it would be a major breaking API change.

**Comment by anttiviljami** [comment]
I would probably just extract the current OpenAPI definition, modify it to create a new properly designed, restful version of the API and just expose it as a new major API version while supporting the old API for a while. Would be easy to do with `openapi-backend`

**Comment by JohnMcLear** [comment]
+1 will be a 1.9 thing :)

**Comment by JohnMcLear** [comment]
@anttiviljami was it possible for you to send through a PR including this breaking change please?

**Comment by anttiviljami** [comment]
Sorry @JohnMcLear. Too busy right now for pro bono work :(

**Comment by heldersepu** [comment]
Is this still a problem?
Did we ever collected a list of those `GET` endpoints that change data?

**Comment by SamTV12345** [comment]
> Is this still a problem?
> 
> Did we ever collected a list of those `GET` endpoints that change data?

Are they included in the open api definition?

**Comment by heldersepu** [comment]
This is worst than what I imagined:
https://petstore.swagger.io/?url=https://etherpad.wikimedia.org/api/openapi.json#/default/getStatsUsingGET

Every endpoint has GET and POST, some should have GET only other POST only, 
... and a few other should be DELETE or PUT

Quite a large undertaking for sure!
if it breaks client libraries this is really an inconvenient change for many

**Comment by SamTV12345** [comment]
> This is worst than what I imagined:
> 
> https://petstore.swagger.io/?url=https://etherpad.wikimedia.org/api/openapi.json#/default/getStatsUsingGET
> 
> 
> 
> Every endpoint has GET and POST, by the naming conventions I would suggest change:
> 
> - most should have GET only or POST only 
> 
> - few should be DELETE or PUT
> 
> 
> 
> Quite a large undertaking for sure!
> 
> if it breaks client libraries this is really an inconvenient change for many
> 
>  
> 
> 
> 
> 
> 
> 

Oh. Yes so let's keep it simple and just add endpoints and not remove the old ones. I bet there are people out there using Get for a post. I think some were also more named after functions instead of resources.

**Comment by heldersepu** [comment]
@SamTV12345 sorry but I strongly disagree the OP got it right:
> poor API design + a potential security vulnerability

If we decide to refactor we should do it right and remove those: 
- GET that change data
- POST that only retrieves data

**Comment by SamTV12345** [comment]
> @SamTV12345 sorry but I strongly disagree, the OP got it right:
> 
> > poor API design + a potential security vulnerability
> 
> 
> 
> If we decide to refactor we should do it right and remove those: 
> 
> - GET that change data
> 
> - POST that only retrieves data
> 
> 
> 
> Make this for far in the future change, maybe next major version change

That would be the other option. Many use Etherpad for scripting so if we refactor the things I agree that this would mean Etherpad 3.x

**Comment by SamTV12345** [comment]
This can be closed. We introduced a new API and the old will be removed in the next major release.
