### ISSUE TITLE
Unable to export group pads

### ISSUE THREAD

**Issue by ozkatz** [ether/etherpad-lite#156]
Hi,

First of all - Etherpad Lite is AWEOSME. so thanks very much for that :)
I am having one issue though, where I can view group pads by getting a session ID and setting it as a cookie
(i.e. after setting the sessionID cookie, doing `GET /p/<pad id>/`  works fine and I have access).

problem happens when I try to do a `GET /p/<pad id>/export/txt` or `GET /p/<pad id>/export/html` - in both cases i'm getting
a "403 - can't touch this" message displayed. the same HTTP call for a public pad works just fine..

Thanks again for the awesomeness that is Etherpad Lite.
Oz

**Comment by chitwarnold** [comment]
not solved yet 2015 is almost over

**Comment by JohnMcLear** [comment]
This was fixed.  Please provide steps to replicate if you have a bug.

Also we know the fucking date, don't be a dick.

**Comment by chitwarnold** [comment]
courtesy is a virtue, and when your writing software for open source there is no need for you to be rude, without the rest of the world you could never know of all the use case of your project/software. now am guessing a ~ couldn’t be this reasonable. community is important in open source always remember that.
