### ISSUE TITLE
pad url is leaked whenever a link is clicked

### ISSUE THREAD

**Issue by elijh** [ether/etherpad-lite#1603]
**The problem:** if a user clicks on a link in the main body or in the chat, the referrer is sent by the browser to the new website showing the full url of the pad, thus revealing the pad's content and history. Typically, this referrer information information is logged and stored by the target website.

**Why this is bad:** most users probably do not realized that clicking on a link in a pad automatically shares the pad with the website they clicked on (!).

Solutions:

**(A)** HTML5 has a `noreferrer` option for links, but is is not widely supported. Move along.

**(B)** One option would be to disable the auto-links in etherpad. As far as I can tell, these can be disabled in ace2_inner.js `handleClick()` and pad_utils.js `escapeHtmlWithClickableLinks()`. 

**(C)** Another option would be to change the way pad names are encoded in the URL to use the location hash instead of the path. For example, instead of `https://pad.riseup.net/p/0Jr0e` etherpad could use `https://pad.riseup.net/#0Jr0e`. The location hash (anchor) is not sent as part of the referrer.

**(D)** A final option is to create an interstitial page as part of etherpad. For example, every link would really go to `/redirect/`, where it would then get auto redirected on to the target website. The final target website could be sent to the request to `/redirect` either as a POST or in the location hash. For example, `/redirect#https%3A%2F%2Friseup.net%2Fwhat-is-my-referrer' would redirect to https://riseup.net/what-is-my-referrer.

Option D seems to me that it is probably the best for the moment: it would be easy to implement and it retains the usability of clickable links. On the downside, interstitial pages are slightly annoying because they make it a bit slower to get to the site you want.

Notes:

https -- If the pad is loaded via https, then the referrer is only sent to other https websites. This is small comfort, but important to know if you are trying this at home. 

chrome -- Chrome is not able to figure out what the referrer should be of the inner ace iframe. I suspect this is because it is dynamically generated. The result is that if you click on a link in a pad body using chrome, no referrer is sent. Firefox has no such confusion, and links from the chat always send referrer in all browsers.

testing -- You can use https://riseup.net/what-is-my-referrer as a link to test if the referrer is being sent by the browser. Make sure to specify `https` and not `http` because the plain `http` link will redirect and erase the referrer.

**Comment by joelpurra** [comment]
Here's a test page, showing leaking pad URL to external links through HTTP referer.
https://etherpad.mozilla.org/eFJXwtxPJu

**Comment by JohnMcLear** [comment]
@joelpurra lulwut.  MoPad is not running Etherpad.  It's running an old abomination of Etherpad we don't even support any more.  Tell MoPad to update.

**Comment by joelpurra** [comment]
@JohnMcLear: is the problem fixed in the latest etherpad then?

**Comment by joelpurra** [comment]
@JohnMcLear: and where is a more recent public version I can test this on?

**Comment by JohnMcLear** [comment]
http://etherpad.org -- Download and test it -- Read this issue.

**Comment by joelpurra** [comment]
@JohnMcLear: fuess it's not fixed:
https://beta.etherpad.org/p/http-referer

**Comment by joelpurra** [comment]
@JohnMcLear: so the problem is money? I see.

**Comment by joelpurra** [comment]
Applied `rel="noreferrer"` in #2498. It's better than nothing and is a very simple patch, as you can see.

**Comment by JohnMcLear** [comment]
Some people might not want this though..

**Comment by xshadow** [comment]
Could there be an option as described in https://github.com/ether/etherpad-lite/issues/2731 ?
There won't be many changes to do:

It would be great to set two options in settings.json 

>    /* Privacy: enable dereferring */
>   "enableDerefering" : True,
>   "derefererUrl": "https://dereferrer.foobar.org/"

and an adjustment in the link constructor accordingly.

At the moment I use @JohnMcLear ep_hide_referrer but that requires a user interaction ( a click ) - if you could use your own refererrer that would not be necessary and the users weren't bothered with it :)

**Comment by rugk** [comment]
Recent news about this issue for webadmins (or a possible inclusion into Etherpad): You can fix the referrer issue by using a CSP header (a relatively new security feature of major browsers). Just set  the [referrer](https://scotthelme.co.uk/csp-cheat-sheet/#referrer) value. E.g. in this way: `Content-Security-Policy: referrer no-referrer;`

FYI you can do much more with a CSP. [Create your CSP here](https://report-uri.io/home/generate).

**Comment by dkg** [comment]
Ther'es also `Referrer-Policy`, https://www.w3.org/TR/referrer-policy/

**Comment by rugk** [comment]
Yes, in https://github.com/ether/etherpad-lite/pull/3044, I added this.

**Comment by muxator** [comment]
Etherpad **1.8.0** changed its referrer policy and started sending `Referrer-Policy: same-origin` HTTP header.

Discussion & PR: https://github.com/ether/etherpad-lite/pull/3636

Note to self about CSP: the use of CSP for configuring referrer policies [has been deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/referrer). The current standard prescribes the use of `Referrer-Policy`.
