### ISSUE TITLE
have PAD sync to .txt file in dropbox (or similar)

### ISSUE THREAD

**Issue by theoryshaw** [ether/etherpad-lite#1654]
Hi, has anyone run across a plugin or etherpad functionality that will sync to a plain text file via a service like Dropbox (or equivalent)?

Thanks, Ryan

**Comment by JohnMcLear** [comment]
Bounty available here: https://www.bountysource.com/issues/1371814-have-pad-sync-to-txt-file-in-dropbox-or-similar - please add to it!

**Comment by JohnMcLear** [comment]
I have a pad sync to git, both text and pad available.

See dirty_db_git (part of the next version of ueberdb) for entire database syncing capability.

See https://github.com/JohnMcLear/ep_git_commit_saved_revision which commits pad text when you hit save revision.
