### ISSUE TITLE
Ask for feedback on plugin uninstall

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#1670]
When a site admin uninstalls a plugin it'd be good to know why they are uninstalling or even uninstall stats or something..

That would help developers know if there plugin is broken.

**Comment by JohnMcLear** [comment]
@gared were you hacking in this area buddy?

**Comment by Gared** [comment]
@JohnMcLear No, because I don't want to track installation statistics and if we would do this I'm not sure if these informations would really help us. 
But I like the idea to add a link to the github issue page or add other informations to the plugin area to contact the plugin author

**Comment by JohnMcLear** [comment]
Ack, also btw I deprecated some plugins today and I'm not sure how our UI reflects that change?

**Comment by Gared** [comment]
What do mean with "deprecated". Have you unpublished them? Please give me an example package and I can investigate if everything is working as expected

**Comment by JohnMcLear** [comment]
I couldn't unpublish as multiple collaborators, but in npmjs you can set to deprecated

https://www.npmjs.com/package/ep_subscript

**Comment by Gared** [comment]
Fixed it. Packages are not in the list anymore

**Comment by JohnMcLear** [comment]
Did you mean to say deprecated packages ? :P

**Comment by Gared** [comment]
Yes, deprecated packages :D

**Comment by JohnMcLear** [comment]
Awesome thanks, btw I used it today to identify which of my plugins are being used.  A lot of people were using the ``ep_subscript_and_superscript`` plugin but not the individuals are it was really poorly maintained.  So because of that I rewrote the plugin, made it awesome and then updated the one everyones using from npm :)  So yay!

**Comment by Gared** [comment]
Glad to hear that it is useful :)
If you have any ideas how we can improve the page let me know (or open an issue)
