### ISSUE TITLE
Rip apart the pad content into separate parts

### ISSUE THREAD

**Issue by theoryshaw** [ether/etherpad-lite#1679]
I could be wrong here, but from what I understand, you can have multiple etherpad instances running on one web page.

If that is the case, is there a performance ceiling--i.e. a range of etherpad instances when things start bogging down?

If i'm wrong, and you can't have multiple instances running on a webpage, has there been any discussions to implement?

**Comment by JohnMcLear** [comment]
Closed as most of this is resolved.
