### ISSUE TITLE
Pads fails to open pads on IE8

### ISSUE THREAD

**Issue by otetard** [ether/etherpad-lite#1724]
When trying to open a pad using Internet Explorer 8 with the latest stable version of Etherpad (1.2.91) the following error is raised:

> CLIENT SIDE JAVASCRIPT ERROR: {"errorId":"rJZW1YAD6tnNtexejxjJ","msg":"'this.language' is null or not an object","url":"https://pad.XXX.org/p/rPJA4PgzGK","linenumber":1,"userAgent":"Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/4.0; Data Center; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)"}

This issue seems to be similar to #1392, but applies here on 1.2.91.

Thank you!
Olivier;

**Comment by smlavoie** [comment]
Since our upgrade to 1.4, pads are not rendered on I.E. 9 or below.  Any clues?

**Comment by smlavoie** [comment]
I tried emptying the cache, I tried the developeré's console. Either it stays on loading on get to a similir screenshot  of Olivier  (April 10th 2013).

Uninstalling the few plugins we have didn't change a thing.

**Comment by JohnMcLear** [comment]
@smlavoie Please bisect to discover which commit is causing the issue: http://mclear.co.uk/2013/04/02/using-git-bisect-to-debug-etherpad-issues/

**Comment by smlavoie** [comment]
Unfortunately, we do not have the required resources to accomplish the bisect operation. 

FYI, we're running 1.5.1 not 1.4 as stated earlier and the problem is related to 1.5.1 not 1.4

**Comment by webzwo0i** [comment]
If you see the screenshot like above than what is the error message and line it refers to?

**Comment by smlavoie** [comment]
Here is the error message : 
An error occured
The error was reported with the following id: 'flT4BTTWYZ6SwVaMJYpf'
Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster: 
'ErrorId: flT4BTTWYZ6SwVaMJYpf
URL: http://epad.ticfga.ca/p/27fev2015-3
UserAgent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3) Impossible d'exécuter le code à partir d'un script libéré in http://epad.ticfga.ca/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 2618'

**Comment by smlavoie** [comment]
Thanks for your assistance! It is appreciated.

**Comment by JohnMcLear** [comment]
Sorry but if you can't bisect I can't help you.

**Comment by smlavoie** [comment]
Hi John, I know you told me to bisect but we don't have the resources to do it. Our sysadmin is on a per hour basis, we're a public school, so money is not abondant.

But, maybe you could look into the beta version? https://beta.etherpad.org/ I do have exactly the same problem with the beta version. Using IE 9 or 10, it stays forever on loading (chargement) and sometimes get to an error.

So, why should I bisect our instance (which runs the latest version of etherpad lite) if even the beta version is not working correctly with IE 9 or 10?

Thank for your understanding!

**Comment by JohnMcLear** [comment]
You don't need your sysadmin to do the bisest. Follow the guide you can do it yourself.  I don't have an ie8 machine, if you want to ship me one to test with I can.

On 28 Feb 2015 01:36, smlavoie <notifications@github.com> wrote:

Hi John, I know you told me to bisect but we don't have the resources to do it. Our sysadmin is on a per hour basis, we're a public school, so money is not abondant.

But, maybe you could look into the beta version? https://beta.etherpad.org/ I do have exactly the same problem with the beta version. Using IE 9 or 10, it stays forever on loading (chargement) and sometimes get to an error.

So, why should I bisect our instance (which runs the latest version of etherpad lite) if even the beta version is not working correctly with IE 9 or 10?

Thank for your understanding!

**Comment by smlavoie** [comment]
I'm not a CLI guy and I don't have time for this (bisect). I'm a etherpad user, not a programmer nor a linux user. I made more tests though on two differents etherpad instances (besides ours and beta) and they all behave the same way with IE 9. So, as a good opensource software user, I report the problem.

As for sending you a machine to test IE9, may I suggest you try a virtual machine (VM)? Take a look at https://www.modern.ie/en-us/virtualization-tools#downloads , you'll have what you need to test Etherpad on IE 9.

My actual users are from different school districts in Canada, and I unfortunately have more than 35% requests coming from IE browser! It is really out of my control, I have to work with this reality. And I would very much like my teachers and students to use etherpad.

Again, thanks for your understanding and your help.

**Comment by JohnMcLear** [comment]
@smlavoie well if you don't have time to help debug we don't have time to fix it for you(it takes a lot longer to fix things than to bisect).  Open source is a give/take thing, you will learn that quickly.

**Comment by JohnMcLear** [comment]
@smlavoie you might want to reach out to http://etherpad.org and ask them about commercial support.  If you are pressed for time you can offload to them.
