### ISSUE TITLE
Express is stuck at 3.1.0

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#1738]
3.1.1 is also fine

**Comment by devoidfury** [comment]
Started on this here: [devoidfury/etherpad-lite/tree/express4](https://github.com/devoidfury/etherpad-lite/tree/express4). The etherpad-yajsml exported static server isn't compatible, so we'll need to either wrap it or update it.

**Comment by JohnMcLear** [comment]
Nice @devoidfury!  Amazing!  So fast too...

**Comment by JohnMcLear** [comment]
Solved thanks to @devoidfury  =)
