### ISSUE TITLE
Chrome bug: Control/Command + F searching doesn't scroll to the found text

### ISSUE THREAD

**Issue by guacamoli** [ether/etherpad-lite#1742]
When finding strings using the browser's ctrl/cmd + F command, EPL doesn't scroll down to the found string.

**Comment by LaKing** [comment]
I will. Only a question of time.
The modularisation process is not complete yet, but ....

In ep_codepad all javascript for the pad-search-and-replace is located clean in one file. /static/js/padsearch.js
The UI elements are defined in /templates/menuLeft.ejs

**Comment by JohnMcLear** [comment]
https://github.com/JohnMcLear/ep_copy_paste_select_all provides the ability to replace

Maybe we should just extend that with find?

**Comment by JohnMcLear** [comment]
Unassigned myself as this is an upstream bug and will get fixed when someone from the webkit team decides to work on it.

**Comment by JohnMcLear** [comment]
Fixed upstream
