### ISSUE TITLE
password protected pads

### ISSUE THREAD

**Issue by nilsja** [ether/etherpad-lite#176]
is it possible to include a feature that allows acces to a pad only wih a password set by the pad creator?

**Comment by 3arn0wl** [comment]
I think it would be really useful to have password protected pads.

**Comment by JohnMcLear** [comment]
@3arn0wl you can

**Comment by 3arn0wl** [comment]
Hi

I'm new to Etherpad, and am keen to use it and promote it. However, I don't 
see a password function on the web version of Ethernet?

3

On Sunday, 29 April 2018 07:51:52 CDT, John McLear 
<notifications@github.com> wrote:
> @3arn0wl you can
> 



-- 
Sent using Dekko from my Ubuntu device
