### ISSUE TITLE
Minify JS/CSS files for installed plugins into 1 file

### ISSUE THREAD

**Issue by guacamoli** [ether/etherpad-lite#1777]
I noticed that when you turn on minification in settings.json, it doesn't minify installed plugins JS/CSS files into 1 FILE. Is there a way to include all plugins in the minification process? The text still gets minified but I want all the JS and CSS to live in one file like the rest of the code.

**Comment by JohnMcLear** [comment]
Help sponsor the development of this: https://www.bountysource.com/issues/1371788-minify-js-css-files-for-installed-plugins-into-1-file

**Comment by JohnMcLear** [comment]
cc @redhog

**Comment by redhog** [comment]
Since we decided to go the AMD/requirejs route these might be usefull:

https://github.com/jrburke/r.js/wiki/Deployment-Techniques
http://requirejs.org/docs/optimization.html

**Comment by JohnMcLear** [comment]
Closing this because we're actually really performant in this area.  The goal in the future might be to minify additional(ie plugin) files but it would be part of a bigger rewrite.
