### ISSUE TITLE
How to grant/forbid (Read/Write/Noaccess) acess to particular pad for other Author?

### ISSUE THREAD

**Issue by pankajghadge** [ether/etherpad-lite#1784]
Suppose there are 2 Authors (Author1 and Author2)
Author1 has pads - pad1, pad2, pad3 and now i want to give following permission to Author2.

pad1 -> write.
pad2 -> read.
pad3 -> No access.

Currently Author1 create session using:
$mappedGroup = $this->pad->createGroupIfNotExistsFor($Author1);
$groupID = $mappedGroup->groupID;
$author = $this->pad->createAuthorIfNotExistsFor($Author1);
$authorID = $author->authorID;
$validUntil     = mktime(0, 0, 0, date("m"), date("d")+1, date("y"));
$session        = $this->pad->createSession($groupID, $authorID, $validUntil);

Currently Author2 create session using:
$mappedGroup = $this->pad->createGroupIfNotExistsFor($Author1);
$groupID = $mappedGroup->groupID;
$author = $this->pad->createAuthorIfNotExistsFor($Author2);
$authorID = $author->authorID;
$validUntil = mktime(0, 0, 0, date("m"), date("d")+1, date("y"));
$session = $this->pad->createSession($groupID, $authorID, $validUntil);

By using above author2 is able to edit author1 all pads because session is created. 
Author2 can copy URL and make changes into pad So is there any way that i can restrict Author2 to particular pad with read/write permission.

Thanks in advance.

**Comment by JohnMcLear** [comment]
Closing as this is explained more clearly in #1790
