### ISSUE TITLE
Specific control over authors' access level (for group pads)

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#1790]
You might want to restrict a user's access to only _view_ the pad contents instead of also being able to _write_ new content. Read-only links are not very useful in this context, because you cannot effectively revoke an author's privilege to write once she knows the real URL.

see #1784

**Comment by JohnMcLear** [comment]
Happy to see this get sponsored: https://www.bountysource.com/issues/1371783-specific-control-over-authors-access-level-for-group-pads

**Comment by JohnMcLear** [comment]
Afaik plugins such as MyPads handle this so this can be closed.
