### ISSUE TITLE
Add option to restore revisions

### ISSUE THREAD

**Issue by osamak** [ether/etherpad-lite#1791]
It would be a very important addition to the revision system to add the ability to restore previous revisions. It was mentioned in issue #229, but the ticket was closed.

[Explanatory note: if a restoration takes place it should happen as a document change and not as a reset back to rev x.]

**Comment by nemobis** [comment]
So, to followup, what revert features are available now to users and since what release? The commit seems to stay admin powers are required, which would be useless for etherpad.wikimedia.org.

**Comment by dcht00** [comment]
For anyone just looking to simply restore contents of a pad - see "ep_cristo_restore_revision" plugin. Install via /admin.

When installed, you get a button in Timeslider, or you can also restore with a link, for example:
http://sometherpad.org/restore/[pad_name]/[revision_no]

**Comment by lstandish** [comment]
I'm a new Etherpad user, and I see a great need to be able to set the current pad content to what was in some past revision.  As pointed out in this discussion, this is not "reversion," history is not lost.  Without this, I think the version history, including all the cool functionality of the "timeslider," is pretty much wasted.

I'm at the current version of etherpad-lite as-of this writing (develop branch), and I installed ep_cristo_restore_revision via /admin. I don't get any button in Timeslider, and restore with a link hangs. I hope one of the developers will look at this.  If I can provide any debug information, I'd be glad to.

**Comment by JohnMcLear** [comment]
@lstandish please post on plugin GitHub repository not here.

**Comment by dcht00** [comment]
You can since version 1.2.13, if you have the key, do it via an API:

`$ curl "https://example.org:9001/api/1.2.13/restoreRevision?apikey=SECRET&padID=yourpad&rev=1337"
`

See the API documentation for more info.
