### ISSUE TITLE
How to set default font size?

### ISSUE THREAD

**Issue by rasos** [ether/etherpad-lite#1812]
Our users say the default font size for a pad is too small.  When installing ep_sizes, they need to mark text to change the font size, which makes pages look bumpy, as the selected font size is not continued on the next line. 

I could not find a custom css entity to change the default font size. Any hint?

**Comment by ljoets** [comment]
Hi,
I would like to use andika font (http://www.dafont.com/fr/andika-basic.font) by default on pads. Where do I place ttf file, and what should the easiest way to proceed ?
Thanks ;-)

**Comment by ljoets** [comment]
Hello,

I installed Andika font on my server as specified here : http://linuxandfriends.com/how-to-install-fonts-in-linux-ubuntu-debian/
I added in my src/static/custom/pad.css

#innerdocbody {
  font-family: Andika;
  font-size: 14px;
  line-height: 16px;
}

restarted etherpad-lite

But it seems to have no effect on pads :-(

**Comment by psy0rz** [comment]
somehow this doenst seem to function anymore?
