### ISSUE TITLE
Add a new hook for aceBeforeDomLineRemoval

### ISSUE THREAD

**Issue by clkao** [ether/etherpad-lite#1814]
Currently we get acePostWriteDomLineHTML for any magicdom line edited.  however when deleting an empty line, there's no hook invoked.

We should provide aceBeforeDomLineRemoval that is called for all edits before the domline is removed, with a special argument in context noting this is a removal, not a replacement.

So in summary:
line editing = aceBeforeDomLineRemoval + acePostWriteDomLineHTML
line removal = aceBeforeDomLineRemoval

**Comment by vercha** [comment]
has this feature been completed now? I encountered the same issue as [#8](https://github.com/clkao/ep_author_neat/issues/8) 
is there any solution to this?

**Comment by lpagliari** [comment]
I believe it has not, @vercha. Would be a great feature to have on Etherpad, are you interested on implementing it and submitting a PR?

**Comment by vercha** [comment]
I'm afraid that I'm not too familiar with its source code to implement it. 
but I'd like to make an effort ,if there is anything I can do.
Thanks again!
