### ISSUE TITLE
Ansible script for setting up Etherpad Lite with nginx

### ISSUE THREAD

**Issue by dirkcuys** [ether/etherpad-lite#1823]
[Here's](https://github.com/p2pu/marvin/tree/master/etherpad-lite-install) a simple [Ansible](http://www.ansibleworks.com/) playbook that we use to setup Etherpad using Nginx to forward traffic and backed by MySQL.

**Comment by N07070** [comment]
The link seems to be broken. Sadly the project seems to have 404'd.

**Comment by JohnMcLear** [comment]
https://github.com/yatesr/playbook-etherpad ?

**Comment by dirkcuys** [comment]
@N07070 I assume you're referring to the link mentioned on the wiki page. I've updated it for posterity, but I wouldn't recommend that anyone run etherpad to ubuntu 12.04!
