### ISSUE TITLE
OPERA & IE: Deleting data in 'ordered list' doesn't delete order in Opera & IE

### ISSUE THREAD

**Issue by nbkdotdev** [ether/etherpad-lite#1825]
While deleting data formatted in ordered list using Backspace, only the data gets deleted while the 'orders' stay in the pad. This issue is noticed in IE8, IE9, IE10 and Opera 12.12 (Havn't tested in other versions of Opera). 

This works fine in Chrome & Firefox.

Steps to reproduce : 

In opera or IE, make a new ordered list
1. one
2. two
3. three

On deleting the above data, the 'orders' stays as it is.

1.
2.
3.

Only the data gets deleted.

**Comment by JohnMcLear** [comment]
This is fine in IE11 on current develop

**Comment by JohnMcLear** [comment]
Confirmed IE 10 on W8.1

**Comment by JohnMcLear** [comment]
This is due to the line counter not being applied on the parent div.  This is a nightmare to debug in IE but we will look into it.
