### ISSUE TITLE
IE “Ordered List” (Numbering) button on the formatting tool bar does not allow entering any text next to the numbers.

### ISSUE THREAD

**Issue by bp323** [ether/etherpad-lite#1836]
Browser: IE9 and IE10

Can the bug be reproduced: All the time

Description: Type a list of things using “Ordered List” in the formatting tool bar, but then it did not allow typing any text against the numbers.

Steps to reproduce: 
1. Click on “Ordered List” button that appears on the formatting tool bar
2. Start typing

Expected Result: The numbering and the text typed right next to it should appear.

Actual Result: The numbering appears but not the text next to it, instead it appears below the numbering.

The first screen shot depicts the actual result in Internet Explorer (IE9 and IE10 have this issue), and the second is the expected result in Chrome.

ACTUAL RESULT
![actual_internetexplorer](https://f.cloud.github.com/assets/4551054/587015/994343cc-c95b-11e2-9253-f5c27c83d176.png)

EXPECTED RESULT
![expected_crome](https://f.cloud.github.com/assets/4551054/587016/9c21c74e-c95b-11e2-8359-bd5aecd6c5a1.png)

**Comment by JohnMcLear** [comment]
This is fine in IE 11 on current develop

**Comment by JohnMcLear** [comment]
Confirmed IE 10 on W8.1
