### ISSUE TITLE
Modify the default size of the text

### ISSUE THREAD

**Issue by Sandroux** [ether/etherpad-lite#1847]
Hi Everybody,

Please can someone help me with Etherpad-lite? I would like to know where I can find the part of the code which treats about the size of the text? I mean, where I can modify the default size of the text.

Thanks!!!

**Comment by JohnMcLear** [comment]
@Sandroux if you want to see this please bump https://www.bountysource.com/issues/1371767-modify-the-default-size-of-the-text
