### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by angezanetti** [ether/etherpad-lite#1853]
I just spend a lot of time using Etherpad for translations and working on several documents. I missed so much the autocompletion features of my text editor. 

Is is possible to implement a feature that parse the text and show a menu when the user hit a key; That menu should contain the word in the page starting with the same begin than the word i'm typing.

**Comment by JohnMcLear** [comment]
Here is an autocomplete plugin for Etherpad: https://github.com/jdittrich/ep_autocomp
