### ISSUE TITLE
Allow text annotations

### ISSUE THREAD

**Issue by zessx** [ether/etherpad-lite#1865]
[Feature request]

Etherpad is used by a french association (Framasoft) for collaborative translation.
We often need to discuss about several parts of the text at a time, but the only way to highlight a "TODO" point is to make it bold/underlined.

It should be useful to allow users to create annotations on a specified portion, and have those annotations easily and quickly retrievable.

**Comment by jibe-b** [comment]
> I released this plugin up as open source

@JohnMcLear I couldn't find it, may I ask if you can help?

**Comment by lpagliari** [comment]
https://github.com/ether/ep_comments
