### ISSUE TITLE
Add flooding protection

### ISSUE THREAD

**Issue by nextl00p** [ether/etherpad-lite#1866]
Implement some kind of flood protection

**Comment by JohnMcLear** [comment]
Help us help you https://www.bountysource.com/issues/1371760-add-flooding-protection

**Comment by JohnMcLear** [comment]
I built some in but nothing that stops X commits per Y seconds..   I can probably do that.

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/pull/4036

**Comment by JohnMcLear** [comment]
4036 merged in, should handle it :)
