### ISSUE TITLE
PDF generation with AbiWord crashes Etherpad-Lite on urls with "&" [problem and solution found]

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#189]
I noticed that AbiWord and the whole etherpad crashes, when I try to export-as-PDF a certain pad.
It has some font decorations like bold, italics and strikethrough. When I delete the formatting of a word, it does not crash.
Other exports do work.

The file /tmp/eplite_export_512688611492.html does exist, and owner is my etherpad user.

AbiWord version 2.8.6
convert (ImageMagick) version 6.6.5-8 2011-09-07

Console output:

611492.pdf pdf
[ERROR] console: convert /tmp/eplite_export_512688611492.html /tmp/eplite_export_512688
AbiWord: could not open the file [/tmp/eplite_export_512688611492.html]
error -1
...
graceful shutdown
db successfully closed

[UPDATE]

The crash is reproducible on a fully independent server with different software versions.
AbiWord 2.8.2
convert 6.6.1-0 2011-09-06

**Comment by c456fa2** [comment]
An other few years later the error occures again.
etherpad crashes when the pad contains UTF-32 Characters like 🍆😂
