### ISSUE TITLE
Right-to-left (RTL) is not a great default for Hebrew

### ISSUE THREAD

**Issue by amire80** [ether/etherpad-lite#1916]
Hello,

I am using Etherpad 1.2.11 at https://etherpad.wikimedia.org . The Accept-Language in my Firefox is Hebrew. Because of this I get Etherpad with the Hebrew interface by default, which is great,* but I also get the whole pad with the RTL direction, which is not great. I can change it in my preferences, but I have to do it every time I enter the pad, so it's quite uncomfortable.

The direction of the content is not supposed to be set according to the user interface language. Because every editor of the same pad can have a different UI language, but the content's language should be common to all the editors.

It makes the most sense to me to set the direction manually per paragraph using a toolbar button; in common word processors such buttons look more or less like this: [◀¶] for RTL and [¶▶] for LTR. If the pad is created by a user whose UI language is RTL (Hebrew, Arabic etc.), then the initial default can be RTL and otherwise it should be LTR.

It is also possible to do some kind of automatic direction detection, for example by counting the number of strong-rtl characters in every paragraph, but that looks like overkill to me at this point.

Thank you!

--
* I happen to be the translator :)

**Comment by JohnMcLear** [comment]
This should be in now, let me know if not :)
