### ISSUE TITLE
Enforce unicode as db charset

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#1936]
Although it's explicitly stated that you have to set your db's charset to utf8, etherpad doesn't check for utf8, which causes some twisted bugs (see #1914).

We need to stop the process if the db charset is not set appropriately.

**Comment by JohnMcLear** [comment]
Upstream: https://github.com/Pita/ueberDB/issues/70

**Comment by webzwo0i** [comment]
I know this is not good style (the alternative is to provide a method for writing/reading without caching in ueberDB or provide a method to change the cache size on-the-fly) but for me the following works. I have a problem removing the db-items though. It increases the startup time by writeInterval+5 milliseconds.
```
diff --git a/src/node/db/DB.js b/src/node/db/DB.js
index 7273c83..a0b6515 100644
--- a/src/node/db/DB.js
+++ b/src/node/db/DB.js
@@ -50,6 +50,21 @@ exports.init = function(callback)
     //everything ok
     else
     {
+      db.set("utf8support4","\uD834\uDF02");
+      for (var i=0;i<db.db.settings.cache+1;i++){
+        db.set("UTF8TEST"+i,"0");
+      }
+      setTimeout(function(){
+        db.get("utf8support4",function(err,res){
+          if(res !== "\uD834\uDF02"){
+            console.error("The database does not support Unicode above U+FFFF");
+            process.exit(1);
+          }
+        })
+      },db.db.settings.writeInterval+10)
+      //for (var i=0;i<db.db.settings.cache+1;i++){
+      //  db.db.remove("UTF8TEST"+i,"0");
+      //}
```
error handling is missing. What it does is 1. filling up the cache and 2. waiting for ueberDB to flush it. I see no reason why ueberDB should not flush (iirc it will block if the cache is full and not written to db).
Combined with the "set names utf8mb4 collate utf8mb4_bin" (https://github.com/ether/etherpad-lite/issues/2516#issuecomment-80506007) this could be a work around

**Comment by JohnMcLear** [comment]
Done in Ueber 0.4.6 afaik
