### ISSUE TITLE
Etherpad of pasted document gives — sometimes — weird exception on load (js encoding issues ?)

### ISSUE THREAD

**Issue by ldidry** [ether/etherpad-lite#1945]
Seems like the #885 issue.

At load, we got:

```
Error: mismatch error setting raw text in setDocAText
```

The "Loading" message appears, the pad content is shown but the "Loading" doesn't hide. And no modification is registered.

The common point between the pads is weird encoding in some words with accents (but only one accent is doomed, all the others are OK).

Here's pads with the problem (same text, weird encoding at different words):
http://lite3.framapad.org/p/philo-dm1 (l.28)
http://lite3.framapad.org/p/noni-philo-dm1 (l.125)

After fixing the accents in gvim, I was able to paste the text in an other pad. Twice.

**Comment by jaraco** [comment]
I think we've encountered this issue with 1.5.7 and 1.6.0. The content was pasted into the Etherpad from the clipboard. I'm not sure what content was there. I'll continue to investigate.

**Comment by jaraco** [comment]
I've tried debugging in Firefox, but I run into #2723.

The document that's triggering these errors appears to be trivially simple in the database:

```
$ mongo ourdb/etherpad
MongoDB shell version: 3.2.9
mongos> db.store.find({key: {$regex: "pad:Converting_Angular_Factories"}})
{ "_id" : ObjectId("57c8f23e593990e071a3ef2e"), "key" : "pad:Converting_Angular_Factories_to_Providers", "val" : "{\"atext\":{\"text\":\"\",\"attribs\":\"\"},\"pool\":{\"numToAttrib\":{\"0\":[\"author\",\"a.Q9ogrSFZs7OYAKlU\"]},\"nextNum\":1},\"head\":1,\"chatHead\":-1,\"publicStatus\":false,\"passwordHash\":null,\"savedRevisions\":[]}" }
{ "_id" : ObjectId("57c8f23e593990e071a3ef30"), "key" : "pad:Converting_Angular_Factories_to_Providers:revs:0", "val" : "{\"changeset\":\"Z:1>6b|5+6b$Welcome to Etherpad!\\n\\nThis pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents!\\n\\nGet involved with Etherpad at http://etherpad.org\\n\",\"meta\":{\"author\":\"\",\"timestamp\":1472787006471,\"atext\":{\"text\":\"Welcome to Etherpad!\\n\\nThis pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents!\\n\\nGet involved with Etherpad at http://etherpad.org\\n\\n\",\"attribs\":\"|6+6c\"}}}" }
{ "_id" : ObjectId("57c8f248593990e071a3ef35"), "key" : "pad:Converting_Angular_Factories_to_Providers:revs:1", "val" : "{\"changeset\":\"Z:6c<6c|6-6c$\",\"meta\":{\"author\":\"a.Q9ogrSFZs7OYAKlU\",\"timestamp\":1472787016277}}" }
```

Opening another document by the same author has no issues.

**Comment by pabelenda** [comment]
It is happening to me as well.

Anyway, it is not something I can easily replicate. How can I turn on some more debug on my side?

`
Uncaught Error: mismatch error setting raw text in setDocATextsetDocAText @ VM218:778
setDocumentAttributedText @ VM218:199
(anonymous function) @ VM218:10325
(anonymous function) @ VM218:195
inCallStack @ VM218:472
inCallStackIfNecessary @ VM218:541
withCallbacks @ VM218:192
setBaseAttributedText @ VM218:10311
Ace2Inner.editorInfo.ace_setBaseAttributedText @ VM218:998
(anonymous function) @ pad.js?callback=require.define:2881
action @ pad.js?callback=require.define:2841
(anonymous function) @ pad.js?callback=require.define:2861
_.each._.forEach @ ace2_common.js?callback=require.define:11298
doActionsPendingInit @ pad.js?callback=require.define:2860
info.onEditorReady @ pad.js?callback=require.define:2985
readyFunc @ test-pad-8nvw2m?&auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbiI6In…:17
(anonymous function) @ VM218:5537
`

**Comment by lpagliari** [comment]
@pabelenda If you have access to server files, you can change setting.json to `"loglevel": "DEBUG"`; otherwise, you'll need to add some breakpoints using browser inspector
