### ISSUE TITLE
Hardcoded path /p breaks pad exports

### ISSUE THREAD

**Issue by arieljlira** [ether/etherpad-lite#1947]
Hi, I have an etherpad-lite instance behind a reverse proxy with an alternative path to my pads,  "/pads" instead of "/p". 
All work fine, except the export functionality. Export routes are "/null/export/$format" and the worst is that it works! because it always returns the pad named "null" ...

How to reproduce it? reverse proxy an instance with a route other than /p/ . Like 

```        
        RewriteRule ^/pads/(.*)$ http://localhost:9001/p/$1 [P]
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^/(.*)$ http://localhost:9001/$1 [P]
```        

I think the problem is in https://github.com/ether/etherpad-lite/blob/develop/src/static/js/pad_impexp.js#L210
Replacing RegExp
```
var pad_root_path = new RegExp(/.*\/p\/[^\/]+/).exec(document.location.pathname);
```
with
```
var pad_root_path = new RegExp(/.*\/[^\/\?]+/).exec(document.location.pathname);
```
seems to fix the problem. I've tested in and with this patch, export routes works as expected with /p, /pads, /some/other/route and /some/other/route?with=params

I saw a similar report in https://bugs.launchpad.net/openstack-ci/+bug/1168455

Thanks!

**Comment by JohnMcLear** [comment]
See https://github.com/MozillaFoundation/mofo-lightsaber/issues/12#issuecomment-72710349

Looks like adding something like ``        rewrite ^/(.*)/export/(.*) /p/$1/export/$2 break;`` will fix this.  Please test and let me know @Yaco 

Also please fix your own reverse proxy configs, it's really not up to the foundation to maintain third party software for you!

**Comment by JohnMcLear** [comment]
I put a fix in for export URLS, please pull latest develop and test.
