### ISSUE TITLE
Suggestion: refactoring the software to facilitate "shared" Etherpad installation to serve differently configured Etherpads instances

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#195]
How can I setup several Etherpad installations which share the code, and perhaps also the database ?

I'd like to set up different Etherpad installations, accessible through Apache2
- sharing a single Etherpad software core installation (shared)
- for different user groups
- with different favicons
- with different default pad texts
- optionally using distinct databases, or a single database but with distinct database prefixes

The current core file is settings.json, but this does not allow to configure everything.
Missing is the possibilty to define different favicons or to use a single database but with database prefixes (like MediaWiki optionally allows).

This bug is filed for tracking. I commit myself to work on a solution.

**Comment by raj15feb** [comment]
Hi All,
I'm using etherpad for Odoo (ubuntu 14.04). I have multiple(4) database on server. Its all are runned from db filter. How to use etherpad for all these database?
  Thanks......
