### ISSUE TITLE
Auth fail

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#1958]
The current authentication system is not very flexible and pretty furry. There are groups and sessions and group pads and when you don't want someone to edit a pad you gotta make sure they get the readOnly link and that kind of stuff.

I'd strip out readOnly pads entirely, this should be pretty easy to realize with a plugin (and if not, we should make sure it is). Furthermore, no more groups, there should simply be pads.

I think, for every edit/pad access a hook should be activated that allows plugins to dictate, which users should be able to do what. (Lot's of settings would become obsolete with this, i.e. requireSession and editOnly.) Also, plugins should not only be responsible for authorizing but also for authenticating. No more session cookies that need to be sent through socket.io and that kind of stuff -- if a message (edit or pad access) arrives plugins on the server check whether the user is authenticated, if not, plugins on the client are notified and may take actions to request authentication from the user (we could send some plugin-defined auth token on every message to the server, but we shouldn't define what that is).

**Comment by JohnMcLear** [comment]
Closing as we have other conversation / threads RE Auth.
