### ISSUE TITLE
Server-side API/Connection fail

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#1959]
There's no clean modular structure in the code. At the moment, changeset processing and socket.io management is pretty much tied together. Plugin devs are faced with lots of obstacles trying to add an API endpoint, sending their own messages to clients, setting or changing the contents of a pad.

I think we should make our code transport agnostic to allow plugins to add new ways of communicating with the server. This would greatly simplify the creation of non-browser client libraries. Changeset processing and connection management, the transport layer, construction of the HTTP API, Import/Export should be independent modules with a defined API and hooks.

**Comment by JohnMcLear** [comment]
This is a lot better now, still not perfect but code never is.  So closing.
