### ISSUE TITLE
Have multiple API key access and use RESTful API - Perhaps OAuth ?

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#1960]
Along with our db model, I want to critisize the way our API works.

One API key with access to everything is not very useful. Also, I'd favor a REST API over the current solution.

Instead we should employ OAuth and add anything as an endpoint, that admin would want to be able to do: An admin back end should use those endpoints at all times.

**Comment by JohnMcLear** [comment]
We can help move this forward: https://www.bountysource.com/issues/1371740-api-fail

**Comment by JohnMcLear** [comment]
This is a duplicate of another issue
