### ISSUE TITLE
Client-side/Interface refactor

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#1961]
I think our client-side code is confusing. We have UI code tangled into other stuff and the API is a jungle.

I think we should separate the client-side code into three independent parts:
- connection management
- settings (global defaults, per-pad and per user)
- changeset / and state management
- the editor
- the UI / the interface
  ( - a timeslider, which should be on the same page and could be built as a plugin)

I think you should be able to easily install your own client-side theme, completely switch out the editor (I'm not sure as to whether that's possible/practical with plugins that my depend on a specific editor) and easily switch out the transport layer.

Things like the chat should become plugins, IMHO.

**Comment by JohnMcLear** [comment]
cc @redhog

**Comment by JohnMcLear** [comment]
2020, still confusing as fuck.

**Comment by JohnMcLear** [comment]
Things are a lot better but this issue isn't helping any more so will close.
