### ISSUE TITLE
Proposing document namespaces

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#1962]
I think we should namespace documents and put the pads available via the interface into a default namespace that could be called 'pad'.

That way plugins can use etherpad for their own needs without polluting the global namespace. Also, admins could set up multiple web interfaces (e.g. `/paste/myPad` and another namespace `/consulting/mypad`) with different auth mechanisms, or one namespace could be used only for access by a non-browser client that does some other magic using etherpad technology.

**Comment by JohnMcLear** [comment]
This could lead to more paint than we would gain IMHO.  An admin could also do this with clever reverse proxying if they wanted.  I feel like it's outside of the scope of this project.
