### ISSUE TITLE
Reduce space usage in DB

### ISSUE THREAD

**Issue by bettmensch** [ether/etherpad-lite#2006]
Add a possibility to reduce space usage.

Option 1 (IRC s1341):
Add an API call to compress a Pad. compressPad(padID, interval)

Option 2:
Buffer Changesets and merge them bevore saving, depending on a timespan or changeset count or something like that

**Comment by JohnMcLear** [comment]
Help us help you: https://www.bountysource.com/issues/1371722-reduce-space-usage-in-db

**Comment by JohnMcLear** [comment]
We have huge deployments that are actively used and never hit the problem of storage.  So this feels like a pointless optimization and will cause more problems than it will benefit admins.
