### ISSUE TITLE
use IP/DNS instead of 'unknown' for new participants

### ISSUE THREAD

**Issue by rstory** [ether/etherpad-lite#2009]
It would be nice if new participants were named by the DNS domain for their IP (or the IP if reverse dns lookup failed). When I use etherpad for meetings, some folks don't bother to set up their names, but i'd be able to recognize who they were based on their domain name.

**Comment by JohnMcLear** [comment]
Help us help you: https://www.bountysource.com/issues/1371721-use-ip-dns-instead-of-unknown-for-new-participants

**Comment by JohnMcLear** [comment]
Rejected as a feature, leaving as a plugin request.
