### ISSUE TITLE
Ctrl-A and "clear colours" should pop up a prompt too

### ISSUE THREAD

**Issue by MarkTraceur** [ether/etherpad-lite#2056]
If you really want to pop up a prompt about that, then it should happen when the entire document is selected _as well as_ when nothing is selected.

Honestly I don't see the value of having the prompt at all - undo still works.

**Comment by sunilkumarc** [comment]
Hi @JohnMcLear ,

I would like to work on this request feature. But I need some help in understanding the code before making changes. Where can I get started ?

Thanks,
Sunil

**Comment by JohnMcLear** [comment]
Take a look at the source code that handles the clear authorship prompt...  ``grep -rni authorship . `` is your friend

**Comment by sunilkumarc** [comment]
Hi @JohnMcLear 

After some research I found out that this -->https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L845 is where I need to make changes to fix this issue. Unfortunately the changes I'm doing are not being reflected when i reload the app in my browser. Am I missing something here ?

PS: My bin/run.sh is running when I make the changes and reload the app.

Also can you confirm once that the above mentioned file is the one I need to make changes in or not ?

**Comment by JohnMcLear** [comment]
Please read the getting started developing documentation.

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/wiki/Example-Development-Settings.JSON should help.

**Comment by sunilkumarc** [comment]
Thanks :smile:

**Comment by JohnMcLear** [comment]
Well that was easy: https://github.com/ether/etherpad-lite/pull/3983/files
