### ISSUE TITLE
/admin/plugins - add date of last modification

### ISSUE THREAD

**Issue by mmccarn** [ether/etherpad-lite#2073]
It would be useful if the Plugin Manager page included a column showing the date of the last modification for each plugin, so that users could easily review uninstalled plugins according to if/whether they have been recently updated.

**Comment by JohnMcLear** [comment]
Help us help you! https://www.bountysource.com/issues/2228144-admin-plugins-add-date-of-last-modification

**Comment by JohnMcLear** [comment]
Done
