### ISSUE TITLE
Documents not editable in Android 4.1 browser on small screen

### ISSUE THREAD

**Issue by sathomas** [ether/etherpad-lite#2077]
Trying to use [*beta.etherpad.org*](http://beta.etherpad.org) from a [Huawei Prism II](http://www.huaweideviceusa.com/products/features?id=88) (320x480 screen resolution, Android 4.1) there are many problems:

* Tapping on the document area (to edit a document) brings up the keyboard which obscures the content area. It is not possible to scroll the content area into view as the page does not respond to scroll swipes.

![screenshot_2014-01-31-07-37-26](https://f.cloud.github.com/assets/1731910/2050463/4643f924-8a75-11e3-99bd-24b3124dd912.png)

* As also seen above, the right side of the toolbar shows up _below_ the document instead of above it. Also, tapping these buttons has no effect.

* The auto-correct / spell check continually flashes on/off. To successfully type characters users must "synchronize" their typing with the auto-correct / spell check. That's a challenge worthy of the best video gamers.

**Comment by JohnMcLear** [comment]
Core UI is dealt with here, its now up to plugins to resolve their issues.  Feel free to create bounties on plugins that cause pain!
