### ISSUE TITLE
Copy&Paste looses line breaks when working with chrome

### ISSUE THREAD

**Issue by linuxundich** [ether/etherpad-lite#2078]
When I copy&paste text into a Etherpad, it losses its line breaks when I open my Etherpad withing chrome. When i use Firefox instead, copy&paste works just fine. I use chrome 32.0.1700.102 and a version of etherpad checked out from git yesterday.

![etherpad-chrome](https://f.cloud.github.com/assets/1716643/2050645/68885760-8a79-11e3-8210-1846bd691729.png)

**Comment by LaKing** [comment]
Sorry for coming late, .. as far as I see this is still an issue with chrome. Any progress on this?

**Comment by JohnMcLear** [comment]
Pretty sure this isn't an issue any more @LaKing

**Comment by LaKing** [comment]
I see the issue exists in the latest, the 1.5.6 release, but does not exists on the current git clone.

**Comment by JohnMcLear** [comment]
Bump @pita and @Gared to do a release :)

**Comment by Gared** [comment]
@JohnMcLear Will do a release tomorrow or the day after tomorrow. Is this okay for you?

**Comment by micah** [comment]
@Gared seems like @JohnMcLear was ready for the release to go and was just notifying you to go ahead

**Comment by Gared** [comment]
@micah I know, but I found this issue #2720 on the current develop branch. Can you please confirm my issue? I'll try to fix this asap and do a release tomorrow

**Comment by Gared** [comment]
@micah New release 1.5.7 is done

**Comment by spiffomatic64** [comment]
Just confirmed this is still occurring in 1.5.7, as well as on current git clone 
Using chrome Version 44.0.2403.155 m

**Comment by dvorak** [comment]
I'm also seeing the issue on Safari on 1.5.7

**Comment by blinry** [comment]
Just wanted to mention @JohnMcLear's workaround again. Maybe it helps someone else:
Surround your text with HTML tags before copying it, for example "<pre>" and "</pre>".

**Comment by svillar** [comment]
BTW this bug also affects WebKit (Safari, epiphany...) and the <pre> workaround does not work for me at all.

**Comment by psaavedra** [comment]
Looks like the problem in Safari and epiphany is inducted by the workaround introudced in #1766. I just reverted this one and the copy&paste works well now in Epiphany:

``` diff
--- ./etherpad-lite/node_modules/ep_etherpad-lite/static/css/iframe_editor.css.orig	2017-02-02 10:21:45.201005469 +0100
+++ ./etherpad-lite/node_modules/ep_etherpad-lite/static/css/iframe_editor.css	2017-02-02 10:23:02.612889597 +0100
@@ -120,8 +120,6 @@
```

**Comment by telephon** [comment]
I see this behavior on Iron (Version 78.0.4050.0), which is Chromium.

**Comment by JohnMcLear** [comment]
@telephon this isn't all that useful I'm afraid.  Please read: https://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/ then add a new comment providing information about where to replicate, steps to replicate etc. etc.

**Comment by telephon** [comment]
Thank you, John, for the information, I didn't think this was all too important since this has been discussed enough above. I just thought the information is useful anyway – sorry if it isn't.

**Comment by telephon** [comment]
But here are the steps for reproducing the error on macOS 10.15.5:

1. The Iron Browser is to be found here https://www.srware.net/iron/
2. open a TextEdit window, switch to plain text and copy the text given below into it
3. open a new etherpad and paste it.

The Text:
```
This is a new line:
and this is another one
any yet another one
```


The result I get is:
```
This is a new line: and this is another one any yet another one
```

**Comment by JohnMcLear** [comment]
Did you test against develop or older?

**Comment by telephon** [comment]
sorry, trying to find out …

**Comment by telephon** [comment]
here it is:

82d1179f24ae8463d94622eed06f53a55ce11d09

**Comment by JohnMcLear** [comment]
And against develop?

**Comment by telephon** [comment]
I suppose not against develop, it was a standard install in a docker.
