### ISSUE TITLE
Documentation/Hooks – learnability

### ISSUE THREAD

**Issue by jdittrich** [ether/etherpad-lite#2085]
The documentation for the [client side hooks](http://etherpad.org/doc/v1.3.0/#index_client_side_hooks) assumes knowledge about etherpad lite which does not seem to be learnable via the documentation itself. So it is not easy to get started (at least in an informed way) with plug-in-development. 
i.e.: 
- [aceCreateDomLine](http://etherpad.org/doc/v1.3.0/#index_acecreatedomline) refers to "processing of DOM lines" and the "formatting engine", but it is not defined what these terms mean in that context. 
- [aceAttribsToClasses](http://etherpad.org/doc/v1.3.0/#index_aceattribstoclasses) refers to the "attribute processing procedure" which I can't find out about either. 

The included examples per hook (a very nice idea actually) only make sense in many cases if you know about the inner workings too. 

In my case, I tried a web search which was not very successful; I studies other's plugins which was helpful but in such way one is still not knowing what one is actually doing.

**Possible Solutions:**
Adding a section explaining the (client side) processes in Etherpad, like the DOM-Line and attribute-processing.

_Meta: Sorry for filing a bit of a bulky bug here. I can split it up in the problems I encountered, but I assumed that this is even less preferable._

**Comment by JohnMcLear** [comment]
Closing because a lot more docs / tutorials / examples exist now
