### ISSUE TITLE
Issues with authorship attribs after cut&paste or cut&undo

### ISSUE THREAD

**Issue by dmitryuv** [ether/etherpad-lite#2104]
Open 2 browsers with the same pad. Type in one window, then type in another. In one of the windows select all text then cut, then paste back (or hit Undo)
Expected:
- both windows should have same result with text coloured by author who did the paste

Actual:
- my window have "before cut&paste" author colours preserved till refresh
  ![image](https://f.cloud.github.com/assets/2512131/2343572/bf2b7488-a510-11e3-82a7-f12a09530fb3.png)

Note:
- sometimes after paste I have same state in both windows - original authors preserved. Sometimes as on the screenshot. Always wrong after Undo.

**Comment by JohnMcLear** [comment]
@dmitryuv any chance you can take a look at solving this one please? :)

**Comment by dmitryuv** [comment]
huh, me create, me fix :) okay

**Comment by JohnMcLear** [comment]
This got resolved a while back.  Author is persistant now
