### ISSUE TITLE
getHTML returns ordered lists without start attributte

### ISSUE THREAD

**Issue by diskman** [ether/etherpad-lite#2112]
Ordered lists in orginal have start attribute set.

Orginal source is

<div id="magicdomid2" class="list-start-number1">
      <ol class="list-number1" start="1">
        <li>
          <span class="author-a-dz72ztwmnz74zz69zp5z80zz87zu27f">Jeden</span>
        </li>
      </ol>
    </div>

```
<div id="magicdomid3" class="list-start-number2">
  <ol class="list-number2" start="1">
    <li>
      <span class="author-a-dz72ztwmnz74zz69zp5z80zz87zu27f">dwa</span>
    </li>
  </ol>
</div>
<div id="magicdomid4" class="">
  <ol class="list-number2" start="2">
    <li>
      <span class="author-a-dz72ztwmnz74zz69zp5z80zz87zu27f">trzy</span>
    </li>
  </ol>
</div>
```

api getHTML returns

<div id="magicdomid2" class="">
      <ol class="list-number1">
        <li>
          <span class="">Jeden</span>
        </li>
      </ol>
    </div>

```
<div id="magicdomid3" class="">
  <ol class="list-number2">
    <li>
      <span class="">dwa</span>
    </li>
  </ol>
</div>
<div id="magicdomid4" class="">
  <ol class="list-number2">
    <li>
      <span class="">trzy</span>
    </li>
  </ol>
</div>
```

**Comment by JohnMcLear** [comment]
@webzwo0i did you get these tests in?  Can we confirm this is fixed?

**Comment by JohnMcLear** [comment]
Closing as this is part of a bigger problem with OL
