### ISSUE TITLE
underscore: outdated or changed behaviour of throttle/debounce

### ISSUE THREAD

**Issue by jdittrich** [ether/etherpad-lite#2113]
Using underscore in a plugin I noticed that the used (as in Etherpad 1.3) `underscore.throttle()` behaves differently that the current underscore version  (e.g. 1.6). In a current underscore version, the returned value is cached and returned on each call; the one that can be required in etherpad the value is not cached and thus it is `undefined` if called.  

*Can the underscore version be updated or is there a specific reason for the behaviour?*

**reproduce the behaviour**
In my plugin, Underscore was used via `var _ = require('ep_etherpad-lite/static/js/underscore');` 

The behaviour was contrasted by using the plugins underscore with the one one on the [underscore-website](http://underscorejs.org/#) (–for the sake of simplicity, as one can quickly try via the dev-tool console).
The following function was used for the test: 
 
   var myfunc = _.throttle(function(value){ return value;}, 1000)

which is called via `myfunc("somevalue")`; 
returning `"somevalue"` in the current underscore version, and `undefined` when used in the etherpad-plugin.

**Comment by JohnMcLear** [comment]
I can only see us using this here: 
```
./js/broadcast_slider.js:169:    var fixPadHeight = _.throttle(function(){
```

**Comment by JohnMcLear** [comment]
Okay maybe that's not the case, updating causes an error delivering a pad..

**Comment by jdittrich** [comment]
I don’t remember exactly but:  I probably found the same line (broadcast_slider.js:169) and I remember that it seemed rather non-breaking and small. I looked at the underscore code as well and it was neither complicated nor did it have any significant changes between the versions concerned here. hmm.

**Comment by JohnMcLear** [comment]
Done :)
