### ISSUE TITLE
Grouppad export fails if requireSession:true

### ISSUE THREAD

**Issue by louvois** [ether/etherpad-lite#2119]
Hello,
I am using Etherpad git version is ca8dce1
I have created successfully many pads using Etherpad API Methods
I can edit and work fine with these pads with or without password.
But unfortunately i can't export it with any format, and i have this message error "403 - Can't touch this".
Can you help me ?

PS: I use  TomNomNom /etherpad-lite-client

Thanks

**Comment by alekiy** [comment]
Hey, I'm facing the exact same problem. I use release 1.5.6 and nearly the same Proxy configuration.
@louvois do u have any advice for me how to fix it?
I also tried to use ur modified setcookie and SetEnv config for apache, but no success.
