### ISSUE TITLE
Etherpad version from GIT HEAD

### ISSUE THREAD

**Issue by normalser** [ether/etherpad-lite#2129]
Very minor thing when etherpad-lite is used as submodule.

`src/hooks/express.js` tries to:

``` js
    var ref = fs.readFileSync(rootPath + "/.git/HEAD", "utf-8");
    var refPath = rootPath + "/.git/" + ref.substring(5, ref.indexOf("\n"));
    version = fs.readFileSync(refPath, "utf-8");
```

Unfortunately when etherpad-lite is used as submodule then `.git` is file and not directory and has content: `gitdir: ../.git/modules/etherpad-lite`

**Comment by JohnMcLear** [comment]
Not sure why this is stlil open, it's been resolved for years.
