### ISSUE TITLE
Animated GIF for real-life showcase

### ISSUE THREAD

**Issue by PanderMusubi** [ether/etherpad-lite#2140]
Please create a new animated GIF of a real-life show case in which multiple authors are writing at the same time. Use it on http://etherpad.org/ (where now is only a static image but with many authors) and https://raw.githubusercontent.com/ether/etherpad-lite/develop/README.md (where the animation is unfortunately at times too jumpy and other times a bit boring).

**Comment by JohnMcLear** [comment]
Help fund this here: https://www.bountysource.com/issues/1793552-animated-gif-for-real-life-showcase
