### ISSUE TITLE
Always show the user list

### ISSUE THREAD

**Issue by christianpbrink** [ether/etherpad-lite#2141]
I just upgraded from an old version of EL (1.0.1) to the current HEAD, and I found that the chat bar no longer displays the list of pad users by default.  It seems a user has to click the little silhouette icon to see the list of users, and while the user list is visible it overlays (i.e. obscures) whatever chat content is near the top of the chat bar.

Is there a way to have the user list display permanently without obscuring the top of the chat bar, the way it worked in 1.0.1?  Even some hacky CSS would be fine.

**Comment by JohnMcLear** [comment]
@christianpbrink check out this pull request: https://github.com/ether/etherpad-lite/pull/2467

Please test.

**Comment by christianpbrink** [comment]
I'll try to get around to it at some point -- we are working on something
else at the moment.  Thanks for the heads-up.

**Comment by JohnMcLear** [comment]
This is obviously already in..  Closing...
