### ISSUE TITLE
Make hook "getLineHTMLForExport" asynchronous

### ISSUE THREAD

**Issue by Gared** [ether/etherpad-lite#2152]
Does anyone know why the server-side hook "getLineHTMLForExport" is synchronous?
Is there any reason why we don't call the hook in an asynchronous way?

**Comment by JohnMcLear** [comment]
Good question, don't know why but it should probably be async..

**Comment by Gared** [comment]
#2487

**Comment by JohnMcLear** [comment]
Oho, forgot about this :)  Awesome, this can be closed once merged.
