### ISSUE TITLE
Unicode astral characters replaced with ??

### ISSUE THREAD

**Issue by stuartf** [ether/etherpad-lite#2154]
This looks similar to #842 but for characters beyond the BMP such as the double struck mathematical alphanumerics like 𝕄 or emojis like 🍕

**Comment by rasos** [comment]
Question marks again appeared when user opened pad with Silk Browser on Kindle Fire.
Well we are still on 1.5.6, however #2348 should have been merged in before - no notes in CHANGELOG though.
