### ISSUE TITLE
suggesting a markup ("track changes") toggle button for "markup" deletions with "strikethrough" and insertions with "underline", and "remove all tracked changes" button

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#217]
I suggest to have a new option "markup" (track changes) and a further button, "remove all markups"

If markup equals true then
- Insertions should be marked by underlines, when markup==true.
  (As a remark only: insertions are already marked by an author's background colour. The colours can be removed.)
- deletions should be marked by "striketrough" attribute instead of actually deleting such characters or lines.

**Comment by 23jay** [comment]
@JohnMcLear can you guide me what direction you provided to @Wikinaut so I can achieve it.
