### ISSUE TITLE
Timeline Cache Feature

### ISSUE THREAD

**Issue by EndruK** [ether/etherpad-lite#2199]
Is it possible to cache the timeline automatically?

In case that there are many changes in a document the loading time of the timeline becomes longer and longer.
But normally users don't click on the timeline directly after loading a document.
So it would be a nice feature if the timeline data will be loaded in background that the user don't have to wait until the data is loaded.

Greetings, André

**Comment by JohnMcLear** [comment]
Sounds like a useful featur, perhaps create a bounty for it : https://www.bountysource.com/issues/3136288-timeline-cache-feature

**Comment by JohnMcLear** [comment]
I really like the idea of having the timeline as "part" of the pad page.  I think it works really well.  Still a useful feature/request IMHO.
