### ISSUE TITLE
sessionID does not exist - Clean up orphaned sessions

### ISSUE THREAD

**Issue by mullrich** [ether/etherpad-lite#2201]
We're having difficulties accessing some of our pads:

`RESPONSE, listSessionsOfGroup, {"code":1,"message":"sessionID does not exist","data":null}`

The problem seems to have occured after a "git pull", but I'm not sure. We did not touch the configuration files. Some of the pads affected are newer, others older - I haven't figured any pattern here.

What can we do to fix this? We're running EPL embedded in our Learning Management System through a plugin. We're on Linux using the latest version of node.

Thanks a lot,
mullrich

**Comment by JohnMcLear** [comment]
Help us help you: https://www.bountysource.com/issues/3168898-sessionid-does-not-exist-clean-up-orphaned-sessions

**Comment by JohnMcLear** [comment]
Script is in ready for tesitng https://github.com/ether/etherpad-lite/pull/3973
