### ISSUE TITLE
Optical feedback for timeslider

### ISSUE THREAD

**Issue by Gared** [ether/etherpad-lite#2207]
What do you think about adding some type of optical feedback when browsing pad versions? On large pads (several thousand of versions) changing to another version might take some seconds, but the user don't know that the browser is currently calculating the pad text and might try to change to another pad version (in some cases changing pad versions doesn't work anymore and you need to reload). This leads to the problem that the user thinks that the timeslider is broken.
I think it would be a good idea to add a popup/overlay as long as the pad version is being calculated.

**Comment by JohnMcLear** [comment]
Yea this sounds good, I'd integrate it into https://github.com/ether/etherpad-lite/pull/2070 which should solve a lot of load issues cc @marcelklehr

**Comment by JohnMcLear** [comment]
Interesting challenge @seballot :D

**Comment by seballot** [comment]
We just need to display a small spinner loader, should be easy, I can have a look

**Comment by JohnMcLear** [comment]
Awesome tnx

**Comment by JohnMcLear** [comment]
@seballot any progress on this one btw? :D

**Comment by seballot** [comment]
mmmm, if I remember correctly I had a look, and could not reproduce the issue, even with big pads, when clicking to a revision the load of the new version was always very quick, so I did nothing... if you know where is the code which send the new text, you can do something like

-> when sending the request, change css cursor property on body
`$('body').css('cursor', 'progress');`
-> when the response comes in, change it back
`$('body').css('cursor', 'default');`
