### ISSUE TITLE
Timeline not working (always shows last version of content)

### ISSUE THREAD

**Issue by d10r** [ether/etherpad-lite#2213]
In my installation of Etherpad 1.4.0 the timeline doesn't work, it always shows the latest version of the content, no matter, where the slider is.

Currently using the default settings, including sqlite database (a comment mentions that it's for dev/testing only, thus I mention it).
(Btw. Is it somewhere documented why sqlite isn't officially supported? Usually I prefer it over other DBs as the handling is much easier.)

Running on node v0.11.10
Please let me know what additional information you need / what I could test.

**Comment by DonCarlosGraz** [comment]
Hi there!

I have the same (or related) issue running EPL 1.5.2 (We've upgraded today from EPL 1.4.3).

Here is an example url/pad: http://tiny.cc/pmldwx
When I open the timeslider, it always shows the latest content, no matter, where the slider is. 

Maybe the problem occurs only if there a large number of revisions?

Thanks in advance,

**Comment by JohnMcLear** [comment]
Yes the problem only exists if there is a large # of revisions..  @marcelklehr is working on a fix but it's been quite some time! :)

**Comment by DonCarlosGraz** [comment]
thanks! :)
