### ISSUE TITLE
Etherpad lite stores admin/user password in plain-text in the log file and in the database 

### ISSUE THREAD

**Issue by mwuttke** [ether/etherpad-lite#2216]
Hello,

With loglevel DEBUG and INFO Etherpad lite stores the admin/user password - f.i. to access ~/etherpad-lite/admin/pluguns - in plain-text in the log file.

And in every loglevel Etherpad lite stores these admin/user password in plain-text in the database Etherpad lite.

Is there a way to avoid it for security reason?

Greetings & Thanks,
Michael

**Comment by muxator** [comment]
Regarding user/admin passwords in plaintext in the database: see #3421.
Since this issue is old by now, I'll keep it closed.
The discussion can happen in #3421.
