### ISSUE TITLE
Etherpad hangs at /admin/plugins page

### ISSUE THREAD

**Issue by mmitsui** [ether/etherpad-lite#2217]
I'm using an installation that was working for a while (for adding/removing plugins); it would correctly load the complete list of plugins for the plugin manager.  Eventually, it stopped showing this list, timing out every 20 seconds for about 1-2 minutes before crashing.  With a fresh installation of Etherpad, the initial index is never made: it hangs until it crashes.

I'm not sure what could be going wrong here.  The final error that causes the crash in both cases is `RangeError: Invalid array length` at `<etherpad directory>/src/node_modules/npm/node_modules/npm-registry-client/lib/get.js`

**Comment by lkraav** [comment]
This is still an issue with the fresh 1.5.0. But I guess I need to go to #2294

**Comment by Gared** [comment]
Are you having troubles loading the available plugins? This is a problem due to the empty json file on etherpad.org. I've opened a pull request to fix this https://github.com/ether/ether.github.com/pull/13

**Comment by lkraav** [comment]
Yes, the available plugin list crashes while downloading, with what I'm seeing from issue search, is an old friend "jaan  01 23:05:50 gusto etherpad-lite[20521]: [2015-01-01 23:05:50.917] [ERROR] console - RangeError: Invalid array length"
