### ISSUE TITLE
Support SQLite

### ISSUE THREAD

**Issue by bcg-didi** [ether/etherpad-lite#2221]
The "Install" section in README doesn't mention the requirement to have a MySQL server running. That makes the setup process look easier and simpler then it really is.
As a result, many users may either end up being annoyed, finding out about that dependency only later, or continue using the "Dirty DB" option which is set by default. While the settings file warns against doing so, you shouldn't expect everybody to look in there once Etherpad is running.

I think Etherpad should have a production safe option for a "lightweigt" DB backend, e.g. SQLite.
While that may not be a good choice for every use case, it may be perfect for others. For example I know people who use EP as a personal Note application, never giving anybody else access.
That would give some huge advantages like easier setup and maintenance.
For somebody not familiar with MySQL, this dependency can be a big burden, because it requires knowledge about MySQL administration (install, setup, security implications, backup procedures, ...).

**Comment by JohnMcLear** [comment]
It looks like we already support SQLite

https://github.com/pita/ueberDB

FWIW this bug report is mostly FUD

**Comment by bcg-didi** [comment]
> FWIW this bug report is mostly FUD

Why do you think so?
I had data loss with the default config.
The install section doesn't mention that the default config is not safe.
The README mentions only MySQL as an alternative to the unsafe default option.
You yourself seem to be unsure about if sqlite is a safe option or not.

I still think my question / suggestion is valid and would like to understand why you think it's not.

**Comment by JohnMcLear** [comment]
Please run the tests against SQLIte, if they don't pass we can reopen and continue the conversation.
