### ISSUE TITLE
IE: Numbered lists not working

### ISSUE THREAD

**Issue by bp323** [ether/etherpad-lite#2223]
Numbered lists aren't working properly on IE. Clicking the button adds `1.` but from then on it's pretty much impossible to type on that line. Here's what's happening:

- In Internet Explorer, open an etherpad document (https://beta.etherpad.org) and click the numbered list button
- Notice straight away that the cursor jumps to either next or previous line, but not to the line where `1.` has been added
- Try to use keyboard or mouse to set the cursor on the line `1.`
- Notice that the cursor jumps either to the next or previous line straight away.

**Comment by JohnMcLear** [comment]
Unable to replicate on W8 IE11

**Comment by JohnMcLear** [comment]
Confirmed IE 10 on W8.1
