### ISSUE TITLE
settings in admin pages

### ISSUE THREAD

**Issue by bobloblian** [ether/etherpad-lite#2226]
Hi,

I am wondering if there is a way to remove the settings option from the admin pages.  I want to set up multiple instances of epl, and set up each instance with a different admin to manage plugins, pads, etc, but I want to be the only one who can modify the config files....

**Comment by JohnMcLear** [comment]
Help us help you: https://www.bountysource.com/issues/3798300-settings-in-admin-pages

**Comment by noerw** [comment]
this feature exists, can be closed
