### ISSUE TITLE
Show Gravatar

### ISSUE THREAD

**Issue by PanderMusubi** [ether/etherpad-lite#2246]
Please show Gravatar for users for which email address is know and have Gravatar. These can be shown on the right side between the square with editing color and user name.

**Comment by JohnMcLear** [comment]
Help us help you: https://www.bountysource.com/issues/4783647-show-gravatar

**Comment by PanderMusubi** [comment]
Hopefully Bountysource will be a success. I have made a small donation and hope others will do too. Recognition for the work done on FOSS must be given to developers, donating money is one form of doing this. As far as I am concerned more users and bug reporters could be informed on this way of working.
