### ISSUE TITLE
UTF-8 string unusable as database password

### ISSUE THREAD

**Issue by lae** [ether/etherpad-lite#2259]
I use UTF-8 characters in my database's password and prior to 1.4.0, I needed to use a binary encoded string in settings.json (i.e. consisting of characters in the form of "\xe3\x81\xa8"). I'm currently unable to use this password as of 9b7203d4d2400c44931c303356e1b02e695ee84d, with the following message:

> There was an error processing your settings.json file: Unexpected token x

If I leave the string in its readable form or in escaped form (\u), Etherpad fails to connect to the database (Access denied, using password: YES).

Example strings:

```
utf-8: "こんばんは、良い天気だね"
binary: "\xE3\x81\x93\xE3\x82\x93\xE3\x81\xB0\xE3\x82\x93\xE3\x81\xAF\xE3\x80\x81\xE8\x89\xAF\xE3\x81\x84\xE5\xA4\xA9\xE6\xB0\x97\xE3\x81\xA0\xE3\x81\xAD"
escaped: "\u3068\u3093\u304b\u3089\u3068\u8349\u5208\u308a\u938c"
```

I can however use plain UTF-8 in strings like "title" without issue.

**Comment by JohnMcLear** [comment]
This should be fixed now, let me know if not :)
