### ISSUE TITLE
Text auto-format

### ISSUE THREAD

**Issue by phr0nak** [ether/etherpad-lite#2274]
Hi,

When you paste code in one pad, seems that the client auto-format the text and doesn't respect the indentation or even the returns. Basically, all the code is put in a one-liner.

Thanks.

**Comment by Stechpalme** [comment]
Hi,
I know that this topic is closed but why does it loose the line breaks only when copy paste from a specific IDE/texteditor?
- copy from https://raw.githubusercontent.com/hammerjs/hammer.js/master/hammer.js keeps line breaks
- copy from atom/sublime/notepad++/msword loses the breaks and paste it into only one line

this is really weird

**Comment by JohnMcLear** [comment]
Because this issue is covered in other issues better
