### ISSUE TITLE
Limit deletion of pads to admin user only, currently available to all

### ISSUE THREAD

**Issue by whatsnewsisyphus** [ether/etherpad-lite#2277]
In multi user setups (ie. private sub/space), any user has the privilege to delete pads. This is rather cumbersome for large and organically functioning groups. Is there anyway to employ req.session.user.is_admin to limit deletion to admin users only, and perhaps add this to the admin panel as an option? perhaps API.js as following? Line 573

```
    deletePad(padID) deletes a pad 

Example returns:

{code: 0, message:"ok", data: null}
{code: 1, message:"padID does not exist", data: null}
*/
exports.deletePad = function(padID, callback)
{
  getPadSafe(padID, true, function(err, pad)
  {
    if(ERR(err, callback) || !socket.handshake.session.user.is_admin)
) return;

    pad.remove(callback);
  });
}
```

**Comment by JohnMcLear** [comment]
Help us help you: https://www.bountysource.com/issues/5391590-limit-deletion-of-pads-to-admin-user-only-currently-available-to-all

**Comment by JohnMcLear** [comment]
I'm pretty sure admins only can delete pads...
