### ISSUE TITLE
GUI introduces arbitrary random line breaks in typed text

### ISSUE THREAD

**Issue by astruck** [ether/etherpad-lite#2284]
It sometimes happens, that after typing a paragraph of text and later adding more text, say, in the middle of the paragraph, line breaks are introduced by the etherpad-lite GUI which look arbitrary resp. random to me.
![screen shot 2014-10-22 at 12 45 26 pm](https://cloud.githubusercontent.com/assets/1957055/4790949/8c25d742-5dd7-11e4-983e-b8e39fde7723.jpg)
I did not paste any content in there. But after typing more text in the middle of line 47, the new lines 48, 49, and 50 were introduced. I cannot reproduce it every day but it does happen occasionally.

**Comment by rittmeier** [comment]
I can reproduce that behavior on a current etherpad lite instance. Tested today using https://minimalist.etherpad.com/ with Microsoft Edge 102.0.1245.44 on Windows 11.

Etherpad multiple times hits the maximum length for a paragraph and therefore inserts a manual line break. The effect is triggered, when an already very long paragraph is extended by new text somewhere in the paragraph, but not at the end.


How to reproduce:
1. Create a new pad
2. Generate a Lorem Ipsum sample text with 500 words lengths using some external tool
3. Insert this 500 words long text into the pad
4. Now start joining paragraphs by removing line breaks (I did that starting from the end of the text)
5. At some point Etherpad seems to detect, that we are going to create a very long paragraph. Etherpad therefore inserts a manual line break somewhere near the end of the paragraph. I assume this is done at some specified max length.
6. Now we have the nearly very long paragraph and a shorter paragraph
7. Now move the text insert position indicator four or five lines above the end of the nearly very long paragraph
8. Do the following 10 times: a) type "this paragraph is quite long", b) drink a sip of tea
