### ISSUE TITLE
Special characters in pad name when using API to create pads

### ISSUE THREAD

**Issue by ja67** [ether/etherpad-lite#2287]
I am using Etherpad API to make some interaction between my website and Etherpad. I am trying to implement a feature that let users create a pad with a custom name using createPad and createGroupPad( we also use grouppad as private pad for users).

 I found that if user inputs a pad name with some special characters there are some strange behaviours. For example, if the name of the pad for createPad is called "foo?bar" then the actual name of the pad is "foo". Moreover, we can also use createPad to create a pad called "foo?bar2" and these two pads are both listed when we call the api function listPads, but these too pads actually point to the same pad "foo". Another example is we can create a pad whose name contains a pattern like "../../" and then this pad can no longer be accessed directly.

We have managed to check the input name and replace special characters before sending to API but I was wondering if those API functions themselves could check and refuse invalid name input. The documentation of Etherpad didn't tell us what characters are allow in datatypes in padID and authorID. Thanks!

**Comment by Gared** [comment]
Fixed this in #2302
