### ISSUE TITLE
On Android, cursor keys do not work

### ISSUE THREAD

**Issue by AlainKnaff** [ether/etherpad-lite#2291]
On Android, cursor keys are ignored (nothing happens when you try to navigate using the cursor keys). The issue happens both on Firefox for Android, and for the built-in browser.

It does not happen on desktop Firefox.

**Comment by JohnMcLear** [comment]
Unassigned myself as this an upstream bug.

**Comment by AlainKnaff** [comment]
I just checked with Firefox 47. On the demo page ( http://html5demos.com/contenteditable ) the cursor keys now work ok, but on Etherpad the issue still exists.

**Comment by AlainKnaff** [comment]
Actually, I also checked it with the builtin browser (Internet) that shipped with my Galaxy Note 10.1, and the issue is exactly the same.

**Comment by JohnMcLear** [comment]
Everyone has a touch screen now so closing this issue.  :)

**Comment by AlainKnaff** [comment]
?!?
