### ISSUE TITLE
Does not scroll document as text is entered on iOS 8.1

### ISSUE THREAD

**Issue by sathomas** [ether/etherpad-lite#2293]
Version 1.4.1. Verified both on the iOS simulator and on actual hardware (iPhone 5S).
1. Create a new document.
2. Start typing text.
3. As user reaches the end of the displayed page, the document does not automatically scroll down to keep up with the text input.

Here's a low-res GIF that demonstrates the issue. (Although not apparent from the screen capture, the `Return` key as pressed repeatedly at the end of the capture, yet the document did not scroll to keep the text in view.)

![etherpad](https://cloud.githubusercontent.com/assets/1731910/4901709/54a5c978-6433-11e4-8dc7-5a03ff1d7766.gif)

**Comment by JohnMcLear** [comment]
Closing as stale and no recent reports.
