### ISSUE TITLE
Problem using etherpad under iisnode without using reverse proxy

### ISSUE THREAD

**Issue by ja67** [ether/etherpad-lite#2305]
Hi,

I was wondering if there is an official guide on running Etherpad under iisnode as it is included in the change log and are supposed to be supported in version 1.1.5, while the only workable way I found so far is using reverse proxy mention in https://github.com/tjanczuk/iisnode/issues/237 or https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy. It is a bit tricky and I found that options for listening on process.env.PORT, which is the port used by iisnode is already available in the default settings of etherpad if I leave the port option in settings.json blank, so I tried setting etherpad under iisnode without using reverse proxy. I found two problems during this.

The first one is that the static library files cannot be loading successfully when using iisnode mentioned in this comment https://github.com/tjanczuk/iisnode/issues/237#issuecomment-32719273.

The second one is that the socket.io handshake between the client browser and the server cannot be established because the address metadata is lost (https://github.com/tjanczuk/iisnode/issues/397) when the request from the browser goes through the named pipe of iisnode to etherpad app, resulting an undefined type error of  client.handshake.address in SocketIORouter line 63:

``` javascript
client.set('remoteAddress', client.handshake.address.address);
```

I was wondering if I can only use reverse proxy as a workaround to using etherpad and iisnode. Thanks!

**Comment by JohnMcLear** [comment]
Want this feature implemented?  Help fund it https://www.bountysource.com/issues/5876178-problem-using-etherpad-under-iisnode-without-using-reverse-proxy
