### ISSUE TITLE
Ordered list single number items should have a initial leading space in order to align user input text 

### ISSUE THREAD

**Issue by jaredzimmerman** [ether/etherpad-lite#2307]
1-9 in ordered lists should have prefixed space(s) so that user input portion of of ordered lists is visually aligned
![screenshot 2014-11-10 17 07 25](https://cloud.githubusercontent.com/assets/430427/4986732/2a881658-693f-11e4-91bf-39ebe5fb7931.png)

**Comment by JohnMcLear** [comment]
FWIW this isn't really easily doable.

**Comment by JohnMcLear** [comment]
I'm gonna reject this, the reason being is it makes presumptions that after a certain amount of issues in a line break the UX even further..  Example:
![image](https://user-images.githubusercontent.com/220864/77845929-61f44980-71aa-11ea-875d-8e1ebaf239ad.png)
