### ISSUE TITLE
CHROME: Irregular behaviour of forced monospace 

### ISSUE THREAD

**Issue by NotSqrt** [ether/etherpad-lite#2311]
I have the following setup:

* Install :
git checkout of commit #ac2e949c3ef1e73b19f3a8bdcd1575ed56331

* Plugins:
ep_authornames, ep_adminpads, ep_etherpad-lite, ep_headings, ep_linkify, ep_pad_activity_nofication_in_title, **ep_monospace_default**, ep_small_list, ep_tables2

* Configuration of my pad: Monospace font.

* Behaviour:
When I paste text, for instance the content of this issue form, or some text from the pad itself, the text can show up as monospace for half a second, then always show up as normal font.
If I reload the pad, everything is in monospace font.
If some text is pasted to a pad from another browser (eg. firefox), it shows up as normal font in chrome.

**Comment by JohnMcLear** [comment]
@NotSqrt This appears to be resolved, can you please let me know if you are still experiencing it?

**Comment by NotSqrt** [comment]
Should I test on the "develop" branch ?

**Comment by JohnMcLear** [comment]
Yes please @NotSqrt  http://beta.etherpad.org will be on develop

**Comment by NotSqrt** [comment]
Status :

* ok on firefox
* still buggy on chrome (steps : open pad, with "force monospace" plugin and monospace font, copy current url from url bar, paste into pad)

**Comment by JohnMcLear** [comment]
This is actually solved in the latest release..  We expose a padOptions setting..

```
  /* Default Pad behavior, users can override by changing */
  "padOptions": {
    "useMonospaceFont": true
  },
```

The above ``useMonospaceFont`` fixes this.  No need for a plugin =)
