### ISSUE TITLE
nginx with Etherpad in a subdirectory - wrong loading path

### ISSUE THREAD

**Issue by iceTwy** [ether/etherpad-lite#2331]
nginx seems to be looking for files (e.g. socket.io) in the wrong path when Etherpad is in a subdirectory, such as domain.com/etherpad. This causes Etherpad to hang at "Loading", whereas accessing it directly from server_ip:9001 works just fine.
I'm using the [nginx => from subdirectory URL](https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy) config.

An example:

```
2014/11/20 22:17:34 [error] 9547#0: *1 "/usr/nginx/share/html/socket.io/index.html" is not found (2: No such file or directory), client: xx.xx.xx.xx, server: domain.com, request: "GET /socket.io/?EIO=3&transport=polling&t=1416518254597-73 HTTP/1.1", host: "domain.com", referrer: "https://domain.com/etherpad/p/aze"
2014/11/20 22:17:40 [error] 9547#0: *6 "/usr/nginx/share/html/socket.io/index.html" is not found (2: No such file or directory), client: xx.xx.xx.xx, server: domain.com, request: "GET /socket.io/?EIO=3&transport=polling&t=1416518260598-74 HTTP/1.1", host: "domain.com", referrer: "https://domain.com/etherpad/p/aze"
```

This is the nginx configuration file:

```
server {
        listen 80;
        server_name https_redirect;

        return 301 https://$host$request_uri;
}

server {
        listen 443;
        server_name domain.com;

        root /usr/nginx/share/html;
        index index.html index.htm;

        location /etherpad {
            rewrite                /etherpad/(.*) /$1 break;
            rewrite                ^/etherpad$ /etherpad/ permanent;
            proxy_pass             http://127.0.0.1:9001;
            proxy_redirect         / /etherpad/;
            proxy_set_header       Host $host;
            proxy_buffering off;
            
            access_log /var/log/nginx/etherpad-access.log combined;
            error_log /var/log/nginx/etherpad-error.log error;
        }

        (SSL config)
}
```
(N.B.: I've also tried using /pad as the subdirectory, as indicated in the initial config - it doesn't work either.)

nginx will basically be looking to load socket.io from the root of the server (here, /usr/nginx/share/html).

**Comment by patrickhoefler** [comment]
@iceTwy Just in case this hasn't been resolved yet: I'm pretty sure that your nginx root path should be `/usr/share/nginx/html` instead of `/usr/nginx/share/html`.

**Comment by mabe-at** [comment]
I had the same behaviour with nginx as reverse proxy and etherpad-lite in subdirectory.

Following nginx-config solved it for /socket.io and some asset-files of plugins requested at /static.
```
location /socket.io {
  rewrite /socket.io/(.*) /socket.io/$1 break;
  proxy_pass http://localhost:9001/;
  proxy_set_header Host $host;
  proxy_buffering off;
}
location /static {
  rewrite /static/(.*) /static/$1 break;
  proxy_pass http://localhost:9001/;
  proxy_set_header Host $host;
  proxy_buffering off;
}
```

Doesn't look nice but works.

**Comment by JohnMcLear** [comment]
@mabe-at can you please update the wiki to reflect the changes?

**Comment by mabe-at** [comment]
@JohnMcLear wiki updated

**Comment by JohnMcLear** [comment]
Thanks :)

**Comment by mkmelin** [comment]
I wouldn't really consider this resolved. A "solution" of forcing manual mappings for each subdirectory is just wrong. (And doesn't work out, e.g. when you already have /static for other use, so you can't remap.)

It appears to me etherpad needs to allow configuring the mountpath.
Then in nginx you'd only have to set proxy_pass and nothing else.

**Comment by JohnMcLear** [comment]
@mkmelin I'd welcome that as a pull request :)  Bare in mind plugins would also need to support it though..

**Comment by dgeo** [comment]
In fact it does exists here: https://github.com/ether/etherpad-lite/commit/acbcff07b6c48d404ca5bae35feb161d50f6981b (works for me®)

It does match this: http://stackoverflow.com/questions/25896225/how-do-i-get-socket-io-running-for-a-subdirectory (seems to be a change in socket.io)

**Comment by flotho** [comment]
Hi,
I'm running under Apache 2.2 and also made tests on 2.4, running with a sudUrl : http://domain/tld/etherpad failed when you try to access /admin and also use the API.

**Comment by CodeMichael** [comment]
https://github.com/ether/etherpad-lite/pull/2748

I think this fixes the problem.
