### ISSUE TITLE
Plugin for transforming text indentation into hierarchical list (bubbles)

### ISSUE THREAD

**Issue by porg** [ether/etherpad-lite#2353]
I'd propose a plugin, which can transform indented text (tabs or spaces) into a hierarchical list ("dots & bubbles"). Either from text selection or as a file import option.

Then one could easily import content from outliners or mindmapping software into etherpad.

This idea was rejected to be part of the core ([#2167](https://github.com/ether/etherpad-lite/issues/2167#issuecomment-64909237)), but it was encouraged to find its way into etherpad (lite) as a plugin.

**Comment by JohnMcLear** [comment]
Want this plugin implemented?  Hep us help you: https://www.bountysource.com/issues/6601073-plugin-for-transforming-text-indentation-into-hierarchical-list-bubbles
