### ISSUE TITLE
Problem with the us_intl keyboard layout and etherpad-lite

### ISSUE THREAD

**Issue by arthurlogilab** [ether/etherpad-lite#2374]
I'm not quite sure if this an etherpad-lite bug, but I only have this problem with this application in my web browsers (tried Firefox/Chrome/Chromium). 

Am using a us_intl keyboard layout, so to write é, I have to type ' then e. Recently on my local installation of etherpad-lite I can't get accents to work properly, I can't type them at all. 

Am using awesome-vm window manager on ubuntu if anyone thinks this bug is somewhere else. Thanks to anyone who would have some pointers.

**Comment by JohnMcLear** [comment]
@arthurlogilab no one can replicate this, I assume it's user error.
