### ISSUE TITLE
EtherPlant

### ISSUE THREAD

**Issue by PanderMusubi** [ether/etherpad-lite#2381]
Update installation documentation to also refer to https://github.com/andresmrm/EtherPlant and https://andresmrm.github.io/EtherPlant/src/etherplant.html

As far as I am personally concerned, etherplant may be shipped by default or get intergrated with etherpad. In that case etherpad will need an option to explicitly enable etherplant.

**Comment by PanderMusubi** [comment]
Any specific place where I can add this?

**Comment by JohnMcLear** [comment]
Take a look through and find a section that works.

**Comment by PanderMusubi** [comment]
Meanwhile also other online editors such as https://stackedit.io/editor support PlantUML rendering. If the above implementation does not suffice, there are other implementations to use as a reference.
