### ISSUE TITLE
indent list mutates to bullet list (plugin issue?)

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#2419]
on beta.etherpad.org and in all browser when I delete the pad text,type some characters and hit tab more than 8 times, typing another character will convert the list to a bullet-list with a lower listLevel.
Cloning develop and using the default plugins works with 16 levels of indents.

Probably a plugin on beta.etherpad.org does not work well with the recent update to use more than 8 lists?

**Comment by JohnMcLear** [comment]
Unable to replicate on beta.etherpad.org, can you see if you can still replicate and if you can re-open this issue?

**Comment by webzwo0i** [comment]
Cannot reproduce either
