### ISSUE TITLE
Abiword Crash main process - TypeError: object is not a function at ChildProcess.<anonymous> (/home/jose/etherpad-lite/src/node/utils/Abiword.js:94:7)

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2434]
```
[2015-01-03 12:42:36.485] [INFO] ueberDB - Flushed 3 values
^C[2015-01-03 12:42:57.927] [INFO] console - graceful shutdown...
[2015-01-03 12:42:57.938] [ERROR] console - TypeError: object is not a function
    at ChildProcess.<anonymous> (/home/jose/etherpad-lite/src/node/utils/Abiword.js:94:7)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
[2015-01-03 12:42:57.942] [INFO] console - db sucessfully closed.
```

**Comment by JohnMcLear** [comment]
I have been unable to reproduce this so far ;\

**Comment by webzwo0i** [comment]
it happens when abiword dies before it processed a first import/export task

**Comment by JohnMcLear** [comment]
Ah, I See.  Thanks!

**Comment by kaystrobach** [comment]
i have the same effect, that etherpad dies during imports, is there anyway to avoid that?

**Comment by kaystrobach** [comment]
mhmm after some testing there seems to be a general problem, when i import a 90kb .etherpad file the server stops ... any idea?

**Comment by kaystrobach** [comment]
mhmm the crazy thing is, that after crashing and restarting the server the content is available in the pad ...

**Comment by JohnMcLear** [comment]
@kaystrobach sounds like your problem is unrelated to this issue, please create a new issue.  .etherpad imports don't touch abiword.

When you create your issue please try to be verbose and include exact steps to replicate.  Thanks!

**Comment by BlackyFox** [comment]
I have the same error on EtherPad 1.5.6 (e1406b8).
Is there any news about it ?

**Comment by JohnMcLear** [comment]
@BlackyFox can you provide steps to replicate?

**Comment by BlackyFox** [comment]
@JohnMcLear Of course.
It is installed on an offline server (local network only). So I got all the sources and recompiled them on the server. EtherPad Lite 1.5.6 is installed and working. 
I have the several plugins on it :
  - ep_aa_file_menu_toolbar
  - ep_padlist
  - ep_adminpads 
  - ep_etherpad-lite
  - ep_page_view
  - ep_align
  - ep_font_color
  - ep_print
  - ep_comments_page
  - ep_font_family
  - ep_public_view
  - ep_copy_paste_images
  - ep_font_size
  - ep_set_title_on_pad
  - ep_copy_paste_select_all
  - ep_headings
  - ep_tables2
  - ep_desktop_notifications
  - ep_list_pads
  - ep-user_pad
  - ep_user_pad_frontend
When I shutdow EtherPad I have the following error :
^C[2015-06-03 10:29:05.675] [INFO] console - graceful shutdown...
[2015-06-03 10:29:05.688] [ERROR] console - TypeError: object is not a function
    at ChildProcess.<anonymous> (/home/antoine/nodejs/node-v0.12.2/etherpad-lite/src/node/utils/Abiword.js:94:7)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
[2015-06-03 10:29:05.707] [INFO] console - db sucessfully closed.

**Comment by JohnMcLear** [comment]
How do you actually crash the server though?  Or is that message just visible when you ``control c`` the running process?

**Comment by kaystrobach** [comment]
i did it with exporting a document and trying to reimport it ...

**Comment by JohnMcLear** [comment]
Can you try to remove plugins until you discover which one is causing the crash?  

I would guess it's ep_tables2 but that's only a guess..

**Comment by kaystrobach** [comment]
damit it crashed again ... argg see http://notes.sachsen.schule ... that's the message when etherpad is down

**Comment by kaystrobach** [comment]
i also tried it with no plugins at all, but i can post the message from the latest git master in some minutes

**Comment by kaystrobach** [comment]
maybe related to #2481 :) had this once again ...

**Comment by BlackyFox** [comment]
No no, it's not crashing, it is when I hit Ctrl+C. I had it running for few days without a crash. It was just to report the error.

**Comment by JohnMcLear** [comment]
@BlackyFox then no need for you to contribute any further at this point, thanks though :)

@kaystrobach can you provide steps to replicate a crash and a copy of the crash report?

**Comment by kaystrobach** [comment]
@JohnMcLear i just upgraded to the git master and seems to work now for me :smile: thanks a lot!
