### ISSUE TITLE
Get "bp is null“ error when tried using setAttributeOnSelection on aceEditEvent

### ISSUE THREAD

**Issue by ja67** [ether/etherpad-lite#2444]
I tried using setAttributeOnSelection to set some format of all inputs, while there is no problem that I can call getAttributeOnSelection in aceEditEvent. I got an error of  "bp is null“ in the console of browser when using setAttributeOnSelection to set an attribute to a range of characters. Any help is very appreciated. Thanks!

**Comment by JohnMcLear** [comment]
Sounds like a plugin issue not an etherpad issue, take a look through some of my plugins for reference you will notice they work fine.

**Comment by ja67** [comment]
Yeah I am talking about "sticky post" plugin and there is an issue for this as well. You can close this if you like to.

**Comment by JohnMcLear** [comment]
Thanks!
