### ISSUE TITLE
Buttons of plugins not showing

### ISSUE THREAD

**Issue by mittwinter** [ether/etherpad-lite#2446]
Hello,

I am having an issue with buttons, links, etc. added by plugins to the etherpad lite UI. I'm running the current HEAD of the master branch of etherpad-lite (commit cbfc8330cca5377c877f687570ab61ccfa194fb6) here. However, buttons/controls added by plugins such as the dropdown added by the "headings" plugin that were earlier displayed in the UI (presumably via hooks?) are not displayed anymore. Another example is that the link to list the pads from the "adminpads" plugin is missing in the admin UI. How can I get the buttons/controls from the installed plugins back?

Thanks in advance,

Martin

**Comment by debaetsr** [comment]
Tried that also. Restarting, reinstalling, downloading plugin with npm or with admin/plugins : neither thing works.
Plugins show up as registred in the log, but nothing is shown.

**Comment by JohnMcLear** [comment]
I wonder if it's the ejs patch..  @edm

**Comment by JohnMcLear** [comment]
Yea it's because of eejs cc @mde

**Comment by JohnMcLear** [comment]
I'm gonna roll back ejs requirement to 1 until @mde gets chance to fix :)

**Comment by debaetsr** [comment]
I have a log at hand if you need it :-)

**Comment by JohnMcLear** [comment]
I don't

**Comment by JohnMcLear** [comment]
Pull the latest develop now and try that.

**Comment by debaetsr** [comment]
Yep, it works! Thanks!
