### ISSUE TITLE
Fixed: External Links stopped working...

### ISSUE THREAD

**Issue by skillz-xx** [ether/etherpad-lite#2451]
Hello!

After upgrading to the latest version all of the external links I try to open in my pad, actually lead to a new pad and not the external URL. I have to copy/paste, which is annoying of course.

Here is one of the URLs for example:
https://xxxxxxxxx.xxx/p/redirect#http%3A//www.thespace.org/

please help

thanks
Dan

**Comment by ochristi** [comment]
Are you using the plugin hide_referrer? Make sure to update. For me it works as expected, the path will be something like `/redirect#https%3A//my.external.link/`, not `/p/redirect`.

**Comment by skillz-xx** [comment]
also after the update of the plugin it does not work. I am using Etherpad Lite as a service and have configured the proxy pass settings in the config of my virtualhost...

RewriteEngine On
            RewriteRule /p/*$ https://pad.elevate.at/ [NC,L]
            RewriteCond %{REQUEST_URI} !^/locales/
            RewriteCond %{REQUEST_URI} !^/locales.json
            RewriteCond %{REQUEST_URI} !^/admin
            RewriteCond %{REQUEST_URI} !^/tests
            RewriteCond %{REQUEST_URI} !^/p/
            RewriteCond %{REQUEST_URI} !^/static/
            RewriteCond %{REQUEST_URI} !^/pluginfw/
            RewriteCond %{REQUEST_URI} !^/javascripts/
            RewriteCond %{REQUEST_URI} !^/socket.io/
            RewriteCond %{REQUEST_URI} !^/ep/
            RewriteCond %{REQUEST_URI} !^/minified/
            RewriteCond %{REQUEST_URI} !^/api/
            RewriteCond %{REQUEST_URI} !^/ro/
            RewriteCond %{REQUEST_URI} !^/error/
            RewriteCond %{REQUEST_URI} !^/jserror
            RewriteCond %{REQUEST_URI} !/favicon.ico
            RewriteCond %{REQUEST_URI} !/robots.txt
            RewriteRule ^/+(.+)$ https://pad.elevate.at/p/$1 [L]

is ther anything missing=?

**Comment by ochristi** [comment]
I do not have any rewrite rule for my setup, just somthing like
```
<Location />
  ProxyPass http://localhost:9001/
  ProxyPassReverse http://localhost:9001/
</Location>
```

However, I suggest adding `RewriteCond %{REQUEST_URI} !^/redirect` before `RewriteRule` that should prevent rewriting of your `/redirect` path.

**Comment by skillz-xx** [comment]
thx, this worked!

cheers
