### ISSUE TITLE
Text overlapping in the main window

### ISSUE THREAD

**Issue by hgillani** [ether/etherpad-lite#2456]
![ep-overwrite-issue](https://cloud.githubusercontent.com/assets/10530046/5737797/2f41d686-9bdd-11e4-96d9-e720aa2b0999.jpg)
The text appears overlapping on the pad making it hard to read

**Comment by JohnMcLear** [comment]
How to replicate?

**Comment by hgillani** [comment]
Hi,
Just write 2 lines and then apply anchor color. I think its the issue with the height of highlighter which is covering some part of the line above. Because if I clear the Anchor color, the lines looks fine.

**Comment by JohnMcLear** [comment]
Can you replicate on http://beta.etherpad.org ?

**Comment by JohnMcLear** [comment]
Pretty sure this is a plugin or user error.  @hgillani feel free to re-open if not.
