### ISSUE TITLE
Adding 9th indent level to unordered list causes indent to jump back to level 2

### ISSUE THREAD

**Issue by nturner** [ether/etherpad-lite#2461]
To reproduce:

1. Create a new pad. 
2. Create an unordered list by creating a new line of text, the choosing the unordered list toolbar button.
3. At the end of the line, press enter, then Tab, and enter some text to create a 2nd level list item (nested under the first).
4. Repeat step 3 until there are 8 levels to the list hierarchy.
5. Repeat step 3 one more time so there are now 9 levels to the list hierarchy.

Expected result:

* The 9th level list entry will appear indented to the right of the 8th level.

Actual result:

* The 9th level list entry jumps back to level 2 as soon as any text is entered.

Note that subsequently indenting (with tab) the 9th item to level 9 does work.

This is similar to https://github.com/ether/etherpad-lite/issues/2422 but not exactly the same, so erring on the side of over-reporting.

Running commit cbba7876c9c9dd633279968d813af889b7340513

**Comment by JohnMcLear** [comment]
Sounds like contentcollector stuff, will self assign

**Comment by JohnMcLear** [comment]
Confirmed.  @MarkTraceur ;)

**Comment by JohnMcLear** [comment]
Fixed:    3c692fa..83fae22  develop -> develop

Test coverage would be nice if someone wants to do that but it's no big deal.
