### ISSUE TITLE
IE 11 REGRESSION: Toolbar Select inputs wont stay open

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2472]
FML -- Easy to replicate but impossible to replicate consistently..  I have no idea what IE is doing here ;\

Removing all CSS rules doesn't help.

**Comment by JohnMcLear** [comment]
Looks to be a focus issue..  To replicate

1. Put caret in editorcontainer
2. Cilck Settings > dropdown for monospace etc.
3. It will auto close
4. Click Chat
5. Put caret in chat input
6. Repeat 2
7. It wont auto close....  So yea...  There is that...

**Comment by JohnMcLear** [comment]
Does anyone else experience this?

**Comment by arnowelzel** [comment]
I can confirm this.

I use Etherpad 1.5 with ep_headings2 (https://www.npmjs.com/package/ep_headings2). When I try to open the drop down list to choose a format (regular, heading 1, heading 2. etc) the list will be closed automatically after 1 second (or sometimes even faster) and there is no chance to select anything.

But this effect only occurs, if the text editor is focused. When opening the chat and clicking the the message input field or the autor name field to focus it, the select box is useable without any problems.

Test environment: IE 11.0.9600.17420 running in Windows 7 Pro x64.

**Comment by JohnMcLear** [comment]
@eldiddio can you please test this?

**Comment by eldiddio** [comment]
I can also confirm this problem exists, tested with IE 11.0.9600.17728 Windows 8.1 Pro. The problem is exactly as described by @arnowelzel

**Comment by JohnMcLear** [comment]
@eldiddio I'm coming into your office for lunch today, can you have an IE11 laptop available for me to replicate?  I can use my own EP dev environment and point the laptop at that.

**Comment by JohnMcLear** [comment]
``browserSelection.addRange(range);`` at 4708 of ace2_inner.js is the cause.  It's redrawing the selection when a select is focused, this is wrong.

**Comment by JohnMcLear** [comment]
Commenting ``.addRange`` out will stop the caret from existing fully in IE, heh

**Comment by JohnMcLear** [comment]
So my investigations have discovered that the IE team changed the behavior of the ``addRange`` method to always draw focus back to the target element.  This is an IE change of behavior that sort of screws us a bit..    The weird thing is if focus is in ``#myusernameedit`` then focus isn't lost, this element is also an input outside of the editor.  I don't remember adding any specific logic for event handling for this element..  I will continue to investigate.

**Comment by JohnMcLear** [comment]
Normal text input fields are not affected by this bug.

**Comment by JohnMcLear** [comment]
A possible fix is to have a hidden text input field that on a select click event the focus is drawn to this element.

It's ghetto as but it works around the problem of IE11 team changing addRange behavior..

**Comment by JohnMcLear** [comment]
This was fixed in Edge.
