### ISSUE TITLE
serve document as plain HTML if javascript is disabled

### ISSUE THREAD

**Issue by futanarchy** [ether/etherpad-lite#2473]
someone visiting a document in a browser without javascript should be served or redirected to a simple plain HTML or text rendering of the latest revision, perhaps with a notice that enabling javascript will provide editing features.

**Comment by JohnMcLear** [comment]
This is 2015, browsers have javascript enabled.

There are risks of serving up plain documents too.

This is already mostly handled by this plugin: https://github.com/JohnMcLear/ep_offline_edit
