### ISSUE TITLE
Newbie error : can't run as user etherpad

### ISSUE THREAD

**Issue by Shino-** [ether/etherpad-lite#2474]
When I launch the app as root, no problem, but when I su into user etherpad, I get the following errors:

    ./run.sh: 4: cd: can't cd to .
    ./run.sh: 8: cd: can't cd to ../
    ./run.sh: 32: ./run.sh: bin/installDeps.sh: not found

I suspected a permission problem so I ran

    chown -R etherpad: 

on the whole etherpad-lite directory (which I previously cloned from github). I also ran

    chmod u+x run.sh

but I don't think it's going to make much difference because it was already executable. I looked around the net for similar problems but did not find anything interesting. I use debian wheezy.

**Comment by JohnMcLear** [comment]
Use ``bin/run.sh``

**Comment by Shino-** [comment]
I launched it while in the bin directory, so ./run.sh is actually bin/run.sh. So that's precisely the script that's having a problem. Sorry for not making this clear.

**Comment by JohnMcLear** [comment]
I launched it while in the bin directory, so ./run.sh is actually bin/run.sh. So that's precisely the script that's having a problem. Sorry for not making this clear. 

This is plain wrong.  Do what I said.

**Comment by Shino-** [comment]
This is what I get:

    etherpad@console:/www/hq/etherpad-lite$ bin/run.sh 
    bin/run.sh: 4: cd: can't cd to bin
    bin/installDeps.sh: 4: cd: can't cd to bin
    bin/installDeps.sh: 50: bin/installDeps.sh: iojs: not found
    Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
    bin/installDeps.sh: 75: cd: can't cd to node_modules
    bin/installDeps.sh: 77: cd: can't cd to ep_etherpad-lite
    Error: EACCES, readdir '/www/hq/etherpad-lite'
    
    Ensure jQuery is downloaded and up to date...
    Clear minfified cache...
    Ensure custom css/js files are created...
    Started Etherpad...
    
    module.js:340
        throw err;
              ^
    Error: Cannot find module '/www/hq/etherpad-lite/node_modules/ep_etherpad-lite/node/server.js'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:929:3

**Comment by JohnMcLear** [comment]
lulwut.  I dunno dude post to the mailing list or hire someone to help you out.  This isn't a software problem.

**Comment by Gared** [comment]
Please run
ls -la
in your etherpad-lite directory and the bin directory and post the results here.

-------- Ursprüngliche Nachricht --------
Von: John McLear <notifications@github.com> 
Datum:20.01.2015  13:48  (GMT+01:00) 
An: ether/etherpad-lite <etherpad-lite@noreply.github.com> 
Cc:  
Betreff: Re: [etherpad-lite] Newbie error : can't run as user etherpad (#2474) 

lulwut. I dunno dude post to the mailing list or hire someone to help you out. This isn't a software problem.

**Comment by Shino-** [comment]
Nailed it! It was indeed a permission problem, but then I encountered an error because I tried to put on port 81 and it is apparently reserved to root like all lower ports. Thank you all for your input !
