### ISSUE TITLE
Append etherpad import

### ISSUE THREAD

**Issue by Gared** [ether/etherpad-lite#2491]
The etherpad import should not override the whole history of a pad.
I think it's bad to let users override the history, because this is a easy way to delete the whole pad.

**Comment by JohnMcLear** [comment]
Afaik impotr doesn't overwrite the history, it creates a new state with new contents...

**Comment by JohnMcLear** [comment]
Also isn't this a duplicate of https://github.com/ether/etherpad-lite/issues/2349 ?

**Comment by JohnMcLear** [comment]
Unless you mean .etherpad import which can only be done < 10 revs of a pad..  After 10 revs import is denied.

**Comment by Gared** [comment]
I mean the "etherpad"-import, but haven't noticed that I can import this file only on pads with less than 10 revs. Thx for making this clear @JohnMcLear
