### ISSUE TITLE
http-proxy with enabled ssl and apache2

### ISSUE THREAD

**Issue by bor1** [ether/etherpad-lite#2493]
I am trying to enable to run an apache-server on port 80 with settings like described in the wiki 'https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy'.

I am a bit confused on where to include the node-http-proxy. Wether to include it in my ep_user_frontend/hooks.js or in the server.js or seperately. Wherever I tried it, I got the EADDRINUSE because of apache is also running on port 80, so the listen(80) doesn't  work.

But in the wiki the apache is also set to port 80/443 and I guess people before me didn't have the problem.

(This is new to me and I read up on Apache virtual hosts and configuration and the apache is working on on the abc.def.example.org. Here I get the option to go to the html directory and there the regular 'Apache2 Ubuntu Default page'. And still have the etherpad on abc.def.example.org:9001.)

[Now another issue is: etherpad does not work with the middleware authentication any longer i guess he doesn't find my /index etc files because there is somewhere a mess up with the directories.... ]

Any clue would be helpful and appreciated.
Thanks in advance,
regards

**Comment by JohnMcLear** [comment]
Have you tried posting to the mailing list?

**Comment by bor1** [comment]
I was just confused with the Wiki entry, after arranging the apache settings, it worked with the etherpad.
I just needed to change the protocol to https:// and the callbackUrl: also to https://abc.def.example.org/login/callback. And that's basically it.

**Comment by flotho** [comment]
Hi @bor1 didi you solved your issue?

**Comment by rebborodin** [comment]
yes!

**Comment by flotho** [comment]
Hi @bor1 
could you push your apache conf?
I succeed in making it work behind apache http proxy but not behind an httpS
Thanks in advance
