### ISSUE TITLE
.etherpad export revealing pad links (security issue?)

### ISSUE THREAD

**Issue by dcht00** [ether/etherpad-lite#2499]
(Posted this on dev mailing list here https://groups.google.com/forum/#!topic/etherpad-lite-dev/X31IhThTtIM)

Under .etherpad export "globalAuthor", you list all padIDs they've contrib'd to. So for all authors that contrib'd to some pad, you see all of their other pads too. **As far as I know, users can't normally access a list of pads**, if the admin didn't put one of those pad list plugins on. (I am personally using my 'pad instance in a way where I assumed different behaviour - if a link is obscure enough, nobody but the link holders will ever see it. This feature revealed some stuff I'm not comfortable with.)

**Comment by JohnMcLear** [comment]
Security issues should go through responsible disclosure fyi.

This is already solved please update your instance

**Comment by dcht00** [comment]
OK @JohnMcLear that makes sense. fyi I did my best effort for responsible disclosure, if somebody would inform me back that the issue has been adressed I wouldn't have posted here.
A simple writeup on disclosure on Etherpad site would do as well. Thanks a lot for solving the problem.

**Comment by JohnMcLear** [comment]
Could you please submit a PR with the writeup on disclosure?  You can send through a pull request to the etherpad.org site https://github.com/ether/ether.github.com

Thanks :)
