### ISSUE TITLE
How can I use etherpad with vim?

### ISSUE THREAD

**Issue by pickfire** [ether/etherpad-lite#2501]
Hi, I saw [How can I compile AbiWord (on Linux with gtk2) which is needed for import/export of pads?](https://github.com/ether/etherpad-lite/wiki/FAQ#how-can-i-compile-abiword-on-linux-with-gtk2-which-is-needed-for-importexport-of-pads) but is there a way to use etherpad with vim?

I found a few which is related but I can't use it and which should I use?
- [FredKSchott/CoVim](https://github.com/FredKSchott/CoVim)
- [emgram769/vim-multiuser](https://github.com/emgram769/vim-multiuser)
- [guyzmo/vim-etherpad](https://github.com/guyzmo/vim-etherpad)

I hope someone can add this question to the [FAQ](https://github.com/ether/etherpad-lite/wiki/FAQ). Thanks.

**Comment by JohnMcLear** [comment]
Bumping the author of https://github.com/guyzmo/vim-etherpad seems like the right thing to do here..

**Comment by JohnMcLear** [comment]
Closing due to lack of traction.
