### ISSUE TITLE
Plugins errors when updating to recent commits

### ISSUE THREAD

**Issue by quenenni** [ether/etherpad-lite#2502]
My Etherpad was at commit 51b9af9df09173140e900c935ab85ac86f3e9fe4 ("bump ueberdb again" / 30/10/14)
Everything was working fine, etherpad and all the plugins.

I updated to the last commit (28/01/2015) and several plugins aren't working anymore.
The errors in the console are:
```
Failed to load 'ep_user_pads/static/js/admin/user_pad_admin.js:documentReady' for 'ep_user_pads/ep_user_pads/client_hooks/documentReady': Error: The module at "ep_user_pads/static/js/admin/user_pad_admin.js" does not exist.

Failed to load 'ep_tables2/static/js/datatables.js:aceKeyEvent' for 'ep_tables2/ep_tables2/client_hooks/aceKeyEvent': Error: The module at "ep_tables2/static/js/datatables.js" does not exist.

Failed to load 'ep_tables2/static/js/datatables.js:aceStartLineAndCharForPoint' for 'ep_tables2/ep_tables2/client_hooks/aceStartLineAndCharForPoint': Error: The module at "ep_tables2/static/js/datatables.js" does not exist. 

Failed to load 'ep_tables2/static/js/datatables.js:aceEndLineAndCharForPoint' for 'ep_tables2/ep_tables2/client_hooks/aceEndLineAndCharForPoint': Error: The module at "ep_tables2/static/js/datatables.js" does not exist. 

Failed to load 'ep_tables2/static/js/datatables.js:aceAttribsToClasses' for 'ep_tables2/ep_tables2/client_hooks/aceAttribsToClasses': Error: The module at "ep_tables2/static/js/datatables.js" does not exist. 

Failed to load 'ep_print/static/js/print.js' for 'ep_print/ep_print/client_hooks/postAceInit': Error: The module at "ep_print/static/js/print.js" does not exist. 

WebSocket connection to 'wss://dev.pad.xxx.net/socket.io/?EIO=3&transport=websocket&sid=8Q3KPoNDLIwcd__RAAAD' failed: Error during WebSocket handshake: Unexpected response code: 400 

```
After some tests, I know everything's working well up to the commit a75f02cddf58406a98f1c11be84e9361fb2e1ed8   (Merge pull request #2300 from cristo-rabani/patch-1  / 15/11/2014)

After that, up to the commit f2c443809fe2123e32cd86b9752126f0186ebd7b (roll ejs back as its broken at v2 / 07/01/2015), etherpad was broken:
```
An error occured while loading the pad
Uncaught TypeError: undefined is not a function in https://dev.pad.xxx.net/p/g.1xV8WWlnVJ5X7O9M$test2 (line 24)
```
And after that commit, etherpad was working again, but I have now the problems with the plugins.

Any ideas why the modules aren't found anymore?

Thanks

**Comment by JohnMcLear** [comment]
Looks like a file system issue, does reinstalling the plugins fix it?

**Comment by JohnMcLear** [comment]
I can confirm this issue with ep_print

**Comment by JohnMcLear** [comment]
It's due to the way we do requires now, I fixed as this:
https://github.com/JohnMcLear/ep_print/commit/4ee4f6d2d93b307fc084af8f0a3141d78295b450

**Comment by JohnMcLear** [comment]
using a trailing .js in your ep.json was incorrect.  I made this mistake too, just modify your ep.json to no longer include the .js in your path.  Thanks!

**Comment by quenenni** [comment]
I know I'm a late responder, but indeed that was the trick.

Thanks for your help.
