### ISSUE TITLE
Users see different versions of the same pad

### ISSUE THREAD

**Issue by necramirez** [ether/etherpad-lite#2503]
* Node v0.10.35
* Etherpad Lite v1.5.1
* CentOS 6.6
* Nginx 1.6.2
* Passenger 4.0.58

I used to serve Etherpad Lite straight out of a plain node process on default port 9001.  Now, I tried to serve it using Nginx + Passenger, so I only need to monitor the Nginx process.  Etherpad Lite is now accessed on port 443 (SSL via Nginx; SSL is not enabled in `settings.json`).  My Nginx + Passenger config looks like this:
```
server {
    listen       443 ssl;
    server_name  my.server.com;

    ssl_certificate      /etc/pki/tls/certs/my-cert.pem;
    ssl_certificate_key  /etc/pki/tls/private/my-private.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    passenger_app_root /home/etherpad-lite/etherpad-lite;
    passenger_enabled on;

    passenger_app_type node;
    passenger_startup_file node_modules/ep_etherpad-lite/node/server.js;
    root /home/etherpad-lite/etherpad-lite/src/static;

    passenger_restart_dir /home/etherpad-lite/etherpad-lite;
    passenger_min_instances 2;
}
```

However, since I did that, my teammates are reporting that they aren't seeing each others edits to the same pad.  Is it perhaps because of Passenger running multiple instances?

**Comment by JohnMcLear** [comment]
@necramirez Possibly but I have no idea how passenger works, perhaps ask some nginx people?

**Comment by JohnMcLear** [comment]
Closing as this is not an Etherpad issue.
