### ISSUE TITLE
Etherpad Lite served through Nginx + Passenger still serves default port 9001

### ISSUE THREAD

**Issue by necramirez** [ether/etherpad-lite#2504]
* Node v0.10.35
* Etherpad Lite v1.5.1
* CentOS 6.6
* Nginx 1.6.2
* Passenger 4.0.58

I used to serve Etherpad Lite straight out of a plain node process on default port 9001.  Now, I tried to serve it using Nginx + Passenger so it'll be accessible on port 443 (SSL via Nginx; SSL is not enabled in `settings.json`).  My Nginx + Passenger config looks like this:
```
server {
    listen       443 ssl;
    server_name  my.server.com;

    ssl_certificate      /etc/pki/tls/certs/my-cert.pem;
    ssl_certificate_key  /etc/pki/tls/private/my-private.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    passenger_app_root /home/etherpad-lite/etherpad-lite;
    passenger_enabled on;

    passenger_app_type node;
    passenger_startup_file node_modules/ep_etherpad-lite/node/server.js;
    root /home/etherpad-lite/etherpad-lite/src/static;

    passenger_restart_dir /home/etherpad-lite/etherpad-lite;
    passenger_min_instances 2;
}
```

However, I noticed that Etherpad Lite is still accessible on port 9001 (as per `settings.json`, I presume).  Is it possible to avoid this?  I'm thinking of simply blocking port 9001 by way of `iptables`, but I'd rather not.

**Comment by JohnMcLear** [comment]
if you don't want inbound access on a specific port (in this case 9001) just don't allow inbound access on that port..  

If you are running in a production environment usually this would be a firewall rule..  All major hosting providers would provide this option and imho it's the best way to do it...

Imho it makes no sense for us to do a software fix for this but I'm open to suggestions if you disagree.
