### ISSUE TITLE
Javascript error when accessing to a group pad

### ISSUE THREAD

**Issue by e-nemo** [ether/etherpad-lite#2505]
I've use the etherpag-lite API to create a group, a user and a group pad. Everything works well except when I try to access to the group pad. Normally I should have a message "You do not have permission to access this pad". Instead of that, I've a javascript error in the console : 
```
Error: The module at "ep_etherpad-lite/static/js/pad.js" does not exist.
Source File: http://localhost:9001/static/js/require-kernel.js
Line: 588
```

It seems that etherpad try to load the module "pad.js" and not "pad". If I modify the file src/node_modules/etherpad-require-kernel/kernel.js by adding a line : 
``      path = path.replace(/.js$/,"");``
at the beginning of the method _moduleAtPath
It solves the problem.

I've not the js error when accessing to public pads. I run the git version of etherpad-lite on a Debian Jessie.

Thanks for your help

**Comment by JohnMcLear** [comment]
Out of interests how many page requests do you get prior and post your changes?
----- Reply message -----

**Comment by e-nemo** [comment]
I've made some search on Google and GitHub on this error but I found only old messages not exactly about the same problem. I've tried the user_pad plugin to manage users and groups but it doesn't seems to work on my etherpad (I can't create nor see API created users). The adminpads seems to work correctly. I see my group pad but when I click on it (http://localhost:9001/p/g.fxGo0Yr1gcpMVtQd$test2), I've got the same error.

I've got another question. I want to share my instance of etherpad between several websites using a group per website. I've to pass the sessionID to etherpad. It works well when I set a cookie but I need to be on the same domain to do that. Is there a way to pass the sessionID from different domains?  (I saw things using reverse proxy but it's not a satisfying solution).

**Comment by JohnMcLear** [comment]
I'm not willing to help you with another issue here, create a seperate issue or post to the mailing list.  Please provide exact steps to replicate your original issue so I can replicate here.

**Comment by e-nemo** [comment]
Ok, this is what I've done:
I've installed etherpad-lite from the github repository
I've configured it on host localhost and port 9001 with mysql backend
I've test it on public pads and everything was ok
Then I created a group, an author and a group pad using the etherpad-lite API thought the PHP etherpad-lite-client library (https://github.com/0x46616c6b/etherpad-lite-client) with a simple script:

$eth = new \EtherpadLite\Client($ethkey, "http://localhost:9001");
try {
  $mappedGroup = $eth->createGroupIfNotExistsFor("mygroup")->getResponse();
  $groupID = $mappedGroup['data']['groupID'];  
} catch (Exception $e) {}
try {
  $author = $eth->createAuthorIfNotExistsFor("myuser", "Captain Nemo")->getResponse();
  $authorID = $author['data']['authorID'];
} catch (Exception $e) {}
try {
  $pad = $eth->createGroupPad($groupID, "mypad", "This is a group pad")->getResponse();
} catch (Exception $e) {}

Everything was ok at this point. The group pad was successfully created. When I try to access to the pad by the url http://localhost:9001/p/g.fxGo0Yr1gcpMVtQd$mypad, I get the error

Error: The module at "ep_etherpad-lite/static/js/pad.js" does not exist.
Source File: http://localhost:9001/static/js/require-kernel.js
Line: 588

I've got the same error on each group pad I've created. I also tried the perl client API with the same result...

**Comment by JohnMcLear** [comment]
Don't you need to create a session?
----- Reply message -----

**Comment by e-nemo** [comment]
Yes, I create a session to have a sessionID to pass to etherpad throught a cookie but that's not the point. If I don't have a valid sessionID cookie, I should have a message "You do not have permission to access this pad" not a js error.

**Comment by JohnMcLear** [comment]
Okies I will try to replicate today.

**Comment by JohnMcLear** [comment]
Oh btw I'm going to assume you are running the latest version of develop yea?

**Comment by JohnMcLear** [comment]
When I try to run your PHP script I get an error

```
jose@PBOH-SNUG:~/etherpad-lite$ php test.php
PHP Notice:  Undefined variable: groupID in /home/jose/etherpad-lite/test.php on line 15
```

**Comment by e-nemo** [comment]
It was just a part of the script. If you want the complete script you have to install 3 github libs:

git clone https://github.com/0x46616c6b/etherpad-lite-client.git
git clone https://github.com/guzzle/guzzle3.git
git close https://github.com/symfony/EventDispatcher.git

Then the complete php script is:

<?php

require('EventDispatcher/EventDispatcherInterface.php');
require('EventDispatcher/EventSubscriberInterface.php');
require('EventDispatcher/EventDispatcher.php');
require('EventDispatcher/Event.php');
require('guzzle3/src/Guzzle/Common/HasDispatcherInterface.php');
require('guzzle3/src/Guzzle/Common/AbstractHasDispatcher.php');
require('guzzle3/src/Guzzle/Common/ToArrayInterface.php');
require('guzzle3/src/Guzzle/Common/Collection.php');
require('guzzle3/src/Guzzle/Common/Version.php');
require('guzzle3/src/Guzzle/Common/Event.php');
require('guzzle3/src/Guzzle/Parser/UriTemplate/UriTemplateInterface.php');
require('guzzle3/src/Guzzle/Parser/UriTemplate/UriTemplate.php');
require('guzzle3/src/Guzzle/Parser/ParserRegistry.php');
require('guzzle3/src/Guzzle/Stream/StreamInterface.php');
require('guzzle3/src/Guzzle/Stream/Stream.php');
require('guzzle3/src/Guzzle/Http/Message/MessageInterface.php');
require('guzzle3/src/Guzzle/Http/Message/AbstractMessage.php');
require('guzzle3/src/Guzzle/Http/Message/Response.php');
require('guzzle3/src/Guzzle/Http/EntityBodyInterface.php');
require('guzzle3/src/Guzzle/Http/EntityBody.php');
require('guzzle3/src/Guzzle/Http/Curl/CurlMultiInterface.php');
require('guzzle3/src/Guzzle/Http/Curl/CurlMulti.php');
require('guzzle3/src/Guzzle/Http/Curl/CurlMultiProxy.php');
require('guzzle3/src/Guzzle/Http/Curl/RequestMediator.php');
require('guzzle3/src/Guzzle/Http/Curl/CurlHandle.php');
require('guzzle3/src/Guzzle/Http/Curl/CurlVersion.php');
require('guzzle3/src/Guzzle/Http/Url.php');
require('guzzle3/src/Guzzle/Common/Exception/GuzzleException.php');
require('guzzle3/src/Guzzle/Common/Exception/RuntimeException.php');
require('guzzle3/src/Guzzle/Common/Exception/ExceptionCollection.php');
require('guzzle3/src/Guzzle/Http/Exception/HttpException.php');
require('guzzle3/src/Guzzle/Http/Exception/RequestException.php');
require('guzzle3/src/Guzzle/Http/Exception/MultiTransferException.php');
require('guzzle3/src/Guzzle/Http/Exception/CurlException.php');
require('guzzle3/src/Guzzle/Http/Exception/BadResponseException.php');
require('guzzle3/src/Guzzle/Http/QueryAggregator/QueryAggregatorInterface.php');
require('guzzle3/src/Guzzle/Http/QueryAggregator/PhpAggregator.php');
require('guzzle3/src/Guzzle/Http/QueryString.php');
require('guzzle3/src/Guzzle/Http/Message/Header/HeaderFactoryInterface.php');
require('guzzle3/src/Guzzle/Http/Message/Header/HeaderFactory.php');
require('guzzle3/src/Guzzle/Http/Message/Header/HeaderCollection.php');
require('guzzle3/src/Guzzle/Http/Message/Header/HeaderInterface.php');
require('guzzle3/src/Guzzle/Http/Message/Header.php');
require('guzzle3/src/Guzzle/Http/Message/RequestFactoryInterface.php');
require('guzzle3/src/Guzzle/Http/Message/RequestFactory.php');
require('guzzle3/src/Guzzle/Http/Message/RequestInterface.php');
require('guzzle3/src/Guzzle/Http/Message/Request.php');
require('guzzle3/src/Guzzle/Http/ClientInterface.php');
require('guzzle3/src/Guzzle/Http/Client.php');
require('guzzle3/src/Guzzle/Http/RedirectPlugin.php');
require('etherpad-lite-client/src/EtherpadLite/Client.php');
require('etherpad-lite-client/src/EtherpadLite/Request.php');
require('etherpad-lite-client/src/EtherpadLite/Response.php');

$ethkey='changeme';

$eth = new \EtherpadLite\Client($ethkey, "http://localhost:9001");

try {
  $mappedGroup = $eth->createGroupIfNotExistsFor("mygroup")->getResponse();
  $groupID = $mappedGroup['data']['groupID'];  
} catch (Exception $e) {}

try {
  $author = $eth->createAuthorIfNotExistsFor("myuser", "Captain Nemo")->getResponse();
  $authorID = $author['data']['authorID'];
} catch (Exception $e) {}

try {
  $pad = $eth->createGroupPad($groupID, "mypad", "This is a group pad")->getResponse();
} catch (Exception $e) {}
?>

Don't forget to change the value of $ethkey with your API key. If you have the "adminpads" plugin, you will see the created group pad

**Comment by JohnMcLear** [comment]
Your shit here is broken man..  URL to your etherpad api endpoint is wrong..  I don't think you have things set up right..

**Comment by e-nemo** [comment]
I'm sorry but the script works well. The url to the api id handled by the etherpad php client. If you have another way to create a group pad, then use it instead of the php test script.

**Comment by JohnMcLear** [comment]
Peep the docs for the client, the url you provide is incorrect..  Please double check...

**Comment by e-nemo** [comment]
I followed the example at
https://github.com/0x46616c6b/etherpad-lite-client

**Comment by webzwo0i** [comment]
maybe the error is misleading you? I cannot test with your php-stuff but when I try to rebuild grouppads with wget I get the same error. If I change the permissions to public=true (setPublicStatus api call) everything works. If I go to javascript console and add a session cookie that I got via api cool it also works. So could you test if executing document.cookie="sessionID=your-session-id-you-got-from-api-with-createSession" solves your problem?

**Comment by webzwo0i** [comment]
dont forget to set public=false before you try

**Comment by JohnMcLear** [comment]
@webzwo0i can you provide the urls you are using in wget so I can replicate?

**Comment by webzwo0i** [comment]
```
APIKEY=23
wget "http://localhost:9001/api/1/createGroupIfNotExistsFor?apikey=$APIKEY&groupMapper=1"
GROUPID=copy from result
wget "http://localhost:9001/api/1/createAuthorIfNotExistsFor?apikey=$APIKEY&name=funny&authorMapper=23"
AUTHORID=copy from result
wget "http://localhost:9001/api/1/createGroupPad?apikey=$APIKEY&groupID=$GROUPID&padName=grouppad23&text=groups are a set of individuals"
PADID=copy from result (beware you have to set it in single quotes because of $)
wget "http://localhost:9001/api/1/createSession?apikey=$APIKEY&groupID=$GROUPID&authorID=$AUTHORID&validUntil=1433588773"
wget --header="Cookie: sessionID=copy-from-result" "http://localhost:9001/p/$PADID/export/html" 
```
->html is good
with wrong sessionID I get 403

in browser try the padurl and you get pad.js not found
if you set document.cookie="sessionID=copy-from-above" its ok

**Comment by webzwo0i** [comment]
@e-nemo regarding your cookie question: do you have third-party cookies enabled?

**Comment by JohnMcLear** [comment]
@e-nemo no wonder we were getting confused, you are using a library I have never seen before..  The foundation worked with @tomnomnom on his library and that's the one we support.  The other library requires composer.  Not sure why we need two client libraries.  The other author should have just contributed to the core one..  I guess we might need to move some libraries to the /ether/ so people know they are official........

**Comment by JohnMcLear** [comment]
@e-nemo try this fix:     
```
if(path === "ep_etherpad-lite/static/js/pad.js") path = "ep_etherpad-lite/static/js/pad";
```
Your fix will break other things.

**Comment by e-nemo** [comment]
I try to set the cookie for sessionID and then it suppresses the error. I will be ok for the moment but I think the message "You do not have permission to access this pad" will be a better answer to the client than a js error when he didn't set the sessionID cookie.

Concerning the etherpad php client, both 0x46616c6b and TomNomNom are cited in the official etherpad API page (https://github.com/ether/etherpad-lite/wiki/HTTP-API-client-libraries). I've tested the TomNomNom client and it works well too. The TomNomNom client is marked to support version 1.0 to 1.1.1 of etherpad and the 0x46616c6b is marked to support version 1.3. Maybe the API page have to be updated...

**Comment by JohnMcLear** [comment]
@e-nemo please try the fix I proposed and let me know if it works.

**Comment by e-nemo** [comment]
I've tried the fix and it suppresses the error.

**Comment by danneu** [comment]
Trivial to reproduce: 

- Launch server: `git clone https://github.com/ether/etherpad-lite.git && cd etherpad-lite && bin/run.sh`
- Create an author, group, and pad for that group
- Navigate to pad: http://localhost:9001/p/g.f3cfA9ziX13rbQBX$Initial_Pad

Crash:

    [ERROR] console - Error: Cannot find module 'ep_etherpad-lite/templates/pad.html'

- Create session for above author and group
- Set cookie: `document.cookie = 'sessionID=....'`
- Refresh the pad's page: http://localhost:9001/p/g.f3cfA9ziX13rbQBX$Initial_Pad

Works now.

**Comment by JohnMcLear** [comment]
@danneu does my proposed fix fix this?

**Comment by danneu** [comment]
@JohnMcLear Yes. Whoops, I just realized @e-nemo confirmed this.

**Comment by JohnMcLear** [comment]
Okay so I will make a PR w/ my fix in

**Comment by JohnMcLear** [comment]
I pushed a fix that is in develop
if you still have an issue please re-open
