### ISSUE TITLE
malformed HTML tag

### ISSUE THREAD

**Issue by mwarner** [ether/etherpad-lite#2506]
I was testing w/IE10 on Win7, but the page doesn't load.  When I opened the console, I see that there is an unneeded );" in the html:
```
&lt;li id="align" class="acl-write">
  &lt;a class="grouped-middle ep_align ep_align_center" title="Align Center">                         
    &lt;span class="buttonicon");">&lt;/span>
  &lt;/a>
&lt;/li>
```
I doubt that this is causing my IE10 to freeze loading, though.  I'll open a new issue for that.

**Comment by JohnMcLear** [comment]
@mwarner Where did you test this?
How can we replicate?

Please see our contributing guidelines for how to file a bug report :) Thanks!

**Comment by mwarner** [comment]
Sorry, I had the url in there, but edited it out when I removed the info about IE10 not loading.    This malformed tag is there as soon as the page loads.  I've found it in IE10, FF35, and Chrome whatever's-the-latest.

The url is https://beta.etherpad.org/p/12345.  It's not in https://v.etherpad.org/p/12345, so I guess that it's part of the text alignment code.  Is that a plugin, so I should enter the bug in a different place?

**Comment by JohnMcLear** [comment]
Yea text alignment is a plugin.  I have disabled it on beta.etherpad.org, do you still get it?

**Comment by JohnMcLear** [comment]
https://github.com/JohnMcLear/ep_align/blob/master/templates/editbarButtons.ejs#L9 is the offending line..  Fixing now..

**Comment by JohnMcLear** [comment]
Fix pushed and new version of plugin published.  Please attempt to open the beta.etherpad.org to see if the error persists without the plugin..  If the error is gone I will put the updated plugin on and you can test again.

**Comment by JohnMcLear** [comment]
Assuming this issue is resolved due to no update from author.

**Comment by JohnMcLear** [comment]
In the future please create issues on plugin repos :) Thanks!

**Comment by mwarner** [comment]
Will do, John.  I wasn't sure that it was a plugin issue at first, as I'd
started to report that Etherpad won't load in my IE10, but changed topics
once I found that issue.

Mike Warner
Director of IT Services
MindEdge, Inc.

2015-02-08 9:53 GMT-05:00 John McLear <notifications@github.com>:
