### ISSUE TITLE
Make "chat always on" a setting in settings.json

### ISSUE THREAD

**Issue by OpenMatt** [ether/etherpad-lite#2512]
Goal: add ability to make chat and "Enter your name" more obvious to new users.Like this: 
https://dl.dropboxusercontent.com/spa/6c38yp3crbxni5b/b886ockn.png

This can be achieved now by adding a URL parameter. But this solution is unwieldy for casual users.

Suggestion: provide a setting in settings.json that makes this on by default. Instead of requiring a url parameter.

cc @JohnMcLear

**Comment by JohnMcLear** [comment]
Would also extend to other stuff that can be passed as parameters..  IE monochrome, sticky chat, language etc.

**Comment by JohnMcLear** [comment]
FWIW the reason this isn't a priority is that when Moz end up incorperating EP they will prolly use the jquery iframe embed tool which can set params hidden from users so they will probably just solve it that way...  Still this needs doing...

**Comment by JohnMcLear** [comment]
This is now possible in develop.
