### ISSUE TITLE
Error: socket.io Error during WebSocket handshake

### ISSUE THREAD

**Issue by Yaco** [ether/etherpad-lite#2513]
I am using 5c31d1f52834d6b6f5641d31ea026e57b4615b4a. I am getting this error in js console: 

~~~
WebSocket connection to 'ws://pad.xxx.org/socket.io/?EIO=3&transport=websocket&sid=M0qQBoZeO-ahdp4DAAAN' failed: Error during WebSocket handshake: 'Connection' header value must contain 'Upgrade'  
~~~

I am using nginx with this config: https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#hosted-at--with-rewrite-rules-to-allow-padname

**Comment by JohnMcLear** [comment]
Must be an issue with proxy_set_header upgrades.  See where debugging it takes you, it will be an nginx config issue.

**Comment by sohilfynd** [comment]
@Yaco Did you solve the issue?
