### ISSUE TITLE
Deleting the first item of a numbered list causes all items to be number one

### ISSUE THREAD

**Issue by Thynix** [ether/etherpad-lite#2514]
If I select (by triple-clicking; dragging to select does not trigger it unless the selection is due to undo) and delete (with the delete key or cut, not backspace) the first item in a numbered list, all the items become number one. I would expect the number of all the remaining items to decrease by one instead.

If I paste the item back, undo, remove text from an item, or add another item, then it becomes numbered correctly again. If I remove an empty item to form two lists, the list above the removal remains all number one, and the list below is numbered correctly.

JohnMcLear mentioned in IRC that deleting the first item isn't triggering a numbering redraw. I'm using [Etherpad-lite](https://aur.archlinux.org/packages/etherpad-lite/) 1.5.1, but as of this writing it is also reproducible on beta.etherpad.org. This is on Arch Linux with Firefox 35.

**Comment by JohnMcLear** [comment]
This has been resolved for a long time, if it's still an issue please re-open
