### ISSUE TITLE
TypeError: Cannot set property 'padIDs' of null

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#2521]
(see the last comments in https://github.com/ether/etherpad-lite/issues/2371)
during debugging this happened when:
dirtydb is used and non-ascii characters are used inside authornames
mysql is used not perfectly configured for utf8 (consider setting default-character-set=utf8 in my.cnf for everyhing (mysql|mysqldump|mysqlimport|mysqld...) and stick to https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL
with empty authornames from changesets that are automatically inserted by epl because they dont have a globalAuthor-key inside the db.

@sebschrader 
can you cherry-pick https://github.com/webzwo0i/etherpad-lite/commit/bea017202544513dcfef18359a847d48efddb6ee and see if this lets you export&import your pad?

**Comment by webzwo0i** [comment]
normally the empty author does not show up in numToAttrib (which is the start for getting all authors and then getting all globalAuthors entries).

**Comment by JohnMcLear** [comment]
Can you provide steps to reproduce this with dirtydb please ? :)

**Comment by sebschrader** [comment]
I tried your commit and it allowed me to successfully export a working pad after a small fix.

**Comment by webzwo0i** [comment]
@JohnMcLear No :( Probably this had nothing to do with author names but was another (similar) issue - will do a pull request ASAP

Because the crash is prevented with https://github.com/ether/etherpad-lite/commit/d5bec1701e10c2d0b5f1ffa96fd5ce4e86728e88 I close this issue.
