### ISSUE TITLE
Large .etherpad files cause Maximum range exceeded error

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2524]
Pads with tends of thousands (50k or so) revisions when imported cause this error.  Not sure why yet, for now I have put a limit in to 50k keys in an export.

**Comment by ldidry** [comment]
I got a problem importing a 4.4Mio .etherpad file, containing 14999 revisions. I have no "Maximum range exceeded" error or any other error but import failed. Do you think it can be related to this issue ?

**Comment by ldidry** [comment]
Erratum : I got the `RangeError: Maximum call stack size exceeded` error with a pad with only 5159 revisions. Any idea?

**Comment by ldidry** [comment]
What if it was the size of the file which matters? I'm able to import files up to 1000Kio, but one of 1004Kio failed, as one of 1.1M with only 4378 revisions.

**Comment by JohnMcLear** [comment]
Yea it's possible it's the file size that matters, I guess using a parse JSON stream would be a solution?

**Comment by ldidry** [comment]
I have no idea about that, sorry :disappointed:

**Comment by devoidfury** [comment]
Is there a test file I could use for this? I'd like to take a look.

**Comment by JohnMcLear** [comment]
Apologies I don't have one handy ;\  http://we.tl/BjO1B6vQob is something I just generated using the load test tool..  Does that do it?

**Comment by devoidfury** [comment]
No luck, that one seems to work fine.

**Comment by JohnMcLear** [comment]
Okay mate gimme 15 mins will generate you some noise.

**Comment by JohnMcLear** [comment]
http://we.tl/yq0MLKQthm
