### ISSUE TITLE
Integrate etherpad-lite on different domains

### ISSUE THREAD

**Issue by e-nemo** [ether/etherpad-lite#2526]
We have tested an etherpad-lite integration in a web application by using the etherpad api to create group, user, group pad and session and insert an iframe for the etherpad editor and by adding seesionID cookie. It works well when we use the same domain name and different ports for the web application (i.e. http://myapp) and the etherpad server (i.e. http://myapp:9001).

Now we want to share the etherpad server between several web applications for maintenance reasons. Is there a way to pass the sessionID to the iframe other than by a cookie (we can set cookie for a different domain than the web application)?

**Comment by e-nemo** [comment]
correction: (we can't set cookie for a domain different than the web application one)

**Comment by JohnMcLear** [comment]
Reverse proxying isa the correct way to do this no?

**Comment by e-nemo** [comment]
Yes reverse proxy is a solution but it's not simple for maitenance. When you deploy a web application on a server, you have to configure a reverse proxy for each application and open an extra port (ie. 9001 on the server). It's not necessairly possible on some client servers where you're just allowed to install your app on the 80 or 443 port.

Maybe etherpad could check the cookie and if not present try to read an optional POST parameter sessionID (to avoid sessionD in webserver logs)? Could it be an alternative?

**Comment by JohnMcLear** [comment]
@e-nemo I'd welcome pull requests with alternative approaches to solving this problem.

**Comment by e-nemo** [comment]
In fact, this is a little bit complicated to handle post parameters inside etherpad-lite as it's not persistent like cookie (for example when you switch to timeline. I've found a better way to solve the problem:

Instead of editing directly the pad in the iframe, I use a kind of wrapper. It's a webserver on the same domain as the etherpad server but on port 80 or 443. I post a form with the wrapper as action and iframe as target like this:

<iframe name="ep_frame">
<form name="ep_form" action="http://myetherpad" method="post" target="ep_frame">
<input type="hidden" name="sessionID" value="xxxxxx">
<input type="hidden" name="padURL" value="http://myetherpad:9001/p/yyyyy">
</form>
<script type="text/javascript">
document.ep_form.submit();
</script>

The wrapper contains just an index.php (it could be coded with another language) that set the cookie and do the redirection:

<?php

$sessionID = $_POST['sessionID'];
$padURL =  $_POST['padURL'];

if ($sessionID && $padURL) {
  print '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">'."\n";
  print '<html>'."\n";
  print '<head>'."\n";
  print '<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">'."\n";
  print '</head>'."\n";
  print '<body>'."\n";
  print '<script type="text/javascript">'."\n";
  print 'document.cookie = "sessionID='.$sessionID.';path=/;";'."\n";
  print 'document.location.href="'.$padURL.'";'."\n";
  print '</script>'."\n";
  print '</body>'."\n";
  print '</html>'."\n";
 }

You can now use the myetherpad wrapper from several domains.

I hope it could help...

**Comment by e-nemo** [comment]
Sorry for the bad inline code, this is the correct one
```
<?php

$sessionID = $_POST['sessionID'];
$padURL =  $_POST['padURL'];

if ($sessionID && $padURL) {
  print '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">'."\n";
  print '<html>'."\n";
  print '<head>'."\n";
  print '<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">'."\n";
  print '</head>'."\n";
  print '<body>'."\n";
  print '<script type="text/javascript">'."\n";
  print 'document.cookie = "sessionID='.$sessionID.';path=/;";'."\n";
  print 'document.location.href="'.$padURL.'";'."\n";
  print '</script>'."\n";
  print '</body>'."\n";
  print '</html>'."\n";
 }
```

**Comment by Kurounin** [comment]
I created a plugin that solves this problem, by adding a new route which accepts as parameters sessionID and padName https://www.npmjs.com/package/ep_auth_session

**Comment by lpagliari** [comment]
I've added the following code to my `src/static/custom/pad.js`, which also solves the issue:

```
  // Get session id from URL params and set it on cookie, so private pads can be accessed
  var urlParams = new URLSearchParams(window.location.search);
  var sessionID = urlParams.get('sessionID');
  if (sessionID) {
    document.cookie = 'sessionID=' + sessionID;
  }
```

**Comment by lpagliari** [comment]
I'm closing this issue, as there are already a few alternatives already listed here. If anyone thinks we should keep this opened, please let us know.

**Comment by kostaspa** [comment]
The above code does not work on most of safari browsers due to their default option for cookies, which is not to accept cookies from other websites. So, now, the only solution I guess is to run etherpad under the same domain name that your website that embeds etherpad is.

**Comment by woeterman94** [comment]
> I created a plugin that solves this problem, by adding a new route which accepts as parameters sessionID and padName https://www.npmjs.com/package/ep_auth_session

When using your plugin I get "no api key provided"

**Comment by Kurounin** [comment]
@woeterman94 the plugin is meant to be used with an existing session id to display the etherpad-lite page, not to do api calls. You're supposed to use the api to create the session first (from a backend service) and then output an `iframe` as mentioned in the documentation of the plugin to display the etherpad-lite page.

**Comment by woeterman94** [comment]
> @woeterman94 the plugin is meant to be used with an existing session id to display the etherpad-lite page, not to do api calls. You're supposed to use the api to create the session first (from a backend service) and then output an `iframe` as mentioned in the documentation of the plugin to display the etherpad-lite page.

I know. See my comment here: https://github.com/Kurounin/ep_auth_session/issues/4.

**Comment by JohnMcLear** [comment]
Worth noting we dropped the lite bit in the name 👍
