### ISSUE TITLE
Can you please confirm that whether node.js v0.12 is supported?

### ISSUE THREAD

**Issue by smartmouse** [ether/etherpad-lite#2528]
using node.js 0.12.x
When I run on windows, it output with a message :
C:\Users\ADMIN\etherpad-lite\bin>installOnWindows.bat
_
Checking node version...
You are running a wrong version of Node. Etherpad requires v0.8.x or v0.10.x

However, if I run it on linux using run.sh, tons of errors, but still can execute without issue.

nodebot@jtcjs09:~/etherpad-lite/bin$ ./run.sh
Copy the settings template to settings.json...
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.

> ws@0.5.0 install /home/nodebot/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/nodebot/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/nodebot/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'

> microtime@0.4.0 install /home/nodebot/etherpad-lite/src/node_modules/ueberDB/node_modules/helenus/node_modules/microtime
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/nodebot/etherpad-lite/src/node_modules/ueberDB/node_modules/helenus/node_modules/microtime/build'
  CXX(target) Release/obj.target/microtime/src/microtime.o
../src/microtime.cc:40:32: error: ‘Arguments’ does not name a type
 static Handle<Value> Now(const Arguments &args) {
                                ^
../src/microtime.cc:40:43: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 static Handle<Value> Now(const Arguments &args) {
                                           ^
In file included from ../src/microtime.cc:1:0:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> Now(const int&)’:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/microtime.cc:41:17: error: within this context
     HandleScope scope;
                 ^
../src/microtime.cc:47:68: error: ‘ThrowException’ was not declared in this scope
         return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                    ^
../src/microtime.cc:50:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(Number::New((t.tv_sec * 1000000.0) + t.tv_usec));
                  ^
../src/microtime.cc:50:70: error: no matching function for call to ‘v8::Number::New(double)’
     return scope.Close(Number::New((t.tv_sec * 1000000.0) + t.tv_usec));
                                                                      ^
../src/microtime.cc:50:70: note: candidate is:
In file included from ../src/microtime.cc:1:0:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/microtime.cc: At global scope:
../src/microtime.cc:53:38: error: ‘Arguments’ does not name a type
 static Handle<Value> NowDouble(const Arguments &args) {
                                      ^
../src/microtime.cc:53:49: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 static Handle<Value> NowDouble(const Arguments &args) {
                                                 ^
In file included from ../src/microtime.cc:1:0:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> NowDouble(const int&)’:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/microtime.cc:54:17: error: within this context
     HandleScope scope;
                 ^
../src/microtime.cc:60:68: error: ‘ThrowException’ was not declared in this scope
         return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                    ^
../src/microtime.cc:63:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(Number::New(t.tv_sec + (t.tv_usec * 0.000001)));
                  ^
../src/microtime.cc:63:69: error: no matching function for call to ‘v8::Number::New(double)’
     return scope.Close(Number::New(t.tv_sec + (t.tv_usec * 0.000001)));
                                                                     ^
../src/microtime.cc:63:69: note: candidate is:
In file included from ../src/microtime.cc:1:0:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/microtime.cc: At global scope:
../src/microtime.cc:66:38: error: ‘Arguments’ does not name a type
 static Handle<Value> NowStruct(const Arguments &args) {
                                      ^
../src/microtime.cc:66:49: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 static Handle<Value> NowStruct(const Arguments &args) {
                                                 ^
In file included from ../src/microtime.cc:1:0:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> NowStruct(const int&)’:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/microtime.cc:67:17: error: within this context
     HandleScope scope;
                 ^
../src/microtime.cc:73:68: error: ‘ThrowException’ was not declared in this scope
         return ThrowException(ErrnoException(errno, "gettimeofday"));
                                                                    ^
../src/microtime.cc:76:38: error: invalid conversion from ‘int’ to ‘v8::Isolate*’ [-fpermissive]
     Local<Array> array = Array::New(2);
                                      ^
In file included from ../src/microtime.cc:1:0:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:2417:23: error:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’ [-fpermissive]
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../src/microtime.cc:77:30: error: no matching function for call to ‘v8::Integer::New(int)’
     array->Set(Integer::New(0), Uint32::New(t.tv_sec));
                              ^
../src/microtime.cc:77:30: note: candidate is:
In file included from ../src/microtime.cc:1:0:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/microtime.cc:77:53: error: no matching function for call to ‘v8::Uint32::New(__time_t&)’
     array->Set(Integer::New(0), Uint32::New(t.tv_sec));
                                                     ^
../src/microtime.cc:77:53: note: candidate is:
In file included from ../src/microtime.cc:1:0:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/microtime.cc:78:30: error: no matching function for call to ‘v8::Integer::New(int)’
     array->Set(Integer::New(1), Uint32::New(t.tv_usec));
                              ^
../src/microtime.cc:78:30: note: candidate is:
In file included from ../src/microtime.cc:1:0:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/microtime.cc:78:54: error: no matching function for call to ‘v8::Uint32::New(__suseconds_t&)’
     array->Set(Integer::New(1), Uint32::New(t.tv_usec));
                                                      ^
../src/microtime.cc:78:54: note: candidate is:
In file included from ../src/microtime.cc:1:0:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/microtime.cc:80:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(array);
                  ^
In file included from ../src/microtime.cc:1:0:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘void init(v8::Handle<v8::Object>)’:
/home/nodebot/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/microtime.cc:85:17: error: within this context
     HandleScope scope;
                 ^
../src/microtime.cc:87:39: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [4], v8::Handle<v8::Value> (&)(const int&))’
     NODE_SET_METHOD(target, "now", Now);
                                       ^
../src/microtime.cc:87:39: note: candidate is:
In file included from ../src/microtime.cc:2:0:
/home/nodebot/.node-gyp/0.12.0/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/nodebot/.node-gyp/0.12.0/src/node.h:228:13: note:   template argument deduction/substitution failed:
../src/microtime.cc:87:39: note:   cannot convert ‘Now’ (type ‘v8::Handle<v8::Value>(const int&)’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
     NODE_SET_METHOD(target, "now", Now);
                                       ^
../src/microtime.cc:88:51: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [10], v8::Handle<v8::Value> (&)(const int&))’
     NODE_SET_METHOD(target, "nowDouble", NowDouble);
                                                   ^
../src/microtime.cc:88:51: note: candidate is:
In file included from ../src/microtime.cc:2:0:
/home/nodebot/.node-gyp/0.12.0/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/nodebot/.node-gyp/0.12.0/src/node.h:228:13: note:   template argument deduction/substitution failed:
../src/microtime.cc:88:51: note:   cannot convert ‘NowDouble’ (type ‘v8::Handle<v8::Value>(const int&)’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
     NODE_SET_METHOD(target, "nowDouble", NowDouble);
                                                   ^
../src/microtime.cc:89:51: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [10], v8::Handle<v8::Value> (&)(const int&))’
     NODE_SET_METHOD(target, "nowStruct", NowStruct);
                                                   ^
../src/microtime.cc:89:51: note: candidate is:
In file included from ../src/microtime.cc:2:0:
/home/nodebot/.node-gyp/0.12.0/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/nodebot/.node-gyp/0.12.0/src/node.h:228:13: note:   template argument deduction/substitution failed:
../src/microtime.cc:89:51: note:   cannot convert ‘NowStruct’ (type ‘v8::Handle<v8::Value>(const int&)’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
     NODE_SET_METHOD(target, "nowStruct", NowStruct);
                                                   ^
make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
make: Leaving directory `/home/nodebot/etherpad-lite/src/node_modules/ueberDB/node_modules/helenus/node_modules/microtime/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodebot/IBMSVT32/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:268:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "node" "/home/nodebot/IBMSVT32/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodebot/etherpad-lite/src/node_modules/ueberDB/node_modules/helenus/node_modules/microtime
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

> ws@0.4.31 install /home/nodebot/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/nodebot/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/home/nodebot/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
npm WARN optional dep failed, continuing microtime@0.4.0
channels@0.0.4 node_modules/channels

security@1.0.0 node_modules/security

async-stacktrace@0.0.2 node_modules/async-stacktrace

slide@1.1.6 node_modules/slide

graceful-fs@3.0.5 node_modules/graceful-fs

tinycon@0.0.1 node_modules/tinycon

formidable@1.0.16 node_modules/formidable

async@0.9.0 node_modules/async

underscore@1.5.1 node_modules/underscore

languages4translatewiki@0.1.3 node_modules/languages4translatewiki

etherpad-require-kernel@1.0.8 node_modules/etherpad-require-kernel

unorm@1.3.3 node_modules/unorm

semver@4.2.0 node_modules/semver

measured@1.0.0 node_modules/measured
└── inherits@2.0.1

ejs@1.0.0 node_modules/ejs

resolve@1.1.0 node_modules/resolve

etherpad-yajsml@0.0.2 node_modules/etherpad-yajsml

log4js@0.6.22 node_modules/log4js
├── semver@1.1.4
├── async@0.2.10
└── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)

clean-css@3.0.8 node_modules/clean-css
├── commander@2.5.1
└── source-map@0.1.43 (amdefine@0.1.0)

supertest@0.15.0 node_modules/supertest
├── methods@1.1.1
└── superagent@0.21.0 (extend@1.2.1, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, qs@1.2.0, mime@1.2.11, debug@2.1.1, readable-stream@1.0.27-1, form-data@0.1.3, formidable@1.0.14)

uglify-js@2.4.16 node_modules/uglify-js
├── uglify-to-browserify@1.0.2
├── async@0.2.10
├── optimist@0.3.7 (wordwrap@0.0.2)
└── source-map@0.1.34 (amdefine@0.1.0)

connect@2.7.11 node_modules/connect
├── fresh@0.1.0
├── cookie-signature@1.0.1
├── pause@0.0.1
├── qs@0.6.5
├── buffer-crc32@0.2.1
├── bytes@0.2.0
├── cookie@0.0.5
├── debug@2.1.1 (ms@0.6.2)
├── send@0.1.1 (range-parser@0.0.4, mime@1.2.11)
└── formidable@1.0.14

request@2.53.0 node_modules/request
├── caseless@0.9.0
├── json-stringify-safe@5.0.0
├── forever-agent@0.5.2
├── aws-sign2@0.5.0
├── form-data@0.2.0
├── stringstream@0.0.4
├── oauth-sign@0.6.0
├── tunnel-agent@0.4.0
├── isstream@0.1.1
├── node-uuid@1.4.2
├── qs@2.3.3
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── mime-types@2.0.9 (mime-db@1.7.0)
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@0.9.4 (readable-stream@1.0.33)
├── tough-cookie@0.12.1 (punycode@1.3.2)
└── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.6.1, hoek@2.11.0)

mocha@2.1.0 node_modules/mocha
├── escape-string-regexp@1.0.2
├── diff@1.0.8
├── growl@1.8.1
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

jsonminify@0.2.3 node_modules/jsonminify

cheerio@0.18.0 node_modules/cheerio
├── dom-serializer@0.0.1 (domelementtype@1.1.3)
├── entities@1.1.1
├── htmlparser2@3.8.2 (domelementtype@1.1.3, domutils@1.5.1, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13)
├── CSSselect@0.4.1 (domutils@1.4.3, CSSwhat@0.4.7)
└── lodash@2.4.1

ueberDB@0.2.11 node_modules/ueberDB
├── channels@0.0.2
├── felix-couchdb@1.0.7
├── redis@0.12.1
├── dirty@0.9.9
├── async@0.1.15
├── mysql@2.5.5 (require-all@1.0.0, bignumber.js@2.0.0, readable-stream@1.1.13)
├── pg@4.3.0 (packet-reader@0.2.0, pg-connection-string@0.1.3, buffer-writer@1.0.0, generic-pool@2.1.1, pg-types@1.7.0, pgpass@0.0.3)
└── helenus@0.6.10 (node-uuid@1.3.3, helenus-thrift@0.7.4)

swagger-node-express@2.1.3 node_modules/swagger-node-express
└── lodash@1.3.1

wd@0.3.11 node_modules/wd
├── vargs@0.1.0
├── q@1.0.1
├── underscore.string@2.3.3
├── request@2.46.0 (caseless@0.6.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, qs@1.2.2, node-uuid@1.4.2, mime-types@1.0.2, form-data@0.1.4, bl@0.9.4, http-signature@0.10.1, tough-cookie@0.12.1, hawk@1.1.1)
├── lodash@2.4.1
└── archiver@0.12.0 (buffer-crc32@0.2.5, lazystream@0.1.0, readable-stream@1.0.33, tar-stream@1.0.2, glob@4.0.6, zip-stream@0.4.1)

socket.io@1.3.3 node_modules/socket.io
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── debug@2.1.0 (ms@0.6.2)
├── socket.io-parser@2.2.3 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
├── engine.io@1.5.1 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.1, ws@0.5.0)
└── socket.io-client@1.3.3 (to-array@0.1.3, indexof@0.0.1, component-bind@1.0.0, debug@0.7.4, backo2@1.0.2, object-component@0.0.3, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.1)

express@3.8.1 node_modules/express
├── parseurl@1.0.1
├── merge-descriptors@0.0.2
├── debug@0.8.1
├── cookie@0.1.2
├── cookie-signature@1.0.3
├── range-parser@1.0.0
├── fresh@0.2.2
├── buffer-crc32@0.2.1
├── methods@1.0.0
├── commander@1.3.2 (keypress@0.1.0)
├── send@0.3.0 (debug@0.8.0, mime@1.2.11)
├── proxy-addr@1.0.0 (ipaddr.js@0.1.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
└── connect@2.17.3 (response-time@1.0.0, pause@0.0.1, method-override@1.0.2, connect-timeout@1.1.0, qs@0.6.6, basic-auth-connect@1.0.0, vhost@1.0.0, bytes@1.0.0, on-headers@0.0.0, morgan@1.1.1, serve-favicon@2.0.0, errorhandler@1.0.1, serve-static@1.1.0, cookie-parser@1.1.0, express-session@1.2.1, body-parser@1.2.2, csurf@1.2.0, type-is@1.2.0, compression@1.0.2, serve-index@1.0.3, multiparty@2.2.0)

npm@2.4.1 node_modules/npm
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-02-25 00:21:15.843] [WARN] console - You need to set a sessionKey value in settings.json, this will allow your users to reconnect to your Etherpad Instance if your instance restarts
[2015-02-25 00:21:15.847] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
[2015-02-25 00:21:17.554] [INFO] console - Installed plugins: ep_etherpad-lite
[2015-02-25 00:21:17.591] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2015-02-25 00:21:17.592] [INFO] console - Your Etherpad git version is 768b012
[2015-02-25 00:21:17.859] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2015-02-25 00:21:17.859] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
[2015-02-25 00:22:23.984] [INFO] access - [CREATE] Pad "svt": Client H_BqQBc7X4ZU37q8AAAA with IP "9.23.34.6" created the pad
[2015-02-25 00:23:02.571] [INFO] access - [ENTER] Pad "svt": Client w2CZJtg6q-83qNgZAAAB with IP "9.23.34.6" entered the pad
[2015-02-25 00:23:41.664] [INFO] access - [ENTER] Pad "svt": Client zhC33AiVhTYYVEdWAAAC with IP "9.23.34.6" entered the pad

**Comment by JohnMcLear** [comment]
It is supported on develop we just haven't "released" a version that is.  Feel free to read the release guide and prepare a release for us to publish :)

**Comment by smartmouse** [comment]
Thank you so much for your prompt reply.
