### ISSUE TITLE
Error when requireSession is set to true.

### ISSUE THREAD

**Issue by Sergio3** [ether/etherpad-lite#2536]
Hello guys,
When requireSession is set to true, then the next message appears when I want to edit a path.

"requireSession" : true Error: The module at "ep_etherpad-lite/static/js/pad.js" does not exist. in static/js/require-kernel.js at line 588'

Ideas?

Thank you very much!

**Comment by tombriles** [comment]
This is happening to me as well.

It only seems to occur directly after an 'Authentication try failed' message, so it isn't a huge deal (though the 'pad.permissionDenied' error would of course be preferable).

I'm on etherpad-lite v1.5.1, running on CentOS 6, node v0.10.28.

Let me know if you'd like any additional info.

**Comment by JohnMcLear** [comment]
I feel like this is fixed on develop, please try the develop branch and let me know.

**Comment by tombriles** [comment]
Thanks for the quick response!

It is indeed fixed on develop.

Is there an ETA for a new tagged version?

**Comment by Sergio3** [comment]
Thanks a lot!! I will be aware for the new fixed version.

**Comment by JohnMcLear** [comment]
@tombriles whenever someone does a release really, possibly when we meet in April or so..  I'd take a pull request with a release in if you wanted to go ahead and do it :)  https://github.com/ether/etherpad-lite/wiki/Release-procedure is the release procedure.
