### ISSUE TITLE
Preserve color between sessions.

### ISSUE THREAD

**Issue by Sergio3** [ether/etherpad-lite#2537]
I don't know if this is an issue, but when a user close his session (without close the navigator) and then access again to the etherpad-lite, a new color appears. I would be great to preserve the color between sessions at least until user close the navigator.

I'm using the ep_ldapauth to access etherpad.

Good job guys!!! Thanks a lot!!

**Comment by JohnMcLear** [comment]
I think this "might" already be the expected behavior..

Read your warning messages when you start Etherpad :)   Do you see any?

**Comment by Sergio3** [comment]
Thanks for the fast response, you know if there is a plugin to do this? I mean, remember the color until the session cookie is deleted. If not, in what files is the code who manage colors?

**Comment by JohnMcLear** [comment]
You are missing the point here, this is already the behaviour.  Read the messages that you see when you start Etherpad.
