### ISSUE TITLE
The parameter has a different name than the documentation

### ISSUE THREAD

**Issue by cristo-rabani** [ether/etherpad-lite#2543]
collectContentPre#

Called from: src/static/js/contentcollector.js

Things in context:

cc - the contentcollector object
state - the current state of the change being made
tname - the tag name of this node currently being processed
style - the style applied to the node (probably CSS) <----here
cls - the HTML class string of the node

```
hooks.callAll('collectContentPre', {
                        cc: cc,
                        state: state,
                        tname: tname,
                        styl: styl,   <----here
                        cls: cls
                    });
```

**Comment by JohnMcLear** [comment]
Yea the documentation will need to be updated to reflect OR we will need to duplicate the object to include both styl and style..  ;\  Duplication is probably the best way sadly..  We have no way to throw a warning on deprecated attribute usage either, I guess some sort of Etherpad plugin helper might be useful for this type of issue..

**Comment by sunilkumarc** [comment]
Why can't we just update the document ? That would be the easiest way and I don't see anything wrong in doing that.

**Comment by JohnMcLear** [comment]
Won't people already be using styl if it's currently named that or is it only the docs that have it wrong?

**Comment by sunilkumarc** [comment]
I'm sorry. I think I haven't understood the issue clearly. Can you explain a little bit more about the issue ?

**Comment by JohnMcLear** [comment]
Fixed.
