### ISSUE TITLE
Etherpad import problem

### ISSUE THREAD

**Issue by SherifSobhy** [ether/etherpad-lite#2544]
Hi All,
I'm using etherpad and i installed it Linux I'm also installed abiword and set the abiword url to my abiword exe ,
when I'm trying to import any file it make a postback without any changes check my error on my Linux server
![1](https://cloud.githubusercontent.com/assets/11437660/6614557/4762bdd6-c8a4-11e4-9b25-db455cd3dd16.png)

**Comment by JohnMcLear** [comment]
I assume you are using other plugins?  That error is due to malformed HTML from (probably) a plugin.
