### ISSUE TITLE
Nginx SSL, 502 Bad Gateway, Most Plugins

### ISSUE THREAD

**Issue by Flauschie** [ether/etherpad-lite#2545]
I have an etherpad instance running in a virtual machine running debian wheezy.
The pad is working fine with either the /pad/p/ subdirectory nginx rule and the usual /p/ running SSL.

My problem is, with either /pad/ or /p/ I get an 502 Bad Gateway exception with most of the plugins... I know that some time ago you had to rewrite rules / or plugins if you want to run an ssl etherpad. Is this still the case?

This is my current usual /p/ rule. How can I fix this? EP is running fine on my server (Powered by Etherpad-lite on node.js (git revision 56dbad)) except that most of the plugins are rewritten for the https issue and /pad/ issue.... Also, most plugins are outdated and throw errors.

Thats why I wanted to update all plugins and revert back to a standard ssl nginx configuration without using subdirs (I would create a subdomain for etherpad) ...

```
    server {

            listen  443 ssl;
            server_name  etherpad.dev;

            ssl_certificate /etc/ssl/certs/localhost.pem;
            ssl_certificate_key /etc/ssl/private/localhost.pem;

	        access_log  /var/log/nginx/eplite.access.log;
        error_log   /var/log/nginx/eplite.error.log;

        location / {
            proxy_pass             http://localhost:9001/;
            proxy_set_header       Host $host;
            proxy_pass_header Server;
            # be carefull, this line doesn't override any proxy_buffering on set in a conf.d/file.conf
            proxy_buffering off;
            proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
            proxy_set_header Host $host;  # pass the host header                                                   
            proxy_http_version 1.1;  # recommended with keepalive connections                                                    
            # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

        }
}

# we're in the http context here
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

server {
    listen      80;
    server_name etherpad.dev;
    rewrite     ^(.*)   https://$server_name$1 permanent;
}

```

**Comment by JohnMcLear** [comment]
Report the problem to the plugin repositories.

**Comment by Flauschie** [comment]
So you say the rule is fine?

**Comment by JohnMcLear** [comment]
I didn't say that at all, I said this is the wrong place to report plugin issues.

**Comment by Flauschie** [comment]
But outgoing from this error it is related to socket.io, isn't it?
So it could be an nginx problem, too. I don't know, thats why I am asking here...

And tbh, i doubt these plugins are maintained and controlled as this repository, thats why I asked here, first. There are several nginx rules, somehow mixed up for me in the wiki... maybe I forgot something, I just don't know... And I doubt someone at nginx forums/support whatever would help me if there is an etherpad community/git ...

Sorry for bothering you

**Comment by JohnMcLear** [comment]
@Flauschie Like I said...  Post on the plugin repos

**Comment by Flauschie** [comment]
I will... in nearly every single one :)
