### ISSUE TITLE
Can't cut text

### ISSUE THREAD

**Issue by lid2000** [ether/etherpad-lite#2546]
This has happened recently and I suspect it is something to do with the changes in #2533. It seems that cutting text, while it still removes it from the pad, no longer places it in the clipboard. Copying still works fine, and as a workaround people can just do copy + delete.

If I comment out the `$(document).on("cut", handleCut);` line from js/static/ace2_inner.js (which was added in #2533) then everything works again.

Steps to reproduce:

1. Go to beta.etherpad.org and make a new pad.
2. Hit Ctrl+A to select everything, then Ctrl+X to cut.
3. Try using Ctrl+V to paste and either nothing will happen if the clipboard is empty, or if the clipboard had something in it before cutting then that will end up being pasted.

I'm using Firefox 36.0.1 on Windows 7 x64, however the problem also exists in Firefox on MacOS, and I can reproduce it in Chrome as well (Chrome seems to paste whatever was in the clipboard *before* cutting though).

**Comment by JohnMcLear** [comment]
$(document).on("cut", handleCut);

shouldn't prevent default behavior..  

Does changing the function to below help?

```
function handleCut(evt){
  inCallStackIfNecessary("handleCut", function()
  {
    doDeleteKey(evt);
  });
  return true;
}
```

**Comment by lid2000** [comment]
Yep, it seems to work with that change.

**Comment by JohnMcLear** [comment]
Wanna send a pull request through with that change in please?

**Comment by Flauschie** [comment]
Doesn't fix this for me. edited src/static/js/ace2_inner.js to 

```
function handleCut(evt){
  inCallStackIfNecessary("handleCut", function()
  {
    doDeleteKey(evt);
  });
  return true;
}
```

**Comment by JohnMcLear** [comment]
This issue still exists in develop

**Comment by JohnMcLear** [comment]
@cjb I'm away this week so wont get chance to take a look, dya wanna take a look at this please?

**Comment by lid2000** [comment]
Huh. Weird. I am certain the above change fixed the problem the other day (the people complaining said it was all good now) yet checking it again it appears it isn't fixed after all. Sorry for the false confirmation.

**Comment by cjb** [comment]
@JohnMcLear Just took a look and can't figure out what's wrong here -- I don't see anywhere we're hitting preventDefault.  :/

**Comment by JohnMcLear** [comment]
Yeah I don't see preventDefault firing, confuses me too.  You want me to see if I can get it sorted?

**Comment by cjb** [comment]
Yes please!

**Comment by JohnMcLear** [comment]
For now I disabled the handleCut event..  I delved further into the code around inCallStack and I'm guessing a return false is coming from there for the event and this is stopping the clipboard from getting the contents on a cut event..  It needs further time though, more than I have today..  @cjb back over to you if you have some ideas -_-

**Comment by JohnMcLear** [comment]
Closing this and re-opening the original issue from cjb
