### ISSUE TITLE
Internet Explorer 11 Compatibility Mode

### ISSUE THREAD

**Issue by danyill** [ether/etherpad-lite#2547]
I've deployed node.js, npm and ethernet on Debian Wheezy. When accessing the base page by Google Chrome on Windows 7 Ultimate, all functionality works fine. I can create new pads and join existing pads.

When accessing an existing pad via Internet Explorer 11 on Windows 7 Ultimate I get an error message, "An error occured while loading the pad Expected identifier, string or number in http://***name removed***:9001/static/js/require-kernel.js (line 226)"

When accessing the base page via IE11, I get banded lines with no information, see below:

![banded_lines](https://cloud.githubusercontent.com/assets/674783/6632031/b1c6b344-c994-11e4-9490-79ced359a5ec.png)

When I open this up in the debugger, it indicates 'JSON is undefined' in html10n.js. Refer the image below.

![html10n](https://cloud.githubusercontent.com/assets/674783/6631927/f9b0bc4c-c992-11e4-8a53-1b54f0d53729.png)

I noticed in IE11 that compatibility mode is enabled for this site. When I remove compatibility mode, the site loads correctly.

No errors are shown in the console log when I start with ./bin/run.sh --root for this event. I am using the "dirty db".

Is it possible to make etherpad work for IE 11 compatibility mode?

npm --version
2.7.0

nodejs --version
v0.10.36

**Comment by JohnMcLear** [comment]
Do you get this issue if you visit http://beta.etherpad.org ?

**Comment by danyill** [comment]
Yes, if I add it to compatibility mode.
![compatibility_mode](https://cloud.githubusercontent.com/assets/674783/6657735/27056b48-cbb9-11e4-9b6c-f935bc483203.png)
![etherpad_on_beta_site](https://cloud.githubusercontent.com/assets/674783/6657736/2b8475e2-cbb9-11e4-9019-e90ba67906a1.png)

**Comment by JohnMcLear** [comment]
@eldiddio found when visiting http://beta.etherpad.org using IE11 v11.0.9600.17631 running Windows 8.1 everything worked as expected.

**Comment by JohnMcLear** [comment]
Closing due to lack of update from OP.

**Comment by danyill** [comment]
Not sure what update I could provide here? Seems like Mar 17 post above confirmed the behaviour.

**Comment by JohnMcLear** [comment]
It should be fixed now
----- Reply message -----

**Comment by danyill** [comment]
Thanks very much John for looking into this and applying a fix. 

I have done 'git pull origin', shut down the service and restarted using run.sh as the root user. The behaviour seems the same as that reported above (i.e. with compatibility mode I do not get a site displayed, just banded lines on the etherpad home page).

Should I be concerned about unmet dependencies (I seem to have many newer versions of modules than etherpad-lite requires)? A log from running run.sh can be found here: http://pastebin.com/x0UKZnfB

With compatibility mode on I am able to load the home page but I get an error when I click create new pad:
![untitled](https://cloud.githubusercontent.com/assets/674783/7305897/9784a6ee-ea55-11e4-8a3b-d82f7e6dbf5a.png)

This is different behaviour to what I get if I open https://beta.etherpad.org/ in compatibility mode. I get the text box for new pad, the OK button and a dark band *without* the words 'New Pad'.

![untitled2](https://cloud.githubusercontent.com/assets/674783/7305943/e92f3ff4-ea55-11e4-9479-a2a59f1446e7.png)

When I click new pad I receive a different error to that above:

![untitled3](https://cloud.githubusercontent.com/assets/674783/7305952/0d5a6264-ea56-11e4-8172-983f90826c22.png)

Unfortunately this upgrade has also resulted in etherpad-lite not working in Chrome. The home screen loads fine. When I click 'New Pad' the screen displays one error and then another, screenshots for both below:

![untitled4](https://cloud.githubusercontent.com/assets/674783/7306138/273837aa-ea57-11e4-9f69-055b888ed67c.png)
![untitled5](https://cloud.githubusercontent.com/assets/674783/7306139/2739d59c-ea57-11e4-8595-69488a4f328d.png)

I am able to load beta.etherpad.org in Chrome without any problems.

Possibly these errors are caused by lack of appropriate dependencies? Happy to provide more information.

**Comment by JohnMcLear** [comment]
Clean your installation deps.
``
`rm -rf src/node_modules
bin/run.sh
```

@eldiddio can you please confirm if compat mode breaks EP?

**Comment by JohnMcLear** [comment]
(!img)[http://memecrunch.com/meme/3FNP1/ie-compatibility-mode/image.jpg?w=450&c=1]

**Comment by danyill** [comment]
Thank you very much. I confirm that the latest github pull solves this issue.
