### ISSUE TITLE
Plugin for highlighting (single text background color option, not syntax highlighting)

### ISSUE THREAD

**Issue by nouyang-curoverse** [ether/etherpad-lite#2555]
I like tomboy note's highlight feature "puts a yellow background around the selected text." Any chance a plugin for this could be written?

(I always have authorship colors turned off -- if authorship colors are turned on, maybe the yellow highlighter just goes away).

**Comment by JohnMcLear** [comment]
See the comments plugin?

On 18 Mar 2015 18:37, nouyang-curoverse <notifications@github.com> wrote:

I like tomboy note's highlight feature "puts a yellow background around the selected text." Any chance a plugin for this could be written?

(I always have authorship colors turned off -- if authorship colors are turned on, maybe the yellow highlighter just goes away).

**Comment by nouyang-curoverse** [comment]
Oh, fascinating, I hadn't thought about using "comments" that way. Obviously not ideal from a UI perspective (I'd imagine something more like clicking the "bold" button, but for "highlight"), and also doesn't show up in the Export to HTML, which is what I care about. I was hoping someone had a "quickfix" solution, and if not I'll might dig around the source code for these plugins in a few weeks. Thanks!

**Comment by JohnMcLear** [comment]
@nouyang-curoverse Doing what you want will take a matter of minutes as a plugin..  Just take any plugin and modify it to apply the styling you need..  I'd suggest you call the plugin something like "Quick highlighting"..  If you want I can probably bash this plugin out in an hour if you want to use me as a gun for hire.

**Comment by nouyang-curoverse** [comment]
@JohnMcLear  I feel meh about pulling out cash for learning to write etherpad-lite plugins (and it's not a feature I actually need at all), but happy to trade hardware (meche/ee) expertise if you feel inclined anyway to write a plugin + document it as a Real-Life Example at https://github.com/ether/etherpad-lite/wiki/Creating-a-plugin (as a more useful example than the otherwise excellent https://github.com/ether/etherpad-lite/wiki/Creating-a-plugin#creating-your-first-plugin).

Otherwise, we can both just backlog this feature request ^^
