### ISSUE TITLE
[Bug] Error in AttributeManager.toggleAttributeOnLine()

### ISSUE THREAD

**Issue by tm-linkwerk** [ether/etherpad-lite#2556]
The toggle function does not work properly for me. 

The reason seems to be that this call: https://github.com/ether/etherpad-lite/blob/develop/src/static/js/AttributeManager.js#L198
should be 
`this.getAttributeOnLine(lineNum, attributeName)`

**Comment by JohnMcLear** [comment]
Yea it should be, please submit a PR with that fix =)
