### ISSUE TITLE
Case sensitive url-paths creates out of sync pads.

### ISSUE THREAD

**Issue by DjSlash** [ether/etherpad-lite#2557]
This brought us some confusion, while our team was working on planning some stuff. We discovered that entering a pad with lowercase characters in the url, it creates the same pad as with uppercase characters in the url - but as an entirely different instance of that pad. And it works the other way around also. We would expect that case sensitivity does count, but then that the non-existingpad would be entirely new and not a new-made copy.

To demonstrate, I've created http://pad.nllgg.nl/p/test first and later http://pad.nllgg.nl/p/Test

I've switched from develop to master (git version b9cdf43) branch to no avail. This instance is behind a Apache proxy, but I've also tried it directly. npm version is 2.5.1, node version is 0.12.0. Installed plugins: ep_adminpads, ep_etherpad-lite, ep_headings, ep_ruler, ep_author_hover

**Comment by webzwo0i** [comment]
additional notes:
If collation on column store.key is case-sensitive then a new pad with different case should result in a completely new pad. 
If collation on column store.key is case-insensitive it should ignore any case in the padids.

I tried with case-insensitive and all database values are fine, however clients connected to one pad don't receive updates from the pads that have another case. I suppose this means, clients are connected to different rooms depending on case.

**Comment by webzwo0i** [comment]
Thinking about this a little bit more:
- need to find out what all the different databases that are supported by ueberDB do (the mysql-tutorial says you should use case-sensitive collation)
- need to find a good way to migrate databases from a wrong setting to a setting that is supported and works (if we support both, then we need to fix pads on sensitive->insensitive transition and store.keys on insensitive->sensitive transition)

**Comment by JohnMcLear** [comment]
Do you have any changes to your settings.json ?
----- Reply message -----

**Comment by DjSlash** [comment]
From switching branches, I didn't. I have recently updated the settings according to the template. Below my current settings.

```
{
        "title": "NLLGG Etherpad",
        "favicon": "favicon.ico",
        "ip": "---",
        "port" : 9001,
        "sessionKey" : "---",

        "dbType" : "mysql",
        "dbSettings" : { 
                "user"    : "---", 
                "host"    : "localhost", 
                "password": "---", 
                "database": "etherpad"
        },  

        "defaultPadText" : "", 
        "requireSession" : false,
        "editOnly" : false,
        "sessionNoPassword" : false,
        "minify" : true,
        "maxAge" : 21600, 
        "abiword" : "/usr/bin/abiword",
        "allowUnknownFileEnds" : true,
        "requireAuthentication": false,
        "requireAuthorization": false,
        "trustProxy" : true,
        "disableIPlogging" : false,  
        "users": {
                "me": {
                        "password": "---",
                        "is_admin": true
                }   
        },  
        "socketTransportProtocols" : ["xhr-polling", "jsonp-polling", "htmlfile"],
        "loglevel": "INFO",

        "logconfig" :
        { "appenders": [
                { "type": "console"
                },  
                { "type": "file"
                        , "filename": "etherpad.log"
                        , "maxLogSize": 10240
                        , "backups": 3 
                }   
        ] } 
}
```

**Comment by JohnMcLear** [comment]
Try the database as another database, I have a feeling your issue is due to mysql.

**Comment by JohnMcLear** [comment]
I'm unable to replicate this on beta.etherpad.org

https://beta.etherpad.org/p/FOORA
https://beta.etherpad.org/p/foora

Have different content..

And updates are not shared...

**Comment by JohnMcLear** [comment]
I'm also unable to replicate this locally w/ MySQL set to UTF8_bin..

Can someone please provide steps to replicate this issue?

**Comment by DjSlash** [comment]
@JohnMcLear Are you saying this issue is depending on the mysql-db configuration? Sounds weird, as long as collation is set to an case insensitive, it would not make a difference, right?

**Comment by DjSlash** [comment]
Actually, reading into it, I see that it just as well might. But then again, the ```value``` column is set to utf8_bin also.

**Comment by JohnMcLear** [comment]
Well once it's wrong, it's wrong.  One assumes the Etherpad MySQL guide wasn't properly followed during installation :|

Any pads created while it's broken will be broken, I can't think of an easy fix.

This really ties into our check we need for UTF8 afaik @webzwo0i is working hard at getting a fix in ASAP so when mistakes are made we catch them.

**Comment by dcht00** [comment]
Oh hai, came here to report this issue and found this thread.
My collation is, for some reason, also "latin1_swedish_ci". In my install notes I've marked the need to change to UTF8... Maybe I was sloppy.
(Using Mysql on Ubuntu + latest Etherpad version.)
