### ISSUE TITLE
How to test if an attribute is set at a range

### ISSUE THREAD

**Issue by tm-linkwerk** [ether/etherpad-lite#2558]
Hi,

I want to find out if an attribute is set at a certain range (in my case the selected text). 

There is a function `editorInfo.ace_getAttributeOnSelection(attributeName)` which name suggests that it should solve my problem but (seems to) return true only if the value of the attribute is true, and false otherwise. 

How can I get the information if an attribute is set to any value? Or even better, get a list of all attributes that are set to any value on a specified range?

**Comment by JohnMcLear** [comment]
You can do it on the caret location/selected range such as this: 
https://github.com/JohnMcLear/ep_font_size/blob/master/static/js/index.js#L63

This will return the value of the attribute IE if you want the font size of this selection it will return the integer associated with that font size, not just a boolean..

There isn't a way to get a list of all attributes on a specified range at current.  I'd welcome this functionality though =)

**Comment by tm-linkwerk** [comment]
That's the way I tried it, but got only boolean values, and looking at the source code of the function https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L2325 I also only found boolean returns.

**Comment by JohnMcLear** [comment]
Try ``console.log`` what the ep_font_size plugin gets, use it as a point of reference.

**Comment by tm-linkwerk** [comment]
The ep_font_size plugin uses only boolean values for attributes (like fs12=true) so it is not affected by the problem.

**Comment by JohnMcLear** [comment]
I'd agree that hooks such as ``getAttributeValueOnSelection`` and ``getAttributesOnSelection`` would be useful if you wanna craft those in?

**Comment by tm-linkwerk** [comment]
For a given position it turned out to be not as difficult to implement as suspected. So I added the function to the AttributeManager and created a pull request. 

But for a range, after thinking about it, I am not yet sure, what a function should reasonably return if the selected range overlaps attributes. So maybe I come back to this point later.

**Comment by JohnMcLear** [comment]
Cool thanks :)
