### ISSUE TITLE
Insert Character in formatted text

### ISSUE THREAD

**Issue by tm-linkwerk** [ether/etherpad-lite#2562]
When I apply an attribute to a selected text, then click somewhere into this text and type another character, this charater does not get applied the surrounding attribute. Instead the surrounding attribute is split into two attributes and the new character lies in between them.

I looked at what other plugins did: they use the collectContentPre-hook and call context.cc.doAttrib(state, attributeName) to apply the attribute to the new text. The downside of this approach is, that there seems to be no way to apply attribute values (the given attribute is just set to true). 

Can't you just tell etherpad for new characters to apply the surrounding attributes, what I think should be the expected behaviour for most use cases?

**Comment by JohnMcLear** [comment]
registerBlockElements is responsible for handling this, please take some time to look through some of the plugins I have written! :) Thanks!

**Comment by tm-linkwerk** [comment]
Hmm, that does not work for me.

*aceRegisterBlockElements
The return value of this hook will add elements into the "lineMarkerAttribute" category, making the aceDomLineProcessLineAttributes hook (documented below) call for those elements.*

This seems to adress only block/line attributes, I'm looking for something that handles inline attributes.

**Comment by JohnMcLear** [comment]
inline attributes are block attributes.

Try it on ep_font_size you will see it functioning properly.

**Comment by tm-linkwerk** [comment]
With inline attributes I mean an attribute that is applied to e.g. just a word of a line. A line or block attribute in my view refers to the whole line (e.g. a heading, list) and needs the whole line marker thing (* and so on). Is my view false?

My problem refers to the first case, aceRegisterBlockElements to the latter. 

Now I tried it with ep_font_size: If I remove the function aceRegisterBlockElements from the code, everything I see still works. But if I uncomment the line context.cc.doAttrib(...) in shared.js (https://github.com/JohnMcLear/ep_font_family/blob/master/static/js/shared.js#L8), it doesn't work anymore. So this function call must be responsible for the desired behaviour, but unfortunately I cannot apply it to my use case, because I have key-value-attributes.

**Comment by JohnMcLear** [comment]
Bummer ;( try to make your logic apply the same as font size then?
