### ISSUE TITLE
What does the embed parameter showControls do?

### ISSUE THREAD

**Issue by chaodoze** [ether/etherpad-lite#2563]
It doesn't seem to do anything for me. Thanks!

**Comment by JohnMcLear** [comment]
Controls is the editbar.  https://beta.etherpad.org/p/foo?showControls=false  - it looks like it's broken ;\

**Comment by chaodoze** [comment]
Thanks, John. I just figured that out by looking at the source. It looks like $('#editbar').show() is called after the parameter arguments are processed (in line#158 static/js/pad_editbar.js). 

The next line then calls hooks.callAll("postToolbarInit"...). I'm not familiar enough with the source: Is there a way to subscribe to the "postToolbarInit" event, and then call $('#editbar').hide() when that event is fired?

**Comment by JohnMcLear** [comment]
I need to fix the bug, sit tight

**Comment by JohnMcLear** [comment]
Bug fixed.
