### ISSUE TITLE
username/author set from authentication plugin

### ISSUE THREAD

**Issue by nebulade** [ether/etherpad-lite#2564]
Is there a way to set the username/author from an authentication hook plugin?
The username in the webaccess.js does not seem to be used any further to get some clue.

**Comment by JohnMcLear** [comment]
Yes, this plugin does this, use it as a reference point: https://github.com/tykeal/ep_ldapauth/blob/master/ep_ldapauth.js

**Comment by nebulade** [comment]
Perfect, thanks!
