### ISSUE TITLE
Enable contentcollector to write key-value attributes

### ISSUE THREAD

**Issue by tm-linkwerk** [ether/etherpad-lite#2567]
After finding no solution to #2562 I digged a bit deeper into contentcollector and I think I found a way to solve the problem.

I am writing a plugin that enables the user to apply font-attributes to selected text. The attributes are stored as key=value and differs in that way of other plugins that store them as key-value=true or key:value=true. I guess these plugins to so because of the following problem:

The problem is (according to my current understanding): after every keystroke that changed the document the contentcollector is called and for every node it calls the hook "collectContentPre". If not explicitly handled by the plugin developer, every new character is assumed to have no attributes (beside author). I would have expected the default behaviour to have new characters to assign the attributes of the surrounding range. Instead the surrounding attribute is split into two attributes and the new character lies in between them.

To address this problem, existing plugins hook in collectContentPre, check for the right node, and then call the function context.cc.doAttrib(state, "attribName") what makes the contentcollector to apply attribName=true to handled node. For example (ep_font_size), this assigns the attribute fs12=true:

https://github.com/JohnMcLear/ep_font_size/blob/master/static/js/shared.js#L8

There seems to be no other api call, that enables one assigning an attribute fs=12. So I tried to understand contentcollector to find a way to handle this problem. I found this function where the attributes are set: https://github.com/ether/etherpad-lite/blob/develop/src/static/js/contentcollector.js#L293 

`var a` is the attributeName the plugin developer had sent to doAttrib(). This is the point where we could do a little refactoring based on a convention, which says that we split attributeNames at one or more certain character, like fs:12 or fs::12 (to avoid breaking existing plugins). The refactoring would replace ` lst.push([a, 'true']);` with the following:

`
if (a.split("::").length > 1) { 
    lst.push([a.split("::")[0], a.split("::")[1]); 
} else { 
    lst.push([a, 'true']); 
}
`

If there are no concerns or other suggestions I would supply a pull request.

The other possibility I see is a major refactoring of state.attribs in contentcollector to hold key-value pairs what would be a lot bigger issue, especially when we want to keep the current api working to not break existing plugins.

**Comment by JohnMcLear** [comment]
Seems logical to me.
