### ISSUE TITLE
Copy-paste sometimes stops working

### ISSUE THREAD

**Issue by nouyang-curoverse** [ether/etherpad-lite#2569]
I and a few other people in my lab have noticed issues with copy-pasting in etherpad. At first, ctrl-c ctrl-v works fine. But then it stops working entirely, or starts to lose formatting, and then middle-click sometimes works, but not always. Refreshing usually fixes it for me, but it is kind of annoying since sometimes it happens a few times a minute.

I'll try to collate reports / system specs from my lab, and attempt to reliably replicate the bug if I have some time in the future, but perhaps other users can chime in.

Otherwise, we're really enjoying etherpad-lite, so thanks!

_System details (for me)_
Chrome, Ubuntu 14.10

_Etherpad Git Commit_
6c933a1

_Installed plugins_
ep_comments_page
ep_etherpad-lite, ep_headings2, ep_markdown

_Installed parts_
ep_markdown/markdown
ep_headings2/main
ep_etherpad-lite/swagger
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/padreadonly
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/static
ep_etherpad-lite/express
ep_etherpad-lite/webaccess
ep_comments_page/comments_page

Edit: http://lightning-dev4.curoverse.com/pad/ if you want to try out my installation -- I haven't installed the "show all pages" plugin, so please don't go crazy on it.

**Comment by JohnMcLear** [comment]
Thanks, keep us posted on:

a) Environment
b) How to replicate
c) Any errors in console

Cheers


J

**Comment by RubenKelevra** [comment]
Copy n Paste seems to work only in 1.5.2 in 1.5.7 is it nearly completly broken. I had to downgrade my pad, please fix it!

In the ctrl+v the text appears but it seems that the server connection is never been notified by the change, and any following one. So the text and any following changes will be lost.

**Comment by JohnMcLear** [comment]
Same on beta.etherpad.org ?
----- Reply message -----

**Comment by JohnMcLear** [comment]
Seems to be fixed.
