### ISSUE TITLE
Error after import file

### ISSUE THREAD

**Issue by daicaca311** [ether/etherpad-lite#2570]
I'm using etherpad.
I config etherpad in nginx with /pad
The link when i created new etherpad is http://localhost/pad/p/cvcvcv
But after i imported a text file. The link of etherpad missing pad in url:  http://localhost/p/cvcvcv And it make me stuck.

Is that the error?

**Comment by JohnMcLear** [comment]
Sounds like a bug with the URL rewrite after importing.

**Comment by daicaca311** [comment]
Here is my ngnix config:

        location /pad {
        rewrite                /pad/(.*) /$1 break;
        rewrite                ^/pad$ /pad/ permanent;
        proxy_pass             http://localhost:9001/;
        proxy_pass_header Server;
        proxy_redirect         / /pad/;
        proxy_set_header       Host $host;
        proxy_buffering off;
        }
Could you tell me where is the URL rewrite after importing?

**Comment by daicaca311** [comment]
+ After import file ,etherpad call switchToPad from pad.js (etherpad server src)

switchToPad: function(padId)
  {
    var options = document.location.href.split('?')[1];
    var newHref = "/p/" + padId;
    if (options != null)
      newHref =  newHref + '?' + options;

    if(window.history && window.history.pushState)
    {
      $('#chattext p').remove(); //clear the chat messages
      window.history.pushState("", "", newHref);      
      receivedClientVars = false;
      sendClientReady(false, 'SWITCH_TO_PAD');
    }
    else // fallback
    {
      window.location.href = newHref;
    }
  },
This make a wrong URL

Solution now:
I've changed:
 var newHref = "/p/" + padId;
To
 var newHref = "/etherpad/p/" + padId;

This should be fixed from etherpad server

**Comment by JohnMcLear** [comment]
Well your solution is wrong too..

Try this..

``document.location.href.split('?')[1];`` should be 

```
var newHref = new RegExp(/.*\/p\/[^\/]+/).exec(document.location.pathname) || clientVars.padId;
newHref = newHref[0];
```

Try that and let me know.

**Comment by daicaca311** [comment]
Your case 1 work fine. Thank you

This should apply to the code

**Comment by JohnMcLear** [comment]
@daicaca311 you wanna open a pull request with the fix in?
