### ISSUE TITLE
b.dropdowns is undefined in pad.js

### ISSUE THREAD

**Issue by LucasCioffi** [ether/etherpad-lite#2577]
Hello, any suggestions for how I should start troubleshooting the following error message?  I can't replicate it, but it happened to a user of mine several times.

Please  press and hold Ctrl and press F5 to reload this page, if the problem  persists please send this error message to your webmaster: 
	'ErrorId: CRSwQiPYBoRXzf3ytUrs
	URL:   http://my-url.com?showControls=true&showChat=true&showLineNumbers=true&useMonospaceFont=false
	UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:36.0) Gecko/20100101 Firefox/36.0
	TypeError:  b.dropdowns is undefined in  http://my-url.com/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define  at line 15'

**Comment by JohnMcLear** [comment]
Try a clean install
----- Reply message -----
