### ISSUE TITLE
"Loading" in Chrome

### ISSUE THREAD

**Issue by LucasCioffi** [ether/etherpad-lite#2578]
Hello,

For one of my users on Chrome, the "Loading" message on the pad doesn't go away and it looks like it never fully loads to the point where he can start typing.

The pad works when he goes to Safari.  I cannot replicate this on my system, however.

Any suggestions for what might be the cause or what I should look into?

Thank you!

**Comment by JohnMcLear** [comment]
Look in the JavaScript console please

What is your etherpad git commit sha?

----- Reply message -----

**Comment by LucasCioffi** [comment]
John, by the way, I love Etherpad-Lite.  Thanks so much for steering the ship all these years.

1. I'll get back on this thread when I can get the JS console info from the user.  I can't make this happen on my system so this will take a few days.

2. I'm not familiar with SHA, but I looked up what to do here: http://git-scm.com/book/en/v2/Git-Internals-Git-Objects

I typed this into the console:
➜  find .git/objects -type f

and these are the last few lines of the output:
.git/objects/fa/2ecc9cef340e56c8948ae78ba1515c0c821cd0
.git/objects/fa/422e6dc2d6a13df04a14b8766eae58f1469a1a
.git/objects/fb/6b1f64d816d28e8ac1207eb12d8005d7c2af74
.git/objects/ff/5aeef92dadfd38dfb0a7a84bbe5033e858be18
.git/objects/pack/pack-fc096c7515f5a1f61deb87a08d54919388134e28.idx
.git/objects/pack/pack-fc096c7515f5a1f61deb87a08d54919388134e28.pack

**Comment by JohnMcLear** [comment]
http://mclear.co.uk/2013/01/28/how-to-find-out-the-version-of-an-etherpad-lite-instance/

**Comment by LucasCioffi** [comment]
Thank you.  I see this:
Server	Etherpad d4a35bd (http://etherpad.org)

**Comment by JohnMcLear** [comment]
Try a clean install, looks like your install has gone "bad".
