### ISSUE TITLE
"Such a padname is forbidden" error message on some file names

### ISSUE THREAD

**Issue by adelriosantiago** [ether/etherpad-lite#2583]
Hello everyone, I'm having bad luck trying to open some files like this:

http://servername:9001/files#/html/dashboard/views/pages/advertiser_campaign_administration.php

I don't know what it is but it simply won't open, it shows a **"Such a padname is forbidden"** error message when I try to manually change the URL for editing like this (changing the "files#" string to "p"):

http://servername:9001/p/html%2Fdashboard%2Fviews%2Fpages%2Fadvertiser_campaign_administration.php

**Anyone else having this issue? Is there a workaround?**

Many thanks.

**Comment by JohnMcLear** [comment]
@Gared

**Comment by a-delrio** [comment]
I don't know if it this is somehow related to the issue but file path with 100 characters or more throw this error. Quick checking the regex at https://github.com/ether/etherpad-lite/blob/9d1eca42b385373bcd6a05d77cfcebbdd9596e91/src/node/db/PadManager.js#L237 it does not seem to make any reference to this number.

**Comment by a-delrio** [comment]
I solved this issue with this patch: https://github.com/a-delrio/etherpad-lite/commit/0c7f985ac5c15f38b07cd77b801ac5d1258ed805, the file now loads fine however I don't really know if it will break another part, was there a purpose on the 50 characters limit?

**Comment by Gared** [comment]
I hadn't the time yet to analyze your problem, but increasing the character limit for pad names isn't a possible fix for this issue. Our database table in mysql (and probably other databases) has a maximum number of characters for keys so we have to limit the length of pad names.
I will have a look on this problem the next days.

**Comment by JohnMcLear** [comment]
Yes it will break certain databases
----- Reply message -----

**Comment by Gared** [comment]
Okay, after I had a deeper look into your question I noticed the following things:
- Why do you use the url http://servername:9001/files#... to open a pad? You have to use http://servername:9001/p/PADNAME to open a pad. If you're using a url without "/p/" you won't get a pad back.
- And the second url can't work, as you already noticed, because the pad name is too long. There is no workaround for that. Do you have to use such long pad names?

**Comment by a-delrio** [comment]
@Gared, I do change the "files#" to "p" to see what the error message says more clearly, however it is not always necessary to do that. Note that, on "files#" window you can also open files to edit by double-clicking on a file, that way you keep the file viewer open.

I don't have to use such long names actually, I can shorten, thats what I currently do, however with the time I consider that padnames greater than 50 characters will be common to many users.

**I propose creating a second field on the database that will handle the file path without the file name, then we can leave the 50 characters restrictions to only file-names (without the directories), that way we don't break functionality with older DB's (which is, I believe, the reason why the number 50 hasn't been increased)**

**Comment by JohnMcLear** [comment]
I propose not doing this.

**Comment by a-delrio** [comment]
I just found this conversation: https://github.com/ether/etherpad-lite/issues/1116, I was understanding the issue the wrong way. @JohnMcLear what do you think about doing a hash (32 chars max) to store the key on ueberDB?

**Comment by LaKing** [comment]
Okay, this is clearly a codepad thing. ( #files is used by codeapd .... )

As far as I remember I was able to patch etherpad to use a 100 character filename-length, but this patch does not seem familiar to me - however might have done the same. ...

@adelriosantiago 
You can overcome this problem with several approaches.
Best is to use shorter file/dir names.
Another option would be to use symlinks.

I hope this problem gets a solution on etherpad-level, if not, and it becomes a serious issue, I might think what to do on the plugin level. ....

**Comment by LaKing** [comment]
```bash
#!/bin/bash

function sed_file {
    ## used to replace a line in a file
    ## filename=$1 oldline=$2 newline=$3
    bak $1
    cat $1 > $1.tmp
    sed "s|$2|$3|" $1.tmp > $1
    rm $1.tmp
}

                        ### increase filesize limitation
                        #sed_file /srv/etherpad-lite/src/node/db/PadManager.js '    if(text.length > 100000)' '    if(text.length > 1000000) /* customization for longer texts*/'
                
                        ### The line containing:  return /^(g.[a-zA-Z0-9]{16}\$)?[^$]{1,50}$/.test(padId); .. but mysql is limited to 100 chars, so patch it.
                        #sed_file /srv/etherpad-lite/src/node/db/PadManager.js '{1,50}$/.test(padId);' '{1,100}$/.test(padId); /* customization for longer padnames*/'
```
