### ISSUE TITLE
Multiple Etherpad instances take a lot of time to load.

### ISSUE THREAD

**Issue by akshat-g** [ether/etherpad-lite#2586]

**Comment by akshat-g** [comment]
I have mutiple Etherpad instances on a single webpage. Every Etherpad instance is an iFrame and has its own set of plugins. Some plugins like ep_tables use YUI libraries which initially take time but later they get loaded from cache.
But native css files and other JS files of every Etherpad instance gets loaded and this causes high loading time.How can I improve loading time for multple instances? How can I load css and native JS files only once and make Etherpad instances use those css and JS files rather than loading their own?

**Comment by JohnMcLear** [comment]
Use minify: true and a high maxAge in your settings.json

We're working on making Etherpad more modular so you can have common resources.
