### ISSUE TITLE
Source Code Documentation

### ISSUE THREAD

**Issue by crash-dive** [ether/etherpad-lite#259]
Is there any value in creating something which better explains how etherpad-lite works from a developer standpoint? There is very little documentation on the  etherpad-lite source code which mean trying to understand how it works can be very hard and tends to involve (alteast for me) lots of break points and moving around the call stack to try and understand how everything happens. The node.js server code is easier to understand, but the ACE editor is difficult to say the least.

It would be nice to hear from other people who have been trying to understand the code to know if they feel the same way.

I know people have differing opinions on source code documentation, for example a friend once said to me if you need to document your source code you need to rewrite it because it is not clear. I have some spare time at the moment so I was planning to read through and get a much better understanding of how etherpad-lite works and as I do so I will make notes. Would it be a good idea if I made notes with a view to creating documentation which could be published or even just something less compressive that could serve as an introduction to the code base for new developers?

**Comment by monkey-pawan** [comment]
Hi JohnMcLear, I couldn't find the link to the video you mentioned above. Please share it, it will be a great help to me to debug how it is working and how can I tweak things as per my requirement.
