### ISSUE TITLE
IE: Alt F9 wont keep focus

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2598]
Control Shift N and L wont work..

Also prolly need to test other keystrokes.

**Comment by adammawson** [comment]
These are both fine in IE 11 for me.

Ctrl+shift+L is fine for normal list in chrome, need a replacement for ctrl+shift+n.  Would suggest ctrl+alt+n or ctrl+alt+L

Tested rest of accessibility buttons in chrome + IE11:
Alt+f9 not working (should go into toolbar)
Alt+c in IE opens favourites list.  Also opens etherpad chat and focuses but doesn’t un-focus
Alt+c  in chrome focuses on chat but doesn’t un-focus

**Comment by JohnMcLear** [comment]
Control Alt L is lock desktop on ubuntu

**Comment by JohnMcLear** [comment]
Alt F9 in IE11 will pull focus back to the editor, obviously related to https://github.com/ether/etherpad-lite/issues/2472

**Comment by JohnMcLear** [comment]
RE Control Shift N --> https://github.com/liftoff/GateOne/issues/290 -- Chromium have flagged as wontfix so there isn't much I can do other than assign a different keystroke.

**Comment by JohnMcLear** [comment]
Docs on restricted keys: http://stackoverflow.com/questions/7295508/javascript-capture-browser-shortcuts-ctrlt-n-w

**Comment by JohnMcLear** [comment]
Proposing control shift 1 as an alternative.

**Comment by JohnMcLear** [comment]
Chrome stuff all sorted so this is purely back to the single IE issue of not leaving focus out of editor.

**Comment by JohnMcLear** [comment]
I'm going to close this in favor of focusing my efforts on resolving https://github.com/ether/etherpad-lite/issues/2472 which when resolved will resolve this issue.
