### ISSUE TITLE
Feature request: "Set my view as default for all new viewers"

### ISSUE THREAD

**Issue by mic-e** [ether/etherpad-lite#2605]
I'm often using etherpad-lite to collaboratively edit/design technical specifications/code; monospace is a hard requirement for that.

It's annoying that every time I re-load the tab I have to manually set the font to monospaced, and every time someone new joins the pad, they need to be reminded to do the same.

A button "set my view as default for all new viewers" would solve that issue.

**Comment by JohnMcLear** [comment]
This is already saved and as of develop today can be handled in settings.json
----- Reply message -----

**Comment by mic-e** [comment]
I see; then it's just a configuration issue with the server I'm using.

An other equally valuable feature would be the ability to add view settings to the URL.

**Comment by JohnMcLear** [comment]
You can already.  Please read the manual....
----- Reply message -----

**Comment by mic-e** [comment]
Oh, sorry...

for the record, the param is `?useMonospaceFont=true`, and my install simply seems to be horribly outdated. Also, what manual? I found that info in `pad.js` line 110.

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/wiki
