### ISSUE TITLE
404 .NET HTTP API client example gives a 404

### ISSUE THREAD

**Issue by narasimhandl** [ether/etherpad-lite#2610]
The .Net HTTP API client api is no longer linked properly at 
https://github.com/ether/etherpad-lite/wiki/HTTP-API-client-libraries#net

this URL returns a http 404.

**Comment by JohnMcLear** [comment]
Author left github or renamed: https://github.com/ja-jo

**Comment by JohnMcLear** [comment]
Fixed: https://github.com/r15ch13/EtherpadLiteDotNet
