### ISSUE TITLE
The 'git guide' link in the README.md file is not pointing anywhere

### ISSUE THREAD

**Issue by sunilkumarc** [ether/etherpad-lite#2613]
In the README.md file, Under the section Development > Things you should know, there is a *git-guide* like which is not pointing anywhere. It should be adjusted with proper link.

![etherpad_issue](https://cloud.githubusercontent.com/assets/3911000/7154933/36bf7cb0-e34a-11e4-844f-caa103a4b4b9.jpg)

@JohnMcLear , I would like to work on this. Can you tell me which link I should put for this text?

**Comment by JohnMcLear** [comment]
Moved to https://training.github.com/
