### ISSUE TITLE
Adding pads doesn't work in Etherpad 1.5.5 on Windows

### ISSUE THREAD

**Issue by shaker** [ether/etherpad-lite#2614]
Hello.

I have a problem with Etherpad 1.5.5 on Windows. I unpacked the files to a clean folder (I got the archive from http://etherpad.org/downloads/etherpad-lite-win-1.5.5-24b0712d77.zip).

1. Run "start.bat".
2. Go to localhost:9001
3. Enter some text on textbox and then press "OK".
4. An error occured while loading the pad. ReferenceError: require is not defined in http://localhost:9009/p/123 (line 531)

Console:
```
GET http://localhost:9009/static/js/require-kernel.js HTTP/1.1 404 Not Found
ReferenceError: require is not defined http://localhost:9009/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define
ReferenceError: require is not defined http://localhost:9009/javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define
ReferenceError: require is not defined dddddd:531:14 require.setRootURI(baseURL + "javascripts/src");
```
I've tried in WinXP, Win7, Firefox and Chome. File require-kernel.js doesn't exist in the folder with static files. I'm not good in Javascript or Node (and English, sorry).
I have successfully used the version 1.2.7 before.

**Comment by JohnMcLear** [comment]
What version of node? Have you tried a
 clean install?

----- Reply message -----

**Comment by shaker** [comment]
Standalone Node is in the archive etherpad-lite-win-1.5.5-24b0712d77.zip and has version 0.10.38.
Have I tried a clean install of Node or Etherpad? Etherpad - I've tried (as actually in the message above), Node - I haven't.

**Comment by JohnMcLear** [comment]
Try download again, extract again and see if it works..  Node 10 should be okay..

**Comment by JohnMcLear** [comment]
I did notice during extraction we have some issues with path being too long, I thought I'd resolved that..

**Comment by JohnMcLear** [comment]
afaik https://github.com/ether/etherpad-lite/blob/develop/bin/buildForWindows.sh#L59 is no longer needed..

**Comment by JohnMcLear** [comment]
I'm able to replicate this issue on 1.5.5

**Comment by JohnMcLear** [comment]
The issue exists on a fully extracted version of Etherpad.  Ugh

**Comment by JohnMcLear** [comment]
This will be a bit of a pain in the ass to debug...  It will be quicker for you to bring up a linux VM and run it in there while we fix it up.

**Comment by JohnMcLear** [comment]
1.5.1 is fine

**Comment by JohnMcLear** [comment]
1.5.3 is broken

**Comment by shaker** [comment]
I don't mind the wait. :-) An older 1.2.7 version of Etherpad works well.

**Comment by JohnMcLear** [comment]
Commit that caused the break is Bisecting: 0 revisions left to test after this (roughly 0 steps)
[7b86eb09bc2235dd2683fb72601934dbcea3a9eb] new fix for #1766

**Comment by JohnMcLear** [comment]
Breaking commit

9d4e5f6e35153129377206ef545d4965afae627d is the first bad commit
commit 9d4e5f6e35153129377206ef545d4965afae627d
Author: John McLear <john@mclear.co.uk>
Date:   Fri Apr 10 22:02:22 2015 +0100

    dont allow directory traversal

:040000 040000 7e28e7ab56134df08cc8d96f5f0b660ec05149b3 536e5baec42fecf77bf691a1
a2ee25c0851ed362 M      src

**Comment by JohnMcLear** [comment]
@devoidfury any suggestion for how to best handle this?

**Comment by JohnMcLear** [comment]
Thanks for the fix @devoidfury -- works 10/10 ! :)

**Comment by JohnMcLear** [comment]
@Gared we might want to do another release due to this?

**Comment by devoidfury** [comment]
No problem, sorry about the regression!

**Comment by Gared** [comment]
@JohnMcLear Do we really want to release again? Maybe we should wait until @Pita is done with his iframe removal process?!
Btw: you can grab latest windows build here: http://stefans-entwicklerecke.de/wp-content/eplite-nightly-builds/

**Comment by JohnMcLear** [comment]
Oh we wont be merging in the iframe stuff for at least 3 months!

I don't think releasing again will hurt, not releasing will..

**Comment by shaker** [comment]
Thanks guys!
Nightly-build works well.

**Comment by JohnMcLear** [comment]
+1 shaker tnx

**Comment by Gared** [comment]
@JohnMcLear If you want I can do another release for this. Probably I can do it today evening.

**Comment by JohnMcLear** [comment]
Perfect thanks :)
