### ISSUE TITLE
Many new errors since updating

### ISSUE THREAD

**Issue by micah** [ether/etherpad-lite#2615]
Since updating to 1.5.5, I'm getting a significant number of the following errors reported in my logs (log level is set to WARNING), so many that I'm concerned I will fill up my disk fairly rapidly, and that it is an indicator that something is wrong:

```
[2015-04-15 14:34:52.616] [WARN] client - TypeError: $(...).closest(...).get(...) is undefined -- { errorId: '<errorid remove>',
  msg: 'TypeError: $(...).closest(...).get(...) is undefined',
  url: '<pad url removed>',
  linenumber: 65,
  userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:37.0) Gecko/20100101 Firefox/37.0' }
```

```
[2015-04-15 14:34:50.384] [WARN] client - Uncaught TypeError: Cannot read property 'className' of undefined -- { errorId: '<erroridremoved>',
  msg: 'Uncaught TypeError: Cannot read property \'className\' of undefined',
  url: '<pad url removed>',
  linenumber: 65,
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36' }
```

**Comment by JohnMcLear** [comment]
Looks like your clients aren't getting the latest JS, try temporarily setting your minify to false and maxAge to 0 in settings.json and see if they persist.

**Comment by micah** [comment]
I set minify to false, and maxAge to 0, and restarted nginx and etherpadlite, but I am still getting quite a lot of these.

**Comment by JohnMcLear** [comment]
Give it a few days and if they persist let me know.

**Comment by Flauschie** [comment]
I haven't updated but I am receiving the same errors since today

^[[33m[2015-04-20 13:59:02.616] [WARN] client - ^[[39mUncaught TypeError: Cannot read property 'className' of undefined -- { errorId: 'my error ID',
  msg: 'Uncaught TypeError: Cannot read property \'className\' of undefined',
  url: 'MYPADURL',
  linenumber: 65,
  userAgent: 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36' }

**Comment by JohnMcLear** [comment]
Can you consistently replicate @Flauschie ?

**Comment by Flauschie** [comment]
The biggest problem is t he span.target error... If I resize the window nothing happens with line break!
Only Safari on OS X / iOS is affected by this.

I can reproduce this error consistently

**Comment by JohnMcLear** [comment]
@Flauschie please create a separate issue that fully documents this including steps to replicate.

**Comment by micah** [comment]
John McLear <notifications@github.com> writes:

> Give it a few days and if they persist let me know.

It looks like it is still happening:

ESC[33m[2015-04-20 12:30:35.901] [WARN] client - ESC[39mUncaught TypeError: Cannot read property 'className' of undefined -- { errorId: 'xxx',
  msg: 'Uncaught TypeError: Cannot read property \'className\' of undefined',
  url: 'padurl',
  linenumber: 65,
  userAgent: 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36' }
ESC[33m[2015-04-20 12:30:39.533] [WARN] client - ESC[39mTypeError: $(...).closest(...).get(...) is undefined -- { errorId: 'xxx',
  msg: 'TypeError: $(...).closest(...).get(...) is undefined',
  url: 'padurl,
  linenumber: 65,
  userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0' }

**Comment by JohnMcLear** [comment]
Any plugins?
----- Reply message -----

**Comment by elijh** [comment]
I am still getting these as of today, even for a brand new pad that only I connected to and after force reloading in the browser.

    Uncaught TypeError: Cannot read property 'className' of undefined

**Comment by elijh** [comment]
here is a summary of the errors:

````
[2015-05-16 22:42:22.963] [WARN] client - TypeError: $(...).closest(...).get(...) is undefined -- { errorId: '03DRyqZDGOJfbySK5RXA',
  msg: 'TypeError: $(...).closest(...).get(...) is undefined',
  url: 'https://pad.riseup.net/p/xxxxxxxxxxx',
  linenumber: 65,
  userAgent: 'Mozilla/5.0 xxxx Firefox/38.0' }

[2015-05-16 22:42:54.359] [WARN] client - Uncaught TypeError: Cannot read property 'className' of undefined -- { errorId: 'LVyT9ylHhBm3b5NdiWK3',
  msg: 'Uncaught TypeError: Cannot read property \'className\' of undefined',
  url: 'https://pad.riseup.net/p/xxxxxxxxxxx',
  linenumber: 65,
  userAgent: 'Mozilla/5.0 xxxx Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36' }

[2015-05-16 22:43:19.889] [WARN] client - TypeError: undefined is not an object (evaluating '$(span.target).closest('span').get(0).className') -- { errorId: 'PvhxJsK4pJyMi6Xn3p7e',
  msg: 'TypeError: undefined is not an object (evaluating \'$(span.target).closest(\'span\').get(0).className\')',
  url: 'https://pad.riseup.net/p/xxxxxxxxxxx',
  linenumber: 65,
  userAgent: 'Mozilla/5.0 xxxx AppleWebKit/600.3.18 Version/8.0.3 Safari/600.3.18' }

[2015-05-16 22:43:59.590] [WARN] client - Error: Permission denied to access property "document" -- { errorId: 'QcYNAUmZ1ZAWBa0MilbS',
  msg: 'Error: Permission denied to access property "document"',
  url: 'https://pad.riseup.net/p/xxxxxxxxxxx',
  linenumber: 34,
  userAgent: 'Mozilla/5.0 xxxx Firefox/38.0' }

````

(pad url and user agent anonymized)

**Comment by JohnMcLear** [comment]
```
bin/cleanRun.sh
```

If it doesn't fix please reopen issue

**Comment by elijh** [comment]
removing all the plugins did not change anything, but bin/cleanRun.sh seems to have reduced the number of errors (or maybe it is just later in the day and there are fewer people connected!). maybe now js will update eventually everywhere. i will update this issue with a report back of how it goes.

**Comment by elijh** [comment]
after 5 hrs on latest develop branch, there are fewer of the previous type of errors, but a bunch of these started showing up (54 instances):

```
[2015-05-17 04:22:41.898] [WARN] client - Script error. -- { errorId: 'sY5o20l45suwRYM3XvVw',
  msg: 'Script error.',
  url: 'https://pad.riseup.net/p/xxxxxxxxxxx',
  linenumber: 0,
  userAgent: 'Mozilla/5.0 xxxx Gecko/20140319 Firefox/24.0 Iceweasel/24.4.0' }
```

**Comment by JohnMcLear** [comment]
Turn minify to false and maxAge to 0 in settings.json, that will give you better debug to catch which error it is .
