### ISSUE TITLE
ep_br_to_p plugin: update necessary

### ISSUE THREAD

**Issue by ternite** [ether/etherpad-lite#2620]
Hi,

the plugin ep_br_to_p does not work with current versions of etherpad-lite. As there appears to be no separate github site for this plugin and I have no idea of how to create and provide a new npm package, I will post a fix here.

Apparently, source of the problem is that there is no getFullHTMLForExport (anymore), but getLineHTMLForExport.

Thus, I changed ep.json in the plugin folder to:
```javascript
{
  "parts": [
    {
      "name": "main",
      "hooks": {
        "getLineHTMLForExport" : "ep_br_to_p/index"
      }
    }
  ]
}
```

And I changed index.js to:
```javascript
/* 
 * Wrap text in Paragraphs in the HTML export, i.e. replace all occurences of {text}<br><br> with an enclosing <p>{text}</p>.
 * 
 * From: 'Prachtig is het licht dat uit de hemel neerdaalt.<br><br>Geen enkele faktor van dit probleem uit de weg gaan. Zich volledig inzetten.<br>Wij zullen het klaarspelen. De moeilijkheden van de eenzaamheid dienen volledig te worden behandeld.<br><br>Hij sterft zonder een enkele frase, de ogen vol tranen.'
 * To: '<p>Prachtig is het licht dat uit de hemel neerdaalt.</p><p>Geen enkele faktor van dit probleem uit de weg gaan. Zich volledig inzetten.<br>Wij zullen het klaarspelen. De moeilijkheden van de eenzaamheid dienen volledig te worden behandeld.</p><p>Hij sterft zonder een enkele frase, de ogen vol tranen.</p>'
 * 
 * This relies on the fact that we know the specifics of Etherpad’s output:
 * no whitespace, lowercase tags, no slashes in self-closing tags.
 * 
 * For a more general purpose implementation we would probably
 * need to use jsdom and the DOM api.
 * */
var sys = require("sys");

exports.getLineHTMLForExport = function(hook, context) {
   var html = context.lineContent;
   return ['<p>' + html.replace(/<br><br>/g, '</p><p>') + '</p>'];
};
```

Please note that I found a mispelled line of code in the [documentation of getLineHTLMForExport (etherpad-lite 1.5.5)] (http://etherpad.org/doc/v1.5.5/#index_getlinehtmlforexport). The example code accesses `context.lineContents`, while this should be `context.lineContent`.

Best regards
ternite

**Comment by JohnMcLear** [comment]
Contact the plugin author: https://www.npmjs.com/~schrijver

**Comment by JohnMcLear** [comment]
Docs fixed in https://github.com/ether/etherpad-lite/commit/d31523aa08d123f421248e249e2194f7689f0b06
