### ISSUE TITLE
More information about the etherpad-lite user

### ISSUE THREAD

**Issue by MartinDelille** [ether/etherpad-lite#2624]
I'm trying to setup etherpad-lite as a service using the following documentation using https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service#ubuntu-1004-debian-6-sysvinit
Unfortunately I'm stucking on the first step: 'create a user called etherpad-lite'
Would it be possible to add the command line to create it? Shall I set a password for this user? a home folder?

**Comment by JohnMcLear** [comment]
``adduser etherpad`` is all I do

**Comment by SamuelMoraesF** [comment]
I use `adduser etherpad --system --create-home --home-dir /var/etherpad`

`--system` to don't allow login as this user(you need to use `sudo su etherpad` to change to this account)
`--create-home` and `--home-dir` to create and set the home folder

**Comment by MartinDelille** [comment]
Shall I add it to the doc for further doubt?

**Comment by JohnMcLear** [comment]
Yea, feel free :)

**Comment by MartinDelille** [comment]
done!

**Comment by MartinDelille** [comment]
I just changed the command you gave me because it didn't work for me: https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service
