### ISSUE TITLE
Errors after upgrade (via git pull)

### ISSUE THREAD

**Issue by lightweight** [ether/etherpad-lite#2626]
I'm running etherpad-lite on Ubuntu 12.04 ( https://etherpad.nzoss.org.nz ) with MariaDB as the backend store, and have recently done a git pull to keep things up-to-date but have ended up in the difficult situation that all pads are now returning the error: 
"An error occured while loading the pad 
Error: The module at "underscore" does not exist. in https://etherpad.nzoss.org.nz/static/js/require-kernel.js (line 589)"

Going to the troubleshooting part of the admin interface ( https://etherpad.nzoss.org.nz/admin/plugins/info ) returns the somewhat vague:
```
{
  "error": "Sorry, something bad happened!"
}
```

I've tried moving src/node_modules and forcing a rebuild on restarting, which resulted in (from what I can tell, being new to the node ecosystem) OK results with the possible exception of these two log messages:
"> ws@0.5.0 install /home/etherpad/local/etherpad/etherpad-lite/src/node_modules/socket.io/node
_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

> ws@0.4.31 install /home/etherpad/local/etherpad/etherpad-lite/src/node_modules/socket.io/nod
e_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)"
```
I've also tried removing all plugins in case it was one of them causing the problem, but that did not seem to have any effect. For the record, the enabled plugins are
- adminpads 0.0.9 	
- author_neat 0.0.31 	
- authornames 0.1.3

Let me know if there's any other info I can provide to help get to the bottom of this.

Dave

**Comment by JohnMcLear** [comment]
You did Every step I'd recommend....  Is minify and maxage set to false and 0?
----- Reply message -----

**Comment by lightweight** [comment]
Wow, that was quick!  I've set minify to false in settings.json, but I don't see a maxage setting except down deep in the js files - assuming it needs to be set somewhere higher?

**Comment by lightweight** [comment]
Sorry, didn't mean to close that.

**Comment by lightweight** [comment]
Hmm - just tried rebuilding the src/node_modules and npm-debug.log says the following (which I haven't been able to interpret):
"0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '--save-dev' ]
2 info using npm@1.4.28
3 info using node@v0.10.37
4 verbose node symlink /usr/bin/node
5 error install Couldn't read dependencies
6 error package.json ENOENT, open '/home/etherpad/local/etherpad/etherpad-lite/package.json'
6 error package.json This is most likely not a problem with npm itself.
6 error package.json npm can't find a package.json file in your current directory.
7 error System Linux 3.0.20-xenU
8 error command "/usr/bin/node" "/usr/bin/npm" "install" "--save-dev"
9 error cwd /home/etherpad/local/etherpad/etherpad-lite
10 error node -v v0.10.37
11 error npm -v 1.4.28
12 error path /home/etherpad/local/etherpad/etherpad-lite/package.json
13 error code ENOPACKAGEJSON
14 error errno 34
15 verbose exit [ 34, true ]"

Do I need to update npm or node itself? Permission issue? Seems like I've seen this sort of problem elsewhere in the etherpad-lite issues...

**Comment by JohnMcLear** [comment]
Maxage is in settings.json
----- Reply message -----

**Comment by JohnMcLear** [comment]
I'd do a clean install.  Looks like your package.json has been deleted.
----- Reply message -----

**Comment by lightweight** [comment]
I've replaced the entire etherpad-lite directory with a fresh git clone (although I would've thought a git pull would accomplish the same thing) and simply transferred my settings.json to the new directory and then restarted etherpad-lite. The same errors mentioned previously result... I'm suspecting that there's something wrong with system npm or node library versions... The same dependency build errors seem to occur, namely: 
"> ws@0.5.0 install /home/etherpad/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)
  
> ws@0.4.31 install /home/etherpad/local/etherpad/etherpad-lite/src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)"

Any further suggestions for what I could change, or things I could try to help narrow down the problem?

**Comment by JohnMcLear** [comment]
Okies well try a node upgrade..
Can you paste the full error again please?

**Comment by lightweight** [comment]
For what it's worth, I'm running 0.10.37-1chl1~precise1 (installed via Ubuntu package manager from the Chris Lea PPA - http://ppa.launchpad.net/chris-lea/node.js/ubuntu). The error log output from the latest run of etherpad-lite (with the freshly cloned repo): 

npm@2.7.6 node_modules/npm
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.

> ws@0.5.0 install /home/etherpad/local/etherpad/etherpad-lite/src/node_modules/socket.io/node
_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

> ws@0.4.31 install /home/etherpad/local/etherpad/etherpad-lite/src/node_modules/socket.io/nod
e_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

channels@0.0.4 node_modules/channels

security@1.0.0 node_modules/security

async-stacktrace@0.0.2 node_modules/async-stacktrace

slide@1.1.6 node_modules/slide

graceful-fs@3.0.6 node_modules/graceful-fs

tinycon@0.0.1 node_modules/tinycon

formidable@1.0.17 node_modules/formidable

async@0.9.0 node_modules/async

etherpad-require-kernel@1.0.9 node_modules/etherpad-require-kernel

underscore@1.8.3 node_modules/underscore

languages4translatewiki@0.1.3 node_modules/languages4translatewiki

unorm@1.3.3 node_modules/unorm

cookie-parser@1.3.4 node_modules/cookie-parser
├── cookie-signature@1.0.6
└── cookie@0.1.2

semver@4.3.3 node_modules/semver

measured@1.0.0 node_modules/measured
└── inherits@2.0.1

express-session@1.11.1 node_modules/express-session
├── utils-merge@1.0.0
├── on-headers@1.0.0
├── parseurl@1.3.0
├── depd@1.0.1
├── cookie-signature@1.0.6
├── cookie@0.1.2
├── crc@3.2.1
├── uid-safe@1.1.0 (base64-url@1.2.1, native-or-bluebird@1.1.2)
└── debug@2.1.3 (ms@0.7.0)

resolve@1.1.6 node_modules/resolve

etherpad-yajsml@0.0.2 node_modules/etherpad-yajsml

ejs@2.3.1 node_modules/ejs

supertest@0.15.0 node_modules/supertest
├── methods@1.1.1
└── superagent@0.21.0 (extend@1.2.1, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, qs@1.2.0, mime@1.2.11, debug@2.1.3, form-data@0.1.3, formidable@1.0.14, readable-stream@1.0.27-1)

express@4.12.3 node_modules/express
├── merge-descriptors@1.0.0
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── cookie@0.1.2
├── fresh@0.2.4
├── escape-html@1.0.1
├── range-parser@1.0.2
├── finalhandler@0.3.4
├── vary@1.0.0
├── content-type@1.0.1
├── parseurl@1.3.0
├── serve-static@1.9.2
├── content-disposition@0.5.0
├── path-to-regexp@0.1.3
├── depd@1.0.1
├── on-finished@2.2.0 (ee-first@1.1.0)
├── qs@2.4.1
├── debug@2.1.3 (ms@0.7.0)
├── etag@1.5.1 (crc@3.2.1)
├── proxy-addr@1.0.7 (forwarded@0.1.0, ipaddr.js@0.1.9)
├── send@0.12.2 (destroy@1.0.3, ms@0.7.0, mime@1.3.4)
├── accepts@1.2.5 (negotiator@0.5.1, mime-types@2.0.10)
└── type-is@1.6.1 (media-typer@0.3.0, mime-types@2.0.10)

clean-css@3.1.9 node_modules/clean-css
├── commander@2.6.0
└── source-map@0.1.43 (amdefine@0.1.0)

log4js@0.6.22 node_modules/log4js
├── semver@1.1.4
├── async@0.2.10
└── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)

uglify-js@2.4.19 node_modules/uglify-js
├── uglify-to-browserify@1.0.2
├── async@0.2.10
├── yargs@3.5.4 (camelcase@1.0.2, decamelize@1.0.0, window-size@0.1.0, wordwrap@0.0.2)
└── source-map@0.1.34 (amdefine@0.1.0)

request@2.55.0 node_modules/request
├── caseless@0.9.0
├── json-stringify-safe@5.0.0
├── aws-sign2@0.5.0
├── forever-agent@0.6.1
├── form-data@0.2.0
├── stringstream@0.0.4
├── oauth-sign@0.6.0
├── tunnel-agent@0.4.0
├── isstream@0.1.2
├── node-uuid@1.4.3
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── qs@2.4.1
├── mime-types@2.0.10 (mime-db@1.8.0)
├── http-signature@0.10.1 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@0.9.4 (readable-stream@1.0.33)
├── tough-cookie@0.12.1 (punycode@1.3.2)
├── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.7.1, hoek@2.12.0)
└── har-validator@1.6.1 (commander@2.8.0, chalk@1.0.0, is-my-json-valid@2.10.1, bluebird@2.9.24)

mocha@2.2.4 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.1
├── diff@1.0.8
├── growl@1.8.1
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

ueberDB@0.2.15 node_modules/ueberDB
├── felix-couchdb@1.0.7
├── redis@0.12.1
├── dirty@0.9.9
├── async@0.1.15
├── cassandra-driver@2.0.1 (async@0.9.0, long@2.2.3)
├── mysql@2.6.1 (require-all@1.0.0, readable-stream@1.1.13, bignumber.js@2.0.5)
└── pg@4.3.0 (packet-reader@0.2.0, pg-connection-string@0.1.3, buffer-writer@1.0.0, generic-pool@2.1.1, pg-types@1.7.0, pgpass@0.0.3)

jsonminify@0.2.3 node_modules/jsonminify

socket.io@1.3.5 node_modules/socket.io
├── debug@2.1.0 (ms@0.6.2)
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
├── engine.io@1.5.1 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.1, ws@0.5.0)
├── socket.io-client@1.3.5 (to-array@0.1.3, indexof@0.0.1, component-bind@1.0.0, debug@0.7.4, object-component@0.0.3, backo2@1.0.2, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.1)
└── socket.io-parser@2.2.4 (isarray@0.0.1, component-emitter@1.1.2, debug@0.7.4, benchmark@1.0.0, json3@3.2.6)

swagger-node-express@2.1.3 node_modules/swagger-node-express
└── lodash@1.3.1

cheerio@0.19.0 node_modules/cheerio
├── entities@1.1.1
├── dom-serializer@0.1.0 (domelementtype@1.1.3)
├── css-select@1.0.0 (boolbase@1.0.0, css-what@1.0.0, nth-check@1.0.1, domutils@1.4.3)
├── htmlparser2@3.8.2 (domelementtype@1.3.0, domutils@1.5.1, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13)
└── lodash@3.7.0

wd@0.3.11 node_modules/wd
├── vargs@0.1.0
├── q@1.0.1
├── underscore.string@2.3.3
├── lodash@2.4.1
├── request@2.46.0 (caseless@0.6.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, qs@1.2.2, node-uuid@1.4.3, mime-types@1.0.2, bl@0.9.4, tough-cookie@0.12.1, http-signature@0.10.1, hawk@1.1.1, form-data@0.1.4)
└── archiver@0.12.0 (buffer-crc32@0.2.5, lazystream@0.1.0, readable-stream@1.0.33, zip-stream@0.4.1, tar-stream@1.0.2, glob@4.0.6)

**Comment by JohnMcLear** [comment]
There is no error here.....

**Comment by lightweight** [comment]
The builderror.log files contain: 

- src/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/builderror.log
--
/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:54
    throw new Error(
          ^
Error: node-gyp requires that the user's home directory is specified in either of the environmental variables HOME or USERPROFILE
    at new Gyp (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:54:11)
    at gyp (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:43:10)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:20:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

and in src/node_modules/socket.io/node_modules/engine.io/node_modules/ws/builderror.log

/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:54
    throw new Error(
          ^
Error: node-gyp requires that the user's home directory is specified in either of the environmental variables HOME or USERPROFILE
    at new Gyp (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:54:11)
    at gyp (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:43:10)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:20:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by JohnMcLear** [comment]
So the error is

```
Error: node-gyp requires that the user's home directory is specified in either of the environmental variables HOME or USERPROFILE
```

**Comment by lightweight** [comment]
Ok - I was triggering the dependency build by running (as root), service etherpad-lite start... Running bin/run.sh as the etherpad user, I get a somewhat different builderror.log (/node_modules/socket.io/node_modules/engine.io/node_modules/ws/builderror.log) - all warnings as far as I can tell:

../src/bufferutil.cc: In static member function 'static void BufferUtil::Initialize(v8::Handle<v8::Object>)':
../src/bufferutil.cc:32:17: warning: 'v8::Local<v8::String> NanSymbol(const char*, int)' is deprecated (declared at ../node_modules/nan/nan.h:1048) [-Wdeprecated-declarations]
../src/bufferutil.cc:32:39: warning: 'v8::Local<v8::String> NanSymbol(const char*, int)' is deprecated (declared at ../node_modules/nan/nan.h:1048) [-Wdeprecated-declarations]
../src/validation.cc: In static member function 'static void Validation::Initialize(v8::Handle<v8::Object>)':
../src/validation.cc:112:17: warning: 'v8::Local<v8::String> NanSymbol(const char*, int)' is deprecated (declared at ../node_modules/nan/nan.h:1048) [-Wdeprecated-declarations]
../src/validation.cc:112:39: warning: 'v8::Local<v8::String> NanSymbol(const char*, int)' is deprecated (declared at ../node_modules/nan/nan.h:1048) [-Wdeprecated-declarations]

**Comment by JohnMcLear** [comment]
Yes just warnings..

**Comment by lightweight** [comment]
Stilll seeing the same problems with the admin/plugins/info and trying to view existing pads...

**Comment by JohnMcLear** [comment]
Hrm, no idea why your environment is having problems..  Something is obviously wrong though.. If you want to email me I can take a look and sees if I can figure out what's unique about your environment that is causing node to misbehave.

**Comment by lightweight** [comment]
I appreciate your help. I'd be happy to have you take a look - to get your email, you can email me at githubspam@sound.org.nz :) (going to bed now, though)

**Comment by JohnMcLear** [comment]
________________________________

**Comment by lightweight** [comment]
Ok, because I need to get the Etherpad-lite instance back up and running fairly urgently, I've resorted to returning to a backup of the code I had in place prior to the most recent git pull... It's now working, however, I'm keen to upgrade it at some point. I will try running an upgraded version elsewhere prior to deploying it on the live site. Thanks very much for your help, John - at this stage, the problem hasn't been fixed, but I've worked around it for the time being.

**Comment by JohnMcLear** [comment]
Old code is vulnerable...
----- Reply message -----

**Comment by lightweight** [comment]
Ok, then I need to work out how to upgrade without munting my installation :) Any suggestions welcome.

**Comment by JohnMcLear** [comment]
Like I said I can jump onto your instance and see what is wrong.

**Comment by lightweight** [comment]
If you're willing/able, let me know - perhaps provide me with your public key via email, and I'll give you ssh access as the etherpad-lite user on the server... would that work?

**Comment by JohnMcLear** [comment]
I use a lot of different hosts(I work in different environments) so public key sharing is a pain for me.  Just create me a user with sudo perms and email me the user/pass.

**Comment by lightweight** [comment]
Thanks again for your help, John. For posterity, what John did was to create a brand new install (via git clone) of the etherpad-lite codebase, and simply copy the settings.json file to the new directory... Thought I'd tried that, but apparently didn't clear everything out properly. Anyway, it works now.

**Comment by cdauth** [comment]
I have the same problem when trying to run Etherpad through different Docker images, for example [fuerst/etherpad-docker](https://hub.docker.com/r/fuerst/etherpad-docker/) and [tvelocity/etherpad-lite](https://hub.docker.com/r/tvelocity/etherpad-lite/).

**Comment by cdauth** [comment]
It turns out that for me this was a simple browser caching issue! After reloading with Ctrl+Shift+R, everything loads fine again.
