### ISSUE TITLE
Etherpad do not auto scroll

### ISSUE THREAD

**Issue by hientuminh** [ether/etherpad-lite#2628]
I am working in Etherpad Timeslider. However, it does NOT auto scroll.
Have you any idea to fix the issue?

![donotautoscroll](https://cloud.githubusercontent.com/assets/4133453/7245457/adf9ba64-e815-11e4-8e64-bfcdb3d701ca.png)

**Comment by JohnMcLear** [comment]
It's currently broken for large pads.  There is already an issue.
----- Reply message -----
