### ISSUE TITLE
Fix documentation for proxy under lighttpd

### ISSUE THREAD

**Issue by MartinDelille** [ether/etherpad-lite#2629]
It seems the documentation is out of date here: https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#lighttpd

The issue link is broken : https://github.com/Pita/etherpad-lite/issues/28
I manage to make it work under lighttpd with the following config:

    $HTTP["host"] =~  "pad\.phnt\.io$" {
        proxy.server = ( "" => ( ( 
            "host" => "127.0.0.1", 
            "port" => 9001
        ) ) )
    }

**Comment by JohnMcLear** [comment]
Please go ahead and fix the docs :)
----- Reply message -----

**Comment by MartinDelille** [comment]
Done: https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#lighttpd

**Comment by JohnMcLear** [comment]
Thanks :)
