### ISSUE TITLE
Problem in ExportHTML.js regarding creation of HTML for lists

### ISSUE THREAD

**Issue by shanukus98765** [ether/etherpad-lite#2630]
My view in Etherpad:
![etherpad_list2](https://cloud.githubusercontent.com/assets/6191415/7251085/8a470574-e845-11e4-9512-84c83a7041f5.png)

This is the so-called HTML associated with it.
<xmp><ol class=\"number\"><li>Numbering1</li><ul class=\"bullet\"><li>bullet1</li><li>bullet2</li><li>bullet3</li></ul><li>Numbering2</li><ol class=\"number\"><li>A</li><li>This is part of A</li><li>This is again part of A</li><ul><ul class=\"indent\"><li>This is a new paragraph and it is not part of the list.</li></ul></ul></ul></ul><br>
</xmp>

The output generated thus, looks like this:
<ol class=\"number\"><li>Numbering1</li><ul class=\"bullet\"><li>bullet1</li><li>bullet2</li><li>bullet3</li></ul><li>Numbering2</li><ol class=\"number\"><li>A</li><li>This is part of A</li><li>This is again part of A</li><ul><ul class=\"indent\"><li>This is a new paragraph and it is not part of the list.</li></ul></ul></ul></ul><br>

This was given by the function "getHTMLFromAtext" within ExportHTML.js
I tried this out with multiple cases and closing tags seem to be missing from a variety of edge cases such as.
1. If you start a 'bullet list' within a 'numbered list' of 2nd level.
2. If you immediately start with an indented paragraph after finishing a list.

**Comment by webzwo0i** [comment]
ups, probably I introduced/did not handle this when I changed export a little bit last year.
Thanks, I will try to reproduce this and get it fixed.

**Comment by shanukus98765** [comment]
Thanks. This would be of great help. I will cross check for more edge cases.

**Comment by JohnMcLear** [comment]
@webzwo0i if you follow the repo I can assign this to you I think :)

**Comment by shanukus98765** [comment]
@webzwo0i: I had mentioned 2 cases where the "getHTMLFromAtext" within ExportHTML.js is generating wrong HTML output.

As far as I can see, putting indentation as a <ul> tag is causing problems. If you immediately start with an indented paragraph after finishing a list, the list tag is not being closed and an extra <ul> tag comes in for indentation.
