### ISSUE TITLE
Push updates from Commandline

### ISSUE THREAD

**Issue by joafri** [ether/etherpad-lite#2633]
Hi,

Maybe not so much an issue as a feature request.
Is it possible to somehow send updates to the pad-area from commandline, say from a script or similar?

**Comment by joafri** [comment]
Silly me - found it in the Api-requests.

**Comment by JohnMcLear** [comment]
@joafri for posterity when you close your own stuff please do include a link to the docs or whatever..  

Here is the link to accomplish this:
https://www.npmjs.com/package/etherpad-cli-client
