### ISSUE TITLE
Changes are not saved or synced

### ISSUE THREAD

**Issue by SPQRInc** [ether/etherpad-lite#2635]
Hello,

I got a little problem - if I open a modified pad, I can see the content and write some stuff. But this stuff is not synced so my second browser, which displays the same pad, is not updated...

Restarting the etherpad-service does not change anything...

**Comment by JohnMcLear** [comment]
Any errors in your JavaScript console?  Does refreshing show the correct pad text?  What browser?  What version of etherpad.
----- Reply message -----

**Comment by JohnMcLear** [comment]
Pretty sure this was user error.
