### ISSUE TITLE
Content Collector not getting the class value of nodes

### ISSUE THREAD

**Issue by lpagliari** [ether/etherpad-lite#2640]
I'm using the plugin ep_font_color, and when I change the pad content using the `setHTML()` hook, Etherpad is ignoring the class on my nodes.

Here's the HTML I'm using as content for my pad:
```
<html><body><span class='color:red'>this should be red</span></body></html>
```

Apparently the issue in on `static/js/contentcollector.js`, when getting the class from node:
```
    nodeProp: function(n, p)
    {
      return n[p];
    },
(...)
var cls = dom.nodeProp(node, "className");
```

When using jsdom to read the HTML, the code above works. But when using cheerio it does not:
```
var jsdom = require("jsdom").jsdom;
var doc = jsdom("<html><body><span class='color:red'>this should be red</span></body></html>");
var body = doc.childNodes[0].childNodes[1];
var span = body.childNodes[0];
span["className"];
// => 'color:red'
```
```
var cheerio = require('cheerio');
var $ = cheerio.load("<html><body><span class='color:red'>this should be red</span></body></html>");
var body = $('html')[0].childNodes[0];
var span = body.childNodes[0];
span["className"]
// => undefined

span.attribs["class"];
// => 'color:red'
```

I found a way to fix it, but wanted to be sure this is an issue with Etherpad code, and not on my environment.

**Comment by JohnMcLear** [comment]
I will look into this when I get time.

**Comment by JohnMcLear** [comment]
What's your suggested fix here?  It looks like Cheerio is just behaving different to jsdom.

Are you thinking about just using the ``span.attribs["class"];`` value instead of ``className``?

**Comment by lpagliari** [comment]
Actually I was thinking about changing
```
    nodeAttr: function(n, a)
    {
      if(n.getAttribute == null) return null;
      return n.getAttribute(a);
    },
```
to
```
    nodeAttr: function(n, a)
    {
       if(n.getAttribute != null) return n.getAttribute(a);
       if(n.attribs != null) return n.attribs[a];
       return null;
    },
```

and use `var cls = dom.nodeAttr(node, "class");` instead of `nodeProp`

**Comment by JohnMcLear** [comment]
Should be okay, run tests after you try it
----- Reply message -----
