### ISSUE TITLE
Errors when creating new pad

### ISSUE THREAD

**Issue by pwnmagic** [ether/etherpad-lite#2644]
An error occured
The error was reported with the following id: 'IdVVhIWZKKVoJQtZQNbH'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: IdVVhIWZKKVoJQtZQNbH
URL: http://etherpad.domain.com:9001/p/test
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
Uncaught ReferenceError: io is not defined in http://etherpad.domain.com:9001/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 232'

**Comment by JohnMcLear** [comment]
Update and clean run.
----- Reply message -----

**Comment by pwnmagic** [comment]
Stopped etherpad-lite. Updated the etherpad-lite code base. Re-started etherpad-lite. 
Still the same error.

============================================================
Error in Logs
------------------
[2015-04-30 12:55:33.883] [ERROR] console - Failed to load 'ep_etherpad-lite/node/hooks/express/socketio:expressCreateServer' for 'ep_etherpad-lite/socketio/hooks/expressCreateServer': TypeError: object is not a function

============================================================
Error when creating a new pad
-----------------------------------------
An error occured
The error was reported with the following id: 'vp3p8YhL29yv7sK9Q5Sq'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: vp3p8YhL29yv7sK9Q5Sq
URL: http://etherpad.domain.com:9001/p/test
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
Uncaught ReferenceError: io is not defined in http://etherpad.domain.com:9001/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 232'

**Comment by JohnMcLear** [comment]
do ``bin/cleanRun.sh``

**Comment by pwnmagic** [comment]
Etherpad works as expected after the cleanRun. Thanks!
