### ISSUE TITLE
Listen on existing port: better error behavior

### ISSUE THREAD

**Issue by vanceza** [ether/etherpad-lite#2645]
If I try to start etherpad with a port already in use, I see this in the logs: "[WARN] socket.io - error raised: Error: listen EADDRINUSE".
I'm running etherpad inside of a daemon manager, and it returns the status of etherpad as "RUNNING". It would be better for me if this error shut down the execution of etherpad, because then I can detect failure to start with external tools.

Version: 8c1868f

**Comment by JohnMcLear** [comment]
afaik we return process.exit(0) which shojuld tell the daemon manager it's not running..
