### ISSUE TITLE
Opening a already running Etherpad instance in the new tab disconnects the previous one.

### ISSUE THREAD

**Issue by akshat-g** [ether/etherpad-lite#2648]
I started my first etherpad instance (name - hello) and get redirected to localhost:9001/p/hello. If I visit the same url in the new tab then old instance gets disconnected and new etherpad instance is connected. Is this a feature?
How can I run same etherpad instance in two different tabs in the same browser without getting any one of them disconnected?

**Comment by JohnMcLear** [comment]
Duplicate

**Comment by akshat-g** [comment]
@JohnMcLear - I looked into all the open issues but could not find this sorry. Can you please throw some light whether this issue is still prevailing or what can be done eradicate this bug? Thanks

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/issues/753
