### ISSUE TITLE
HTTP API - padID

### ISSUE THREAD

**Issue by jgranduel** [ether/etherpad-lite#2652]
Hi, 

I've installed EPL-1.5.x on an intranet for testing purposes with Redis. I'm very confused with HTTP API that I cannot make work.
What is API version: 1, or 1.2.12 or should it reflect EPL version?
What is padID? not pad's name. But once EPL is installed pads can be created at once, without groups! So Pads exist so must padID! how can we find their ID ?

When I realised  PadID is $groupID$name, we might be lucky with listAllGroups() and then listPads(groupID)? What is the proper URL to get listAllGroups?
Thanks to https://github.com/ether/etherpad-lite/issues/1924 I'm just discovering, I could call listAllGroups with API = 1.1 or API = 1.2
    
    $ curl "http://my.server:9001/api/1.2/listAllGroups?apikey=myKey" 
    {"code":0,"message":"ok","data":{"groupIDs":[]}}

So no groupIDs! what's the way to get the PadIDs?

Thanks in advance for a full example. Maybe [RAML](http://raml.org/) style would help.
Best regards
jgr

**Comment by JohnMcLear** [comment]
Have you read the documentation?  It would be useful for you..  http://etherpad.org/doc/v1.5.6/#index_http_api

**Comment by jgranduel** [comment]
Sorry, my big mistake, I had missed that listAllPads was available from API >= 1.2.1. My brain was stuck with pad.domain/api/**1**/createGroupIfNotExistsFor?apikey=secret&groupMapper=7 trying testing 1.1, then 1.2 without realising I could query the API with **GET /api**.

Thanks.
