### ISSUE TITLE
Non-working left bracket

### ISSUE THREAD

**Issue by theredfish** [ether/etherpad-lite#2654]
Hi,

A little minor bug report.

- **Bug** : can't write left bracket with azerty **Altgr + 5**
  - Windows 8.1 | Chrome v42.0.2311.135m 
  - or Windows 7 | Chrome v42.0.2311.135m
  - or Windows 7 | Internet Explorer 11

- **Works** : Firefox v36.0.4

Test with https://beta.etherpad.org and https://etherpad.fr/

**Comment by JohnMcLear** [comment]
Give this branch a test @theredfish https://github.com/ether/etherpad-lite/pull/2621

Let me know if it fixes it for you

**Comment by theredcat** [comment]
No, unfortunatly it doesn't fix it : the.red.cat:9001/p/fghfgh

**Comment by JohnMcLear** [comment]
What keyboard input language are you set to?

**Comment by JohnMcLear** [comment]
Oh azerty

**Comment by theredcat** [comment]
My windows language, windows ketboard language and etherpad language are all French

**Comment by snolahc** [comment]
Maybe you could try with a real OS and a real keymap ?
</troll> sorry :)

**Comment by JohnMcLear** [comment]
Heh Windows Language pack for French is 156Mb, ridiculous.

**Comment by JohnMcLear** [comment]
Alt Gr 5 for ``[`` Works fine for me in Windows 8 Firefox on https://beta.etherpad.org

**Comment by JohnMcLear** [comment]
Heh ~I see the issue, it's treating Alt Gr F5 as strikethrough

**Comment by JohnMcLear** [comment]
Fixed in the fix-dead-keys branch which I merged into develop..  There are still issues with some dead keys though fwiw

**Comment by theredcat** [comment]
Thank you! Works for me too now
