### ISSUE TITLE
[SOLVED] Doesn't work on rasbian - DirtyDB issue

### ISSUE THREAD

**Issue by falanster** [ether/etherpad-lite#2658]
Hello guys,

Have you eve faced with the issue in rasbian?

    Ensure custom css/js files are created...
    Started Etherpad...
    [2015-05-08 17:55:08.958] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: Corrupted row at the end of the db:     {"key":"sessionstorage:4FyRqzw4LFJnpeaptN14mLzLr7gMhC6m","val":{"cookie":    {"path":"/","_expires":null,"originalMaxAge":null,"htt
        at ReadStream.<anonymous> (/home/pi/download/etherpad-lite/src/node_modules/ueberDB/node_modules/dirty/lib/dirty/dirty.js:186:28)
        at ReadStream.emit (events.js:129:20)
        at _stream_readable.js:908:16
        at process._tickDomainCallback (node.js:381:11)`

System version:

    Linux version 3.18.7-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015

**Comment by falanster** [comment]
it was clean up var/dirty.db file because it was written incorrect with overflow spave in root part.

about increase space for system is here
raspberrypi.stackexchange.com/questions/499/how-can-i-resize-my-root-partition

**Comment by JohnMcLear** [comment]
Do bin/cleanRun.sh
----- Reply message -----

**Comment by falanster** [comment]
@JohnMcLear thanks
