### ISSUE TITLE
Can't export with version 1.5.6: 403 - Can't touch this

### ISSUE THREAD

**Issue by moodlebeuth** [ether/etherpad-lite#2660]
Hello,

I can't export pads with the latest stable version (1.5.6). I always get the error message "403 - Can't touch this". requireSession & editOnly are set to: true.

I cleaned my installation with: rm -Rf src/node_modules & service etherpad-lite restart.
And I made a complete reinstall/new checkout of 1.5.6.
But same same! ;-(

Any idea, what is wrong with my installation?

Thanks & Greetings,
Michael

**Comment by JohnMcLear** [comment]
Do you get this on develop branch? cc @simong

**Comment by moodlebeuth** [comment]
Hallo John,

unfortunately yes!

Michael

**Comment by JohnMcLear** [comment]
What happens if you disable your settings one by one?  Which one is causing the issue?

**Comment by moodlebeuth** [comment]
Hello John,

sorry it was my mistake, but I checked out the master branch. With the 
develop branch the export works again with my settings. ;-)

Great! Thanks a lot!

Could you give me please a hint, what is changed in the develop branch 
since 1.5.6?

Greetings,
Michael

**Comment by JohnMcLear** [comment]
Look at the last commit to the develop repo :)
