### ISSUE TITLE
Is there a documentation on how to interact with the socket API

### ISSUE THREAD

**Issue by LukasBombach** [ether/etherpad-lite#2662]
Hi,

for my master's thesis I am writing a WYSIWYG editor with Etherpad support. The HTTP API is not very useful when it comes to real time collaboration. Is there any documentation on the socket(.io) interaction or only the source code?

Thanks,
Lukas

**Comment by JohnMcLear** [comment]
Read the changeset and easysync documentation and take a look at the node client..

https://www.npmjs.com/package/etherpad-cli-client

Questions like this really do belong on the mailing list and not the repo just FYI!

Best of luck :)

**Comment by LukasBombach** [comment]
:+1:
