### ISSUE TITLE
Can we get the improvement on maths equation support in etherpad-lite?

### ISSUE THREAD

**Issue by akshat-g** [ether/etherpad-lite#2663]
I am writing a research paper using etherpad-lite for collaboration with my fellow authors. I am familiar with most of the code base of etherpad-lite and used most of its plugins.
I found ep_mathjax plugin which provides equation facility to be not of much use for writing my research paper. ep_mathjax forms images from the latex and paste it on the editor. However we can only put equations at the starting of the line. I mean we cannot provide inline equation in the text like google docs. But may be Google docs might be using different approach for collaboration and not like etherpad where we use magic-dom ids to represent each line on the editor.

Can we here get the better approach to incorporate equations in the etherpad editor so it looks more natural? Right now Image integration for equations does not look to be much neat.
Thanks

**Comment by JohnMcLear** [comment]
What's wrong, if anything, with using an image?

Is your only beef here that the equations aren't inline?

**Comment by akshat-g** [comment]
yeah there are two features which I think should be there - 
1) Inline equation support
2) Resizing of equation image

Also I was bugged that is image the only solution for equation? Also right now that * which is inserted for every image is also a problem. Sometimes that * mark becomes visible in the text editor.

**Comment by JohnMcLear** [comment]
Then if that's the case please close this issue and open it on the ep_mathjax plugin with a clear description about what you want :)

**Comment by akshat-g** [comment]
yeah done that. Thanks :)

**Comment by RoyiAvital** [comment]
Where is the request for MathJax Plug In?
