### ISSUE TITLE
Plugin manager error.

### ISSUE THREAD

**Issue by Sergio3** [ether/etherpad-lite#2664]
Well, everything were working properly since now. I can't see the "available pulgins" list and I get the next error on console:

[2015-05-14 12:43:25.125] [INFO] console - The plugin admin page is at http://xxx.xxx.xxx.xxx:XXXXX/admin/plugins
[2015-05-14 12:43:27.031] [ERROR] console - error parsing plugins.json: [SyntaxError: Unexpected token u]
SyntaxError: Unexpected token u
    at Object.parse (native)
    at Request._callback (/var/www/etherpad-lite/src/static/js/pluginfw/installer.js:70:22)
    at Request.self.callback (/var/www/etherpad-lite/src/node_modules/request/request.js:368:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/var/www/etherpad-lite/src/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/var/www/etherpad-lite/src/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)

Any help will be appreciated.
Thank you very much.

**Comment by JohnMcLear** [comment]
Yea something is broken..
http://static.etherpad.org/plugins.html

**Comment by JohnMcLear** [comment]
cc @Gared

**Comment by JohnMcLear** [comment]
@Gared I ran ``/home/stefan/ep-plugins/loadPlugins.sh > /home/stefan/ep-plugins/loadPlugins.log 2>&1`` as your user on static.etherpad.org

**Comment by JohnMcLear** [comment]
I setup keyword monitoring.  If "undefined" on http://static.etherpad.org/plugins.json then I will get an email.  You can set this up too on uptimerobot.

**Comment by JohnMcLear** [comment]
@Gared your script is still returning ``undefined``

**Comment by JohnMcLear** [comment]
```
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
[SyntaxError: Unexpected token <

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 backend read error</title>
  </head>
  <body>
    <h1>Error 503 backend read error</h1>
    <p>backend read error</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-dfw1824-DFW 1431601061 4108992830</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
]
undefined

```

**Comment by JohnMcLear** [comment]
npm is fucked?

**Comment by JohnMcLear** [comment]
http://status.npmjs.org/ looks fine..

**Comment by JohnMcLear** [comment]
Well status.npmjs.org lies a big crock of lies..  ``npm search etherpad`` fails from every box I tried on.

**Comment by JohnMcLear** [comment]
It's back up.  a ``npm cache clean`` is required.  JOY

**Comment by JohnMcLear** [comment]
okay wtf...  cleaning works fine but then running the index script again returns undefined..  It appears as soon as you do..

```
  npm.commands.search(['ep_'], /*silent?*/true, function(er, results) {
...
```

It corrupts the local npm registry index..  @isaacs

**Comment by JohnMcLear** [comment]
Oh no, scrap that, it's even worst..  running ``npm search etherpad`` the second time retuirns "error parsing json"..    Something is really fucked with npm search/indexing ;\

**Comment by JohnMcLear** [comment]
STR:

```
npm cache clean && npm search etherpad
```
This will return the expected results..
Then
```
npm search etherpad
``` 
Will return
```
npm ERR! registry error parsing json
```
GG!

**Comment by JohnMcLear** [comment]
FWIW I emailed @Isaacs - he should be able to bump someone internal in a few hours.  I gotta grab some lunch before my next meeting, I will test on latest node while I'm eating if I can.

**Comment by Gared** [comment]
@JohnMcLear I've inserted manually the json content for the plugins as a workaround for now

**Comment by Gared** [comment]
@Sergio3 Please try again

**Comment by JohnMcLear** [comment]
Latest node installed.  Bug still exists..  Jesus :|

**Comment by JohnMcLear** [comment]
Upstream bug fixed :)
