### ISSUE TITLE
Users who have not identified themselves could be reminded to do so

### ISSUE THREAD

**Issue by SpamapS** [ether/etherpad-lite#2676]
Often when running large sessions in the OpenStack summit, we stop to remind people to attach a name to their chat and colorized-updates. It would be quite cool if a tiny pop up pointed people to the name control if they had not identified themselves when they start editting.

**Comment by JohnMcLear** [comment]
https://www.npmjs.com/package/ep_prompt_for_name

Please use this when searching for features for Etherpad: http://static.etherpad.org/plugins.html

**Comment by SpamapS** [comment]
That's really great, thank you for directing me to it!
