### ISSUE TITLE
Etherpad and the keyboard compose key

### ISSUE THREAD

**Issue by Natim** [ether/etherpad-lite#2677]
In order to type complicated characters on a english keyboard for instance we can use the compose key to type some characters (i.e —, é, ç, à)

With Etherpad you must be really fast in order to type both characters before etherpad updates the cursor (half a seconds maybe less)

I would like a way (from the interface maybe) to change this frequency in order to be able to type easily french texts with an english keyboard.

**Comment by JohnMcLear** [comment]
We already have an issue for this, checkout the dead keys issue.  Thanks!

**Comment by Natim** [comment]
I search for compose before creating this ticket and didn't find anything, I search with dead key and keys without success either. Coud you please add a link to the issue you are talking about?

Thanks.

**Comment by Natim** [comment]
Related:
- https://github.com/ether/etherpad-lite/issues/2539
- https://github.com/ether/etherpad-lite/pull/2621

**Comment by Natim** [comment]
It seems to work well on https://beta.etherpad.org/ though.
