### ISSUE TITLE
Pad settings always set to default instead of using cookie

### ISSUE THREAD

**Issue by R1kk3r** [ether/etherpad-lite#2679]
When an anonymouse user set his name and move to another pad, the name and color is saved. But when the user change his settings "chat and user always visible" for example, then, they are reset to default (from settings.json) when moving to another pad.

Seems like the "cookie thing" is not working properly.

**Comment by JohnMcLear** [comment]
Are you sure?

Works fine for me..

https://beta.etherpad.org

Can you replicate here?

**Comment by R1kk3r** [comment]
https://beta.etherpad.org works fine. When you have settings.json with "alwaysShowChat" and "chatAndUsers" set to "true" then the user's preferences are overwrited each time the user access to a new/existing pad, regardless if a cookie contains other preferences.

From my point of view, these settings should apply only when you first connect to a pad. Afterwards, if the user change these settings (saved in the cookie), they should overwrite the default one (from settings.json) when accessing any pad during the user session.

**Comment by JohnMcLear** [comment]
They are forced settings, do other settings behave differently?

**Comment by R1kk3r** [comment]
I made some testing (last version 7e38e2c2b1876a1f03b32824495f747ea16d3eb2)  with many different padOptions:

```
  "padOptions": {
    "noColors": false,
    "showChat":false,
    "showLineNumbers": true,
    "useMonospaceFont": true,
    "userName": true,
    "userColor": false,
    "rtl": false,
    "alwaysShowChat": true,
    "chatAndUsers": false,
    "lang": "en-gb"
  },
```

#### noColors
Enable/Disable the possibility to have user color in Etherpad.

But it does not disable the checkbox inside user preference. So the user can try to check/uncheck it without making any difference.

**improvement :** Mark the checkbox as greyed inside user preference box. Maybe specify in comments that is option overwrite the "userColor" option.

#### showControls
Disable/Enable the toolbar. 

If disable, a user can activate it with Firebug for example (by modifying HTML). If a plugin like "fileupload" was used before setting this option to "false", then an attacker can reactivate the toolbar and upload file (php?). Seems dangerous...

**improvement :** Don't just hide the toolbar, but remove it from the HTML source.

#### showChat
Enable/Disable a minified chat window in case of "alwaysShowChat" set to false.

**improvement :** Add this option in the user preference box too.

#### showLineNumbers
Enable/Disable line numbering.

If set to "true", user can override it through the user preference box and the choice is saved between pad.
If set to "false", user can override it through the user preference box **but** the choice is **not** saved between pad.

**improvement :** Keep the user choice about showing line number even if set to "false" as default value.

#### userName
No idea what this option is doing... Seems to have no effect at all.

#### userColor
Enable/Disable user color.

Can be overrided by user in both case ("true", or "false").
Have no effect if "noColor" is set to "true".

**improvement :** Add a comment about the dependence with "noColor" option.

 #### rtl
Enable/Disable right to left.

If set to "true", the checkbox in user preference is not checked.

**improvement :** Fix the bug in user preference by enabling the checkbox if this option is set to true.

 #### alwaysShowChat
Enable/Disable the chat panel.

If set to "false", user can overwrite the value and it's saved between pad.
If set to "true", user can overwrite the value for the current pad only (not saved between pad).

**improvement :** Keep the user preference between pad for both case.

 #### chatAndUsers
Enable/Disable both chat and user panel.

If set to "false", user can overwrite the value and it's saved between pad.
If set to "true", user can overwrite the value for the current pad only (not saved between pad).

**improvement :** Keep the user preference between pad for both case.

#### General
Some options are just default value for the user preference while other options disable completely an etherpad functionnality. It should be nice to add comments to make the difference between these two kind of option clear.

**Comment by JohnMcLear** [comment]
You are missing the point here, padOptions is designed to set the default then it's up to the user if they want to change behaviour.  I'd suggest a separate group of settings for forced/restricted behaviour. 

RE showControls I agree it might make sense to not render the HTML,  please create a separate issue for that.

RE showLineNumbers sounds like a bug, please create a separate issue for that.

RE userName I'm not sure either without looking at the source

I'd happily merge a pull request fixing these bits if you have time to fix?

**Comment by R1kk3r** [comment]
No time right know but in a few weeks yes I will.

**Comment by JohnMcLear** [comment]
Re toolbar it makes no sense to change this as a user could just change URL and get toolbar.  The right way would he to modify your settings.json removing the items from there or use the read-only URL
