### ISSUE TITLE
Won't install etherpad-lite on Debian Jessie

### ISSUE THREAD

**Issue by julpec** [ether/etherpad-lite#2682]
Hello

I tried to install etherpad-lite on Debian Jessie but bin/installDeps.sh gave me the error : 

> Please install node.js ( http://nodejs.org )

Strange because I have just installed nodejs with packet manager. My nodejs version is 0.10.29.

In the `installDeps.sh` script, I found this lines : 

> hash node > /dev/null 2>&1 || {
>  echo "Please install node.js ( http://nodejs.org )" >&2
>  exit 1
>}

and this lines : 

> #check node version
> NODE_VERSION=$(node --version)

I changed `node` for `nodejs` in this lines and it's working… the script is finding nodejs installed on my Debian Jessie. So, to fix you have to change this lines for : 

> hash nodejs > /dev/null 2>&1 || {

and

> NODE_VERSION=$(nodejs --version)

Regards

**Comment by julpec** [comment]
To run properly etherpad-lite, you have to change the last line in `bin/run.sh` : 

> node $SCRIPTPATH/node_modules/ep_etherpad-lite/node/server.js $*

to : 

> nodejs $SCRIPTPATH/node_modules/ep_etherpad-lite/node/server.js $*

**Comment by JohnMcLear** [comment]
Read the docs.  Install nodejs from Source
