### ISSUE TITLE
Etherpad shouldn't print terminal sequences into the file log

### ISSUE THREAD

**Issue by yurivict** [ether/etherpad-lite#2685]
You need to only print terminal sequences when the output is an actual terminal.

**Comment by JohnMcLear** [comment]
Please elaborate

On 31 May 2015 05:36, yurivict <notifications@github.com> wrote:

You need to only print terminal sequences when the output is an actual terminal.

**Comment by yurivict** [comment]
When piped to file, log looks like this

````
Started Etherpad...
^[[33m[2015-05-30 21:26:58.721] [WARN] console - ^[[39mDirtyDB is used. This is fine for testing but not recommended for production.
^[[32m[2015-05-30 21:27:00.402] [INFO] console - ^[[39mInstalled plugins:
^[[32m[2015-05-30 21:27:00.439] [INFO] console - ^[[39mReport bugs at https://github.com/ether/etherpad-lite/issues
^[[32m[2015-05-30 21:27:00.442] [INFO] console - ^[[39mYour Etherpad version is 1.5.6 (b049f4b)
^[[32m[2015-05-30 21:27:00.622] [INFO] console - ^[[39mYou can access your Etherpad instance at http://0.0.0.0:9001/
^[[33m[2015-05-30 21:27:00.622] [WARN] console - ^[[39mAdmin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
````

**Comment by JohnMcLear** [comment]
Sounds like a log4js bug? We use that...

On 31 May 2015 10:46, yurivict <notifications@github.com> wrote:

When piped to file, log looks like this

Started Etherpad...
^[[33m[2015-05-30 21:26:58.721] [WARN] console - ^[[39mDirtyDB is used. This is fine for testing but not recommended for production.
^[[32m[2015-05-30 21:27:00.402] [INFO] console - ^[[39mInstalled plugins:
^[[32m[2015-05-30 21:27:00.439] [INFO] console - ^[[39mReport bugs at https://github.com/ether/etherpad-lite/issues
^[[32m[2015-05-30 21:27:00.442] [INFO] console - ^[[39mYour Etherpad version is 1.5.6 (b049f4b)
^[[32m[2015-05-30 21:27:00.622] [INFO] console - ^[[39mYou can access your Etherpad instance at http://0.0.0.0:9001/
^[[33m[2015-05-30 21:27:00.622] [WARN] console - ^[[39mAdmin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json

**Comment by yurivict** [comment]
This same issue came up with git ~6 mo ago, in relation with pager. You might want to look up that discussion in archives. I remember this was very tough to guess if pager can handle colors. They ended up insisting on colors, but involved guess work makes system error prone.  No general way to do this accurately.

You need to either go this hard way. Or just disable colors when output isn't the terminal, which is 100% easy.

**Comment by JohnMcLear** [comment]
I'd accept a pull request if you have an easy fix
----- Reply message -----

**Comment by yurivict** [comment]
Now when I looked, you have a lot of copy-pasted code with terminal sequences.
You need to use some standard js package (like this one https://github.com/sindresorhus/chalk) Then either this package will handle printing correctly, or it will be easy to fix it. But not with the current hard-coded style.

**Comment by Gared** [comment]
@yurivict See #2835

**Comment by leegee** [comment]
One solution might be to look at this in reverse: only render in colour if requested to do so.
