### ISSUE TITLE
Using dependencies on the client side

### ISSUE THREAD

**Issue by tm-linkwerk** [ether/etherpad-lite#2691]
Hi,
when I declare dependencies in my plugin's package.json they are installed into the plugin's node_modules folder. I want to use these dependencies in client-side hooks, but the files in the node_modules folder are not accessible on the client side, and so require('my-dep') fails.

I don't want to commit my dependencies to the static folder, are there other possibilities?

**Comment by JohnMcLear** [comment]
We don't support client side dependency requires.  Your best bet is to include the javascript in ``your_plugin/static/js/lib`` or something

TLDR; package.json dependance is for server side only packages.
