### ISSUE TITLE
autoscroll notes if scroll bar is at the bottom

### ISSUE THREAD

**Issue by m4chinations** [ether/etherpad-lite#2692]
Keeping up with notes should be a glance-action (just glance over to see what's been shared), but if notes go past the bottom of your view, you have to scroll down.

This is a bit annoying, when the view could auto-scroll down to always keep the latest notes visible.

In order to keep this from bouncing down, it should only auto scroll when you're already at the bottom of the notes.

**Comment by JohnMcLear** [comment]
I could probably make this in a few hours if you wanted to create a bounty for the plugin?
