### ISSUE TITLE
Question: update css class of text client-side

### ISSUE THREAD

**Issue by Eragon666** [ether/etherpad-lite#2693]
Hello,

For a university project we are using etherpad. We have extended etherpad with a plugin, but we couldn't find a good solution for the following problem. 

We are building an app that can do (realtime) analysis on the text in the pad. The analysis will be shown in a sidebar (this is working fine), but we also want to show more analysis/feedback inside the pad. One of the analysis we want to show is which paragraphs are not correct, for that we added a border to the magicdivs inside the iframe. Now the problem: we also want to give feedback for seperate words and sentences. But if we find and select a word/sentence with jQuery and if we add a class or css style the pad gets updated and the changes are removed. 

How can we select something (with jQuery), and add a class (it doesn't need to be saved server side, and it may be removed if the user edits the row). We tried lot's of functions and checked other plugins, but couldn't find a proper way. The most promising function is 'editorInfo.ace_performDocumentApplyAttributesToRange()' but we couldn't find a good example, and we can't figure out how to set the range. 

Can someone please give us some tips and/or example code on how to accomplish this?

Kind regards,

Matthijs

**Comment by JohnMcLear** [comment]
Take a look through my plugins for reference..  You need to add an attribute to the target span/element.  ep_comments does this for example..  https://github.com/JohnMcLear/ep_comments/blob/master/static/js/index.js#L758

If you still need help I'm available as a gun for hire.
