### ISSUE TITLE
IE9: Import in IE9 breaks pad

### ISSUE THREAD

**Issue by goldquest** [ether/etherpad-lite#2694]
When I try to import a txt file on Win7 IE9, the pad hangs on "Loading" and the server logs following:

```
[2015-06-17 18:46:55.091] [WARN] client - Failed assertion: line assembler not finished:Z:bj<bg|8-bj+3$AAA -- { 
errorId: 'mAW939jmA6z58CaJ5gmV',  
msg: 'Failed assertion: line assembler not finished:Z:bj<bg|8-bj+3$AAA',  
url: 'https://lab.cms.hu-berlin.de/eplite/p/g.1hG2uIMZyIphGEtJ$jojo',  
linenumber: 1,  
userAgent: 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C)' }
```

- etherpad-lite: a0aa9470a383e5361e544a9ba76fad06f69fd628 (Jun 11, 15)
- node: v0.10.36

**Comment by JohnMcLear** [comment]
Can you replicate in other IEs?
Can you replicate on beta.etherpad.org?
More info would be useful!

**Comment by goldquest** [comment]
I have one IE9 in VirtualBox and an IE11 on SaaS. where the import doesn't work at all.
With IE9, I can't access beta.etherpad.org at all.

What kind of information can I provide to you?

**Comment by JohnMcLear** [comment]
http://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/ should cover it, if not let me know

**Comment by goldquest** [comment]
Hmm, maybe some steps to replicate:
1. Get Windows 7
2. Get Internet Explorer 9 (maybe as VM from modern.ie)
3. Make a new txt file with content: "AAA"
4. Open a new group
5. Open a new grouppad
6. Click on Import/Export and try to import the txt file.
Now the pad reloads and the user sees following:

![screenshot 2015-06-17 19 34 16](https://cloud.githubusercontent.com/assets/1248214/8214231/22b08416-1528-11e5-8a62-cfbee5c37643.png)

When I try to import a file in a normal pad, it just tells me, that the import failed.

**Comment by goldquest** [comment]
After this problem, the pad is broken for everybody.

Expected behaviour:
Either import file successfully, 
or fail, as in normal pads.

**Comment by JohnMcLear** [comment]
Is this group pads only?

**Comment by goldquest** [comment]
Yes

--
mobile

**Comment by goldquest** [comment]
I have access to a Windows Machine, later and will check other ie versions

**Comment by JohnMcLear** [comment]
@eldiddio can you confirm please?

**Comment by eldiddio** [comment]
I have tested this with Windows 8.1 and Chrome and i get the same behaviour.
Created a new text document with AAA in the body.
Imported into a Group Pad
Group pad is now broken and sticks on loading.

**Comment by goldquest** [comment]
So ad137fa4c876f9d7dc2d8113d8bcef9b9425ce0c resolved this error.
Import now works on Win7 IE9 in group and normal pads
