### ISSUE TITLE
getAttributesOnLine has no docs?

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2698]
```
./AttributeManager.js:103:  getAttributesOnLine: function(lineNum){
```

**Comment by JohnMcLear** [comment]
https://github.com/JohnMcLear/ep_comments/blob/master/static/js/index.js#L1071 is an example of it being used.

**Comment by Tristramg** [comment]
I think this issue is no longer relevant: https://github.com/ether/etherpad-lite/blob/develop/src/static/js/AttributeManager.js#L161-L164

**Comment by muxator** [comment]
Yep, closing, thanks.
