### ISSUE TITLE
mismatch error setting raw text in setDocAText / assertion errors

### ISSUE THREAD

**Issue by LaKing** [ether/etherpad-lite#2700]
While updating codepad and checking compatibility a bug came up with the recent etherpad version.
It causes a client-freeze with an endless loading ...

Here is some sample code:
```javascript
var padManager = require("ep_etherpad-lite/node/db/PadManager");
var padMessageHandler = require("ep_etherpad-lite/node/handler/PadMessageHandler");

exports.padCreate = function(hook, context) {
context.pad.setText("TEST");
padManager.getPad(context.pad.id, null, function(err, value) {
    if (err) throw err;
	padMessageHandler.updatePadClients(value, function() {});
    });
};
```

The error message leads to ace2_inner.js line ~770. 
```javascript
    if (rep.alltext != atext.text)
    {
      dmesg(htmlPrettyEscape(rep.alltext));
      dmesg(htmlPrettyEscape(atext.text));
      throw new Error("mismatch error setting raw text in setDocAText");
    }
```
With the test data above rep.alltext is TES and a newline character, and atext.text is TEST. As it seems, the last character always disappears and a newline character always appears.
The pad content is just TES
 
Is this a bug, Could we fix this?  Or is my method for setting pad text at pad creation incorrect?

**Comment by JohnMcLear** [comment]
You said this bug exists in the latest version, did you do regression testing?

**Comment by LaKing** [comment]
Okay, I tryed to reproduce it in a more blank, enviroment, and the error didnt show up, ..

However, I still get issues on my development enviroment. Messages like:
Error: Failed assertion: line assembler not finished:Z:j>27s|1-j|2g+289+2$

I have the feeling this might be a timing-related issue. ...

**Comment by LaKing** [comment]
Well, the blank enviroment was using the latest zip release, and there is no such problem.
Something broke between the latest release and the current git version.

Steps to reproduce the problem.
Install etherpad from the latest git release.
Install the unreleased ep_test ... here is a bash script that will do it.

```bash
#!/bin/bash

## set this directory according to your enviroment
tp="/srv/etherpad-lite/node_modules/ep_test"

## create the plugin directory
mkdir -p $tp

## ep.json with a server side hook
cat > $tp/ep.json <<EOF
{
    "parts": [ 
        {
            "name": "ep_test",
            "hooks": {
                "padCreate": "ep_test/index:padCreate"
            }
        }
    ]
}
EOF

## on pad-creation we set TEST as text, and update the pad.
cat > $tp/index.js <<EOF
var padManager = require("ep_etherpad-lite/node/db/PadManager");
var padMessageHandler = require("ep_etherpad-lite/node/handler/PadMessageHandler");

exports.padCreate = function(hook, context) {
context.pad.setText("TEST");
padManager.getPad(context.pad.id, null, function(err, value) {
    if (err) throw err;
    padMessageHandler.updatePadClients(value, function() {});
    });
};
EOF

## if there is no package.json, etherpad crashes so we make one
cat > $tp/package.json <<EOF
{
  "name": "ep_test"
}
EOF

## run this script as etherpad user, or chown the created files
chown -R codepad:srv $tp

## restart etherpad
```
You will see the bug instantly, when creating a new pad.

Existing pads tend to break too.
As far as I see, some assertation error breaks something in the database, and once the database-entry of the pad is broken, the mismatch error shows up when loading the pad.
The assertation error is IMO server side.

**Comment by JohnMcLear** [comment]
@LaKing okies if it's a change in Etherpad do a bisect to figure out which commit b0rked it.

http://mclear.co.uk/2013/04/02/using-git-bisect-to-debug-etherpad-issues/

**Comment by LaKing** [comment]
I did a regression test manually / written in bash. 

BROKEN: HEAD is now at ee0368f Merge pull request #2649 from xavidotron/develop
WORKIN: HEAD is now at a1893ec Merge pull request #2650 from ether/iframe-issues

So if I step back 26 steps from the current, it's still broken and at 27 steps back from current it works ok.

**Comment by JohnMcLear** [comment]
Hrm, https://github.com/ether/etherpad-lite/blob/develop/tests/backend/specs/api/pad.js#L198 seems to cover this issue already and it's passing fine..  So maybe ththe API is working fine but ``context.pad.setText("TEST");`` is doing something incorrect..  I'm not sure how to create a test that does a frontend task then checks it on the backend..  I guess a frontend test would be required but doing that would also be a pain in the ass...

**Comment by xavidotron** [comment]
I think Etherpad assumes some places that a pad will always end with a newline.  (Which I guess is the reason for the behavior before my #2649, though I didn't realize this at the time.)  Possibly the right behavior is for setText() to only add a newline if the parameter doesn't already end with a newline.  I expect that would fix this issue while still avoiding my problem where a series of getText() and setText() calls would keep adding additional newlines to the end of the pad.

**Comment by JohnMcLear** [comment]
@xavidotron might be worth submitting a PR with that fix?

**Comment by LaKing** [comment]
.. looks much better. .)

Thank you. :+1:
