### ISSUE TITLE
Possible error in settings.json / settings.json.template or missing documentation

### ISSUE THREAD

**Issue by rabanti-github** [ether/etherpad-lite#2704]
There is a possible problem with the file settings.json / settings.json.template, respectively missing documentation about a part of the settings.
If uncommenting the section for SSL support, an error occurs after starting etherpad (unexpected string). The error can be resolved by adding a comma after the second line “cert”:
Before:

```
  "ssl" : {
            "key"  : "/path-to-your/epl-server.key",
            "cert" : "/path-to-your/epl-server.crt"
            "ca": ["/path-to-your/epl-intermediate-cert1.crt", "/path-to-your/epl-intermediate-cert2.crt"]
          },
```

After:

```
  "ssl" : {
            "key"  : "/path-to-your/epl-server.key",
            "cert" : "/path-to-your/epl-server.crt",
            "ca": ["/path-to-your/epl-intermediate-cert1.crt", "/path-to-your/epl-intermediate-cert2.crt"]
          },
```

But there is also a problem with the third line “ca”. The documentation (https://github.com/ether/etherpad-lite/wiki/Providing-encrypted-web-access-to-Etherpad-Lite-using-SSL-certificates) says: “Some intermediate files will be generated but not explained here, too keep it concise. Read the page in "References" if you are curious what they are for.”
But I could not figure out where or when these files are created. Are they created anyway? etherpad terminated because of the intermediate crt files are not found. At least not, if the keys are generated according the documentation (see above).
Therefore, I erased the line “ca” and etherpad worked just fine in SSL mode:

Before:

```
  "ssl" : {
            "key"  : "/path-to-your/epl-server.key",
            "cert" : "/path-to-your/epl-server.crt",
            "ca": ["/path-to-your/epl-intermediate-cert1.crt", "/path-to-your/epl-intermediate-cert2.crt"]
          },
```

After (<b>working solution</b>; paths must be adjusted naturally):

```
  "ssl" : {
            "key"  : "/path-to-your/epl-server.key",
            "cert" : "/path-to-your/epl-server.crt",
          },
```

1)  Are the template settings not up to date?
2)  Is there missing information in the documentation about these intermediate crt files?

<i>
Further info about my configuration in case of obscurities:
Etherpad was installed on a Synology with DSM5.2 (underlying Linux system).
The installation was made according the official documentation. Sources were pulled from the repository over git.
</i>

**Comment by JohnMcLear** [comment]
Due to https://github.com/ether/etherpad-lite/pull/2636

Bump @andreassolberg

**Comment by rabanti-github** [comment]
One could consider to separate the settings for SSL and CA support like this:
```
  "ssl" : {
            "key"  : "/path-to-your/epl-server.key",
            "cert" : "/path-to-your/epl-server.crt"
          },
/*
  "ssl-ca" : {
            "key1"  : "/path-to-your/epl-intermediate-cert1.crt",
            "key2" : "/path-to-your/epl-intermediate-cert2.crt"
          },
*/
```
It is a little bit confusing at the moment. The CA part could remain commented, whereas the common SSL part would be a separate block. The documentation for the CA part could also be (kind of) separated.

**Comment by JohnMcLear** [comment]
Gonna let @andreassolberg maintain this.
