### ISSUE TITLE
ERROR: module at "ep_etherpad-lite/static/js/colorutils" does not exist

### ISSUE THREAD

**Issue by bcorrero** [ether/etherpad-lite#2705]
I am experiencing the same error described here from August 2013:
https://github.com/ether/etherpad-lite/issues/1856

Is there any way to avoid this by automatically clearing the cache or something like that?

I am getting the same error after running Etherpad as a service for a few hours. I get this exact initial error once and then after that it returns a simple "connection refused" error and won't even display Etherpad. Because of this, we simply cannot leave it running on the server since it crashes after a few hours. This would require multi-daily restarts of the service which defeats the entire purpose of having it permanently running on a server.

An error occured while loading the pad
Uncaught Error: The module at "ep_etherpad-lite/static/js/colorutils" 
does not exist. in http://*********:9001/static/js/require-kernel.js 
(line 596)

Brian

**Comment by JohnMcLear** [comment]
Duplicate.  Don't do this.

**Comment by JohnMcLear** [comment]
The error you are seeing isn't killing the instance, something else must be killing your Etherpad instance.  Perhaps a script or so?

**Comment by bcorrero** [comment]
I notice I can only see that error one time before the instance gets killed and then doesn't even display that error - just a straight up "page not found"/"connection refused" error.

I am trying to run Etherpad in the background using a Linux screen.  This works for several hours but then eventually crashes every time.  I notice you mentioned a "cache" error on the original Github issue - do you have any idea if there's a way to automatically clear the cache on a regular basis?

Aside from that, any information around what types of "scripts" might be running/killing the instance?  Is there a default log that would have this?  

I'm not seeing anything in the standard directory locations.

**Comment by JohnMcLear** [comment]
I don't think the cache is related.. You could try set ``minify`` to ``false`` and ``maxAge`` to ``0`` in ``settings.json`` and see if that fixes it?

**Comment by bcorrero** [comment]
Sure thing - will try those changes and keep you posted if the error returns.  Usually takes less than 24 hours to get the error so we should have a good idea whether that worked or not by tomorrow.

**Comment by bcorrero** [comment]
So far so good.  The above changes appear to have resolved our issues.  The instance was consistently crashing after 4-5 hours of light-moderate usage but has now been going strong 40+ hours without any issues.

Thanks for your help John!

Brian

**Comment by JohnMcLear** [comment]
Once you are happy, try re-enable minify and set maxAge to some rediculously large value IE add 10 extra 0's and see if it still crashes.

It might be that minification is crashing during trying to write to the filesystem due to some permission issue or so?

**Comment by bcorrero** [comment]
Yeah I was thinking about a permission issue as well and tried changing permissions on a few folders but probably not the right ones.

Do you know the specific directory it tries to write to?

I noticed an error with user 'etherpad' trying to delete files in /var/ or /tmp/ when I kick off /run.sh so I changed permissions on those folders but don't think that captured it fully.

**Comment by JohnMcLear** [comment]
``var/``

**Comment by bcorrero** [comment]
Hey John,

Etherpad has been running flawlessly for us the last month since setting minify to false and MaxAge to 0 so I'm hesitant to tweak them.

What are the long-term impacts for leaving minification off and maxage at 0?  Will certain aspects of the server eventually max out and crash or am I mostly just doing things less efficiently than I could?

If the trade-off is only an increase in I/O, costs, etc, then we're probably willing to sacrifice that in favor of 100% uptime.  We're running this on a very small EC2 instance (m3.medium) that costs about $500 for an entire year of 24/7 uptime so even a significant % increase over that is fine for us.

Brian
