### ISSUE TITLE
Windows 7 - Etherpad 1.5.6 - "The filename or extension is too long"

### ISSUE THREAD

**Issue by miketran777** [ether/etherpad-lite#2706]
I am not a coder, but CTO that would like to use etherpad...I just downloaded the latest version to my local Windows 7 machine so that I can do some testing...But the zip file cannot finish extracting (using Winzip) due to having a directory structure deeper than allowed by windows...What am a missing?  I must be missing something...

Thanks!

**Comment by JohnMcLear** [comment]
CTO's don't read error logs? :P

The error will state the path is too long, windows can't handle log file paths.  You have 2 options.

1) Extract it to a less deep folder location IE c:\
2) Use something other than the native extract tool to extract it..  http://www.7-zip.org/ is your friend :)
