### ISSUE TITLE
CSS width bug on timeslider #editbar in Chrome on Mac

### ISSUE THREAD

**Issue by benlind** [ether/etherpad-lite#2708]
I'm using Chrome v43.0.2357.130 on a Macbook Pro OS 10.10.3.

In the timeslider for an etherpad, the "Return to pad" button at the top right is hidden. I tracked the problem down to the width of the `.timeslider-bar #editbar` element. That width is set to 180px by timeslider.css, which apparently is too small for Chrome.

Changing the width to `auto` fixed the problem for me.

**Comment by JohnMcLear** [comment]
Pull request local but please test responsive layout too with that change in..

On 26 Jun 2015 16:41, Ben Lind <notifications@github.com> wrote:

I'm using Chrome v43.0.2357.130 on a Macbook Pro OS 10.10.3.

In the timeslider for an etherpad, the "Return to pad" button at the top right is hidden. I tracked the problem down to the width of the .timeslider-bar #editbar element. That width is set to 180px by timeslider.css, which apparently is too small for Chrome.

Changing the width to auto fixed the problem for me.
