### ISSUE TITLE
Better default fonts, better font fallbacks

### ISSUE THREAD

**Issue by charakterziffer** [ether/etherpad-lite#2713]
I’m not so lucky with the font selection of etherpad lite. It’s partly not portable, usable or don’t give a professional impression. I base the following suggestion on three assumptions:

a) The fonts are for reading text.
→ Symbol fonts like Wingdings are useless for formatting a document. I’d suggest to remove Symbol, Webdings and Wingdings from the selection. Why should one want to have a text in this fonts?

b) Etherpad is not for graphical design (evidence: no images, borders, columns, …) but for creating well structured, readable text.
→ Better provide a small, great font choice than a list of crappy ones. I’d suggest to remove Impact, Lucida (it’s enough to have Georgia), Trebuchet and Tahoma. For the last one I’d add Segoe UI to have modern neutral sans-serif, which is narrower than Verdana (with Tahoma as one fallback).

c) Etherpad runs on different platforms, this should be considered when defining the selectable fonts and their definiton in CSS.
→ The CSS fallback fonts are insufficient at the moment. For example, if I select the font named Serif, I actually choose MS Serif. Because it is not installed on my Ubuntu laptop (or on a Mac or any other non-Windows machine) and no fallback is provided I get the default sans-serif font defined in my browser instead.

Here’s my suggested font list with the corresponding CSS font definition and some comments why I choose these fallbacks.

**Normal**
`'Helvetica Neue',Arial,sans-serif`
Helvetica Neue is technically better on Macs – and only there installed. So Windows user get Arial anyway. To define a fallback for Linux users isn’t necessary, because their OS has codified an appropriate fallback for Arial.

**Monospace**
`monospace`
Use the font which the user has defined as the monospace font in the browser. There are a lot of better monospaced fonts than Courier New, e.g. Consolas, Andale Mono, Lucida Console, Inconsolata, Source Code Pro, Fira Mono, … Respect the users’ choice.

**Open Dyslexic**
`OpenDyslexic`
Not sure, if it should came so early in the selection list, for non-dyslexic users it’s just ugly and (in my opinion) hinders the recognition of words.

**Comic Sans**
`Comic Sans, Comic Sans MS, cursive`
Personally I don’t like this font but a lot of people do, because it looks handwritten. On Macs its names comes without the MS part, cursive would be the generic fallback.

**Georgia**
`Georgia, 'Bitstream Charter', serif`
It’s rare to find computers without Georgia installed, but providing the serif fallback can’t go wrong.

**Lucida Sans**
`'Lucida Sans', 'Lucida Grande', 'Lucida Sans Unicode', 'Luxi Sans', sans-serif`
On Mac it’s called Lucida Grande. Lucida Sans Unicode doesn’t have italic nor bold but a lot more characters so it comes later in the list. Luxi isn’t that widely used on Linux PCs anymore but it’s the exactest design.

**Palatino**
`Palatino, 'Palatino Linotype', 'URW Palladio', Georgia, serif`
The first for Macs, second for Windows. Palladio is a similar version for Linux.

**Segoe UI**
`'Segoe UI', Myriad, Calibri, UnDotum, Optima, Tahoma, sans-serif`
A neutral font more humanistic than Arial but not as much as Lucida Sans. Difficult to find fallbacks for Mac and Linux, but UnDotum and Optima could fit.

**Times New Roman**
`'Times New Roman', Times, serif`

**Verdana**
`Verdana, 'DejaVu Sans', sans-serif`
DejaVu Sans for the Linux users who don’t have the Microsoft Core Fonts installed.

**Sans Serif**
`sans-serif`
As said with Monospace: Please respect the user settings in the browser.

**Serif**
`serif`
As said with Monospace: Please respect the user settings in the browser.

So the list would contain the generic Sans, Serif and Monospace, defined by the user in the browser settings; three sans fonts (humanistic Lucida Sans, neutral Segoe, sturdy Verdana), three serif fonts (narrow Times, classical Palatino, robust Georgia), one handwritten (personal Comic Sans), one deemed to support dyslexic readers (Open Dyslexic) and the Normal default.

If one wants to be more minimalistic, I’d suggest leaving out the Sans (and make the Normal the browsers sans-serif), Segoe, Times (it’s the standard serif in most browsers anyway) and OpenDyslexic (I don’t think it really makes reading easier other than Comic Sans could do. But I’m not dyslexic, the font surely was desired by someone who is and the readability of fonts often depend on habits and personal preferences, so it may be good to have OpenDyslexic nevertheless).

**Important note:**
This issue is not about _“I want to have more fonts”_, it’s not about _“I want a plug-in to use my own fonts”_ and it’s not about _“you should contain my favorite fonts”_. It’s about making a better standard, providing usable, cross-plattform and sound font defaults.

**Comment by JohnMcLear** [comment]
Happy to see a pull request with these changes in.

We won't be dropping the Open Dyslexic font though, that is a ridiculous proposal.

I also disagree with removing fonts that are currently being used (a).  That is a bad idea.

Happy to see fixes for (c)

**Comment by charakterziffer** [comment]
A correction: Palladio (fallback for Palatino) has to be reference with `URW Palladio L` in the CSS.

Would really have been great to discuss a) and b) more factual – not just “ridiculous” or “bad idea“. Why is it bad to kick out some fonts? Backwards compatibility? It would make the font list more concise, clearly and therefore more useful. You seem to have a strong opinion about it, would be nice to know why.

I would also be interested if you know some ressources about OpenDyslexic. I’ve only found [a publication about it](http://www.taln.upf.edu/system/files/biblio_files/assets2013.pdf), which had no significant results. What was your motivation to include it?

I’ll try a pull request in the next days. I’ve never done that before with an other project but I’ll figure it out.

**Comment by JohnMcLear** [comment]
Memoving fonts that are already use is obviously a bad idea, I feel like your trolling me asking me why that might be the case?

Open dyslexic font gives us the ability to provide better accessibility, something we're keen on.  Why would you want to remove it?  For what gain?  "To be more professional impression" is not a good enough argument to sacrifice accessibility for those who need it.  We're not Apple.

Good luck w/ the PR, let me know if you get stuck.

**Comment by charakterziffer** [comment]
I’m sorry that you feel to be trolled, that’s really not my intention. I just can’t understand how this font selection was made. I think it’s annoying to have at least three options which aren’t usable at all.

Webdings and Windings would make sense, if you could format single characters. But if you only could set the whole text in this fonts: Seriously, what’s the point? Yu can’t read anything anymore and the fonts aren’t combatible to each other or any other font, because they don’t use standardized Unicode points (like ☺ ✓ ♥ or Σ).

The [font Symbol](http://www.microsoft.com/typography/fonts/family.aspx?FID=15) doesn’t even contain a single latin character (no a–z, no A–Z)! It was developed in times before the Unicode standard and only contains a greek alphabet, mathematical symbols and some punctiation. Nowadays these 190-something symbols are integrated in one font file (Times New Roman shipped with Windows 7 contains all the Symbol characters and a lot more). So using the font Symbol will almost always result in getting something else.

It’s like having a menu to choose from where two dishes are inedible and one consists of an empty blade. That’s what I meant with “not professional”.

Concerning OpenDyslexic I got your point. Just wondered if you have information about that font I didn’t have.

It’s not comfy when your decisions are questioned. But believe me: Answering with only “That’s a bad idea” will bring us nowhere. (I know that sounds so trolling again, sorry) Please at least think about having less but more useful options.

Removing these three fonts, would this destroy documents set in Wingdings, Webdings or Symbol? Or would it assign the Normal font?

**Comment by JohnMcLear** [comment]
Happy to close this now?

**Comment by charakterziffer** [comment]
If you have thought about having three useless options in the list and don’t find that annoying … I’m not fully convinced.
At least you have fallbacks now, so that the working fonts are presented more true to original on different systems.

**Comment by JohnMcLear** [comment]
Yea having those isn't ideal but it could be the case some IE users are using them..  We could always hide those list options to non IE users?

**Comment by charakterziffer** [comment]
I guess the following proposal is too much, isn’t it?

Hide these three fonts for all and remove them in six months unless someone who misses them files a bug report before. So every user would still have the same functionality independent of the browser s/he uses (I think browser hacks are bad).

But of course, if there’s really someone out there who likes his/her texts in nothing but icons, removing these fonts is not the best idea.

So even while it collywobbles me – hiding Wingdings, Webdings and Symbol only for non-IE users should be okay.

[An IE user writes to a Chrome user: “Hey, look how funny, you could make little images by choosing the font Webdings. The ! is a spider!“. What’s the better pointe? 1) Chrome user: “Can’t find Webdings” or 2) “Has no effect here” – I know, I’m bad and love discussing too much. Just ignore this and have a nice day! 🕷]

**Comment by JohnMcLear** [comment]
Yea @charakterziffer send through a PR w/ your proposal, should be okay cc @Pita

**Comment by charakterziffer** [comment]
I just don’t get it. I’ve deleted my fork and forked it again (so I have the very up-to-date files). Then I edited the relevant files, cloned them locally, tested them successful in Opera, Chrome and Firefox on Ubuntu – but I don’t find the button to make a pull request so that they could be merged to your development branch. The edited files with differences are listed here:

[https://github.com/ether/etherpad-lite/compare/develop...charakterziffer:5c025dbde2d38ca8ecb76e3dcd09fb52bb4fe737]

Is that useful for you or what do I have to do?

I only commented out the three fonts so that they could be restored easily. I’ve prepared a bug report, so that IE users who miss the fonts could leave a comment there (I’ll publish the report when the files are merged). The report also contains hints what has to be done to remove the fonts completely and get clean code (so in December 2015 or July 2016, depending an how long we should wait for complaints). Is that okay so?

**Comment by charakterziffer** [comment]
And now, what’s the next step? How can this bug be closed? By the way, here’s the text of the new one which will be the reminder to remove the fonts completely:

> # Remove the fonts Symbol, Wingdings and Webdings completely

> ## Note to the Reader

> Are you an user of Internet Explorer and miss the fonts Symbol, Wingdings and Webdings in the font selection menu of Etherpad? Then you’ve found the right bug report. Just comment below that you wish to have these font options back. Because I’m curious it would be nice if you could describe for what you use the fonts in Etherpad.

> Not an user of Internet Explorer? Then you’ve probably never seen Wingdings, Webdings or Symbol on the Etherpad anyway. All three fonts use a propriatery character setting of Microsoft which is not compatible with any other font or the Unicode Standard. Only Internet Explorer shows the fonts correctly – as unreadable icons. Any other browser shows a fallback. Effectively without these three fonts the font selection is more usable to all users.

> Related bug report: [#2713](https://github.com/ether/etherpad-lite/issues/2713)

> ## Why Weren’t These Fonts Removed Completely?

> There may be Internet Explorer users out there who really love these fonts and work with them. At the moment the fonts only where hidden in the menu (pull request **##NUMBER##**) and could be brought back easily if anybody misses them. Users whose browser has a cookie containing one of the three fonts are able to keep their display setting (until they change it in the menu).

> ## What Is yet to Be Done?

> If nobody misses these fonts in a reasonable time (maybe wait until December 2015, July 2016?) the following files should be edited to remove Webdings, Wingdings and Symbol completely:

> **src/static/js/pad_editor.js**
> line 35 → 'useTrebuchetFont',…
> and lines 175–177 → if(font === "symbol")…

> **src/static/js/timeslider.js**
> lines 181–183 → if(font === "symbol")…

> **src/static/js/pad.js**
> line 609 → 'useTrebuchetFont',…

> **src/templates/timeslider.html**
> remove the comments in line 181–183

> **src/templates/pad.html**
> remove the comments in line 174–176

> **src/locales/en.json**
> lines 54–56 → "pad.settings.fontType.symbol"

> Then this bug report can be closed.

**Comment by rugk** [comment]
There are no changes in https://github.com/ether/etherpad-lite/compare/develop...charakterziffer:5c025dbde2d38ca8ecb76e3dcd09fb52bb4fe737.

See this article for how to make a pull request:
https://help.github.com/articles/creating-a-pull-request/

**Comment by charakterziffer** [comment]
Sorry, after not hearing anything for more than a year I deleted my branch. It felt that noone was interested. I just tried to recreate my changes but don’t know anymore how to test them. I’m very sorry but am no longer interested in solving this bug. At least there are better fallback fonts.

**Comment by JohnMcLear** [comment]
My guess is now Edge has their shit

**Comment by JosephPall** [comment]
While it's true that symbol fonts like <a href=" https://fontbots.com/wingdings-translator/   " >wingding</a> may not be suitable for formatting an entire document, they can still serve specific purposes and add visual elements to your content. Symbol fonts are commonly used for creating bulleted lists, adding icons or decorative elements, or emphasizing specific information. They can be useful in presentations, infographics, or specific design elements where you want to convey information in a visually appealing way. However, for general text formatting and readability, it is recommended to use standard fonts that are designed for optimal legibility. So, while symbol fonts may not be ideal for overall document formatting, they can still play a valuable role in certain contexts.
