### ISSUE TITLE
markdown export broken

### ISSUE THREAD

**Issue by azrdev** [ether/etherpad-lite#2716]
The markdown export has several flaws, the one I could remember and reproduce right now is the indentation in the second line of following example:

* first
    * second
    * third

In the export of our installation (version 1.2.12) second is wrongly indented twice.

I'd be willing to dig into the markdown export, can you point me to how and where that is implemented?

**Comment by mweinelt** [comment]
Actually we're on e509824f290c6e0e70d23a489aac0e97be7e9d20 (which is the 1.5.6 tag)

**Comment by Gared** [comment]
Markdown export is not a core feature of etherpad. You're probably using this plugin:
https://github.com/johnmclear/ep_markdown
Please file this issue there.
