### ISSUE TITLE
Cannot access admin...

### ISSUE THREAD

**Issue by miketran777** [ether/etherpad-lite#2719]
I have uncommented the user admin section and changed the password in the settings.json file, but I am still unable to access the admin section.  I get the login pop-up window, I enter "admin" for the user name and my password, but the authentication window just pops up again...

Any ideas on what would be causing this?

![image](https://cloud.githubusercontent.com/assets/8708702/8531913/9d9a8936-23f8-11e5-8de7-5b3d9ccb73ad.png)

**Comment by Gared** [comment]
Do you have cookies disabled in your browser?
Have you tried it in another browser?

**Comment by miketran777** [comment]
I have found that the changes in the settings.json file do not take affect until I run the screen utility for node.js...

**Comment by Gared** [comment]
@miketran777 Is it working for you now or do you have still problems to access the admin backend?

**Comment by miketran777** [comment]
It's working!  Thank you!
