### ISSUE TITLE
TypeError: can't convert val to string

### ISSUE THREAD

**Issue by Kevin94** [ether/etherpad-lite#2723]
TypeError: can't convert val to string in http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define at line 2597

I get this error very often when opening a pad on localhost. The problem is, that some script code (invoked after the websocket was opened) wants to access translations before these are loaded. The translation lookup returns an empty array (after printing a warning in the console), this is given to some jQuery method that doesn't expect an empty array and throws this error.

I haven't figured out completely when this weird timing problem occurs, but what I can say is:
- It sometimes also happens when the etherpad server is accessed from remote
- I haven't noticed it yet with no plugins installed, but it makes small to no difference if there are 4 or 10 plugins installed or which ones are installed
- As far as I have seen, it does only happen when the local.json file is loaded from browser cache (HTTP 304 not modified), and not when directly loaded (HTTP 200). So reloading the page without caching is my temporary workaround.

I hope you are able to introduce some lock mechanism or handling for this error. It makes setting up new plugins a pain.

System information:
OS: Linux Mint 17
Browser: Firefox 38
etherpad: current development version
node: 0.10.25

**Comment by heidar-ice** [comment]
Had same problem. Changing 'localhost' to local IP (192.168...) fixed this for me.

**Comment by nilsfr** [comment]
I consistently get this error when I have Firebug active. There is no difference if I access it through localhost or through my local IP.
