### ISSUE TITLE
Where to start with "Cannot Get"

### ISSUE THREAD

**Issue by phoebebright** [ether/etherpad-lite#2728]
I've install etherpadlite successfully on both a mac and ubuntu.  I can create a pad and edit fine but I can't get the API to work.

First I tried the python library pyetherpadlite then I tried straight http copying from the docs using the API key generated by the system.  Tried deleting the key and letting it regenerate one, just to sure.

http://127.0.0.1:9001/1/createAuthorIfNotExistsFor?apikey=2b110ceed76b44f46132cf50266ca3d631853b911547c83ce1d858de6a2873ac&name=Michael&authorMapper=7

On both the mac and linux I get:
Cannot GET /1/createAuthorIfNotExistsFor?apikey=2b110ceed76b44f46132cf50266ca3d631853b911547c83ce1d858de6a2873ac&name=Michael&authorMapper=7

I've scoured the docs and issues and can't find anything that will help me to understand what I'm doing wrong.  Probably going to feel silly shortly....

**Comment by tombriles** [comment]
You need a 'api/' just before the version number.

**Comment by phoebebright** [comment]
Feeling silly!  Thanks.
