### ISSUE TITLE
Feature: Enable derefer for etherpad lite? 

### ISSUE THREAD

**Issue by xshadow** [ether/etherpad-lite#2731]
I would really like to have a dereferring enable option in etherpad-lite. 

Short summary why:
Assuming you use a plain etherpad lite installation, the only way to keep your pad private is to set the pad ID pretty random and only share it between "allowed" users. If you want to include urls in this pad, which will be clicked by you or other pad users, you endanger the privacy of this pad. The admin on "the other side" of that link could easily determine where this request come from - and find out the pad ID. This could endanger the content of the pad. 

This risk could be limited, if the etherpad lite admins owns/trust a dereferer, which could be enabled via config. This feature would be dereferring all outgoing links. The admin on the requested page, will only see "dereferrer.foobar.org" in the logs - and not the unique pad ID.

It would be great to set two options in settings.json 

 > /* Privacy: enable dereferring */
 >"enableDerefering" : True,
 >"derefererUrl": "https://dereferrer.foobar.org/"

and an adjustment in the link constructor accordingly.

Thanks for your awesome service :)

**Comment by 0x46616c6b** [comment]
+1

**Comment by webzwo0i** [comment]
You could give https://github.com/JohnMcLear/ep_hide_referrer a try. It rewrites the handler for onclick. (Not sure if it covers all links in a pad installation)
The plugin makes a redirect.html page that gets the link via https://en.wikipedia.org/wiki/Fragment_identifier . Clicking on a link brings you to redirect.html#link , transforms the fragment to a new anchor and clicking that sets the referrer to the redirect.html location.
Other options had been discussed in the past in https://github.com/ether/etherpad-lite/issues/1603
It's old, but you can share your thoughts there, too.

**Comment by Gared** [comment]
As @webzwo0i mentioned: Use the plugin "ep_hide_referrer" it should do what you need
