### ISSUE TITLE
Node consuming 1Gb at startup

### ISSUE THREAD

**Issue by flotho** [ether/etherpad-lite#2732]
Hi,

I would like to know if the consumption of 1Gb at startup for etherpad is a common value? I found this a little High and would like to know if there is any way to manage this?

regards

**Comment by Gared** [comment]
@flotho This is not a common value. Can you please provide informations on your installation and how you find out this value?

**Comment by flotho** [comment]
Hi @Gared 

I think I read a bad info. It was a kind of shared memory.
Bad info sorry
