### ISSUE TITLE
":" character in URL seems to generate "bad url - posssible XSS attempt" error response

### ISSUE THREAD

**Issue by wrought** [ether/etherpad-lite#2737]
Not sure if this is an etherpad issue, cross-posting from riseup.net:

https://user.riseup.net/ticket/326251/booking@omnicommons.org

On line 3 of this pad: https://pad.riseup.net/p/omnicommons is a URL that etherpad redirects to https://pad.riseup.net/redirect#https%3A//omnicommons.org/wiki/Event%3A2015/07/18_Commons_Working_Group which produces the error message "bad url - posssible XSS attempt" which seems to be an issue with the ":" character in the URL, however the url-encoded equivalent of "%3A" produces the same result.

Our work-around is to use the instructions:

'right click "Open Link in New Tab"'

**Comment by Gared** [comment]
This is an issue in the plugin https://github.com/JohnMcLear/ep_hide_referrer/issues/9

**Comment by wrought** [comment]
I submitted a patch here: https://github.com/JohnMcLear/ep_hide_referrer/pull/12
