### ISSUE TITLE
Alt Gr - B for { on hungarian keyboard

### ISSUE THREAD

**Issue by LaKing** [ether/etherpad-lite#2738]
My users keep reporting that chrome on windows does not put the { character when pressing AltGr - B.
Hungarian layout ...

**Comment by nlac** [comment]
/src/static/js/ace2_inner.js, line 3904: add this extra condition: `&& !evt.altKey` to the end of the long conditional expression that handles key "b"

**Comment by JohnMcLear** [comment]
@muxator we have 3 open issues for the same thing

**Comment by muxator** [comment]
This issue is from 2016.

I do not think that this problem is still present in recent Etherpad, at least not on Firefox.

#3413 (landed in 1.7.0, 2018-08-17) merged a change that unified Firefox key event handling with Chrome.
