### ISSUE TITLE
Server does not receive write updates

### ISSUE THREAD

**Issue by Zeletochoy** [ether/etherpad-lite#2746]
When I try to write something in a pad I don't see anything on the server side even with DEBUG log.
Of course the new text is not saved and synchronized with the other users.

On client side I get a lot of "TypeError: tname is null" errors in require-kernel.js:226.

I tried both on master and develop branches but the result is the same.

You can try on my install at http://pad.zeletochoy.fr/p/etherpad-issue

**Comment by Gared** [comment]
Looks like a configuration error of your reverse proxy to me. Please try to open your etherpad directly.
