### ISSUE TITLE
Unable to load a pad on https://beta.etherpad.org on ie8

### ISSUE THREAD

**Issue by Aur0r** [ether/etherpad-lite#2750]
Hi all,
I was unable to open https://beta.etherpad.org/p/Test or any other pad on https://beta.etherpad.org ie8 on win7. Is the support for this version dropped or is it just a bug?

![bs_win7_ie_8 0](https://cloud.githubusercontent.com/assets/444048/9154921/1d4206ec-3ea6-11e5-9582-89707029b887.jpg)

Best regards,
Martin

**Comment by Gared** [comment]
Can someone confirm this please?

**Comment by Gared** [comment]
I can confirm this bug with latest IE 11 in emulation mode on IE 8

**Comment by JohnMcLear** [comment]
IE is test covered by Sauce Labs CI testing
