### ISSUE TITLE
Chat messages issued via appendChatMessage are not pushed to clients

### ISSUE THREAD

**Issue by fread** [ether/etherpad-lite#2753]
When I issue a new chat message using the HTTP API (appendChatMessage), this message is saved correctly, but not pushed to the currently connected clients (I waited 5 minutes, just to be sure). The clients need to reload the pad to see the new message. The history returned by the HTTP API (getChatHistory) includes the new message.

Etherpad revision: 02c022aab14f9087e22cebd4123336935cc089d8
Database: dirtyDB
Browser used by client: Firefox 39.0

I will probably not get to test this on MySQL before next week, so I'm happy if anybody can reproduce.

**Comment by Gared** [comment]
@fread I can confirm your bug report. Will try to fix this

**Comment by Gared** [comment]
@fread Can you please have a look on my PR? Is this fixing your problem?

**Comment by fread** [comment]
Yes, that fixes the problem for me. Thank you.
