### ISSUE TITLE
Support for RethinkDB as Backend

### ISSUE THREAD

**Issue by RubenKelevra** [ether/etherpad-lite#2755]
Hey!

I would love to see a RethinkDB-Support in Etherpad-Lite. Since it would be easier to share the database-load on more than one server, since RethinkDB supports easy clustering.

**Comment by RubenKelevra** [comment]
No comments?

**Comment by Gared** [comment]
This is not the right place to ask for support of a new database. We use ueberDB for all database transactions so please file your issue there: https://github.com/Pita/ueberDB

**Comment by RubenKelevra** [comment]
Thanks, created there a bug as well...

https://github.com/Pita/ueberDB/issues/86
