### ISSUE TITLE
Error: Cannot find module 'base64id'

### ISSUE THREAD

**Issue by Liz-Gtz** [ether/etherpad-lite#2759]
Please help me, I need to make note with Humhub and I'm trying to install etherpad but when type bin/run.sh on console show me an error [ERROR] console - Failed to load 'ep_etherpad-lite/node/hooks/express/socketio:expressCreateServer' for 'ep_etherpad-lite/socketio/hooks/expressCreateServer': Error: Cannot find module 'base64id'.
OS Ubuntu 14.04 Lts

Thanks in advance

**Comment by Gared** [comment]
Does this error still persists?
Can someone confirm this problem?
