### ISSUE TITLE
Pasting formatted content breaks pad since 1.5.7

### ISSUE THREAD

**Issue by neffs** [ether/etherpad-lite#2760]
When pasting formatted content (from e.g. other websites) it doesn't get a colored background and won't be pushed to the server. After pasting no further changes will be pushed to the server. No error message is shown to the user or in etherpad log but every second or so the JS console shows the following error:
[Error] TypeError: null is not an object (evaluating 'cls.indexOf')
	inCallStack (undefined, line 9)
	inCallStackIfNecessary
	(anonyme Funktion)
	callback

It is reproducible since 1.5.7 and didn't happen in 1.5.6. I solved it by going back to 1.5.6 (which I wanted to avoid because group pad export is broken)
Tested with several browsers (Safari, Chrome, Firefox).

Environment: 
Debian Wheezy
node 0.12
I use group pads with requireSession

**Comment by elijh** [comment]
I have not been able to reproduce this problem in 1.5.7.

**Comment by mabe-at** [comment]
Hi!
We have experienced the same problem.
Uninstalling the tasklist plugin solved it.

**Comment by otetard** [comment]
This issue exists since 58ab17bf9e21cd5c5266f3f7c1de80eedc1821dd. I find a way to fix this issue (see that a pull-request on `ep_tasklist` : JohnMcLear/ep_tasklist#18).

**Comment by Gared** [comment]
@neffs Do you use the ep_tasklist plugin? If yes is it working now with these changes?

**Comment by mabe-at** [comment]
Installed the bugfix of ep_tasklist and it's working now for us.
Thanks.

**Comment by neffs** [comment]
Issue was with ep_tasklist. Thanks!
