### ISSUE TITLE
Android app'

### ISSUE THREAD

**Issue by Salamandar** [ether/etherpad-lite#2761]
Hi !

I'm using etherpad-lite for a long time, but without any mobile app it's a pain in the ass on phone (web or native).

I would love to participate/lead the dev of a native android app. But I don't know anything to network, so I won't be able to finish the project alone.

Would someone from the original etherpad project join me ?

Félix aka Salamandar.

**Comment by akuckartz** [comment]
@Salamandar _Which_ problems do you see with etherpad-lite on a phone (and intend to solve using native Android technoloigies) ?

**Comment by Salamandar** [comment]
Well :
* somehow "laggy"
* some "bugs" related to the browser zooming when we click on the text area
* loading the whole page (not only text) can be slow on a slow connection
* no responsive design for the chat.
* the small window gives a crappy look (line wrapping, etc)
That is for the problems.
Some features can be added :
* Notifications
* well… we'll see :p

**Comment by akuckartz** [comment]
Those issues can be resolved using web technologies.

**Comment by Salamandar** [comment]
It seems that you just don't want to see a native app for etherpad. What's the matter ?

**Comment by akuckartz** [comment]
@Salamandar No, I do not care if a native app is developed or not. But I think that the issues you listed should be resolved in the web app.

**Comment by Gared** [comment]
@Salamandar An app is a good idea, but I see more befinits in improving the web app then create apps for some mobile devices so I don't want to spend much time on it, but I can provide you infos about communication with the server.
Anyway: This is not the right place to ask for help. Please write on the developer mailing list for such purposes: etherpad-lite-dev@googlegroups.com

**Comment by Salamandar** [comment]
Got it. I may start to work on it then.

**Comment by soft1700** [comment]
did you get a chance to work on it?
