### ISSUE TITLE
Provide shortcuts for title 1-6

### ISSUE THREAD

**Issue by philippejadin** [ether/etherpad-lite#2764]
This might be good : Ctrl + Alt + [1-6] = H1-H6

(same as g\* docs)

Thanks btw for the superb tool

**Comment by SimonClavier** [comment]
Hi,
First of all, thanks for this tool, etherpad-lite is just great !
I was looking for this feature too (shortcuts for heading) but it still seems not to be implemented (or am I wrong ?)
Does anybody know if there is any plugin or workaround to do it ?
Thanks !

**Comment by lpagliari** [comment]
The headings feature you find on https://beta.etherpad.org/ is actually implemented by the `ep_headings2` plugin, and there's already [an issue there asking for this feature](https://github.com/ether/ep_headings2/issues/10).

If you want to submit a PR with that feature (it will be awesome!), you can take a look on the [`aceKeyEvent`](http://etherpad.org/doc/v1.6.0/#index_acekeyevent) hook. This seems to be a  good example about how to implement it: https://github.com/tm-linkwerk/ep_linebreak/blob/master/static/hooks.js.

Please let me know if there's something I can help you with to implement the PR.
