### ISSUE TITLE
How can I configure ldap in Humhub?

### ISSUE THREAD

**Issue by Liz-Gtz** [ether/etherpad-lite#2766]
I want to configure ldap in humhub but I don't know which parameters I need. Somebody can help me please.
 
Thanks in advance

**Comment by Liz-Gtz** [comment]
When I try to save, show me error

Status: ¡Error! (Mensaje: 0x34 (Server is unavailable; 00000000: LdapErr: DSID-0C090F7B, comment: Error initializing SSL/TLS, data 0, v2580): 192.168.1.6:389)

**Comment by Gared** [comment]
We don't support ldap in etherpad core. Please ask the author of the plugin for support.
