### ISSUE TITLE
History: Back to the pad-Button disappeared 

### ISSUE THREAD

**Issue by RubenKelevra** [ether/etherpad-lite#2768]
I upgraded my pad from 1.5.2 to 1.5.7 and the "back to pad" button, in the history is gone. How do you plan to guide users back to the pad?

**Comment by Gared** [comment]
There is a "Return to pad" button in 1.5.7 in the timeslider.
Look here: https://beta.etherpad.org/p/6k8VQobe9j/timeslider

**Comment by RubenKelevra** [comment]
Since this seems so clear to you, that you close the bugreport without waiting for a response please spot out the missing button here:

http://i.imgur.com/NoY1D3P.png

**Comment by 0ip** [comment]
Different translations, i.e. varying text lengths, cause this behavior.
`.timeslider-bar #editbar` shouldn't have a fixed width (180px).

**Comment by RubenKelevra** [comment]
Well, I don't changed anything between 1.5.2 and 1.5.7, especially not on the translations ... so this bug has to be caused by changes in the german translation between this two versions.

**Comment by 0ip** [comment]
You are right, this bug was introduced in version 1.5.7: e02708313623fa90600c1f6a24f17a01eff4aec8.
Until this is fixed, you may change the responsible line manually in this file as mentioned above: /src/static/css/timeslider.css#L235

**Comment by RubenKelevra** [comment]
Well I don't want to change anything in the design-code. I'm waiting for the next update, which I think is going to be released soon, since this bug here is a blocker. :)

I think in my setup the back to pad-button is used very rarely... so I think in my case it's not that important.

**Comment by Gared** [comment]
@RubenKelevra Sorry for being to fast.
@0ip Reverting the change in line 235 does not fix the hidden button, but setting the width to 200 pixel

**Comment by 0ip** [comment]
@Gared I'm not saying that we should revert it, but explicitly override it with `auto`, which is more bulletproof.
Setting it to 200px, which is an arbitrary value I guess, poses the risk, that, depending on the selected language, whose translation for this specific text requires even more than 200px (for example Farsi), will make it disappear again.

**Comment by Gared** [comment]
@0ip You're right. I just wanted to say that the change you found in the commit is probably not the reason for the bug, but anyway do you want to open a PR for that?
