### ISSUE TITLE
Error in export command

### ISSUE THREAD

**Issue by Liz-Gtz** [ether/etherpad-lite#2769]
Hello all!

I'm new in etherpad.
I'm trying install etherpad in this way: 
  sudo su - etherpad -s /bin/bash 
  mkdir ~/local
  cd ~/local
  wget http://nodejs.org/dist/v0.8.7/node-v0.8.7.tar.gz
  tar -zxvf  node-v0.8.7.tar.gz
  cd node-v0.8.7
  ./configure –-prefix=$HOME/local/node
  make
  cd /opt/etherpad/local/node-v0.8.7
  make install
  echo ‘export PATH=$HOME/local/node/bin:$PATH’ >> ~/.profile
  echo ‘export NODE_PATH=$HOME/local/node:$HOME/local/node/lib/node_modules’ >> ~/.profile

  The issue is when I typing this line   source ~/.profile,   I get an error
  'export: Not found command

somebody help me please. How can I fix it?

Thanks in advance

**Comment by Gared** [comment]
We provide only node version 0.10 and above. So this won't work for you with this version of node.js
