### ISSUE TITLE
Permanent authors list (even after disconnect)

### ISSUE THREAD

**Issue by vkrizan** [ether/etherpad-lite#2770]
There is no way now to figure out the authors name by color, when the author is disconnected.

Display list of all authors and their colors, who were involved in editing, even after they are disconnected. Indicate actually connected authors/users with some proper icon.

**Comment by aspiers** [comment]
Great idea. Also, connected users should appear at the top of the list, otherwise they could be buried deep in a long list if the etherpad had many editors over a long time.

**Comment by JohnMcLear** [comment]
ep_author_hover is one way of doing this.  It shows the author of an edit on hover of content.  

Putting as a feature wouldn't be too hard too.
