### ISSUE TITLE
Truncated pads after editing with an iPhone

### ISSUE THREAD

**Issue by neurolit** [ether/etherpad-lite#2771]
Hi!

We are using Etherpad 1.5.6 and 1.5.7 and we noticed that every pad we edited with an iPhone (*Mozilla/5.0 (iPhone; CPU iPhone OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4*) became corrupted:

    TypeError: pad.collabClient is null in https://pad.inria.fr/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 266'

These pads can't be read anymore, and when we try, the whole nodejs server restarts. 

MySQL is our engine storage. We noticed the pads were truncated (and thus JSON is no JSON anymore):
```sql
select * from store where store.key="pad:g.ZYGOzusb6LPFIgsY$V5Vm6ARoUCeSSFGe" ;
+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| key | value |
+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| pad:g.ZYGOzusb6LPFIgsY$V5Vm6ARoUCeSSFGe | {"atext":{"text":"abcdefgh |
+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

It's a bug: a browser shouldn't be able to destroy a pad like that.

## Footnotes

Nginx is the frontend, and MySQL is the storage engine:
```sql
CREATE TABLE `store` (
  `key` varchar(100) COLLATE utf8_bin NOT NULL DEFAULT '',
  `value` longtext COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin
```

**Comment by Gared** [comment]
See this bug #2522. The solution in this ticket should also resolve your problem

**Comment by neurolit** [comment]
@Gared Thanks for your answer! I'll try this solution.

**Comment by Gared** [comment]
@neurolit Any update on this?

**Comment by neurolit** [comment]
@Gared we updated MySQL charset to utf8mb4. So far, we haven't detected a newly corrupted pad.
