### ISSUE TITLE
Crashloop

### ISSUE THREAD

**Issue by RubenKelevra** [ether/etherpad-lite#2778]
Suddenly a installation which was stable for years stuck. I'm was on 1.5.2 a.t.m. because a plugin seems to break copy'n'paste on 1.5.7.

Since the bug seems to crash 1.5.2 in a loop, I updated the pad to 1.5.7... the bug remains:

Sep 09 23:48:19 vali.freifunk-nrw.de systemd[1]: Started Etherpad-Lite server.
Sep 09 23:48:19 vali.freifunk-nrw.de run.sh[27518]: Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
Sep 09 23:48:20 vali.freifunk-nrw.de run.sh[27518]: npm WARN package.json ep_etherpad-lite@1.5.2 No license field.
Sep 09 23:48:22 vali.freifunk-nrw.de run.sh[27518]: Ensure jQuery is downloaded and up to date...
Sep 09 23:48:22 vali.freifunk-nrw.de run.sh[27518]: Clear minfified cache...
Sep 09 23:48:22 vali.freifunk-nrw.de run.sh[27518]: Ensure custom css/js files are created...
Sep 09 23:48:22 vali.freifunk-nrw.de run.sh[27518]: Started Etherpad...
Sep 09 23:48:24 vali.freifunk-nrw.de run.sh[27518]: [2015-09-09 23:48:24.717] [WARN] console - Can't get git version for server header
Sep 09 23:48:24 vali.freifunk-nrw.de run.sh[27518]: ENOENT, no such file or directory '/usr/share/webapps/etherpad-lite/.git/HEAD'
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: [2015-09-09 23:48:26.938] [ERROR] console - JSON-PROBLEM:{"atext":{"text":"Protokoll vom 9.9.2015\n==================\n\n# Themen\n\n# Vorstellungsrunde\n\n* ca. 20 Leute da\n\n# Bericht von Installationen\n* Teske-Schule (Tempelhoferweg)\n   siehe schöner Wiki…in
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: [2015-09-09 23:48:26.947] [ERROR] console - Async Stacktrace:
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at /usr/share/webapps/etherpad-lite/src/node/handler/PadMessageHandler.js:1306:5
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at /usr/share/webapps/etherpad-lite/src/node/handler/PadMessageHandler.js:1042:16
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at /usr/share/webapps/etherpad-lite/src/node/db/PadManager.js:171:10
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at Object.callback (/usr/share/webapps/etherpad-lite/src/node/db/Pad.js:400:8)
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: SyntaxError: Unexpected end of input
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at Object.parse (native)
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at /usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/CacheAndBufferLayer.js:164:24
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at Query._callback (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/mysql_db.js:115:5)
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at Query.Sequence.end (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at Query._handleFinalResultPacket (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at Query.EofPacket (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at Protocol._parsePacket (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:274:23)
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at Parser.write (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:77:12)
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at Protocol.write (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:39:16)
Sep 09 23:48:26 vali.freifunk-nrw.de run.sh[27518]: at Socket.<anonymous> (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:96:28)
Sep 09 23:48:27 vali.freifunk-nrw.de systemd[1]: etherpad-lite.service: Service hold-off time over, scheduling restart.
Sep 09 23:48:27 vali.freifunk-nrw.de systemd[1]: Stopped Etherpad-Lite server.
Sep 09 23:48:27 vali.freifunk-nrw.de systemd[1]: Started Etherpad-Lite server.
Sep 09 23:48:27 vali.freifunk-nrw.de run.sh[27559]: Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
Sep 09 23:48:28 vali.freifunk-nrw.de run.sh[27559]: npm WARN package.json ep_etherpad-lite@1.5.2 No license field.
Sep 09 23:48:30 vali.freifunk-nrw.de run.sh[27559]: Ensure jQuery is downloaded and up to date...
Sep 09 23:48:30 vali.freifunk-nrw.de run.sh[27559]: Clear minfified cache...
Sep 09 23:48:30 vali.freifunk-nrw.de run.sh[27559]: Ensure custom css/js files are created...
Sep 09 23:48:30 vali.freifunk-nrw.de run.sh[27559]: Started Etherpad...
Sep 09 23:48:32 vali.freifunk-nrw.de run.sh[27559]: [2015-09-09 23:48:32.838] [WARN] console - Can't get git version for server header
Sep 09 23:48:32 vali.freifunk-nrw.de run.sh[27559]: ENOENT, no such file or directory '/usr/share/webapps/etherpad-lite/.git/HEAD'
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: [2015-09-09 23:48:34.133] [ERROR] console - JSON-PROBLEM:{"atext":{"text":"Protokoll vom 9.9.2015\n==================\n\n# Themen\n\n# Vorstellungsrunde\n\n* ca. 20 Leute da\n\n# Bericht von Installationen\n* Teske-Schule (Tempelhoferweg)\n   siehe schöner Wiki…in
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: [2015-09-09 23:48:34.143] [ERROR] console - Async Stacktrace:
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at /usr/share/webapps/etherpad-lite/src/node/handler/PadMessageHandler.js:1306:5
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at /usr/share/webapps/etherpad-lite/src/node/handler/PadMessageHandler.js:1042:16
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at /usr/share/webapps/etherpad-lite/src/node/db/PadManager.js:171:10
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at Object.callback (/usr/share/webapps/etherpad-lite/src/node/db/Pad.js:400:8)
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: SyntaxError: Unexpected end of input
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at Object.parse (native)
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at /usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/CacheAndBufferLayer.js:164:24
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at Query._callback (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/mysql_db.js:115:5)
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at Query.Sequence.end (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at Query._handleFinalResultPacket (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at Query.EofPacket (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at Protocol._parsePacket (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:274:23)
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at Parser.write (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Parser.js:77:12)
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at Protocol.write (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:39:16)
Sep 09 23:48:34 vali.freifunk-nrw.de run.sh[27559]: at Socket.<anonymous> (/usr/share/webapps/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/Connection.js:96:28)
Sep 09 23:48:34 vali.freifunk-nrw.de systemd[1]: etherpad-lite.service: Service hold-off time over, scheduling restart.
Sep 09 23:48:34 vali.freifunk-nrw.de systemd[1]: Stopped Etherpad-Lite server.
Sep 09 23:48:34 vali.freifunk-nrw.de systemd[1]: Started Etherpad-Lite server.

**Comment by RubenKelevra** [comment]
This seems to be a broken pad which causes the error ...

An error occured
The error was reported with the following id: 'MBceVEPUIHYjLdFoVpV4'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: MBceVEPUIHYjLdFoVpV4
URL: https://padurl.com/p/padname
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
Uncaught TypeError: Cannot read property 'setChannelState' of null in https://pad.freifunk.net/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 254'

I removed the url

**Comment by RubenKelevra** [comment]
Still this Bug is a BLOCKER for our Etherpad-Lite installation, is it restarted several HUNDRED TIMES a day... a fast fix for this issue is very much appreciated!

Best regards and thanks in advance

Ruben

**Comment by Gared** [comment]
See #2522

**Comment by Gared** [comment]
@RubenKelevra This should be fixed?!

**Comment by Gared** [comment]
@RubenKelevra Any update on this?
