### ISSUE TITLE
Etherpad-lite general instability

### ISSUE THREAD

**Issue by lightweight** [ether/etherpad-lite#2785]
I'm trying to work out why my etherpad-lite implementation (https://etherpad.nzoss.org.nz) - up-to-date with the dev branch as of today - has been (and continues) to fall over frequently with any significant use. I've just applied the database collation fixes described by webzwo0i in #2516 and have been looking at removing the few plugins I have to see if they're responsible... Has anyone else experienced this delicate nature from their etherpad-lite install?

I'm wanting to open our service to collaborating groups, but need to develop confidence in its ability to support more than a few users without falling over... 

Need to learn more about debugging etherpad-lite, so I can provide more useful insight. Currently looking at nginx logs (and need to make sure I've got that configured fully and correctly). Any pointers to other debugging tricks appreciated.

**Comment by Gared** [comment]
What do you mean by "fall over"? Could you please provide more infos? Have you take a look in the log file of etherpad?

**Comment by lightweight** [comment]
Apologies - I'm trying to work out how to debug etherpad-lite (and node.js in general). I've now got my etherpad running with a log file, and running it manually rather than via my etherpad-lite.conf... I'll report back once I've identified any pattern in the crashes. Previously, all I knew was that etherpad-lite would stop responding to nginx, and that a restart of etherpad-lite was required.

**Comment by Cyrille37** [comment]
I agree that version 1.5.7 does not work well.
bullet list and tabulation make the pad do not record changes.
In the console I've many many errors like in the attached screenshot.

![selection_004](https://cloud.githubusercontent.com/assets/368965/10191717/e59eb7b8-6776-11e5-874e-fc76d3114aac.png)

**Comment by Cyrille37** [comment]
When I reload a pad (Ctrl+F5) an error is logged in /var/log/etherpad-lite/etherpad-lite.log

```
[2015-09-30 15:48:31.147] [WARN] client - Uncaught TypeError: Cannot read property 'className' of undefined -- { errorId: 'FqBfkPCsXTSdMA6kMwPa',
  msg: 'Uncaught TypeError: Cannot read property \'className\' of undefined',
  url: 'http://pad.comptoir.net/p/xxxx',
  linenumber: 66,
  userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.85 Chrome/45.0.2454.85 Safari/537.36' }
```

**Comment by Cyrille37** [comment]
I've removed plugin [ep_author_hover](https://npmjs.org/package/ep_author_hover) and it seems to come back to a nice work ...

**Comment by Cyrille37** [comment]
I confirm that without ep_author_hover EP 1.5.7 works like a charm !!
Problems with ep_author_hover seem to be old, like with EP 1.5.6 (information from my EP instance users).

**Comment by lightweight** [comment]
Useful, thanks Cyrille37 - I also had ep_author_hover on my 1.5.7 instance (wasn't experiencing your specific problem, but general instability, with etherpad-lite crashing for unknown reasons)... Removed and now testing stability...

**Comment by lightweight** [comment]
For the record, stability has been much better since that change... still the occasional crash, but only every month or so as opposed to every few hours. Thanks for your hard work on this all, especially you, @JohnMcLear!

**Comment by JohnMcLear** [comment]
*doesn't know what he, did but sure, my pleasure :)  Props to @webzwo0i @Gared and everyone else who is doing the majority of the real heavy lifting lately :)
