### ISSUE TITLE
Error: Attempt to load undefined module. in/static/js/require-kernel.js after upgrading from 1.4.1 to 1.5.7

### ISSUE THREAD

**Issue by vieville** [ether/etherpad-lite#2789]
I upgraded etherpad-lite from 1.4.1 to 1.5.7.

The api runs well but the UI to pad failed during loading with the following error 

"An error occured while loading the pad

Error: Attempt to load undefined module. in https://etherpad.univ-lille1.fr/static/js/require-kernel.js (line 1)"

I removed all the node_modules and reruns etherpad but I still had the same message.

Any idea to help me ?

Thank you

**Comment by vieville** [comment]
I tested again my new installed release 1.5.7 with a blank database and it works fine.

Is it required to updgrade the database when upgrading from release 1.4.1 to 1.5.7 ?

I yes, what is the procedure to run ?

Thank you for your help

**Comment by Gared** [comment]
@vieville No there is no database upgrade needed. Please try to remove the folder src/node_modules/

**Comment by dissolve** [comment]
I am getting the something similar, tried it on the git master and i get this

An error occured while loading the pad
Uncaught Error: The module at "underscore" does not exist. in http://192.168.1.50:9001/static/js/require-kernel.js (line 1)

But ONLY when loading from my IP, if i use 127.0.0.1, it works fine.  my settings.json has it set for "0.0.0.0"

**Comment by Gared** [comment]
@vieville Do you still have problems with your installation?

**Comment by helioloureiro** [comment]
Hi,

I just tripped in this problem today, upgrading etherpad-lite.  The proposed solution didn't work.

I just commented the line w/ such statement in src/templates/timeslider.html and it worked.

[root@server etherpad-lite]# cat -n src/templates/timeslider.html | grep kernel
   222  
[

**Comment by jincreator** [comment]
Today I upgrade from 1.4.0 to 1.5.0 and notice same error message.
Sometimes removing node_modules is not enough for all users.
For me, pressing Ctrl + F5 solve it ;)
