### ISSUE TITLE
Empty Pads

### ISSUE THREAD

**Issue by RubenKelevra** [ether/etherpad-lite#2790]
Well, we discovered some fully empty pads on our pad-server.

Example:
https://pad.freifunk.net/p/Aachen

It's might be related to database conversation, as decribed here:
https://github.com/ether/etherpad-lite/issues/2516#issuecomment-79659984

How do we fix this?

**Comment by Gared** [comment]
is there anything about this problem in your log file?

**Comment by RubenKelevra** [comment]
Nope. No loggs while opening the pad or scrolling thru the empty timeline...

**Comment by webzwo0i** [comment]
hi, I am so sorry that I had no time to finish all the open issues surrounding utf8&broken pads, hopefully I can get this done in the next weeks. It touches different areas in epl and multiple fixes are needed. :-(

I think you resolved this now with export&import?

**Comment by webzwo0i** [comment]
for the record: I try to export (http://your-pad-domain/p/your-pad-name/export/etherpad) and import 
```
curl -F 'file=@your-pad-name.etherpad' http://127.0.0.1:9001/p/new-pad-url/import
```
Be sure that the file is ending in ".etherpad". If you want to preserve the old pad name you probably need to comment the check in https://github.com/ether/etherpad-lite/blob/develop/src/node/handler/ImportHandler.js#L128

To check if any other pads in your installation are broken I would suggest you get a list of all pad names from the database, feed them into selenium and look for errors in the logs of selenium and epl respectively (an additional check would be to point the timeslider to every revision). Maybe you should select the pad text from selenium and if its empty you know something is broken (or the last edit deleted the whole pad content). I can help you with that, just tell me if you need it.
