### ISSUE TITLE
Unable to configure etherpad-lite to use HTTP_PROXY for retrieval of plugins

### ISSUE THREAD

**Issue by JonTheNiceGuy** [ether/etherpad-lite#2792]
I am trying to configure etherpad-lite in an environment where there is no direct access to the internet.

In this environment, I would set HTTP_PROXY and HTTPS_PROXY values to the IP address and port of the proxy which lives between the application and the internet, and this would be intercepted by the application and translated to a local setting. I've not been able to find a setting in the settings.json file as that doesn't appear to be translated.

As such, I'm unable to install plugins from within the application. Happy to help debug, if required.

**Comment by Gared** [comment]
@JonTheNiceGuy Have you tried this configuration? http://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by JonTheNiceGuy** [comment]
So, this is not me saying I have or haven't (I'm struggling to get some other tasks completed today), but for anyone else following along at home ;)

On Windows, you perform this by running (note, replace $PATH_TO_EP with your own path to etherpad):

`````
cd $PATH_TO_EP
node src\node_modules\npm\bin\npm-cli.js config
`````

I'll get my ntlm proxy stood back up this afternoon and check to see if it works.

Thanks for your help thus far @Gared.
