### ISSUE TITLE
Relative path in socket.io.js

### ISSUE THREAD

**Issue by janriokrause** [ether/etherpad-lite#2795]
In `socket.io/socket.io.js` there is an absolute path for `/socket.io` and `/engine.io`. If Etherpad is installed in a sub-directory, this path cannot be found. It would be great, if these were relative. So just adding a dot before the path would work.

    // Manager constructor
    opts.path = opts.path || '/socket.io';

and

    // Socket constructor
    this.path = (opts.path || '/engine.io').replace(/\/$/, '') + '/';

**Comment by lkraav** [comment]
1.5.7 and same problem here. This has to be a recent change because early 1.5.x worked fine.

**Comment by lkraav** [comment]
Indeed #2748 seems to fix the issue. Pulling the latest `develop` branch works better.

**Comment by JohnMcLear** [comment]
Please Close Issues when resolved!
