### ISSUE TITLE
Shortcutkey problem in last version of Etherpad online instances

### ISSUE THREAD

**Issue by jaskow** [ether/etherpad-lite#2800]
shortcutkey conflict with Polish language, because alt+ctrl+c keys opens
Chat window, preventing typing one of Polish speciall charakters

**Comment by bhldev** [comment]
Please see #2891 for workaround, configuration in settings.json

Please give [bounty](https://www.bountysource.com/issues/30676386-iceweasel-switching-tabs-with-pgup-down-moves-the-cursor-in-the-pad) for UI/plugin development "enable/disable shortcut keys", UI will look like this  
![image](https://cloud.githubusercontent.com/assets/4929336/13028377/5944fe28-d23b-11e5-936b-3d1783dfeb6c.png)

**Comment by lpagliari** [comment]
This is the same issue as #2884, I'll close this one and leave the other one opened, so we keep all the discussion on a single place.
