### ISSUE TITLE
504 Gateway Time-out returned for etherpad.net

### ISSUE THREAD

**Issue by PanderMusubi** [ether/etherpad-lite#2804]
504 Gateway Time-out is returned for all pages on etherpad.net. When will these be accessible again?

**Comment by 0ip** [comment]
Please do not post issues on Github that are not directly related to the Etherpad software itself.
For problems like these, please use the contact information given on the page in order to talk to the corresponding maintainer.

**Comment by PanderMusubi** [comment]
There was non to find on the page and it looked to me that this one was run by core developers of this project. Perhaps good to add contact information of important sites that run Ethernet in the wiki next to the respective urls? Meanwhile all is up and running again. Thanks.

**Comment by 0ip** [comment]
Maybe it is not placed visible enough, but there is a "Questions?" link on the bottom of that page.

I agree, adding a website or mail address next to each site would be a good thing.
