### ISSUE TITLE
load settings not work

### ISSUE THREAD

**Issue by lufeihaidao** [ether/etherpad-lite#2807]
In `server.js`:75

``` javascript
hooks.aCallAll("loadSettings", { settings: settings });
```

It seems this line doesn't take effect and can be removed.

**Comment by lufeihaidao** [comment]
`plugins.js`:147 `parts[part.full_name] = part;` parts is initialised as Array(in line 84) therefore it doesn't take effect, too.

**Comment by JohnMcLear** [comment]
@lufeihaidao you can console.log settings, I tested it and it seems to work fine.
