### ISSUE TITLE
Inserting an URL into an empy line removes font-family setting

### ISSUE THREAD

**Issue by g-borgulya** [ether/etherpad-lite#2811]
It's possible to remove font style settings from lines in a pad with inserting a URL into empty line.

I don't fully understand the mechanisms of font settings in etherpad, but I can explain what I experience:
1. Initially innerdocbody use to have font settings in its style attribute. Like: <body id="innerdocbody" role="application" class="syntax doesWrap noprewrap ltr" spellcheck="false" style="font-family: 'Helvetica Neue', Arial, sans-serif;"> ...
2. If I edit the pad, it either remains that way or every magicdom line gets a style attribute and the body loses it, I don't understand the triggers for this. Like: <div id="magicdomid37" class="ace-line" style="font-family: 'Helvetica Neue', Arial, sans-serif;">...
3. If you insert a URL to an empty line then even if it hasn't happened yet the behavior will be to set style for every magicdom line and not for the body. But the style won't be set for the line where you inserted the URL.
4. After this point if you edit any line in the pad, that line will lose its style attribute. 

The active font-family setting for these lines will be inherit, which seemingly inherits the browser default font. This is a problem if you use any other font for etherpad then the default.

**Comment by JohnMcLear** [comment]
I'm unable to replicate this bug.  Are you running plugins?  If so, disable them and provide to replicate.  If you can't replicate please close this bug and create issue on the plugin repo.

**Comment by JohnMcLear** [comment]
Unable to replicate, closing.
