### ISSUE TITLE
How to install on linux shared hosting using cpanel?

### ISSUE THREAD

**Issue by sikrigagan** [ether/etherpad-lite#2821]
I'm trying to install etherpad on Linux Shared Hosting using cpanel, but unable to do so, can you please provide valid documentation or video tutorial to do so?

**Comment by 0ip** [comment]
cPanel does not officially support node.js to my knowledge, but there are many tutorials on how to install node.js manually via command line.

Then take a look at: https://github.com/ether/etherpad-lite/blob/develop/README.md#gnulinux-and-other-unix-like-systems

**Comment by Dubidubiduu** [comment]
This changed in between but I still don't know how to configure it with cpanel

**Comment by ocdtrekkie** [comment]
According to HostGator this has not changed and is still not possible, though I found an article on how to do it: https://www.dzeta.biz/add-nodejs-hostgator-shared-hosting-server/

**Comment by Dubidubiduu** [comment]
![cpanelnode](https://user-images.githubusercontent.com/34820982/50846179-cee5ae80-136e-11e9-8cad-2627cb13bfc5.gif)

Node.js is installed on my cpanel, but I still don't get Etherpad to work, due my lack of experience, but it should work somehow I guess

**Comment by Dubidubiduu** [comment]
![cpanelnode](https://user-images.githubusercontent.com/34820982/50846788-47993a80-1370-11e9-991e-b043676e2ff3.gif)

Node.js is installed on my cpanel, but I still don't get Etherpad to work, due my lack of experience, but it should work somehow I guess. Hoster: serverprofis.de
