### ISSUE TITLE
Etherpad-lite horizontal application scaling

### ISSUE THREAD

**Issue by teran** [ether/etherpad-lite#2826]
Hello,

Now  because of ueberDB it's impossible to setup more than one frontend contains etherpad-lite application with dedicated database accessible remotely.
This causes confuses in attempts to setup reliable etherpad instance and normally should be fixed.

So for now the only way to make etherpad reliable is to use cold-standby scheme with one of the frontends(etherpad-lite application) be down while other one(1) handles requests.
More ideas about how to scale it now I've found here: https://groups.google.com/forum/#!topic/etherpad-lite-dev/o5ERp3g7SF8

To make it fixed you probably could:
- Add options to settings json to disable or eliminate ueberDB caching.
  This obviously could cause higher DB load, but it's slightly out of application care and mostly about DB tuning for particular task.
- Add ability to share ueberDB cache(probably it's not etherpad-lite purpose, but anyway) with interconnect

Thanks for attention.

**Comment by JohnMcLear** [comment]
Surely this should be an issue on the UeberDB repo not here?

**Comment by teran** [comment]
Not sure since UeberDB is slightly about another thing and works as expected here.
And the issue is mostly about scaling particular application.

**Comment by Jmainguy** [comment]
ran into this today trying to scale etherpad. Awesome project, would be great to see this feature added.
