### ISSUE TITLE
How to Merge Contents of Mulitple Pads into an HTML Document or PDF?

### ISSUE THREAD

**Issue by LucasCioffi** [ether/etherpad-lite#2829]
Etherpad is working well.

Often I have several related pads, and I'd like to merge the contents from all of them so that they can easily be printed or downloaded in a PDF.

I can currently export the individual pads to a text file or HTML, but it would be great if my users could export all 10 of their pads in some way (PDF, HTML, text, etc) with one click.

I was hoping that Nokogiri would work, but I see "head and body had been removed intentionally" so I don't think that will work.  I tried to print one pad to PDF from Chrome, but it was blank, probably for the same reason.

Any advice is greatly appreciated.

**Comment by JohnMcLear** [comment]
You would write something outside of Etherpad to do this.  It would GET each HTML export and combine them then print them as one document.  This is outside of the scope of Etherpad.

**Comment by LucasCioffi** [comment]
Thank you; I should have thought to get the HTML export rather than the pad.  I'll give it a try.
