### ISSUE TITLE
Avoid printing terminal sequences when output not into terminal

### ISSUE THREAD

**Issue by yurivict** [ether/etherpad-lite#2835]
When the log is redirected into the file, it still prints the terminal sequences.
```
^[[32m[2015-11-17 00:37:56.313] [INFO] ueberDB - ^[[39mFlushed 1 values
```

**Comment by Gared** [comment]
To prevent log4js to print the color terminal sequences into the file you have to add the "layout" option in settings.json to the "logconfig" part:
```
"logconfig": {
    "appenders": [
        { "type": "console",
          "layout": { "type": "basic" }
...
```
Found this info here: https://github.com/nomiddlename/log4js-node/issues/112#issuecomment-13061075

**Comment by leegee** [comment]
Using this solution, how can I also use a custom layout pattern? Why not just #2685 ?
