### ISSUE TITLE
Type Error:Invalid version when visiting the plugins page in admin

### ISSUE THREAD

**Issue by rkhyd** [ether/etherpad-lite#2837]
etherpad service stops when i visit the plugins page in the admin area.  This is the error i get. 
![image](https://cloud.githubusercontent.com/assets/15903310/11234719/d2792772-8df0-11e5-97b7-1d6809de8776.png)

**Comment by JohnMcLear** [comment]
Do you get this on latest develop branch @rkhyd  ?

**Comment by Gared** [comment]
@rkhyd Does this problem still persists?

**Comment by Billaboong** [comment]
Hello I also have the above problem and earlier it was working fine but after installing some plugins I got the above error.
The plugins I have installed are:disable change author name,offlibe_edit,pad+tracker,page_ruler,page_view,previewimages,real_time_chat,simpletextsearch,spellcheck,sticky_attributes,themes_ext and word_edit.
Please assist.
Thank you.

**Comment by meetbryce** [comment]
Try manually deleting the last plugin you installed from `etherpad-lite/node_modules/ep_<plugin name>`.
