### ISSUE TITLE
Split credentials and settings into different json files

### ISSUE THREAD

**Issue by cmbirk** [ether/etherpad-lite#2838]
Right now I have an instance that I am working on with a small development team.  Trying to keep the `settings.json` file up to date across our team is difficult because we cannot add it to our repo without exposing our mysql credentials.  We're working with quite a few plugins and plugin settings, and it would be nice to be able to keep our `settings.json` file in sync.

I think separating the `settings.json` file and something like a `creds.json` file would be very useful.  I'm happy to help on this if a pull request would be welcome.

**Comment by JohnMcLear** [comment]
I will create this as a plugin

**Comment by JohnMcLear** [comment]
https://github.com/JohnMcLear/ep_extend_settings

**Comment by JohnMcLear** [comment]
You will need to git pull etherpad as it's a new hook
