### ISSUE TITLE
API Key sent unencrypted

### ISSUE THREAD

**Issue by kunoFM** [ether/etherpad-lite#284]
As far as I can see it, the API key is sent in plain text with every API request. Given the fact, that everybody, who knows the API key can completely manage your server, this might be a bit problematic, or did I get anything wrong?

Other projects (like bigbluebutton http://code.google.com/p/bigbluebutton/wiki/API#API_Security_Model ) use the API key as a salt to generate a checksum for every request. That way, the request can not be manipulated and the key itself is not sent in plain text. 

The API clients would need to make this change too, of course, but it would be  very easy to implement.

**Comment by JohnMcLear** [comment]
@stephan48 How's progress?  Are you still wanting to take this on?

**Comment by stephan48** [comment]
Hi,
Sadly i completely lost focus. I got many projects now so i will sadly have to admit that it probably makes no sense for me to continue "blocking" the bug.
Kind Regards,
Stephan

**Comment by JedMeister** [comment]
@muxator - IMO this one should also be tagged security.

**Comment by muxator** [comment]
Yeah, needs confirmation. Labeling for now.

**Comment by JohnMcLear** [comment]
Just to add  Have multiple API key access and use RESTful API - Perhaps OAuth ? #1960 

to this, more granual controls.  Closing 1960 in favor of this.

**Comment by SamTV12345** [comment]
I guess we can close this. There is now OAuth2.0 with configurable token validity etc.
