### ISSUE TITLE
org-mode import and behaviour

### ISSUE THREAD

**Issue by dariopuerot** [ether/etherpad-lite#2843]
It's a feature request.

Including outliner-like behaviour, with trees collapsing and opening, for working in larger stuff.

Being able to work on org files

**Comment by JohnMcLear** [comment]
@dariopuerot you need to provide more details on what you want here, this is horribly unclear.

**Comment by leinadlime** [comment]
Probably, orgmode.org/ is meant.

This is a really nice way for organizing plaintext,
one feature allows un-/folding text sections,
via simple markup:

* chapter 1
** subchapter a
   here comes some  texxt
** subchapter b

.... and so on

Would love to be able to synchronize an "org-mode"-file with these pads... that's how i arrived here.

there are many different parsers, and web-ui's 
- https://github.com/DanielDe/org-web
- https://github.com/mooz/org-js

i would wish some etherpadeLite dev having a guess, if this can be done, or if not, how else... :)

**Comment by JohnMcLear** [comment]
See ep_markdown et al, just copy/paste using that logic.
