### ISSUE TITLE
Creating list in indented text should be indented too

### ISSUE THREAD

**Issue by bujatt** [ether/etherpad-lite#2844]
1. I am in the editor
2. I press "TAB" and type a few lines of indented text
3. I click on the bulleted list button
4. List items are created but they look de-indented
5. I would expect them to be indented

![](https://s3.amazonaws.com/f.cl.ly/items/192C0B1R2b3r0g2k0c0A/Screen%20Recording%202015-11-26%20at%2003.00%20pm.gif)

OS/browser independent.

**Comment by bujatt** [comment]
#2812 looks to be a related issue.

**Comment by Gared** [comment]
@bujatt Can you please test if you're issue is solved with the latest version of develop?

**Comment by bujatt** [comment]
Thanks @Gared for the note. Just tested it, works well!

![screen shot 2016-02-16 at 10 09 22](https://cloud.githubusercontent.com/assets/2033401/13071694/670146a0-d495-11e5-8ee8-7e40157eb5c2.png)

Thank you!
