### ISSUE TITLE
Paragraph style lost when hitting Enter on line start

### ISSUE THREAD

**Issue by bujatt** [ether/etherpad-lite#2845]
1. I am at the edtior.
2. I add some lines.
3. I set one line to Style "Heading 1"
4. I move the caret to beginning of this styled line
5. I hit ENTER
6. The styling *looks* to be lost. What actually happens: the "Heading 1" styled line is empty, and the content of the styled line is moved one line to bottom and styled as "body text".

**Expected behaviour:**
Move the "Heading 1" style line one line to bottom, and insert an empty line styled as "body text".

![](https://s3.amazonaws.com/f.cl.ly/items/443K2e0j0v45191z3W42/Screen%20Recording%202015-11-26%20at%2005.48%20pm.gif)

**Comment by lpagliari** [comment]
Isn't this an issue of https://github.com/johnmclear/ep_headings2?

**Comment by bujatt** [comment]
Might be. Unfortunately I can't tell as I am not a developer.



—
CEO, cofounder at opp.io

**Comment by lpagliari** [comment]
@bujatt can you open an issue on the plugin repo, please? I believe it is not an Etherpad issue. Tks!

**Comment by bujatt** [comment]
Thank @lpagliari, did so. https://github.com/JohnMcLear/ep_headings2/issues/7
