### ISSUE TITLE
Cannot use HTTP API movePad with spaces in pad name (sourceID)

### ISSUE THREAD

**Issue by dam660** [ether/etherpad-lite#2852]
I cant use the HTTP API movePad method with spaces ont the pad ID (the sourceID).

It works with getRevisionsCount calls for instance.
But when I try the movePad method with these params for instance:
`{ "sourceID": "pad test 1", "destinationID": "pad test 2",  "apikey": "somekey" }`

I have this result:
`{ "code": 1 "message": "padID does not exist"}`

It seems that I have to replace spaces by underscores, but only for this case... I don't feel good using this solution.

May I have missed out something?

**Comment by JohnMcLear** [comment]
I didn't know pads could have spaces in the pad ID, I would assume spaces = ``%20`` or so
