### ISSUE TITLE
Text color not set

### ISSUE THREAD

**Issue by jplatte** [ether/etherpad-lite#2853]
In Firefox, if you change the color settings (under 'Content') to have light text on a dark background per default (for html pages without CSS), this breaks Etherpad Lite because it sets the background color to white, but doesn't set a text color.

Possible fix:

```
#innerdocbody {
  color: #333;
}
```

**Comment by JohnMcLear** [comment]
I feel this is related to a plugin and not Etherpad core?

**Comment by jplatte** [comment]
What? No, it's definitely not. Have you tried reproducing it? It's under `Preferences` > `Content` > `Colors...` in Firefox, but there doesn't seem to be a setting in Chromium / Chrome. But there are probably other browsers out there that derive the background and text color from the system theme or that kind of thing.

Neither the HTML or the CSS standard guarantees the default colors to be black for text and white for background, so if a webapp wants to control the coloring of the page, it should set set both a background color and a text color.

I also attached a screenshot of the settings and how EtherPad looks for me, to be absolutely clear.

![scrot_settings](https://cloud.githubusercontent.com/assets/951129/11998456/3ea25dc6-aaa0-11e5-9b2a-7ea3b7f25d8b.png)
![scrot_etherpad](https://cloud.githubusercontent.com/assets/951129/11998457/3ea5be94-aaa0-11e5-943f-1ad4c32418b8.png)

**Comment by Gared** [comment]
@jplatte Check latest version from develop if this problem is fixed for you now

**Comment by jplatte** [comment]
Yeah, it's fixed now, thanks!
