### ISSUE TITLE
Using SQLite with Etherpad-Lite

### ISSUE THREAD

**Issue by canyon289** [ether/etherpad-lite#2854]
Hi,
I'm trying to use Sqlite with Etherpad-lite and I get this following helpful message. However after following the instructions I still get the same error.

A sqlite3 directory and files do appear in the node_modules directory but this error persists.

I'm at a loss with what to do to move past this error. Any suggestions on what to do next?

-Ravin Kumar
 
>[2015-12-14 10:15:25.148] [ERROR] console - FATAL: The sqlite dependency could not be loaded. >We removed it from the dependencies since it caused problems on several Platforms to compile it. If >you still want to use sqlite, do a 'npm install sqlite3' in your etherpad-lite root folder

**Comment by canyon289** [comment]
Found that I had an issue with the sqlite arch. Not a problem with Etherpad. My apologies

**Comment by pauschuu** [comment]
@canyon289 could you reveal how you exactly solved the problem? I have the same problem after updating and I struggle with finding a solution. Thank you.

**Comment by canyon289** [comment]
Hi @pauschuu 
It's been so long I really can't remember. My apologies

**Comment by pauschuu** [comment]
No worries I found the solution.

As the error message states: 
> [...]If you still want to use sqlite, do a 'npm install sqlite3' in your etherpad-lite root folder

That worked. I just was in the wrong folder before.
