### ISSUE TITLE
Unable to edit files under a directory

### ISSUE THREAD

**Issue by adelriosantiago** [ether/etherpad-lite#2855]
I can't edit files that are under a folder, for example trying to edit the file "css/file.css" will result in 

![cattura](https://cloud.githubusercontent.com/assets/5462382/11792417/e2bb574e-a25a-11e5-84be-214f4f127b32.PNG)

*Not Found*
*The requested URL /p/css/lumston.css was not found on this server.*
*Apache/2.4.7 (Ubuntu) Server at obsidian.lumston.com Port 80*

I'm running etherpad on Linux Ubuntu 12.04, Apache, Node version 10.34.

Any ideas? I remember to be able to change files under directories, I don't know what has changed now.

**Comment by JohnMcLear** [comment]
lulwut?  Fix your rewrite rules.
