### ISSUE TITLE
No licence field

### ISSUE THREAD

**Issue by ljoets** [ether/etherpad-lite#2861]
Hello,
On a fresh install of etherpad-lite (1.5.7) on a Debian Jessie (8) server whith node v4.3.2 and npm v2.14.7, I can see this warning at launch : 
npm WARN package.json ep_etherpad-lite@1.5.7 No license field.
But everything goes fine except this warning ;-)

**Comment by JohnMcLear** [comment]
Resolved

**Comment by ljoets** [comment]
Ok, thanks ;-)
