### ISSUE TITLE
Corrupted Pad

### ISSUE THREAD

**Issue by chrishaigy** [ether/etherpad-lite#2873]
I've got a pad that I'm not able to access. When I try it gives me:

>An error occured
>The error was reported with the following id: '0Tj21dkePSiI4IwMMh8m'
>
>Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this >error message to your webmaster:
>'ErrorId: 0Tj21dkePSiI4IwMMh8m
>URL: https://pads.quorummeeting.com/p/g.2U7nwVRmoAk9CifJ$pad6?>showControls=true&showChat=true&showLineNumbers=true&useMonospaceFont=false
>UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) >Chrome/47.0.2526.106 Safari/537.36
>Uncaught TypeError: Cannot read property 'setChannelState' of null in >https://pads.quorummeeting.com/javascripts/lib/ep_etherpad-lite/static/js/pad.js?>callback=require.define at line 266'

I've tried getting the text with URL/export/txt but I get just get "502 - Web server received an invalid response while acting as a gateway or proxy server."

All the rest of my pads work just fine though. Any ideas of how I can this pad working or, failing that, at least get the text from it?

**Comment by JohnMcLear** [comment]
See https://github.com/ether/etherpad-lite/wiki/Getting-to-know-the-tools-in-bin
