### ISSUE TITLE
adding username to padurl leads to seperate pads

### ISSUE THREAD

**Issue by bor1** [ether/etherpad-lite#2875]
Hello,

I have registered users only, and I want the default name to be their 'userName'.
So when I call the 'padurl' in the 'iframe' I am passing also the 'userName' entry, as follows:
`<iframe src="<% padurl %>&userName=<% userName %>" width="100%" id="iframePad"></iframe>`. The 'userName' in the chat appears the same way it is registered which is what I wanted but, he is suddenly the only User for this Pad.
Now, I can imagine why I am getting different instances of the same 'padurl' where each has only one user, the currently logged in user.
I suppose there is a better way to have all current userNames appear (in the chat) as their registered username.

Maybe someone can help me to find it.

**Comment by JohnMcLear** [comment]
``<iframe src="<% padurl %>&userName=<% userName %>" width="100%" id="iframePad"></iframe>``
is wrong
``<iframe src="<% padurl %>?userName=<% userName %>" width="100%" id="iframePad"></iframe>``
is probably right.
