### ISSUE TITLE
Two inconsistent versions with %20 at the end

### ISSUE THREAD

**Issue by timisch3k** [ether/etherpad-lite#2877]
One can access the same etherpad 
https://beta.etherpad.org/p/test20percent
with the following link as well
https://beta.etherpad.org/p/test20percent%20.
Now these version will split: 
If you start editing one the other will not change.  
Can be seen here:
https://beta.etherpad.org/p/20percenttest
https://beta.etherpad.org/p/20percenttest%20.

Maybe this a feature as one can steal/copy pads.

**Comment by JohnMcLear** [comment]
They are different links ergo different pad Ids ..  I don't see the bug here..

**Comment by timisch3k** [comment]
But then 
foo.com/bar%20 
should be empty, 
(if one had only written something in foo.com/bar). 
Which it is not.
This is the feature (or bug). 
Also firefox bookmarks foo.com/bar%20 as  foo.com/bar,
 which was the reason I was confused.

**Comment by JohnMcLear** [comment]
Have you tried this in production?  I have a feeling you are using dirty as your database....  Try using a production database and see if you have this problem..

**Comment by Gared** [comment]
Any update on this? @timisch3k

**Comment by slel** [comment]
Maybe rename this issue:

    - Two incositent version with %20 at the end.
    + Two inconsistent versions with %20 at the end

**Comment by JohnMcLear** [comment]
This problem doesn't exist if you use Dirty.

It does exist if you use MySQL.

**Comment by JohnMcLear** [comment]
PR in ready for test.  Thanks to @Pita

**Comment by akosiaris** [comment]
As pointed out in https://github.com/ether/etherpad-lite/pull/3817#issuecomment-620026619, the fix has caused a pretty significant performance regression
