### ISSUE TITLE
Error: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_bin'

### ISSUE THREAD

**Issue by skillz-xx** [ether/etherpad-lite#2878]
hello!

Error: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_bin'

since a recent update (via git pull) my etherpad installation on a debian squeeze server wont start anymore..

My mysql version is: MySQL-Client-Version: 5.1.73

Started Etherpad...
[2016-01-10 21:48:06.856] [ERROR] console - ERROR: Problem while initalizing the database
[2016-01-10 21:48:06.857] [ERROR] console - Error: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_bin'

please help. what happened?

thanks
d

**Comment by xjtluapp** [comment]
Your mysql version is too old, place it with the 5.6

**Comment by skillz-xx** [comment]
what if I can't do that on this server for now?

**Comment by IVI053** [comment]
@skillz-xx have you tried changing to a clean tag e.g. with

git checkout -b myBranch 1.5.7

worked for me

**Comment by skillz-xx** [comment]
I have moved my installation to a different VM, since it seemed impossible to run it in Squeeze.

**Comment by Gared** [comment]
So this issue is not relevant for you anymore, @skillz-xx ? Can you close it, please?

**Comment by JohnMcLear** [comment]
This caught me out too..

**Comment by lb1a** [comment]
Same problem on CentOS after upgrading via git pull (on branch develop).
Mysql-Server version: 5.1.73-log Source distribution
Downgraded therpad to pre-upgrade version via git reset --hard HEAD@{1} . 
But I couldn't find a mysql minimum version in the docs. Could anyone give me a hint which mysql version is compatible?

**Comment by Gared** [comment]
You need mysql 5.5.3 or higher for the collation utf8mb4. With version 1.5.7 you can still use your mysql version, but you will get problems with your pads if someone is writing special utf8 characters in it
