### ISSUE TITLE
How to set another default font in pads ?

### ISSUE THREAD

**Issue by ljoets** [ether/etherpad-lite#2879]
Hello,

I am using etherpad with dyslexic pupils, and I would change the default pads font to http://www.dafont.com/fr/andika-basic.font

I installed Andika font on my debian server as specified here : http://linuxandfriends.com/how-to-install-fonts-in-linux-ubuntu-debian/
I added in my src/static/custom/pad.css

#innerdocbody {
font-family: Andika;
font-size: 14px;
line-height: 16px;
}

restarted etherpad-lite

But it seems to have no effect on pads :-(

Any idea ?

Thanks

**Comment by ljoets** [comment]
Hi,
So I am able to change font on everything around the writing area by modifying /home/etherpad/etherpad-lite/src/static/css/pad.css & iframe_editor.css, but the text typing zone still stay with Tahoma, but I don't found Tahoma font in any css file !

Should I create a iframe_editor.css in /home/etherpad/etherpad-lite/src/static/custom/ folder ?

**Comment by rschiang** [comment]
Installing fonts on server would not make the font available on client.
See https://css-tricks.com/snippets/css/using-font-face/

**Comment by ljoets** [comment]
Andika font was already installed on my client. Your solution is useful if the font isn't installed on the client.
But it doesn't solve my problem.
I am able to change font in parameters window, line numbers and everything displayed but not in the pad writing zone !
Please help ! ;-)

**Comment by rschiang** [comment]
I suggested `@font-face` since the original question has mentioned that 

> ... I installed Andika font on my debian server ...

But I think I've understood your question. By inspecting DOM elements, it seems the style of `#innerdocbody` was overridden by `style` attribute. You could see if **[Font Settings]** is interfering with that, or simply override the style with `font-family: Andika !important`.

**Comment by ljoets** [comment]
So I tested in `src/static/custom/pad.css`
```
#innerdocbody {
  font-family: Andika !important;}
```
-> not working
```
body#innerdocbody {
  font-family: Andika !important;}
```
-> not working
It seems that an inline 'font-family' element overrides the css even if I use `!important`.

**Comment by ljoets** [comment]
Sorry, it works fine !
So for my dyslexics users, I added in `src/static/custom/pad.css`
```
body#innerdocbody {
  font-family: Andika !important;
  font-size: 14px;
  line-height: 20px
}
```
But you need to both restart etherpad-lite and refresh browser with CTRL+F5 to see changes ;-)

Thanks !
