### ISSUE TITLE
Is there any way we can display a password protected pad for some users on a wordpress site

### ISSUE THREAD

**Issue by umairriaz90** [ether/etherpad-lite#2883]
Hi, 

I have installed etherpad on a wordpress site. I have to limit the access only to users with a certain role. I don't want to go through authentication because it asks for httpd authentication which I don't want at the user front end to be displayed, so I opted for password protected pads, but now I don't know I have read the whole http API docs but couldn't found how to display a password protected pad to certain users.

**Comment by JohnMcLear** [comment]
See the wordpress etherpad plugin.
