### ISSUE TITLE
BUG: Timeslider not translated when EP is opened with lang parameter

### ISSUE THREAD

**Issue by tiblu** [ether/etherpad-lite#2885]
**Reproduce:**

* Go to https://beta.etherpad.org/p/asd?lang=de
* Go to Timeslider page, by clicking the icon

**Result:**

* Timeslader page is in English

**Expected:**

* Timeslider page to be in German (de)

**Technical info:**

* Etherpad 1.5.7 (02c022a)

**Comment by JohnMcLear** [comment]
Confirmed

**Comment by JohnMcLear** [comment]
Confirmed

**Comment by bhldev** [comment]
@tiblu please get latest develop and confirm, thanks

**Comment by tiblu** [comment]
Thanks, fixed!
