### ISSUE TITLE
Problem with translation into German

### ISSUE THREAD

**Issue by dscso** [ether/etherpad-lite#2895]
Firefox 44.0; Chomium similar problem
Server: Debian 8.3; Kernal 3.16.0-4-amd64
NodeJS Version: v0.10.29

"Neues Dokument" ≙ "New Pad" 
I'm not sure but @german_people: change "Dokument" to Pad
my pull request: https://github.com/ether/etherpad-lite/pull/2896
![image](https://cloud.githubusercontent.com/assets/6866008/12593458/7fb8e54c-c471-11e5-95f9-97ca886d033b.png)

**Comment by akuckartz** [comment]
"Dokument" is word known by every German speaker. "Pad" is neither a German word nor one offen used by Germans.

**Comment by dscso** [comment]
Yes you are right. But even the french translation of etherpad-lite uses "Nouveau pad" or the spanish translation: "Nuevo pad". So I think German is the only language which uses "Dokument" (german document) instead of pad.

**Comment by thmsjkn** [comment]
To me a document (Dokument) is more static than a Pad. I would go with the term "Pad".

**Comment by dscso** [comment]
Me too. Most popular languages are using "pad".

**Comment by Gared** [comment]
I would also prefer "pad" for the german translation. Please use translatewiki.net to change these translations @dscso

**Comment by Gared** [comment]
Fixed
