### ISSUE TITLE
API client author comments

### ISSUE THREAD

**Issue by c-martinez** [ether/etherpad-lite#2897]
Is it possible to use the http-API to insert comments, as if they were written by a user ?

I am writing a _bot_, but I would like him to look like any other author on the pad: have his name on the list of authors, have the text he writes coloured, etc. At the moment I'm using: `getText` / `setText`, but this feels really clumsy. Is there a better way? Would it be desirable to have such a feature in the api? How would one go about implementing this feature?

**Comment by lpagliari** [comment]
@c-martinez take a look on [ep_comments](https://github.com/JohnMcLear/ep_comments#creating-comment-via-api)

**Comment by c-martinez** [comment]
Thanks for the suggestion @lpagliari but I don't think this will do what I need. If I understand correctly, I still need to do `getHTML` / `setHTML` to add the comment tags to the main body of the text.

What I would really want is for my *bot* to be able to "type" on the pad itself and for other user's to see the text from the bot appear in the same way as it does when another user types.

**Comment by Gared** [comment]
@c-martinez I would really appreciate to see this function in the HTTP API. It shouldn't be too difficult to implement this function. Maybe I have time to implement this the next days.

**Comment by c-martinez** [comment]
Hi @Gared -- so it would be a useful feature then. I'll also give it a go at implementing it then. I thought it was better to ask before I started trying to implement it myself. Now that I know it is not yet there and it may be useful, I'll have a go at it.

**Comment by Gared** [comment]
@c-martinez Yes, indeed. Please let me know if you need any help.

**Comment by Gared** [comment]
@c-martinez Any update on this? Do you need any help?

**Comment by c-martinez** [comment]
Nothing yet, sorry @Gared -- I was distracted by another project, but I should get back to it this week.
