### ISSUE TITLE
Missing buttons on mobile iOS 9 - iPhone 6

### ISSUE THREAD

**Issue by dmkanter** [ether/etherpad-lite#2900]
When I load etherpad-lite I'm missing all the buttons. Tried restarting but didn't fix. Just using latest version from 1/31/16

![](http://media.davidkanter.com/Photo-2016-01-31-09-27.jpg)

**Comment by JohnMcLear** [comment]
Please point some other iOS people at this to replicatee.

**Comment by lpagliari** [comment]
Tested on iPhone 5S with iOS 9 on both Safari and Chrome, worked fine for
me when I've accessed https://beta.etherpad.org.

@dmkanter do you have the same issue when you access
https://beta.etherpad.org?
