### ISSUE TITLE
How to use etherpad for multiple databases on same server in Openerp

### ISSUE THREAD

**Issue by raj15feb** [ether/etherpad-lite#2901]
Hi All,
I'm using etherpad for Odoo (ubuntu 14.04). I have multiple(4) database on server. Its all are runned from db filter. How to use etherpad for all these database? Can we use etherpad with different port using same IP. For example: 0.0.0.0:9001, 0.0.0.0:9005, 0.0.0.0:9006 etc..
Thanks......

**Comment by Gared** [comment]
Why do you want to run multiple etherpad instances?
Of course, you can run multiple etherpad installations on different ports. Just modify the port in the settings.json

**Comment by raj15feb** [comment]
Hi Gared,
I want to use etherpad with multiple port for same IP. For example: 0.0.0.0:9001, 0.0.0.0:9005, 0.0.0.0:9006 etc. not different sorry for my mistake in my question. Because I'm using multiple databases on same ip with database filter. And need all databases etherpad. So i need Etherpad on multiple Port.

Thanks

**Comment by Gared** [comment]
You have to run multiple etherpad instances on this server or one etherpad instance with multiple reverse proxies (on different ports)

**Comment by raj15feb** [comment]
Hi Gared,
One more question, Can we run etherpad server like: bin/run.sh --port=9005 or any command that we can assign server with port.
Thanks..

**Comment by Gared** [comment]
You can use multiple settings.json files: https://github.com/ether/etherpad-lite#tweak-the-settings
