### ISSUE TITLE
Attempt to load undefined module

### ISSUE THREAD

**Issue by clayu** [ether/etherpad-lite#2903]
I have clients using software incorporating Etherpad Lite, they are reporting (in alarming numbers) the following error message:

"Attempt to load undefined module. .../static/kernel.js (line 429)"

There's a catch. I cannot reproduce the problem on my machine. (Win 7, Chrome Version 48.0.2564.97 m)

Here's what I know:
* Only occurs in IFrame
* I've cleared the /src/node_modules folder and requested a client clear their cache.
* We can temporarily eliminate the error by clearing the cache, the moment a second pad is loaded, the error occurs.
* Had no problems with the software for several months. Problems started last Friday. 
* No changes were made to the software to prompt this.
* Most clients are using chrome.
* Problems occur on both mac and pc.

I don't have log files with the error message yet, though I've just turned on DEBUG printouts.

npm -v  = 1.3.6
node -v = v0.10.36
Server is running 'Amazon Linux 2015.09'

What do I need to do to fix this by Friday?

Thank you for your help.

**Comment by JohnMcLear** [comment]
Lol
