### ISSUE TITLE
Trigger changeset when inserting new line with js

### ISSUE THREAD

**Issue by JeremyPlease** [ether/etherpad-lite#2904]
I'm attempting to insert a new line of content into a pad from javascript. Essentially, when a user clicks a button a new line of text is inserted after a specific line. 

I've tried the below two methods. Both methods successfully insert the content into the pad, but don't trigger a changeset or save the changes in the pad.

### Method 1: jQuery `.after()`
```
var innerFrame = frames['ace_outer'].frames['ace_inner'];
var $thirdLine = inner.$('body > div:eq(2)')
$thirdLine.after('<div><span>Test line to insert</span></div>');
```

### Method 2: `.ace_replaceRange()`
```
var thirdLine = context.rep.lines.atIndex(2);
context.editorInfo.ace_performSelectionChange([2, 0], [2, thirdLine.width-1], true);
context.editorInfo.ace_updateBrowserSelectionFromRep();	
context.editorInfo.ace_doReturnKey();
context.editorInfo.ace_replaceRange(undefined, undefined, 'Test line to insert');
```

So, my questions is: **How do I insert content into a pad from javascript and trigger a changeset?**

Thanks!

**Comment by JeremyPlease** [comment]
I dug into the ace editor code some more and this is the method I came up with that appears to work. It inserts the new line and changeset is triggered and saved to pad immediately.

```
context.editorInfo.ace_inCallStackIfNecessary('lineInsert', function() {
	var lineIndex = 3;
	var line = context.rep.lines.atIndex(lineIndex);
	var endOfLine = line.width - 1;
	context.editorInfo.ace_performSelectionChange([lineIndex, endOfLine], [lineIndex, endOfLine], true);
	context.editorInfo.ace_doReturnKey();
	var newLineIndex = lineIndex + 1;
	context.editorInfo.ace_replaceRange([newLineIndex, 0], [newLineIndex, 0], 'Test line to insert');
});
```

Anyone see any potential issues with doing it this way?

**Comment by bhldev** [comment]
Hi, just dug into db code yesterday for #2923
Every time a key is pressed is a complete write to the database, at least to dirtydb
Why not just do complete replacement of all the text and do some fancy string replaces?
Have not looked so don't know if that is possible, just an idea

**Comment by JeremyPlease** [comment]
Replacing all of the text would result in loss of proper author highlighting.  
The approach in my last comment worked fine, but I eventually ended up moving things to Quill.js with Socket.io.
