### ISSUE TITLE
etherpad does not install locally

### ISSUE THREAD

**Issue by EvanMisshula** [ether/etherpad-lite#2905]
# etherpad does not install locally<a id="orgheadline2"></a>

## system specs<a id="orgheadline1"></a>

    node --version

v5.0.0

    npm --version

3.3.6

    lsb_release -a

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">Distributor ID:</td>
<td class="org-left">Debian</td>
</tr>

<tr>
<td class="org-left">Description:</td>
<td class="org-left">Debian GNU/Linux 8.3 (jessie)</td>
</tr>

<tr>
<td class="org-left">Release:</td>
<td class="org-left">8.3</td>
</tr>

<tr>
<td class="org-left">Codename:</td>
<td class="org-left">jessie</td>
</tr>
</tbody>
</table>

The latest stable version of node is v5.0.0 as of February
5, 2016. This does work with the version pulled from git.  However,
when the linux/mac file available for download on
<http://etherpad.org/#downloadversion> is used:

    ./bin/run.sh

You're running a wrong version of node, or io.js is not
installed. You're using v5.0.0, we need v0.10.x, v0.11.x or v0.12.x

If you examine release 1.5.7 and look at the file `/ether-etherpad-lite-8359756/bin/installDeps.sh`

    #check node version
    NODE_VERSION=$(node --version)
    NODE_V_MINOR=$(echo $NODE_VERSION | cut -d "." -f 1-2)
    #iojs version checking added
    if hash iojs 2>/dev/null; then
      IOJS_VERSION=$(iojs --version)
    fi
    if [ ! $NODE_V_MINOR = "v0.10" ] && [ ! $NODE_V_MINOR = "v0.11" ] && [ ! $NODE_V_MINOR = "v0.12" ]; then
      if [ ! $IOJS_VERSION ]; then
        echo "You're running a wrong version of node, or io.js is not installed. You're using $NODE_VERSION, we need v0.10.x, v0.11.x or v0.12.x" >&2
        exit 1
      fi
    fi

Whereas the git version contains the approprate code to understand the newer version of node.

    #check node version
    NODE_VERSION=$(node --version)
    NODE_V_MINOR=$(echo $NODE_VERSION | cut -d "." -f 1-2)
    NODE_V_MAIN=$(echo $NODE_VERSION | cut -d "." -f 1)
    #iojs version checking added
    if hash iojs 2>/dev/null; then
      IOJS_VERSION=$(iojs --version)
    fi
    if [ ! $NODE_V_MINOR = "v0.10" ] && [ ! $NODE_V_MINOR = "v0.11" ] && [ ! $NODE_V_MINOR = "v0.12" ] && [ ! $NODE_V_MAIN = "v4" ] && [ ! $NODE_V_MAIN = "v5" ]; then
      if [ ! $IOJS_VERSION ]; then
        echo "You're running a wrong version of node, or io.js is not installed. You're using $NODE_VERSION, we need node v0.10.x or higher" >&2
        exit 1
      fi
    fi

I tried to make this comply with your contributing guidelines. If you would welcome a pull request I can write one. Thank you for your excellent work on this incredibly useful project.

&#x2013;Evan Misshula

**Comment by sheesh** [comment]
+1

**Comment by Gared** [comment]
I know. We have to do a new release.
You can also use the latest version from develop to run etherpad

**Comment by Gared** [comment]
Fixed in the new release: 1.6.0
