### ISSUE TITLE
iceweasel : switching tabs with PgUP/DOWN moves the cursor in the pad

### ISSUE THREAD

**Issue by matrohon** [ether/etherpad-lite#2907]
I'm using iceweasel 44.0-1 and the server is running TurnKey EtherPad version (13.0) with the following plugins : ep_authornames; ep_headings2; ep_markdown; ep_previewimages; ep_prompt_for_name; ep_rss; ep_table_of_contents; ep_syntaxhighlighting.

while writing in etherpad, if I want to move to another tab in iceweasel, I use PgUP/PgDOWN; If I get back to my pad's tab with the same shortcut, the cursor is moved at the bottom or at the top of the tab, depending of which key I used to get back to my pad's tab.

**Comment by bhldev** [comment]
Please see pull #2891 for potential workaround, disable pgup/pgdown through settings.json

**Comment by bhldev** [comment]
Please give [bounty](https://www.bountysource.com/issues/30676386-iceweasel-switching-tabs-with-pgup-down-moves-the-cursor-in-the-pad) for UI/plugin development "enable/disable shortcut keys", UI will look like this  
![image](https://cloud.githubusercontent.com/assets/4929336/13028377/5944fe28-d23b-11e5-936b-3d1783dfeb6c.png)

**Comment by JohnMcLear** [comment]
Page Up and Page Down will always do those tasks.  Are you not using a special key at the same time (Control / Alt )
