### ISSUE TITLE
Error creating new Pad with forward slash in name

### ISSUE THREAD

**Issue by mikesterlingw** [ether/etherpad-lite#2908]
When creating a new pad with a slash in the name (eg. test/slash) the escape character is not escaped resulting in "Cannot GET /p/test/slash"

**Comment by bhldev** [comment]
Checked latest develop branch, cannot reproduce issue currently outputs "Such a pad name is forbidden" when typing in slash in either the pad name at the intro screen or typing it into the browser as escaped

**Comment by mikesterlingw** [comment]
Oh, that's special. I had branched off of an old branch. Deleting issue now.
