### ISSUE TITLE
Frontend test fails

### ISSUE THREAD

**Issue by Gared** [ether/etherpad-lite#2910]
If I try to access the frontend tests I get the following exception (in chromium):
```
Uncaught SecurityError: Blocked a frame with origin "http://localhost:9001" from accessing a frame with origin "http://localhost:9001". The frame being accessed set "document.domain" to "localhost", but the frame requesting access did not. Both must set "document.domain" to the same value to allow access.
```
When I remove the "document.domain" thing from here:
https://github.com/ether/etherpad-lite/blob/develop/tests/frontend/runner.js#L167
It works again.

Tested in latest firefox and chromium. Was there an update on the frame-origin-stuff?

**Comment by lpagliari** [comment]
I've researched a little bit more on this error, and found out that the commits on Jan 8th broke tests (tested on Chrome and Firefox). Commit #638757f is fine, all tests passing; next one is not. Also tried #eeab7e8, which looks like a fix for it, but it's still raising the error.

@JohnMcLear were you working on that?

**Comment by JohnMcLear** [comment]
I was working on the document.domain hacks, I removed them for working drag and drop between windows.
