### ISSUE TITLE
etherpad-lite; Where are the "mail settings" supposed to go?

### ISSUE THREAD

**Issue by farid-ho** [ether/etherpad-lite#2916]
My question about etherpad-lite; 
Where does the **mail configuration** (specified in MyPads administration) get saved actually? in _settings.json_ or in the _MySQL-DB_?
and If in settings.json, would the following be the right Code-Snippet in there? 

.....

      , { "type": "logLevelFilter"
        , "level": "error" // filters out all log messages that have a lower level than "error"
        , "appender":
          { "type": "smtp"
          , "subject": "An error occured in your EPL instance!"
          , "recipients": "bar@blurdybloop.com, baz@blurdybloop.com"
          , "sendInterval": 60*5 // in secs -- will buffer log messages; set to 0 to send a mail for every message
          , "transport": "SMTP", "SMTP": { // see https://github.com/andris9/Nodemailer#possible-transport-methods >>> geh dem bitte mal nach!!!
              "host": "smtp.example.com", "port": 465,
              "secureConnection": true,
              "auth": {
                  "user": "foo@example.com",
                  "pass": "bar_foo"
              }
            }
          }

**Comment by JohnMcLear** [comment]
If this is MyPads issue create it on the MyPads repo.
