### ISSUE TITLE
Timeslider not working again

### ISSUE THREAD

**Issue by helioloureiro** [ether/etherpad-lite#2920]
Hi,

For some unknown reason, timeslider stopped to work.  When I upgraded to 1.5.7, it worked just fine.  Now, this same version, just hanged.

I tried to run "npm cache clear .npm", "npm rebuild" and "npm update".  No success so far. 

Any idea what else I can do to recover functionality?

**Comment by webzwo0i** [comment]
could you open firebug/browser's error console and see if anything shows up there? thx

**Comment by helioloureiro** [comment]
Hi,

Thanks for the prompt response.  I got this.

Uncaught ReferenceError: require is not defined(anonymous function) @ timeslider:241(anonymous function) @ timeslider:271
html10n.js:173 XHR finished loading: GET "http://etherpad/locales.json".window.html10n.Loader.fetch @ html10n.js:173window.html10n.Loader.load @ html10n.js:137(anonymous function) @ html10n.js:897asyncForEach @ html10n.js:717window.html10n.html10n.build @ html10n.js:895window.html10n.html10n.localize @ html10n.js:689(anonymous function) @ l10n.js:7window.html10n.MicroEvent.trigger @ html10n.js:104window.html10n.html10n.index @ html10n.js:963(anonymous function) @ html10n.js:968

**Comment by helioloureiro** [comment]
It can be closed.  For some reason someone (maybe me) commented the line on timeslider.js which was importing require-kernel.js.


./src/templates/timeslider.html
