### ISSUE TITLE
Same issue - not the same solution 

### ISSUE THREAD

**Issue by Netmage-76** [ether/etherpad-lite#2922]
Hello,

I couple of month ago I opened an issue with the following description:

=====================
Hello,

after I installed etherpad lite on freebsd 10.2 I tried to install a couple of plugins.
When I tried to install the plugins via webinterface by clicking "Install" I received the following error message"

An error occured while installing ep_adminpads
EACCES: permission denied, open '/root/.npm/ep_adminpads/0.0.9/package/package.json'

When I use "npm install ep_author_neat" from CLI I see:

npm install ep_author_neat
ep_author_neat@0.0.31 node_modules/ep_author_neat

and the etherpad-lite log shows:

[2015-11-01 10:21:10.412] [WARN] console - { [Error: EACCES: permission denied, open '/root/.npm/ep_adminpads/0.0.9/package/package.json']
errno: -13,
code: 'EACCES',
syscall: 'open',
path: '/root/.npm/ep_adminpads/0.0.9/package/package.json' }
Error: EACCES: permission denied, open '/root/.npm/ep_adminpads/0.0.9/package/package.json'
at Error (native)
[2015-11-01 10:21:10.413] [INFO] console - Restarting express server

I already tried to set /root/.npm/ to 777 without success. The error message is still the same whether I use the command in /root/.npm/ or /usr/local/www/etherpad (the directory I installed etherpad-lite)
In general I wonder why why the json packets are located at the root directory, because etherpad should run at the created user "etherpad".

=====================

Right now I have exactly the same error message. 

For the questions I received afterwards, I have to say that the node version is different: 5.7.0 and the npm is 2.14.7. For the next hint I received I have to say that I don't have the file /usr/local/etc/npmrc, but I added cache = "/tmp/npm" to /usr/local/lib/node_modules/npm/npmrc unfortunately without success.

Does anyone has an hint for me ?

BR Marcus

**Comment by JohnMcLear** [comment]
Clear your npm cache
