### ISSUE TITLE
Check to see if target=_blank causes a security issue

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#2928]
As per https://mathiasbynens.github.io/rel-noopener/

**Comment by JohnMcLear** [comment]
@nashe

**Comment by nashe** [comment]
It is a security issue but honestly, phishing scenarios with Etherpad are pretty limited. 
Maybe the mitigation could be one of ep_hide_referrer's feature (see [`templates/redirect.html`](https://github.com/ether/ep_hide_referrer/blob/master/templates/redirect.html#L25))?
