### ISSUE TITLE
Unordered to ordered list bug

### ISSUE THREAD

**Issue by ber8749** [ether/etherpad-lite#2933]
Switching from an unordered list to an ordered list triggers an error which causes all subsequent list items to be labeled "1."

Replication instructions:
1. Select unordered list
2. Enter text
3. Press Enter/Return button
4. Switch to ordered list
5. Enter text
6. Press Enter/Return button 
7. Repeating steps 5 and 6 will cause all list items to be labeled "1."

**Comment by JohnMcLear** [comment]
Same issue in each browser?

**Comment by ber8749** [comment]
Yes, this problem seems to be browser agnostic.

**Comment by theredfish** [comment]
Hi, 

I don't experience this issue with FF 49.0.2.

**Comment by ber8749** [comment]
Still seeing a variation of this issue in version 1.6.0. Updated replication instructions:

1. Select unordered list
2. Enter text
3. Press enter/return TWICE
4. Select ordered list
5. Enter text
6. Press enter/return
7. All subsequent items will be labeled "1."

Screenshot:
![screen shot 2016-11-30 at 1 54 59 pm](https://cloud.githubusercontent.com/assets/2344085/20773175/67d5030c-b705-11e6-9fbc-56c4ec2acea4.png)

**Comment by monkey-pawan** [comment]
This issue is still there in 1.6.1

**Comment by monkey-pawan** [comment]
Hi,
can any of etherpad maintainer tell me where the command/variables are turned into tags and their attributes are set? maybe I could help you solve this one. I need to know where it is decided whether `<ul>` or `<ol>` is to be inserted in dom and their relevant attributes are set. All I know so far is that anything other than `number` in [doInsertList](https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L5428) will create `<ul>`. I deduced few more things but they don't seem so relevant for now, maybe I could get somewhere with your help. Thanks in advance.

**Comment by JohnMcLear** [comment]
@monkey-pawan Just take a look through the source code for handling list items, I can't remember the exact locations but if you grep for ``ordered-list`` or somesuch you will find something :)

**Comment by JohnMcLear** [comment]
I'm not experiencing this bug but I am seeing super weird horrible behavior that makes my eyes bleed.  Will close this as it seems to be resolved and leave other OL/UL woes open.
