### ISSUE TITLE
Email Settings in MyPads

### ISSUE THREAD

**Issue by farid-ho** [ether/etherpad-lite#2936]
In MyPads plugin as the admin user you can set the desired mail settings. But it doesn't seem to have the effect on etherpad lite in my case; for example there is no "automatic Mail sending" after creating a new user and giving them the invitation to join the pad. Actually I'm not sure where this mail configuration from the plugin(MyPads) get saved in the Application(etherpad-lite)? Is this supposed to be in the "settings.json" or in the "MySQL-DB"?

**Comment by Gared** [comment]
As you wrote: This is not an etherpad related issue.
Open your issue here: https://git.framasoft.org/framasoft/ep_mypads
