### ISSUE TITLE
Nested lists pasted out of Etherpad are not nested.

### ISSUE THREAD

**Issue by edg2s** [ether/etherpad-lite#2941]
Etherpad doesn't use proper nested lists in the view, this means copying these lists into other editors (Word, Google Docs, etc.) results in lost information.

Etherpad is also used a lot within the Wikimedia Foundation for taking notes, and often these notes are then pasted into MediaWiki via VisualEditor, our rich text JS editor (which I work on), so it would be good if lists were preserved correctly.

One could use the export HTML function, but it would be much easier if it just worked on copy, as the user would expect.

We solve this particular problem in VisualEditor by intercepting copy events and making sure the HTML written to the clipboard is semantically correct, as well as that it contains sufficient metadata to be pasted back in to the same editor.

Corresponding issue on MediaWiki's bug tracker: https://phabricator.wikimedia.org/T130970

**Comment by JohnMcLear** [comment]
+1 @edg2s thanks for this I will take a goosey :)

**Comment by JohnMcLear** [comment]
This appears to be fixed.  I can copy/paste into MS Word / Google Docs without any problems.
