### ISSUE TITLE
IPv6 and IPv4

### ISSUE THREAD

**Issue by dscso** [ether/etherpad-lite#2943]
Why isn't it possible to listen at both (IPv4, IPv4) if you don't want to use a proxy (like nginx).

**Comment by Gared** [comment]
Set your ip in your settings.json to a empty value:
```
"ip": "",
```

**Comment by dscso** [comment]
root@vs:~# cat /srv/etherpad-lite/settings.json | grep ip
      "ip": "",
    root@vs:~# curl http://[::1]:8001/
    curl: (7) Failed to connect to ::1 port 8001: Connection refused
    root@klima-ag:~# curl http://127.0.0.1:8001/       
    <!doctype html>
    <html>
    ...
As you can see, it doesn't work.
I am using GNU/Linux Debian 8 x86_64 (systemd) nodejs 0.10.29 npm 1.4.21

**Comment by dscso** [comment]
I've also tried it before.

**Comment by Gared** [comment]
@dscso Try to use ```"::"``` instead.
In the 0.10.x docs they're not mention IPv6: https://nodejs.org/docs/latest-v0.10.x/api/all.html#all_server_listen_port_host_callback
Latest docs: https://nodejs.org/dist/latest-v5.x/docs/api/tls.html#tls_server_listen_port_hostname_callback

I've tested it with the latest node version and it is working with a empty value.

**Comment by dscso** [comment]
You are right... It depends on the Node version. Thank you for your answer.
Great Work with Etherpad-lite. Thank you and all other contributors 👍.

**Summary:** If somebody want to use both (IPv6, IPv4) he/she just have to set the value of "ip" in settings.json to an empty value (`"ip":"",`) and have to use a newer version of Node.
