### ISSUE TITLE
Initial Tab indents mutates to * or disappears

### ISSUE THREAD

**Issue by phoebebright** [ether/etherpad-lite#2945]
If I create a document that makes heavy use of indents (just using tab, not indent or bullet buttons) then use getText to import the content into my app, I get the first tab replaced with a *.  If I simply copy and paste, I lose the first tab level altogether.

I have no plugins installed
If I uses spaces this does not happen and the spaces are maintained correctly.

I've attached a couple of screen shots to demonstrate.  
I can replicate the copy and paste behaviour in beta.etherpad.org and attach a screenshot showing it losing ALL indents when I copy and paste into a text editor.

![screen shot 2016-03-30 at 19 08 40](https://cloud.githubusercontent.com/assets/132747/14152421/2b3a2e6a-f6ab-11e5-877b-18d378023fd8.png)
![screen shot 2016-03-30 at 18 55 50](https://cloud.githubusercontent.com/assets/132747/14152422/2b4fa470-f6ab-11e5-9409-1d3867dfd4fe.png)
![screen shot 2016-03-30 at 18 55 40](https://cloud.githubusercontent.com/assets/132747/14152423/2b69f14a-f6ab-11e5-9f8d-8d44116811f4.png)

Would really like to understand what is going on as indents are critical to what I'm doing.  

Information on my install of etherpad:

Etherpad  

Version number: 1.5.6

Git sha:

Installed plugins

ep_etherpad-lite
Installed parts

ep_etherpad-lite/swagger
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/webaccess
ep_etherpad-lite/padreadonly
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/static
ep_etherpad-lite/express
Installed hooks

Server side hooks

expressCreateServer
ep_etherpad-lite/node/hooks/express/swagger:expressCreateServer from ep_etherpad-lite/swagger
expressCreateServer
ep_etherpad-lite/node/hooks/express/adminsettings:expressCreateServer from ep_etherpad-lite/adminsettings
expressCreateServer
ep_etherpad-lite/node/hooks/express/adminplugins:expressCreateServer from ep_etherpad-lite/adminplugins
expressCreateServer
ep_etherpad-lite/node/hooks/express/admin:expressCreateServer from ep_etherpad-lite/admin
expressCreateServer
ep_etherpad-lite/node/hooks/express/tests:expressCreateServer from ep_etherpad-lite/tests
expressCreateServer
ep_etherpad-lite/node/hooks/express/socketio:expressCreateServer from ep_etherpad-lite/socketio
expressCreateServer
ep_etherpad-lite/node/hooks/express/errorhandling:expressCreateServer from ep_etherpad-lite/errorhandling
expressCreateServer
ep_etherpad-lite/node/hooks/express/importexport:expressCreateServer from ep_etherpad-lite/importexport
expressCreateServer
ep_etherpad-lite/node/hooks/express/apicalls:expressCreateServer from ep_etherpad-lite/apicalls
expressCreateServer
ep_etherpad-lite/node/hooks/express/padreadonly:expressCreateServer from ep_etherpad-lite/padreadonly
expressCreateServer
ep_etherpad-lite/node/hooks/express/padurlsanitize:expressCreateServer from ep_etherpad-lite/padurlsanitize
expressCreateServer
ep_etherpad-lite/node/hooks/express/specialpages:expressCreateServer from ep_etherpad-lite/specialpages
expressCreateServer
ep_etherpad-lite/node/hooks/i18n:expressCreateServer from ep_etherpad-lite/i18n
expressCreateServer
ep_etherpad-lite/node/hooks/express/static:expressCreateServer from ep_etherpad-lite/static
socketio
ep_etherpad-lite/node/hooks/express/adminsettings:socketio from ep_etherpad-lite/adminsettings
socketio
ep_etherpad-lite/node/hooks/express/adminplugins:socketio from ep_etherpad-lite/adminplugins
expressConfigure
ep_etherpad-lite/node/hooks/express/webaccess:expressConfigure from ep_etherpad-lite/webaccess
createServer
ep_etherpad-lite/node/hooks/express:createServer from ep_etherpad-lite/express
restartServer
ep_etherpad-lite/node/hooks/express:restartServer from ep_etherpad-lite/express
Client side hooks

**Comment by JohnMcLear** [comment]
* looks like the line style identifier character, that is nasty.

Do you experience the same in every browser?

**Comment by phoebebright** [comment]
Only able to test on OSX Chrome 50 and Firefox 45.  On pasting in some indented text I find that:
Chrome ignores indents of both spaces and tabs
Firefox shows correct indents but is changing tabs to spaces (not a problem for me)

Have attached the test text that I pasted

[testindent.txt](https://github.com/ether/etherpad-lite/files/249623/testindent.txt)
![screen shot 2016-05-04 at 22 36 32](https://cloud.githubusercontent.com/assets/132747/15030240/0b4481dc-1249-11e6-846d-dc9e8a83c872.png)
![screen shot 2016-05-04 at 22 35 37](https://cloud.githubusercontent.com/assets/132747/15030239/0b434024-1249-11e6-8b81-5e3669aaa504.png)

**Comment by JohnMcLear** [comment]
Just waiting on testing and merge now, should be fixed.

**Comment by JohnMcLear** [comment]
Just waiting on testing and merge now, should be fixed.

**Comment by phoebebright** [comment]
Great!
