### ISSUE TITLE
Frontend travis sauce test doesn't run

### ISSUE THREAD

**Issue by tfsamaral** [ether/etherpad-lite#2948]
After unzipping the "sauce.zip", just gives an error "Missing required arguments USERNAME, API_KEY".

Like so: 
**Archive:  /tmp/sauce.zip
      inflating: /tmp/NOTICE.txt
      inflating: /tmp/license.html
      inflating: /tmp/Sauce-Connect.jar
Missing required arguments USERNAME, API_KEY**

I noticed it when trying to do a pull request

**Comment by JohnMcLear** [comment]
Only me and Pita appear to be authorized to do this, I can't remember how it's setup.. ;\

**Comment by jainendra** [comment]
Please close this issue if resolved

**Comment by lpagliari** [comment]
not resolved yet

**Comment by rhelmer** [comment]
I can get into the github and travis configs, looks like the `SAUCE_USER` and `SAUCE_ACCESS_KEY` are not set. I'll see if I can't figure it out.

**Comment by rhelmer** [comment]
OK well I got it a little closer - I made a new sauce labs account (etherpad-lite, but we can probably get them to merge and just use etherpad). Now the travis script appears to be hanging instead of erroring out, so there is further work to be done.

@lpagliari I suggest we disable the sauce labs integration (maybe just comment it out) until it's functional, so contributors don't get confused by their PRs failing. What do you think?

**Comment by lpagliari** [comment]
Thanks for working on this, @rhelmer ! [My understanding](https://github.com/ether/etherpad-lite/issues/3179#issuecomment-299856724) was that we needed to use JWT to enable PRs to run SauceLabs + Travis:

> Note that due to security restrictions, the Sauce Labs addon is not available on pull request builds unless you use the JWT Addon.

From [here](https://docs.travis-ci.com/user/sauce-connect/).

But I'm fine with disabling the integration until we fix this -- lately most of the improvements of Etherpad come from external PRs anyway.

**Comment by muxator** [comment]
This was dealt with in #3230 (59ba183c82eb) disabling the Sauce integration.

BTW, in the meantime `tests/frontend/travis/sauce_tunnel.sh` rotted, because it now tries to download a file that gives an HTTP/404. I'll add a comment in the code anyway.

**Comment by muxator** [comment]
For context: the Saucelab frontend tests were enabled again by John and me with 61f0b5db0bfe, and the following work.
