### ISSUE TITLE
Yoruba 'special' character deletes the next character on Chrome

### ISSUE THREAD

**Issue by hardcorekancil** [ether/etherpad-lite#2949]
Hello Github contributors,

My Yoruba class uses [Etherpad.fr](url) as a collaborative tool and some users are experiencing problems when typing characters such as ṣ ẹ́ ì ọ̀ etc. This occurs only on Google Chrome with Windows, not on Firefox. We use a custom keyboard layout designed to type Yoruba.

Here are the steps leading to the issue:
1. Type character ẹ by key combination ALTGR + e (or any other character obtained by a key combination using ALTGR)
2. On Chrome, the next character on the right is erased

I am new to this forum and just an end user with no coding experience so I hope the issue was expressed clearly enough. I'd be happy to explain further and carry out some tests if you have ideas on how to get past this.

Thanks!

**Comment by JohnMcLear** [comment]
I'm unable to replicate this @hardcorekancil - can you let me know if you can still replicate it and I will re-open this issue.

Please test at https://beta.etherpad.org
