### ISSUE TITLE
Useless comparison in sessionsAndGroups test

### ISSUE THREAD

**Issue by xiemaisi** [ether/etherpad-lite#2951]
[This line](https://github.com/ether/etherpad-lite/blob/15c9041f129c68cedade9b663fe5f8725d8264fb/tests/backend/specs/api/sessionsAndGroups.js#L159) looks wrong (it compares a Boolean to a string):

```javascript
if(res.body.code !== 0 || !res.body.data === "john") ...
```

I assume it should be this?

```javascript
if(res.body.code !== 0 || res.body.data !== "john") ...
```

**Comment by JohnMcLear** [comment]
heh yeah :)  Please send PR w/ this fix in :)
