### ISSUE TITLE
SSL Certificate Expired on Plugin Static Site

### ISSUE THREAD

**Issue by n03lx** [ether/etherpad-lite#2955]
The static.etherpad.org site has an invalid SSL certificate which leads to the following error when attempting to fetch the /admin/plugins page on an etherpad instance.

<img width="735" alt="screen shot 2016-04-29 at 12 28 48 pm" src="https://cloud.githubusercontent.com/assets/6200997/14922495/f06018b4-0e05-11e6-814d-d0bb5f7cd924.png">

**Comment by Gared** [comment]
@JohnMcLear Could you please renew the certificate?

**Comment by j0ker-222** [comment]
same problem. 
sorry, how can i renew certificate?

**Comment by wolfskaempf** [comment]
@j0ker-222 You can not. The certificate is on a server owned by (I assume) one of the maintainers of the project. He or she will have to renew the certificate.

**Comment by JohnMcLear** [comment]
Sorry been busy..

**Comment by wolfskaempf** [comment]
@JohnMcLear Is it a certificate issued by Let's Encrypt? In that case I could send you a handy cronjob which automatically renews the certificate on a regular basis.

**Comment by JohnMcLear** [comment]
It's provided by GlobalSign at current.

**Comment by JohnMcLear** [comment]
@wolfskaempf sorted this :)  beta.etherpad.org still needs doing :) though @wolfskaempf  if you fancy it?

**Comment by wolfskaempf** [comment]
I'll take care of it!

2016-05-04 22:41 GMT+02:00 John McLear <notifications@github.com>:

**Comment by wolfskaempf** [comment]
Fixed as well. Should renew automatically now.

**Comment by wolfskaempf** [comment]
@JohnMcLear I think you can close this bug.

**Comment by JohnMcLear** [comment]
Thanks @wolfskaempf btw we appreciate this!  You rock!
