### ISSUE TITLE
What if a bot generates millions of pages?

### ISSUE THREAD

**Issue by dbech** [ether/etherpad-lite#2958]
If a bot or something just kept loading page after page where xxxx represents some random string it's generated as below.

`https://beta.etherpad.org/p/xxxx `

I'd imagine this would eventually crash the site right? Or is there some protection for this?

**Comment by JohnMcLear** [comment]
Rate limit on reverse proxy ftw.

**Comment by rugk** [comment]
So if this is the only solution, I think you can also close this issue, because when contributors look for "easy to solve" issues they do not really expect such issues...
