### ISSUE TITLE
Settings: Option for changing paths

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#2959]
I am trying to install etherpad on my server so one can access it via `www.example.com/etherpad` and the pads e.g. like this `www.example.com/etherpad/pad`.

You especially have a "subdirectory" part [in your wiki for nginx](https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#from-subdirectory-url), but even when using this config there I have a problem, because etherpad always sends the HTML so that the browser requests the files from the root dir, so it e.g. requests this:
- `/static/js/html10n.js`
- `/static/custom/index.css`
- `/locales.json`

This is bad for my use case as I rather want it to request the files like this:
- `/etherpad/static/js/html10n.js`
- `/etherpad/static/custom/index.css`
- `/etherpad/locales.json`

However in the `settings.json`I could not find an option to change the paths.
So:
1. How can I do this?
2. Could you please add these options to the settings file?

**Comment by rugk** [comment]
Ah okay, I just solved `1)`.
This is basically done by [`proxy_redirect`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect) and your config works.

So I wonder whether 2) would still be useful...

**Comment by JohnMcLear** [comment]
Is there a plugin for this?

**Comment by rugk** [comment]
AFAIK no. I've seen no one.

**Comment by rugk** [comment]
This issue is still relevant IMHO. #badbot :no_bell::robot::no_bell:
