### ISSUE TITLE
Option to deactivate viewing/editing settings.json in admin dashboard

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#2960]
I am really not keen on viewing my `settings.json` in my admin dashboard.
This is very sensitive as all password (including potential database passwords) are included and I do not really want to have them travelled over the net.
Especially I (and a potential attacker) do not want to edit my setting over a web interface!

The issue is that an attacker who gains access to the admin password immediately gains access to my database too! This is unjustifiable!
Another - very simple scenario - is it that I e.g. want to show a person the etherpad admin panel (or my installed plugins, ...), but when I accidentally click "Settings" the person sees all my passwords!

That's not what I want. As I see few reasons and many potential security issues when showing (and allow editing!) config files (which are also sensitive without passwords in them) over the web, I would at least like an option to disable the whole "Settings" part in the admin panel.
Alternatively you may just censor passwords or such things, but this would only be a partial solution.

With this setting you have much less issues when your admin dashboard passwords is in the hands of an attacker. Currently you have failed as an attacker can change any config values and knows your passwords, when such a thing happens.

**Comment by noerw** [comment]
feature is implemented in #2991 - can be closed now?
