### ISSUE TITLE
Plugin installation does not (re)load translation

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#2965]
See https://github.com/JohnMcLear/ep_comments/issues/91

**Comment by JohnMcLear** [comment]
Steps to replicate.  

1. Install a plugin via cli ``npm install ep_email_notifications@0.1.4``
1. Update a plugin via the web UI

Language strings wont be updated in UI.

But this appears to be part of a different issue.  This plugin isn't showing right locale for me.  Will try ep_comments_page next.
