### ISSUE TITLE
[1.6.0] missing CHANGELOG update

### ISSUE THREAD

**Issue by Cyrille37** [ether/etherpad-lite#2971]
Hi,
The CHANLOG.md is not uptodate in tag 1.6.0.
To know 1.6.0 changes, have to look at develop branch

Cheers.

**Comment by Gared** [comment]
This was my mistake. I tagged the wrong commit, but I can't easily change the tag to another commit.

**Comment by JohnMcLear** [comment]
Next time we will get it right :)
