### ISSUE TITLE
aceEditEvent fires every second?

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#2973]
Using the add-on ep_countable:

> In the browser console I can see the numbers update nearly every second (even if the popup is not opened).
I think this is not good for performance and it is - at least - unnecessary. I can imagine this can lead to problems with large Etherpads.

> ![constantchange](https://framagit.org/luc/ep_countable/uploads/1de28aa0868efec2636d780a2916ddfa/constantchange.gif)

Original issue: https://framagit.org/luc/ep_countable/issues/4

**Comment by ldidry** [comment]
More infos: with aceEditEvent, we expect to have an event only if there is an edition. The aceEditEvent is fired with idleTimeworker type.

Is it wanted? If yes, maybe the documentation need some more explanation about when this event is fired.

**Comment by JohnMcLear** [comment]
This is a plugin bug.

**Comment by rugk** [comment]
As @ldidry explained it is not. And if it is it means the doc is incorrect or ambiguous.
@ldidry please explain it again, so this issue can be reopened.

**Comment by lpagliari** [comment]
"Edit" events can be a lot of things (changing the text, adding an attribute to one line or a piece of text, etc). If by "edit" you want any text change, `aceEditEvent` has some information on the `context` that might help you. Check the flag `context.callstack.docTextChanged` for that scenario.

The issue reported by @rugk is indeed as an issue with the plugin, as it should not update the values if no changes were made.

Regarding the doc, it can certainly be improved, and [every help is appreciated] (https://github.com/ether/etherpad-lite/wiki/FAQ#im-not-a-developer-how-can-i-help-you). Could you submit a PR with more details on the documentation of `aceEditEvent`? :-)

**Comment by ldidry** [comment]
> "Edit" events can be a lot of things (changing the text, adding an attribute to one line or a piece of text, etc)

Or, as I said, idleTimeworker, which occurs every second :smiley: 

> The issue reported by @rugk is indeed as an issue with the plugin, as it should not update the values if no changes were made.

Yes, we know that (and it's fixed, but by using [different hook](https://framagit.org/luc/ep_countable/commit/d13c55eee1589fb39fd8e856b68bc792ec683de2)), but the lack of doc didn't help to understand `aceEditEvent` behavior.

> Could you submit a PR with more details on the documentation of aceEditEvent? :-)

Sure, I will. Could you please tell me where I can find the code of the callstack, to know what's in it?

**Comment by lpagliari** [comment]
> and it's fixed, but by using [different hook](https://framagit.org/luc/ep_countable/commit/d13c55eee1589fb39fd8e856b68bc792ec683de2)

That explains why I didn't find anything on the plugin code this morning that showed me why that behavior was happening... :smiley: 

> Could you please tell me where I can find the code of the callstack, to know what's in it?

Sure! You can find it on [ace2_inner](https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L452)

Thanks a lot, @ldidry !!
