### ISSUE TITLE
Small ambiuity in FAQ

### ISSUE THREAD

**Issue by fisx** [ether/etherpad-lite#2979]
In https://github.com/ether/etherpad-lite/wiki/FAQ#is-there-help-or-general-discussion-available, you say "20:00" is an active time, but you don't mention the time zone.  I would fix it myself, but I don't want to guess.  (-:

**Comment by JohnMcLear** [comment]
8pm  GMT :)

**Comment by fisx** [comment]
Erm...  you closed it, but i am still seeing the old text without TZ info in the FAQ?

**Comment by rugk** [comment]
Well... [it's a wiki](https://github.com/ether/etherpad-lite/wiki/FAQ/_compare/a906fc1b13cf521397f8025ce1678e0a36432a33...7c9e2c172193bee35ad6f3042fc35a79827405b4).

BTW:
> GMT was formerly used as the international civil time standard, now superseded in that function by Coordinated Universal Time (UTC).

https://en.wikipedia.org/wiki/Greenwich_Mean_Time
That's why I'm using UTC there.
