### ISSUE TITLE
Add to fail2ban config

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#2980]
Has anyone a RegExp for parsing the Etherpad log file, so it can be added to Fail2Ban?

@fail2ban

**Comment by xjer** [comment]
> Has anyone a RegExp for parsing the Etherpad log file, so it can be added to Fail2Ban?
> 
> @fail2ban

Did you by any chance found a workaround for this?

**Comment by rugk** [comment]
No, unfortunately not.
