### ISSUE TITLE
Admin interface: Enable/Disable plugins without uninstalling

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#2983]
[Here](https://github.com/ether/etherpad-lite/issues/2981) I got this idea and I'm a bit surprised that there is not an issue about this for this already.

**Comment by lpagliari** [comment]
Can you submit a PR with that feature? It would be a nice contribution to the project...

**Comment by rugk** [comment]
I have no idea how to do it. I'm also not that experienced in JS programming.

But you can tag it with "good volunteer task" or something similar.

**Comment by JohnMcLear** [comment]
I Feel like this is a duplicate of another issue..

**Comment by rugk** [comment]
But which one... :laughing: 

Note: Of course I have looked for dupes, but I found no one.

**Comment by JohnMcLear** [comment]
Please start being more independent.  https://github.com/ether/etherpad-lite/issues/967
