### ISSUE TITLE
I wonder "recreateDOM" in ace2_inner.js

### ISSUE THREAD

**Issue by yoonyoungkim** [ether/etherpad-lite#2990]
What is "recreateDOM"s role in ace2_inner.js?
It runs well without "recreateDOM".
But it make the program slow down.

**Comment by JohnMcLear** [comment]
It recreates the DOM..

**Comment by yoonyoungkim** [comment]
I tracked down that. It used in 'setWraps'. 'setWraps' called when ace_setProperty initialized for setting in setting.json. But 'setting.json' don't have using it.

**Comment by yoonyoungkim** [comment]
Besides, when it removes, it speed up.

**Comment by JohnMcLear** [comment]
Sorry for late reply..  Say you have a line 12345, but there are 2000+"1"'s..  IE 1111.....*500.  Etherpad will wrap that string.  It rebuilds the DOM to do it.

Removing it will break other things (specifically create slowness in other browsers..
