### ISSUE TITLE
Nginx claims the websocket POST requests fail, but this seems to be wrong

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#2992]
I have asked a question about this on Serverfault, but as I talk about your software, I wanted to let you the chance to answer the question by yourself if you can.
I also doubt that this can be fixed in Etherpad, but at least I wanted to let you know...

The full description is here: https://serverfault.com/questions/778814/websocket-proxy-with-nginx-error-about-post-request-in-server-log-but-works-in

So in short:
* Nginx reports that the POST & Websocket requests fail (`Connection refused`)
* In my browser I can see these requests to be successful
* Everything with Etherpad seems to work
* There are no errors with Etherdraw, because it seems Etherdraw does not use POST requests to Socket.io

In my view this is a very strange behaviour...
If you have no idea about why this might happen, you can of course close this issue.

**Comment by webzwo0i** [comment]
Imo this can happen if you have conflicting IPv4 and IPv6 priorities and your name server (if you don't hard code IP addresses in nginx) returns addresses for both families but node is listening on only one of them. So I would start debugging with tcpdump.

**Comment by rugk** [comment]
Thanks for the tip. I'll try it out.

**Comment by rugk** [comment]
BTW: It worked!
