### ISSUE TITLE
exploration of a version into history 

### ISSUE THREAD

**Issue by PhilLAL** [ether/etherpad-lite#2995]
Hi, 
I tried to use history to find some modifications, but it is very complex to find them into text of more than 10000 lines.
It would be great if a tool allow to navigate between modifications into a version of a pad history.

For instance, it could be a line of a few pixels width and a fixed height. This height would represent the length of the document, and some red pixels would represent the places into the document where lines have been modified between this version and the former one.

Ideally, when we open a version, we are placed at the first modification, and two buttons allow to go to next/former modification into the document.

**Comment by JohnMcLear** [comment]
ep_diff does this no?

**Comment by PhilLAL** [comment]
Sorry, I think I did not knew it exists. I will check this, thank you.

**Comment by PhilLAL** [comment]
Do you talk of ep_timesliderdiff?

**Comment by JohnMcLear** [comment]
Yea

On 20 Jun 2016 09:24, PhilLAL <notifications@github.com> wrote:

Do you talk of ep_timesliderdiff?
