### ISSUE TITLE
PDF / Word export doesn't work with nested lists in the end of a pad

### ISSUE THREAD

**Issue by raimann** [ether/etherpad-lite#2997]
If you write in a pad, and the last line ist a nested list on the second level, the Export doesn't work.

I added a few screenshot to show the problem. It's written in the pad, where the export works and where not:
this works:
![bildschirmfoto 2016-06-07 um 16 35 02](https://cloud.githubusercontent.com/assets/7721945/15861870/035a4e08-2cce-11e6-99dc-32d260dfaea0.png)

this doesn't work
![bildschirmfoto 2016-06-07 um 16 34 37](https://cloud.githubusercontent.com/assets/7721945/15861869/0359dd6a-2cce-11e6-9e3c-a9d020a0cf01.png)

this works:
![bildschirmfoto 2016-06-07 um 16 34 05](https://cloud.githubusercontent.com/assets/7721945/15861868/03593f2c-2cce-11e6-9978-d7d44a5aae0a.png)

**Comment by lpagliari** [comment]
Do you get an error message? Or the line is exported incorrectly?

**Comment by JohnMcLear** [comment]
I have a feeling this guy is using a third party instance and isn't the site admin..

**Comment by raimann** [comment]
I installed Etherpad on different servers, to use it with a LMS. I'm the site admin of these installations. ;-)
But the screenshots are from another site, not my own, where the problem also exists.

**Comment by JohnMcLear** [comment]
Please export the .etherpad file so I can import and replicate.

**Comment by JohnMcLear** [comment]
I can replicate this locally...

**Comment by JohnMcLear** [comment]
The HTML is wrong..

```
<body>
<ul class="bullet">
        <li>hello</li>
        <ul class="bullet">
                <li>world</li>
        </ul>
        </li>
        </ul></body>
</html>
```

**Comment by JohnMcLear** [comment]
This bug has existed for years..  It was introduced so far back I can't get such an old version of Etherpad to install...

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/ExportHtml.js#L474 is the offending line.  I don't have time to dig much deeper than this but I expect a catch to see if we are still in a nested list would solve the problem.  @webzwo0i did a lot of work on this so he might be able to get a fix in quicker than me!

**Comment by skupfer** [comment]
Still relevant ... Cannot export my pads. This isn't related to the last line only because the last 20 lines are text

```
<rpad_export_196131594.html /tmp/etherpad_export_196131594.pdf pdf           ror: convert /tmp/etherpad_export_196131594.html /tmp/etherpad_export_19
AbiWord: could not open the file [/tmp/etherpad_export_196131594.html]
error -1
AbiWord:>
    at module.exports (/usr/share/nginx/www/etherpad-lite/src/node_modules/async-stacktrace/ERR.js:46:13)
    at /usr/share/nginx/www/etherpad-lite/src/node/handler/ExportHandler.js:182:36
    at /usr/share/nginx/www/etherpad-lite/src/node_modules/async/lib/async.js:254:17
    at /usr/share/nginx/www/etherpad-lite/src/node_modules/async/lib/async.js:151:21
    at /usr/share/nginx/www/etherpad-lite/src/node_modules/async/lib/async.js:251:21
    at Object.callback (/usr/share/nginx/www/etherpad-lite/src/node_modules/async/lib/async.js:615:34)
    at stdoutCallback (/usr/share/nginx/www/etherpad-lite/src/node/utils/Abiword.js:135:14)
    at Socket.<anonymous> (/usr/share/nginx/www/etherpad-lite/src/node/utils/Abiword.js:116:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
<rpad_export_196131594.html /tmp/etherpad_export_196131594.pdf pdf
AbiWord: could not open the file [/tmp/etherpad_export_196131594.html]
error -1
AbiWord:>
    at module.exports (/usr/share/nginx/www/etherpad-lite/src/node_modules/async-stacktrace/ERR.js:46:13)
    at /usr/share/nginx/www/etherpad-lite/src/node/handler/ExportHandler.js:182:36
    at /usr/share/nginx/www/etherpad-lite/src/node_modules/async/lib/async.js:254:17
    at /usr/share/nginx/www/etherpad-lite/src/node_modules/async/lib/async.js:151:21
    at /usr/share/nginx/www/etherpad-lite/src/node_modules/async/lib/async.js:251:21
    at Object.callback (/usr/share/nginx/www/etherpad-lite/src/node_modules/async/lib/async.js:615:34)
    at stdoutCallback (/usr/share/nginx/www/etherpad-lite/src/node/utils/Abiword.js:135:14)
    at Socket.<anonymous> (/usr/share/nginx/www/etherpad-lite/src/node/utils/Abiword.js:116:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

**Comment by poVoq** [comment]
yeah... still happens :(

**Comment by JohnMcLear** [comment]
Not sure why this is still open it was resolved ages ago...  :?  I'm unable to replicate in 1.8.0 with or without abiword..
