### ISSUE TITLE
Generate menu links on admin page

### ISSUE THREAD

**Issue by Gared** [ether/etherpad-lite#3001]
The links on the menu on all admin pages are hard coded in the template files.
This leads to a problem to generate differnt links on differnt pages like here:
https://github.com/ether/etherpad-lite/blob/a3188cf3574234f17f927499c2f739c2bd5fd9d3/src/templates/admin/plugins-info.html#L16-L20
and
https://github.com/ether/etherpad-lite/blob/a3188cf3574234f17f927499c2f739c2bd5fd9d3/src/templates/admin/index.html#L16-L20

If you want that the links also work in your plugin you have to do some weird thinks like this: https://github.com/spcsser/ep_adminpads/blob/afd49b119c0d743af453d75187ca64c9df4aa10f/index.js#L157

So I think we have to generate links by etherpad core to fix this problem.

**Comment by JohnMcLear** [comment]
@Gared Would your solution work if Etherpad was hosted in a subdir IE http://mysite.com/etherpad/admin ?

Looking at https://github.com/spcsser/ep_adminpads/blob/afd49b119c0d743af453d75187ca64c9df4aa10f/index.js#L154 I'm skeptical.

**Comment by JohnMcLear** [comment]
We use basePath to do this elsewhere..

```
let basePath = document.location.href.substring(0, document.location.href.indexOf("/admin"));
let yourLink = basePath + "/someEndPointForPlugin";
```
I don't think we should do this on the server because it's 2 lines of JS (see above) and if we start creating the logic on the server it's part of a bigger job IE assigning name space to plugins IE forcing you to use /admin/ep_admin_pads and that's a slippery slope.
