### ISSUE TITLE
Set Link header for server push

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#3003]
It would be nice if you could set link headers for pushing assets to the user. Especially the [HTTP/2 server push](https://blog.cloudflare.com/announcing-support-for-http-2-server-push-2/) is an efficient way of doing that and it really speeds up website loadings.

And you have a lot of assets, which are loaded _always_ when accessing a pad,  so this is a very good scenario for HTTP/2 server push.

**Comment by JohnMcLear** [comment]
We will wait for Express to mature into this.
