### ISSUE TITLE
Announcing ep_oauth2

### ISSUE THREAD

**Issue by oliamb** [ether/etherpad-lite#3006]
Hi,

_I did not find a better spot to announce it so I put an issue here._

I release the first version of an Etherpad Lite OAuth2 plugin, called ep_oauth2. passport.js and the passport-oauth are the backbone of this library.

https://github.com/HumanBrainProject/ep_oauth2

It does not handle the authorization hook at this point. I don't come up with one right way to do it, and I fear that it will prevent people to use it. Only the authentication is managed.

I am of course willing to accept contributions, issues and comments.

Thanks to the whole community for doing Etherpad, it is awesome!

**Comment by JohnMcLear** [comment]
Yay :) Thanks!

**Comment by JohnMcLear** [comment]
btw the mailing list is probably a better place ;)
