### ISSUE TITLE
make correction appear as a crossed out word

### ISSUE THREAD

**Issue by FilLupin** [ether/etherpad-lite#3007]
When a word (or more) is deleted (or replaced), some users prefer to view it appear as crossed out more than simply disappear from text.
Since the 4th button allow to cross out some characters, it seems the behaviour could be the following: -When deleting a word, the word is crossed out.
-When replacing a word, the word is crossed out and next to it appear the replacing word.
-In both case, a metadata indicates this crossed out word is a correction.

After one of these action, a boolean has_deletion is set to true and a button allow to validate all previous modification which have been done since the last validation (or the creation of document).
When clicking on the validation button, all words with metadata indicating they are corrections are deleted and the boolean has_deletion is set to false.

History should keep crossed out word with metadata attached to it.

**Comment by JohnMcLear** [comment]
I have to deal with documents that sometime exhibit this behavior and it's a fucking nightmare.  Use the timeslider.  I will leave it open as a feature request but I hope to god no one ever implements it inside of Etherpad.

**Comment by PhilLAL** [comment]
I agree you can do this through timeslider but the visibility is absolutly not the same : while you would see each modification immediatly with this suggestion, you need to slide each modification by using timeslider, and it is not intuitive for users. 
For example, it is not cleat why there are steps in timeslider at time T1, T2 and T3 but not between these steps.
The proposition to validate modification will avoid this experience you had with some documents. I have the same, that's the reason I though about this validation step.

**Comment by PhilLAL** [comment]
It would be clearer not to need to open history IMHO

**Comment by JohnMcLear** [comment]
we would welcome it as a plugin :)

**Comment by JohnMcLear** [comment]
See ep_who_chaged_what and ep_what_did_i_miss plugins.
