### ISSUE TITLE
Official, Lightweight Docker Image

### ISSUE THREAD

**Issue by sammcj** [ether/etherpad-lite#3010]
It would be fantastic if there could be an official, lightweight (based off Alpine preferably) Docker image for etherpad.

Lots of people are hesitant to install and maintain apps (Especially NodeJS app servers) directly onto servers and having the ability to quickly spin up Etherpad as a docker image on one or many servers not only greatly simplifies the install and deployment process, but _can_ add a layer of security when coupled with SELinux and proper cgroup isolation. (Note: I am not saying that Docker itself adds security).

Node and Docker have a quick getting started that may help you out here: https://nodejs.org/en/docs/guides/nodejs-docker-webapp/ that tutorial isn't too bad, it will result in a Debian Jessie based image, but a lightweight one - really the only thing that could be better than that is an Alpine based image, but that could be a future milestone ;)

**Comment by lpagliari** [comment]
I'm not sure if this is what you need, but maybe it can help: https://github.com/ether/etherpad-docker.

**Comment by felixboehm** [comment]
Installing a plugin does a `npm install <plugin>` in the backend - how could you persist the installed plugins with a docker volume ?

**Comment by Jamesits** [comment]
I maintain a working Etherpad Docker image which configures itself (including auto-installation of plugins) using environment variables. This is optimized to deploy using docker management service. 

GitHub repo: https://github.com/Jamesits/docker-etherpad-lite
Docker Hub: https://hub.docker.com/r/jamesits/etherpad-lite/

**Comment by arogozhnikov** [comment]
@lpagliari 
seems like a good solution, but the image does not exist on docker hub:
```
$sudo docker pull leibnitius/etherpad-docker
Using default tag: latest
Error response from daemon: pull access denied for leibnitius/etherpad-docker, repository does not exist or may require 'docker login'
```

@Jamesits  good job! 
Why did you decide to keep a separate container for mysql? (what's wrong with sqlite?)

**Comment by Jamesits** [comment]
@arogozhnikov Because it is “production ready” :)
And you can configure MySQL connection use envs; you don’t really need to put MySQL in container.
