### ISSUE TITLE
Multiple variations of "console - Error: EMFILE, open / too many open" errors

### ISSUE THREAD

**Issue by bcorrero** [ether/etherpad-lite#3012]
Every couple of days our Etherpad instance is crashing due to some variation/combination of the error listed in the title, with a different minified_... or file name each time.

Any insight around how to resolve this?  

I'm assuming users open their Etherpads then leave the session open permanently.  Is there anyway to automatically close long-opened sessions?  

This is a production instance so impossible to contact every user individually, would definitely benefit from an auto-disconnect parameter or feature.

I got these errors with minify set to both true or false, I thought that would resolve the "minified_" portion of the errors but still nothing.

`[2016-06-17 09:42:21.915] [ERROR] console - Error: EMFILE, too many open files '/home/etherpad/node_modules/ep_etherpad-lite/templates/pad.html'`<br>
`[2016-06-17 09:43:34.233] [ERROR] console - Error: EMFILE, too many open files '/home/etherpad/node_modules/ep_etherpad-lite/templates/index.html'`<br>
`[2016-06-17 09:43:45.539] [ERROR] console - Error: EMFILE, open '/home/etherpad/src/static/favicon.ico'`<br>
`[2016-06-17 09:43:58.685] [ERROR] console - Error: EMFILE, open '/home/etherpad/var/minified_L2phdmFzY3JpcHRzL2xpYi9lcF9ldGhlcnBhZC1saXRlL3N0YXRpYy9qcy9hY2UyX2NvbW1vbi5qcz9jYWxsYmFjaz1yZXF1aXJlLmRlZmluZQ'`

**Comment by bcorrero** [comment]
Continuing to happen - another error log below:

[2016-07-22 13:09:49.908] [ERROR] console - Error: EMFILE, open '/home/etherpad/var/minified_L2phdmFzY3JpcHRzL2xpYi9lcF9ldGhlcnBhZC1saXRlL3N0YXRpYy9qcy9hY2UyX2NvbW1vbi5qcz9jYWxsYmFjaz1yZXF1aXJlLmRlZmluZQ'
[2016-07-22 13:09:49.908] [INFO] console - graceful shutdown...
[2016-07-22 13:09:49.942] [ERROR] console - Error: EMFILE, open '/home/etherpad/src/static/favicon.ico'
[2016-07-22 13:09:49.976] [INFO] ueberDB - Flushed 1 values
[2016-07-22 13:09:50.076] [INFO] ueberDB - Flushed 1 values
[2016-07-22 13:09:50.177] [INFO] console - db sucessfully closed.
[2016-07-22 13:27:22.635] [INFO] console - Installed plugins:
[2016-07-22 13:27:22.649] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues

Is there no fix for this?  Am I the only one having this issue?  Please advise if there's a better way to go about error resolution.

**Comment by Gared** [comment]
This is probably a configuration problem of your server, but first we need more infos:
What OS do you use?
Can you please post the results of ```lsof -i -n -P | grep node``` and ```ulimit -a```?

**Comment by bcorrero** [comment]
Thanks @Gared .  Here are my current configurations.

**OS:**
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Red Hat Enterprise Linux Server release 6.7 (Santiago)

**grep node:**
node      29580     root   11u  IPv4 6484954      0t0  TCP 127.0.0.1:43378->127.0.0.1:3306 (ESTABLISHED)
node      29580     root   12u  IPv4 6484965      0t0  TCP *:9001 (LISTEN)
node      29580     root   13u  IPv4 6643733      0t0  TCP 10.205.73.227:9001->10.210.10.28:64633 (ESTABLISHED)
node      29580     root   14u  IPv4 6487570      0t0  TCP 10.205.73.227:9001->10.120.155.116:57706 (ESTABLISHED)
node      29580     root   15u  IPv4 6485634      0t0  TCP 10.205.73.227:9001->10.210.219.71:51227 (ESTABLISHED)
node      29580     root   16u  IPv4 6522654      0t0  TCP 10.205.73.227:9001->172.28.56.74:50714 (ESTABLISHED)
node      29580     root   17u  IPv4 6525896      0t0  TCP 10.205.73.227:9001->10.250.111.233:63677 (ESTABLISHED)
node      29580     root   18u  IPv4 6486135      0t0  TCP 10.205.73.227:9001->10.120.155.244:59983 (ESTABLISHED)
node      29580     root   19u  IPv4 6484977      0t0  TCP 10.205.73.227:9001->10.120.35.92:64861 (ESTABLISHED)
node      29580     root   20u  IPv4 6530337      0t0  TCP 10.205.73.227:9001->10.250.40.136:61741 (ESTABLISHED)
node      29580     root   21u  IPv4 6548326      0t0  TCP 10.205.73.227:9001->10.250.0.79:63570 (ESTABLISHED)
node      29580     root   22u  IPv4 6488220      0t0  TCP 10.205.73.227:9001->10.250.0.79:50092 (ESTABLISHED)
node      29580     root   23u  IPv4 6484983      0t0  TCP 10.205.73.227:9001->10.222.246.112:49158 (ESTABLISHED)
node      29580     root   24u  IPv4 6484985      0t0  TCP 10.205.73.227:9001->10.120.35.92:64864 (ESTABLISHED)
node      29580     root   25u  IPv4 6497257      0t0  TCP 10.205.73.227:9001->10.120.154.53:59995 (ESTABLISHED)
node      29580     root   26u  IPv4 6485959      0t0  TCP 10.205.73.227:9001->10.210.220.105:54252 (ESTABLISHED)
node      29580     root   27u  IPv4 6489337      0t0  TCP 10.205.73.227:9001->10.210.31.107:63074 (ESTABLISHED)
node      29580     root   28u  IPv4 6485715      0t0  TCP 10.205.73.227:9001->10.210.4.179:61860 (ESTABLISHED)
node      29580     root   29u  IPv4 6501458      0t0  TCP 10.205.73.227:9001->10.120.152.78:65078 (ESTABLISHED)
node      29580     root   30u  IPv4 6492719      0t0  TCP 10.205.73.227:9001->10.210.222.40:58889 (ESTABLISHED)
node      29580     root   31u  IPv4 6639341      0t0  TCP 10.205.73.227:9001->10.250.58.57:63889 (ESTABLISHED)
node      29580     root   32u  IPv4 6485001      0t0  TCP 10.205.73.227:9001->10.120.35.92:64865 (ESTABLISHED)
node      29580     root   33u  IPv4 6494619      0t0  TCP 10.205.73.227:9001->10.120.28.160:55699 (ESTABLISHED)
node      29580     root   34u  IPv4 6552986      0t0  TCP 10.205.73.227:9001->172.28.42.1:64493 (ESTABLISHED)
node      29580     root   35u  IPv4 6485007      0t0  TCP 10.205.73.227:9001->10.114.225.128:50371 (ESTABLISHED)
node      29580     root   36u  IPv4 6494668      0t0  TCP 10.205.73.227:9001->10.210.221.237:64706 (ESTABLISHED)
node      29580     root   37u  IPv4 6488558      0t0  TCP 10.205.73.227:9001->10.210.11.211:62487 (ESTABLISHED)
node      29580     root   38u  IPv4 6500524      0t0  TCP 10.205.73.227:9001->172.28.10.190:53400 (ESTABLISHED)
node      29580     root   39u  IPv4 6496417      0t0  TCP 10.205.73.227:9001->10.210.221.237:64980 (ESTABLISHED)
node      29580     root   40u  IPv4 6497044      0t0  TCP 10.205.73.227:9001->10.222.223.103:58995 (ESTABLISHED)
node      29580     root   41u  IPv4 6547934      0t0  TCP 10.205.73.227:9001->10.250.0.79:62986 (ESTABLISHED)
node      29580     root   42u  IPv4 6487664      0t0  TCP 10.205.73.227:9001->10.120.155.116:58419 (ESTABLISHED)
node      29580     root   43u  IPv4 6487596      0t0  TCP 10.205.73.227:9001->172.28.26.117:60667 (ESTABLISHED)
node      29580     root   44u  IPv4 6486771      0t0  TCP 10.205.73.227:9001->10.120.153.188:50641 (ESTABLISHED)
node      29580     root   45u  IPv4 6485837      0t0  TCP 10.205.73.227:9001->10.120.155.76:64664 (ESTABLISHED)
node      29580     root   46u  IPv4 6565380      0t0  TCP 10.205.73.227:9001->172.28.61.3:55132 (ESTABLISHED)
node      29580     root   47u  IPv4 6490097      0t0  TCP 10.205.73.227:9001->10.120.147.149:63130 (ESTABLISHED)
node      29580     root   48u  IPv4 6498209      0t0  TCP 10.205.73.227:9001->10.210.10.55:59283 (ESTABLISHED)
node      29580     root   49u  IPv4 6485032      0t0  TCP 10.205.73.227:9001->10.210.218.154:53327 (ESTABLISHED)
node      29580     root   50u  IPv4 6554690      0t0  TCP 10.205.73.227:9001->172.28.42.1:50793 (ESTABLISHED)
node      29580     root   51u  IPv4 6568935      0t0  TCP 10.205.73.227:9001->172.28.120.119:52405 (ESTABLISHED)
node      29580     root   52u  IPv4 6620732      0t0  TCP 10.205.73.227:9001->10.250.84.146:57130 (ESTABLISHED)
node      29580     root   53u  IPv4 6496447      0t0  TCP 10.205.73.227:9001->10.217.8.38:54391 (ESTABLISHED)
node      29580     root   54u  IPv4 6487668      0t0  TCP 10.205.73.227:9001->10.120.155.116:58421 (ESTABLISHED)
node      29580     root   55u  IPv4 6490121      0t0  TCP 10.205.73.227:9001->10.120.155.247:60822 (ESTABLISHED)
node      29580     root   56u  IPv4 6493702      0t0  TCP 10.205.73.227:9001->10.120.154.234:60907 (ESTABLISHED)
node      29580     root   57u  IPv4 6485048      0t0  TCP 10.205.73.227:9001->10.210.218.126:59963 (ESTABLISHED)
node      29580     root   58u  IPv4 6497275      0t0  TCP 10.205.73.227:9001->10.120.154.53:61032 (ESTABLISHED)
node      29580     root   59u  IPv4 6485052      0t0  TCP 10.205.73.227:9001->10.120.155.82:50546 (ESTABLISHED)
node      29580     root   60u  IPv4 6486838      0t0  TCP 10.205.73.227:9001->10.120.28.160:51472 (ESTABLISHED)
node      29580     root   61u  IPv4 6488026      0t0  TCP 10.205.73.227:9001->172.28.39.66:49463 (ESTABLISHED)
node      29580     root   62u  IPv4 6493406      0t0  TCP 10.205.73.227:9001->172.28.25.148:62524 (ESTABLISHED)
node      29580     root   63u  IPv4 6490838      0t0  TCP 10.205.73.227:9001->10.120.28.160:63675 (ESTABLISHED)
node      29580     root   64u  IPv4 6494963      0t0  TCP 10.205.73.227:9001->10.210.10.236:63450 (ESTABLISHED)
node      29580     root   65u  IPv4 6488645      0t0  TCP 10.205.73.227:9001->10.222.223.103:58709 (ESTABLISHED)
node      29580     root   66u  IPv4 6485066      0t0  TCP 10.205.73.227:9001->10.222.246.43:56915 (ESTABLISHED)
node      29580     root   67u  IPv4 6489422      0t0  TCP 10.205.73.227:9001->10.210.222.34:54991 (ESTABLISHED)
node      29580     root   68u  IPv4 6497279      0t0  TCP 10.205.73.227:9001->10.120.154.53:51722 (ESTABLISHED)
node      29580     root   69u  IPv4 6495785      0t0  TCP 10.205.73.227:9001->10.210.219.19:58939 (ESTABLISHED)
node      29580     root   70u  IPv4 6491795      0t0  TCP 10.205.73.227:9001->10.120.153.188:52331 (ESTABLISHED)
node      29580     root   71u  IPv4 6485076      0t0  TCP 10.205.73.227:9001->10.210.218.154:53329 (ESTABLISHED)
node      29580     root   72u  IPv4 6485078      0t0  TCP 10.205.73.227:9001->10.210.218.154:53330 (ESTABLISHED)
node      29580     root   73u  IPv4 6560347      0t0  TCP 10.205.73.227:9001->10.250.45.73:56668 (ESTABLISHED)
node      29580     root   74u  IPv4 6493420      0t0  TCP 10.205.73.227:9001->172.28.25.148:62527 (ESTABLISHED)
node      29580     root   75u  IPv4 6485084      0t0  TCP 10.205.73.227:9001->10.210.10.55:56842 (ESTABLISHED)
node      29580     root   76u  IPv4 6497303      0t0  TCP 10.205.73.227:9001->10.221.154.191:58082 (ESTABLISHED)
node      29580     root   77u  IPv4 6489701      0t0  TCP 10.205.73.227:9001->10.120.155.247:60752 (ESTABLISHED)
node      29580     root   78u  IPv4 6485090      0t0  TCP 10.205.73.227:9001->10.222.246.121:53211 (ESTABLISHED)
node      29580     root   79u  IPv4 6487711      0t0  TCP 10.205.73.227:9001->10.250.7.51:64464 (ESTABLISHED)
node      29580     root   80u  IPv4 6490226      0t0  TCP 10.205.73.227:9001->10.210.10.129:62527 (ESTABLISHED)
node      29580     root   81u  IPv4 6494269      0t0  TCP 10.205.73.227:9001->10.210.222.150:58958 (ESTABLISHED)
node      29580     root   82u  IPv4 6499878      0t0  TCP 10.205.73.227:9001->10.210.10.28:54024 (ESTABLISHED)
node      29580     root   83u  IPv4 6665887      0t0  TCP 10.205.73.227:9001->172.28.4.131:49518 (ESTABLISHED)
node      29580     root   84u  IPv4 6657370      0t0  TCP 10.205.73.227:9001->172.28.125.60:53385 (ESTABLISHED)
node      29580     root   85u  IPv4 6490300      0t0  TCP 10.205.73.227:9001->10.210.216.208:56930 (ESTABLISHED)
node      29580     root   86u  IPv4 6497285      0t0  TCP 10.205.73.227:9001->10.120.154.53:51729 (ESTABLISHED)
node      29580     root   87u  IPv4 6490932      0t0  TCP 10.205.73.227:9001->10.219.26.3:55657 (ESTABLISHED)
node      29580     root   88u  IPv4 6491703      0t0  TCP 10.205.73.227:9001->10.120.147.149:65489 (ESTABLISHED)
node      29580     root   89u  IPv4 6492414      0t0  TCP 10.205.73.227:9001->10.210.221.227:59778 (ESTABLISHED)
node      29580     root   90u  IPv4 6598651      0t0  TCP 10.205.73.227:9001->172.28.80.246:57183 (ESTABLISHED)
node      29580     root   91u  IPv4 6490659      0t0  TCP 10.205.73.227:9001->10.210.222.34:55211 (ESTABLISHED)
node      29580     root   92u  IPv4 6554728      0t0  TCP 10.205.73.227:9001->172.28.42.1:50849 (ESTABLISHED)
node      29580     root   93u  IPv4 6641417      0t0  TCP 10.205.73.227:9001->10.250.9.141:55040 (ESTABLISHED)
node      29580     root   94u  IPv4 6497804      0t0  TCP 10.205.73.227:9001->10.210.223.108:50314 (ESTABLISHED)
node      29580     root   95u  IPv4 6490673      0t0  TCP 10.205.73.227:9001->10.120.155.244:60795 (ESTABLISHED)
node      29580     root   96u  IPv4 6495091      0t0  TCP 10.205.73.227:9001->10.250.6.210:49574 (ESTABLISHED)
node      29580     root   97u  IPv4 6492854      0t0  TCP 10.205.73.227:9001->10.210.221.227:60194 (ESTABLISHED)
node      29580     root   98u  IPv4 6554707      0t0  TCP 10.205.73.227:9001->172.28.42.1:50833 (ESTABLISHED)
node      29580     root   99u  IPv4 6659105      0t0  TCP 10.205.73.227:9001->172.28.72.83:51748 (ESTABLISHED)
node      29580     root  100u  IPv4 6661771      0t0  TCP 10.205.73.227:9001->10.250.125.189:54470 (ESTABLISHED)
node      29580     root  101u  IPv4 6661660      0t0  TCP 10.205.73.227:9001->10.250.4.79:54918 (ESTABLISHED)
node      29580     root  102u  IPv4 6497448      0t0  TCP 10.205.73.227:9001->10.210.223.197:49682 (ESTABLISHED)
node      29580     root  103u  IPv4 6661815      0t0  TCP 10.205.73.227:9001->10.250.118.150:55149 (ESTABLISHED)
node      29580     root  104u  IPv4 6665889      0t0  TCP 10.205.73.227:9001->172.28.4.131:49522 (ESTABLISHED)
node      29580     root  105u  IPv4 6647111      0t0  TCP 10.205.73.227:9001->172.28.25.148:58543 (ESTABLISHED)
node      29580     root  106u  IPv4 6489755      0t0  TCP 10.205.73.227:9001->10.219.18.223:57119 (ESTABLISHED)
node      29580     root  107u  IPv4 6665891      0t0  TCP 10.205.73.227:9001->172.28.4.131:49520 (ESTABLISHED)
node      29580     root  108u  IPv4 6665893      0t0  TCP 10.205.73.227:9001->172.28.4.131:49521 (ESTABLISHED)
node      29580     root  109u  IPv4 6660696      0t0  TCP 10.205.73.227:9001->172.28.29.119:54459 (ESTABLISHED)
node      29580     root  110u  IPv4 6485152      0t0  TCP 10.205.73.227:9001->10.210.10.200:55060 (ESTABLISHED)
node      29580     root  111u  IPv4 6665894      0t0  TCP 10.205.73.227:9001->172.28.4.131:49519 (ESTABLISHED)
node      29580     root  112u  IPv4 6665896      0t0  TCP 10.205.73.227:9001->172.28.4.131:49523 (ESTABLISHED)
node      29580     root  114u  IPv4 6664306      0t0  TCP 10.205.73.227:9001->10.250.4.79:55955 (ESTABLISHED)
node      29580     root  117u  IPv4 6485166      0t0  TCP 10.205.73.227:9001->10.210.221.3:62486 (ESTABLISHED)
node      29580     root  119u  IPv4 6485170      0t0  TCP 10.205.73.227:9001->10.119.221.162:65194 (ESTABLISHED)
node      29580     root  123u  IPv4 6485178      0t0  TCP 10.205.73.227:9001->10.120.153.188:49505 (ESTABLISHED)
node      29580     root  124u  IPv4 6485482      0t0  TCP 10.205.73.227:9001->10.222.247.119:61184 (ESTABLISHED)
node      29580     root  125u  IPv4 6485182      0t0  TCP 10.205.73.227:9001->10.114.225.128:50373 (ESTABLISHED)
node      29580     root  127u  IPv4 6485186      0t0  TCP 10.205.73.227:9001->10.210.222.34:54514 (ESTABLISHED)
node      29580     root  130u  IPv4 6485192      0t0  TCP 10.205.73.227:9001->10.210.10.55:56844 (ESTABLISHED)
node      29580     root  133u  IPv4 6485198      0t0  TCP 10.205.73.227:9001->10.120.147.149:52472 (ESTABLISHED)
node      29580     root  134u  IPv4 6485200      0t0  TCP 10.205.73.227:9001->10.250.127.103:61087 (ESTABLISHED)
node      29580     root  137u  IPv4 6485206      0t0  TCP 10.205.73.227:9001->172.28.89.182:52188 (ESTABLISHED)
node      29580     root  154u  IPv4 6485238      0t0  TCP 10.205.73.227:9001->10.210.10.236:62180 (ESTABLISHED)
node      29580     root  158u  IPv4 6485579      0t0  TCP 10.205.73.227:9001->10.210.216.214:52253 (ESTABLISHED)
node      29580     root  164u  IPv4 6485257      0t0  TCP 10.205.73.227:9001->10.210.218.170:56575 (ESTABLISHED)
node      29580     root  168u  IPv4 6485265      0t0  TCP 10.205.73.227:9001->10.210.11.74:58338 (ESTABLISHED)
node      29580     root  172u  IPv4 6485273      0t0  TCP 10.205.73.227:9001->10.210.221.89:63377 (ESTABLISHED)
node      29580     root  180u  IPv4 6485289      0t0  TCP 10.205.73.227:9001->10.210.221.89:63381 (ESTABLISHED)
node      29580     root  188u  IPv4 6485306      0t0  TCP 10.205.73.227:9001->10.210.10.236:62182 (ESTABLISHED)
node      29580     root  190u  IPv4 6485310      0t0  TCP 10.205.73.227:9001->10.210.10.236:62183 (ESTABLISHED)
node      29580     root  194u  IPv4 6485318      0t0  TCP 10.205.73.227:9001->10.120.153.188:49506 (ESTABLISHED)
node      29580     root  196u  IPv4 6485322      0t0  TCP 10.205.73.227:9001->10.210.222.150:57093 (ESTABLISHED)
node      29580     root  200u  IPv4 6485330      0t0  TCP 10.205.73.227:9001->10.210.218.170:56577 (ESTABLISHED)
node      29580     root  207u  IPv4 6485344      0t0  TCP 10.205.73.227:9001->10.210.221.227:59132 (ESTABLISHED)

**ulimit -a:**
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31355
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31355
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by Gared** [comment]
Have you executed these commands with the user which is running etherpad? This looks fine so far. You may increase the "open files" value, but this shouldn't solve your problem.
What is the peak of users that are connected at the same time to your etherpad?

**Comment by JohnMcLear** [comment]
I think this got resolved in express

Either way you need express to be in production mode

```export NODE_ENV=production```
