### ISSUE TITLE
What about using Greenkeeper?

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#3013]
It can help you to keep your npm dependencies updated.

See https://greenkeeper.io/ for more details.

@greenkeeperio

**Comment by ocdtrekkie** [comment]
Is this solving a problem this software is currently burdened by? This seems like... an advertisement more than an "issue". Maybe because you're spamming it on a bunch of the repositories I watch.

**Comment by rugk** [comment]
Now big crosslinking...
See https://github.com/JohnMcLear/draw/issues/246#issuecomment-229452503

**Comment by Gared** [comment]
I don't see benefits in using this Software. We don't have enough tests to check if our software is still running with the latest version of an updated library and we reference to a specific version. So I think it's simpler to update the dependencies from time to time.

**Comment by rugk** [comment]
> We don't have enough tests to check if our software is still running with the latest version of an updated library

Yeah, that's a requirement for sure. But it is also not a bad idea to add more test. :wink: 
But you're of course right if there are only few tests, this service won't help you.

**Comment by rugk** [comment]
As an alternative maybe consider https://david-dm.org/. This shows you a warning when your outdated dependencies have known security vulnerabilities.
