### ISSUE TITLE
Custom Export File Name

### ISSUE THREAD

**Issue by DanielBickley** [ether/etherpad-lite#3014]
Hello,

I'm trying to dig in and find a way to customize a filename on export. Currently, my pad names use a very cryptic hash approach that I've implemented for other reasons. However, on export, this looks very ugly for the typical user.

I can see how src/static/js/pad_impexp.js seems to create a frame on the fly, and how that same file updates the id="exportColumn" link hrefs in pad.html. Now I'm trying to figure out how to assign a more proper file name to the download. I'm assuming the downloaded file takes on the name of the assigned path by default. 

Would somebody help me understand the export process, so I might be able to work in a custom file name plugin, or would you have an idea for how that could be easily overriden on a temp basis at a bare minimum?

Thanks!

**Comment by lpagliari** [comment]
[This hook](http://etherpad.org/doc/v1.6.0/#index_exportfilename) might help.

**Comment by DanielBickley** [comment]
Bingo! Thank you much.
