### ISSUE TITLE
Using Etherpad Lite ver 1.6 with API version 1.2.1 - appendChatmessage method does not work

### ISSUE THREAD

**Issue by snakeye5** [ether/etherpad-lite#3015]
I keep getting error when I use the http API. The message is
{
  "code": 3,
  "message": "no such function",
  "data": null
}

Using Java library I again get that the method does not exist!!

Any help will be greatly appreciated as I am really stuck

**Comment by lpagliari** [comment]
[The doc](http://etherpad.org/doc/v1.6.0/#index_appendchatmessage_padid_text_authorid_time) says it was introduced on API v 1.2.12

**Comment by snakeye5** [comment]
Thanks I have updated to latest API version which is 1.2.13 and still same error!! Any other ideas?

**Comment by Gared** [comment]
Please post the link that you use to call the API. Do you use version 1.2.12 or higher in your link?

**Comment by LOB-PatrickT** [comment]
here's the link: [http://s1.coranetsolutions.com:9001/api/](url)
It has a version of **{"currentVersion":"1.2.13"}**

**Comment by lpagliari** [comment]
@LOB-PatrickT I believe Gared was asking about the full link (without APIKEY, of course). If you're calling [http://s1.coranetsolutions.com:9001/api/**1**/appendChatMessage...](), you'll get that error message; if you call [http://s1.coranetsolutions.com:9001/api/**1.2.13**/appendChatMessage...](), it should be fine.

**Comment by lpagliari** [comment]
BTW, you can run the backend tests (`src/node_modules/mocha/bin/mocha --timeout 5000 --reporter nyan tests/backend/specs/api/chat.js`) to check if the chat API is working fine, and if so just add some `console.log` to get the values you need (ex: the URL that is being called) to see if you're calling the API with the correct values -- that was the way I figured out you might be using the wrong URL.

**Comment by LOB-PatrickT** [comment]
@lpagliari This is the full link I used previously:
[http://s1.coranetsolutions.com:9001/api/1.2.13/getText?apikey=secret&padID=test_test](url)

I tried your solution to change **1** to **1.2.13** and it now works.

**Comment by lpagliari** [comment]
Any pending question here, or can we close this issue?

**Comment by LOB-PatrickT** [comment]
yes we can close the issue now @lpagliari
