### ISSUE TITLE
import delete history

### ISSUE THREAD

**Issue by PhilLAL** [ether/etherpad-lite#3018]
I recently made some tests, and I realized that import seems to delete previous history from the pad.
It seems to be more a bug than a functionnality. Is there any way to avoid this?
As a result, it seems impossible to go back to the pad before the import when the import result is wrong.

**Comment by PhilLAL** [comment]
Any comment ? Am I wrong ?

**Comment by JohnMcLear** [comment]
Yea you are wrong.  https://beta.etherpad.org/p/5/timeslider#24  -- History is maintained on upload..

**Comment by PhilLAL** [comment]
Ok, thank you for your answer.
I probably made a mistake back then, but when I try again today, it works perfectly!
