### ISSUE TITLE
search & replace

### ISSUE THREAD

**Issue by PhilLAL** [ether/etherpad-lite#3023]
Hi, since there are some bugs with import #3019 and because this functionnality is always useful, I think it would be a good thing to allow search and replace for a string or even a regexp.
Do you think it is possible?

**Comment by Gared** [comment]
Yes, this should be possible to build as a plugin

**Comment by shuyanglin** [comment]
hi, is there anyone working on this feature? can't wait  to use it :p

**Comment by JohnMcLear** [comment]
I think this is available on codepad - bump https://github.com/LaKing
