### ISSUE TITLE
Etherpad Cloudron app

### ISSUE THREAD

**Issue by gramakri** [ether/etherpad-lite#3024]
Thanks for Etherpad! We made a Cloudron app for Etherpad (The Cloudron is a smartserver on which you can install apps and manage users).

We have been following etherpad for quite a while now and keep it updated. The app source is at https://git.cloudron.io/cloudron/etherpad-lite-app We also have selenium based integration tests under https://git.cloudron.io/cloudron/etherpad-lite-app/tree/master/test (this way we know if something might break when the user updates the app on the Cloudron).

Do you think it's possible to get us listed in the README.md or the etherpad.org site as an installation option? I can submit a PR if you can suggest how I should go about this.

**Comment by gramakri** [comment]
If you want to try a demo, https://my-demo.cloudron.me (username: cloudron password: cloudron).

**Comment by gramakri** [comment]
Bump :-) Did any contributor/maintainer have a comment on this?

**Comment by lpagliari** [comment]
@gramakri I see that you've added Cloudron on [wiki](https://github.com/ether/etherpad-lite/wiki/Sites-that-run-Etherpad-Lite), which seems to be the right thing to do. @JohnMcLear any comment about it, or can we close this issue?
