### ISSUE TITLE
How to determine when text is set  completely 

### ISSUE THREAD

**Issue by xsbear** [ether/etherpad-lite#3025]
I want to know when text is set completely at first time, I found "aceSelectionChanged" invoked  3 times when loading. At first time,  cursor at line 0, column 0, second,   cursor at last line, last column,  third, cursor at line 0, column 0 again. So, how to determine  when text is set  completely when cursor at  line 0, column 0 ?

**Comment by lpagliari** [comment]
Try `aceEditEvent` instead of `aceSelectionChanged `. `'setWraps'` seems to be the last event before user can start typing.

**Comment by xsbear** [comment]
Got it, thanks!
