### ISSUE TITLE
Update minimatch

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#3028]
Minimatch seems to be vulnerable:

> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> 
> npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by Gared** [comment]
│ ├─┬ mocha@2.4.5
│ │ ├─┬ glob@3.2.3
│ │ │ └─┬ minimatch@0.2.14

So mocha has to update the glob dependency first

**Comment by rugk** [comment]
Okay, [reported](https://github.com/mochajs/mocha/issues/2404).

**Comment by rugk** [comment]
As from the error message somewhere aloes "minimatch@1.0.0" is used. DO you know where?

**Comment by pmontrasio** [comment]
I also get this

```
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```
There are many versions of minimatch used by all the modules required by etherpad but ```minimatch@1.0.0``` is not among them.

```
$ npm ls minimatch
/home/me/etherpad/etherpad-lite
└─┬ ep_etherpad-lite@1.6.1 -> /home/me/etherpad/etherpad-lite/src
  ├─┬ mocha@2.4.5
  │ └─┬ glob@3.2.3
  │   └── minimatch@0.2.14 
  └─┬ npm@4.0.2
    ├─┬ fstream-npm@1.2.0
    │ └─┬ fstream-ignore@1.0.5
    │   └── minimatch@3.0.3 
    ├─┬ glob@7.1.1
    │ └── minimatch@3.0.3 
    ├─┬ init-package-json@1.9.4
    │ └─┬ glob@6.0.4
    │   └── minimatch@3.0.3 
    ├─┬ node-gyp@3.4.0
    │ └── minimatch@3.0.3 
    └─┬ read-package-json@2.0.4
      └─┬ glob@6.0.4
        └── minimatch@3.0.3 
```

Digging into the output of ```npm install``` I got it

```
└─┬ wd@0.3.11 
  ├─┬ archiver@0.12.0 
  │ ├── buffer-crc32@0.2.13 
  │ ├─┬ glob@4.0.6 
  │ │ ├─┬ graceful-fs@3.0.11 
  │ │ │ └── natives@1.1.0 
  │ │ ├── minimatch@1.0.0 
```

**Comment by rugk** [comment]
And BTW the current version of Mocha is 3.2.0 and it has been said there an up-to-date version of minimatch is included.

**Comment by JohnMcLear** [comment]
Done
