### ISSUE TITLE
ace_inner ios safari height bug

### ISSUE THREAD

**Issue by AlexKuzyaev** [ether/etherpad-lite#3029]
Hello everyone, I have this bug on iOS.
When there are a lot of letters in etherpad, on the next etherpad start height calculating seems incorrect - too big. This happens only on Safari on iOS, it's ok on Android.

You can see how it looks [here](https://youtu.be/n6nXOe0L1Ao).

**Comment by JohnMcLear** [comment]
I assume Safari team fixed this by now..
