### ISSUE TITLE
arguments and variables

### ISSUE THREAD

**Issue by bobloblian** [ether/etherpad-lite#3034]
Hi,
I have been tweaking etherpad on my system, seeing what I can make it do.  I found one article that said I could export TMPDIR to change the /tmp directory, and I found another article that said I could pass a -s to run.sh (server.js) to define settings files in order to run multiple instances.  
This got me to thinking there might be more things like this that let me do more things, but I cannot seem to find where such things might be listed.  In particular I am interested in things that let me run multiple instances from a single source while keeping the generated files from each instance separated.  
Any chance someone can point me in the right direction, maybe there is a file in the code I am missing, or a section of documentation I have overlooked?

**Comment by JohnMcLear** [comment]
See settings.json.template :)
