### ISSUE TITLE
setHTML Table Tage

### ISSUE THREAD

**Issue by mjdeslongchamps** [ether/etherpad-lite#3036]
Hello,

I am trying to insert the following html using setHTML:

`<!DOCTYPE html><html><head></head><body><table><thead><tr><th colspan='2'></th><th colspan='1'>Criteria</th><th></th></tr><tr><th>Solution #</th><th>Solution Ideas</th><th>1</th><th>Total</th></tr></thead><tbody><tr><td></td><td></td><td></td><td></td></td></tr></tbody></table></body></html>`

I get no errors but when looking at the pad, there is no table. Any help would be appreciated.

**Comment by lpagliari** [comment]
Take a look on this plugin, it might provide what you need: https://github.com/quenenni/ep_tables2

**Comment by mjdeslongchamps** [comment]
The plugin did not address my issue. Are there any limitations when using the setHTML and inserting html code to a pad. I am able to see content, but the table tags are being stripped.

**Comment by lpagliari** [comment]
@mjdeslongchamps yes, Etherpad removes tags it does not understand and keeps only the text read, so it is probably not ready to handle table-related tags. I was supposing ep_tables2 would handle those tags for you.

**Comment by lpagliari** [comment]
To keep the discussion in a single place, I'll copy the text of #3038 here and close it there:

My previous issue was closed.  It was here: https://github.com/ether/etherpad-lite/issues/3036

I applied the plugin but I still cannot create a table via setHTML. Here is the code I am using.

 ```
$url = $EtherPadURL."api/1/setHTML";
                // Create map with request parameters
                $params = array ('apikey' => $EtherPadAPI, 'padID' => $padId,'html'=>$SheetGrid);
                $query = http_build_query ($params);
                $contextData = array (
                    'method' => 'POST',
                    'header' => "Connection: close\r\n".
                        "Content-Length: ".strlen($query)."\r\n",
                    'content'=> $query );
                $context = stream_context_create (array ( 'http' => $contextData ));
                $result =  file_get_contents (
                    $url,  // page url
                    false,
                    $context);
```

When viewing the pad you can see all the text that would have been in the table. But the table structure has been stripped out.

Here is the link to the pad.

http://104.238.110.63:9001/p/356a192b7913b04c54574d18c28d46e6395428ab

So you can see what is happening.

**Comment by lpagliari** [comment]
@mjdeslongchamps BTW: when I check your pad, I see errors on the console:

```
Failed to load 'ep_tables/static/js/datatables.js:aceKeyEvent' for 'ep_tables/tables/client_hooks/aceKeyEvent': Error: The module at "ep_tables/static/js/datatables.js" does not exist.window.console.error @ VM85:27
Failed to load 'ep_tables/static/js/datatables.js:aceStartLineAndCharForPoint' for 'ep_tables/tables/client_hooks/aceStartLineAndCharForPoint': Error: The module at "ep_tables/static/js/datatables.js" does not exist.window.console.error @ VM85:27
Failed to load 'ep_tables/static/js/datatables.js:aceEndLineAndCharForPoint' for 'ep_tables/tables/client_hooks/aceEndLineAndCharForPoint': Error: The module at "ep_tables/static/js/datatables.js" does not exist.window.console.error @ VM85:27
Failed to load 'ep_tables/static/js/datatables.js:aceAttribsToClasses' for 'ep_tables/tables/client_hooks/aceAttribsToClasses': Error: The module at "ep_tables/static/js/datatables.js" does not exist.
```

**Comment by ritesshguptaa** [comment]
Hi  @lpagliari / @mjdeslongchamps , 
I am facing the same issue, Did you  found any plugin or solution for the same ? 
Please let me know
