### ISSUE TITLE
setHTML Table Tag

### ISSUE THREAD

**Issue by mjdeslongchamps** [ether/etherpad-lite#3038]
My previous issue was closed.  It was here: https://github.com/ether/etherpad-lite/issues/3036

I applied the plugin but I still cannot create a table via setHTML. Here is the code I am using.

 ```
$url = $EtherPadURL."api/1/setHTML";
                // Create map with request parameters
                $params = array ('apikey' => $EtherPadAPI, 'padID' => $padId,'html'=>$SheetGrid);
                $query = http_build_query ($params);
                $contextData = array (
                    'method' => 'POST',
                    'header' => "Connection: close\r\n".
                        "Content-Length: ".strlen($query)."\r\n",
                    'content'=> $query );
                $context = stream_context_create (array ( 'http' => $contextData ));
                $result =  file_get_contents (
                    $url,  // page url
                    false,
                    $context);
```

When viewing the pad you can see all the text that would have been in the table. But the table structure has been stripped out.

Here is the link to the pad.

http://104.238.110.63:9001/p/356a192b7913b04c54574d18c28d46e6395428ab

So you can see what is happening.

**Comment by ritesshguptaa** [comment]
Hi  @lpagliari , @mjdeslongchamps 
I am facing the same issue, Did you  found any plugin or solution for the same ? 
Please let me know
