### ISSUE TITLE
Problem when opening multiple Etherpads from a Server in Firefox

### ISSUE THREAD

**Issue by dan-elevate** [ether/etherpad-lite#3039]
Hello!

As soon as I open more than 4 tabs with Etherpad-Lite pads in Firefox I am getting an error. After restarting Firefox, I can again load a maximum of 4 pads - not more.
In Chromium there doesn't seem to be this problem..

This is the error message

> An error occured
> The error was reported with the following id: 'RxQ7JBIK6MKMfEFHQXtB'
> 
> Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
> 'ErrorId: RxQ7JBIK6MKMfEFHQXtB
> TypeError: pad.collabClient is null in https://xxxx.com/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 253'

I am running the latest version of Etherpad-Lite on my server - what can I do to fix this nd have 10 pads (at least) open in my Firefox?

thx for your amazing work!

**Comment by JohnMcLear** [comment]
Works fine for me on really crappy Internet connection too..
