### ISSUE TITLE
Use referrer policy

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#3043]
See
* https://w3c.github.io/webappsec-referrer-policy/
* http://caniuse.com/#feat=referrer-policy

You can use it in HTML (`<meta name="referrer" content="no-referrer">`) or as [a HTTP header](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-header)

**Comment by lpagliari** [comment]
@rugk can you submit a PR with a fix for this issue, please? This is an open source project, which means you can contribute with some code too. That would help us much more than only opening the issue. Thanks!!
