### ISSUE TITLE
Running on Dreamhost VPS

### ISSUE THREAD

**Issue by phillycodehound** [ether/etherpad-lite#3046]
Hi,

I'm new to Node.js. I have everything installed at http://encryptr.xyz/ep, but when I go there, I just get a directory tree not the app. How do I get it setup?

**Comment by DanielBickley** [comment]
Did you just dump into a directory? You'll need to follow the install instructions at https://github.com/ether/etherpad-lite#installation for your particular environment.

To get up and running, you won't need to be too concerned with "node" per se, but just follow the instructions and it should get you going. The service will most likely run on a diff port than your web server (i.e. :9001 vs :80), and then you'll either need to proxy in a pad, or use an iframe. There are instructions for that as well.

Hope that helps.
