### ISSUE TITLE
TypeError: pad.collabClient is null

### ISSUE THREAD

**Issue by kuldeepdhaka** [ether/etherpad-lite#3047]
```
[2016-08-27 02:11:35.216] [WARN] client - TypeError: pad.collabClient is null -- { errorId: 'msd9a2Z0tYni3mUDZ9LP',
  msg: 'TypeError: pad.collabClient is null',
  url: 'https://foo.bar:9001/p/YMZ332qHz6',
  linenumber: 266,
  userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0' }

```

**Comment by kuldeepdhaka** [comment]
maybe this is also related to above:
```
[2016-08-27 02:12:18.519] [WARN] message - Authentication try failed:{"component":"pad","type":"CLIENT_READY","padId":"bla-bla","sessionID":"null","password":null,"token":"t.0WWVLKdkFOOyJcrBAR4e","protocolVersion":2}
``

**Comment by kuldeepdhaka** [comment]
```
[2016-08-27 02:06:44.102] [INFO] console - Your Etherpad version is 1.6.0 (8ad9d4f)
```

**Comment by kuldeepdhaka** [comment]
I can locally reporduce the problem with:

diff settings.json settings.json.template
```
41c41
<   "dbType" : "sqlite",
---
>   "dbType" : "dirty",
44c44
<                    "filename" : "var/data.db"
---
>                    "filename" : "var/dirty.db"
80c80
<   "requireSession" : true,
---
>   "requireSession" : false,
113c113
<   "requireAuthentication" : true,
---
>   "requireAuthentication" : false,
126c126
<   
---
>   /*
136a137
>   */
169c170
<   "loglevel": "DEBUG",
---
>   "loglevel": "INFO",

```

**Comment by kuldeepdhaka** [comment]
tried in two browser: (same problem)
- Firefox 48.0
- Chromium Version 52.0.2743.116 (64-bit)

**Comment by fralix** [comment]
I got this very same problem. It happens sometimes - I tried installing and removing plugins and the problem persisted.

**Comment by Mte90** [comment]
Sometimes I have a crash on https://public.pad.fsfe.org/p/wproma-tday-2016, like now on chrome and firefox i cannot access to the content

**Comment by fralix** [comment]
Yeah this is the problem we said. I would call this "important" as it is not fixed yet AFAIK

**Comment by Choco-Bo** [comment]
So there's nothing to do about it ? Just keep reloading the page till it works ? :(

**Comment by fralix** [comment]
I think this problem is important is it makes parts of etherpad not useable.

**Comment by Choco-Bo** [comment]
@fralix Think so too as people are going to complain when having this error :/ and may not be as patient as me when reloading 10 times there page for it to work
