### ISSUE TITLE
socket.io client connection options have been depcreated

### ISSUE THREAD

**Issue by jokecamp** [ether/etherpad-lite#3049]
The client connection settings `max reconnection attempts` and `max reconnection attempts` are no longer used in the socket.io version 1.3.7 that ep uses.

The current code in `etherpad-lite/src/static/js/pad.js`

```
  socket = pad.socket = io.connect(url, {
    // Allow deployers to host Etherpad on a non-root path
    'path': exports.baseURL + "socket.io",
    'resource': resource,
    'max reconnection attempts': 3,
    'sync disconnect on unload' : false
  });
```

Version 1.37 and above use the following settings for client connect:
- **reconnection** - whether to reconnect automatically (true)
- **reconnectionDelay** - how long to wait before attempting a new
  reconnection (1000)
- **reconnectionDelayMax** - maximum amount of time to wait between reconnections (5000). Each attempt increases the reconnection by the amount specified by reconnectionDelay.
- **timeout** - connection timeout before a connect_error and connect_timeout events are emitted (20000)

See http://socket.io/docs/client-api/
See http://stackoverflow.com/a/26331082/215502

**Comment by jdittrich** [comment]
Thanks, thats good to know!

**Comment by Gared** [comment]
@jokecamp Thanks for this info. I provided a PR with the appropriate changes.
