### ISSUE TITLE
Invalid export path crashes etherpad

### ISSUE THREAD

**Issue by jsimpsoncd** [ether/etherpad-lite#3050]
Client: Chrome, various versions.
Host: Linux Mint 18, x64, based on Ubuntu 16.04 LTS npm 3.5.2 and nodejs 4.2.6
**steps to reproduce**
Start etherpad (I started via debugRun.sh). visit an invalid export path, example:
http://localhost:9001/p/path/pad/export/txt
**what you expected to happen**
An error, or a failed export.
**what actually happened**
etherpad crashed

**Comment by jdittrich** [comment]
I just tried it with the demo and got: 

> Error: remote exception: remote exception: remote exception: remote exception: remote exception: remote exception: expected headersComplete; HTTP response from sandboxed app had incomplete headers.
    at Error (native)
C++ location:(remote):??
type: failed

Have not tried it locally yet.

**Comment by Gared** [comment]
@jdittrich Thx for reporting this bug. If you have time please test my PR

**Comment by jdittrich** [comment]
@Gared I don't get a crash and I can continue to write. Minor problem

**Comment by Gared** [comment]
@jdittrich I know, but this fixes the crash. If you think we should fix this behaviour please reopen this issue

**Comment by jdittrich** [comment]
@Gared: I think teh reload indication is a non-harmful edgecase, so I'd leave this issue closed.
