### ISSUE TITLE
allow print/hide authors colors

### ISSUE THREAD

**Issue by FilLupin** [ether/etherpad-lite#3054]
I didn't find an issue for this even if it seems to me I already discuss this matter before so I opened a new ticket.
A lot of users make mistake of erasing colors (unvonluntary shortcut, or erasing thinking they can go back) and want to get back. Actually, there seems to be no way to get colors back once erased.
1. A simple solution would be to forbid erasing colors for all, but some users may want to erase it knowing what they want.
2. A more subtile solution would be to make appear a clear warning before validating the color erasing.
3. A good solution would be to keep the author colors into metadata, and make the button register a boolean value. The colors would appear only when the button (hide colors) is not clicked (boolean false).

**Comment by JohnMcLear** [comment]
All 3 of these options exist afaik..  

1. Defo does, just remove button in settings.json
2. Defo does, but only on whole document (and not if you Control A)
3. Afaik it does and can be restored using the API.
