### ISSUE TITLE
safeRun.sh sends a mail with the content as attachment

### ISSUE THREAD

**Issue by StruBE-KAUST** [ether/etherpad-lite#3056]
When a color is present in the log file (for instance the red color when an error occurred), the mail sent by safeRun.sh does not respect the standard format of ASCII mails.
Therefore, in most of mail client, the mail has an empty body, and a binary file in attachment that we can read with cat or another reading tool.

More exactly, this behavior is caused by the `[31m` or `[39m` sequence, or any other color code.

While the mail is still sent, this way of receiving an email is not really lovely. I propose either to remove the color codes of the log file when sending its content, either to change the color code to an HTML tag.

**Comment by StruBE-KAUST** [comment]
I propose this patch to remove the colors :

    diff --git a/bin/safeRun.sh b/bin/safeRun.sh
    index 519a0b6..6a4854a 100755
    --- a/bin/safeRun.sh
    +++ b/bin/safeRun.sh
    @@ -55,7 +55,7 @@ do
         TIME_SINCE_LAST_SEND=$(($TIME_NOW - $LAST_EMAIL_SEND))
     
         if [ $TIME_SINCE_LAST_SEND -gt $TIME_BETWEEN_EMAILS ]; then
    -      printf "Server was restarted at: $(date)\nThe last 50 lines of the log before the error happens:\n $(tail -n 50 ${LOG})" | mail -s "Pad Server was restarted" $EMAIL_ADDRESS
    +      printf "Server was restarted at: $(date)\nThe last 50 lines of the log before the error happens:\n $(tail -n 50 ${LOG} | sed 's,\x1B\[[0-9;]*[a-zA-Z],,g')" | mail -s "Pad Server was restarted" $EMAIL_ADDRESS
       
           LAST_EMAIL_SEND=$TIME_NOW
         fi

**Comment by StruBE-KAUST** [comment]
Do you prefer a pull request instead of the path ?

**Comment by lpagliari** [comment]
Yes, that would be easier, thanks!
