### ISSUE TITLE
Instructions to use postgresql

### ISSUE THREAD

**Issue by StruBE-KAUST** [ether/etherpad-lite#3057]
To use postgresql with Etherpad, the package node-pg should be installed. This instruction should be written somewhere.

**Comment by lpagliari** [comment]
@StruBE-KAUST can you help us on that, please? There are some pages on wiki to support Etherpad configuration (ex: https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL), but none for postgresql, AFAICT

**Comment by dunatotatos** [comment]
Done.
See [here](https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-PostgreSQL).

**Comment by lpagliari** [comment]
AWESOME, @dunatotatos !! Thanks a lot!
