### ISSUE TITLE
Pad fails to load with error ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by darcykenworthy** [ether/etherpad-lite#3060]
My installation recently went from "functioning" to "non-functioning" for reasons that remain unclear. I have updated some things since then, but nothing major I'm aware of. The Etherpad server starts fine, and everything seems normal in the logs. Going to the root of the Etherpad location also works. However, attempting to access any pad gives a misformatted screen with an error message: """An error occured while loading the pad

ReferenceError: Can't find variable: require in https://darcykenworthy.com/etherpad/p/Temp (line 547)"""
The malfunctioning page can be found at the link above.

This is occurring on an Ubuntu 16.04.1 machine, with an nginx web server acting as a reverse proxy in front of it. Node.js version is 4.2.6, npm version 3.5.2. I have not installed any plugins.

Log file with debug enabled looks like this:
`Sep 21 05:57:22 smtp.darcykenworthy.com nodejs[8289]: <dt>createServer</dt><dd>ep_etherpad-lite/node/hooks/express:createServer from ep_etherpad-lite/express</dd>
Sep 21 05:57:22 smtp.darcykenworthy.com nodejs[8289]: <dt>restartServer</dt><dd>ep_etherpad-lite/node/hooks/express:restartServer from ep_etherpad-lite/express</dd></dl>
Sep 21 05:57:22 smtp.darcykenworthy.com nodejs[8289]: [2016-09-21 05:57:22.160] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
Sep 21 05:57:22 smtp.darcykenworthy.com nodejs[8289]: [2016-09-21 05:57:22.163] [INFO] console - Your Etherpad version is 1.6.0 (7ecf240)
Sep 21 05:57:24 smtp.darcykenworthy.com nodejs[8289]: [2016-09-21 05:57:24.220] [INFO] console - You can access your Etherpad instance at http://127.0.0.1:9001/
Sep 21 05:57:24 smtp.darcykenworthy.com nodejs[8289]: [2016-09-21 05:57:24.221] [INFO] console - The plugin admin page is at http://127.0.0.1:9001/admin/plugins
Sep 21 05:57:46 smtp.darcykenworthy.com nodejs[8289]: [2016-09-21 05:57:46.482] [DEBUG] SessionStore - GET ERt1hbz_7O2F0M5MSOW5uAkuOb-bSY4n
Sep 21 05:57:46 smtp.darcykenworthy.com nodejs[8289]: [2016-09-21 05:57:46.521] [DEBUG] ueberDB - GET    - sessionstorage:ERt1hbz_7O2F0M5MSOW5uAkuOb-bSY4n - {"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true}} - from database
Sep 21 05:57:46 smtp.darcykenworthy.com nodejs[8289]: [2016-09-21 05:57:46.562] [DEBUG] ueberDB - GET    - pad:Temp - {"atext":{"text":"asdfasfWelcome to Etherpad!\n\nThis pad text is synchronized as you type, so that everyone viewing this page sees the s
Sep 21 05:57:46 smtp.darcykenworthy.com nodejs[8289]: [2016-09-21 05:57:46.682] [DEBUG] SessionStore - SET ERt1hbz_7O2F0M5MSOW5uAkuOb-bSY4n
Sep 21 05:57:46 smtp.darcykenworthy.com nodejs[8289]: [2016-09-21 05:57:46.719] [DEBUG] ueberDB - SET    - sessionstorage:ERt1hbz_7O2F0M5MSOW5uAkuOb-bSY4n - {"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true}} - to buffer
Sep 21 05:57:46 smtp.darcykenworthy.com nodejs[8289]: [2016-09-21 05:57:46.800] [DEBUG] http - 200, GET /p/Temp
Sep 21 05:57:46 smtp.darcykenworthy.com nodejs[8289]: [2016-09-21 05:57:46.802] [INFO] ueberDB - Flushed 1 values`

I've tried clearing src/node_modules/ and restarting , as well as running "git pull" to see if there was an update I missed, with no luck

**Comment by jdittrich** [comment]
It seems that the called page can't load any files like scripts or stylesheets. 

Also, I can't access any of the files manually too: Usually I could go to an instance like 
*"foobar.bar/pad/p/someetherpad"* 
and if I substitute the part behind pad, I could get to the javascript files, like 
*"foobar.bar/pad/socket.io/socket.io.js"*. 
On the server you linked I get only a git list page with
 "No route found for "GET /socket.io/socket.io.js"

**Comment by darcykenworthy** [comment]
Ah, got it; I'd misconfigured Nginx location, and it was sending requests for .js files to the wrong directory.
