### ISSUE TITLE
Pick old authorship colors

### ISSUE THREAD

**Issue by z-beeblebroxx** [ether/etherpad-lite#3063]
This is a feature request.

It would be great, if one could pick authorship colors that have been used before. Maybe small color patches could be used for this purpose. This would enable people to continue contributing to a document, even when they reconnect/reopen the browser.

Cheers!

**Comment by Gared** [comment]
As far as I know all users can select the same color on a pad. There is no restriction. You're not able to select a authorship color from the text, but this is not a feature I would like to have

**Comment by dreeves** [comment]
I recommend the [brightcolorpicker plugin](https://www.npmjs.com/package/ep_brightcolorpicker). Does that do what you have in mind?

**Comment by fsch2** [comment]
This looks great, I didn't know about that plugin. Will give it a try! Best, z-beeblebroxx, fsch2
