### ISSUE TITLE
Real-time Collaborative Algorithm

### ISSUE THREAD

**Issue by YuxiangQue** [ether/etherpad-lite#3065]
Hi, I am quite interested in the real-time collaborative algorithm in this wonderful etherpad, can I find some doc or links about it?  Thanks a lot.

**Comment by Aur0r** [comment]
If you go to the [Wiki](https://github.com/ether/etherpad-lite/wiki) in the "For developers" section you can find the "EasySync documentation". I think this is what you are looking for.
