### ISSUE TITLE
Pad stuck on Loading status after paste some text

### ISSUE THREAD

**Issue by pabelenda** [ether/etherpad-lite#3066]
I have suffered several times this annoying behaviour. From time to time, I cut and paste some text (even inside the pad itself) and the pad goes empty and shows Loading message forever.

```
Uncaught Error: mismatch error setting raw text in setDocAText

setDocAText  @VM367:778
setDocumentAttributedText @ VM367:199
(anonymous function) @ VM367:10325
(anonymous function) @ VM367:195
inCallStack @ VM367:472
inCallStackIfNecessary @ VM367:541
withCallbacks @ VM367:192
setBaseAttributedText @ VM367:10311
Ace2Inner.editorInfo.ace_setBaseAttributedText @ VM367:998
(anonymous function) @ VM42 pad.js?callback=require.define:2881
action @ VM42 pad.js?callback=require.define:2841
(anonymous function) @ VM42 pad.js?callback=require.define:2861
_.each._.forEach @ VM43 ace2_common.js?callback=require.define:11298
doActionsPendingInit @ VM42 pad.js?callback=require.define:2860
info.onEditorReady @ VM42 pad.js?callback=require.define:2985
readyFunc @ pad-testwrm?&auth_token=eyJ0eXAiOJ9.eyJsb2dpbi…:17
(anonymous function) @ VM367:5537
```

Taking a look into older issues I found #885 and #769. This should be addressed, but seems like it is happening again. At least on my deployment.

node version: v0.10.29
npm version: 1.4.21
etherpad-lite version: 1.6.0

**Comment by lpagliari** [comment]
@pabelenda Do you have any plugin installed? If you load your Etherpad instance without the plugins and repeat the copy/paste steps on the same pad, do you still get the issue?

**Comment by pabelenda** [comment]
Yes, I have some.

```
ep_author_hover
ep_list_pads
ep_activepads
ep_etherpad-lite
ep_adminpads
ep_delete_empty_pads
ep_small_list
ep_user_font_size
ep_linebreak
ep_pad-lister
ep_mypads
```

I've deployed the instance on another server and removed all the plugins. The error is exactly the same on the affected pads.

**Comment by lpagliari** [comment]
Just to clarify, @pabelenda: you cut/paste, then load the pad later and it never loads, is that it? Or does the pad goes empty right after you pasted the content (without reloading it)?

**Comment by pabelenda** [comment]
Copy + Paste + Reload (after few secons) -> crash

BTW, thanks for answer me back on this :-)

**Comment by lpagliari** [comment]
My guess is that the paste itself caused the error, so existing pads will keep being stuck at "Loading".

Looking at the list of plugins, the only one that looked suspicious of causing this issue was `ep_linebreak`. If you have some time, could you install this plugin on your new Etherpad instance and try to copy/paste some lines with manual line-breaks to see if you can reproduce the error?

Thanks, @pabelenda !

**Comment by pabelenda** [comment]
Finally I decided to remove `ep_linebreak` on the production environment and, since then, no issues were reported.

Anyway, on the testing environment, with `ep_linebreak` installed, I am not able to reproduce the thing.

At this point I think we can close this issue. Many thanks for the help :-)
