### ISSUE TITLE
HTML Export problem : discarded style (heading 2/3/..) in list items

### ISSUE THREAD

**Issue by guillaume-uH57J9** [ether/etherpad-lite#3068]
Greeting,

When applying some style (heading 2, heading 3, ...) to items in a list, and exporting to HTML, the style is discarded. 

Etherpad view:

![etherpad-edit](https://cloud.githubusercontent.com/assets/4953748/19855089/01971944-9f73-11e6-83fb-ee4936cb2f70.png)

Exported HTML view:

![etherpad-html-export](https://cloud.githubusercontent.com/assets/4953748/19855099/08aecf42-9f73-11e6-8cc6-e3f8330f7c3d.png)

Exported HTML snippet: 

`<ul class="bullet"><li>List level 1</li><ul class="bullet"><li>List level 2</li><li>List level 2</li></ul></ul>`

**Comment by lpagliari** [comment]
@guillaume-uH57J9 Does this happen to other styles applied to the entire line (like alignment, for example)? The ep_headings2 plugin has [an open issue related to export to HTML](https://github.com/ether/ep_headings2/issues/9), so it might be an issue with the plugin, not Etherpad.

**Comment by guillaume-uH57J9** [comment]
@lpagliari You're right, HTML export also discards alignement, as shown below. 

Does that mean this is an issue with ep_headings2, or Etherpad ? 

I'm not sure I follow the relation with ep_headings2, but I will close/move the issue if you think it's caused by a different piece of code/plugin. 

Etherpad view : 

![align-ether](https://cloud.githubusercontent.com/assets/4953748/19885044/da7ff24a-a01c-11e6-9198-2c3efef2a7c6.png)

Exported HTML view : 

![align-html-export](https://cloud.githubusercontent.com/assets/4953748/19885051/de26810c-a01c-11e6-8587-6b3554c2c3fc.png)

**Comment by lpagliari** [comment]
If alignment was correctly exported I would say it was probably an issue with ep_headings2. As both line attributes are not being exported, it might be (a) an issue with Etherpad not handling correctly line attributes on export; or (b) both plugins are not exporting their contents correctly. 

We'll need to take a closer look on the code to be sure. But thanks for your report and your tests!

**Comment by JohnMcLear** [comment]
Plugin problem, please create the bug reports on the plugins.
