### ISSUE TITLE
Etherpad settings.json connection to Secure Mysql Database with Keys

### ISSUE THREAD

**Issue by subhashdasyam** [ether/etherpad-lite#3072]
Hi Guys,

I don't know if this is mentioned earlier (i quickly searched for the SSL configuration for DB settings but couldn't find), can some one point me to the settings on how to connect to a secure database with SSL cetrtificates.

Regards

**Comment by lpagliari** [comment]
I haven't worked with SSL on DB settings, but you might find more info examining the ueber db code: https://github.com/Pita/ueberDB/blob/master/mysql_db.js

**Comment by subhashdasyam** [comment]
Thanks @lpagliari for the link, i have already referred to the above link, unfortunately i was not able to find anything related to the SSL connectivity

**Comment by DanielBickley** [comment]
Once your mysql installation is configured for SSL connections, you'll probably have to hunt/peck for the connection call in the etherpad code. Edit or hook from there.

https://dev.mysql.com/doc/refman/5.5/en/using-secure-connections.html

"To establish a secure connection, use the mysql_ssl_set() C API function to set the appropriate certificate options before calling mysql_real_connect(). See Section 23.8.7.67, “mysql_ssl_set()”.

**Comment by subhashdasyam** [comment]
thanks @DanielBickley i don't think i can use hook to pass the connected ssl connection, as i am new to nodejs. 
If you have time, or when every you can, would you be willing to write a small example for me

Thanks in advance

Regards,

**Comment by DanielBickley** [comment]
Sorry, I don't have time, but am currently attempting a plugin that better manages database connections, mainly in an effort to see if I can assign entire etherpad databases to individual etherpad users. It's slow going, but I'll try to add in SSL connectivity as an option, and update this post at completion. I'm not entirely certain how you'd go about editing your local installation of etherpad, but if you can just do a conditional check in there to see if the pad is loaded over https, then tack on the mysql_ssl_set() or something. Just thinking aloud here.

**Comment by JohnMcLear** [comment]
This is really an ueberDB request not an Etherpad thing!
