### ISSUE TITLE
Doesn't work with node >= 7

### ISSUE THREAD

**Issue by kpcyrd** [ether/etherpad-lite#3074]
During `installDeps.sh` there are multiple deprecations:
```
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```
the `graceful-fs` package causes etherpad to be incompatible with node >= 7.0 and causes etherpad to crash with
```
 module.js:474
     throw err;
     ^
 Error: Cannot find module 'internal/fs'
     at Function.Module._resolveFilename (module.js:472:15)
     at Function.Module._load (module.js:420:25)
     at Module.require (module.js:500:17)
     at require (internal/module.js:20:19)
     at evalmachine.<anonymous>:17:20
     at Object.<anonymous> (/opt/etherpad/src/node_modules/npm/node_modules/graceful-fs/fs.js:11:1)
     at Module._compile (module.js:573:32)
     at Object.Module._extensions..js (module.js:582:10)
     at Module.load (module.js:490:32)
     at tryModuleLoad (module.js:449:12)
```

**Comment by alejoduque** [comment]
I can confirm this is the case and I was mislead by the internal-fs error trying all kinds of tricks, none worked so here we have another broken etherpad-lite. Please anyone give us a hint on how to patch this one. Tx!

npm -v
4.0.2
# node -v
v7.0.0

**Comment by DocMAX** [comment]
please fix that stupid error!!!

**Comment by 2Belette** [comment]
no idea to solve this one ?

**Comment by lpagliari** [comment]
For now, I would say "use Node 6.9" if you desperately need Etherpad running; to fix it we need to check the compatibility with newer versions of some libs -- for now I can say that at least mocha and npm are on this list.

**Comment by 2Belette** [comment]
thanks yes it is working I just downgraded to 6.9

**Comment by thomwiggers** [comment]
FYI: I've tried updating only Mocha and npm, but a *lot* of things broke. For example, in a lot of random places the recursion limit was reached. I don't know enough js to fix it.

**Comment by lpagliari** [comment]
@thomwiggers that's the exact point I was, when I had to pause my work on this issue. Still don't know what is happening there... If you find anything else, let me know. And thanks for trying to fix this too!

**Comment by Gared** [comment]
NPM needs an update.
My changes worked so far and I can hopefully provide a PR tomorrow.
