### ISSUE TITLE
Continously "Reconnecting to your pad.." and then Connected

### ISSUE THREAD

**Issue by matbgn** [ether/etherpad-lite#3078]
More than 10 times per minutes the message Reconnect to your pad appears quickly, then access to parameters is no more reachable and on some machines did a lost of data.

![2016-11-12_12h07_48](https://cloud.githubusercontent.com/assets/13169819/20237400/5c409ee4-a8d1-11e6-9ead-93181cf08f0c.png)
![2016-11-12_12h10_22](https://cloud.githubusercontent.com/assets/13169819/20237401/5fe0fa8a-a8d1-11e6-9823-8bfb04c27fac.png)

N.B. : The internet connection is not in question : 
![2016-11-12_12h16_25](https://cloud.githubusercontent.com/assets/13169819/20237411/dfc4f378-a8d1-11e6-90eb-7640de5902c7.png)

**Comment by lpagliari** [comment]
Can you give us more details about your issue, please?

Which plugins do you have installed? What are the error messages you see on browser console (if any)? And on Etherpad log? Do you have the same issue when you run your Etherpad instance without plugins? Is there any action the user does to trigger the reconnect?

Thanks!

**Comment by matbgn** [comment]
With pleasure : 

1° Only one plugin is installed : ep_adminpads

2° Unfortunately no message at all on the browser console...

3° On the server side I have logically that : 
`[2016-11-12 11:15:30.418] [INFO] access - [ENTER] Pad "Z7WzkB5xDa": Client AcktCzbMDQfcf6_VAABL with IP "194.230.159.101" entered the pad
[2016-11-12 11:15:30.441] [INFO] ueberDB - Flushed 1 values
[2016-11-12 11:15:40.636] [INFO] access - [LEAVE] Pad "Z7WzkB5xDa": Author "a.1VTy8NnZaRuc2upf" on client AcktCzbMDQfcf6_VAABL with IP "194.230.159.101" left the pad`

4° It was precisely the idea to test a minimal configuration without plugins (except adminpads). Do you really thick it's necessary to throw out this one too ? I will recompile without in thos case.

5° No trigger at all quiet random and disturbing. The only thing I can say is that if a infinitely click the mouse it didn't appear... (but not really sure of that).

**Comment by matbgn** [comment]
On a real DEBUG lvl I have this, does this talk to anyone ? 

`[2016-11-12 12:35:38.926] [INFO] access - [ENTER] Pad "XiwrhMxtzK": Client 5S5TYotSEB9Gkk3hAAAl with IP "194.230.159.101" entered the pad
[2016-11-12 12:35:38.926] [DEBUG] message - to 5S5TYotSEB9Gkk3hAAAl: {"type":"COLLABROOM","data":{"type":"USER_NEWINFO","userInfo":{"ip":"127.0.0.1","colorId":"#2d8e80","userAgent":"Anonymous","userId":"a.1VTy8NnZaRuc2upf","name":""}}}
[2016-11-12 12:35:38.975] [INFO] ueberDB - Flushed 1 values`

**Comment by matbgn** [comment]
More special, when I checkout on the develop branch I obtain simply this : 

`[2016-11-12 13:01:32.741] [DEBUG] SessionStore - GET false
[2016-11-12 13:01:32.742] [DEBUG] ueberDB - GET    - sessionstorage:false - null - from cache
`

**Comment by categis-may2011** [comment]
Every time we are copying and pasting or even running the etherpad for more time, we are getting the message as "Reconnecting.. and Connected.."

**Comment by rhansen** [comment]
@categis-may2011 See #4951.
