### ISSUE TITLE
[Export functions] Exported pages (e.g. PDF pages) bear spooky label "JavaScript license information"

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#3079]
When exporting pages as pdf, or odf, the last page shows a spooky string  `JavaScript license information`.

I suppose this is caused by the static page code
```
<div style="display:none"><a href="/javascript" data-jslicense="1">JavaScript license information</a
</div>
```

Is there already a solution to fix this ?

**Comment by MartB** [comment]
This is still around, is there any workaround besides removing this from the html ?
Tbh the exporters should ignore all display:none elements.

**Comment by JohnMcLear** [comment]
Unable to replicate

**Comment by Wikinaut** [comment]
@JohnMcLear one moment, please

**Comment by Wikinaut** [comment]
@JohnMcLear please reopen, as the problem is still present (recent master version)

![20180403-21 08 15_auswahl](https://user-images.githubusercontent.com/1151915/38270321-4ec9ef12-3783-11e8-932b-6c6279f4b630.png)

Output of a fresh pad.

**Comment by Wikinaut** [comment]
String does not appear in plain text export format.

**Comment by Wikinaut** [comment]
@JohnMcLear I have revisited this, the issue is still present and I kindly ask you to reopen the bug report.

**Comment by JohnMcLear** [comment]
This has to be coming from Abiword or some third party thing that's doing the conversion.. What are you using?  Version of abiword?  soffice? etc

**Comment by Wikinaut** [comment]
settings.json:
```
  /* This is the path to the soffice (LibreOffice) executable. Setting it to null, disables abiword.
     Abiword or LibreOffice is needed to advanced import/export features of pads*/  
  "soffice" : "/usr/bin/soffice",
```

```
$ soffice --version
LibreOffice 5.2.7.2 20m0(Build:2)
```

**Comment by JohnMcLear** [comment]
If you convert a .html file with soffice manually does it append the license string?

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/commit/97fd1ab2feffa92494d837d2aefd842853d9f816

**Comment by Wikinaut** [comment]
Confirmed! Solved!! Bravo!!!
