### ISSUE TITLE
Cannot find module /node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node

### ISSUE THREAD

**Issue by DannieFly** [ether/etherpad-lite#3083]
Error: Cannot find module '/var/www/html/CTFPad/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node'
But i can find the module '/var/www/html/CTFPad/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'

**Comment by Gared** [comment]
Please provide more infos:
- Node.js and npm version
- OS
- What did you do? Steps to reproduce? Probably bin/run.sh, right?

**Comment by DannieFly** [comment]
I already have the answer for myself. Because at first, I install nodejs which version is v6.9.1,so do npm install i got the v48,the i unistall nodejs ,and try nodejs v0.10.x ,so there {node_api} will be v11. 
https://nodejs.org/en/download/releases/
