### ISSUE TITLE
Chat bubble shown on bottom right even though chat disabled

### ISSUE THREAD

**Issue by kernelfreak** [ether/etherpad-lite#3088]
Hello friends,

I am trying to work with etherpad and currently facing some problem. I have disabled chat from settings.json as well as installed disable-chat plugin from admin-plugins. Even after that, whenever a pad is opening, for a few seconds on bottom right corner, I see a 0 which at hover says chat(alt+c). How can I remove this 0. Thank you.

**Comment by JohnMcLear** [comment]
The solution would be to hide chat in CSS and only show it if showChat is set to true or undefined.  pad.js would handle this.

This is a low hanging fruit for someone.
