### ISSUE TITLE
 ETIMEDOUT 104.130.77.39:443

### ISSUE THREAD

**Issue by kingmook** [ether/etherpad-lite#3090]
When attempting to access the plugin manager in admin I'm getting a timeout in the error log. 

```
Error: connect ETIMEDOUT 104.130.77.39:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

```

I believe 104.130.77.39:443 is the npm lookup for etherpad plugins. It has worked in the past with my production server, but today I don't seem to be able to ping. Is this service temporarily down or has this service been moved?

**Comment by Gared** [comment]
I know you're right. This service is temporarily down since yesterday. Hope I'll get it online again soon.

**Comment by kingmook** [comment]
Thanks for the quick check-in. I'm not hurting for it, and frankly happy it's not something on my end for a change.

**Comment by eviltel** [comment]
It seems to be the same problem with the plugin list link <http://static.etherpad.org/plugins.html> which I found on the Wiki page <https://github.com/ether/etherpad-lite/wiki/Plugin,-a-list>.
static.etherpad.org resolvs to the same address.

**Comment by Thireus** [comment]
Still down, is there another alternative?

**Comment by Gared** [comment]
@Thireus You can install those plugins on your cli:
```
npm install ep_PLUGINNAME
```

**Comment by Aur0r** [comment]
Just if someone didn't know: In the meanwhile if you can't figure out the name of a plugin there is a json blob that can be used to figure out the needed plugin names. I hope this one is up-to-date.

**Comment by Thireus** [comment]
Also, https://www.npmjs.com/search?q=ep_ is where you get the plugin list. Anything starting with "ep_" should be for Etherpad.

**Comment by Gared** [comment]
The server is up again!

**Comment by theredfish** [comment]
Thank you for your work!

**Comment by dbareiro** [comment]
Hi!

It looks like the service is down again:

```
Jan  9 18:49:39 conference node[392]: #033[33m[2017-01-09 18:49:39.272] [WARN] console - #033[39m{ Error: connect ETIMEDOUT 104.130.77.39:443 
Jan  9 18:49:39 conference node[392]: at Object.exports._errnoException (util.js:1022:11) 
Jan  9 18:49:39 conference node[392]: at exports._exceptionWithHostPort (util.js:1045:20) 
Jan  9 18:49:39 conference node[392]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14) 
Jan  9 18:49:39 conference node[392]: code: 'ETIMEDOUT', 
Jan  9 18:49:39 conference node[392]: errno: 'ETIMEDOUT', 
Jan  9 18:49:39 conference node[392]: syscall: 'connect', 
Jan  9 18:49:39 conference node[392]: address: '104.130.77.39', 
Jan  9 18:49:39 conference node[392]: port: 443 } 
Jan  9 18:49:39 conference node[392]: Error: connect ETIMEDOUT 104.130.77.39:443 
Jan  9 18:49:39 conference node[392]: at Object.exports._errnoException (util.js:1022:11) 
Jan  9 18:49:39 conference node[392]: at exports._exceptionWithHostPort (util.js:1045:20) 
Jan  9 18:49:39 conference node[392]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

Kind regards,
Daniel

**Comment by Gared** [comment]
See #3092

**Comment by dbareiro** [comment]
Thanks for the prompt resply, Gared. I'll be watching the news on #3092.

Kind regards,
Daniel

**Comment by jgribonvald** [comment]
This error appear again today:
`[ERROR] console - Can not perform Etherpad update check: Error: connect ECONNREFUSED 80.244.243.156:443`

**Comment by badboby** [comment]
This error appear again today:

**Comment by badboby** [comment]
This error appear again today:

**Comment by badboby** [comment]
This error appear again today:
Can not perform Etherpad update check: Error: connect ETIMEDOUT 5.75.249.160:443

**Comment by andrewchenshx** [comment]
[2023-09-23 11:48:06.517] [ERROR] console - Can not perform Etherpad update check: Error: connect ETIMEDOUT 5.75.249.160:443

**Comment by Kelivan** [comment]
Same problem
[2024-05-29 17:38:24.856] [ERROR] console - Can not perform Etherpad update check: Error: connect ETIMEDOUT 5.75.249.160:443

**Comment by yuyongsong** [comment]
> 首先要明确这一点：此错误意味着 Etherpad 无法检查可用的最新 etherpad 版本，并且根本不会影响任何功能。尽管如此，它发生的还是很奇怪的。
> 
> 有人可以重现此错误吗？我在服务器端看不到任何问题。也许这是运行etherpad的服务器上的问题？有人可以检查插件列表是否可以在管理界面中加载（因为插件列表托管在同一台服务器上）？

[2024-06-20T02:17:55.486] [ERROR] settings - Can not perform Etherpad update check: AggregateError
[2024-06-20T02:30:56.909] [ERROR] settings - AxiosError [AggregateError]
    at AxiosError.from (/home/yys/Etherpad/etherpad-lite/node_modules/.pnpm/axios@1.6.8/node_modules/axios/dist/node/axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (/home/yys/Etherpad/etherpad-lite/node_modules/.pnpm/axios@1.6.8/node_modules/axios/dist/node/axios.cjs:3086:25)
    at RedirectableRequest.emit (node:events:518:28)
    at RedirectableRequest.emit (node:domain:488:12)
    at eventHandlers.<computed> (/home/yys/Etherpad/etherpad-lite/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:518:28)
    at ClientRequest.emit (node:domain:488:12)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/home/yys/Etherpad/etherpad-lite/node_modules/.pnpm/axios@1.6.8/node_modules/axios/dist/node/axios.cjs:3876:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/yys/Etherpad/etherpad-lite/src/static/js/pluginfw/installer.ts:2:5967 {
  code: 'ETIMEDOUT',
  errors: [
    Error: connect ETIMEDOUT 5.75.249.160:443
        at createConnectionError (node:net:1646:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1705:38)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '5.75.249.160',
      port: 443
    },
    Error: connect ENETUNREACH 2a01:4f8:c17:ba99::1:443 - Local (:::0)
        at internalConnectMultiple (node:net:1180:16)
        at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2a01:4f8:c17:ba99::1',
      port: 443
    }
  ],
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'Etherpad/2.0.1',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://static.etherpad.org/plugins.json',
    data: undefined
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Function: handleRequestSocket]
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/plugins.json',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'static.etherpad.org',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/plugins.json'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /plugins.json HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: Etherpad/2.0.1\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: static.etherpad.org\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/plugins.json',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'static.etherpad.org',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://static.etherpad.org/plugins.json',
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: AggregateError [ETIMEDOUT]: 
      at internalConnectMultiple (node:net:1116:18)
      at internalConnectMultiple (node:net:1184:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    [errors]: [ [Error], [Error] ]
  }
}
