### ISSUE TITLE
beta.etherpad.org is down

### ISSUE THREAD

**Issue by theredfish** [ether/etherpad-lite#3092]
Hi here,

Since one week beta.etherpad.org is down. Do you have any information about that?

If you prefer you can answer here :) https://twitter.com/julian__didier/status/804413663096356864

good afternoon!

**Comment by lpagliari** [comment]
@Gared is this related to #3090 ?

**Comment by Gared** [comment]
Yes, it's the same issue. I'm on it

**Comment by theredfish** [comment]
Ok thanks for your answers. Let me know when it's ok. I will follow #3090 too. Thank you!

**Comment by theredfish** [comment]
Hi @Gared / @lpagliari ,

It seems that beta.etherpad.org is down again. I got a timeout.

**Comment by Gared** [comment]
@theredfish @lpagliari Our services have been disabled by our hoster, but I'm on it again

**Comment by akuckartz** [comment]
Strange hoster...

**Comment by theredfish** [comment]
Up again :) thanks!

**Comment by Gared** [comment]
@theredfish Well spotted!
