### ISSUE TITLE
Can't load my etherpad, no refresh successful

### ISSUE THREAD

**Issue by deloeuw** [ether/etherpad-lite#3098]
Hi evreybody !

Sorry for my English : it's not my language...

I lost the access to my etherpad but the comment-box remains. When I click to the adress, I've got the blank page for loading, the comment box appears on the right bottom, but loading is long befor this error message :
"An error occured
The error was reported with the following id: '*************************'
Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: ********************
URL: https://etherpad.fr/p/**************
UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0
TypeError: self.dropdowns is undefined in https://etherpad.fr/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 2419'" (I've hidden by stars the identity of my page. Hope you'll understand).

I tried to refresh but nothing's got better. Have an idea about how to fix the issue and get back my text ?

Thanks a lot for your advices !

**Comment by lpagliari** [comment]
@deloeuw are you able to edit other pads on the same Etherpad instance? I mean, is it an issue with an specific pad, or the Etherpad installation?

If your pad is not accessible anymore and you want to recover its content to work on another pad, you can try to export it by appending `/export/etherpad` after the id of your pad:  `https://etherpad.fr/p/**************/export/etherpad`.

You can also try to navigate through the revisions of your pad @ `https://etherpad.fr/p/**************/timeslider`, and then export an specific version where the issue does not happen by clicking on the button at the upper right corner of the Timeslider: 
![image](https://cloud.githubusercontent.com/assets/836386/21183267/541accea-c1ee-11e6-80c6-ec17ec9247cf.png)

**Comment by deloeuw** [comment]
@lpagliari 
Thanks a lot for your answer !

I've got several pads but just this one was concerned by the problem. I had no access to the menus : juste the comment box. So your advice can't be my solution... 

However, after your answer, I checked my pad and all oh them are KO. Error 504 : 

"504 Gateway Time-out
nginx"

An ether idea ? ^^

**Comment by joassouza** [comment]
Do you have admin access? You can try to get html of the pad using the API.

**Comment by deloeuw** [comment]
@joassouza 
Thank you very much for your answer... that I try to understand ^^
Get the sense from English to French when we are not a wizard of computers is a challenge ^^
Like I wrote in the message I sent just before your answer, I've no pannel to enter the controls, juste the comment box. 
And since some hours, I've just the white out error page : "504 Gateway Time-out
nginx"

But maybe is there an element where I'm wrong... When I use etherpad, do I use an object supported by several devices or is it everywher the same platform ? Because I just found your forum to help me, but it seems to be dedicated for etherpad-lite and I'm a French user who use etherpad.fr on Internet...

Is there something wrong with my presence here or this place is the best to find something's good to fix my issue ?

Thanks for your help and advices !

**Comment by lpagliari** [comment]
@deloeuw it looks like etherpad.fr runs etherpad-lite, so you are at the right place to ask. :-) I've tried to access a pad at etherpad.fr with issues too (https://etherpad.fr/p/Test), and if I access its Timeslider (https://etherpad.fr/p/Test/timeslider) I am able to see its content. The only thing you would have to do is to replace `Test` by your pad id (the one you replaced by `*****` on your original question). Does that work for you?

**Comment by deloeuw** [comment]
@Ipagliari
Wow ! You're fantastic ! Do you know it ?
Thanks to your explanations, I could see my text again, but I don't know what I can do to make etherpad work again... 
Are my pads totally frozen without any hope to get back to the normality ?

**Comment by deloeuw** [comment]
Thanks to you for your explanations ! I wrote too fast !

**Comment by lpagliari** [comment]
@deloeuw if you want to restore your pad, you can try to export an old version of it and import into another pad:

- go to the Timeslider (https://etherpad.fr/p/******/timeslider)
- go back to an old revision by clicking on 
![image](https://cloud.githubusercontent.com/assets/836386/21191843/943bd5a2-c20d-11e6-87eb-aebcca28e677.png)
- export this revision by clicking on 
![image](https://cloud.githubusercontent.com/assets/836386/21191869/aca3debe-c20d-11e6-8b7c-08f03fde1aa1.png)
- create **another** pad (so you don't loose your work)
- on the new pad, import your file by clicking on 
![image](https://cloud.githubusercontent.com/assets/836386/21191983/12052c9a-c20e-11e6-980e-639ebab4cadb.png)

You might need to try the steps above for different revisions, until you find one that loads correctly.

**Comment by deloeuw** [comment]
Thx ! You were very helpfull !

**Comment by deloeuw** [comment]
@Ipagliari : your explanations were very clear but it doesn't work properly : the version which is exported/imported isn't the version I'I've chosen... Have you an ether idea !

**Comment by lpagliari** [comment]
Sorry, I won't be able to help you now...

**Comment by deloeuw** [comment]
Don't be sorry ! You've been an angel into this jungle !

Thank you very much !

I hope I'll be lucky again next time I'll have an issue and I'll fall on you !

I wish tou a good continuation !

**Comment by jywarren** [comment]
Thank you all - we had an almost identical issue and did the same -- many thanks!!! 🎉
