### ISSUE TITLE
official debian package for etherpad

### ISSUE THREAD

**Issue by simevo** [ether/etherpad-lite#3099]
Hi I am trying to package etherpad for Debian (https://bugs.debian.org/576998). 6 years have passed from the 1st attempts, many nodejs modules are now in Debian and there is a dim hope to get it in before the Debian Stretch freeze (Jan 5th).

Would anyone here be willing to support me ? As a start I have 3 questions.

1) what is the right name here, etherpad or etherpad-lite ?
2) you depend on etherpad-yajsml, is that same as https://www.npmjs.com/package/yajsml ?
3) if we choose postgresql as DB backend, can we skip some code / modules / dependencies (like nano, rethinkdb, couchdb stuff...) ?

Thanks, Paolo

**Comment by Gared** [comment]
I would support you, but I don't know if it is enough time to do all the work in a few weeks.
We have a script to build a debian package, but it is not really working (anymore): https://github.com/ether/etherpad-lite/blob/develop/bin/buildDebian.sh
1. It's called "etherpad", although it's a little bit irretating because of the "java etherpad".
2. no it's not the same as far as I know. We have created a few modules that etherpad depends on.
3. Yes, probably, but I'm not that deep in the subject. ueberdb has many database dependencies which are not absolutely necessary.

But it's great to see that someone wants to work on it!

**Comment by simevo** [comment]
Another question I have is about the dependency on swagger-node-express version 2.1.3 (based on  [src/package.json](https://github.com/ether/etherpad-lite/blob/develop/src/package.json)). While this is the current release on [npm registry](https://www.npmjs.com/package/swagger-node-express), [upstream](https://github.com/swagger-api/swagger-node/releases) has moved on to version 0.7.3.
And BTW is this a node module you are using (that gets installed in `/usr/lib/nodejs/foo`) or a javascript library (that gets installed in `/usr/share/javascript/foo/`) ?

**Comment by jonasstein** [comment]
@simevo Will you develop the package on github? Please document the problems and solutions well. It will be a great help for other distributions too. We wish to have it in gentoo too. You can find our results here: https://bugs.gentoo.org/show_bug.cgi?id=328897 Let me know, if you need betatesters for your debian package and I will ask in our linux user group.

**Comment by simevo** [comment]
The repo is here: https://anonscm.debian.org/git/pkg-javascript/etherpad-lite.git, but there's not much there yet to see.
The main thread on the Debian package in this phase is the ITP bug (https://bugs.debian.org/576998).
I'll notify major news here as well.

**Comment by simevo** [comment]
Alright we just missed the stretch freeze window so let's relax !
There is still a lot of work required, particular on packaging socket.io stuff & its requirements.
My new goal is to target the next Debian release (testing i..e buster). Creating a version for stretch-backports is also a possibility.

**Comment by PanderMusubi** [comment]
Please, see also for both Debian and Ubuntu https://bugs.launchpad.net/ubuntu/+bug/1397373 Adding a vote there will also help gain support for packaging etherpad.

**Comment by simevo** [comment]
Do you mean clicking on "this bug affects me" in launchpad ? I have just done that.

But there's more you can do. For example here is an (incomplete) list of dependencies we need to package before we get etherpad-lite in debian:
- node-socket.io http://bugs.debian.org/707166
- node-socket.io-client https://bugs.debian.org/781412
- node-engine.io https://bugs.debian.org/781426
- node-socket.io-adapter https://bugs.debian.org/781405
- node-express-session http://bugs.debian.org/751885

Any help is welcome, just join the [debian javascript packaging team](https://alioth.debian.org/projects/pkg-javascript) and start hacking !

**Comment by JohnMcLear** [comment]
bump @simevo  <3

**Comment by Natureshadow** [comment]
Bumping this issue because the Teckids schul-frei project has started packaging BigBlueButton for Debian 10, which depends on etherpad-lite. So if anyone has done something that helps this, or has tiem to do so, please speak up ☺!

**Comment by JohnMcLear** [comment]
I'd love to see this too :)  Let me create a bounty.

**Comment by JohnMcLear** [comment]
Bounty made: https://gitpay.me/#/task/327

**Comment by hex-m** [comment]
Thanks, but there are [lots of dependencies](https://wiki.debian.org/Javascript/Nodejs/Tasks/Etherpad-lite) missing before etherpad-lite itself can be packaged. So most likely this will not be a one-person-project.

**Comment by muxator** [comment]
@hex-m, how does dependency installation & resolution for nodejs application work in Debian?

Does it have to exist a package in the official repository for each dependency, or they can be bundled together in a `node_modules` somewhere?

**Comment by hex-m** [comment]
> Does it have to exist a package in the official repository for each dependency, or they can be bundled together in a `node_modules` somewhere?

I'm no Debian Developer but reading the [documentation](https://wiki.debian.org/Javascript/GroupSourcesTutorial) I would say the normal way is to package each module separately. Exceptions are explained in the link.

Having one `node_modules` package containing the entire npm registry would have serious downsides.

**Comment by abskmj** [comment]
is it possible to automate the steps? I might be able to put together a workflow on GitHub actions to package and publish new Debian packages. Sounds feasible?

**Comment by muxator** [comment]
@abskmj, that would be cool.

However, I think the problem here is _defining_ those steps, which are not clear at all. For example, there is the whole issue of packaging the dependencies in Debian, before working on Etherpad.

**Comment by abskmj** [comment]
Oh, I meant automating packaging the dependencies in Debian. I went through the referenced articles on Debian wiki. I see most of the steps are similar for most of the packages (there may be few exceptions). I'm wondering if I could execute those steps for all the missing packages in a Github action workflow. This might take less effort than doing it manually for all the dependency.
