### ISSUE TITLE
Feature request: allow cookie-less read access

### ISSUE THREAD

**Issue by janvlug** [ether/etherpad-lite#3109]
I would like to have the possibility to read etherpads with having to store cookies.
Currently, when you have cookies disabled you get this message:
"Cookie could not be found. Please allow cookies in your browser!"
Please allow read access to etherpads without having to allow cookies.

**Comment by JohnMcLear** [comment]
This is the same as the Read only HTML request which shouldn't require cookies / javascript.  So closing as duplicate.
