### ISSUE TITLE
Setting/removing bullet points causes text not to be saved in etherpad

### ISSUE THREAD

**Issue by kernelfreak** [ether/etherpad-lite#3110]
Hello friends,

We are experiencing a weird issue with Etherpad. Whenever we are adding bullet-points, and then when we go backspace, and delete 1-2 bullet points and its text, then the entire text in etherpad is not saved. There is no error generated as there is no log file created/updated when this happens. 

I found this bug when I googled, is this related to it? What is the fix, we are running the latest version already.

Link for [https://bugzilla.mozilla.org/show_bug.cgi?id=850824](url)

Any ideas? Thank you.

**Comment by lpagliari** [comment]
@kernelfreak Does this happen only on Firefox, or could you reproduce in Chrome too? And is there any error message logged on browser console (not server console)? Thanks!

**Comment by kernelfreak** [comment]
@lpagliari Problem happening in chrome as well(confirmed by tester). No error in browser or server. Any ideas. Thank you.

**Comment by faelnor** [comment]
I encounter the same problem where there is a transparent loss of synchronisation with the server when manipulating lists and even when copy/pasting without reason. So nothing gets saved after that.

[URL of my etherpad instance](http://ether.anodal.org), running with nginx forwarding.

I also another problem where etherpad never loads when using Chrome on Android but that's probably another issue.
