### ISSUE TITLE
node-uuid deprecated, use uuid module instead

### ISSUE THREAD

**Issue by pmontrasio** [ether/etherpad-lite#3111]
Just cloned the repository and run ```run.sh```, which installed everything.
Got this and other warnings that I'll put into their own issues.

```
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
```

```
$ npm ls node-uuid
/home/me/etherpad/etherpad-lite
└─┬ ep_etherpad-lite@1.6.1 -> /home/me/etherpad/etherpad-lite/src
  ├─┬ npm@4.0.2
  │ └─┬ request@2.78.0
  │   └── node-uuid@1.4.7 
  └─┬ request@2.55.0
    └── node-uuid@1.4.7 
```

Probably an issue to be opened to ```npm``` and ```request``` but it could be useful to have it here for tracking its progress. Close it if you feel like it doesn't belong to here.

**Comment by lpagliari** [comment]
`request` already has a version using the correct dependency (see https://github.com/request/request/blob/master/package.json#L49), so it's a matter of Etherpad to use a newer version of `request`. It makes sense to be tracked here, @pmontrasio . Thanks!
