### ISSUE TITLE
systemd start crased

### ISSUE THREAD

**Issue by wojtas911** [ether/etherpad-lite#3113]
Hi,
uname -a
Linux  4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

npm -v
4.0.5

node -v
v7.2.1

cat /etc/systemd/system/etherpad-lite.service
[Unit]
Description=etherpad-lite (real-time collaborative document editing)
After=syslog.target network.target

[Service]
Type=simple
User=etherpad
Group=etherpad
ExecStart=/opt/etherpad/bin/run.sh

[Install]
WantedBy=multi-user.target

systemctl start etherpad-lite ;  journalctl -f
sty 04 22:11:44 server systemd[1]: Started etherpad-lite (real-time collaborative document editing).
sty 04 22:11:44 server run.sh[20350]: Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
sty 04 22:11:49 server run.sh[20350]: Ensure jQuery is downloaded and up to date...
sty 04 22:11:49 server run.sh[20350]: Clearing minified cache...
sty 04 22:11:49 server run.sh[20350]: Ensure custom css/js files are created...
sty 04 22:11:49 server run.sh[20350]: Started Etherpad...
sty 04 22:11:50 server run.sh[20350]: module.js:472
sty 04 22:11:50 server run.sh[20350]:     throw err;
sty 04 22:11:50 server run.sh[20350]:     ^
sty 04 22:11:50 server run.sh[20350]: Error: Cannot find module 'internal/fs'
sty 04 22:11:50 server run.sh[20350]:     at Function.Module._resolveFilename (module.js:470:15)
sty 04 22:11:50 server run.sh[20350]:     at Function.Module._load (module.js:418:25)
sty 04 22:11:50 server run.sh[20350]:     at Module.require (module.js:498:17)
sty 04 22:11:50 server run.sh[20350]:     at require (internal/module.js:20:19)
sty 04 22:11:50 server run.sh[20350]:     at evalmachine.<anonymous>:17:20
sty 04 22:11:50 server run.sh[20350]:     at Object.<anonymous> (/opt/etherpad/src/node_modules/npm/node_modules/graceful-fs/fs.js:11:1)
sty 04 22:11:50 server run.sh[20350]:     at Module._compile (module.js:571:32)
sty 04 22:11:50 server run.sh[20350]:     at Object.Module._extensions..js (module.js:580:10)
sty 04 22:11:50 server run.sh[20350]:     at Module.load (module.js:488:32)
sty 04 22:11:50 server run.sh[20350]:     at tryModuleLoad (module.js:447:12)
sty 04 22:11:50 server systemd[1]: etherpad-lite.service: Main process exited, code=exited, status=1/FAILURE
sty 04 22:11:50 server systemd[1]: etherpad-lite.service: Unit entered failed state.
sty 04 22:11:50 server systemd[1]: etherpad-lite.service: Failed with result 'exit-code'.

But when i try to run by run scrip as user etherpad 
everything is working fine.

**Comment by wojtas911** [comment]
BWT
etherpad is starting but
I got a lot of warning, did i mess up something?


/opt/etherpad$ bin/run.sh 
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
Ensure jQuery is downloaded and up to date...
Clearing minified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2017-01-04 22:15:00.047] [ERROR] console - (node:20422) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[2017-01-04 22:15:02.301] [WARN] pluginfw - /opt/etherpad/node_modules/ep_etherpad-lite/node_modules/has-cors requires global@'https://github.com/component/global/archive/v2.0.1.tar.gz' but will load
/opt/etherpad/node_modules/ep_etherpad-lite/node_modules/global,
which is version 2.0.1 unmet dependency
[2017-01-04 22:15:02.320] [WARN] pluginfw - /opt/etherpad/node_modules/ep_etherpad-lite/node_modules/engine.io-client requires xmlhttprequest@'https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz' but will load
/opt/etherpad/node_modules/ep_etherpad-lite/node_modules/xmlhttprequest,
which is version 1.5.0 unmet dependency
[2017-01-04 22:15:05.771] [INFO] console - Installed plugins: 
[2017-01-04 22:15:05.776] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2017-01-04 22:15:05.777] [WARN] console - Can't get git version for server header
ENOENT: no such file or directory, lstat '/opt/etherpad/.git'
[2017-01-04 22:15:05.778] [WARN] console - Can't get git version for server header
ENOENT: no such file or directory, lstat '/opt/etherpad/.git'
[2017-01-04 22:15:05.778] [INFO] console - Your Etherpad version is 1.6.0 ()
[2017-01-04 22:15:06.160] [INFO] console - You can access your Etherpad instance at http://127.0.0.1:9001/
[2017-01-04 22:15:06.161] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json

**Comment by lpagliari** [comment]
@wojtas911 regarding the errors, it's probably because you're running a version of Etherpad that is not compatible with node v.7 (see #3074). Could you update to v. 1.6.1, please?

About the warnings, they are normal. There are other issues opened to fix them (ex: #2954)

**Comment by wojtas911** [comment]
@lpagliari 
Hi, thank You for info.
sorry i didn't notice that Issue (#3074)
Thanks for explain.

I will do upgrade right away.
