### ISSUE TITLE
Problem using Abiword as converter.

### ISSUE THREAD

**Issue by dbareiro** [ether/etherpad-lite#3116]
Hi all.

First of all, thanks for sharing your work with Etherpad Lite.

I'm trying Etherpad Lite with Jitsi Meet and I have found some issues that I would like to share with you.

To the default text I add a list, leave a line as a separator and add a new paragraph:

![etherpad_original](https://cloud.githubusercontent.com/assets/7597354/21754820/d0ea9c58-d5e6-11e6-865c-dd44f92f3677.png)

Conversion to PDF and Word does not seem to respect the separation.

![etherpad_doc_file](https://cloud.githubusercontent.com/assets/7597354/21754847/497a9c22-d5e7-11e6-83f1-6dfecdf43847.png)

![etherpad_pdf_file](https://cloud.githubusercontent.com/assets/7597354/21754863/a1d6ca94-d5e7-11e6-9d72-17f5d8da15b2.png)

In fact, it looks like the missing space below the list, is above the list.

On the other hand, the conversion to ODT did not work for me:

![etherpad_odt_file](https://cloud.githubusercontent.com/assets/7597354/21754958/53774610-d5e9-11e6-8dc3-fba3ff114471.png)

The problem converting to ODT seems to be related to Etherpad, but in the other two cases it seems like a conversion bug with Abiword (I am using the packaged version of Abiword in Debian's Jessie repositories (3.0.0-8 + b1)). I'm using Etherpad version is 1.6.1 (deed74c).

I would like to know what do you think about this and if you observed the same behavior.

I also did the same test with LibreOffice and here all conversions worked, being faithful to the original version in all cases.

![etherpad_doc_filelo](https://cloud.githubusercontent.com/assets/7597354/21755052/6820baa4-d5eb-11e6-88ae-b658bc362bbf.png)

![etherpad_pdf_filelo](https://cloud.githubusercontent.com/assets/7597354/21755056/7427123a-d5eb-11e6-91a7-347ec5a44891.png)

![etherpad_odt_filelo](https://cloud.githubusercontent.com/assets/7597354/21755061/7cbfcc02-d5eb-11e6-8b78-c889dc339336.png)

Also here It catches my eye the link "Javascript license information" (which did not appear with Abiword), but this link is broken.

Thanks in advance for your reply and your time.

Kind regards,
Daniel

**Comment by JohnMcLear** [comment]
This is not a present bug any more
