### ISSUE TITLE
etherpad-lite cannot read property 'dependencies' of undefined

### ISSUE THREAD

**Issue by MonMohonSingha** [ether/etherpad-lite#3117]
please help me to solve this issue.
cannot read property 'dependencies' of undefined
static\js\pluginfw\plugins.js
![epad-error](https://cloud.githubusercontent.com/assets/304477/21850442/9e197f00-d830-11e6-8bd4-cb7e0ea3c5a4.jpg)

**Comment by lpagliari** [comment]
@Gared can this be related to 00c9ca?

**Comment by MonMohonSingha** [comment]
yes......... thank you

**Comment by Gared** [comment]
@lpagliari Yeah, probably.
@MonMohonSingha Which version of windows are you using?

**Comment by MonMohonSingha** [comment]
**windows 7**

not working, lots of error
I tried etherpad 1.6.1 form http://etherpad.org/
not working for me.
i pull from https://github.com/ether/etherpad-lite
error log4js

i'm trying for the last five days still no hope.

can you please send me the link of working version. I need it for my project

Thanks

**Comment by MonMohonSingha** [comment]
windows [version 6.17601]
i install the latest nodejs
npm: 4.0.5
node: 6.6.4

**Comment by lpagliari** [comment]
The previous version (1.6.0) probably won't have this issue, @MonMohonSingha : http://etherpad.org/downloads/etherpad-lite-win-1.6.0-dcfb287990.zip

**Comment by MonMohonSingha** [comment]
thanks again
i'll try and get back to you, if issue found

**Comment by MonMohonSingha** [comment]
thanks a lot

just want to know.
to start etherpad i've to run stat.bat or (node\server.js) every time if so

how to run on host server?

**Comment by lpagliari** [comment]
https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service#windows-nssm
