### ISSUE TITLE
Embedded etherpads don't let 2 people type at once

### ISSUE THREAD

**Issue by dreeves** [ether/etherpad-lite#3124]
This is for Etherpad version 1.6.0 and I believe 1.6.1. Not sure about other versions.

## Steps to reproduce:

1. Get 2 people using Google Chrome or Firefox (or any other browser, presumably).
2. They both load a web page with an embedded (via iframe) Etherpad doc.
3. They both type at the [exact] same time on different lines.

## Expected:

Both people should be able to type and edit to their hearts' delight, the killer feature of Etherpad from day one.

## What happens:

The caret jumps to beginning of line as you type and starts prepending to the line and everything is messed up and teeth are gnashed and tears are shed.

## Debugging hints:

See more detailed testing below. I confirmed that it's fine with the same document loaded directly (not embedded). And it seems to not be specific to the Chrome browser.

UPDATE: Important bit of evidence! The caret jumping around happens specifically to whoever has the document in an iframe. If both users have it embedded in an iframe they'll both have the caret jump around on them. If only one does then only that user will see the bug.

-----

Keywords for future searchers: cursor jumps to start of line, people messing up each other's typing, cursor moves while typing, can't collaborate in real time with embedded pad

**Comment by dreeves** [comment]
UPDATE: This only happens for an embedded etherpad document, ie, in an iframe.

**Comment by dreeves** [comment]
And I've only confirmed this with the Chrome browser.

**Comment by JohnMcLear** [comment]
Are both users (browsers) visiting from different desktops/laptops/whatever or same hardware?

**Comment by dreeves** [comment]
Different hardware. I don't know how to test this with both instances on the same physical computer since step 3 of the steps to reproduce involve typing at the same time.

**Comment by JohnMcLear** [comment]
@dreeves I guess it would be VM's w/ VNC to one VM or something weird..  We see a lot of weird issues...

**Comment by dreeves** [comment]
I see. But, yeah, I think this bug is reproducible for 2 totally normal, separate users. So I think the severity of the bug is high!

**Comment by JohnMcLear** [comment]
Is this bug still an issue?  If so I will re-open but afaik it's closable.

**Comment by dreeves** [comment]
Still reproducible for me! Seems to not depend on what browser you use and it does not require that both users be using an embedded pad -- just one is enough.

## Combinations that exhibited the bug

1. User 1 on Chrome on macOS with embedded etherpad, User 2 on a Chromebook with embedded etherpad.
2. User 1 on Firefox on macOS with embedded etherpad, User 2 on a Chromebook with NON-embedded etherpad.

And a few more that I won't list out unless that would be helpful.

## Combinations that _did not_ exhibit the bug

1. User 1 on Chrome on macOS with normal etherpad, User 2 on a Chromebook with normal etherpad
2. User 1 on Firefox on macOS with normal etherpad, User 2 on a Chromebook with normal etherpad

## Conclusion

This is not browser-specific. Embedding an etherpad in an iframe breaks the ability for people to edit it at the exact same time.

**Comment by JohnMcLear** [comment]
https://youtu.be/_LhJlA77644

I can't replicate.  Chrome, FF, Edge, Opera on Microsoft Windows 10.

I tried an additional test with more spamming on lines and still no dice.  Everything works fine..  Can you record a video showing the problem?

**Comment by dreeves** [comment]
I'm sorry! I should've emphasized, the bug happens when both people are typing literally simultaneously. So you'll need two keyboards to reproduce it! I'd be delighted to coordinate with you by phone/zoom/whatever (or just pick an exact time to do the test!) and be the other user typing at the same time.

**Comment by JohnMcLear** [comment]
It's cool I got people here so will get them to help.

**Comment by JohnMcLear** [comment]
Can't replicate on Windows w/ Chrome and Chrome based browser on a tablet.

Can't replicate on Windows w/ Firefox and Chrome based browser on a tablet.

Tested using: https://unconceivedainudog.htmlpasta.com/

@dreeves Can you test with the above URL please and see if you can replicate there?

**Comment by JohnMcLear** [comment]
Oh for some reason I thought it was disconnecting?! :D  It's a caret jump issue..  Okay lemme try  test that..

**Comment by JohnMcLear** [comment]
Nope, no caret jump.  I did witness a huge amount of latency on the tablet connection (or so it seemed) though..  Poss a socket routing issue?  I don't get the caret jump at all tohugh with my test setup.  What OS do you get the caret jump on, Chrome on MacOS?

**Comment by dreeves** [comment]
Well I'll be darned. It does not happen on unconceivedainudog.htmlpasta.com !
It's sounding like this is something idiosyncratic to my own installation. Let me keep investigating but I think you're right to close this in the meantime. Thanks so much for the thorough testing!
