### ISSUE TITLE
Copy pad causes the pad to load for other user.

### ISSUE THREAD

**Issue by kernelfreak** [ether/etherpad-lite#3125]
Hello friends,

We are using Etherpad for one of our projects and we are facing a problem with copyPad functionality. When we call the function copyPad(padId);, the pad does get copied correctly, but whichever other user is accessing the pad, gets a loading page. Even if the pad is currently opened, they get a loading image.

Is this  a known issue? 

code for copyPad()

 ```
   public void copyPad(String sourcePadId, String destinationPadId){
        this.client.copyPad(sourcePadId,destinationPadId,true);
    }
```

Thank you.

**Comment by lpagliari** [comment]
#3183 is about the same issue, closing this one and keeping the discussion there.
