### ISSUE TITLE
Is there a way to embed a pad's latest revision as static html?

### ISSUE THREAD

**Issue by beppe9000** [ether/etherpad-lite#3127]
Is there a way to embed a pad's latest revision  as readonly static html content in an iframe?
for example <iframe src='www.pads/pad/blabla/latest?view=html'>

**Comment by lpagliari** [comment]
Yes, it is possible. First, you need to get the read-only id for the pad (check [here](http://etherpad.org/doc/v1.6.1/#index_getreadonlyid_padid) how to get it); then you can use that id as the pad id on the URL.

There's a [jQuery plugin](https://github.com/ether/etherpad-lite-jquery-plugin) available for embedding pads, if you want. Or you can customize the appearence with some of the accepted configurations as parameters for the URL (check [here](https://github.com/ether/etherpad-lite/wiki/Embed-Parameters) )

**Comment by beppe9000** [comment]
Thanks! By the way, I assume I need to host my own instance of etherpad lite to have access to an API key?

**Comment by lpagliari** [comment]
Yes. The APIKEY is stored on a file at the root folder of Etherpad instance. If you don't create one, it will generate a random one for you when you first run Etherpad.

**Comment by beppe9000** [comment]
Thanks for the information!
