### ISSUE TITLE
HTML Export exports invalid HTML

### ISSUE THREAD

**Issue by renebrain** [ether/etherpad-lite#3129]
In our project we we're able to "break" the etherpad export to html. We have a testcase put on your server under the following link: [https://beta.etherpad.org/p/bugWithExportBugBug](https://beta.etherpad.org/p/bugWithExportBugBug) 

The Magical Dom gets exported as invalid html. List Elements are floating without an existing ul's and there are some random ul elements hanging around in the html.

Is it a bug in the export oder maybe in the paste functionality? The text was pasted from outlook initially.

**Comment by renebrain** [comment]
Anything?

**Comment by JohnMcLear** [comment]
Confirmed.  Export HTML OL / UL is pretty wildly broken.

https://github.com/ether/etherpad-lite/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+lists

**Comment by JohnMcLear** [comment]
Closed because not specific enough
