### ISSUE TITLE
You do not have permission to access this pad

### ISSUE THREAD

**Issue by rafaelangarita** [ether/etherpad-lite#3130]
Hi, I'm having the following error when embeding EPL in my web application:

Web browser error: 

`You do not have permission to access this pad`

Console error:

`[Error] WebSocket connection to 'wss://myserver.fr/etherpad/socket.io/?EIO=3&transport=websocket&sid=SvHCSd-fomsj1Y0XAAAF' failed: Unexpected response code: 400
`

EPL access log:

`[WARN] message - Authentication try failed:{"component":"pad","type":"CLIENT_READY","padId":"r.3e926ddb032b971ddb872d51f899c17d","sessionID":"null","password":null,"token":"t.ywLvJfUMCICeCIJWi7rh","protocolVersion":2}`

If I go directly to https://myserver.fr/etherpad, http://myserver.fr/etherpad, or https://myserver.fr:9001, it works perfectly.

I have this Apache configuration:

```
<VirtualHost *:443>
        ServerName myserver.fr
        SSLEngine on
        ProxyRequests On
        ProxyPreserveHost On
        DocumentRoot /srv/apache2/htdocs
       
        ProxyPass /etherpad/  http://127.0.0.1:9001/
        ProxyPassReverse /etherpad/  http://127.0.0.1:9001/
       #the  rest of the config....
</VirtualHost>
```

I have another instance of EPL as a subdomain (etherpad.myserver.fr) in another server and it works fine when embedded:

```
<VirtualHost *:443>
        ServerName etherpad.myserver.fr
        SSLEngine on
        ProxyRequests On
        ProxyPreserveHost On
        DocumentRoot /srv/apache2/htdocs
       
        ProxyPass /  http://127.0.0.1:9001/
        ProxyPassReverse /  http://127.0.0.1:9001/
       #the  rest of the config....
</VirtualHost>
```

**Comment by sissieadmin** [comment]
Any details on what resolved this? I am having a similar issue.

**Comment by luixxiul** [comment]
@sissieadmin did you happen to try this guide? https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy
