### ISSUE TITLE
File inconsistence on "push"

### ISSUE THREAD

**Issue by undermink** [ether/etherpad-lite#3132]
When I use the "push" button it always gives me a "File inconsistent with pad content 15281/15280" warning. It is always a offset by 1. Is there a simple way to either fix this or disable that feature?

**Comment by offlinehoster** [comment]
We got the same issue...our etherpad would like to save files to /tmp instead to the database.

Are we missing a setting inside the config? What's the use for "push" ?

**Comment by undermink** [comment]
hmm sorry this seems to be related to the ep_codepad plugin.
changing:
`if (adat !== text.slice(0, -1)) {`
to
`if (adat !== text) {`
in handleButtonMessage.js seems to fix it for me.
[https://github.com/LaKing/ep_codepad/blob/master/handleButtonMessage.js#L108](url)
