### ISSUE TITLE
Exception - g.8gVzfVypiWy4ESNJ$ is not a valid padId

### ISSUE THREAD

**Issue by beerpal243** [ether/etherpad-lite#3133]
Hello, I'm getting an issue trying to use Etherpad-lite in Moodle for the first time.  I can get it to work no problem on its own, but when I try to use it inside moodle, I get a error message saying the following..
Exception - g.8gVzfVypiWy4ESNJ$ is not a valid padId

**Comment by lpagliari** [comment]
@beerpal243 can you give more details about what you've already tried? Like: which steps did you perform? Were you following any instructions about how to use Etherpad + Moodle?

Thanks!

**Comment by beerpal243** [comment]
turns out, I was missing a setting in my moodle configuration for the padName value.  If you don't type anything in, then it will be blank.
