### ISSUE TITLE
Incorrect string value - after upgrade to 1.6.1

### ISSUE THREAD

**Issue by wojtas911** [ether/etherpad-lite#3138]
Hi,
In Issue
#3113 
I did upgrade to lates version to etherpad and in logs i can see:
Feb  9 09:42:03  run.sh[12801]: #033[31m[2017-02-09 09:42:03.565] [ERROR] console - #033[39mError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xC5\x82y\n\...' for column 'value' at row 1
Feb  9 09:42:03  run.sh[12801]:     at Query.Sequence._packetToError (/opt/etherpad/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
Feb  9 09:42:03  run.sh[12801]:     at Query.ErrorPacket (/opt/etherpad/src/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
Feb  9 09:42:03  run.sh[12801]:     at Protocol._parsePacket (/opt/etherpad/src/node_modules/mysql/lib/protocol/Protocol.js:271:23)
Feb  9 09:42:03  run.sh[12801]:     at Parser.write (/opt/etherpad/src/node_modules/mysql/lib/protocol/Parser.js:77:12)
Feb  9 09:42:03  run.sh[12801]:     at Protocol.write (/opt/etherpad/src/node_modules/mysql/lib/protocol/Protocol.js:39:16)
Feb  9 09:42:03  run.sh[12801]:     at Socket.<anonymous> (/opt/etherpad/src/node_modules/mysql/lib/Connection.js:82:28)
Feb  9 09:42:03  run.sh[12801]:     at emitOne (events.js:96:13)
Feb  9 09:42:03  run.sh[12801]:     at Socket.emit (events.js:188:7)
Feb  9 09:42:03  run.sh[12801]:     at readableAddChunk (_stream_readable.js:176:18)
Feb  9 09:42:03  run.sh[12801]:     at Socket.Readable.push (_stream_readable.js:134:10)
Feb  9 09:42:03  run.sh[12801]:     --------------------
Feb  9 09:42:03  run.sh[12801]:     at Protocol._enqueue (/opt/etherpad/src/node_modules/mysql/lib/protocol/Protocol.js:135:48)
Feb  9 09:42:03  run.sh[12801]:     at Connection.query (/opt/etherpad/src/node_modules/mysql/lib/Connection.js:185:25)
Feb  9 09:42:03  run.sh[12801]:     at /opt/etherpad/src/node_modules/ueberdb2/mysql_db.js:214:18
Feb  9 09:42:03  run.sh[12801]:     at /opt/etherpad/src/node_modules/ueberdb2/node_modules/async/lib/async.js:462:21
Feb  9 09:42:03  run.sh[12801]:     at /opt/etherpad/src/node_modules/ueberdb2/node_modules/async/lib/async.js:194:13
Feb  9 09:42:03  run.sh[12801]:     at /opt/etherpad/src/node_modules/ueberdb2/node_modules/async/lib/async.js:97:13
Feb  9 09:42:03  run.sh[12801]:     at Array.forEach (native)
Feb  9 09:42:03  run.sh[12801]:     at _forEach (/opt/etherpad/src/node_modules/ueberdb2/node_modules/async/lib/async.js:26:24)
Feb  9 09:42:03  run.sh[12801]:     at async.forEach (/opt/etherpad/src/node_modules/ueberdb2/node_modules/async/lib/async.js:96:9)
Feb  9 09:42:03  run.sh[12801]:     at _asyncMap (/opt/etherpad/src/node_modules/ueberdb2/node_modules/async/lib/async.js:193:9)
Feb  9 09:42:03  run.sh[12801]: #033[32m[2017-02-09 09:42:03.565] [INFO] console - #033[39mgraceful shutdown...
Feb  9 09:42:06  systemd[1]: etherpad.service: Main process exited, code=exited, status=1/FAILURE

Feb  9 10:41:34 kameleon run.sh[2453]: #033[33m[2017-02-09 10:41:34.050] [WARN] console - #033[39mError: Can't apply USER_CHANGES Z:w<a-b*0+1$S with oldLen 32 to document of length 22
Feb  9 10:41:34 kameleon run.sh[2453]:     at /opt/etherpad/src/node/handler/PadMessageHandler.js:770:25
Feb  9 10:41:34 kameleon run.sh[2453]:     at /opt/etherpad/src/node_modules/async/lib/async.js:610:21
Feb  9 10:41:34 kameleon run.sh[2453]:     at /opt/etherpad/src/node_modules/async/lib/async.js:249:17
Feb  9 10:41:34 kameleon run.sh[2453]:     at iterate (/opt/etherpad/src/node_modules/async/lib/async.js:149:13)
Feb  9 10:41:34 kameleon run.sh[2453]:     at /opt/etherpad/src/node_modules/async/lib/async.js:160:25
Feb  9 10:41:34 kameleon run.sh[2453]:     at /opt/etherpad/src/node_modules/async/lib/async.js:251:21
Feb  9 10:41:34 kameleon run.sh[2453]:     at /opt/etherpad/src/node_modules/async/lib/async.js:615:34
Feb  9 10:41:34 kameleon run.sh[2453]:     at Object.async.whilst (/opt/etherpad/src/node_modules/async/lib/async.js:686:13)
Feb  9 10:41:34 kameleon run.sh[2453]:     at /opt/etherpad/src/node/handler/PadMessageHandler.js:719:13
Feb  9 10:41:34 kameleon run.sh[2453]:     at /opt/etherpad/src/node_modules/async/lib/async.js:610:21
Feb  9 10:41:34 kameleon run.sh[2453]: #033[32m[2017-02-09 10:41:34.052] [INFO] ueberDB - #033[39mFlushed 1 values

run.sh[634]: #033[32m[2017-02-09 09:42:23.397] [INFO] console - #033[39mYour Etherpad version is 1.6.1 ()

**Comment by lpagliari** [comment]
Please take a look on #2651 for instructions on how to fix your issue.
