### ISSUE TITLE
Get <TypeError: Cannot read property 'language' of undefined>

### ISSUE THREAD

**Issue by pageye123** [ether/etherpad-lite#3139]
I did all what the [installation](https://github.com/ether/etherpad-lite#installation) says.

however, after inputting user name and clicking OK button on the portal screen,I get `TypeError: Cannot read property 'language' of undefined`. like this:
![image](https://cloud.githubusercontent.com/assets/11813936/22981136/86861dbe-f3d6-11e6-81bc-5c41814d48b2.png)

my node version `is  v6.9.2`.
my `etherpad` git cloned with the branch `develop`,  [the version](https://github.com/ether/etherpad-lite/commit/203a48b42d988e172006b1b6efad9914cad56734) in specific.

google but without any effective answser! what's the matter? Is some configuration ignored?

------------------------
added at 2017-2-15
I think the Error may concern this ：`Cannot find module 'ep_etherpad-lite/node_modules/express-session`(when I run start.bat, it happens)
![errors](https://cloud.githubusercontent.com/assets/11813936/23000238/9802037a-f41a-11e6-8ac2-5cbfbf4776f2.png)

however,the module `express-session` surely exist:
![express-session](https://cloud.githubusercontent.com/assets/11813936/23002076/ad60a6dc-f423-11e6-9c57-d4a2334b36ad.png)

well, [indows 1.6.1 download](http://etherpad.org/#download) is OK,but I switch branch to 'release/1.6.1 ', it shows the same errors.

**How can I fix it?**

**Comment by lpagliari** [comment]
@pageye123 it looks like [`req.cookies` is not set](https://github.com/ether/etherpad-lite/blob/203a48b42d988e172006b1b6efad9914cad56734/src/node/hooks/express/specialpages.js#L46): 

```
line 46: if (req.cookies.language === undefined)
```

Does that give you any hint?

**Comment by pageye123** [comment]
I know what's it! 
The key Error is `Can't find module: etherpad-lite/node_modules/express-session` which remind me to npm install

so，we should `npm install` in `*/etherpad-lite/node_modules/ep_etherpad-lite`
