### ISSUE TITLE
Can't create or join (for new users) a pad some time after server start

### ISSUE THREAD

**Issue by ent-mtp** [ether/etherpad-lite#3140]
### Context
Etherpad is running on an application server and is connected to a postgres database running on another server.

### Issues
The problems I encounter is that about 2 hours after starting etherpad:
1. No user can create a new pad
1. Users with unregistered cookies cannot join an existing pad

Note: Users with registered cookies can still access to the existing pads and edit them.

#### App server
CentOS 6.5
node 6.3.0
npm 3.10.3
etherpad 1.6.0

#### DB server
CentOS 6.3
Postgres 9.1

### Configuration
Available at [http://pastebin.com/QAt1wBVA](http://pastebin.com/QAt1wBVA)

**Comment by JohnMcLear** [comment]
This sounds like an ueberDB related issue where it isn't keeping connection to the Postgres server.  Please file the issue with ueberDB.
