### ISSUE TITLE
Toolbar settings in settings.json have no effect

### ISSUE THREAD

**Issue by notnow123** [ether/etherpad-lite#3143]
I am using 1.6.1. 

Editing the toolbar section of settings.json in order to remove some buttons from the pad toolbar and restarting has no effect.

All buttons are still visible.

**Comment by lpagliari** [comment]
Hum, I can't reproduce the issue here... Did you uncomment the lines where toolbar is defined? [They are all commented out](https://github.com/ether/etherpad-lite/blob/develop/settings.json.template#L150-L167) on the generated `settings.json`
