### ISSUE TITLE
How can I butt my users

### ISSUE THREAD

**Issue by hanwenbo** [ether/etherpad-lite#3145]
I see the sessionid problem in the document mentioned t replace the cookies is no cookies sessionid, what do I need to change

**Comment by hanwenbo** [comment]
还有，这俩程序不在一个域名下，跨域替换不太合适吧

**Comment by hanwenbo** [comment]
官网文档有点简陋，我建议好好写一下。

**Comment by hanwenbo** [comment]
createAuthor 卵用木有，因为我接口创建  你的web再创建一遍 等于是两个 那么没有任何意义

**Comment by hanwenbo** [comment]
我感觉哈你的文档写的不对，你大概的意思是先拿到cookie的token，然后获得authorID，再拿authorID创建sessionID存入到cookie里，这样才能绕过你的限制，如果这么说是正确的。。。那你的文档写的就有问题，我不知道authourID我怎么创建session，我创建了也没用的

**Comment by lpagliari** [comment]
This might help: https://translate.google.com/

**Comment by hanwenbo** [comment]
How to get the current user's author ID

**Comment by hanwenbo** [comment]
其他应用如果获得当前用户的authorID

**Comment by hanwenbo** [comment]
Other applications if the current user's authorID

**Comment by hanwenbo** [comment]
xxx.domain.com   want  to get    etherpad.domain.com 's  current user's authorID

**Comment by hanwenbo** [comment]
我在xxx.domain.com调用etherpad.domain.com的接口，想影响etherpad.domain.com的当前authorid，可是无效

**Comment by hanwenbo** [comment]
I call etherzer.domain.com in xxx.domain.com and want to affect the current authorid of etherpad.domain.com, but it is invalid

**Comment by hanwenbo** [comment]
My main purpose is to achieve two applications of user information synchronization

**Comment by hanwenbo** [comment]
I do not know if the document is wrong, my idea is this, through the etherpad-lite api interface to create a mapping authorID, and then create the groupID corresponding to the authorID session, so that users can access the pad, but I so Dry, open the pad you will find the current authorID is still created by the system, through the cookie token, you can go to the database to find the authorID, and I created through the interface authorID does not match, perhaps I understand the wrong interface, Hope to find a solution. Thank you, hope someone can help me

**Comment by hanwenbo** [comment]
Has been solved, can change the sessionID switching users

**Comment by pageye123** [comment]
@hanwenbo I met the same question. Please tell me how u solve the problem? Although I set the sessionID in the cookie, but when I entered the etherpad iframe, the etherpad created it's own authorID(according to the client,which means different client is different author)
