### ISSUE TITLE
Where is the configuration of cookie scope?

### ISSUE THREAD

**Issue by hanwenbo** [ether/etherpad-lite#3146]
Where is the configuration of cookie scope?

**Comment by hanwenbo** [comment]
How to update the etherpad under other domain name under the domain of the session

**Comment by hanwenbo** [comment]
how to renew sessionID?

**Comment by hanwenbo** [comment]
https://github.com/ether/etherpad-lite/issues/2934   I met problems and this person should be the same

**Comment by lpagliari** [comment]
I am closing this issue and keeping #2934 opened, as they are the same. Let me know if this is a different issue, and I will reopen it.
