### ISSUE TITLE
29G dirtyDB has been unable to start

### ISSUE THREAD

**Issue by hanwenbo** [ether/etherpad-lite#3148]
![image](https://cloud.githubusercontent.com/assets/5869741/23595776/744ec0be-025f-11e7-8016-fe42743a882e.png)

**Comment by hanwenbo** [comment]
If I change a little can open

**Comment by hanwenbo** [comment]
What should I do?The background now also can't open it Want to delete some data

**Comment by hanwenbo** [comment]
The content of the test is too much...

**Comment by lpagliari** [comment]
https://github.com/felixge/node-dirty#dirtyrmkey-cb

**Comment by hanwenbo** [comment]
Settled, I put the 29G dirtyDB files, downloaded from the server, use my MAC, it took just six minutes to open.Performance may be apple's read too well
![image](https://cloud.githubusercontent.com/assets/5869741/23637608/a02ad7f0-0317-11e7-9ea0-c00993f89d05.png)
Don't know me so others will meet a large number of tests, also can solve this

**Comment by lpagliari** [comment]
@hanwenbo can this issue be closed, then?

**Comment by hanwenbo** [comment]
@lpagliari can
