### ISSUE TITLE
TypeError: callbak is not a function

### ISSUE THREAD

**Issue by dam660** [ether/etherpad-lite#3152]
Hi there,

I just got a bug on my etherpad container yesterday.
Here is the log i got: 

`[2017-03-21 14:14:16.620] [ERROR] console - TypeError: callback is not a function
    at /var/etherpad-renater/src/node/utils/ExportHtml.js:503:9
    at /var/etherpad-renater/src/node/utils/ExportHtml.js:66:5
    at /var/etherpad-renater/src/node/utils/ExportHtml.js:58:5
    at fn (/var/etherpad-renater/src/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/var/etherpad-renater/src/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
`

In the end, my container stopped.
I don't know what happened, is this bug already identified?

Tank's for all :)

**Comment by lpagliari** [comment]
@dam660 can you give us more information about your Etherpad instance? Which version were you running? Linux, Windows? Did you try to export via API or on the browser?

Thanks!

**Comment by dam660** [comment]
I'm running EtherpadLite threw a Docker container (Linux), and the version runinng is 1.6.1.

If it can helps, here is the plugin list I installed:

`[2017-03-22 10:22:33.185] [INFO] console - Installed plugins: ep_align@0.0.23, ep_better_pdf_export@0.0.3, ep_comments_page@0.0.35, ep_copy_paste_select_all@0.0.4, ep_font_color@0.0.11, ep_font_family@0.2.7, ep_font_size@0.1.11, ep_headings2@0.0.9, ep_horizontal_line@0.0.4, ep_line_height@0.0.4, ep_mammoth@0.0.7, ep_markdown@0.0.10, ep_monospace_default@0.0.3, ep_page_view@0.5.23, ep_print@0.0.9, ep_spellcheck@0.0.3, ep_subscript_and_superscript@0.0.3, ep_table_of_contents@0.1.15, ep_unoconv@0.0.1
`
In fact the container totally stopped, so neither the API or the interface were accessible ...

Thank's for help!

**Comment by lpagliari** [comment]
Thanks, @dam660 . Regarding the API, I was referring to the moment when Etherpad crashed. According to the logs you've sent, you were exporting a pad, right? Were you doing that on the browser or the API?

**Comment by dam660** [comment]
Ho, i undestrand what you mean.

Unfortunately I can't know this. 
I developped a website wich allows my users to list, create, update, export or delete their own pads.
This is based on the EtherpadLite API.

So my users have two ways to export their pads: 

- Straightly from the EtherpadLite interface
- With this website I developped

So well, I guess it was exported from my website (so via the API), but i'm not sure :/

**Comment by dam660** [comment]
Hello!

I had some time to work on it.

So I found something: when you select "export" then "PDF" in the interface, a proxy error is shown and the Etherpad container dies (the log of the container says "TypeError: callback is not a function at....").

Maybe there is something here?

**Comment by JohnMcLear** [comment]
Caused by a plugin
