### ISSUE TITLE
No export possible when using read-only ID

### ISSUE THREAD

**Issue by jrocho** [ether/etherpad-lite#3154]
I'm embedding Etherpads with the read-only ID. When I display the import/export button it does not show the import/upload dialog (as expected) but it show the export links. If I click on a link I get a "403 - Can't touch this" from the Etherpad server. I think it still should be possible to export and Etherpad when using read-only as this is also just a read operation.

**Comment by JohnMcLear** [comment]
I just tested this and it worked..

**Comment by JohnMcLear** [comment]
@jrocho are you still getting this problem?  If so, let me know and I will re-open this issue..  For me it works as expected (export works fine from a read only pad)

**Comment by stanley89** [comment]
I am having similar problem on current etherpad version. Read-only export returns default pad text

https://pad.pirati.cz/p/r.08b4e397ab943b83dda649e3621a61f9
```
Příliš žluťoučký kůň úpěl ďábelské ódy.
```


https://pad.pirati.cz/p/r.08b4e397ab943b83dda649e3621a61f9/export/txt
```
Welcome to Etherpad!

This pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents!

Get involved with Etherpad at http://etherpad.org

```

**Comment by Bergiu** [comment]
I have the same problem

**Comment by JohnMcLear** [comment]
@Bergiu please provide details.
 https://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/

**Comment by fortuna** [comment]
This is still a problem. For example, here is an editable pad:
https://etherpad.wikimedia.org/p/6qOCyhue3ewXrvjZnf2d

You can export to text fine:
https://etherpad.wikimedia.org/p/6qOCyhue3ewXrvjZnf2d/export/txt

This is the read-only version of the same pad:
https://etherpad.wikimedia.org/p/r.fc667082410bef6063769e4f6c39bc06

This is the export link:
https://etherpad.wikimedia.org/p/r.fc667082410bef6063769e4f6c39bc06/export/txt

When you open that, you get an error:
![image](https://user-images.githubusercontent.com/113565/92531251-e936f600-f1fb-11ea-8a48-36bae76e1c68.png)

With curl:
```
$ curl https://pad.riseup.net/p/r.0ad03f77ca2c6c5811d53759e596911c/export/txt
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /p/r.0ad03f77ca2c6c5811d53759e596911c/export/txt</pre>
</body>
</html>
```

This happens for multiple installations of Etherpad found at https://github.com/ether/etherpad-lite/wiki/Sites-that-run-Etherpad-Lite

**Comment by JohnMcLear** [comment]
https://video.etherpad.com/p/r.2bf9e8f549026ecfc46c7b2b86936563 clicking export 404s.

Feck

**Comment by JohnMcLear** [comment]
I thought we had test coverage in for this too ;\, my bad.

@webzwo0i any chance you can take a stab at this one as it needs test coverage.

**Comment by webzwo0i** [comment]
I'll try. Stuff on my etherpad list increases, but I have more time the next weeks

**Comment by JohnMcLear** [comment]
Tnx @webzwo0i
