### ISSUE TITLE
Able to access group pads without a valid session

### ISSUE THREAD

**Issue by pauldatta** [ether/etherpad-lite#3156]
The [API](http://etherpad.org/doc/v1.5.1/#index_session) and [the examples](http://etherpad.org/doc/v1.5.7/#index_examples) state that a session cookie on the client is required to allow for authenticated user access to Group Pads. 
I am able to open and even edit a group pad via its URL without being an authenticated user (almost like the pad is public). Is there a way to configure Etherpad such that only users with either a valid session cookie or accessing a group pad via a [special URL](https://www.npmjs.com/package/ep_auth_session) have access to a pad?

**Comment by pauldatta** [comment]
Found out that Etherpad does not map group_id with author_id internally which means that this has to be managed elsewhere like within the Etherpad API calling app for example.

**Comment by lpagliari** [comment]
Hum, interesting... Tks, @pauldatta
