### ISSUE TITLE
`make` command triggered in cmd has wrong

### ISSUE THREAD

**Issue by pageye123** [ether/etherpad-lite#3158]
I want to make the markdown docs into purely html.

In the root directory of the project, I executed `make` in cmd, but it unreached the expected effect.The `out\doc\api` is still empty (^_^)

But I surely have the `bin/bash`, I don't know what's wrong with it?

And my systme is window7, 64bit, with the tool git bash.

the following is what I do:
![image](https://cloud.githubusercontent.com/assets/11813936/24594828/6b7c8966-1863-11e7-9a0e-18cc78a52e8c.png)
![image](https://cloud.githubusercontent.com/assets/11813936/24594833/74b80154-1863-11e7-9970-62664bf28127.png)

**Comment by lpagliari** [comment]
You don't need to run `make` to install Etherpad (see installation instructions [here](https://github.com/ether/etherpad-lite#installation)).

As per [the other issue you've recently closed](https://github.com/ether/etherpad-lite/issues/3139#issuecomment-291069776), I'm assuming you'd already figured out how to fix your installation, right? If that is not the case, please let me know and I'll reopen this issue.

**Comment by pageye123** [comment]
@lpagliari  sorry,but I'm not mean to install Etherpad. I just want to transfer all the *.md files in /doc to *.html and I got trouble doing that.
so please do me a favor~ ^_^

**Comment by lpagliari** [comment]
My bad, I didn't understand what you were trying to do.

On [the README of `doc/`](https://github.com/ether/etherpad-lite/tree/423d8e584eaf3ecc47c9d166cf3b695952293069/bin/doc#cli-usage) I've found this:

```
node tools/doc/generate doc/index.md --format=html --template=doc/template.html > out.html
```

Could you try to run this command and see if it works, please?

**Comment by pageye123** [comment]
@lpagliari  well it helps~
Finally the out.html comes out .

but the CLI should be 
`node bin/doc/generate doc/index.md --format=html --template=doc/template.html > out.html`
I think it should be revised.

however, I am still curious about the make command~

**Comment by lpagliari** [comment]
@pageye123 would you mind sending us a PR with that fix?

**Comment by pageye123** [comment]
@lpagliari sure, of course~https://github.com/ether/etherpad-lite/pull/3160
