### ISSUE TITLE
Login error in ep_user_pad_frontend

### ISSUE THREAD

**Issue by pajaro23** [ether/etherpad-lite#3159]
Hi.
I find myself using the ep_user_pad_frontend plugins but I noticed that ultimante does not allow the user to login so that it can be logged in, the etherpad must be rebooted, the terminal does not send me any type of error to base myself. Someone has gone through a similar situation.

**Comment by lpagliari** [comment]
@pajaro23 this seems to be an issue with the plugin, not Etherpad.

- Is there any error message on the _browser console_ (not Etherpad)?
- Did you follow [all the steps for the installation of the plugin](https://github.com/aoberegg/ep_user_pad_frontend/blob/master/installation.pdf)?

**Comment by pajaro23** [comment]
Does not send me any type of error in the administration console of etherpad and if I followed all the steps.
