### ISSUE TITLE
Not fire “acePostWriteDomLineHTML” when delete one domline

### ISSUE THREAD

**Issue by EricTiger1986** [ether/etherpad-lite#3166]
I am coding a plugin. I find if I enter "Enter", new domline will be created and "acePostWriteDomLineHTML" will be fired. But when I delete one domline, nothing happened.

Who can help me? Is there any other hooks when deleting one domline?

**Comment by lpagliari** [comment]
Unfortunately there is none, as far as I can tell.

When a line is deleted the hook `aceEditEvent` is triggered, but it is also triggered when other actions happened, so you need to filter those other actions.

BTW: `acePostWriteDomLineHTML` is called whenever a line needs to be re-written on editor, not only when the line is created. Ex: when you type something, when you add bold to part of the line, etc.

**Comment by EricTiger1986** [comment]
Thank you for your help.
