### ISSUE TITLE
Cursor blinking closes dropdown

### ISSUE THREAD

**Issue by renebrain** [ether/etherpad-lite#3167]
In IE11 the blinking cursor is always closing the dropdown menus when the cursor is blinking up. This way the user never has a chance to make a selection in the dropdown. Any ideas what the issue might be here?

Gif with the issue is attached ;)

![test](https://cloud.githubusercontent.com/assets/9963399/24997273/54db9ef6-2036-11e7-8d1f-030efd10d0d7.gif)

**Comment by lpagliari** [comment]
@renebrain does that happen when you open the "Language" dropdown on the pad settings?

**Comment by renebrain** [comment]
Yes it does.

**Comment by JohnMcLear** [comment]
Can't replicate in Edge.  Don't wanna sink resources into IE* really..
