### ISSUE TITLE
Heads up: Html10n.js got an update

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#3174]
Hey,

I know I've not been very caring with this particular creation of mine, but I just wanted to let you know, that I've pushed a few updates to github, that you might want to have: https://github.com/marcelklehr/html10n.js
(Perhaps you have already made your own adjustments, though, so this might become a bit tricky.. Feel free to ask if you need help.)

Cheers,
Marcel

**Comment by lpagliari** [comment]
@marcelklehr There are basically 2 differences between your repo and the file we have here:

- https://github.com/ether/etherpad-lite/commit/d7a181be677362dd993c91e6f57fc51803439cb9 uses a clearer way to handle errors when `console` is not defined. Do you want me to submit a PR with this change?

- https://github.com/ether/etherpad-lite/commit/90575064a9367141d570e641933abee0678d1600 sets the `aria-label` for all translated elements. This might be too far from what `html10n` was created for, but if you want me to submit a PR with the change, I can do that too.

Cheers!

**Comment by marcelklehr** [comment]
Hey @lpagliari ! :)

d7a181b overrides the global console object, which I find problematic, even if it's not defined. If the newly defined console object was local-only in scope, I'd accept this.

9057506 seems like a good solution.

**Comment by lpagliari** [comment]
> d7a181b overrides the global console object, which I find problematic, even if it's not defined. If the newly defined console object was local-only in scope, I'd accept this.

Do you mean something like this: `var console = window.console || {};`, instead of `var console = (window.console = window.console || {});`?

**Comment by marcelklehr** [comment]
Exactly. Only, the wrapping function confines the variable so the actual html10n.js code won't be able to access it, unless it's returned or the wrapper function removed. Feel free to submit a pr. If you'd like me to do this instead, just let me know. :)

**Comment by lpagliari** [comment]
@marcelklehr I've just created the PR: https://github.com/marcelklehr/html10n.js/pull/20. I wasn't able to test it with Etherpad because it looks like the latest version on html10n.js breaks something on Etherpad (I testes with Brazilian Portuguese -- `pt-br` --, and lots of keys could not be found). Maybe it's something we're doing on our side, like not using `br` in uppercase, as it is usual...

I'll close this issue for now, as there is a newer one regarding the same thing (#3244).

**Comment by marcelklehr** [comment]
Mh. weird

**Comment by JohnMcLear** [comment]
*Bump @marcelklehr

**Comment by marcelklehr** [comment]
Ah, totally forgot about this! Thanks for the nudge john :)
