### ISSUE TITLE
Feature request: Delete version

### ISSUE THREAD

**Issue by jekuno** [ether/etherpad-lite#3175]
As a user I want to delete a version (part of a history) if I accidentally added private/secret content to a wrong pad (e.g. by accidentally pasting private content from the clipboard).
It would be even better if users could also choose to delete a range of versions or even the whole history.

**Comment by FredMa01** [comment]
Is there a plugin to delete versions ?

**Comment by JohnMcLear** [comment]
If you paste a password by mistake it's in the memory/database/changesets/socket messages/everyone else who was on the Pads PC et al.  

You would need to ask an admin to revert the padId revision to a prior revision.  Only an admin would ever have this authority else it could be easily abused and would break the core deliverable of Etherpad which is true document fidelity.  

A user can never rewrite history and it would only serve of an illusion of security (as is the case of pasting your password anywhere) if they did so..

Sorry.
