### ISSUE TITLE
Plug Ins wont load

### ISSUE THREAD

**Issue by pipoweruser2019** [ether/etherpad-lite#3176]
Hi there ive tried to install several plugins using npm and supposedly it does load them. I looked in the log and dont see any errors. It simply doesnt display anything in the front page. The last plug in i used was past-lister with no success

**Comment by lpagliari** [comment]
Did you restart Etherpad? New plugins installed out of the /admin page won't be loaded until Etherpad is restarted (as far as I know)

**Comment by pipoweruser2019** [comment]
yes i have, ive reset the server several times

**Comment by lpagliari** [comment]
Ok, so let's try to get more info here: 

* Which OS are you using?
* Could you set the log level on your `settings.json` to `DEBUG` and paste here the output, please?

Tks
