### ISSUE TITLE
Support for ReplicaSet with MongoDB

### ISSUE THREAD

**Issue by magicbelette** [ether/etherpad-lite#3177]
I don't find a way to configure access to replicaset with mongodb as backend.

Is it possible and how ?

Cheers

**Comment by lpagliari** [comment]
I've submitted [a PR to ueberDB](https://github.com/Pita/ueberDB/pull/95) some days ago to enable this, but it was not approved yet.

**Comment by lpagliari** [comment]
When the PR is approved and ueberDB version on Etherpad is upgraded, you should define an `url` attribute on  `settings.json` according to the [mongodb docs](https://docs.mongodb.com/manual/reference/connection-string/):

> To describe a connection to a replica set named test, with the following mongod hosts:
> 
> db1.example.net on port 27017 and
> db2.example.net on port 2500.
> You would use a connection string that resembles the following:
> 
> mongodb://db1.example.net,db2.example.net:2500/?replicaSet=test

Your `settings.json` might be similar to this:

```
  "dbSettings" : {
                    "url": "mongodb://db1.example.net,db2.example.net:2500/?replicaSet=test",
                    "extra": {
                      "replset": {
                        (...)
                      }
                    }
                 },
```

For values on `replset: {...}`, take a look on the [`MongoClient` doc](http://mongodb.github.io/node-mongodb-native/2.0/api/MongoClient.html#.connect) -- note that ueberDB uses v.2.0, not v.2.2, so make sure you're reading the correct version of the mongodb for node.

**Comment by magicbelette** [comment]
Nice work !

**Comment by JohnMcLear** [comment]
@lpagliari did this land?
