### ISSUE TITLE
PostgreSQL MD5 authentication does not work

### ISSUE THREAD

**Issue by gracinet** [ether/etherpad-lite#3180]
Hi,

the current version of ueberdb shipping with etherpad-lite (4.3.0) itself bundles a version of the PostgreSQL client library (pg) that doesn't handle MD5 authentication (the most common password-based auth) properly.

There's a [PR on ueberdb for that](https://github.com/Pita/ueberDB/pull/93). Once it is merged (or the problems are solved in another way), bumping ueberdb would solve the issue in etherpad-lite

So this issue is for later reference, thanks !

**Comment by grinapo** [comment]
(same as #3128 ? is there any way to permanently fix it? editing the file vanishes on updates... I ain't no familiar w/npm.)
