### ISSUE TITLE
Client with copied pad receives a "pad deleted" message

### ISSUE THREAD

**Issue by lpagliari** [ether/etherpad-lite#3183]
How to reproduce:

- open a browser with a pad
- call the api to copy the pad
- result: a message is displayed on the browser saying the pad was removed

[Code](https://github.com/ether/etherpad-lite/blob/develop/src/node/db/Pad.js#L467-L469) that makes this happen:
```
Pad.prototype.copy = function copy(destinationID, force, callback) {
(...)
  //kick everyone from this pad
  // TODO: this presents a message on the client saying that the pad was 'deleted'. Fix this?
  padMessageHandler.kickSessionsFromPad(sourceID);
```

Does anybody know if there was a reason for `Pad.prototype.copy` to call `kickSessionsFromPad`? It does not make sense to me at all. I suspect that `Pad.prototype.copy` code was based on `Pad.prototype.remove`, and in this case it makes total sense to tell clients the pad is no longer available. But for copy...

I'll implement a fix for this, unless someone gives a good reason to kick everyone from the copied pad.

**Comment by renebrain** [comment]
#3125 was excactly this problem, solved it back then, by ignoring that message.

**Comment by lpagliari** [comment]
Great, @renebrain , I'll close #3125 then.
