### ISSUE TITLE
adding support for pdf and jpg upload

### ISSUE THREAD

**Issue by djboidash** [ether/etherpad-lite#3186]
good day guys.

how do i add support for *.jpg & *.pdf files (upload)

Regards
Dash

**Comment by jdittrich** [comment]
As far as Ia am concerned you can combine [ep_fileupload](https://www.npmjs.com/package/ep_fileupload) and [ep_previewimages](https://www.npmjs.com/package/ep_previewimages); Both should be available in the admin UI.

**Comment by lpagliari** [comment]
Thanks, @jdittrich !
