### ISSUE TITLE
CORS when using Etherpad API

### ISSUE THREAD

**Issue by ToniIltanen** [ether/etherpad-lite#3189]
(Etherpad on port 3001, web application on port 8080)

I have the actual client which runs along etherpad listening also on localhost, but i get this issue:

XMLHttpRequest cannot load http://127.0.0.1:3001/api/1.2.12/createGroupIfNotExistsFor?apikey=foo&groupMapper=bar The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

How can i solve this, ep_etherpad-lite -module already has a :
res.header("Access-Control-Allow-Origin", "*");
in the ep_etherpad-lite/node/hooks/express.js

**Comment by JohnMcLear** [comment]
Looks like you are not doing the JSONP GET request properly.

**Comment by ToniIltanen** [comment]
the actual problem was with the etherpad client which was in use, which had to have a withCredentials: false parameter set to allow wildcards in cors.
