### ISSUE TITLE
Log Etherpad-lite Error: listen EADDRINUSE 0.0.0.0:9001 

### ISSUE THREAD

**Issue by DCOATOS** [ether/etherpad-lite#3190]
Hello,
I have this in etherpad.log :

[31m[2017-05-11 10:51:39.791] [ERROR] console - [39mError: listen EADDRINUSE 0.0.0.0:9001
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
[32m[2017-05-11 10:51:39.791] [INFO] console - [39mgraceful shutdown...
[32m[2017-05-11 10:51:39.792] [INFO] console - [39mdb sucessfully closed.
RESTART!
[32m[2017-05-11 10:51:41.169] [INFO] console - [39mInstalled plugins: 
[32m[2017-05-11 10:51:41.172] [INFO] console - [39mReport bugs at https://github.com/ether/etherpad-lite/issues

The crontab is this :
0 7 * * * nohup /bin/sh /opt/etherpad-lite/bin/cron.sh /var/log/etherpad/etherpad_$(date +\%A).log 
0 13 * * * nohup /bin/sh /opt/etherpad-lite/bin/cron.sh /var/log/etherpad/etherpad_$(date +\%A).log &
0 17 * * * nohup /bin/sh /opt/etherpad-lite/bin/cron.sh /var/log/etherpad/etherpad_$(date +\%A).log &

cron.sh : 
PATH=/usr/local/bin:$PATH
SHUTDOWN_WAIT=10
LOG="$1"

echo "[cron.sh : $(date +\%F_\%R)]" >> $LOG

cd /opt/etherpad-lite/bin
/bin/sh stop.sh >> $LOG

let kwait=$SHUTDOWN_WAIT
count=0;
until [ $count -gt $kwait ]
do
    sleep 1
    let count=$count+1;
done

/bin/sh safeRun.sh $LOG –root

stop.sh :
pid=`ps -ef | grep "ep_etherpad-lite/node/server.js" | grep -v grep | awk '{print $2}'`
pid2=`ps -ef | grep "/bin/sh safeRun.sh" | grep -v grep | awk '{print $2}'`

SHUTDOWN_WAIT=10

if [ -n "$pid" ]
then
    echo "Stopping Etherpad : $pid"
    kill -9 $pid
    
    if [ -n "$pid2" ]
    then
        echo "Stopping safeRun.sh : $pid"
        kill -9 $pid2
    fi
    
    let kwait=$SHUTDOWN_WAIT
    count=0;
    until [ $count -gt $kwait ]
    do
        sleep 1
        let count=$count+1;
    done
    
    echo "Etherpad stopped.";

else
    echo "Etherpad is not running\n"
fi

Thank you for the analysis.

**Comment by lpagliari** [comment]
> `EADDRINUSE 0.0.0.0:9001`

It seems that the Etherpad server is still on. Are you sure Etherpad is being shutdown by `stop.sh`?

**Comment by DCOATOS** [comment]
Thank you for the reply. We control.
