### ISSUE TITLE
How to edit homepage?

### ISSUE THREAD

**Issue by Nic321** [ether/etherpad-lite#3192]
Hey guys, I'm using the Arch AUR repo, how do I edit my etherpad landing/homepage? I'd like to simply add a background image. Which file(s) should I be modifying?

**Comment by lpagliari** [comment]
@Nic321 The HTML is [here](https://github.com/ether/etherpad-lite/blob/develop/src/templates/index.html), but the best place to customize styles is on the [custom static files](https://github.com/ether/etherpad-lite/blob/7ecf240d9e46ac41259100bf83242ca7b8fc205b/doc/custom_static.md#L5)
