### ISSUE TITLE
start etherpad lite instance with different settings?

### ISSUE THREAD

**Issue by hajika** [ether/etherpad-lite#3194]
Is it possible to start a second etherpad lite instance with a different settings.json? I want to have a public etherpad and one hidden behind apache authentication. Do I have to run a completely new source instance (and src-folder) or is it possible to use the same source but a second instance with other settings on another port?

**Comment by lpagliari** [comment]
You can specify which file to be used as `settings.json`: https://github.com/ether/etherpad-lite/wiki/Getting-to-know-the-tools-in-bin#runsh
```
bin/run.sh --settings /home/etherpad/thatSettingsFile.json
```
