### ISSUE TITLE
ubuntu 16.04 - Etherpad like a service

### ISSUE THREAD

**Issue by Spartacus2018** [ether/etherpad-lite#3198]
Hello, 

well i m using ubuntu 16.04 etherpad works cool, but i have to start it with command line : 

`sudo /opt/etherpad/etherpad-lite/bin/run.sh --root`

so if i close my ssh session etherpad closed.

so now i m looking how start it like a service : 

So first i create this files : 

`sudo nano /etc/systemd/etherpad-lite.service`

```
[Unit]
Description=Etherpad-lite, the collaborative editor.
After=syslog.target network.target

[Service]
Type=simple
User=etherpad
Group=etherpad
WorkingDirectory=/opt/etherpad
ExecStart=/usr/bin/nodejs /opt/etherpad/etherpad-lite/node_modules/ep_etherpad-lite/node/server.js
Restart=always

[Install]
WantedBy=multi-user.target
```

the second files :  

`sudo nano /etc/init.d/etherpad-lite
`

```
#!/bin/sh
### BEGIN INIT INFO
# Provides: etherpad-lite
# Required-Start: $local_fs $remote_fs $network $syslog
# Required-Stop: $local_fs $remote_fs $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: starts etherpad lite
# Description: starts etherpad lite using start-stop-daemon
### END INIT INFO
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/node/bin"
LOGFILE="/var/log/etherpad-lite/etherpad-lite.log"
EPLITE_DIR="/opt/etherpad/etherpad-lite/"
EPLITE_BIN="bin/run.sh"
USER="root"
GROUP="root"
DESC="Etherpad Lite"
NAME="etherpad-lite"
set -e
. /lib/lsb/init-functions
start() {
echo "Starting $DESC... "
start-stop-daemon --start --chuid "$USER:$GROUP" --background --make-pidfile --pidfile /var/run/$NAME.pid --exec "$EPLITE_DIR/$EPLITE_BIN" -- $LOGFILE || true
echo "done"
}
# Nous avons besoin de cette fonction pour assurer la totalité du processus lorsqu'il sera tué
killtree() {
local _pid=$1
local _sig=${2-TERM}
for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
killtree ${_child} ${_sig}
done
kill -${_sig} ${_pid}
}
stop() {
echo "Stopping $DESC... "
while test -d /proc/$(cat /var/run/$NAME.pid); do
killtree $(cat /var/run/$NAME.pid) 15
sleep 0.5
done
rm /var/run/$NAME.pid
echo "done"
}
status() {
status_of_proc -p /var/run/$NAME.pid "" "etherpad-lite" && exit 0 || exit $?
}
case "$1" in
start)
start
;;
stop)
stop
;;
restart)
stop
start
;;
status)
status
;;
*)
echo "Usage: $NAME {start|stop|restart|status}" >&2
exit 1
;;
esac
exit 0
```

ok so now when i start my etherpad service i have this error : 

` sudo /etc/init.d/etherpad-lite start
[....] Starting etherpad-lite (via systemctl): etherpad-lite.serviceFailed to start etherpad-lite.service: Unit etherpad-lite.service not found.
 failed!
`

can u please tell me what is wrong ?

thanks

**Comment by lpagliari** [comment]
I don't know much about running Etherpad as a service, but I've remembered there's a wiki page about that: https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service. Does that help you?

**Comment by rhelmer** [comment]
@ychoucha I'm not sure why you'd want both the init script and the systemd service... in any case I'd try the `.service` file @lpagliari linked and see if that helps.

It might be worth landing an `etherpad.service` file in the etherpad-lite repo, although that's the sort of thing I'd expect distro packagers to add...
