### ISSUE TITLE
Once set, Font Size gets forgotten

### ISSUE THREAD

**Issue by Samurai88** [ether/etherpad-lite#3200]
1. When setting a font size manually to say 18, then any new text that is written/added in the middle or at the end of the document gets the default (smaller) font size.

2. When copying a portion of the text (which has font size 18) and pasting it elsewhere in the same page, resets the fontsize back to the default (smaller) font size.

This happens all the time and is a consistent bug. Apart from this little annoyance its a very very nice opensource realtime texteditor! Tested in FireFox 50 on a Windows 10 64 bit machine.

**Comment by lpagliari** [comment]
Hi, @Samurai88 , those seems to be issues of [ep_font_size plugin](https://github.com/JohnMcLear/ep_font_size). Could you open this issue there, so they can handle it? Thanks!
