### ISSUE TITLE
Difficult to read the user name in the modifications

### ISSUE THREAD

**Issue by LAfricain** [ether/etherpad-lite#3202]
When you want to read the changes made by an other user it's difficult to read his name because it is superimposed with the text.
Look the picture:
![etherpad](https://user-images.githubusercontent.com/19690477/27024109-36406fb2-4f4d-11e7-9576-d3114a152013.png)

**Comment by Gared** [comment]
You're using a plugin for this functionality. This is not a core feature

**Comment by LAfricain** [comment]
what are you speaking about? What kind of plugin?

**Comment by lpagliari** [comment]
There are some plugins that show the author name (like [ep_author_hover](https://github.com/ether/ep_author_hover), for example). Do you know which plugins are installed on your Etherpad instance?

I believe what @Gared meant was that your issue should be opened on that repo, not here.
