### ISSUE TITLE
Buttons: Showing the active state of the formatting

### ISSUE THREAD

**Issue by renebrain** [ether/etherpad-lite#3204]
Is there any possibility to let the buttons show the current state of the formatting, when clicking or marking a specific part of the text, like other texteditors do?

Test on https://beta.etherpad.org:
![etherpad1](https://user-images.githubusercontent.com/9963399/27179984-71409836-51d1-11e7-995a-d2ac568fc414.gif)

Test on LibreOffice:
![etherpad1-vergleich](https://user-images.githubusercontent.com/9963399/27180093-f67ae7f4-51d1-11e7-94fb-4b1ca0b1ba41.gif)

**Comment by lpagliari** [comment]
Fixed via #3301
