### ISSUE TITLE
LibreOffice Export Crash

### ISSUE THREAD

**Issue by skupfer** [ether/etherpad-lite#3211]
Worked one time, since then I receive the following error

EDIT: also happens on 1.6.1
/tmp/ folder is full with etherpad_*.html files

```
[2017-06-29 19:50:47.039] [ERROR] console - Async Stacktrace:
    at /usr/share/nginx/www/etherpad-lite/src/node/handler/ExportHandler.js:182:36

Error: ENOENT: no such file or directory, rename '/tmp/etherpad_export_1695677848.pdf' -> '/tmp/etherpad_export_1695677848.pdf'
    at Error (native)
```

EDIT2 (6th July 17):
this is working on an etherpad instance running in a virtual machine. I tried to replicate my server setup as good as I can. i.e. used a ep-dir-copy of the live system

Could you guide me finding the problem? npm/node/nginx/libreoffice/plugin/etherpad/debian/ -versions, nearly everything is identical except some apps like docker, btsync, ...

EDIT3: Oh and it would be great if the export would preserve the font used in etherpad... I set it to monospace but the exported pdf is using a different one...

EDIT4: This is definitely linked to reverse proxies from what I experienced (reverse proxy in VM = same issue)

EDIT5: does anyone know non outdated projects but like etherpad with non outdated plugins (if used)? Very sad to see that most of the plugins became useless or not working properly

**Comment by skupfer** [comment]
So, has this been fixed? Just curious. This is not related to plugins (I mean you offer the functionality via config) but a simple reverse proxy...

**Comment by P-D-** [comment]
neede to add an env variable because of running soffice process...
