### ISSUE TITLE
Cannot import 2.7 MB *.etherpad dump

### ISSUE THREAD

**Issue by flberger** [ether/etherpad-lite#3213]
I am trying to migrate from an Etherpad Lite instance where I have no backend access to a self-hosted instance. I would like to preserve the pad history.

As I can not access the backend, I exported an `*.etherpad` JSON file of about 2.7 MB size via the web interface.

Trying to import this via the web interface in the new pad apparently uploads the file, but then yields "_Import failed: Please copy and paste_".

There are no errors on the browser's JS console.

The server console also displays no errors.

I set the loglevel to DEBUG, reloaded the pad, which resulted in loads of debug messages of GET, SET and the likes.

The final message before the import is

```
[2017-07-04 22:24:46.625] [DEBUG] http - 200, GET
/javascripts/lib/unorm/lib/unorm.js?callback=require.define
[2017-07-04 22:24:46.638] [INFO] ueberDB - Flushed 1 values
[    ] - :
```

with the latter looking like a progress bar, but nothing happens there.

During and after the import, no errors (or, in fact, any debug messages) are displayed, except from the reported error in the web interface.

I was trying in Firefox first; I tried again in Chromium. The result is the same.

When I leave the pad in the browser, the debug messages yield

```
[2017-07-04 22:33:56.695] [INFO] access - [LEAVE] Pad "test": Author
"a.d9ElzoopyP5jVJLH" on client 0qT8GxHnSCnPt0OpAAAA with IP "ANONYMOUS"
left the pad

```
etc., so it is still working. The import process seems to be completely silent.

I am reluctant to post the pad dump in public, but I can provide it upon request.

Any hints would be greatly appreciated.

**Comment by JohnMcLear** [comment]
I'd be interested in taking this bug on, if you can provide the .etherpad file!

**Comment by JohnMcLear** [comment]
Well, I just tested with a 4Mb file and it was fine..  Assuming this was user error as no further data was provided.
