### ISSUE TITLE
cannot access the product website

### ISSUE THREAD

**Issue by lennyli** [ether/etherpad-lite#3217]
Hi
I downloaded  your product and extracted the files at c:\ on my windows 2008 r2 sp1 platform. I edited the settings.json file to take out the/* for admin username password section, and replaced 0.0.0.0 with the server's IP address.
Then after i launch start.bat, the console stopped at the characters [.............] and I cannot access your web based product by using internet explorer to visit http://localhost:9001
Please enlighten me.

**Comment by lpagliari** [comment]
> and replaced 0.0.0.0 with the server's IP address

If you've changed `0.0.0.0` by another IP you need to access that IP on your browser, not `localhost`

**Comment by lennyli** [comment]
Thanks, I can access your web interface, but now after I input a username and click ok, I see the message an error occurred while loading the pad. Expected identifier in http://10.33.98.130:9001/static/is/require-kernel.js line 226
What should I do??

**Comment by lennyli** [comment]
Hi
I now created a new text that has the sample
Welcome to Etherpad!

On right hand top corner I input my name
And started typing. Meanwhile I asked a coworker to goto same URL but he cannot see my typing in real time.

Please advise how I can test this coediting software

**Comment by lpagliari** [comment]
Does your co-worker have access to the same server you're using? Can he/she access http://10.33.98.130:9001? What does he/she sees when accessing the URL you provided to him/her?

**Comment by lennyli** [comment]
my coworker tried to use a different windows username to access the client computer that has access to our intranet servers. he can access http://10.33.98.130:9001. If he clicks the button to start a new document, he sees the basic sample template as mine but cannot see changes i made. i tried to give him the same url with the random alphanumeric that follws, still cant see edits in real time. we have already tried to use different names on the right top corner so we are represented by different colours.my expectation is that we should be able to see each others real time edit in different colours. please enlighten me.

      寄件人︰ Luiza Pagliari <notifications@github.com>
 收件人︰ ether/etherpad-lite <etherpad-lite@noreply.github.com> 
副本(CC)︰ lennyli <lennyli@lennyli.com>; Author <author@noreply.github.com>
 傳送日期︰ 2017年07月12日 (週三) 5:32 PM
 主題︰ Re: [ether/etherpad-lite] cannot access the product website (#3217)
   
Does your co-worker have access to the same server you're using? Can he/she access http://10.33.98.130:9001? What does he/she sees when accessing the URL you provided to him/her?—

**Comment by lpagliari** [comment]
Hum, then I have no idea about what is happening there... :-/ If you edit your text and your coworker reloads the URL you've provided, does he/she see the updated text, at least?
