### ISSUE TITLE
Automatic Refresh

### ISSUE THREAD

**Issue by Billaboong** [ether/etherpad-lite#3224]
I have set up etherpad as a service but each time I need to use it I need to run bin/run.sh.How can it run always.
Thank you.

**Comment by lpagliari** [comment]
There are some instructions [on the wiki](https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service). Do they help you solve your issue, @Billaboong ?

**Comment by Billaboong** [comment]
Thank you @lpagliari  for your response....I have set up the service as per the wiki but after a day the service seems to stop working and I am forced to run run.sh command for it to work again.So I am wondering why what could be the problem.

**Comment by lpagliari** [comment]
I've never used Etherpad as a service, but I can try to help you. Can you
provide more details? Like: was there any message on Etherpad logs when it
stopped running? Could you set the debug mode as "DEBUG" instead of "INFO"
on your settings.json and send here what the tail of the output was when
service stopped, please?

**Comment by Billaboong** [comment]
I have changed the debug mode to debug and I am now waiting for the output and as soon as I get the output I will surely post here.

Thank you.

**Comment by Billaboong** [comment]
Hello @lpagliari 
I changed the debug mode and all I can see is alot of information but when the terminal is closed etherpad stops running.

**Comment by lpagliari** [comment]
> I changed the debug mode

Did you run Etherpad as a service or did you exec the `bin/debugRun.sh`? The later would stop Etherpad when you close the terminal. What I meant on the other message was only to enable the debug logging...

**Comment by Billaboong** [comment]
I exec run.sh

**Comment by lpagliari** [comment]
Could you please run it as a service? BTW, which SO are you using? Which instructions of the wiki did you follow to create the service?

**Comment by Billaboong** [comment]
The OS I am using is CentOS 6.8 and I used the instructions of CentOs 6 from the wiki.

**Comment by lpagliari** [comment]
is there any error on the log file, @Billaboong ? It is probably on `/var/log/etherpad.log`

**Comment by Billaboong** [comment]
Good morning @lpagliari...What I did was to reinstall etherpad again.The error log is attached below:

![etherpad-lite-errorlog](https://user-images.githubusercontent.com/4427236/28704005-7f41f9c8-7370-11e7-95a0-a32b566e32f6.png)

**Comment by lpagliari** [comment]
Hum, it looks like there's something wrong with your environment vars or configs, did you notice that? There's a "cannot change directory to /bin/**false**"...

**Comment by Billaboong** [comment]
Hallo @lpagliari  let me contact my administrator about it then I will inform you.
Thank you.
