### ISSUE TITLE
Etherpad server crashing when pad member changed. 

### ISSUE THREAD

**Issue by kernelfreak** [ether/etherpad-lite#3225]
Hello friends,
Etherpad version : 1.6.1
I am working on integrating etherpad into our project. Currently the project is working good. We have a very specific issue when calling the history functionality of etherpad. Here is the scenario. 
Author A creates a pad and adds some data into it. Author B adds some data into it and etherpad keeps a track of it. 
Now we call the copy_pad functionality and the pad is copied into a new pad. In this new pad, Author A does not exist or doesn't have access to this new pad. 
Now when we open the history and reach the point where Author A had made changes, entire etherpad server crashesh. 
A very similar issue was opened in 2013, but this is a bit different as the use-case is different. 

Error log :

`[2017-07-19 09:50:19.886] [ERROR] console - Error: Not a exports: null
    at Object.error (/home/deploy/node_modules/etherpad-lite/src/static/js/Changeset.js:39:11)
    at Object.exports.unpack (/home/deploy/node_modules/etherpad-lite/src/static/js/Changeset.js:874:13)
    at Object.exports.inverse (/home/deploy/node_modules/etherpad-lite/src/static/js/Changeset.js:1882:26)
    at /home/deploy/node_modules/etherpad-lite/src/node/handler/PadMessageHandler.js:1505:35
    at /home/deploy/node_modules/etherpad-lite/src/node_modules/async/lib/async.js:610:21
    at /home/deploy/node_modules/etherpad-lite/src/node_modules/async/lib/async.js:249:17
    at iterate (/home/deploy/node_modules/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
    at /home/deploy/node_modules/etherpad-lite/src/node_modules/async/lib/async.js:160:25
    at /home/deploy/node_modules/etherpad-lite/src/node_modules/async/lib/async.js:251:21
    at /home/deploy/node_modules/etherpad-lite/src/node_modules/async/lib/async.js:615:34

`

**Comment by ravinet** [comment]
Hi,

I am trying to reproduce this bug. When you say "copy_pad", what commands are you running?

Thanks!

**Comment by ravinet** [comment]
Hi,

I tried to reproduce this bug but was unable to. So, I would like to make sure that I am understanding the use case:
- create a pad
- Author A writes something to the pad
- Author B opens the pad and writes something to it
- Author B calls copy_pad which creates a new pad which builds on the pad with Author A and B's comments (the new pad maintains the authorship colors from the original pad). There is only one user in the new pad (Author B).
- Author B then clicks on  'timeslider'.

Are you suggesting that in the timeslider, you can go back to the changes made just by Author A, and this triggers the problem? For me, the timeslider only has two stages: an empty pad, and the complete pad which was written when copy_pad was called.

Perhaps I am missing a step or doing something incorrectly?

**Comment by kernelfreak** [comment]
@ravinet : Author A is removed from etherpad as an author. That's the step you missed.

**Comment by ravinet** [comment]
Thanks for the response @kernelfreak. In the copied pad, there is only one active user listed (Author B). Also, after copying the pad, I modified the settings.json file to remove Author A. Yet, the timeslider still functions properly.

Do you have any other info/code that could help me reproduce the bug?

**Comment by JohnMcLear** [comment]
This sounds like a bug with a plugin no?
