### ISSUE TITLE
Semver.js:Invalid version Error on accesing the admin panel

### ISSUE THREAD

**Issue by Billaboong** [ether/etherpad-lite#3228]
Hi,
My etherpad lite was working fine but when I installed plugins I got the following error attached.
![etherpad-lite-error](https://user-images.githubusercontent.com/4427236/28622298-b8a77094-721c-11e7-8510-9b4598726f54.png)

#npm -v
5.3.0
#gulp -v
CLI version 1.2.2
Local version 3.9.1
#node -v
v8.2.1

**Comment by lpagliari** [comment]
Duplicate of #2837

**Comment by Billaboong** [comment]
@lpagliari How was the above issue resolved?

**Comment by lpagliari** [comment]
It was not resolved, it is still opened. It's just that this issue is exactly the same as #2837, so we don't need 2 of them opened

**Comment by Billaboong** [comment]
okay thanks alot...
