### ISSUE TITLE
CSS - Background

### ISSUE THREAD

**Issue by Billaboong** [ether/etherpad-lite#3234]
Hallo,

From the link [https://beta.etherpad.org/p/beta](https://beta.etherpad.org/p/beta) the background is green and I have looked for where the color has been set but I have not found it.

The color green is on Mozilla broswer but other browsers it is grey.

How can I solve it to have a consistent color.

**Comment by lpagliari** [comment]
This is actually a bug on https://github.com/ether/ep_page_view, the plugin that draws the page layout on Etherpad. I've noticed the same, but never heard of a fix for that, sorry.

**Comment by Billaboong** [comment]
@lpagliari Thank you
