### ISSUE TITLE
[Updated] html10n.js has a new version

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#3244]
Greetings!

this is just a heads-up that I've just updated html10n.js, the l10n engine of etherpad to fix a bug producing faults with russian plural rules.

Check out https://github.com/marcelklehr/html10n.js

Cheers,
Marcel

**Comment by lpagliari** [comment]
Code was reverted, so I'm reopening this issue.

**Comment by JohnMcLear** [comment]
*bumping @marcelklehr and @lpagliari

**Comment by marcelklehr** [comment]
This commit seems to have been the culprit: https://github.com/marcelklehr/html10n.js/commit/be55f93587a0fae373016051b59f59a92ac0d5a7

It was overtaken from a fix for NFCRing, which makes me think that the library is used wrong over there... (The root json files should contain keys for languages under which the translations are provided, even if only one language is in the file.)

**Comment by JohnMcLear** [comment]
okay cool, yeah don't worry about NFCRing package

**Comment by JohnMcLear** [comment]
"Latest commit
e21c5eb
on Apr 3, 2018 "

I don't think there is much value staying up to date with this package because it doesn't appear to being well maintained upstream.
