### ISSUE TITLE
Etherpad caching not working properly.

### ISSUE THREAD

**Issue by kernelfreak** [ether/etherpad-lite#3251]
Hello friends,

I am working on integrating etherpad in our application. Currently it's working good. We only have an issue with caching. I had enabled caching and minify. We had set the cache period to 24 hours. On Friday, we updated some CSS files, and then today when we checked, still the old CSS files were being used. 

In the network tab, we could see that the new CSS files were fetched with 0 caching period, but when you inspect the etherpad element, still old css settings are active. Only solution now is to clear the cache. Any ideas what is happening? Thank you.

**Comment by JohnMcLear** [comment]
Seems to be working fine for me..

Let me know if you can still replicate and I will reopen
