### ISSUE TITLE
migrateDirtyDBtoRealDB.js fails to run

### ISSUE THREAD

**Issue by sdkrum** [ether/etherpad-lite#3252]
Hi!
We have an etherpad instance which we first had in dirty mode to try out some stuff, but that shall now go production, what means we want to convert the database from the dirty to mysql. 

The version of etherpad we used so far was 1.5.7, the new system is a 1.6.1. So after we installed the new version and checked out that it properly connects to the mysql db, we copied the dirty.js file into the var directory, and tried to run migrateDirtyDBtoRealDB.js:

```
$ node bin/migrateDirtyDBtoRealDB.js 
module.js:491
    throw err;
    ^

Error: Cannot find module '../src/node_modules/dirty'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at EventEmitter.<anonymous> (/opt/etherpad/bin/migrateDirtyDBtoRealDB.js:10:15)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

And indeed, there is no such directory under ../src/node_modules. Did we missed a step? 

Otherwise, a cool tool! Keep it up!

**Comment by lpagliari** [comment]
Hi, @sdkrum , I believe you need to run `bin/installDeps.sh` before performing the migration...

**Comment by sdkrum** [comment]
Hello @lpagliari 
Thanks for the suggestion, i tried it out, but unfortunately it does not fix my problem. No new folder in `src/node_modules`, and the migrate script exits with the same error. Wondering if that is coming from that i used puppet to install etherpad-lite. 

I am wondering a bit about a line in the script: 
`var dirty = require("../src/node_modules/dirty")('var/dirty.db');`
Looks a bit strange for me, but it may be perfect valid js syntax. 

Does anyone know which libraries are supposed to be stored under `dirty`?

**Comment by lpagliari** [comment]
Do you have any folder on `src/node_modules/` at all? This is what I have on my instance:

![image](https://user-images.githubusercontent.com/836386/29663468-aca4b428-88a1-11e7-9972-904e837097a1.png)

Regarding the syntax you've mentioned, the first part (`require("../src/node_modules/dirty")`) is getting a function from `dirty` module; the second part (`('var/dirty.db')`) is calling that function with the string `'var/dirty.db'`. My guess is that it loads the `dirty` module with the content of that file.

**Comment by sdkrum** [comment]
Yes, i have that folder, with plenty of modules: 
`/opt/etherpad/src/node_modules$ ls
asap              cheerio        core-util-is             etherpad-yajsml  fs-write-stream-atomic  imurmurhash  languages4translatewiki  normalize-git-url   path-is-absolute           request      semver            string_decoder        ueberdb2     unorm
async             clean-css      dezalgo                  express          graceful-fs             inherits     log4js                   npm                 process-nextick-args       resolve      slide             supertest             uglify-js    util-deprecate
async-stacktrace  concat-map     ejs                      express-session  hosted-git-info         isarray      measured                 npm-install-checks  readable-stream            safe-buffer  socket.io         swagger-node-express  underscore   wd
channels          cookie-parser  etherpad-require-kernel  formidable       iferr                   jsonminify   mocha                    npm-package-arg     realize-package-specifier  security     spdx-license-ids  tinycon               unique-slug  wrappy`

And you are probably right, i checked, the syntax seems valid. 

Any chance to patch my instance? I have not really found a hint where this folder and its content is coming from

**Comment by sdkrum** [comment]
Hm, found some sources under another path... `/opt/etherpad/src/node_modules/ueberdb2/node_modules/dirty` and after adding a symlink from that place to `src/node_modules/dirty` it seems to work smoothly!

Thanks for the help! :-)

**Comment by lpagliari** [comment]
Cool!
