### ISSUE TITLE
Etherpad having strange JS issues on Firefox 55.0.3

### ISSUE THREAD

**Issue by ocdtrekkie** [ether/etherpad-lite#3254]
I noticed this first on Sandstorm, which hasn't had a new update for Etherpad since November (nor a super recent Sandstorm build), but I just tested this on beta.etherpad.org and found the exact same behavior. I could've sworn I was having no issues using Etherpad with Firefox 55.0.3 like... yesterday. But today, no dice. When I go to the same in Internet Explorer, things work fine.

Etherpad shows the document correctly, but if I try to type, it says server disconnected.

This displays briefly on pad loading:

![image](https://user-images.githubusercontent.com/4399499/30388685-04119b0c-9876-11e7-940e-b64873ca3f15.png)

**Comment by joassouza** [comment]
For me it seems everything is ok!
_Mac OS 10.12.6 (16G29)
Firefox 55.0.3 (64-bit)_
Can you test it in this pad?
https://beta.etherpad.org/p/joas123

**Comment by ocdtrekkie** [comment]
Same behavior.

Note that I am on Windows 10.15063 64-bit, and Firefox 55.0.3 32-bit. But another Sandstorm user confirmed they are having the issue on Mac OS with FF 55.0.3, though they didn't detail exact version and build info.

**Comment by joassouza** [comment]
Are there any errors on the Firefox inspector console? If so, can you paste it here?

**Comment by ocdtrekkie** [comment]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/  require-kernel.js:284:4
unreachable code after return statement[Learn More]  require-kernel.js:580:4
unreachable code after return statement[Learn More]  require-kernel.js:2172:4
TypeError: ERROR.captureStackTrace is not a function[Learn More]  joas123:81:7
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  ace2_common.js:3751:28
XML Parsing Error: syntax error
Location: https://beta.etherpad.org/jserror
Line Number 1, Column 1:  jserror:1:1
Object { type: "CLIENT_VARS", data: Object }  pad.js:314:27
Object { type: "COLLABROOM", data: Object }  pad.js:3402:25
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/  joas123:299:4
unreachable code after return statement[Learn More]  joas123:580:4
unreachable code after return statement[Learn More]  joas123:2172:4
unreachable code after return statement[Learn More]  joas123%20line%20241%20%3E%20Function:2172:4
unreachable code after return statement[Learn More]  joas123%20line%20241%20%3E%20Function:580:4
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  ace2_common.js:3751:28
Object { type: "COLLABROOM", data: Object }  pad.js:3402:25
unreachable code after return statement[Learn More]  require-kernel.js%20line%20226%20%3E%20Function:580:4
unreachable code after return statement[Learn More]  require-kernel.js%20line%20226%20%3E%20Function:2172:4

**Comment by ocdtrekkie** [comment]
The Mac user has stated that they both have one computer that it does work and one computer that it doesn't, and that both are running 55.0.3 64-bit.

**Comment by ocdtrekkie** [comment]
Tested without Privacy Badger installed. I think we may have a culprit. Privacy Badger detects no trackers, and the issue occurs even with it "disabled for this site". But it is version 2017.09.12 which indicates it changed in the last day.

**Comment by ocdtrekkie** [comment]
They just released a point release to fix "major site breakages in Firefox" including Google Sheets. So with that little bit of testing, that changelog, and some common sense, I'm going to call this solved.

https://github.com/EFForg/privacybadger/commit/8bd780fe4274799341e6f5e0079a18d7a3a6c69b

**Comment by timmc-bcov** [comment]
Note that Privacy Badger 2017.07.24 produces the initial error screen, but does not block editing.

**Comment by ocdtrekkie** [comment]
@timmc-bcov I do not see the error screen at all on 2017.07.24.

**Comment by joassouza** [comment]
I'm gonna try to reproduce this error on a windows machine. Maybe it's the easier way to figure out what's happening.

**Comment by joassouza** [comment]
Good @ocdtrekkie! =)

**Comment by timmc** [comment]
2017.9.12.1 fixes both issues for me as well. Good find.

**Comment by cataclysmic** [comment]
Is there a way to fix this?
I'm Windows Firefox 52.7.3 32bit ESR. Company policy and I kinda have to use it.
