### ISSUE TITLE
Firefox 55.x TypeError

### ISSUE THREAD

**Issue by mcantsin** [ether/etherpad-lite#3255]
Using etherpad-lite with FF 55.x produces the following error:

> [2017-09-13 19:45:02.085] [WARN] client - TypeError: ERROR.captureStackTrace is not a function -- { errorId: 'xypRiv4Cyxxxxx',
>   msg: 'TypeError: ERROR.captureStackTrace is not a function',
>   url: 'https://foo.bar/p/oiqwhijqnweijhnqwe',
>   linenumber: 81,
>   userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0' }

**Comment by ocdtrekkie** [comment]
This is a regression in Privacy Badger 2017.09.12 which has been pulled from the Firefox Add-ons page. Uninstall and reinstall Privacy Badger, or wait until 2017.09.12.1 comes out sometime today.

See also the duplicate: #3254

**Comment by mcantsin** [comment]
Thanks @ocdtrekkie

I actually *did* diable Privacybadger for the specific domain, as I suspected it could be one of the activated add-ons. Seemingly only uninstalling helps here...

**Comment by ocdtrekkie** [comment]
Yup, I had originally tried that as well. ;)
