### ISSUE TITLE
When will we get a new release?

### ISSUE THREAD

**Issue by rugk** [ether/etherpad-lite#3259]
The current stable version is nearly one year old. When will we get a new release?

**Comment by Gared** [comment]
I'll create a new version if you think it is time for it. Unfortunately there are just a few code changes...
Is there anything a new release is worth for?

**Comment by rugk** [comment]
The last release was at 23 Dec 2016, so I think there are quite a lot code changes, are not there?

**Comment by Gared** [comment]
Here you can see the changes: https://github.com/ether/etherpad-lite/compare/master...develop?expand=1

**Comment by dvzrv** [comment]
@Gared that looks to more than enough changes to me already.
Also, there must be a new version, to fix deprecations, such as #3111.

**Comment by Gared** [comment]
New version released
