### ISSUE TITLE
Add markdown syntax highlighting

### ISSUE THREAD

**Issue by fungs** [ether/etherpad-lite#3262]
Among the different programming languages, it would be an improvement for non-programming source code to support markup language such as markdown, in some common minimalistic flavor. This should be in the dropdown list.

**Comment by lpagliari** [comment]
Hi, @fungs , there's a plugin for this: https://www.npmjs.com/package/ep_markdown. You can check other plugins on this list: https://static.etherpad.org/plugins.html.

**Comment by fungs** [comment]
Thanks, this looks good. However, I was thinking about simple syntax highlighting as for the other programming languages. This should be easy to add for the default installation.

**Comment by fungs** [comment]
Sorry, didn't know that but the instance I'm referring to is at https://public.etherpad-mozilla.org. If I know the plugin, I can report at the right place, of course. Thanks for the fast responses.

**Comment by lpagliari** [comment]
It looks like this is the plugin they're using: https://github.com/etinquis/etherpad-plugins/tree/master/ep_syntaxhighlighting. There's an [open PR](https://github.com/etinquis/etherpad-plugins/pull/28/files) with some examples of sintaxes, you can take a look on them to submit a PR to `ep_syntaxhighlighting` with the Markdown syntax.

**Comment by fungs** [comment]
Thanks, since this was the wrong place, you can close the issue.
