### ISSUE TITLE
Markdown for headers is incorrect

### ISSUE THREAD

**Issue by dessalines** [ether/etherpad-lite#3264]
I've noticed instead of using the ordinary `#`(h1), or `##`(h2) for headers, etherpad uses a `======`, why is this?

**Comment by lpagliari** [comment]
which part of the code are you talking about?

**Comment by dessalines** [comment]
Go into etherpad and click the text type, and change it to header.

**Comment by lpagliari** [comment]
Etherpad doesn't have this kind of feature on its core, it might be a plugin that is providing that feature. Which Etherpad instance are you using?

**Comment by dessalines** [comment]
The demo site. There's a button that says markdown.

**Comment by lpagliari** [comment]
Ok, got it. This is the plugin that provides the feature, please ask their creators for more info: https://github.com/ether/ep_markdown
