### ISSUE TITLE
Bad line-wrapping in WebKit browsers

### ISSUE THREAD

**Issue by caitp** [ether/etherpad-lite#3270]
The line

```js
$$INCLUDE_CSS("../static/css/iframe_editor.css");
```

from ace2.js, adds the style `whitespace: nowrap` to `body`. In Blink-based browsers, this style gets overridden by the `.noprewrap` class, but for whatever reason this class is not applied when viewed from Safari, WebKit Nightly, or presumably Epiphany or other similar browsers. Effectively, this makes pads unreadable from an iphone.

Surely there's no good reason to add `whitespace: nowrap` to `body` for the entire document, this only  makes sense from a text editor rendered in an iframe (and even then... does it really make sense?)

**Comment by JohnMcLear** [comment]
Are you sure?  This feels like a serious bug in Safari on iPhones...

**Comment by caitp** [comment]
I’m not sure (I’ve only used my org’s ep-lite), but it’s certainly the case there.

**Comment by caitp** [comment]
Here's a reproduction you you can try https://pads.igalia.com/mypads/?/mypads/group/igalia-all-6veuyqq/pad/view/ep-lite-bug3270-c7p7ww6

Webkit:

<img width="802" alt="webkit" src="https://user-images.githubusercontent.com/2294695/38261659-df15fa48-3738-11e8-8fe0-d14f91a5e297.png">

Chromium:

<img width="822" alt="chromium" src="https://user-images.githubusercontent.com/2294695/38261668-ea527a12-3738-11e8-9cbc-0904bab45af0.png">

**Comment by JohnMcLear** [comment]
Do you get the problem if you don't embed in iFrame?  IE access https://beta.etherpad.org directly?

Can it be replicated on Safari or Chrome Canary on Windows?

**Comment by caitp** [comment]
> Do you get the problem if you don't embed in iFrame? IE access https://beta.etherpad.org directly?

yes

> Can it be replicated on Safari or Chrome Canary on Windows?

Chrome/Blink doesn't seem to suffer the problem (as mentioned above) --- I don't know of a WebKit-based browser that's available on Windows, or at least not a contemporary one (so it's hard to check there).

**Comment by caitp** [comment]
This seems to be fixable with the following change:

```diff
index 757bfa96..3fdc9936 100644
--- a/src/static/css/iframe_editor.css
+++ b/src/static/css/iframe_editor.css
@@ -43,7 +43,7 @@ body.grayedout { background-color: #eee !important }
 }
 
 body.doesWrap {
-  /* white-space: pre-wrap; */
+  white-space: unset;
 
   /*
     Must be pre-wrap to keep trailing spaces. Otherwise you get a zombie caret,
```

**Comment by psaavedra** [comment]
Related: https://github.com/ether/etherpad-lite/pull/3134

**Comment by psaavedra** [comment]
I don't think. My patch was for Mozilla browsers not sure about the status in Webkit

**Comment by JohnMcLear** [comment]
Okay do you want to send through a pull request with your fix and we can see how it's received.
