### ISSUE TITLE
why mysql?

### ISSUE THREAD

**Issue by hajika** [ether/etherpad-lite#3272]
I wonder why the data is saved in mysql because the data is formated only in a key/value format. This looks much more like a nosql format and a non relational DB would be even faster to process that data, would it not?

**Comment by ocdtrekkie** [comment]
"You can choose between dirty, postgres, sqlite and mysql"

SQLite works pretty well with Etherpad, and is a lot lighter/thinner than MySQL.

**Comment by hajika** [comment]
But its also sql DB, and because textbased slower than mysql. True, dirty DB is key/value, maybe that is the reason why the data is stored in key/value format?! That would be really weird to tie the data format to a DB that is recommended not to be used. Or was is planned to support another DB in the future? Looks like Redis would be a good way, it is also used by Ethercalc by the way..

**Comment by lpagliari** [comment]
You can actually choose [some other DBs](https://github.com/Pita/ueberDB#database-support), including some noSQL. Redis is there too, by the way.
You don't _need_ to use MySQL, but you can, if that is the option you have in hand.
