### ISSUE TITLE
Connection with mssql and etherpad

### ISSUE THREAD

**Issue by jinbullsushil** [ether/etherpad-lite#3275]
Is There any plugins available to connect mssql and etherpad

**Comment by lpagliari** [comment]
No, @jinbullsushil. To do that you'll need to make [ueberDB](https://github.com/Pita/ueberDB) support mssql, then Etherpad can be configured to use it.

**Comment by jinbullsushil** [comment]
@lpagliari , I have created mssql which connect to etherpad with mssql.

**Comment by lpagliari** [comment]
@jinbullsushil did you submit your PR to `ueberDB`? If they accepted your PR, Etherpad just needs to get the latest version to be able to support mssql

**Comment by lpagliari** [comment]
as a workaround while your PR is not approved, you can use your fork on your Etherpad instance. **It shouldn't be a final solution**, but at least you won't have to wait for the approval: on `src/package.json`, replace `"ueberdb2": "0.3.0",` by `"ueberdb2": "git@github.jinbullsushil/ueberDB.git",`

**Comment by rodrigonmelo** [comment]
Hello guys,
I am a newbie, but I would like to connect mssql to the Etherpad. Do you have a guide for this? Thanks a lot.

**Comment by JohnMcLear** [comment]
Docs at: https://www.npmjs.com/package/mssql
```
const config = {
    user: '...',
    password: '...',
    server: 'localhost', // You can use 'localhost\\instance' to connect to named instance
    database: '...',
}
```
Just set user, pass, server and database in ``settings.json`` to match whatever you setup in mssql.

**Comment by rodrigonmelo** [comment]
I appreciate your reply @JohnMcLear . Thanks and I would like to post  soon the pad, but I have to receive an authorization if they will allow me a new pad from my workplace.

**Comment by rodrigonmelo** [comment]
It does not work like this. There is not a mssql_db file on Etherpad_lite  like this:

`[2020-08-12 10:53:13.167] [INFO] console - Session key loaded from: D:\Program Files\nodejs\etherpad-lite\SESSIONKEY.txt
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module './mssql_db'
Require stack:
- D:\Program Files\nodejs\etherpad-lite\src\node_modules\ueberdb2\CloneAndAtomicLayer.js
- D:\Program Files\nodejs\etherpad-lite\src\node\db\DB.js
- D:\Program Files\nodejs\etherpad-lite\src\node\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at new exports.database (D:\Program Files\nodejs\etherpad-lite\src\node_modules\ueberdb2\CloneAndAtomicLayer.js:36:20)
    at Object.<anonymous> (D:\Program Files\nodejs\etherpad-lite\src\node\db\DB.js:28:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Program Files\\nodejs\\etherpad-lite\\src\\node_modules\\ueberdb2\\CloneAndAtomicLayer.js',
    'D:\\Program Files\\nodejs\\etherpad-lite\\src\\node\\db\\DB.js',
    'D:\\Program Files\\nodejs\\etherpad-lite\\src\\node\\server.js'
  ]
}`

**Comment by JohnMcLear** [comment]
Ueberdb will need mssql

It must not install it by default for some reason??

Are you on latest Etherpad develop branch?

**Comment by rodrigonmelo** [comment]
Yes, it should be installed by Ueberdb, but it is not installed on Ueberdb the mssql_db file. I got this with our fellow @jinbullsushil that uploaded the file on his repository. 
I got the file and now it works like a charm.

**Comment by JohnMcLear** [comment]
https://github.com/ether/ueberDB/blob/master/package.json#L32  it is required...
and it exists in the repo: https://github.com/ether/ueberDB/blob/master/databases/mssql_db.js

I think you need to **update**, feels like this is all I spend my days saying to people lately ;\

**Comment by rodrigonmelo** [comment]
Hello John.

Sorry for spending your days in this. I had installed npm install ueberdb2,
not uberdb. However I have appreciated your collaboration and prompt reply
to help people like me. ;)

Thanks,
Rodrigo N. de Melo
rodrigonogueiramelo@gmail.com
+1 613 501 8846

**Comment by JohnMcLear** [comment]
https://github.com/ether/ueberDB/blob/master/package.json#L2 is ueberdb2...

I think TLDR; again for anyone is to update Etherpad before posting here 📟

**Comment by jinbullsushil** [comment]
Hi,
Is mssql working for you?

**Comment by jinbullsushil** [comment]
> Yes, it should be installed by Ueberdb, but it is not installed on Ueberdb the mssql_db file. I got this with our fellow @jinbullsushil that uploaded the file on his repository.
> I got the file and now it works like a charm.

I have used mssql with etherpad. And it is working.

**Comment by rodrigonmelo** [comment]
Thanks again @JohnMcLear .
 I downloaded the zip file from etherpad official web site and I did not find the mssql_db.js there. Can you please update there?

**Comment by rodrigonmelo** [comment]
> > Yes, it should be installed by Ueberdb, but it is not installed on Ueberdb the mssql_db file. I got this with our fellow @jinbullsushil that uploaded the file on his repository.
> > I got the file and now it works like a charm.
> 
> I have used mssql with etherpad. And it is working.

Yes, it is working like a charm. Thanks a lot. You saved me. 👍

**Comment by JohnMcLear** [comment]
I'm hoping @muxator will do a rls soon. Will ping him.
