### ISSUE TITLE
Screen Jumping when typing

### ISSUE THREAD

**Issue by jinbullsushil** [ether/etherpad-lite#3276]
Hi,

When I am typing into pad text is jumping left right. 
I have attached gif image.
![screen_jumping](https://user-images.githubusercontent.com/30068021/32533711-fe158a1e-c477-11e7-94bf-7a56eb256d77.gif)

**Comment by rhelmer** [comment]
Hi @jinbullsushil - which browser+version are you using, and which version of Etherpad is this?

**Comment by jinbullsushil** [comment]
Hi @rhelmer - My Pad Version is : etherpad-lite-win-1.6.2.
Brower: chrome, firefox, safari and IE.

**Comment by JohnMcLear** [comment]
Try disable plugins until you find which one is causing this :)
