### ISSUE TITLE
[feature] add annotations and edition suggestion

### ISSUE THREAD

**Issue by jibe-b** [ether/etherpad-lite#3277]
Collaborative edition is improved by the possibility to comment text (which is then visible by other users and styled differently to text),

and an "edition suggestion" feature (selection of a piece of text and proposition of a change either a blank or a new piece of text)

Suggestions:
- use of github.com/hypothesis/h

Hypothesis could be updated to support this.

**Comment by lpagliari** [comment]
There's a plugin for that, please check #1865
