### ISSUE TITLE
Out of date or broken instances?

### ISSUE THREAD

**Issue by a-raccoon** [ether/etherpad-lite#3278]
Asked on #etherpad-lite-dev
Regarding the list of Sites that run Etherpad Lite -- https://github.com/ether/etherpad-lite/wiki/Sites-that-run-Etherpad-Lite

There seems to be no explanation regarding the sites categorized under "Out of date or currently broken instances (WARNING MAY CONTAIN SECURITY ISSUES)"

Could someone elaborate for me whether they were identified as using an older version of etherpad, and how is that determination made?

Some of those sites listed have since switched from HTTP to HTTPS and so I am wondering if their status is still appropriate, or if their status was compounded by some vulnerable software version as well?

**Comment by lpagliari** [comment]
I've checked [the history of the page](https://github.com/ether/etherpad-lite/wiki/Sites-that-run-Etherpad-Lite/_history?page=2) and it looks like those instances were moved to the "Out of date" section after some releases with security fixes (see releases [1.5.1-1.5.4](https://github.com/ether/etherpad-lite/releases)). You probably need to double-check witch Etherpad version they are using right now, so be sure they are not running a version with those issues still around.

**Comment by a-raccoon** [comment]
How do I check which version of Etherpad someone else is using?  I also suspect all the Non-HTTPS links got shoved down there, and some of them have since become HTTPS now.

**Comment by lpagliari** [comment]
> How do I check which version of Etherpad someone else is using? 

I'm not sure if you can. You would need to get in touch with their supporting teams...

> I also suspect all the Non-HTTPS links got shoved down there, and some of them have since become HTTPS now.

Can you post here those changes? I'll update the wiki. Thanks, man!

**Comment by JohnMcLear** [comment]
Please update the Wiki if you find it's out of date!

**Comment by a-raccoon** [comment]
It's difficult to update the wiki without specific steps to identify which servers are vulnerable and why.  Can you give me details on how these servers were initially identified as being vulnerable, and how I can confirm and re-validate that information?

**Comment by JohnMcLear** [comment]
By 1.7 I mean 1.6.4
