### ISSUE TITLE
Page Break w/ blank lines and following cursor

### ISSUE THREAD

**Issue by poafernandes** [ether/etherpad-lite#3279]
So, recently I've been having some problems with page break from page view.

One of them shown on this gif, where just by moving my cursor to the line above eventually screws the page break. The other problem is that a blank line gets added while setting up the new page and when you try to remove it to get the text filling the entire page, it breaks the page break and the editor flicks between adding and removing the page break. Any tips about this? Is it a issue or I'm using incorrectly? 

Thanks in advance.

![boooa](https://user-images.githubusercontent.com/30806203/33071800-21b11700-cea4-11e7-84ae-59815e2a3cfc.gif)

**Comment by lpagliari** [comment]
This is an issue of [the ep_page_view plugin](https://github.com/ether/ep_page_view), not Etherpad. Could you open an issue there, please? And, yes, it is a bug, you're using the plugin correctly.
