### ISSUE TITLE
Etherpad plugin does not work, if npm package uses organization.

### ISSUE THREAD

**Issue by ToniIltanen** [ether/etherpad-lite#3281]
when a npm package is under an organization, plugin is not loaded. 
npm organization uses a name convention of [@organization]/[plugin_name], and is installed to node_modules/[@organization]/[plugin_name].
When etherpad loads, plugins under the organization folder are not loaded. 

Tested with the latest version of etherpad-lite.
More info on Org -scoped packages, https://www.npmjs.com/docs/orgs/
Can be tested with https://www.npmjs.com/package/@omahoito/ep_gh_markdown (Markdown converter plugin), which installs under ```node_modules/@omahoito/ep_gh_markdown```.

**Comment by JohnMcLear** [comment]
Sounds about right!

**Comment by JohnMcLear** [comment]
for now just install organizational plugins using ``npm install``
