### ISSUE TITLE
Active directory support

### ISSUE THREAD

**Issue by mrquivousveuxdubien** [ether/etherpad-lite#3283]
Hello,

Is it possible to add active directory link, so it's possible to connect your app with domain users and not with pseudo ou custom username.

With access levels and readonly right as bonus.

Regards

**Comment by ocdtrekkie** [comment]
@mrquivousveuxdubien Etherpad Lite itself, to my knowledge, has no real authentication system, however, some platforms which DO support Active Directory and permissions implement Etherpad.

For instance, Sandstorm.io supports LDAP and SAML authentication, user permissions, and includes Etherpad, EtherCalc, Wekan, and Rocket.Chat by default. I know Cloudron.io also has Etherpad, and uses LDAP amongst it's own apps, but I'm not sure it's possible to interface a Cloudron server with AD.

**Comment by Carl4** [comment]
Using LDAP Auth to an active directory server, I can get as far as "user doesn't exist" errors. Has anyone solved this issue yet?

**Comment by JohnMcLear** [comment]
See Plugins for Active directory.
