### ISSUE TITLE
Support EPL installation in an apache subdir?

### ISSUE THREAD

**Issue by majoscho** [ether/etherpad-lite#3290]
i installed etherpad lite(1.6.1) on apache 2.4.18. (Mac OS X Server 10.11.6)
The tool works fine and is listing on port 9001.
Now i’m trying to get rid of this ugly port number in the url and put the etherpad in a sub directory.
Like: https://www.myintranetserver.org/etherpad/
I followed some tips, but i didn’t get it working.

I have now an apache configuration for etherpad like this:

```
ProxyVia On
ProxyRequests Off
ProxyPreserveHost on

<Location /ge>
RewriteEngine On
RewriteRule ^/ge$ /ge/ [R]
   ProxyPass http://141.xx.xx.195:9001 retry=0 timeout=30
   ProxyPassReverse  http://141.xx.xx.195:9001
   Options FollowSymLinks MultiViews
</Location>

<Location /ge/socket.io>
   RewriteEngine On
   RewriteCond %{QUERY_STRING} transport=websocket    [NC]
   RewriteRule /(.*) ws://localhost:9001/ge/socket.io/$1 [P,L]
   ProxyPass http://141.xx.xx.195:9001/ge/socket.io retry=0 timeout=30
   ProxyPassReverse http://141.xx.xx.195:9001/ge/socket.io
</Location>

<Proxy *>
   Options FollowSymLinks MultiViews
   AllowOverride All
   Order allow,deny
   allow from all
</Proxy>
```

The errors i get:
In Browser: 502 Proxy Error. The proxy server could not handle the request GET /ge/.
In apache's service_proxy_error.log: appears 
[Tue Dec 12 15:17:49.955002 2017] [ssl:info] [pid 33470] (70007)The timeout specified has expired: [client 141.xx.xx.195:59577] AH01991: SSL input filter read failed.

What do i wrong? 
Thanks in advance.
Marcus

**Comment by lpagliari** [comment]
Could you make it work without the subdirectory (only hiding the port number)? There's a wiki page for that: https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#apache

**Comment by majoscho** [comment]
Thanks for your answer and sorry for late response.
I tried to configure it as subdomain. But to do so, i need a new DNS entry and a new certificate. That's not so easy in my organisation, and this just for testing.
My guess it is about proxing the websocket.  And that would mean to alter something in the code.
