### ISSUE TITLE
Make writable folders (for keys, customization files and plugins) settable in configuration and/or cli

### ISSUE THREAD

**Issue by dvzrv** [ether/etherpad-lite#3293]
I have recently taken over maintenance of etherpad-lite for [Arch Linux AUR](https://aur.archlinux.org/packages/etherpad-lite) (first tries can be found in #3274).
Its current install files are [publicly accessible](https://aur.archlinux.org/cgit/aur.git/tree/?h=etherpad-lite).

Since 1.6.2 I have chosen a new route on how to create the package, incorporating the [StateDirectory](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=) settings offered since systemd 235, [systemd-sysusers](https://www.freedesktop.org/software/systemd/man/sysusers.d.html) and [systemd-tmpfiles](https://wiki.archlinux.org/index.php/Systemd#Temporary_files).

To understand the difference, it might be interesting to look at how etherpad-lite is currently being installed, which is more of a loose user based approach, that should not be used for system-wide applications.
The `bin/run.sh` script is run and calls `bin/installDeps.sh` to download and install dependencies and after that runs `src/node/server.js` using node.
During install the folder `node_modules` is created with the the symlink `ep_etherpad-lite -> ../src` in it.
During first run `APIKEY.txt` and `SESSIONKEY.txt` alongside `src/.ep_initialized` are created.
This approach requires an install directory writable to the user running `bin/run.sh`.

However, this is not how packages work.
They are not supposed to change their contents during runtime and if dynamic content is generated, it should reside in the runtime (e.g. /run) or state (e.g. /var/lib) directories.
Therefore, the etherpad-lite package was switched to a static install, i.e. its content directory is owned by root and not the specific user the software is run as. This in turn brings difficulties for a system-wide install, of which I could only workout some.

- etherpad-lite is installed under `/usr/share/etherpad-lite`, owned by _root_
- etherpad-lite's configuration and customization is installed under `/etc/etherpad-lite`, owned by _etherpad-lite_ user
- etherpad-lite's dynamic files are located in `/var/lib/etherpad-lite`, dynamically created by systemd service file and owned by _etherpad-lite_ user
- `server.js` is run via `node /usr/share/etherpad-lite/src/node/server.js --settings /etc/etherpad-lite/settings.json`
- `/usr/share/etherpad-lite/src/static/custom` is symlinked to `/etc/etherpad-lite/custom` to ensure configurability of its content
- `APIKEY.txt` and `SESSIONKEY.txt` are symlinked to `/var/lib/etherpad-light` to ensure, that they can be created during first run

While this all ensures, that files under `/usr/share/etherpad-lite` are only modified/created during build/install of the package, the downsides are obvious:

- plugins can not be installed, because `/usr/share/etherpad-lite` is rightfully owned by _root_.
- symlinks exist for the customization folder and the key files (initially dead)
- `settings.json` has to be patched to move creation of dirty.db to `/var/lib/etherpad-lite`

The last one is pretty much a non-issue, but the first two are show stoppers.
Therefore I'd like to get some feedback on whether it's possible to define a custom directory (e.g. below `/var/lib/etherpad-lite`) for the node_modules installable as plugins, the folder holding customizations (*.js and *.css) and the two key files.
This would greatly improve the package quality and the overall security of this software I think.

**Comment by dvzrv** [comment]
One consideration I forgot to mention regarding the modules:

Other distributions such as Debian (afaik) started packaging node modules system wide. This however is not something a small scale distribution such as Arch Linux can offer and additionally, I'm not sure whether etherpad-lite is able to recognize and facilitate those anyways.

Meeting half-way could be the installation of the `ep_*` by means of separate packages (but those would be plenty), installing below `/usr/share/etherpad-lite/src/node_modules/`.
This would still not be ideal, as the internal installation process could not be used.

So, ideally a (settable) separate installation directory for plugins would be the way to go.

**Comment by dvzrv** [comment]
@pluehne suggested symlinking the `APIKEY.txt` and `SESSIONKEY.txt` files to `/etc/etherpad-lite` instead of `/var/lib/etherpad-lite`.
As it seems, that they should be settable, is this a good idea?

**Comment by muxator** [comment]
Acknowledged, this is one of my pain points, too.

**Comment by muxator** [comment]
Plugins require a specific care (they are installed / loaded / uninstalled at runtime in `node_modules`). Opened #3593 for tracking that aspect.

**Comment by dvzrv** [comment]
Thanks, that's great to hear!

**Comment by dvzrv** [comment]
As mentioned in #3317 IMHO it's not a good idea to auto-close tickets by a bot. It will lead to noone finding this issue and/ or fix this issue (but I understand why you would want to close some of the many open tickets).
To my understanding #3936 has been opened to deal with some aspect of this. Therefore it doesn't make much sense to me to close this ticket (also as it is still very much relevant).
