### ISSUE TITLE
Uncaught TypeError on subsequent changes

### ISSUE THREAD

**Issue by poafernandes** [ether/etherpad-lite#3295]
So, recently I've been having some weird issues that I really don't know how to solve.

I've been getting some errors that prevent me from updating the pad's text. When I open the pad, I can write anything that I want. but as soon as I stop, the following changes aren't saved.

If I open the pad and change something with a plugin, like changing font size, or color, it also prevents me from adding more to the pad, since it stops saving and everything that I do now shows the following error on the run.sh console:

Uncaught TypeError: Cannot read property 'entry' of undefined -- { errorId: '0YrE3h1lS30uWySHY2JX',
  msg: 'Uncaught TypeError: Cannot read property \'entry\' of undefined',
  url: 'http://sideshowbob:9001/p/5a311ca415bfajjZ2yQvJ7Ga?lang=es&showLineNumbers=false&userName=Felipe%20Vianna',
  linenumber: 505,
  userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36' }

I've tried removing some plugins that I thought were conflicting, but so far nothing have worked, now the only plugins I have are the following:

![image](https://user-images.githubusercontent.com/30806203/34310648-da40396e-e73f-11e7-9349-0cc9796ffb3c.png)

Any tips or thoughts?

**Comment by lpagliari** [comment]
My suggestion would be to remove all plugins and check if the error happens when you add each of the plugins on your list -- yes, not ideal, but the error message is not very clear about where the issue would be.

BTW, do you have the `page_view` setting to insert automatic page breaks turned on?
