### ISSUE TITLE
Password protected Redis as database

### ISSUE THREAD

**Issue by poVoq** [ether/etherpad-lite#3298]
Hi!

I have Etherpad-lite running with Redis as explained here:
https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-Redis

But I would like to password protect my Redis for various reasons, see: https://redis.io/topics/security

Is that supported?

**Comment by nashe** [comment]
This is not documented in Etherpad but [it seems to be supported by the database layer](https://github.com/Pita/ueberDB/blob/master/redis_db.js#L37). Can you try to add a `password` member to the `dbSettings` object in your configuration?

**Comment by poVoq** [comment]
Sorry, can't test it for now as I am migrating my VPS. But thanks for looking into it, seems like it should work indeed.

**Comment by nashe** [comment]
Let me know the result and I'll update the documentation accordingly :-)

**Comment by moretocome** [comment]
I have just added a similar issue. Please see the syslog errors in #3349 

Thanks in advance :)
