### ISSUE TITLE
unix socket activation

### ISSUE THREAD

**Issue by dvzrv** [ether/etherpad-lite#3299]
This project could benefit from implementing [unix domain socket](https://en.wikipedia.org/wiki/Unix_domain_socket) activation, alongside the provided IP socket based setup.
Unix sockets are particularly useful, if etherpad-lite is run on the same machine as the web server (which very often is the case). Instead of communicating with a TCP/IP socket, a unix network socket is used, involving less overhead and context switches.

This approach could be settable in the configuration file (to be used instead of IP socket).

In such a scenario, instead of redirecting user traffic to the local TCP/IP port, it is pointed towards the inode representing the socket (e.g. `/run/etherpad-lite/etherpad-lite.sock`).
Etherpad-lite would be started by some other process accessing the socket and not started as a fixed system job.

Someone on the [AUR](https://aur.archlinux.org/) has created [a patched version of etherpad-lite](https://aur.archlinux.org/cgit/aur.git/tree/socket-activation.patch?h=etherpad-lite-systemd) a while ago.
I'm just wondering, whether it's really that easy...

**Comment by rhelmer** [comment]
This does look really easy, with the `systemd` and `autoquit` modules.

The only added complexity really is making it configurable, but that shouldn't be too hard.

I don't have time to do this myself right now but happy to mentor or review, looks like a really useful feature.
