### ISSUE TITLE
automatic quit on inactivity

### ISSUE THREAD

**Issue by dvzrv** [ether/etherpad-lite#3300]
This feature request goes somewhat hand in hand with #3299.
It would be very helpful, if etherpad-lite would quit automatically on inactivity (i.e. no user input on any pad and no logged in user for more than time `x`, whereas `x` will be configurable).

This would mean less ressource consumption over time and the possibility of a dynamic startup using (unix domain) socket activation.

Ideally, the process would quit with a `0` or `non-1` exit code.

**Comment by JohnMcLear** [comment]
What problem are you trying to solve here?

**Comment by dvzrv** [comment]
the pointless use of resources during inactivity?

**Comment by muxator** [comment]
PR #3312 addresses both socket activation (#3299) and automatic quit (this one).
