### ISSUE TITLE
bin/installDeps.sh - failing with unable to find `dezalgo` error

### ISSUE THREAD

**Issue by ArcticSnowman** [ether/etherpad-lite#3302]
Using the latest 1.6.2,  get the following error when trying to start up.  It seems to come from the installDeps.sh

```
[root@2274172dfbae etherpad]# bin/installDeps.sh
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm ERR! path /opt/etherpad/src/node_modules/npm/node_modules/dezalgo
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/opt/etherpad/src/node_modules/npm/node_modules/dezalgo' -> '/opt/etherpad/src/node_modules/npm/node_modules/.dezalgo.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-03T17_44_19_081Z-debug.log
```

Versions:
```
[root@2274172dfbae etherpad]# npm -v
5.6.0
[root@2274172dfbae etherpad]# node -v
v4.8.7
```

Any ideas?

**Comment by ArcticSnowman** [comment]
Maybe there's a problem in using npm 5.x with etherpad.

**Comment by ArcticSnowman** [comment]
`npm 4.0.2` works ..  so maybe this needs to be a request to update the dependencies again or add a warning in the docs about npm 5.x

**Comment by lpagliari** [comment]
I got some dependencies errors in the past (not with `dezalgo` though), so sometimes what worked for me was to install dependencies without sym links. Not ideal, but works:
```
npm cache clean
cd src
npm install --no-bin-links
```
If you get an error `Maximum call stack size exceeded`, run `npm install --no-bin-links` again.

**Comment by Doemela** [comment]
@lpagliari Did not work "delzago" error still there and prevent etherpad to run
npm version: 5.6.0
node version: 8.9.4
Debian 9

**Comment by Doemela** [comment]
I removed all package-lock.json files and run bin/installDeps.sh with success

**Comment by fspc** [comment]
@lpagliari I am wondering whether a better solution would be to modify bin/installDeps.sh to use yarn rather than npm? An earlier version of npm (5.5.1) was working without a glitch, that isn't the case with 5.6.0.

**Comment by lpagliari** [comment]
@fspc Looks good to me. Let us know if it worked for you.

**Comment by fspc** [comment]
@lpagliari Yes, that does the trick.  I will send a pull request that alters installDeps.sh so that if npm >= 5.6.0, yarn will be used, instead.

**Comment by revolunet** [comment]
to make it work with npm@5.6.0 : remove the `src/package-lock.json`

**Comment by dessalines** [comment]
Just running `bin/run.sh` twice in a row fails with current etherpad.
