### ISSUE TITLE
Index.js path traversal

### ISSUE THREAD

**Issue by coffeebreakerz** [ether/etherpad-lite#3303]
The javascript function go2Name() has a path traversal bug.
A user could enter a ../../something name for the etherpad name and then it will be redirected incorrectly.
This issue can be resolved through better input validation.

**Comment by nashe** [comment]
Do you think of the `go2Name` function from [`src/templates/index.html`](https://github.com/ether/etherpad-lite/blob/991155c8d4cc419bff276ddf7d52c133f1f076d1/src/templates/index.html#L177)? If yes, this code is only client-side and does not seem to create any risk.
