### ISSUE TITLE
Password protection: Not asked for a password

### ISSUE THREAD

**Issue by MPW1412** [ether/etherpad-lite#3304]
Hello,

for a private pad instance, I set sessions_required and authentication to true. And I set up a couple of users in the settings.json, which work perfectly in the admin area.

But accessing a normal pad is impossible. I'm not even asked for my credentials. EP just gives me "You do not have permission to access this pad".

I tried to access the admin page first. So a session should be established. Still no change to access any pad. I guess this is a bug?

I found a lot of howtos with proxies etc. I'm not using any proxy, just plain etherpad lite, but with ssl.

Regards,
Matthias

**Comment by lpagliari** [comment]
What's the value of the `editOnly` setting? Is it set to `true`?

If you set `sessions_required` to `false`, do you still get the message "You do not have permission to access this pad"?

**Comment by MPW1412** [comment]
Yes, that's it. The require session seems to be something else. Just require authentication does the trick.
