### ISSUE TITLE
Expiry Time API

### ISSUE THREAD

**Issue by kousu** [ether/etherpad-lite#3305]
For integration with nextcloud (via ownpad) or sandstorm or other wrappers, I think there needs to be an API that can at least read, and maybe write, the expiry time for a document. Or, at least, for integrating a pad into one of these cloud-storage wrapper systems, we need a way to mark sheets as non-expiring.

See otetard/ownpad#47

**Comment by JohnMcLear** [comment]
I think this is just confusion and can be closed.
