### ISSUE TITLE
Feature request: view pad content without javascript enabled

### ISSUE THREAD

**Issue by metamorforme42** [ether/etherpad-lite#3306]
Hello, this is a feature request:

As an user, I would like to be able to view a pad content without enabling javascript.
This feature will allow me to read the content of a pad (like I can do with any others pure html+css pages) and enable javascript only if I want to edit this pad.

Best regards – metamorforme42.

**Comment by rhelmer** [comment]
I'd be interested in this too. There are many advantages to being able to serve pads as static content, it works with more systems (simpler agents like curl), makes first-load faster, and so on.

**Comment by JohnMcLear** [comment]
So basically the HTML export endpoint (with authorship colors) that doesn't download the file?

**Comment by raybellis** [comment]
I'd like this too, so that we can archive off formatted copies of historic pads (including authorship colours) and trim down our database.
