### ISSUE TITLE
Request: Publish new release because of security vulnerability in EJS

### ISSUE THREAD

**Issue by pluehne** [ether/etherpad-lite#3307]
I just built Etherpad Lite 1.6.2 from sources, and I got a warning that EJS 2.4.1 is vulnerable:

```
npm WARN deprecated ejs@2.4.1: Critical security bugs fixed in 2.5.5
```

I’m aware of your bugfix in bb11d014ab7f3e025ccf951ea7c43345498c86e3. However, there still isn’t a new release of Etherpad Lite with EJS ≥ 2.5.5 (which is already over a year old). I have reservations running Etherpad Lite with vulnerabilities known for this long 😅.

For this reason, I’d suggest publishing a security release of Etherpad Lite, even if it wouldn’t contain any important new features 😄. Thanks!

**Comment by lpagliari** [comment]
@Gared this looks like an important fix indeed, I think we should release it. If you need any help on this, please let me know.

**Comment by lpagliari** [comment]
Thanks, @Gared ! @pluehne [version 1.6.3 is available](https://github.com/ether/etherpad-lite/releases/tag/1.6.3)

**Comment by pluehne** [comment]
@Gared, @lpagliari: Thanks for taking care of this quickly 😄! I’ll notify the Arch Linux maintainers.
