### ISSUE TITLE
Error: secret option required for sessions on empty SESSIONKEY.txt

### ISSUE THREAD

**Issue by dvzrv** [ether/etherpad-lite#3317]
When the `SESSIONKEY.txt` file is an empty file, it will generate a `Error: secret option required for sessions`.

However, smarter would be to write a new secret to that file and then use it, instead of failing.

**Comment by JohnMcLear** [comment]
What would cause the SESSIONKEY.txt file to be empty?  Surely that is something done by the sysadmin intentionally?  If so, how about not doing that?

**Comment by muxator** [comment]
My current understanding is:

on a freshly started Etherpad, when the first client connects, the server tries to read `SESSIONKEY.txt`.

1. if `SESSIONKEY.txt` exists and is not empty, everything is fine
2. if `SESSIONKEY.txt` does not exists, a random one is created, and everything goes on
3. if `SESSIONKEY.txt` exists but is 0 bytes, the session crashes

Given point 2, point 3 seems surprising to me: almost a missed edge case.

Example log:
```
[2018-04-10 23:10:38.999] [ERROR] console - Error: secret option required for sessions
    at session ([...]/src/node_modules/express-session/index.js:167:12)
    at Layer.handle [as handle_request] ([...]/src/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix ([...]/src/node_modules/express/lib/router/index.js:312:13)
    at [...]/src/node_modules/express/lib/router/index.js:280:7
    at Function.process_params ([...]/src/node_modules/express/lib/router/index.js:330:12)
    at next ([...]/src/node_modules/express/lib/router/index.js:271:10)
    at [...]/src/node_modules/log4js/lib/connect-logger.js:103:5
    at Layer.handle [as handle_request] ([...]/src/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix ([...]/src/node_modules/express/lib/router/index.js:312:13)
    at [...]/src/node_modules/express/lib/router/index.js:280:7
```

**Comment by igalic** [comment]
Another problem, and the reason why you would want to just create those files and have etherpad write them is that otherwise, you'd have to give the application user write access to the entire application home directory.

Of course these things could be circumvented, but that's all a step, by step, by step process, rather than something that can be done declaratively.

**Comment by dvzrv** [comment]
@muxator I understand that you would like to have less tickets on this repo, but just auto-closing them by a bot is also not the way to go.
This will neither fix the issue nor show anyone that there is an issue. IMHO it's really not the best practice to deal with problems :S

**Comment by JohnMcLear** [comment]
See stale.yml.  it does not stale bugs.

**Comment by dvzrv** [comment]
Then maybe it would be a good idea to add a bug label to this ticket?
The issue leads to a crash after all, when following best practices for safe packaging on a Linux distribution. It also means that the `SESSIONKEY.txt` can not be tracked as a file that should be backed up by the package manager (because it can not be created as an empty file).

**Comment by muxator** [comment]
> @muxator I understand that you would like to have less tickets on this repo, but just auto-closing them by a bot is also not the way to go

Hi @dvzrv: I agree with you, I do not think auto-closing stale tickets makes them disappear. This was not my choice. But I do not have the right to object, because, I am currently on "extended leave" for at least another month, and @JohnMcLear is taking care of the repo.

**Comment by JohnMcLear** [comment]
@muxator see stale.yml.  I'm closing plugin requests and feature requests that no one has picked up.

**Comment by mikkorantalainen** [comment]
I know this is an old issue but I'll comment for future package devs:

- The Package should install a symlink from installation directory `SESSIONKEY.txt` to e.g. `/etc/etherpad/SESSIONKEY.txt`.
- The package should include empty *configuration* file /etc/etherpad/SESSIONKEY.txt **if package manager doesn't allow creating symlinks to missing files.** I think it's better if the file is not included in the package at all if package manager cannot handle upgrading the package without bothering the user about modified file that was originally empty. For modern Debian based systems it would be okay to include empty configuration file in the package and update its value via postinst or via systemd launch script.
- Package should include e.g. `postinst` (after/post installation script) which checks for empty or missing `/etc/etherpad/SESSIONKEY.txt` and if so, generate random content for that file.
