### ISSUE TITLE
Is the plugin list stucked?

### ISSUE THREAD

**Issue by ldidry** [ether/etherpad-lite#3323]
Hello,

The plugin list seems stucked: ep_mypads 1.2.0 has been released a couple of weeks ago and https://static.etherpad.org/plugins.json still shows ep_mypads at 1.0.5 version.

Can somebody look after the script/cron task/whatever that updates the list please?

**Comment by JohnMcLear** [comment]
@Gared

**Comment by JohnMcLear** [comment]
Looks tha tway
```
/usr/bin/env: ‘node’: No such file or directory
/home/xxxx/ep-plugins/node_modules/npm/lib/cache/update-index.js:61
            var t = +data._updated || 0
                         ^

TypeError: Cannot read property '_updated' of undefined
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by JohnMcLear** [comment]
Looks like npm broke search results.

**Comment by JohnMcLear** [comment]
fixed with ``npm config set searchlimit 5000``

**Comment by ldidry** [comment]
Where is the code of the script please? I could have a look.

**Comment by JohnMcLear** [comment]
The crux of it is

```
npm.load({}, function (er) {
  if (er) console.error(er);
  npm.commands.search(['ep_'], true, function(er, results) {
    console.log(results);
  })
})
```

**Comment by muxator** [comment]
Still relevant, isn't it?

**Comment by JohnMcLear** [comment]
Well npm is fundamentally broken so yea ;\  They changed the search API essentially breaking the way we implement plugins..  I could report to Matt or Isaac but pretty sure our bastardized approach to work around the early API will be disregarded as a suboptimal approach so I doubt a fix will come upstream..

No fix in sight imho.

**Comment by ezzra** [comment]
Does this only affect the overview or does it mean, that all installed plugins are always out of date? Does it help, not to install via Webfrontend but via `npm install`?

**Comment by lpagliari** [comment]
@ezzra I'm not sure this is what you've asked, but the plugins you have on your Etherpad instance need to be updated, they are not automatically upgraded.

**Comment by ezzra** [comment]
@lpagliari no I was asking, if just the plugin overview list shows the wrong versions, or if plugins are actually out of date when installed. I just ordered the webfrontend pluginlist by last_update, and the most current plugin is ep_padwiki from **2017-05-04** !

As I now have found out, there is a more recent version of padwiki. So, I would like to try what happens when I click install, if it will try to install te most recent version or the one from 2017. Unfortunately it doesn't work at all because of an error, so I would need to check that out first before testing what version is installed.

**Comment by Gared** [comment]
I rewrote the script to update the script for collecting all ep-plugins and their versions. Please have a look, try it out and report any missing or wrong plugins

**Comment by ezzra** [comment]
mh, now the last edited row is empty in my etherpad instance :)

**Comment by Gared** [comment]
@ezzra Thx, I've fixed it. Maybe it takes some time until the new version has been downloaded from you're instance

**Comment by muxator** [comment]
@gared, can we close this?

**Comment by Gared** [comment]
@muxator Yes, I think we can close this issue
