### ISSUE TITLE
dezalgo bug

### ISSUE THREAD

**Issue by Skarm54** [ether/etherpad-lite#3324]
Hello,
I'm having a bug on etherpad
I explain when I start Etherpad for the first time no problem it works but when I do Ctrl + C to turn it off and I turn it on again it puts me this error:
https://pastebin.com/23cq064d
How to adjust this?
thank you in advance

**Comment by 0ip** [comment]
Consider it as a non-ideal interim solution only:
```bash
rm -rf node_modules/
npm i npm@4 -g
```

**Comment by Skarm54** [comment]
thanks you very much
it's works
