### ISSUE TITLE
Provide right click menu in text editor mode

### ISSUE THREAD

**Issue by rasos** [ether/etherpad-lite#3329]
Several users have asked to offer right click functions such as copy or paste highlighted text, as available in most text editors. 

An intermediate solution could be that we have a plugin that is showing text snippets as soon as you clik the right mouse button, such as 
   Ctrl-C = copy
   Ctrl-P = Paste
   Ctrl-X = Cut 
(which is not true for OS X and would need i18n).

**Comment by lpagliari** [comment]
Hi, @rasos , this looks more like a plugin feature, not a core one.

BTW, I don't think we should override the default context menu, as there might be other functions on the browser that are used often, and that we are not aware of. Eg: translations, dictionary, search on Google, speech, etc. Once we override the context menu, we're disabling these features.

**Comment by JohnMcLear** [comment]
+1 @lpagliari
