### ISSUE TITLE
Where is the code of https://beta.etherpad.org？

### ISSUE THREAD

**Issue by TangXT** [ether/etherpad-lite#3332]
Where is the code of https://beta.etherpad.org？
I hava installed etherpad with the Branch develop, but I find it different with the demo  https://beta.etherpad.org

**Comment by 0ip** [comment]
That's because it uses some plugins.

See https://static.etherpad.org/plugins.html for available plugins and https://github.com/ether/etherpad-lite/wiki/Available-Plugins that explains how to install them.

If you like the page view on beta.etherpad.org, take a look at https://github.com/ether/ep_page_view

**Comment by TangXT** [comment]
Could you tell me what plugins it uses？

**Comment by lpagliari** [comment]
I know some, but not all:

- ep_headings2
- ep_font_color
- ep_font_size
- ep_font_family
- ep_comments
- ep_page_view
- ep_text_statistics
- ep_themes
- ep_desktop_notifications

**Comment by TangXT** [comment]
While I upload a .doc or a .docx files, It shows that Import failed,Please copy paste. That's why? @lpagliari @0ip

**Comment by lpagliari** [comment]
https://github.com/ether/etherpad-lite/wiki/How-to-enable-importing-and-exporting-different-file-formats-with-AbiWord

**Comment by TangXT** [comment]
@lpagliari Thank you for your reply. I had done this as https://github.com/ether/etherpad-lite/wiki/How-to-enable-importing-and-exporting-different-file-formats-with-AbiWord
on Debian, with sudo installed and www-data being the web server, one can edit /etc/sudoers and add the following for an AbiWord installation folder of /usr/bin/abiword.

www-data ALL = NOPASSWD: /usr/bin/abiword

But it also dosen't work, While I upload a .doc or a .docx files, It shows that Import failed,Please copy paste. 
and My  files:
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults    env_reset
Defaults    mail_badpass
Defaults    secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL:ALL) ALL

# Allow members of group sudo to execute any command
%sudo    ALL=(ALL:ALL) ALL
www-data ALL = NOPASSWD: /usr/bin/abiword
# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
