### ISSUE TITLE
Etherpad in cluster!

### ISSUE THREAD

**Issue by anugu-chegg** [ether/etherpad-lite#3335]
With current implementation etherpad cannot run in a cluster mode. 

Here are the issues with the current implementation:

1. Uber db's Caching layer
2. Cache of loaded pads
3. Storing client sessions locally (sessioninfos)
4. Socket.io - Rooms and client sessions are associated with a particular instance

Possible solutions for handling above issues:

1. Cache layer can be removed from uberdb. I have raised a PR for this https://github.com/Pita/ueberDB/pull/104
2. Logic for loading pad needs to be changed. Everytime a pad is requested, it needs to be served directly from the db.
3. Use socket.io-emitter https://github.com/socketio/socket.io-emitter to send and receive session updates across all nodes in the cluster.
4. Use socket.io-redis https://github.com/socketio/socket.io-redis for storing room and client information in a separate redis server

**Comment by jainendra** [comment]
Yeah, this looks promising. It would be great to see etherpad running in cluster. It could be next big thing for etherpad.
Some suggestion:
I see there's a problem with ueberDB caching when running etherpad in cluster, one alternative could be to use redis or memcache for storing cache.

I am not sure if socket.io-reddis is reliable or not. What do you think about all this @Gared ?

**Comment by jgribonvald** [comment]
Hi,
How is going on for this issue ? Someone have done something ? It would be really great to be able to do that !

**Comment by jmaupetit** [comment]
Hey @jgribonvald :wave: I was also about to raise a hand in this issue :wink: 

We are trying to use `redis` as a socket.io communication layer in a k8s context, and we are having issues with some events: not all events are sent to redis. It seems that chat-related events are, but not pad changes.

Our WIP: https://github.com/openfun/etherpad-docker/pull/8

This project has been deployed in our OpenShift cluster (see: https://pad.education) but scaling is an issue.

I have the feeling that we need to modify the code to achieve this. Any advice would be greatly appreciated.

Thanks for your work on this project :pray:
