### ISSUE TITLE
etherpad-lite is extremely easy to crash with Unicode emojis

### ISSUE THREAD

**Issue by martinvonwittich** [ether/etherpad-lite#3340]
To reproduce the issue:

1. Open this page in a browser to get some Unicode emojis: https://unicode.org/emoji/charts/full-emoji-list.html
2. Copy a random emoji from the "Browser" column into your clipboard
3. Paste the emoji into a pad
4. Position the cursor behind the emoji and press backspace
5. Etherpad crashes:

```
[2018-03-08 16:39:39.657] [ERROR] console - error: invalid byte sequence for encoding "UTF8": 0xed 0xa0 0xbd
    at Connection.parseE (/usr/share/etherpad-lite/src/node_modules/ueberdb2/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/usr/share/etherpad-lite/src/node_modules/ueberdb2/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/usr/share/etherpad-lite/src/node_modules/ueberdb2/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10)
```

We have the issue in the pretty ancient version 1.5.7, but apparently the current version is still affected, because I can reproduce it on beta.etherpad.org. Sorry for crashing your demo site :/

**Comment by caugner** [comment]
I can confirm this issue with etherpad-lite 1.6.3 and MariaDB 15.1 with utf8mb4 / utf8mb4_general_ci.

**Comment by martinvonwittich** [comment]
We use etherpad-lite 1.5.7 with both postgres 9.4 and postgres 9.6, so it's most probably not database-dependant.

**Comment by caugner** [comment]
> Etherpad crashes:

What exactly do you mean by crash? For me, the emoji only corrupts the current pad, which cannot be loaded anymore after restarting etherpad (which is obviously due to caching, see #2107).

**Comment by caugner** [comment]
@JohnMcLear Do you have advice on how to avoid/fix this problem? In #2107 you mentioned that [there might be a fix](https://github.com/ether/etherpad-lite/issues/2107#issuecomment-68359114).

**Comment by caugner** [comment]
```
// Paste emoji.
pad:emoji-test:revs:6 - {"changeset":"Z:1>2*0+2$😎","meta":{"author":"a.7O43iZgpsTGm4cFi","timestamp":1520601291592}} - to buffer

// Backspace.
pad:emoji-test:revs:7 - {"changeset":"Z:3<1=1-1$","meta":{"author":"a.7O43iZgpsTGm4cFi","timestamp":1520601296408}} - to buffer

// Backspace again.
pad:emoji-test:revs:8 - {"changeset":"Z:2<1-1$","meta":{"author":"a.7O43iZgpsTGm4cFi","timestamp":1520601298102}} - to buffer
```

Afaik the problem lays in the changeset of adding the emoji, which is recorded as adding two characters: `Z:1>2*0`**+2**`$😎`.

**Comment by caugner** [comment]
Okay, I wasn't aware that

```js
"😎".length == 2
```

So it depends whether changesets are supposed to operate on code points or characters. Two solutions:

1. Make changesets operate on characters. Adding an emoji would add one character and backspace would remove one character.
2. Let changesets operate on code points, but fix removing characters with multiple code points (see below).

Removing one character currentlyl assumes a length of 1:

**Comment by martinvonwittich** [comment]
> What exactly do you mean by crash? 

In our case, Etherpad crashed completely, ie the node process terminated.

1. Before reproducing the issue:

	```
	stable.iserv.eu ~ # systemctl status etherpad-lite.service 
	● etherpad-lite.service - LSB: starts etherpad lite
	Loaded: loaded (/etc/init.d/etherpad-lite)
	Active: active (running) since Do 2018-03-08 16:42:26 CET; 22h ago
	CGroup: /system.slice/etherpad-lite.service
			├─18834 node node_modules/ep_etherpad-lite/node/server.js
			└─18844 /usr/bin/abiword --plugin AbiCommand

	Mär 08 16:42:26 iserv.stable.iserv.eu etherpad-lite[18830]: Starting Etherpad Lite...
	Mär 08 16:42:26 iserv.stable.iserv.eu etherpad-lite[18830]: done
	Mär 08 16:42:26 iserv.stable.iserv.eu systemd[1]: Started LSB: starts etherpad lite.
	
	stable.iserv.eu ~ # ps aux|grep etherpad
	root      2813  0.0  0.1  14220  2268 pts/1    S+   15:01   0:00 grep --colour=auto etherpad
	etherpa+ 18834  0.2  5.0 1024284 104476 ?      Sl   Mär08   2:52 node node_modules/ep_etherpad-lite/node/server.js
	postgres 18843  0.0  0.5 107592 11920 ?        Ss   Mär08   0:00 postgres: etherpad etherpad [local] idle                                                                                    
	
	stable.iserv.eu ~ # tail /var/log/etherpad-lite/etherpad-lite.log
	stable.iserv.eu ~ # 
	```

2. After reproducing the issue:

	```
	stable.iserv.eu ~ # systemctl status etherpad-lite.service
	● etherpad-lite.service - LSB: starts etherpad lite
	Loaded: loaded (/etc/init.d/etherpad-lite)
	Active: active (exited) since Do 2018-03-08 16:42:26 CET; 22h ago

	Mär 08 16:42:26 iserv.stable.iserv.eu etherpad-lite[18830]: Starting Etherpad Lite...
	Mär 08 16:42:26 iserv.stable.iserv.eu etherpad-lite[18830]: done
	Mär 08 16:42:26 iserv.stable.iserv.eu systemd[1]: Started LSB: starts etherpad lite.
	```

	```
	stable.iserv.eu ~ # ps aux|grep etherpad                  
	root      2954  0.0  0.1  14220  2092 pts/1    S+   15:04   0:00 grep --colour=auto etherpad
	```

	Hm, but for some reason, this time it didn't log anything:

	```
	stable.iserv.eu ~ # tail /var/log/etherpad-lite/etherpad-lite.log
	stable.iserv.eu ~ # 
	```

We then have to restart Etherpad to get it running again (`systemctl restart etherpad-lite.service`). The pad itself doesn't seem to be damaged; I can open it after having restarted Etherpad, and the emoji looks fine again. Apparently it crashed before it was able to save the damaged UTF-8 data.

**Comment by caugner** [comment]
> In our case, Etherpad crashed completely, ie the node process terminated.

If your Etherpad instance crashes, while mine doesn't, I assume that etherpad-lite has been made more robust between your version (1.5.7) and mine (1.6.3). Have you considered updating to the latest version (which includes security fixes)?

> Hm, but for some reason, this time it didn't log anything:

Have you tried setting `"loglevel": "DEBUG",` in `settings.json` while reproducing the issue? I have obtained my logs by running `journalctl -f | grep <name-of-pad>`.

**Comment by martinvonwittich** [comment]
> Have you considered updating to the latest version (which includes security fixes)?

Yes, we're planning to replace our old etherpad-lite installation with the official docker image soonish :)

What about beta.etherpad.org? I assumed it would use the most recent version, but as far as I can tell, it's still broken since I reproduced the issue there yesterday. Maybe it needs updating too ^^

**Comment by akosiaris** [comment]
I can not reproduce this on https://etherpad.wikimedia.org/p/ohmy. Per https://github.com/wikimedia/puppet/blob/production/modules/etherpad/templates/settings.json.erb `charset` is set to `utf8mb4`. Backend db is `10.0.23-MariaDB`.

**Comment by alexis-renard** [comment]
Hi, any updates here ? It seems (after some tests on multiple pads), that it makes all the pads crashing when one pad is corrupted by an emoji. And that produces a lot of reloading + 502 errors that makes the use of the pads pretty difficult on real time note taking. It seems that fixes had been found around, but not up to date here. Thanks 😄 !

**Comment by JohnMcLear** [comment]
I guess the update is to use the correct database encoding as per the installation instructions?

**Comment by pichouk** [comment]
I successfully reproduced the bug on my Etherpad instance.

Then I checked [this documentation page](https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL) where it is recommended to add `"charset" : "utf8mb4"` to database settings on `settings.json`. It worked for me, I am not able to reproduce now.
