### ISSUE TITLE
Problems using setHTML

### ISSUE THREAD

**Issue by poafernandes** [ether/etherpad-lite#3343]
I've been using a script to get texts that have been saved as HTML and save them on Etherpad, the problem is that everything that I try to input for setHTML gets returned as malformed.

Here's a example from one of the HTML's that is being rejected

`<! DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"><html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><base target="_blank" /></head><body><font style="font-family: Verdana;" size="5"><span style="font-weight: bold; text-decoration: underline; font-style: italic; color: rgb(255, 153, 0);">kkk</span></font></body></html>`

I also attached a  print from the console below

![capture](https://user-images.githubusercontent.com/30806203/37221606-574ed532-23a9-11e8-89e8-cff8619aa003.JPG)

**Comment by joassouza** [comment]
can you test with a HTML like 
`<html><body><div><span>test</span></div></body></html>`?

**Comment by lpagliari** [comment]
The log states that the error is on `ep_page_view/blob/master/static/js/shared.js` (not on Etherpad, by the way), but there's no `indexOf` on the [latest version](https://github.com/ether/ep_page_view/blob/master/static/js/shared.js) of this plugin. Do you know which version of `ep_page_view` you're using?

**Comment by poafernandes** [comment]
@joassouza it still gives me the same error

@lpagliari 0.5.24 is the version that I'm using

**Comment by poafernandes** [comment]
So, I've just downgraded ep_page_view to 5.23 and now it works. :+1:

**Comment by joassouza** [comment]
As it seems to be an issue of the plugin, not the Etherpad, can you close it? Feel free to report the error on the ep_page_view =)
