### ISSUE TITLE
Assign specific configs to single pad

### ISSUE THREAD

**Issue by jeyca** [ether/etherpad-lite#3346]
When I open a Pad I can se some configs like "Page View" or "Autoship Colors". But this is only set for my session, I would like to assign it to the specific pad, so everyone who uses this Pad will have these settings as default (and can change it for his/her session if wanted)

**Comment by nashe** [comment]
As far I know, the setting `padOptions` is what you are looking for:
https://github.com/ether/etherpad-lite/blob/cb856ea6246f2db206eae9f9e9b6e4193612f01d/settings.json.template#L61-L74

**Comment by jeyca** [comment]
No, thats not what I meant. I want to save configs for single pads, not to change the global Etherpad settings (the issue title was misleading). Currently, changed settings are only saved for the user session, not for the single pad itself.

**Comment by JohnMcLear** [comment]
This sounds like a horrible use case.  You can export a URL with pad settings set IE https://beta.etherpd.org/p/test?noColors=true -- Do that instead?

**Comment by jeyca** [comment]
> This sounds like a horrible use case.

don't think so. Most pad users are unexperienced with the software and servers behind it. People who set up a Pad could personalize it this way for their specific usecase.

> You can share a URL with pad settings

thats quite ok workaround, just uglifys urls. But well, works
