### ISSUE TITLE
newline inserted at some keystroke 

### ISSUE THREAD

**Issue by PhilLAL** [ether/etherpad-lite#3350]
Hi there,
I noticed since a few months/years that a newline appears sometimes when a key is striked.
It appears when several person are typing on the same pad, and each of us noticed the issue when s·he strike a key with the cursor in an unordered list.
Newline deletion also make appear a newline most of the time when this bug occurs.
After 3 person close the tab, the issue is still present for the 4th person.

However, this bug occurs not always occurs so I can not send a complete bug report.
This issue occurs from Firefox 59.0.1 64 bits on ubuntu, Firefox 52.7.2 on debian 9, and Chrome 65.0.3225.181 on Windows 10.
The server used is https://framapad.org (version 1.5.7 with PostegreSQL, more precision about plugins in french on page https://framacloud.org/fr/cultiver-son-jardin/etherpad.html#concernant-framapad)

This issue is very annoying since we loose much time when collaborativly working.
Thank you.

**Comment by PhilLAL** [comment]
After some cross tests, it seems closing the pad on each computer but one make the bug disappear.
Opening again the pad on some computer works if the computer with 200 opened tab does not open the pad. 
I am absolutly not sure this means this issue is linked to the 200 opened tabs?

**Comment by JohnMcLear** [comment]
Unable to replicate.  If you can replicate on a clean instance with no plugins please let us know.
