### ISSUE TITLE
copy-paste changes author 

### ISSUE THREAD

**Issue by PhilLAL** [ether/etherpad-lite#3351]
Hello,
we noticed an issue when copy-paste on a pad used by 4 users: the line just after become attributed to the author which pasted a test.
This issue occurs in an unordered list. 

This bug occurs not always occurs so I can not send a complete bug report.
This issue occurs from Firefox 59.0.1 64 bits on ubuntu, Firefox 52.7.2 on debian 9, and Chrome 65.0.3225.181 on Windows 10.
The server used is https://framapad.org (version 1.5.7 with PostegreSQL, more precision about plugins in french on page https://framacloud.org/fr/cultiver-son-jardin/etherpad.html#concernant-framapad)

Do you have any idea how to solve this?
Thank you.

**Comment by PhilLAL** [comment]
After some cross tests, it seems closing the pad on each computer but one make the bug disappear.
Opening again the pad on some computer works if the computer with 200 opened tab does not open the pad. 
I am absolutly not sure this means this issue is linked to the 200 opened tabs?

**Comment by JohnMcLear** [comment]
Feels like a duplicate bug report..  Please check

**Comment by PhilLAL** [comment]
If you think it is a duplicate from #3350 I confirm this is a **different** issue. :)

**Comment by PhilLAL** [comment]
@JohnMcLear could you confirm this was the issue you though of? If not, what issue is it?
Thanks

**Comment by JohnMcLear** [comment]
Please provide exact steps to replicate or a test case (in spec js file).

Also please confirm you can replicate without plugins.

**Comment by PhilLAL** [comment]
Sorry, it seems fixed. Thank you for your fast answer
