### ISSUE TITLE
File Drop on Header breaks Page

### ISSUE THREAD

**Issue by renebrain** [ether/etherpad-lite#3355]
When you Drag & Drop a file from your OS into the Header Element of the etherpad (see gif),it accepts the file and lets the browser open it / Or try to download it, which breaks everything for the user. Can this somehow be prevented? It happens on Linux & Windows with FF and Chrome (Haven't tested anything else) with your demo, the sandstorm demo and the primarypad demo as well.

Dropping into the text is just getting ignored by etherpad (That is the behaviour that we would expect from the header aswell)

![header bug](https://user-images.githubusercontent.com/9963399/38017410-3f3ce1c8-3272-11e8-8060-3dbebd62775d.gif)

**Comment by JohnMcLear** [comment]
Dropping a file onto the browser's normal behavior is to load it and this is what you are experiencing...  I don't think we have plans to integrate drag and drop uploads to the editor but will put this in as a feature request...

**Comment by renebrain** [comment]
why is this closed? i don't understand. I don't want that functionality  but what i can see is, that dropping into the etherpad contenteditable the drop is getting prevented, but not on the header, which means a user can break an etherpad app by accidentally dropping something on the header. shouldn't that behaviour be forbidden? What is the intention behind accepting the drop event on the header in the first place?
