### ISSUE TITLE
etherpad + Odoo - CORS error after upgrade on Firefox 52.7.3

### ISSUE THREAD

**Issue by cataclysmic** [ether/etherpad-lite#3365]
I did an upgrade of the Etherpad installation from git today.
 Etherpad-lite is integrate via its API with Odoo.
However, since the upgrade I get a CORS error on Firefox 52.7.3 32Bit ESR Windows release when calling pads from Odoo. It's no problem in Internet Explorer, though.
Odoo runs on port 8069 and etherpad on 9001 but both on the same server.

TBH I don't have clue where to start looking to fix the issue.

Thanx for any help in advance.

**Comment by JohnMcLear** [comment]
Best bet is to do a git bisect and find out where the bug was introduced.

http://mclear.co.uk/2013/04/02/using-git-bisect-to-debug-etherpad-issues/

**Comment by cataclysmic** [comment]
Thanx. Will have access to the system again on Monday. Will report back then.

**Comment by cataclysmic** [comment]
I apologize for the hassle.
Etherpad-lite is fine. The 'ep_fullscreen' module caused the error.
I will talk to the module maintainer.
Thank you for the quick reply and help.
