### ISSUE TITLE
Data loss after uprading to 1.6.4 ?

### ISSUE THREAD

**Issue by hrefhref** [ether/etherpad-lite#3370]
Hello,

I upgraded etherpad.fr to 1.6.4 this morning and some users reported me data loss up to three hours prior of the upgrade. What could have done that ? Is there another way to update properly instead of just pulling the code and running it again?

Thanks.

**Comment by nashe** [comment]
Which database backend are you using?

**Comment by hrefhref** [comment]
Sorry, forgot to tell. I use MySQL.

**Comment by JohnMcLear** [comment]
There is no logic tha tallows data loss and this was the only report so probably database configuration / failure of sync.
