### ISSUE TITLE
Line numbers visual alignment broken in 1.6.4+

### ISSUE THREAD

**Issue by akosiaris** [ether/etherpad-lite#3378]
Starting with 1.6.4 it seems like the line numbers no longer visually align with the lines they refer to. Looking at a brad new pad created on 1.6.4 and 1.6.5 it's clear that lines 3-4 and 5-6, 7-8 visually correspond to a single line. This is confusing at the very least and makes it difficult to refer to specific lines. A regression IMHO

![38684085-314dea9a-3e6f-11e8-8fb1-b19a96a563aa](https://user-images.githubusercontent.com/814130/38725432-fb89c8c4-3f0f-11e8-81d7-c47714e74573.gif)

**Comment by muxator** [comment]
This is due to #3280, merged in f15c7d7186db.
