### ISSUE TITLE
"Unaligned" line numbers

### ISSUE THREAD

**Issue by roman-soft** [ether/etherpad-lite#3379]
Hi,

I've upgraded from v1.6.2 to v1.6.5 (6dc8ead).

Before upgrade, line numbers were aligned to text.

After upgrade, I'm getting "unaligned" line numbers, as in the following image:

![pad_unaligned_numbers](https://user-images.githubusercontent.com/6954870/38811534-13140a64-418a-11e8-924d-c9a3bfa5dbb4.png)

Why? Is it expected behaviour? Is it fixable?

Thanks in advance for your time.

**Comment by roman-soft** [comment]
Just to clarify. Before upgrade, line numbers were exactly at the same high as the corresponding text line.

**Comment by slel** [comment]
See #3378

**Comment by roman-soft** [comment]
Yes, it's dupped from #3378. Sorry.

I checked issues few days ago, and it didn't exist but till now I hadn't had time to write the ticket and didn't re-check, so... race condition! ;-)))

I'm closing this ticket. Thank you.
