### ISSUE TITLE
Persist author name automatically?

### ISSUE THREAD

**Issue by scttnlsn** [ether/etherpad-lite#3381]
Based on my experimentation with Etherpad it seems like even if I pass a `userName` URL parameter when embedding an Etherpad, that value is not persisted and visible to other users to see until explicitly choosing a user color and clicking "Save".  Am I understanding this correctly?  Is there a way to persist the `userName` value automatically when the pad is loaded?

Alternatively, is there some way I can update the author's name w/o requiring explicit actions from the user?  I did not see any sort of HTTP API to do this.

**Comment by muxator** [comment]
As a user, I always had this desire, too.

I encourage you to try to write a PR for this functionality, limiting it to the case of authenticated users.
