### ISSUE TITLE
Add an index on some DB backends?

### ISSUE THREAD

**Issue by ldidry** [ether/etherpad-lite#3382]
Hello,

At [Framasoft](https://framasoft.org), we have a ±100GiB PostgreSQL database for our Etherpad instance with MyPads plugin (more than 100,000 pads). MyPads uses the `store` table of Etherpad to store data. I needed to search some of those data (say `SELECT * FROM STORE WHERE key LIKE 'mypads:user:%';`) and it was horribly slow. After some tests, I added an index on the `key` column and the time dropped from more than 2 minutes to less than 100ms.

I added this index:

```sql
CREATE INDEX pattern_idx ON store (key varchar_pattern_ops);
```

Since Etherpad do some queries similar to the one I used, I think Etherpad should benefit of such index.

What do you think? Should it go in Etherpad do you think it should go in UeberDB?

**Comment by nashe** [comment]
Somehow related: https://github.com/ether/etherpad-lite/issues/1957. Anyway, I think this issue belongs to https://github.com/Pita/ueberDB/ :-)
