### ISSUE TITLE
Etherpad cannot handle its own shortcut keys with Firefox Nightly

### ISSUE THREAD

**Issue by masayuki-nakano** [ether/etherpad-lite#3383]
Firefox is now trying to conform to the latest keypress event spec, that is, keypress event should be dispatched only when a key press produces a character input (e.g., typing 'KeyA', 'Space', etc) and Enter key press (Enter, Shift+Enter and Control+Enter for compatibility both with backward and the other browsers). I.e., 'Tab', Shift + 'Space', Ctrl + 'A' etc won't cause keypress event even on Firefox too. You can test this with setting "dom.keyboardevent.keypress.dispatch_non_printable_keys_only_system_group_in_content" in about:config to true on Firefox 60 or later (60 is currently Beta). If you use Firefox Nightly, you also need to ensure that your Etherpad URI is not included in "dom.keyboardevent.keypress.hack.dispatch_non_printable_keys".

Then, you can test this with the following steps:

0. Download Firefox Nightly or Firefox Beta, install it and launch it. <https://www.mozilla.org/en-US/firefox/channel/desktop/>
1. Open an Etherpad.
2. Type someting.
3. Type 'Tab' key.

Then, the paragraph should be indented.  However, nothing happens.

We will include major public Etherpad URLs into the blacklist. So, be careful at testing.

Bug at Mozilla: <https://bugzilla.mozilla.org/show_bug.cgi?id=1455059>

**Comment by muxator** [comment]
Thanks for reporting this [before May 9](https://developer.mozilla.org/en-US/Firefox/Releases/60).

This will not just apply to `tab` key, but also to other combinations (like `ctrl`-`b` for bold), right?

Could you please point to some documentation about how to keep up with this change? I guess a lot of products will need to handle this.

**Comment by masayuki-nakano** [comment]
> This will not just apply to tab key, but also to other combinations (like ctrl-b for bold), right?

Right.

> Could you please point to some documentation about how to keep up with this change? I guess a lot of products will need to handle this.

Here is an unofficial document:
https://www.fxsitecompat.com/en-CA/docs/2018/non-printable-keys-will-soon-stop-firing-keypress-event/

There are some points:

- Firefox will stop dispatching "keypress" event when user presses non-printable keys (e.g., 'Tab', 'ArrowLeft', 'Escape', etc) and non-printable key combinations (e.g., Ctrl+'B', etc) except Enter/Shift + Enter/Ctrl + Enter for compatibility with backward and the other browsers.
- The other browsers have already behaved so (so, basically, using same path as other browsers should work fine even on both new and current Firefox).
- Firefox does **not** stop dispatching non-printable keypress events immediately in Beta and Release channels (until major web apps fix their bugs).
- Unfortunately, web apps cannot detect if Firefox uses legacy behavior or standardized new behavior at least for now.

If you have some reasons to listen keypress events only on Firefox, let me know. We're thinking that web apps can listen to keydown events instead of non-printable keypress events as running on the other browsers.

FYI: If you need to distinguish if received keypress event is non-printable (i.e., won't be fired with new Firefox), you can check as:

```
function isRedundantKeyPressEvent(aEvent) {
  if (aEvent.type != "keypress") {
    return false;
  }
  if (aEvent.key === "Enter") {
    // Enter, Shift + Enter, Ctrl + Enter causes keypress.
    if (aEvent.altKey || aEvent.metaKey || aEvent.getModifierState("OS")) {
      return true;
    }
    return aEvent.ctrlKey && aEvent.shiftKey;
  }
  // charCode is 0, it's not printable.
  // ctrlKey, altKey, metaKey of "keypress" event are always false if it's printable.
  // Currently, Windows Log key state is checkable with getModifierState("OS") on Firefox.
  return !aEvent.charCode ||
         aEvent.ctrlKey ||
         aEvent.altKey ||
         aEvent.metaKey ||
         aEvent.getModifierState("OS");
}
```

Note that this function shouldn't be used on the other browsers because this logic does not conform to local rules of the other browsers.

**Comment by masayuki-nakano** [comment]
Now, I included a lot of URIs of public Etherpad instances into our blacklist to making Firefox Nightly testers can use Etherpad.  However, this blacklist mechanism won't go to release channel even if we enable the new strict keypress event behavior in release channel.

When you test Etherpad, please check "dom.keyboardevent.keypress.hack.dispatch_non_printable_keys" settings in about:config in today's or newer Nightly builds.

**Comment by manta12** [comment]
The 'ace2_inner.js' of etherpad-lite uses the 'keydown' if UA is not chrome/safari/IE. [1] As far as I can see, this code is exist from first commit of etherpad-lite.

[1] https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L3711
[2] https://github.com/ether/etherpad-lite/blame/2fa1d8768b52ebf7483a4ecb41c2a0ad007efaef/static/js/ace2_inner.js#L3025

If I added 'firefox' to above code, I confirmed that Firefox 63 work well without "dom.keyboardevent.keypress.hack.dispatch_non_printable_keys" preference.

**Comment by muxator** [comment]
Fixed in #3413.

**Comment by birtles** [comment]
@muxator I'm having a little trouble making sense of the status of this issue. Is it fixed? If not, what still needs to happen? It seems like 42e0646327527ff0db7bcbd93fb9d16ff738905b added the frontend test fixes?

**Comment by muxator** [comment]
That's right, @birtles. 42e0646 fixed the tests. I forgot to close this again. Thanks.

**Comment by birtles** [comment]
Thank you!
