### ISSUE TITLE
在大篇幅频繁的文档编辑中，我的浏览器已经卡死了，不能操作了

### ISSUE THREAD

**Issue by xulayen** [ether/etherpad-lite#3387]
如题

**Comment by xulayen** [comment]
![image](https://user-images.githubusercontent.com/15044564/39392581-bf839fda-4aea-11e8-90b9-bc3760ac4164.png)

**Comment by muxator** [comment]
@xulayen, in [google translate](https://translate.google.com/?sl=zh-CN&tl=en&text=%E5%9C%A8%E5%A4%A7%E7%AF%87%E5%B9%85%E9%A2%91%E7%B9%81%E7%9A%84%E6%96%87%E6%A1%A3%E7%BC%96%E8%BE%91%E4%B8%AD%EF%BC%8C%E6%88%91%E7%9A%84%E6%B5%8F%E8%A7%88%E5%99%A8%E5%B7%B2%E7%BB%8F%E5%8D%A1%E6%AD%BB%E4%BA%86%EF%BC%8C%E4%B8%8D%E8%83%BD%E6%93%8D%E4%BD%9C%E4%BA%86#zh-CN/en/%E5%9C%A8%E5%A4%A7%E7%AF%87%E5%B9%85%E9%A2%91%E7%B9%81%E7%9A%84%E6%96%87%E6%A1%A3%E7%BC%96%E8%BE%91%E4%B8%AD%EF%BC%8C%E6%88%91%E7%9A%84%E6%B5%8F%E8%A7%88%E5%99%A8%E5%B7%B2%E7%BB%8F%E5%8D%A1%E6%AD%BB%E4%BA%86%EF%BC%8C%E4%B8%8D%E8%83%BD%E6%93%8D%E4%BD%9C%E4%BA%86) your comment sounds like this:

> In a large space of frequent document editing, my browser is stuck and cannot be operated

It's a bit hard to understand your problem.
Could you please try to be more specific (and - possibly - write in English)?

Also, next version will contain [a fix](https://github.com/ether/etherpad-lite/issues/3327) that makes client connections more robust. Maybe your difficulty can benefit from that.

**Comment by icedwater** [comment]
@xulayen could I help with translation? Maybe you could post more details about your issue here.

**Comment by muxator** [comment]
Stale issue, closing as probably fixed by #3327, released in **1.6.6**.
