### ISSUE TITLE
Use the site name as page title prefix?

### ISSUE THREAD

**Issue by YesThatAllen** [ether/etherpad-lite#3388]
I like that the `dynamicsyntax` view sets the page title, but if I have a number of pages open, having them all sort together, by the instance name title, would be very useful in Chrome's tab manager.

How could I get the custom title to reverse its ordering? (css trick, plugin, etc)

**Comment by YesThatAllen** [comment]
It seems to be set here

https://github.com/ether/etherpad-lite/blob/d42393dc939c32789813ff478388bf42ccc1cffc/src/static/js/pad.js#L146-L151

and here

https://github.com/ether/etherpad-lite/blob/d42393dc939c32789813ff478388bf42ccc1cffc/src/static/js/timeslider.js#L45-L46

So, some custom js here


https://github.com/ether/etherpad-lite/blob/d42393dc939c32789813ff478388bf42ccc1cffc/src/static/custom/js.template#L3
could override the default?

**Comment by JohnMcLear** [comment]
In 1.8.3 this is default behavior afaik?

If not, ep_set_title would be a great solution?  Lemme know if this isn't solved for you
