### ISSUE TITLE
TypeError: log4js.replaceConsole is not a function

### ISSUE THREAD

**Issue by karstengit** [ether/etherpad-lite#3389]
I tried to install etherpad-lite following the description.
After it several installations are missing.
So i needed

apt-get install npm
npm install log4js
npm install async
npm install measured

After this the start of the server fails with

nodejs src/node/server.js
/srv/etherpad-lite/src/node/server.js:29
log4js.replaceConsole();
       ^

TypeError: log4js.replaceConsole is not a function
    at Object.<anonymous> (/srv/etherpad-lite/src/node/server.js:29:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

How this can be fixed?

**Comment by karstengit** [comment]
I am using debian jessie and nodejs v8.10.0

**Comment by karstengit** [comment]
There where many warnings installing log4js!

npm install log4js
npm WARN engine log4js@2.5.3: wanted: {"node":">=4.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN engine streamroller@0.7.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine date-format@1.2.0: wanted: {"node":">=4.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN engine request@2.85.0: wanted: {"node":">= 4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN engine form-data@2.1.4: wanted: {"node":">= 0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN engine form-data@2.0.0: wanted: {"node":">= 0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine form-data@2.3.2: wanted: {"node":">= 0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine har-validator@5.0.3: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine request@2.85.0: wanted: {"node":">= 4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine sntp@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@3.1.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@4.3.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@4.2.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine escodegen@1.9.1: wanted: {"node":">=4.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine esprima@3.1.3: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@5.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine form-data@2.3.2: wanted: {"node":">= 0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine har-validator@5.0.3: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine sntp@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@4.2.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@4.3.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@3.1.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@5.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
log4js@2.5.3 node_modules/log4js
├── date-format@1.2.0
├── circular-json@0.5.3
├── semver@5.5.0
├── debug@3.1.0 (ms@2.0.0)
├── redis@2.8.0 (double-ended-queue@2.1.0-0, redis-commands@1.3.5, redis-parser@2.6.0)
├── streamroller@0.7.0 (mkdirp@0.5.1, readable-stream@2.3.6)
├── axios@0.15.3 (follow-redirects@1.0.0)
├── nodemailer@2.7.2 (nodemailer-shared@1.1.0, socks@1.1.9, mailcomposer@4.0.1, nodemailer-smtp-transport@2.7.2, libmime@3.0.0, nodemailer-smtp-pool@2.8.2, nodemailer-direct-transport@3.3.2)
├── loggly@1.1.1 (json-stringify-safe@5.0.1, timespan@2.3.0, request@2.75.0)
├── amqplib@0.5.2 (safe-buffer@5.1.2, buffer-more-ints@0.0.2, bitsyntax@0.0.4, readable-stream@1.1.14, bluebird@3.5.1)
├── hipchat-notifier@1.1.0 (request@2.85.0, lodash@4.17.10)
├── mailgun-js@0.7.15 (is-stream@1.1.0, tsscmp@1.0.5, inflection@1.10.0, q@1.4.1, debug@2.2.0, path-proxy@1.0.0, form-data@2.1.4, proxy-agent@2.0.0, async@2.1.5)
└── slack-node@0.2.0 (requestretry@1.13.0)

**Comment by karstengit** [comment]
I tried
npm install npm
but this leads only to bigger problems.
Now
npm -v

/usr/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

node -v
v8.10.0

I have no idea to handle this java-script engine ... ?
The original node package of the distribution is to old - the new node engine is running - but not this npm stuff. :-(

**Comment by karstengit** [comment]
I tested it again today and i can only start etherpad, when i use the windows package on linux, where all the needed npm packages are included.

**Comment by muxator** [comment]
@karstengit, I suggest to:
- `apt remove` any nodejs releted packages from your system
- download the nodejs binary from https://nodejs.org/en/download/ (for example [node-v8.11.4-linux-x64.tar.xz](https://nodejs.org/dist/v8.11.4/node-v8.11.4-linux-x64.tar.xz), it's just 11 MB)
- `tar xf downloaded-file.tar.xf`
- creating 2 symlinks to `node` and `npm` in `/usr/local/bin/` (or in a folder that is in the `PATH` of the user that is going to execute Etherpad if you do not want a system-wide install)
- `rm -rf ETHERPAD_BASEDIR/src/node_modules`
- trying again

p.s.: please be aware that `npm install some_node_module` is not like `apt install some_linux_package`: `apt` installs system-wide and always in the same directory, `npm` installs locally (unless you use `--global`), and "locally" == the directory you are currently in.

**Comment by muxator** [comment]
Closing: the installation procedure mixed os-level packages and application-specific modules.

Write here or open another issue if there are further problems.
