### ISSUE TITLE
favicon setting issues: external custom favicon is not respected on /admin pages, but should be.

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#3392]
Favicon setting is disregarded on /admin pages: the standard EPL favicon is shown

When you define a favicon.ico in the settings.json, this is not respected on /admin pages, but should be.

**Comment by Wikinaut** [comment]
There is also another major problem with the other favicon settings

I have used this since years (works, but not an /admin)
```
 "favicon": "https://another-server/favicon.ico",
 "faviconPad": "https://www.another-server/favicon.ico",
 "faviconTimeslider": "https://www.another-server/favicon.ico",
```
but when I read https://github.com/ether/etherpad-lite/blob/6dd172d6b76cb219f0aa095ea09e43ef7f259d3d/src/node/utils/Settings.js#L44 nd the following lines in /src/node/utils/settings.js, a single custom favicon ico definition like in the following should also be working one all pad pages, but does not:
```
 "favicon": "https://another-server/favicon.ico",
// "faviconPad": "https://www.another-server/favicon.ico",
// "faviconTimeslider": "https://www.another-server/favicon.ico",
```

**Comment by JohnMcLear** [comment]
Confirmed.  Easy one for someone to pick up and solve.

**Comment by KSSaiTeja** [comment]
i will pick this, can you assign me this?

**Comment by JohnMcLear** [comment]
Great thanks @KSSaiTeja

**Comment by KSSaiTeja** [comment]
My pleasure :D @JohnMcLear

**Comment by KSSaiTeja** [comment]
Unfortunately i cant figure out the issue, as i am a beginner please help me with the file which i work on to. and please give some guidance to work upon this..

**Comment by SamTV12345** [comment]
Looks like someone fixed it in the meantime between 2018 and today. It is working flawlessly. When I download a favicon and set it to ./favicon.ico in the settings.json it is also displayed on the admin pages after login.

**Comment by KSSaiTeja** [comment]
ok thanks for confirming! i will work on other issues

**Comment by SamTV12345** [comment]
Alright👍🏻. Maybe get yourself familiar with the codebase first.

**Comment by KSSaiTeja** [comment]
yeah i will

**Comment by q2apro** [comment]
Hello from Dec 2023.

Unfortunately, this is not fixed.

In `/admin/settings` the example setting:

`"favicon": "https://www.myothersite.com/favicon.ico",`

does have NO effect. Still the defaul ../favicon.ico can be seen in the HTML.

How to fix this?

**Comment by SamTV12345** [comment]
> Hello from Dec 2023.
> 
> Unfortunately, this is not fixed.
> 
> In `/admin/settings` the example setting:
> 
> `"favicon": "https://www.myothersite.com/favicon.ico",`
> 
> has NO effect. Still the default `<link rel="shortcut icon" href="../favicon.ico">` can be found in the HTML.
> 
> How to fix this?
> 
> **Update:**
> 
> By accident, found this in the changelog:
> 
> > * The `favicon` setting is now interpreted as a pathname to a favicon file, not a URL. Please see the documentation comment in `settings.json.template`.
> 
> This would be a big disadvantage, because in Etherpad Lite Docker you cannot touch the files without recompiling!

That is fixed. Once you enter a url. The image is loaded from there and displayed in the browser.
