### ISSUE TITLE
Hot-Key to move line (list-item) up/down?

### ISSUE THREAD

**Issue by Yoven** [ether/etherpad-lite#3393]
Especially when working with lists, it's really helpful to have an option to move lines up/down without having resort to copy/paste.

Would it be possible to add such a feature?

**Comment by JohnMcLear** [comment]
Alt up / Down is probably the expected keystroke?

**Comment by JohnMcLear** [comment]
I have been testing this recently in different editors:
* MS use Control Alt
* LO use Shift Alt
* Goog use Shift Alt
* Atom uses Control

Imho Shift Alt is the best option here.

Behavior is practically the same throughout.

MS Word behavior: flashes on page re-render
Libreoffice: Get's OL item #'s wrong or so it appears, it's probably expected tho.

![Capture](https://user-images.githubusercontent.com/220864/77828249-2b6af000-7112-11ea-9a51-ed7c870fe547.PNG)

The big consideration is what you do RE indentation / parenting of List items.
