### ISSUE TITLE
Problems when using Libreoffice as converter (Abiword works)

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#3398]
In a fresh Etherpad installation on debian 10 (buster) I noticed that Libreoffice does not give a proper export output, wherea Abiwiord does, for example, Libreoffice starts with some empty pages before starting the converted pad text.

I will add some screenshots later (here), and exact version information.

* debian 10 
* Operating System: Debian GNU/Linux buster/sid
* Kernel: Linux 4.16.0-1-amd64
* Etherpad 1.6.6 (fe08d2a)
* LibreOffice 6.0.4.1 00m0(Build:1)

Provisionally also see https://github.com/ether/etherpad-lite/issues/3116 regarding a problem with Abiword (I do not have problems when using Abiword as converter).

**Comment by muxator** [comment]
Confirmed.

Etherpad **1.7.pre**, libreoffice **6.0.5.2**

**Comment by Wikinaut** [comment]
Perhaps https://github.com/ether/etherpad-lite/pull/3473 solves this (needs confirmation).

**Comment by muxator** [comment]
I believe this is fixed by #3473, indeed.
Works for me on Etherpad 1.7, linux, Libreoffice 6.0 & 6.1.

**Comment by Wikinaut** [comment]
Fixed by #3473 , closing this issue.
