### ISSUE TITLE
Etherpad removes HTML tags (like links, ...) after export

### ISSUE THREAD

**Issue by xyNNN** [ether/etherpad-lite#3400]
Hey folks,

when I try to export my HTML from a pad it removes all my links in this content.
My content from a pad:

```
<h1>My Headline</h1>
<a href="http://www.example.com">My Link</a>
```

and I got 
```
<h1>My Headline</h1>
My Link
```

Have someone an idea which component is relevant for this? Can I prevent this behaviour?

Thanks in advance!

**Comment by xyNNN** [comment]
Some update about this topic? 
Thanks in advance!

**Comment by muxator** [comment]
Hi,

it's working for me (Etherpad **1.6.6**, no plugins installed):

Typing this text into the pad:
![etherpad-1 6 6-hyperlink](https://user-images.githubusercontent.com/4067621/44118916-e0d74998-a017-11e8-91c3-d75537c8cce0.png)


Gets exported to this html:

```html
[...]
<body>
<a href="http&#x3a;&#x2F;&#x2F;www&#x2e;google&#x2e;com">http:&#x2F;&#x2F;www.google.com</a><br><br>
</body>
[...]
```

How are you generating the link?
Could it be anything plugin related?
