### ISSUE TITLE
Can't install new plugins

### ISSUE THREAD

**Issue by maniackcrudelis** [ether/etherpad-lite#3401]
Hi

We have a problem when is about to install a plugin from the admin interface of Etherpad.
When clicking on "Install" of any plugin, nothing happen in the web interface, but the log print out this:
```
[ERROR] console - SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/etherpad_mypads/src/node_modules/npm/lib/install.js:109:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```
Then Etherpad restart, and so on if we retry.
The log is the same with loglevel set at DEBUG.

We running node v4.9.1, npm v2.15.11 and Etherpad v1.6.5.
Version 1.6.6 is affected the same way.

**Comment by nashe** [comment]
Can't reproduce it at home. Can you show us the context around this stacktrace, like 10 lines before and 10 lines after?

**Comment by maniackcrudelis** [comment]
Here a complete log, https://paste.yunohost.org/jifaqasugu
I reinstall an etherpad instance and tried to install the first available plugin (activepads) from the admin interface. This action crashed my etherpad at the line 39 of the given log.

This instance is running on a virtual machine, I keep the current state aside in case you want me to try anything on this etherpad instance.

**Comment by anmol26s** [comment]
Any update on it?

**Comment by anmol26s** [comment]
Someone reproduced this? The plugins are not getting installed.

**Comment by fdellwing** [comment]
Can confirm this with newest develop version.

**Comment by muxator** [comment]
I am not able to reproduce it (current develop, 58c315476954), node **10.6.0**.

I was able to install via /admin/plugins the following plugins (taken at random):
* https://www.npmjs.com/package/ep_delete_after_delay
* https://www.npmjs.com/package/ep_embedded_hyperlinks

**Comment by fdellwing** [comment]
I solved the problem after installing node 6 (it's ubuntu 12, so don't judge..) and all updates for the node modules.

Would be nice, if the error message could hint in this direction?

**Comment by muxator** [comment]
Sure, @fdellwing: minimum node version should be clearly indicated in the docs and enforced in the startup scripts.

I'll repeat the test with node < 6 to verify it breaks and eventually open an issue.

BTW: installing arbitrary node versions is really easy if you are willing to use the official tarball: it's just untar + some symlinks (and it's distro independent, too). You can have a look at [this comment](https://github.com/ether/etherpad-lite/issues/3417#issuecomment-405197546), if it can help you.

**Comment by fdellwing** [comment]
It ran completely fine with node 4, just the plugin install was not working. So I remembered that it complained about an outdated node version.

**Comment by maniackcrudelis** [comment]
I confirm that upgrading to node 6 instead of 4 fix the issue on our side as well.
Thanks for finding a solution to that :)

**Comment by tessierp** [comment]
I installed the latest docker etherpad/etherpad and I am unable to install plugins. When I select to install one, I get the notification of installation at the top but it never installs

![image](https://user-images.githubusercontent.com/6784384/202464180-1cc010fc-d175-4c0a-9926-d9e4baa1b596.png)
