### ISSUE TITLE
Paid etherpad hosting

### ISSUE THREAD

**Issue by jrmuizel** [ether/etherpad-lite#3403]
Mozilla's etherpad is probably not going to continue to operate. See: https://wiki.mozilla.org/Etherpad

Is there an option for a paid etherpad hosting alternative that we could use?

**Comment by fralix** [comment]
If people are only looking for an etherpad service to use (non-paid):
I'd always recommend Wikimedia for new users: [etherpad.wikimedia.org](https://etherpad.wikimedia.org)

**Comment by rasos** [comment]
See the list of sites that run etherpad https://github.com/ether/etherpad-lite/wiki/Sites-that-run-Etherpad-Lite
