### ISSUE TITLE
Translation problems: Languages like "de-de" fail: /locales/de-de.json "Language not available"

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#3404]
I noticed a problem where the existing translation files like /src/locales/de-de.json cannot be loaded, you can test this by accessing
```
https://your-pad-server/locales/de-de.json
```
which fails with message
```
Language not available
```

As an ad-hoc fix, I changed the test in
https://github.com/ether/etherpad-lite/blob/develop/src/node/hooks/i18n.js#L33

from
```
 if ((ext == '.json') && languages.isValid(locale)) {
```
to
```
 if (ext == '.json') {
```

CC: @marcelklehr

**Comment by marcelklehr** [comment]
Hey there!
apparently the module used for providing language info is outdated (last update 5 years ago, heh).
I recommend adding some of the code to etherpad directly: https://github.com/joker-x/languages4translatewiki/ (It simply fetches the data from the translatewiki API)

**Comment by Wikinaut** [comment]
@marcelklehr I just "digged" into the code, and resumed my work with Etherpad (especially, my plan is to fix and improve the ep-email-notification pliugin). Perhaps you can work (together with me, if I can help) to fix the i10n issue/s ? Would be great. The hooks/i18n.js btw looks very ugly and old.

**Comment by marcelklehr** [comment]
As suggested in #3263 I recommend replacing languages4translatewiki with https://github.com/wikimedia/language-data which is already maintained. I won't work on this myself, however.

**Comment by SimJoSt** [comment]
Funnily enough, only the translations of the font names rely on the browser language. They are missing when running into this error, everything else is in the settings.json defined language.
Unifying that, would probably also be a good idea :-)

I always assumed the browser language takes precedence, but if it fails, the default language is chosen.

**Comment by anoymouserver** [comment]
In my opinion the l10n handler should fallback to a default language (probably english) if a translation for a specific property doesn't exist. Currently the text seems to be empty in the ui.

For example in german most of the font names are missing in the `de.json`. (`"pad.settings.fontType"`)
However, I think it is unnecessary to copy such strings into every language, because they are always the same.

**Comment by muxator** [comment]
Hi, I think this and #3263 are important, but I really do not have the time to dig into it. Any volunteer?

**Comment by SimJoSt** [comment]
I would if I could, but I am missing the technical skill.

**Comment by JohnMcLear** [comment]
@Wikinaut just so I can replicate this; what's the actual problem?  If I visit Etherpad using a German locale set on my browser (IE navigator.language === "de.de") then German translations will not be visible??  

I feel like I'm being kinda dumb, I get the technical issue but I don't see how it's practically affecting users.  Thanks!

**Comment by Wikinaut** [comment]
Hi @JohnMcLear , long time, no see! Nice that you are back!!

Give me some time, I am still along and working with Etherpad, give me some time to upgrade my running instance/s and to look, if the problem is still present.

I will come back and report **here**.
