### ISSUE TITLE
Path of hyperlinks doesn't fit

### ISSUE THREAD

**Issue by diesocke** [ether/etherpad-lite#3410]
Hi there,

I've recently set up a etherpad-lite instance on my webspace at https://sockenseite.de/pad. I've installed several plugins to make it comparable to the pads at piratenpad.de. However, I seem to have missed something. Most hyperlinks referencing contents leave out the "pad" an thus cause 404s (like the link to "All Pads" on the starting page). Funfact: The link to the Padlist (https://sockenseite.de/pad/pad-lister) works, but the link to pads listed there leaves out "/pad" all the same.

Is there something in .htaccess or in the settings.json that needs to be fixed?

**Comment by xpilgrim** [comment]
I think, I've a similarly problem with the plugin mypads [Issue on gitlab](https://framagit.org/framasoft/Etherpad/ep_mypads/issues/189)
It seems, that using etherpad itself in a virtual subdirectory works, but not several plugins?

**Comment by JohnMcLear** [comment]
Try remove each plugin one by one to see which is breaking your install.  If this is still an issue for you please let me know and we can reopen the issue.
