### ISSUE TITLE
Language Server Protocol

### ISSUE THREAD

**Issue by InTheCloudDan** [ether/etherpad-lite#3415]
Looking around the documentation and searching I haven't found any implementations of LSP. Is there any known interfaces of server side supporting it to provide the output back to the client?

**Comment by muxator** [comment]
Hi, there is no LSP support.

But I am not getting what a possible Etherpad-specific use case would be.

**Comment by JohnMcLear** [comment]
This is a plugin request.  Afaik each plugin IE ep_markdown might consume LSP.  I don't think it should be an issue open here.
