### ISSUE TITLE
Put etherpad-lite in production

### ISSUE THREAD

**Issue by LePandaDuNet** [ether/etherpad-lite#3422]
Hi,

I want to put etherpad-lite in production on OVH but to do that I need to lunch etherpad with an index.php.
I'm a php beginner, so I would know if it's possible and if one of you have an index.php example because mine doesn't works.

Thank you in advance,

Lisa

**Comment by muxator** [comment]
Hi @LePandaDuNet, did you already have a look at [the installation guide](https://github.com/ether/etherpad-lite#installation)?

Etherpad is not based on PHP (you will need to install it following that guide, anyhow). You can easily integrate it on the client side: see, for example https://github.com/ether/etherpad-lite/wiki/Embed-Parameters
