### ISSUE TITLE
expose version only when explicitly configured

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3423]
The `Server` http header generated for every http response contains the Etherpad version.

```
HTTP/1.1 200 OK
...
X-Powered-By: Express
...
Server: Etherpad 3362c68 (http://etherpad.org)
```

Issue #2968 also asks for showing that number in the web interface.

While useful in certain contexts, an hardened production installation should probably avoid to directly expose the version number.

My proposal is to add a configuration setting to enable or disable populating this header (and the corresponding UI element in #2968, when it gets implemented).

```json
// expose Etherpad version in the web interface and in the Server http header.
// Do not enable on production machines.
expose_version: false
```

Examples of similar configuration directives in other projects:
https://httpd.apache.org/docs/2.4/mod/core.html#servertokens
https://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens
https://secure.php.net/manual/en/ini.core.php#ini.expose-php

Applies to: Etherpad **1.6.6**

**Comment by lpagliari** [comment]
@muxator Agree, a flag on settings should turn this on and off.

**Comment by muxator** [comment]
Since this is an easy fix, I would be happy if the feature could be implemented by a new contributor.
Any volunteers? :)

**Comment by sgimeno** [comment]
Maybe I can help. Are there any backend tests regarding the server settings configuration?

The version and commit id are also leaked in the logs in https://github.com/ether/etherpad-lite/blob/develop/src/node/hooks/express.js#L17
Should that be configurable as well?

**Comment by muxator** [comment]
Thanks @Tristramg for implementing this (and #2968) with #3596.
