### ISSUE TITLE
read only through admin panel

### ISSUE THREAD

**Issue by armansansd** [ether/etherpad-lite#3439]
Hi, 
I would like to know if it is possible make a pad in read only mode through admin. So if the user accesses it through the main address it is still in read only mode unless you undo it from the admin, 
I hope I'm clear, here's an example of what I'm trying to do : 
If the user accesses the pad with the address ```http://pad.com:9001/p/mypad``` it is in read only unless I change it in the admin. 

Its seems that no plugin exists to allow one to do that. But is it possible to add create a plugin for that ? Or would this go against the way etherpad works ? 

Thanks a lot, 

Cheers,

**Comment by JohnMcLear** [comment]
I don't think it's possible at the moment.  It would be doable with a plugin tho.
