### ISSUE TITLE
Are pictures and tables supported?

### ISSUE THREAD

**Issue by leka2002** [ether/etherpad-lite#3440]
If so, what should I do to use it?

I saw two links below.

https://www.youtube.com/watch?v=B11p1tWBZLo
https://github.com/JohnMcLear/ep_copy_paste_images

**Comment by michaelha** [comment]
+1

Also want to follow up.  I see that there is a ep_table2 plugin but it doesn't seem to be active.

**Comment by lpagliari** [comment]
There are some plugins that might be useful. Here's a list of some of them: https://static.etherpad.org/plugins.html. Maybe [`ep_image_upload`](https://www.npmjs.com/package/ep_image_upload) will fit your needs -- I've never used it, so I don't know if it is supported.
