### ISSUE TITLE
Admin username and password not set in settings.json

### ISSUE THREAD

**Issue by tobit6795** [ether/etherpad-lite#3442]
etherpad shows the following warning: 

> Admin username and password not set in settings.json. To access admin please uncomment and edit ‘users’ in settings.json

despite the parameter being setup correctly:

```
 /*
  "users": {
    "admin": {
      "password": "passwd1",
      "is_admin": true
    },
    "user": {
      "password": "passwd2",
      "is_admin": false
    }
  },
  */
```

**Comment by Wikinaut** [comment]
@tobit6795 remove the comment tokens ( /* ... */ )

**Comment by tobit6795** [comment]
ouch...

**Comment by Wikinaut** [comment]
then pls. close

**Comment by Wikinaut** [comment]
By the way, better store hashes instead of plain text passwords, see https://www.npmjs.com/package/ep_hash_auth

**Comment by tobit6795** [comment]
Thanks, I just looked for sth like that

**Comment by muxator** [comment]
This should be probably be a standard part of a production install anyways.
If the plugin is compatible, I would even make it a suggested option in the install documentation.

**Comment by Wikinaut** [comment]
@muxator I fully support your proposal.
