### ISSUE TITLE
Unable to remove

### ISSUE THREAD

**Issue by c526537207** [ether/etherpad-lite#3445]
![_20180809172904](https://user-images.githubusercontent.com/31339057/43890631-d359bd90-9bf9-11e8-9fea-95e94cae3c11.png)

I have deleted the following characters in setting.json, but the page still exists. What's the matter?

**Comment by lpagliari** [comment]
You should not remove `suppressErrorsInPadText` from `settings.json`, you should set it to `true`.

**Comment by c526537207** [comment]
Thank you for your reply. The problem has been solved!
