### ISSUE TITLE
txt export: ordered lists number == indentation level

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3450]
[edit]: **please see below for a more precise characterization of this bug**.

Manually insert this list in a pad:
![txt-export-bug-on-ol](https://user-images.githubusercontent.com/4067621/43986344-e1ea71bc-9d0f-11e8-8458-baeeb64fb017.png)

Export it as txt. The result will be:
```
1. a
1. b
1. c
1. d
```
This bug was discovered while replicating #3447: that bug inserts an html via API, and the text gets both displayed and exported wrongly.

This case is _simpler_: **the same list** is inserted manually via the GUI (and thus displayed correctly), yet the exported txt has **exactly** the same errors as in #3447.

**Comment by zorrikon** [comment]
Btw, exported TXT lists start with with whatever level indent they are. So all items indented once start with "2." and those indented twice start with "3." etc.

**Comment by JohnMcLear** [comment]
Test coverage in for this

**Comment by JohnMcLear** [comment]
Fix here: https://github.com/ether/etherpad-lite/pull/3839

**Comment by JohnMcLear** [comment]
Final part of fix landed here: https://github.com/ether/etherpad-lite/pull/4086
