### ISSUE TITLE
MariaDB issues

### ISSUE THREAD

**Issue by petrk94** [ether/etherpad-lite#3453]
Hello Etherpad Community,

Im facing a problem to run Etherpad as productive.
I have it run sucessfully on CentOS 6 with dirtyDB, unfortunately, the shared host provide not the latest MySQL which is needed to use the charset utf8mb4. As altenative the shared host provide MariaDB, which is able to work with utf8mb4.
My theory, just change the config and let it work, but its wrong. while mysql need to be called localhost, the port ist 3306, but for the mariadb its called 127.0.0.1:3307 ; This is a problem, due etherpad try to add the port additional and than it shows: 127.0.0.1:3307:3306

Now is my question, can the port number be set manually or can there be another database charset?
DirtyDB is only for testing, sqlite is not available, postgres is hard to set up on the server.
I would really prefer the mysql utf8 charset.
I hope you can help

**Comment by petrk94** [comment]
@muxator 
yes, works well, the just the port parameter was necessary, now it works fine with MariaDB.
Thanks for the help.

Ps. It were nice if the database can be checked/switched in the backend or adjusted there manually without typing all in the settings.json.

**Comment by muxator** [comment]
Committed d38f53181f151f45355718449aa3712566659c7a to mention the existence of `port` in `settings.json.template`, so these customizations are easier in the future.
