### ISSUE TITLE
Funding Developer for Plugins and continue work on etherpad

### ISSUE THREAD

**Issue by petrk94** [ether/etherpad-lite#3455]
Hello,

Im not a developer of etherpad, but I like to use it and its honestly the most used alternative to google docs. But in the last years, the design doesnt changed a lot, and plugins was made in the "glory years", are already between 4-6 years old, without any update of the developer. 
This is very bad, because without these, etherpad would die in a future, due the basics are not enough.
The latest share #3441 showed me finally a beautiful theme for etherpad, where I hope it can cause that etherpad can get more popular again.
Therefore, Im not sure whether it got already talked, discussed or share here. But there are Open Source Funding platforms, which make it better to get the money to work more and develop etherpad sustainable for the future (Just imagine, what would you use, if etherpad is dead?).

Here are few funding platforms where I think etherpad should be there too:

- https://opencollective.com
- https://liberapay.com
- https://www.bountysource.com/?search=etherpad

Please tell me what you think and whether you would donate?
Thanks

**Comment by JohnMcLear** [comment]
@muxator one for you.
