### ISSUE TITLE
Etherpad : r.dropdowns is undefined.

### ISSUE THREAD

**Issue by kernelfreak** [ether/etherpad-lite#3464]
Hello friends,

We have an etherpad instance running on our server. Sometimes we are getting an issue with r.dropdowns not found and it's causing the pad to not load and just wait at loading. We have only added plugins as mentioned below, nothing changed on development part. 
Error log : 
```

ESC[33m[2018-08-20 09:25:22.495] [WARN] client - ESC[39mTypeError: r.dropdowns is undefined -- { errorId: 'NsxaLg52nwIjTGE8hSD0',
  msg: 'TypeError: r.dropdowns is undefined',
  url:
   'https://domain_name/p/g.ihnMF00JfaiKvFv1$9gjd2s5g6c2b4lskkkv0s5mu2',
  linenumber: 18,
  userAgent:
   'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0' }
```

List of plugins enabled : 

authornames
cursortrace
font_color
font_size
headings2

We are running the latest version of Etherpad.

**Comment by muxator** [comment]
Hi @kernelfreak. I fear that in the current state of the code base it is a bit hard to analyze your problem.

Those kind of error messages happen when there is a client-side exception. In that cases `setupGlobalExceptionHandler()` in `pad_utils.js` sends back the error to the server:

https://github.com/ether/etherpad-lite/blob/07bc163cb698768020cb4d41808f1cd92c0d1b7b/src/static/js/pad_utils.js#L530-L535

Personally, I do find the idea very neat, but the implementation could be improved, as I think these logs are not really informative enough.

In your specific case, a possible place to look at would be `src/static/js/pad_editbar.js`. Maybe this is a case of use before initialization. But without a complete stack trace it's a bit hard to imagine.

**Comment by doobry-systemli** [comment]
We experience the same bug with some larger pads on our pad instance. Any chance to helpy you with debugging the root cause?

**Comment by JohnMcLear** [comment]
Closing as stale.

**Comment by manu-p** [comment]
Hi, we're experiencing the same error on our etherpad instance, here's what is displayed over the opened pad:
TypeError: r.dropdowns is undefined in https://pad.ourdomain.fr/javascripts/lib/ep_etherpad-lite/static/js/pad_utils.js?callback=require.define at line 22'

Any help appreciated!

**Comment by JohnMcLear** [comment]
@manu-p Please provide some information....  OS, Version of Etherpad, Git Sha, Are you running minified?  What maxAge?  Have you tried cleaning browser cache.  Please see https://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/

**Comment by manu-p** [comment]
Thanks @JohnMcLear 
Etherpad-lite **1.8** is running **minified** on a server:
- **Ubuntu 18.04.4** 
- **nodejs v12.16.1**
- **maxAge : 21600**

We're using Firefox 74+, Brave Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit), and probably other chromium/chrome browsers.

For a long time, the pad is displayed without menus and with a "Loading..." in the pad header. Then after a while a message is displayed in red and black:
**An error occurred
The error was reported with the following id: 'mmOZLIJfB2q1EAEzY03U'**

**Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:**
'ErrorId: mmOZLIJfB2q1EAEzY03U
URL: https://pad.ourdomain.fr/p/jotworxk36qxkf3s
UserAgent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
TypeError: r.dropdowns is undefined in https://pad.combustible-numerique.fr/javascripts/lib/ep_etherpad-lite/static/js/pad_utils.js?callback=require.define at line 22'

Ctrl+F5 changes nothing.

**Comment by JohnMcLear** [comment]
Try running with (``in settings.json``)
1. ``minified: false,`` and ``maxAge:0,`` 
1. restart Etherpad
1. then clear browser cache and 
1. refresh (or use network tab to disable browser cache)

See if problem persists

**Comment by elmatusov** [comment]
Thanks A LOT, @JohnMcLear! Superhelpful!

I was getting the following error on my Etherpad Lite 1.8.4 running on Windows Server 2019:

ErrorId: 4wNmhAZ2hYo9zBrq1xHb
URL: https://diaped.soe.udel.edu:9001/p/g.NfRQhXclxTNNzHYW$DiaMoodle
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0
TypeError: $sidedivinner is undefined in https://diaped.soe.udel.edu:9001/static/js/require-kernel.js?v=c4855223 line 1 > Function at line 5

I followed your guidelines of changing settings.json to "minify: false, and maxAge:0," then "restart Etherpad" and the problem disappeared. 

I hope this bug will be cleaned in the next version of Etherpad.

**Comment by JohnMcLear** [comment]
It is but I will say we don't have test coverage for Windows server so we just have to hope that Microsoft don't break any APIs and keep up which so far they have been doing.

**Comment by webzwo0i** [comment]
@elmatusov 
$sidedivinner seems to be related to ep_author_neat plugin. Also ep_copy_paste_images has problems on your instance (go to a pad and watch for console errors)

**Comment by elmatusov** [comment]
Thanks, @webzwo0i for the info. You wrote, "go to a pad and watch for console errors." I do not see any errors in the console. Maybe, I don't know where to look for the errors. Can you guide me, please?

**Comment by JohnMcLear** [comment]
Press f12.  Google how to use developer console if you are stuck.

**Comment by elmatusov** [comment]
Thanks, @JohnMcLear, I do not see any problem when I click F12. However, when I open the etherpad log file, I can see many errors of the following two types:

1) [WARN] message - Authentication try failed:{"component":"pad","type":"CLIENT_READY","padId":"g.NfRQhXclxTNNzHYW$DiaMoodle","sessionID":"null","password":null,"token":"t.nlx6g9QWnjgnB2qimJF9","protocolVersion":2,"client_rev":1699,"reconnect":true}

2) [WARN] client - Uncaught TypeError: Cannot read property 'setStateIdle' of null -- { errorId: '0lFDpzga1bs79Ap8S1sK',
  msg:
   'Uncaught TypeError: Cannot read property \'setStateIdle\' of null',
  url:
   'https://diaped.soe.udel.edu:9001/p/g.NfRQhXclxTNNzHYW$DiaMoodle',
  linenumber: 215,
  userAgent:
   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' }

A lot of errors come from Mac computers.

Yesterday, I was teaching an online Moodle class and my students again start getting error messages (see in my original posting) preventing them to use EtherPad. But this time, after I changed the settings as you guided me, only some students had problems. After reloading the Etherpad page with Moodle several times during the class, I got the same error on my computer as well and it lasted for several hours afterward -- I could not access that particular Etherpad page on Moodle. But after a few hours after the class, again I was able to open it.

I wonder if I should downgrade Etherpad from 1.8.4 to 1.7.5 and Moodle plugin to the earlier version. I did not have this problem with Etherpad on Moodle before.  Any ideas or advice, please? I'd highly appreciate your help.

**Comment by JohnMcLear** [comment]
1.8.5 is stable.  Use that.
