### ISSUE TITLE
Etherpad : applySubmittedChangesToBase: no submitted changes to apply 

### ISSUE THREAD

**Issue by kernelfreak** [ether/etherpad-lite#3465]
Hello friends,

We are running an Etherpad instance on our server in which are sometimes getting the error mentioned above and the pad doesn't load. We have not done any modifications to etherpad, as other users in similar threads had. We only have a few plugins installed. 

Error log : 

```
ESC[33m[2018-08-19 14:17:37.031] [WARN] client - ESC[39mError: applySubmittedChangesToBase: no submitted changes to apply -- { errorId: 'NyOWlXnwZj4av00AqT64',
  msg:
   'Error: applySubmittedChangesToBase: no submitted changes to apply',
  url:
   'https://domain.com/p/g.ihnMF00JfaiKvFv1$kuiu49ekq2527bqmr6g8ol14ec',
  linenumber: 36,
  userAgent:
   'Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1' }
```
Plugins installed : 

authornames
cursortrace
font_color
font_size
headings2

We are running the latest version of Etherpad. Thank you.

**Comment by JohnMcLear** [comment]
Please provide steps to replicate and see if you get these errors without plugins or not.
