### ISSUE TITLE
Safari: iOs - Text disappears behind overlay

### ISSUE THREAD

**Issue by renebrain** [ether/etherpad-lite#3469]
When you type in etherpad and come close to the bottom, somehow in safari he is typing behind the bottom menubar. For all other browsers he is not getting into that invisible line behind it. Only in Safari on iOs. It happens with the simulator as well as a real device. That looks weird. Any ideas how to fix that, or is that intended? I've tried it on your beta.etherpad.org page. It also happens in our app.

![d8a05ef6-6bfa-49d4-b986-53a7d5f3e458](https://user-images.githubusercontent.com/9963399/44515962-1cb19100-a6c4-11e8-95e3-5e01d82e7ea3.gif)

**Comment by JohnMcLear** [comment]
Afaik this is a VERY old Safari bug already reported.  I reported it to Apple and they didn't do anything.  

https://github.com/ether/etherpad-lite/issues/3029

Is it still an issue?
