### ISSUE TITLE
Check running etherpad version

### ISSUE THREAD

**Issue by ge-fa** [ether/etherpad-lite#3485]
...to compare it against the latest upstream release.

I would like to write a check for my monitoring, which checks my running version against the latest upstream version. I would like to keep the check plain and simple, that is, without relying on a additional plugin for example.

I had hoped to use the `Server` response header, like in
```
Server: Etherpad bc0871e (http://etherpad.org)
```

However, git tells me that `bc0871e` is unknown -- I thought initially that this is a git SHA.

Any idea regarding this?

Thanks for your work!

**Comment by muxator** [comment]
Hi @ge-fa, that sounds really strange...

What is the output of `git log -1`?

If you want to have a look at how it is supposed to work, you can have a look at the "Server" header from http://beta.etherpad.org.
We also have a plan to selectively disable it if wanted: #3423.


Some pointers if you want to have a look at the code:

The code that computes the git hash is this (not super elegant, but effective, I would say...):
https://github.com/ether/etherpad-lite/blob/2a5e87cc7da748da94d1169df2a470b6406b65b9/src/node/utils/Settings.js#L322-L343

That number is sent to the client in:
https://github.com/ether/etherpad-lite/blob/2a5e87cc7da748da94d1169df2a470b6406b65b9/src/node/hooks/express.js#L79

**Comment by ge-fa** [comment]
Thanks, and sorry for the noise. I've overlooked that I made my own commits on top of the upstream release branch which are obviously not part of the public git. Therefore, closing.
