### ISSUE TITLE
ElasticSearch Support

### ISSUE THREAD

**Issue by ArcticSnowman** [ether/etherpad-lite#3486]
In your latest release you mention ElasticSearch under security update..

Is there support for ElasticSearch?  If so what are the setup needed for it?

**Comment by Tristramg** [comment]
Yes, there is a support through https://github.com/pita/ueberDB

I didn’t test it, but the configuration in settings.json should look something like: 

```
"dbType" : "elasticsearch"
"dbSettings": {}
```

The default settings being: 
```
{
  hostname      : '127.0.0.1',
  port          : '9200',
  base_index    : 'ueberes',
  api           : '2.4'
};
```
