### ISSUE TITLE
A4 Format and index

### ISSUE THREAD

**Issue by duven87** [ether/etherpad-lite#3493]
Hi, this project looks very good.
Im thinking about to write a book of linux LPIC with the posibility that another people can contributeto it.
But my idea needs format A4 to download in pdf or odt for later print it.
I cant see the limits of a page wirh etherpad.
I didnt find a open source online program to do it. Just Zoho, but it isnst open.
Can you integrate it?
And maybe an index in the left part for big documents.

Thanks
Regards

**Comment by ukcb** [comment]
For a book, I would rather use LaTeX. https://www.latex-project.org/
The text can always be written in etherpad. :-)

**Comment by joassouza** [comment]
If you need pagination, you can use this plugin 
https://github.com/ether/ep_page_view
Etherpad exports to PDF as well.

**Comment by duven87** [comment]
Oh thanks.
Its there any website where is already installed this plugin? I dont have a server to install it

**Comment by muxator** [comment]
@duven87, one of the advantages of Etherpad is that you can host your own instance if you want. I guess in your case a managed solution would be more suitable.

I'll close the issue, as the specific question has been answered already.
