### ISSUE TITLE
what are the risk when I set group pad status as true?

### ISSUE THREAD

**Issue by sfp12** [ether/etherpad-lite#3497]
I have done createAuthorIfNotExistsFor -> createGroupIfNotExistsFor -> createGroupPad -> setPassword -> createSession at server.
Then, return 'iframe_src, sessionID, password' to browser, at the same time, set 'sessionID password' into cookie, but the tip is "You do not have permission to access this pad", the page is work until I set pad status as true at my server. 
The problem is whether or not  this action(set pad status as true) has some potential risks?  

ps: I embed etherpad into nodejs server.
![server](https://user-images.githubusercontent.com/6441477/46906801-e8c45080-cf3b-11e8-925e-0e289ac05696.jpg)
![browser](https://user-images.githubusercontent.com/6441477/46906807-f1b52200-cf3b-11e8-9961-80b22d078606.jpg)

**Comment by JohnMcLear** [comment]
Let me know if thi sis still an open issue.
