### ISSUE TITLE
I have found an error-prone code.

### ISSUE THREAD

**Issue by wonseop** [ether/etherpad-lite#3499]
Below is code from line 465 to line 471 of  'src/node/handler/PadMessageHandler.js'.

```js
  var count = start - count;  // 465 line

  if(count < 0 && count > 100)  // 467 line
  {
    messageLogger.warn("Dropped message, GetChatMessages Message, client requested invalid amout of messages!");
    return;
  }
```

In the code above, Local variable 'count' declared at line 465 is uninitialized.
Variable 'count' has an undefined value, which is converted to 'NaN' at '-' operator.

Also, Condition 'count> 100' is always false at line 467.
because it conflicts with the previous condition 'count <0'.

**Comment by muxator** [comment]
This is so true, thanks!
Let's have a look ASAP.

In the meantime, note to self: this was introduced in 2013, with [5592c4b#diff-5d2aa4336c4964b828a123e20e09b73cR389](https://github.com/ether/etherpad-lite/commit/5592c4b0feb42082ab50e1c90753c28e5cd79334#diff-5d2aa4336c4964b828a123e20e09b73cR389).

**Comment by muxator** [comment]
At last :)
