### ISSUE TITLE
Markdown support. ep_markdown is abandoned

### ISSUE THREAD

**Issue by dessalines** [ether/etherpad-lite#3503]
I really need a way to import / export markdown, but unfortunately the markdown plugin is abandoned. Is there any chance of baking markdown support directly into etherpad? You can already import and export html without a plugin, this could be like that.

**Comment by JohnMcLear** [comment]
If I get time during C19 I will work on this.

**Comment by JohnMcLear** [comment]
Right all my other stuff is done so this is getting my attention now.   I'm not a huge user of Markdown so I will do what I can but I will need your input @dessalines -- are you available to collaborate?

**Comment by JohnMcLear** [comment]
Closing here and all issues need to go onto the plugin repo.  The plugin can be actively developed their.
