### ISSUE TITLE
Add password parameter when creating new pad

### ISSUE THREAD

**Issue by timtebeek** [ether/etherpad-lite#351]
Would it be possible to add a password parameter when creating a new pad? This way passwords can trivially be managed by users of an etherpad installation themselves, without needing an external management site using the API. The welcome page could then also be updated to add a password field to make it easy for users to use this functionality.
I'd envision this as a one time set operation, after which the user is left to distribute the password themselves, without any further password management.

**Comment by JohnMcLear** [comment]
Help us help you: https://www.bountysource.com/issues/1371947-add-password-parameter-when-creating-new-pad

**Comment by xi** [comment]
I tried to work on this feature, but then I realized that there are serious limitations. But maybe I'm wrong:

-  If anyone can set a password on a normal (non-group) pad, it is trivial to block other people from their own pads (DOS). So setting a password needs to be limited to pad creation.
-  Pads are not listed anywhere, so they are protected by a "you need to know the URL" mechanism. I don't really see how "you need to know the password" is significantly more secure.

I still feel like this feature would make sense somehow. But before I seriously start working on it I would like to understand the thread model.

**Comment by dcht00** [comment]
>     * Pads are not listed anywhere, so they are protected by a "you need to know the URL" mechanism. I don't really see how "you need to know the password" is significantly more secure.

I thought so too, but started reconsidering this because of the HTTP "referer" situation (leaking your link to external sites by following URLs there!), also see #1603 and recently #3636 . Thought this is relevant to mention here.

**Comment by muxator** [comment]
@dcht00: Etherpad **1.8.0** will change its referrer policy and stop sending `referer`.

Discussion: https://github.com/ether/etherpad-lite/pull/3636

**Comment by JohnMcLear** [comment]
Closing this as we're moving security outside of Etherpad.

**Comment by ge-fa** [comment]
On 20-05-06 09:00:00, John McLear wrote:
> Closing this as we're moving security outside of Etherpad.

@JohnMcLear Mind to elaborate?

**Comment by JohnMcLear** [comment]
The concept that Etherpad should store/maintain etc. passwords is IMHO bad practice.  Etherpad is not an authentication platform.  

User management & Authentication platforms exist (think Auth0) and do a very specific job very well.  50% of Etherpad's technical debt is this horrible auth etc. so we're ripping it out so we can focus on the features users want.  

This means plugins will provide different auth mechanisms (including password) and they can be responsible for password storage etc.  See ep_hash_auth for example...
