### ISSUE TITLE
Generate "unique" pad names

### ISSUE THREAD

**Issue by drebs** [ether/etherpad-lite#3516]
Hello, and thanks for the great piece of software!

Currently, etherpad-lite relies on the user's browser to generate a random pad name. The random function currently used is `Math.random()` which [does not provide cryptographically secure random numbers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random) and the generated pad name is not long enough (10 chars would lead to ~60-bit security if a PRNG was used). Because of those, the current solution is not safe against collisions.

If the expected behavior is to generate unique pad names, and that is delegated to the user's browser (i.e. there's no server-side check to ensure the generated name does not collide), i suggest the following:

* use a PRNG instead of `Math.random()` and ensure uniform distribution when selecting chars.
* choose the name length to achieve a specific number of bits of security.

The following is a suggestion:

```diff
diff --git a/src/templates/index.html b/src/templates/index.html
index 872367c9..f5dd4468 100644
--- a/src/templates/index.html
+++ b/src/templates/index.html
@@ -187,12 +187,22 @@
 
             function randomPadName()
             {
-                var chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
-                var string_length = 10;
+                // the number of distinct chars (64) is chosen to ensure that
+                // the selection will be uniform when using the PRNG below
+                var chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-+";
+                // the length of the pad name is chosen to get 120-bit security:
+                // log2(64^20) = 120
+                var string_length = 20;
+                // make room for 8-bit integer values that span from 0 to 255.
+                var randomarray = new Uint8Array(string_length);
+                // use browser's PRNG to generate a "unique" sequence
+                window.crypto.getRandomValues(randomarray);
                 var randomstring = '';
                 for (var i = 0; i < string_length; i++)
                 {
-                    var rnum = Math.floor(Math.random() * chars.length);
+                    // instead of writing "Math.floor(randomarray[i]/256*64)"
+                    // we can save some cycles.
+                    var rnum = Math.floor(randomarray[i]/4);
                     randomstring += chars.substring(rnum, rnum + 1);
                 }
                 return randomstring;
```

Might be related (not enough info on the motivation of the request): #3418

I will also create a PR, but of course feel free to suggest fixes, modifications or even re-implement in better ways.

**Comment by muxator** [comment]
Hi @drebs, thanks for the PR.

I have just two small observations, please have a look at [the code review](https://github.com/ether/etherpad-lite/pull/3517).

**Comment by drebs** [comment]
@muxator, thanks for the input, i have updated the PR (and marked conversations as resolved, i hope that's ok).

@Gared, do you think it makes sense to propose the same changes made here to the "new pad" plugin? At the very lease, the cryptographic quality of the randomness of the pad name provided by the server would be increased and would prevent possible collisions with pad names generated by outdated or malicious clients. Makes sense?
