### ISSUE TITLE
is it possible to set password for normal pads through the API ?

### ISSUE THREAD

**Issue by HamzaKhait** [ether/etherpad-lite#3518]
Hello,

is it possible to set password for **normal** pads through the API ? (Not group pads)

Thanks

**Comment by lpagliari** [comment]
I believe so. There's [an API method](http://etherpad.org/doc/v1.6.0/#index_setpassword_padid_password) to do that.

**Comment by HamzaKhait** [comment]
> I believe so. There's [an API method](http://etherpad.org/doc/v1.6.0/#index_setpassword_padid_password) to do that.

Well, not really, setPassword is only available for group Pads ...

**Comment by lpagliari** [comment]
Oh, you're right. I've just checked the source code and there's a validation for that. We definitely need to improve the docs for that method, this restriction is not clear.

**Comment by HamzaKhait** [comment]
Hello @lpagliari 
Any news about this feature ?

**Comment by slel** [comment]
Please fix the typo "se" -> "set" in the title/summary and first comment of this issue.
This will prevent wondering if "se" is a typo for "set" or "see" and having to dig in.

**Comment by HamzaKhait** [comment]
> Please fix the typo "se" -> "set" in the title/summary and first comment of this issue.
> This will prevent wondering if "se" is a typo for "set" or "see" and having to dig in.

Done. Sorry about that!

**Comment by slel** [comment]
No worries. Thanks for fixing and sorry for the noise.
