### ISSUE TITLE
How to develop locally

### ISSUE THREAD

**Issue by fabin5** [ether/etherpad-lite#3520]
Hello, if I want to do secondary development locally, I can't start debugging directly now. How can I do that?

**Comment by lpagliari** [comment]
If you want to debug files on `static/` folder, you can debug them. Now, if you want to debug files on server-side you need to run Etherpad on [debug mode](https://github.com/ether/etherpad-lite/wiki/Getting-to-know-the-tools-in-bin#debugrunsh) and have Node Inspector installed
