### ISSUE TITLE
Is this product for developers only?

### ISSUE THREAD

**Issue by miracleflame** [ether/etherpad-lite#3521]
I am looking into this thing for half an hour already and so far I was not able to establish just a simple one document shared with another person only. Such a trivial thing to accomplish and I'm still browsing through this maze of technical information to find a simple answer how to achieve this in the very first place.

Seriously is this project even aimed for general public? Or developers only? You know I am actually an "IT person" so you have an idea what impression this makes to any ordinary client.

**Comment by muxator** [comment]
Hi @miracleflame, every documentation can always be improved, and this project is certainly no exception.

If you describe a bit your platform & what you have tried to do, maybe we can help you, and hopefully improve the documentation in the meantime.

This project's requirements are basically very simple: a modern nodejs (>=6.9, **8.9** preferred), and a local copy of the source code (eventually cloned via git). A unix-like system is preferred but not required (you can also run on Windows, a package is provided).

If you are fluent with Docker, there is https://github.com/ether/etherpad-docker. We still do not have an official image on Docker hub, but it should be ready soon.

I have simplified a bit the README, which mentioned stale dependencies.

**Comment by muxator** [comment]
I think the most important part is this:

> what I see in the brower does not seem to offer some intuitive means to invite anyone to the contribution.

To share your pad, you would have to tell the other users the URL of the pad you want to work on.

Let's suppose you created a pad named `mypad`. If your host name is `myhost`, then the url would be `http://myhost:9001/p/padname`.

**Comment by miracleflame** [comment]
Ahhahhaha... so it was all about this. You know each time someone fails to figure things out by himself the reason is he expects it to be more complicated. Still consider adding some more elemental sentences regarding this to the first steps explanation. 

Similarly I was wondering how do I create a pad named mypad and similarly gave up on searching through the articles and tried the most easiest possible way.

Still I believe there is considerable number of people giving up entirely without asking just because those steps are not explicitly explained in common-folk language anywhere nearby.

Thank you for your support muxator. Close as you see fit.

**Comment by JohnMcLear** [comment]
+1 Simplifying docs and outputs to make Etherpad more user friendly, for example on Windows on start.bat we could fire up a browser to access Etherpad saving the user any interaction.

**Comment by JohnMcLear** [comment]
Closing as the user had the issue resolved and this is related to no commercial solution being available for "users".
