### ISSUE TITLE
strange export characters

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#3523]
Recently, my etherpad creates strange characters when exporting to PDF, using 
* Etherpad (github 49449453c9b268495663127b17c7a659ad4f3cf9 ) 
* LibreOffice 6.1.3.2 10(Build:2)
* debian 10

![grafik](https://user-images.githubusercontent.com/1151915/49693145-37bce980-fb6b-11e8-8c6a-c5fc5a975c23.png)

**Comment by muxator** [comment]
Hi @Wikinaut, works as usual, here.

I have tried with both Libreoffice 6.1.2.1 10(Build:1) (from ubuntu's repositories) and LibreOffice 6.1.3.2 86daf60bf00e (from https://www.libreoffice.org/download/download/).

Etherpad 49449453c9b2, node 8.14.0, ubuntu 18.10.

Could be something in your libreoffice's configuration?

**Comment by Wikinaut** [comment]
@muxator Any idea, where and how I could start debugging this issue?

**Comment by Wikinaut** [comment]
It looks like a font issue or so, but it worked (some months ago).

**Comment by Wikinaut** [comment]
Update: It may be, that some parts are missing
libreoffice --headless text.html text.pdf
javaldx: Could not find a Java Runtime Environment!
Please ensure that a JVM and the package libreoffice-java-common
is installed.
If it is already installed then try removing ~/.libreoffice/3/user/config/javasettings_Linux_*.xml
Warning: failed to read path from javaldx

**Comment by Wikinaut** [comment]
Looks to be a local problem with Libreoffice. Closing this issue.
