### ISSUE TITLE
Installer issue with nodejs 11.4 on debian 9

### ISSUE THREAD

**Issue by improvethings** [ether/etherpad-lite#3525]
ii  nodejs                          11.4.0-1nodesource1            amd64 

$ uname -srm
Linux 4.9.0-8-amd64 x86_64

$ cat /etc/issue
Debian GNU/Linux 9 \n \l

~/etherpad-lite$ bin/run.sh
/usr/lib/node_modules/npm/bin/npm-cli.js:85
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
Cannot extract npm major version from version string ""

**Comment by muxator** [comment]
This was probably reported with Etherpad <= **1.6.6** and with an old npm version in `node_modules`.
If so, doing a clean install (`rm -rf <basedir>/src/node_modules`) would have fixed the problem. Recent Etherpad versions (>=1.7) would not have had the problem, for a different reason.

Explanation:
Etherpad **1.6.6** had a lax dependency on npm, which was replaced with a strict one in 36b629346dfe.

Test:
```
$ docker run -ti --rm  node:11-stretch bash
# node --version
v11.14.0
root@398833d46d9b:/etherpad-lite# git checkout 1.6.6
HEAD is now at 275f1b1f... Merge new release into master branch

# cat src/node_modules/npm/package.json | grep '"version"'
  "version": "6.9.0"   <-- clean install on Etherpad 1.6.6 == recent, but time-depending npm version
# bin/run.sh --root # do not do this at home
[etherpad starts]
```


Closing, thanks for the report.
