### ISSUE TITLE
Dutch translation error

### ISSUE THREAD

**Issue by RickvLeeuwen** [ether/etherpad-lite#3529]
Hi,
When opening the main page where you can create or open a pad, the Dutch text says:
_Pad maken **op** openen met de naam:_
This should be: 
_Pad maken **of** openen met de naam:_

Please see pull request https://github.com/ether/etherpad-lite/pull/3530

**Comment by muxator** [comment]
Fixed by 02b3d427711805bf6f96d4ac6ba5e24d264db3f1, I guess.
Closing this.

**Comment by RickvLeeuwen** [comment]
Indeed, thank you!
