### ISSUE TITLE
Error: ER_NOT_SUPPORTED_AUTH_MODE

### ISSUE THREAD

**Issue by msongz** [ether/etherpad-lite#3532]
not work with:
Server version: 10.1.37-MariaDB-0+deb9u1 Raspbian 9.0

work with:
Server version: 10.1.23-MariaDB-0+deb9u1 Raspbian 9.0

**Comment by muxator** [comment]
Thanks for reaching out, @msongz, but without more information this issue will be hard to understand.

**Comment by msongz** [comment]
@muxator  I run etherpad on raspberry pi2 and with Dietpi image clean installed. then I config the mysql and not works with 10.1.37-MariaDB.

**Comment by MikaMaracuja** [comment]
same error on Server version: 10.1.37-MariaDB-0+deb9u1 Debian 9.6

Steps to reproduce:
Mysql Password stored and defined with .... IDENTIFIED by ('mysupersecretPA$$WORD').

then settings.json:

  "dbSettings" : {
                   "user"    : "etherpaduser",
                   "host"    : "localhost",
                   "port"    : 3306,
                   "password": "mysupersecretPA$$WORD",
                   "database": "etherpad_lite_db",
                   "charset" : "utf8mb4"
                 },


[2019-01-29 16:42:16.937] [ERROR] console - Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MariaDB client
    at Handshake.Sequence._packetToError (/var/www/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/var/www/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
    at Protocol._parsePacket (/var/www/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/var/www/etherpad-lite/src/node_modules/mysql/lib/protocol/Parser.js:76:12)

at startup time.

**Comment by MikaMaracuja** [comment]
also same issue on 
Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1

**Comment by JohnMcLear** [comment]
Afaik Maria / MySQL introduced some changes and there was mismatch on Maria/MySQL Client.  Needs fixing by updating the consumed npm client packages.

Afaik it's something to do w/ Sockets or so...

**Comment by JohnMcLear** [comment]
Looks like it was an upstream mariadb bug that's now resolved.
```
jose@server:~/etherpad-lite$ mariadb --version
mariadb  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
Works with the above version of Maria

**Comment by dcht00** [comment]
For whatever reason, I also had this message just now, while installing EP on some desktop. It was finishing some half-done installation, upgrading all of the parts in the process, so I can't really say for sure what caused it.

Versions:
```
Ubuntu 20.04, npm 9.5.1, node v18.16.0,
Etherpad version is 1.9.0 (facaee5),
mysql  Ver 15.1 Distrib 10.3.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

```

Anyway, to resolve it, I've followed the top answer here:
https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

However another answer claims it is unsafe, and recommends using a "mysql2" package, instead of the "mysql" one.
