### ISSUE TITLE
Link support, especially with closing punctuation

### ISSUE THREAD

**Issue by wbt** [ether/etherpad-lite#3533]
In documents, I frequently have a point followed by a URL in parentheses.  Pasting or typing a URL in an Etherpad, as long as it has the protocol, will automatically create a link (https://github.com/ether/etherpad-lite/issues/143), but the close parentheses are part of the link unless separated from the link by a nongrammatical space.  

However, clicking in the link between the last character of the URL and the close parentheses automatically follows the link (often to a 404 error) instead of letting the user fix the link.  Up to this point, that's a bug with unexpected software behavior negatively affecting what a user can do.

There does not seem to be an easily discoverable popup via toolbar button, right-click menu, or keyboard shortcut to change the link target, or to make text into a hyperlink so the document isn't quite so full of hard-to-read URLs interrupting flow.

The only workaround I've found is to click the Pad Settings (gear icon), activate Show Markdown, and learn markdown. This is not a good workaround for typical / new users.

I propose the following changes, with this Issue primarily focused on the first (please post updates below if you open separate Issues for others):

1.  [ ] Omit non-alphanumeric closing punctuation preceding a space from automatically created links.  MS Word, GitHub's editor, and others might have some inspiration to model from.
2.  [ ] Have an option to require CTRL+Click in order to follow a link, to ease link editing.
3.  [ ] Add an edit hyperlink dialog with fields for the link destination (href), the displayed text, and maybe an "open in new tab" checkbox, which I would have **on** by default.  The link destination (href) field has focus when this dialog comes up, for easy pasting of a copied URL.  The Enter button submits and dismisses the dialog.
4.  [ ] Add a toolbar button for the dialog in the previous item.  If text is selected when this button is pressed, it is automatically in the displayed text field.
5.  [ ] Add keyboard shortcuts CTRL+K and CTRL+L to bring up the dialog from two items up in this list.

GitHub and Stack Exchange's editors might also have some inspiration, even if requiring users to learn and use markdown.

**Comment by wbt** [comment]
Why is this WONTFIX?

**Comment by JohnMcLear** [comment]
Because plugins exist to change link behaviour.  Search the plugins for link and you will see various different approaches...  Sorry it should be closed and not left floating around.
