### ISSUE TITLE
Feature request: Audio channel

### ISSUE THREAD

**Issue by wbt** [ether/etherpad-lite#3534]
This is a long-shot feature request, but it seems like a decent place to anchor discussion.

When multiple Etherpad users are collaborating simultaneously but aren't physically co-located in the same room, it's common to use some audio and/or videoconferencing program to support audio discussion.   

This feature request is to bundle one in with Etherpad or better integrate with popular options so that it's not as much of a disjointed user experience using one platform for the audio and another for the text portion of the same collaboration session.

**Comment by JedMeister** [comment]
(Please note I am not an Etherpad developer - just an interested third party)

Personally, I think that integrating audio chat into the core of Etherpad is a bad idea. 

Whilst I'm aware that Etherpad is cross platform, I'm a big believer in the the Unix philosophy of ["do one thing and do it well"](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well).

In my mind, audio chat support is non-core functionality (i.e. feature creep) for Etherpad and therefore should not be part of the core software.

Having said that, I can certainly see how some sort of audio chat integration could be nice for some users. IMO a plugin to support integration with one (or more) of the myriad of existing audio chat platforms would be the best way to approach this.

Just my 2c...

**Comment by fcecagno** [comment]
There's a work in progress to integrate Etherpad with BigBlueButton, which is an open source webconferencing system, so it will provide not only an audio channel but also video channels, polls, recordings, among other collaboration features. See: https://github.com/bigbluebutton/bigbluebutton/pull/6510

**Comment by lpagliari** [comment]
@fcecagno wow, that would be awesome!!

Regarding the feature request, I agree with @JedMeister , it might be too much for Etherpad to do. **But** as this might be useful for other users, I would suggest implementing it as a plugin, not a core feature, so it would be available only for the instances that actually want to provide that feature for their users.

**Comment by slel** [comment]
The way [CoCalc](https://cocalc.com/index.html) does it is that chat files and the side chat
of any file have a button to start a video or audio chat (formerly using
appear-in, presently using jit-si).

**Comment by Adorfer** [comment]
the name "etherpad/lite" (it's second part) should stand for something.
mumble exists and coexists. And there are alread a ton of different WebRTS-Solutions available.
Just another platform (with registration, credentials etc) will create so much trouble and even scare users away. 
(up to now, the pad was really the lowtech approach. If people want stylish stuff with login, there is already other platforms. But there you get trapped in a tool discussion between compatiblity, ease of use, mobile dataplans, 2FA-logins etc.)

**Comment by wbt** [comment]
> the name "etherpad/lite" (it's second part) should stand for something.

Like "let's invent together engaged?" 

> there are alread a ton of different WebRTS-Solutions available.

Allowing one of those to be easily integrated is the target solution here.

> Just another platform (with registration, credentials etc) will create so much trouble and even scare users away. (up to now, the pad was really the lowtech approach. If people want stylish stuff with login, there is already other platforms. But there you get trapped in a tool discussion between compatiblity, ease of use, mobile dataplans, 2FA-logins etc.)

Why do you assume that adding an audio channel must necessarily require logins, registration, 2FA, etc.?
Authentication control for Etherpad collaboration is or at least should be a completely independent question.    

Unfortunately, by not having an audio channel directly in Etherpad, people who want to collaborate together _do_ have to find _another_ platform and go through its registration/auth process separately and in addition to any that may apply to the EtherPad they're working on, so they might be less likely to participate in a collaborative effort that could benefit from their contributions.  If Etherpad supported an easy audio channel among current collaborators who want to use it, maybe fewer people would be "scared away" by the technology chosen by their collaboration hosts.

**Comment by JohnMcLear** [comment]
https://github.com/bit/ep_webrtc/ is the solution for this.
