### ISSUE TITLE
Doesn't work with Phusion Passenger

### ISSUE THREAD

**Issue by poVoq** [ether/etherpad-lite#3535]
The wiki claims that it used to work with Phusion Passenger:
https://github.com/ether/etherpad-lite/wiki/Running-Etherpad-on-Phusion-Passenger

But at least on my shared host that uses it via Plesk it results in a lot of errors when trying to start it.
I fixed a few of them (for example why does it insists on everything being in a "ep_etherpad-lite" directory, when in reality everything is in a "src" directory. And it is also strange that it refers everywhere to files without the ".js" extension, which seems to cause issues).

In 1.7.0 the devDependencies in the package.json also cause issues (see: https://github.com/ether/etherpad-lite/issues/3460 ), but that doesn't seem to be the root cause of why it doesn't run.

Out of curiosity I tried to run version 1.4.1 on NodeJS 6.14.1 (which I guess was the setup at the time the above Wiki entry was last updated), but that seems to have the same issues as 1.7.0 with 9.10.1 with Phusion Passenger.

Any ideas? Thanks in advance!

Edit: the server runs nginx/1.11.10 Phusion_Passenger/5.1.11

**Comment by JohnMcLear** [comment]
Issue of Phusion, not Etherpad.

**Comment by ThorsenRune** [comment]
@poVoq poVoq did you ever solve that?

**Comment by poVoq** [comment]
no, but I stopped trying.

**Comment by ThorsenRune** [comment]
Thanks, ill stop trying then.
