### ISSUE TITLE
Deploying on heroku

### ISSUE THREAD

**Issue by Loghijiaha** [ether/etherpad-lite#3539]
When deploy etherpad-lite on heroku , it logs following error
`No default language could be detected for this app.

			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.

			See https://devcenter.heroku.com/articles/buildpacks

 !     Push failed
advance thanks in any help.
`

**Comment by JohnMcLear** [comment]
Heroku issue afaik
