### ISSUE TITLE
Move to async/await. Get rid of callback hell

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3540]
Currently (1.8pre), Etherpad code base is heavily based on callbacks. While this made sense at the time (~2011) JS ecosystem has moved forward, and better solutions exist.

We should investigate the possibility of migrating the code base to an `async/await` paradigm, in order to make the code easier on the eye of future contributors.

This move was anticipated in #3424. It is now time to start discussing it concretely.

As usual, the first concern is maintaining stability: this change is going to be wide, but should be as shallow as possible, ideally not containing any new functionality work. After this, hopefully the code base will be easier to reason about, less buggy, and new features will be easier to implement.

**Edit**: the Pull Request that implements this change is #3559.

**Comment by muxator** [comment]
Ray has completed the fist stage of his amazing work at https://github.com/raybellis/etherpad-lite/tree/async.

The review is being done at https://github.com/raybellis/etherpad-lite/tree/async-PR. That branch is a linear variant of Ray's work, rebased on the latest develop on which some adaptation are being made.

async-PR is a mutable branch, i.e. it will be periodically force-pushed until it is ready to be merged.

**Comment by muxator** [comment]
Branch [raybellis/async-PR](https://github.com/raybellis/etherpad-lite/tree/async-PR) is now deployed on https://beta.etherpad.org/ to allow widespread testing.

It will be periodically updated while the branch is audited.

**Comment by raybellis** [comment]
Please note that I've added a couple of extra commits to the `async` branch which relate to import and export.

**Comment by muxator** [comment]
Thanks, imported.

I am (slowly) going through the series, trying to:
- separate out purely syntactic changes from substantial ones (to ease later review and catch eventual bugs)
- split changes where possible (for example https://github.com/raybellis/etherpad-lite/commit/2075e6fd6acda938d605cc4f94c8522f342c4a8e in async contained a [condition inversion](https://github.com/raybellis/etherpad-lite/commit/1948ed9f93668a5af032123eea2767e535ab0807) and the part that strictly [introduced promises consumption](https://github.com/raybellis/etherpad-lite/commit/f2300e60be36fe8b0c5b6c9cf69f787fcf87668c ), so they can be examined separately.

This will take some time.

**Comment by Wikinaut** [comment]
Clarification request/question:

From the above I understand that the branch https://github.com/raybellis/etherpad-lite/tree/async-PR is now stable enough to try and test it on own instances.

Is my view correct?

**Comment by muxator** [comment]
Hi @Wikinaut, yes please, test as much as you can. Any info is welcome to help polishing this branch.
As soon as https://beta.etherpad.org/ comes back online it will host that branch, too.

@raybellis: is it possible to write here a brief list of known issues, if any?

**Comment by raybellis** [comment]
@muxator The only issue I'm currently aware of is a possible problem (to be confirmed) with importing ".etherpad" format files.

**Comment by muxator** [comment]
Yeah, the `.etherpad` export needs to be investigated.
Both on beta (which uses mysql) and locally (dirtydb) I am receiving `authorEntry is not defined` in `ExportEtherpad.js`.

```
[2019-02-21 22:43:06.969] [ERROR] console - (node:16064) UnhandledPromiseRejectionWarning: ReferenceError: authorEntry is not defined
    at Object.exports.getPadRaw (/home/etherpad-lite/etherpad-lite/src/node/utils/ExportEtherpad.js:49:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

BTW, I am frequently seeing another "author-related" error both in the beta and locally:

```
Error: Can't apply USER_CHANGES, because Trying to submit changes as another author in changeset Z:i>1|1=h*0|1+1$
    at handleUserChanges ([...]/src/node/handler/PadMessageHandler.js:638:13)
    at <anonymous>
```

**Comment by raybellis** [comment]
The first one is easily fixed (commit c5a633d5ca3c6c53f88fbf65d87537a1ec3e59d0 in my async branch).   I don't know what I was thinking there, but the double assignment of `authorEntry` is clearly incorrect.

The second one is going to require more investigation...

**Comment by raybellis** [comment]
I can't see how to replicate the `USER_CHANGES` issue - do you have some of the preceding log messages?

**Comment by muxator** [comment]
A recap of the issues so far:

1. ~~problem in `.etherpad` **export**~~. Fixed by Ray and integrated in async-PR. It works now;
2. problem in `.etherpad` **import**. To be investigated;
3. Sometimes a user change gets rejected with `Can't apply USER_CHANGES, because Trying to submit changes as another author in changeset XXX at handleUserChanges (PadMessageHandler.js)`. This is present in beta (logs are not verbose there), and I personally experienced it locally. I will try to describe a simple case to replicate it.

**Comment by muxator** [comment]
I think I found the problem with `.etherpad` import. It is a scope problem. emoving a `let` statement as explained in comments to https://github.com/raybellis/etherpad-lite/commit/af0a276fbaeddc4027d892bca514201d01ea0e86#diff-55dbdbca4a859fc5f879f68721f70cbcR30 should be enough.

**Comment by Wikinaut** [comment]
@raybellis @muxator I have now setup my test server using raybellis/async 39b0c7efdf2d86f84c11615e26cf9915bf7fb9a1 (and before, I tried, raybellis/async-PR  https://github.com/raybellis/etherpad-lite/commit/4bf1a434d44c792850bb643a9b2c04d78c65af42 ) branch.

Both branches currently fail to load a page. Let me know, when you have some news.

```
...
[2019-02-26 12:14:37.352] [INFO] ueberDB - Flushed 5 values
[2019-02-26 12:14:43.990] [ERROR] console - { inspect: [Function: inspect] }
[2019-02-26 12:14:45.576] [INFO] ueberDB - Flushed 1 values
...
[2019-02-26 12:14:45.677] [INFO] ueberDB - Flushed 1 values
[2019-02-26 12:14:45.911] [INFO] access - [ENTER] Pad "test": Client kFv_Vbak0IPr100-AAAA with IP "127.0.0.1" entered the pad
[2019-02-26 12:14:45.913] [ERROR] console - (node:1489) UnhandledPromiseRejectionWarning: ReferenceError: newVars is not defined
    at handleClientReady (/srv/etherpad/src/node/handler/PadMessageHandler.js:1132:28)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
[2019-02-26 12:14:45.914] [ERROR] console - (node:1489) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[2019-02-26 12:14:45.914] [ERROR] console - (node:1489) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-02-26 12:14:45.984] [INFO] ueberDB - Flushed 1 values
```

**Comment by raybellis** [comment]
@Wikinaut thanks for the report - fixed in commit f8a26cbf44a2a2aa090e65d4c1a05a2fe31f82cb in my async branch

**Comment by muxator** [comment]
Integrated in async-PR with the original change that touched SecurityManager.js and some related functions (https://github.com/ether/etherpad-lite/commit/ee034566184c52e2a62d4dcadef244881019ece6#diff-5d2aa4336c4964b828a123e20e09b73cR1230), and deployed on beta.

I never encountered that error, btw. Thanks to @Wikinaut's testing.

**Comment by Wikinaut** [comment]
@raybellis Confirmed, https://github.com/ether/etherpad-lite/commit/f8a26cbf44a2a2aa090e65d4c1a05a2fe31f82cb works! Thank you.

I see one error:

```
2019-02-26 23:23:23.066] [INFO] ueberDB - Flushed 1 values
[2019-02-26 23:23:26.081] [ERROR] console - { inspect: [Function: inspect] }
...
[2019-02-26 23:23:28.681] [INFO] ueberDB - Flushed 1 values
[2019-02-26 23:23:29.045] [INFO] access - [ENTER] Pad "test": Client AlC0RET9-mC4OmtLAAAA with IP "XXX" entered the pad
[2019-02-26 23:23:29.987] [INFO] ueberDB - Flushed 1 values
[2019-02-26 23:23:32.428] [WARN] console - Getting pad email stuff for test
[2019-02-26 23:23:32.431] [WARN] console - padId is test
...
[2019-02-26 23:23:32.993] [INFO] ueberDB - Flushed 3 values

```

**Comment by Wikinaut** [comment]
And I see 
```
[ERROR] console - (node:3464)
[DEP0096] DeprecationWarning: timers.unenroll() is deprecated.
Please use clearTimeout instead.
```
This Error is also present in the callback version.

**Comment by muxator** [comment]
> And I see
> 
> ```
> [ERROR] console - (node:3464)
> [DEP0096] DeprecationWarning: timers.unenroll() is deprecated.
> Please use clearTimeout instead.
> ```
> 
> This Error is also present in the callback version.

I think this is #3472.

**Comment by Wikinaut** [comment]
I am now checking the compatibility with my plugins; I will present a list of the working plugins soon, but this

* https://npmjs.org/package/ep_small_list

is not working, perhaps @raybellis can you have a look, why "small_list" appears not to work with the async branch?

**Comment by raybellis** [comment]
@Wikinaut I'll take a look, but my suspicion is that 1.8 will be incompatible with most (if not all) existing plugins because none of the exposed functions take a final `callback` parameter any more.    For those, a simple solution is to use the `nodeify` module to turn a Promise-based API back into a NodeJS style `callback(err, result)` one.

**Comment by muxator** [comment]
This is probably worh a dedicated issue.

@raybellis, could you open one with a brief description so we can keep track of it?

**Comment by Wikinaut** [comment]
Are you interested in the list of my plugins which run (on the async version) without apparent issues?

**Comment by raybellis** [comment]
@Wikinaut that would be useful, but on the other ticket (#3566) please.

**Comment by raybellis** [comment]
Back-end test failures with the SessionManager on the async branches were mentioned (and resolved) at https://github.com/ether/etherpad-lite/issues/3567#issuecomment-468613960

**Comment by muxator** [comment]
It's done. See https://github.com/ether/etherpad-lite/pull/3559#issuecomment-470342390.
