### ISSUE TITLE
showChat attribute doesnt work

### ISSUE THREAD

**Issue by kostaspa** [ether/etherpad-lite#3541]
Hello,
i found that the chat cannot be disabled if you previously have visited the same or even another pad, where the chat was maximized. 
Here is an example, visit the following link https://beta.etherpad.org/p/thisisanotheronepad and maximize the chat by pressing the orthogonal item which when you hover on it, says "stick chat to screen". Now visit the below link https://beta.etherpad.org/p/thisisanotheronepad?showChat=false which is the same as above with the only difference the attribute showChat=false. The chat should not be visible but it is. I also found that if you minimize the chat and you refresh the page, on the below link https://beta.etherpad.org/p/thisisanotheronepad?showChat=false only then the chat is not visible and it works as it should.
thank you, 
i hope that was helpful !

**Comment by kostaspa** [comment]
Do you think that there is any temporary solution?
I tried the below code on the file src/static/custom/pad.js but still does not  work.

function customStart()
{
  var urlParams = new URLSearchParams(window.location.search);
  var showChat = urlParams.get('showChat');

  if(showChat == 'true'){
    document.getElementById('chatbox').style.display = 'none';
    document.getElementById('chaticon').style.display = 'none';    
  }
}

Can someone help me?

Thank you in Advance.

**Comment by kostaspa** [comment]
I found a temporary solution, I comment out the lines with he following code from the file /src/static/js/pad.js
      if(padcookie.getPref("chatAlwaysVisible")){ // if we have a cookie for always showing chat then show it
        chat.stickToScreen(true); // stick it to the screen
         $('#options-stickychat').prop("checked", true); // set the checkbox to on
      }
If you a better solution, it would be great,
thank you in advance!

**Comment by JohnMcLear** [comment]
When you paste Code into Github please use three `'s so the code is properly formatted.  I went in and did an example for you.

**Comment by kostaspa** [comment]
@JohnMcLear  thank you! What do you think about the solution, can this code be in some kind of plugin?

**Comment by JohnMcLear** [comment]
Waiting on review/merge.
