### ISSUE TITLE
code smell in src/node/express/apicalls.js

### ISSUE THREAD

**Issue by raybellis** [ether/etherpad-lite#3544]
The `apiCaller` function wraps `res.send` in its own function, storing the original `res.send` in the variable `res._____send`.

There's no need for the assignment back to `res` - the original function reference can be stored in a local variable `send` and then invoked with `send.call(res, response)` (to maintain the context, if required).

**Comment by raybellis** [comment]
The same pattern is in `src/node/hooks/express/swagger.js`.

**Comment by JohnMcLear** [comment]
@muxator is this now solved due to the move to openapi?

**Comment by muxator** [comment]
For context, the migration to OpenAPI is being done with #3786.

The `apiCaller()` function is gone in that version. The commit that nukes it (pre-review) is https://github.com/ether/etherpad-lite/commit/26044a267e195ea872f22cbe4fdc7b9df27b7bb6.

Closing this.
Thanks.
