### ISSUE TITLE
bin/repairPad.js completely non-functional?

### ISSUE THREAD

**Issue by raybellis** [ether/etherpad-lite#3545]
I'm reading the source for bin/repairPad, and it seems like it doesn't remotely do what it says it does.

The final loop where it iterates over the keys does this:

    neededDBValues.forEach(function(key, value) {
      console.debug("Key: "+key+", value: "+value);
      db.remove(key);
      db.set(key, value);
    })

but `neededDBValues` is a plain 1D array, so the value being passed through here is just the array entry number per the usual `Array#forEach` callback.   There is _no code_ in the script to retrieve the existing values for those keys.

Fortunately it seems that because these function calls just go into ueberdb2's cache and there's a `process.exit()` call immediately after the loop with no call to `db.doShutdown()` no changes are actually made to the database.

**Comment by JohnMcLear** [comment]
Lots of weirdness here..  I wonder how this landed..  We defo need a way to replicate so we can fix the logic tho..  Maybe someone can upload a working & broken ueberdb database file or so ??

**Comment by gnd** [comment]
Hi, while trying to repair a broken pad with bin/repairPad.js it finishes with:

`[2020-09-25 10:36:08.174] [INFO] console - aborting [gitlab #3545]`

Is that still of interest for this ticket ?

**Comment by JohnMcLear** [comment]
I think it checks the pad but never does the repair, unless I'm mistaken.
