### ISSUE TITLE
Set text area width

### ISSUE THREAD

**Issue by akshaysgithub** [ether/etherpad-lite#3547]
Hello friends,

I am trying to set the size of text-area. As you can see from the image, it's kind of in the middle. I tried to edit pad.css options for no-skin. But it didn't help. I am running latest etherpad, as i just did a git pull today. Also, I have some default pad options, which I would like to completely remove. For example, the RTL option, I would like to remove it from pad-options. How can I do that? I already tried to remove them from pad.js, didn't help. Adding screenshots for both with imgur links. Thank you.

[https://imgur.com/txEf2n9](url)

[https://imgur.com/pUaN2QG](url)

**Comment by lpagliari** [comment]
> Also, I have some default pad options, which I would like to completely remove. For example, the RTL option, I would like to remove it from pad-options. How can I do that?

@akshaysgithub on `pad.js` of your skin, you can remove it using jQuery:
```
$('#settings p:has(#options-rtlcheck)').remove()
```

**Comment by akshaysgithub** [comment]
> > Also, I have some default pad options, which I would like to completely remove. For example, the RTL option, I would like to remove it from pad-options. How can I do that?
> 
> @akshaysgithub on `pad.js` of your skin, you can remove it using jQuery:
> 
> ```
> $('#settings p:has(#options-rtlcheck)').remove()
> ```

Hi,

As you can see in the screenshot below, I have added the option you mentioned in my pad.js. But that has not changed anything. Can you also please tell me how I can increase the width of text area . Thank you. 
[https://imgur.com/a/ASiQ4BR](url)

Skin link : [https://framagit.org/colibris/etherpad-custom-colibris](url)

**Comment by lpagliari** [comment]
The code should be **inside** the `customStart` body, not outside of it.

And I see that you've added the code with back-ticks around it:

![image](https://user-images.githubusercontent.com/836386/52413531-0c9e3a00-2ac9-11e9-9a95-4c34f0d8d7aa.png)

It should not have them. Please remove the **`** and try again
