### ISSUE TITLE
chatandusers in colibris skin

### ISSUE THREAD

**Issue by ezzra** [ether/etherpad-lite#3548]
whn chatandusers is activated (by settings.json or using pad settings) in colibri skin, the users overlay covers the chat and its not possible to hide with clicking on the user button.

![screenshot_2019-02-08_16-07-55](https://user-images.githubusercontent.com/37742522/52486712-28363d00-2bbc-11e9-8780-a00ea85bfe4b.png)

**Comment by muxator** [comment]
Thanks for the report, @ezzra, the skin is new and we are looking forward to stabilize it.

@seballot, can you have a look?

**Comment by seballot** [comment]
Sure will have a look asap !

**Comment by muxator** [comment]
Hi, @seballot, I am busy with #3540. I will test & merge this ASAP.

**Comment by muxator** [comment]
#3555 deployed in https://beta.etherpad.org (together with #3554), please test.
