### ISSUE TITLE
colibris: no colors for names in chat

### ISSUE THREAD

**Issue by ezzra** [ether/etherpad-lite#3549]
The names in the chat are not colored in the colibris skin. Thats a useful feature in the original no-skin because its possible see what changes the chatuser made.

**Comment by muxator** [comment]
@seballot can you have a look?

**Comment by muxator** [comment]
Hi, @seballot, I am busy with #3540, will test & merge this ASAP.

**Comment by muxator** [comment]
Fixed with #3555, closing.
