### ISSUE TITLE
Manual installation on Windows: [ERROR] AbsolutePaths - Could not identity Etherpad base path in this win32 installation in "C:\etherpad-lite\src"

### ISSUE THREAD

**Issue by AirQuick** [ether/etherpad-lite#3550]
Etherpad manually installed on Windows doesn't work. Node fails to run with this error:
> [ERROR] AbsolutePaths - Could not identity Etherpad base path in this win32 installation in "C:\etherpad-lite\src"

### Steps to repro

1. Log on to Windows 10 1803 x64.

1. Install Node.js.
  https://nodejs.org/dist/v10.15.1/node-v10.15.1-x64.msi
  Accept the default options during the installation.

1. Install Git for Windows.
  https://github.com/git-for-windows/git/releases/download/v2.20.1.windows.1/Git-2.20.1-64-bit.exe
  Accept the default options during the installation.

1. Restart Windows.
  Just to make sure the prerequisite installations take effect.

1. Run `C:\Windows\System32\cmd.exe` as administrator (i.e. UAC elevated).

1. Install Etherpad and run it.
    1. Go to `C:\`
    1. Clone the repository master branch
    1. Go to `C:\etherpad-lite`
    1. Run the installation script (`bin\installOnWindows.bat`)
    1. Run `start.bat`

```console
Microsoft Windows [Version 10.0.17134.1]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd \

C:\>git clone --branch master https://github.com/ether/etherpad-lite.git
Cloning into 'etherpad-lite'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 31721 (delta 0), reused 1 (delta 0), pack-reused 31716 eceiving objects: 100% (31721/31721), 19.05 MiB | 3Receiving objects: 100% (31721/31721), 20.15 MiB | 3.92 MiB/s, done.

Resolving deltas: 100% (22590/22590), done.

C:\>cd etherpad-lite

C:\etherpad-lite>bin\installOnWindows.bat
_
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
symbolic link created for ep_etherpad-lite <<===>> ..\src
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

> wd@1.11.1 install C:\etherpad-lite\node_modules\ep_etherpad-lite\node_modules\wd
> node scripts/build-browser-scripts

added 1050 packages from 1461 contributors and audited 8186 packages in 121.953s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
_
Clearing cache...
Could Not Find C:\etherpad-lite\var\minified*
_
Setting up settings.json...
Can't find settings.json.
Copying settings.json.template...
        1 file(s) copied.
_
Installed Etherpad!  To run Etherpad type start.bat

C:\etherpad-lite>start.bat

C:\etherpad-lite>node node_modules\ep_etherpad-lite\node\server.js
[2019-02-08 23:32:24.837] [DEBUG] console - Running on Node v10.15.1 (minimum required Node version: 6.9.0)
[2019-02-08 23:32:25.009] [DEBUG] AbsolutePaths - C:\etherpad-lite\src does not end with "node_modules\ep_etherpad-lite"
[2019-02-08 23:32:25.009] [ERROR] AbsolutePaths - Could not identity Etherpad base path in this win32 installation in "C:\etherpad-lite\src"

C:\etherpad-lite>
```

**Comment by muxator** [comment]
Thanks for the report, @AirQuick.

It is indeed an oversight in:

https://github.com/ether/etherpad-lite/blob/6a3e4c69b8e83ff98c468529bc6a0ba1698a7526/src/node/utils/AbsolutePaths.js#L84-L92

where I have inadvertently assumed that the only way of running Etherpad on Windows would have been using [the Windows package](http://etherpad.org/downloads/etherpad-lite-win-1.7.5-6a3e4c69b8.zip), leaving out this case ([manually install on Windows](https://github.com/ether/etherpad-lite#manually-install-on-windows)).

If you need to run it now, please replace `if (process.platform === 'win32')` with `if (false)` (or use the prebuilt package), while a proper patch is produced.

**Comment by muxator** [comment]
@AirQuick, could you please take the version of [AbsolutePaths.js from PR 3551](https://github.com/ether/etherpad-lite/blob/1dbce28684f8e78f5f5dd2f42a8ec0104a136c6f/src/node/utils/AbsolutePaths.js) and verify if it solves your issue?

**Comment by AirQuick** [comment]
Thanks, @muxator,
Using the exact same steps above but this time using you PR branch, the manual installation started to work:
```console
...
C:\>git clone --branch develop https://github.com/muxator/etherpad-lite.git
...
C:\etherpad-lite>start.bat

C:\etherpad-lite>node node_modules\ep_etherpad-lite\node\server.js
[2019-02-11 09:55:35.389] [DEBUG] console - Running on Node v10.15.1 (minimum required Node version: 6.9.0)
[2019-02-11 09:55:35.655] [INFO] console - All relative paths will be interpreted relative to the identified Etherpad base dir: C:\etherpad-lite
[2019-02-11 09:55:35.671] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "C:\etherpad-lite\settings.json"
[2019-02-11 09:55:35.671] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "C:\etherpad-lite\credentials.json"
[2019-02-11 09:55:35.671] [INFO] console - Settings loaded from: C:\etherpad-lite\settings.json
...
[2019-02-11 09:55:40.296] [WARN] console - Etherpad is running in Development mode.  This mode is slower for users and less secure than production mode.  You should set the NODE_ENV environment variable to production by using: export NODE_ENV=production
```

**Comment by muxator** [comment]
Nice. I'll merge the PR then.

Thanks for catching this!
