### ISSUE TITLE
beta.etherpad.org is offline

### ISSUE THREAD

**Issue by gabriel-lucas** [ether/etherpad-lite#3552]
@Gared @webzwo0i 

Do you know who is in charge of this?
Thanks :)

**Comment by gnd** [comment]
hi ! i have the same q ..

**Comment by Gared** [comment]
I don't know why, but the server was off. So I booted it up and it's working again :-)

**Comment by Gared** [comment]
Okay, I broke the server finally...
I will set up a newly installed server and migrate everything. Please email me if you have important scripts/files on the server
