### ISSUE TITLE
Import of text-file makes timeslider behave wierdly

### ISSUE THREAD

**Issue by dbauer91** [ether/etherpad-lite#3560]
Good Morning,

I recently got around to updating my Etherpad installation to version 1.7.5 and wanted to check up on some older internal bug reports, where I stumbled upon some weird behavior in regards to the time slider and imported text files.

After importing a plaintext file, the timeslider can be moved, but the content of the pad is "stuck" on the last imported revision. Only after moving to revision 0, it functions properly again, until reaching another import, where the same issue happens yet again.

Steps to reproduce:
1. Open a new pad and write some text
2. Import a plaintext file
3. Take a look at the pads history

To make this easier to understand: Here's a gif of the issue at hand
![peek 2019-02-22 12-55](https://user-images.githubusercontent.com/42297094/53241207-47939680-36a1-11e9-96db-24a9ada929b0.gif)

I searched for existing bug reports regarding this issue, but could not find any. If this is a duplicate, please excuse the inconvenience.

With kind regards
Dirk Bauer

**Comment by JohnMcLear** [comment]
I can't replicate this.  Can you still replicate on latest Etherpad?  If so let me know and I will re-open.  Also things like database info would be useful.

**Comment by eloyesp** [comment]
It seems to happen almost the same on the board.net instance (but going to revision 0 does not fix it :( )

**Comment by JohnMcLear** [comment]
Is board.net running latest develop?

**Comment by eloyesp** [comment]
I'm not sure and I don't know if there is an endpoint to check that.

**Comment by eloyesp** [comment]
I'm not sure, I've submitted an issue there https://git.fairkom.net/hosting/board.net/issues/39 .
