### ISSUE TITLE
Secure flag is not set for cookies in HTTPS

### ISSUE THREAD

**Issue by HamzaKhait** [ether/etherpad-lite#3561]
Hello,

I noticed that Etherpad doesn't use "secure" flag for 3 cookies : 

- **express_sid**
- **io**
- **language**

![image](https://user-images.githubusercontent.com/11749913/53251456-f98c8c00-36bc-11e9-88ed-ad3e5906e586.png)

my Etherpad instance is behind Nginx reverse proxy whose configuration contains the header 
`proxy_set_header X-Forwarded-Proto $scheme`

Any ideas how to solve this ?
Thanks

**Comment by muxator** [comment]
ACK, needs to be fixed in a way that is coherent with node native TLS, which could be enabled via `config.ssl`.

**Comment by HamzaKhait** [comment]
Hello and thanks for the answer.
If I am not mistaken, this will be fixed in Etherpad 1.8 right ?

**Comment by muxator** [comment]
Hi, yeah, it's on the radar.

**Comment by muxator** [comment]
Hi @HamzaKhait, I finally found the time to address this issue.

Now the `secure` flag is correctly set for all the cookies, see the attached screenshot.

![cookies](https://user-images.githubusercontent.com/4067621/70369116-ad5db180-18b4-11ea-9e46-88f59bee574e.png)

Please note that:

1. if you are using a reverse proxy for terminating the SSL it is **mandatory** to set `trustProxy` in `settings.json`. I have updated the comments in `settings.json.template` to make it more explicit;
2. with this change (from Etherpad **1.8.0**) it is not possible to serve the same instance both in cleartext and over ssl. It was not a good practice anyway, but now is simply unsupported;
3. the `io` cookie was deleted. It may be needed for some socket.io deployments, but not for Etherpad (see the relevant explanation).
