### ISSUE TITLE
Ordered list, unordered list, indent an outdent doesn't work in normal view

### ISSUE THREAD

**Issue by jwevhn** [ether/etherpad-lite#3565]
Using etherpad 1.7.5, node 9.11.2 on CentOS7 with mariadb. Everything works, but these 4 Buttons 
ordered list, unordered list, indent an outdent
doesn't show any effect in the normal pad view. In Timeslider lists an in/outdent are shown correct. Also when exporting it they are correctly shown. Same effect on several browsers. Other formatings i.e. bold, italic, underline are ok.

Many thanks for help or ideas to solve.
Juergen

**Comment by lpagliari** [comment]
hi, @jwevhn, are you using any plugin?

**Comment by jwevhn** [comment]
hi, @lpagliari, i have only the adminpad plugin installed.

**Comment by lpagliari** [comment]
I've created an example on https://beta.etherpad.org/p/LFP, and it seems to be working fine. @jwevhn, could you inspect the CSS styles on your instance, and check if the styles for `ul` (or `ol`) are being overwritten?

Maybe there's something on the theme you're using. CSS was the only option I could think of...

**Comment by jwevhn** [comment]
First of all, many thanks for your support. I tried your pad https://beta.etherpad.org/p/LFP and found that if you export the part from line 1 to 14 there are different results in numbers when exporting to txt or exporting to pdf or word. Wrote it on the pad itself to show you, so when you're exporting again it's propably cascading.
In my own installation i found out, it's working when i'm accessing the pad directly with <IP>:9001.
But list's are not working when accessing with nginx-proxy. That narrows the problem, but doesn't solve it till now.

**Comment by lpagliari** [comment]
Did you get the chance to take a look on the CSS styles?
![image](https://user-images.githubusercontent.com/836386/53563620-5f509c00-3b33-11e9-8219-3f96ec299947.png)

Maybe you have something like this, which would block the visual changes to lists:
```
ul {
  list-style-type: none;
}
```

**Comment by jwevhn** [comment]
I'm sorry, i am not very confirme with CSS Styles. I found something like:
![28-02-2019 16-01-41](https://user-images.githubusercontent.com/37309605/53575916-dbb69f80-3b72-11e9-847c-a29964d6d9a2.jpg)

I think it must be something wrong inside the nginx-proxy config. I' ll try to find that out, probably not until the beginning of next week, because lack of time now.

**Comment by jwevhn** [comment]
After some strange effekts i started with a new clone of git ep version 1.7.5 and it seems to work now as it should. I guess there was something left from former tests with the headings2 plugin and that doesn't seem to be ready for ep 1.7.5 or even not for 1.7.0 as described here:
https://github.com/ether/ep_headings2/issues/19
Nevertheless many thanks for help.
