### ISSUE TITLE
Async API changes may break plugins

### ISSUE THREAD

**Issue by raybellis** [ether/etherpad-lite#3566]
Most of the exported functions from the Etherpad internals will no longer take callback parameters in Etherpad 1.8+ (see #3540) and return Promises instead.  This may break plugins that rely on those functions.

If backwards compatibility is required one solution may be to use the `nodeify` module to conditionally wrap the invocations of those exported functions.

**Comment by raybellis** [comment]
Here's an example of how an existing plugin has been modified to provide backwards compatibility:

https://github.com/raybellis/ep_small_list

and also an example of how that same plugin would now be written if backwards compatibility is not required:

https://gist.github.com/raybellis/0a99d4762364605223bb79f84e4d59cf

**Comment by raybellis** [comment]
We should probably add some sort of Etherpad API versioning to the internal modules (collectively, not per module) so that the /admin page can indicate which plugins are compatible.

**Comment by Wikinaut** [comment]
@raybellis Just as an idea: perhaps the compatibility can programmatically be tested at runtime, perhaps at least in some cases.

**Comment by raybellis** [comment]
@Wikinaut  see the other ticket ;-)

**Comment by raybellis** [comment]
@Wikinaut see my forked version of your plugin, which does just that.

**Comment by Wikinaut** [comment]
@raybellis In general I meant above: Etherpad _core_ (admin module) can _perhaps_ test (with assertions?) whether or not the installed plugins are async-compatible.

**Comment by raybellis** [comment]
Oh, I see - the other way around?    That's kind of what I meant by a versioning system, i.e. an expectation that each plugin's `ep.json` file specifies its minimum required Etherpad version.  It would be *very* difficult to actually programmatically figure out whether a plugin is using callbacks or not.

**Comment by raybellis** [comment]
I've made good progress writing some additional code that adds callback compatibility back into all of the exported functions that are now `async`, such that the `ep_small_list` plugin now works again without modification.

The code is slightly hacky, insomuch as it uses `eval` to create a new wrapper function that has the same arity as the existing functions.   It's committed to my async branch (commit 64fdc73cdc47829fcb19f3e82c878a5f94e00f0d) so that it can be cherry picked if you want it.

Further testing is however stalled due to #3567.

**Comment by Wikinaut** [comment]
@raybellis I confirm that also my installation (currently 64fdc73cdc47829fcb19f3e82c878a5f94e00f0d ) is now working with the original ```ep_small_list``` plugin.

**Comment by muxator** [comment]
Hi, I still did not integrate this into async-PR.

**Comment by muxator** [comment]
Hi, I am going to merge https://github.com/ether/etherpad-lite/pull/3559 now. It contains all of your work on the async branch, **except** for your proposed fix for this issue (https://github.com/ether/etherpad-lite/commit/64fdc73cdc47829fcb19f3e82c878a5f94e00f0d), to give us more time to think about a solution.

If we'll continue to like that approach, please remember me to cherry pick this change in the next days.

**Comment by raybellis** [comment]
The `eval` hack is only necessary to preserve the arity of the original functions, and was added to allow clients of the API elect to probe the arity to check whether the API is callback or promise -based (per my first attempt to show how to support either model).

Since the patch adds back in the ability to use either method based on the arguments received the support for arity testing could be dropped, and the wrappers generated as simple closures.

**Comment by muxator** [comment]
I have lost context about this issue, but I am going to release **1.8.0** anyway.
Moving to **1.8.1** to keep track of it.

**Comment by mspae** [comment]
I've cloned two existing but apprently not maintained plugins and refactored them to work with the async functions:
* https://gitlab.com/gebrauchsgrafik/ep_httpauth_author (original: ep_auth_author)
* https://gitlab.com/gebrauchsgrafik/ep_pad_overview (original plugin: ep_pad-lister)

**Comment by JohnMcLear** [comment]
Hey guys, I can refactor my plugins to support this new approach as soon as it's landed.

**Comment by muxator** [comment]
We can close this issue, now that the first point release (**1.8.3**) after the async rewrite (**1.8.0**) is ready to be released, and the few actively maintained plugins have been adapted.

Thanks.
