### ISSUE TITLE
HTTP API needs POST for large parameters in NodeJS 8.14+

### ISSUE THREAD

**Issue by raybellis** [ether/etherpad-lite#3568]
NodeJS 8.14.0 introduced a limit of 8KB to the size of HTTP headers that can be received.

This prevents HTTP API methods such as `setText` from working if the text content exceeds that size.

A possible solution would be to support the `POST` method in addition to `GET`, with any JSON object found in the HTTP body augmenting the URL parameters.

**Comment by raybellis** [comment]
On further inspection, the API already has _some_ support for `POST`, but it's not documented.

**Comment by raybellis** [comment]
Potential fix in branch `http-post` (commit 882b93487fe2bbd47a1cbab1b7d7b4b16bae5015) which allows all backend tests to pass 

If the preference is to allow _only_ body parameters in an HTTP POST then please advise, and I'll amend the patch and tests accordingly.    Also, the EP docs make no mention of HTTP POST support nor how to use it.   I'll wait to submit a PR until I hear back.

**Comment by muxator** [comment]
I did not write the API spec, and it is on the wild for a long time now, so the following is just


I think it is more reasonable to maintain backwards compatibility as much as possible, and so retaining GET seems sensible.

**Comment by raybellis** [comment]
In which case I think you should be able to cherry pick that commit, although the API documentation does need an update to mention POST and the need to use it if the data is too large.

**Comment by muxator** [comment]
(sorry I hit CTRL+ENTER and posted an half backed comment).

Apart from the documentation (that should be updated), would it be possible to print a WARN in the logs when receiving a GET with a too big payload on node 8.14+? That would give an operator some hints about what needs to be done to maintain a working installation.

If, instead, it is the node runtime that discardeds the request at a low level, it would never hit the application, and nothing could be done.

**Comment by raybellis** [comment]
I'm a little fuzzy on the details right now, but ISTR it was the latter.

The question on `GET` vs `POST` was not about deprecating the former, but whether the `POST` handler should work as my patch currently does, and _combine_ the parameters supplied in the body with those in the query string (with the former taking precedence) or alternatively completely ignore any that are in the query string and only use those found in the `POST` body.

The disadvantage of the "body only" approach is that it then becomes mandatory to put things like the `padID` field in the body (for `POST` requests).

**Comment by muxator** [comment]
The approach taken in your patch (`GET` parameters are read, and eventually overridden by `POST` parameters of the same name) is the most sensible.

Ignore my comment on using GET vs POST: it was a rambling about how I would have designed the API in the first place. Totally not relevant now.

**Comment by muxator** [comment]
Note to self for the documentation:

Example of a command line invocation of the setHTML API that works with 882b93487fe2bbd47a1cbab1b7d7b4b16bae5015:

```
curl -XPOST "http://localhost:9001/api/1/setHTML?apikey=<API_KEY>&padID=<PAD_ID>" -H "Content-Type: application/json" --data '{"html":"<html><body>Text content</body></html>"}'
```

To be noted is that the header `Content-Type: application/json` is mandatory: without it the invocation fails with:

```json
{"code":1,"message":"html is not a string","data":null}

```
