### ISSUE TITLE
Is there a hard limit to the # of concurrent users on a pad?

### ISSUE THREAD

**Issue by erstwhile** [ether/etherpad-lite#357]
We're using Etherpad-Lite for collaborative note-taking and transcripts of large conference calls but people from the calls are claiming to be bumping up against a 60-user limit.  Is there a configurable (or hardcoded) limit on users?

This may be something particular to the riseup.net implementation

**Comment by ramancode** [comment]
If I do the load-balance by pad id route, 
Is it possible ?
is there a good up-to-date resource on the best way to implement this?

**Comment by JohnMcLear** [comment]
@ramancode are you actually experiencing issues with load limits or are you just over-engineering because you think it's a good idea?
