### ISSUE TITLE
DigitalOcean Marketplace

### ISSUE THREAD

**Issue by kattti** [ether/etherpad-lite#3570]
What do you think of adding Etherpad to the @digitalocean [marketplace](https://marketplace.digitalocean.com/category/all)?

**Comment by muxator** [comment]
Hi, I do not know Digital Ocean's marketplace. Right now I would like to first bring in good shape Docker support.

So: I have no objections, but I cannot commit on it right now.

**Comment by JohnMcLear** [comment]
If Digital Ocean wanna create a package/config whatever for their platform that's cool with us but we don't want to do their development work for their products.

For now people can install docker on DO then install Etherpad through that no?  How far do we go at supporting each platform, I say it's up to the upstream providers to put some work in IMHO.
