### ISSUE TITLE
Docker support for arm processors

### ISSUE THREAD

**Issue by krystian-wojtas** [ether/etherpad-lite#3571]
It would be great if etherpad could run in docker container on arm host.

Currently it supports only x86 architecture.

I rebuilt docker image on my own arm 64 host from yours Dockerfile and it succedded :) Then I uploded this image to docker hub here
https://hub.docker.com/r/kwojtas1/etherpad

I believe that it would be much better if arm processor could be supported officialy. Like in nextcloud case user runs command
```
docker pull nextcloud
```
and docker takes care which architecture it is interesting for user's host.

What do you think?

**Comment by muxator** [comment]
Hi,

I have a caveat for this: in the roadmap for 1.8 there is #3463 (integration of **ep_hash_auth**), which is an important security enhancement.



Right now, ep_hash_auth depends on the [npm package bcrypt](https://www.npmjs.com/package/bcrypt), which provides prebuilt binaries on a best effort basis, and [only for Intel architechtures](https://github.com/kelektiv/node.bcrypt.js#install-via-npm):

>Currently, we have pre-built binaries that support the following platforms:
>
>- Windows x32 and x64
>- Linux x64 (GlibC targets only). Pre-built binaries for MUSL targets such as Apline Linux are not available.
>- macOS

Thus I would be ok with enabling ARM support, provided that we have a strategy to deal with the compatibility problem that will arise afterwards.
