### ISSUE TITLE
Redundant callback argument in Pad.prototype.copy()?

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3580]
@raybellis, is this `callback` argument is a leftover that can be removed?

https://github.com/ether/etherpad-lite/blob/7433d749f00cd389b6e4f8f1f9b1aa0c0a82dd23/src/node/db/Pad.js#L402

I am reviewing the code with the typescript compiler hoping to find some errors.

**Comment by raybellis** [comment]
Yes, it's redundant, and I'm surprised it never came up in testing!  When executed it ought to trigger an "undefined variable" error.

**Comment by raybellis** [comment]
The `return` in line 397 is also redundant - it's immediately after a `throw`.

**Comment by muxator** [comment]
Incorporated this and other fixes in #3585.

I'll close the issue once that one is merged.

**Comment by muxator** [comment]
Closed by #3585
