### ISSUE TITLE
Is it possible to have single line input & no bold, italic etc buton with collabrative editing?

### ISSUE THREAD

**Issue by anantjain6** [ether/etherpad-lite#3583]
I want 2 different customization options
1. A pad without bold, italic etc editor option which allows multi-line input
2. A pad without bold, italic etc editor option which NOT allows multi-line input

Is it possible?
If yes, how?

**Comment by lpagliari** [comment]
To remove "bold, italic etc": on the `settings.json`on root folder, disable [the shortcuts for those styles](https://github.com/ether/etherpad-lite/blob/develop/settings.json.template#L171-L194) and remove [the buttons on the toolbar](https://github.com/ether/etherpad-lite/blob/develop/settings.json.template#L395).

To disallow line break I believe you would need to block all the ways to insert it (ex: listening to the `ENTER` key and prevent its default behaviour + disabling [the shortcut](https://github.com/ether/etherpad-lite/blob/develop/settings.json.template#L176), etc). But you can't have both options on the same Etherpad instance, as far as I know.

By the way, both suggestions won't work if the user copies those styles or line breaks from other places and pastes them on a pad.
