### ISSUE TITLE
Automated builds on Docker Hub

### ISSUE THREAD

**Issue by Reverite** [ether/etherpad-lite#3584]
It would be good to set up Autobuild on Docker Hub so that changes pushed to **develop** are also built and reflected on any git push, as well as automating new tagged releases. https://docs.docker.com/docker-hub/builds/

**Comment by muxator** [comment]
Done for the `develop` branch.
`latest` in https://hub.docker.com/r/etherpad/etherpad will be automatically rebuilt after each push to `develop`.
Stable releases will still be done by hand for now.

Thanks for the suggestion.
