### ISSUE TITLE
deletions should be marked by "striketrough" attribute

### ISSUE THREAD

**Issue by 23jay** [ether/etherpad-lite#3586]
When you press the delete button: Characters are not deleted but marked with "strikethrough" (CSS "text-decoration: line-through") attribute, so that readers can see what is "marked as deleted".

**Comment by lpagliari** [comment]
Is this a question, a feature request, ...?

**Comment by 23jay** [comment]
it's a question.

**Comment by 23jay** [comment]
It's a feature request. I want to work on it, so can you guide me on how I can achieve it?
Thanks in advance.

**Comment by lpagliari** [comment]
Ok, got it, @23jay! This feature looks more like a plugin than a feature on Etherpad core, so I would implement it on a separated repo. I don't see anything like that on the [plugin list](https://static.etherpad.org/plugins.html), so you might be the first one needing that.

You would probably need to override all changes that would remove chars from the text -- that includes the DELETE, but also CUT, PASTE (when there's some text selected), etc. You might have to think of all those scenarios too.

To mark a text with an attribute and later show it with a different style, you would do something very similar to what [ep_font_color](https://github.com/JohnMcLear/ep_font_color) does -- although in your case you don't need to store the color name, just a boolean to mark if text has strikethrough or not.

Does that help?

**Comment by loetting** [comment]
@23jay are you actively working on this issue? I'd be very interested in this feature as well and would love to be kept in the loop on any progress you make

**Comment by JohnMcLear** [comment]
This is a lot harder to do as per @lpagliari -- I can't think of a way but it's a good challenge for a budding plugin dev.
