### ISSUE TITLE
API: getHTML blocks the whole event loop

### ISSUE THREAD

**Issue by tiblu** [ether/etherpad-lite#3589]
### Overview

When you call API-s `getHTML` (https://etherpad.org/doc/v1.7.5/#index_getlinehtmlforexport) endpoint, it **blocks the whole event loop** which means no other request served while the export runs.

Affected versions: <=1.8

### The cause?

The event loop gets blocked in the "check" phase where all `setImmediate` callbacks are handled.
Thats because the 

* https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/ExportHtml.js#L42 - is not async itself
* https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/ExportHtml.js#L424 - does not call 
`getLineHTMLForExport` with a callback, thus not supporting plugins to create async hooks.

For more info:

* How event loop works - https://github.com/citizenos/citizenos-fe/issues/205#issuecomment-479004410
* Citizen OS specific benchmarks and issue description - https://github.com/citizenos/citizenos-fe/issues/205#issuecomment-479008158

### How to reproduce?

* Make a huge pad, like 10000+ lines.
* Start polling some API endpoint:
```
for i in {1..10000}; do echo date & curl -i -k 'https://dev.p.citizenos.com:9001/api/1/getListAllPads?apikey=APIKEY&padID=PADID' | head -n 1; sleep 1; done
```
* Call API endpoint to export that pad:
```
curl -i -k 'https://dev.p.citizenos.com:9001/api/1/getHTML?apikey=APIKEY&padID=PADID' | head
```

#### Result

You can see that while `getHTML` is running, the no request to `getListAllPads` responses are sent.

### Thoughts on fixing it

Some of my thoughts on fixing this issue, probably have to do it for >=1.8:

* Make https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/ExportHtml.js#L42 actually async.
* Make sure the function calls all the hooks with callbacks.
* Make sure the documentation gets updated - all plugin hooks should be async and return a callback.
* Log a warning if a hook does not support a callback.
* In the long run all hooks should return Promises, is this the time to enforce it? It may be quite a big rewrite.
* We may want to take the HTML export to another worker thread/child process, to keep the main thread flowing.

**Comment by JohnMcLear** [comment]
``getListAllPads`` is now ``listAllPads``

for i in {1..10000}; do echo date & curl -i -k 'http://127.0.0.1:9001/api/1.2.13/listAllPads?apikey=APIKEY

**Comment by JohnMcLear** [comment]
I am unable to replicate this bug any more, it probably got fixed during the async change.  I replicated the setup / environment on a pad w/ 13k lines and spammed the getLists with the script then did getHTML and it didn't stop anything functioning as expected.. 

If you can still replicate please let me know and I will re-open this issue <3

**Comment by tiblu** [comment]
Confirmed, cannot reproduce. Thanks a lot!

And, @JohnMcLear glad to see you back in action!
