### ISSUE TITLE
Horizontal line screen jumping on moving cursor.

### ISSUE THREAD

**Issue by jinbullsushil** [ether/etherpad-lite#3590]
Hi,

I am facing the problem when I am trying to move the cursor around the horizontal line my pad screen jumping. I have attached a scene shot please provide any solution for this.

![screencast- 04-14-15-17](https://user-images.githubusercontent.com/30068021/55544449-bc1e1400-56e8-11e9-9bd4-0112fdefffaf.gif)

Please suggest.

**Comment by lpagliari** [comment]
Is this line inserted by a plugin? Which plugins do you have on your
instance?

**Comment by jinbullsushil** [comment]
Hi,

I have used ep_horizontal_line plugin.

**Comment by JohnMcLear** [comment]
Please open this issue on the plugin repo
