### ISSUE TITLE
Move plugins to a dedicated directory

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3593]
Currently, plugins are installed as npm packages in `<basedir>node_modules/ep_<pluginName>`.
By definition, plugins are out-of-core libraries, that can be installed and uninstalled at runtime.

As such, is makes sense to put them into a dedicated directory, separated from the one containing the main Etherpad code.

This would facilitate, among other things, packaging (deb, rpm) and running in a Docker container.

**Comment by JamesMcMahon** [comment]
Got here from https://github.com/ether/etherpad-lite/issues/3582

Have there been any updates to the design of plugins?
