### ISSUE TITLE
Change the default TAB key function

### ISSUE THREAD

**Issue by Gurzo** [ether/etherpad-lite#3594]
is possible to change the current function (indent the line) with the standard tab?
I mean like in Notepad++

thanks to all

**Comment by lpagliari** [comment]
@Gurzo what does Notepad++ do with TAB?

I would guess you could create a plugin for that, but depending on what N++ does on TAB pressed there might already be one.

**Comment by Gurzo** [comment]
@lpagliari 

after writing a word, pressing TAB adds a special character to verical align the next word on the next 4Xspace row, see the example

![2019-04-16_11-40-53](https://user-images.githubusercontent.com/7054182/56199137-9aa01f00-603c-11e9-9ba6-ee3016868f1e.gif)

**Comment by lpagliari** [comment]
Got it! 

I don't know any plugin that does that (see [this list](https://static.etherpad.org/plugins.html)), would you be interested on creating one?

**Comment by Gurzo** [comment]
I would like to try

but first:
- I have to understand if a plugin would be in contrast with the default function of the button
- if there is a similar plugin that I can use as a starting point.

any idea?

**Comment by lpagliari** [comment]
> I have to understand if a plugin would be in contrast with the default function of the tab key

A plugin like that would avoid the default TAB behaviour. By implementing the `aceKeyEvent` and returning `true` (see comments below), the [default code for TAB](https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L3892-L3900) won't be executed.

> if there is a similar plugin that I can use as a starting point.

`ep_page_view` does something similar to what you need (besides a ton of other things): it [listens to `Ctrl+ENTER`](https://github.com/ether/ep_page_view/blob/master/static/js/page_view.js#L316-L326) and does something when this happens. You would need to listen to the TAB instead, but that would be it.

[This resource from the wiki](https://github.com/ether/etherpad-lite/wiki/Creating-a-plugin) might be useful for you too.

**Comment by JohnMcLear** [comment]
bump @Gurzo
