### ISSUE TITLE
£200 to install for non-profit  

### ISSUE THREAD

**Issue by joereddington** [ether/etherpad-lite#3599]
This is very likely the wrong way to do this but [it's worked for our charity before](http://equalitytime.co.uk/5631/2016/01/25/i-cut-the-code-but-i-did-not-cut-the-api/). 

I currently use Google Drive as the core for a [nonprofit project](http://whitewaterwriters.com/) and I'd like to replace it with Etherpad.  

I could work out how to do it myself but I have a budget and it would be nice to spend it.  

I would like: 

1. A recommendation for a host where I can put etherpad-lite and have ssh access and where I can point etherpad.whitewaterwriters.com at. 
1. Given the relative passwords, someone to set up an etherpad-lite instance and provide two scripts: 
*  upload.sh camp number file.txt which creates a pad at etherpad.whitewaterwriters.com/camp/number and preloads it with file.txt 
* download.sh camp number filename which saves the current pad at etherpad.whitewaterwriters.com/camp/number into filename

I *actually* would like to call that functionality from a python script so .py would probably be better, but I'll take .sh
3. Some cosmetics - putting our logo in the right place and changing the colours to look 'nice'.  

I feel like this is probably trivial for people who frequent this board and it's worth £200 to save me a few hours.  There is fairly likely to be some follow-up dev work. 

So two questions: 

* Am I asking anything impossible? 
* Does anyone want to take it on?

**Comment by joereddington** [comment]
First person in my inbox was @joassouza who asked some sensible questions (e.g. I wasn't aware that everpad has a 2000 character line limit, but it doens't matter in this usecase) and who I've asked to get started.  On his recommendation I opened an account with Digital Occean and have sent over the account details.

**Comment by muxator** [comment]
Thanks @joereddington for offering this - I hope Etherpad will be useful for your goals - and _obrigado_ @joassouza for offering your help!

Everything went fine: closing the issue.
