### ISSUE TITLE
Etherpad 1.7.5 unusable under iOS with chrome and safari

### ISSUE THREAD

**Issue by lascapi** [ether/etherpad-lite#3605]
Hi guys ! I'm working with some friends in an french association, there are twenty of us. 
Usualy we work with our smartphones, it was not good, but not bad ! 😁  

With the new Etherpad 1.7.5 upgrade and this awesome new look some troubles have arisen. No problems with Android, but with iOS. (tested with Safari and Chrome) 

I don't have an iPhone, but some guys shown me what's going on. 

1. The doc is incredibly slow to appear, 
2. For a long doc there is only the beginning 
3. And when you want write something the keyboard don't pop up 
4. Or Sometimes it shows up, but when you tap a letter .... nothing ... is .... happening .... for .... several ..... long .... seconds 

And that why some of us can't use Etherpad anymore :/ 

If I forgot something please let me know !! 😃  And thank's for this amazing application 👏

**Comment by ldidry** [comment]
Precision: the skin is `colibris`.

**Comment by lascapi** [comment]
Do you think the skin is the problem ? 
I notice the pad is slower with android too ! And even with a computer, it's always slow to be show. This is the good way/place to submit this bug ? 
Thanks

**Comment by ldidry** [comment]
I don’t know, but more informations is always better. 

Yes, I think this is the good place to submit this bug.

Note that whatever browser you use on iOS, you always use the same browsing engine (Apple policy :man_shrugging:).

Just to be sure the slowness is not due to the high use of Framapad’s servers, could you try https://beta.etherpad.org/ and tell if it’s still slow?

**Comment by lascapi** [comment]
Thank's ! I'll try it soon as I can. 

Note : we have a big pad, if I export it there is 10,6Mo (etherpad format with history) and when I try to import it on beta.etherpad.org there is a failure. So I just copy/paste the text (only 106Ko) so probably it will be faster...

**Comment by ldidry** [comment]
Well, with a lot of characters in a pad, it’s not unusual for it to be slow. I even wrote a plugin to warn users about that: https://www.npmjs.com/package/ep_warn_too_much_chars

With an export of 10,6Mo, I guess you may have a lot of characters. How many characters do you have? (you can see that on Framapad by clicking on the "counter" icon on the right of the bar)

**Comment by lascapi** [comment]
Hi! I tried with https://beta.etherpad.org/ and we have the same issue. It's just a little bit better but not usable. 
And with a very lite pad on Framapad too! 

I wonderif Etherpad is compatible with iOs/safari? The previous theme was better on this point! 

What I can do to help now?

**Comment by muxator** [comment]
Hi, do not have access to iOS or macOS machines, so I fear I cannot help much.

**Comment by JohnMcLear** [comment]
We can't replicate this on any version of Etherpad and we have plenty of Safari / iOS users in production on large(ish) pads without any issue.  I'm going to close this unless you can come back with further insights.
