### ISSUE TITLE
Error: `secret` option required for sessions

### ISSUE THREAD

**Issue by Anonym2309** [ether/etherpad-lite#3608]
how to fix this issue Error: `secret` option required for sessions??
i already running this apps on my localhost:300 but there is an error about secret option issue.

please help me..
![twitter clone error](https://user-images.githubusercontent.com/20036673/57613448-168c7900-75a1-11e9-9e68-7c0e07981ca4.png)

**Comment by JohnMcLear** [comment]
Set the value in settings.json :)

**Comment by muxator** [comment]
[settings.json.template](https://github.com/ether/etherpad-lite/blob/467fc11b723723275f1ebd0fed556a0525ea5f0b/settings.json.template) does not mention any `secret` option. If this is the solution, it should probably be documented there.

**Comment by JohnMcLear** [comment]
Wait, is this error even from Etherpad?  How can I replicate this error?  This error looks very much developer generated and not an issue with Etherpad
