### ISSUE TITLE
Error executing command, exiting

### ISSUE THREAD

**Issue by davidshumway** [ether/etherpad-lite#3609]
Staring from `curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -`:

    (dwiki-venv)dave@debian:~/dev/django-wiki$ sudo ./x.sh

    ## Installing the NodeSource Node.js 9.x repo...

    ## Populating apt-get cache...

    + apt-get update
    Ign http://download.webmin.com sarge InRelease
    Hit http://download.webmin.com sarge Release.gpg                                                                       
    Hit http://download.webmin.com sarge Release                                                                           
    Ign http://ftp.us.debian.org jessie InRelease                                                                          
    Hit http://ftp.us.debian.org jessie-updates InRelease                                                                  
    Hit http://download.webmin.com sarge/contrib amd64 Packages                                                            
    Hit http://security.debian.org jessie/updates InRelease                                                                
    Hit http://ftp.us.debian.org jessie Release.gpg                                                                        
    Hit https://apt.dockerproject.org debian-jessie InRelease                                                              
    Hit http://ftp.us.debian.org jessie Release                                                                            
    Ign http://download.webmin.com sarge/contrib Translation-en_US                                                         
    Ign http://download.webmin.com sarge/contrib Translation-en                                                       
    Get:1 http://security.debian.org jessie/updates/main Sources [310 kB]                       
    Ign http://ftp.debian.org jessie-backports InRelease                                                                   
    Get:2 https://apt.dockerproject.org debian-jessie/main amd64 Packages [6,892 B]                                   
    Ign http://webmin.mirror.somersettechsolutions.co.uk sarge InRelease                                              
    Get:3 http://security.debian.org jessie/updates/main amd64 Packages [678 kB]                                           
    Get:4 http://security.debian.org jessie/updates/main Translation-en [342 kB]                                           
    Hit http://ftp.us.debian.org jessie/main Sources                                                                       
    Get:5 https://apt.dockerproject.org debian-jessie/main Translation-en_US [454 B]                          
    Ign http://ftp.debian.org jessie-backports Release.gpg                                                                 
    Hit http://ftp.us.debian.org jessie/main amd64 Packages                                                                
    Hit http://webmin.mirror.somersettechsolutions.co.uk sarge Release.gpg                                                 
    Hit http://ftp.us.debian.org jessie/main Translation-en                                                                
    Ign http://ftp.debian.org jessie-backports Release                                                                     
    Hit http://webmin.mirror.somersettechsolutions.co.uk sarge Release
    Get:6 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]         
    Ign http://ftp.debian.org jessie-backports/main amd64 Packages/DiffIndex                                             
    Get:7 https://apt.dockerproject.org debian-jessie/main Translation-en_US [454 B]                                     
    Get:8 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]                                          
    Get:9 https://apt.dockerproject.org debian-jessie/main Translation-en_US [454 B]                                       
    Hit http://webmin.mirror.somersettechsolutions.co.uk sarge/contrib amd64 Packages                                      
    Get:10 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]                                         
    Get:11 https://apt.dockerproject.org debian-jessie/main Translation-en_US [454 B]                                     
    Get:12 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]                                         
    Get:13 https://apt.dockerproject.org debian-jessie/main Translation-en_US [454 B]                                      
    Ign https://apt.dockerproject.org debian-jessie/main Translation-en_US                                                 
    Get:14 https://apt.dockerproject.org debian-jessie/main Translation-en [454 B]                                         
    Ign https://apt.dockerproject.org debian-jessie/main Translation-en              
    Ign http://webmin.mirror.somersettechsolutions.co.uk sarge/contrib Translation-en_US
    Ign http://webmin.mirror.somersettechsolutions.co.uk sarge/contrib Translation-en
    Ign http://ftp.debian.org jessie-backports/main Translation-en_US
    Ign http://ftp.debian.org jessie-backports/main Translation-en
    Err http://ftp.debian.org jessie-backports/main amd64 Packages
      404  Not Found [IP: 130.89.148.12 80]
    Fetched 6,892 B in 4s (1,533 B/s)        
    W: Failed to fetch http://ftp.us.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

    W: Failed to fetch http://ftp.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found [IP: 130.89.148.12 80]

    E: Some index files failed to download. They have been ignored, or old ones used instead.
    Error executing command, exiting

`uname -a`:

    Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

`cat /etc/os-release`:

    PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
    NAME="Debian GNU/Linux"
    VERSION_ID="8"
    VERSION="8 (jessie)"
    ID=debian
    HOME_URL="http://www.debian.org/"
    SUPPORT_URL="http://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"

`nodejs --version`:

    v0.10.29

**Comment by muxator** [comment]
@davidshumway, this is a problem setting up your linux environment.

1. > E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)

   This means either you are not root or (as likely) some sort of auto-updater in your distro is working in background. The nodesource script does not catch this error condition, and continues.

2. > (dwiki-venv)dave@debian:~/dev/django-wiki$ sudo ./x.sh
   Are you running inside a python venv? This would mess up your PATH and environment variables. Deactivate it typing `deactivate`, you'll notice that `(dwiki-venv)` will disappear from your prompt.

3. > Err http://ftp.debian.org jessie-backports/main amd64 Packages
   > [...]
   > W: Failed to fetch http://ftp.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found [IP: 130.89.148.12 80]

   That's a real http/404 (replicated on my side here). In which state is your debian installation?

I would advise solving these problems before attempting to install Etherpad.

**Comment by davidshumway** [comment]
> @davidshumway, this is a problem setting up your linux environment.
> 
> 1. > E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
>    
>    
>    This means either you are not root or (as likely) some sort of auto-updater in your distro is working in background. The nodesource script does not catch this error condition, and continues.
> 2. > (dwiki-venv)dave@debian:~/dev/django-wiki$ sudo ./x.sh
>    > Are you running inside a python venv? This would mess up your PATH and environment variables. Deactivate it typing `deactivate`, you'll notice that `(dwiki-venv)` will disappear from your prompt.

Oops, included in the output the command when run as not sudo! So disregard this.

> 3. > Err http://ftp.debian.org jessie-backports/main amd64 Packages
>    > [...]
>    > W: Failed to fetch http://ftp.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found [IP: 130.89.148.12 80]
>    
>    
>    That's a real http/404 (replicated on my side here). In which state is your debian installation?
> 
> I would advise solving these problems before attempting to install Etherpad.

Hm. Which state? Possibly Georgia. `$ wget 130.89.148.12` seems to be working fine.

**Comment by davidshumway** [comment]
@muxator 

Output of `$ sudo cat /etc/apt/sources.list`:

      # 

      # deb cdrom:[Debian GNU/Linux 8.0.0 _Jessie_ - Official amd64 NETINST Binary-1 20150425-12:50]/ jessie main

      # deb cdrom:[Debian GNU/Linux 8.0.0 _Jessie_ - Official amd64 NETINST Binary-1 20150425-12:50]/ jessie main

      deb http://ftp.us.debian.org/debian/ jessie main
      deb-src http://ftp.us.debian.org/debian/ jessie main

      deb http://security.debian.org/ jessie/updates main
      deb-src http://security.debian.org/ jessie/updates main

      # jessie-updates, previously known as 'volatile'
      deb http://ftp.us.debian.org/debian/ jessie-updates main
      deb-src http://ftp.us.debian.org/debian/ jessie-updates main
      deb https://apt.dockerproject.org/repo/ debian-jessie main
      # deb-src https://apt.dockerproject.org/repo/ debian-jessie main

**Comment by ukcb** [comment]
jessie-backports and sourcen has been moved to the archive.

http://archive.debian.org/debian/dists/

**Comment by muxator** [comment]
Closing.
