### ISSUE TITLE
exporting odt/doc does not work

### ISSUE THREAD

**Issue by eitzenbe** [ether/etherpad-lite#3610]
fails with error not being able to copy file inm temp folder. reason is that in etherpad-lite/src/node/handler/../utils/LibreOffice.js

code at the bottom of file needs to be changed to:

    // Move the converted file to the correct place
    function(callback) {
      var filename = path.basename(task.srcFile);
      **//**var sourceFilename = filename.substr(0, filename.lastIndexOf('.')) + '.' + 'html';
      **//**var sourcePath = path.join(tmpDir, sourceFilename);
      libreOfficeLogger.debug(`Renaming ${**task.srcFile**} to ${task.destFile}`);
      fs.rename(**task.srcFile**, task.destFile, callback);
    }

Also unlinking is implemented unconditionally which breaks as Libreoffice first creates a temp odt file when converting to doc. Thus it would be good to check if file exists before unlinking it:

code at bottom of etherpad-lite/src/node/handler/ExportHandler.js needs to be changed to:

    fs.stat(destFile, function(err,stats) {
        if (err) {
            return;
        }
        fs.unlink(destFile, callback);
    });

the same for srcFile....

**Comment by JohnMcLear** [comment]
@muxator Did you confirm this before adding these labels?  I can't for the life of me replicate this bug...

**Comment by JohnMcLear** [comment]
I'm still unable to replicate this and now with test coverage up in Travis I am confident our solution is working.  If someone can provide steps to replicate I will re-open this issue
