### ISSUE TITLE
JSON-PROBLEM and server shut down

### ISSUE THREAD

**Issue by chatellier** [ether/etherpad-lite#3613]
Hi,

This may be related to #2522, but a can't find any solution.

One of our pad is corrupted in database. Log shows:
`[2019-06-04 10:17:49.658] [ERROR] console - JSON-PROBLEM:{"atext":{"text":"some anonymized text`

I've tried to delete this pad using `/api/1/deletePad?apikey=yourkey&padID=mypad` API, this results in:
```[2019-06-04 10:16:13.574] [INFO] API - RESPONSE, deletePad, {"code":2,"message":"internal error","data":null}
[2019-06-04 10:16:13.580] [ERROR] console - Async Stacktrace:
    at /var/www/etherpad-lite/src/node/handler/APIHandler.js:255:7
    at /var/www/etherpad-lite/src/node/db/API.js:755:8
    at /var/www/etherpad-lite/src/node/db/API.js:1268:8
    at Object.callback (/var/www/etherpad-lite/src/node/db/PadManager.js:190:8)

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /var/www/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:164:24
    at Query._callback (/var/www/etherpad-lite/src/node_modules/ueberdb2/mysql_db.js:115:5)
    at Query.Sequence.end (/var/www/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/var/www/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/var/www/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/var/www/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/var/www/etherpad-lite/src/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/var/www/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/etherpad-lite/src/node_modules/mysql/lib/Connection.js:103:28)
```

I've also tried to use `ep_adminpads` plugin, but the delete action has no efffect.

No server crash several times a day when displaying corrupted pad.

Can this issue been fixed ?

**Comment by muxator** [comment]
My thought about corrupted values in the data store:
1. they should never get there in the first place (code correctness & lack of transactional updates?)
2. once they are there, ueberDB should have an escape hatch to deal with them, or at least allowing deleting corrupted data
3. ueberDB is an external package, and we do not control it directly.

Point 1 is the most important, but I do not think we will have a solution shortly.
Point 2 may or may not be within reach, depending on the specific corruption and what we see once we start working on point 3 (vendorize ueberDB), which will be tracked in #3675.

No immediate solution for now, @chatellier, sorry, but maybe you could help with 2) giving some example of corrupted data when we have the possibility of working on this issue.

**Comment by chatellier** [comment]
The error trace is almost complete. Only the text is anonymized.
I can't find any other information about this corruption and corrupted data.

**Comment by JohnMcLear** [comment]
Hey @chatellier I'm going to close this as we haven't heard from you in a month.  If you have more info please let us know!

**Comment by muxator** [comment]
@chatellier, what Etherpad version was this? Was it before **1.8.0**?

@JohnMcLear, if this happened on Etherpad **1.8.0** I do not think we should close it: we are talking about a systematic, complete shut down of the server, and could be introduced by the migration to `async`/`await`.

If it's an older version (< **1.8.0**), then it's another story.

**Comment by Marx1st** [comment]
Its happening on our server, too. Just updated to 1.8 and it still happens (same error as above).

**Comment by JohnMcLear** [comment]
Please paste your error dump and also let us know any useful information, like OS, database, any plugins..

**Comment by chatellier** [comment]
The bug happened before version 1.7.5 and then I updated to version 1.7.5 with the same results.
I'm curently using version 1.7.5.

I also tried to repair and delete the pad, but it also fails with the same error.

There is no procedure that I know to reproduce the bug. Some pad are "invalid", but I have no clue to produce another "invalid" pad.

**Comment by JohnMcLear** [comment]
@chatellier that's great, thanks.

Please try 1.8.1 (latest develop), as of 6 days ago the deletePad script works: https://github.com/ether/etherpad-lite/commit/cdf5b63f262db9ba4fe6b097cbabd7ca7df8df2c

We also provide an ``extractPadData.js`` which dumps a .db file I can bring into my instance and debug for you 👍 

So:
  - [ ] Try replicate the problem on ``develop`` branch
  - [ ] If you can, try dump the pads content using ``extractPadData.js`` and hit me up with that file contact@etherpad.org
  - [ ] If you want to nuke it, use ``deletePad.js``

🌊 Profit?

**Comment by LucasCioffi** [comment]
Hi All, I'm not sure if this is helpful, but we ran into this one problem with a pad this week.  It seems from the last recorded changesets on that pad (pasted below) that the user was just typing this regular sentence without any special characters, "Is there something in Chrome that doesn't automatically load the first tab.  Is there a way to i" and then that's it.

We are using UberDB.  Could it be something wrong with the database?  Are there any suggestions for how to catch errors like this?
```
pad:cc1-uysEUEpfkMApoQAlgymuSjOnu-0:revs:16803 | {"changeset":"Z:r72>1|i=tl=i*1w+1$I","meta":{"author":"a.jTx7jbKNR06x1UXf","timestamp":1627584141905}}    |
| pad:cc1-uysEUEpfkMApoQAlgymuSjOnu-0:revs:16804 | {"changeset":"Z:r73>2|i=tl=j*1w+2$s ","meta":{"author":"a.jTx7jbKNR06x1UXf","timestamp":1627584142409}}   |
| pad:cc1-uysEUEpfkMApoQAlgymuSjOnu-0:revs:16805 | {"changeset":"Z:r75>4|i=tl=l*1w+4$ther","meta":{"author":"a.jTx7jbKNR06x1UXf","timestamp":1627584142931}} |
| pad:cc1-uysEUEpfkMApoQAlgymuSjOnu-0:revs:16806 | {"changeset":"Z:r79>2|i=tl=p*1w+2$e ","meta":{"author":"a.jTx7jbKNR06x1UXf","timestamp":1627584143407}}   |
| pad:cc1-uysEUEpfkMApoQAlgymuSjOnu-0:revs:16807 | {"changeset":"Z:r7b>2|i=tl=r*1w+2$a ","meta":{"author":"a.jTx7jbKNR06x1UXf","timestamp":1627584143907}}   |
| pad:cc1-uysEUEpfkMApoQAlgymuSjOnu-0:revs:16808 | {"changeset":"Z:r7d>1|i=tl=t*1w+1$w","meta":{"author":"a.jTx7jbKNR06x1UXf","timestamp":1627584144409}}    |
| pad:cc1-uysEUEpfkMApoQAlgymuSjOnu-0:revs:16809 | {"changeset":"Z:r7e>2|i=tl=u*1w+2$ay","meta":{"author":"a.jTx7jbKNR06x1UXf","timestamp":1627584144907}}   |
| pad:cc1-uysEUEpfkMApoQAlgymuSjOnu-0:revs:16810 | {"changeset":"Z:r7g>2|i=tl=w*1w+2$ t","meta":{"author":"a.jTx7jbKNR06x1UXf","timestamp":1627584145408}}   |
| pad:cc1-uysEUEpfkMApoQAlgymuSjOnu-0:revs:16811 | {"changeset":"Z:r7i>2|i=tl=y*1w+2$o ","meta":{"author":"a.jTx7jbKNR06x1UXf","timestamp":1627584145909}}   |
| pad:cc1-uysEUEpfkMApoQAlgymuSjOnu-0:revs:16812 | {"changeset":"Z:r7k<1|i=tl=i-1$","meta":{"author":"a.jTx7jbKNR06x1UXf","timestamp":1627584150015}}        |
| pad:cc1-uysEUEpfkMApoQAlgymuSjOnu-0:revs:16813 | {"changeset":"Z:r7j>1|i=tl=i*1w+1$i","meta":{"author":"a.jTx7jbKNR06x1UXf","timestamp":1627584150615}}    |
```

**Comment by rhansen** [comment]
@LucasCioffi Please open a new bug report with as much info as you can provide—it's hard to troubleshoot without knowing what plugins you have installed or steps to reproduce. Be sure to mention whether exporting and importing the pad (Etherpad format) triggers the bug; if so, provide a link to the export if possible.

**Comment by almereyda** [comment]
Recently we went through a similar occurrence of incomplete JSON values, most probably caused due to `latin1` encoding of the database.

The progress has been publicly recorded for search engine retrievability:

- https://github.com/ether/etherpad-lite/issues/2522#issuecomment-1292493410
