### ISSUE TITLE
setHTML API not working

### ISSUE THREAD

**Issue by anantjain6** [ether/etherpad-lite#3615]
I have tried
`http://localhost:9001/api/1.2/setHTML?apikey=secret&padID=g.something$sonething&html=%3Chtml%3E%3Chead%3E%3C%2Fhead%3E%3Cbody%3EA%3C%2Fbody%3E%3C%2Fhtml%3E`
and
`http://localhost:9001/api/1.2/setHTML?apikey=secret&padID=g.something$sonething&html=<html><head></head><body>A</body></html>`

But getting error

`{"code":1,"message":"HTML is malformed","data":null}`

Tried with Etherpad API version 1, 1.1 and 1.2
Node v9.11.2
Npm v6.9.0

**Comment by lpagliari** [comment]
@anantjain6 I've tried both ways and got no error, so I'm wondering if there's something wrong with your instance configs or the way you're sending the GET request. I'm running Etherpad on node `v8.9.0` and npm `5.5.1`.

Are you able to access the Etherpad logs? Can you enable `"loglevel" : "DEBUG"` on `settings.json` to see if more info is provided about the request being received?

Which OS are you using to send the request? How are you sending the request -- using any tool, or simply by accessing the URL on a browser?

**Comment by anantjain6** [comment]
My going deeper in the code I tried to print exception and got the error "ReferenceError: localStorage is not defined"

I'm not sure why it is occurring. So, I installed a fresh copy of etherpad and it started working well

I'm on Ubuntu 18.0.4
Tried through both browser and postman
