### ISSUE TITLE
Initial author color selecter is not set on current author color

### ISSUE THREAD

**Issue by Salamandar** [ether/etherpad-lite#3617]
When opening the color selecter on the first time, the selected color is not the current color.

See the screenshot : The initial author color is blue, but the color selecter is on grey-ish. It should be on blue.

![Capture d’écran du 2019-06-28 11-30-40](https://user-images.githubusercontent.com/6552989/60333006-49939c00-9998-11e9-886f-12c5190aa8db.png)

**Comment by JohnMcLear** [comment]
Confirmed.  Color is right but ?hue? is not..  This should be a really easy fix for someone..  should be in pad_userlist.js

**Comment by orblivion** [comment]
I have a fix that seems to almost work:

https://github.com/ether/etherpad-lite/compare/develop...orblivion:farbtastic-initial-color?expand=1

I was about to PR it but it seems that the color picker is still set to gray on _first_ use, _sometimes_. I'll look more.

**Comment by orblivion** [comment]
It seems like a caching issue :man_shrugging: This is my first time developing for etherpad. I'm not sure where some of the behavior might get cached, but if I delete `~/.mozilla`, `~/.cache`, and the `etherpad-lite` project directory (I assume this is overkill), then the behavior is consistent. `master` and `develop` seems to always exhibit the bug, and my change always seems to fix it. So I'll go ahead with the PR.
