### ISSUE TITLE
Support creating docker image with plugins

### ISSUE THREAD

**Issue by overclockedllama** [ether/etherpad-lite#3618]
Hi

I would like to build a docker image with the codepad plugin built in. Is this possible?

I have ep_codepad installed in my directory with ep_codepad installed. When running ./bin/run.sh it runs perfectly. Then I followed the instructions to create a custom docker image. It seems it pulls some upstream version of etherpad and only allows me to change the config file. When running this image it just runs stock etherpad. Is it possible to make it use my local version of etherpad with codepad built in?

This is the ep_codepad I am talking about: https://www.npmjs.com/package/ep_codepad
It says it is supported here: https://static.etherpad.org/plugins.html

Many thanks

**Comment by muxator** [comment]
Seems useful.

Written a PR for implementing this.
If you are in the condition of testing it, it would be appreciated.
