### ISSUE TITLE
Add docker install instructions to readme.

### ISSUE THREAD

**Issue by dessalines** [ether/etherpad-lite#3623]
There are no instructions on how to do a docker install on the README.

**Comment by muxator** [comment]
Hi @dessalines, personally I think this is a bit out of scope: an advanced user would know how to do it, while a newcomer would blindly copy the (soon outdated) instructions without understanding them.

But then, maybe you are right and a short section with the instructions (maybe with an external link for who wants more information) could be useful.

Feel free to propose a change and let's see.
