### ISSUE TITLE
Docker runs etherpad as root user

### ISSUE THREAD

**Issue by Cronixx** [ether/etherpad-lite#3629]
Hey, i've noticed etherpad/node is running under the root user account in the default docker container.
Is there any special reason it has to be like that?

#1315 mentions it would be advisable to have ep run as a special etherpad user

**Comment by zem** [comment]
+1 pse fix

**Comment by Fnjn** [comment]
It's common practice to run as root in container just for simplicity. Unless you want to run many different services in a single container, which is generally not advisable.

**Comment by muxator** [comment]
Merged #3643. Thanks @pierreprinetti for reworking the commit.

**Comment by Fnjn** [comment]
> Using the root user in a container is bad practice

@pierreprinetti I don't think it's possible that a root user in a container can escalate to be root user on the host machine.

The example in docker official document [Best practices for writing Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) does not switch to unprivileged user.

**Comment by pierreprinetti** [comment]
@Fnjn 
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user

> If a service can run without privileges, use USER to change to a non-root user.
