### ISSUE TITLE
I would like to log each activity (open, edit, close etc) of a user in order to notify blind user. In EtherPad, where I can find all this activity log?

### ISSUE THREAD

**Issue by Usman-Asghar-Raja** [ether/etherpad-lite#3632]
Dear Team of EtherPad, I want to use EtherPad for my project in which I’m going to support the blinds community for collaborative writing purpose.  I have some question about EtherPad customization. Can I customize source code according to my requirements?

 

Please send me helpful links from where I can read about my conflicts or answer this email with an appropriate answer.

**Comment by yorbicardozo24** [comment]
Do you have it in a hosting?

**Comment by JohnMcLear** [comment]
Yes.  We already provide aria for every element that appears on the page specifically for this use case so very little development should be needed.  See Aria
