### ISSUE TITLE
Applying Changesets with wrong character

### ISSUE THREAD

**Issue by kostaspa** [ether/etherpad-lite#3635]
Hello, I got the '*' character when I'm hitting the tab button in the middle of a text and after applying the below changesets with the function applyToText from the file https://github.com/ether/etherpad-lite/blob/develop/src/static/js/Changeset.js
The star character is not visible on the pad neither in timeslider, is visible only when I apply the changesets with the function applyToText. Also the star character is not visible, when I hit the tab button in the start of the line of the text.

Below are the last changesets that this is happening.
```

"pad:g.wHsSsWbOhL5ZKYbR$teamcollabr1:revs:144": {
    "changeset": "Z:1c>9|1=s=8*0+9$sdjfkdsjf",
    "meta": {
      "author": "a.0VZqJGepNQc41EzX",
      "timestamp": 1565810688484
    }
  },
  "pad:g.wHsSsWbOhL5ZKYbR$teamcollabr1:revs:145": {
    "changeset": "Z:1l>1|1=s*0*3*4*5+1$*",
    "meta": {
      "author": "a.0VZqJGepNQc41EzX",
      "timestamp": 1565810690087
    }
```

Below is also the code that i'm using in order to apply the changesets

```
var Changeset = require('./Changeset');

//the variable etherpadContent contains all the pad revisions
var textAttributes = etherpadContent['pad:'+padId].pool.numToAttrib;
var str = etherpadContent['pad:'+padId+':revs:'+0].meta.atext.text;

  //iterate over all pad revisions
  for (var i = 1; etherpadContent.hasOwnProperty('pad:'+padId+':revs:'+i); i++){
    var padRev = etherpadContent['pad:'+padId+':revs:'+i];
    var cs = padRev.changeset;
    str = Changeset.applyToText(cs, str);
  }
```
I'm supposing that the library is being used in the timeslider is different from the one that I'm using from the Changeset.js. In any case, how can i take the content of the timeslider without this (maybe) bug?
Thank you.

**Comment by lpagliari** [comment]
The `*` on the beginning of the line usually means a line attribute not being processed. Do you have any plugins installed on your Etherpad instance, or is the affected line a list -- ordered or unordered?

Maybe one of the plugins you have installed adds a line attribute when pressing TAB, but it does not implement `aceDomLineProcessLineAttributes` -- or if it does, the returned object does not have `processedMarker` as `true`.
