### ISSUE TITLE
Missing plugin repo: https://github.com/itguy51/ep_signature (I suggest to add it again)

### ISSUE THREAD

**Issue by Wikinaut** [ether/etherpad-lite#3649]
Is there a reason, why the https://github.com/itguy51/ep_signature (adds a timestamp and authors name) plugin has been (aparently) removed from the Plugin list?

I like that plugin and it was quite difficult to find it back.

**Comment by JohnMcLear** [comment]
It's because the author of the plugin hasn't published it to npm or has unpublished it.
