### ISSUE TITLE
How to inject/migrate a public pad into my own on-premise one?

### ISSUE THREAD

**Issue by hydrogenpi** [ether/etherpad-lite#3653]
I kept a public etherpad online for a while and lately started my own hosting it at home. I see the ability to export it and download as "etherpad" format, but how would I convert and insert this into the (I'm using mysql) database so that I can effectively migrate it from the online pad to my local pad server?

**Comment by JohnMcLear** [comment]
.etherpad keeps ALL document fidelity.  Just export .etherpad and import it.  You lose 0 fidelity, that's what makes Etherpad unique.
