### ISSUE TITLE
clicking in right margin doesn't seek to end of line

### ISSUE THREAD

**Issue by sudoman** [ether/etherpad-lite#3664]
This is a very minor feature request.

On <https://beta.etherpad.org> with Firefox 68 in Debian Buster, clicking in the right margin doesn't move the cursor to the end of the closest line.

This would be a useful feature because it would make selecting the end of a line easier. In lines that are long or that wrap, it's currently required to horizontally seek the cursor to the very end of the line and to click there to go to the end of the line.

Thanks : )

**Comment by muxator** [comment]
Hi @sudoman, never noticed it, because I am accustomed to doing this via keystrokes (`home`, `shift` + `end`).

Does it work on other browsers?

**Comment by sudoman** [comment]
I tested Firefox 68, Chromium 78 and Midori 7.0. They all show this behavior. Thanks : )

**Comment by JohnMcLear** [comment]
I don't recall baking this in at all, we would need to be careful though because some plugins (IE ep_comments_page) use the right margin for their content so catching click events would need to be explicit to within X pixels and not to the end of the page..

**Comment by JohnMcLear** [comment]
I just tested this in Chrome and if you click to the right of the pad but within the "page" it does put caret in correct position.  There is however a 40px or so padding of  ``iframe["ace_inner"]`` with css value ``var(--editor-horizontal-padding)`` which stops click events putting the caret in location.  I'm not sure how best to fix this @seballot any ideas?

**Comment by seballot** [comment]
Yes I can move the padding property from the outerdocbody to the innnerdocbody and it will works, please assign to me, I just need to double check there will not be side effects

**Comment by seballot** [comment]
mmm actually it's not possible, because if I set the padding inside innerdocbody (so clicking in the padding will put the caret at the end of the line) then I can no more change the padding depending of the size of the screen. Because media query will refer to the size of the ace_inner iframe. So I cannot keep consistency between sidediv padding (with media query applying from ace_outer iframe) and innerdocbody (media query applied to ace_inner iframe). then the line number are not aligned anymore etc.. 

Maybe I could find a workaround, but I don't think it worth it, it will need some work...

**Comment by JohnMcLear** [comment]
No worries, thanks for taking a look.  I concluded the same but it is doable but I feel like code to do it could introduce a lot of caveats.

**Comment by seballot** [comment]
mmm, I think I finally fixed this one ! I added a small default margin in the innerdocument, so it get easier to click the end of the line (if you click too far in the margin it does not work anymore)

**Comment by JohnMcLear** [comment]
Wow nice job.  Does it play well with responsive design?  Ie how well does it work on mobile where afaik the responsive CSS removes the margin

**Comment by JohnMcLear** [comment]
@seballot will we see a PR with your fix in soon?  I ask because I finish my EP work soon!

**Comment by seballot** [comment]
Hi @JohnMcLear, the fix is already merged ! Probably with a PR where I was doing multiple UI improvements

**Comment by JohnMcLear** [comment]
Okay cool, will close it up @sudoman please see if the UX is okay to you :)

**Comment by JohnMcLear** [comment]
@seballot just for reference can you refer to the commit that fixed this?  I didn't see any commits land recently from you :)

**Comment by seballot** [comment]
Yep was this commit : 7aa7e02e273c66936516f1ba87f435e4fe206c75
But as I said, it's mixed up other others small improvements

**Comment by seballot** [comment]
Actually all my commits I've been merged into one, so the original commit for this ticket is this one : https://github.com/ether/etherpad-lite/pull/4017/commits/9ef38436a14c90a5bbba2db8b0d8070f12c6226c
