### ISSUE TITLE
EasySync docu: optimizations and pseudo code

### ISSUE THREAD

**Issue by superjojo140** [ether/etherpad-lite#3665]
In the [Etherpad and EasySync Technical Manual](https://github.com/ether/etherpad-lite/raw/master/doc/easysync/easysync-full-description.pdf) are mentioned additional topics on the last page:

> Additional topics
(a) Optimizations (strips, more caching, etc.)
(b) Pseudocode for composition, merge, and follow
(c) How authorship information is used to color-code the document based
on who typed what
(d) How persistent connections are maintained between client and server

How is that to be understood? Are there any documents on these topics? If so, where and how can these documents be found?

Especially the topics optimizations and pseudo code would really interest me.

**Comment by muxator** [comment]
@superjojo140, that document has an historical value, unlikely you'll find those information now.

Closing, sorry.

**Comment by NikaZhenya** [comment]
I would like to know about that to for research purposes.
