### ISSUE TITLE
Specify user name in URL

### ISSUE THREAD

**Issue by mitjastachowiak** [ether/etherpad-lite#3667]
Hello,
is there a way to specify the user name, that needs to be/should be entered in the upper right corner, in the URL, used to open the pad?

Like this: https://mypad.xy/p/the-pad-name?user=Alice

This would be helpful when embedding such pads in iframes of sites, where the user is already known...

**Comment by lucast15** [comment]
Hello, 
that is already possible. You just have to use ?userName.

Like that: https://mypad.xy/p/the-pad-name?userName=Alice 

Look in \etherpad\node_modules\ep_etherpad-lite\static\js\pad.js line 75-87 for all GET variables.
I hope I could help you.

**Comment by mitjastachowiak** [comment]
You mean this file: https://github.com/ether/etherpad-lite/blob/develop/src/static/js/pad.js

Yes, that's what I was looking for. Hard to find it via google...
Thanks :-)
