### ISSUE TITLE
embed_hyperlinks2 is forgetting the : of http://  (version 1.7.5 and 1.8.0)

### ISSUE THREAD

**Issue by revast** [ether/etherpad-lite#3673]
Hello, I am posting this issue here, as https://github.com/sebballot/ep_embedded_hyperlinks2#readme
is 404, and the plugin is in the list of supported plugins.

When entering a url without http(s):// , it works, but when  http:// or https:// is used, the resulting link is e.g https//github.com  ... not good

I guess this is the code which is doing that is this:  

`exports.aceCreateDomLine = function(name, context) {
    var cls = context.cls;
    var domline = context.domline;
    var url = /(?:^| )url-(\S*)/.exec(cls);
    var modifier = {};
    if(url != null) {
        url = url[1];

        if(!(/^http:\/\//.test(url)) || 
            !(/^https:\/\//.test(url))) {
                url = "http://" + url;
            }

        modifier = {
            extraOpenTags: '<a href="' + url + '">',
            extraCloseTags: '</a>',
            cls: cls
        }
        return modifier;
    }
    return [];`

Now I am not a (javascript) coder, could somebody have a look please?

thanks.

**Comment by muxator** [comment]
@seballot, is embed_hyperlinks2 a plugin of yours? The author's username is so similar to yours.

**Comment by seballot** [comment]
hello @muxator, not a plugin of mine but I did take the ownership to improve the UI !
@revast, could you open an issue on this repo ? (there was a typo in your url) https://github.com/seballot/ep_embedded_hyperlinks2#readme

**Comment by muxator** [comment]
Thanks Sebastian!

**Comment by seballot** [comment]
@revast, I fixed the bug and publish 1.1.3, no need to open new issue, unless you find another problem !!

**Comment by muxator** [comment]
@revast, did @seballot solve your problem? If so, feel free to close the issue and thanks for signaling.

**Comment by revast** [comment]
yes, seems fixed. testing more thorougly, though

**Comment by seballot** [comment]
Hi ! I enable issue tracker, and created the issue so we do not bother muxator here :)

https://github.com/seballot/ep_embedded_hyperlinks2/issues/1

@muxator you can close now, thanks !

**Comment by muxator** [comment]
Closing :)
