### ISSUE TITLE
Is comments_page  unable  in a read-only Pad?

### ISSUE THREAD

**Issue by duduxiao** [ether/etherpad-lite#3679]
I like this project and have been following it for a long time. However, I encountered a problem as below:
The plugin 'comments_page' is not available in read-only mode. It can display icons and add comments, but the pad itself cannot save any comment information. I don't know if there is any problem with my configuration or some other restrictions, I hope you can give me some suggestions.
The plugin i used is as below image:
![image](https://user-images.githubusercontent.com/20200954/70292303-d92b5980-1818-11ea-9020-ab8fb9d5b572.png)
The configuration of 'comment_page' is as follows:
![image](https://user-images.githubusercontent.com/20200954/70292318-e2b4c180-1818-11ea-86c9-aa20a3c93e89.png)

**Comment by muxator** [comment]
Hi @duduxiao, probably @joassouza (or maybe @lpagliari) can give you a hint?

**Comment by duduxiao** [comment]
@muxator Thanks a lot for your information .
@joassouza @lpagliari  Could you please kindly give me some suggestions for the problem I am facing ? Thanks very much in advance!

**Comment by JohnMcLear** [comment]
ep_comments_page is not available in read only mode.  If you would desire that behavior please create an issue on the plugin github repo.
