### ISSUE TITLE
Etherpad keeps forgetting my author color, hard to get the exact same one again

### ISSUE THREAD

**Issue by AmyBSOD** [ether/etherpad-lite#3682]
There's the problem because I access the etherpad of someone's project from different PCs (sometimes at home, sometimes at work, sometimes when I'm visiting friends...) and every time I have to set my author color again when I want to contribute to that etherpad. I know the approximate hue of color that I want, but it's very hard to get the exact same color again with that color circle thing; would it be possible to let me simply enter the RGB value of my desired color so I'd be able to get the exact same color again? Keep the inexact color circle thing but also have RGB value boxes that allow an exact selection? That would be great :-)

**Comment by muxator** [comment]
Agreed, I would merge a PR about this.
