### ISSUE TITLE
npm `test` and `test-container` should use the same spec files

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3686]
13d9e86be16b (part of #3677) introduced a useful feature (running a simplified version of backend tests in CI via Docker), but in doing so copied & modified & pasted two files. See https://github.com/ether/etherpad-lite/pull/3677#issuecomment-568810560:

- backend/loadSettings.js container/loadSettings.js
- backend/specs/api/pad.js container/specs/api/pad.js

This was very useful to get the feature out, but now it would be better to unify the spec files.

A possible idea could be pass some parameters at runtime, so that `npm test` and `npm test-container` end up calling the same script with just different command line parameters.

Any idea on how to achieve this?

**Comment by JohnMcLear** [comment]
``npm run test`` now runs on travis when the backend tests run
