### ISSUE TITLE
Ansible Builder for Etherpad in a Disconnected Environment

### ISSUE THREAD

**Issue by m3047** [ether/etherpad-lite#3689]
I humbly offer https://github.com/m3047/pangolin/blob/master/etherpad_server.md which is instructions for deploying Etherpad on top of the Pangolin base server along with Ansible script which makes it go. The goal for this project is to find collaboration tools which will run in a disconnected environment, and Etherpad accomplishes that as long as it's allow to run once first so that Node has a chance to pull in the swamp. Thanks for all you do...

**Comment by muxator** [comment]
Hi, @m3047, thanks a lot for using Etherpad.

I [opened an issue](https://github.com/m3047/pangolin/issues/1) with some hints on how to speed up running the Etherpad service in your project.


**p.s.**: I really hope Etherpad's startup method will get rid of bash scripts. For now that's what we have.

**Comment by m3047** [comment]
@muxator thanks for the hints, let me see what I can do!

**Comment by m3047** [comment]
I'm calling this done! I really don't mind the script wrappers, but they do tend to end up as dust bunnies over time and it's nice to know what's essential. This page was key: https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service

Thanks again... fwm
