### ISSUE TITLE
Embedding on Personal Website; doesn't load on Safari

### ISSUE THREAD

**Issue by matters-of** [ether/etherpad-lite#3691]
Hello,

I'm trying to embed a beta.etherpad.org page onto a personal website. While it does load on Chrome, it doesn't seem to load / open on Safari. 

The following is an error pop-up on Safari:

> "Warning: it appears that your browser does not have cookies enabled. EtherPad uses cookies to keep track of unique users for the purpose of putting a quota on the number of active users.  Using EtherPad without  cookies may fill up your server's user quota faster than expected."

The embed block shows this:

> "An error occurred
> The error was reported with the following id: 'YzvVE1npuaWhXaO2C0Vl'
> 
> Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
> 'ErrorId: YzvVE1npuaWhXaO2C0Vl
> URL: https://pad.planka.nu/p/matters-of?showControls=true&showChat=true&showLineNumbers=true&useMonospaceFont=false&wmode=opaque
> UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15
> TypeError: null is not an object (evaluating 'pad.collabClient.setStateIdle') in https://pad.planka.nu/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 3'"
> 

Would appreciate any help! 

Thank you.

**Comment by JohnMcLear** [comment]
Make sure you are running the latest version of Etherpad.  Afaik this sounds like a legacy issue.  Let us know which commit you are running

``git commit`` would show it.
