### ISSUE TITLE
Changing the client's system clock back causes Etherpad to lose data!!!

### ISSUE THREAD

**Issue by hydrogenpi** [ether/etherpad-lite#3692]
I found this out the hard way when I realized my system clock was faster by an hour than the actual time, I changed my clock back an hour in timedate.cpl and started typing in etherpad, later on realized stuff I typed up didn't save when I went back to the etherpad. This being cloud etherpad at first I thought there was something wrong with the server, but had a suspicion that reverting time was the culprit. I created a local instance of etherpad on my own box, using vmware workstation etc, and lo and behold, when I reverted my client clock back an hour, and then did some more typing, then closed out of browser session, rebooted the client (not the etherpad server), then launched the etherpad in the browser again, all work that happened after the clock was reversed back an hour was LOST! 

Is there a way to retrieve or recover this if I have access to the etherpad server itself? (windows server, mysql, etc)

**Comment by JohnMcLear** [comment]
I have a windows debug environment here.

If I change my system time back one hour and hit f5 should I expect to see data loss?

If I put data on a remote server then do the same as above should I expect to see data loss?

**Comment by JohnMcLear** [comment]
I'm pretty sure this was user error cause I can't see a way to replicate.
