### ISSUE TITLE
Postgres set schema / search_path

### ISSUE THREAD

**Issue by rogierlommers** [ether/etherpad-lite#3694]
In a postgres database, you can have multiple schema's. In most languages you can set the schema using f.e. the connection string. Here is an example:

```
postgres://shareddb:xxxx@192.168.1.1:5432/shareddb?search_path=myschema"
```

When I look at the settings of etherpad, I don't see the option to set the schema, right? Or am I missing something?

**Comment by JohnMcLear** [comment]
We consume ueberdb2 for our database abstraction.  This issue would belong there.  

https://github.com/Pita/ueberDB
