### ISSUE TITLE
editor iframe remove?

### ISSUE THREAD

**Issue by tanyo520** [ether/etherpad-lite#3701]

**Comment by JohnMcLear** [comment]
We did this before and there was zero gain.  The main gain was handling weird editor edge cases but all it did was shift the edge cases to non iframe weirdness..  So while it would a nice to have it's absolutely not essential for the foreseeable future.

That said, if anyone wants to hack on it we'd love to see a PR land w/ it achieved in such a way it doesn't break all plugins :D
