### ISSUE TITLE
The "star" button disappears for all pads after visiting a readonly pad

### ISSUE THREAD

**Issue by babu15** [ether/etherpad-lite#3702]
When I use a read-only link the little star-icon disappears. It does not just disappear from one pad. All the old pads and all the newly generated pads no longer have the star in the toolbar.
When I restart the etherpad-service the little star appears again.

**Comment by JohnMcLear** [comment]
Good catch.

Confirmed.  Little star is "saved revision" and it's hidden server side, you gotta restart instance to get it back!  Pretty serious imho.
