### ISSUE TITLE
Plugin ep_delete_after_delay compatibility with etherpad-lite v1.8.0

### ISSUE THREAD

**Issue by ukcb** [ether/etherpad-lite#3704]
ep_delete_after_delay v0.0.8 does not work with etherpad-lite v1.8.0 and nodejs v12.16.1 LTS

> ###################################
> [2020-03-09 19:44:44.282] [INFO] console - Your Etherpad version is 1.8.0 (70bc71c)
> [2020-03-09 19:44:44.873] [INFO] console - You can access your Etherpad instance at http://127.0.0.1:9066/
> [2020-03-09 19:44:44.873] [INFO] console - The plugin admin page is at http://127.0.0.1:9066/admin/plugins
> [2020-03-09 19:44:44.883] [INFO] ueberDB - Flushed 2 values
> [2020-03-09 19:44:44.985] [INFO] ueberDB - Flushed 2 values
> [2020-03-09 19:44:45.451] [ERROR] console - (node:3431) UnhandledPromiseRejectionWarning: apierror: text is not a string
>     at Object.exports.getPad (/home/etherpad/apps/etherpad-lite/src/node/db/PadManager.js:126:13)
>     at /home/etherpad/apps/etherpad-lite/node_modules/ep_delete_after_delay/delete.js:213:20
>     at Layer.handle [as handle_request] (/home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
>     at next (/home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/route.js:137:13)
>     at Route.dispatch (/home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/route.js:112:3)
>     at Layer.handle [as handle_request] (/home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
>     at /home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/index.js:281:22
>     at param (/home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/index.js:354:14)
>     at paramCallback (/home/etherpad/apps/etherpad-lite/src/node_modules/express/lib/router/index.js:401:21)
> [2020-03-09 19:44:45.451] [ERROR] console - (node:3431) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> [2020-03-09 19:44:45.451] [ERROR] console - (node:3431) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> [2020-03-09 19:44:45.815] [ERROR] console - (node:3431) UnhandledPromiseRejectionWarning: apierror: text is not a string
>     at Object.exports.getPad (/home/etherpad/apps/etherpad-lite/src/node/db/PadManager.js:126:13)
>     at Object.exports.handleMessage [as hook_fn] (/home/etherpad/apps/etherpad-lite/node_modules/ep_delete_after_delay/delete.js:136:20)
>     at normalizedhook (/home/etherpad/apps/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
>     at hookCallWrapper (/home/etherpad/apps/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
>     at /home/etherpad/apps/etherpad-lite/src/static/js/pluginfw/hooks.js:88:7
>     at /home/etherpad/apps/etherpad-lite/src/node_modules/async/lib/async.js:249:17
>     at /home/etherpad/apps/etherpad-lite/src/node_modules/async/lib/async.js:125:13
>     at Array.forEach (<anonymous>)
>     at _each (/home/etherpad/apps/etherpad-lite/src/node_modules/async/lib/async.js:46:24)
> [2020-03-09 19:44:45.815] [ERROR] console - (node:3431) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> ###################################

**Comment by JohnMcLear** [comment]
Please create issue on the plugin.

**Comment by ukcb** [comment]
The new version `ep_delete_after_delay@0.0.9` now works. Thank you very much.
