### ISSUE TITLE
Latest UI breaks front end tests

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3706]
Not sure why this wasn't tested prior to merge but mmehhheh

http://instanceURI/tests/frontend

Run it and see what got broken :)

**Comment by muxator** [comment]
Run a test just now.

- Etherpad *bb868beb9cf6*, Colibris, DirtyDb, clean install
- Node *v12.13.1* on Linux
- Firefox 73.0.1 (linux)

http://localhost:9001/tests/frontend/ completes with 100% success.

Analogously, the tests completed with the most recent (at the time) combination of Software & Browser versions when the integration was performed.

I am sure there may be some failures in other setups. I'll try to update Firefox to 74.0 asap and test again, for example.

I am willing to accept any proposal to consistently guarantee a meaningful test matrix, this cannot be left to the goodwill of the developers.

**Comment by JohnMcLear** [comment]
http://192.168.1.42:9001/tests/frontend/?grep=scroll.js%20scroll%20when%20focus%20line%20is%20out%20of%20viewport%20when%20the%20line%20height%20is%20bigger%20than%20the%20scroll%20amount%20percentage%20*%20viewport%20height fails for me

**Comment by JohnMcLear** [comment]
Failure is due to "colibris" skin.  Switching to no-skin passes test

@seballot 
@pkrasicki

**Comment by seballot** [comment]
Hi ! cannot self assign, do not have the proper rights, but yes I can have a look !

**Comment by muxator** [comment]
I have updated to Firefox **74** (Etherpad **1.8.0**).
I can confirm the scroll test started failing for me, too. It worked with Firefox **73**.

Obviously the [changelog for Firefox 74](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/74#Changes_for_web_developers) does not readily mention anything regarding the reason for this failure.

**Comment by seballot** [comment]
Mmmm, I had a look. The behaviour of colibris is good (same as for no-skin) re this scrolling requirement when a line is higher than viewport, the problem come from the test...

Don't know why, when setting up the test  `scroll.js line 294` the `scrollEditorToLeaveTopAndBottomOfBigLineOutOfViewport($bigLine);` does not work with colibris, the page is still scroll to Top, and the selector is in first position of the document.

I tried to fix quickly, but without success sorry, and I prefer dedicate my time to fix real issue :)

Will try the mobile toolbar now!
