### ISSUE TITLE
Adding plugin items to toolbar then removing the plugin causes server to crash w/ no explanation

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3707]
For example see https://github.com/JohnMcLear/ep_align/issues/13
Add these to settings.json
Restart Server
Works
Remove ep_align plugin
Restart Server
Dead server.

**Comment by orblivion** [comment]
#3707 is merged, should this be closed?

**Comment by JohnMcLear** [comment]
Tnx
