### ISSUE TITLE
Use of space key causing weird cursor behaviour

### ISSUE THREAD

**Issue by maxkratz** [ether/etherpad-lite#3728]
Hi,

I've tested etherpad as docker container and I found a bug that shows up even if no special configuration gets applied.

The cursor jumps back to the beginning of a line if the user types in a space. I can reproduce this with docker-image 'latest', '1.8.0' and '1.7.5' on Chromium/Firefox (Ubuntu 18.04) and iPad Safari. Changing the theme to 'no-skin' did not help. (Furthermore there are no plugins installed at all.)

You will find a gif attached to this message for further description.

![ezgif-2-3132bdf18dad](https://user-images.githubusercontent.com/20956405/76955885-4ddf5b00-6913-11ea-9c91-c4853c35d555.gif)

**Comment by muxator** [comment]
Thanks for the detailed report.

Since #3663 describes the same issue, let's move the discussion there.

I'll try to manually move your message there.

**Comment by muxator** [comment]
@maxkratz, is it possible for you to test #3729 and see if this problem is solved for you?

If you need help in integrating those changes, fell free to write here.

**Comment by maxkratz** [comment]
@muxator I've pulled your pr and built a new docker-image out of it (using the provided Dockerfile). As far as I can tell, the issue persists and nothing changed. (Tested with chromium and firefox, both on linux.)

**Comment by maxkratz** [comment]
@muxator I think I made a mistake. In my previous tests I did not clear the caches of all my browsers.
**As soon as I always empty the cache(s), the Docker image with tag '1.8.0' (and older) does the job.**

(Furthermore I am able to build a local Docker image out of this repository with tag '1.8.0' and everything works fine. If I use the latest version of the develop branch, the bug occurs!)

So in my opinion the error must be a change in code after version '1.8.0'.

**Comment by maxkratz** [comment]
> @muxator I've pulled your pr and built a new docker-image out of it (using the provided Dockerfile). As far as I can tell, the issue persists and nothing changed. (Tested with chromium and firefox, both on linux.)

My comment above was **wrong** as I did not clear the browsers cache.

@muxator I've tested your pr again with proper clearing of my browsers cache. **Your change does indeed resolve the problem!**

I was able to build a local Docker image from your pr and this version just works as expected. Thank you for your help!

**Comment by muxator** [comment]
Thanks @maxkratz for validating it. As you can see these sort of issues are finky to debug, and more eyeballs are always a good protection net.

I'll wait for further tests by other users and merge #3729.


**p.s.**: I am starting to suspect that the Etherpad's caching behaviour needs a rework

**Comment by muxator** [comment]
Confirmed that this debilitating issue was definitely caused by  3292429ab312.

Pulled in #3729 that fixes it, thanks for reporting.

**n.b.**: issue #3663 is unrelated

**Comment by JohnMcLear** [comment]
Thanks for quick revert, correct thing to do.

https://github.com/ether/etherpad-lite/pull/3622/files#r394967755

So @tombriles I put a comment on the offending line.  Please review and fix.

**Comment by manu-p** [comment]
Hi, I guess I'm facing the same issue and I would like to apply the corrections as of mentioned here but I'm not a dev and also I don't know the way I could just download these 2 files in order to replace them in my installation.

Where can I find these files, please?

**Comment by maxkratz** [comment]
@manu-p How did you install etherpad?

Normally a fresh installation or an update of your current installation should fix the issue. (Do not repeat my mistake and clear your browsers cache before testing :-).)

**Comment by JohnMcLear** [comment]
``git pull``

**Comment by maxkratz** [comment]
@JohnMcLear If he is using a prebuilt Docker image this is not going to work.

**Comment by manu-p** [comment]
Thanks for your help, I just did a new fresh install following the [installation procedure](https://github.com/ether/etherpad-lite/blob/develop/README.md), so I get 1.8.0 but have not been able to check if it's correcting the strange cursor behavior because I get the infinite "Loading" syndrome... 
Gonna open another issue for this. :-/
