### ISSUE TITLE
Abiword/Odt export fail due to wrong html

### ISSUE THREAD

**Issue by elacour** [ether/etherpad-lite#3732]
Using etherpad-lite 1.7.5 with abiword 3.0.2, abiword failed to open the html produced by etherpad lite saying it's invalid:

AbiWord: could not open the file [/tmp/etherpad_export_2901074964.html]

In fact a tidy on the body content says:

$ tidy -xml html.html 
line 1 column 5296 - Error: unexpected </ul> in <li>
line 1 column 5452 - Error: unexpected </ul> in <li>
line 1 column 10073 - Error: unexpected </ul> in <li>
line 1 column 11028 - Error: unexpected </ul> in <li>
line 1 column 12115 - Error: unexpected </ul> in <li>

The pad cannot be shared publicly and has 4k+ lines, so I'm not able to identify exactly the problem :(

**Comment by JohnMcLear** [comment]
try ``soffice`` and other tools.  Also push the html through an HTML validator.  It's possible the HTML is bad but it's often ``abiword`` that causes the problems ;\

**Comment by JohnMcLear** [comment]
Closing this as it hasn't got sufficient info for me to help.

**Comment by elacour** [comment]
> try `soffice` and other tools. Also push the html through an HTML validator. It's possible the HTML is bad but it's often `abiword` that causes the problems ;\

Yes, I can open it manually through libreoffice. But in fact the html produced is invalid. Abiword is more strict. I see very is other export plugins such as this one: https://www.npmjs.com/package/ep_unoconv, I may try it.

**Comment by JohnMcLear** [comment]
I mean, unless you can tell me what part of the HTML is invalid it's hard for me to fix this for you ;\  Any chance you can give me the HTML validation error or provide steps to replicate/reproduce this issue?

**Comment by risacher** [comment]
See below errors which happen in attached file.

```
$ tidy -xml /tmp/etherpad_export_675394756.html
line 43 column 1 - Error: unexpected </head> in <meta>
line 125 column 43 - Warning: unescaped & which should be written as &amp;
line 127 column 16 - Warning: unescaped & which should be written as &amp;
line 253 column 6 - Warning: unescaped & which should be written as &amp;
line 374 column 1 - Error: unexpected </body> in <br>
line 375 column 1 - Error: unexpected </html> in <br>
Tidy found 3 warnings and 3 errors!
```
[etherpad_export_675394756.txt](https://github.com/ether/etherpad-lite/files/12937918/etherpad_export_675394756.txt)

**Comment by SamTV12345** [comment]
@risacher The official w3c html validator is happy. Also I can't really get why this tool reports these errors. The structure is correct. 

![image](https://github.com/ether/etherpad-lite/assets/40429738/42c37f02-afb7-43e4-bbc1-d9033064ec76)

**Comment by risacher** [comment]
@SamTV12345  I don't disagree; I just note that if you fix these "errors" which are valid HTML but not valid XML, then abiword works.  The upshot of abiword's pedantic HTML parser is that etherpad can't actually export. :(

**Comment by SamTV12345** [comment]
> @SamTV12345 I don't disagree; I just note that if you fix these "errors" which are valid HTML but not valid XML, then abiword works. The upshot of abiword's pedantic HTML parser is that etherpad can't actually export. :(

Ok. Didn't know that Abiword is that pedantic. Alright I'll have a look at this tomorrow.
