### ISSUE TITLE
[SOLVED] Pad opening failure, keeps loading...

### ISSUE THREAD

**Issue by manu-p** [ether/etherpad-lite#3735]
Fresh Etherpad re-installation, because of strange cursor behavior.
Ubuntu Server 18.04 with apache2
nodejs v10.19.0
Etherpad 1.8.0

When I try to open a pad I get a blank page with "Loading..." and nothing else is happening.

etherpad runs as a service (been working like a charm before re-install).

Yes, nodejs is running, ps | grep nodejs:
`etherpad  8138  0.3  0.3 920304 74340 ?        Ssl  18:45   0:06 /usr/bin/nodejs /home/etherpad/etherpad-lite/node_modules/ep_etherpad-lite/node/server.js`

Using a MySQL database, restored it from a nightly backup: no change.
When I let 3306 as port in settings.json, I can see errors in apache etherpad log:
`[Fri Mar 20 19:18:40.962344 2020] [proxy_http:error] [pid 10065] (20014)Internal error (specific information not available): [client A.B.C.D:60610] AH01102: error reading status line from remote server 127.0.0.1:9001`
`[Fri Mar 20 19:18:41.034503 2020] [proxy:error] [pid 30862] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:9001 (127.0.0.1) failed`
`[Fri Mar 20 19:18:41.034607 2020] [proxy_http:error] [pid 30862] [client A.B.C.D:60630] AH01114: HTTP: failed to make connection to backend: 127.0.0.1`

When I switch port to /var/run/mysqld/mysqld.sock as mentioned [here](https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL) no more errors, but still **Loading...**

`# systemctl status etherpad`
`● etherpad.service - Etherpad-lite, the collaborative editor.`
`   Loaded: loaded (/etc/systemd/system/etherpad.service; enabled; vendor preset: enabled)`
`   Active: active (running) since Fri 2020-03-20 19:29:29 CET; 2s ago`
` Main PID: 6494 (nodejs)`
`    Tasks: 11 (limit: 4915)`
`   CGroup: /system.slice/etherpad.service`
`           └─6494 /usr/bin/nodejs /home/etherpad/etherpad-lite/node_modules/ep_etherpad-lite/node/server.js`

`mars 20 19:29:29 vps801837 nodejs[6494]: [2020-03-20 19:29:29.887] [INFO] console - No credentials file found in /home/etherpad/etherpad-lite/credentials.json`
`mars 20 19:29:29 vps801837 nodejs[6494]: [2020-03-20 19:29:29.889] [INFO] console - Using skin "no-skin" in dir: /home/etherpad/etherpad-lite/src/static/skins`
`mars 20 19:29:29 vps801837 nodejs[6494]: [2020-03-20 19:29:29.890] [INFO] console - Session key loaded from: /home/etherpad/etherpad-lite/SESSIONKEY.txt`
`mars 20 19:29:29 vps801837 nodejs[6494]: [2020-03-20 19:29:29.981] [ERROR] console - (node:6494) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated`
`mars 20 19:29:30 vps801837 nodejs[6494]: [2020-03-20 19:29:30.910] [INFO] APIHandler - Api key file read from: "/home/etherpad/etherpad-lite/APIKEY.txt"`
`mars 20 19:29:31 vps801837 nodejs[6494]: [2020-03-20 19:29:31.130] [INFO] console - Installed plugins:`
`mars 20 19:29:31 vps801837 nodejs[6494]: [2020-03-20 19:29:31.132] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues`
`mars 20 19:29:31 vps801837 nodejs[6494]: [2020-03-20 19:29:31.133] [INFO] console - Your Etherpad version is 1.8.0 (c8580a6)`
`mars 20 19:29:31 vps801837 nodejs[6494]: [2020-03-20 19:29:31.290] [INFO] console - You can access your Etherpad instance at http://127.0.0.1:9001/`

Been strugling for hours with this, can't find what's wrong...

**Comment by muxator** [comment]
From the logs it seems that Etherpad is running correctly, binds on 127.0.0.1:9001, and you have an Apache reverse proxy in front of it. Is that true?

Apache is not being able to connect to 127.0.0.1:9001. Have a look at the Apache configuration. 

Anyway, this is definitely an ops problem.

**Comment by manu-p** [comment]
Thanks @muxator for your help.

Here's the apache conf for etherpad, it's been working fine before I re-install etherpad:
`<VirtualHost *:443>`
`    ServerName pad.domain.fr`
`    ServerAdmin identifier@domain.fr`
`    CustomLog  ${APACHE_LOG_DIR}/etherpad.access.log combined`
`    ErrorLog  ${APACHE_LOG_DIR}/etherpad.error.log`
`    <IfModule mod_http2.c>`
`      Protocols h2 http/1.1`
`    </IfModule>`
`    SSLEngine on`
`    SSLCertificateFile    	/etc/letsencrypt/live/pad.domain.fr/fullchain.pem`
`    SSLCertificateKeyFile   	/etc/letsencrypt/live/pad.domain.fr/privkey.pem`
`     Header always set Strict-Transport-Security "max-age=15768000"`
`    ProxyRequests Off`
`    <Proxy *>`
`      Order deny,allow`
`      Allow from all`
`    </Proxy>`
`    ProxyPass / http://127.0.0.1:9001/`
`    ProxyPassReverse / http://127.0.0.1:9001/`
`    <Location />`
`      Order allow,deny`
`      Allow from all`
`    </Location>`
`</VirtualHost>`

Definitely an ops problem? No change apart re-install etherpad, it has to be somewhere in etherpad config but I just can't find where...

**Comment by manu-p** [comment]
> Apache is not being able to connect to 127.0.0.1:9001. Have a look at the Apache configuration.

Only when 3306 is let as "port" in settings.json which is not the case since I put '/var/run/mysqld/mysqld.sock' instead.

**Comment by manu-p** [comment]
Mmh... just rebooted the server and... guess what? 
Yes, pads are opening instantly.
