### ISSUE TITLE
Developer help

### ISSUE THREAD

**Issue by seballot** [ether/etherpad-lite#3739]
Hello !

I'm running etherpad locally with dirtyDB and running `sh bin/run.sh`

**When I edit a javascript file, I always need to stop the server and start it again for my changes to be loaded,** which is very annoying... What am I doing wrong? I did try with `h bin/debugRun.sh` but it does the same thing

Also, a **strange issue I got from today, the space bar does not work anymore.**.. I tried with develop branch, even with master at 1.8.0, still happening... Any idea? On online etherpad instance I do not have this problem (so not coming from my keyboard)

See this screencast : after writing "usingwhitespace" I did press the space bar multiple time, first time it goes back to start of the line, then move cursor to the right, then come back to the start and so on...
![Peek 21-03-2020 13-40](https://user-images.githubusercontent.com/17404254/77226557-a2840f80-6b79-11ea-9d64-546bcb99a6fc.gif)

**Comment by muxator** [comment]
> When I edit a javascript file, I always need to stop the server and start it again for my changes to be loaded

Yes, you have to restart. Theg good news is, as long as your changes did not touch any dependency in `package.json`, *a direct Etherpad restart can be very quick*. Have a look at https://github.com/ether/etherpad-lite/issues/3711#issuecomment-599135831.

> the space bar does not work anymore

You were hit by #3728. This was solved in #3729 (and this is the reason for which a was slow to review your recent PR).  I think *you also have to clear your browser's cache*. If you still experience the problem (which I hope not), please write there.

Hope it helps.

**Comment by JohnMcLear** [comment]
Thanks @muxator this should be resolved now.

**Comment by seballot** [comment]
Oh great, thanks for your quick reply !
fastRun in very nice, and sorry for the space bar, I should have search in the issues. I only checked the recent commit but I did not make the link with "contentcollector"

> and this is the reason for which a was slow to review your recent PR

Ah ah, you have a strange conception of the slowness !! looked quite fast to me :)
Ok, going back to css refactor..
