### ISSUE TITLE
exporting authorship colours

### ISSUE THREAD

**Issue by dora71** [ether/etherpad-lite#374]
This is a feature request:
It would be nice that when exporting to PDF, OpenDocument or Microsoft Word, not only to export the plain text, but also the authorship colours.
Perhaps it is possible to choose whether or not to export the colours by (un)checking a box.

**Comment by JohnMcLear** [comment]
Bounty for this: https://www.bountysource.com/issues/1371946-exporting-authorship-colours

**Comment by JohnMcLear** [comment]
https://github.com/Gared/ep_export_authors
