### ISSUE TITLE
Remove wd from devDependencies

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3741]
The [wd library](https://www.npmjs.com/package/wd) seems not used anywhere in the codebase. I guess this adds a sizable quantity of packages to our dev installation for no benefits.

Moreover, in the past we had some users having problems installing Etherpad because of it.

@JohnMcLear, from your memory: do you see any problems in removing `wd`?

**Comment by JohnMcLear** [comment]
Afaik we have automated tests run on saucelabs / jenkin no?  They test each browser for us on each commit...  Or is that not a thing any more :D

**Comment by muxator** [comment]
Apparently they stopped working long time ago.

2017-07-27: 59ba183c82eb: Issue #2948 - disable sauce labs frontend tests until they are working. (#3230)
2019-12-21: bf0bb58c703f: a commit by me on an unrelated question where I resumed a bit the situation

**Comment by JohnMcLear** [comment]
I think my input here is limited..

I liked having full integrated test coverage as it caught a lot of edge cases (caret jumping around in browsers etc) and the ability to test vendors who restrict developers access to software / product.  It saved my bacon enough times to justify the effort.

But it's up to you really, I can imagine fixing saucelabs wont be a huge effort tho?  It'd be nice to get it running again no?  They are still supporting OSS project so...  https://saucelabs.com/solutions/open-source

I did notice the CEO changed though so maybe winds of change!?

I can find time to take a punt at getting SL working again if that's gonna be the win here else we can just remove wd or whatever.

Your decision :)

**Comment by muxator** [comment]
> It'd be nice to get it running again no? 

Sure it is. The more testing the better.

Please go on with [Open Souce](https://saucelabs.com/solutions/open-source), it would be wonderful!

**Comment by JohnMcLear** [comment]
Will dump research here..

Created branch with SL added back in

```
$ bin/installDeps.sh
install.2

0.01s$ export GIT_HASH=$(git rev-parse --verify --short HEAD)
install.3

4.62s$ npm install ep_test_line_attrib

$ tests/frontend/travis/sauce_tunnel.sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100   558  100   558    0     0    975      0 --:--:-- --:--:-- --:--:--   975

gzip: stdin: not in gzip format

tar: Child returned status 1

tar: Error is not recoverable: exiting now

mv: cannot stat '/tmp/sc-*-linux': No such file or directory

tests/frontend/travis/sauce_tunnel.sh: line 14: /tmp/sauce_connect/bin/sc: No such file or directory
```

``https://saucelabs.com/downloads/sc-latest-linux.tar.gz`` 404s :D

**Comment by JohnMcLear** [comment]
Okay fix is in, tests are running again.  But I think more work is required because afaik if you try and send a commit the tests wont run, it's something environment specific to my github user or so...

We need to keep wd in.

More fixes landed

**Comment by JohnMcLear** [comment]
As Saucelabs is now restored, I'm gonna close this off.
