### ISSUE TITLE
Is the global view section ever used in the settings popup?

### ISSUE THREAD

**Issue by seballot** [ether/etherpad-lite#3746]
Hi !
In settings popup, there are two columns : My view and Global View

I've always seen the global view empty, is this ever used by some plugin?

![image](https://user-images.githubusercontent.com/17404254/77258605-d9424e80-6c7b-11ea-9e6d-ee11eba582f5.png)

**Comment by JohnMcLear** [comment]
Good question, I can't think when I did it, why I did it or what the use case was.

But I'd guess at "no" being the answer here.  I do remember writing a "stop writing" plugin and that would make sense to be there...  Lemme checlk..

**Comment by JohnMcLear** [comment]
I took a more scientific approach and google searched for

site:github.com "ep_" globalView

literally 0 plugins use that hook (or at least ones published on Github).

So we can drop it.
