### ISSUE TITLE
build/install help 

### ISSUE THREAD

**Issue by f1-outsourcing** [ether/etherpad-lite#3750]
Say I want to use etherpad and create a docker image. I just want to include the nodejs app no docs and test and whatever.

So I did a 
```
git clone --branch master https://github.com/ether/etherpad-lite.git /tmp/etherpad
cp -a /tmp/etherpad/src/* /usr/local/etherpad/
cd /usr/local/etherpad/
npm ci --production
```
But when I try to execute, I am getting this. 

```
bash-5.0# node node/server.js
[2020-03-23 19:59:11.038] [DEBUG] console - Running on Node v10.19.0 (minimum required Node version: 8.9.0)
[2020-03-23 19:59:11.410] [DEBUG] AbsolutePaths - /usr/local/etherpad does not end with "src"
[2020-03-23 19:59:11.411] [ERROR] AbsolutePaths - Could not identity Etherpad base path in this linux installation in "/usr/local/etherpad"
```
What is the correct way to get only necessary files?

**Comment by JohnMcLear** [comment]
Etherpad is an application, it's not a node module.
Etherpad comes with documentation, it's software, that's what software comes with.
Etherpad comes with test coverage, it's software, that's what software comes with.

Perhaps tell me what you are trying to achieve and I can help you.  It sounds like you are going about things in the wrong way right now and I think you maybe think Etherpad is just the operational transport element of Etherpad??  If you want an OT engine, see ShareJS.

If you want just general help and support installing the software please see the wiki :)

**Comment by f1-outsourcing** [comment]
> 
> Etherpad is an application, it's not a node module.

I know, it is nodejs application

> Etherpad comes with documentation, it's software, that's what software comes with.

I do not need that in a docker image, nobody is going to read it there.

> Etherpad comes with test coverage, it's software, that's what software comes with.
You test before going into production. You do not need your test scripts in a production docker image.

> Perhaps tell me what you are trying to achieve and I can help you. It sounds like you are going about things in the wrong way right now and I think you maybe think Etherpad is just the operational transport element of Etherpad?? If you want an OT engine, see ShareJS.
> 
> If you want just general help and support installing the software please see the wiki :)

Do you understand the commands I have typed? Those should be self explanatory

**Comment by JohnMcLear** [comment]
Yea, I mean you said "whatever", so no.  You weren't explicit so by definition it wasn't self explanatory..

We provide a docker image here: https://github.com/ether/etherpad-lite/blob/develop/Dockerfile

Perhaps you should refer to that?  If you don't want docs then just rm -Rf the docs folder in the Dockerfile ?

**Comment by muxator** [comment]
@f1-outsourcing, Etherpad setup/start sequence is a bit unusual, in which it involves the creation of a **specific directory structure** (right now you have to deduce it from reading [`installDeps.sh`](https://github.com/ether/etherpad-lite/blob/43ca44e444d89e886dc22e2f745f2656439cb8ff/bin/installDeps.sh) and to a lesser extend the [`Dockerfile`](https://github.com/ether/etherpad-lite/blob/43ca44e444d89e886dc22e2f745f2656439cb8ff/Dockerfile)).

From memory (I may be wrong), the steps you could try would be:
- `git clone --branch master https://github.com/ether/etherpad-lite.git /tmp/etherpad`
- `cd /tmp/etherpad`
- `bin/installDeps.sh`
- `mv {src,node_modules,var} /usr/local/etherpad/`
- copy `settings.json.template` as `/usr/local/ehterpad/settings.json` and **customize it**
- launch with `node node_modules/ep_etherpad-lite/node/server.js` from working directory `/usr/local/ehterpad`

Hope it helps.

By the way, thanks for showing us the use ot the [`npm ci`](https://docs.npmjs.com/cli/ci.html): it may be useful for making our builds more reproducible.

**Comment by muxator** [comment]
Also, I think a lot of confusion in Etherpad users with respect to its startup sequence comes from the fact that it is effectively a strange hybrid: **an application that also wants to be a node module**.

See this commit from **2012**: 1239ce7f2848 ("_The Big Renaming - etherpad is now an NPM module_"), which caused me a lot of headaches in the past while trying to simplify the startup sequence (something I still did not manage to do without breaking compatibility).

To be fair, this project was an early adopter of nodejs, and its ecosystem was far from mature. It would be hard to do better at the time.

Please let's focus on how to improve it moving forward.

**Comment by f1-outsourcing** [comment]
> 
> 
> @f1-outsourcing, Etherpad setup/start sequence is a bit unusual, in which it involves the creation of a **specific directory structure** (right now you have to deduce it from reading [`installDeps.sh`](https://github.com/ether/etherpad-lite/blob/43ca44e444d89e886dc22e2f745f2656439cb8ff/bin/installDeps.sh) and to a lesser extend the [`Dockerfile`](https://github.com/ether/etherpad-lite/blob/43ca44e444d89e886dc22e2f745f2656439cb8ff/Dockerfile)).
> 
> From memory (I may be wrong), the steps you could try would be:
> 
>     * `git clone --branch master https://github.com/ether/etherpad-lite.git /tmp/etherpad`
> 
>     * `cd /tmp/etherpad`
> 
>     * `bin/installDeps.sh`
> 
>     * `mv {src,node_modules,var} /usr/local/etherpad/`
> 
>     * copy `settings.json.template` as `/usr/local/ehterpad/settings.json` and **customize it**
> 
>     * launch with `node node_modules/ep_etherpad-lite/node/server.js` from working directory `/usr/local/ehterpad`
> 
> 
> Hope it helps.
> 
> By the way, thanks for showing us the use ot the [`npm ci`](https://docs.npmjs.com/cli/ci.html): it may be useful for making our builds more reproducible.

Thanks!!!!

**Comment by tacerus** [comment]
This is very helpful.
The installation routine caused me a lot of headache. I did not understand why there were several directories containing `node_modules`. Using `npm install` from different directories yielded different results. Installing plugins from the base directory using `npm install` caused a ton of unsolvable dependency issues, installing them from `src/` however seems to work and allow the application to start up. Until however a client tries to connect:

`[2022-03-16 15:04:56.210] [ERROR] AbsolutePaths - Could not identity Etherpad base path in this linux installation in "/opt/etherpad/etherpad-lite/src/node_modules/ep_etherpad-lite"`

What does this message mean? How does one "identity a base path"?

I attempted running it using `node <path>/server.js` file, trying the paths `src/node/` and `node_modules/ep_etherpad-lite/node/server.js`.

The shell scripts do not seem to be of help either - `run.sh` seemingly tires to re-install hundreds of packages with each run, making it seem more like an installation, and less a "run" script. The `installDeps.sh` script seems to initialize a working set of dependencies, however the results seem similar enough to using `npm install` from within `src/`.

**Comment by tacerus** [comment]
OK, I was able to work around my issue by commenting out all references to `maybeEtherpadRoot` in `src/node_modules/ep_etherpad-lite/node/utils/AbsolutePaths.js` and hard-coding `etherpadRoot = '/opt/etherpad/etherpad-lite/';`.

Given this comment in the file:
```
 * The path is computed only on first invocation. Subsequent invocations return
 * a cached value.
```
I assume there might have been some wrong location cached, however I could not find any documentation on how to dump and flush this cache (and why this cache would be there in the first place).

Whilst tampering with the application code is certainly not an ideal solution, I will leave this here in case it helps anyone encountering the given error message in the future.

**Comment by rhansen** [comment]
> installing other NodeJS applications is generally only a task of navigating to a single directory and running a single command to initialize dependencies, after which one can launch the program manually or through an init system by pointing the node binary to the main .js file. With EtherPad I feel like being on a big safari tour through a jungle of JavaScript.

Yeah, it's a mess. I think it was done this way so that plugin installation wouldn't modify any checked-in files. Unfortunately, npm's behavior changed with v7.x causing more problems. A temporary workaround until we can clean this up is to pass `--no-save --legacy-peer-deps` to `npm` when installing plugins.
