### ISSUE TITLE
is logging to syslog supported?

### ISSUE THREAD

**Issue by f1-outsourcing** [ether/etherpad-lite#3753]
is logging to syslog supported?

**Comment by JohnMcLear** [comment]
Not out of the box but that's something you could pluginify relatively easily.  

Can you explain a little bit more about how you would like it to behave?

**Comment by f1-outsourcing** [comment]
just log to /dev/log because that is what most containers (I guess) use. /dev/log I am redirecting to a remote syslog server.

**Comment by f1-outsourcing** [comment]
pfff
