### ISSUE TITLE
Revision author

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3754]
When hovering over the star of the revision, show who its author is https://prnt.sc/rlq9lm. It is convenient to keep track of who did the revisions when co-editing the document.

**Comment by JohnMcLear** [comment]
From the API
```
  , "saveRevision"              : ["padID", "rev"]
```
No authorInfo is saved via API.

```
  pad.addSavedRevision(pad.head, userId);
```
Yet addSavedRevision does save UserId..  So watch out for the caveat of the API not storing a userId with save.
