### ISSUE TITLE
trying to setup as cpanel passenger app

### ISSUE THREAD

**Issue by beppe9000** [ether/etherpad-lite#3756]
I saw this https://github.com/ether/etherpad-lite/wiki/Running-Etherpad-on-Phusion-Passenger
But cpanel's gui lacks a way to set those settings separately and i think it just reads the package json

I get this when running manually
```
[username@s1 etherpad-lite-1.8.0]$ /opt/cpanel/ea-nodejs10/bin/node src
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/username/priv/etherpad-lite-1.8.0/src'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

This is cpanels phusion settings for the application:
![image](https://user-images.githubusercontent.com/6625123/77442116-8044f880-6dea-11ea-9943-3d775a05204e.png)

**Comment by muxator** [comment]
@beppe9000, was `bin/installDeps.sh` run at least once?

**Comment by beppe9000** [comment]
It asked me to install node when I tried, before....

**Comment by muxator** [comment]
Ciao @beppe9000, can we close this?

**Comment by beppe9000** [comment]
i've managed to run etherpad manually but it wouldn't start when run from passenger, which I would like to use for the integrated rub+ssl proxying in cpanel ... :\

**Comment by JohnMcLear** [comment]
I'd reach out to the passenger github / support / community and if it turns out it's something we can do / need to do to improve the UX then let us know but at current I think it's a passenger config issue.
