### ISSUE TITLE
Save revision icon showing on left menu bar?! :D

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3767]
[
![awtf](https://user-images.githubusercontent.com/220864/77750496-cdf47780-701b-11ea-9ebf-5e89c33eb938.PNG)
](url)

**Comment by ukcb** [comment]
A little question please: I see icons for microphone and camera on your screenshot. Is this a plugin or how does it work? Thanks a lot!

**Comment by JohnMcLear** [comment]
https://video.etherpad.org



ep_webrtc :)



-----Original message-----

**Comment by alekso87** [comment]
<img width="1438" alt="444" src="https://user-images.githubusercontent.com/25965602/77793923-a9c48500-7073-11ea-90e4-ce6397672457.png">
icon in two palces ? :)

**Comment by alekso87** [comment]
<img width="1435" alt="5555" src="https://user-images.githubusercontent.com/25965602/77794014-cd87cb00-7073-11ea-8bb6-ac56b3280ee1.png">
save revision icon on the time slider side?

**Comment by JohnMcLear** [comment]
oh man, good spot...
