### ISSUE TITLE
sessionID does not exist

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3773]
`http://xx.xx.xx.xx:9001/api/1/createGroup?apikey=f87c39500ff33a59401235b34e604efcf206964057c825beedfad48256fbcb89`

`{
  "code": 0,
  "message": "ok",
  "data": {
    "groupID": "g.BkM9IEVXPlxLzl63"
  }
}`

`http://xx.xx.xx.xx:9001/api/1/createGroupPad?apikey=f87c39500ff33a59401235b34e604efcf206964057c825beedfad48256fbcb89&groupID=g.BkM9IEVXPlxLzl63&padName=newPad&text=12345`

`{
  "code": 0,
  "message": "ok",
  "data": {
    "padID": "g.BkM9IEVXPlxLzl63$newPad"
  }
}`

After that i will try to open pad `http://xx.xx.xx.xx:9001/p/g.BkM9IEVXPlxLzl63$newPad`

<img width="1439" alt="3" src="https://user-images.githubusercontent.com/25965602/77767563-f09d8500-7049-11ea-87bb-7e3b3bcff592.png">

`"requireSession": false,` in settings.json if it is important

**Comment by alekso87** [comment]
I apologize. The setting above was from the master branch.

Installed a project from a develop branch, the error is gone. But still failed to open the pad.

<img width="740" alt="1" src="https://user-images.githubusercontent.com/25965602/77783573-c657c180-7061-11ea-9716-eedae028433f.png">
<img width="1439" alt="11" src="https://user-images.githubusercontent.com/25965602/77784137-b7254380-7062-11ea-9dac-fcf265dd63ea.png">

I tried to set the password on the pad, the password was successfully set, but I did not see it in the next error message.

<img width="1434" alt="33" src="https://user-images.githubusercontent.com/25965602/77784066-8f35e000-7062-11ea-8ebc-3e4533ea2048.png">

**Comment by JohnMcLear** [comment]
Take a look at the backend test logic.  I'm pretty sure this is covered and tested so I doubt it's broken.

https://github.com/ether/etherpad-lite/blob/develop/tests/backend/specs/api/sessionsAndGroups.js

If you read through that file and maybe copy/paste some of the calls then it might help you get to where you are trying to get to! 

Without your source code for api calls it would be hard for me to debug your situation.

**Comment by alekso87** [comment]
Thanks, I'll try. But do I really need to create a session for group ped? Without this, I see that there is no access.

**Comment by JohnMcLear** [comment]
If that's what the tests do and that's what the docs say you need to do I'm gonna say yes.  But obviously our error msg is not clear enough?

**Comment by alekso87** [comment]
@JohnMcLear, from settings.json

`  /*
   * If this option is enabled, a user must have a session to access pads.
   * This effectively allows only group pads to be accessed.
   */
  "requireSession": false,`

Then I do not quite understand this setting. I have it turned off, but the group pad requires access, although it was created without a session.
