### ISSUE TITLE
beta.etherpad.org and codepad.etherpad.org links are broken in wiki

### ISSUE THREAD

**Issue by dlebauer** [ether/etherpad-lite#3774]
The first two links on this wiki page: https://github.com/ether/etherpad-lite/wiki/Sites-that-run-Etherpad-Lite#development-environments-used-for-testing-new-versions--plugins-etc are broken

**Comment by JohnMcLear** [comment]
Yea Rackspace removed their hosting for beta.etherpad.org, I can bring it back up I guess on the video.etherpad.com box..
