### ISSUE TITLE
Put an updated screenshot in README.md

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3779]
Now that the default skin is **Colibris**, we should replace the animated gif in [README.md](https://github.com/ether/etherpad-lite/blob/1ad6e9c2880ed074ba7f6185bdb399d84b298310/README.md) with a more modern one.

![Demo Etherpad Animated Jif](https://i.imgur.com/zYrGkg3.gif "Etherpad in action")

@seballot is going to do the same in https://github.com/ether/ether.github.com/issues/30 for the website.

**Comment by locness3** [comment]
Running etherpad, I get something looking exactly like in README...

**Comment by locness3** [comment]
Nevermind, I didn't change in `settings.json`

**Comment by JohnMcLear** [comment]
@seballot is actively working on this still, it would make sense he makes the screen shots as he will know the best view :D
