### ISSUE TITLE
Release 1.8.3: what do we want to include?

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3781]
We have done a lot of work lately, thanks to @JohnMcLear that came back with all his energy (many thanks, John).

It is time to start thinking about a release.

There are still a lot of PRs & issues outstanding, and before we cut a new release, we need to select what to include and what to leave behind.

My proposal is:

Let's review the [milestone for **1.8.1**](https://github.com/ether/etherpad-lite/milestone/13) and include there all the PRs / issues that we want to integrate, and move to [**1.8.2**](https://github.com/ether/etherpad-lite/milestone/14) everything that we decide to leave out.

**Comment by JohnMcLear** [comment]
Push to future version:
- [ ] https://github.com/ether/etherpad-lite/issues/3463
- [ ] https://github.com/ether/etherpad-lite/pull/3408

Other stuff should be worked on and merged.

**Comment by JohnMcLear** [comment]
I think we should include https://github.com/ether/etherpad-lite/pull/3833
and
https://github.com/ether/etherpad-lite/pull/3827

As they both address security issues.

**Comment by muxator** [comment]
> Also did we rename 1.8.1 > 1.8.3 for some reason? :D

Yep. 1.8.3 was the version that programmed to dump nodejs 8 support. Sticking to that.

**Comment by micah** [comment]
Is it possible to have a release that only fixes the critical, security bugs, and doesn't do the entire nodejs migration? The reason I ask is because those fixes seem important to get out there quickly, and combining those with the nodejs migration will make it harder for us to deploy the new version.

Thanks!

**Comment by JohnMcLear** [comment]
What do you mean by "entire nodejs migration"? :D

**Comment by JohnMcLear** [comment]
Ah okay well I guess a specific one worth addressing is:



https://github.com/ether/etherpad-lite/issues/3404



https://github.com/ether/etherpad-lite/issues/3882



Afaik it should be trying to load ru.json if ru-RU.json is not available?



It's probably an easy fix and a good one to warm up on? :)







-----Original message-----

**Comment by muxator** [comment]
@micah, starting from 2020, nodejs 8 is not supported by its developer (https://nodejs.org/en/about/releases/). The deprecation has been in the roadmap for quite a long time.

Moving to a different node version is really easy, if you are ok using the binary release from https://nodejs.org/en/download/ instead of your distro's.

It's really unzipping a tarball and putting a symlink to `node` and `npm` in your process's path. It does not even need to be done on the system level.

**Comment by muxator** [comment]
Closing this ticket. The missing items for the release are being tracked [in the 1.8.3 milestone](https://github.com/ether/etherpad-lite/milestone/13).
