### ISSUE TITLE
Etherpad keeps spamming to /ttl/[padname] after Apache2 Reverse Proxy Setup

### ISSUE THREAD

**Issue by Benjarobbi** [ether/etherpad-lite#3787]
Hi there,

just noticed that my Etherpad began to spam requests to /ttl/[padname] and got redirected to /p/ttl/[padname] with the Apache2 Reverse Proxy configuration described in the wiki.

After adding:
`RewriteCond %{REQUEST_URI} !/ttl/` to the Apache2 vHost used it began to work flawlessly. 

Could anyone confirm that? And if this behaviour also applies to their setup maybe change the wiki?
I'm too unfamiliar at the moment with Etherpad to make sure, that this isn't a problem just on my side, maybe because of a misconfiguration, or a mistake in the tutorial in general.

I'd appreciate your contribution & thank y'all for your efforts.

Best wishes,
Benjamin

**Comment by JohnMcLear** [comment]
what commands are you using to confirm the "spamming"

**Comment by Benjarobbi** [comment]
Checked the network analysis tab in Firefox (F12 and "Network analysis") and there I saw tons of requests to [mydomain]/p/ttl/[mypadname].

https://img.l1.si/27a72b1e-64f7-493a-a56c-f6c32ea9ad45.png <- that's what looks like when I'm not having this RewriteCond active.

**Comment by JohnMcLear** [comment]
Gimme your full apache config *with bits redacted:* so I can see if I can replicate.

**Comment by Benjarobbi** [comment]
There you go: https://img.l1.si/Smm9SwegtS9gWg35TzLyEgIX4HDmhckZ.conf
It's basically the one from your wiki - I hope I copied everything right.

**Comment by JohnMcLear** [comment]
I'm seeing no requests in Firefox attempting to hit /ttl -- 59 requests today when opening a new pad.



minify true and maxage 21600.




running in development mode (not production).







-----Original message-----

**Comment by Benjarobbi** [comment]
Did you remove the "RewriteCond %{REQUEST_URI} !/ttl/" I had added as a workaround?
As soon as I added it the problem had disappeared.
My maxage is set to 216000 and minify is also active.

**Comment by JohnMcLear** [comment]
Yes.  I commented it out, same, no requests with or without it ;\



-----Original message-----

**Comment by Benjarobbi** [comment]
Weird. I've just set up another instance (just cloned my local one) and deployed it to https://pad.katzencloud.de with the out commented "RewriteCond %{REQUEST_URI} !/ttl/".

There you'll see that the ace2_common.js is spamming a lot of requests.
Or is it just my client? I'm unsure.

**Comment by JohnMcLear** [comment]
I see it there..







-----Original message-----

**Comment by JohnMcLear** [comment]
Why am I seeing



Microsoft-IIS/6.0



in the header response? :D



-----Original message-----

**Comment by Benjarobbi** [comment]
That's just for fun purposes. My hoster did for a while unannounced security and port scans on their IPs. To troll them I've changed the Header of my Apache2 instance.

**Comment by JohnMcLear** [comment]
Try host etherdraw on the same rewrite, see if you get the same ttl spam.







-----Original message-----

**Comment by ldidry** [comment]
@Benjarobbi Do you use ep_delete_after_delay plugin?

**Comment by Benjarobbi** [comment]
Yes, I do. Could this be the issue?

**Comment by JohnMcLear** [comment]
Closing, good spot @ldidry 

https://github.com/ldidry/ep_delete_after_delay/blob/master/delete.js#L226
