### ISSUE TITLE
Delete pads and versions Etherpad-lite 1.8 and MySQL

### ISSUE THREAD

**Issue by FredMa01** [ether/etherpad-lite#3795]
I don't find any way to delete pads and versions of a pads with Mysql database. I test also with dirty DB.

1 -  With the plugin adminpads : the adminpads list is completly empty : Is it compatible with 1.8 ? 
adminpads doesn't seem to work with MySQL and dirty DB

2 - With node bin/deletePad.js test. I have in the logs : "Finished deleting padId: test" but the pad is still here.

Fred

**Comment by squiddle** [comment]
when using bin/deletePad.js the pad is still available due to etherpads internal caching (that is what i observed, not sure if true).

best for us was to delete via the API

**Comment by tom-chase** [comment]
I am having the same problem with the deletePad api.  Response says it was deleted and it is removed when I run listPads api; however, if I create a pad with the same name, I get the contents of the deleted pad.  I am also having problems getting the setText, setHTML, and copyPad to place the content into the pads.  I have 1.8 with mysql on debian with nginx for certbot.  I'm using jsonp to embed js and html in another website.  I can create, list and display pads fine through the api.  Only the spellcheck plugin is installed.  Thanks.
