### ISSUE TITLE
Microsoft Edge ignores cursor:pointer !important on links

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3803]
Upstream Edge bug.  @rhelmer can you report to MS plz I cba w/ the paperwork.

I tried setting it inline with HTML too, it's defo a browser bug.

It's prolly due to contentEditable

**Comment by rhelmer** [comment]
Hm. So my webcompat colleagues aren't aware of any public reporting mechanism outside of the feedback form in their UI:

![image](https://user-images.githubusercontent.com/61412/78942662-ff832f00-7a6e-11ea-96ca-21f154491b98.png)

I'll see if I can find anything else, and also a workaround for this.

**Comment by JohnMcLear** [comment]
Fixed upstream :)
