### ISSUE TITLE
If Etherpad is hosted on Windows OS Frontend test URI needs to be /tests/frontend/index.html (docs say .../frontend/)

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3804]
This page isn’t working127.0.0.1 redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

When visiting http://127.0.0.1:9001/tests/frontend/

Visiting http://127.0.0.1:9001/tests/frontend/index.html however does work.

**Comment by Gabrielpatrola** [comment]
Can you check this commit?
[c85543b](https://github.com/Gabrielpatrola/etherpad-lite/commit/c85543bfc251078e41f33e1386b1414ddb73224b )

**Comment by JohnMcLear** [comment]
Nicely done, have commented on the commit :)  

TLDR; Works but I think @muxator wont want formatting changes in the same commit as a bugfix...

Still, I think that file needed some polish so I'm +1 seeing some formatting changes.

**Comment by Gabrielpatrola** [comment]
How can I contact you or @muxator? I'm on the [GitPay](https://gitpay.me/#/task/325) task and and want to understand some things
