### ISSUE TITLE
Can't add or remove plugins since 1.8.0

### ISSUE THREAD

**Issue by maniackcrudelis** [ether/etherpad-lite#3810]
Hi

After an upgrade from 1.7.5 to 1.8.0, I can't deal with plugins anymore from the plugin manager into the admin panel.

Each time I try to add or remove a plugin I got that error message:
```
An error occurred while uninstalling the ep_activepads 
ENOENT: no such file or directory, rename '/var/www/etherpad_mypads/node_modules/.staging/ep_etherpad-lite-629fb491/node_modules/@babel/code-frame' -> '/var/www/etherpad_mypads/node_modules/.staging/@babel/code-frame-525bc192'
```
And that error into the log which says the same things
```
{ [Error: ENOENT: no such file or directory, rename '/var/www/etherpad_mypads/node_modules/.staging/ep_etherpad-lite-629fb491/node_modules/@babel/code-frame' -> '/var/www/etherpad_mypads/node_modules/.staging/@babel/code-frame-525bc192']
  cause:
   { Error: ENOENT: no such file or directory, rename '/var/www/etherpad_mypads/node_modules/.staging/ep_etherpad-lite-629fb491/node_modules/@babel/code-frame' -> '/var/www/etherpad_mypads/node_modules/.staging/@babel/code-frame-525bc192'
     errno: -2,
     code: 'ENOENT',
     syscall: 'rename',
     path:
      '/var/www/etherpad_mypads/node_modules/.staging/ep_etherpad-lite-629fb491/node_modules/@babel/code-frame',
     dest:
      '/var/www/etherpad_mypads/node_modules/.staging/@babel/code-frame-525bc192' },
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path:
   '/var/www/etherpad_mypads/node_modules/.staging/ep_etherpad-lite-629fb491/node_modules/@babel/code-frame',
  dest:
   '/var/www/etherpad_mypads/node_modules/.staging/@babel/code-frame-525bc192' }
Error: ENOENT: no such file or directory, rename '/var/www/etherpad_mypads/node_modules/.staging/ep_etherpad-lite-629fb491/node_modules/@babel/code-frame' -> '/var/www/etherpad_mypads/node_modules/.staging/@babel/code-frame-525bc192'
```

And indeed, the plugin activepads is still there.

I do not have this directory `node_modules/.staging`, but if I add it, I have the same error and the directory is removed.

**Comment by JohnMcLear** [comment]
Will test this now

**Comment by JohnMcLear** [comment]
Works fine for me on latest develop.

**Comment by maniackcrudelis** [comment]
First it appears that it didn't happen with a fresh install of 1.8.0, only with the upgrade from 1.7.5 to 1.8.0.

From the same fresh installed 1.8.0 to the last develop, still working.
From 1.7.5 directly to last develop, broken.
Finally, 1.7.5 to 1.8.0, doesn't work. The same instance updated to last develop, still broken...

It's important to notice that the last test end up with a broken instance with errors about corrupted tarball. And errors abour .staging not existing.

My guess is that the upgrade from 1.7.5 to upper version does not work properly for some reason.
Is there any migration to do ?

**Comment by JohnMcLear** [comment]
The migration path is  `` git pull && bin/run.sh``

It sounds like something is going wrong and I doubt you are using git..

So I'd be tempted to copy your ``settings.json`` and ``var/dirty.db`` (if you are using dirty) over to a clean 1.8 install, then install the plugins you want from there :)

**Comment by maniackcrudelis** [comment]
I indeed don't git pull to install, I use the release 1.8.0 tarball.
Same for the upgrade.
To just git pull would give me the current develop branch. I don't feel like it would be safe for a normal user.

I do not use dirty but a mysql database.
I can't just start over my installation as it's not just mine, but the installation of many different users. Currently on 1.7.5

There nothing in bin/run.sh (or bin/installDeps.sh) that could explain that error.
Is there another log or anything I could do to grab more information about what's going wrong ?

**Comment by JohnMcLear** [comment]
Okay so that's super easy, just copy/paste the ``settings.json`` from old to new.  All data will remain in MySQL untouched.

**Comment by maniackcrudelis** [comment]
> I can't just start over my installation as it's not just mine, but the installation of many different users. Currently on 1.7.5

It's not just me.
I can handle a new installation on my own, but that isn't for me. (I didn't actually moved to 1.8.0 myself)
My concern here is to find what breaks during that upgrade so I can fix it and safely let all my users upgrade to 1.8.0

**Comment by JohnMcLear** [comment]
I can't help if you can't make the changes I propose so we can isolate he issue.

**Comment by JohnMcLear** [comment]
If others have this issue I'm happy to reopen!

**Comment by maniackcrudelis** [comment]
But I told you that if I install a new 1.8.0, it works, my issue is with the upgrade from 1.7.5 to 1.8.0
Of course If I do install 1.8.0 and move the settings json it will work.

> If others have this issue I'm happy to reopen!

An hundred users or more !
Told you it's not just for me.
I have this issue with the installation for YunoHost, which represent at least a hundred users (for etherpad)

I can't consider using git pull, knowing that I may have problems solvable with some work.
I have to provide a solution out of the box for all my users. That's why I try to solve that issue !

**Comment by maniackcrudelis** [comment]
Thanks for the support...
Next time I have an issue with your app, I won't forget to not ask...

For those who have that issue, apparently to remove `src/package-lock.json` solve the problem.

**Comment by JohnMcLear** [comment]
@maniackcrudelis I suggest you read back through this thread.  

I provided debug steps to isolate the problem, you refused to do them.  We provide free software and free support, saying "Next time I have an issue with your app, I won't forget to not ask..." is not how I expect people in our community to behave when we have tried our best to help you.

It sounds like when you used the tarball it didn't overwrite your ``src/package-lock.json`` and that's expected behavior.   Look at the docs, they clearly state how to install and maintain a site.  You took a route (of using the tarball) which may seem sane/sensible but has this exact caveat where the update route is somewhat different.  

You will notice that https://github.com/ether/etherpad-lite/blob/develop/src/package-lock.json is included in the develop branch so if you followed the docs you wouldn't of had this problem.

So please, follow the docs, be polite and let us try to help you.  Gracias!
