### ISSUE TITLE
When changing package.json, please also update package-lock.json

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3814]
@JohnMcLear, commit 4db91cb2ed1a (done recently on master) updated  `package.json`, but missed the corresponding update to `package-lock.json`.

If we do not do this, we could potentially brak some installations / make things inconsistent among environments.

For reference, the changes on OpenAPI (#3786) we are about to merge respect this: each time there is a modification in `package.json`, there is the corresponding modification in `package-lock.json`.

**Comment by JohnMcLear** [comment]
Done
