### ISSUE TITLE
http-parser update broke etherpad

### ISSUE THREAD

**Issue by rgarrigue** [ether/etherpad-lite#3815]
Hi there

We're running a SoftwareFactory, a packaging of OpenStack Zuul including an etherpad. On CentOS 7 64. A `yum update` this morning broke etherpad : we had empty reply from the NodeJS process itself. It did work without HTTP header (like using netcat only). Looking at the update log, we tried downgrading http-parser. Then etherpad service restart. It fixed the issue.

Here are the versions

- CentOS Linux release 7.7.1908 (Core)
- node: v8.9.4
- etherpad: 1.7.5 

http-parser: 
- The broken version : http-parser-2.7.1-8.el7_7.2.x86_64 
- The functional version after downgrade : http-parser-2.7.1-8.el7.x86_64

**Comment by JohnMcLear** [comment]
Do you have this problem on the latest version of Etherpad?  Feels weird you would open an issue for an old version without testing a modern release?

**Comment by muxator** [comment]
What is `http-parser` used for?

The only hard dependency Etherpad has is a working nodejs. All the dependencies are installed as `node_modules` when running `bin/installDeps.sh`.

**Comment by rgarrigue** [comment]
Most likely the packaging by CentOS and/or Software Factory is in cause. I don't want to hijack that to run another version of etherpad / node / http-parser. I just though I'ld signal the issue  and my workaround just in case for other people to hit some result when searching. Guess I'll close the issue, sorry for the trouble.

**Comment by JohnMcLear** [comment]
Ah yea I maintain a bunch of CentOS boxes and it's not much fun especially deploying abiword.  To be fair to the CentOS guys, if you run a relatively modern setup (modern nodejs/systemctl,soffice) it's really stable and works great.  I kinda like the way it forces you to use modern stuff in that way.  Thanks for posting your issue and keeping us in the loop :)
