### ISSUE TITLE
sessionID cookie enveloped in quotes is not parsed properly

### ISSUE THREAD

**Issue by MarcinCieslak** [ether/etherpad-lite#3819]
Some servers, like WildFly 11, surround cookie value in double quotes.  It depends on cookie value characters and cookie version. Here is some background
https://issues.redhat.com/browse/UNDERTOW-1096
Etherpad SecurityManager expects sessionID cookie value without quotes. If quotes are present, they are considered a part of session ID, resulting in "session not found" error.

**Comment by JohnMcLear** [comment]
lulwut!  This is amazing.

**Comment by muxator** [comment]
I think this is a bug in Etherpad cookie parsing logic.

I have merged #3820 (df08883a009aeaebfbe59a53c592ac25cd3aff06), which is a fix, but I think the the problem still remains deep down.

For documentation's sake, this is my comment to the issue (and the remediation):

> Sometimes, [RFC 6265](https://tools.ietf.org/html/rfc6265)-compliant web servers may send back a cookie whose value is enclosed in double quotes, such as:
>
> ```
> Set-Cookie: sessionCookie="s.37cf5299fbf981e14121fba3a588c02b,s.2b21517bf50729d8130ab85736a11346"; Version=1; Path=/; Domain=localhost; Discard
> ```
>
> Where the double quotes at the start and the end of the header value are just delimiters. This is perfectly legal: **Etherpad parsing logic should cope with that**, and remove the quotes early in the request phase.
>
> Somehow, this does not happen, and in such cases the actual value that `sessionCookie` ends up having is:
>
> ```
> sessionCookie = '"s.37cf5299fbf981e14121fba3a588c02b,s.2b21517bf50729d8130ab85736a11346"'
> ```
>
> As quick measure, let's strip the double quotes (when present).
> Note that here we are being minimal, limiting ourselves to just removing quotes at the start and the end of the string.
