### ISSUE TITLE
Comments not exported

### ISSUE THREAD

**Issue by pescepalla** [ether/etherpad-lite#3821]
The export function generates a file with the main text, but without comments.

This is the same issue as https://github.com/ether/ep_comments/issues/102 but related to Etherpad Lite. I've reported it here also because the bug is still active now after having been reported in 2016.

**Comment by JohnMcLear** [comment]
Refer to the issue on the plugin please, thanks for the bump tho 👯‍♂

**Comment by nekohayo** [comment]
In case anyone stumbles upon this like me: I filed https://github.com/ether/ep_comments_page/issues/190 specifically about exporting to ODT and PDF, as I surprisingly couldn't find any issue about that (the one mentioned above seems to be about preserving comments when migrating from one etherpad instance to another?). I hope that's the right place.
