### ISSUE TITLE
set a pad to a certain revision via api

### ISSUE THREAD

**Issue by dora71** [ether/etherpad-lite#383]
This is a feature request:
It would be great to be able (as admin) to set a certain pad back to a certain revision via http api. So the users will see only that revision as the latest. Later modifications can be deleted.
This would be a great thing against abuse or unwanted deletion.

**Comment by JohnMcLear** [comment]
Bounty for this: https://www.bountysource.com/issues/1371945-set-a-pad-to-a-certain-revision-via-api

**Comment by BlastDanger** [comment]
+1 - Any plans to update Etherpad to be able to revert to a version in the timeline?
