### ISSUE TITLE
How can you target to run only one backend test?

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3836]
Tests are run with
``cd src && npm run test``

But how do you target one test IE ``cd src && npm run test chat.js``

**Comment by anttiviljami** [comment]
```
npx mocha tests/backend/specs/api/chat.js
```

**Comment by anttiviljami** [comment]
Or just `mocha [file]` if you have mocha installed globally.

**Comment by JohnMcLear** [comment]
Woop awesome thanks :D!!!
