### ISSUE TITLE
Plugin manager empty

### ISSUE THREAD

**Issue by julianmiguel** [ether/etherpad-lite#3840]
Hello
I just install a fresh Etherpad lite, everything is working well but my plugin manager is emty
It seem like i cannot view any plugin inside

It is very strange because when i use the search fied it's seems like its looking for something

Can you help me ?
<img width="1148" alt="Capture d’écran 2020-04-06 à 17 16 25" src="https://user-images.githubusercontent.com/63249082/78574633-8dbaa380-782a-11ea-9b8e-31c101e6bd70.png">

**Comment by julianmiguel** [comment]
OK sorry i found the solution, I launch etherpad as root
thanks

**Comment by Gared** [comment]
Good to hear. If you have other issues with the plugin manager. Let us know
