### ISSUE TITLE
Feature Request: case-insensitive pad names

### ISSUE THREAD

**Issue by fwolfst** [ether/etherpad-lite#3844]
It would be great if a setting would **allow the use of case-insensitive pad names** (`overview` -> `oVErvieW`). Having etherpad deployed in a German environment where nouns are written capitalized, this lead to some confusion of users (some capitalize the pad name, others dont).

Currently, i work around that with some nasty nginx-rule (because not all request should be lowercased, some javascript assets use capital letters).

I am not a JavaScript-person and do not know the EP codebase but would assume that this is a rather low-hanging fruit (but then I don't know if the code is structured such that plugins etc just use the API which would respect the lowercase-setting).

Probably related:
https://github.com/ether/etherpad-lite/issues/2557

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/blob/develop/src/node/db/PadManager.js#L181 Afaik

**Comment by fwolfst** [comment]
Previous comment pointed out: https://github.com/ether/etherpad-lite/blob/79406051fa6610690f7c5ae1d6a0c79dc37f8a78/src/node/db/PadManager.js#L78 as a place to look at.
You mean I would need case **insensitive** database, right?
I have seen that actually some people did use a mysql-feature to do that.

My wish would be that I can tell etherpad that case does **not** matter.

> http://video.etherpad.com/p/blah
> https://video.etherpad.com/p/blaH

Exactly. Thats my problem!

**Comment by JohnMcLear** [comment]
Yes, make your database key case insensitive.

**Or** just add ``.toLower()`` on a pad Id anywhere in ``hooks/express/padurlsanitize.js``.  

I'm not sure I'm gonna write code/test coverage etc. for it tho!  I can re-open and if enough people want it I will do it.

That's defo a weird feature request!  Users are weird 💃

**Comment by fwolfst** [comment]
Yes users are weird :)

otoh its not such a weird expectancy that URLs are handled case-insensitive
... like hTTPs://EtHeRPAd.oRG should work fine. Yep, I know why, but tell
this an ordinary user. Also, the etherpad blog does not care about
capitalization (
https://blog.etherpad.org/2020/03/17/Video-CHAT-with-etHErpAd/). I don't
want to argue, but its not uncommon that URLs are treated as-if
case-insentitive (same for email-adresses). Did somebody ever tell you the
case of a letter when telling you a domain or an URL?

**Comment by DanielHabenicht** [comment]
I would greatly support this being implemented. 
For me there is no reason to allow case sensitive rooms: What's the benefit? 
On the Con Side users are confused and it may not work with other systems that are case insensitive (e.g. Jitsi)

**Comment by DanielHabenicht** [comment]
Also as of today, there is no way to make it case-insentive anymore. `ueberDB` forces binary encoding which is case sensitive: 
https://github.com/ether/ueberDB/blob/7bef202597018bb2966f9f1fd00931760eb6b979/databases/mysql_db.js#L58-L62

I can add a Pull Request for adding a settings to make it case insensitive, if thats alright? @JohnMcLear

**Comment by DanielHabenicht** [comment]
I have a pr ready so we can get it fixed!
