### ISSUE TITLE
Importing documents into pad fails.

### ISSUE THREAD

**Issue by doodlebug70** [ether/etherpad-lite#3845]
**System Settings:**
- Debian 10
- Node v11.15.0
- abiword 3.0.2-8

**Plugins**
- align
- hash_auth
- tables2
- tasklist 
- timestamp

**Etherpad-lite**
```
$ git log -1
commit 79406051fa6610690f7c5ae1d6a0c79dc37f8a78 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Paul Tiedtke <PaulTiedtke@web.de>
Date:   Fri Mar 27 06:33:39 2020 +0100
```

**Issue**

When importing a document into etherpad it fails.   

steps taken

- open a pad
- click the import button
- click browse and select document (tried, txt, odt, html)
- click import now  (only shows "import no" on button)

the pad reloads but the document is not in the pad.    The tables menu and the show users button are expanded

In the logs I see the following after import attempt

```
[WARN] ImportHtml - HTML was not properly formed { inspect: [Function: inspect] }
[WARN] ImportHandler - Error importing, possibly caused by malformed HTML
```

**Note**
Exporting is working as expected

**Comment by JohnMcLear** [comment]
Thanks for this report (it's a good one!), can you confirm if the problem exists with the plugins removed?

**Comment by doodlebug70** [comment]
Yes removing all plugins seem to get it working again.  but some quirks

- I initially removed all but `hash_auth` and it started working. 
- I went to re-add one by one the ones I removed, starting with `align`.  It broke again
- I removed `align`, leaving just `hash_auth` and it was still broken.
- I had to remove `hash_auth` to get it working again,  leaving me with no plugins

**Comment by JohnMcLear** [comment]
FWIW I just tested importing with a plugin installed (``ep_spellcheck``) and it didn't break import.  Will try ep_align now

**Comment by JohnMcLear** [comment]
Nope, import still works..  Will try with abiword instead of soffice

**Comment by kamleshmanek** [comment]
can anybody please guide me for this [issue](https://github.com/ether/etherpad-lite/issues/3847)?

**Comment by doodlebug70** [comment]
@JohnMcLear hmm  I had tried with both existing pads and new ones yesterday and it was causing problems, even after removing all plugins, though usually restarting the service helped get import working.  Restarting service was done as uninstalling and installing plugins were taking at least two attempts before it worked.

today, not touching the back-end, re-adding some plugins and it seems to be behaving with importing to both new and existing pads that had problems yesterday

**Comment by JohnMcLear** [comment]
Great, if you run into problems with this again please do let us know.
