### ISSUE TITLE
Etherpad for react native

### ISSUE THREAD

**Issue by kamleshmanek** [ether/etherpad-lite#3847]
Hello All,

Hope you are doing well!
I want to implement Etherpad in my react native app without using webview. Is it possible for react native with customise view of Editor and Chat box for mobile app? I have checked for SDK/Library for react native but there are not available. So please guide me to implement Etherpad for react native app.

Thank you

**Comment by JohnMcLear** [comment]
Yes it's possible but you will need to do some work.

We don't support any specific framework, be it cordova, angular, react etc.  You will have to implement it yourself.  There are too many and the gravy train moves so quick we decided not to try to follow it.

It will mean looking through the client side code and implementing it within react.  It will also mean changing some of the client side delivery logic.  Etherpad delivers files upon request, and the client javascript is specific for a pad, the server and client are explicitly bonded so we can deliver a client side experience that matches what the server expects.

Take a look through the connectivity logic, read through the wiki.  I'd estimate about 1 week full time work for an MVP with significant breaking changes to existing installs.

If you make a react native implementation then come back to us, we'd love to see it :)
