### ISSUE TITLE
send last-modified-header for export files

### ISSUE THREAD

**Issue by ezzra** [ether/etherpad-lite#3853]
for the export file links like https://pad.example.org/p/test/export/txt it would be good, if the server could send a last-modified-header, or is there any other good way to check programmatically (from external) the latest update time?

**Comment by JohnMcLear** [comment]
See:

https://etherpad.org/doc/v1.7.0/#index_getlastedited_padid

getLastEdited(padID)
#

    API >= 1

returns the timestamp of the last revision of the pad 

```
jose@server:~/etherpad-lite/src/node/db$ grep -rni lastEdited .
./API.js:461:getLastEdited(padID) returns the timestamp of the last revision of the pad
./API.js:465:{code: 0, message:"ok", data: {lastEdited: 1340815946602}}
./API.js:468:exports.getLastEdited = async function(padID)
./API.js:472:  let lastEdited = await pad.getLastEdit();
./API.js:473:  return { lastEdited };
```

so 

```
pad.getLastEdit();
```
would do it, just include that as a header in the export (I'd cover all exports not just HTML).  It's really easy to do this.  I'd be +1 seeing it as a PR.

**Comment by ezzra** [comment]
>  I'd be +1 seeing it as a PR.

me too :) Because I would like to have that available on other etherpad instances

**Comment by ezzra** [comment]
by the way, I found a workaround if its useful to anyone else. You can just check the content-length header of the json export (export/etherpad), if that changes between two requests, something happened in the history.

**Comment by JohnMcLear** [comment]
@ezzra yea that's always a safe way to do it.  An .etherpad file will always grow (after 10 revisions afaik).  The only exception is if someone imports a rev0 ``.etherpad`` file to a pad with < 10 revisions.  Super edge case but worth being mindful of.

**Comment by ezzra** [comment]
why only after 10 revisions? Because changes are always appended, the content-length changes with every revision (and because its in the header, you just need to make a cheap head request without loading the etherpad file which can become quite large)

**Comment by JohnMcLear** [comment]
@ezzra That's the logic I wrote, to stop .etherpad files getting written over pads which have activity.  The logic is that an .etherpad file can always be imported into a new pad.  The reasoning is for legal / auditing so an .etherpad is always a ~~~100% true representation of a pad.
