### ISSUE TITLE
Please take care of the documentation part, or at least drop two lines here.

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3858]
Please take care of the documentation part, or at least drop two lines here.

_Originally posted by @muxator in https://github.com/ether/etherpad-lite/pull/3833_

**Comment by muxator** [comment]
Let me try to write down some points to help our memory:

1. find a place in the documentation in which the newly introduced rate limiting may be mentioned
2. help describe the effect of `requireAuthorSessionToImport` in `settings.json.template`. For example look at this change: https://github.com/ether/etherpad-lite/commit/9847bf67ff0ff24e87131833004a8e2e050c020d#diff-8ab11a170627f11a32a1d642d7114743R412-R417 where I grouped all the relevant changes
3. find a place in the documentation where we can mention `requireAuthorSessionToImport`. Does it apply only to the web interface or to the API calls too?
4. we have to decide if `requireAuthorSessionToImport` will be true for old installs that upgrade, and eventually mention this in the CHANGELOG
5. do we have to mention `importMaxFileSize` somewhere?

**Comment by JohnMcLear** [comment]
3. Web only.  does NOT apply to API. 
4. IMHO absolutely yes.
5. It's mentioned in the docs.  I guess if we hit the limit we could warn to logs / notify user?  I can't remember what I implemented.

**Comment by JohnMcLear** [comment]
3. done

**Comment by JohnMcLear** [comment]
5. we currently don't pass "reason" for upload failure, not sure I want to bring that logic in right now.

**Comment by muxator** [comment]
I say we can close this, all the points were addressed in the discussion in #3833 and force-pushing there.
