### ISSUE TITLE
Only one way to access to your etherpad - https + domain (say NO to IP address) and without 9001 port at the end (NGINX version)

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3862]
I hope it will be helping someone. I spent a couple of days resolving this task.

**nginx.conf**

```
server {
    listen 443 ssl;
    
    server_name spexfy.xyz;
    
    if ($host !~* "^spexfy\.xyz$") {
    	return 444;
    }
    
    location / {
    	# proxy headers and other options
    	proxy_pass http://127.0.0.1:9001/;
    }
    
    ssl_certificate /home/spexfy/ssl.combined;
    ssl_certificate_key /home/spexfy/ssl.key;
}
```
In the block "server" added condition that helped me close access as I needed.

**credentials.json**
```
{
  "ip": "127.0.0.1"
}
```
Yes, yes, it is necessary to assign such an IP address instead of 0.0.0.0, otherwise, access via the IP through the browser will still be open. I checked many options, only this one gave the desired result.

<img width="286" alt="Screenshot at Apr 13 17-55-19" src="https://user-images.githubusercontent.com/25965602/79130806-4004e480-7db0-11ea-8df6-e2c9e083ed7f.png">
If I'm wrong about something or you want to add something, I'm ready to listen.

**Comment by muxator** [comment]
@alekso87, I think you may want to review how server **socket binding** works.

This is not Etherpad related at all, it's just how every TCP server works on every platform. If you bind on `0.0.0.0`, the process will accept connections from everywhere. If you bind on a specific address (== the address of one of the IP interfaces of your server), the process will only accept connections arriving to that interface. In that regard, `127.0.0.1` is only a special interface you are guaranteed to have, and it will only accept connections coming from co-located processes (== processes that are being executed on the same host).

For a quick reference, have a look at [this superuser.com question](https://superuser.com/questions/949428/whats-the-difference-between-127-0-0-1-and-0-0-0-0), but for a more disciplined approach I would advise to take a good book, for example [Kurose-Ross, Computer Networking A Top-Down Approach](https://eclass.teicrete.gr/modules/document/file.php/TP326/%CE%98%CE%B5%CF%89%CF%81%CE%AF%CE%B1%20(Lectures)/Computer_Networking_A_Top-Down_Approach.pdf).
