### ISSUE TITLE
Latest develop import

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3864]
I'm gonna do some polish on this today.

- [x] import errors should bubble up to user.  
  - [x]  Max file size
  - [x] User has to contribute to pad before uploading -- Ideally just being present on a pad should be enough.

- [x] using lenient-import branch - PDF imports are not being properly decoded <-- I didn't have ``soffice or abiword`` set.
- [x] .Doc imports are not being properly decoded <-- I didn't have ``soffice or abiword`` set.
- [x] This page needs updating: https://github.com/ether/etherpad-lite/wiki/How-to-enable-importing-and-exporting-different-file-formats-with-AbiWord-or-LibreOffice
- [x] Need to test the whole UTF8 logic / issue, https://github.com/ether/etherpad-lite/issues/3019

**Comment by muxator** [comment]
Fine, I was thinking, indeed, about opening an issue about these UI polishings that need to be done now that the import has been reworked.

The black of feedback on failed import was indeed evident yesterday while testing. Thanks!

**Comment by JohnMcLear** [comment]
```
  "pad.importExport.importUnsuccessful.maxFileSize": "Import Failed, file size too big, contact your site admin to increase file size",
  "pad.importExport.importUnsuccessful.permission": "Import Failed, please contribute to the pad and try again!",
```

These should do it.

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/pull/3865

**Comment by JohnMcLear** [comment]
I am just going to hide import functionality until their has been a contribution from that user.  Hide and say "you need to contribute to the pad prior to importing."  That seems logical.

**Comment by JohnMcLear** [comment]
Okay PR is in, please review.

**Comment by JohnMcLear** [comment]
Closing as this is all merged.
