### ISSUE TITLE
Console & Network errors in watching the pad

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3866]
Hi everyone! As soon as I created a new pad, I see the following picture. What could it be?

Server Ubuntu 18.04.4 LTS
Nodejs 12.16.2 LTS
Nginx

Etherpad - develop branch, up to date

Console log

<img width="1438" alt="console" src="https://user-images.githubusercontent.com/25965602/79241668-04cfe780-7e7c-11ea-8fb5-89a5585b1673.png">

Network log

<img width="1439" alt="network" src="https://user-images.githubusercontent.com/25965602/79241698-11544000-7e7c-11ea-9ace-75ecd2eb29a3.png">

Etherpad log

<img width="1439" alt="etherpad" src="https://user-images.githubusercontent.com/25965602/79243348-2df17780-7e7e-11ea-86f4-e0dd7860d8c8.png">

Nginx.conf
```
server {
    server_name spexfy.xyz;
    
    listen 443 ssl;
    
    access_log /var/log/virtualmin/spexfy.xyz_access_log;
    error_log /var/log/virtualmin/spexfy.xyz_error_log;
    
    if ($host !~* "^spexfy\.xyz$") {
    	return 444;
    }
    
    location / {
    	# proxy headers and other options
    	proxy_pass http://127.0.0.1:9001/;
    }
    
    ssl_certificate /home/spexfy/ssl.combined;
    ssl_certificate_key /home/spexfy/ssl.key;
}
```

**Comment by JohnMcLear** [comment]
Your nginx config is wrong.  https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy
