### ISSUE TITLE
What if client lose NEW_CHANGES or ACCEPT_COMMIT message?

### ISSUE THREAD

**Issue by opriz** [ether/etherpad-lite#3872]
On the server side , server send messages and update session rev directly:
```
if (author == sessioninfos[sid].author) {
        client.json.send({ "type": "COLLABROOM", "data":{ type: "ACCEPT_COMMIT", newRev: r }});
      } else {
        let forWire = Changeset.prepareForWire(revChangeset, pad.pool);
        let wireMsg = {"type": "COLLABROOM",
                       "data": { type:"NEW_CHANGES",
                                 newRev:r,
                                 changeset: forWire.translated,
                                 apool: forWire.pool,
                                 author: author,
                                 currentTime: currentTime,
                                 timeDelta: currentTime - sessioninfos[sid].time
                               }};

        client.json.send(wireMsg);
      }

      if (sessioninfos[sid]) {
        sessioninfos[sid].time = currentTime;
        sessioninfos[sid].rev = r;
      }
```

What if client missed one of these messages? In my comperhension, since clients always only apply rev+1, once missed one message, client may stuck forever.

client side:
```
if (newRev != (rev + 1))
      {
        window.console.warn("bad message revision on NEW_CHANGES: " + newRev + " not " + (rev + 1));
        // setChannelState("DISCONNECTED", "badmessage_newchanges");
        return;
      }
```

**Comment by JohnMcLear** [comment]
Doesn't the client check that the rev is in sequence?  IE

Client has 1,2,3,4 then gets 6, it will say, nope.  That's not right and wont apply that changeset.

**Comment by opriz** [comment]
@JohnMcLear  
I meant this kind of circumstance:
Server has 1,2,3,4,5  Client has 1,2,3 then client submits 4 which server applies as 6, then server should send 5,6(accept) to client. But if the 5 was lost, 6 will be reject.However server thinks 5,6 are all sent successfully as I see the code it just update `sessioninfos[sid].rev` directly. Then server will only send 7,8... which will all be reject by client which is waiting for 5 forever.
Did I missed something? Thanks.

**Comment by JohnMcLear** [comment]
To be honest, I can't remember..  If you are going through a write up of the functionality in the wiki would be awesome.  I just did one for attributes: https://github.com/ether/etherpad-lite/wiki/How-does-Etherpad-go-from-a-Pad-to-other-formats-and-vice-versa.

Something similar to that for revisions would be useful

**Comment by opriz** [comment]
That's great if I can make my contribution. 
I'm figuring out how etherpad works. And I'm wondering how this circumstance been handled or here may have a logical problem? 
Once I get the point, I'd love to add to wiki.

**Comment by JohnMcLear** [comment]
Track at #4040
