### ISSUE TITLE
Remove the name of the pad from the title

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3876]
Hi everybody!

Is it necessary to see the name of the pad in the title? The character set does not decorate the title. I think it's more important to see the name of the project there right away than to push this project name to the background.

<img width="260" alt="Screenshot at Apr 17 16-13-05" src="https://user-images.githubusercontent.com/25965602/79574048-3e952e00-80c8-11ea-95aa-64f5f9876e6c.png">

**Comment by JohnMcLear** [comment]
Plugins exist to solve this problem.

Go to the /admin/plugins page and search for title

Or look here: https://static.etherpad.org/plugins.html

**Comment by alekso87** [comment]
@JohnMcLear Thanks. Just do not understand why to do this a separate plugin, if it can be fixed globally. I do not see any use in the title of the pad in the title.

**Comment by JohnMcLear** [comment]
@alekso87 because you can visit /p/whatever and it will make the title whatever.

http://video.etherpad.com/p/whatever for example

It is incredibly useful when you bookmark etc.  You don't have to use the newpad endpoint..  Also on index.html you can set padId..
