### ISSUE TITLE
Sending out notifications upon change

### ISSUE THREAD

**Issue by marek-j** [ether/etherpad-lite#388]
It would be great, to have etherpad-lite send out notifications to the authors once a (in time/once an hour/day/month) whenever a pad changes.

**Comment by marsjaninzmarsa** [comment]
Wiki link outdated, [more proper](https://github.com/ether/etherpad-lite/wiki/Plugin-Wishlist), [following request](http://etherpad.idea.informer.com/proj/?ia=67108) and [one of implementations](https://github.com/JohnMcLear/ep_rss).
