### ISSUE TITLE
Error: Couldn't find translations for ru-RU

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3882]
Hi everyone!

<img width="597" alt="Screenshot at Apr 18 17-58-48" src="https://user-images.githubusercontent.com/25965602/79641202-acac2480-819e-11ea-8d4e-e80ee44fc667.png">

**Comment by JohnMcLear** [comment]
![image](https://user-images.githubusercontent.com/220864/79669576-6366cf80-81b4-11ea-8cd9-f29c112b9114.png)

**Comment by JohnMcLear** [comment]
file name is ``ru.json``

**Comment by JohnMcLear** [comment]
Possibly related to https://github.com/ether/etherpad-lite/issues/3404 ?

**Comment by alekso87** [comment]
Browser - Chrome
Browser language - Russian
HTTP_ACCEPT_LANGUAGE - ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7

and

<img width="1105" alt="Screenshot at Apr 18 22-49-01" src="https://user-images.githubusercontent.com/25965602/79669842-51daf300-81c7-11ea-9961-f1596b93180f.png">

**Comment by alekso87** [comment]
Browser - Firefox
Browser language - English
HTTP_ACCEPT_LANGUAGE - en,de;q=0.7,en-US;q=0.3

all is ok

**Comment by JohnMcLear** [comment]
Yea, I mentioned that if ru-RU file is not available it should always fall back to ``language.substring(0,1)``, it's an easy fix I have put someone on it.

**Comment by iquidus** [comment]
Having some trouble reproducing this. 

Related: https://github.com/ether/etherpad-lite/blob/develop/src/static/js/html10n.js#L186

**Comment by JohnMcLear** [comment]
hrm, the OP is another dev so you could just push back to him to add some debug/logging.



He seems to know how to do basic stuff so prolly fine to push back to him.



It might be that we are sending the error but actually handling it gracefully?







-----Original message-----

**Comment by iquidus** [comment]
ok, i am able to replicate in firefox using ru-MD on the home page. The issue appears to go a little deeper than originally thought. ru-RU -> ru is being handled correctly as is (by line 186 linked above). However its then getting set back to en by this line here

https://github.com/ether/etherpad-lite/blob/develop/src/static/js/l10n.js#L7

studying further.
