### ISSUE TITLE
Wrong url address when I use read only mode

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3883]
Hi everyone! I use this config https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#hosted-at--with-friendly-urls-for-pads, a little modified for myself.
![33](https://user-images.githubusercontent.com/25965602/79641711-e3376e80-81a1-11ea-9172-62076eed092a.gif)

**Comment by JohnMcLear** [comment]
Works fine here: https://video.etherpad.com/p/testreadonlyURI

Possibly a setting?

Video.etherpad.com is running nginx reverse proxy too..

**Comment by alekso87** [comment]
@JohnMcLear I see, but i use settings without /p/

**Comment by JohnMcLear** [comment]
Afaik the read only URI is computed based on the location of ``/p/``, I think you would need to look at the logic around that and compute it from a setting or so?  Are you hoping to hack on some of this stuff or just making issues for now?

I just don't want them to go into a black hole because I wouldn't consider this a bug but a quirk of your specific deployment so for core devs it's gonna be low down on the priority list -_-  We don't like having open bugs though!

**Comment by alekso87** [comment]
> Are you hoping to hack on some of this stuff or just making issues for now?
I followed the instructions from your wiki. I like this setting, where there are no extra parameters in the url.

I showed that with this configuration and the inclusion of "read-only", the URL breaks and there is no mention of a domain.

> We don't like having open bugs though!
And who loves bugs?

**Comment by muxator** [comment]
@alekso87, I am sure there is some quirk somewhere in the code.

If possible, try to find it, and send a PR.

If it takes too much time, or happens to be too difficult, please [update the wiki page](https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#hosted-at--with-friendly-urls-for-pads) mentioning the problem you just found. At least this would not be surprising anymore.

That would be helpful and really appreciated. Thank you.

**Comment by alekso87** [comment]
@muxator what PR can be used for this fix?

**Comment by JohnMcLear** [comment]
I think what @muxator id saying is that you will need to create a pr to address this bug.

**Comment by JohnMcLear** [comment]
Nice job on getting a PR in!  We will review ASAP.  We're currently in release mode so give us a few days to get this release out please <3

**Comment by alekso87** [comment]
@JohnMcLear I have not yet worked in fork mode, so in the first PR I added too many commits :( Now I want to work out a scheme for myself in which I will not push extra commits into the PR.

**Comment by JohnMcLear** [comment]
@alekso87 I feel your pain.  Git can be a fickle mistress.

**Comment by alekso87** [comment]
@JohnMcLear @muxator Can i close current PR and open a new from another branch? I again added an unnecessary commit :( I needed to do PR from the branch. Sorry
