### ISSUE TITLE
etherpad-lite 1.8.0 (48b0290) and Safari wrong display 

### ISSUE THREAD

**Issue by lweingart** [ether/etherpad-lite#3900]
Hi,

I have recently installed etherpad-lite and this is how it looks like on Safari 13.1 macOS 10.15.4

<img width="1920" alt="Screenshot 2020-04-19 at 16 01 15" src="https://user-images.githubusercontent.com/4840059/79691845-0a557500-8262-11ea-8a17-fd8099e40e51.png">

Although the content of the file is very long, it remains in a very small part of the screen with a scroll bar appearing on the right.
I don't have this issue with Chrome, nor with Firefox.

Tell me if you need any additional information

Cheers

**Comment by JohnMcLear** [comment]
Try on https://video.etherpad.com - do you get the same thing?  cc @seballot

**Comment by lweingart** [comment]
Hi,
I tried on the link you gave me and created a pad, and yes, I get the same thing unfortunately

Result on Safari:
<img width="1920" alt="Screenshot 2020-04-19 at 20 03 23" src="https://user-images.githubusercontent.com/4840059/79695763-f5381080-8278-11ea-9f5f-5c2ae31fc554.png">

Result on Firefox:
<img width="1920" alt="Screenshot 2020-04-19 at 20 04 59" src="https://user-images.githubusercontent.com/4840059/79695799-1ef13780-8279-11ea-96ed-e23e3c3fad39.png">

**Comment by JohnMcLear** [comment]
Bollocks.  Hopefully @seballot can get to this ASAP.  Our automated Safari test runner isn't working so that doesn't help ;\

**Comment by seballot** [comment]
Arf, I'm on linux, no way to test that myself (well, could install a VM, install safari, install etherpad...) but I think it's a small thing, so if someone could have a look? My guess is that we should add

`#editorcontainerbox { height: 0 }`

and/or

 `#editorcontainerbox #editorcontainer iframe { height: 100% }`

You can just add those rules from the developer console in the browser, @lweingart could you have a try? Or if you installed it locally just add the rules I wrote in `src/static/css/pad.css`

**Comment by JohnMcLear** [comment]
@seballot I think I can replicate a problem in FF

https://video.etherpad.com/p/fooxxxxxxxxxxxxxxx

Scroll bar is visible when it shouldn't be...

**Comment by JohnMcLear** [comment]
If I delete "importexport" , "settings" etc. from the dom I get less issues...  Not sure why they are affecting scrollbar when not visible.. ?

**Comment by JohnMcLear** [comment]
This is in Chrome https://video.etherpad.com/p/fooxxxxxxxxxxxxxxxa

![image](https://user-images.githubusercontent.com/220864/79699620-8e225800-8288-11ea-9cb9-c4c77ddebbf9.png)

**Comment by JohnMcLear** [comment]
Notice the white space at the bottom of the pad...  ;\

**Comment by lweingart** [comment]
@seballot 

I added 
#editorcontainerbox { height: 0 }
and
#editorcontainerbox #editorcontainer iframe { height: 100% }

in src/static/cas/pad.css

and it does indeed seem to fix the issue

**Comment by muxator** [comment]
Let's converge on a PR and we'll include it in **1.8.3**. I cannot help because I am no mac user, too.

Thanks @lweingart for freeing us of the hassle of having to issue an hotfix the day after the release :)

**Comment by seballot** [comment]
Thanks @lweingart for testing ! So I pushed the fix, once merge, could you try again @JohnMcLear ? Strange you got this on firefox and chrome also...

I will create a ticket for general browser compatibility

**Comment by lweingart** [comment]
@seballot  I pulled the repo and the issue seems to be fixed

Thanks a lot guys
