### ISSUE TITLE
New FlexLayout / Browser compatibility

### ISSUE THREAD

**Issue by seballot** [ether/etherpad-lite#3907]
We should test it seriously on most possible browser. I guess there are some tools to do that online, if you know some please inform me :)

Also, I think we should add a prefixer in our assets pipeline.
Prefixer convert css rule like `display: flex` to something like
```
display: -webkit-box;
display: -ms-flexbox;
display: flex
```

How the assets pipeline works for now? Where does the css minify takes place? If you could point me the right direction would be nice :)

Please assign to me

**Comment by luixxiul** [comment]
Maybe it is too late but how about implementing [`normalize.css`](https://github.com/csstools/normalize.css)? It would definitely break the existing plugins layout so I am not quite if it is right time to do so...

**Comment by seballot** [comment]
Hi ! thanks but that is different, and I already added it along with refactoring ;)

https://github.com/ether/etherpad-lite/blob/develop/src/static/css/pad/normalize.css

**Comment by JohnMcLear** [comment]
![image](https://user-images.githubusercontent.com/220864/79734065-03744400-82ee-11ea-8a57-213a3a8542fd.png)

Note the white bar at the bottom clipping the pad text

Firefox on Windows

**Comment by luixxiul** [comment]
by the way @JohnMcLear 幸せの肉 = Meat of happiness / Happy Meat 😄

**Comment by muxator** [comment]
> How the assets pipeline works for now? Where does the css minify takes place? If you could point me the right direction would be nice :)

Have a look at [src/node/utils/Minify.js](https://github.com/ether/etherpad-lite/blob/4ceb42603e2c9d4051df1a9140728ea30f2f833f/src/node/utils/Minify.js).

That specific part (along with the "peculiar" startup sequence and cache handling) is one of the parts of thecodebase that really show their age.

I won't spend more than a couple of lines on that file. Anything more complex deserves taking the time to tear apart what exists and rebuild on more modern foundations (hopefully without bringing in too much complexity).

It can be a fruitful line of work, indeed.

**Comment by JohnMcLear** [comment]
> by the way @JohnMcLear 幸せの肉 = Meat of happiness / Happy Meat 😄 🍖

Hahah no way I worked in Nagoya and Tokyo for a bit and I never was told this!  Japanese politeness I guess!  Awesome translation!  :P

**Comment by JohnMcLear** [comment]
@seballot did a number of fixes on this today but we're still not ready for release, most bugs are now in Safari so I gave Sebastian my Saucelabs credentials and he will be able to debug there :)

**Comment by muxator** [comment]
@JohnMcLear, ack.
@seballot, feel free to close when this is done.

I am working on the other items in the meantime.

**Comment by seballot** [comment]
Hi ! Thanks @JohnMcLear, saucelabs was quite useful (even it's soooo slooooow !!)

I made some fix, and from my tests new UI works from

Firefox 30 (current 75)
Edge 16 (current 80)
IE -> not working, but etherpad is not working at all, even with old layout
Chrome 49 (current 81)
Safari 9 (current 13)

We are loosing some browser compatibility, old version was working for example with safari 8. But I think it's fine, no?

I also test with mobile emulator, using oldest version proposed each time, and it was working nicely.

Once it's merged and pushed to video.etherpad.com, I will do some final test and close the ticket

**Comment by seballot** [comment]
Oh and I tried to add css autoprefixer, but was not working... And actually I think it would not have help so much, maybe getting works 2 or 3 old browser version

**Comment by JohnMcLear** [comment]
Merged, live on video.etherpad.com

**Comment by JohnMcLear** [comment]
One last bug

If you deny access to the camera, the white pad area ends a significant distance from the text chat column.

**Comment by JohnMcLear** [comment]
![image](https://user-images.githubusercontent.com/220864/79873480-11ee5880-83df-11ea-948b-814f873a43cb.png)

**Comment by seballot** [comment]
yep this is the comment section

**Comment by JohnMcLear** [comment]
I think this is more of an ep_webrtc bug?

**Comment by JohnMcLear** [comment]
okies

**Comment by JohnMcLear** [comment]
looks closable then :) good job!

**Comment by muxator** [comment]
I think I hit a nasty bug when importing.

Right now I am not at my PC, I'll post a screenshot asap.

**Comment by seballot** [comment]
oh yes, content is duplicate in two column, you have the same? quite funny

**Comment by seballot** [comment]
oh and actually my last commit break something, arf it's because locally even with force refresh, my browser still load css from cache inside the iframe editor, so we can not longer scroll the pad ! Fixed, taking care of import now

**Comment by JohnMcLear** [comment]
![image](https://user-images.githubusercontent.com/220864/79875314-6692d300-83e1-11ea-8b65-af7ee4740d96.png)

this is hte no scrollbar bug just for ref.

**Comment by JohnMcLear** [comment]
![image](https://user-images.githubusercontent.com/220864/79875394-80ccb100-83e1-11ea-92af-8391a0de7037.png)
The import bug =D  Can't believe test runner didn't spot that... ;/

**Comment by JohnMcLear** [comment]
Also after "import now" shouldn't the popup close?  Minor issue.  Will fix the markdown item in the list..

**Comment by seballot** [comment]
```js
handleFrameCall: function(directDatabaseAccess, status)
    {
      if (status !== "ok")
      {
        importFailed(status);
      }
      // commenting that line make it works fine...
      // if(directDatabaseAccess) pad.switchToPad(clientVars.padId);
      importDone();
    },
```

**Comment by seballot** [comment]
but I wonder if there will be unattended consequences of removing this line?

and for closing the popup, good idea
```js
if (status !== "ok")
      {
        importFailed(status);
      } else {
        $('#import_export').removeClass('popup-show');
      }
```

**Comment by JohnMcLear** [comment]
// if(directDatabaseAccess) pad.switchToPad(clientVars.padId);

``directDatabaseAccess`` is used for ``.Etherpad`` file imports.

``pad.switchToPad(clientVars.padId);`` allows the user to import a ``.etherpad`` file without forcing a refresh.

``directDatabaseAccess`` should be false for all but ``.etherpad`` file imports afaik...

**Comment by JohnMcLear** [comment]
@seballot for some reason ``directDatabaseAccess`` is ``undefined`` but returning true...    Something wrong here..  Continuing investigations.

**Comment by JohnMcLear** [comment]
``
      console.log(typeof directDatabaseAccess)``
Is returning string, lolwtf.

**Comment by JohnMcLear** [comment]
```

      // Server sends a string, not a boolean
      if(directDatabaseAccess !== 'undefined') pad.switchToPad(clientVars.padId);
```
Is the fix I used for html et al.  Will now fix the ``pad.switchToPad`` issue

**Comment by seballot** [comment]
Great thanks ! don't forget to add the line of code to close the popup :)

**Comment by JohnMcLear** [comment]
I put a fix together which is ungraceful but works:
https://github.com/ether/etherpad-lite/pull/3915

Ideally import would never refresh the browser but for now it does the job to get 1.8.3 out the door.

**Comment by seballot** [comment]
Nop nothing else under the radar for me !

**Comment by slel** [comment]
Any chance to revisit #2671?

**Comment by muxator** [comment]
> Nop nothing else under the radar for me !

Ok thanks. I am closing this issue, let's focus on #3569 

After solving that one, we have only a documentation change and then we can release :partying_face: 

@seballot, would you be ready to work on the website (https://github.com/ether/ether.github.com/issues/30)? Simply updating the screenshots would be more than enough for now.
