### ISSUE TITLE
package-lock.json need to update into repo?

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3911]
Hi everyone! I am at a loss of what to do in this case.

1 - cloned a development branch to my server
2 - went into the src folder and ran the 'npm outdate' and 'npm update' commands in order to update the dependencies to the allowed ones
3 - ran the 'git status' command and saw the following result

<img width="768" alt="Screenshot at Apr 21 04-48-17" src="https://user-images.githubusercontent.com/25965602/79816927-fa867f80-838c-11ea-9ef8-eee574f4b964.png">

Without step 2, if you start the server immediately, you will need to perform 'npm audit' and 'npm audit fix' in order to fix the dependencies. Otherwise, everything is fine with the dependencies.

The question is - should I create a commit with this file and send PR?

**Comment by muxator** [comment]
Hi @alekso87. Ignore the modifications in package-lock.json.

Once #3778 is implemented everything will be easier.

**p.s.**: your point 2 is not very clear (and is not something you are supposed to do when installing Etherpad).

**Comment by alekso87** [comment]
@muxator Got it! Thanks.

**Comment by JohnMcLear** [comment]
@muxator can we close this now please? :)
