### ISSUE TITLE
How to restore the database?

### ISSUE THREAD

**Issue by luixxiul** [ether/etherpad-lite#3912]
Since a couple of days I was trying to test how to restore the database.

I successfully set up etherpad-lite instance with mysql (mariadb) following the manual on Wiki: https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL. I dumped the database with `mysqldump` and tried to import that to another VM instance with the same mariadb user/password as the main machine. After importing the database (successfully I think) I tried to run etherpad-lite with `bin/run.sh` and I got the error related with database initialization.

Would anyone please let me know how to import the database and start etherpad instance without that error?

**Comment by JohnMcLear** [comment]
You didn't paste the error....

You did it right though..  dump > import > copy ``settings.json`` and ??``credentials.json``?? to the new instance...  

Also you will need to create the new mysql user on the new VM..

**Comment by luixxiul** [comment]
> You didn't paste the error....

Ah right, I should have pasted that and shown you steps I did to experience the error. Sorry!

I will test once more to see what I am doing wrong.

**Comment by luixxiul** [comment]
Due to an incident unrelated with etherpad-lite, I was required to reset the server on which etherpad-lite was hosted too. Since I would like to set up the environment afresh (thanks to the fact that our community still has not made use of etherpad yet), I am going to close this issue for now. If I would find a bug (if any) related with importing the database, I'll reopen this one.

**Comment by JohnMcLear** [comment]
Ack :)  tnx
