### ISSUE TITLE
Skin builder: add coma in resulting code

### ISSUE THREAD

**Issue by meaz** [ether/etherpad-lite#3919]
When using Skin builder, you get the code to copy in settings.json
However, in the provided there is no coma at the end.
For example, you get `"skinVariants": "super-light-toolbar light-background super-light-editor"`

But when you copy this in the settings, if you don't add a coma, you then got an error.

So I suggest to directly provide the coma in the code you got from Skin builder, so  `"skinVariants": "super-light-toolbar light-background super-light-editor",`

**Comment by muxator** [comment]
I think it makes sense. 90% of the times the comma will be needed.

@seballot, do you agree?
@meaz, write a small PR.

**Comment by seballot** [comment]
Yep !

**Comment by muxator** [comment]
Done. Thanks.
