### ISSUE TITLE
1.8.3 shouldn't refresh after import .etherpad file

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3923]
https://github.com/ether/etherpad-lite/pull/3915#discussion_r413407628

I made a promise to fix it properly.  Which I intend to do.

**Comment by JohnMcLear** [comment]
Fixed in https://github.com/ether/etherpad-lite/pull/3925

**Comment by muxator** [comment]
#3925 is merged. Closing.
