### ISSUE TITLE
switchToPad not working as expected

### ISSUE THREAD

**Issue by Gared** [ether/etherpad-lite#3928]
Tested with the latest develop version.
I'm using the ```pad.switchToPad("test")``` function to change the pad. Looks like this is broken:
![grafik](https://user-images.githubusercontent.com/913630/80150460-faae9700-85a7-11ea-8f52-ce6edd401dfa.png)

On master everything is working as expected

**Comment by JohnMcLear** [comment]
Yea it's fixed, just waiting on a merge, will get merged 2nite 🗡️

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/pull/3925 fyi

**Comment by JohnMcLear** [comment]
Closing this because I know I wont offend you by doing so :)
