### ISSUE TITLE
Where can I see a fresh HTTP API doc for 1.2.14?

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3930]
Hi everyone! I see only HTTP API docs for old etherpad.

<img width="1163" alt="Screenshot at Apr 24 18-01-55" src="https://user-images.githubusercontent.com/25965602/80228545-d8745200-8657-11ea-818d-7f14fd07ee08.png">
Thanks!

**Comment by JohnMcLear** [comment]
https://etherpad.org/doc/v1.8.0-beta.1/#index_client_side_hooks

**Comment by JohnMcLear** [comment]
Please update Wiki @alekso87 :) Tnx!

**Comment by alekso87** [comment]
done :)
