### ISSUE TITLE
Timeslider errors when content is deleted and content is no longer consistant. - AWAITING REVIEW/MERGE

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#3932]
I'm placing this as an early catch, this needs working on urgently.

https://youtu.be/Wf0TJa3CucQ shows the timeslider content being incorrect.

Error is: 

```
Uncaught Error: Can't copy unknown attrib (reference attrib string to non-existant pool entry). Inconsistent attrib state!
    at Object.error (timeslider.js?callback=require.define:2540)
    at timeslider.js?callback=require.define:4033
    at String.replace (<anonymous>)
    at Object.exports.moveOpsToNewPool (timeslider.js?callback=require.define:4030)
    at Object.handleMessageFromServer (timeslider.js?callback=require.define:6157)
    at r.<anonymous> (timeslider.js?callback=require.define:93)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
```
**And it is reproducable by deleting all pad content**.

This error was present in 1.6.2..  Jeez

## Steps to replicate
1. Create pad
1. Open timeslider in another window
1. Delete pad contents.
1. Type new pad contents.

## who is impacted
Anyone who reviews pad content[with the timeslider when a pad is being edited.  Most people don't use this functionality but it's a really key part of reviewing pad edits and IMHO a decent feature worth promoting/fixing.

**Comment by JohnMcLear** [comment]
## timeslider
```          console.warn("obj.apool", obj.apool)
          console.warn("padcontents.apool", padContents.apool)
          var changesetBack = Changeset.moveOpsToNewPool(
            changesetBack, (new AttribPool()).fromJsonable(obj.apool), padContents.apool);
```
Returns

![image](https://user-images.githubusercontent.com/220864/80241635-d7ddba80-865b-11ea-9f66-ebf3f49845bf.png)

**Comment by JohnMcLear** [comment]
Surgical gloves were required for this one...  *wipes sweat from brow..

**Comment by muxator** [comment]
Nice catch. This can go in **1.8.3** for sure.
