### ISSUE TITLE
Officially supported plugins

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3935]
# Official plugins
With no plugins Etherpad is functional, yet very basic,. This is by design, and it is a good thing.

However, many users will certainly want to extend the UX using some plugins, for example:

- ep_comments
- ep_author_hover
- ep_headings2 
- ep_markdown
- *TODO*: work on this list

I propose to choose a **curated list of plugins** and invest in their functionality.
If they are deemed sufficiently mature **and maintainable**, we can then feature them directly in the README, and promote their use for **1.9**.

Once a plugin is stable it may be integrated in core, as an optional feature (>= **2.0**).

## PROS
1. useful functionalities;
2. more appeal to users;
3. official support would mean better stability and cross testing between core & plugins;
4. more real-word checks for potentially breaking changes.

## CONS
1. **maintenance burden will increase very much**;
2. more manual testing & verification needed;
3. necessity to invest in improved automatic testing **code** & **infrastructure**;
4. development could slow down due to increased inter-dependencies.

**Comment by JohnMcLear** [comment]
We have ongoing efforts already here..  Note the activity on the repos.

1. ep_webrtc [needs test coverage & more real world deployments]
1. ep_hash_auth [need clear docs on security / auth as per conversation]
1. ep_headings2 [needs settings unified (see below)], better export functionality etc.
1. ep_font_size [needs settings unified (see below)], better export functionality etc.
1. ep_comments [needs settings unified (see below)], better export functionality etc.
1. ep_author_hover [needs settings unified (see below)]
1. ep_pad_title [needs settings unified (see below)]
...  Insert more here :)

@orblivion is making a unified code base for things like handling settings/admin interface etc. which once complete we will roll out across all the plugins.

Most of the plugins have test coverage, but it will be getting improved.

The challenge atm is prioritizing what gets worked on.  I have tried to prioritize the list as I see fit. Top Priority is ep_webrtc atm.

I agree RE pushing for core by 2.0 and other suggestions.
