### ISSUE TITLE
Update hint

### ISSUE THREAD

**Issue by Gared** [ether/etherpad-lite#3937]
Currently an admin of a etherpad instance gets no notification about a new etherpad release.

What about adding a hint to the admin page?
Any other ideas?

**Comment by muxator** [comment]
Why not. The Admin page already requests `https://static.etherpad.org/plugins.json` after all. It may be a matter of adding the latest version information there in a backward compatible way.

**Comment by JohnMcLear** [comment]
This should be super easy to implement but be really impactful.  I'd also be keen to see it land on the logs in startup too.

@Gared you wanna take this challenge on and if you get stuck feel free to reach out and I will assist?
