### ISSUE TITLE
You do not have permission to access this pad

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3938]
Hi everyone! Why am I seeing this when I visit my group pad - https://site.com/g.kU30kGMSetcKsjrg$asdfvcfd? I did not find any mention in the documentation that group pads require a session, given that the **requireSession** parameter is **false**. Examples and settings below.

<img width="926" alt="1" src="https://user-images.githubusercontent.com/25965602/80288809-39c51f80-8743-11ea-8255-ae344e2c83db.png">

<img width="934" alt="2" src="https://user-images.githubusercontent.com/25965602/80288811-3d58a680-8743-11ea-80a5-736648b2eb51.png">

settings.json
```
{
  ...
  "requireSession": false
  ...
}
```
```
[2020-04-25 22:21:15.674] [WARN] message - Authentication try failed:{"component":"pad","type":"CLIENT_READY","padId":"g.kU30kGMSetcKsjrg$asdfvcfd","sessionID":"null","password":null,"token":"t.pgKq4hZ59aIr43ppd3AR","protocolVersion":2}
```

**Comment by JohnMcLear** [comment]
Are you using a library for Auth flow etc? 

I'm not sure what requiresession setting does but I don't think it's related to authentication or authorization.

**Comment by alekso87** [comment]
> Are you using a library for Auth flow etc?

I did not quite understand the question, but rather, what not. Basic setting - I did not change the settings file, the necessary settings are located in the credentials file.

I can give access to the API so that you can create a group + group ped and check access to the ped.

Send it to email?

**Comment by alekso87** [comment]
And I don't quite understand why this file is needed - SESSIONKEY.txt :D I do not see the information in the documentation.

**Comment by alekso87** [comment]
credentials.json

<img width="380" alt="Screenshot at Apr 26 22-18-29" src="https://user-images.githubusercontent.com/25965602/80317390-334eaa80-880c-11ea-858b-65e6ecd31b6a.png">

**Comment by JohnMcLear** [comment]
1. ``SessionKey`` is for the API, not for user sessions..
1. This setting is for if you want to enforce a user to have a pre-defined session ( from another API or so) to access NON GROUP pads (as per the setting).
```
  /*
   * If this option is enabled, a user must have a session to access pads.
   * This effectively allows only group pads to be accessed.
   */
  "requireSession": false,
```
1. I haven't looked at the docs but I'm 99% sure it talks about the flow for creating a session for an author.
1. You might find that you can find a library for your language IE php/nodejs/python that can handle the majority of the API / session management for you.  Did you look for one?  If so, use that and reduce your headache :)

**Comment by alekso87** [comment]
> 1. `SessionKey` is for the API, not for user sessions..

To send a request through the API, I use the APIKEY.txt.
SESSIONKEY.txt as far as I understand the application itself uses on its side?

> 4. You might find that you can find a library for your language IE php/nodejs/python that can handle the majority of the API / session management for you.  Did you look for one?  If so, use that and reduce your headache :)

I know, thanks.

**Comment by JohnMcLear** [comment]
1. My mistake.  You are correct.  sessionKey is used to generate express session IDs that can be then re-used after restart.  To retain uniqueness...

Did you solve this?  Happy to help further if I can.  If you want another example you can look at how the backend tests auth, I'm pretty sure it does a make user flow, create group pad etc.

**Comment by alekso87** [comment]
Yes, I solved the question by running a couple of tests.
