### ISSUE TITLE
Such a padname is forbidden without large names

### ISSUE THREAD

**Issue by muzzol** [ether/etherpad-lite#3939]
hi,

I'm having a strange problem with some of my pads.
I'm receiving **"Such a padname is forbidden"** but is not related to name lenght like here:  https://github.com/ether/etherpad-lite/issues/2583

My pads are not that long, you can check it here: https://pad.cat/p/a/

I configured loglevel to DEBUG but I didn't find any usefull info.

The only particular thing about this installation is that I use sqlite with 1.8.0
No auth, no especial plugins.

I'm completely lost. Ask for further info if you need it. I can provide full etherpad_sqlite.db file if you want to debug it directly.

**Comment by muxator** [comment]
Hi @muzzol,

Remove the trailing "/" at the end of your URL and it will work.

Pad names cannot end in "/".

If you feel contributing, you could write a small PR to improve the error message.

P.s.: we are releasing 1.8.3 today. Try it, and change "skinName" from "no-skin" to "colibris". You won't regret it. 😄

**Comment by muzzol** [comment]
> Hi @muzzol,
> 
> Remove the trailing "/" at the end of your URL and it will work.
> 
> Pad names cannot end in "/".
> 
> If you feel contributing, you could write a small PR to improve the error message.
> 

besides improving error message, do you have any rewrite rule for apache/nginx to remove trailing slash?


> P.s.: we are releasing 1.8.3 today. Try it, and change "skinName" from "no-skin" to "colibris". You won't regret it. smile

I already activated, my only complain is that I would like to make it wider, not full page but a little wider. where can I modify that value?

**Comment by muzzol** [comment]
ok, I'm gonna answer myself about the rewrite part. I managed to force removing trailing slashes with this configuration.

`
    	RewriteEngine On
    	RewriteCond %{REQUEST_URI} !^/locales/
    	RewriteCond %{REQUEST_URI} !^/locales.ini
    	RewriteCond %{REQUEST_URI} !^/admin
    	# RewriteCond %{REQUEST_URI} !^/p/
    	RewriteCond %{REQUEST_URI} !^/static/
    	RewriteCond %{REQUEST_URI} !^/pluginfw/
    	RewriteCond %{REQUEST_URI} !^/javascripts/
    	RewriteCond %{REQUEST_URI} !^/socket.io/
    	RewriteCond %{REQUEST_URI} !^/ep/
    	RewriteCond %{REQUEST_URI} !^/minified/
    	RewriteCond %{REQUEST_URI} !^/api/
    	RewriteCond %{REQUEST_URI} !^/ro/
    	RewriteCond %{REQUEST_URI} !^/error/
    	RewriteCond %{REQUEST_URI} !^/jserror
    	RewriteCond %{REQUEST_URI} !/favicon.ico
    	RewriteCond %{REQUEST_URI} !/robots.txt
    	RewriteRule ^(.*)/+$ $1 [R=301,L]
`


please note that I DON'T remove the /p/ from pads but I supose it would be easy to adapt.
can you please take a look and confirm it's OK?
maybe this could be added to docs.

**Comment by muzzol** [comment]
even easier (sorry for double posting):

```
	RewriteEngine On
	RewriteCond %{REQUEST_URI} ^/p/
	RewriteRule ^(.*)/+$ $1 [R=301,L]
```

I repeat, this works only if you're NOT removing /p/ from your pads.

**Comment by JohnMcLear** [comment]
Can this be closed now? :)

**Comment by muzzol** [comment]
sure, I'll close it mysefl.

**Comment by muxator** [comment]
```
	RewriteEngine On
	RewriteCond %{REQUEST_URI} ^/p/
	RewriteRule ^(.*)/+$ $1 [R=301,L]
```

@muzzol, a fast feedback: this `mod_rewrite` rule seems ok.


> I already activated, my only complain is that I would like to make it wider, not full page but a little wider. where can I modify that value?

Currently there is no user-level support in core for setting a custom width.

**Comment by muzzol** [comment]
> @muzzol, a fast feedback: this `mod_rewrite` rule seems ok.
>

nice, can I suggest putting this somewhere on the docs?
also would be nice to throw a DEBUG exception to logs indicating someone tried to put a non allowed character on a pad name
 
> > I already activated, my only complain is that I would like to make it wider, not full page but a little wider. where can I modify that value?
> 
> Currently there is no user-level support in core for setting a custom width.

ok, I'll tinker a little bit with the code and see if I break something.
