### ISSUE TITLE
de-precambrianize or remove dependency from async

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3940]
Etherpad depends on a very old version of [async npm library](https://www.npmjs.com/package/async):

```
$ npm outdated
Package          Current  Wanted      Latest  Location
async              0.9.0   0.9.0       3.2.0  ep_etherpad-lite
```

Times have changed quiet a lot from its introduction in etherpad. Continuing using it may or may not make sense.

- [x] investigate is the use of `async` library is unavoidable in Etherpad code base;
- [ ] if `async` is not necessary, remove it and adapt the existing code;
- [x] if `async` is still needed, update it to the lastest version and deal with the fallout of the major version change.

**Comment by JohnMcLear** [comment]
```
jose@server:~/develop/src/node$ grep -rni async . | grep require
./utils/caching_middleware.js:17:var async = require('async');
./utils/Minify.js:22:var ERR = require("async-stacktrace");
./utils/Minify.js:24:var async = require('async');
./utils/LibreOffice.js:19:var async = require("async");
./utils/Abiword.js:22:var async = require("async");
```

**Comment by muxator** [comment]
Yep, **0.9** -> **3.2** couldn't be a smooth ride. But we can get there :smile:

**Comment by JohnMcLear** [comment]
Waiting on review still...

**Comment by JohnMcLear** [comment]
I just need to update package.json and package lock...
