### ISSUE TITLE
function setPassword only for group pads? 

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3946]
Hi everyone! Did you forget to mention this in the documentation? [Link to doc](https://etherpad.org/doc/v1.8.0-beta.1/#index_setpassword_padid_password)

<img width="929" alt="1" src="https://user-images.githubusercontent.com/25965602/80373951-90933c00-889e-11ea-8730-8491af9bb680.png">
<img width="927" alt="2" src="https://user-images.githubusercontent.com/25965602/80373967-9426c300-889e-11ea-8a4d-fe6214f05be6.png">

**Comment by alekso87** [comment]
If so, why not make a password with binding not only to padID, but + also to authorID?

setPassword(padID, authorID, password)

For example - a group pad and there are 2 authors in it.

The password is set on the pad. The owner of the pad urgently needs to close access to the second author. It changes the password to the pad, and since the password is shared, the password must be re-entered to the owner of the pad as well. And if 3 or more people have access to the pad?

**Comment by JohnMcLear** [comment]
I wouldn't use Etherpad internal mechanism for passwords, is it something you really want to do?

**Comment by alekso87** [comment]
A little later I will give an answer in one of the issue :)

**Comment by alekso87** [comment]
I close the topic due to uselessness. Thanks.
