### ISSUE TITLE
BUILD/RELEASE process: Create release branch along with tag

### ISSUE THREAD

**Issue by tiblu** [ether/etherpad-lite#3949]
**What?**

Please create release branch along with release tag when new version of Etherpad is released.

**Why?**

When using Etherpad as a submodule in another project, you can reference a specific branch, but AFAIK not a tag. We would like to reference submodule from Etherpads official repository.

Why not reference `master`? `master` contains latest release version, but due to the nature of our Citizen OS project with all of it's 10+ plugins, we would like to do controlled update for Etherpad, that is test the latest version to play nice with our modifications before we release our own.

**Urgent?**

No, not really. We can still use our own fork and reference that in our submodule.

**Background**

From GH history, it seems, at some point release branches were created, but not any more.

**Related projects**

* https://github.com/citizenos/etherpad-lite-heroku

**Comment by tiblu** [comment]
@muxator  Thanks for the quick response!

We're not in a hurry, but if you can create a release branch for us, it would be great. Release tag would be OK for those who are historically interested in the tag.

I'll put my 10 cents to https://github.com/ether/etherpad-lite/pull/3943

**Comment by JohnMcLear** [comment]
I'm +1 release branches they make bisect much easier

**Comment by muxator** [comment]
Hi,

I have created https://github.com/ether/etherpad-lite/tree/release/1.8.3.

Noting this use case for the next releases, thanks.
