### ISSUE TITLE
UI issue after 1.8.3 release

### ISSUE THREAD

**Issue by seballot** [ether/etherpad-lite#3954]
- [x] in safari, the select dropdowns inside the toolbar (ep_headings, ep_font_color) do not work (because of the overflow of the toolbar. I already noticed this bug, but on chrome and firefox using a `position: fixed` fixed it. Not on safari :) )

- [x] A strange vertical line is displayed on middle of the screen on load : https://youtu.be/MiJ5AcS6S-g

- [x] Index page need to use new font
- [x] ep_set_title_on_pad is not colored by skin variants
Others small stuff I already fixed, not yet pushed

Please assign to me !

**Comment by JohnMcLear** [comment]
I can't assign to you.  Not sure why!

**Comment by muxator** [comment]
This issue was assiged to the wrong milestone (1.8.5). It was always part of 1.8.4, just released.
