### ISSUE TITLE
"Synchronous XMLHttpRequest on the main thread is deprecated" message on Firefox Nightly

### ISSUE THREAD

**Issue by luixxiul** [ether/etherpad-lite#3962]
**Description of the issue**: On Firefox Nightly I see a warning log on the devtool's console.

`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ require-kernel.js:284:12`

I understand this is not an error, still I am a bit worried that this issue would become so critical that Etherpad could no longer work as expected on Firefox in the future. I think maybe you guys have already noticed that warning, and I am just wondering if you would have some time to work on this stuff.

Thanks!

Browser Version: 77.0a1 (2020-05-01) (64-bit)
Etherpad Version: 6210114
OS Version: Debian 10 with nginx

**Comment by JohnMcLear** [comment]
Isn't there already an open issue for this?

**Comment by JohnMcLear** [comment]
See #2427

**Comment by luixxiul** [comment]
ok- thanks for checking!
