### ISSUE TITLE
Learn: Get and Post text into a newly created pad programmatically without API key

### ISSUE THREAD

**Issue by makefu** [ether/etherpad-lite#3963]
Hi all and thanks for the great project, i am currently trying to programmatically create new pads and add some text if no text was added before.
Currently the first part (creation) works but i am having issues with the posting of our template text.
We use etherpad for our podcast show notes (https://blog.binaergewitter.de) and our current code can be found at https://github.com/Binaergewitter/gecloudpad 
I saw that there is an API, however it only seems to work with the administrative API key which we do not have access to as we are using https://board.net instead of hosting our own board.

Maybe you have some pointers how i could achieve getting and post-ing text into an existing board.

Cheers!

**Comment by JohnMcLear** [comment]
Host your own board!  It's really easy to do.  Search for Etherpad docker or k8s.
