### ISSUE TITLE
Etherpad as a service

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3967]
Hi everyone! I have a question about the current configuration from Wiki.

If the Etherpad has never been launched, then how can we indicate the path to the startup script **"/opt/etherpad/node_modules/ep_etherpad-lite/node/server.js"**? The folder **"node_modules"** is created at the time of the first start.

<img width="768" alt="Screenshot at May 04 21-48-25" src="https://user-images.githubusercontent.com/25965602/81002420-dc6f5380-8e51-11ea-9437-fb85cc9db76d.png">

**Comment by muxator** [comment]
Hi, @alekso87. A manual run of bin/installDeps.sh is needed before first start.

Of this is not on the wiki, please add it, since it's needed.

Thanks

**Comment by alekso87** [comment]
@muxator Thanks, updated doc.
