### ISSUE TITLE
Can the Etherpad handle "connection failure"?

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#3968]
Hi everyone! I use the current configuration of the unit to start the service.

```
[Unit]
Description=Etherpad-lite, the collaborative editor.
After=syslog.target network.target

[Service]
Type=simple
User=etherpad
Group=etherpad
WorkingDirectory=/opt/etherpad
Environment=NODE_ENV=production
ExecStart=/usr/bin/nodejs /opt/etherpad/node_modules/ep_etherpad-lite/node/server.js
Restart=always # use mysql plus a complete settings.json to avoid Service hold-off time over, scheduling restart.

[Install]
WantedBy=multi-user.target
```

I use proxying through Nginx, as well as the MySQL database. I see that there is a certain dependence of Etherpad on other services, namely in their order of launch.
```

[Unit]
...
After=syslog.target network.target mysql.service nginx.service
Requires=mysql.service nginx.service
...
```

Or can an Etherpad handle "connection failure" if **mysql.service** and **nginx.service** started later than the Etherpad itself?

**Comment by JohnMcLear** [comment]
One of the first called Etherpad does it ``db.init()`` to ``initialize`` the Database connectivity (in your case MySQL).  I have a lot of boxes in production with Etherpad & MySQL and have NEVER seen Etherpad launch before MySQL.  But then again I use systemctl so maybe it is trying to start but erroring and I just never spotted it in logs (unlikely)..   

Systemctl handles it like this: https://unix.stackexchange.com/questions/43202/how-can-i-start-a-systemd-service-only-after-mysql-has-started.  So without doing your homework for you, I think you need...

```
[Unit]
Description=Etherpad
After=mysql.service
```

Or am I misunderstanding?  I literally spent 2 mins Googling this so I imagine I am misunderstanding..

**Comment by alekso87** [comment]
@muxator The question is very simple - will the service of Etherpad start if it is launched earlier than the Nginx and MySQL services? In the configuration from the documentation for the service of Etherpad, there is no priority to launch.

**Comment by JohnMcLear** [comment]
MySQL = no.
Nginx = Yes.

Unless Etherpad start takes longer than the time it takes MySQL to start accepting connections AND/OR the MySQL driver / library has timeout/retry baked in.  YMMV depending on MySQL library and this is not an Etherpad thing, you can configure it in settings no?

https://github.com/mysqljs/mysql#connection-options
