### ISSUE TITLE
/ still offers create/open pad even when it's forbidden

### ISSUE THREAD

**Issue by ssendev** [ether/etherpad-lite#3970]
When setting `EDIT_ONLY=true` the `New Pad` button is still there and the label below is `create/open pad with the name:`.

When setting `REQUIRE_SESSION=true` and there is no session create/open pad buttons are still there.

But clicking these buttons will always fail since it's forbidden.

It would be better UX to hide these buttons when they don't work.

**Comment by JohnMcLear** [comment]
I didn't even realize this functionality existed..  @seballot 

@ssendev is this something you can do as it's just a case of applying a class based on a clientVar (one assumes)?  Or should we hide this in the .ejs file?  Probably the .ejs file I guess?
