### ISSUE TITLE
what is the recommended node version for Etherpad ?

### ISSUE THREAD

**Issue by mrflos** [ether/etherpad-lite#3972]
Hello,
I'm running https://pad.coop.tools and https://pad.colibris-outilslibres.org and since the update to 1.8.3, I also changed node version to node 12.  
I have noticed that the software is more often loosing network connection and i'm not sure if it's related to change of version the etherpad or of node version..  
What version do you recommand to use? 

And as bonus question : is deleting de node_modules folder and run updateDeps.sh the best way to update etherpad?  

Thanks for the good work to all the etherpad team! 🥇

**Comment by JohnMcLear** [comment]
> Hello,
> I'm running https://pad.coop.tools and https://pad.colibris-outilslibres.org and since the update to 1.8.3, I also changed node version to node 12.
> I have noticed that the software is more often loosing network connection and i'm not sure if it's related to change of version the etherpad or of node version..
> What version do you recommand to use?

10+.



> And as bonus question : is deleting de node_modules folder and run updateDeps.sh the best way to update etherpad?

``git pull`` ``bin/run.sh`` usually does it.  

If things aren't right do a ``rm -rf src/node_modules``.  ``bin/run.sh`` does most of the house keeping for you now.



> Thanks for the good work to all the etherpad team! 🥇

+1 Tnx & yw.

**Comment by mrflos** [comment]
Thank you for your quick response!
I'm closing this issue, being 100% satisfied! 😃 

Have a nice day!
