### ISSUE TITLE
我应该如何使用钩子

### ISSUE THREAD

**Issue by TianPuJun** [ether/etherpad-lite#3976]
非常抱歉打扰您，我是一个前端小白，对 https://etherpad.org/doc/v1.6.2/#index_userleave 中的钩子函数并不是很会使用，我的问题是，我如果要进行userleavel这个钩子的使用，我应该如何做。
任何小小的提示都是对我的协助，thank you

**Comment by JohnMcLear** [comment]
The hooks and API are not for front end users.

挂钩和API不适用于前端用户。
