### ISSUE TITLE
incorrect MIME types from Minify.js

### ISSUE THREAD

**Issue by claudeha** [ether/etherpad-lite#3977]
I put some WASM in the static directory, but it was served as `application/octet-stream` instead of `application/wasm`.  The culprit is the minifier not using any proper MIME database but its own very short hardcoded list:

https://github.com/ether/etherpad-lite/blob/82d1179f24ae8463d94622eed06f53a55ce11d09/src/node/utils/Minify.js#L180-L199

**Comment by JohnMcLear** [comment]
Great spot, I will fix this today prolly as it falls under my helmet work.

**Comment by JohnMcLear** [comment]
btw check out ep_helmet :D

**Comment by JohnMcLear** [comment]
Here you go: https://github.com/ether/etherpad-lite/pull/3979

Try that branch please, confirm if working, if so will leave for mux to merge.

**Comment by claudeha** [comment]
Seems to work fine for me, at least WASM + CSS + JS + fonts are served correctly, no mime errors in Firefox console, no obvious regressions (I was on 1.8.3 tag before).
