### ISSUE TITLE
Don’t attempt to refresh the page after having been disconnected

### ISSUE THREAD

**Issue by linkmauve** [ether/etherpad-lite#3985]
I was reading a pad when the server got restarted by the admin, so I got a notification that it was unreachable and all was fine.

I continued reading, but after about a minute the entire page got refreshed to a 502 nginx error, which makes sense because the server wasn’t back yet.

It would have been much better if the JS continued to attempt to reconnect to the server (with capped exponential back-off and such), but let me continue to read the page until it was actually back.

I could see this being an issue with intermittent connections such as on trains, or even when planning for a trip, opening the wanted pads in browser tabs, and then getting them all refreshed to nothing once without any Internet connection.

Aside from that, thanks a lot for your efforts, I really enjoy using Etherpad, it gets the work done and doesn’t get in the way!

**Comment by JohnMcLear** [comment]
Thanks for your issue.

Good news, this is already a setting the admin can set.

https://github.com/ether/etherpad-lite/blob/develop/settings.json.template#L353

**Comment by linkmauve** [comment]
Thanks! <3
