### ISSUE TITLE
Scrolling issue on timeline history

### ISSUE THREAD

**Issue by vince2bir** [ether/etherpad-lite#3992]
I'm unable to scroll to the end of file on the timeline history. (vertically)
https://pad.161803.eu.org/p/testing/timeslider#11

I have tried without plugins and with "no-skin" without luck.
What did I miss ?

v1.8.3

**Comment by JohnMcLear** [comment]
Yikes, bloody scrolling. ..  Sorry about this, we had test coverage for this but browser APIs restricted special keys/arrows etc. so we had to comment it out.

@seballot I think this on you buddy!  Sorry!

Good spot!  Thanks for pointing it out!  Will confirm this locally in a few mins

**Comment by seballot** [comment]
Hi! it's already fixed, waiting to be deployed in 1.8.4, sorry about that !

**Comment by JohnMcLear** [comment]
Yea, I have it live on https://video.etherpad.com/p/x8GsRW9KCxoljzaNY9zb/timeslider#4 -- Nice one @seballot  I can confirm the fix is in :)  OP needs to pull develop or wait for 1.8.4
