### ISSUE TITLE
etherpad-lite Dockerfile not works

### ISSUE THREAD

**Issue by codeschwarz** [ether/etherpad-lite#3997]
Hello, im trying to use the Dockerfile that is inside of etherpad-lite and it not works well.
The only change I do to Dockerfile is:
node version => FROM node:10.15.3  and some plugins to install. I dont change anything more.
Running at => Linux
docker-compose version =>  '3.7'
If you need more info let me know.
### Installing plugins
Step 11/15 : RUN for PLUGIN_NAME in ${ETHERPAD_PLUGINS}; do npm install "${PLUGIN_NAME}"; done
 ---> Running in be10c1c6e3ba
```
npm WARN saveError ENOENT: no such file or directory, open '/opt/etherpad-lite/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad-lite/package.json'
npm WARN etherpad-lite No description
npm WARN etherpad-lite No repository field.
npm WARN etherpad-lite No README data
npm WARN etherpad-lite No license field.

ep_page_view@0.5.24
added 1 package from 2 contributors and audited 731 packages in 2.967s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```
 **This happend in every plugin I want to install**
```
### Finish the installing plugins (running container with compose)
etherpad_app    | internal/modules/cjs/loader.js:584
etherpad_app    |     throw err;
etherpad_app    |     ^
etherpad_app    | 
etherpad_app    | Error: Cannot find module '/opt/etherpad-lite/node_modules/ep_etherpad-lite/node/server.js'
etherpad_app    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
etherpad_app    |     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
etherpad_app    |     at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
etherpad_app    |     at startup (internal/bootstrap/node.js:283:19)
etherpad_app    |     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
etherpad_app exited with code 1
```
Is this a bug? I can't reach this container works fine.. 
## How to replicate this error
1. Clone github repository: git clone https://github.com/ether/etherpad-lite.git
2. Edit Dockerfile and add:
 - ARG ETHERPAD_PLUGINS="ep_page_view ep_headings2 ep_align ep_comments_page ep_spellcheck"
 - FROM node:10.15.3, change it from default version in Dockerfile
3. Make a docker-compose, you can use this (basic)
```
version: '3.7'
services:
    etherpad_prueba:
        build:
            context: ./etherpad-lite/
            dockerfile: Dockerfile 
        ports:
            - "30001:9001"
        restart: always
        volumes:
            - "./data/prueba:/opt/etherpad-lite"
volumes:
    data: 
```
4. docker-compose up

With that you can reproduce errors. Thank you. If you need more info you can ask.

**Comment by JohnMcLear** [comment]
Please provide the exact commands you are typing to get to this error.

**Comment by codeschwarz** [comment]
> Please provide the exact commands you are typing to get to this error. We need steps to replicate. Generally I ask people to follow: https://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/ when writing new bug reports :) Thanks!

Edited

**Comment by JohnMcLear** [comment]
I edited your edits to include code blocks.  Does it work if you don't include any modifications IE the example config/setup?

**Comment by JohnMcLear** [comment]
What do you mean by "make a docker compose", please provide exact commands / steps to replicate.  I do not use docker.

**Comment by JohnMcLear** [comment]
Currently this is the steps to replicate..

```
git clone https://github.com/ether/etherpad-lite.git docker
cd docker/
sudo apt-get install docker-compose
...
```

**Comment by codeschwarz** [comment]
> Currently this is the steps to replicate..
> 
> ```
> git clone https://github.com/ether/etherpad-lite.git docker
> cd docker/
> sudo apt-get install docker-compose
> ...
> ```

Well I suppost you had docker / docker-compose install in your PC. What I mean with "make a docker-compose" is make a docker-compose file that create a container from that Dockerfile.(docker-compose file I share).

**Comment by codeschwarz** [comment]
> I edited your edits to include code blocks. Does it work if you don't include any modifications IE the example config/setup?

Still breaking if I use the Dockerfile without any modifications. Same error



etherpad_prueba_1  | internal/modules/cjs/loader.js:638
etherpad_prueba_1  |     throw err;
etherpad_prueba_1  |     ^
etherpad_prueba_1  | 
etherpad_prueba_1  | Error: Cannot find module '/opt/etherpad-lite/node_modules/ep_etherpad-lite/node/server.js'
etherpad_prueba_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
etherpad_prueba_1  |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
etherpad_prueba_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
etherpad_prueba_1  |     at startup (internal/bootstrap/node.js:283:19)
etherpad_prueba_1  |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by JohnMcLear** [comment]
It's still unclear how to do this..  

If I create a file called "docker-compose" containing 
```
version: '3.7'
services:
    etherpad_prueba:
        build:
            context: ./etherpad-lite/
            dockerfile: Dockerfile 
        ports:
            - "30001:9001"
        restart: always
        volumes:
            - "./data/prueba:/opt/etherpad-lite"
volumes:
    data: 
```

then run
```
docker-compose up
```

I get
```
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

Remember here, we're not Docker support, we know nothing about Docker so you need to hand hold with us to get it setup :)

**Comment by codeschwarz** [comment]
Oh I see sorry, execute in command line docker version, you will see what version you had installed of docker and then expecific in your docker-compose.yml file in field version (where i have 3.7) the version that is compatible with your docker. Details [compose file]( https://docs.docker.com/compose/compose-file/) . Im running docker in linux lastest version (19.03.0+)

My directory structure to reproduce is like this:
parting from home.
1. mkdir eherpad
2. cd etherpad
3. touch docker-compose.yml (and enter the code that I share)
4. git clone https://github.com/ether/etherpad-lite.git
5. In etherpad(directory) path,(where is docker-compose.yml file you created, NOT inside etherpad-lite, you need to execute command `docker-compose up` where the compose file is placed) execute  `docker-compose up`
6. Wait to compose do it things, and you will get the error. 
Think this is better explanation.

**Comment by muxator** [comment]
@codeschwarz, I just rebuilt the container following [the example in the docs](https://github.com/ether/etherpad-lite/blob/develop/doc/docker.md#examples), and it went fine:

```
docker build --build-arg ETHERPAD_PLUGINS="ep_comments_page ep_author_neat" --tag muxator/etherpad .
```

This the build step where plugins are installed:

```
[...]
Step 11/15 : RUN for PLUGIN_NAME in ${ETHERPAD_PLUGINS}; do npm install "${PLUGIN_NAME}"; done
 ---> Running in 9f46f8c1d9f5
npm WARN saveError ENOENT: no such file or directory, open '/opt/etherpad-lite/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad-lite/package.json'
npm WARN etherpad-lite No description
npm WARN etherpad-lite No repository field.
npm WARN etherpad-lite No README data
npm WARN etherpad-lite No license field.

+ ep_comments_page@0.1.4
added 33 packages from 25 contributors and audited 763 packages in 10.141s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/opt/etherpad-lite/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad-lite/package.json'
npm WARN etherpad-lite No description
npm WARN etherpad-lite No repository field.
npm WARN etherpad-lite No README data
npm WARN etherpad-lite No license field.

+ ep_author_neat@0.0.31
added 1 package from 2 contributors and audited 781 packages in 5.941s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 9f46f8c1d9f5
 ---> ba7e4885af0e
Step 12/15 : COPY --chown=etherpad:0 ./settings.json.docker /opt/etherpad-lite/settings.json
[...]
```

If you now run this container via:

```
docker run --rm --publish 9001:9001 muxator/etherpad
```

And connect to http://localhost:9001, you should see a working Etherpad with [`ep_comments_page`](https://github.com/ether/ep_comments) and `ep_author_neat` enabled and running.

Internally, the plugin installation is performed by npm. When npm installs Etherpad plugins, it **writes some messages to stderr**. This is normal, and the build progresses normally.

I am wondering if this has to do with the interaction with Docker Compose.

Could you please confirm that you are able to manually build a container following the instructions I just gave you (== in the documentation)?

If so, we can start debugging from there, and probably this issue either has to be closed or its title be updated to something more specific.

**Comment by codeschwarz** [comment]
I can confirm your solution works perfectly @muxator .
But I can confirm with docker-compose it dont work, because this error

`    etherpad_prueba_1 | internal/modules/cjs/loader.js:638
       etherpad_prueba_1 | throw err;
        etherpad_prueba_1 | ^
        etherpad_prueba_1 |
         etherpad_prueba_1 | Error: Cannot find module '/opt/etherpad-lite/node_modules        /ep_etherpad-lite/node/server.js'
`
Maybe I should create container like you did, and then use it in my docker-compose.

What I tried too was comment last line of Dockerfile (CMD["node"....]) and change it for a `RUN bin/run.sh` and it works, container works but it dont go out of that execution and compose cant finish the build of containers. 
I see in that script (bin/run.sh), at the last line, it execute `exec node "$SCRIPTPATH/node_modules/ep_etherpad-lite/node/server.js" "$@"` that it is the last CMD line in Dockerfile. Dont know if this can help. 
Thank you for your time

**Comment by codeschwarz** [comment]
Finaly found the problem: 
volumes are the problem. If you try to create a volume, container will throw you this error:

internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module '/opt/etherpad-lite/node_modules/ep_etherpad-lite/node/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Why? I really don't know. Times? Permisions inside container? If I have some update in the future or explanation I will post here.
If you have some explanation to this or theroy, it will be insterstring to know

# how to replicate problem 
### Build a basic image
` docker build  --tag prueba/etherpad . `
### Run container creating volume
 ` docker run --rm -p 9001:9001 -v /data2:/opt/etherpad-lite prueba/etherpad`

If you run the container without volumes works, as @muxator  did above, but not with volumes
Same thing in docker-compose.yml files, don't declare volumes and it will work.

**Comment by JohnMcLear** [comment]
Awesome research and good spot / job on the find :)

I have a feeling this is a docker problem though, perhaps the docker forums / user groups would be a good place to post this issue?

**Comment by rhansen** [comment]
I see you are binding `/data2` outside the container to `/opt/etherpad-lite` inside the container. Doing that completely shadows the Docker image's `/opt/etherpad-lite` directory. This could break Etherpad in all sorts of weird ways depending on the contents of your `/data2` directory.

Why are you binding `/data2` to `/opt/etherpad-lite`? There's probably a better way to accomplish what you're trying to do.

**Comment by rhansen** [comment]
I think this should be closed—I don't have any problems building the Docker image or running a container from that image.

**Comment by JohnMcLear** [comment]
Thanks @rhansen I'm inclined to agree.  I will ask for Docker users to please speak to your docker community before posting here.  We don't want the technical debt of Docker if possible <3
