### ISSUE TITLE
Performance issues with 1.8.3

### ISSUE THREAD

**Issue by barthalion** [ether/etherpad-lite#3999]
I have updated GNOME's etherpad-lite instance from 1.8.0 to 1.8.3 but it appears much slower than it was, to the point of being unusable.

To see it for yourself, go to https://etherpad.gnome.org and try to create new paste. It's either stuck `Loading` forever or gets to the editor after 30-60s depending on dice roll, while creating new paste usually timeouts; it's usually quickish when a pad was loaded before. It's still slower than https://video.etherpad.com.

The only relevant error in logs is `client - Uncaught TypeError: Cannot read property 'setStateIdle' of null`, however it happens only when the error is actually displayed in the browser, not on every request.

It is deployed on OpenShift (behind haproxy terminating SSL), which connects to apache, which connects to etherpad container. https://gitlab.gnome.org/Infrastructure/etherpad-web/-/tree/oscp-frontend/ and https://gitlab.gnome.org/Infrastructure/etherpad-web/-/tree/oscp-backend/ have files for the last two.

I'm a little bit clueless. Is there anything else I can check to make this bug report useful?

(Edit: it got somewhat better after removing some unmaintained plugins that were installed since forever but still seems slower to me when compared to video.etherpad.com).

**Comment by muxator** [comment]
Hi @barthalion, if GNOME is using Etherpad with mysql, you may be experiencing a performance regression that was indeed introduced in 1.8.3.

If this is the case, I hope to release **1.8.4** tonight.

**Comment by barthalion** [comment]
I was impatient and backported the fix. I can confirm it fixes the problem, in fact, our instance has never been so fast. Thanks!

**Comment by muxator** [comment]
Glad it helped!

If I manage to solve the [three remaining issues for the 1.8.4 milestone](https://github.com/ether/etherpad-lite/milestone/17), I'll release it today.

p.s.: thanks for working on GNOME from a KDE guy :smile:
