### ISSUE TITLE
How to secure API url in a different way through reverse proxy

### ISSUE THREAD

**Issue by flotho** [ether/etherpad-lite#4024]
Hi @JohnMcLear ,

Thanks for this great tool I'm tottaly fan and using it for a long time. So much activity and improvements here, congrats.

I would like to improve my configuration and I'm looking for advices. Just for sharing here is my conf : 
```
Etherpad version

Version number: 1.8.4

Git sha: 4644e7a
Installed plugins

ep_adminpads
ep_delete_empty_pads
ep_comments_page
ep_author_hover
ep_embedded_hyperlinks2
ep_font_family
ep_list_pads
ep_align
ep_etherpad-lite
ep_tables3
ep_table_of_contents
ep_mypads
ep_headings2

Installed parts

ep_headings2/main
ep_mypads/ep_mypads
ep_table_of_contents/ep_table_of_contents
ep_tables3/tables
ep_etherpad-lite/openapi
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/padreadonly
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/express
ep_align/main
ep_list_pads/ep_list_pads
ep_font_family/main
ep_embedded_hyperlinks2/main
ep_author_hover/ep_author_hover
ep_etherpad-lite/webaccess
ep_comments_page/comments_page
ep_etherpad-lite/static
ep_delete_empty_pads/ep_delete_empty_pads
ep_adminpads/ep_adminpads
```
This working perfectly behind a reverse proxy Apache letsencrypt

I added CAS authentication in my Reverse proxy and everything is doing fine even with mypads https://framagit.org/framasoft/Etherpad/ep_mypads/-/issues/234 
My point is that I would like to protect the /api url in a different way because I need that my Odoo application to be able to call the api url without authentication through CAS. 

So here is my question, does it looks to you "legal" to use specific location for url matching /api and have different authentication method for / url ?

I asked this question because I tried many location pattern in my apache and as it used to work for other solution it failed here.

Here is the simple additionnaly conf I added to the apache RP before the Location / : 
```
.../...
<Location /api/ >
    Require all granted
    ProxyPass http://10.0.199.7:9001/api/ retry=0 timeout=30
	ProxyPassReverse http://10.0.199.7:9001/api/

</Location>

<Location / >
	Authtype CAS
	Require valid-user
	CASAuthNHeader Cas-User
        #Require all granted
    ProxyPass  http://10.0.199.7:9001/ retry=0 timeout=30
	ProxyPassReverse  http://10.0.199.7:9001/
</Location>

.../...
```
If it looks Ok to you I'll dig in with apache conf.

Thanks in advance for the time spent on reading this issue.

Regards

**Comment by JohnMcLear** [comment]
Try ep_helmet for additional security.

I don't know anything about CAS or Odoo, sorry!  But having specific rewrites for /API/ should be totally feasible and work fine!

**Comment by flotho** [comment]
Hi @JohnMcLear ,

GReat thanks for this fast answer, I'll share the solution to you once solved.

Regards

**Comment by flotho** [comment]
Damned,

It was so easy, precedence in Apache directive did the trick thanks to this https://serverfault.com/questions/391457/how-does-apache-merge-multiple-matching-location-sections

So I make the opposite :
```
<Location / >
	Authtype CAS
	Require valid-user
	CASAuthNHeader Cas-User
        #Require all granted
    ProxyPass  http://10.0.199.7:9001/ retry=0 timeout=30
	ProxyPassReverse  http://10.0.199.7:9001/
</Location>

<Location /api/ >
    Require all granted
    ProxyPass http://10.0.199.7:9001/api/ retry=0 timeout=30
	ProxyPassReverse http://10.0.199.7:9001/api/

</Location>
```

And it worked out !

Thanks
