### ISSUE TITLE
Skin Variant doesn't work

### ISSUE THREAD

**Issue by Redglouby** [ether/etherpad-lite#4025]
I have no idea why, but the skin variant does not work at all. I use the skin editor provided in the settings.json (on a web interface), then I copy/past the parameters

"skinVariants": "dark-toolbar super-dark-background super-light-editor",

The section is not commented out - And there is no option that indicates where I can turn this feature on. So I assumed it was enabled, but when I create a new pad, nothing works. It is still the very first skin for colibri that appears on my screen. Does anyone know how to  solve this issue ?
I am running etherpad on a Debian-10 system, and I use a nginx proxy to redirect etherpad on a domain name. I have the latest version of nginx and of etherpad, as I downloaded everything just yesterday. 
Warning: I am a beginner on Linux

**Comment by JohnMcLear** [comment]
Did you restart Etherpad after editing settings.json?  Also did you clear browser cache etc.  Also is minify/maxAge on / off / set to a 0 value?

**Comment by Redglouby** [comment]
I switched minify to false (as it was activated before), disabled maxAge, cleared my browser's cache, enabled the option "trustProxy" (which I forgot ^^'), and there is still no difference on any of my pages. I have restarted Etherpad multiple times, tried with two different browsers and created a new pad for every change I made in my conf file, and nothing changed.

**Comment by JohnMcLear** [comment]
Is this instance public?

**Comment by JohnMcLear** [comment]
Try copy / paste this to bottom of settings.json

```
,
  "skinVariants": "super-dark-toolbar super-dark-background super-dark-editor full-width-editor",
```

Also make sure skinName is set to ``colibris`` :)

**Comment by Redglouby** [comment]
Yes, my instance is public, and I have my skinName set to colibris. 
I have tried this, but etherpad crashed when I launched it. I also commented out the first line so as to avoid any conflict. 
I am running etherpad with some plugins, do you think they might cause some problems ? 
![msedge_msvCYy2F9B](https://user-images.githubusercontent.com/63715603/82190607-8f7b8a80-98f1-11ea-9cd4-f2f7cf156cf1.png)

**Comment by Redglouby** [comment]
I have solved my problem :) 
It appears that the plugin "offline_edit" was blocking the application of my theme. 
Thanks for helping me.

**Comment by JohnMcLear** [comment]
Ah I haven't worked on offline edit recently.  Does it even work?  Can you create an issue in the plugins repo please?
