### ISSUE TITLE
Problem with the JQuery plugin

### ISSUE THREAD

**Issue by romainmunier** [ether/etherpad-lite#4029]
When I use the JQuery plugin in my own site, an error appears and I can't solve it. This error is the following: 

`Refused to display 'https://video.etherpad.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Comment by JohnMcLear** [comment]
You can solve this; don't use video.etherpad.com in your site.  Host your own Etherpad instance and use that in your site.

At least I know ``ep_helmet`` is doing it's job ;)

**Comment by JohnMcLear** [comment]
To add to this, I was stupid and left "embed" on the UI :D  

https://github.com/tjwelde/ep_remove_embed/pull/2 - waiting on this before installing the plugin.
