### ISSUE TITLE
Show inactive formatting buttons in read only pads

### ISSUE THREAD

**Issue by mir123** [ether/etherpad-lite#4032]
I would like to still show formatting buttons (bold, underline, strikethrough) in read only pads but to have them be inactive, i.e. nothing happens when they get clicked. I see the function at toolbar.js that checks for isReadOnly and wipes out the buttons array, but commenting this out produces active buttons that allow editing. 

Could there be a way to render the buttons but to remove the click event? Any suggestion on how to make the buttons "harmless"?

**Comment by JohnMcLear** [comment]
Create a plugin that sets them to disabled.

**Comment by mir123** [comment]
What would setting them to disabled imply? Where in the code is the click event attached?

**Comment by JohnMcLear** [comment]
it would do what you want...  the click event handlers is in pad_editbar.js or something afaik, but it sounds like you want a single client side plugin that just sets the attribute ``disabled`` to ``disabled``, don't hack on core, use plugins else you wont be able to upgrade/update..

**Comment by mir123** [comment]
Yes, you are correct, bad idea to hack on the core. I thought about the client-side disabled, however could someone turn it to enabled on the client and edit the text?

**Comment by JohnMcLear** [comment]
Stupid question, but why do you want to still show them if they can't be used?  What are you trying to achieve?

**Comment by JohnMcLear** [comment]
> 
> 
> Yes, you are correct, bad idea to hack on the core. I thought about the client-side disabled, however could someone turn it to enabled on the client and edit the text?

No.  Read pad ID commits are rejected by the `PadMessageHandler``

**Comment by mir123** [comment]
> Stupid question, but why do you want to still show them if they can't be used? What are you trying to achieve?

For aesthetic reasons. It's for a website where people can see other people writing, and the read only pad should look like a regular pad as much as possible. Which means I also would like to have a caret, but the cursortrace plugin seems not to be working  (separate issue!).

**Comment by JohnMcLear** [comment]
@mir123 just fyi we're not gonna do this for you, you will need to do this yourself.  Just in case you wondered..  This will need to be a plugin.  Hope that's clear :)

**Comment by mir123** [comment]
@JohnMcLear clear and working on it! :)

So I'm using the eejsBlock_editbarMenuLeft and editbarMenuRight for this, checking the args.renderContext.isReadOnly property to either leave the editbars alone or send the buttons (since the buttons  on the editbar left are cleared by the menu function in toolbar.js). I'm directly inserting the HTML, but I know this is not the best solution. I haven't found the way to remove and add specific buttons using the editbar controller.

Here's the plugin code I have so far to insert bold, italic and underline "buttons" (non-working) on the left and to leave just the author list on the right:

```
exports.eejsBlock_editbarMenuLeft = function (hook_name, args, cb) {
  if(args.renderContext.isReadOnly) {args.content = '<li data-type="button"><a class="grouped-left" aria-label="Bold (Ctrl+B)"><span class=" buttonicon buttonicon-bold" aria-label="Bold (Ctrl+B)" disabled></button></a></li><li data-type="button"><a class="grouped-middle" aria-label="Italic (Ctrl+I)"><span class=" buttonicon buttonicon-italic" aria-label="Italic (Ctrl+I)" disabled></button></a></li><li data-type="button"><a class="grouped-middle" aria-label="Underline (Ctrl+U)"><span class=" buttonicon buttonicon-underline" aria-label="Underline (Ctrl+U)" disabled></button></a></li>'}
  return cb();
}

exports.eejsBlock_editbarMenuRight = function (hook_name, args, cb) {
  if(args.renderContext.isReadOnly) {args.content = '<li data-type="button" data-key="showusers"><a class="" data-l10n-id="pad.toolbar.showusers.title"><button class=" buttonicon buttonicon-showusers" data-l10n-id="pad.toolbar.showusers.title"></button></a></li>'}
  return cb();
}
```

**Comment by JohnMcLear** [comment]
I think it's safe to close this now as OP is writing a plugin to make what he wants.
