### ISSUE TITLE
Issue in Installing draw plugin into etherpad

### ISSUE THREAD

**Issue by shivSD** [ether/etherpad-lite#4033]
I have installed draw plugin into etherpad and i see the icon/button in the etherpad screen on the top left, but when i click on it says "**draw.etherpad.org’s server IP address could not be found.**"
Please can you help me in resolving this issue.

**Comment by JohnMcLear** [comment]
Host an Etherdraw instance.  We don't host one at the moment.  https://github.com/johnmclear/draw
