### ISSUE TITLE
Should I publish my plugin straight away?

### ISSUE THREAD

**Issue by mir123** [ether/etherpad-lite#4038]
I've created a plugin (https://github.com/mir123/etherpad-solar), and I'm wondering whether I should publish it to npm while it's still experimental or should I wait for more feedback here? I don't have time to write tests and so on at this point and don't know the etiquette. Cheers!

**Comment by JohnMcLear** [comment]
1. We just call it Etherpad now.  You can drop the lite.

1. I'd make the settings come from settings.json before publishing.

My genera rule is publish once someone can use it straight from the admin ui.  That's usually 0.01 then 0.1.0 is stable with frontend test coverage.

0.2 is usually accessibility ie language support.

Awesome idea for plugin btw.  I use dark all day now so this is something I would use.
