### ISSUE TITLE
Configuring context path

### ISSUE THREAD

**Issue by lfoppiano** [ether/etherpad-lite#4043]
Hi all, 
   I have a server with multiple services running on it, and I would like to map   ``http://myserver.bla/pads `` to etherpad. 

It is possible? It seems that etherpad does not allow the configuration of a context path in the application, so all the solutions behind the reverse proxy have a redirect from `/` to `/myContext_path`

is it possible to configure the context path anywhere? 

Thank you in advance

**Comment by JohnMcLear** [comment]
You would use a reverse proxy to accomplish this: https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy

You can not set Etherpad to run on a subdirectory, nor would you want to :)  A reverse proxy is the correct tool for this job.

**Comment by lfoppiano** [comment]
I use already a reverse proxy which assigns different context paths to different applications, therefore I cannot define a redirect from / to /whatever (as seems to be suggested [here](https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#from-subdirectory-url). 

AFAIK this can work if the application generates its own link internally allowing a context path.

**Comment by JohnMcLear** [comment]
Please read the wiki page.  Just rewrite a url ie /pad to Etherpad

**Comment by lfoppiano** [comment]
Thanks @JohnMcLear. 

I've used the following configuration on my apache configuration: 

```
   RewriteRule ^/pad$ /pad/ [R]
    <Location /pad>
       RewriteEngine On
       RewriteRule ^/pad$ /pad/ [R]
       RewriteRule /pad/(.*) /$1 [R]
       ProxyPass http://127.0.0.1:9001
       ProxyPassReverse http://127.0.0.1:9001
    </Location>
    <Location /pad/socket.io>
        # Taken from https://github.com/ether/etherpad-lite/issues/2318#issuecomment-63548542
        RewriteEngine On
        RewriteCond %{QUERY_STRING} transport=websocket    [NC]
        RewriteRule /(.*) ws://localhost:9001/socket.io/$1 [P,L]
        ProxyPass http://localhost:9001/socket.io retry=0 timeout=30
        ProxyPassReverse http://localhost:9001/socket.io
    </Location>

    <Location /static>
        Header add host "$host"
        RewriteRule /static/(.*) /static/$1 [R]
        ProxyPass http://localhost:9001/
    </Location>

```
