### ISSUE TITLE
How to auth user from jitsi to create new pad 

### ISSUE THREAD

**Issue by tech62** [ether/etherpad-lite#4046]
Hi,

I want to restrict utilisation of my etherpad-lite service to my jitsi users and i search how to authenticate theses users to etherpad to create / share pad.

Anyone can help me ?

Thanks !

**Comment by JohnMcLear** [comment]
What does jitsi use for Auth?  You would just implement a plugin that supports that. For example oauth.

**Comment by tech62** [comment]
I thinking we could use the builtin authentification system used by jitsi (xmpp) or ldap, but there is no docs with how to deploy that :/
I'm not a developper, just submitting the idea and see if it's possible ;)

**Comment by JohnMcLear** [comment]
xmpp is a comms protocal, ldap is auth.  

https://www.npmjs.org/package/ep_ldapauth

**Comment by tech62** [comment]
My bad, i wanted to say prosody not xmpp, xmpp use prosody as auth.
