### ISSUE TITLE
Plugin not importing settings

### ISSUE THREAD

**Issue by ISNIT0** [ether/etherpad-lite#4047]
# Error
```bash
Failed to load 'ep_plugin/index' for 'ep_plugin/ep_plugin/hooks/import': Error: Cannot find module 'ep_etherpad-lite/node/utils/Settings'
```
# Run command
```bash
npm i ../ep_plugin && ./bin/debugRun.sh
```
# `ep.json`
```json
{
  "parts": [
    {
      "name": "ep_plugin",
      "client_hooks": {
        "documentReady": "ep_plugin/static/js/index:clientVars"
      },
      "hooks": {
        "clientVars": "ep_plugin/index:clientVars"
      }
    }
  ]
}
```

# `./index.js`
```javascript
var settings = require('ep_etherpad-lite/node/utils/Settings');

exports.clientVars = function (hook, context, callback) {
    console.log(settings);
    return callback({
    });
};
```

Using latest master of this branch

**Comment by JohnMcLear** [comment]
Look at how other plugins are getting clientVars.  I m sure his is working fine.  See ep_draw for a really basic example..

**Comment by ISNIT0** [comment]
Yes, most of what I have so far is absolutely copy-pasted. I just don't understand why this is happening. The server throws an error while loading the plugin file using code I copy-pasted.

**Comment by ISNIT0** [comment]
For future reference/someone else with this issue...
It seems the re-compilation step was treating the context of the file weirdly when I used `npm link ../plugin` or `npm i ../plugin`.

As a temp fix for development I ran `npm i ../etherpad-lite/src` from in my plugin src folder.
