### ISSUE TITLE
POST or PUT: 405 Method Not Allowed

### ISSUE THREAD

**Issue by filehoarder** [ether/etherpad-lite#4048]
Hello together,
im working on a plugin to change the password. for this i want to do a post or put request in the following way:

server-side:
args.app.post("/password_change", function .....);

client side:
$.ajax({ type: "POST", url: "/password_change", ...});

but im getting a http response 405, saying only get and head are allowed.. with a get request my functions are working but i want to use an other request type.

is there any way to change this behaviour?

thank you

**Comment by JohnMcLear** [comment]
Disclaimer: Is this the password within Etherpad itself?  Because we're hopefully dropping that in Etherpad 2.0.

If you are changing password as a session, you could use the socket message instead of POST/GET?  We encourage comms over sockets usually, do you have them available?  If so, I'd use that then you can check the sessionID is valid and is on the padId etc.

**Comment by filehoarder** [comment]
thanks for the quick response!

it is an extension to the ep_hash_auth plugin (https://github.com/filehoarder/ep_password_change)

socket messages should work. i will give it a try. do i create them with the socketio server-side hook?

**Comment by JohnMcLear** [comment]
afaik handleMessage hook.  Peep ep_set_title for a basic example

**Comment by filehoarder** [comment]
can i use them on the index page too or only on the pad page?

**Comment by JohnMcLear** [comment]
only pad.  index page doesn't have sockets afaik

**Comment by filehoarder** [comment]
thanks for the help! i will think about putting the dialog there

**Comment by JohnMcLear** [comment]
post should be available though btw, does https://www.npmjs.org/package/ep_post_data not work?

https://www.npmjs.com/package/ep_post_message ?

**Comment by filehoarder** [comment]
https://github.com/JohnMcLear/ep_post_data/commit/42ad4f594a7b004f07493ffb5c98c2ab1a98aa83
this change seems to fix it for me. thank you very much, you saved the day!

**Comment by JohnMcLear** [comment]
Win.

**Comment by filehoarder** [comment]
i celebrated too early.. as soon as is add a data payload to the request i still get this issue. still not able to trackdown why this happens

**Comment by filehoarder** [comment]
https://github.com/filehoarder/ep_password_change/tree/post

as soon as i wrote the comment it started to work again.. now i have the problem that the payload is empty server-side. 

i assume that there are differences in loading which are causing this indeterminist behavior of working/not working.. are there any more components i should add to the "post" key in the ep.json file?
