### ISSUE TITLE
When one pad has an error, it takes down the server

### ISSUE THREAD

**Issue by LucasCioffi** [ether/etherpad-lite#4052]
Hi All, something strange happened today where when one particular pad loaded, it seemed to take the whole server down, causing a "502 Bad Gateway Error" for any other pads that I tried to load, and also when I reloaded the pad that had a problem.

Before I reloaded it, I saw this error on the pad that had a problem.  What should I do to debug it?  
Thank you.
```
An error occured
The error was reported with the following id: 'QLRc9Z9YfBJLhORwpv02'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: QLRc9Z9YfBJLhORwpv02
URL: https://MY_EXAMPLE.com/pad/abc-32
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Uncaught TypeError: Cannot read property 'setChannelState' of null in https://notes.MY_EXAMPLE.com/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 266'
```

**Comment by JohnMcLear** [comment]
Send a copy of the server console :)

It could be due to a number of things, the most common being an improperly configured server database or an old version of Etherpad.

**Comment by JohnMcLear** [comment]
Will close until more data is available, please re-open if you have info.

**Comment by LucasCioffi** [comment]
Hello @JohnMcLear when I SSH into the server, would you like me to get the server logs or something else?  

I'm running Etherpad with Screen.  Which directory would you advise I go into to get the data you need?  What command would I run there to see the "server console"?
<img width="1378" alt="Screen Shot 2020-06-01 at 7 48 09 PM" src="https://user-images.githubusercontent.com/1825103/83465142-ee3c1a80-a440-11ea-8e01-260d2cbf4415.png">


Thank you!

**Comment by JohnMcLear** [comment]
@LucasCioffi It depends how your logging is setup.

Your error should have been in the screen if you run in a screen...  

Just scroll up till you find the error.

You should prolly do

```
screen -S etherpad
bin/fastRun.sh
```

so the screen doesn't disappear if Etherpad does...??
