### ISSUE TITLE
ajax api call error after upgrading to 1.83 and 1.8.4

### ISSUE THREAD

**Issue by tom-chase** [ether/etherpad-lite#4067]
HI, I encountered this error after upgrading from 1.8.0 to either 1.8.3 or 1.8.4.  Nothing else changed with my client-side js code, and the api calls worked fine in 1.8.0.  Below are the error messages and the api call code.  I am not a professional coder and apologize if I'm missing something simple.  I am embedding this in a 3rd-party site and I can only work with adding js scripts.  
This is a great tool and thank you for your help!

![Untitled_1](https://user-images.githubusercontent.com/51177658/83400919-b8ac1880-a3d1-11ea-8c5a-729cdffa04c0.png)

This is the debugging response I get when I click the link in the above console error message

![Untitled_2](https://user-images.githubusercontent.com/51177658/83400938-c19cea00-a3d1-11ea-85c4-cd9025f257ba.png)
```
  $.ajax({
    type: "POST",
     url: apiHost + "createGroupIfNotExistsFor?apikey=" + apikey + "&groupMapper=" + groupId +  "&jsonp=?",
    success: function (result) {
                console.log(result);    
  }});
```

This is a great tool and thank you for your help!

**Comment by JohnMcLear** [comment]
Try roll back and see if it persists.  If it does then re-open this issue.  The issue looks very related to your code (not Etherpads).

**Comment by tom-chase** [comment]
Thanks, John.  I've run fresh installations of 1.8.0 and 1.8.4 in docker containers from the same configurations (from debian 9 image, nodejs 12.x, nginx), except to clone the different EP branches.  I didn't change the client-side code, except to update the api version to 1.2.14.  The api calls in my client-side code work for 1.8.0 but I get the above errors when running 1.8.4.  Upon further investigation, the problem is a jsonp parser error:

Result: parsererror Error: jQuery351083446219935612_1591113408405 was not called 200 load

From what I can find online, it sounds like the server should be doing something related to the callback function.  Please let me know if you need more info.  Thanks again, Tom.

**Comment by JohnMcLear** [comment]
try put your client side JS through a JS validator.

**Comment by tom-chase** [comment]
It's clean.

**Comment by JohnMcLear** [comment]
Okay try use git bisect to see if you can find the offending commit.  Search for mclear git bisect if you need a step by step guide.

**Comment by tom-chase** [comment]
Here is the offending commit info -

25e081ac89c24b3236ae60491f6ca06b4f05b283 is the first bad commit
commit 25e081ac89c24b3236ae60491f6ca06b4f05b283
Author: Viljami Kuosmanen <viljami.kuosmanen@futurice.com>
Date:   Sun Mar 29 16:25:52 2020 +0200

    openapi: implement API handler with openapi-backend

    - Tests pass ✅
    - Added openapi-backend hook
    - Generating OpenAPI v3 definitions for each API version
    - Definitions served /api/openapi.json /api/{version}/openapi.json

**Comment by tom-chase** [comment]
Hi @JohnMcLear, I found the line with the missing ) in openapi.js.  I was going to try to make a pull request but I'm not familiar with making the test to demonstrate the bug, which is described above.  This change fixed the problem (after a server reboot):

 src/node/hooks/express/openapi.js  - Line 691

        // support jsonp response format
        if (req.query.jsonp && isValidJSONPName.check(req.query.jsonp)) {
          res.header('Content-Type', 'application/javascript');
-          response = `${req.query.jsonp}(${JSON.stringify(response)}`;
+          response = `${req.query.jsonp}(${JSON.stringify(response)})`;
        }

        // send response
        return res.send(response);
      });

Thanks for your help and this cool tool!

**Comment by JohnMcLear** [comment]
Good find.  Will fix.
