### ISSUE TITLE
Export from timeslider does not work for numeric padid

### ISSUE THREAD

**Issue by rittmeier** [ether/etherpad-lite#4071]
If you have a pad with a numeric PadID like "42", the export feature will not work from timeslider, as the export links are not generated properly.

Assume your pad at https://pad.helloworld.com/p/42
Then the export link for the pad to pdf is https://pad.helloworld.com/p/42/export/pdf
A working link to export rev 23 to pdf would be https://pad.helloworld.com/p/42/23/export/pdf

Unfortunately, etherpad-lite currently generates the following link:
https://pad.helloworld.com/42/23/export/pdf

I could identify 
https://github.com/ether/etherpad-lite/blob/09ddfb9e20f21872b1c99dbdac2ce9a2659d6129/src/static/js/timeslider.js#L150 as the line generating the export url.
For a numeric padid the first group matches "https://pad.helloworld.com". For a textual oder mixed padid the first group matches "https://pad.helloworld.com/p".

**Comment by JohnMcLear** [comment]
Confirmed.  Fixing today.

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/pull/4073/files

Please test this PR.
