### ISSUE TITLE
[Bug] Error message after each click in the pad (Version 1.8.4)

### ISSUE THREAD

**Issue by michaelflohr** [ether/etherpad-lite#4079]
We have integrated the latest version of Etherpad (1.8.4) into our platform.

The following plugins are also installed:
* ep_font_color
* ep_comments_page
* ep_embedded_hyperlinks_2
* ep_heading2
* ep-align
* ep_webpack
* ep_author_hover
* ep_table_of_contents

## Server Setup Information:
-  Version of Etherpad: 1.8.4
-  Operating System: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64)
-  Deployment Method: snap
-  Number of Running Instances: 1
-  DB Replicaset Oplog: (default)
-  NodeJS Version: v8.17.0
-  MongoDB Version: v3.6.3

## Error message (see screenshot)
![grafik](https://user-images.githubusercontent.com/54441922/83734440-4cd6e380-a64f-11ea-82f1-e2538dede33c.png)

Error occurs independently of browser (Firefox, Chrome).

## Replication error
* Create new pad and type in text. Error appears immediately.
* Open existing pad and click with mouse on any position. Error appears immediately.

**Comment by JohnMcLear** [comment]
1. Do you get this experience w/ out any plugins installed?
1. Do you get any errors in client console?
1. Do you get any errors in server console?

We run automated tests against ether/etherpad-lite so it's highly likely this is a problem caused by something else.

**Comment by michaelflohr** [comment]
Thanks @JohnMcLear . We have uninstalled ep_webpack. This seems to work for now. We will contact you if the error occurs again.
