### ISSUE TITLE
Broken install after git pull

### ISSUE THREAD

**Issue by tigexplorer** [ether/etherpad-lite#4080]
I've made a `git pull` for update my install. 

Now it looks like this. What can I do?

![etherpad_update_fail](https://user-images.githubusercontent.com/43775552/83772680-ee782800-a683-11ea-9c7b-7267578e22f9.png)

**Comment by JohnMcLear** [comment]
Restart Etherpad ?  Restarting is usually required after doing a ``git pull``

Further reading on how to file issues is here: https://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/

If you still have a problem after restart then please let me know and I will re-open the issue.

**Comment by tigexplorer** [comment]
Before the `git pull` I've stopped etherpad with `sudo systemctl stop etherpad.service`. After updating, I've restarted with `sudo systemctl start etherpad.service`. That seams leading to the misbehavior. 

Instead of using `systemctl stop start`, it seams one *must* execute `bin/run.sh` after updating. 

Maybe, it can be more precisely described in the Readme?
