### ISSUE TITLE
Installation on managed VPS

### ISSUE THREAD

**Issue by thomasottogalli** [ether/etherpad-lite#4085]
Hello to all,
I finally resolved to ask for help concerning the installation and setup on a managed VPS (hosted by Infomaniak)
I spent a long time reading the docs and can't get past the first steps (installing node, installing etherpad-lite, running via ssh console, etherpad on 127.0.0.1:9001)
I still have no clue on how to access etherpad interface via url on a browser.
I know so far that the VPS runs Debian Jessie.

Thank you for reading and if you could enlighten me, that would be awesome !

**Comment by JohnMcLear** [comment]
Please read: https://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/

Provide things like debug output, errors etc.  Currently we're in the dark.

**Comment by thomasottogalli** [comment]
Kind of figured it out... 
I'll post this because it might be of some help.
For people with no control over apache, create or edit your .htaccess file and add these lines (worked for me, -ish : still have small issues to figure out) : 
`DirectoryIndex ""`
`RewriteEngine On`
`RewriteRule ^(.*)$ http://127.0.0.1:9001/$1 [L,P]`
The IP should be the same as the one in the settings.json (I changed mine from 0.0.0.0 to 127.0.0.1)
Then you should view etherpad in the browser via url (ex: https://subdomain.domain.com/etherpadFolderName)
