### ISSUE TITLE
Add a docker-compose file

### ISSUE THREAD

**Issue by Niwla23** [ether/etherpad-lite#4095]
It would be good if there would be a docker-compose.yml file allowing one command deploys without needing to set up a database manually

**Comment by JohnMcLear** [comment]
Test this: https://github.com/ether/etherpad-lite/pull/3855

and if it works comment on the PR.

**Comment by Niwla23** [comment]
Thanks @JohnMcLear it works when you tweak some things (set the image name manually and put the ports there)
