### ISSUE TITLE
Fails to load client modules

### ISSUE THREAD

**Issue by mir123** [ether/etherpad-lite#4101]
I'm at my wit's end trying to figure this one out. Etherpad fails to load client modules at two plugins in development. Modules attached to server hooks load ok. Other plugin client modules load ok too. 

On the JS console:

```
Failed to load 'ep_solar/static/js/index:diayNoche' for 'ep_solar/solar/client_hooks/aceSetAuthorStyle': Error: The module at "ep_solar/static/js/index" does not exist. ace2_common.js:14728:17
```
But `etherpad-lite/node_modules/ep_solar/static/js/index.js` does indeed exist...

the `ep.json`:

```
{
  "parts": [
    {
      "name": "solar",
      "client_hooks": {
        "aceSetAuthorStyle": "ep_solar/static/js/index:diayNoche"
      },
      "hooks": {
        "clientVars": "ep_solar/index"
      }
    }
  ]
}
```

I can see it's at `function _designatedRequire` in `require-kernel.js` where it fails. On the syslog I get: 

```
[ERROR] console - #033[39mError compressing JS (../../node_modules/ep_solar/static/js/index.js) using UglifyJS { inspect: [Function: inspect] }
```

**Comment by JohnMcLear** [comment]
You need to export the function..

```
exports.aceSetAuthorStyle = function(){
  ... some thing
}
```

**Comment by mir123** [comment]
The issue seems to be with minifying and UglifyJS. It needs code to be in ES5, so in the case of ep_solar, a default function parameter declaration,

```
function solarElevation(latitude, longitude, date = new Date()) {
...
```

Is in ES2015 format, when changed to 

```
function solarElevation(latitude, longitude, date) {
    date = (typeof date !== 'undefined') ?  date : new Date();
...
```
It works. Similarly, `const` declarations didn't pass the UglifyJS test before minifying. Not minifying, however, works ok as the code is sent to the browser and it interprets it ok.

The plugin documentation should include the notice that code needs to be ES5 compliant. 

Awaiting further tests to confirm.

**Comment by JohnMcLear** [comment]
Use ``develop`` we use ``terser`` instead of ``uglify-js`` which supports the ES6.

So TLDR; Update but if you want your plugin to work < 1.8.~5 you should not use methods not supported by ``uglify``.  ``uglify`` has been present in Etherpad for a long time and hundereds of plugins work fine with this dependency..  

<3
