### ISSUE TITLE
timeslider:  why isn't it awesome?

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4102]
This is a musings/dump pad on my thoughts on the timeslider.  

Essentially the timeslider is a method to review a pad both present and past.  I recently patched up ep_diffview which allows a user to get a diff between two versions.  This is rather basic/rudimentary but it did inspire me to further think about how the timeslider UX could be improved and in general how a "viewer" or "forker" might intereact with a pad.

* Viewer: someone watching a pad or looking to see how things have changed for archeogical or historcal purposes.  For example a fact checker.

* forker: someone reviewing a pad who liked it's contents at point a, b, c but wants to diverge at point d(think Git forking) to create a new pad to continue contributing at point d.

The timeslider is a hugely overlooked function and a real Unique feature to Etherpad.  With some effort and some guidance

## What's broken/needs fixing
  Things feel slow (no loading animation) - https://github.com/ether/etherpad-lite/issues/2207
  It's not in the pad interface (it could be) and for example the read only view could just be the timeslider view.  A whole new interface feels kinda pointless and possibly a mistake during initial implementation.
  JS error on rev#0: https://github.com/ether/etherpad-lite/issues/4100

## What does the timeslider do for me?
1. I want to know who changed what ,when
  "x added y to line xxyy -- so diff but with authors"?
1. I want to know what I missed since I last saw the pad?
  Keep record of when I was last active on pad.
1. I want to follow a specific author
1. I want to follow a specific heading (portion) 
1. I want to follow a pad
  Go to pad contents as it's changed
1. I want to just follow history
  Going to rev 0 of a really big pad just hangs browser

``pad.collabClient.getCurrentRevisionNumber()`` can be used to get the current revision number.

https://hal.inria.fr/hal-01882069/document is interesting.. 

> Our findings show that:(1)about half of the pads have been edited by a single author, witnessing no collaborationwhatsoever;(2)space-collaboration is commonplace, but is usually asynchronous, with authors taking turnsin editing co-authored document parts;(3)spacetime-collaboration happens very rarely, calling into question the need of very fine-grained conflict resolution mechanisms, document models, and user interfaces;

**Comment by edsaperia** [comment]
It's surprising that there's no revert function. Of course it is possible to do manually. Primary use in my case is reverting vandalism - someone comes and deletes a chunk of a page, and you want to undo it. Seeing edits by a specific author would be helpful here.

**Comment by JohnMcLear** [comment]
@edsaperia there is a plugin for revert.

**Comment by JohnMcLear** [comment]
Okay so here is the progress.

1. A pr is in that follows new content as it lands in the timeslider.  Solves 5.

2. A plugin called ep_what_did_i_miss is in which solves 2.

3. A plugin called ep_follow_author fixes 3.

4. A plugin called ep_who_did_what provided a method to see pad history in a report format.  Solves 1.

The what did I miss plugin is probably the most important because it lets users know that history review is a thing and links the pad to timeslider gracefully.  

The functionality is welcome to be merged into core, it's all Apache2 licensed.

I'm going to step away from this now knowing that sufficient progress has been made and it's up to the community to vote with their installs if they want the functionality in core.  

We will obviously merge the most popular plugins into core.

**Comment by edsaperia** [comment]
Thank you!
