### ISSUE TITLE
Authorship colors cover text in some cases

### ISSUE THREAD

**Issue by cboylan** [ether/etherpad-lite#4106]
On version 1.8.4 using the no-skin skin we've found that authorship colors cover bits of text, particularly the "tails" of characters like 'y' and 'g'. Version 1.8.0 doesn't exhibit this behavior. Visually this seems to happen because the next line's authorship colors cover a portion of the previous line. With 1.8.0 there was a distinct boundary between colors on each line.

Looking at the commit log I expect that 5fd6aeeea62674cecf997421546a675d91cf45ef is a likely culprit, but I don't know enough about CSS to know for sure.

I've attached screenshots of 1.8.0 and 1.8.4 renders to show the problem (both were rendered in Firefox 77 64bit Linux). The etherpad deployments were done with the docker.io/etherpad/etherpad:1.8.0 and docker.io/etherpad/etherpad:1.8.4 docker images.

1.8.0 without overlap:

![etherpad-1 8 0-no-overlap](https://user-images.githubusercontent.com/231403/84318000-95e0d900-ab22-11ea-80a3-d18c9bb863d6.png)

1.8.4 with overlap:

![etherpad-1 8 4-overlap](https://user-images.githubusercontent.com/231403/84318063-ae50f380-ab22-11ea-8e56-2cbedce7f711.png)

**Comment by cboylan** [comment]
I've managed to do more investigating to figure out the source of this issue. 08930fae053776e166fac8e4521579c41a3ac3a8 introduced padding to the top and bottom of innerdocbody span of 6px. This caused the author color spans to overlap with each other.

I managed to address this against version 1.8.4 by updating the padding there to 0 which makes this render more similarly to 1.8.0 with clear row borders. When I went to apply this to the develop branch I discovered that 7aa7e02e273c66936516f1ba87f435e4fe206c75 appears to have fixed this in a different manner. The text no longer gets cut off, but the lack of borders between rows remains. I think this is likely fine for us.

If we were to deploy 1.8.4 with innerdocbody span set with `padding: 0 0 !important` while we wait for a release of 1.8.5 do you see that causing any problems?

**Comment by JohnMcLear** [comment]
Cc'ing @seballot

**Comment by JohnMcLear** [comment]
So this is fixed in develop?

**Comment by cboylan** [comment]
Yes, I think it is largely addressed on develop. At this point I think the only reason I'm holding it open is to get thoughts on whether or not the old 1.8.0 behavior of having distinct borders between lines is desirable. I don't think it is a functional issue like the cut off text was on 1.8.4 though.

Feel free to close this if the current border less (between line rows) author colors is what people prefer going forward.

**Comment by seballot** [comment]
Hi ! I made it on purpose to remove this blank seperator betwwen lines when possible, seems more readable to me and also more beautiful. But that's just my opinion, I do not know what other people prefer :)
