### ISSUE TITLE
AuthorId not set

### ISSUE THREAD

**Issue by LucasCioffi** [ether/etherpad-lite#4107]
I have Etherpad Lite in an iframe and I noticed this [line](https://github.com/ether/etherpad-lite/blob/master/src/static/js/ace.js#L107) on the master branch
`top.console.warn("setAuthorInfo AuthorId not set for some reason", arguments);`
was causing a CORS problem.

Solving the CORS problem proved to be too difficult for a friend and I so we commented out the console warning.  Solving the CORS problem would be ideal, but it's not relevant to this repo.

What might cause that situation where the Author ID is not set?  Do you know what the user experiences when it is happening?  Should be concerned about it?

Thank you!

**Comment by JohnMcLear** [comment]
Pull latest develop as afaik this is resolved.

Cors is WIP too, see the pr related to this and ep_helmet.
