### ISSUE TITLE
Backup and restore DB mysql

### ISSUE THREAD

**Issue by halley1970** [ether/etherpad-lite#4111]
Hey, guys,

I want to make a backup (DB mysql) to import it on a new etherpad installation.
Old etherpad version => v1.1
New etherpad version => v1.8.4

I tried with :
1/ mysqldump without success.
2/ A migration from mysql to MongoDB (node importSqlFile.js etherpad.sql), it finds 1372 keys but 0 imported.

Is it possible with this difference of etherpad version ?
If not, what do you advise me ? new install v1.1 and upgrade ?

Thanking you for your answers,
Yours sincerely,

**Comment by JohnMcLear** [comment]
1372 keys is tiny.  How many pads?  Might be easier to just dump each pads .Etherpad file and import that.

Migration should work fine though, the schema hasn't changed.  

No need to dump and import.  Just point new Etherpad at the database...

**Comment by halley1970** [comment]
Hello,

Thank you for your response.
However, this is a 'fresh install' in debian buster.

So I performed a mysqldump of the mysql database.

But when I test the URLs like :
http://xxxx:9001/CUXXu7pHG2

the server returns the error Cannot GET /CUXXu7pHG2

"Might be easier to just dump each pad. Etherpad file and import that." 
How do you do that ?

Thanking you for your answers,
Yours sincerely.

**Comment by JohnMcLear** [comment]
your URL is wrong.
http://xxxx:9001/p/CUXXu7pHG2
is right :)
