### ISSUE TITLE
for many authors, authors list is cut off in timeslider

### ISSUE THREAD

**Issue by rittmeier** [ether/etherpad-lite#4112]
If you have a lot of authors working on a pad (e.g. 23 authors) and each of them has a name like "Jane Doe", then only some of them are displayed in the #authorsList area of the timeslider view. The reason for that is, that they are all rendered in one row, without any wrap.

If one shrinks the window width, all names are displayed, because they are wrapped:
https://github.com/ether/etherpad-lite/blob/045ac70db8630717e3fd34a42186d52c935b78da/src/static/css/timeslider.css#L150

It would be nice if the author list would always be wrapped if it is too long to display in one row.

**Comment by rittmeier** [comment]
Might also be a topic for #4102

**Comment by rittmeier** [comment]
Simply moving the css rule out of the media query does not work fine, because the authors label (.authors-label) then is displayed in a seperate row, even if that is not needed.

**Comment by JohnMcLear** [comment]
Is this on latest develop?  We fixed this recently...

**Comment by JohnMcLear** [comment]
bump @rittmeier

**Comment by rittmeier** [comment]
Sorry, you are totally right, on latest develop the authors list is rendered properly for this scenario.
