### ISSUE TITLE
create & edit pad on click event via ajax

### ISSUE THREAD

**Issue by wazirsoft** [ether/etherpad-lite#4114]
Is this possible to create a new pad or edit a pad by clicking from the list using just Ajax without loading the whole page? Something like this

![image](https://user-images.githubusercontent.com/10064456/84576420-15460500-adce-11ea-8a26-6c386d13f2ff.png)

**Comment by JohnMcLear** [comment]
https://www.npmjs.org/package/ep_switch_pad does most of it, it doesn't provide a list.

You could fork that plugin and add the functionality you want :)

**Comment by wazirsoft** [comment]
> https://www.npmjs.org/package/ep_switch_pad does most of it, it doesn't provide a list.
> 
> You could fork that plugin and add the functionality you want :)

Thanks so much, this one method made my day...
