### ISSUE TITLE
#skinvariantsbuilder disconnects other users

### ISSUE THREAD

**Issue by chronikum** [ether/etherpad-lite#4115]
Hi there!

We are running a big instance with etherpad-lite.
We just moved to a new server and also updated our instance while doing this.

Right now, we are experiencing some problems with the `#skinvariantsbuilder`-feature.
If you are on a pad, you can go to `#skinvariantsbuilder` and if you do that, everyone who is on this pad will be disconnected with the message, they would have opened it another tab.

After that, only one person at a time can use a single pad-document. If anyone connects to the pad, the other connected person will be kicked off.
This can **only** be resolved by a restart.

It is really weird. Do you have any suggestions or do you have an idea how we could disable the skin variants builder?

I can provide additional details, if needed.

**Comment by JohnMcLear** [comment]
wtf.  Testing...

**Comment by JohnMcLear** [comment]
No.  This isn't a thing.  Please test your issues(in isolation by pulling latest develop etc) before submitting them on Github.

https://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/

**Comment by chronikum** [comment]
We tested this with multiple computers and multiple users on multiple, different pads. I wasn’t able to replicate this on another pad instance, but i thought an issue could be appropriate. 

I’ll look into it, i’m pretty sure now it could be a plugin. I’ll update this if I know more :)
