### ISSUE TITLE
setHTML not support CSS style?

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#4117]
Hi everyone! I want to draw up a document using CSS styles, but nothing happens in the end. The text is displayed correctly, but there is no style design. There are no errors in the console.

API version - 1.2.14

```
$pad_content = $client->post( EP_API_PATH."setHTML",
    [
        "form_params" => [
            "apikey" => EP_API_KEY,
            "padID" => $padID,
            "html" => "<!doctype html><html lang=\"en\"><body><ul style=\"color:red;\"><li>123<ul><li>dfd</li></ul></li><li>555</li></ul></body></html>"
        ]
    ]
);
```

**Comment by JohnMcLear** [comment]
No.  CSS is not supported.  

See how ep_font_color creates new markup or blockElements to notify a portion of content as red.

And/or.

Modify ep_font_color to look for Css color attribute on import and set block element at that point.

Either way the plug ep_font_color would be where to work :)
