### ISSUE TITLE
Etherpad 1.8.4. Admin password works exactly once after startup

### ISSUE THREAD

**Issue by wkulhanek** [ether/etherpad-lite#4119]
I have an Etherpad container that I'm building myself for use on Red Hat OpenShift (Kubernetes). In the container I create a file settings.json dynamically based on external configuration parameters.

I have the problem that I can log in as Admin exactly once after the Etherpad starts. The browser I logged in on will continue to function as an admin. But every other browser (or really any other computer) trying to access /admin will not get the password accepted.

The log shows nothing suspicious.

I'd be happy to provide any additional information that might help.

My container logic is here: https://github.com/wkulhanek/docker-openshift-etherpad

My container uses a PostgreSQL database as its backend.

The users section from the settings.json file mounted into the container reads like this:

```
  "users": {
    "admin": {
      "password": "hidden",
      "is_admin": true
    }
  },
```

I went through every available variable to see if this could be some setting that I set false - but didn't really see anything that would create this kind of behavior.

I have the following flags set:

```
"requireAuthentication": false,
"requireAuthorization": false,
```

**Comment by JohnMcLear** [comment]
Please read other closed issues on this topic.  It's fixed in develop.

**Comment by wkulhanek** [comment]
Thanks @JohnMcLear. Good to hear.

Do you have a reference (issue number)? I went through every issue that had admin or password but did not see this referenced anywhere I'm afraid.
