### ISSUE TITLE
Missing documentation in some files

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4124]
Especially in src/static, some files lack proper code-level documentation. I'm going to inspect the code base and add JSDoc comments wherever [eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc) complains. Besides having better documentation (hopefully :)), I think I can reuse them later for TypeScript or [flow types](https://flow.org/en/docs/types/). Typed code makes Etherpad more resilient and also helps with refactoring. The process of reusing JSDoc comments for flow or TypeScript probably can't be fully automated, but having JSDoc will speed up things.

This issue is for documenting my progress. If you think there are better alternatives to JSDoc, please feel invited to discuss them here.

**Comment by JohnMcLear** [comment]
We don't plan on moving to typescript.  Just fwiw.

**Comment by muxator** [comment]
True: there is no concrete plan about moving to typescript right now.

However, I would strongly support any effort towards incrementally migrating the codebase.
