### ISSUE TITLE
Error with mod_proxy

### ISSUE THREAD

**Issue by subrichhsnr** [ether/etherpad-lite#4125]
Hello,

we have problems with etherpad-lite behind a apache mod_proxy. In front we have a haproxy and in a backend a etherpad server with local apache and node.js etherpad. The local apache is configured with mod_proxy to 127.0.0.1:9001.

Apache Conf:

 ProxyPreserveHost On
        ProxyRequests Off
        ProxyVia Off

        SetEnv proxy-initial-not-pooled
        SetEnv proxy-nokeepalive 1
        RequestReadTimeout header=30
        Timeout 600
        ProxyTimeout 900

        <Location "/">
                ProxyPass http://127.0.0.1:9001/ connectiontimeout=60 timeout=60 retry=0
                #ProxyPass http://127.0.0.1:9001/ retry=0
                ProxyPassReverse http://127.0.0.1:9001/
        </Location>
        <Proxy *>
                Options FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Proxy>

Error in the Apache Log:

[Wed Jun 17 13:03:08.375594 2020] [proxy_http:error] [pid 12181:tid 140023114495744] (20014)Internal error (specific information not available): [client x.x.x.x:56870] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:03:08.375838 2020] [proxy:error] [pid 12181:tid 140023114495744] [client x.x.x.x:56870] AH00898: Error reading from remote server returned by /api/1.1/createAuthorIfNotExistsFor
[Wed Jun 17 13:03:21.590558 2020] [proxy_http:error] [pid 12181:tid 140022929921792] (20014)Internal error (specific information not available): [client x.x.x.x:44116] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:03:21.590747 2020] [proxy:error] [pid 12181:tid 140022929921792] [client x.x.x.x:44116] AH00898: Error reading from remote server returned by /api/1.1/createAuthorIfNotExistsFor
[Wed Jun 17 13:05:08.398516 2020] [proxy_http:error] [pid 12181:tid 140022980278016] (20014)Internal error (specific information not available): [client x.x.x.x:60426] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:05:08.398569 2020] [proxy:error] [pid 12181:tid 140022980278016] [client x.x.x.x:60426] AH00898: Error reading from remote server returned by /api/1.1/createSession
[Wed Jun 17 13:05:21.613081 2020] [proxy_http:error] [pid 12181:tid 140022963492608] (20014)Internal error (specific information not available): [client x.x.x.x:47738] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:05:21.613274 2020] [proxy:error] [pid 12181:tid 140022963492608] [client x.x.x.x:47738] AH00898: Error reading from remote server returned by /api/1.1/createSession
[Wed Jun 17 13:05:39.127683 2020] [proxy_http:error] [pid 12181:tid 140023106103040] (20014)Internal error (specific information not available): [client x.x.x.x:33170] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:05:39.127889 2020] [proxy:error] [pid 12181:tid 140023106103040] [client x.x.x.x:33170] AH00898: Error reading from remote server returned by /api/1.1/createAuthorIfNotExistsFor
[Wed Jun 17 13:06:42.768276 2020] [proxy_http:error] [pid 12182:tid 140023097710336] (20014)Internal error (specific information not available): [client x.x.x.x:50350] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:06:42.768511 2020] [proxy:error] [pid 12182:tid 140023097710336] [client x.x.x.x:50350] AH00898: Error reading from remote server returned by /api/1.1/createAuthorIfNotExistsFor
[Wed Jun 17 13:06:52.751663 2020] [proxy_http:error] [pid 12181:tid 140023097710336] (20014)Internal error (specific information not available): [client x.x.x.x:50626] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:06:52.751716 2020] [proxy:error] [pid 12181:tid 140023097710336] [client x.x.x.x:50626] AH00898: Error reading from remote server returned by /api/1.1/createAuthorIfNotExistsFor
[Wed Jun 17 13:07:08.805076 2020] [proxy_http:error] [pid 12182:tid 140022703449856] (20014)Internal error (specific information not available): [client x.x.x.x:35870] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:07:08.805261 2020] [proxy:error] [pid 12182:tid 140022703449856] [client x.x.x.x:35870] AH00898: Error reading from remote server returned by /api/1.1/createAuthorIfNotExistsFor
[Wed Jun 17 13:07:20.297188 2020] [proxy_http:error] [pid 12181:tid 140023080924928] (20014)Internal error (specific information not available): [client x.x.x.x:51454] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:07:20.298194 2020] [proxy:error] [pid 12181:tid 140023080924928] [client x.x.x.x:51454] AH00898: Error reading from remote server returned by /api/1.1/createAuthorIfNotExistsFor
[Wed Jun 17 13:07:30.928162 2020] [proxy_http:error] [pid 12181:tid 140022946707200] (20014)Internal error (specific information not available): [client x.x.x.x:36474] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:07:30.928360 2020] [proxy:error] [pid 12181:tid 140022946707200] [client x.x.x.x:36474] AH00898: Error reading from remote server returned by /api/1.1/createAuthorIfNotExistsFor
[Wed Jun 17 13:07:39.146066 2020] [proxy_http:error] [pid 12182:tid 140022795704064] (20014)Internal error (specific information not available): [client x.x.x.x:36640] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:07:39.146115 2020] [proxy:error] [pid 12182:tid 140022795704064] [client x.x.x.x:36640] AH00898: Error reading from remote server returned by /api/1.1/createSession
[Wed Jun 17 13:08:19.376036 2020] [proxy_http:error] [pid 12181:tid 140023064139520] (20014)Internal error (specific information not available): [client x.x.x.x:38042] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:08:19.376225 2020] [proxy:error] [pid 12181:tid 140023064139520] [client x.x.x.x:38042] AH00898: Error reading from remote server returned by /api/1.1/createAuthorIfNotExistsFor
[Wed Jun 17 13:08:35.446804 2020] [proxy_http:error] [pid 12182:tid 140022804096768] (20014)Internal error (specific information not available): [client x.x.x.x:38660] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:08:35.447529 2020] [proxy:error] [pid 12182:tid 140022804096768] [client x.x.x.x:38660] AH00898: Error reading from remote server returned by /api/1.1/createAuthorIfNotExistsFor
[Wed Jun 17 13:08:42.787105 2020] [proxy_http:error] [pid 12182:tid 140022686664448] (20014)Internal error (specific information not available): [client x.x.x.x:54098] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:08:42.787147 2020] [proxy:error] [pid 12182:tid 140022686664448] [client x.x.x.x:54098] AH00898: Error reading from remote server returned by /api/1.1/createSession
[Wed Jun 17 13:08:52.089713 2020] [proxy_http:error] [pid 12181:tid 140023206749952] (20014)Internal error (specific information not available): [client x.x.x.x:39416] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:08:52.089762 2020] [proxy:error] [pid 12181:tid 140023206749952] [client x.x.x.x:39416] AH00898: Error reading from remote server returned by /api/1.1/createAuthorIfNotExistsFor
[Wed Jun 17 13:08:52.769376 2020] [proxy_http:error] [pid 12181:tid 140023328466688] (20014)Internal error (specific information not available): [client x.x.x.x:54540] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:08:52.769411 2020] [proxy:error] [pid 12181:tid 140023328466688] [client x.x.x.x:54540] AH00898: Error reading from remote server returned by /api/1.1/createSession
[Wed Jun 17 13:09:08.823081 2020] [proxy_http:error] [pid 12182:tid 140022812489472] (20014)Internal error (specific information not available): [client x.x.x.x:39998] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:09:08.823183 2020] [proxy:error] [pid 12182:tid 140022812489472] [client x.x.x.x:39998] AH00898: Error reading from remote server returned by /api/1.1/createSession
[Wed Jun 17 13:09:20.316318 2020] [proxy_http:error] [pid 12181:tid 140023240320768] (20014)Internal error (specific information not available): [client x.x.x.x:55464] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:09:20.316369 2020] [proxy:error] [pid 12181:tid 140023240320768] [client x.x.x.x:55464] AH00898: Error reading from remote server returned by /api/1.1/createSession
[Wed Jun 17 13:09:30.944971 2020] [proxy_http:error] [pid 12181:tid 140023248713472] (20014)Internal error (specific information not available): [client x.x.x.x:40692] AH01102: error reading status line from remote server 127.0.0.1:9001
[Wed Jun 17 13:09:30.945019 2020] [proxy:error] [pid 12181:tid 140023248713472] [client x.x.x.x:40692] AH00898: Error reading from remote server returned by /api/1.1/createSession
[Wed Jun 17 13:09:37.095037 2020] [proxy_http:error] [pid 12182:tid 140022820882176] (20014)Internal error (specific information not available): [client x.x.x.x:56036] AH01102: error reading status line from remote server 127.0.0.1:9001

Have any a idea?

Thx
Stefan

**Comment by JohnMcLear** [comment]
Why run two reverse proxies?!  You are asking for trouble.  Just use one.

**Comment by subrichhsnr** [comment]
Hello,

the HAProxy is the LB for Moodle and Etherpad. We have problem with HAProxy and Connection to 9001 Port. So we have implemented a Apache local on the etherpad Server.

**Comment by JohnMcLear** [comment]
Fix the haproxy problem.  Don't push it further down.  This isn't an Etherpad problem anyway you would be better off asking the haproxy and Apache communities for help.  Sorry but we can't support everyone's software!
