### ISSUE TITLE
Wait for eejsBlock_ to finish before rendering?

### ISSUE THREAD

**Issue by mir123** [ether/etherpad-lite#4127]
I want to feed some data to an eejsBlock_afterEditbar, but the callback seemingly won't wait for promises before delivering the block to the pad. How can I have the rendering wait for a promise?

**Comment by JohnMcLear** [comment]
Eejs was built before promises existed.  You pass data to it.

https://github.com/JohnMcLear/ep_list_pads/blob/6fd005b9a6e8f638d507017a39d0bb0567bbc93c/index.js#L21

As an example for how to pass data to a template.

**Comment by JohnMcLear** [comment]
Closing as no reply from op.
