### ISSUE TITLE
[Bug] Chaos with authorship

### ISSUE THREAD

**Issue by Oremountainflorian** [ether/etherpad-lite#4128]
## System

We have integrated the latest version of Etherpad (1.8.4) into our platform. Occurs independently from used browser. 

The following plugins are also installed:
- ep_font_color "version": "0.0.11"
- ep_comments_page "version": "0.1.3"
- ep_embedded_hyperlinks_2 "version": "1.2.2"
- ep_heading2 "version": "0.1.3"
- ep_align "version": "0.2.0"
- ep_author_hover "version": "0.2.0"
- ep_table_of_contents "version": "0.2.0"
- ep_adminpads2 "version": "0.0.4"

**Server Setup Information:**

- Version of Etherpad: 1.8.4
- Operating System: Linux 5.5.0-2-amd64 #1 SMP Debian 5.5.17-1 (2020-04-15) x86_64 GNU/Linux
- Deployment Method: Manual install, git tag 1.8.4 (commit 89a155fdce7a5f190df3858c7f441e9e3e6312af) with systemd service
- Number of Running Instances: 1
- DB Replicaset Oplog: (default)
- NodeJS Version: v10.21.0
- NPM Version: 6.14.4
- MariaDB Version: 10.3.22-MariaDB-0+deb10u1 Debian 10
- operating behind nginx reverse proxy => setup: https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy

**Problem description** 

Since we installed Etherpad Lite we face serious problems regarding the authorship (names and colours). The problem is pretty hard to describe but I'll try my best to explain it with the help of screenshots. We use pads in our organization with up to 15 persons and the problem occurs with 4 or more persons. Unfortunately, with this bug Etherpad is barely useable for us... 

Below we see a screenshot of the reported online meeting. All persons were asked to write their name in the pad to identificate them at the beginning to run further test in the chat. In the chat I'm **Flo**. I guess Carsten appears twice as he entered the pad with two browsers because he had connection problems. Here we directly see what the problem is: Even if I already set my name, I can also set another name of the person below my name. 

![Authorship_Problem4](https://user-images.githubusercontent.com/44228345/85206509-e62a1900-b322-11ea-9e3e-0af68a682080.png)

As we see on the next image, "unbenannt"/"unnamed" is someone real who writes something to the chat (probably Valentina/Anja because they don't appear on the upper right where all users are listed, even if they entered their name to the pad). 

![Authorship_Problem5](https://user-images.githubusercontent.com/44228345/85207008-1d4df980-b326-11ea-8fc2-aaf9d4eadbd2.PNG)

Now I name "unbekannt"/"unknown" with **Icanwritemyname**. 

![Authorship_Problem6](https://user-images.githubusercontent.com/44228345/85207035-6605b280-b326-11ea-8bb5-76c5b1463559.PNG)

Now some strange things happen. Some people disappear from the upper right. Before, I could write something to the chat in turquiose (under the name Flo), but once I entered the name "Icanwritemyname" I turn to out to be "unbekannt"/"unnamed" myself (I wrote "Who is "Icanwritemyname"" to the chat). Before that, the person who really is Icanwritemyname wrote "+". 

![Authorship_Problem7](https://user-images.githubusercontent.com/44228345/85207082-b846d380-b326-11ea-8b64-5b8da66c6e83.PNG)

Also people (we lost track who) wrote to the chat as "unbekannt"/"unknown" (there are now more than one) even if they don't appear on the upper right. 

![Authorship_Problem9_first_unknown_is_Cornell_other_2nd_unknown_Nikster](https://user-images.githubusercontent.com/44228345/85207105-e0cecd80-b326-11ea-9d22-991e2b52b493.PNG)

When I reload the pad, I am Flo again 

![Authorship_Problem10_Flo_again](https://user-images.githubusercontent.com/44228345/85207122-efb58000-b326-11ea-9c72-df8bfe2299f0.PNG)

What a mess! We are really clueless what to do... We appreciate any hints.

**Comment by JohnMcLear** [comment]
I don't understand the suggested bug report.

Please provide exact steps to replicate in the format of (Example)..

1. Join X number of users on a pad.
2. User A changes name of user B to value X
3. User A tries to type in chat and expected outcome is Y

Actual outcome is Z.

**Comment by JohnMcLear** [comment]
Btw maybe you want https://www.npmjs.org/package/ep_disable_change_author_name ?

**Comment by JohnMcLear** [comment]
This is gonna go stale soon and I don't believe OP would like that.  OP can you please add more information?
