### ISSUE TITLE
no way to delete comment replies or chat messages

### ISSUE THREAD

**Issue by dioraman** [ether/etherpad-lite#4129]
Dear etherpad devs, thanks for this tiny gem! :hugs: 
This is my first issue so feel free to edit it to fit better your issue reporting policies.

**Steps to reproduce**
Insert a reply to a comment or a message to the chat
**What you expected to happen**
A trash icon with alt-text "delete this reply" / "delete this message"
**What actually happened**
No function to delete replies and messages. Replies can be removed with the workaround of removing the parent comment (although losing the time). No way to remove chat messages.

See following picture:
![no way to delete replies and chat messages](https://framapic.org/xQFxGgCIcLE7/3wYza7IWg2MD.jpg)

**Comment by JohnMcLear** [comment]
Comments are part of ep_comments

Chat messages cannot be deleted by design.
