### ISSUE TITLE
multiple sessionIDs in the cookie not working?

### ISSUE THREAD

**Issue by alekso87** [ether/etherpad-lite#4130]
> https://etherpad.org/doc/v1.8.0-beta.1/#index_session The session cookie **can also contain multiple comma-separated** sessionIDs, allowing a user to edit pads in different groups at the same time.

cookie - s.8181e6d4c8ceaebdf91f7f11eae70351,s.1151e6d4c8ceaecdf91f7f11eae70356,...

I added the correct session to cookies - the group pad opened successfully. As soon as I added another session separated by commas for another group pad, access to the current pad was lost - "You do not have permission to access this pad". Why?

I work with a development branch.

**Comment by alekso87** [comment]
I understood the reason. I registered a non-existing session in the second case. It turns out that before allowing the user access to a specific group pad, the system checks all sessions that are recorded in the cookie. I think this is bad. Consider the case.

The user has access to different group pads. Accordingly, he has 2 sessions in the cookie, separated by commas. Everything will be fine until the administrator removes at least one session from the database. Access will be lost to both group pads.

**Comment by JohnMcLear** [comment]
Follow bug reporting guidelines

**Comment by alekso87** [comment]
**Describe the bug**
If you write in the cookie "sessionID" of more than one session through a comma and at least one of them is absent in the database, access to the group pad for the existing session will be terminated.

**To Reproduce**
1 - create a group - createGroup API
2 - create a pad - createGroupPad API
3 - create author - createAuthor API
4 - create a session - createSession API
5 - set above session in the cookie "sessionID"
6 - check result - everything will be ok
7 - manually change the cookie "sessionID" - add a non-existing session, separated by commas
8 - repeat step 6 - "You do not have permission to access this pad"

**Expected behavior**
I believe that the presence of a non-existing session in cookie "sessionID" should not affect access to group pads.

**Screenshots**
<img width="1438" alt="1" src="https://user-images.githubusercontent.com/25965602/85393677-10afe800-b556-11ea-8c4b-77bcd3c15eda.png">
<img width="1439" alt="2" src="https://user-images.githubusercontent.com/25965602/85393707-19a0b980-b556-11ea-981b-25f1d530f918.png">

**Desktop:**
 - OS: MacOS
 - Browser: Firefox
 - Version: 76.0.1

**Comment by JohnMcLear** [comment]
Can you provide a node or bash script to replicate the API calls please?

**Comment by JohnMcLear** [comment]
When the session value is sent (when it's comma separated) what value is sent?  Is it an array of a single object or a string or??

Also note line 103 of ``SecurityManager.js``

**Comment by alekso87** [comment]
> When the session value is sent (when it's comma separated) what value is sent? Is it an array of a single object or a string or??

The data is stored as a string separated by commas. How to check the sending of cookies to the server?

**Comment by alekso87** [comment]
> Can you provide a node or bash script to replicate the API calls please?

No, sorry

**Comment by alekso87** [comment]
got it, thanks
