### ISSUE TITLE
Export support for tables (solution)

### ISSUE THREAD

**Issue by WC2-Foundation** [ether/etherpad-lite#4131]
I think I've come up with a possible fix for the tables export bug that has been a problem for some time. Part of it is written in PHP, which is of little use although it might be helpful to someone looking to implement a solution within Etherpad. 

Word support, as you may notice is a little wonky due to a regex pattern that could use some help (closing and opening table tags are not being parsed correctly). Anyway, you're welcome to take a look here:

https://wc2.io/x/p/g.GuS0yt5EZqwX6twY$djuUWvi5ou#

Server side:
PHP
npm chrome-headless-render-pdf
lynx browser for text conversion and Apache (any HTTP server should work)
libreoffice
NPM ep_tables4

The server is up and running most of the time, so feel free to export/test any of the four formats listed: PDF, Word, HTML, Text. A full description is provided along with required CSS files.

I welcome any suggestions/comments.

Thanks !

**Comment by JohnMcLear** [comment]
Shouldn't this be on the table plugin repo?  It's not part of core.
