### ISSUE TITLE
Etherpad relative static files path breaks down when use proxy

### ISSUE THREAD

**Issue by HMarzban** [ether/etherpad-lite#4145]
**Describe the bug**
The relative static file path blocks all solutions for using a reverse proxy.

When using a proxy to change the routing path! all things break down!

e.g. I want to change this route `/p/:pad` to `/:pad`, but when i proxy the request, the front-end can not require the static files and we get lots of errors.
even when I change the main router (`/src/node/hooks/express/specialpages.js`) `/p/:pad` to `/:pad` all things break down!

**Comment by JohnMcLear** [comment]
Please read closed issues.  This has been discussed and solved multiple times.
