### ISSUE TITLE
Server URL missing from read-only sharing link

### ISSUE THREAD

**Issue by fmichonneau** [ether/etherpad-lite#4146]
**Describe the bug**
The URL included in the text box to share a read-only version of a Pad doesn't include the server URL.

**To Reproduce**
1. click on the share icon in the top right corner of Pad
2. click on the Read-only check box
3. the URL starts with `/p/r.<hash>`

**Expected behavior**
The full URL should be included.

**Comment by JohnMcLear** [comment]
What version of Etherpad?  Latest develop or something prehistoric?..

**Comment by JohnMcLear** [comment]
Cannot replicate btw..  https://video.etherpad.com/p/Ts3SLu4xlV6_Zt7FYcJM

Will re-open if this bug exists on latest develop.   Assumption at the moment is OP tested an old version of Etherpad hence why version was omitted from bug report despite it being a requirement.
