### ISSUE TITLE
[docs] Add a list of recommended plugin to installation guide

### ISSUE THREAD

**Issue by maxloh** [ether/etherpad-lite#4147]
* * *

name: Feature request
about: Add a list of recommended plugin to installation guide
title: '[docs] Add a list of recommended plugin to installation guide'
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**

The [demo gif](https://github.com/ether/etherpad-lite/blob/develop/doc/images/etherpad_demo.gif) in official website were recorded with the following plugins enabled, which are not installed by default

- ep_headings2
- ep_markdown
- ep_comments_page
- ep_align
- ep_page_view
- ep_font_color
- ep_webrtc
- ep_embedded_hyperlinks2

It confuses new-comers as we expect to get something like the demo out of the box.

**Describe the solution you'd like**

Add a list of recommended plugins to [Customize functionalities with plugins](https://github.com/ether/etherpad-lite#customize-functionalities-with-plugins) part of the README guide, so that new-comers can install those plugins and get the same UI and functions as the demo.

**Comment by JohnMcLear** [comment]
Welcome this as a pr but not as recommended.  As "example".

I never run the plugins in example you are referring to on my local deployment.
