### ISSUE TITLE
Import failed: We were not able to import this file.

### ISSUE THREAD

**Issue by aliyousefiaan** [ether/etherpad-lite#4150]
Hi there.

I have installed Etherpad + MariaDB with these plugins :

Installed plugins: ep_align@0.2.0, ep_draw@0.1.1, ep_embedded_hyperlinks2@1.2.2, ep_headings2@0.1.3, ep_markdown@0.1.7

Also, installed LibreOffice on the server (ubuntu18) using apt.

Everything is working well, minus importing PDF file functionality.

When I try to import a PDF file on UI, get this error:
Import failed: We were not able to import this file.

The errors on Syslog:

Jul  7 13:23:23 TEH-DC2-ETHERPAD etherpad[11347]: #033[32m[2020-07-07 13:23:23.251] [INFO] ueberDB - #033[39mFlushed 1 values
Jul  7 13:23:27 TEH-DC2-ETHERPAD etherpad[11347]: #033[32m[2020-07-07 13:23:27.323] [INFO] access - #033[39m[CREATE] Pad "abcccddd": Client BDeG-Xph6JbJyp5ZAAAA with IP "xxxx" created the pad
Jul  7 13:23:27 TEH-DC2-ETHERPAD etherpad[11347]: #033[32m[2020-07-07 13:23:27.330] [INFO] ueberDB - #033[39mFlushed 6 values
Jul  7 13:23:42 TEH-DC2-ETHERPAD etherpad[11347]: #033[32m[2020-07-07 13:23:42.364] [INFO] ueberDB - #033[39mFlushed 3 values
Jul  7 13:23:42 TEH-DC2-ETHERPAD etherpad[11347]: #033[32m[2020-07-07 13:23:42.865] [INFO] ueberDB - #033[39mFlushed 3 values
Jul  7 13:23:43 TEH-DC2-ETHERPAD etherpad[11347]: #033[32m[2020-07-07 13:23:43.367] [INFO] ueberDB - #033[39mFlushed 3 values
Jul  7 13:23:56 TEH-DC2-ETHERPAD etherpad[11347]: #033[32m[2020-07-07 13:23:56.600] [INFO] ueberDB - #033[39mFlushed 1 values
Jul  7 13:23:58 TEH-DC2-ETHERPAD etherpad[11347]: #033[33m[2020-07-07 13:23:58.291] [WARN] console - #033[39mConverting Error: LibreOffice died with exit code 1 and message: func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26
Jul  7 13:23:58 TEH-DC2-ETHERPAD etherpad[11347]: convert /tmp/upload_86996d4f7726914b3779df78f1d694ac.pdf -> /tmp/upload_86996d4f7726914b3779df78f1d694ac.html using filter : XHTML Writer File:UTF8
Jul  7 13:23:58 TEH-DC2-ETHERPAD etherpad[11347]: Application Error
Jul  7 13:24:01 TEH-DC2-ETHERPAD etherpad[11347]: #033[32m[2020-07-07 13:24:01.151] [INFO] access - #033[39m[ENTER] Pad "abcccddd": Client BDeG-Xph6JbJyp5ZAAAA with IP "xxxx" entered the pad
Jul  7 13:24:01 TEH-DC2-ETHERPAD etherpad[11347]: #033[32m[2020-07-07 13:24:01.174] [INFO] ueberDB - #033[39mFlushed 1 values

Etherpad version is 1.8.4

What is the problem?

**Comment by JohnMcLear** [comment]
Read the guidelines for bug reoorts.  It says to test without plugins.

**Comment by aliyousefiaan** [comment]
Hi there,

I try the latest develop without any plugin and also update libreoffice, get same error:

Jul  7 14:38:38 TEH-DC2-ETHERPAD etherpad[29819]: #033[33m[2020-07-07 14:38:38.841] [WARN] console - #033[39mConverting Error: LibreOffice died with exit code 1 and message: func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26
Jul  7 14:38:38 TEH-DC2-ETHERPAD etherpad[29819]: convert /tmp/upload_e640a6cd72f30bc66c45fb0f5ffb3745.pdf -> /tmp/upload_e640a6cd72f30bc66c45fb0f5ffb3745.html using filter : XHTML Writer File:UTF8
Jul  7 14:38:38 TEH-DC2-ETHERPAD etherpad[29819]: Application Error

libreoffice is already the newest version (1:6.0.7-0ubuntu0.18.04.10).
Your Etherpad version is 1.8.4 (27c5610)

**Comment by JohnMcLear** [comment]
CAn you use ``/usr/bin/soffice`` to convert the file to HTML?

**Comment by aliyousefiaan** [comment]
Yes the pdf file converted to html using:

root@TEH-DC2-ETHERPAD:~# /usr/bin/soffice --convert-to html dummy.pdf
MoTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26
convert /root/dummy.pdf -> /root/dummy.html using filter : draw_html_Export

it's get error but converted fine.

**Comment by JohnMcLear** [comment]
Can you share the .pdf?

**Comment by aliyousefiaan** [comment]
It's a simple PDF file.

[dummy.pdf](https://github.com/ether/etherpad-lite/files/4886313/dummy.pdf)

**Comment by JohnMcLear** [comment]
Wait,...  What version o flibreoffice are you on?

Did you update it?  Saying you installed the latest via apt is not updating it btw...

**Comment by aliyousefiaan** [comment]
Hi There,
You right I update Libreoffice using their official repo to the latest version and the error have solved.

Now still I have problem with importing PDF file.
Now I get error only on web:
Import failed: Please copy paste

On console there is no error.

Your Etherpad version is 1.8.4 (27c5610)

Try to convert using cli:
root@TEH-DC2-ETHERPAD:~# /usr/bin/soffice --convert-to html dummy.pdf
convert /root/dummy.pdf -> /root/dummy.html using filter : draw_html_Export
it works like a charm.


etherpad log:
Jul  7 18:56:08 TEH-DC2-ETHERPAD etherpad[12132]: #033[32m[2020-07-07 18:56:08.659] [INFO] Minify - #033[39mCompress CSS file skins/colibris/index.css.
Jul  7 18:56:12 TEH-DC2-ETHERPAD etherpad[12132]: #033[32m[2020-07-07 18:56:12.471] [INFO] Minify - #033[39mCompress CSS file css/pad.css.
Jul  7 18:56:12 TEH-DC2-ETHERPAD etherpad[12132]: #033[32m[2020-07-07 18:56:12.474] [INFO] Minify - #033[39mCompress CSS file skins/colibris/pad.css.
Jul  7 18:56:12 TEH-DC2-ETHERPAD etherpad[12132]: #033[32m[2020-07-07 18:56:12.852] [INFO] Minify - #033[39mCompress CSS file css/iframe_editor.css.
Jul  7 18:56:12 TEH-DC2-ETHERPAD etherpad[12132]: #033[32m[2020-07-07 18:56:12.866] [INFO] Minify - #033[39mCompress CSS file css/iframe_editor.css.
Jul  7 18:56:13 TEH-DC2-ETHERPAD etherpad[12132]: #033[32m[2020-07-07 18:56:13.375] [INFO] access - #033[39m[CREATE] Pad "gggg": Client GOUzbjPjT_FwnHtJAAAA with IP xxxxx" created the pad

**Comment by aliyousefiaan** [comment]
There is a error on browser console after importing a pdf file:


Uncaught TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (jquery.js:9612)
    at import:1

**Comment by JohnMcLear** [comment]
Thanks for letting me know.  Can you make a separate issue for the import please and I will assign that to me.
