### ISSUE TITLE
PDF import generate empty pad with libreoffice

### ISSUE THREAD

**Issue by brunob** [ether/etherpad-lite#4151]
First, sorry to open a ticket for that since it's not really a bug that i can reproduce on https://video.etherpad.com/ :\

We have problem with PDF import on pad.infini.fr which use latest 1.8.4 (also tested locally with daily develop branch) and libreoffice as recommended in the wiki.

As described in #194 importing a PDF result in a pad showing the "source" bites of the PDF. So i've used soffice command line to test this cf `soffice --headless --convert-to html:"XHTML Writer File:UTF8" --outdir . install.pdf --invisible --nologo --nolockcheck --writer` which produce this output : 

```
:1: parser error : Document is empty
%PDF-1.5
^
:1: parser error : Document is empty
%PDF-1.5
^
:1: parser error : Document is empty
%PDF-1.5
^
```

Installing `libreoffice-pdfimport` package help us to fix this error, but the generated html contains again the source bites of the PDF embedded in html tags. Updating libreoffice from 5.2.7-1+deb9u11 to 6.1.5-3+deb10u4~bpo9+1 lead to a change, the generated HTML is now empty, better but not fixed :p
 
Finally, if i add `--infilter="writer_pdf_import"` option to the command it works well and i the PDF is correctly converted, that make me think we miss a libreoffice package handling the type detection of input files.

As said first, i've tested the same PDF on video.etherpad.com and it works well, so the question is : could you share the list of libreoffice packages installed on this instance in order to help us to find the package we are missing for that file type detection problem ?

FTR, here is the test PDF i'm using, it's generated by libreoffice from a txt file : 
[install.pdf](https://github.com/ether/etherpad-lite/files/4886302/install.pdf)

**Comment by JohnMcLear** [comment]
Lol LO5? :D!!!

  "soffice": "/bin/libreoffice6.4", is on video.etherpad.com

6.4 as a minimum...  

LO is on like 7 afaik?!

**Comment by brunob** [comment]
@JohnMcLear thx for answering :) LO 5 is the default version available on debian stretch, i got 6.1 from backport repo, and i use 6.4.4.2 locally with no more luck :\

**Comment by JohnMcLear** [comment]
okay, not sure then ;\  I'd try the LO mailing lists because it is surely LO related?

**Comment by JohnMcLear** [comment]
confirmed upstream bug with LO:

## Fails with empty file output
```
jose@server:~$ soffice --headless --convert-to html:"XHTML Writer File:UTF8" install.pdf
convert /home/jose/install.pdf -> /home/jose/install.html using filter : XHTML Writer File:UTF8
Overwriting: /home/jose/install.html
```

## Works
```
jose@server:~$ soffice --headless --convert-to html install.pdf
convert /home/jose/install.pdf -> /home/jose/install.html
```

Defo one for LO team :)  Not much we can do here, whatever output they give us we have to trust as good unless it throws an error.

**Comment by brunob** [comment]
See also #4152

**Comment by brunob** [comment]
@JohnMcLear FTR i'm on IRC #libreoffice-dev and filling a bug on their tracker.

**Comment by brunob** [comment]
@JohnMcLear we got an answer https://bugs.documentfoundation.org/show_bug.cgi?id=134681#c1

As i said in my first message here, `--infilter="writer_pdf_import` is the solution for PDF, but it could work for all types with `soffice --headless --convert-to html:"XHTML Draw File" install.pdf`

**Comment by brunob** [comment]
So, i got it working with this simple patch : 

```diff
diff --git a/src/node/utils/LibreOffice.js b/src/node/utils/LibreOffice.js
index 267f7a0c..12a98fa4 100644
--- a/src/node/utils/LibreOffice.js
+++ b/src/node/utils/LibreOffice.js
@@ -44,6 +44,10 @@ exports.convertFile = function(srcFile, destFile, type, callback) {
   if (type === "html") {
     // "html:XHTML Writer File:UTF8" does a better job than normal html exports
     type = "html:XHTML Writer File:UTF8";
+    // PDF files need to be converted with LO Draw ref https://github.com/ether/etherpad-lite/issues/4151
+    if (path.extname(srcFile).toLowerCase() === ".pdf") {
+      type = "html:XHTML Draw File"
+    }
   }
 
   // soffice can't convert from html to doc directly (verified with LO 5 and 6)
```

Do you want a PR for that ?
