### ISSUE TITLE
Import failed: Please copy paste

### ISSUE THREAD

**Issue by aliyousefiaan** [ether/etherpad-lite#4152]
We get error on browser  when try to import a PDF file:
Import failed: Please copy paste

On browser console:
Uncaught TypeError: url.indexOf is not a function
at jQuery.fn.init.jQuery.fn.load (jquery.js:9612)
at import:1

There is no error on terminal.

libreoffice is already the newest version (1:6.4.4~rc2-0ubuntu0.18.04.1).
Etherpad version is 1.8.4 (27c5610)
No plugin installed.

**Comment by JohnMcLear** [comment]
Confirmed on https://video.etherpad.com/p/C1GurIr2-h6WcEiVRBGE

All PDF files seem to do it, not a specific file.  More testing required.

**Comment by JohnMcLear** [comment]
I expect the port to jQ3 was teh cause.  Will need to fix it up.

**Comment by JohnMcLear** [comment]
Did 2 parts of the patch

Part 1 is removing a huge amount of overhead of jQ which is just not necessary to call a function
Part 2 is fixing the variable check to only perform direct on .etherpad files
Part 3 will be to find out why the file isn't being written to core, I suspect some fuckery is afoot and will hopefully solve tomorrow.

**Comment by JohnMcLear** [comment]
Part 3 is related to LibreOffice being broken upstream "still".

Doing an export from Etherpad of a PDF then using soffice binary to convert that to HTML works but if you use HTML:UTF8 et al it breaks.  

Libreoffice 7 still fails:

## UTF8
```
jose@server:~$ /opt/libreoffice7.0/program/soffice.bin --headless --convert-to "html:XHTML Writer File:UTF8" testexpo.pdf
convert /home/jose/testexpo.pdf -> /home/jose/testexpo.html using filter : XHTML Writer File:UTF8
Overwriting: /home/jose/testexpo.html
jose@server:~$ cat /home/jose/testexpo.html
# no output
```

## No UTF8
```
jose@server:~$ /opt/libreoffice7.0/program/soffice.bin --headless --convert-to html testexpo.pdf
convert /home/jose/testexpo.pdf -> /home/jose/testexpo.html using filter : draw_html_Export
Overwriting: /home/jose/testexpo.html
jose@server:~$ cat /home/jose/testexpo.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
     "http://www.w3.org/TR/html4/transitional.dtd">
<html>
<head>

  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <title></title>
  <meta name="generator" content="LibreOffice 7.0.0.1 (Linux)"/>
  <meta name="created" content="00:00:00"/>
  <meta name="changed" content="00:00:00"/>
</head>
<body>
<h1></h1>
<p>Welcome to Etherpad!</p>
<p>This pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows </p>
<p>you to collaborate seamlessly on documents!</p>
<p>Get involved with Etherpad at https://etherpad.org</p>
<p>Warning: DirtyDB is used. This is fine for testing but not recommended for production. -- To suppress these </p>
<p>warning messages change suppressErrorsInPadText to true in your settings.json</p>
</body>
</html>jose@server:~$
```

1. Etherpad is creating VALID PDFs.  
1. LibreOffice is failing to convert them.

One option is to remove the UTF8 option which will break OL/UL import into Etherpad by adding double items instead of single.

The real fix is for the LO team to fix the ``html:XHTML Writer File:UTF8`` logic.  @aliyousefiaan can you file a bug w/ LO team and point them here?

**Comment by aliyousefiaan** [comment]
Hi there,
Now I report the issue to LibreOffice?
Kind Regards.

**Comment by JohnMcLear** [comment]
I have no idea

**Comment by aliyousefiaan** [comment]
Is there any way a teacher loads a PDF file on Etherpad to show them to students?

**Comment by JohnMcLear** [comment]
Try latest develop.  This should be fixed.
