### ISSUE TITLE
Cant embed etherpad in an IFrame using correct CORS and CSP

### ISSUE THREAD

**Issue by gnd** [ether/etherpad-lite#4155]
Hi,

we are currently trying to embed a etherpad-lite pad on a different domain in an IFrame. However it doesnt seem to work. This is the setup: 

- current working copy of etherpad-lite: https://pad.xpub.nl/p/Collectiveioning
- embedded here: https://project.xpub.nl/collectiveioning/live.html
- the host pad.xpub.nl sets the correct CSP header: Content-Security-Policy: frame-ancestors https://project.xpub.nl;
- the host project.xpub.nl sets the correct CORS header: Access-Control-Allow-Origin: https://pad.xpub.nl

The embed still doesn't work in no browser :/

Do you have a Wiki somewhere on how to correctly setup Etherpad embedding via IFrames ? Im sure more people wuld be interested.

**Comment by gnd** [comment]
I just noticed https://github.com/ether/etherpad-lite/issues/4031 so i set out to remove all console.log and top.console statements from https://github.com/ether/etherpad-lite/pull/4039 but i still get a "Uncaught DOMException: Permission denied to access property "console" on cross-origin object" in Safari..

**Comment by JohnMcLear** [comment]
Is the issue now Safari specific?

On the example URI I Get: "VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }"

Please provide exact steps to replicate if possible.

Are you testing against latest develop branch or a release?

**Comment by gnd** [comment]
Hi John, sorry for the chaotic intro. 

We are running on (almost) latest master from github:

```
commit 62101147a0c3495dc80daa87ab53a3366321a205 (HEAD -> master, tag: 1.8.3, origin/release/1.8.3, origin/master)
Merge: d3f583c9 5e6af287
Author: muxator <a.mux@inwind.it>
Date:   Mon Apr 27 03:31:35 2020 +0200

    Release version 1.8.3
```
After i created this ticket, my colleague has replaced the live.html file with one without the iframe, so thats why you couldnt see the embedded etherpad. I have just created the file debug.html so we can look into the issue, however it seems to work now (at least in chromium, vanadium and ff):

https://project.xpub.nl/collectiveioning/debug.html

What i thik happened overnight is that the browser cache got expired and new js was sent from etherpad, so although i might have solved the issue already yesterday i oly see the results now. I wonder.. If you are interested, i can write up the steps taken to make this run somewhere and also send you a diff with my changes yesterday - the crusade to remove all console output from etherpad.

**Comment by JohnMcLear** [comment]
Yes please document what you did.

**Comment by gnd** [comment]
We are running nginx, but i think the steps are similar for Apache too, just different directives. First we tried with X-Frame-Options, but that is deprecated and ignored by at least Chrome and Firefox, and one has to use CSP instead.

1. Set CSP header on nginx vhost for the pad (pad.xpub.nl):

```
# Allow IFrame embedding on project.xpub.nl
add_header Content-Security-Policy "frame-ancestors https://project.xpub.nl;";
```

2. On the vhost that is hosting the iframe (project.xpub.nl) I added a CORS header. (Not sure this is needed tho)

`add_header Access-Control-Allow-Origin https://pad.xpub.nl;`

3. Restart nginx and verify that headers are correctly set with curl:

```
curl -I https://pad.xpub.nl
HTTP/1.1 200 OK
Date: Fri, 10 Jul 2020 08:33:59 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 8557
Connection: keep-alive
X-Powered-By: Express
X-UA-Compatible: IE=Edge,chrome=1
Referrer-Policy: same-origin
ETag: W/"216d-t3QndKS0QegVE7UyFkUmu9y8xCs"
Set-Cookie: express_sid=s%3AOxGOGXAUEe_LNgNgczjt1Hp0wPr0l1cm.dsaShDMkmv1H48J3NhgE%2FE6%2FHaoQQghvlMWhh3ilm8c; Path=/; HttpOnly
Content-Security-Policy: frame-ancestors https://project.xpub.nl;

curl -I https://project.xpub.nl
HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Fri, 10 Jul 2020 08:35:09 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 16902
Last-Modified: Sat, 04 Jul 2020 17:34:05 GMT
Connection: keep-alive
ETag: "5f00bd8d-4206"
Access-Control-Allow-Origin: https://pad.xpub.nl
Accept-Ranges: bytes
```
4. Remove all console output from Etherpad. This is the diff of the changes I did yesterday:
https://project.xpub.nl/collectiveioning/diff 

I dont think all of them were necessary but since I have still seen output from etherpad in my console I tried to get rid of all that I could find. I even see some errors in my changes (like forgotten 'i' from vi).

5. Wait a night. Actually I wonder what exactly happened in this time. Did some cache expire ? Where ? Browser ? Etherpad ? Some js minification ? Some nodejs cache ?

**Comment by JohnMcLear** [comment]
4. Not required since 1.8.4

5. Cache age is set in ``settings.json``
