### ISSUE TITLE
No test coverage for PDF/ODT export/import

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4160]
PDF/ODT import test coverage does not exist because we can't afford soffice is available in test environments.

2 options.

1. Move PDF/ODT export out of settings.json and into a plugin.  Advantage is the plugin can specify to do the test.
2. Make Travis install LibreOffice - completed in: https://github.com/ether/etherpad-lite/pull/4159

So next thing is to write tests to cover PDF / ODT export / import.  I'm not sure ohw to write import tests but export would be easy, set some HTML, have an expected ODT output (string) and compare the two after running an export of a pad.

**Comment by webzwo0i** [comment]
RE import: I started to migrate import/export-tests from frontend-tests to backend-tests some years ago. It's really ugly and things might have changed in the meantime, but maybe 35f387b2f96fc49fd6a1d036738215f85343e12b helps as a start

**Comment by JohnMcLear** [comment]
Looks like https://github.com/ether/etherpad-lite/blob/develop/tests/backend/specs/api/importexportGetPost.js already had the logic..  Lol doh..  Will figure out what's not being covered... 👍

**Comment by JohnMcLear** [comment]
Merged in.
