### ISSUE TITLE
Clarity on which browsers/OS we support

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4162]
Can I get opinions on which browser/OS-combinations we support?

ATM it's impossible to test some combinations due to limitations in our CI (using Saucelabs):
- no Android/iPhone (we may get emulated device tests, I did not try that, but we may need to apply to (Real Device Testing)[https://saucelabs.com/platform/real-device-cloud] to be sure our frontend tests pass on those devices)
- no Opera (however we have 3 places in the editor-code that check for browser.opera)
- no BSD-derivates for frontend tests

But my main concern is Internet Explorer. We have some legacy code in different areas of the editor to support very old IE-versions. IE11 does not seem to support Promises, so if we want to support IE11, we need a solution for that.

Are you okay with dropping support for <IE11? Or do we even only want to support Edge?
And can we reach out to SL to get Real Device testing for Android/iPhone? (If they can't help us, maybe ask other services and have our desktop browsers run an SL but Android/iPhone somewhere else?)

**Comment by JohnMcLear** [comment]
If ie 11 can be supported within a few hours and a tiny amount of additional code then it would be nice to support ie 11.  If not, drop it.

Drop opera.

**Comment by JohnMcLear** [comment]
Ie11 working again with a 5 min patch.

![IMG_20200715_104509.jpg](https://user-images.githubusercontent.com/220864/87530455-42fdc280-c688-11ea-9956-a6d1fb8c3de9.jpg)

Power cut here so can't commit :p

**Comment by JohnMcLear** [comment]
PR @ https://github.com/ether/etherpad-lite/pull/4167 for IE11.

**Comment by JohnMcLear** [comment]
So to answer this question:

Are you okay with dropping support for <IE11?  **Yes, IE11 would be nice to have though now we have a "fix".**
Or do we even only want to support Edge?  **IE11 would be nice, anything Promises+ is "supported" but core functionality (basic editing) should work IE9+ afaik.**
RE OS: **The current testing platforms we have is sufficient.**

RE automating mobile devices IE android/ios, that's a nice to have but it isn't covered in our open source package with Sauce Labs and we would need to get a commercial package to have this.  IMHO it's not necessary right now but maybe worth reviewing in the future.

**Comment by JohnMcLear** [comment]
Okay I'm giving up with IE11.  Too many things are broken.  Let's can it.

**Comment by JohnMcLear** [comment]
Firefox 52+
Chrome 55+
