### ISSUE TITLE
HTML Export produces broken HTML with multiple unordered lists

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4165]
**Describe the bug**
HTML-Export is broken IE `<ul class="bullet"></li><ul class="bullet"></ul></li></ul>` when multiple bullet/unordered lists are used.

**To Reproduce**
1. Open a pad, ctrl+a to select everything
2. ctrl+shift+L to make an unordered list
3. tab to make a second level of unordered list
4. export HTML

**Comment by JohnMcLear** [comment]
What's the expected html output and the actual output?

**Comment by webzwo0i** [comment]
Sorry for not being clear.
Actual relevant output:
`<ul class="bullet"></li><ul class="bullet"><li>test</ul></li></ul>`

Expected:
`<ul class="bullet"><ul class="bullet"><li>test</li></ul></ul>` or maybe `<ul class="bullet"><li><ul class="bullet"><li>test</li></ul></li></ul>`

With two lines (first one bullet level, second two levels) this becomes:
`<ul class="bullet"><li>UL1<ul class="bullet"><li>UL2</ul></li></ul>` vs. expected: `<ul class="bullet"><li>UL1<ul class="bullet"><li>UL2</li></ul></li></ul>`

**Comment by webzwo0i** [comment]
Yeah with content the first `<li>` is correct, without content its a single closing `</li>`. However, in both cases the last clasing `</li>` seems to be at the wrong place

**Comment by webzwo0i** [comment]
This is a minor issue because browsers actually display it correctly when viewing the exported HTML, so the lists are readable and correctly intended. Also it seems to work when importing the exported HTML again. So I am not sure now, if this is a bug or not... :-)

**Comment by JohnMcLear** [comment]
It's not semantically clean HTML so ideally I will get time to fix before the 21st.

**Comment by JohnMcLear** [comment]
Confirmed.
