### ISSUE TITLE
Authentication required

### ISSUE THREAD

**Issue by Erika-epr** [ether/etherpad-lite#4170]
I have installed Etherpad Lite 1.8.3 on Centos7
with the standard settings and the user with cleartext passwords in the settings.json

I open a browser for the first time and log in, does the login work
If you close the complete browser and open it again, you will always be asked for the password
after restarting the service, you can log in again
if you open only one new tab, you can log in as often as you like

what should I set so that I don't have to restart the service

![Screenshot 2020-07-16 at 12 02 16](https://user-images.githubusercontent.com/68369740/87659008-3a2af080-c75d-11ea-91d3-ca21149c2236.png)

**Comment by JohnMcLear** [comment]
Please use latest version of Etherpad, this issue was resolved.

**Comment by Erika-epr** [comment]
Thx, i will use the latest version and test it

**Comment by Frogging101** [comment]
@Erika-epr Note that the fix is in the current tip of master, and not release 1.8.4.

**Comment by JohnMcLear** [comment]
Thanks @Frogging101 .  We work to develop branch fwiw so it's often best to use that to check for lates there as we rarely get time to release due to a semi time consuming release procedure.

We are due a release soon
