### ISSUE TITLE
Frontend tests problems with Saucelabs

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4188]
There are still some problems with frontend tests on Saucelabs. I am working on this, tracking this here.

1. after the async update, queue.drain must be called with a callback (fix is https://github.com/ether/etherpad-lite/commit/ccfbe22c06eb735b6dd853fd9106a8e1ffb8e4c7)
2. travis cancels the SL-job when no output was received for 10 minutes, but in that case mocha results won't be logged (fix is https://github.com/ether/etherpad-lite/commit/a48079588d90174de01a0f3aa5023edcdf1091b2 setting a max limit for all SL-tests to 9.5 minutes)
~~3. for unknown reasons the frontend test output in travis is broken in some cases, might be a problem in https://github.com/ether/etherpad-lite/blob/develop/tests/frontend/runner.js#L107~~ travis output log is not 100% in time and sometimes changes for me on reload - the problems I've seen (in PASSED/FAILED only the first five letters are green/red or sometimes there was a line missing) are gone on reload of the page
4. failed hooks are not printed as FAILED, so one can get the wrong impression that all tests pass (fix is to move FAILED out of "test end"-handler, because "test end" is not called when a hook failed)
5. related to 4., browsers seem to not be able to POST to /jserror in some cases (this makes sense when in the middle of loading a pad some error occurs, but in other cases I have the feeling it should work but doesn't during frontend tests) - eval if it's possible to setup this error-logging earlier on loading

**Comment by JohnMcLear** [comment]
Are things stable if you just target one browser?  I often found that the more devices you target the less reliable saucelabs was

**Comment by webzwo0i** [comment]
Yes and no. The problems described above are bugs in runner.js/remote_runner.js, fixes with explanations will come today! Without those it will look like everything is fine, while there are actually failing tests due to newPad (or something else) in a before(Each)-hook throwing. (You can see failing before-hooks on the left side during tests, but they are not logged because mocha's "test end"-hook, where we log the pass/fail/pending, will not be called - fix is to log in the pass/fail/pending events)

After applying those fixes, Travis and SL seem to work and print results every time (I have issued a lot of build jobs....), but I see that there are a couple of "Pad never loaded"-exceptions in different tests and the tests, where those exceptions occur, change. If I run only one browser test in multiple travis jobs there *seems to be* less "Pad never loaded" messages - I am not sure because I messed things up, but I will check this. But the thing is, I see those "Pad never loaded"-messages also sometimes in my local environment, not as often as in the tests, but they happen. Yesterday I also increased the timeout in waitFor to 15 seconds without luck.

Sadly, we can't just use mocha's retry-feature, because that does not work for failing hooks

**Comment by JohnMcLear** [comment]
Fwiw I still find saucelabs inconsistent on which tests fail / pass but with a few runs if we can isolate the ones that frequently fail we can look to see why it's those and not others.

**Comment by webzwo0i** [comment]
I configured a cron job to run daily. It's not possible to run it more often, but theoretically we can trigger it via Travis API hourly. I have a script at https://github.com/webzwo0i/ep-travis-jobs to collect all the results, we can use that to isolate them.

I did a very quick look,for instance https://github.com/ether/etherpad-lite/blob/develop/tests/frontend/specs/chat.js#L113
This is sometimes failing and I think the problem is: never use setTimeouts at all, always use waitFor. (animations should be already disabled) The `click` makes changes on the DOM and those changes might or might not have been applied in 10 milliseconds, so always use waitFor. However, atm I have a little bit problems with test readability, so I think it would be best if we consequently use helper-methods, e.g. `helper.buttons.chatSticky`, `helper.buttons.chatClose`, `helper.buttons.timesliderOpen` etc. and implement the waitFor-logic there, so that in our tests we simply can do things like `helper.buttons.chatSticky.click()` and don't write anything about waitFor.

Some thing in https://github.com/ether/etherpad-lite/blob/develop/tests/frontend/specs/xxauto_reconnect.js#L39 This was failing yesterday for my branch but its imo again not waiting for the click-event to happen.

The failing chat.js-test in https://travis-ci.org/github/ether/etherpad-lite/jobs/713000220#L2167 is probably my mistake. We don't reuse the padName in a lot of tests so my logic to reuse it when a beforeEach-hook fails might be wrong, essentially leading to loading a brand new pad instead of the old one. Will have a look asap!

I think I can identify and fix the sometimes-failing tests in a few hours, but refactoring all the tests to make them readable and use helper-methods whenever possible to reduce the noise of having waitFor-calls all over the place will take more time.

**Comment by webzwo0i** [comment]
stupid mistake for retry-logic (https://travis-ci.org/github/ether/etherpad-lite/jobs/713000220#L2167) fix is in https://github.com/ether/etherpad-lite/pull/4206

**Comment by webzwo0i** [comment]
OK, I have the list now https://github.com/webzwo0i/ep-travis-jobs
The "errors_in_x_jobs" are based on the last x jobs that returned errors.
It's not perfect because as it includes failures that have already been fixed or that were introduced during coding but never merged in develop. 

`makes chat stick to right side of the screen then makes it one step smaller Error: Uncaught Error: expected false to equal true`

`Makes sure the export URIs are as expected when the padID is numeric Error: Error: expected -1 to not equal -1`

!! compare "sees the same text" and "sees the sametext" what is this? `6 loads adds a hundred revisions Error: Uncaught Error: expected 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaWelcome to Etherpad! This pad text is synchronized as you type, so that everyone viewing this page sees the sametext. This allows you to collaborate seamlessly on documents! Get involved with Etherpad at https://etherpad.org Warning: DirtyDB is used. This is fine for testing but not recommended for production.-- To suppress these warning messages change suppressErrorsInPadText to true in your settings.json 'to sort of not equal 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaWelcome to Etherpad! This pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents! Getinvolved with Etherpad at https://etherpad.org Warning: DirtyDB is used. This is fine for testing but not recommended for production. -- To suppress these warning messages change suppressErrorsInPadText to true in your settings.json '`

`timeslider contained in URL Error: Error: wait for condition never became true function`

`checks for button vanishing Error: Error: expected 'block' to equal 'none'`

**Comment by webzwo0i** [comment]
The noise of failing tests that have already been fixed and the fact that I skip all jobs that have more than ten errors is problematic.

I think I go for hitting the Travis API for some time to run a frontend test build. When I set SL-parallelism to maybe 3 or 4 it should be enough for our "regular" builds to run. Because a test runner takes up to 8 minutes right now (Safari) and Travis cancels after 10 minutes of no new messages there should not be any interruption. Only the tests will take a little bit longer.

**Comment by webzwo0i** [comment]
side note:
We use https://github.com/admc/wd that only supports old Selenium ("legacy" 2). Had no luck migrating to webdriver.io yet, while still preserving the ability to launch our test suite in a local browser.

**Comment by JohnMcLear** [comment]
@webzwo0i are you fixing the settimeouts or me?  Thanks

**Comment by webzwo0i** [comment]
will do it today

**Comment by webzwo0i** [comment]
not finished yet... I wanted to beautify them a little bit, but this took longer than expected.
https://github.com/ether/etherpad-lite/compare/develop...workaround-dom-latency-in-tests#diff-48fdde5ec1dd1027446ff1f41bb125db I cannot handle jquery's Deferred better...

I am triggering rebuilds on travis for the rest of the night, I think tomorrow I am able to prepare a PR

**Comment by webzwo0i** [comment]
Triggering the same build I run into https://github.com/travis-ci/travis-ci/issues/7443 The results in travis web ui (and also using travis-gem locally to get the logs) are not 100% reliable in the first minutes after the job finished and after triggering a rebuild they are overwritten. Now I am pushing empty commits to trigger a new build, so everything can settle and I can watch for sporadic failures.

In case you are working hard today and I consume all saucelabs resources - just ping me and I will stop the rebuilds or limit the number of saucelabs worker. I already removed backend/load tests and also libreoffice to speed things up, but will need ~50 builds to check what fails atm

**Comment by JohnMcLear** [comment]
I am not working hard today.  I am hardly working...  Seriously tho I'm mostly gardening today :P 🌱

**Comment by webzwo0i** [comment]
Should be solved, except for problem no. 4. Tracking this as part of https://github.com/ether/etherpad-lite/issues/4191
