### ISSUE TITLE
Easysync tests aren't run when backend tests are run

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4190]
Easysync tests.js exists in node folder.  They should be refactored and included in the backend tests.

**Comment by webzwo0i** [comment]
I started this some years ago but at that time did not now mocha very well. 
https://github.com/webzwo0i/etherpad-lite/blob/tests-backend-tests/tests/backend/specs/easysync/easysync_tests.js

I can continue porting them if you haven't started

**Comment by JohnMcLear** [comment]
If you started will leave you to finish.  My goal was to take the apply test logic and implement that in load testing

**Comment by JohnMcLear** [comment]
@webzwo0i :+1:

**Comment by webzwo0i** [comment]
70% ready :)

**Comment by rhansen** [comment]
@webzwo0i Do you have a published branch with your work-in-progress commits? If so, would you like my help in finishing?
