### ISSUE TITLE
Error with clientVars hooks

### ISSUE THREAD

**Issue by joassouza** [ether/etherpad-lite#4193]
Since we've updated to the 1.8.4 we've got a bug where the variables set on 
clientVars is not working. A deep look in to the code, I've realised there's one
part of code that's causing the error. That was added on https://github.com/ether/etherpad-lite/commit/d1330a1e1c0fc536244c77605f0612cf4412e9fe. 

The misbehaviour happens because it has async code inside a forEach loop
https://github.com/ether/etherpad-lite/commit/d1330a1e1c0fc536244c77605f0612cf4412e9fe#diff-e4533b536e57db4e3299a5214e5c2e24R88

**To Reproduce**
I've tried to reproduce on a controlled scenario (only one plugin) without success. Maybe, the error
is easily reproducible on instances with lots of plugins and hooks.  

**Expected behavior**
It should allow set variables on clientVars hook

**Screenshots**
![2020-07-23_15_36](https://user-images.githubusercontent.com/4945372/88325321-5699d080-ccfb-11ea-98ca-f12aa72f5c9d.png)

**Desktop (please complete the following information):**
 - OS: [windows, linux, mac]
 - Browser [chrome]

**Comment by JohnMcLear** [comment]
Can we get test coverage in for this please?

**Comment by joassouza** [comment]
I don't know how to test it, could you give me some guidance?
What I did to fix it, it was kind of follow your comment recommendation :)
https://github.com/ether/etherpad-lite/pull/4194/files#diff-e4533b536e57db4e3299a5214e5c2e24L86

**Comment by JohnMcLear** [comment]
fix looks good.  I think the best test coverage is something I documented here: https://mclear.co.uk/2020/07/18/suggestions-for-improving-etherpad-plugins/ where certain plugins(that use hooks in X way) are tested on merge to develop.
