### ISSUE TITLE
Handle deprecation warnings after jquery update

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4196]
I prepared a [gist with integrated versions of jquery-migrate](https://gist.github.com/webzwo0i/f93fbb8f06a85686abcdeff08298d01d) that replace src/static/js/jquery.js

That's a jquery-plugin that should help people with transitioning to new jquery versions. There are two versions of it in the gist atm: one for the old jquery version before @JohnMcLear's update last month and one for the version after update.

The process would be to go back to the old version of last month, replace it with the version in the gist, let frontend tests run and look through all the deprecation warnings (there aren't many with the 1.12.4-version). Best would also be to temporarily activate some of the disabled frontend tests. Even though they might be wrong, they probably trigger additional code paths. It would be also nice to have the process include two browsers, e.g. join the same pad with firefox and chromium and write something because this also triggers other code paths compared to only running the frontend tests.

After warnings are silenced the whole process needs to be repeated with the updated 3.0.0 version.

I am not very skilled in clientside webdev so for me it probably would take a little bit too long, because I would need to learn a lot about browser internals etc to understand and verify the nature of some of the warnings, but I think it would be helpful to actually fix them, especially because 3.0.0 is already outdated and when we update to a recent jquery version, stuff could break.

The reason I stumbled across this is that they made document-ready handler async in 3.0 and I suspect this to have an effect on our frontend tests and page setup in general. Unfortunately though, jquery-migrate does not log warnings in the areas I suspected. (RE frontend tests I found two things that made them unreliable and one that prevented travis to get the logs and I am now testing with jquery 3.1.1 (cf https://blog.jquery.com/2016/07/07/jquery-3-1-0-released-no-more-silent-errors/) because with 3.0 errors from ready-handler are swallowed. Will finish on the weekend)

**Comment by JohnMcLear** [comment]
That was one long weekend ;)

**Comment by webzwo0i** [comment]
Hehe :-) yeah... Fixing the deprecation warnings will be way more convenient when we have console output in frontend tests.

**Comment by webzwo0i** [comment]
Reopening as we're going to update jquery again
