### ISSUE TITLE
[i18n / l10n] Additional strings

### ISSUE THREAD

**Issue by ovari** [ether/etherpad-lite#4202]
Please add additional strings to
https://github.com/ether/etherpad-lite/blob/develop/src/locales/hu.json
and the other locales.

### When joining an Etherpad
For example
https://video.etherpad.com/p/A7rHLQSTbUuBohq6fOK1
please add
````
OK
````
![Landing page](https://user-images.githubusercontent.com/17465872/88749904-ad8a2480-d197-11ea-8b9e-db73925f6e4f.png)

### When in a Etherpad

For example
https://video.etherpad.com/p/A7rHLQSTbUuBohq6fOK1
please add
````
Untitled Pad
OK
Style
Normal
Heading 1
Heading 2
Heading 3
Heading 4
Code
Add new comment on selection
Align Left
Align Center
Align Right
Align Justify
Enable Audio/Video Chat
Audio On At Start
Video On At Start
Show Comments
About
Powered by Etherpad-lite
````
![Style](https://user-images.githubusercontent.com/17465872/88750053-fd68eb80-d197-11ea-8379-e460a57a5f62.png)

![Settings](https://user-images.githubusercontent.com/17465872/88750146-3bfea600-d198-11ea-8ddc-09f84215ad78.png)

````
A warm welcome to Etherpad!

This Etherpad site is built for meetings and on going distance learning during the Corona Virus outbreak.  We will keep this instance up post the outbreak for at least 3 years.

If you want to roll your own Etherpad site then you can.  Etherpad is free and open source.  Https://etherpad.org -- All pads are fully exported with full fidelity so no content or data is lost in the move.

If this Etherpad site doesn't have the functionality you want then see the extensive list of adaptations, plugins and modifications available: https://static.etherpad.org/plugins.html

Thanks to 26LLC for providing the Hosting.  If you have a feature request, problem or bug to report please visit https://github.com/ether/etherpad-lite
````
Should `26LLC` be a hyperlink, say [26LLC](https://26llc.com/)?

What do you think?

Thank you

**Comment by JohnMcLear** [comment]
Please read the docs 

https://translatewiki.net/wiki/Translating:Etherpad_lite

If you require translations in plugins please send pull request to each plugin individually.

**Comment by ovari** [comment]
The following weren't in the file
````
Style
Normal
Heading 1
Heading 2
Heading 3
Heading 4
````

How does one translate them? The don't seem to be in a plugin as they are shown on the main [Etherpad](https://etherpad.org/) page. Image shown below

![image](https://user-images.githubusercontent.com/17465872/88793054-8c4d2680-d1df-11ea-8389-51bd30c4da2c.png)

Thank you

**Comment by ovari** [comment]
The following wasn't in the file
````
Enable Audio/Video Chat
````

How does one translate them? The don't seem to be in a plugin as they are shown on the main Etherpad page. Image shown below
![image](https://user-images.githubusercontent.com/17465872/88793347-ff569d00-d1df-11ea-9674-2176fa966497.png)

Thank you

**Comment by ovari** [comment]
> The [Etherpad Foundation](http://etherpad.org/) hosts a [test site](http://beta.etherpad.org/) for everybody to try it.
https://translatewiki.net/wiki/Translating:Etherpad_lite

The **test site** link http://beta.etherpad.org/ redirects to https://video.etherpad.com/.

Can you please advise:
1. What _plugins_ the test site has?
2. How long does it take for _new strings_ and _translations_ to be live on the test site?

Thank you once again.

**Comment by JohnMcLear** [comment]
Find the plugin, find the translation file, send pull requests to those plugins

1. "What plugins the test site has?", see README.md in etherpad-lite
2.  No set amount of time, depends when I get around to updating it :)

**Comment by ovari** [comment]
https://static.etherpad.org/

https://github.com/ether/ep_headings2/pull/30
https://github.com/ether/ep_spellcheck/pull/14
https://github.com/ether/ep_webrtc/pull/63

**Comment by JohnMcLear** [comment]
?

**Comment by ovari** [comment]
@JohnMcLear can you please help?

1. Can you please merge ether/ep_markdown#37?
2. Is `ep_comments_page` the same as `ether/ep_comments`?
3. Can you please advise where ep_embedded_hyperlinks2 is located?

Thank you

Updating information at https://github.com/ether/etherpad-lite/issues/4202#issuecomment-666286170

**Comment by ovari** [comment]
> Find the plugin, find the translation file, send pull requests to those plugins
>     1. "What plugins the test site has?", see README.md in etherpad-lite

The https://video.etherpad.com/ site doesn't seem to have the https://github.com/JohnMcLear/ep_font_color/ which is stated at https://github.com/ether/etherpad-lite#getting-the-full-features. Can you please advise the plugins that need translating as we seem to not have found the location of what plugins the test site has from the README.md in etherpad-lite.

Thank you

**Comment by slel** [comment]
> 3. Can you please advise where ep_embedded_hyperlinks2 is located?

Not sure if that answers one of your questions, but
searching at https://static.etherpad.org/index.html
for `ep_embedded_hyperlinks2` points to the npmjs page
https://www.npmjs.com/package/ep_embedded_hyperlinks2
which has a link to the repository
https://github.com/seballot/ep_embedded_hyperlinks2

**Comment by ovari** [comment]
All the plugins that are used in the test site should be merged. Cf. https://github.com/ether/etherpad-lite/issues/4202#issuecomment-666286170. If any plugins have been missed, please feel free to advise so this can be remedied.

@JohnMcLear can you please update the test site to enable `testing Etherpad[Develop Branch] and Plugins`?
Cf. https://github.com/ether/etherpad-lite/wiki/Sites-that-run-Etherpad-Lite#development-environments-used-for-testing-new-versions--plugins-etc

Thank you

**Comment by ovari** [comment]
@muxator could you please advise when these translations would be available in the released branch?
https://github.com/ether/etherpad-lite/tags

Thank you

**Comment by JohnMcLear** [comment]
I would need to publish all the plugins,.

Afaik Etherpad plugins do/does test against the develop branch.

I release on bugfix/feature add/.travis config change.

**Comment by ovari** [comment]
Does **all** plugins mean there are more plugins than https://github.com/ether/etherpad-lite/issues/4202#issuecomment-666286170 that need to be translated into `hu`?

Do you know when a `bugfix/feature add/.travis config change` is planned?

Sorry, we don't have a server; however, it is hoped that anyone who does will benefit from the `hu` translations.

Thank you once again.

**Comment by JohnMcLear** [comment]
@ovari the list of plugins on video.etherpad.com is fluid, but for the moment I would say they are all translated with your thanks.  Did you get the HTML / EJS modified for the other plugins you wanted?  I don't recall merging it!

I don't know when a release is due, it really depends on what changes mostly with travis as that will trigger an automated update/release.  I'm not willing to trigger it and fire up 10k vms just for some translations(of only one language) tho ;)

Appreciate it RE translations.  Perhaps a future endeavour may be to push plugin translations to the translatewiki team so they are automatically updated/maintained into all languages...  Right now I have other things taking my attention, apologies.  However if you fancy that challenge/have the time for it I think it would be a suitable move.  I can set you up as a repo maintainer/admin of the package and we can work with @Nikerabbit et al to support translating plugins on TW...  Any thoughts on taking that responsibility on?

**Comment by ovari** [comment]
> Did you get the HTML / EJS modified for the other plugins you wanted?

Not sure. https://github.com/ether/etherpad-lite/issues/4202#issuecomment-666286170 lists the plugins that are merged. @JohnMcLear are you able to please advise if there are other ones yet to be modified that we have missed?

Can you please advise if `ep_comments_page` is the same as `ether/ep_comments`? Cf. https://github.com/ether/etherpad-lite/issues/4202#issuecomment-667450039

> I don't know when a release is due.

Do you know if it would be within a year or by the end of the year? Thank you

>  Perhaps a future endeavour may be to push plugin translations to the translatewiki team so they are automatically updated/maintained into all languages

That is an excellent idea.

> I can set you up as a repo maintainer/admin of the package and we can work with @Nikerabbit et al to support translating plugins on TW

Thank you for the privilege; however, we only use GitHub web based interface.

> Any thoughts on taking that responsibility on?

Thank you for thinking of us. Unfortunately, coding requires a higher level than translating. If there is something we could help @Nikerabbit et al. with we would be happy to help.

Thank you once again.

**Comment by Nikerabbit** [comment]
We can add plugins as well, if we are speaking about a dozen of them. Basically need the same things as for initial setup:

- Name
- Description (optional)
- Repo URLs and paths to files and push access for pushes or pull requests

If we are talking about a larger number of plugins, we need to add some automation and process for keeping the list up to date to keep overhead manageable.

**Comment by JohnMcLear** [comment]
Automation of plugins you say,...  https://github.com/ether/etherpad-lite/tree/develop/bin/plugins

We can make it part of the auto-update of plugins process..  

Name, Description and Repo URL can come from package.json

Let me know what it takes on your side @Nikerabbit -- for example we can do an API call to make it if that exists?  Alternatively I can create a CSV file or some such but obviously that would not be dynamic as more plugins are supported...

**Comment by Nikerabbit** [comment]
If you have a list of plugins you maintain & have access, we can start with those and them manually.

On our side, we will make the current "Etherpad lite" group to be an aggregate group that consists of `Etherpad lite – Core` and  `Etherpad lite - Plugin Name` groups corresponding to the new plugins.

Oh and we also need to know whether those plugins also follow the `develop` branch model or something different.

**Comment by JohnMcLear** [comment]
Plugin list at https://www.npmjs.com/~johnyma22 -- scroll down to get all of them (afaik it's 131 plugins)

All plugins follow develop branch model.

**Comment by Nikerabbit** [comment]
Hmm, I don't see any links to git repos on those package pages.

**Comment by JohnMcLear** [comment]
would it help if I went through each package.json and ensured the repository is set?  It usually is..

https://www.npmjs.com/package/ep_metrics is an example of the repository set in package.json

**Comment by Nikerabbit** [comment]
I guess it would help... though your examples also seems to be an example of a plugin with no i18n messages?

**Comment by JohnMcLear** [comment]
I went ahead and made sure most plugins have a git repository in ``package.json``.

@ovari I suggest you go through every plugin you want translations for and ensure the translations are supported.

Here are the plugins you need to modify:

```
node_modules/ep_add_buttons
node_modules/ep_align_v2
node_modules/ep_better_pdf_export
node_modules/ep_br_to_p
node_modules/ep_button_link
node_modules/ep_chat_always_on_screen_and_tokbox_link
node_modules/ep_clear_authorship_no_prompt
node_modules/ep_clear_formatting
node_modules/ep_codepad
node_modules/ep_copypad
node_modules/ep_copy_paste_images
node_modules/ep_copy_paste_select_all
node_modules/ep_database_query_auth
node_modules/ep_defaultPadText
node_modules/ep_define
node_modules/ep_desktop_notifications
node_modules/ep_disable_change_author_name
node_modules/ep_disable_custom_scripts_and_styles
node_modules/ep_disable_drag_and_drop
node_modules/ep_disable_error_messages
node_modules/ep_disableErrorMessages
node_modules/ep_disable_reset-authorship_colours
node_modules/ep_disable_reset_authorship_colours
node_modules/ep_draw
node_modules/ep_embedmedia
node_modules/ep_ether-o-meter
node_modules/ep_export_authors
node_modules/ep_extend_settings
node_modules/ep_feedback_ii
node_modules/ep_file_menu_toolbar
node_modules/ep_fileupload
node_modules/ep_git_commit_saved_revision
node_modules/ep_github
node_modules/ep_google_analytics
node_modules/ep_header_and_footer
node_modules/ep_helmet
node_modules/ep_help_bubbles
node_modules/ep_hide_line_numbers
node_modules/ep_imageconvert
node_modules/ep_indent_context
node_modules/ep_invite_via_email
node_modules/ep_irc
node_modules/ep_latex
node_modules/ep_latexexport
node_modules/ep_list_pads
node_modules/ep_loading_message
node_modules/ep_mammoth
node_modules/ep_mediawiki
node_modules/ep_metrics
node_modules/ep_monospace_default
node_modules/ep_narration
node_modules/ep_oauth
node_modules/ep_offline_edit
node_modules/ep_pad_activity_nofication_in_title
node_modules/ep_pad_title
node_modules/ep_plantuml
node_modules/ep_post_data
node_modules/ep_previewimages
node_modules/ep_print
node_modules/ep_print_preview_pdf
node_modules/ep_prompt_for_name
node_modules/ep_public_view
node_modules/ep_push2delete
node_modules/ep_real_time_chat
node_modules/ep_reference
node_modules/ep_remove_embed
node_modules/ep_rewrite_share_paths
node_modules/ep_right_to_left
node_modules/ep_rss
node_modules/ep_rtc
node_modules/ep_scrollto
node_modules/ep_search
node_modules/ep_set_title_on_pad
node_modules/ep_show_whitespace
node_modules/ep_slideshow
node_modules/ep_sociallinks
node_modules/ep_special_characters
node_modules/ep_stats
node_modules/ep_sticky_attributes
node_modules/ep_stop_writing
node_modules/ep_switch_pad
node_modules/ep_tasklist
node_modules/ep_template_content
node_modules/ep_text_statistics
node_modules/ep_text_to_speech
node_modules/ep_themes
node_modules/ep_timesliderdiff
node_modules/ep_two_editors
node_modules/ep_visual_slider
node_modules/ep_wrap
node_modules/ep_xmlexport
```

You can use ep_page_view or something as easy reference for how to modify the EJS/HTML to support translations.  I expect it will take a few hours work.  @ovari let me know when this is done so we can discuss next steps with @Nikerabbit

**Comment by ovari** [comment]
How can this issue be re-opened? Thank you

**Comment by JohnMcLear** [comment]
It doesn't need to be re-opened, the issue needs to exist on each plugin but the best thing for you to do is just to start working and start sending through pull requests with your translation files and I will merge.

**Comment by ovari** [comment]
@JohnMcLear does this change https://github.com/ether/etherpad-lite/issues/4317 anything?
