### ISSUE TITLE
Language switch ?lang=<locale> and language selector/drop-down box

### ISSUE THREAD

**Issue by ovari** [ether/etherpad-lite#4203]
1. Please allow adding a language switch, for example `?lang=fr` for `French`
https://video.etherpad.com/?lang=fr

2. Please add a language/locale selector/drop-down box on the landing page at
https://video.etherpad.com/

What do you think?

Thank you

**Comment by JohnMcLear** [comment]
Seems like a good idea and easy to do.  Just copy paste the logic from pad.html and also see how we handle URL Params in pad.js.

**Comment by ovari** [comment]
.

**Comment by JohnMcLear** [comment]
@ovari we allow non worked on issues to go stale.  If you want this to be worked on please ask people to work on it.
