### ISSUE TITLE
Is there a way to go back to the old style/theme?

### ISSUE THREAD

**Issue by hydrogenpi** [ether/etherpad-lite#4204]
I really am not a fan of the new aesthetic makeover, how to keep the updated code base but revert to the old styles?

* * *

name: Feature request
about: Suggest an idea for this project
title: ''
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when (...)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Plugin?**
Might this feature be better suited to being a plugin?  Usually features that can be plugins, should be.

**Comment by webzwo0i** [comment]
Is skinName parameter in settings.json what you are looking for?

**Comment by webzwo0i** [comment]
Not sure if there is a plugin or way to change this as a user

**Comment by JohnMcLear** [comment]
Yea this is changable server-wide in ``settings.json``.  Afaik ep_themes provides user changable edits but IDK about going back from colibris to no-skin.
