### ISSUE TITLE
Relative static file path and Pad names depend on the URL

### ISSUE THREAD

**Issue by HMarzban** [ether/etherpad-lite#4207]
**Describe the bug**

Hello John, two dependencies blocking us, to make a plugin.

1. Relative static files path, which depends on the URL path.
2. Pad name, which the pad management system also gets that name from the URL path.

#### What do I want to achieve with the plugin?

I'm going to create a sub pad! like this one `/p/:pad/:subpad`. the navigation flow is so simple. when a user navigates to, i have to sever `pad.html`. so far there is not any problem.

_My router function for sub pad (like the original one):_

```js
  args.app.get('/p/:pad/:view', function(req, res) {
    const {pad, view} = req.params

    // The below might break for pads being rewritten
    var isReadOnly = req.url.indexOf("/p/r.") === 0;

    hooks.callAll("padInitToolbar", {
      toolbar: toolbar,
      isReadOnly: isReadOnly
    });

    res.send(eejs.require("ep_etherpad-lite/templates/pad.html", {
      req: req,
      toolbar: toolbar,
      isReadOnly: isReadOnly
    }));

  })
```

**Notes:** here we don't ever use `req` in that file! why do you pass it to `eejs` (At least I don't know how it's handy).
**suggestion:** It would be good to pass the pad name here to remove dependency on URL. (I did not go deep into the Etherpad core to realize why you make this decision, maybe there is a reason.)

Okay let's continue,
Every problem pops up when the `pad.html` generates and renders on the client-side.

These are the logs when i look up the network tab of the browser:

```
/p/:pad
Request URL: http://localhost:9001/static/js/html10n.js?v=36cee976
Status Code: 200

/p/:pad/:subPad
Request URL: http://localhost:9001/p/static/js/html10n.js?v=1a7ddb6c
Status Code: 404 Not Found

/p/:pad/:subPad/:view
Request URL: http://localhost:9001/p/static/js/html10n.js?v=1a7ddb6c
Status Code: 404 Not Found
```

![image](https://user-images.githubusercontent.com/20157508/88842359-99c0db80-d1f4-11ea-8b37-6fb6339b2ee1.png)

So what's happening here! and what was the strategy that caused these problems is the main question?

I took a look at the code and found out the two reasons that I mentioned in the beginning.

#### 1.Relative static files path, which depends on the URL path

These lines in `pad.html` have a relative path and depend on the URL, if the URL changes, the client can not resolve paths then they get `404` status code.

**suggestion:** If it's possible, I do suggest resolving these paths in the template engine.

```
45: <link href="../static/css/pad.css?v=<%=settings.randomVersionString%>" rel="stylesheet">
48: <link href="../static/skins/<%=encodeURI(settings.skinName)%>/pad.css?v=<%=settings.randomVersionString%>" rel="stylesheet">
55: <script type="text/javascript" src="../static/js/html10n.js?v=<%=settings.randomVersionString%>"></script>
56: <script type="text/javascript" src="../static/js/l10n.js?v=<%=settings.randomVersionString%>"></script>
438: <script type="text/javascript" src="../static/js/require-kernel.js?v=<%=settings.randomVersionString%>"></script>
441: <script type="text/javascript" src="../javascripts/lib/ep_etherpad-lite/static/js/pad_utils.js?callback=require.define&v=<%=settings.randomVersionString%>"></script>

464: <script type="text/javascript" src="../javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=<%=settings.randomVersionString%>"></script>

465: <script type="text/javascript" src="../javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define&v=<%=settings.randomVersionString%>"></script>

468: <script type="text/javascript" src="../static/skins/<%=encodeURI(settings.skinName)%>/pad.js?v=<%=settings.randomVersionString%>"></script>

481: require.setRootURI(baseURL + "javascripts/src");
482: require.setLibraryURI(baseURL + "javascripts/lib");
```

#### 2.Pad name, which the pad management system also gets that name from the URL path

If we resolve the first issue, then all files resolve correctly, but after all the second one shows up!

In the files like `pad.js` when the `sendClientReady` function call, it makes `padId` with `location.pathname`. (stateful design)

```js
// /etherpad-lite/src/templates/pad.html
143: var padId = document.location.pathname.substring(document.location.pathname.lastIndexOf("/") + 1);
```

e.g. if a user is in this route `/p/padname/view`, the code takes the last part of the location path for the pad name which is `view` in this case. In this way the pad name is okay, but the question is, what should we do in the server-side (from middleware to router)?

I hope I have fully explained what i want.

**Comment by JohnMcLear** [comment]
Just to be clear, I'm not gonna be spending any time on this.  Sorry, I have other commitments 🔢

**Comment by HMarzban** [comment]
It's okay, as long as you know, this feature is a big shift in the core.
Do you think if we work on it, it has a chance to merge with the master?

**Comment by JohnMcLear** [comment]
Yea if it's stable it absolutely would land in develop > master/release :)
