### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by fangwei57** [ether/etherpad-lite#4213]
**TypeError**
When i  deploy it with docker 

**To Reproduce**

1. run the docker image  "etherpad/etherpad"
2. upload or download with office file  at web page 
3. contanier close 

**Expected behavior**
docker image etherpad/etherpad:lasted
`etherpad    | All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad-lite
etherpad    | Random string used for versioning assets: 9c641f04
etherpad    | [2020-08-05 06:09:42.944] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/opt/etherpad-lite/settings.json"
etherpad    | [2020-08-05 06:09:42.951] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/opt/etherpad-lite/credentials.json"
etherpad    | settings loaded from: /opt/etherpad-lite/settings.json
etherpad    | No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
etherpad    | [2020-08-05 06:09:42.958] [WARN] console - No "skinName" parameter found. Please check out settings.json.template and update your settings.json. Falling back to the default "colibris".
etherpad    | [2020-08-05 06:09:42.958] [INFO] console - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
etherpad    | [2020-08-05 06:09:42.959] [INFO] console - Session key file "/opt/etherpad-lite/SESSIONKEY.txt" not found. Creating with random contents.
etherpad    | [2020-08-05 06:09:42.960] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production. File location: /opt/etherpad-lite/var/dirty.db
etherpad    | [2020-08-05 06:09:43.999] [INFO] APIHandler - Api key file "/opt/etherpad-lite/APIKEY.txt" not found. Creating with random contents.
etherpad    | [2020-08-05 06:09:44.171] [INFO] console - Installed plugins: 
etherpad    | [2020-08-05 06:09:44.174] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
etherpad    | [2020-08-05 06:09:44.175] [INFO] console - Your Etherpad version is 1.8.4 (1b6a9d8)
etherpad    | [2020-08-05 06:09:44.321] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
etherpad    | [2020-08-05 06:09:44.321] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
etherpad    | Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
etherpad    | Node worker_threads not available. Trying to fall back to tiny-worker polyfill...
etherpad    | [2020-08-05 06:09:46.026] [INFO] Minify - Compress CSS file css/pad.css.
etherpad    | [2020-08-05 06:09:46.033] [INFO] Minify - Compress CSS file skins/colibris/pad.css.
etherpad    | [2020-08-05 06:09:46.199] [INFO] Minify - Compress CSS file css/iframe_editor.css.
etherpad    | [2020-08-05 06:09:46.242] [INFO] Minify - Compress CSS file css/iframe_editor.css.
etherpad    | [2020-08-05 06:09:46.493] [INFO] access - [CREATE] Pad "1": Client 07MYH2A255fA-DG1AAAB with IP "192.168.182.1" created the pad
etherpad    | [2020-08-05 06:11:13.656] [INFO] console - Exporting pad "1" in doc format
etherpad    | [2020-08-05 06:11:13.673] [ERROR] console - TypeError: Cannot read property 'on' of undefined
etherpad    |     at /opt/etherpad-lite/src/node/utils/LibreOffice.js:94:22
etherpad    |     at eachfn (/opt/etherpad-lite/src/node_modules/async/dist/async.js:2948:28)
etherpad    |     at replenish (/opt/etherpad-lite/src/node_modules/async/dist/async.js:440:21)
etherpad    |     at /opt/etherpad-lite/src/node_modules/async/dist/async.js:445:13
etherpad    |     at eachOfLimit$1 (/opt/etherpad-lite/src/node_modules/async/dist/async.js:471:34)
etherpad    |     at awaitable (/opt/etherpad-lite/src/node_modules/async/dist/async.js:208:32)
etherpad    |     at eachOfSeries (/opt/etherpad-lite/src/node_modules/async/dist/async.js:658:16)
etherpad    |     at awaitable (/opt/etherpad-lite/src/node_modules/async/dist/async.js:208:32)
etherpad    |     at awaitify (/opt/etherpad-lite/src/node_modules/async/dist/async.js:2947:9)
etherpad    |     at awaitable (/opt/etherpad-lite/src/node_modules/async/dist/async.js:208:32)
etherpad    | [2020-08-05 06:11:13.674] [INFO] console - graceful shutdown...
etherpad    | [2020-08-05 06:11:13.674] [ERROR] console - Error: spawn /usr/bin/soffice EACCES
etherpad    |     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
etherpad    |     at onErrorNT (internal/child_process.js:415:16)
etherpad    |     at process._tickCallback (internal/process/next_tick.js:63:19)
etherpad    | [2020-08-05 06:11:13.674] [INFO] console - db sucessfully closed.`

docker image etherpad/etherpad:1.8.0
`etherpad    | [2020-08-05 06:23:10.095] [DEBUG] console - Running on Node v10.17.0 (minimum required Node version: 8.9.0)
etherpad    | [2020-08-05 06:23:10.251] [INFO] console - All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad-lite
etherpad    | [2020-08-05 06:23:10.251] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/opt/etherpad-lite/settings.json"
etherpad    | [2020-08-05 06:23:10.251] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/opt/etherpad-lite/credentials.json"
etherpad    | [2020-08-05 06:23:10.256] [INFO] console - settings loaded from: /opt/etherpad-lite/settings.json
etherpad    | [2020-08-05 06:23:10.256] [INFO] console - No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
etherpad    | [2020-08-05 06:23:10.257] [WARN] console - No "skinName" parameter found. Please check out settings.json.template and update your settings.json. Falling back to the default "no-skin".
etherpad    | [2020-08-05 06:23:10.258] [INFO] console - Using skin "no-skin" in dir: /opt/etherpad-lite/src/static/skins/no-skin
etherpad    | [2020-08-05 06:23:10.258] [INFO] console - Session key file "/opt/etherpad-lite/SESSIONKEY.txt" not found. Creating with random contents.
etherpad    | [2020-08-05 06:23:10.259] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production. File location: /opt/etherpad-lite/var/dirty.db
etherpad    | [2020-08-05 06:23:11.236] [INFO] APIHandler - Api key file "/opt/etherpad-lite/APIKEY.txt" not found. Creating with random contents.
etherpad    | [2020-08-05 06:23:11.490] [INFO] console - Installed plugins: 
etherpad    | [2020-08-05 06:23:11.492] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
etherpad    | [2020-08-05 06:23:11.492] [INFO] console - Your Etherpad version is 1.8.0 (1dfd52b)
etherpad    | [2020-08-05 06:23:11.609] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
etherpad    | [2020-08-05 06:23:11.609] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json
etherpad    | [2020-08-05 06:23:11.609] [WARN] console - Etherpad is running in Development mode.  This mode is slower for users and less secure than production mode.  You should set the NODE_ENV environment variable to production by using: export NODE_ENV=production
etherpad    | [2020-08-05 06:23:15.548] [INFO] access - [CREATE] Pad "1": Client MB4KTPQxJ2_E8HDrAAAB with IP "192.168.182.1" created the pad
etherpad    | [2020-08-05 06:23:17.766] [INFO] console - req.params.pad 1
etherpad    | [2020-08-05 06:23:17.780] [ERROR] console - TypeError: Cannot read property 'on' of undefined
etherpad    |     at /opt/etherpad-lite/src/node/utils/LibreOffice.js:82:22
etherpad    |     at /opt/etherpad-lite/src/node_modules/async/lib/async.js:610:21
etherpad    |     at /opt/etherpad-lite/src/node_modules/async/lib/async.js:249:17
etherpad    |     at iterate (/opt/etherpad-lite/src/node_modules/async/lib/async.js:149:13)
etherpad    |     at async.eachSeries (/opt/etherpad-lite/src/node_modules/async/lib/async.js:165:9)
etherpad    |     at _asyncMap (/opt/etherpad-lite/src/node_modules/async/lib/async.js:248:13)
etherpad    |     at Object.mapSeries (/opt/etherpad-lite/src/node_modules/async/lib/async.js:231:23)
etherpad    |     at Object.async.series (/opt/etherpad-lite/src/node_modules/async/lib/async.js:608:19)
etherpad    |     at doConvertTask (/opt/etherpad-lite/src/node/utils/LibreOffice.js:61:9)
etherpad    |     at Immediate.process (/opt/etherpad-lite/src/node_modules/async/lib/async.js:809:21)
etherpad    | [2020-08-05 06:23:17.780] [INFO] console - graceful shutdown...
etherpad    | [2020-08-05 06:23:17.781] [ERROR] console - Error: spawn /usr/bin/soffice EACCES
etherpad    |     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
etherpad    |     at onErrorNT (internal/child_process.js:415:16)
etherpad    |     at process._tickCallback (internal/process/next_tick.js:63:19)
etherpad    | [2020-08-05 06:23:17.781] [INFO] console - db sucessfully closed.`

I don't know whether I configured it wrong

**Comment by webzwo0i** [comment]
can you docker run it with ls -la /usr/bin/soffice as last command please?

**Comment by fangwei57** [comment]
i  use docker-compose to run it . 
the config

`version: '2'
services:
  etherpad:
    image: etherpad/etherpad
    container_name: etherpad
    hostname: etherpad
    restart: always
    environment:
       - DB_TYPE=mysql
       - DB_HOST=192.168.182.128
       - DB_PORT=3306
       - DB_NAME=etherpad
       - DB_USER=root
       - DB_PASS=mysql123
    ports:
       - "9001:9001"
    volumes:
       - /usr/local/office/libreoffice-6.3.6.2:/usr/bin/soffice`

**Comment by fangwei57** [comment]
> version: '2'
services:
  etherpad:
    image: etherpad/etherpad
    container_name: etherpad
    hostname: etherpad
    restart: always
    environment:
       - DB_TYPE=mysql
       - DB_HOST=192.168.182.128
       - DB_PORT=3306
       - DB_NAME=etherpad
       - DB_USER=root
       - DB_PASS=mysql123
    ports:
       - "9001:9001"
    volumes:
       - /usr/local/office/libreoffice-6.3.6.2:/usr/bin/soffice

**Comment by webzwo0i** [comment]
you can use 'command: bash -c "ls -la /usr/bin/soffice"' inside your docker-compose.yml

**Comment by fangwei57** [comment]
> you can use 'command: bash -c "ls -la /usr/bin/soffice"' inside your docker-compose.yml
i use `volumes :
- /usr/local/office/libreoffice-6.3.6.2:/usr/bin/soffice`  so document list as the same as the path '/usr/local/office/libreoffice-6.3.6.2 ' that installed on the host。

![image](https://user-images.githubusercontent.com/20739640/89387618-53f49d80-d735-11ea-96de-7087a4ee3536.png)


**If i do not config the volumes ,the container will show the follow error **

` etherpad    | All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad-lite
etherpad    | Random string used for versioning assets: 36f243c1
etherpad    | [2020-08-05 07:23:22.933] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/opt/etherpad-lite/settings.json"
etherpad    | [2020-08-05 07:23:22.935] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/opt/etherpad-lite/credentials.json"
etherpad    | settings loaded from: /opt/etherpad-lite/settings.json
etherpad    | No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
etherpad    | [2020-08-05 07:23:22.940] [WARN] console - No "skinName" parameter found. Please check out settings.json.template and update your settings.json. Falling back to the default "colibris".
etherpad    | [2020-08-05 07:23:22.940] [INFO] console - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
etherpad    | [2020-08-05 07:23:22.941] [INFO] console - Session key file "/opt/etherpad-lite/SESSIONKEY.txt" not found. Creating with random contents.
etherpad    | [2020-08-05 07:23:22.941] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production. File location: /opt/etherpad-lite/var/dirty.db
etherpad    | [2020-08-05 07:23:23.042] [ERROR] console - soffice (libreoffice) does not exist at this path, check your settings file. File location: /usr/bin/soffice`

**Comment by fangwei57** [comment]
![image](https://user-images.githubusercontent.com/20739640/89387780-93bb8500-d735-11ea-9c9a-346329d33b54.png)

and entry  the container without the path 
![image](https://user-images.githubusercontent.com/20739640/89387956-dbdaa780-d735-11ea-83de-0fa10eb472c9.png)

**Comment by webzwo0i** [comment]
in /usr/bin/soffice a binary file is expected, not a directory. Try setting the volume target to /usr/local/.... eg
`/usr/local/office/libreoffice-6.3.6.2:/usr/local/office/libreoffice-6.3.6.2`, find out where your executable is located (find /usr/local/office/libreoffice-6.3.6.2 -type f -executable) and set your soffice environment variable to that destination.

Is there a reason you build libreoffice yourself? I would recommend building your own image based on etherpad/etherpad and simply call `RUN apt update && apt install -y --no-install-recommends` in your Dockerfile and then in docker-compose.yml use your own build that includes libreoffice

**Comment by fangwei57** [comment]
> in /usr/bin/soffice a binary file is expected, not a directory. Try setting the volume target to /usr/local/.... eg
> `/usr/local/office/libreoffice-6.3.6.2:/usr/local/office/libreoffice-6.3.6.2`, find out where your executable is located (find /usr/local/office/libreoffice-6.3.6.2 -type f -executable) and set your soffice environment variable to that destination.
> 
> Is there a reason you build libreoffice yourself? I would recommend building your own image based on etherpad/etherpad and simply call `RUN apt update && apt install -y --no-install-recommends libreoffice-writer` in your Dockerfile and then in docker-compose.yml use your own build that includes libreoffice

It works! thankyou!

`FROM etherpad/etherpad
USER root
COPY ./sources.list  /etc/apt/sources.list
COPY ./rootfs/defaults/settings.json /opt/etherpad-lite/settings.json
RUN apt-get update && apt-get install -y --no-install-recommends libreoffice-writer


EXPOSE 9001`

change to chinese repo 
`deb http://mirrors.ustc.edu.cn/debian stable main contrib non-free
# deb-src http://mirrors.ustc.edu.cn/debian stable main contrib non-free
deb http://mirrors.ustc.edu.cn/debian stable-updates main contrib non-free
# deb-src http://mirrors.ustc.edu.cn/debian stable-updates main contrib non-free
# deb http://mirrors.ustc.edu.cn/debian stable-proposed-updates main contrib non-free
# deb-src http://mirrors.ustc.edu.cn/debian stable-proposed-updates main contrib non-free`

**Comment by slel** [comment]
@fangwei57 can you edit your last comment
to use triple-backticks to display blocks of code?

Something like

    ```
    bits of code
    # comments
    more bits of code
    ```

will render properly -- otherwise comments render as titles.
