### ISSUE TITLE
Can't copy paste when etherpad is in iframe

### ISSUE THREAD

**Issue by nickhil-tekwani** [ether/etherpad-lite#4218]
**Describe the bug**
I am trying to embed etherpad into an iframe on a different website such that someone can collaborate from either the iframe or the etherpad directly. When in the etherpad directly, copy+paste works great, but from within the iframe there seems to be no access to the clipboard. 

I understand that this is is a generally known issue with cross-domain iframes due to security risks. However, since I own both the site that the iframe exists on as well as the server that the etherpad is hosted on, I can make edits accordingly on either one. 
Are there any known workarounds/patches/plugins for etherpad to get around this issue and allow for copy/paste when rendered through an iframe?

**To Reproduce**
1. Put desired link to etherpad in an iframe on a different website 
2. Try to paste in that iframe
3. See error: whatever is pasted is not what's actually the most recent on clipboard 
4. Try to copy text from that iframe, then go to a separate site and paste 
5. See error: whatever is pasted is not actually what you copied from the etherpad iframe

**Expected behavior**
Clipboard should be updated and used appropriately when editing etherpad in an iframe on a separate website

**Device Information**
 - OS: macOS
 - Browser: chrome

**Additional context**
I believe one work around could be by overriding the cmd+c/v or ctrl+c/v hotkeys in pad.html (using [Mousetrap](https://github.com/ccampbell/mousetrap)), but in my testing this does not work since the pad editor is in an iframe within pad.html so hotkeys while the iframe editor is in focus do not get triggered. 

Also, to make this fix work I would have to have some information on what text is currently selected in the iframe editor. Based on my reading of the documentation, this seems possible considering that the toggleAttributeOnSelection function exists (see [here](https://etherpad.org/doc/v1.2.7/#index_editorinfo_ace_toggleattributeonselection)) but there doesn't seem to be a function that simply returns what is current selected in the pad editor.

These two issues seem to be less so bugs and more so just related to my understanding of etherpad. I am relatively new to etherpad development so any help is much appreciated!

**Comment by JohnMcLear** [comment]
@nickhil-tekwani Sorry I didn't respond to this because I assume you resolved it with a quick Google check?

https://github.com/flutter/flutter/issues/53651 for more details.  TLDR; use https.
