### ISSUE TITLE
New line added while typing

### ISSUE THREAD

**Issue by Gredin67** [ether/etherpad-lite#4219]
**Describe the bug**
New lines are added while typing writing continues in the new line up or down.

**To Reproduce**
1. Type text
4. See new lines introduced automatically

**Expected behavior**
no new line while typing

**Screenshots**
https://forum.arn-fai.net/uploads/default/original/2X/c/cbf0c02db17f3e8de90a3904441d1b11d85a3e09.gif

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser Firefox
 - Version [78.1.0]

**Additional context**
installed with yunohost https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/112

**Comment by JohnMcLear** [comment]
I doubt this is an Etherpad bug.  We have test coverage in for this sort of stuff..

Can you replicate on latest develop branch of Etherpad or https://video.etherpad.com

**Comment by Gredin67** [comment]
Could it be related to one of the plugins listed here? : https://github.com/YunoHost-Apps/etherpad_mypads_ynh#additionnal-informations

**Comment by JohnMcLear** [comment]
Please read the issue template!  It says to confirm the bug without plugins before creating the issue.

**Comment by Gredin67** [comment]
yep, sorry, it was related to plugins that were not updating correctly
