### ISSUE TITLE
Confusing when Create or Open a new pad with name 

### ISSUE THREAD

**Issue by GeminienTan** [ether/etherpad-lite#4220]
I am a new user to Etherpad.
I am confusing when creating a new pad.
Sometimes when I entered a name for a new pad, I am not sure that I am creating a pad or opening a pad. 
Is there a way to know if the name of a pad has been created?
Thank you.

**Comment by regnoh** [comment]
I am a new user too
when I access the name, it will hint the names I used.
and I installed the plugin “adminpads3“ to manage all my pads
