### ISSUE TITLE
ADMIN_USER missing in settings template

### ISSUE THREAD

**Issue by lupa18** [ether/etherpad-lite#4223]
**Describe the bug**
In Docker deployment, if you don't set env var ADMIN_USER then you got this warning:
`WARNING: The ADMIN_USER variable is not set. Defaulting to a blank string.`

So you think you must set that variable, but settings template didn't include such option.
 
The result is: you set that variable but it hasn't any effect. 

**To Reproduce**
1. Create the container and run with env variables set, particularly ADMIN_USER and ADMIN_PASSWORD
2. Set non empty values, ie: myadmin / mypass
3. Try to login with myadmin / mypass

**Expected behavior**
You can't login to admin interface with myadmin / mypass credentials

What actually happen is that you will success making login as: admin / mypass (instead myadmin)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: NA
 - Version: tested in tag 1.8.4 and master

**Comment by JohnMcLear** [comment]
@rhansen Can you look into this please?  I still don't want Docker issues on my radar :+1:

**Comment by rhansen** [comment]
> In Docker deployment, if you don't set env var ADMIN_USER then you got this warning:
> `WARNING: The ADMIN_USER variable is not set. Defaulting to a blank string.`

I am unable to reproduce that warning. Where are you seeing it?

If I run `git grep ADMIN_USER` I get no hits, so I'm not surprised that setting `ADMIN_USER` has no effect. That warning must be coming from somewhere else, not Etherpad.

I don't think the `settings.json` environment variable substitution works for JSON keys (only values), so if you want to change the admin username you will have to edit [`settings.json.docker` line 405](https://github.com/ether/etherpad-lite/blob/ec01e4c9478930a1411b2c602454f37c4bbbc1ee/settings.json.docker#L405).

**Comment by lupa18** [comment]
Sorry, can't make it happen again. I will delete ADMIN_USER references from my env files. 

Thanks for your time.
