### ISSUE TITLE
how can i see Etherpad logs, please share the log file location

### ISSUE THREAD

**Issue by girdharsoni** [ether/etherpad-lite#4225]

**Comment by girdharsoni** [comment]
ok i am checking

**Comment by regnoh** [comment]
as follow, in settings.json, search "logconfig" > uncomment "type" : "file"... > change the filename > restart etherpad > will see server.log in rootpath 
 "logconfig" :
    { "appenders": [
        { "type": "console"
        //, "category": "access"// only logs pad access
        }

      
      , { "type": "file"
      , "filename": "server.log"
      , "maxLogSize": 20971520
      , "backups": 10 // how many log files there're gonna be at max
      //, "category": "test" // only log a specific category
        }

**Comment by brunob** [comment]
This one could be closed too...

**Comment by JohnMcLear** [comment]
Ops are friggin lazy :P  tnx @brunob

**Comment by brunob** [comment]
@JohnMcLear u're welcome :)
