### ISSUE TITLE
Error when trying to delete a group through the http api - WAITING ON MERGE OF TESTS

### ISSUE THREAD

**Issue by etienneleba** [ether/etherpad-lite#4227]
## Describe the bug
I have a php app which create a group, create a pad inside the group, some authors. When I show the pad, the app create a session token for the user. 
Then the app want to delete the group but there is an internal error. If the app doesn't create session token, the app can delete the group.

I looked into the etherpad code and it's when etherpad is deleting the session.

So, I tried to delete the sessions before delete the group but it didn't work, someone have a clue for me ? 

#### API Error
```
{
    "code": 2,
    "message": "createHTTPError.InternalError is not a constructor",
    "data": null
}
```
#### Etherpad Error
```
etherpad_1  | [2020-08-26 13:53:09.998] [ERROR] API - TypeError: Cannot convert undefined or null to object
etherpad_1  |     at Function.keys (<anonymous>)
etherpad_1  |     at Object.exports.deleteGroup (/opt/etherpad-lite/src/node/db/GroupManager.js:56:28)
etherpad_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
etherpad_1  | TypeError: Cannot convert undefined or null to object
etherpad_1  |     at Function.keys (<anonymous>)
etherpad_1  |     at Object.exports.deleteGroup (/opt/etherpad-lite/src/node/db/GroupManager.js:56:28)
etherpad_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
etherpad_1  | [2020-08-26 13:53:09.999] [ERROR] console - (node:1) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
```

## Expected behavior
It should delete the group

## Additional context
I'm running etherpad on Docker

**Comment by JohnMcLear** [comment]
Please look at the backend tests for this operation.  You will see from that an example of what's required.

**Comment by etienneleba** [comment]
Hi, Thx for your answer.

Could you be more accurate, plz. I look at : tests/backend/specs/api/sessionsAndGroups.js but there are just API route testing. I didn't see a test where a group is deleting when is having sessions. 

Maybe I was not clear in my post, but the internal error is in Etherpad, an api call shoudn't create an internal error, no ? 

Thx for your help :relaxed:

**Comment by webzwo0i** [comment]
@etienneleba 
Can you cherry-pick and test https://github.com/ether/etherpad-lite/pull/4231 please?

**Comment by webzwo0i** [comment]
If you want it would be really awesome if you could write tests for group deletion of a group that has 2 pads and 2 sessions

**Comment by etienneleba** [comment]
Hi @webzwo0i,

Thx for your help. I didn't cherry-pick but I removed the "s" in GroupManager.js like you did in your commit, and it's working great :smile: 

Do you know when it's gonna be released ? 

I can try but it has been a while I touched node js :sweat_smile:

**Comment by JohnMcLear** [comment]
Just waiting on test coverage now, I bumped @webzwo0i so prolly middle of this week as we have a few more things landing then we need @Gared to do a release :)

**Comment by JohnMcLear** [comment]
@webzwo0i did tests land for this?  I wanna get this closed off.

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/pull/4673 is PR for test coverage.  cc @webzwo0i

**Comment by JohnMcLear** [comment]
I'm closing this as tests were merged.
