### ISSUE TITLE
Copy/Paste within the pad loses bold formatting in Chrome

### ISSUE THREAD

**Issue by cwassert** [ether/etherpad-lite#4229]
Text with bold sections can be copied into the pad and out of the pad. But when I try to copy text from the pad into the same pad the bold formatting ist lost. Italic and underlined text is not affected. I cannot reproduce this bug in Firefox.

**To Reproduce**
Open a pad, type some text, make the text bold, select it and press CTRL-C then CTRL-V

**Desktop (please complete the following information):**
 - OS: GNU/Linux (X11) and Windows
 - Browser: Chrome
 - Version etherpad/etherpad:1.8.4 (docker), no-skin

**Comment by webzwo0i** [comment]
confirmed. bisect seems to indicate fb5a65c5fc42ded503491f07ec8bc33794216fe8 as the commit that introduced this behaviour. 
Can you test if this fixes the problem for you?
```
diff --git a/src/static/css/pad/normalize.css b/src/static/css/pad/normalize.css
index cd043933..202aa292 100644
--- a/src/static/css/pad/normalize.css
+++ b/src/static/css/pad/normalize.css
@@ -125,7 +125,6 @@ abbr[title] {
  * Address style set to `bolder` in Firefox 4+, Safari, and Chrome.
  */
 
-b,
 strong {
   font-weight: bold;
 }
```

**Comment by webzwo0i** [comment]
However, I don't understand what happens here :-)

**Comment by JohnMcLear** [comment]
I think it's contentcollector doing its job.  Prolly expects <b> elements not span styles.

**Comment by JohnMcLear** [comment]
Can't replicate in chromium or chrome on ubuntu on 1.8.6...  

Can this still be replicated @webzwo0i or @cwassert ??

**Comment by JohnMcLear** [comment]
If you can still replicate, I will re-open.

**Comment by JohnMcLear** [comment]
Wait I can replicate on video.etherpad.com but not on a local dev instance.  Both are running develop branch..  So wtf is going on ? :D  I assume plugins are causing issues here...

**Comment by webzwo0i** [comment]
weird. I can replicate in local environment with develop, also when I install the plugins that are installed on video.etherpad.com
(It works on video.etherpad.com for me, too)

**Comment by jinbullsushil** [comment]
Hi,
Is this issue fixed?
I am still facing the same problem. I have copied and paste the text and formatted(Bold) disappeared.
I have using https://video.etherpad.com/p/copypast for testing.
