### ISSUE TITLE
Cannot type quotation mark (") in tables with tables4 plugin

### ISSUE THREAD

**Issue by sodiumchl** [ether/etherpad-lite#4230]
**Describe the bug**
With the latest etherpad-lite and tables4 plugin, you cannot enter quotation marks ("). If you type ", the whole row disappears.

**Comment by sodiumchl** [comment]
Each table row has the following code:
{"payload":[["Cell1","Cell2 ","Cell3 ","Cell4 ","Cell5 "]],"tblId":"1","tblClass":"data-tables", "tblProperties":{"borderWidth":"1","cellAttrs":[],"width":"100","rowAttrs":{},"colAttrs":[],"authors":{}}}

Apparently, if you have Ce"ll1 in place of Cell1, the whole row is messed up because there is no escape for quotation mark.

**Comment by JohnMcLear** [comment]
File plugin bugs under specifc plugins please.  Thankd

**Comment by sodiumchl** [comment]
The "Issues" tab is unavailable for the tables4 plugin...
