### ISSUE TITLE
Error embedding pad in iframe chrome

### ISSUE THREAD

**Issue by vivekvt** [ether/etherpad-lite#4236]
I tried emebedding my etherpad into react web app using iframe.
It is working fine on **firefox** and **opera** but on **chrome** I am getting error.

Warning: it appears that your browser does not have cookies enabled. EtherPad uses cookies to keep track of unique users for the purpose of putting a quota on the number of active users.  Using EtherPad without  cookies may fill up your server's user quota faster than expected.

![Screenshot from 2020-08-30 18-33-25](https://user-images.githubusercontent.com/50275510/91661504-21528080-eafa-11ea-8b71-77243f359905.png)
![Screenshot from 2020-08-30 18-33-49](https://user-images.githubusercontent.com/50275510/91661506-23b4da80-eafa-11ea-961d-de43de617b33.png)

**Do I need to make any changes in settings.json ?**

I also tried embedding this pad from **video.etherpad.com** It works perfectly fine on all browsers I tried firefox, opera, chrome.
**[https://video.etherpad.com/p/XZEW-ZW_CwAyfNShcWcc](https://video.etherpad.com/p/XZEW-ZW_CwAyfNShcWcc)**
![Screenshot from 2020-08-30 20-01-52](https://user-images.githubusercontent.com/50275510/91661770-af7b3680-eafb-11ea-957e-e018deb5d6f3.png)

 - OS: Ubuntu 18.04.5 LTS
 - Browser Chrome
 - Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by JohnMcLear** [comment]
Update to latest develop branch
