### ISSUE TITLE
Feature Request/RFC: Shallow Copy Feature

### ISSUE THREAD

**Issue by joassouza** [ether/etherpad-lite#4242]
name: Feature request
about: Implement a way to copy a pad that is less resource demanding
title: 'Shallow Pad Copy'
labels: enhancement
assignees: me

* * *
**Is your feature request related to a problem? Please describe.**
We use the duplication of pads (copyPad API) a lot in our use case. We provide it as a way to the users to create versions of their pads. With that users can keep track of the different versions of the pad and the work of their team as well. It's really good because they use this feature in the same way as we use with code branches.
The main problem with it is because Etherpad does not provide a simple copy of pads. Every copy it's like a clone of the source pad. The whole content: revisions, chat, etc is copied. This by itself it brings some problems with pads with lots of revisions. It's not difficult to find pads with over 100.000 revisions in our instance. So, every copy it needs to loop over more than 100.000 revisions. This causes problems in our Etherpad instance because the Ueberdb has a problem to handle this amount of data, please check https://github.com/ether/ueberDB#dobulk-operations-on-set-out-of-memory . On the contrary what it's said in the documentation that is easily reproducible.

**Describe the solution you'd like**
The shallow copy would only copy the content of the pad and set the head revision to 0. It would be quite similar to what we have today but only the pad content, users who contributed to this pad would be copied. We could provide a flag to warn the plugins that the operation triggered is a shallow copy, so the plugins could act properly depending on the type of the copy. Something like:
hooks.callAll('padCopy', { 'originalPad': this, 'destinationID': destinationID, fullCopy: fullCopy });

**Describe alternatives you've considered**
I could implement that feature on a plugin, but I think other people could face a similar problem like us, so being in the Etherpad core would be easier to use and benefit the community more.
I've found a plugin that does something similar to that https://github.com/redhog/ep_copypad. I didn't try this plugin and two things concerns me:
This plugin does not have any test
The last update was 7 years ago

**Additional context** 
We had to upgrade the Etherpad machine we use on AWS to one that costs **10x** more to solve this temporally. That solution does not scale well.
Usually our pads have more than 100 pages (over 5000 lines).

**Plugin?**
As I mentioned before, implementing this feature on the core has some advantages.

**Where the Copy is made**
https://github.com/ether/etherpad-lite/blob/develop/src/node/db/Pad.js#L359

I must implement that shallow copy because it's the only problem we have now with Etherpad. Everything else works flawlessly. We use the version 1.7.5 in production and we have a work in progress to upgrade to version 1.8.4.
**I will gladly implement it if you guys agree with it.**

**Comment by JohnMcLear** [comment]
I'm +1 for a "copy a pad without full fidelity" existing but it should be clearly commented that it's not best practice and that historical reference points will be lost.  It's like taking a git repo, copy/pasting all the files and creating a new repo.

Shifting everything to rev:0 I "think" should be okay.  Any historical lookup IE timeslider will obv be nuked.

I think we need a clear name for this, it's almost like flattening a git repo or something and losing all history.  Perhaps ``copyWithoutHistory`` ?

Why is UeberDB struggling w/ 100k?  We have CI test coverage for 1M rows to ensure small instance coverage and it's working fine.  I'd like to fix the actual problem rather than skirting around it by doing a "copy without history" because ultimately if something is getting big, it's big, we should support it, because the next file / pad can also get big etc. etc.

Can you provide an issue on ueberdb with some test/example code maybe we can collabo to solve the problem upstream without having to expose a new API?  If we can't, exposing a new API is fine :)  https://github.com/ether/ueberDB/issues/new

**Comment by joassouza** [comment]
So, I think that problem is already known, or at least kinda. Reading the ueberDB part that mention the problem, it says:

> doBulk operations that chain IE a large number of .set without a pause to handle the channel clearance can cause a Javascript out of heap memory. It's very rare this happens and is usually due to a bug in software causing a **constant write to the database**.

If I understand correctly that operation of copy matches this bug case because it does not call a pause between a  large number of set operation, right?

Here's a screenshot what's shown on the logs after a duplication of a pad. Look that we have multiple call of GC on the same time! Idk if that's a problem per se
<img width="710" alt="Screen Shot 2020-09-04 at 14 04 07" src="https://user-images.githubusercontent.com/4945372/92270348-46f5d600-eebc-11ea-84cd-78615bcbdb91.png">

I'm gonna try to give you more detailed data about that problem.

> Why is UeberDB struggling w/ 100k? We have CI test coverage for 1M rows to ensure small instance coverage and it's working fine.

@JohnMcLear can you send me that CI test path? I'd like to simulate this scenario :)

**Comment by JohnMcLear** [comment]
Just fork https://github.com/ether/ueberDB and enable it on Travis.

https://github.com/ether/ueberDB/blob/master/.travis.yml

https://github.com/ether/ueberDB/blob/master/.travis.yml#L29 is where we dump in a script https://github.com/ether/ueberDB/blob/master/.travis.yml#L30 to generate data 

Tests can be run locally with ``npm test`` as per https://github.com/ether/ueberDB/blob/master/package.json#L57

Logic for actual tests is available here: https://github.com/ether/ueberDB/blob/master/test/test.js -- this might be where we make changes, specifically in https://github.com/ether/ueberDB/blob/master/test/test.js#L182 where it checks for speeds.

**Comment by joassouza** [comment]
@JohnMcLear, I've done more tests. It seems it does not have any problem with ueberDB at all. The main problem is with the operation of copy per se. Using a pad with 100.000 revisions, it's done at least 200.000 operations (100.000 get on the source pad and 100.000 set on the new pad). So, the CPU stays on 100% forever until the processing ends. The memory allocation increases as well, what's not strange anyway. 
That amount of operation just for one user scares me because this will only increase over time. 
So, answering your question... 
> Can you provide an issue on ueberdb with some test/example code maybe we can collabo to solve the problem upstream without having to expose a new API? 

As it's not an issue, we can do nothing to solve on the Ueberdb side.
I've already started to work on the `copyWithoutHistory` code on the Etherpad side. Hopefully, I’ll submit a PR soon
