### ISSUE TITLE
Regression caused by PR 4241

### ISSUE THREAD

**Issue by Hufschmidt** [ether/etherpad-lite#4262]
The pull-request https://github.com/ether/etherpad-lite/pull/4241 caused a regression for #4006!

## Error Message

Getting the following error when importing a pad via the ILIAS Etherpad-Lite [Plugin](https://github.com/jrocho/ILIAS-Etherpad-Lite-Plugin): 

```
Unable to import file into "p.[...]". Author "a.[...]" exists but he never contributed to this pad
```

Its the same error as described in #4006, where the AuthorId displayed in the warning does not match the AuthorId of the user trying to import the pad.

Doing `git revert 2bf076043f6c4d49fdc18f4e3163390aacb8d314` (https://github.com/ether/etherpad-lite/pull/4241) on the current development branch fixes the issue.

**Comment by JohnMcLear** [comment]
@rhansen
