### ISSUE TITLE
Etherpad 1.8.5, 1.8.6 not tagged on Dockerhub

### ISSUE THREAD

**Issue by jeanfabrice** [ether/etherpad-lite#4276]
latest tag seems to have been built a few hours ago, but tag for 1.8.5 is not present.

**Comment by 8sd** [comment]
There is no tag for 1.8.6 as well...

**Comment by Gared** [comment]
@8sd Sorry I don't know how to do that. @JohnMcLear Can you give me instructions? I will add this to our release procedure list

**Comment by jeanfabrice** [comment]
Something may be broken or not correctly setup on your [Dockerhub CI configuration](https://hub.docker.com/repository/docker/etherpad/etherpad/builds/edit)

**Comment by jeanfabrice** [comment]
ping @Gared @JohnMcLear

**Comment by JohnMcLear** [comment]
I don't do anything to do with docker, sorry!

**Comment by Gared** [comment]
@jeanfabrice I'm sorry, but we don't have access to this docker hub. I'm trying to find the owner

**Comment by JohnMcLear** [comment]
I sent you access @Gared

**Comment by Gared** [comment]
@JohnMcLear @jeanfabrice Fixed. Tags for 1.8.5 and 1.8.6 created and (hopefully) new tags will be added automatically
