### ISSUE TITLE
Uncaught TypeError: exports.plugins is undefined after upgrade 1.8.4 > 1.8.5

### ISSUE THREAD

**Issue by fabrice-noel** [ether/etherpad-lite#4284]
**Uncaught TypeError: exports.plugins is undefined**

I upgraded 1.8.4 > 1.8.5 but it didn't go well...

I first updated my OS (Ubuntu Srv 18.04)

Then I updated the Etherpad plugins :
adminpads2 v0.0.4 	
align v0.2.0 	
author_hover v0.2.1 	
delete_after_delay v0.0.21 	
embedded_hyperlinks2 v1.2.2 	
font_color v0.0.11 	
font_size v0.2.0 	
headings v0.1.6 	
pads_stats v0.0.9 	
spellcheck v0.0.7 	

Then I did:
```
git pull origin
bin/run.sh
```

The homepage is displayed but when you want to edit a PAD or create a new one, the interface doesn't load (Loading...) and you get the error (see subject and details at the end of this post)

I restarted the service >>> Always the same problem
I restarted the server >>> Always the same problem

I use Firefox 80.0 (64 bits)

**Did I forget to do something?**

-------------------------------------

Uncaught TypeError: exports.plugins is undefined
    aCallAll https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:41
    aCallAll https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:41
    getLineStyleFilter https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:10480
    getSpansForLine https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:1260
    insertDomLines https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:1749
    forEach https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:25
    insertDomLines https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:1723
    init https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:5337
    inCallStack https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:437
    init https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:5319
    i https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    fireWith https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    ready https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    F https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    promise https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    js https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    js https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    js https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    loadModule https://pad.nfcg.tv/p/test line 24 > injectedScript:451
    after https://pad.nfcg.tv/p/test line 24 > injectedScript:481
    _find https://pad.nfcg.tv/p/test line 24 > injectedScript:493
    _moduleAtPath https://pad.nfcg.tv/p/test line 24 > injectedScript:500
    moduleAtPathSync https://pad.nfcg.tv/p/test line 24 > injectedScript:536
    _designatedRequire https://pad.nfcg.tv/p/test line 24 > injectedScript:605
    designatedRequire https://pad.nfcg.tv/p/test line 24 > injectedScript:626
    requireRelative https://pad.nfcg.tv/p/test line 24 > injectedScript:632
    require https://pad.nfcg.tv/p/test line 24 > injectedScript:667
    js https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:14
    loadModule https://pad.nfcg.tv/p/test line 24 > injectedScript:451
    after https://pad.nfcg.tv/p/test line 24 > injectedScript:481
    _find https://pad.nfcg.tv/p/test line 24 > injectedScript:493
    _moduleAtPath https://pad.nfcg.tv/p/test line 24 > injectedScript:500
    moduleAtPathSync https://pad.nfcg.tv/p/test line 24 > injectedScript:536
    _designatedRequire https://pad.nfcg.tv/p/test line 24 > injectedScript:605
    designatedRequire https://pad.nfcg.tv/p/test line 24 > injectedScript:626
    requireRelative https://pad.nfcg.tv/p/test line 24 > injectedScript:632
    require https://pad.nfcg.tv/p/test line 24 > injectedScript:667
    js https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:35
    loadModule https://pad.nfcg.tv/p/test line 24 > injectedScript:451
    after https://pad.nfcg.tv/p/test line 24 > injectedScript:481
    fetchModuleSync https://pad.nfcg.tv/p/test line 24 > injectedScript:425
    _find https://pad.nfcg.tv/p/test line 24 > injectedScript:491
    _moduleAtPath https://pad.nfcg.tv/p/test line 24 > injectedScript:500
    moduleAtPathSync https://pad.nfcg.tv/p/test line 24 > injectedScript:536
    _designatedRequire https://pad.nfcg.tv/p/test line 24 > injectedScript:605
    designatedRequire https://pad.nfcg.tv/p/test line 24 > injectedScript:626
    requireRelative https://pad.nfcg.tv/p/test line 24 > injectedScript:632
    require https://pad.nfcg.tv/p/test line 24 > injectedScript:667
    <anonymous> https://pad.nfcg.tv/p/test line 24 > injectedScript:698
    onload https://pad.nfcg.tv/p/test line 3160 > injectedScript:24
    setTimeout handler*window.onload https://pad.nfcg.tv/p/test line 3160 > injectedScript:6
    EventHandlerNonNull* https://pad.nfcg.tv/p/test line 3160 > injectedScript:4
    init https://pad.nfcg.tv/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=6ce5545f:3160
    init https://pad.nfcg.tv/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=6ce5545f:3162
    init https://pad.nfcg.tv/javascripts/lib/ep_etherpad-lite/static/js/pad_utils.js?callback=require.define&v=6ce5545f:1435
    _afterHandshake https://pad.nfcg.tv/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=6ce5545f:527
    handshake https://pad.nfcg.tv/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=6ce5545f:291
    emit https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    onevent https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:8
    onpacket https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:8
    exports https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:8
    emit https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    ondecoded https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    exports https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:8
    emit https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    add https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    ondata https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    exports https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:8
    emit https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    onPacket https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    setTransport https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    emit https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    onPacket https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    n https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    decodePayload https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    onData https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    doPoll https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    emit https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    onData https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    onLoad https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
test line 24 > injectedScript line 237 > Function:41:425
    aCallAll https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:41
    aCallAll https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:41
    getLineStyleFilter https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:10480
    getSpansForLine https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:1260
    insertDomLines https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:1749
    forEach https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:25
    insertDomLines https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:1723
    init https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:5337
    inCallStack https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:437
    init https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:5319
    i https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    fireWith https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    ready https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    F https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    (Asynchrone : EventListener.handleEvent)
    promise https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    js https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    js https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    js https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:11
    loadModule https://pad.nfcg.tv/p/test line 24 > injectedScript:451
    after https://pad.nfcg.tv/p/test line 24 > injectedScript:481
    _find https://pad.nfcg.tv/p/test line 24 > injectedScript:493
    _moduleAtPath https://pad.nfcg.tv/p/test line 24 > injectedScript:500
    moduleAtPathSync https://pad.nfcg.tv/p/test line 24 > injectedScript:536
    _designatedRequire https://pad.nfcg.tv/p/test line 24 > injectedScript:605
    designatedRequire https://pad.nfcg.tv/p/test line 24 > injectedScript:626
    requireRelative https://pad.nfcg.tv/p/test line 24 > injectedScript:632
    require https://pad.nfcg.tv/p/test line 24 > injectedScript:667
    js https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:14
    loadModule https://pad.nfcg.tv/p/test line 24 > injectedScript:451
    after https://pad.nfcg.tv/p/test line 24 > injectedScript:481
    _find https://pad.nfcg.tv/p/test line 24 > injectedScript:493
    _moduleAtPath https://pad.nfcg.tv/p/test line 24 > injectedScript:500
    moduleAtPathSync https://pad.nfcg.tv/p/test line 24 > injectedScript:536
    _designatedRequire https://pad.nfcg.tv/p/test line 24 > injectedScript:605
    designatedRequire https://pad.nfcg.tv/p/test line 24 > injectedScript:626
    requireRelative https://pad.nfcg.tv/p/test line 24 > injectedScript:632
    require https://pad.nfcg.tv/p/test line 24 > injectedScript:667
    js https://pad.nfcg.tv/p/test line 24 > injectedScript line 237 > Function:35
    loadModule https://pad.nfcg.tv/p/test line 24 > injectedScript:451
    after https://pad.nfcg.tv/p/test line 24 > injectedScript:481
    fetchModuleSync https://pad.nfcg.tv/p/test line 24 > injectedScript:425
    _find https://pad.nfcg.tv/p/test line 24 > injectedScript:491
    _moduleAtPath https://pad.nfcg.tv/p/test line 24 > injectedScript:500
    moduleAtPathSync https://pad.nfcg.tv/p/test line 24 > injectedScript:536
    _designatedRequire https://pad.nfcg.tv/p/test line 24 > injectedScript:605
    designatedRequire https://pad.nfcg.tv/p/test line 24 > injectedScript:626
    requireRelative https://pad.nfcg.tv/p/test line 24 > injectedScript:632
    require https://pad.nfcg.tv/p/test line 24 > injectedScript:667
    <anonyme> https://pad.nfcg.tv/p/test line 24 > injectedScript:698
    onload https://pad.nfcg.tv/p/test line 3160 > injectedScript:24
    (Asynchrone : setTimeout handler)
    onload https://pad.nfcg.tv/p/test line 3160 > injectedScript:6
    (Asynchrone : EventHandlerNonNull)
    <anonyme> https://pad.nfcg.tv/p/test line 3160 > injectedScript:4
    init https://pad.nfcg.tv/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=6ce5545f:3160
    init https://pad.nfcg.tv/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=6ce5545f:3162
    init https://pad.nfcg.tv/javascripts/lib/ep_etherpad-lite/static/js/pad_utils.js?callback=require.define&v=6ce5545f:1435
    _afterHandshake https://pad.nfcg.tv/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=6ce5545f:527
    handshake https://pad.nfcg.tv/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=6ce5545f:291
    emit https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    onevent https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:8
    onpacket https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:8
    exports https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:8
    emit https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    ondecoded https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    exports https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:8
    emit https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    add https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    ondata https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    exports https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:8
    emit https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    onPacket https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    setTransport https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    emit https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    onPacket https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    n https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    decodePayload https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    onData https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    doPoll https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    emit https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:6
    onData https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7
    onLoad https://pad.nfcg.tv/socket.io/socket.io.js?v=6ce5545f:7

​

**Comment by JohnMcLear** [comment]
Remove all plugins and add one by one.  The issue template even has this in btw.

**Comment by fabrice-noel** [comment]
Hello John,

Thank you very much for this answer, I will follow your instructions but it will be for next Sunday, when I will do the next maintenance and I will keep you informed of the results. Have a good Sunday.

**Comment by webzwo0i** [comment]
Confirmed with maxAge=6*3600
This is probably like https://github.com/ether/etherpad-lite/issues/3955 
Files, that are dynamically required, don't have a version string.

@fabrice-noel In case you have a low/default value for maxAge in settings.json, when you wait for this amount of time, does it work? We don't have "versions" in our file names atm, but use a workaround, where a query string (with a random version that's regenerated on restart) is applied to resource requests.
However, not every file has this version string attached, so your browser will not re-request them.

Workaround: wait for maxAge settings and reload the pad or clear your browser cache

**Comment by fabrice-noel** [comment]
I will check this next Sunday because our maintenance window is now closed. Many thanks for your reply!

**Comment by fabrice-noel** [comment]
Dear all, I made the update this morning 1.8.4 > 1.8.6 and everything went well, I had no problem! Thanks for the work done!

**Comment by caugner** [comment]
> Remove all plugins and add one by one. The issue template even has this in btw.

@JohnMcLear I cannot seem to find the location you're referring to which would explain this. I tried updating from 1.8.4 to 1.8.6 (patch release?) and got this error (`Uncaught TypeError: exports.plugins is undefined`) when accessing a pad. Removing all three plugins (`adminpads`, `hash_auth`, `hide_referrer`) did not solve the issue, neither did adding them one by one again.

**Comment by webzwo0i** [comment]
Without a plugin installed, Is it possible for you to provide a HAR file (you can email it if you don't want to upload) or if not, can you open up the network tab of your browser, ensure that "disable cache" is not selected, load a pad, click XHR (and a second time for Javascript) and check if for every Javascript file there is a version string (`?v=some_randomness`) added to the resource name? I can reproduce this 

Probably ace2_inner.js and ace2_common.js will appear.

The workaround should be to reload everything once with ctrl+shift+r or by clicking "disable cache" in the network tab.

I'm reopening this, as doing the above steps probably make a bad experience and it would be great to ensure future versions have version strings attached for all requests

**Comment by webzwo0i** [comment]
Maybe before you do the above, can you check what your maxAge setting in settings.json was when using 1.8.4 and if that time has definitely elapsed?

**Comment by JohnMcLear** [comment]
Closing as stale.
