### ISSUE TITLE
iFrame Error

### ISSUE THREAD

**Issue by alperbayata** [ether/etherpad-lite#4293]
An error occurred
Please press and hold Ctrl and press F5 to reload this page
If the problem persists please send this error message to your webmaster:

ErrorId: jhbtJrpqhA7OeIfFOvsV
URL: https://canli.evdekiokulum.com/etherpad/p/alper?showControls=true&showChat=true&showLineNumbers=true&useMonospaceFont=false
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
Uncaught TypeError: Cannot read property 'setStateIdle' of null in https://canli.evdekiokulum.com/etherpad/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=6ac017cc at line 237

Use:Google Chrome

**Comment by JohnMcLear** [comment]
Try updating Etherpad (git pull) and clearing browser cache.  Etherpad is working fine btw, please do test before creating new issues, most of the issues you are making could be resolved by yourself if you spent a little time thinking about it.

**Comment by alperbayata** [comment]
Thank you
