### ISSUE TITLE
Add markup without selection

### ISSUE THREAD

**Issue by Porrumentzio** [ether/etherpad-lite#4308]
Currently on Etherpad-lite without using any plugin, the markup (**B**old, *I*talic...) can only be applied if a some character is selected. It can not be changed otherwise, for example:

Proposed type history:

> This is a `Ctrl+B` bold `Ctrl+B` text, this a `Ctrl+I` italic `Ctrl+I`.

This should print:

> This is a **bold** text, this a _italic_.

Nowadays this cannot been while typing, but only a selected text can be marked up.

**Comment by JohnMcLear** [comment]
This is by design.  I don't think applying formatting prior to typing provides a good ux.

**Comment by Porrumentzio** [comment]
This is the workflow of major text editors, both offices, text-editors... isn't?

**Comment by JohnMcLear** [comment]
Imho just because other projects do things one way doesn't mean we should.  Still, if you want this as a plugin or if someone wants to work on it then feel free!

Ps see sticky attributes plugin.  It might already do something similar but idk.

**Comment by Porrumentzio** [comment]
I have been thinking about this and I think that even keyboards, at one time mechanic, worked this way: there's a key that can change the _markup_ to make letters become uppercase, that's the Caps Lock key.

So a markup option can be changed while typing and not interpret it as editing. It's more fluid.

**Comment by JohnMcLear** [comment]
@Porrumentzio I already told you this already exists.

https://github.com/JohnMcLear/ep_sticky_attributes

If you want to further extend the sticky attributes plugin please open issues there :)
