### ISSUE TITLE
[Feature Request] Show cursor positions of the users

### ISSUE THREAD

**Issue by cdluminate** [ether/etherpad-lite#4319]
* * *

name: Feature request
about: editor, cursor position
title: Show cursor positions of the users
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**

When doing an online meeting, I hope the others can see where my cursor (editing cursor, not the mouse cursor) is pointing at.
So that I don't have to tell them, like, "please look at line 123".

A similar collaborative editing tool, named overleaf (https://www.overleaf.com/), is able to show that editing cursor.
**Describe the solution you'd like**

I'm not familiar with the technical stack used by etherpad, so I have no idea.

**Describe alternatives you've considered**

Overleaf, but it's too heavy for a lightning meeting.

**Plugin?**

I have no idea about it.

**Comment by joassouza** [comment]
There's a plug-in that does that 

http://redhog.org/ep_cursortrace
🙂

**Comment by cdluminate** [comment]
@joassouza Ah, thanks!
