### ISSUE TITLE
[QUESTION] How to install plugins in the docker version?

### ISSUE THREAD

**Issue by wsw70** [ether/etherpad-lite#4320]
I assume that https://hub.docker.com/r/etherpad/etherpad is the official docker container for Etherpad, sorry if this is not the case (I saw a copy paste of the README from this repo). Sorry if this is not the case.

If so - is there an instruction on **how to install plugins when running Etherpad in a container?** The problem is that the way it is suggested in the main documentation will probbaly not work as the container is volatile.

**Comment by jeanfabrice** [comment]
Sure.
You will have to build you own customized image using the upstream Dockerfile:
`docker build --build-arg ETHERPAD_PLUGINS="ep_codepad ep_author_neat"  https://github.com/ether/etherpad-lite`

See [documentation](https://github.com/ether/etherpad-lite/blob/develop/doc/docker.md#build-a-personalized-container)

**Comment by JohnMcLear** [comment]
@wsw70 it's good manners to close issues upon resolution.  Thanks for fix @jeanfabrice
