### ISSUE TITLE
Etherpad on mobile devices

### ISSUE THREAD

**Issue by tim-krieger** [ether/etherpad-lite#4321]
iPads (and other mobile devices with relatively large screens) do not use the mobile version of etherpad-lite. This results in broken icons in the toolbar. I think the [media queries](http://stephen.io/mediaqueries/#iPad) have to be adapted.

![Screenshot_20200919_125849](https://user-images.githubusercontent.com/64839715/93666222-ac30f600-fa7c-11ea-876a-432e6711d5e3.png)

**Comment by JohnMcLear** [comment]
@seballot is the CSS ninja who probably already knows the fix..

**Comment by seballot** [comment]
Ok fixed with #4322, @tim-krieger would be very good if you could have a careful testing on this feature. With colibris skin, without colibris skins, with different plugins, opening popups from the bottom toolbar, from the top toolbar etc...
I did test myself but I know I'm not very good at testing my own features, so could you spend some time on that? we don't want to introduce UI bug because of this change

Thanks !

**Comment by tim-krieger** [comment]
Thanks a lot @seballot. I've tested your changes with colibri skin. It looks good (iPad Safari & Android Chrome) and I didn't notice any bug. Tomorrow I will do further tests.

**Comment by tim-krieger** [comment]
I've tested your feature now with no-skin and it works (iPad Chrome & Safari). Also with no plugins. I noticed only a tiny visual glitch in to icons (star, collaboration), but I'm not sure this is related to your changes.

![48EA5357-247A-4E37-923D-1B97D3433078](https://user-images.githubusercontent.com/64839715/93711281-47919c00-fb4d-11ea-827f-230741653b58.png)

**Comment by tim-krieger** [comment]
One addition: With Android Chrome the bottom toolbar is above the keyboard in mobile view. With an iPad you can see the bottom toolbar (and the popups) only if you hide the keyboard.

**Comment by tim-krieger** [comment]
And a last addition: With another iPad (2018, 9.7") popups are displayed on the left side. I don't know if this is a intended behavior.

![89638741-F4F9-4A09-AA56-11073A495A7F](https://user-images.githubusercontent.com/64839715/93713744-3604c000-fb5e-11ea-8ba9-1c72fda6ddca.png)

**Comment by seballot** [comment]
Thanks for testing @tim-krieger ! I think we are fine, those small stuff does not seems bug to me. Okay to close the issue?

**Comment by tim-krieger** [comment]
Yes, of course, thanks a lot again!
