### ISSUE TITLE
Wrong condition on access check to group pad

### ISSUE THREAD

**Issue by ashitikov** [ether/etherpad-lite#4323]
https://github.com/ether/etherpad-lite/blob/12bd617f511de1da4f4511617ffed6e2804ac9d7/src/node/db/SessionManager.js#L75

The last condition is wrong: si.validUntil <= now, which means that only expired sessions will be matched. Instead we should match only si.validUntil > now sessions.

**Comment by JohnMcLear** [comment]
cc @rhansen

**Comment by rhansen** [comment]
Doh! Sorry about that. Fixed in PR #4324.
