### ISSUE TITLE
node-scrypt is deprecated, over a year old

### ISSUE THREAD

**Issue by robinpaulson** [ether/etherpad-lite#4327]
**Describe the bug**
according to https://github.com/barrysteyn/node-scrypt , node-scrypt is no longer maintained, but is still used in etherpad-lite

recommended replacement (by the maintainers):
https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback

**Comment by JohnMcLear** [comment]
Isn't this only used in hash auth plugin?

**Comment by robinpaulson** [comment]
> Isn't this only used in hash auth plugin?

ah, thanks! that's why, i understand the error now. closing

**Comment by JohnMcLear** [comment]
Please create issue on ep_hash_auth repository.  Thanks.
