### ISSUE TITLE
iframe error

### ISSUE THREAD

**Issue by tim-krieger** [ether/etherpad-lite#4332]
I noticed an iframe error with different pads from different server in different browsers (Firefox, Chromium). Cache is empty.

https://pad.colibris-outilslibres.org/

![pad1](https://user-images.githubusercontent.com/64839715/93851595-b63b3a80-fcb0-11ea-934b-3e1e986e435a.png)

https://pad.kits.blog

![pad2](https://user-images.githubusercontent.com/64839715/93851791-0fa36980-fcb1-11ea-97f6-d810bd091e8d.png)

The browser console shows me following 

`TypeError: Cannot read property 'setStateIdle' of null`

For pad.kits.blog nginx is properly configured:

  ```
proxy_pass http://localhost:9001;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP         $remote_addr;
  proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

```

And I haven't found any websocket error.

https://video.etherpad.com works ;-)

**Comment by rhansen** [comment]
Please provide:
  * Instructions on how to reproduce. I don't see any errors when I visit https://pad.colibris-outilslibres.org/ or https://pad.kits.blog.
  * The version of Etherpad (which Git commit).

**Comment by tim-krieger** [comment]
1. Open https://jsfiddle.net/westonruter/6mSuK/
2. Insert 

`<iframe name="embed_readwrite" src="https://pad.kits.blog/p/test?showControls=true&showChat=true&showLineNumbers=true&useMonospaceFont=false" width="100%" height="600" frameborder="0"></iframe>`

or

`<iframe name="embed_readwrite" src="https://pad.colibris-outilslibres.org/p/test?showControls=true&showChat=true&showLineNumbers=true&useMonospaceFont=false" width="100%" height="600" frameborder="0"></iframe>`

3. Click on »Run«

Result: You can see the errors I descriped above.

4. Try the following code:

`<iframe name="embed_readwrite" src="https://video.etherpad.com/p/test?showControls=true&showChat=true&showLineNumbers=true&useMonospaceFont=false" width="100%" height="600" frameborder="0"></iframe>`

Result: The pad opens fine in an iframe.

Version of pad.kits.blog: 1.8.6 12bd617f511de1da4f4511617ffed6e2804ac9d7

**Comment by JohnMcLear** [comment]
ep_helmet facilitates this maybe?

**Comment by tim-krieger** [comment]
I didn't enable ep_helmet before but I tried it yesterday without success.

**Comment by JohnMcLear** [comment]
It requires config.  Did you read the plugin docs?

**Comment by JohnMcLear** [comment]
Filed upstream as it's 99% an apache proxy issue not an Etherpad issue.

**Comment by tim-krieger** [comment]
Yes, of course, I've read the docs. It works but ep_helmet didn't solve the problem. 

I think this issue is related to a problematic cookie setting:

video.etherpad.com 

`Set-Cookie: express_sid=s%3AQmId8pn_7CAQRzx0rFNpHtucJ5V5jEBE.KKA%2BpIjLQri%2FD6aevZRB9ZrUkMQAiUqBWphSYgFBkBg; Path=/; HttpOnly; Secure; SameSite=Strict`

pad.kits.blog

`set-cookie: express_sid=s%3AR9MVUcfKIwxdCbkFYGbX1zB6x_JHeb4_.NaKctIa6RjK5ej4eYm7nuNCs8GUV0dbGZ3BZjeUoKTA; Path=/; HttpOnly; Secure; SameSite=Lax`

https://pad.colibris-outilslibres.org/

`Set-Cookie: express_sid=s%3A1CtPHmkjvAroI1NDtLAvOO38JcunGqKs.%2FLJj1S0NG8kVTU5Q62xsALQYWLnKsGWfEdRT5jXNJtE; Path=/; HTTPOnly; Secure; HttpOnly; Secure`

I think etherpad has to set SameSite=strict or SameSite=none automatically to prevent iframe-errors. But maybe I'm wrong.

**Comment by JohnMcLear** [comment]
can you test it without apache?  I want to ensure it's not an apache issue which I suspect.

**Comment by tim-krieger** [comment]
We've only nginx enabled.

**Comment by JohnMcLear** [comment]
-apache +nginx :)

**Comment by webzwo0i** [comment]
Confirmed. Bug introduced in d0a16d23cbcbf4b835467fbc6eff0be50948971d
@tim-krieger Can you downgrade pad.kits.blog to 4434e54368d8ba4be23d665caa09c216ea16d9ea and verify it works?

**Comment by JohnMcLear** [comment]
ugh good spot.  Perhaps we need test coverage for iframe usage... ;\  I am not sure how we'd achieve it but worth trying.  FWIW I thought the test runner already ran in an iframe but I guess it's not cross domain...

**Comment by tim-krieger** [comment]
> Can you downgrade pad.kits.blog to [4434e54](https://github.com/ether/etherpad-lite/commit/4434e54368d8ba4be23d665caa09c216ea16d9ea) and verify it works?

Thanks! This works fine.

**Comment by rhansen** [comment]
Do you have `settings.requireAuthentication` set to false? If so, would you try PR #4342 to see if it fixes the problem for you?

**Comment by tim-krieger** [comment]
An addition to the cookie issue I mentioned before: In Firefox the pad works but the debugger shows me an error. To fix this may prevent issues in the future.

![Screenshot_20200924_095840](https://user-images.githubusercontent.com/64839715/94117723-e1f32780-fe4c-11ea-9ee8-b7b153f65208.png)

**Comment by rhansen** [comment]
> In Firefox the pad works but the debugger shows me an error. To fix this may prevent issues in the future.

Unfortunately fixing those isn't trivial because the cookies would have to be replaced with something else. This is doable for `express_sid`, but not `token` or `prefs`. Fortunately, the `token` and `prefs` cookies aren't strictly necessary (they just provide a better user experience), and `express_sid` is no longer necessary (since PR #4342) as long as `settings.requireAuthentication` is false.

**Comment by tim-krieger** [comment]
Thank you @rhansen for explanation and for developing this great app!

**Comment by woeterman94** [comment]
Cookies should have the "secure" flag when using `samesite = none` in chrome.

Works
image
![image](https://user-images.githubusercontent.com/5755057/94924465-dbecee80-04bd-11eb-9b2b-f52a6d5e66c6.png)

Doesn't work
image
![image](https://user-images.githubusercontent.com/5755057/94924478-e14a3900-04bd-11eb-8c50-5afa1a4cd337.png)

**Comment by rhansen** [comment]
FYI: PR #4384 will allow pad admins to set `SameSite=None` for session cookies, which should make Etherpad usable in iframes even with `requireAuthentication = true` (assuming the user's browser does not block third-party cookies).

**Comment by woeterman94** [comment]
How can I pass the sessionID as a parameter to the iframe?

**Comment by rhansen** [comment]
> How can I pass the sessionID as a parameter to the iframe?

Currently not supported. Patches welcome!

(And I just realized that [my previous comment](https://github.com/ether/etherpad-lite/issues/4332#issuecomment-703200887) could be misunderstood so I edited it to clarify.)

**Comment by AjayShivanagol** [comment]
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/29257275/218147740-4e828336-b1e9-4b87-ba53-aa668a9ae5bd.png">


on safari getting same error...
