### ISSUE TITLE
Migrate JohnMcLear plugins to Ether/

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4337]
The top 10 plugins as per https://static.etherpad.org/ should hand ownership of those repos to the Etherpad Foundation and be part of ether/.

The plugins should pass all checks from checkPlugins (localizations, stale issues resolved, frontend and backend test coverage) and these plugins will all be checked when Etherpad (core) is commited to or has a new open PR (as per current existing CI).

The logic here is:
* That any changes that break plugins will be detected during install.
* That we can show best practice for plugins

We already did this transition with ep_comments_page and ep_hash_auth and it was relatively pain free.

Some work will be required
- [x] Confirm with plugin authors that they want to move the plugin to ether/
- [x] Move repos to ether/
- [x] Run all plugins through checkPlugins to identify the work required.
- [ ] Ensure all top plugins have i18n, test coverage and other best practices enabled.
- [x] Register plugins w/ Travis
- [ ] Add plugins to etherpad ``.travis`` file

**Comment by JohnMcLear** [comment]
Work required:

Checking the plugin: ep_author_follow
No repository in package.json

Checking the plugin: ep_author_hover
Test files not found, please create tests.  https://github.com/ether/etherpad-lite/wiki/Creating-a-plugin#writing-and-running-front-end-tests-for-your-plugin

Checking the plugin: ep_cursortrace
Translations not found, please create.  Translation files help with Etherpad accessibility.
Test files not found, please create tests.  https://github.com/ether/etherpad-lite/wiki/Creating-a-plugin#writing-and-running-front-end-tests-for-your-plugin

Checking the plugin: ep_hash_auth
Translations not found, please create.  Translation files help with Etherpad accessibility.

Checking the plugin: ep_hide_referrer
Translations not found, please create.  Translation files help with Etherpad accessibility.
Test files not found, please create tests.  https://github.com/ether/etherpad-lite/wiki/Creating-a-plugin#writing-and-running-front-end-tests-for-your-plugin

Checking the plugin: ep_markdown
Test files not found, please create tests.  https://github.com/ether/etherpad-lite/wiki/Creating-a-plugin#writing-and-running-front-end-tests-for-your-plugin

Checking the plugin: ep_mathjax
Translations not found, please create.  Translation files help with Etherpad accessibility.
Test files not found, please create tests.  https://github.com/ether/etherpad-lite/wiki/Creating-a-plugin#writing-and-running-front-end-tests-for-your-plugin

Checking the plugin: ep_subscript_and_superscript
Test files not found, please create tests.  https://github.com/ether/etherpad-lite/wiki/Creating-a-plugin#writing-and-running-front-end-tests-for-your-plugin

Checking the plugin: ep_table_of_contents
Test files not found, please create tests.  https://github.com/ether/etherpad-lite/wiki/Creating-a-plugin#writing-and-running-front-end-tests-for-your-plugin

Checking the plugin: ep_test_line_attrib
Translations not found, please create.  Translation files help with Etherpad accessibility.

**Comment by rhansen** [comment]
In addition to moving the Git projects to the `ether/` namespace, the Etherpad devs should be added to the plugin's npm collaborators.

I'd be happy to move the plugins I currently own over to `ether/`, just as long as I retain push access.

**Comment by Gared** [comment]
Maybe create a team on npm to manage those plugins?!

**Comment by JohnMcLear** [comment]
Team members: @rhansen @Gared @webzwo0i @translatewiki @orblivion 

Who else would like access?

**Comment by rhansen** [comment]
Does anyone here have access to https://www.npmjs.com/~etherpad or know who does?

**Comment by JohnMcLear** [comment]
Access sorted.  Most repos ported, nearly done..  Just ep_line_height and ep_comments_page to sort do testing.

**Comment by JohnMcLear** [comment]
All done btw w/ various updates since! 👍
