### ISSUE TITLE
More test setups for CI

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4341]
There are probably other issues that describe similar things, but this is not so much about concrete areas that need more tests but more about the environment in which etherpad can be deployed. Please add more ideas which environments we need to test. I don't say they should run on every commit, but it would be cool to have them at hand.

- todo: search Github issues for other "missing tests" (things like increase coverage put aside)
- test embedded pad (different port and different hostname - research if https://docs.travis-ci.com/user/hosts/ is enough or with a dummy page hosted on a domain under our control)
- SSL enabled (this should be possible with selenium capabilities, but might need update of webdriver-npm which is on my agenda, but not sure when I have time for this, because of more important current issues) - this is needed because it affects several http header and cookies
- Apache/nginx+etherpad (the vast majority of users don't directly serve from express and it affects things like trust proxy)
- subdirectory hosting (lots of dynamic requests and some routes make it necessary imo)

For a long time I thought different database configurations should be included, too, but now ueberDB has better coverage. We can stick to dirtydb until we find new regressions. However, it's imo not totally worthless to have it in the drawer.

**Comment by JohnMcLear** [comment]
It'd also be nice to be able to test against a known amount of hardware so we can get load test reference numbers to see if a change has a negative impact on the servers ability to handle messages.  I don't think Travis offers that specifically but I think you can target cpus?  If not, ``cpulimit`` ?

**Comment by webzwo0i** [comment]
I'm afraid only different architectures and maybe no. of vCPU can be choosen. In virtualization environments this won't help much, because other jobs on the same hardware have an effect. But it's probably fun to try to get some insights there:
- run the same test multiple times and choose the fastest pass
- repeat the same test with pauses in the hope we get a time slot with less impact from other jobs on the same hardware
- take a baseline commit (fastest pass or with expected +/- deviation) that is run before we execute our desired commit. Suppose we run our test very often, discarding 20% outliers and get 30 seconds on average. When a new commit comes in, we start our job, run the baseline commit, which is 25 seconds this time, so we know we need to divide our value by 1.2 to get an adequate result.

Problem is to find a good balance: fast tests can be repeated very often, which makes the average values better, but they depend more on different effects from other jobs on the same hardware.

However, I find performance metrics very important. I'm also thinking of:
- time until DOMContentLoaded/time until pad is usable
- reponsiveness test, lots of lines, list operations, number of requests, different rendering tasks
- easysync (it hasn't changed much in the past, thus not so important)

Maybe not testing those on every commit, but at least before release or as cronjob

**Comment by JohnMcLear** [comment]
Sounds good to me, I do think having these metrics is valuable but it might be a V2 thing as 1.9 prolly wont include the port to a modern webdriver.

**Comment by webzwo0i** [comment]
Just adding another special one - test the update path (will probably only catch caching problems):
- install an old or the current version, e.g. 1.8.4, 1.8.5, 1.8.6 etc
- open up browser (iirc caching is enabled by default, maybe ensure that's the case) and go to a pad, also go to timeslider
- update to the next release
- run the frontend tests (maybe only reloading pad/timeslider is enough)

.travis.yml could be configured to run this only when pushing to a release-branch
