### ISSUE TITLE
Discard wd in favour of webdriver.io or similar

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4344]
I probably did not open a ticket for this, yet. We use https://github.com/admc/wd that only supports old Selenium (legacy version 2).

This has impact on our Saucelabs tests, among others:
- we cannot get console output
- we cannot get performance metrics

It must be guaranteed that we can still launch the frontend tests in a local browser after migration.

**Comment by JohnMcLear** [comment]
+1 yes please! :+1:

**Comment by webzwo0i** [comment]
I had some luck today with https://www.npmjs.com/package/selenium-webdriver 
so it will definitely happen in the near future... :-)

I am not sure if this will help with test stability, but at least we'll know, that it's not related to selenium 2 and we'll have console.log
