### ISSUE TITLE
Permission denied when accessing pad with ID containing umlauts

### ISSUE THREAD

**Issue by ldruschk** [ether/etherpad-lite#4345]
**Describe the bug**
Accessing a pad containing umlauts (and potentially other special characters requiring URL encoding) always leads to "You do not have permission to access this pad".

**To Reproduce**
1. Enable Authentication (we are using a OAuth2 plugin, but I don't think that matters)
2. Access a pad containing an umlaut, e.g. /p/ü-test
3. See "You do not have permission to access this pad"

**Expected behavior**
The pad should be accessible (just like any other pad not containing umlauts)

**Screenshots**
![Screenshot from 2020-09-24 09-27-09](https://user-images.githubusercontent.com/14059613/94114228-57a8c480-fe48-11ea-905a-8a65a3eadfa4.png)

```
pad       | [2020-09-24 07:18:57.505] [DEBUG] SessionStore - GET censored
pad       | [2020-09-24 07:18:57.505] [DEBUG] ueberDB - GET    - sessionstorage:censored - {"cookie":{"path":"/","_expires":null,"originalMaxAge":null,"httpOnly":true,"sameSite":"Lax","secure":true},"afterAuthUrl":"/p/%C3%BC-test","passport":{"user":{"id":1,"uid":"lui","token":{"type":"bearer","accessToken":"censored","refreshToken":"censored"}}},"user":{"username":"lui","padAuthorizations":{"%C3%BC-test":"create"}}} - from cache
pad       | [2020-09-24 07:18:57.678] [DEBUG] auth - access denied: unauthorized
pad       | [2020-09-24 07:18:57.678] [WARN] message - Authentication try failed:{"component":"pad","type":"CLIENT_READY","padId":"ü-test","sessionID":null,"password":null,"token":"censored","protocolVersion":2}
```

**Desktop (please complete the following information):**
- across multiple Browsers (tested with Firefox and Chromium)

**Additional context**
Judging by the logs it appears that padAuthorizations are stored URL-encoded (`%C3%BC-test`) but when checking authorizations a non-url-encoded string is used (`ü-test`), but I did not verify this theory yet.

**Comment by ldruschk** [comment]
As an additional note, this issue only started appearing recently (the same pads worked earlier), so it is most likely related to this commit: https://github.com/ether/etherpad-lite/commit/b80a37173efe592c07c89e2e16a7fe6602441ed5#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by webzwo0i** [comment]
Can you change line 42 from `const` to `let` and insert `padID = decodeURIComponent(padID)` after `if (padID == null) return next();` and see if this solves your problem?

**Comment by ldruschk** [comment]
Thanks for the quick response. Yes, this does indeed fix the issue.

**Comment by webzwo0i** [comment]
You did all the debug work yourself :-)

@rhansen
You think this is correct or do we need to encodeURIComponent in src/node/db/SecurityManager#checkAccess ?

**Comment by JohnMcLear** [comment]
Also please include a test.  I have a fuzz test for pad content not pad IDs.
