### ISSUE TITLE
Download document as a PDF?

### ISSUE THREAD

**Issue by chetanmadaan** [ether/etherpad-lite#4350]
* * *
name: Feature request
about: Ability to download the document as PDF.
labels: enhancement
assignees: 
* * *

**Comment by rhansen** [comment]
Etherpad already supports PDF export. To enable, you must set either `soffice` or `abiword` in `settings.json`.

![Screenshot_20200925_205833](https://user-images.githubusercontent.com/1612291/94326550-99358e80-ff72-11ea-8825-560638493007.png)

**Comment by chetanmadaan** [comment]
My apologies!
