### ISSUE TITLE
First time setup questions!

### ISSUE THREAD

**Issue by chetanmadaan** [ether/etherpad-lite#4375]
Hello Gentlemen (& Ladies),

Now that I have the instance running, I have some lame a** questions that I wanted to ask.

1. How do I actually set the session. All this time I have been doing it via console and etherpad would run on a subdomain compared to the primary domain from where the user's will be coming here.
Can it be done via URL or something i.e. http://127.0.0.1:9001/p/g.oNlM73EFpQCYuoIB$Pad7?setsessionid=xxx
2. Do I have to run it on port 9001 or can I run it on standard Apache 80/443? I know there is a setting in settings.json about this but wanted to be sure. Perhaps this is more of a general nodejs question.

You don't have to answer the above questions and I can totally create a new topic for the same

**Comment by chetanmadaan** [comment]
3. How do I configure the domain name on this since this is no longer Apache and we don't have virtual hosts.

**Comment by chetanmadaan** [comment]
#3.
https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#http-proxy

Tried setting up the basic https proxy (didn't work, nothing  would show up on domain name).
Setup Apache with SSL and I have 502 Proxy error.

Will try this again in a few hours with more energy.

**Comment by rhansen** [comment]
1. Your frontend server returns it to the user in a `sessionID` cookie.
2. `settings.json` has [`port`](https://github.com/ether/etherpad-lite/blob/554eef77708fcc5b597d5864395bd4ba61dfde5e/settings.json.template#L129) and [`ssl`](https://github.com/ether/etherpad-lite/blob/554eef77708fcc5b597d5864395bd4ba61dfde5e/settings.json.template#L147-L151) options, but I recommend using a reverse proxy.
3. Not applicable. If you use a reverse proxy (nginx is a popular choice) you can set up a vhost in that.

**Comment by chetanmadaan** [comment]
@rhansen 
1. Frontend server might not be able to do this, since the frontend server is running on domain.com and etherpad is running on domain2.com

Please keep this open as I am working on 2/3 and will post back a fix which may/may not be helpful with others.

**Comment by rhansen** [comment]
>  1. Frontend server might not be able to do this, since the frontend server is running on domain.com and etherpad is running on domain2.com

That's currently not supported (patches welcome). To work around it you can have your frontend server also act as a reverse proxy to Etherpad.

**Comment by chetanmadaan** [comment]
Got it. that's more complicated stuff then.

If we get something like ?setsessionID or so. That should be perfect. Let me see if I can do some digging around and find a patch. I am pretty sure I won't though.
