### ISSUE TITLE
ssl connection is required. please specify ssl options and retry

### ISSUE THREAD

**Issue by woeterman94** [ether/etherpad-lite#4377]
How can I specify that SSL is required to connect with my postgres database? 

I tried adding   **"sslmode": "require"** but that does not seem to work.

```
  "dbSettings": {
    "host": "${DB_HOST}",
    "port": "${DB_PORT}",
    "database": "${DB_NAME}",
    "user": "${DB_USER}",
    "password": "${DB_PASS}",
    "charset": "${DB_CHARSET}",
    "sslmode": "require",
    "filename": "${DB_FILENAME:var/dirty.db}"
  },
```

**Comment by ukcb** [comment]
Activate ssl-mode in postgres?

> $ grep ssl /etc/postgresql/11/main/postgresql.conf
> ssl = true                              # (change requires restart)
> #ssl_ciphers = 'HIGH:MEDIUM:+3DES:!aNULL' # allowed SSL ciphers
> #ssl_prefer_server_ciphers = on         # (change requires restart)
> #ssl_ecdh_curve = 'prime256v1'          # (change requires restart)
> ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'          # (change requires restart)
> ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'         # (change requires restart)
> #ssl_ca_file = ''                       # (change requires restart)
> #ssl_crl_file = ''                      # (change requires restart)

**Comment by woeterman94** [comment]
Other way around. My postgres DB (in azure) demands ssl connections. I'm unable to connect using ssl because there is no "sslmode require" option anywhere.

**Comment by JohnMcLear** [comment]
See ueberdb.  You can use any normal setting for postgres module afaik.

**Comment by JohnMcLear** [comment]
Closing as inactive.  Assuming op got it sorted.
