### ISSUE TITLE
API: listAll... failed

### ISSUE THREAD

**Issue by Joggel72** [ether/etherpad-lite#4378]
**Describe the bug**
I've tried to use the listAll... methods.
Bull methods received the following response:
_{"code":2,"message":"createHTTPError.notFound is not a constructor","data":null}_

There is no entry in the log for these requests.
Other requests are working.

**To Reproduce**
Using curl:
_curl "http://localhost:9001/api/1/listAllGroups?apikey=477d..." _

**Expected behavior**
code: 0 and list of elements

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10, Debian
- Version 1.8.4 (6a0f73d)
 - API-Version 1.2.14

**Comment by JohnMcLear** [comment]
Does it work on develop?

**Comment by Joggel72** [comment]
In the log I can see this:
 Etherpad is running in Development mode.

**Comment by JohnMcLear** [comment]
Please try develop branch

**Comment by Joggel72** [comment]
I've tried to use it, but start failed.

I've get the zip from https://github.com/ether/etherpad-lite/archive/develop.zip unzipped the actuell version in a new directory. Then called in directory src 
_npm install_
called _start.bat_
and got
C:\tmpWork\etherpad-lite-develop>node node_modules\ep_etherpad-lite\node\server.js
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\tmpWork\etherpad-lite-develop\node_modules\ep_etherpad-lite\node\server.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

Where are the configuration files for this version?

**Comment by webzwo0i** [comment]
bin/installOnWindows.bat before start.bat

**Comment by YSelfTool** [comment]
@Joggel72 listAllGroups is not available in API version 1. You need to pass version >= 1.1, just pass 1.2.14 (the current one):
`curl …/api/1.2.14/listAllGroups?…`, then it will work.
@JohnMcLear Something is wrong with the import of http-errors, leading to this "notFound is not a constructor" error when calling "new createHTTPError.notFound".

**Comment by rhansen** [comment]
The error handling code in [`openapi.js`](https://github.com/ether/etherpad-lite/blob/891d2600fa4659d6183bb3ac524b88e504835ff3/src/node/hooks/express/openapi.js) (specifically [here](https://github.com/ether/etherpad-lite/blob/891d2600fa4659d6183bb3ac524b88e504835ff3/src/node/hooks/express/openapi.js#L586-L591) and [here](https://github.com/ether/etherpad-lite/blob/891d2600fa4659d6183bb3ac524b88e504835ff3/src/node/hooks/express/openapi.js#L615-L628)) looks all wrong to me, but maybe I'm missing something. @anttiviljami: Any ideas?

**Comment by JohnMcLear** [comment]
bump @anttiviljami

**Comment by JohnMcLear** [comment]
Bumped @anttiviljami via email

**Comment by anttiviljami** [comment]
The error handling itself looks file, but it indeed does look like the [constructor names](https://www.npmjs.com/package/http-errors#list-of-all-constructors) on lines [587](https://github.com/ether/etherpad-lite/blob/891d2600fa4659d6183bb3ac524b88e504835ff3/src/node/hooks/express/openapi.js#L587) and [590](https://github.com/ether/etherpad-lite/blob/891d2600fa4659d6183bb3ac524b88e504835ff3/src/node/hooks/express/openapi.js#L590) are wrong.  

I've gone ahead and opened a [PR](https://github.com/ether/etherpad-lite/pull/4437) #4437 to fix the generation of http-errors and moved to using the new [`isHttpError`](https://www.npmjs.com/package/http-errors#createerrorishttperrorval) utility provided by the `http-errors` package.

I do stress however that this will _not_ fix the underlying 404 error that's being generated here.

**Comment by anttiviljami** [comment]
> @Joggel72 listAllGroups is not available in API version 1. You need to pass version >= 1.1, just pass 1.2.14 (the current one):
curl …/api/1.2.14/listAllGroups?…, then it will work.

I can confirm that this solution works. On a fresh install:

```
$ curl -i "http://localhost:9001/api/1.2.15/listAllGroups?apikey=XXXX"
HTTP/1.1 200 OK
X-Powered-By: Express
X-UA-Compatible: IE=Edge,chrome=1
Referrer-Policy: same-origin
Content-Type: application/json; charset=utf-8
Content-Length: 48
ETag: W/"30-IZDLiyB3tfjqz1eiHK3/CWE2fj0"
Set-Cookie: express_sid=s%3AqCnXPTq0q78fML_wIqbDNuBqadsOGHlP.OxBMoLVCFNipnF6c3vat%2F2%2B%2F%2FkOrV%2FRourAf1uMq5%2BU; Path=/; HttpOnly; SameSite=Lax
Date: Sun, 25 Oct 2020 10:48:54 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"code":0,"message":"ok","data":{"groupIDs":[]}}
```

**Comment by anttiviljami** [comment]
@Joggel72 the full URL endpoints for the listAll* methods are also correctly listed in the `/api/openapi.json` spec.

This means you can easily use any openapi client to call any endpoint. Command line example:

```bash
npx openapicmd call http://localhost:9001/api/openapi.json # latest api version
npx openapicmd call http://localhost:9001/api/<version>/openapi.json # specific api version
```

Alternatively, open Swagger UI in your browser to browse the API docs and try different endpoints. @JohnMcLear maybe a good idea to spin up a Swagger UI endpoint by default in etherpad? 

```bash
npx openapicmd swagger-ui http://localhost:9001/api/openapi.json
```

**Comment by JohnMcLear** [comment]
I'd certainly welcome that as a pull request if possible please.  I assume it's a case of creating a new express route and putting in your package logic?

**Comment by anttiviljami** [comment]
Sure! I'll see what I can do.

>  I assume it's a case of creating a new express route and putting in your package logic?

Exactly. Swagger UI is just a static HTML page, also available as an [npm package](https://www.npmjs.com/package/swagger-ui).

**Comment by Joggel72** [comment]
@YSelfTool 
Thank you for detecting the wrong api version I've used!!

> @Joggel72 listAllGroups is not available in API version 1. You need to pass version >= 1.1, just pass 1.2.14 (the current one):
> `curl …/api/1.2.14/listAllGroups?…`, then it will work.
