### ISSUE TITLE
[QUESTION] How to export/import pdf file in etherpad through its API?

### ISSUE THREAD

**Issue by faizan-glowlogix** [ether/etherpad-lite#4379]
I'm trying to use etherpad-lite with one of my php laravel based application. In our application user will upload the document on system and our system needs to display that document in a window for editing.

Until now, I've been able to create pad and padGroups in my laravel app through API for dummy text.

I've also installed LibreOffice and required plugin in my server. Import/Export functionality is working on etherpad but I want to get this functionality from my app's backend code but there is no method/detail in etherpad's API docs about import/export.

Please guide if what I'm asking makes sense? If yes, I'd be pleased if I get some help or useful link? I've search it but all could find is step to install abiword/libreoffice.

**Comment by webzwo0i** [comment]
afaik there is no API endpoint for import/export and you need to convert the file in your backend, but there are API endpoints for getHTML/setHTML

**Comment by n-goncalves** [comment]
I was having a similar problem a few days ago. 

From what I saw there's nothing in the HTTP API allowing to set the content of a pad using something else than text or HTML. And no way to hook to the HTTP API in order to extend it (Please correct me if I'm wrong).

What I ended up doing is creating a plugin which adds the ability to import export.
It's basically a mix of [APIHandler.js](https://github.com/ether/etherpad-lite/blob/develop/src/node/handler/APIHandler.js) in order to use the same apikey handling and  [importexport.js](https://github.com/ether/etherpad-lite/blob/develop/src/node/hooks/express/importexport.js) for the actual import and export APIs.

**Comment by faizan-glowlogix** [comment]
@n-goncalves  Can you please share your code?

**Comment by rhansen** [comment]
Does `GET` of `/p/${pad}/export/pdf` and `POST` to `/p/${pad}/import` not work for your use case? You will have to create a session first and pass the session ID via the `sessionID` cookie.

**Comment by n-goncalves** [comment]
You could do that for exporting, but you need to be an author to import from what I understood.

@faizan-glowlogix Here's my plugin https://gist.github.com/n-goncalves/84683a3f7806cb05a3fc8d0384e3146a 

It adds news endpoint at `/importExport/${pad}/export/${type}` and `/importExport/${pad}/import` to which you can pass the apikey as you would normally.

**Comment by JohnMcLear** [comment]
> that



> You could do that for exporting, but you need to be an author to import from what I understood.

This is a setting that can be enabled/disabled.  The example curl for importing is available in the backend tests folder.

**Comment by rhansen** [comment]
> You could do that for exporting, but you need to be an author to import from what I understood.

PR #4381 will remove the need to create and edit a pad before import. You will still need to authenticate as a user or create a session unless the `requireAuthentication` and `requireSession` settings are both false.

**Comment by faizan-glowlogix** [comment]
Uncaught TypeError: Cannot read property 'setStateIdle' of null -- { errorId: 'CIHQm6npexmwmnCUKfw5',
  msg:
   'Uncaught TypeError: Cannot read property \'setStateIdle\' of null',
  url: 'http://127.0.0.1:9001/p/Test',
  linenumber: 227,
  userAgent:

Anyone know about this? @rhansen  @n-goncalves

**Comment by rhansen** [comment]
> 'Uncaught TypeError: Cannot read property 'setStateIdle' of null',
> Anyone know about this?

Not me. Where are you seeing this? Is this related to import/export of PDFs? Steps to reproduce?

**Comment by JoseLopezSolis** [comment]
> You could do that for exporting, but you need to be an author to import from what I understood.
> 
> @faizan-glowlogix Here's my plugin https://gist.github.com/n-goncalves/84683a3f7806cb05a3fc8d0384e3146a
>
> It adds news endpoint at `/importExport/${pad}/export/${type}` and `/importExport/${pad}/import` to which you can pass the apikey as you would normally.

Hi,

Thank you for the code. I was wondering about the version of the API your code uses. For instance, in the Etherpad documentation, each endpoint specifies an API version, such as:

`http://pad.domain/api/1/setText?apikey=secret&padID=padname`

Here, 'api/1' indicates the API version. Does your code work with version 1 of the API, or have you added a versioning mechanism for this API?

Thanks for your reply.

**Comment by faizan-glowlogix** [comment]
@JoseLopezSolis I don't remember now. what I did at that time.

**Comment by n-goncalves** [comment]
This is completely separate from Etherpad's own HTTP API, as far as I'm aware you can't extend it. So to access the endpoint if my plugin using your example domain, you'd do `http://pad.domain/importExport/${pad}/export/${type}` .

And no I haven't written any versioning mechanism for this, we ended up scrapping that code later.
