### ISSUE TITLE
Revisit allowAnyoneToImport

### ISSUE THREAD

**Issue by rhansen** [ether/etherpad-lite#4381]
PR #3833 added a requirement to edit a pad before import, unless `settings.allowAnyoneToImport` is true (see issue #3964 and PR #3965). I don't know all of the background that went into adding that requirement, but with recent authentication and authorization changes (see issue #4325) it might now be safe to rely solely on [`securityManager.checkAccess`](https://github.com/ether/etherpad-lite/blob/ceb09ce99ad080ae804d322804b22e3e8f0be005/src/node/db/SecurityManager.js#L54) and [`webaccess.userCanModify`](https://github.com/ether/etherpad-lite/blob/ceb09ce99ad080ae804d322804b22e3e8f0be005/src/node/hooks/express/webaccess.js#L38-L47) to check if a user is allowed to import. Removing the need to edit a pad before import will simplify certain use cases such as programmatic imports (see issue #4379).

**Comment by JohnMcLear** [comment]
That's a very good point.  However having "tools" that can import without creating sessions is also useful.  That said, shifting for clients to use ``userCanModify`` etc. is a great idea.

So to summarize.  Keep ``allowAnyoneToImport`` logic but shift clients to use ``userCanModify`` to enable/disable import.  @rhansen does that make sense?  Fancy taking a stab at it?

**Comment by rhansen** [comment]
Currently, the `'/p/:pad/import'` handler calls `securityManager.checkAccess` before checking `settings.allowAnyoneToImport`. Thus, tools must authenticate as a user (assuming authn is required) or create a session before importing even if `settings.allowAnyoneToImport` is true. Tools won't be affected if we completely remove `allowAnyoneToImport`.

To make it possible for tools to import and export without authenticating (or creating a session), I think we should add a new API endpoint.

I will work on removing the `allowAnyoneToImport` logic.
