### ISSUE TITLE
Importing Document cleares all revision history

### ISSUE THREAD

**Issue by chetanmadaan** [ether/etherpad-lite#4382]
**Describe the bug**
Uploading a document (in this case I used a .doc) replaces the pad ( _which is expected behavior_), but also the revision's prior to file upload are then no longer visible.

**To Reproduce**
1. Create a new type.
2. Type in some content.
3. Download a copy as word doc ( _you must have soffice or abiword installed and setup in order to do this_)
![image](https://user-images.githubusercontent.com/3968575/94854888-9ff15500-03fb-11eb-9c86-31f6e359d8af.png)

4. Modify word doc locally.
5. Upload back the word doc.
6. Your revisions prior to upload are no longer visible.

**Expected behavior**
Upload should just be considered a revision rather than a complete reset.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows.
 - Browser Chrome

**Additional context**
I am using the develop branch latest build.

**Comment by JohnMcLear** [comment]
- I created a pad
- wrote 1,2,3
- imported a new doc
- visited timeslider
- I see 1,2,3 then the 4th revision is the new doc..

Are you sure about this?

**Comment by chetanmadaan** [comment]
> * I created a pad
> * wrote 1,2,3
> * imported a new doc
> * visited timeslider
> * I see 1,2,3 then the 4th revision is the new doc..
> 
> Are you sure about this?

I'll test again. May be it's just me.
