### ISSUE TITLE
Uncaught Error: The module at "js-cookie/src/js.cookie" does not exist.

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4387]
```Uncaught Error: The module at "js-cookie/src/js.cookie" does not exist.```

When visiting the timeslider of a pad with contents in.

Branch: Develop

**Comment by rhansen** [comment]
This is related to PR #4384.

I am unable to reproduce. The `js-cookie` package was added to `src/package.json`—did you remember to re-run `./bin/installDeps.sh`?

**Comment by JohnMcLear** [comment]
Oh I'm so used to using fastRun.sh lately I totally forgot..   This makes total sense :)  Ignore, I'm a noob.
