### ISSUE TITLE
Export of HTML in attributes within a line (not line attributes) are broken

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4394]
STR:

1. checkout develop etherpad
1. install ep_font_size / ep_font_color (``npm install ep_font_size``)
1. ``bin/run``
1. put line attributed content in pad
1. export html

No additional HTML is included to represent the attributes.

d1330a1e1c0fc536244c77605f0612cf4412e9fe is the first bad commit
commit d1330a1e1c0fc536244c77605f0612cf4412e9fe
Author: John McLear <john@mclear.co.uk>
Date:   Fri Jul 17 10:08:40 2020 +0100

    Bugfix: Async bump part 2
    
    Sorry, not sure what happened but having kids jump all over the keyboard while I do this probably didn't help... :|

 src/package.json                |  2 +-
 src/static/js/pluginfw/hooks.js | 24 +++++++++++++-----------
 2 files changed, 14 insertions(+), 12 deletions(-)

Requested help from @rhansen to fix the async/await bug present at https://github.com/ether/etherpad-lite/commit/d1330a1e1c0fc536244c77605f0612cf4412e9fe#diff-e4533b536e57db4e3299a5214e5c2e24R80

**Comment by rhansen** [comment]
There is a bug in d1330a1e1c0fc536244c77605f0612cf4412e9fe (`Array.prototype.forEach` returns `undefined`, not a Promise), but that's a red herring. `aCallAll` has been fixed since then, so I'd try your tests again at 0835bfeabb4babd8ee55111e82462b9d8fd3dd57 (the commit that fixed `aCallAll`).
