### ISSUE TITLE
Pad name length is limited to 50 chars ... that’s DEFINITELY not enough.

### ISSUE THREAD

**Issue by fooness** [ether/etherpad-lite#4396]
**Describe the bug**
> Such a padname is forbidden

Works: https://scalar.vector.im/etherpad/p/01234567890123456789012345678901234567890123456789

Doesn’t: https://scalar.vector.im/etherpad/p/012345678901234567890123456789012345678901234567890

In contrary to comments in https://github.com/ether/etherpad-lite/issues/1116, this bug is pretty much real and happens quite often when using Etherpad integration widgets in Matrix / Element https://element.io/ …

We’d be very happy if this issue could be resolved. Thank you very much!

**Comment by JohnMcLear** [comment]
@fooness - Matrix/Element are making padIds with values longer than 50 characters despite it being documented that we have that limit?

How is this an Etherpad issue?  We have this limitation in for a reason as per #1116 

Why can't the third party software just use a shorter padId or so?  Is a uniqueness of 8.8817842e+84 not good enough?

**Comment by JohnMcLear** [comment]
I'm closing this due to lack of feedback, this is not a bug in Etherpad but a bug with some random third party tool we have a very clear policy on saas / hosting third party software issues and our policy is that we don't allow them to distract us from core dev.
