### ISSUE TITLE
cmd-delete should delete entire line, not single word (Mac OS X)

### ISSUE THREAD

**Issue by rmondello** [ether/etherpad-lite#440]
In a standard textarea on Mac OS X, cmd-delete removes all of the text from the insertion point back until the beginning of the line the insertion point is on. In etherpad-lite, a single word is deleted, which is what option-delete does.

In order to match the expected behavior of textareas on Mac OS X, this should be changed.

**Comment by JohnMcLear** [comment]
Mac people are such heavy contributors, I just can't handle the number of pull requests landing to solve this issue despite it only being a one liner...  *grins.

**Comment by muxator** [comment]
@Tristramg, given your recent story with Etherpad, do you happen to have a Mac and want to work on this macOS ergonomy fix?

Otherwise I'll close for inactivity.

**Comment by JohnMcLear** [comment]
I think we can close it :)
