### ISSUE TITLE
Error "Context is undefined" with v 1.8.6

### ISSUE THREAD

**Issue by fabrice-noel** [ether/etherpad-lite#4403]
**Description of the bug**
The message below appears after several seconds of use of the PAD, I press Ctrl+F5 but the message comes back a few seconds later... This problem appeared after the migration from 1.8.5 to 1.8.6.

![Capture du 2020-10-07 10-33-34](https://user-images.githubusercontent.com/69907322/95308272-fb9f6080-0889-11eb-81aa-aaa2ac1892ce.png)

**To Reproduce**
1. Open the pad with firefox 81.0
2. Validate the warning message of ep_delete_after_delay
3. Wait a few seconds
4. Error happens...

**The problem apparently does not occur on Chromium (Version 85.0.4183.121)**

Many thanks for your help.

-----------------------------------------------------------------------------------------------------------------
Uncaught TypeError: $(...).context is undefined
    draw https://pad.nfcg.tv/static/js/require-kernel.js?v=702f4c55 line 226 > Function:131
    show https://pad.nfcg.tv/static/js/require-kernel.js?v=702f4c55 line 226 > Function:72
    timer https://pad.nfcg.tv/static/js/require-kernel.js?v=702f4c55 line 226 > Function:60
require-kernel.js:131:16
Erreur d’analyse XML : erreur de syntaxe
Emplacement : https://pad.nfcg.tv/jserror
Numéro de ligne 1, Colonne 1 :
-----------------------------------------------------------------------------------------------------------------

**Troubleshooting information**

Etherpad version (on Ubuntu Server 18.04)

Version number: 1.8.6

Latest available version: 1.8.6

Git sha: 3886e95

**Installed plugins**

ep_adminpads2
ep_align
ep_author_hover
ep_delete_after_delay
ep_embedded_hyperlinks2
ep_etherpad-lite
ep_font_color
ep_font_size
ep_headings
ep_pads_stats
ep_spellcheck

All plugins are up to date.

![Capture du 2020-10-07 10-58-03](https://user-images.githubusercontent.com/69907322/95309910-09ee7c00-088c-11eb-8960-15d9d9303c36.png)

**Installed parts**

ep_spellcheck/ep_spellcheck
ep_pads_stats/ep_pads_stats
ep_headings/main
ep_font_size/main
ep_font_color/main
ep_etherpad-lite/openapi
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/webaccess
ep_etherpad-lite/padreadonly
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/static
ep_etherpad-lite/express
ep_embedded_hyperlinks2/main
ep_delete_after_delay/ep_delete_after_delay
ep_author_hover/ep_author_hover
ep_align/main
ep_adminpads2/ep_adminpads2

**Installed hooks**
Server side hooks

eejsBlock_mySettings
    ep_spellcheck/spellcheck from ep_spellcheck/ep_spellcheck
eejsBlock_mySettings
    ep_author_hover/index from ep_author_hover/ep_author_hover
eejsBlock_dd_view
    ep_spellcheck/spellcheck from ep_spellcheck/ep_spellcheck
expressCreateServer
    ep_pads_stats/index:registerRoute from ep_pads_stats/ep_pads_stats
expressCreateServer
    ep_etherpad-lite/node/hooks/express/openapi:expressCreateServer from ep_etherpad-lite/openapi
expressCreateServer
    ep_etherpad-lite/node/hooks/express/adminsettings:expressCreateServer from ep_etherpad-lite/adminsettings
expressCreateServer
    ep_etherpad-lite/node/hooks/express/adminplugins:expressCreateServer from ep_etherpad-lite/adminplugins
expressCreateServer
    ep_etherpad-lite/node/hooks/express/admin:expressCreateServer from ep_etherpad-lite/admin
expressCreateServer
    ep_etherpad-lite/node/hooks/express/tests:expressCreateServer from ep_etherpad-lite/tests
expressCreateServer
    ep_etherpad-lite/node/hooks/express/socketio:expressCreateServer from ep_etherpad-lite/socketio
expressCreateServer
    ep_etherpad-lite/node/hooks/express/errorhandling:expressCreateServer from ep_etherpad-lite/errorhandling
expressCreateServer
    ep_etherpad-lite/node/hooks/express/importexport:expressCreateServer from ep_etherpad-lite/importexport
expressCreateServer
    ep_etherpad-lite/node/hooks/express/apicalls:expressCreateServer from ep_etherpad-lite/apicalls
expressCreateServer
    ep_etherpad-lite/node/hooks/express/padreadonly:expressCreateServer from ep_etherpad-lite/padreadonly
expressCreateServer
    ep_etherpad-lite/node/hooks/express/padurlsanitize:expressCreateServer from ep_etherpad-lite/padurlsanitize
expressCreateServer
    ep_etherpad-lite/node/hooks/express/specialpages:expressCreateServer from ep_etherpad-lite/specialpages
expressCreateServer
    ep_etherpad-lite/node/hooks/i18n:expressCreateServer from ep_etherpad-lite/i18n
expressCreateServer
    ep_etherpad-lite/node/hooks/express/static:expressCreateServer from ep_etherpad-lite/static
expressCreateServer
    ep_delete_after_delay/delete:registerRoute from ep_delete_after_delay/ep_delete_after_delay
padLoad
    ep_pads_stats/index:padLoad from ep_pads_stats/ep_pads_stats
padUpdate
    ep_pads_stats/index:padUpdate from ep_pads_stats/ep_pads_stats
padRemove
    ep_pads_stats/index:padRemove from ep_pads_stats/ep_pads_stats
eejsBlock_editbarMenuLeft
    ep_headings/index from ep_headings/main
eejsBlock_editbarMenuLeft
    ep_font_size/index from ep_font_size/main
eejsBlock_editbarMenuLeft
    ep_font_color/index from ep_font_color/main
eejsBlock_editbarMenuLeft
    ep_embedded_hyperlinks2/index from ep_embedded_hyperlinks2/main
eejsBlock_editbarMenuLeft
    ep_align/index from ep_align/main
collectContentPre
    ep_headings/static/js/shared from ep_headings/main
collectContentPre
    ep_font_size/static/js/shared from ep_font_size/main
collectContentPre
    ep_font_color/static/js/shared from ep_font_color/main
collectContentPre
    ep_align/static/js/shared from ep_align/main
collectContentPost
    ep_headings/static/js/shared from ep_headings/main
collectContentPost
    ep_font_size/static/js/shared from ep_font_size/main
collectContentPost
    ep_font_color/static/js/shared from ep_font_color/main
collectContentPost
    ep_align/static/js/shared from ep_align/main
getLineHTMLForExport
    ep_headings/index from ep_headings/main
getLineHTMLForExport
    ep_font_color/exportHTML from ep_font_color/main
getLineHTMLForExport
    ep_align/index from ep_align/main
eejsBlock_dd_format
    ep_font_size/index from ep_font_size/main
eejsBlock_dd_format
    ep_font_color/index from ep_font_color/main
aceAttribClasses
    ep_font_size/index from ep_font_size/main
exportHtmlAdditionalTags
    ep_font_size/index from ep_font_size/main
exportHtmlAdditionalTagsWithData
    ep_font_color/exportHTML from ep_font_color/main
stylesForExport
    ep_font_color/exportHTML from ep_font_color/main
socketio
    ep_etherpad-lite/node/hooks/express/adminsettings:socketio from ep_etherpad-lite/adminsettings
socketio
    ep_etherpad-lite/node/hooks/express/adminplugins:socketio from ep_etherpad-lite/adminplugins
socketio
    ep_adminpads2 from ep_adminpads2/ep_adminpads2
expressConfigure
    ep_etherpad-lite/node/hooks/express/webaccess:expressConfigure from ep_etherpad-lite/webaccess
createServer
    ep_etherpad-lite/node/hooks/express:createServer from ep_etherpad-lite/express
restartServer
    ep_etherpad-lite/node/hooks/express:restartServer from ep_etherpad-lite/express
eejsBlock_editorContainerBox
    ep_embedded_hyperlinks2/index from ep_embedded_hyperlinks2/main
handleMessage
    ep_delete_after_delay/delete from ep_delete_after_delay/ep_delete_after_delay
eejsBlock_styles
    ep_delete_after_delay/delete from ep_delete_after_delay/ep_delete_after_delay
eejsBlock_adminMenu
    ep_adminpads2 from ep_adminpads2/ep_adminpads2

**Client side hooks**

collectContentPre
    ep_headings/static/js/shared from ep_headings/main
collectContentPre
    ep_font_size/static/js/shared from ep_font_size/main
collectContentPre
    ep_font_color/static/js/shared from ep_font_color/main
collectContentPre
    ep_align/static/js/shared from ep_align/main
collectContentPost
    ep_font_size/static/js/shared from ep_font_size/main
handleClientMessage_CUSTOM
    ep_delete_after_delay/static/js/reconnect from ep_delete_after_delay/ep_delete_after_delay
documentReady
    ep_delete_after_delay/static/js/reconnect from ep_delete_after_delay/ep_delete_after_delay
`

**Comment by fabrice-noel** [comment]
In the end I reproduce this problem also on Chromium...

**Comment by JohnMcLear** [comment]
@fabrice-noel as per the issue creation guidelines please attempt to recreate this issue without plugins.  Then add plugins until you find the plugin at fault and open an issue on that plugins repo.

**Comment by fabrice-noel** [comment]
Hi John,

Thank you very much for your very quick response and sorry for not respecting the "protocol" for opening a ticket. So I will investigate in this sense, plugin by plugin.

Thank you very much!
