### ISSUE TITLE
The automatic indentation after a colon is annoying

### ISSUE THREAD

**Issue by cwassert** [ether/etherpad-lite#4405]
When typing a colon followed by a linebreak the etherpad automatically indents the next line with four spaces.
This is annoying, if you want to start an enumeration, an itemlist or a section indented by TAB because starting either of those keeps the four spaces in tact.

There are multiple ways to improve this behavior. The easiest to implement would be do remove the automatic indentation.

Version: etherpad/etherpad:1.8.4

**Comment by JohnMcLear** [comment]
Lists were practically rewritten in 1.8.5 and afaik we decided to keep this as it's expected and desired UX.

I'd welcome a PR that is a setting to enable/disable this behavior, if you look at the files in ``src/static/js`` you should be easily able to figure out where the logic is make clientVars pass a setting.

Also this could be a plugin.  It's defo a "user choice" and you might even want to extend the setting to be a togglable setting in the user UX.
