### ISSUE TITLE
Ability to Use tables inside the document!

### ISSUE THREAD

**Issue by chetanmadaan** [ether/etherpad-lite#4413]
**Describe the bug**
Unable to create/paste tables inside the document.

**To Reproduce**
1. Create a table in HTML/Google Docs or some online editor.
2. Try pasting it inside the etherpad.
3. Table fades away.

**Expected behavior**
Table should stay.

**Video of behavior**
Copying and Pasting online created table.
![ether-pad-tables](https://user-images.githubusercontent.com/3968575/95867341-0d27b300-0d37-11eb-86ee-3744a9b1e928.gif)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: Version 85.0.4183.121 (Official Build) (64-bit)

**Additional context**

**Comment by JohnMcLear** [comment]
Please do a little bit of research before posting here..  Table support is from plugins, it is not in core, never has been.

**Comment by chetanmadaan** [comment]
Hi John,

I tested on the demo site https://video.etherpad.com/ and had the assumption that it had all the plugins installed. Since the video/audio & export/import documents is also possible with plugin and visible on the demo site.

In any case, I should have researched better.
