### ISSUE TITLE
API: how to open a new pad using only javascript api?

### ISSUE THREAD

**Issue by lookabass** [ether/etherpad-lite#4418]
Hi, sorry for my bad english, but I don't understand how I can open a new Pad by javascript API. I've read the documentation and I have write the example 1 in my installation. It work correctly, but I don't undestand what url I can paste in the iframe.

**Comment by JohnMcLear** [comment]
@lookabass please give information on what you are trying to achieve exactly.

**Comment by lookabass** [comment]
Like the example 1 in the documentation, I would to create a new pad author logged by my platform. To Create a group with my pad author created in this new group, and open etherpad by an iframe.

This is my code:


// new pad name 
			var randomPadName = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);

			// new pad author
			var userName = 'Luca' // user name
			var userID = 110; // user id (by my platform)
			var args ={
				"name": userName,	
				"authorMapper": userID 
			}
			etherpad.createAuthorIfNotExistsFor(args, function(error, data) {
			if(error){
				console.error('Error: ' + error)
			}else{
				console.log('createAuthorIfNotExistsFor success:')
				var authorID = data.authorID // author id generated by etherpad

				// new group for new author
				args ={
					"groupMapper": userID  
				}
				etherpad.createGroupIfNotExistsFor(args, function(error, data) {
				if(error){
					console.error('Error: ' + error)
				}else{
					console.log('createGroupIfNotExistsFor success:'

					// new pad for the group
					var groupID = data.groupID 
					args ={
						"groupID": groupID, // 
						"padName": randomPadName, 
						"text": ['prova'] // default text for the pad
					}
					etherpad.createGroupPad(args, function(error, data) {
						if(error){
							console.error('createGroupPad error: ')
							console.log(error)
						}else{
							console.log('createGroupPad success:')
							console.log(data)
						}
					})
					
					// new session 
					args ={
						"groupID": groupID, 
						"authorID": authorID, 
						"validUntil": 1702999999 
					}
					etherpad.createSession(args, function(error, data) {
						if(error){
							console.error('createSession error: ')
							console.log(error)
						}else{
							console.log('createSession success:')

							// javascript cookie with the sessionID
							document.cookie = 'sessionID =' + data.sessionID;
							
							// oper the pad on screen
							// I don't understand what is the src url I can use for the iFrame
							$('#mainEditor').html('<iframe name="embed_readwrite" src="#######" width="80%" height="600" frameborder="0"></iframe>');
						}
					})
				}
			})

**Comment by JohnMcLear** [comment]
Eh?  ``src`` is the URI of your Etherpad instance is hosted..  IE the Etherpad Video service would read ``https://video.etherpad.com``

I haven't done auth/embedding in a long time but afaik if you set a cookie you don't you need to specify the domain?  Also be mindful of cookie not being available if your etherpad instance is not in the same domain as your application...

But really, I'm confused how you don't know the URL of your own Etherpad instance..  What am I missing here?

**Comment by lookabass** [comment]
Sorry I forgot to mention that I have installed etherpad on a Raspberry Pi for use within a private LAN and with a mysql db. My problem is that I don't understand what parameters I have to pass in the src of the iframe after http: //192.168.50.10/p / ....

I have try http://192.168.50.10/p/PAD_NAME (where PAD_NAME is the name of the pad I created via API), but etherpad creates a new pad with a new user and doesn't use the one I generated via API.

**Comment by JohnMcLear** [comment]
Cookies need to be from same host and protocol afaik...

**Comment by lookabass** [comment]
on my browser I have the same cookie at the ip 192.168.50.10 and at the ip 192.168.50.10:9001 
1. express_sid with the value s:"HY6c2Jo8ZRX7hj_xloVYotZSAgubq9Iv.hAH1+uYRVR+YtEWOUF6ueeiRIim0bULCSDXTEzixMXM"
2. sessioID: with an array 0:"s", 1:"730102fdca77eecc2333d6c339e0ef78"
3. token: with another array 0:"t",1:"hW4FPt51SPLQLOBVHNp3"

It's not ok?

**Comment by JohnMcLear** [comment]
I feel like your best bet here is to look at plugins and see how they solve the problem.

**Comment by lookabass** [comment]
Ok I'll look the plugin. Thank you for all :-)

**Comment by bharath-naik** [comment]
@lookabass , hi did you find the solution from Plugins, as i also want to achieve exactly like you

**Comment by lookabass** [comment]
thank for your interesting, but i don't resolve my issue.

do you have any suggest?

Il giorno gio 12 nov 2020 alle ore 02:32 bharath <notifications@github.com>
ha scritto:

**Comment by bharath-naik** [comment]
i didn't find ... but sure we will help out each other

**Comment by lookabass** [comment]
as I wrote in the post, my problem is related to the use of etherpd via
API. I followed the example of the documentation, but once I went through
the steps of creating the group, user and pad, I would like the web page to
automatically open the pad I generated, but I don't understand how to do
this step.

Il giorno gio 12 nov 2020 alle ore 19:35 bharath <notifications@github.com>
ha scritto:

**Comment by bharath-naik** [comment]
hi @lookabass , i have run your code but it say's `document.cookie = 'sessionID =' + data.sessionID; ` logs an error ` document is not defined`,  how are you defining this document using api. you are actually close to the solution. i have hard coded the session id in browser console and it worked like you needed.

**Comment by squiddle** [comment]
hi, i wanted to clean it up and package properly but i just do not have time. so here is my solutions so far. maybe it helps.

For group pads you use the API to create the pad, the group and a session. That session needs to be in a cookie. i created a new endpoint in etherpad which creates the correct session cookie (leaving existing session cookies intact) and redirects to the final pad.

```
/**
 * takes query parameter `sessionID` and redirects to the query parameter `target`.
 * 
 * target must be an absolute uri starting with /p/
 */
const authorManager = require('ep_etherpad-lite/node/db/AuthorManager');
const db = require("ep_etherpad-lite/node/db/DB");

exports.expressCreateServer = function(_hook_name, args) {
    args.app.get("/auth_session", function(req, res){
        const sessionID = req.query['sessionID'];
        if (!sessionID) {
            return res.sendStatus(400);
        }
        const target = req.query['target'];
        if(!target || !target.startsWith('/p/')){
            return res.sendStatus(400);
        }

        const existingSessionIds = (req.cookies['sessionID'] || '')
              .split(',')
              .map(s => s.trim())
              .filter(s => !!s);

        if(existingSessionIds.indexOf(sessionID) === -1){
            res.cookie('sessionID', [sessionID, ...existingSessionIds].join(','), {
                secure: req.secure
            });
        }
        res.setHeader('Cache-Control', 'no-cache');
        return res.redirect(target);
    });
```

for non-group pads the session does not matter, but a token is necessary. for that a similar logic applies but you cannot create the token via the api.
So via API you create the author (and the pad if you want). and then redirect to the following new endpoint:

```
/*
 * new endpoint that generates a token cookie for the given query parameter `authorID` and redirects to query parameter `target`
 * 
 * target must be an absolute uri starting with /p/
 *
 * this uses internals of etherpad which will probably not be a long term maintainable solution.
 */
exports.expressCreateServer = function(_hook_name, args) {
    args.app.get("/auth_authortoken", function(req, res) {
        const authorID = req.query['authorID'];
        if (!authorID) {
            return res.sendStatus(400);
        }
        const target = req.query['target'];
        if (!target || !target.startsWith('/p/')) {
            return res.sendStatus(400);
        }

        return authorManager.getAuthor(authorID)
                     .then((author) => {
                         if (!author) {
                             return res.sendStatus(404);
                         }
                         let existingToken = req.cookies['token'];
                         return db.get("token2author" + ":" + existingToken)
                                  .then(function(existingAuthor){
                                      if (existingAuthor !== authorID) {
                                          const token = existingToken || generateToken();
                                          db.set("token2author" + ":" + token, authorID);
                                          res.cookie('token', token, {
                                              secure: req.secure

                                          });
                                      }
                                      res.setHeader('Cache-Control', 'no-cache');
                                      return res.redirect(target);
                         });
                     });
    });
```

**Comment by bharath-naik** [comment]
will this also work for Docker installation.
