### ISSUE TITLE
Alt F9 is broken

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4422]
As per accessibility docs alt f9 should focus on toolbar and left/right keys should nav through.

CSS is missing for the focus and left/right doesn't work because the focus is on a button in an a href in a li..  Afaik the focus would need to be on the list item to be able to left/right toggle through??

Bumped @seballot because he's a ninja at these types of things :1st_place_medal:

**Comment by rhansen** [comment]
I did some testing and it looks like it is actually working (Firefox 81):
* Select some text
* Hit Alt-F9 (there is no visual indicator that anything happened, other than the cursor might disappear)
* Hit Tab to move to the italic button (no visual indicator)
* Hit space to activate the italic button. (With the colibris skin there's no visual indicator other than the text becoming italic. With the no-skin skin the italic button becomes darker.)

So I think the problems are:
* No visual indicator showing that a button has focus.
* No visual indicator in colibris showing that a button is in the toggled state (bold on, italic on, etc.).

**Comment by JohnMcLear** [comment]
Left and right arrow keys should nav through without tab key no?

**Comment by rhansen** [comment]
Left and right don't work. Only tab.

**Comment by JohnMcLear** [comment]
Wiki docs say Left/right arrow keys should work, is that only if a specific browser setting is enabled?

**Comment by rhansen** [comment]
¯\_(ツ)_/¯

**Comment by seballot** [comment]
Hi ! I made the css fix for bouton to be outline when focused

> No visual indicator in colibris showing that a button is in the toggled state (bold on, italic on, etc.).

There is a visual indicator, but it's light :)

![image](https://user-images.githubusercontent.com/17404254/97104076-31797d00-16b1-11eb-827b-2a367c9a45d9.png)

**Comment by JohnMcLear** [comment]
I'm closing this with the hope that accessibility is okay w/ tab
