### ISSUE TITLE
Support for pencils (e.g. on surface, ipad...)

### ISSUE THREAD

**Issue by efinder2** [ether/etherpad-lite#4428]
* * *

name: Feature request
about: Suggest an idea for this project
title: ''
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
We use etherpad in math class. It's quite fustrating to copy paste the special characters like ∧ or ⇒ in the etherpad around. Same thing for working with roots and so on. Currently I use the handwriting recognition of OneNote and copy and paste the whole expression to the etherpad.

**Describe the solution you'd like**
It would be nice to be able to use the pen support of the device (graphic tablet, active stylus...) to write the notes like in OneNote. So you can draw your characters like on a paper sheet.

**Describe alternatives you've considered**
As alternative it would be possible to implement a special character selection to fetch the needed characters. Problem in this approach is, it takes a lot of time to find the characters needed for a complex expression.

**Additional context**

**Plugin?**
I don't know how deep a pixel based drawing would cut in to the architecture of this package so I won't suggest here this option.

**Comment by JohnMcLear** [comment]
@efinder2 Just FYI in general if the request requires special equipment we have a minimum requirement of 3 devices of said special equipment before we even consider the problem.  Is that something you can facilitate?

**Comment by efinder2** [comment]
Sorry have pressed wrong button while quick reading. Currently I only have a [wacom tablett](https://www.amazon.de/gp/product/B079QBDTDF/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1). It is my daily driver for college, so I can't provide it. Class mate of mine have an acer spin and a apple ipad. Each with a corresponding pen and might help for testing. As student I can not afford to buy three of this kind for you.

In the semester holidays of my computer science studies I may be able to look in to it and create a pull request.
