### ISSUE TITLE
Control F error

### ISSUE THREAD

**Issue by vishnuvijayanpv** [ether/etherpad-lite#4444]
Chrome and Microsoft Edge keeps searching as soon as it opens. It also makes the cursor stuck. The problem exist only on the browsers. Nowhere else..

**Comment by JohnMcLear** [comment]
Cursor or caret?

**Comment by JohnMcLear** [comment]
I have no idea what this error / bug report means, please try to be coherent in your bug reporting and following the guidelines that are visible when you create a new issue.

**Comment by JohnMcLear** [comment]
Steps to replicate are really important in bug reports @vishnuvijayanpv -- in this instance I guessed what you are bug reporting

1. Control F
1. Type something
1. Press Escape
1. Try to type in pad
1. Caret is placed in selection ``[[0,0][0,0]]``

Ideally the caret would be at the last position prior to hitting Control F.

It's 99% this behaviour is upstream in browsers and has nothing to do with Etherpad.

Is this the bug report you were trying to write?

**Comment by JohnMcLear** [comment]
Gonna close as no update in nearly a week.
