### ISSUE TITLE
Travis builds slow - migrate to travis-ci.com?

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4445]
The Travis builds start with a huge delay (hours). 

Some people on Twitter but also from [Travis staff](https://travis-ci.community/t/builds-hang-in-queued-state/10250/6) recommend moving to travis-ci.com which supports open source projects since [2018](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg)

Should we try to migrate?

**Comment by webzwo0i** [comment]
https://travis-ci.community/t/org-to-com-migration-deadline/10260 there probably even exists a definite plan to close travis-ci.org

**Comment by JohnMcLear** [comment]
Environment variables for sauce_username et al are not maintained during migration so I would need to put a few hours aside to manually do that for 100 or so repos ;\

**Comment by JohnMcLear** [comment]
All done.
