### ISSUE TITLE
ReferenceError: sesionAuthorID is not defined

### ISSUE THREAD

**Issue by Benno1308** [ether/etherpad-lite#4454]
@rhansen @JohnMcLear 

https://github.com/ether/etherpad-lite/blob/master/src/node/db/SecurityManager.js#L129

Typo in 'sesionAuthorID' should be 'sessionAuthorID', how can something like this be on master for > 2 months?!

**Comment by JohnMcLear** [comment]
We work from develop....

**Comment by Benno1308** [comment]
Then please update the "Manual install" section in your README.md to checkout 'develop' and not 'master'...

**Comment by rhansen** [comment]
I cherry-picked the two critical fixes to `master`.

**Comment by JohnMcLear** [comment]
Thanks and sorry for late release.
