### ISSUE TITLE
Support Ctrl (or Shift) + click on link to open it in a background tab (or a new window)

### ISSUE THREAD

**Issue by JustAnotherArchivist** [ether/etherpad-lite#4456]
* * *

name: Feature request
about: Suggest an idea for this project
title: Support Ctrl + click on link to open it in a background tab
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
I use pads for working collaboratively on lists of links. I tend to open several links at once in background tabs, then go through them. But opening links from Etherpad in a background tab only works via right click – if the context menu isn't disabled (it is e.g. on board.net).

**Describe the solution you'd like**
I'd like links to behave like standard links. In particular, Ctrl + click on a link should open it in a new background tab, and Shift + click should open it in a new window (by default, in most browsers).

Sidenote: Etherpad should not try to emulate Ctrl/Shift + click but delegate the handling to the browser. There are browser settings and extensions that modify link interaction, and those should still work as expected. Effectively, links in pads should be as close to plain, non-scripted `<a target="_blank" href="...">` tags as possible.

**Plugin?**
A previous issue on various other link-related things but also including this (#3533) was closed with a mention of plugins, so I guess it might be possible. However, I believe core Etherpad should mirror the standard behaviour of links throughout the web and only *non-standard* behaviour would be plugin-worthy.

**Comment by rhansen** [comment]
What browser and operating system are you using?

**Comment by rhansen** [comment]
Note that simply setting `contentEditable` to false when Ctrl is pressed isn't a great solution because it will break Ctrl-C and Ctrl-V.

**Comment by JohnMcLear** [comment]
Doesn't middle click do this?

**Comment by JustAnotherArchivist** [comment]
@rhansen Firefox 82 on Debian sid

@JohnMcLear Middle-click inserts the X11 primary selection (on GNU/Linux) because it's an editable field. On normal links though, yes, it would. I'm not sure which behaviour is preferable here since inserting the selection that way should also be possible.

**Comment by rhansen** [comment]
> Middle-click inserts the X11 primary selection (on GNU/Linux) because it's an editable field.

FYI: That behavior changed with https://github.com/ether/etherpad-lite/pull/4434. Now middle clicking on a link should do nothing (on X11 systems).

**Comment by JustAnotherArchivist** [comment]
Thanks, I suppose that makes most sense: middle-clicking on a link would (after this issue is fixed) open it in a background tab, and middle-clicking anywhere else would paste the primary selection (on X11).

**Comment by rhansen** [comment]
I was looking at how Google Docs handles URLs and maybe we should imitate its behavior: When you click on a link, Google Docs moves the caret to the click location and pops up a bubble that has its own clickable copy of the link (as well as buttons to edit the link or unlinkify).

**Comment by JustAnotherArchivist** [comment]
Since that bubble is above/below the actual link, that means clicking on the link, moving the mouse, and clicking again. Not ideal in my opinion when working with many links.

For context: my current usage is essentially a (commented) list of URLs to be archived, and the interaction with the document consists of opening links (multiple at once for efficiency), doing something with the opened tabs, then marking them as done in some way (e.g. strikethrough) or noting any issues.

**Comment by JustAnotherArchivist** [comment]
The middle-click workaround exists now (although it doesn't appear to work correctly, but I haven't been able to investigate yet whether a plugin interferes or similar), but this issue is still valid.

**Comment by JustAnotherArchivist** [comment]
This issue is still valid.

**Comment by JustAnotherArchivist** [comment]
No, this still isn't stale.

**Comment by SamTV12345** [comment]
I'm not sure. It seems to open up in new window when clicking SHIFT + click. Is this still relevant for  you?

**Comment by JustAnotherArchivist** [comment]
I just retested with the official trial instance (which I assume runs the current dev version or something close to it?) with Firefox. No, it does not behave correctly.

* Shift + click should open a new window but opens a tab instead.
* Ctrl + click should open a background tab but doesn't work at all.
* Ctrl + Shift + click should open a foreground tab but also doesn't work at all.

Other link interaction doesn't work either: clicking and dragging a link to the URL bar should open that URL in the current tab; dragging it onto the tab bar would open a tab in the relevant position, etc. None of these things work; trying to drag selects text instead despite the hand pointer cursor on the link.

**Comment by heldersepu** [comment]
Really an interesting case...
in the monaco editor it work
https://monaco-react.surenatoyan.com/

![image](https://github.com/ether/etherpad-lite/assets/545474/dc2ae7ad-1370-4056-b665-d9bedfe6456a)

**Comment by heldersepu** [comment]
smells like it could be here:

https://github.com/ether/etherpad-lite/blob/404ffde232cd311dfcf507c69f9d337259a2780a/src/static/js/ace2_inner.js#L2243-L2268
