### ISSUE TITLE
Delay before deletion message

### ISSUE THREAD

**Issue by meaz** [ether/etherpad-lite#4461]
When you modify a pad, there is a popup with a message that says:
```
Delay before deletion

Without further modification, your pad will be removed in approximately 179.9 days.
Please modify your pad or export it to save your work.
```

Is that possible to remove this message, or to set to appear only like X days before the deletion?

**Comment by JohnMcLear** [comment]
Sounds like a plugin and not an etherpad thing.  Please read the contributing and issue guidelines.
