### ISSUE TITLE
How do I import and Excel spreadsheet into etherpad?  Any help is appreciated! 

### ISSUE THREAD

**Issue by meintx** [ether/etherpad-lite#4467]
* * *

name: Feature request
about: Suggest an idea for this project
title: ''
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when (...)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Plugin?**
Might this feature be better suited to being a plugin?  Usually features that can be plugins, should be.

**Comment by JohnMcLear** [comment]
Please read contributing guidelines before creating issues.
