### ISSUE TITLE
Some spaces lost on .doc import

### ISSUE THREAD

**Issue by vasylOstrovskyi** [ether/etherpad-lite#4468]
**Describe the bug**
After loading documents in .doc (probably, pdf too), some spaces in the document disappear. Most noticeable with Cyrillic documents, but for purely Latin also happens in some places.

**To Reproduce**
1. Go to https://video.etherpad.com/, create random pad
2. insert all letters of Cyrillic alphabet separated by spaces: "а б в г ґ д е є ж з и і ї й к л м н о п р с т у ф х ц ч ш щ ю я ь"
3. save as MSWord document. Open saved file with LibreOffice, verify that all is imported correctly.
4. Import saved .doc file back to Etherpad. The result is "а б в г ґ д е є ж з и і ї й к л м н о п р с ту ф х ц ч ш щ ю я ь", no space between  "т" and "у"
5. check that this is not a LibreOffice error: open the file in LibreOffice, and export it to xhtml. The result is correct.
6. Repeat the same once again: save pad to .doc, load it back. One more space disappeared: "а б в г ґ д е є ж з и і ї й к л м н о п р с туф х ц ч ш щ ю я ь" etc.
7. In real-life Latin documents this also happens sometimes, I noticed that space in the beginning of a new sentense disappears on import (e.g., "...end of something. Continue..." is sometimes changed to  "...end of something.Continue...", no space after ".") 

**Expected behavior**
Correct spacing of imported documents.- Version [e.g. 22]

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser Chromium, Firefox
 
Regards,
 Vasyl

**Comment by JohnMcLear** [comment]
Can you replicate locally on latest develop?  Testing on video... Is useful but not representative of Etherpad (as plugins can influence experience)

**Comment by vasylOstrovskyi** [comment]
1. In fact, I first noticed this problem in my ("production") envirornment v.1.8.6, with the latest plugins:
ep_align
ep_embedded_hyperlinks2
ep_comments_page
ep_etherpad-lite
ep_headings2
ep_font_color
ep_markdown
ep_spellcheck
ep_webrtc
ep_whiteboard
Import of Cyrillic .doc files is almost unuseable due to lost spaces.
2. It seems that it is not a LibreOffice itself error, I have BigBlueButton installed on the same server which uses LibreOffice for document import (convert .doc, .pdf etc to svg), and no issues observer there.
3. No issues with txt, html, etherpad import, only .doc (as I remember, pdf also had problems, but I need to re-check)
4. I will try fresh and clean install on my local system and report the result.
Regards,
 Vasyl

**Comment by JohnMcLear** [comment]
Okay great, duly noted.  Yea try without plugins and on latest develop.  If it's .doc it depends if you are using abiword or libreoffice?  I assume LO given your previous response.

Let me know your further findings.

**Comment by vasylOstrovskyi** [comment]
OK, I installed on ly laptop from git, 'git status' shows 'origin/develop' system Ubuntu 18.04, node v10.23.0, modified path to soffice in settings.json, and started bin/run.sh
The issue is still there, but I noticed some new effect:
1. when I load file exported from video..., I get "а б в г ґ д е єж з и і ї й к л м н о п р с т у ф х ц ч ш щ юя ь", no spaces between "єж" and "юя", on video... and my production server it was only one missing space in "ту", which is now on its place
2. when load file produced on my laptop, I get one space missing between "мн", but loading it on production  produced again missing space in "ту".
3. I opened produced .doc file in LO and exported it to xhtml. The resulting file loads withall spaces present, so the sequence
etherpad -> .doc -> .html -> etherpad is exact. Thus I admit that my copy of LibreOffice is good.
4. Import-export with pdf works correct, tried with real-life document, too.
5. Import of odt has issue, again, but spaces are lost in different place

Regards,
Vasyl

**Comment by webzwo0i** [comment]
Probably related to https://github.com/ether/etherpad-lite/pull/4240 ?

**Comment by webzwo0i** [comment]
This should be fixed on develop branch.

@vasylOstrovskyi Could you test if it works for you now, please?

**Comment by vasylOstrovskyi** [comment]
@webzwo0i Thanks, now it looks resolved.
Regards,
 Vasyl
