### ISSUE TITLE
Text / planing templates

### ISSUE THREAD

**Issue by wadeeProd** [ether/etherpad-lite#4472]
First time in Github, following your project. I'm not a developer but a filmmaker with a website in construction, so I'm just a future user of this beautiful doc editor. 
Question - suggestion: 
What is the best roadmap to create text templates that we can use in etherpad? 
I'm looking to create templates for filmmakers: story board, call sheet..etc that we user can edit in etherpad
Again I'm not a developer,  so do I need a developer to create these templates? if yes, can I hire a developer from your community here?
Many thanks for your effort guys, 
Wadee

**Comment by JohnMcLear** [comment]
See ``settings.json``, you edit that file to set the default pad text.  **You can also edit it through the /admin url.**

You don't need to hire anyone, it's just a case of editing a blob of text.   If you do need to hire someone then a 10$ an hour very junior javascript engineer would be able to handle this task.  It shouldn't take them more than 5 minutes.

https://www.npmjs.org/package/ep_default-pad-text is a plugin (again install through the admin interface) that provides more advanced functionality than editing ``settings.json``.  See the documentation for that plugin for details.

If you are stuck or want further input please do feel free to join us on our discord @ https://discord.gg/daEjfhw

**Comment by wadeeProd** [comment]
Thank you John. 
I will follow and keep you updated in case. 
Great day to you

**Comment by JohnMcLear** [comment]
You are welcome :)

**Comment by wadeeProd** [comment]
Hi, sorry to write here again, let me know if I have to start new issue.
 I'm looking for ( a text analyses tool) to analyse film scenario that will be written in etherpad.
I'm looking for this type of results: list of persons/names & locations list & props/things list.. which are in the scenario.
Do you have any partners working on this (text analyses ) that can connect with your app?
If not , do you have any suggestion of (text analyses tool) that I can search or  contact to use with your app? 
Thanks,
Wadee

**Comment by JohnMcLear** [comment]
There are thousands of types of text analysis.  If I was you I'd search for Javascript "whatever type of analysis you want here"



If you can find the library an Etherpad plugin could implement it with some development.

We're not Text analysis people here, you will want to reach out to a text analysis community to find out the type of analysis you want :)  Perhaps it's meta-text-analysis, I simply don't know!

**Comment by wadeeProd** [comment]
Thanx again :)

**Comment by wadeeProd** [comment]
Hi John, 
I want to clear that my templates that i need for filmmakers are tables templates, example here: 
http://marchonfilm.com/call-sheets/

I saw that you added a new plugin for tables last week, I'm wondering if the etherpad with your plugin will help me to prepare this call sheet template / PAD? 
Can I add a photo/logo inside the table in your plugin?

Thanks again, 
Wadee

**Comment by JohnMcLear** [comment]
No idea.  Sorry, I originally helped you to solve a problem.  I'm not your support here.  The community at large can help.

**Comment by JohnMcLear** [comment]
Ps you might want to look at hiring a Dev to support you.

**Comment by wadeeProd** [comment]
Thank you again, excuse me for addressing you with many questions. 
Good Day to you,
Wadee
