### ISSUE TITLE
Branches may not be executed ????

### ISSUE THREAD

**Issue by CHWYH** [ether/etherpad-lite#4483]
https://github.com/ether/etherpad-lite/blob/8c55a38582e68c35bbebc63c8a22d86cd9b8bf67/src/static/js/ace2_inner.js#L5142

listType: RegExpExecArray | null
t:  string

“togglingOn = false”，I guess the branch will not be executed

**Comment by JohnMcLear** [comment]
Read the issue posting guidelines.  This is not an acceptable or actionable bug report.

**Comment by JohnMcLear** [comment]
Did you want to add context here?
