### ISSUE TITLE
websocket is not included in settings.json

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4486]
Websocket should be the primary method for comms between a client and server, but it's not include din the default ``settings.json.template``?

https://github.com/ether/etherpad-lite/blob/develop/settings.json.template#L451

This seems backwards/weird..

**Comment by rhansen** [comment]
Huh. Weird. In dev console I see it upgrade to websockets even though it's missing from that setting. Maybe socket.io is ignoring the setting?

**Comment by JohnMcLear** [comment]
Yea it appears it's being ignored or something, gonna dig deeper at a later date as it's not affecting performance/operations atm.
