### ISSUE TITLE
Etherpad users

### ISSUE THREAD

**Issue by sarikatekale** [ether/etherpad-lite#4508]
Please suggest me, what is wrong in my settings.json

  
  "dbType" : "mysql",
  "dbSettings" : {
    "user":     "root",
    "host":     "localhost",
    "port":     3306,
    "password": "",
    "database": "test",
    "charset":  "utf8mb4"
  },
  "requireSession": false,
"sessionNoPassword": false,
 "requireAuthentication": false,
 "requireAuthorization": true,

"users": {
    "admin": {
      "password": "changeme1",
      "is_admin": true
    },
    "user": {
      "password": "changeme1",
      "is_admin": true
    }
  },

and so on.
Here my etherpad for windows starts and gets close automatically with error : Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
can anyone tell me why this happens?

**Comment by JohnMcLear** [comment]
A trialing ``,``
