### ISSUE TITLE
TypeError: rowsPresent[index] is undefined

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4517]
Not 100% sure, but this appeared first somewhere between 1.6.6 and 1.8.4.

Often no edits happened right before/after the error appeared and it appeared multiple times in a short period on the affected client.

Seems only to happen on Firefox (but this could be due to a lot of people using firefox on our instance).

https://github.com/ether/etherpad-lite/blob/ba7d80fa571836e8ebb1b1f5a90a23f3b066b882/src/static/js/pad_userlist.js#L140 is the offending line

**Comment by rhansen** [comment]
I studied the relevant code for a bit and might have found something. As far as I can tell, `rowsPresent` is supposed to be an array that corresponds 1:1 with the rows in `#otheruserstable`, but this isn't true in one particular condition: row removal with animation. If the row is removed and the removal is animated, the row will be gone from `rowsPresent` but a row will still be in `#otheruserstable` until the animation completes.

A row can be removed in two ways:

* A user disconnects.
* A user changes their name in a way that causes their entry to change position in the user list. (Users are always listed in alphabetical order.) Moving a user up or down in `#otheruserstable` is implemented as a simultaneous add and remove, so if the remove is animated then there is a brief period of time when two rows exist in `#otheruserstable` for the same user, but only one entry exists in `rowsPresent`.

I haven't yet tried to reproduce, but I think it should be possible to reproduce by doing the following:

1. Have three clients (and only three clients) visit the same pad. One will be the observer (this is the user that should experience the exception), and the other two must be unnamed.
1. Determine which of the two unnamed users sorts higher on the list of users seen by the observer user. For convenience I'll refer to these as unnamed user 1 (sorts higher) and unnamed user 2 (sorts lower).
1. Make unnamed user 2 leave the pad. Wait for that user's row to completely disappear (as seen from the observer user).
1. Make unnamed user 1 leave the pad.
1. Wait 8000ms. (When a user leaves, their entry [lingers for 8 seconds](https://github.com/ether/etherpad-lite/blob/ba7d80fa571836e8ebb1b1f5a90a23f3b066b882/src/static/js/pad_userlist.js#L538) in case they come right back.)
1. Make unnamed user 2 join the pad.

If unnamed user 2 joins the pad immediately after the removal animation for unnamed user 1 starts, then there will be two rows in `#otheruserstable`: one for unnamed user 1 (at the top) and one for unnamed user 2 (bottom). But there will only be one entry in `rowsPresent` (for unnamed user 2). When `handleOtherUserInputs()` is called, it will find a match for unnamed user 2 at index 1. Index 1 doesn't exist in `rowsPresent`, so `rowsPresent[1]` will evaluate to `undefined`.

That's the theory at least.
