### ISSUE TITLE
Allow users to select their color by typing in the Hex value

### ISSUE THREAD

**Issue by randyho-kk** [ether/etherpad-lite#452]
This is a feature request that came from the ep-lite mailing list.

Daniel Reeves wrote:

> We're working on migrating from Etherpad 1.0 to Etherpad Lite and the
> color picker kind of drives me batty. It's tedious to pick the color
> from a continuous space like that instead of just picking my usual
> color (my colleagues and I are now used to each other's standard
> colors) from a short list.
> 
> Have others found a way to deal with that? Even an option to enter a
> hex color value would be nice.

**Comment by JohnMcLear** [comment]
Bounty for this: https://www.bountysource.com/issues/1371942-allow-users-to-select-their-color-by-typing-in-the-hex-value

**Comment by JohnMcLear** [comment]
Closing due to lack of interest.  This would be a really easy plugin to make if someone shows interest they can notify this thread.
