### ISSUE TITLE
Blocked autofocusing on a <input> element in a cross-origin subframe.

### ISSUE THREAD

**Issue by theraw** [ether/etherpad-lite#4525]
**Describe the bug**
Blocked autofocusing on a <input> element in a cross-origin subframe.

**To Reproduce**
1. install etherpad in example.com
2. create index.html on example2.com and use `<iframe src="https://example.com"></iframe>`
3. open chrome developer console.

**Expected behavior**
be able to iframe without errors even tho i tried to set `"trustProxy": true,` or `"sameSite": "None"`

**Screenshots**
1. simple iframe
![image](https://user-images.githubusercontent.com/32969774/100491008-cba16a80-3120-11eb-91b7-b8da0924f71c.png)

2. jitsi frame
![image](https://user-images.githubusercontent.com/32969774/100491157-cc86cc00-3121-11eb-8e84-651429193f8c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome & Chrome Canary
 - Version [e.g. 22] Latest

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] did not test via phone

**Additional context**
Tried many things and proper setup of headers but the thing won't fix, anyone seen same problem or is it just me? came around other similar issues couldn't find anything helpful and i'm using develop version..

**Comment by JohnMcLear** [comment]
If you embed video.etherpad.com do you have this problem?

Are you up to date on develop branch?

Tried set X domain origin policy with ep_helmet?

**Comment by theraw** [comment]
> If you embed video.etherpad.com do you have this problem? 

Yes

> Are you up to date on develop branch? 

Yes

> Tried set X domain origin policy with ep_helmet? 

no plugin is installed, i tried to install ep_helmet without doing any change i cannot embed my site anymore, i'm trying to find out where to set/allow my domain but can't find the config part also ep_helmet wiki doesn't seem published yet so can you please help on what part should i change or add?

**Comment by JohnMcLear** [comment]
Take a look through other closed issues regarding embedding Etherpad if you want to get this sorted ASAP.

**Comment by theraw** [comment]
as i already said i tried to search about similar issues and i tried some of them but didn't got any good result, sorry but as for ASAP i think looking more into issues it'll just go longer since there are over 100 issues only with "embed" problems!!

Not that important anyway i was just curious on why my nginx reverse proxy setup did fail since i also tried to bypass headers set by express.

**Comment by JohnMcLear** [comment]
I imagine it's a browser restriction.  Generally we recommend embeds are subdomain or same domain.

**Comment by rohitgupta274509** [comment]
How did you solve this issue, I also tried but not found solution

**Comment by theraw** [comment]
@rohitgupta274509 no i did not solve it.

**Comment by Sultan-Khalaily** [comment]
cant tell whats worse, people comments or simply github cummunity
