### ISSUE TITLE
Line numbers should line up with baseline

### ISSUE THREAD

**Issue by rhansen** [ether/etherpad-lite#4527]
Currently line numbers are positioned near the top of the line, so if you use `ep_font_size` to make a tall line then the line number is rendered too far up:

![screenshot](https://user-images.githubusercontent.com/1612291/100494104-4a3fdd00-310c-11eb-8d1f-488a0d0f7e19.png)

**Comment by JohnMcLear** [comment]
Cc @seballot

**Comment by seballot** [comment]
Sorry, no time to contribute to etherpad right now...

**Comment by JohnMcLear** [comment]
No rush.  I have another good challenge for you too with another plugin but it can wait some weeks.  Thanks man!!

**Comment by JohnMcLear** [comment]
Ready for review: https://github.com/ether/etherpad-lite/pull/4825 cc @seballot please let me know if I did it wrong :)

**Comment by JohnMcLear** [comment]
![image](https://user-images.githubusercontent.com/220864/108592495-07398280-7366-11eb-99c0-32269aeabf58.png)

Happy with this?  The code isn't as clean as the image and I'm worried about additional browser processing cost..  But it was never gonna come for free...

**Comment by rhansen** [comment]
Looks awesome, thanks!

**Comment by seballot** [comment]
I made some tests re https://github.com/citizenos/ep_image_upload/issues/35 and yes it's not related to the image_upload plugin

https://video.etherpad.com/p/test2

![image](https://user-images.githubusercontent.com/17404254/109616278-440b3380-7b35-11eb-9e83-0e6f95ab7ebb.png)

**Comment by JohnMcLear** [comment]
Yea it's defo core and 99% related to our patch :/

**Comment by seballot** [comment]
No it's not :) seems to come from a commit after our patch (if I checkout on our patch it works fine, but if I check out develop it's buggy)

I guess it's coming from your new loading image !! (just kidding)

Any idea?

**Comment by JohnMcLear** [comment]
Will look

**Comment by JohnMcLear** [comment]
cc @rhansen 
```
a17f9bf3cfc745a44d0e57b77912e346ffd3ce1c is the first bad commit
commit a17f9bf3cfc745a44d0e57b77912e346ffd3ce1c
Author: Richard Hansen <rhansen@rhansen.org>
Date:   Thu Feb 25 21:11:30 2021 -0500

    ace: Build the outer and inner iframes programmatically

    This makes the code easier to read and it silences Chrome's
    `document.write()` warning:
    https://developers.google.com/web/updates/2016/08/removing-document-write

:040000 040000 d0dba82aa650114a377976b7a6509f886215a38e ee192aa17ea74d23cd095b5ae98c8453a87867a0 M        src
```

**Comment by rhansen** [comment]
Opened #4914.

**Comment by TheThingGoesSkra** [comment]
Hi, thanks for your work !
Has this been resolved? Can I help ?

**Comment by JohnMcLear** [comment]
I just merged the pr reverted the bug causing code so now develop is stable(r) again.
