### ISSUE TITLE
Monospace doesn't stick if you directly link to a pad

### ISSUE THREAD

**Issue by alex-ong** [ether/etherpad-lite#4531]
**Describe the bug**
I'm using the `"useMonospaceFont": true` setting, which works fine if users
goto etherpad.site/ and then type in the pad name.

If you just go to etherpad.site/p/padname, the monospace setting does not stick

**To Reproduce**
0. Set settings.json `"useMonospaceFont": true`
1. User 1 goes etherpad.site and creates a pad (e.g. test1), it displays as monospace
2. User 2 goes to etherpad.site/p/test1
3. User 2 won't have monospaced font.
4. User 2 goes to etherpad.site/ and then types in `test1` and enters
5. User 2 gets correct behavior

**Expected behavior**
All users should have monospace font by default, then they can change it to whatever after.

**Screenshots**
Left side is User1
Right side is User2.
![image](https://user-images.githubusercontent.com/6406312/100576811-f6630d00-3332-11eb-8726-da5c380b6997.png)

**Desktop (please complete the following information):**
 - OS: Win 10 2004
 - Browser: Chrome, Firefox, Brave
 - Version : Chrome 86.0.4240.198 (Official Build) (64-bit)

**Comment by JohnMcLear** [comment]
This is expected behavior.

The Settings are "user settings" not site wide settings.

https://github.com/ether/etherpad-lite/blob/develop/settings.json.template#L210 -- change this line to true to make monospace the default for pads.

**Comment by alex-ong** [comment]
@JohnMcLear thats the exact setting that i was using.
Its user setting but if someone joins via URL it should default them to monospaced

**Comment by JohnMcLear** [comment]
Sounds very strange..  Will check.

**Comment by JohnMcLear** [comment]
Works fine...

Can you please provide exact Steps to replicate?

Did you test it w/ out any plugins as per issue posting requirements?

**Comment by alex-ong** [comment]
Can confirm it works fine on a different computer, using @42c0d809 and @d1e9ea6e.

No idea why it was broken...

Sorry for wasting your time!
