### ISSUE TITLE
Non node deployment

### ISSUE THREAD

**Issue by ThorsenRune** [ether/etherpad-lite#4532]
Hi, I think the Etherpad looks great and I'd like to try it.
Following the instructions got it up and running locally,but 
I wanted to deploy it using https://github.com/niutech/node.php
Where can I find information about what to do?
However im currently NOT a node.js developer so I do not understand the nodeworkflow but just like to get it up and running at this stage on my non node.js server.
Thanks for any help

**Comment by JohnMcLear** [comment]
Hey @ThorsenRune

We won't be supporting any PHP based deployment of Etherpad.

Sorry but this isn't something we would not take on as technical debt.

Apologies, the PHP node project repo might be a better place for this issue.

**Comment by ThorsenRune** [comment]
Thanks @JohnMcLear, I do understand and agree. May I suggest writing it in the readme/wiki for the project so its clear upfront, in case others had the same question?
