### ISSUE TITLE
Semantic versioning in package.json ignored because of npm ci

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4533]
I tag this as question. github just ate my comment, but I try to repeat all relevant information

https://github.com/ether/etherpad-lite/issues/3778 introduced `npm ci` during normal builds for performance reasons and reproducable builds. There's a problem with that:

We use semantic versioning in package.json:
- our dependency in package.json is `^1.2.3` and the dependency is at 1.2.3
- we commit the package-lock.json
- dependency gets to `v1.2.4`, but because we're using `npm ci` in `./bin/installDeps.sh` this version is never installed.

Besides not getting bugfix or security updates without releasing a new etherpad version, imo this is also against best practices -  I never look into package-lock.json to understand the dependencies, but at package.json.

I acknowledge that we got a lot of issues that were fixed with a clean installation and those reports have stopped after https://github.com/ether/etherpad-lite/issues/3778 I'm not sure about the origin of those, though. Did they use a global node_modules? Did some modules get loaded from `./node_modules` instead of `./src/node_modules`? (e.g. a plugin is loaded before every core code file and node remembered that it found the package in `./node_modules` - maybe someone knows the logic of require better, I'd need to test this - e.g. a plugin has dependency 1.2.0 but core has `^1.2.5`. both plugin and core do `require('the-dependency')`. if the plugin gets loaded, in theory, before core and node resolves the dependency in `./node_modules/the-dependency` (version 1.2.0) will it use that directory also for the core code, or will it repeat the steps and find it in `./src/node_modules/the-dependency` (version 1.2.5))

It would be good to know, why there were so many broken installations in the past - maybe npm got better or people tried broken plugins etc. In any case I think we should support semantic versioning again and drop `npm ci` for normal deployments. It has better performance (2x times faster), so it would be awesome if we can speed up the normal `npm i` a bit.

**Comment by rhansen** [comment]
> * dependency gets to `v1.2.4`, but because we're using `npm ci` in `./bin/installDeps.sh` this version is never installed.
> 
> Besides not getting bugfix or security updates without releasing a new etherpad version, imo this is also against best practices - I never look into package-lock.json to understand the dependencies, but at package.json.

The purpose of `package-lock.json` is to lock down the versions, so the fact that we would continue to use v1.2.3 is expected. It's also desired because it provides reproducibility (all of our users are using the same versions of the dependencies that we tested against). I think there are security benefits too.

To get security fixes and bug fixes, we should be regularly running `npm audit` and `npm update`.

**Comment by webzwo0i** [comment]
I'm okay with that in theory (using package-lock.json across all installations). Do you think we should use https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/ ?

I still find it somehow problematic that we stop users from getting the latest fixes of our dependencies until we release and they update etherpad, when this could happen automatically.
Also it's tempting to combine dependency/bugfix updates and feature updates, but I think we have this problem anyway (it's not easily avoidable, without doing a lot of backporting and supporting multiple releases - we don't do this right now).

**Comment by rhansen** [comment]
> Do you think we should use https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/ ?

Yes.

> I still find it somehow problematic that we stop users from getting the latest fixes of our dependencies until we release and they update etherpad, when this could happen automatically.

Auto-updating dependencies comes with risks. There's a trade-off here, and for now I think that it's better for us and for most of our users to be conservative about updating dependencies.

Some users will prefer the latest dependencies over stability. Those users can always run `npm up` themselves.

Maybe a good compromise would be to change our startup script to auto-update only vulnerable dependencies by running `npm audit --fix`.
