### ISSUE TITLE
start attribute in a nested list inconsistent?

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4539]
make three lines
```
a
b
c
```
make them a ordered list via button
```
1. a
2. b
3. c
```
highlight the second line (b) and press tab to apply nesting
```
1. a
  1.1 b
2. c
```

Export the HTML or inspect the second line: it has a start attribute with value "1" to indicate it should start the (sub) list with 1.

When importing back the same HTML, while the numbers visible in the pad are preserved, the start attribute of the second line is now "2". When exporting it again, the start attribute of the second line is still "2". Due to CSS applied, the visible numbers however are correct.

So ace2_inner.js does the right thing (it also repairs the attribute in case some list edits happen), but contentcollector does not. This also results in the list item getting a wrong pool attribute.

This issue is mostly to find out if you agree, as there seem to be no consequences in the UI. Imo this still needs to be addressed, especially because the pool attribute is clearly wrong. A import test, that checks the start attribute, is already [in](https://github.com/ether/etherpad-lite/blob/develop/tests/backend/specs/api/importexport.js#L40). A contentcollector test is currently [here](https://github.com/ether/etherpad-lite/blob/eplite-cc-and-import-tests/tests/backend/specs/contentcollector.js#L428).

Related question: starting a list with an arbitrary number is and will be unsupported (maybe due to counter-reset used in CSS?), right? e.g. without having list entries 1,2,3, start with number 4

**Comment by JohnMcLear** [comment]
Starting a list with an arbitrary number is afsik not supported.
