### ISSUE TITLE
Page View and Page Break support, since ep_page_view is now defunct

### ISSUE THREAD

**Issue by noumaans** [ether/etherpad-lite#4549]
* * *

name: Feature request
about: Suggest an idea for this project
title: ''
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
ep_page_view plugin has been marked as defunct. The repo's README states that page view functionality is available under Etherpad 1.8 under colibris.
However, in Etherpad 1.8 there is no setting available for page view, using &page_view also doesn't work. Control-Enter to add page breaks also doesn't work. Also found no references of this functionality being added in Changelog for 1.8.3.

**Describe the solution you'd like**
Pull the functionality from ep_page_view into Etherpad.

**Additional context**
It would be great if we can have automated page breaks (based on paper size), as well as manually inserted page breaks.

Thanks for all the great work @JohnMcLear 

**Plugin?**
This used to be a plugin.

**Comment by JohnMcLear** [comment]
@noumaans are you familiar with plugins to be able to develop this?  

It's essentially just a plugin that adds ``<p style="page-break-before: always">`` as lineContent when a user does key event "control enter"

It's very, very easy to make :)  See ep_headings2 for reference and good practice.

**Comment by santirodrigo** [comment]
I would like to see this included on Etherpad too... Could you re-open this issue?

**Comment by rico-c** [comment]
I would like to see this included on Etherpad too... Could you re-open this issue?
