### ISSUE TITLE
Export PDF with text colors

### ISSUE THREAD

**Issue by NathanHbt** [ether/etherpad-lite#4555]
* * *

name: Export with text colors
about: Export pad to PDF
title: ''
labels: enhancement
assignees: 

* * *

Hello,

Is it possible to add the possibility of exporting a PAD to PDF while keeping the text colors configured by the user when editing the PAD?

Thanks,
Regards,

**Comment by Barikad** [comment]
This feature would be a REAL improvement.

**Comment by dr0i** [comment]
This would be very useful. Please reopen.
