### ISSUE TITLE
Toolbar doesn't wrap unless window width is small enough

### ISSUE THREAD

**Issue by licaon-kter** [ether/etherpad-lite#4556]
1.8.6, Firefox, plain or embedded in Jitsi Meet

## Steps to reproduce the behavior
Install some plugins with toolbar buttons

## Screenshots
If more than enough width (larger than the toolbar length):
![ifenough](https://user-images.githubusercontent.com/2282799/101645831-b71d7600-3a2e-11eb-9922-2a7e03beee86.PNG)

If a small enough width (<40% of toolbar length) it wraps as expected:
![wrapping](https://user-images.githubusercontent.com/2282799/101645879-c43a6500-3a2e-11eb-9913-9404c8bee279.PNG)

In actual usage (>40% <toolbar length):
![reality](https://user-images.githubusercontent.com/2282799/101645898-cac8dc80-3a2e-11eb-85fb-162c12144d52.PNG)

On Android it wraps as expected.

**Comment by JohnMcLear** [comment]
cc @seballot

**Comment by seballot** [comment]
Hi ! I think I already fixed that with a similar ticket, maybe it has not been released yet? or maybe the fix was not good enough :) could you test with develop branch?

**Comment by licaon-kter** [comment]
@seballot Fixed in develop indeed, now a quick question, how to default to expanded view so the user does not need to press the +, hidden buttons will be rather hidden :)
