### ISSUE TITLE
Locale not enforced as setup in .json

### ISSUE THREAD

**Issue by licaon-kter** [ether/etherpad-lite#4559]
HEAD develop (d25010d5d7e5e53a020c24ea69cac64e58d266c5)
**To Reproduce**
Set
```
...
  "padOptions": {
    "lang":             "XX"
...
```

**Expected behavior**
No matter what locale the browser asks for, my language set as above is used by the UI.

**Actual results**
If browser locale is "EN", etherpad-lite is in English
If browser locale is "XX", etherpad-lite is in XX

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox, Vivaldi

**Comment by JohnMcLear** [comment]
Without testing id guess this was a cookie issue.  Did you try clear cookies before testing visiting the pad?

**Comment by licaon-kter** [comment]
Always using private tabs.

ID of locale? try `ro`

**Comment by JohnMcLear** [comment]
Confirmed.  I'm not sure why this is even in tho?  Why would you want to disregard the locale of the viewer?

Is there something I'm missing?

**Comment by licaon-kter** [comment]
Dunno about the reasoning, but I want this.

Locale tracking is a vector for unwanted analytics, no gain for the user to leak this.

But, I want them to have Etherpad in their actual locale. :)

**Comment by JohnMcLear** [comment]
I'm still confused to as why anyone would want this and / or the reason this issue exists ;/

**Comment by licaon-kter** [comment]
Because my users are on a certain locale that I'd like to enforce.

The fact that you don't use this is a moot point. :)

**Comment by JohnMcLear** [comment]
Etherpad will default to your users configured locale...  Is Etherpad not doing so?

This setting will not enforce anything, it's just a default and will over overridden if the user has a browser which exposes locale which is 99.9999% of modern browsers....

**Comment by licaon-kter** [comment]
Etherpad is not using the configured etherpad setting .json of "lang", as the OP says. 

Etherpad defaults, erroneusly, to the browser configured locale. 

Are we lost in translation?

**Comment by JohnMcLear** [comment]
> /LE: "it will not enforce" mmmkay, but when is it actually used? Under which conditions exactly?

Under conditions where browser locale isn't available one assumes....

**Comment by licaon-kter** [comment]
So like never then?
> browser exposes locale which is 99.9999% of modern browsers....

**Comment by JohnMcLear** [comment]
I will let a non-English speaker share there input on this thread because I think this is not an issue.

**Comment by webzwo0i** [comment]
Not sure, if I'm doing something wrong, but it seems that option (`lang`) is simply ignored. I can't get it to serve the page in the language I configure (ie. I set `lang` to `fr` and Accept-Language to a language etherpad does not have locales for - I assume it should default to `fr` then).

I would suggest renaming the option to `enforceLanguage` and find out, why it seems to have no effect.

**Comment by Nikerabbit** [comment]
I think there are legitimate concerns and needs to disable the automatic language detection based on the Accept-Language header (but still honor manual language selection), given that many users have don't have their browsers Accept-Language configured "correctly". But that would be a new feature request in my opinion.

Possible workaround, I think, would be to use a reverse proxy which overrides the language header.
