### ISSUE TITLE
pdf import not working

### ISSUE THREAD

**Issue by echristiaans** [ether/etherpad-lite#4585]
**Describe the bug**
When trying to import a pdf file into a pad, the following error message is displayed:

Import failed: We were not able to import this file. Please use a different document format or copy paste manually

import of other formats works. Export to pdf also works. 

**To Reproduce**
1. Go to 'import/export'
2. Click on 'choose file'
3. Select the file to import
4. Click on 'import now'
5. See error

**Expected behavior**
I would expect the contents of the pdf file to be imported into the pad. 

**Desktop (please complete the following information):**
 - OS: Client runs on MacOS 11.1, Etherpad 1.8.6 is deployed on Ubuntu 18.04.5 LTS
 - Browser: Brave 
 - Version: 1.17.75 Chromium: 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
list of installed plugins:
    - ep_hash_auth
    - bcrypt
    - ep_comments_page
    - ep_headings2
    - ep_align
    - ep_font_color
    - ep_table_of_contents
    - ep_font_family
    - ep_font_size
    - ep_image_upload
    - ep_embedded_hyperlinks2
    - ep_set_title_on_pad
    - ep_print
    - ep_mammoth
    - argon2
    - ep_draw

using LibreOffice (1:6.0.7) for conversion, also using Tidy (1:5.2.0-2)

The error message that is displayed in etherpad.log is:

```
[2020-12-18 13:45:20.019] [INFO] console - Exporting pad "dsfugauegfuoageh" in pdf format
[2020-12-18 13:45:20.020] [INFO] console - Found  undefined  for  dsfugauegfuoageh
[2020-12-18 13:45:35.888] [WARN] console - Converting Error: { [Error: ENOENT: no such file or directory, rename '/tmp/upload_f69452d349b913b2ea6766d70e14c6de.html' -> '/tmp/etherpad_import_635019763.html']
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/tmp/upload_f69452d349b913b2ea6766d70e14c6de.html',
  dest: '/tmp/etherpad_import_635019763.html' }
Error: ENOENT: no such file or directory, rename '/tmp/upload_f69452d349b913b2ea6766d70e14c6de.html' -> '/tmp/etherpad_import_635019763.html'
[2020-12-18 13:45:39.945] [INFO] access - [LEAVE] Pad "dsfugauegfuoageh": Author "a.wjkq3dh3PRzg9Ng9" on client YAh9_7m1mjNcFEawAAAD with IP "ANONYMOUS" left the pad
```

**Comment by JohnMcLear** [comment]
as per bug reporting guidelines have you tried replicating this bug without any plugins installed?

**Comment by echristiaans** [comment]
apologies, I must have overlooked that in the guidelines. Will try without
plugins and report back here.

**Comment by echristiaans** [comment]
have just installed with no plugins enabled and no plugins installed, same behavior. Here is the output int etherpad.log:

```
[2020-12-22 19:43:39.303] [WARN] console - Converting Error: { [Error: ENOENT: no such file or directory, rename '/tmp/upload_b5141bf89d13f1bd8a2f2e95bb567935.html' -> '/tmp/etherpad_import_3916987808.html']
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/tmp/upload_b5141bf89d13f1bd8a2f2e95bb567935.html',
  dest: '/tmp/etherpad_import_3916987808.html' }
Error: ENOENT: no such file or directory, rename '/tmp/upload_b5141bf89d13f1bd8a2f2e95bb567935.html' -> '/tmp/etherpad_import_3916987808.html'
[2020-12-22 19:43:39.305] [ERROR] console - (node:19039) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
[2020-12-22 19:43:39.307] [DEBUG] http - 200, POST /p/a95010ed98404ce1b62437793212f509/import
```

**Comment by JohnMcLear** [comment]
Are you running latest develop branch or a release?

**Comment by echristiaans** [comment]
running "main" branch. Have also tried develop branch, unfortunately with develop only etherpad and txt works - none of the other default import / export types work.

**Comment by JohnMcLear** [comment]
what's your soffice path from ``settings.json``?

Test against develop branch please.

**Comment by echristiaans** [comment]
```
"soffice": "/usr/bin/soffice"
```

```
stat /usr/bin/soffice
  File: /usr/bin/soffice -> ../lib/libreoffice/program/soffice
  Size: 34        	Blocks: 0          IO Block: 4096   symbolic link
Device: 10301h/66305d	Inode: 55319       Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-12-22 08:21:02.522148138 +0100
Modify: 2019-09-21 13:44:15.000000000 +0200
Change: 2020-12-14 11:37:20.733700489 +0100
 Birth: -
```

**Comment by JohnMcLear** [comment]
What version of node are you running?

**Comment by echristiaans** [comment]
```
node --version
v10.23.0
```

had enabled Tidy to try different options, also tried in combination with Abiword - want to make sure I have tried whatever I can first before submitting an issue. Will disable it again to keep things clean

**Comment by echristiaans** [comment]
installed develop branch with no plugins enabled (and no Tidy):

```
[2020-12-22 20:17:16.212] [INFO] console - Your Etherpad version is 1.8.6 (be56750)
```

alas the same problem exists. it tries to rename / move a .html file:

```
Error: ENOENT: no such file or directory, rename '/tmp/upload_2ffcf863ecc6615a63af5f3436f118a4.html' -> '/tmp/etherpad_import_1830510356.html'
```

but afaik the file to be moved should be a .pdf, not a .html. The pdf is there in the /tmp directory.

**Comment by JohnMcLear** [comment]
what happens if you do

``cd src && npm test`` ?

Does your import/export tests pass or fail?

**Comment by echristiaans** [comment]
ok this will take me a while, will try to get the results back as soon as I can. Thanks for your support so far!

**Comment by brunob** [comment]
@echristiaans could you share a pdf that generate the bug in order to let us try to reproduce this one ?

**Comment by echristiaans** [comment]
absolutely, this one I used as an example. Have not been able to run the
tests, sorry.

**Comment by JohnMcLear** [comment]
No file attached...

**Comment by echristiaans** [comment]
[AWS-Security-Pillar.pdf](https://github.com/ether/etherpad-lite/files/5741813/AWS-Security-Pillar.pdf)

**Comment by JohnMcLear** [comment]
![image](https://user-images.githubusercontent.com/220864/103135319-5e491100-46af-11eb-8577-d0bce67f81bf.png)

Imports fine..

**Comment by webzwo0i** [comment]
Please install the libreoffice-draw package that is required for PDF import.

Please note that there currently is a [bug](https://github.com/ether/etherpad-lite/issues/4607), so that PDF files result in unformatted text.

**Comment by echristiaans** [comment]
installing the libreoffice-draw version did not resolve the issue, I do notice I am using a newer version of LibreOffice (6.0.7.3) - will try with version 5.2

**Comment by webzwo0i** [comment]
I'm at 7.0.4 and pretty sure I also tested with 6.1.5

**Comment by echristiaans** [comment]
so I have upgraded to 7.0.4.2:
```
libreoffice --version
LibreOffice 7.0.4.2 00(Build:2)
```

on the cli, the conversion now works, but with accessibility warnings:
```
soffice --headless --convert-to "html:XHTML Draw File" /tmp/upload_06d1a36abaeac2b167bcff3aa6abc5de.pdf
convert /tmp/upload_06d1a36abaeac2b167bcff3aa6abc5de.pdf -> /home/echristi/upload_06d1a36abaeac2b167bcff3aa6abc5de.html using filter : XHTML Draw File
Overwriting: /home/echristi/upload_06d1a36abaeac2b167bcff3aa6abc5de.html

    Accessibility Warning:
         No alternate text ('svg:title' element) set for
         image '
                            '!
```
this works without warnings:
```
soffice --headless --convert-to html /tmp/upload_06d1a36abaeac2b167bcff3aa6abc5de.pdf
convert /tmp/upload_06d1a36abaeac2b167bcff3aa6abc5de.pdf -> /home/echristi/upload_06d1a36abaeac2b167bcff3aa6abc5de.html using filter : draw_html_Export
Overwriting: /home/echristi/upload_06d1a36abaeac2b167bcff3aa6abc5de.html
```
This also works:
```
soffice --headless --convert-to "html:XHTML Writer File:UTF8" upload_06d1a36abaeac2b167bcff3aa6abc5de.pdf
convert /home/echristi/upload_06d1a36abaeac2b167bcff3aa6abc5de.pdf -> /home/echristi/upload_06d1a36abaeac2b167bcff3aa6abc5de.html using filter : XHTML Writer File:UTF8
Overwriting: /home/echristi/upload_06d1a36abaeac2b167bcff3aa6abc5de.html
```

will continue from here, keep you updated.

**Comment by echristiaans** [comment]
ok, it appears we got it working. My colleague dove in deep with some low level straces and found out it is a permissions issue as suspected.

We are running Etherpad under systemd, using the following config:

```
[Unit]
Description=Etherpad-lite, the collaborative editor.
After=syslog.target network.target

[Service]
Type=simple
User=etherpad
**Group=etherpad**
WorkingDirectory=/opt/etherpad
Environment=NODE_ENV=production
ExecStart=/usr/bin/nodejs /opt/etherpad/node_modules/ep_etherpad-lite/node/server.js
Restart=always

[Install]
WantedBy=multi-user.target
```

The conversion works when the `Group=etherpad` setting is removed, effectively having user "etherpad" fall back to the "users" group. 

As to the why, the suspicion is that the convert process is trying to load fonts from the local file system, assumedly as they were specified in the PDF. We think "soffice" is trying to access some shared files, like fonts etc and for whatever reason those files are not accessible by group "etherpad" or user "etherpad", but are accessible by group "users".
