### ISSUE TITLE
Nested OLs can start with 0

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4589]
Just want to get confirmation that this is indeed our wanted behavior:

Type something, make it an OL and press tab several times

If there is no containing OL, than the nested OL will have 0's in the numbering, ie:
`0.0.1` when tab was pressed two times.

I remember a user who was confused by that (can't find the issue atm). Do we want to change that to always start numbering with 1?

**Comment by JohnMcLear** [comment]
IMHO that's the desirable behavior...

**Comment by JohnMcLear** [comment]
Afaik I fixed this no?  @webzwo0i
