### ISSUE TITLE
Javascript is slow to send and problems with the admin interface

### ISSUE THREAD

**Issue by Bischnu** [ether/etherpad-lite#4597]
**Describe the bug**
I installed etherpad-lite a couple of days ago on a Raspberry Pi with a MySQL / MariaDB database and nginx as a reverse proxy. It is on a fiber connection (but this Raspberry is limited to 100 Mb/s which is well enough for this application).
At first it was quite slow to get the homepage, then everything was quite quick as the files are cached in the browser (but when I force a refresh the problem comes back). So I looked what was slowing everything with the developer tools on Firefox  and it was the javascript files (and maybe the stylesheet too), especially the jquery which takes approximately 8 seconds to load just 85 kB. When looking in the Timings tab of the developer tools, all this time is distributed on the “Waiting” step and not on the “Receiving” one.
I tried different things found on the web, changing the “minify” setting, the “maxage”, changing the sendfile_max_chuck in nginx settings, changing the worker_processes, enabling gzip compression for everything, disabling it, and one or two other things. I checked that node is not running as root. Finally, I found someone advising to install the plugin ep_disable_custom_scripts_and_styles and it solved the problem… for one day.
Today javascript is slow again, I did not change etherpad-lite config, and now, in addition to the long waiting time for the javascript files, the “Plugin manager” and the “Settings” pages in the admin interface are broken. There isn't any plugin displayed, neither in the installed ones, nor in the available ones, and the configuration appears empty. Though the “Troubleshooting information” page is OK and displays the plugins (ep_etherpad_lite, ep_hash_auth and ep_disable_custom_scripts_and_styles plugins).

**Server:**
 - OS: Raspberry Pi OS
 - etherpad-lite version: 1.8.6
 - NodeJS version: 14.15.3
 - MariaDB version: 10.3.27
 - nginx version: 1.14.2

**Desktop and smartphone:**
 - Desktop: Manjaro with GNU/Linux 5.9
 - Desktop browser: Mozilla Firefox 83.0
 - Smartphone: LineageOS 17.1 (based on Android 10)
 - Smartphone browser; Fennec (Firefox for F-Droid) 84.1

Edit: I wanted to add that it does this with HTTP 1.1 and HTTP 2

**Comment by JohnMcLear** [comment]
@webzwo0i working on this tomorrow.  But I noticed this too even when browser isn't slow.
