### ISSUE TITLE
PDF import results in unformatted text

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4607]
When importing PDF, all formatting is lost. It works if I using `soffice --headless --convert-to "html:HTML (StarWriter):UTF8"` on the cli and importing the HTML. We're using a special converter for pdf, that got introduced lately with https://github.com/ether/etherpad-lite/issues/4151 so that needs evaluation again

because https://github.com/ether/etherpad-lite/issues/4385 talks a lot about other special case bugs, I made it a separate issue

**Comment by webzwo0i** [comment]
I'm trying to import a pdf version 1.6. we should also check if other versions are effected

**Comment by JohnMcLear** [comment]
@webzwo0i I assigned this to you but if you don't want to work on it just unassign yourself :)  I assume you are working on it as part of a larger project.
