### ISSUE TITLE
hot to debug a etherpad plugin's script in static folder in browser?

### ISSUE THREAD

**Issue by NoTalk-ly** [ether/etherpad-lite#4626]
I found that plugins script in static folder is loaded in browser and loaded by xhr. In this case, I can not add a breakpoint in browser to debug plugins, even debugger statement can not trigger.

this problem effect my development efficiency very much?
anybody can help me how to debug a etherpad plugin's static script(that means script run in browser)?
as a junior developer，I am very glad to develop plugin for etherpad， but this problem bothered me a few days.

**Comment by JohnMcLear** [comment]
Please provide link to your plugin repo so we can see what you are doing.

**Comment by NoTalk-ly** [comment]
> Please provide link to your plugin repo so we can see what you are doing.

sorry, I am developing and don't create a repo.

I just want to know as a static script loaded by xhr request which content like this

![image](https://user-images.githubusercontent.com/30374176/103407234-d8d6cc80-4b98-11eb-9eea-9009087a4e28.png)

and run with eval ( I guess).  how can I debug more effectivly.

**Comment by JohnMcLear** [comment]
So our general rule is that if you want help, you should have some way we can see what you are doing right/wrong..  So please create a repo and upload your logic so we can replicate your problem locally and provide suggestions to improve.  You can upload an MVP example and that's even ideal..

Tbh tho, I usually use console to debug, I use debugger sometimes in core but I still prefer console to avoid having to "step".

**Comment by JohnMcLear** [comment]
Please don't leave stale issues @NoTalk-ly
