### ISSUE TITLE
comment on selection issue with overlapsing comments in same line

### ISSUE THREAD

**Issue by hollisticated-horse** [ether/etherpad-lite#4627]
Bug: 

when there multiple comments on selection in the same line, it isn't possible to select which comment to interact with, whether to accept change or respond

**To Reproduce**
1. create a pad
2. make two comments on selection in the same line of any text
3. if you you try to go and accept the change/ try to select on of them (maybe as a different user)
4. you'll see that either they overlaps, in which case you need to get rid of the first one, or one of them doesn't get displayed

**Expected behavior**
[maybe feature dunno] to be able to access comments on selection on the right side of the text;
 to show all comments if there are more then comments on selection
easy selection of which comment to interact

**Screenshots**
![2021-01-03_19h07m34s_fs](https://user-images.githubusercontent.com/76632257/103485544-5a2b9a80-4df7-11eb-941a-93100dfeaee4.png)

![2021-01-03_19h06m53s_fs](https://user-images.githubusercontent.com/76632257/103485548-5dbf2180-4df7-11eb-8150-46d595e8b6cc.png)

**Desktop (please complete the following information):**
 - OS: Linux OS flavor, using aptitude package for Firefox and chromium
 - Browser  Firefox and chromium
 - Version latest at time of writing

**Smartphone (please complete the following information):**
 NA

**Additional context**
collaborative text writing

**Comment by webzwo0i** [comment]
thanks for the bug report. Because I think this is an issue with the comments plugin and we try to keep plugin issues separated, I'm going to close this here.
I opened a bug report on https://github.com/ether/ep_comments_page/issues/181
