### ISSUE TITLE
Bad contrast of icons in bottom line of halved window with dark background

### ISSUE THREAD

**Issue by Oremountainflorian** [ether/etherpad-lite#4632]
**Description**
With background set in dark grey, it's not possible to see the icons (users, settings, ...) in the bottom line when the browser window is halved because of the really bad contrast. Why? In the bottom line the background color isn't set. 

**To Reproduce**
1. Open a pad with dark background. On the right in the top line you can see the normal icons.
![grafik](https://user-images.githubusercontent.com/44228345/103705295-16799200-4fab-11eb-889c-b3b472237944.png)
2. Halve the browser window in which the pad is opened. 
3. Those icons can't be found in the top line anymore (intended behaviour). Now they should be displayed in the bottom line, but there the contrast is bad because the background color isn't adjusted. 

**Expected behavior**
You can see the setting icon, export, ... icons in the bottom line with good contrast when the background color is set as it is in the top icon line. 

**Screenshot**

![grafik](https://user-images.githubusercontent.com/44228345/103706127-9f44fd80-4fac-11eb-9539-96c38c142a3c.png)

**Desktop (please complete the following information):**
 - OS: WIndows 8.1
 - Browser: Mozilla Firefox 84.0.1
 - Screen resolution: 1360x768

**Further comments**
Also the line numbers are missing in halved mode, but I guess this is intended behaviour. 

Anyways, great work what all of you have accomplished in respect of the pads optical appeareance during the latest version updates! Many thanks for your work! Keep on going!

**Comment by JohnMcLear** [comment]
lol wtf :D @seballot - I haven't confirmed.  

![image](https://user-images.githubusercontent.com/220864/103747324-5f0c6c00-4ffa-11eb-8a38-8c1ce15a1218.png)

I can't duplicate using the skinVariantBuilder FWIW

I will see if I can replicate by changing settings.

**Comment by JohnMcLear** [comment]
![image](https://user-images.githubusercontent.com/220864/103747576-cb876b00-4ffa-11eb-8a7d-df721d7e43fc.png)

unable to replicate using settings.json

**Comment by Oremountainflorian** [comment]
Sorry for the inconveniences, we missed to update our skin folder during the last etherpad update... Our fault. Solved
