### ISSUE TITLE
provide a docker-compose.yml example along the docker example

### ISSUE THREAD

**Issue by datenheim** [ether/etherpad-lite#4634]
* * *
title: 'provide a docker-compose example along the docker example'
labels: "Feature request", "Easy to solve"
* * *

**Is your feature request related to a problem? Please describe.**
Not a problem, but would be helpful if a complete docker-compose.yml is provided either alongside the existing docker example in  [doc/docker.md](doc/docker.md) or in a separate document.

**Describe the solution you'd like**
A decent docker-compose file showing available database options and maybe also how to upgrade or install plugins working with the default image available on https://hub.docker.com/r/etherpad/etherpad.

As a starting point it could look similar to https://github.com/uni-halle/etherpad-lite-docker.

**Comment by Gared** [comment]
Where should be publish this docker-compose file? Should we add it to the wiki, this project or maybe a new project? @SamTV12345

**Comment by SamTV12345** [comment]
@Gared I'd suggest adding a docker compose with all the relevant options on Dockerhub in the Readme. I normally always go to DockerHub and check if that contains a docker-compose which I can use as a starting point.
