### ISSUE TITLE
Scroll viewport when pressing enter on the last line of viewport

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4636]
If the caret is on the last line that's visible in the viewport, pressing enter won't move the viewport one line down. If you press enter two times, then the viewport moves one line.

**Comment by JohnMcLear** [comment]
Does the caret ever become non visible?

**Comment by JohnMcLear** [comment]
Caused by https://github.com/ether/etherpad-lite/commit/7aa7e02e273c66936516f1ba87f435e4fe206c75#diff-48a27c7f5ec73d98c4c3883a313f2d8218a687bfff92edb5654a404da91d4f06L315

Test coverage available in PR, still working on a fix.

cc @seballot

**Comment by JohnMcLear** [comment]
FWIW we found that caret is not hidden if dev tools are open =)

**Comment by JohnMcLear** [comment]
modifying ``pad-variants.css``
```
@media (min-width: 1001px) {
  .super-light-editor.super-light-background,
  .light-editor.light-background,
  .super-dark-editor.super-dark-background,
  .dark-editor.dark-background {
    --editor-horizontal-padding: 20px;
    --editor-vertical-padding: 25px;
  }
}
```
breaks things which points me towards a CSS issue, but it could be that something is trying to draw the editor down to the line and getting line height but disregarding padding

**Comment by JohnMcLear** [comment]
I took a look and boiled it down to ``scrollYPageWithoutAnimation`` that when I call manually only works if the line has a character in.  *boggles.

**Comment by JohnMcLear** [comment]
I found that doing
```
    } else if (caretIsBelowOfViewport) {
      setTimeout(function(){
        const outer = window.parent;
        top.console.log(outer.outerHeight);
        outer.scrollTo(0,outer[0].innerHeight)
      }, 150);
    }
```

works, might be not ideal but a patch to keep things moving forward..   Will make some changes later and push that for testing..
