### ISSUE TITLE
Stuck at "loading"

### ISSUE THREAD

**Issue by noppelmax** [ether/etherpad-lite#4637]
**Describe the bug**
I installed the latest master version. After the creation of a new page the editor is not loaded. The Icon Bar on the top is shown, but where the editor should be, is just a big "Loading" sign.

**To Reproduce**

- Update to master
- Create new page

**Expected behavior**
Showing the normal editor screen

**Screenshots**
![screeny](https://user-images.githubusercontent.com/7629938/104000775-0924f900-519f-11eb-8a41-326bf2159339.png)

**Desktop (please complete the following information):**
 - Device: Thinkpad T490
 - OS: Ubuntu 20.04
 - Browser Google Chrome
 - Version Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
I executed `bin/run.sh` and I use no special db. This is the console trace:
```
[2021-01-08 10:42:36.181] [INFO] Minify - Compress CSS file css/pad.css.
[2021-01-08 10:42:36.185] [INFO] Minify - Compress CSS file skins/colibris/pad.css.
[2021-01-08 10:42:36.958] [INFO] Minify - Compress JS file js/require-kernel.js.
[2021-01-08 10:42:37.239] [INFO] Minify - Compress JS file js/l10n.js.
[2021-01-08 10:42:37.278] [INFO] Minify - Compress JS file js/html10n.js.
[2021-01-08 10:42:38.275] [INFO] Minify - Compress JS file skins/colibris/pad.js.
[2021-01-08 10:42:39.058] [INFO] access - [CREATE] pad:bericht socket:x9UCauFatcPlP-CMAAAB IP:xx.xx.xx.xx authorID:a.P9eKvYqsFqxN16Cu
```

It also tried with different document names. 

Kind regards,
nopx

**Comment by JohnMcLear** [comment]
Tried clearing browser cache?

**Comment by sonikanishk** [comment]
![image](https://user-images.githubusercontent.com/58775605/104067135-9d876e00-5228-11eb-878c-12e589fb13c3.png)

![image](https://user-images.githubusercontent.com/58775605/104067573-64033280-5229-11eb-9448-f58e24105e29.png)

Hi John I'm facing the exact same issue
Plugins Installed:
1) ep_aa_file_menu_toolbar
2) ep_align
3) ep_comments_page
4) ep_copy_paste_images
5) ep_copy_paste_select_all
6) ep_font_color
7) ep_font_size
8) ep_headings2
9) ep_print
10) ep_set_title_on_pad
11) ep_table_of_contents
12) ep_who_did_what

**Comment by JohnMcLear** [comment]
As per issue docs, please test without plugins installed....

**Comment by sonikanishk** [comment]
After uninstalling all the plugins it came back to default state. Thank you!

**Comment by noppelmax** [comment]
Nop, I got no plugins installed. I looked it up in <link>/admin/plugins. I therefore activated the User und Admin account in the `settings.json` file. Now it is working for some reason... Maybe this is a requirement? You may note this in the installation description.

Thanks a lot for developing Etherpad!!! 

Kind regards,
nopx

**Comment by webzwo0i** [comment]
User accounts are no requirement. The default setting for Cache-Control max age is 6 hours. We have a solution for stale resources in place (attaching a random version string to the request) but unfortunately two resources don't get loaded with the random version string. This is described in https://github.com/ether/etherpad-lite/issues/4443  Not sure if this will be fixed in time though, because we want to switch to packaging with webpack in the near future, which should circumvent this kind of problems in the future anyway.
