### ISSUE TITLE
Unable to upload images through the api (sethtml)

### ISSUE THREAD

**Issue by woeterman94** [ether/etherpad-lite#4638]
Tried adding a collectContentImage hook in a plugin to support adding image tags through the etherpad api.

```
exports.collectContentImage = (name, context) => {
  const tname = context.tname;
  const state = context.state;
  const lineAttributes = state.lineAttributes;
  if (tname === 'div' || tname === 'p') {
    delete lineAttributes.img;
    delete lineAttributes.imgSize;
  }
  if (tname === 'img') {
    lineAttributes.img = `<img src='${context.node.attribs.src}'>  `;
  }
};
```

![image](https://user-images.githubusercontent.com/5755057/104010975-a71fc000-51ad-11eb-80ed-2041d3151a9f.png)
For some reason this line always removes the "img" line attribute
https://github.com/ether/etherpad-lite/blob/fd3004faadca9586566b7904580037bb33759747/src/static/js/contentcollector.js#L426

![image](https://user-images.githubusercontent.com/5755057/104011198-067dd000-51ae-11eb-97fc-d39f942c4e24.png)

Anyone know why that line is there? Is there a workaround. 

My plugin code if anyone wants to take a look: https://github.com/woeterman94/ep_copy_paste_images/commits/feature/import-images

**Comment by woeterman94** [comment]
If I comment out the line images give weird behaviors. For example: I can't delete an image anymore: using the delete button just adds more images:
![ezgif-2-855f53bf39b1](https://user-images.githubusercontent.com/5755057/104011840-0fbb6c80-51af-11eb-9e63-46c467665650.gif)

**Comment by JohnMcLear** [comment]
Confirmed, I wouldn't describe this as a core bug but we probably need this bit looking at

https://github.com/ether/etherpad-lite/blob/develop/src/static/js/contentcollector.js#L415

In general

Etherpad should always delete Images
Plugins should be able to stop etherpad deleting images

I think the if/else in the above code is not ideal, instead we should check what blockelements are registered and only support those, dropping everything else.

**Comment by JohnMcLear** [comment]
I think the issue is caused by a missing / incorrect ``else if`` in ``contentcollector.js``

https://github.com/ether/etherpad-lite/commit/e39e959347e041a6bf89bfb95d15428094dcee40#diff-eb5bdca212827982d62b0f8dd98abf2de79c54005f337091c7e3f1edf86293caR428

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/pull/4647 contains a fix.
I also made a core example: https://github.com/ether/etherpad-lite/pull/4646 to refer to making changes in plugins.

**Comment by JohnMcLear** [comment]
This is working now afaik w/ ep_upload_image
