### ISSUE TITLE
Functions that depend on setSub / getSub will silently fail to write to the database.

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4645]
https://github.com/ether/ueberDB/issues/176

Will affect group pads & author info(s) causing no data to be stored, as such I'm flagging as serious.

**Comment by rhansen** [comment]
What are the symptoms? UeberDB's `setSub()` and `getSub()` functions seem to be working OK according to new tests I just added to ueberDB's unit tests.

**Comment by rhansen** [comment]
https://github.com/ether/etherpad-lite/runs/1680196224 shows backend tests working OK (except for the import/export tests which have been chronically failing for a while now).

**Comment by JohnMcLear** [comment]
Change the user color in a pad, hit refresh, color wont have been saved to database (dirtydb was tested).

This used to work 👍

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/runs/1749635883?check_suite_focus=true#step:7:211

We're consistently reproducing on the frontend tests :?
