### ISSUE TITLE
Trobule Installing Etherpad Lite

### ISSUE THREAD

**Issue by tobidwest** [ether/etherpad-lite#4650]
Hi there, when running the run.sh file I'm getting a message that node.js is not installed. I did install it but as I'm new to node and Etherpad I wasn't sure what path to install it to. Might this be the reason for the error? Where does Etherpad search for node.js?

**Comment by JohnMcLear** [comment]
Type ``which node`` - I suggest trying to install from nodesource if you are still stuck :)

https://github.com/nodesource/distributions
