### ISSUE TITLE
Host Ether Instance on Azure

### ISSUE THREAD

**Issue by Daviid1010** [ether/etherpad-lite#4651]
Hi all!

I'm new to etherpad and using it in development if anyone can help!

I have an application requirement to host Etherpad on Azure. So this would mean  I need to access it embedded in an iframe from another app for example
azureapp.myetherapp.com/pad1 to access pad name pad1

I understand how to build Etherpad locally and access a pad in an iframe its hosting it online which I find challenging. I can't use an IP address like most guides say on etherpad but I need mine to come from Azure. Is there a way to do this perhaps but hosting a web app.

Any help would be greatly appreciated!

**Comment by rhansen** [comment]
@alexeisenhart has been working on getting Etherpad working on Azure. See #4800 for progress.
