### ISSUE TITLE
Question: Group Pads

### ISSUE THREAD

**Issue by disco-panda** [ether/etherpad-lite#4652]
Hello there, 

I have been looking through the documentation today and am trying to understand the benefit of using a group pad (with sessions, authors, etc) vs just creating a normal pad and sharing it to other users? 

Am I correct in assuming that if I create a normal pad, any authenticated user will be able to see it whereas a group pad provides a level of access control to pads?

Thank you!

**Comment by rhansen** [comment]
With group pads you implement your own access controls via the HTTP API. Normal pads are open to everyone by default, but you can control access to normal pads with authentication and authorization plugins.
