### ISSUE TITLE
Postpone installation of some optional dependencies?

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4662]
This is something between feature request and question.

Etherpad installs some dependencies that might not be used during runtime. ie if I want to use mysql, it will still install dependencies for postgres, if I don't use minify, it will install terser or if I don't want to import HTML documents, it will install rehype.

Especially the sqlite fix in ueberDB slows down "normal" installation, because it compiles stuff.

There is a npm flag `--no-optional` that only works when there is no package-lock.json, so we can't use that right away.

I'm not sure if this is worth the effort, but can we check settings.json on startup to find out what options the instance wants to use and decide if some of the packages can be skipped or need to be installed, because they are missing?

This would introduce some unexpected behavior, e.g. when I want to start a program, I don't expect it to install packages... But is there some alternative you can think of?

**Comment by JohnMcLear** [comment]
afaik sqlite got moved to an optional anyway to remove this problem?  I agree things are hella slow tho ;/  Especially when you have a raspberry pi as a build environment like I do when I'm overseas ;\

**Comment by webzwo0i** [comment]
right, not sure what I did wrong yesterday, but `npm i --no-optional` in ./src does not install sqlite3.

If we default to put more optional dependencies in, e.g. for other database packages, can you think of a good way to inform the user? IE on startup, after parsing settings.json, determine what packages are missing for the settings to work? We have npm installed anyway, so we could install it on demand? If there is a way, then we can default to `npm i --no-optional` in ./bin/installDeps.sh easily
