### ISSUE TITLE
Trying to get a mysql docker container to communicate with the etherpad docker over a network

### ISSUE THREAD

**Issue by DDraeger1** [ether/etherpad-lite#4665]
Hello! I've been trying to connect a mysql docker container and an etherpad container through a bridge network. But I allways get this error: 

etherpad_1  | [2021-01-21 14:55:56.628] [ERROR] console - ERROR: Problem while initalizing the database
etherpad_1  | [2021-01-21 14:55:56.628] [ERROR] console - Error: connect ECONNREFUSED 172.20.0.3:16
etherpad_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
etherpad_1  |     --------------------
etherpad_1  |     at Protocol._enqueue (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:144:48)
etherpad_1  |     at Protocol.handshake (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:51:23)
etherpad_1  |     at Connection.connect (/opt/etherpad-lite/src/node_modules/mysql/lib/Connection.js:116:18)
etherpad_1  |     at Connection._implyConnect (/opt/etherpad-lite/src/node_modules/mysql/lib/Connection.js:454:10)
etherpad_1  |     at Connection.query (/opt/etherpad-lite/src/node_modules/mysql/lib/Connection.js:196:8)
etherpad_1  |     at exports.database.init (/opt/etherpad-lite/src/node_modules/ueberdb2/databases/mysql_db.js:81:6)
etherpad_1  |     at exports.database.init (/opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:115:18)
etherpad_1  |     at exports.database.init (/opt/etherpad-lite/src/node_modules/ueberdb2/index.js:49:13)
etherpad_1  |     at Promise (/opt/etherpad-lite/src/node/db/DB.js:43:6)
etherpad_1  |     at new Promise (<anonymous>)
etherpad-lite_etherpad_1 exited with code 1

Here are both of the docker-compose.yml and the settings.json 

Mysql docker:

`version: '3'

services:

  mysql-docker:
    image: mysql/mysql-server:latest
    
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: etherpaddb
      MYSQL_USER: etherpad
      MYSQL_PASSWORD: changeme
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql-docker
    ports:
      - "8080:8080"

networks: 
  default:
    external:
      name: mysql_default
`

Etherpad:
`
version: '3'

services:
  etherpad:
    build:
      context: .
    ports:
      - 9001:9001

networks: 
  default:
    external:
      name: mysql_default
`

settings.json
`
  "dbType" : "mysql",
  "dbSettings" : {
    "user"    : "etherpad",
    "host"    : "172.20.0.3",
    "port"    : 16,
    "password": "change",
    "database": "etherpaddb",
    "charset" : "utf8mb4"
  },
`

I got the Ip of the mysql database from "docker inspect" command

`        "Containers": {
            "56c7567c15627247a9da6879469056bff631809c286a63737db21484a03c52f7": {
                "Name": "mysql_mysql-docker_1",
                "EndpointID": "004b75dfc1ef4a7c1499fc1ec49d2e775c0d6350715d13720289dc231c00c243",
                "MacAddress": "02:42:ac:14:00:03",
                "IPv4Address": "172.20.0.3/16",
                "IPv6Address": ""
            },
`

Any help would be appreciated! Im pretty new to docker. 
I know this would be way easier having everything in 1 docker-compose but my boss wanted me to have this in 2 different dockerfiles

**Comment by n-goncalves** [comment]
This error appeared cause etherpad is trying to connect to the database at port 16 as is defined in your settings.json and you've configured your mysql image to use port 3306. Changing that should fix the current error.

But that wouldn't be the end of it. If you try to just change that, you'd get another error: ER_NOT_SUPPORTED_AUTH_MODE which appears because the mysql container default authentification method changed since 8.0 and I guess etherpad doesn't support it. 
You need to add a command to change that in the docker-compose file that defines the mysql service 
` command: --default-authentication-plugin=mysql_native_password` or you could go back to mysql 5.7. 

Last instead of using the IP given by the docker network,  you can use their name instead, so `172.20.0.3` would become `mysql-docker` in settings.json (or in the environment variables of etherpad). Doing it your way works, but if you give your file to someone else or destroy your network by mistake, there's no way to know if docker will create a network with the same IP. 
 
Hope this helps.

**Comment by Sbeajy** [comment]
It works like a charm. I cant thank you enough. I´ve been on this for a week. I had no prior experience to docker before but me boss wanted me to do this. You saved me from another tiresome week of trying the same thing again and again. Thank you!

> This error appeared cause etherpad is trying to connect to the database at port 16 as is defined in your settings.json and you've configured your mysql image to use port 3306. Changing that should fix the current error.
> 
> But that wouldn't be the end of it. If you try to just change that, you'd get another error: ER_NOT_SUPPORTED_AUTH_MODE which appears because the mysql container default authentification method changed since 8.0 and I guess etherpad doesn't support it.
> You need to add a command to change that in the docker-compose file that defines the mysql service
> ` command: --default-authentication-plugin=mysql_native_password` or you could go back to mysql 5.7.
> 
> Last instead of using the IP given by the docker network, you can use their name instead, so `172.20.0.3` would become `mysql-docker` in settings.json (or in the environment variables of etherpad). Doing it your way works, but if you give your file to someone else or destroy your network by mistake, there's no way to know if docker will create a network with the same IP.
> 
> Hope this helps.
