### ISSUE TITLE
Installed plugins via cli do not appear after server restart via /admin/settings

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4678]
Install a plugin via `npm i` in the main directory
Go to /admin/settings and click restart server
Plugin will never appear in /admin/plugins

As soon as you install (another) plugin via /admin/plugins, all plugins will appear in /admin/plugins.

The bug is probably that clicking restart not triggers the logic to load all available plugins

**Comment by JohnMcLear** [comment]
Confirmed.

cc @rhansen
