### ISSUE TITLE
Error in deleteGroup

### ISSUE THREAD

**Issue by t-schroeder** [ether/etherpad-lite#4689]
**Describe the bug**
We see an error in the log.

**To Reproduce**
Not reproducible. We use Etherpad Lite through its [Moodle plugin](https://github.com/moodlehu/moodle-mod_etherpadlite).

**Expected behavior**
No errors.

**Screenshots**
```
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at Object.exports.deleteGroup (/var/etherpad-lite/src/node/db/GroupManager.js:56:28)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Desktop (please complete the following information):**
don't know

**Smartphone (please complete the following information):**
don't know

**Additional context**
We had one user earlier that day receive an error trying to use Etherpad Lite in Moodle. Not sure if this is related. She couldn't tell us what error she got and now it's working for her ...

**Comment by JohnMcLear** [comment]
Did you test against develop?  We have test coverage in for this as a pr @webzwo0i is due to merge

**Comment by t-schroeder** [comment]
No, we only observed this on our production system. This is the version we are using:

```
Etherpad version
Version number: 1.8.4
Git sha: 6a0f73d

Installed plugins
ep_adminpads2
ep_etherpad-lite
ep_headings2
ep_what_have_i_missed
ep_tables4
ep_who_did_what
ep_author_hover
```

**Comment by JohnMcLear** [comment]
Plz update

**Comment by JohnMcLear** [comment]
Closing as it was probably due to old instance.
