### ISSUE TITLE
Clicking restart in admin/settings hangs Etherpad

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4702]
Etherpad never comes back up

```
[2021-02-02 19:26:57.396] [INFO] http - Closing HTTP server...
```

No further things happen until all sockets are disconnected / browser is closed.

**Comment by rhansen** [comment]
HTTP connections are not all closing. Can you sleep a few seconds then get a wtfnode dump?

**Comment by rhansen** [comment]
Looks like the socket.io connections are no longer being terminated.

**Comment by JohnMcLear** [comment]
If I close the browser window it goes from

```
[2021-02-03 11:44:36.007] [INFO] http - Closing HTTP server...
```
to
```
[2021-02-03 11:45:14.960] [INFO] http - HTTP server closed
```

but then nothing in logs yet http is served.

the same UX between current develop and socket.io@2.3.0
