### ISSUE TITLE
Background color changes from to dark to light after reconnect

### ISSUE THREAD

**Issue by Oremountainflorian** [ether/etherpad-lite#4715]
**Description**
By default, our pads background is set to dark. After a short disconnect followed by a reconnect, the pad continues working without refreshing since the last etherpad update (which is quite cool, thankyou!). But after the reconnect, the background isn't dark anymore but rather becomes light. Also the line numbers become then invisble as their color is set to light in dark mode. 

**Steps to reproduce the behavior**
- open pad with dark background. 
- wait for a short disconnect or force it
- background turned to light

**Expected behavior**
Background stays dark after reconnect. 

**Screenshots**
Before disconnect
![grafik](https://user-images.githubusercontent.com/44228345/107113440-3d9fd980-685f-11eb-8218-36f1863b190d.png)

After reconnect
![grafik](https://user-images.githubusercontent.com/44228345/107113413-18ab6680-685f-11eb-8ba7-5b965a51a61b.png)

**Desktop**
- OS: Windows 8.1
- Browser: Mozilla Firefox 85.0.1 / Chrome 88
- Etherpad Version 1.8.7
- Installed Plugins: Headings 2, Hover, Font Color, Table of Contents, Align, Comments

Anyways, great work what all of you have accomplished in respect of the pads optical appeareance during the latest version updates! Many thanks for your work! Keep on going!

**Comment by JohnMcLear** [comment]
Will sort asap thanks for the bump

**Comment by JohnMcLear** [comment]
Fixed in #4716
