### ISSUE TITLE
pads do not load

### ISSUE THREAD

**Issue by jonnymauser76** [ether/etherpad-lite#4727]
Hi there,

**Describe the bug**
After installing an instance of etherpad 1.8.7. via docker running on Debian 9 new pads won't show up. Formating Buttons can be seen. Page says "loading". No additional plugins where used, database is mariadb, connection is working

**Additional context**
While trying to fix it, I have read ( I guess it was in a closed issue) that reverting to 1.7.5. solved the problem. In this threat there was also mentioned that the described error points to a regression which was explained there in detail by comparing a few lines of code from 1.8.7. and 1.75. After setting up some testing instance of Version 1.7.5 which actually worked quite well, I decided to try to go back to 1.8.7 and try to fix the error by modifying the container. Unfortunately I was unable to locate the mentioned threat (went through my hole browser history but, did not find it again... I know that sounds crazy)

Maybe someone knows the threat I am talking about and can point me in the right direction. Would be really helpful.
thanks in advance

**Comment by JohnMcLear** [comment]
Please try latest develop branch.  It had 1.8.8 in.

**Comment by jonnymauser76** [comment]
Hi John,
thanks for your quick reply, works perfect now.
