### ISSUE TITLE
Embed Headings plugin to default EtherPad install

### ISSUE THREAD

**Issue by ZDVokoun** [ether/etherpad-lite#4730]
* * *

name: Feature request
about: Suggest an idea for this project
title: ''
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
Lots of public instances of EtherPad don't have the headings plugin installed, although heading are used in majority of documents. This can be a problem for someone, including me.

**Describe the solution you'd like**
Either build headings plugin into EtherPad or automatically install headings plugin on install.

**Describe alternatives you've considered**
Contact admins of public instances and ask them to install the plugin.

**Additional context**

**Plugin?**

**Comment by JohnMcLear** [comment]
This isn't really a suitable place for this issue.  A better place would be core etherpad.

**Comment by JohnMcLear** [comment]
Ready for review/testing.
