### ISSUE TITLE
Consider hidden lines during sidediv update

### ISSUE THREAD

**Issue by ingoncalves** [ether/etherpad-lite#4764]
**Describe the bug**

The `updateLineNumbers` function is called to calculate the size of each line after editing/removing a text and updates its respective line-height on the `#sidediv` container. The problem happens when we have a scenario where it is possible to have lines with zero height. An example would be a plugin that allows toggling the visualization of lines created by a specific author, hiding all other lines from other authors. In this scenario, the line height within `#sidediv` is not updated properly. See the code below:

https://github.com/ether/etherpad-lite/blob/73d31b12a868fbc4c478c4a2d3ed7230d178df55/src/static/js/ace2_inner.js#L3860-L3866

The `if(lineHeights[currentLine])` condition is only true for height ​​greater than zero. However, hidden lines would have 0 height, which would not satisfy the `if` condition and therefore not update its height in `#sidediv`.

To help the understanding, the image below shows the line number on the left side and the `#sidediv` HTML code on the right side.

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/5985312/107818487-73a8f600-6d56-11eb-870a-378e3cbc2548.png">

**Comment by JohnMcLear** [comment]
How would the caret behave around lines with 0 height?  Does it enter the line?  Does it enter the line then exit it in the correct position?  Do you have a plugin I can clone to see what the behavior is?  I ask all these because I imagine just ignoring the sidediv line numbering is only one small part of the problem and the approach to setting height to 0 or hiding the div might not be ideal.

**Comment by ingoncalves** [comment]
> How would the caret behave around lines with 0 height? Does it enter the line? Does it enter the line then exit it in the correct position?

The caret skips the line with 0 height. It's like these lines are not in the text.

> Do you have a plugin I can clone to see what the behavior is?

Unfortunately, we have a private plugin within our infrastructure that depends on many other plugins. We've recorded a video capturing this behavior:
 
![Kapture 2021-02-12 at 17 40 19](https://user-images.githubusercontent.com/5985312/107820335-66413b00-6d59-11eb-9bab-3f1485c5247f.gif)

**Comment by ingoncalves** [comment]
> I ask all these because I imagine just ignoring the sidediv line numbering is only one small part of the problem and the approach to setting height to 0 or hiding the div might not be ideal.

Actually, we do not set the height to 0. We only allow that lines with zero height to be properly calculated. Otherwise, their previous height value would be used wrongly.

> hiding the div might not be ideal

Hiding lines is required in some features that we have.

**Comment by rhansen** [comment]
Fixed in commit 3ff244f7a046af0916d6cdc4186a4fc4602741ad.
