### ISSUE TITLE
Import allow filetype that that etherpad can't handle

### ISSUE THREAD

**Issue by brunob** [ether/etherpad-lite#4795]
**Describe the bug**

Import allow user to upload file types that etherpad can't handle and can lead to breakage of pad content.

**To Reproduce**

Click on import icon, select a png file and import it in your pad => you get the "source code" of your png file and it if it's a big file it can generate so many revisions that the pad is broken. 

**Expected behavior**

Import should restrict upload (or at least import action after upload) only if the uploaded file could be handled by the etherpad instance (and its settings).

**Additional context**

Tested on pad.infini.fr which runs on latest 1.8.7 version of etherpad.

**Comment by JohnMcLear** [comment]
Please test against latest develop and if it's still an issue let us know.

**Comment by brunob** [comment]
@JohnMcLear thx for the info, and sorry for the noise. I've tested the import of a png file and it's not imported anymore and result in an error `Import failed: The upload failed, please try again`.

**Comment by JohnMcLear** [comment]
Did you look in settings.json?  

```
  /*
   * Allow import of file types other than the supported ones:
   * txt, doc, docx, rtf, odt, html & htm
   */
  "allowUnknownFileEnds": true,
```

set this to ``false``?

**Comment by brunob** [comment]
nice, thx for the hint :)
