### ISSUE TITLE
Regression: Version 1.8.8 doesn't run with Phusion Passenger

### ISSUE THREAD

**Issue by dliw** [ether/etherpad-lite#4809]
**Describe the bug**

Contrary to what has been claimed in issues #3535 and #4540, Etherpad worked fine in Plesk in Phusion Passenger up to version 1.8.7. All you had to do was create a (minimal) `app.js` that starts the server.

This is no longer the case since fc9f2369779a93594b19681eb848cd3f85c2175a as npm (apparently) cannot be executed in Plesk / Phusion Passenger:
```
[ERROR] npm - /usr/bin/env: »node“: No such file or directory
[ERROR] runNpm - Failed to get npm version: Error: Command exited non-zero: npm --version
```

**To Reproduce**
Run Etherpad using Phusion Passenger if npm is not available. 

**Expected behavior**
Etherpad can be executed.

**Screenshots**
The following settings used to work, but no longer work (changes in the folder structure are taken into account):
![Etherpad-in-Plesk](https://user-images.githubusercontent.com/800832/108254459-53fd3d80-715b-11eb-8760-2feba645e34a.png)

`app.js` looks like this:
```
#!/usr/bin/env node

'use strict';

const server = require('./server');

server.start();
```

**Comment by JohnMcLear** [comment]
Does phusion run on windows or something?  If so, we know about a deployment/pathing issue on windows that we're working to resolve :)

**Comment by JohnMcLear** [comment]
Just a heads up btw, Etherpad moved it's main run scripts from ``/bin/`` to ``/src/bin/`` - but we put symlinks in.  Other than that, I am not sure what would break for you guys.

**Comment by dliw** [comment]
No, as far as I know, Plesk runs on Linux using Phusion Passenger in combination with Nginx for Node.js applications.

According to the Etherpad wiki this setup is supported:
https://github.com/ether/etherpad-lite/wiki/Running-Etherpad-on-Phusion-Passenger

I think the problem is that Passenger doesn't allow you to run binaries or it doesn't have access to npm. This has obviously not been a problem so far.

**Comment by JohnMcLear** [comment]
> According to the Etherpad wiki this setup is supported:
https://github.com/ether/etherpad-lite/wiki/Running-Etherpad-on-Phusion-Passenger
Just a heads up, The Etherpad foundation doesn't maintain that page, someone from the Phusion community does 🖌️ 

Is there a way to give Etherpad access to ``npm`` within Phusion?

**Comment by dliw** [comment]
Plesk is a management tool for shared hosting. I don't know if a server provider could allow npm, mine at least does not.

**Comment by JohnMcLear** [comment]
If they allow access to ``node``, IDK why why wouldn't allow access to ``npm``?   I think someone from the plesk community needs to champion this as it's not something I'm going to be spending time on.

**Comment by dliw** [comment]
There is also no direct access to node. You can only configure the entry point of the app and provide a ``package.json``. It is a very restricted environment. Nevertheless, Etherpad has worked very well for me so far. If npm now becomes mandatory, I will have to stay on the old version and sooner or later shut down my instance.
Anyway, thanks for the quick feedback.

**Comment by dliw** [comment]
Are the calls to npm essential? The version check could be disabled. Is there was a way to deploy Etherpad as a static app that doesn't need npm, that would be good enough.So far this has been the case.

**Comment by JohnMcLear** [comment]
``npm`` is used for plugin management and I think some internals might be loaded through ``npm`` too...

It was a change made within ``npm`` 7 that required us to use the ``npm`` binary instead of the internal ``npm`` API.

It's probably for the best tbh, there are lots of ways to deploy/containerize Etherpad, I think this is one of the cases where Etherpad's requirements have outgrown the containers capabilities, I'd be very happy to be proven wrong tho :)

**Comment by rhansen** [comment]
npm is used for plugin discovery and to install or unnstall plugins via `/admin/plugins`. Etherpad itself is implemented as a plugin, so it is currently essential.

https://github.com/ether/etherpad-lite/commit/fc9f2369779a93594b19681eb848cd3f85c2175a is the commit that broke things for you. That commit removed an old and buggy reimplementation of npm's internals and replaced it with execing the npm binary. Unfortunately, it is not practical to revert that commit.

A possible solution would be a new setting that contains a list of installed plugins. If that setting is set we would skip plugin discovery, or at least make plugin discovery failure a non-fatal error. You would have to update that setting every time you add or remove a plugin, but it's better than nothing. Patches welcome. :slightly_smiling_face:
