### ISSUE TITLE
Dealing with stale plugins

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4824]
- [x] Make repository a requirement of being visible in static.etherpad.org and the admin plugin framework.
- [x] Tell plugin admins to deprecate their plugins if they want to kill them off.
- [ ] Write updateThirdPartyPlugins.js which will do the same as updateCorePlugins.sh but for all plugins..    Note that I will 
need to fork the repository, make changes on my local branch then send a PR w/ the changes.
- [x] Don't show plugins from either interface that haven't been updated for 1000 days. <-- Stefan doing this.
- [x] Don't show plugins from either interface that haven't got a repository listed. <-- Stefan doing this.
- [ ] Update checkPlugins.js to check for require('ep_etherpad-lite') calls and ideally provide alternative <-- Waiting on @rhansen to give me example.

My jobs related to #4714

Data:

- total 290 plugins
- no repo 53 <-- need to be emailed to be told to add a repository to their package or deprecate their package
- stale 114

**Comment by Gared** [comment]
@JohnMcLear If you want I can do the changes for static.etherpad.org

**Comment by JohnMcLear** [comment]
Yes please @Gared - should we agree that 5 years is plenty stale enough?

**Comment by Gared** [comment]
@JohnMcLear Removed plugins older than 5 years from plugin list

**Comment by JohnMcLear** [comment]
I got this as far as I intend to.
