### ISSUE TITLE
Best way to hide chat?

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4851]
I expected there to be a setting to be able to remove chat completely from the UI but there isn't one, it would make sense if there was..

**Comment by pjvandehaar** [comment]
👍.  I add `#chaticon, #chatbox { display: none !important; }` in my custom CSS.  If you're adding options for a minimal UI, I'd also like an option to hide the bottom toolbar like `.mobile-layout #editorcontainerbox { margin-bottom: 0 !important; }`.

**Comment by JohnMcLear** [comment]
Is custom.css still a thing?  I didn't think it worked for some time?

**Comment by JohnMcLear** [comment]
I published ep_disable_chat

**Comment by pjvandehaar** [comment]
> Is custom.css still a thing? I didn't think it worked for some time?

I just add css to files in src/static/css/ and stash when I `git pull`.

It's cool that Etherpad's plugin/hooks architecture makes these features so quick without touching the core codebase.  Thanks for this.

**Comment by JohnMcLear** [comment]
Yw
