### ISSUE TITLE
SocketIO migrate from 2.x to 3.x

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#4857]
Although we intend to migrate away from SocketIO I'm curious to see if we experience any gains in performance for our load testing.

Because this patch is unlikely to ever land in production code I'm going to make this a bounty project and offer it out to the paid community.

Etherpad is currently using the SocketIO 2.x API and has deep connections into it.  These will need to be shifted over to the new SocketIO API as per the migration guide.

Migration guide > https://socket.io/docs/v3/migrating-from-2-x-to-3-0/

**Comment by cerebralcourt** [comment]
Hey! I'd be interested in taking this on. Will keep in touch if I have any questions or problems.

**Comment by JohnMcLear** [comment]
Cc @HMarzban

**Comment by Zahrun** [comment]
@JohnMcLear Are you still interested to get this done provided the bounty?
