### ISSUE TITLE
GHSL-2020-359: seeking security contact for your project

### ISSUE THREAD

**Issue by anticomputer** [ether/etherpad-lite#4863]
The GitHub Security Lab reported a potential security vulnerability (GHSL-2020-359) in your project (ether/etherpad-lite). We are approaching 90 days since our initial report and as per our [coordinated disclosure policy](https://securitylab.github.com/advisories#policy), we intend to publish a public advisory detailing this issue. If you wish to discuss or further coordinate a response to this issue with the GitHub Security Lab, please contact us at securitylab@github.com within the next 7 days in reference to GHSL-2020-359 and we would love to help you resolve these issues. If not, feel free to close this issue and we will proceed with advisory publication on expiration.

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/blob/develop/SECURITY.md

No results found for "GHSL-2020-359".  Which issue specifically is this?

**Comment by anticomputer** [comment]
> https://github.com/ether/etherpad-lite/blob/develop/SECURITY.md
>
> No results found for "GHSL-2020-359".  Which issue specifically is this?
>

We've resent the report to the appropriate contact as per your security policy.

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/commit/0f16e518ff6c0a1edc33fd36fdc9d7ef3d3e732a <-- resolved here, we need to get a release out I think so you can say "resolved in version X"?

**Comment by anticomputer** [comment]
> https://github.com/ether/etherpad-lite/commit/0f16e518ff6c0a1edc33fd36fdc9d7ef3d3e732a
> <-- resolved here, we need to get a release out I think so you can say
> "resolved in version X"?
>

Great thank you, yes that would be ideal.

**Comment by JohnMcLear** [comment]
Okay cool, will try to ship over the weekend.

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/releases/tag/1.8.10



There ya go, tnx for the bump.







-----Original message-----

**Comment by anticomputer** [comment]
> https://github.com/ether/etherpad-lite/releases/tag/1.8.10
>
>
>
> There ya go, tnx for the bump.
>

:+1:
