### ISSUE TITLE
Clarification on backwards compatibility for jquery/underscore

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#4875]
If I understand the changes correctly then:
- if plugins use underscore in their backend code, they need to update from `require('ep_etherpad-lite/static/js/underscore')` to `require('ep_etherpad-lite/static/js/vendors/underscore')`
- if plugins do `require('underscore')` in their backend code, it's best if they'd define a dependency on underscore in their package.json. We could however add our src directory to `module.path` during startup, so that even for plugins that live under `./node_modules` a dependency that lives in `./src/node_modules` can be found without using `ep_etherpad-lite` prefix
- if plugins use jquery in their backend or frontend code, they should `require('ep_etherpad-lite/static/js/rjquery')` and don't need to change anything.
- if plugins use `require('jquery')` in their backend code, they should define a dependency on jquery in their package.json
- if plugins link to files in their frontend code with `<script src="/static/plugins/ep_plugin/static/js/underscore"` they need to update the path

So to summarize: whenever plugins use underscore in their backend code they need to update their code anyway (cp. failing tests in https://github.com/ether/etherpad-lite/runs/1988391793?check_suite_focus=true#step:13:35)

In https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/Minify.js I would rather only check for "/static/js/jquery" and deliver "/static/js/vendors/jquery" - that should catch all different cases for linking in src-attributes.
If required for backend code usage or via `require()` in the frontend, the "rjquery" file should always be used and no update is needed.

Also I would move underscore back to the old position. It's really just a wrapper not the vendors file. And I would remove the changes to tar.json as jquery/underscore does not need to be a package on it's own.

Did I miss something?

**Comment by rhansen** [comment]
(Replying mostly for the benefit of users and plugin authors who might come across this bug.)

> If I understand the changes correctly then:
> 
> * if plugins use underscore in their backend code, they need to update from `require('ep_etherpad-lite/static/js/underscore')` to `require('ep_etherpad-lite/static/js/vendors/underscore')`

Not anymore thanks to your PR #4876.

> 
> * if plugins do `require('underscore')` in their backend code, it's best if they'd define a dependency on underscore in their package.json.

They would *have* to define a dependency in their `package.json`.

> We could however add our src directory to `module.path` during startup, so that even for plugins that live under `./node_modules` a dependency that lives in `./src/node_modules` can be found without using `ep_etherpad-lite` prefix

No—we want to discourage plugins from piggybacking off of Etherpad's dependencies. It's better if their dependencies are explicitly enumerated in `package.json`.

> 
> * if plugins use jquery in their backend or frontend code, they should `require('ep_etherpad-lite/static/js/rjquery')` and don't need to change anything.

"Should" might be too strong of a word. It might be better for them to depend on jquery directly and use that (so that we don't break them when we update our jQuery), but there is overhead to doing that.

> 
> * if plugins use `require('jquery')` in their backend code, they should define a dependency on jquery in their package.json

They *must* define a dependency on jQuery in their `package.json`.

> 
> * if plugins link to files in their frontend code with `<script src="/static/plugins/ep_plugin/static/js/underscore"` they need to update the path

I assume you mean `ep_etherpad-lite` instead of `ep_plugin`. That's no longer the case thanks to your PR #4876.

> 
> 
> So to summarize: whenever plugins use underscore in their backend code they need to update their code anyway (cp. failing tests in https://github.com/ether/etherpad-lite/runs/1988391793?check_suite_focus=true#step:13:35)

Not anymore thanks to PR #4876.

> 
> In https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/Minify.js I would rather only check for "/static/js/jquery" and deliver "/static/js/vendors/jquery" - that should catch all different cases for linking in src-attributes.
> If required for backend code usage or via `require()` in the frontend, the "rjquery" file should always be used and no update is needed.
> 
> Also I would move underscore back to the old position. It's really just a wrapper not the vendors file. And I would remove the changes to tar.json as jquery/underscore does not need to be a package on it's own.

+1
