### ISSUE TITLE
Unsettled function bug in hook function

### ISSUE THREAD

**Issue by meaz** [ether/etherpad-lite#4880]
**Describe the bug**
In Firefox console, I see this

`UNSETTLED FUNCTION BUG IN HOOK FUNCTION (plugin: ep_table_of_contents, function name: ep_table_of_contents/static/js/aceEditEvent:aceEditEvent, hook: aceEditEvent): The hook function neither called the callback nor returned a non-undefined value. This is prohibited because it will result in freezes when a future version of Etherpad updates the hook to support asynchronous behavior.`

and also : 
`UNSETTLED FUNCTION BUG IN HOOK FUNCTION (plugin: ep_real_time_chat, function name: ep_real_time_chat/static/js/main:postAceInit, hook: aceInitialized): The hook function neither called the callback nor returned a non-undefined value. This is prohibited because it will result in freezes when a future version of Etherpad updates the hook to support asynchronous behavior. uM7pKcOTJwcqbKYUL64m line 24 > scriptElement line 25 > Function:67:1793`

I'm not too sure what it means and if I have to disable those plugins... Pad seems to load without problem otherwise.

**Server (please complete the following information):**
 - Etherpad version: 1.8.10
 - OS: Debian buster
 - Node.js version (`node --version`): v14.16.0
 - npm version (`npm --version`): 6.14.11

**Desktop (please complete the following information):**
 - OS: Debian buster
 - Browser: firefox
 - Version [e.g. 22]: esr 78.8

**Comment by rhansen** [comment]
I opened bugs against the plugins. You don't have to disable the plugins yet; those errors are warning about freezes that could happen with a future version of Etherpad if the bugs aren't fixed before then.

Thanks for reporting.
