### ISSUE TITLE
Change "About" Info

### ISSUE THREAD

**Issue by jannikb16** [ether/etherpad-lite#4895]
How can I change the "About" information in the pad settings?
![Github](https://user-images.githubusercontent.com/45617754/109424659-c0423180-79e4-11eb-91f5-da4492f4315d.png)

**Comment by JohnMcLear** [comment]
It's hard coded, a plugin would need to do 
```
$padOuter('.dropdowns-container > a').text('some new text');
```

**Comment by jannikb16** [comment]
thx!
