### ISSUE TITLE
Table4 table rows and columns cannot be dragged

### ISSUE THREAD

**Issue by richard7130** [ether/etherpad-lite#4907]
The plug-in table4 is installed，but table rows and columns cannot be dragged

![image](https://user-images.githubusercontent.com/24645381/109593467-ff3ec700-7b4b-11eb-9b4c-084d58ce033a.png)

**Comment by JohnMcLear** [comment]
Please post plugin issues on plugin repos

**Comment by richard7130** [comment]
plugin issues
