### ISSUE TITLE
Table4 plugin table rows and columns cannot be dragged

### ISSUE THREAD

**Issue by richard7130** [ether/etherpad-lite#4908]
* * *

name: Plugin request
about: Suggest a plugin for this project
title: Table4 plugin table rows and columns cannot be dragged
labels: plugin request
assignees: 

* * *

**Is your plugin request related to a problem? Please describe.**
table rows and columns cannot be dragged

**Describe the solution you'd like**
Table rows and columns can be dragged

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/24645381/109605210-bee94400-7b5f-11eb-8328-bf5b2a73b759.png)

**Comment by JohnMcLear** [comment]
I'm not the maintainer of this plugin and it's not a foundation plugin, pleease speak to the maintainer of the plugin :)  


https://www.npmjs.com/package/ep_tables4
