### ISSUE TITLE
Table4 plugin table rows and columns cannot be dragged

### ISSUE THREAD

**Issue by richard7130** [ether/etherpad-lite#4909]
The plug-in table4 is installed，but table rows and columns cannot be dragged
![image](https://user-images.githubusercontent.com/24645381/109605990-f60c2500-7b60-11eb-9c95-88e858c513ca.png)

**Comment by richard7130** [comment]
Does etherpad not support image tables well

**Comment by rhansen** [comment]
Please contact the maintainers of the ep_tables4 plugin: https://github.com/WC2-Foundation/ep_tables4
