### ISSUE TITLE
table4 plugin plug Show questions

### ISSUE THREAD

**Issue by richard7130** [ether/etherpad-lite#4910]
With the table4 plug-in installed, the table can be displayed normally through URL direct access, but the HTML data returned through gethtml interface cannot be displayed normally。
URL show：
![image](https://user-images.githubusercontent.com/24645381/109606309-6d41b900-7b61-11eb-944a-634fa4759ce9.png)

getHtml API show：
![image](https://user-images.githubusercontent.com/24645381/109606331-76328a80-7b61-11eb-8e03-2d560d7a240e.png)

**Comment by JohnMcLear** [comment]
Please stop.

**Comment by JohnMcLear** [comment]
This is not the correct place :)  Please visit https://github.com/WC2-Foundation/ep_tables4

Please stop posting on this repository Github issues as it's not the correct location (this is for the core code, not plugins).

Thanks!
