### ISSUE TITLE
Pass plugin settings to hook calls

### ISSUE THREAD

**Issue by jasonaowen** [ether/etherpad-lite#4923]
* * *

name: Feature request
about: Suggest an idea for this project
title: 'Pass plugin settings to hook calls'
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**

Many plugins need some static, site-specific configuration. These settings generally live in `settings.json`, under a key matching the plugin's name.

However, I have found accessing these settings to be surprisingly difficult in practice. The typical pattern seems to be `require('ep_etherpad-lite/node/utils/Settings')`, but that's reaching into Etherpad's internals in a way that https://github.com/ether/etherpad-lite/issues/4714 is explicitly saying is bad and will change.

One alternative is to use the `loadSettings` hook, but the hook isn't called until somewhat late in the loading process, and it is difficult to retain the value in a useful way. For my first iteration I created a promise to hold the value, and that works with hooks that don't require an immediate response, but not with hooks that do (such as any of the `eejsBlock_*` hooks which the plugin wants to modify). I haven't yet figured out a solution involving `loadSettings` that works with immediate hooks.

Under either approach, plugins need to extract their specific settings from the complete settings object, which in turn requires the plugin's name, either as a constant or as a literal. In addition to being a minor inconvenience, exposing the complete settings to plugins may also be a security risk: https://github.com/ether/etherpad-lite/issues/4772.

Finally, and I'm not sure if this is still a relevant concern, in 2012 @JohnMcLear [wrote](https://github.com/ether/etherpad-lite/pull/893#issuecomment-9345193):

> I'm scared of putting plugin settings into the settings.json file because then how do we handle changing plugin settings in the UI? Ultimately I want the plugin experience to be enable.. change settings in the /admin/plugins UI whilst installing, fin. No restart, no modifying files, no moonshine

Laying the groundwork for runtime configuration of plugin settings seems like worthwhile work.

**Describe the solution you'd like**

I propose that calls to server-side hooks include plugin settings, either as an additional bit of `context` or as an additional parameter. The caller should look up the plugin name in the loaded settings and pass the value to the plugin's callback.

Passing a plugin's settings into its hooks allows plugins to reduce the number of explicit dependencies on Etherpad internals, allow for less stateful / more functional-style plugins, avoid hardcoding the plugin's name in the source code, and open a path to splitting plugin settings back out of `settings.json`.

**Comment by JohnMcLear** [comment]
This ties into the conversation around an etherpad intermediate lib for plugins.

**Comment by jasonaowen** [comment]
> This ties into the conversation around an etherpad intermediate lib for plugins. #4714

Yes, I was trying to keep #4714 in mind! I was imagining this settings work as part of that larger work.

If this solution seems on-path to you, @JohnMcLear, I have some bandwidth to work on implementing it! I just want to make sure that it fits with yours and @rhansen's vision before I spend too much time on it.

**Comment by JohnMcLear** [comment]
Yea this looks good, be mindful of @orblivion 's work on this too tho, he has an open PR atm https://github.com/ether/etherpad-lite/pull/4273





-----Original message-----

**Comment by rhansen** [comment]
> One alternative is to use the `loadSettings` hook, but the hook isn't called until somewhat late in the loading process

Why do you say that? The `loadSettings` hook is the very first hook run after all plugins are discovered. It runs before the HTTP server is even created, so all `eejsBlock_<name>` hooks run after it.

> and it is difficult to retain the value in a useful way.

How so? Seems straightforward to me:

```javascript
let settings;

exports.loadSettings = (hookName, {settings: {ep_example = {}}}) {
  settings = ep_example;
};
```

> Finally, and I'm not sure if this is still a relevant concern, in 2012 @JohnMcLear [wrote](https://github.com/ether/etherpad-lite/pull/893#issuecomment-9345193):
>
>> I'm scared of putting plugin settings into the settings.json file because then how do we handle changing plugin settings in the UI? Ultimately I want the plugin experience to be enable.. change settings in the /admin/plugins UI whilst installing, fin. No restart, no modifying files, no moonshine

Plugin settings have to be saved somewhere. If not in `settings.json` then where? Settings could be saved in the database, but then the settings can't be easily checked into a Git repo. (Version control is a must for important production servers.)

**Comment by JohnMcLear** [comment]
Good point RE saved settings being saved somewhere and a lot has changed in 9 years (containerization wasn't even a thing then).  I think saving settings in ``settings.json`` is probably fine as it has been mature for quite some time but I think we can help promote settings being available in /admin/settings by a "helper" which would be part of #4714.  A suggestion would be..

```
plugin.namespace = 'ep_set_title_on_pad'; // this namespace might be automatically set by ``ep.json``
plugin.settings.set(ep_set_title_on_pad, {
  key: 'defaultPadTitleText',
  name: 'Default Pad Title Text',
  value: 'Hello world',
  adminSetting: true, // it this setting changable in /admin/setting
  userSetting: false, // can the user change this setting through the "Settings" dialog (saves as cookie)
  clientAccessible: true, // should server pass this value to the client
  ...
})
```

Consumed with

```
const title = plugin.settings.get('defaultPadTitleText');
...
```

**Comment by jasonaowen** [comment]
I realize now that I never gave an example in the initial issue, which probably made my proposal less clear than it should have been. Sorry about that!

As a hook author, I would like to be able to receive my plugin's settings with each hook as a property on the `context` argument, sometimes also called `args` by hooks.

```json
{
  "...": "rest of settings.json",

  "ep_example": {
    "enableFeature": true,
    "featureInitialValue": "The Feature"
  }
}
```
```js
exports.padUpdate = (hookName, context) => {
  const { pad, settings } = context;
  if (settings.enableFeature) {
    doThingWithFeature(pad, settings.featureInitialValue);
  }
};
```

Hopefully this example better illustrates the way I'd like to be able to work with settings as a plugin author, and will make the rest of the discussion a little easier.

> > One alternative is to use the `loadSettings` hook, but the hook isn't called until somewhat late in the loading process
> 
> Why do you say that? The `loadSettings` hook is the very first hook run after all plugins are discovered. It runs before the HTTP server is even created, so all `eejsBlock_<name>` hooks run after it.

Ah, perhaps I should have said "later than I'd like". :slightly_smiling_face:  The `loadSettings` hook runs after the hooks have been loaded (of course), which means that the value passed to it cannot be used by other hook code evaluated at import time.

> > and it is difficult to retain the value in a useful way.
> 
> How so? Seems straightforward to me:
> 
> ```js
> let settings;
> 
> exports.loadSettings = (hookName, {settings: {ep_example = {}}}) => {
>   settings = ep_example;
> };
> ```

This approach does not work as well when using multiple files. The ESLint rule [import/no-mutable-exports](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-mutable-exports.md) complains about the subsequent `export { settings }`. I hadn't dug into the details of that rule before, and the rule description itself does not really explain, beyond "[you can turn this rule off if] your environment correctly implements mutable export bindings". Does the environment Etherpad provides to plugins correctly implement mutable export bindings?

Both the [Airbnb style guide](https://github.com/airbnb/javascript#modules) and [Google style guide](https://google.github.io/styleguide/tsguide.html#mutable-exports) go into a little more detail. From Google:

> Regardless of technical support, mutable exports can create hard to understand and debug code, in particular with re-exports across multiple modules. One way to paraphrase this style point is that `export let` is not allowed.

Part of why I choose to use the Airbnb ESLint configuration is to avoid these edge cases; I am grateful to the people who have spent time studying the problem and thinking about the solution.

The other reason this solution didn't occur to me was that I allowed my preference for `const` over `let` to get in my way. :slightly_smiling_face: 

> > > Finally, and I'm not sure if this is still a relevant concern, in 2012 @JohnMcLear [wrote](https://github.com/ether/etherpad-lite/pull/893#issuecomment-9345193):
> > > > I'm scared of putting plugin settings into the settings.json file because then how do we handle changing plugin settings in the UI? Ultimately I want the plugin experience to be enable.. change settings in the /admin/plugins UI whilst installing, fin. No restart, no modifying files, no moonshine
> > 
> > Plugin settings have to be saved somewhere. If not in `settings.json` then where? Settings could be saved in the database, but then the settings can't be easily checked into a Git repo. (Version control is a must for important production servers.)
> 
> Good point RE saved settings being saved somewhere and a lot has changed in 9 years (containerization wasn't even a thing then). I think saving settings in `settings.json` is probably fine as it has been mature for quite some time

Ah, to clarify, I am not proposing to change where plugin settings are saved as part of this issue - I am only suggesting a new way for plugins to *receive* settings.

I quoted the comment about `settings.json` because I think passing the plugin's settings as part of the `context` sent to a hook would allow for you to change where settings live later, once plugins have moved away from `require('ep_etherpad-lite/node/utils/Settings')`. If that's not a concern any more - and it sounds like, at least for some users, dynamically loaded settings will never be acceptable - then making that future change easier is not a very compelling reason.

> Yea this looks good, be mindful of @orblivion 's work on this too tho, he has an open PR atm #4273

Thanks for the heads up, @JohnMcLear! After a first pass through PR #4273, I believe this should not overlap. If we decide to move forward with this approach, I'll look at it more closely when implementing.

> I think we can help promote settings being available in /admin/settings by a "helper" which would be part of #4714. A suggestion would be..
> 
> ```
> plugin.namespace = 'ep_set_title_on_pad'; // this namespace might be automatically set by ``ep.json``
> plugin.settings.set(ep_set_title_on_pad, {
>   key: 'defaultPadTitleText',
>   name: 'Default Pad Title Text',
>   value: 'Hello world',
>   adminSetting: true, // it this setting changable in /admin/setting
>   userSetting: false, // can the user change this setting through the "Settings" dialog (saves as cookie)
>   clientAccessible: true, // should server pass this value to the client
>   ...
> })
> ```

Ah, default settings values are a good thing to point out! Giving plugins a first-class way to set default values seems very valuable. Do you think that's something that we need to figure out as part of this? Or, would you like me to open a new issue to discuss that? For my first pass, I'm inclined to say it's a related but distinct problem, just to make this change a smaller scope.

> Consumed with
> 
> ```
> const title = plugin.settings.get('defaultPadTitleText');
> ...
> ```

As I've been working on this response, I've realized that the core concept that I'm arguing for is passing data in via each hook that needs it rather than relying on hooks to maintain state. I'll also comment to that effect in #4714. So, if you want to keep the settings bundled in the new plugin object, that's fine, but I'd love to see that `plugin` passed as part of the `context` into each hook call!
