### ISSUE TITLE
Disabling showChat at settings file padOptions

### ISSUE THREAD

**Issue by pedrobmarin** [ether/etherpad-lite#4927]
**Describe the bug**
Disabling `showChat` does not hide chat the same way passing `showChat=false` as an URL query string. https://github.com/ether/etherpad-lite/blob/4ca989a255a9b4eed06b122b9fad97304eb930d7/settings.json.template#L208

**To Reproduce**
1. Set `showChat` to false at settings
2. Join user
3. Chat is visible
4. Add `?showChat=false` to the URL
5. Chat is hidden

**Expected behavior**
Chat to be hidden when disabling showChat at settings.

**Server (please complete the following information):**
 - Etherpad version: 1.8.12
 - OS: Ubuntu 18.04.3
 - Node.js version (`node --version`): v12.18.2
 - npm version (`npm --version`): 6.14.5

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3
 - Browser Firefox & Chrome
 - Version 86.0 & 89.0.4389.72

**Comment by JohnMcLear** [comment]
We need to make a bigger decision on if passing false as a param hides it by default or just minimizes it.  For now can you use ep_disable_chat and be in an okay position?

**Comment by webzwo0i** [comment]
Proposal:

Site admins determine if they want chat functionality via settings ('enableChat' defaults to true). If false, PadMessageHandler should not react to chat messages/all server code re chat should be ignored and any functionality re chat in UI should be unavailable (e.g. no sticky, "show chat and user" should read "show user", showChat query param should be ignored)

If enabled, user can pass the following as query string:
- showChat, determines if the chat window is visible (maximized) after page load, defaults to false
- disableChat, removes all chat functionality from UI, defaults to false

**Comment by JustAnotherArchivist** [comment]
I just ran into the same issue. I also expected `showChat = false` to hide the chat entirely.

And I agree with @webzwo0i. A way to actually disable chat entirely would be great. ep_disable_chat is an okay workaround but only hides the UI elements; the backend would still accept, process, and broadcast chat messages, etc.

**Comment by rhansen** [comment]
My preference would be to move all chat functionality to another plugin.

**Comment by Loki-Afro** [comment]
@rhansen plus one for the plugin approach.
For context, we integrate etherpad in our platform and have a chat there, having another chat in etherpad is confusing therefore we need to disable it :)

**Comment by rhansen** [comment]
I decided to split this into three issues:
  * This issue: `padOptions.showChat` should behave the same as the `showOptions` URL parameter.
  * #5314
  * #5315
