### ISSUE TITLE
Click anywhere on empty pad won't open device keyboard

### ISSUE THREAD

**Issue by ramonlsouza** [ether/etherpad-lite#4928]
**Describe the bug**
When you have a pad with empty text on mobile devices, you need to click in the blinking cursor to open the device keyboard.

The same does not happen if you already have some text (or in older versions of Etherpad).

**To Reproduce**
1. Go to http://demo.etherpad.com/ (on a mobile device)
2. Create new pad
3. Erase all default text
4. Close device keyboard
5. Click anywhere on the screen except the blinking cursor
6. Device keyboard won't open

**Expected behavior**
Device keyboard should open by clicking anywhere on step 6.

**Server (please complete the following information):**
 - Etherpad version: 1.8.7 (also happens in https://demo.etherpad.com/)
 - OS: Ubuntu 18.04
 - Node.js version (`node --version`): v12.21.0
 - npm version (`npm --version`): 6.14.11

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10e
 - OS: Android 11
 - Browser: Google Chrome
 - Version: 89.0.4389.72

**Additional context**
We have an older test server running Etherpad 1.8.0 and the behavior is as expected (https://etherpad.wikimedia.org/ also works  as expected)

**Comment by webzwo0i** [comment]
Thanks for reporting. Bisect says 98de2b089973c4a01bd0f02745a4be02ad51642e

**Comment by JohnMcLear** [comment]
Wow good job @webzwo0i that's a decent bisect and super interesting

**Comment by rhansen** [comment]
@ramonlsouza Can you try copying this line to `#innerdocbody`: https://github.com/ether/etherpad-lite/blob/404486069c204cbec840aa802fc6a18dac013418/src/static/css/iframe_editor.css#L14

**Comment by ramonlsouza** [comment]
> @ramonlsouza Can you try copying this line to `#innerdocbody`:
> 
> https://github.com/ether/etherpad-lite/blob/404486069c204cbec840aa802fc6a18dac013418/src/static/css/iframe_editor.css#L14

It worked!
