### ISSUE TITLE
Can’t run Etherpad after upgrade to 1.8.12 : `try: not found`

### ISSUE THREAD

**Issue by ldidry** [ether/etherpad-lite#4930]
**Describe the bug**
After upgrading to 1.8.12, I can’t run Etherpad with `safeRun.sh`: it fails saying `try: not found`

**Expected behavior**
`safeRun.sh` should launch Etherpad

**Server (please complete the following information):**
 - Etherpad version: 1.8.12
 - OS: Debian 10
 - Node.js version (`node --version`): v12.21.0
 - npm version (`npm --version`): 6.14.11
 - bash (which launch `safeRun.sh`) version: 5.0.3

**Additional context**
`try` in `safeRun.sh` was introduced in https://github.com/ether/etherpad-lite/commit/8b28e007842efefccf852a55f783761f86dc6090#diff-d9f65dd56d7d1ec3afc44b2c3eadde1d3dcd64513764bcdc0bc1f1cb6512b990

**Comment by boehm-e** [comment]
Have you tried to : 
- remote node_modules 
- clean npm cache
- reinstall your plugins ?
