### ISSUE TITLE
how to handle HTML table (not related to ep_tableX) 

### ISSUE THREAD

**Issue by boehm-e** [ether/etherpad-lite#4931]
Hi,
First i'd like to thank you for this amazing project.

I do not understand how i can handle table of this type : 
```html
<table>
    <tr>
        <td>
            <p>column1</p>
        </td>
        <td>
            <p>column2</p>
        </td>
    </tr>
    <tr>
        <td>
            <p>Value1</p>
        </td>
        <td>
            <p>Value2</p>
        </td>
    </tr>
</table>
```

since every "\<p\>" tag of the original HTML table are processed as a new magicdom line.
 
![image](https://user-images.githubusercontent.com/11290215/110298772-42d67c80-7ff5-11eb-8d0d-a9b2d6d2d8c0.png)

I tried multiple hooks :
- aceDomLineProcessLineAttributes
- aceRegisterBlockElements, to register table, tr, td.
- aceCreateDomLine
- collectContentPre
- collectContentLineBreak
- acePostWriteDomLineHTML

But I do not understand which hook I need to implement in order to re-create my table in the editor. The ep_tables plugins seem irrelevant to me, since they are not create from HTML raw tables.
If someone could put me on the track :)

PS: my final goal, is to create an ep_docx plugin to import docx with "all" formatting (using improved version of mammoth.js) . For now color, highlight and font-size are working. As you have guessed, I try to import tables.

Have a great day, thank you.

**Comment by boehm-e** [comment]
@JohnMcLear any recommendations?

**Comment by JohnMcLear** [comment]
I have intentionally avoided tables and will continue to do so.  Sorry if that's not the answer you wanted.

**Comment by boehm-e** [comment]
@JohnMcLear ok but are you against it? And could you say why ? 
And is it even possible ? Just want some directions on what hook to use.

**Comment by JohnMcLear** [comment]
I'm not against any use of Etherpad.  I don't know the answers to your questions.  Sorry

**Comment by rajasekharponakala** [comment]
is this related to embed tabled in etherpad? like table embed in libreoffice writer?
