### ISSUE TITLE
Importing unknown file will cause crash

### ISSUE THREAD

**Issue by AltayAkkus** [ether/etherpad-lite#4932]
**Describe the bug**
When you import a unknown filteype (in this case rdf), Etherpad Lite imports the document as raw binary data.
This leads to serious lagging. In my school we used it and a student accidentally imported a malformatted file, we effectively lost everything we couldn't even rollback.

**To Reproduce**
1. Go to an instance of Etherpad Lite (yopad.eu for me)
2. Create a new pad
3. Get a random file from your PC (not txt or MD, something binary)
4. Rename it to a file extension that doesn't exist (RDF in my case)
5. Import it
6. See the damage

**Expected behavior**
Warning that the filetype was not detected, since no user should ever want to import binary data. Make an exception for documents like txt or MD but in a real world scenario no user would ever want to import binary data.

**Screenshots**
see https://yopad.eu/p/ahsdhds

**Server (please complete the following information):**
not self hosted, tested on other public Etherpad LItes

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Firefox

**Comment by JohnMcLear** [comment]
Is this present on develop or the latest release?

**Comment by JohnMcLear** [comment]
Can you replicate on https://dark.etherpad.com ?
