### ISSUE TITLE
Timeslider does not work

### ISSUE THREAD

**Issue by haivala** [ether/etherpad-lite#4937]
**Describe the bug**
Timeslider page works but it does not show the contents of the pad like it used to
Console has an error:
 Unexpected error: could not translate element content for key timeslider.toolbar.returnbutton

**To Reproduce**
1. Create pad
2. edit
3. go to timeslider
4. See error in console

**Expected behavior**
Timeslider should show the edits of the pad

**Screenshots**
![screen](https://user-images.githubusercontent.com/3918267/110655727-f98a5680-81c7-11eb-955d-d4dd3f53439c.png)

**Server (please complete the following information):**
 - Etherpad version: clone from develop branch today
 - OS: docker node:10-buster-slim:lastest
 - Node.js version (`node --version`): docker node:10-buster-slim:lastest
 - npm version (`npm --version`): docker node:10-buster-slim:lastest
 - db: 10.4.18-MariaDB

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox or any other
 - Version Latest

**Comment by JohnMcLear** [comment]
Can you replicate this on one of the public etherpad.com instances?  We have test coverage for this so I doubt this bug exists in latest release...

**Comment by haivala** [comment]
There is some information missing. sorry for that.

This has something to do with the database encoding. 
I had latin1 database and someone used emoji in one of the pads which broke that pad.
So this led me to update etherpad and that the same time I converted the database to utf8mb4 to make sure emojis are allowed.

After the update I created new pad and used the same emoji to test if it breaks the pad and it did not.
But I never got the broken pad to work and it now has this error in the frontend:
```
Failed assertion: [object Object][object Object]
at unknown at line -1
```
and the timeslider does not work in any of the pads.

**Comment by JohnMcLear** [comment]
Please answer my question.  Thanks!

**Comment by haivala** [comment]
> Please answer my question. Thanks!

WelI doubt that I can fiddle around with the database encoding in the public pads

**Comment by JohnMcLear** [comment]
No but you can put an emoji in a pad and see if it works in timeslider....

**Comment by haivala** [comment]
It works
https://etherpad.wikimedia.org/p/qr40PZIWcaKwLKNpbQ7g/timeslider#3

**Comment by JohnMcLear** [comment]
See readme for the public test instances we provide.

**Comment by haivala** [comment]
> See readme for the public test instances we provide.

You mean this? https://github.com/ether/etherpad-lite/wiki/Sites-that-run-Etherpad-Lite
What about it?

**Comment by JohnMcLear** [comment]
No.   The readme.  It's the page that you see first in GitHub for this project...

**Comment by haivala** [comment]
https://rich.etherpad.com/p/4-nsp0NY9WUjL5LcYW_j/timeslider#2

This has the same problem with the time slider

**Comment by JohnMcLear** [comment]
Confirmed .

Serious regression bug with tests that obviously are failing.  Needs fix ASAP.

**Comment by webzwo0i** [comment]
Bisect says 470f40d7db01b68856edf47ac7a5befd50b50340 for the timeslider not loading issue. I'm amazed we did not see this in CI. Needs more investigating to find out if this is related to emojis. I'm running on dirtydb, so there should not be any encoding issues.

My first guess is these are two bugs. One that makes our timeslider non-functional related to 470f40d7db01b68856edf47ac7a5befd50b50340 and a second with how the encoding issue was resolved. @haivala Is it possible for you to grant us access to the broken pad? Especially `/export/etherpad` of it.
If not, can you /export/etherpad the broken pad, search for the changeset that introduced the emoji and paste that changeset? I'm pretty sure it is wrong and then the resulting atext is also wrong.
Also, do you only see the "object object" error message and no stack trace?

**Comment by haivala** [comment]
I can give access to the pad but I don't want to paste the url here.

export is 1.1MB

I hope I had more time to investigate!

**Comment by JohnMcLear** [comment]
You can email contact@etherpad.org it.

**Comment by haivala** [comment]
> You can email [contact@etherpad.org](mailto:contact@etherpad.org) it.

done

**Comment by haivala** [comment]
Thank you for this!
