### ISSUE TITLE
TypeError: null is not an object (evaluating 'browserSheet.insertRule')

### ISSUE THREAD

**Issue by rhansen** [ether/etherpad-lite#4961]
Client-side exception at [src/static/js/cssmanager.js#L64](https://github.com/ether/etherpad-lite/blob/cb9f6d67768da5c87651c03bcc24e019574121aa/src/static/js/cssmanager.js#L64) on latest develop (cb9f6d67768da5c87651c03bcc24e019574121aa). Seems to only happen on Safari. It doesn't always happen, so it appears to be a race condition. I had hoped that PR #4960 would fix it, but it did not.

**Comment by webzwo0i** [comment]
Do you have a trace to find out which makeCSSManager call caused it?
