### ISSUE TITLE
Crash on startup: missing dependencies

### ISSUE THREAD

**Issue by sbrl** [ether/etherpad-lite#4962]
**Describe the bug**
When I  start etherpad, it claims that all the dependencies are missing, despite the fact that `installDeps.sh` has just installed them.

**To Reproduce**
1. Install Node.js v15.11.0 & npm 6.14.11
2. Run `src/bin/installDeps.sh`, followed by `npm install sqlite3`
3. Execute `path/to/etherpad/bin/run.sh`

**Expected behavior**
Etherpad runs as normal

**Screenshots**
Log files are probably more helpful here.

 - Logs: https://pastebin.com/raw/hQfDj21p
 - Dockerfile that reproduces the issue: https://pastebin.com/raw/1bqahnab
      - `minideb-node` is a private Dockerfile based on minideb with `nodejs-sbrl` installed from [my apt repository](https://apt.starbeamrainbowlabs.com/)

**Server (please complete the following information):**
 - Etherpad version: 1.8.12
 - OS: Host OS: Raspberry Pi OS, based on Debian Buster, armv7l - Guest OS inside Docker container: [minideb](https://github.com/bitnami/minideb)
 - Node.js version (`node --version`): v15.11.0
 - npm version (`npm --version`): 6.14.11

**Desktop (please complete the following information):** NOT relevant, because I can't get etherpad to start so I can't access it - but I'm including it for completeness
 - OS: Ubuntu Desktop 20.10
 - Browser Firefox
 - Version 87.0b9 (64-bit)

**Smartphone (please complete the following information):** Again NOT relevant because I do NOT access etherpad on my smartphone and even if I could I can't because etherpad won't start, but I'm including it for completeness.
 - Device: Nokia 7.1
 - OS: Android 10
 - Browser Firefox for Android
 - Version 87.0.0-beta.4 (Build #2015797515)

**Additional context**

**Comment by JohnMcLear** [comment]
Can you replicate this if you DON'T use docker please?

**Comment by JohnMcLear** [comment]
Also please check the root etherpad folder, do you see ``package.json`` or ``package-lock.json``?  Thanks¬

**Comment by webzwo0i** [comment]
installDeps.sh output would be useful, also `du -sh node_modules` and `du -sh ./src/node_modules`.

**Comment by sbrl** [comment]
@webzwo0i:

```bash
$ cd /srv/etherpad
$ du -sh node_modules
32M	node_modules
$ du -sh ./src/node_modules
396K	./src/node_modules
```

@JohnMcLear:

```bash
$ cd /srv/etherpad;
$ ls package* -lh
-rw-r--r-- 1 70 70 74K Mar 19 22:44 package-lock.json
-rw-r--r-- 1 70 70  52 Mar 19 22:44 package.json
$ ls src/package* -lh
-rw-r--r-- 1 70 70 307K Mar 19 22:25 src/package-lock.json
-rw-r--r-- 1 70 70 6.1K Mar 19 22:25 src/package.json
```

Regarding reproducing this without Docker, absolutely. I did the following on a regular Ubuntu Desktop 20.10 computer that doesn't even have Docker installed, and got the exact same error:

```bash
git clone --branch master https://github.com/ether/etherpad-lite.git /tmp/etherpad-test
cd /tmp/etherpad-test
git checkout b99c2cae22f35a0c0831e2fef0719f115b486bd9
git status
node --version
npm --version
src/bin/installDeps.sh
npm install sqlite3
bin/run.sh
```

I tried this process multiple times, and I can reliably reproduce the same error every single time - regardless of whether I copy my `settings.json` file in or not.

For reference:

```
$ node --version
v15.11.0
$ npm --version
7.6.3
$ uname -a
Linux PC_NAME 5.8.0-45-generic #51-Ubuntu SMP Fri Feb 19 13:24:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```

I can verify I can reproduce this on Raspberry Pi OS Debian Buster (armv7l) and Ubuntu Desktop 20.10 (amd64).

**Comment by JohnMcLear** [comment]
If you don't install sqlite3 dep do you get any errors?

**Comment by sbrl** [comment]
No, if I don't install `sqlite3` with `npm install sqlite3` I don't see any errors @JohnMcLear.

**Comment by webzwo0i** [comment]
Could you give it a try with `npm i --no-save sqlite3` in the main directory or `npm i sqlite3` in ./src/ directory?

**Comment by sbrl** [comment]
Both of those seem to work, @webzwo0i. Though it claims it's loading 1 plugin, and doesn't use sqlite3 (insted preferring "dirtyDB" instead of sqlite:

```
[2021-03-25 20:44:54.181] [WARN] console - DirtyDB is used. This is not recommended for production. File location: /tmp/etherpad-test/var/dirty.db
[2021-03-25 20:44:54.181] [INFO] console - Random string used for versioning assets: f38b1e55
[2021-03-25 20:44:54.295] [INFO] server - Starting Etherpad...
[2021-03-25 20:44:54.303] [INFO] plugins - Running npm to get a list of installed plugins...
[2021-03-25 20:44:54.394] [INFO] plugins - npm --version: 6.14.11
[2021-03-25 20:44:55.762] [INFO] plugins - Loading plugin ep_etherpad-lite...
[2021-03-25 20:44:55.763] [INFO] plugins - Loaded 1 plugins
[2021-03-25 20:44:55.893] [INFO] APIHandler - Api key file "/tmp/etherpad-test/APIKEY.txt" not found.  Creating with random contents.
[2021-03-25 20:44:55.945] [INFO] server - Installed plugins: 
[2021-03-25 20:44:55.953] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2021-03-25 20:44:55.953] [INFO] console - Your Etherpad version is 1.8.12 (b99c2ca)
[2021-03-25 20:44:56.518] [INFO] http - HTTP server listening for connections
[2021-03-25 20:44:56.518] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
```

**Comment by sbrl** [comment]
The weird thing is that I can always install the `sqlite3` package myself without issue - it's just etherpad that doesn't appear to like it very much. I took another read of the documentation, but it didn't help me.

**Comment by sbrl** [comment]
Excuse me @stale, but my issue is NOT resolved. I am not the one not replying here, so that it VERY unhelpful of you to close this issue. Looks like I need to look for an alternative to etherpad then.....

**Comment by webzwo0i** [comment]
I cannot reproduce your problem. It simply works when I git clone, move my settings in, run `npm i sqlite3` in ./src and then run ./bin/run.sh. The only thing I think we should change is the hint that you should run `npm i sqlite3` from the main folder into running it inside ./src or running `npm i --no-save sqlite3` from the main directory, because our console.log message is wrong here, when sqlite3 is missing as a dependency. Maybe you just forget to configure sqlite as database in settings.json the last time when running https://github.com/ether/etherpad-lite/issues/4962#issuecomment-807456904

Also please rethink your attitude. stale is an automated bot and you could have replied yourself, bumping the issue or saying "please don't close, it still does not work for me", so there is no need to take it personally. We're helping free of charge here, so be respectful or yes, please use another tool.

**Comment by sbrl** [comment]
Hrm, that's really odd - I think I tried that previously and I didn't work either. What's the offically supported version of Node.jsj for Etherpad?

> Also please rethink your attitude. stale is an automated bot and you could have replied yourself, bumping the issue or saying "please don't close, it still does not work for me", so there is no need to take it personally. We're helping free of charge here, so be respectful or yes, please use another tool.

Apologies there. I just found @stale's response to sudden and abrupt. On other repos, it first posts a `There doesn't seem to be any activity here. Are there any updates?` message a week or so before closing the issue to give those involved a chance to comment and pick things up again (e.g. tldr-pages/tldr, for which I'm a maintainer), when that isn't the case here - so having my issue closed in a way that I didn't feel I had any comeback or way to pick it up again was unpleasant. In addition, I wasn't aware that stable bot would do this, so I did not think I needed to set myself a reminder on my own systems to double check on this issue if nobody replied.

To this end, it looks like etherpad's support for SQLite is less than stable, so indeed I'm going to use another tool I think. Sucks that I'm losing all my existing pads that are stored in Etherpad, but I guess it can't be helped.

**Comment by webzwo0i** [comment]
stale bot should write a message 7 days before closing. It actually does not close issues when they are labeled as bug, which wasn't the case here.

I think the last release still supported v10, but now we support >=12.13.0. We test node versions 12/14/16 automatically, but until some days ago we also tested v15. We didn't include tests for different database backends on Etherpad, because we had limited parallel runners on Travis and not enough minutes for all the tests. Now, that we use Github actions, I think we could run tests for different databases... (IIRC we already run tests for different databases on ueberDB - but as this bug shows the installation procedure can be problematic, too)

The following works for me on x86_64
```
git clone --branch master https://github.com/ether/etherpad-lite.git /tmp/etherpad-test
cd /tmp/etherpad-test
git checkout b99c2cae22f35a0c0831e2fef0719f115b486bd9
git status
node --version
npm --version
# copy your settings.json
src/bin/installDeps.sh
(cd src && npm install sqlite3)
bin/run.sh
```
In settings.json I configured 
```
  "dbType": "sqlite",
  "dbSettings": {
    "filename": "var/dirty.db"
  },
```

node v15.14.0
npm 7.7.6

**Comment by sbrl** [comment]
Thanks for the reply.

Hrm, that's odd. Maybe there's a bug in stale bot or something.

Ah, that's interesting. I thought that it might have been an issue with me using a new version of Node.js or something.

Oh, I haven't heard of ueberDB - I'll have to look into it.

Awesome! Those instructions actually work for me!

 - Dockerfile: https://pastebin.com/5zdNcr1z
 - Original Dockerfile (specific to my infrastructure, in which I have a custom minideb base image with my apt repo baked in): https://pastebin.com/XP19jGBU

I can confirm this works on Raspberry Pi, so it was in all likelihood an installation problem here. Note that I have now updated to Node.js v16 since this issue was opened.

**Comment by robinpaulson** [comment]
Hi, I think I'm getting an issue related to this, but I'm not entirely sure. I've been running e-l for maybe two years on an Ubuntu server. I upgraded today, from 1.8.12 to 1.8.14, using "git pull origin master", then ran installDeps.sh

When I start e-l, using run.sh, I get errors of missing dependences, including sqlite3, and it bugs out. I've manually installed sqlite3 using the methods supplied above, but no luck.

my node version is 16, npm is 7.23

thanks

**Comment by rhansen** [comment]
> Hi, I think I'm getting an issue related to this, but I'm not entirely sure.

If my responses below don't help, please open a new bug report with full details.

> I get errors of missing dependences

Delete `/path/to/etherpad-lite/package.json` and `/path/to/etherpad-lite/package-lock.json` (if they exist) and try again.

> I've manually installed sqlite3

Make sure you install it under `src/`

```shell
cd /path/to/etherpad-lite/src && npm i sqlite3
```

> my node version is 16, npm is 7.23, both installed via nvm. Upon running, e-l reports I am using npm v6.13

That's a good thing. We [intentionally install a copy of npm v6.13](https://github.com/ether/etherpad-lite/blob/d58b649c76e98c3908fe02b60561eac1f85e17fc/src/package.json#L56) due to compatibility problems with npm v7. That log line indicates that Etherpad has successfully found the version installed as a dependency, and is not using the host's version.

**Comment by robinpaulson** [comment]
yes! thanks, deleting package and package-lock did it.

**Comment by dcht00** [comment]
> That's a good thing. We [intentionally install a copy of npm v6.13](https://github.com/ether/etherpad-lite/blob/d58b649c76e98c3908fe02b60561eac1f85e17fc/src/package.json#L56) due to compatibility problems with npm v7. That log line indicates that Etherpad has successfully found the version installed as a dependency, and is not using the host's version.

I just wanted to say, while debugging some serious startup issues on my own system just now, and seeing

> [INFO] plugins - npm --version: 6.14.18

during Etherpad startup, knowing that 

> $ npm --version
> 10.2.0
> 

I was left confused trying to figure out what's going on & what's loading from where...
Maybe (while Etherpad includes this old npm as a dependency, as I understand), this could be expressed clearer during startup, so knobs like me don't panic thinking I'm in some package hell situation again :) ...
