### ISSUE TITLE
How do I setup your project locally into my machine?

### ISSUE THREAD

**Issue by priyanshuSharma-WebDev** [ether/etherpad-lite#4981]
I'm facing some serious issue I don't understand, How do I setup project. Can anybody help me?

**Comment by webzwo0i** [comment]
Please see the README with steps on how to install and start it. The issues here are for bugs. Before you write, please read the [contributing guide](https://github.com/ether/etherpad-lite/blob/develop/CONTRIBUTING.md)

If you want you can post your questions at https://github.com/ether/etherpad-lite/discussions or join our discord channel. I'm sure there are people willing to help, but you need to be more specific.
