### ISSUE TITLE
Pads not working on snopyta.org

### ISSUE THREAD

**Issue by Lady-Awinita** [ether/etherpad-lite#4982]
Etherpad.snopyta.org will not open a new pad or exsiting pads. can data from exsisting pads here be recovered ? The main site is fine, but entering a new pad or trying to open an exsisting pad does not work, it 504 times out

**Comment by webzwo0i** [comment]
afaik we don't run this instance. Please contact the admins of this site.

**Comment by webzwo0i** [comment]
In case the instance is connected to it's database, then it might be possible to request `domain/p/padname/export/etherpad` where padname is the pad you want to export. However, as we don't run this instance, I don't know if this works.
