### ISSUE TITLE
Etherpad version wrong in "Troubleshooting information" (/admin/plugins/info)

### ISSUE THREAD

**Issue by JedMeister** [ether/etherpad-lite#4997]
When viewing Etherpad "Troubleshooting information" (via url `YOUR_DOMAIN/admin/plugins/info`) the version info is incorrect. It currently shows:

```
Etherpad version
Version number: 1.8.13

Latest available version: 1.8.12

Git sha: 5db0c8d
```

**Expected behavior**
Show "Latest available version: 1.8.13"

**Screenshots**

![Plugin information - Etherpad](https://user-images.githubusercontent.com/818633/114008522-ac240680-98a5-11eb-9b97-6c7c79c1d8fb.png)

**Server:**
 - Etherpad version: 1.8.13
 - OS: Debian 10/Buster
 - Node.js version (`node --version`): v14.16.1
 - npm version (`npm --version`): 6.14.12

**Desktop:**
 - OS: Debian 10/Buster
 - Browser: Chrome 
 - Version: 89

**Comment by webzwo0i** [comment]
@Gared What information does https://static.etherpad.org/info.json get its version from? I probably missed to update something on the last release

**Comment by Gared** [comment]
@webzwo0i I update this information manually from time to time. Done it right now. So this information should be up to date now

**Comment by webzwo0i** [comment]
Perfect, thanks! :-)

**Comment by JedMeister** [comment]
Nice work! Thanks guys! :smile: :+1:
