### ISSUE TITLE
authorID and groupID created by API does not exist, in following request

### ISSUE THREAD

**Issue by a-r-m-i-n** [ether/etherpad-lite#5000]
In the past week I've integrated Etherpad Lite to a PHP application. The group pads get created using the API and then I create a session, save the cookie and show the group pad in iframe.

Everything works like charm (when using latest version 1.8.13). I'm using Docker for local development and also for the staging server. On the staging server I had weird API errors.

Basically I'm using those API calls (in this order):
- `createAuthorIfNotExistsFor` -> I get a valid authorID (a.xyz)
- `listSessionsOfAuthor` 

Suddenly I get **error code 4** (which is invalid or missing apikey) with the message "**authorID does not exist**", when calling `listSessionsOfAuthor` route. This only occures for the first time a portal user get in touch with Etherpad API. I was able to reconstruct it with a second user, but then I wasn't able to reproduce it anymore (with other, new users) on Staging environment. Locally I'm entirely unable to reconstruct this issue (with same Docker containers).

Same with:
- `createGroupIfNotExistsFor` -> I get a valid groupID (g.zzz)
- `createGroupPad`

**Error 4: groupID does not exist.**

Just for the records: We are talking about the authorID and groupID, which the API gave me one request earlier. Also, the apikey is given and valid in query params. 

Because this issue does not appear everytime, I guess there is an issue with the database itself (I'm on MySQL)? Concurrent requests, maybe. Do you ever had similar issues? Do I need to add sleep commands between my requests?

For the API requests in PHP I'm using this lib: https://packagist.org/packages/tomnomnom/etherpad-lite-client

Thanks in advance!

**Comment by a-r-m-i-n** [comment]
🎉 #5000

**Comment by a-r-m-i-n** [comment]
Here I got another example:
![image](https://user-images.githubusercontent.com/1275298/114199975-0d56e300-9955-11eb-9652-efc86c3c7dc4.png)

**Comment by webzwo0i** [comment]
Interesting! And congrats for 5000th issue. :-)

I would recommend running etherpad with DEBUG logging enabled (loglevel: DEBUG in settings.json) This should log db queries and tell you if the data is read from cache/dirty cache or database.
The queries are serialized on one connection, so there is no concurrency. Additionally, we use a buffer/cache from which entries are normally served, unless they are served for the first time (then they will hit the database). So in theory, if the problem only happens when you want to get back a value, that you have just written, we probably have a problem with serving dirty values.

**Comment by a-r-m-i-n** [comment]
The issue did not just occure on the first time, I've realized later. The action which displays the iframe always fires several api calls before. To ensure the portal user has a valid session for the requested group pad.

(Only) on this staging environment this issue occure. And it happens randomly. On the same page I press F5, and sometimes I get the autorID exception,  next refresh the groupID is not existing and on the next request, I see the IFrame with contents. This is totally random.

But only on this staging machine, where I don't have direct access to logs and stuff. And with the Docker Compose environment I was unable to reconstruct this issue locally. Maybe the performance of this staging server is just too bad to handle real-time etherpad app.

So I can't provide logs, for now.

**Comment by a-r-m-i-n** [comment]
What made me thinking was the error code 4, which said invalid api key, but the message said other things and the apikey works. Otherwise I wouldn't be able to create an author and get an authorID.
