### ISSUE TITLE
redirect to https

### ISSUE THREAD

**Issue by yjeanrenaud** [ether/etherpad-lite#5017]
* * *

name: Feature request
about: Suggest an idea for this project
title: 'redirect to https'
labels: enhancement
assignees: 

* * *

I find it hard for non-experienced users to teach them to use https:// in front of the etherpad-lite url while having a non-standard port (e.g. 9001) hence the browsers don't fill it in automatically.

**Describe the solution you'd like**
I want to open a second express instance that just redirects to the encrypted one.

**Describe alternatives you've considered**
I know and also realised this via nginx or apache2 reverse proxy, but some people prefer to run etherpad-lite bare with it's native inbuilt ssl support of node.js 

**Additional context**
I wrote some code lines for this, too:
https://github.com/ether/etherpad-lite/compare/develop...yjeanrenaud:patch-1

**Comment by rhansen** [comment]
We recommend using a reverse proxy (such as NGINX) in front of Etherpad. If you do, you can set that up to automatically redirect users to https.

**Comment by yjeanrenaud** [comment]
true. But for some users this is a lot of work to configure a reverse proxy, too.

**Comment by JohnMcLear** [comment]
I don't think adding additional networking logic within Etherpad is a good idea.  Anyone deploying into production will be reverse proxying and/or will go through the effort of setting up the ssl certificate and changing the port to 443.
