### ISSUE TITLE
Etherpad starting successful but not opening ports

### ISSUE THREAD

**Issue by HansM-200** [ether/etherpad-lite#5025]
Hello,

i use an Ubuntu 18.04 Server and tried to install Etherpad 1.8.13 (https://github.com/ether/etherpad-lite/archive/1.8.13.zip) with MySQL DB.
There are some tutorials in web and i did like mentioned. 
I created a new User etherpad with homedir /home/etherpad and in his context i installed nodejs (exporting PATH)  and installed required modules. After all i edited settings.json to activate Mysql, default users and ip/port.
For me the file looks clean an valid. 
My Server is a standardserver with one exception. It is located behind a proxy and there is no easy way to internet, just intranet is possible. This is why the updatecheck at startup fails. even npm needs proxy settings to successful connect to internet.
Here is my startuplog:

```
etherpad@shostname:~/etherpad-lite$ ./src/bin/run.sh
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN prepare removing existing node_modules/ before installation

> wd@1.12.1 install /home/etherpad/etherpad-lite/src/node_modules/wd
> node scripts/build-browser-scripts

added 683 packages in 6.47s
Clearing minified cache...
Starting Etherpad...
[2021-05-06 10:50:00.802] [DEBUG] console - Running on Node v14.16.1 (minimum required Node version: 10.17.0)
[2021-05-06 10:50:00.816] [INFO] console - All relative paths will be interpreted relative to the identified Etherpad base dir: /home/etherpad/etherpad-lite
[2021-05-06 10:50:00.817] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/home/etherpad/etherpad-lite/settings.json"
[2021-05-06 10:50:00.817] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/home/etherpad/etherpad-lite/credentials.json"
[2021-05-06 10:50:00.830] [INFO] console - settings loaded from: /home/etherpad/etherpad-lite/settings.json
[2021-05-06 10:50:00.832] [INFO] console - No credentials file found in /home/etherpad/etherpad-lite/credentials.json. Ignoring.
[2021-05-06 10:50:00.834] [INFO] console - Using skin "colibris" in dir: /home/etherpad/etherpad-lite/src/static/skins/colibris
[2021-05-06 10:50:00.834] [DEBUG] AbsolutePaths - Relative path "./SESSIONKEY.txt" can be rewritten to "/home/etherpad/etherpad-lite/SESSIONKEY.txt"
[2021-05-06 10:50:00.834] [INFO] console - Session key loaded from: /home/etherpad/etherpad-lite/SESSIONKEY.txt
[2021-05-06 10:50:00.835] [INFO] console - Random string used for versioning assets: 085baaf9
[2021-05-06 10:50:01.066] [DEBUG] runCmd - Executing command: npm --version
[2021-05-06 10:50:01.066] [DEBUG] runCmd - cwd: /home/etherpad/etherpad-lite
[2021-05-06 10:50:01.067] [DEBUG] runCmd - PATH=/home/etherpad/etherpad-lite/src/node_modules/.bin:/home/etherpad/etherpad-lite/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/etherpad/nodejs/bin
[2021-05-06 10:50:01.075] [INFO] server - Starting Etherpad...
[2021-05-06 10:50:01.123] [INFO] plugins - Running npm to get a list of installed plugins...
[2021-05-06 10:50:01.124] [DEBUG] runCmd - Executing command: npm ls --long --json --depth=0 --no-production
[2021-05-06 10:50:01.124] [DEBUG] runCmd - cwd: /home/etherpad/etherpad-lite
[2021-05-06 10:50:01.124] [DEBUG] runCmd - PATH=/home/etherpad/etherpad-lite/src/node_modules/.bin:/home/etherpad/etherpad-lite/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/etherpad/nodejs/bin
[2021-05-06 10:50:01.249] [DEBUG] runCmd - Command returned successfully: npm --version
[2021-05-06 10:50:01.249] [INFO] plugins - npm --version: 6.14.11
[2021-05-06 10:50:05.133] [DEBUG] runCmd - Command returned successfully: npm ls --long --json --depth=0 --no-production
[2021-05-06 10:50:05.149] [INFO] plugins - Loaded 0 plugins
[2021-05-06 10:50:05.151] [INFO] server - Installed plugins:
[2021-05-06 10:50:05.151] [DEBUG] server - Installed parts:

[2021-05-06 10:50:05.152] [DEBUG] server - Installed server-side hooks:

[2021-05-06 10:50:05.153] [INFO] server - Etherpad is running
[2021-05-06 10:52:12.236] [ERROR] console - Can not perform Etherpad update check: Error: connect ETIMEDOUT 80.244.243.156:443
```

It tells about successful startup, but with lsof or netstat i can see that it is not opening and listening on port 9001.
I just see successful connection to localhost:mysql and to pluto.server.stefans-entwicklerecke.de which is used for updatecheck i think.
This is the part of my /home/etherpad/etherpad-lite/settings.json:

```
  "ip": "127.0.0.1",
  "port": 9001,
```

This part is not commented out, it is active and has valid values. I cant explain this behaviour. I cant find any error or message in logs.
I tried with different versions of nodejs but it happens all the time.

What can i do now, what have i missed?
Please help and give me some hints.

Thanks,
Hans

**Comment by HansM-200** [comment]
So i tried earlier ep versions and went down to etherpad 1.8.6 which is working. I reused my config etc. and system starts up. I added an apacheproxy in front of the pad and it seems ok. creating new Pads/sharing works.
I think there is something strange in new versions.
I experienced some errormessage if folders have not expected names or if run.sh was not started from expected locations.
old: ./bin/run.sh new: ./src/bin/run.sh
I also had the problem eralier discussed in this page. Adding all required modules manuell or with installdeps.sh, but startup did not find them although "npm ls --long --json --depth=0 --no-production" showing them without problems.
I think basically there is a problem with paths which was introduced.
1.8.6 is woking for me without glitches.

thanks,
Hans

**Comment by webzwo0i** [comment]
Is it possible for one of you two to run git bisect please?

**Comment by tailcat** [comment]
I wish I knew about git bisect before.

50929fe7f7657de8bd8440f6653bdb27d894e616 is the first bad commit
commit 50929fe7f7657de8bd8440f6653bdb27d894e616
Author: Richard Hansen <rhansen@rhansen.org>
Date:   Tue Feb 9 16:46:37 2021 -0500

    express: Call expressConfigure, expressCreateServer hooks asynchronously

 CHANGELOG.md              | 3 ++-
 src/node/hooks/express.js | 7 ++++---
 2 files changed, 6 insertions(+), 4 deletions(-)

**Comment by webzwo0i** [comment]
Okay, thank you!
However, I'm unable to reproduce. Here is a Dockerfile that works for me: (It does not use mysql but I think this is unrelated)
```
FROM ubuntu:20.04
LABEL maintainer="Etherpad team, https://github.com/ether/etherpad-lite"

ENV NODE_ENV=production

ARG EP_HOME=
ARG EP_UID=5001
ARG EP_GID=0
ARG EP_SHELL=
RUN groupadd --system ${EP_GID:+--gid "${EP_GID}" --non-unique} etherpad && \
    useradd --system ${EP_UID:+--uid "${EP_UID}" --non-unique} --gid etherpad \
        ${EP_HOME:+--home-dir "${EP_HOME}"} --create-home \
        ${EP_SHELL:+--shell "${EP_SHELL}"} etherpad
ARG EP_DIR=/opt/etherpad-lite
RUN mkdir -p "${EP_DIR}" && chown etherpad:etherpad "${EP_DIR}"
RUN apt update && apt install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt install -y nodejs
USER etherpad
WORKDIR "${EP_DIR}"
COPY --chown=etherpad:etherpad ./ ./
COPY --chown=etherpad:etherpad ./settings.json.docker "${EP_DIR}"/settings.json
RUN chmod -R g=u .
EXPOSE 9001
CMD ["src/bin/run.sh"]
```

Can you post a Dockerfile that does not work or exact steps to replicate?

**Comment by webzwo0i** [comment]
Just in case: Do you see a symlink in node_modules/ep_etherpad-lite which points to the src directory?

**Comment by webzwo0i** [comment]
@HansM-200 Can you post exact commands to reproduce please

**Comment by tailcat** [comment]
not using docker, just running it from the git clone

**Comment by webzwo0i** [comment]
And the steps you use to install/start etherpad are the same as in my Dockerfile example?

**Comment by tailcat** [comment]
yes except for its node12 but I tried 14 and it still gives the same results.

Updated to the latest version of etherpad and commented the "await Promise.all([" line and its matching end and I am able to run it without problems.

**Comment by HansM-200** [comment]
Hello,

i was able to avoid some problems because they are proxy related.  But basic problem still exists: etherpad tells it is running, but is not opening port 9001.

My way to reproduce:

#adding new user and switch to
useradd -m -s /bin/bash etherpad1
su - etherpad1

#because my proxy is not allowing git i downloaded zip-file directly from webpage and exracted them. 
# i extended PATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/etherpad1/nodejs/bin"

#so its looking like:
etherpad1@myhost:~$ dir
total 25M
drwxr-xr-x  4 etherpad1 etherpad1 4,0K Mai 11 09:06 .
drwxr-xr-x 12 root      root      4,0K Mai 11 09:04 ..
-rw-rw-r--  1 etherpad1 etherpad1 4,4M Mai  5 16:58 1.8.13.zip
-rw-r--r--  1 etherpad1 etherpad1  220 Apr  4  2018 .bash_logout
-rw-r--r--  1 etherpad1 etherpad1 3,8K Nov  4  2019 .bashrc
drwxr-xr-x  7 etherpad1 etherpad1 4,0K Mai 11 09:05 etherpad-lite-1.8.13
drwxr-xr-x  6 etherpad1 etherpad1 4,0K Mai 11 09:05 nodejs
-rw-rw-r--  1 etherpad1 etherpad1  21M Apr  6 19:30 node-v14.16.1-linux-x64.tar.xz
-rw-r--r--  1 etherpad1 etherpad1  807 Apr  4  2018 .profile
etherpad1@myhost:~$ npm --version
6.14.12
etherpad1@myhost:~$ node --version
v14.16.1
etherpad1@myhost:~$

#next is to make sh file executable, they have no executable bit in zip-file
chmod 755 ./src/tests/frontend/travis/runner.sh ./src/tests/frontend/travis/runnerLoadTest.sh ./src/tests/frontend/travis/adminrunner.sh ./src/tests/frontend/travis/runnerBackend.sh ./src/tests/ratelimit/testlimits.sh ./src/bin/cleanRun.sh ./src/bin/plugins/getCorePlugins.sh ./src/bin/plugins/updateCorePlugins.sh ./src/bin/plugins/updateAllPluginsScript.sh ./src/bin/plugins/reTestAllPlugins.sh ./src/bin/updatePlugins.sh ./src/bin/debugRun.sh ./src/bin/installDeps.sh ./src/bin/buildDebian.sh ./src/bin/createRelease.sh ./src/bin/buildForWindows.sh ./src/bin/fastRun.sh ./src/bin/functions.sh ./src/bin/safeRun.sh ./src/bin/run.sh

# i added proxy with auth-settings to npm config to successful download modules
npm config set proxy http://"user:pass"@proxyname:8080

#starting like mentioned in Readme
etherpad1@myhost:~/etherpad-lite-1.8.13$ ./src/bin/run.sh
Copy the settings template to settings.json...
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
src/bin/installDeps.sh: 42: cd: can't cd to ep_etherpad-lite
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/etherpad1/etherpad-lite-1.8.13/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/etherpad1/etherpad-lite-1.8.13/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/etherpad1/.npm/_logs/2021-05-11T07_10_52_452Z-debug.log

#´We see an error because files are missing:
etherpad1@myhost:~/etherpad-lite-1.8.13$ cp src/package-lock.json src/package.json .

#now start again and reach successmessage
etherpad1@myhost:~/etherpad-lite-1.8.13$ ./src/bin/run.sh
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN prepare removing existing node_modules/ before installation

> wd@1.12.1 install /home/etherpad1/etherpad-lite-1.8.13/src/node_modules/wd
> node scripts/build-browser-scripts

added 683 packages in 5.704s
Clearing minified cache...
Starting Etherpad...
[2021-05-11 10:56:45.703] [DEBUG] console - Running on Node v14.16.1 (minimum required Node version: 10.17.0)
[2021-05-11 10:56:45.715] [INFO] console - All relative paths will be interpreted relative to the identified Etherpad base dir: /home/etherpad1/etherpad-lite-1.8.13
[2021-05-11 10:56:45.716] [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/home/etherpad1/etherpad-lite-1.8.13/settings.json"
[2021-05-11 10:56:45.716] [DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/home/etherpad1/etherpad-lite-1.8.13/credentials.json"
[2021-05-11 10:56:45.729] [INFO] console - settings loaded from: /home/etherpad1/etherpad-lite-1.8.13/settings.json
[2021-05-11 10:56:45.730] [INFO] console - No credentials file found in /home/etherpad1/etherpad-lite-1.8.13/credentials.json. Ignoring.
[2021-05-11 10:56:45.731] [INFO] console - Using skin "colibris" in dir: /home/etherpad1/etherpad-lite-1.8.13/src/static/skins/colibris
[2021-05-11 10:56:45.732] [INFO] console - Session key loaded from: /home/etherpad1/etherpad-lite-1.8.13/SESSIONKEY.txt
[2021-05-11 10:56:45.732] [INFO] console - Random string used for versioning assets: b7ae76d4
[2021-05-11 10:56:45.964] [INFO] server - Starting Etherpad...
[2021-05-11 10:56:46.005] [INFO] plugins - Running npm to get a list of installed plugins...
[2021-05-11 10:56:46.117] [INFO] plugins - npm --version: 6.14.11
[2021-05-11 10:56:49.480] [INFO] plugins - Loaded 0 plugins
[2021-05-11 10:56:49.480] [INFO] server - Installed plugins:
[2021-05-11 10:56:49.481] [INFO] server - Etherpad is running

It tells it is running, but there is no listening on port 9001 (i used a working config), it just opened a connection to mysql.

  ├─sshd,1664 -D
  │   ├─sshd,1682
  │   │   └─sshd,1829
  │   │       └─bash,1830
  │   │           └─sudo,2714 -i
  │   │               └─bash,2716
  │   │                   └─su,9577 - etherpad1
  │   │                       └─bash,9578
  │   │                           └─node,9711 src/node/server.js
  │   │                               ├─{node},9723
  │   │                               ├─{node},9724
  │   │                               ├─{node},9725
  │   │                               ├─{node},9726
  │   │                               ├─{node},9727
  │   │                               ├─{node},9728
  │   │                               ├─{node},9736
  │   │                               ├─{node},9737
  │   │                               ├─{node},9738
  │   │                               └─{node},9739


lsof -i
node      9711       etherpad1   19u  IPv4  91729      0t0  TCP localhost:42228->localhost:mysql (ESTABLISHED)
node      9711       etherpad1   21u  IPv4  93981      0t0  TCP myhost:37220->pluto.server.stefans-entwicklerecke.de:https (SYN_SENT)

I also downloaded zip of develeopment version from git, but there is no difference and same problem.

Version 1.8.6 ist still working without problems.

@tailcat 
which file did you edit to comment "await Promise.all([" ? i could try it too.

Thanks,
Hajo

**Comment by webzwo0i** [comment]
Thanks for the detailed steps. I assume you have a problem with your environment. The zip file does include executable bit in the relevant files. Also your second assumption that the package.json is at the wrong place is probably wrong. The zip file contains a symlink in node_modules/ep_etherpad-lite that points to the src directory. If it's not found it creates one. So in your case the symlink is not created which again is probably due to your environment.

What's the version of your zip program? Can you run from the main directory
```
cd node_modules
ln -s ../src ep_etherpad-lite
ls
```
Is the symlink created?

**Comment by webzwo0i** [comment]
Okay sorry. I still think there is something weird going on with the environment of @HansM-200 (it could theoretically be a problem with our zip file, but no symlinks and no executable bit is strange).

However, I'm seeing a similar problem like @tailcat and also confirmed that 50929fe7f7657de8bd8440f6653bdb27d894e616 seems to introduce it. However, I can only trigger the problem with buggy plugins.

@tailcat You don't happen to have any plugins installed, do you? One plugin that I just fixed is ep_hide_referrer.
Can you run the following test for me, please? Remove the changes you made in src/node/hooks/express.js and apply the following patch:
```
diff --git a/src/static/js/pluginfw/hooks.js b/src/static/js/pluginfw/hooks.js
index 89f4267b..593b4f8c 100644
--- a/src/static/js/pluginfw/hooks.js
+++ b/src/static/js/pluginfw/hooks.js
@@ -346,8 +346,15 @@ exports.aCallAll = async (hookName, context, cb = null) => {
   if (cb != null) return await attachCallback(exports.aCallAll(hookName, context), cb);
   if (context == null) context = {};
   const hooks = pluginDefs.hooks[hookName] || [];
+  console.error("hooks to call:",hooks)
   const results = await Promise.all(
-      hooks.map(async (hook) => normalizeValue(await callHookFnAsync(hook, context))));
+      hooks.map(async (hook) => {
+             const res = await callHookFnAsync(hook, context);
+             const normalized = normalizeValue(res);
+             console.log("finished hook",hook.hook_fn_name);
+             return normalized;
+      }));
+       console.log("finished calling hooks")
   return flatten1(results);
 };
```

Then start Etherpad. It should not print "finished calling hooks". Immediatly before the "finished hook...hookname" messages you should see a larger block of hooks from the "hooks to call" message. What I need you to do is compare the list of hook names that have finished ("finished hook...hookname") with the list of hooks that should be called. Which one is missing?

**Comment by HansM-200** [comment]
Hello,

you are right. 
I used mc to unzip files, mc seems to hide some packagecontents like executablebits or symlink.s If i unzip on console package works fine and system starts up like expected.
Iam suprised by behaviour of mc, i use it for some time.  Seems to concern zip-Files, because nodejs is a tar.xz file and was extracted and used without problems and i never saw this problem for other tar-Files.

So my case seems to be solved.

Thank you,
Hans

**Comment by webzwo0i** [comment]
Perfect, thanks for confirming!

I'll leave this open until I here back from @tailcat.

**Comment by rhansen** [comment]
> `[2021-05-11 10:56:49.480] [INFO] plugins - Loaded 0 plugins`

This indicates that the `node_modules/ep_etherpad-lite` symlink is missing.

> confirmed that 50929fe7f7657de8bd8440f6653bdb27d894e616 seems to introduce it. However, I can only trigger the problem with buggy plugins.

Yes, this is certainly due to a buggy plugin.
