### ISSUE TITLE
setHTML and getHTML are not symmetrical (at all)

### ISSUE THREAD

**Issue by stippi** [ether/etherpad-lite#5027]
**Describe the bug**

When I use the setHTML() API to set the contents of a Pad, and immediately afterwards retrieve the contents with getHTML(), the result is completely different from the original input.

**To Reproduce**
1. Invoke the setHTML() API with for example the following contents: `<!DOCTYPE HTML><html><body><p style='style1'>Hello,</p><p style='style2'>world!</p></body></html>`
2. Invoke the getHTML() API. The result for the above input is `<!DOCTYPE HTML><html><body>Hello,<br>world!<br><br></body></html>`

**Expected behavior**
The original input should be preserved.

**Context**
This could be interpreted as a bug or missing feature, or known limitation. I am fully aware that everything may work as intended. I am hoping that you could provide input on how I can work around this. Currently, I am evaluating EtherPad with the following purpose: I have an existing text processing application that lacks any real-time collaboration. What are the options to transfer styled text onto a Pad to work on it temporarily in collaboration, and then transfer that text back from the Pad, preserving "arbitrary meta data"? For this, I would host my own instance of EtherPad and perhaps I would have to write plugin code as well. I am trying to explore my options. Thanks for any input!

**Server (please complete the following information):**
 - Etherpad version: 1.8.13
 - OS: macOS 10.15.7
 - Node.js version (`node --version`): v14.13.0
 - npm version (`npm --version`): 6.14.8

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Not relevant (using API from Java)

**Comment by webzwo0i** [comment]
My first impression is intended behavior re non-symmetrical import/export.

Etherpad internally uses custom HTML so it's not designed to be a HTML editor, but rather a text editor that has a lot of styling functionality. We try to support as much different HTML and markup from text editors like LibreOffice/Word as possible, but we convert it to this custom representation internally. We often convert docx etc. to HTML first (e.g. with LibreOffice's headless converters) and then import it. With one or two deviations, importing and exporting HTML that you exported before should result in nearly the same representation. If not, I would consider it a bug. 

The import capabilities for complex styled HTML might be limited (e.g. parsing style attributes) but I'm +1 for supporting any sane HTML and the infrastructure is there to do this (mainly the contentCollector hooks if it's done as a plugin - however, depending on the HTML it might be a core feature).

I think it depends on how complex and deterministic your HTML is. You could write a custom export or a plugin to save your styling into the database, pull it on export and assemble the HTML you want. So if you don't care that the visual representation is not 100% accurate to what you would expect when viewing the document in a browser (e.g. suppose one of your paragraphs has different margins/padding - should the visual representation reflect this?), I think it's possible to preserve arbitrary meta data in the database and re-use it on export. You could add a class attribute, like `<div class="ace-line"><span class="custom-style1">Hello,</span></div>` where "custom-style1" has no special meaning to Etherpad but is something that you parse during export. (You probably also need some code to stop Etherpad from absorbing those during copy&paste)

Another approach would be to add support for your HTML "dialect", ie make Etherpad understand (and layout) it correctly, ie any styling would end up as an "attribute" in Etherpad (everything like lists, formatting, author information, images etc. is stored as an attribute in Etherpad).

**Comment by stippi** [comment]
Thanks for the detailed reply! On a quick test, the spans with their class don't seem to be preserved in the set/getHTML() cycle. Maybe I am missing something from your explanation.

**Comment by webzwo0i** [comment]
No your understanding is correct. I was not clear enough. Etherpad strips out all "unknown" classes/styles, but this would imo be the fastest way to hook into the logic, ie [contentcollector](https://github.com/ether/etherpad-lite/blob/develop/src/static/js/contentcollector.js)'s hooks [collectContentPre](https://github.com/ether/etherpad-lite/blob/develop/doc/api/hooks_client-side.md#collectcontentpre) and [collectContentPost](https://github.com/ether/etherpad-lite/blob/develop/doc/api/hooks_client-side.md#collectcontentpost) are used during import and [ExportHTML](https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/ExportHtml.js) on export.

When you say "work on styled text", do you mean that it should render the styled text like in a WYSIWYG editor? If yes, then you would need to make Etherpad understand every aspect of it in addition to changing the export to return the HTML you want. If this is not needed, maybe you can just import it as text?
