### ISSUE TITLE
NoScript causes crash

### ISSUE THREAD

**Issue by JustinMogel** [ether/etherpad-lite#5033]
**Describe the bug**
having NoScript Browser Addon in Firefox can cause a crash even if it's deactivated in the tab with etherpad

**To Reproduce**
1. Have NoScript in your Browser
2. Go to https://rich.etherpad.com/ with Firefox and a different Browser
3. type some stuff in both Browsers

**Expected behavior**
no error

**Screenshots**
![BBB notes issue 1](https://user-images.githubusercontent.com/80588280/117979494-42c76580-b333-11eb-9f10-1d6d1081498a.PNG)

**Desktop (please complete the following information):**
 - Browser : Firefox
 - Version 88.0.1

**Additional context**
discovered over BBB, 
https://github.com/bigbluebutton/bigbluebutton/issues/12292

**Comment by webzwo0i** [comment]
Thanks for the report. Unfortunately, I seem to be unable to reproduce on rich.etherpad.com :-( Also I believe rich.etherpad.com uses an old version. What version are you using with BBB and can you test if it works on latest develop and/or 1.8.13?

**Comment by pedrobmarin** [comment]
Hi @webzwo0i ,

BBB is currently running v1.8.13 with some plugins:
- https://github.com/alangecker/bbb-etherpad-plugin
- https://github.com/pedrobmarin/ep_pad_ttl
- https://github.com/mconf/ep_redis_publisher
- https://github.com/ether/ep_sticky_attributes
- https://github.com/ether/ep_cursortrace
- https://github.com/ether/ep_disable_chat

And themed skin:
- https://github.com/alangecker/bbb-etherpad-skin

Would it help if I try to reproduce this on a clean v1.8.13?

**Comment by rhansen** [comment]
> Would it help if I try to reproduce this on a clean v1.8.13?

Please try it on a clean 1.8.14.

**Comment by JohnMcLear** [comment]
Closing as stale.
