### ISSUE TITLE
console error: "Uncaught ReferenceError: require is not defined"

### ISSUE THREAD

**Issue by risacher** [ether/etherpad-lite#5041]
When loading a pad in 1.8.13, I get an error in the Chrome console: "ace2_common.js?callback=require.define&v=17d4f570:1 Uncaught ReferenceError: require is not defined
    at ace2_common.js?callback=require.define&v=17d4f570:1"

Also sometimes:  "ace2_inner.js?callback=require.define&v=17d4f570:1 Uncaught ReferenceError: require is not defined
    at ace2_inner.js?callback=require.define&v=17d4f570:1"

Everything seems to work, as far as I can see.  It's not a big deal, but seems a bit worrisome. 

**Server (please complete the following information):**
 - Etherpad version: 1.8.13
 - OS: Ubuntu 16.04.7 LTS
 - Node.js version (`node --version`): v16.1.0
 - npm version (`npm --version`): 7.12.1, but ep seems to bundle 6.14.13

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser [e.g. chrome, safari] chrome

**Comment by webzwo0i** [comment]
I see this too. It's probably a race after https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace.js#L266, that fetching ace2_inner/ace2_common is executed before the require-kernel is executed.

It should not cause any harm, just a little slow down. Parent issue for reworking this area is https://github.com/ether/etherpad-lite/issues/4820

**Comment by risacher** [comment]
Thanks for the analysis, @webzwo0i.  It didn't seem to affect anything important.  At least now the diagnosis is documented as a (closed) issue.

**Comment by q2apro** [comment]
Hello from 2024. I ran into the same error message, using Etherpad docker. 

Still not resolved?

**Comment by risacher** [comment]
For what it's worth, I don't see this in my recent installs (and I have re-installed recently) so I suspect it's a transient problem.

**Comment by q2apro** [comment]
Are you using Docker? ... The approach of "I don't have the problem." does not help.

**Comment by risacher** [comment]
Yeh, sorry.  My experience may not be relevant.  I do not currently use docker for Etherpad. (Although I do use it for Wordpress, Wekan, Gitea, & Owncloud.)
