### ISSUE TITLE
API performance issues after updating from 1.8.9 to 1.8.13

### ISSUE THREAD

**Issue by iserv-paik** [ether/etherpad-lite#5044]
We have updated to Etherpad Version 1.8.13 and experienced a significant decrease in performance / API requests per second.

We run Etherpad inside a Docker container and use Postgresql 11.12 as a database backend.

I ran `git bisect` on the commits between 1.8.9 (our previous version) and 1.8.13 (where we experienced the problems) and identified the following range of commits to contain the cause of the performance degradation:

https://github.com/ether/etherpad-lite/compare/926f0fcefb5a368bdcc3f030475de37bf47adc38...785b7d2b44fcbebabcb759cf06a7c29c592479da

If I had to guess, I would suspect the following update of the UberDB dependency to be of relevance here:

https://github.com/ether/etherpad-lite/compare/926f0fcefb5a368bdcc3f030475de37bf47adc38...785b7d2b44fcbebabcb759cf06a7c29c592479da#diff-cc5a2f170768969f124108ad3be7fdbcbed774c11774d99a87a3a78fef4ab97bR72

I haven't had the time yet to run a bisect on the changes of that library (https://github.com/ether/ueberDB/compare/v1.3.2...v1.4.4) and we have solved the problem temporarily by staying with 1.8.9 for the time being as well as minimising the number of requests we send to the Etherpad API.

However, we were wondering if you have any idea what could cause our performance problems, or what steps we could to to further debug / investigate this issue.

Thanks a lot in advance and all the best!

**Comment by rhansen** [comment]
See the discussion in #5072. The problem is likely the same: a change in ueberDB is exposing unnecessarily serialized code paths. We'll have to dig through to code to identify those code paths and parallelize them. Which API calls are slow?
