### ISSUE TITLE
Accessing read-only Pads ... sometimes ... returns an ID that cannot be accessed

### ISSUE THREAD

**Issue by ptandler** [ether/etherpad-lite#5062]
**Describe the bug**
We had a couple of pads where we used the API call `getReadOnlyID` to get the read-only version of the pads.
This did work - in most cases. For some pads (I'd guess about 10-15 %) the read-only pad could not be opened.
![grafik](https://user-images.githubusercontent.com/934595/121806209-452d2000-cc4f-11eb-801d-6f4f5f87568b.png)
(translates to "access denied")

When we used `getPadID` with these read-only ID that did not work, we got the error `padID does not exist`.
![grafik](https://user-images.githubusercontent.com/934595/121806307-90dfc980-cc4f-11eb-9ae5-4b28296caa47.png)

We also tried with those pads to get the read-only ID via the "share" button. This did return the same readOnlyID that we got from the API call. 

**To Reproduce**
1. Create a Pad
2. Click on 'share read only'
3. open this read-only pad
4. If you don't get the error message process with step 1 using a different pad name ;-)

**Expected behavior**
Well, the read-only ID should be valid in all cases. ;-)

**Server (please complete the following information):**
 - Etherpad version: 1.8.13
 - OS: Ubuntu 20.04.2
 - Node.js version (`node --version`): v14.16.1
 - npm version (`npm --version`): 6.14.12

**Comment by ptandler** [comment]
This is one of those pads https://pad.teambits.events/p/r.4e93657d53a040d74
I did not find the original pad ID anymore.
In case this would help debugging, I could try to find some of the pairs that were not working.

**Comment by webzwo0i** [comment]
Can you check if applying https://github.com/ether/etherpad-lite/commit/c51f0cc5286e35ad21d0081ffbdc64da8be4f77a fixes the problem?

**Comment by rhansen** [comment]
> Can you check if applying [c51f0cc](https://github.com/ether/etherpad-lite/commit/c51f0cc5286e35ad21d0081ffbdc64da8be4f77a) fixes the problem?

The changes to `src/node/db/SessionStore.js` should be reverted—that file is intentionally using the non-Promisified API (it's calling `DB.db.get()` not `DB.get()`).

**Comment by webzwo0i** [comment]
> The changes to `src/node/db/SessionStore.js` should be reverted—that file is intentionally using the non-Promisified API (it's calling `DB.db.get()` not `DB.get()`).

Thanks. It was even written in the comments of the file...

**Comment by ptandler** [comment]
@webzwo0i I'll check - this means that you could reproduce the problem?

In case it's helpful, here's a simple JSP script we used for testing:

```
<%@ page import="net.gjerull.etherpad.client.EPLiteClient" %>
<%@ page import="java.util.List" %>

<%
//  final String padId = request.getParameter("padId");
  final EPLiteClient etherpadClient = new EPLiteClient("https://pad.teambits.events", "secretApiKey");
  final List<String> padIds = List.of(
    "0_9186b619-3dad-46c1-a34f-44d20ddff54c", //:"r.d1eeddaf075f0076e856cc85149ef54e"
    "0_eb7a4ab0-3e3f-425c-9d95-28ce869138b3", //:"r.437baa9ac9f49da9e2ee626c8c909911"
    "1_60770b71-c7f9-4bd8-87b9-cc0abdd110e8", //:"r.9633012df936a2268c6d647f48de4c97"
    "1_6bed1fdd-1be1-47c1-935c-91f432164dfd", //:"r.969f5ae0e3cfd6b3034a0af5906e5913"
    "1_86920606-648c-4176-88fd-bcda5d29ecb6", //:"r.29b88f205170cede9df4dd8fd461decd"
    "1_b896c097-908a-4449-9a33-94099a1406ed", //:"r.55fbc3ed30f48465af4b36fbbaa9079e"
    "2_09e1e49d-388b-4595-b4db-9e0c6488bfeb", //:"r.e27a02b689ae9ecf0f5f1b47d94610f4"
    "2_8d1328df-4742-44e5-a2e7-4cf2effc42fa", //:"r.b717f97d9c0926ce5d2ebc832be542ab"
    "2_a60d79cc-ac58-4fbb-8b8d-d897e9b6a533", //:"r.e51236c2809ff9ec58b9fb1cca7df946"
    "3_64494de6-4f3e-49cc-99c8-c2e3f680bc27", //:"r.0d4fdbd953d5aa930f6e84f7cde6511a"
    "3_a0f507cc-d2a7-46f5-b796-469e03d55def", //:"r.e417a290bb89597dbc6d8917a1a13498"
    "4_216ee35d-dda9-403f-ad15-c41bfb2031a1", //:"r.9f0e485393b87331e0447a0ac7df260d"
    "4_71989c6d-441d-4a00-b511-78ba4d930f0c", //:"r.3eb0d797a1f2484a349af8ae1d4f0af5"
    "5_50de702f-1602-4505-a5a9-c11227d3f3c3", //:"r.694b1ce904b4ab5f6c62bea2cb23d357"
    "5_a58b7bf1-855f-4ed9-8fe2-18f9cb458112", //:"r.f5725ef199fd7c8d1f87ff886750cc05"
    "6_045d41c3-d3e6-45fa-9ab3-aa0e8148d34c", //:"r.0a9169f07a4caa0d1045dd40472dd8cb"
    "6_7dc26161-07e2-460c-9174-4b2056dbfb07", //:"r.b5e64331bb87c65053a865c35d9608d2"
    "7_6be485b3-aba6-45ce-8372-b507ab781a17", //:"r.738401181886c456c06c3d192f39c1bf"
    "7_cb647395-e40b-4173-9317-254b4289ec52" //, //:"r.e7b44d615db794516058fa90da8c7423"
  );
%>
<table>
  <tr>
    <th>pad id</th>
    <th>read only id</th>
  </tr>
<%
  for (String padId: padIds) {
    final String readOnlyID = (String) etherpadClient.getReadOnlyID(padId).get("readOnlyID");
%>
  <tr>
    <td>
      <a href="https://pad.teambits.events/p/<%= padId %>" target="_blank"><%= padId %></a>
    </td>
    <td>
      <a href="https://pad.teambits.events/p/<%= readOnlyID %>" target="_blank"><%= readOnlyID %></a>
    </td>
  </tr>
<%
  }
%>
</table>
```

**Comment by webzwo0i** [comment]
Couldn't reproduce, but it looks like some kind of race condition because it happens only sometimes, so awaiting the db queries is a good idea. There was a similar bug some weeks ago https://github.com/ether/etherpad-lite/issues/5000

**Comment by webzwo0i** [comment]
There's a API hook for `listAllPads` so in theory you can add this to your script to get a list of *all* readonly/writeable pad mappings. If there are any missing entries when repeatedly calling the script we know that my patch did not fix it.

**Comment by rhansen** [comment]
The changes [discussed above](https://github.com/ether/etherpad-lite/issues/5062#issuecomment-860228401) are now in PR #5106.

**Comment by ptandler** [comment]
PR #5106 is still open, so this shouldn't be closed yet.
