### ISSUE TITLE
"An edit you have made was classified illegal by the synchronization server."

### ISSUE THREAD

**Issue by wlanowski** [ether/etherpad-lite#5067]
**Describe the bug**
If I want to write or change something in my etherpad, I get the following Error:
![1](https://user-images.githubusercontent.com/25705332/121923328-1b512780-cd3b-11eb-8b22-badb4622b4fa.JPG)

I get also the following error in docker log:

```
[33m[2021-06-14 16:03:12.341] [WARN] console - [39mError: ER_NET_PACKET_TOO_LARGE: Got a packet bigger than 'max_allowed_packet' bytes
    at Query.Sequence._packetToError (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/opt/etherpad-lite/src/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/opt/etherpad-lite/src/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/opt/etherpad-lite/src/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at Pool.query (/opt/etherpad-lite/src/node_modules/mysql/lib/Pool.js:199:23)
    at /opt/etherpad-lite/src/node_modules/ueberdb2/databases/mysql_db.js:44:20
    at new Promise (<anonymous>)
    at exports.Database._query (/opt/etherpad-lite/src/node_modules/ueberdb2/databases/mysql_db.js:42:20)
    at exports.Database.set (/opt/etherpad-lite/src/node_modules/ueberdb2/databases/mysql_db.js:141:16)
    at writeOneOp (/opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:559:32)
    at /opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:580:56
    at Array.map (<anonymous>)
    at exports.Database._write (/opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:580:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /opt/etherpad-lite/src/node_modules/ueberdb2/lib/CacheAndBufferLayer.js:515:9
```

**To Reproduce**
- Type in or change something in a existing pad.
- Error occurs
- After click on "Force reconnect" I can change one sign.
- Error occurs again

- Other pads are working
- changing IP-Adress and use "private mode" in browser does not change anything
- Pad is not usable anymore. I have to create a new pad and copy the old data to it

**Expected behavior**
- Error should not occur

**Screenshots**
see above

**Server (please complete the following information):**
 - Etherpad version: 1.8.13
 - OS: Ubuntu 18.04.5 LTS
 - I am using Etherpad as a docker-container etherpad/etherpad (Node-V: 14.16.1; Yarn: 1.22.5)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 89.0

**Comment by webzwo0i** [comment]
Thanks for the bug report. When you say you can add one character after force reconnect, is this character really included after you reconnect again? I suppose it's not.

It could be that you experience two bugs, so I need more information:
One bug (the stacktrace) means that mysql rejects the packet that wants to write the change. In Etherpad (to be more specific: in ueberDB2) we usually collect multiple writes and send them together in one larger write. We call this bulk write. I suggest you enable debug logging in Etherpad so that you can see the database queries.
You can increase the max allowed size of packets in the database or find out the reason why so large queries are sent in the first place (with the help of debug logging). Maybe your pad or the pad's pool is very large or too much queries are collected into the bulk write.

Find instructions to change the allowed size on https://dev.mysql.com/doc/refman/8.0/en/packet-too-large.html

To limit the number of queries that are collected set `bulkLimit` in settings.json's dbSettings section, but I would rather incrase the max allowed packet.

If your illegal changeset bug is not solved by the above, it would be best if you could share the pad. If you don't want to share it publicly, you can send my an email. In case you don't want to share it privately, I can provide you with some more debug logging that you would need to apply to src/node/handler/PadMessageHandler.js

**Comment by wlanowski** [comment]
Hi webtwo0i! I am very happy, that you want to help me!

> When you say you can add one character after force reconnect, is this character really included after you reconnect again? I suppose it's not.

Actually it is. But only one character. If I enter more then one, still one is included

> I suggest you enable debug logging in Etherpad so that you can see the database queries.
How to? I am using the docker container...

> Maybe your pad or the pad's pool is very large or too much queries are collected into the bulk write.
Yes, I know, that the pad is very large. We share images (image_upload plugin) in our pad. We had this experience once. But then I created a new pad and copied the old data. The failure is gone. (Is it possible to "clean up" a pad? I am using 

> it would be best if you could share the pad.
I can not share the pad for privacy reasons. We discuss internal matters in etherpad. I can share the URL of the etherpad-system-URL, if this is helpful.

Here I have a list of all enabled plugins
![1](https://user-images.githubusercontent.com/25705332/121948937-30887f00-cd58-11eb-8f6e-786a014a3001.JPG)

**Comment by webzwo0i** [comment]
> > I suggest you enable debug logging in Etherpad so that you can see the database queries.
> 
> How to? I am using the docker container...

`docker run... -e 'LOGLEVEL=DEBUG' ...`

> > Maybe your pad or the pad's pool is very large or too much queries are collected into the bulk write.
> 
> Yes, I know, that the pad is very large. We share images (image_upload plugin) in our pad. We had this experience once. But then I created a new pad and copied the old data. The failure is gone. (Is it possible to "clean up" a pad? I am using who_did_what, maybe this is too much for the system in combination with the images)

Try to configure image_upload to store the images on disk, not inside the pool. ep_image_upload's documentation describes how to do that. In that case a large amount of space is saved in the pads pool, which is updated on every changeset. This will extremely slow down your instance if you store multiple images in the pool. I wrote a script some days ago, not yet published though, that can move images from pool storage to disk storage.

> > it would be best if you could share the pad.
> 
> I can not share the pad for privacy reasons. We discuss internal matters in etherpad. I can share the URL of the etherpad-system-URL, if this is helpful.

I don't think this is necessary. Can you verify that you store images inside the pool? If yes, I'll make a PR on ep_image_upload in the next days so you could run the script and move the images out of the pool. In the meantime I recommend you increase the max packet size of mysql.

**Comment by webzwo0i** [comment]
One thing to remember: if you happen to have ep_image_upload configured to store images in the pool in the past and you'd uploaded an image to a pad, that you still use, then those image will stay in the pool. So in case you reuse a pad for a long time, adding and removing images from time to time, those images add up space in the pool... So to verify if this is the case, hit the etherpad export at `https://domain/p/yourpad/export/etherpad` and check the file if it contains image blobs in the pool

**Comment by JohnMcLear** [comment]
My assumption here is that the images were being stored in the pad as base64 and when editing a pad (maybe it affected the line that included the image) that the image contents was rewritten causing a large changeset that was larger than the usual allowable edit size.

We can close as it's essentially https://github.com/ether/etherpad-lite/issues/4951
