### ISSUE TITLE
Slow export rate

### ISSUE THREAD

**Issue by dcht00** [ether/etherpad-lite#5072]
Html export rate went from around 50-100/s (before) to around 3-5/s (now).

* Comparing 1.8.6 (50c22f0) and 1.8.13 (7ca336c)
* Same settings.json file, same DB
* neither with any plugins

The instanes share everything, I've tried switching them back and forth, it's consistent.

I also tried
```
loadtest=true
```
And it didn't make any difference.

Changing these parameters to
```
    "windowMs": 10000,
    // maximum number of requests per IP to allow during the rate limit window
    "max": 100000
```
changes nothing of course; if I reduce "max" to 1, EP starts handing out 429's.

Is this expected behaviour? Am I missing some new rate throttling setting?
Thank you :)

Ubuntu 18.04.5 LTS
Node v12.22.1
npm 6.14.12
EP behind an Apache proxy pass
NODE_ENV=production

**Comment by webzwo0i** [comment]
Wow that sounds bad. Non-expected behavior. What database do you use? Is develop also slow?

In case develop is slow, is it possible for you to do a `git bisect`? There might have been ueberdb updates that have a negative impact on performance, but it shouldn't be that large, so we might have to also bisect the different ueberdb versions (pinning the version in package.json).

I did a fast test using mysql backend and it's still pretty fast for me, however I don't have large pads on my test instance.

**Comment by dcht00** [comment]
`
71dfa7070d0a231a1f0e0cfe9188ea5d446da341 is the first bad commit
commit 71dfa7070d0a231a1f0e0cfe9188ea5d446da341

    deps: Update ueberdb2 to get metrics
`
Also, a more adequate measure of the drop is ~18/s to ~4/s, sorry I was going a bit over the thumb. :) Less dramatic but still considerable. 
I've never done a bisect before so thanks for that. Let me know if there's anything else I can do.

**Comment by rhansen** [comment]
I'm guessing https://github.com/ether/ueberDB/commit/fe9ea736b740b01a8417869b0a0db1b360c905bb is the culprit.

Would you be willing to bisect ueberDB between v1.3.2 and v1.4.1? You can delete `etherpad-lite/src/node_modules/ueberdb2` and replace it with a symlink to a clone of the ueberDB repo (or clone the repo into `etherpad-lite/src/node_modules/ueberdb2`).

**Comment by dcht00** [comment]
@rhansen gladly, I tried that but whatever I seem to put there (symlink/own clone) gets overridden with the restart. Do you have any suggestions how to link it there so it sticks?

**Comment by rhansen** [comment]
Make sure you start it with `./src/bin/fastRun.sh`. The normal `run.sh` script re-installs all dependencies; `fastRun.sh` doesn't touch dependencies.

**Comment by dcht00** [comment]
Oh, that was easy, I was poking at package.json and npm didn't like that...
Your guess was correct!

```
fe9ea736b740b01a8417869b0a0db1b360c905bb is the first bad commit
commit fe9ea736b740b01a8417869b0a0db1b360c905bb
Author: Richard Hansen <rhansen@rhansen.org>
Date:   Fri Mar 5 17:05:06 2021 -0500
```

**Comment by rhansen** [comment]
Thanks for investigating. We'll have to do some digging to locate the serial code paths.

How are you exporting to HTML? Did you write a script that iterates over a bunch of pads or something?

**Comment by dcht00** [comment]
Great, thank you! Actually I miswrote, **it's not /html but /txt exports**, don't think it makes a difference though. Correct, I use a syntax for internal links on my pod, and spider it to a graph, via the EP exports. It started timing out with the performance drop.

**Comment by rhansen** [comment]
Do you loop over the URLs serially? If so, does the QPS increase if you attempt to fetch a handful of URLs at a time?

**Comment by webzwo0i** [comment]
I can reproduce now. Non-parallel export is slow, parallel is fast.

**Comment by webzwo0i** [comment]
imo ueberdb is working perfectly. Etherpad is doing additional writes:
- sessioninfo issue https://github.com/ether/etherpad-lite/issues/4898
- https://github.com/ether/etherpad-lite/blob/develop/src/node/db/AuthorManager.js#L155

**Comment by rhansen** [comment]
Thanks for investigating @webzwo0i. Is that second issue easy to fix?

**Comment by webzwo0i** [comment]
Yeah it was, see https://github.com/ether/etherpad-lite/pull/5090

tests indicate that it's now faster, but still not as it was before. will work on the sessionstorage problem today
