### ISSUE TITLE
Text export includes attribs

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#5073]
See https://github.com/ether/etherpad-lite/issues/5071 for details, citing:
> `getText(padID, [rev])`
> works as expected by taking 'rev' into account.
> But it has a different return schema when 'rev' is specified. It wraps the "text" object in another "text" object, and also adds an "attribs" blob.

introduced by commit e7dc0766fdcc3c8477e97c83393fcc2683fab72e

**Comment by JohnMcLear** [comment]
If we already return ``foo.text.text`` we'd also need to return ``foo.text`` when rev is specified so not ideal to duplicate the data, if we dropped ``foo.text.text``it would break existing installs...  I think we should..
1. Also return ``foo.text`` when rev is specified
2. Docs to say to migrate from ``foo.text.text``(when rev is specified) to ``foo.text``
3. Make a new API version that supports ``foo.text`` for when rev is specified & drop the attribs blob

**Comment by JohnMcLear** [comment]
For posterity..  

No rev
127.0.0.1:9001/api/1/getText?apikey=e0c49272bd0a22fce486dbb7d255b76d5c75ce9b9a59682690521cec8a92c88d&padID=foo is my test URI


```
{"code":0,"message":"ok","data":{"text":"hello world\n\nthis world\n\nis real.\n\n\n"}}
```

With rev

http://127.0.0.1:9001/api/1/getText?apikey=e0c49272bd0a22fce486dbb7d255b76d5c75ce9b9a59682690521cec8a92c88d&padID=foo&rev=2

```
{"code":0,"message":"ok","data":{"text":{"text":"hel\n","attribs":"*0+3|1+1"}}}
```

https://github.com/ether/etherpad-lite/tree/jm-bugfix-api-change-text-export-rev-contents can be used for testing.

**Comment by JohnMcLear** [comment]
Please test with: https://github.com/ether/etherpad-lite/pull/5190
