### ISSUE TITLE
ep image upload plugin not working.

### ISSUE THREAD

**Issue by fourcolver** [ether/etherpad-lite#5076]

**Comment by fourcolver** [comment]
I am using the latest etherpad 1.8.13.
And just installed the ep_image_upload plugin.
And updated the settings.json like below image.
But i can't see the upload image icon.
Hope to solve this issue asap.
Thanks.

**Comment by fourcolver** [comment]
![image](https://user-images.githubusercontent.com/52229166/122277020-443bfe80-ce9a-11eb-9242-d24fa521e17b.png)
![image](https://user-images.githubusercontent.com/52229166/122277065-4ef69380-ce9a-11eb-8791-b54be4c0f5e8.png)

**Comment by rhansen** [comment]
Please file a bug with the ep_image_upload plugin maintainers: https://github.com/citizenos/ep_image_upload/issues
