### ISSUE TITLE
exports is not defined in plugin client side script

### ISSUE THREAD

**Issue by alexfrench** [ether/etherpad-lite#5084]
I have a client side plugin script `static/js` as follows. When the pad is loaded it fails with the error "**exports** is undefined". Any suggestions on what might be causing this? Thanks so much. 

```javascript
exports.postAceInit = (hookName, args, cb) => {
 -- do some stuff in here
	cb();
};
```

`ep.json` contains the following:
```json
{
  "parts":[
    {
      "name":"autoscroll",
      "hooks":{
    	  "eejsBlock_scripts":"ep_autoscroll/index"
      },
      "client_hooks":{
    	  "postAceInit":"ep_autoscroll/static/js/index:postAceInit" 
      }
    }
  ]
}
```

**Comment by rhansen** [comment]
Looks OK from the snippet you've pasted. Can you post a link to the full source?

**Comment by alexfrench** [comment]
Thanks Richard! 

Here's my repo. Probably a bunch of stuff that's not needed, as I have been trying to work through issues with NPM 7 at the same time as trying to resolve this issue.

https://github.com/alexfrench/ep_autoscroll

**Comment by rhansen** [comment]
Sent you a pull request: alexfrench/ep_autoscroll#1

**Comment by alexfrench** [comment]
Thanks Richard. Really appreciate your help. Now I know!
