### ISSUE TITLE
importSqlFile.js does not work for very large SQL dumps

### ISSUE THREAD

**Issue by almereyda** [ether/etherpad-lite#5085]
**Describe the bug**

After converting a 2,7 GiB SQLite database to a 1,7 GiB SQL dump, it is not possible to ingest the file with `importSqlFile.js`.

**To Reproduce**

1. Create a large anough SQL dump from an Etherpad instance
2. Run `node importSqlFile.js etherpad.sql`
3. See error

```
[2021-06-17 22:57:04.504] [INFO] console - 0.098        initializing db
[2021-06-17 22:57:04.510] [INFO] console - 0.104        done
[2021-06-17 22:57:04.510] [INFO] console - 0.104        open output file...
/opt/etherpad-lite/src/bin/importSqlFile.js:5
process.on('unhandledRejection', (err) => { throw err; });
                                            ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (buffer.js:605:37)
    at Buffer.toString (buffer.js:804:14)
    at Object.readFileSync (fs.js:438:41)    at /opt/etherpad-lite/src/bin/importSqlFile.js:75:20    at processTicksAndRejections (internal/process/task_queues.js:95:5) {  code: 'ERR_STRING_TOO_LONG'
}
```

**Expected behavior**

The database dump is imported asynchronously, in so Node can parse the file as a stream. As an explanation I like what was said in https://github.com/jprichardson/node-fs-extra/issues/653#issuecomment-449763179:

> You're dealing with a file that is far to large to load into memory at once. We cannot buffer the file for you, etc. because the size of the file is larger than Node.js itself is capable of creating a string for; actually, larger than Node.js is able to store in memory at once as well. You're going to have to use streams to work with such a big file.

Unfortunately I am not knowledgeable enough with JavaScript to turn the code in

https://github.com/ether/etherpad-lite/blob/485538bd79620f254e1088d84abd8658435fe563/src/bin/importSqlFile.js#L75-L95

into an async version. Is it possible to refactor this code in such a way, that the very large SQL dump can be ingested and migrated into the configured ueberDB store?

**Comment by almereyda** [comment]
There are things like

- https://gist.github.com/Luzifer/f73e1d4c158590cd38c8 (go)
- https://stackoverflow.com/a/18700749/1959568 (PHP)

but they don't work on SQL files directly, which in our case is an ubiquituous and nicely generalised exchange format.

**Comment by almereyda** [comment]
@rhansen Thank you for the update in #5087. This actually allowed to read the whole file. For my actual flavour of an SQL dump (from an SQLite database) I had to make the following adjustments to finish successfully with:

```
[2021-06-18 00:49:02.942] [INFO] console - 484.5        finished, imported 3459708 keys.
```

```diff
81,83c81,83
<     if (l.substr(0, 27) === 'REPLACE INTO store VALUES (') {
<       const pos = l.indexOf("', '");
<       const key = l.substr(28, pos - 28);
---
>     if (l.substr(0, 25) === 'INSERT INTO store VALUES(') {
>       const pos = l.indexOf("','");
>       const key = l.substr(26, pos - 26);
85c85
<       value = value.substr(0, value.length - 2);
---
>       value = value.substr(0, value.length - 3);
```

**Comment by rhansen** [comment]
Thanks. I wonder if it's worth modifying the script to accommodate either format.
