### ISSUE TITLE
🚨 Potential Security Vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [ether/etherpad-lite#5094]
Hello, @JohnMcLear @Pita   @rhansen @marcelklehr  - a potential high severity security vulnerability in your repository has been disclosed to huntr.

Visit report url and validate them 
https://huntr.dev/bounties/1624811768438-ether/etherpad-lite/

Report details is only visible to repo-maintainer and reporter

**Comment by webzwo0i** [comment]
Thank you! Please write a mail to security@etherpad.org or contact@etherpad.org (which will be forwarded when John has some minutes) or if you want to my private mail address as seen in my description. I can do releases on this repo, but I'm unable to see the details on huntr.dev. John is on vacation for some month and I'm not sure @rhansen can see the details on huntr either.

**Comment by marcelklehr** [comment]
Ahoy. Since I was mentioned, I tried to see if I can see the details and I turns out I cannot. I can only see a reference to a file. Weird.

**Comment by ranjit-git** [comment]
hi,
only maintainer can see the report details for privacy reason . You need to login using etherpad-repo github account .
Anyway if you are not interested  to signup there then i can sent you the report details via security@etherpad.org.

**Comment by ranjit-git** [comment]
@webzwo0i  just sent the report details to security@etherpad.org via mail

**Comment by webzwo0i** [comment]
Thank you, interesting finding :)
The bug not only affects HTML export, but also Etherpad export. I pushed a possible fix to https://github.com/ether/etherpad-lite/pull/5096 in case you want to verify that it fixes the problem! Test coverage needs to be included, though, which I haven't done yet.

**Comment by ranjit-git** [comment]
Hi,
 Huntr team is sent a magick link to security@etherpad.org to validate the report . Here you dont need to signup . Just using this magick link you can validate the report.

Thanks

**Comment by rhansen** [comment]
Read-only pad IDs are not a substitute for real access controls via `readOnly` and `canCreate` permissions (provided in [`settings.json`](https://github.com/ether/etherpad-lite/blob/b475296cee6d202c8badda1e5432418e5c660880/settings.json.template#L446-L449) or by authentication and authorization plugins such as [ep_readonly_guest](https://github.com/ether/ep_readonly_guest) and [ep_openid_connect](https://github.com/ether/ep_openid_connect)).

Eventually we should remove the read-only pad ID feature or move it to a plugin.

**Comment by webzwo0i** [comment]
Agreed, that it could be a plugin.

Just as randomly generated pad ids, I think random ro ids are an acceptable means for preventing write access. A good number of instances are public and don't use API sessions or external auth, so there is no possibility for users to control access to pads. I'm not sure if there are a lot of access plugins apart from mypads that enable users to control those things. Most plugins seem to need the instance provider to define access control.

I suppose users choose pad ids, that no one can remember, when they don't want others to guess the id and in the same way they are using ro ids, when they want to share a pad, but prevent others from writing.

**Comment by ranjit-git** [comment]
any progress?

**Comment by JohnMcLear** [comment]
Picking back up on this now, hope to have it resolved this week.

**Comment by JohnMcLear** [comment]
Tests available, needs final review and merge in, I bumped @rhansen for this.

**Comment by ranjit-git** [comment]
if bug is fixed plz mark it as valid here https://huntr.dev/bounties/1624811768438-ether/etherpad-lite/ .
Let me know if you have any problem to validate the report there

**Comment by ranjit-git** [comment]
@rhansen 
Hello, as this is  fixed . can you plz mark the report as valid here https://huntr.dev/bounties/1624811768438-ether/etherpad-lite/ .
I will ask huntr team to send a magick link to your email id so that you can verify it without signup .
Thanks

**Comment by ranjit-git** [comment]
security team just sent report magick link to contact@etherpad.org security@etherpad.org . Using this magick link you can validate the report without signup .
@rhansen

**Comment by JamieSlome** [comment]
@rhansen @JohnMcLear - can you confirm that the report disclosed by @ranjit-git is valid and has been fixed? I can go ahead and update the report on our side once we have this confirmation from you?

I assume [70c16bb](https://github.com/ether/etherpad-lite/commit/70c16bb1b562dcfb55f5f3d9de2f9efd2f3d8725) address the concern?

**Comment by ranjit-git** [comment]
@rhansen @marcelklehr 
Can you plz assign a cve for this report
