### ISSUE TITLE
Support square brackets in URL detection

### ISSUE THREAD

**Issue by disturbio** [ether/etherpad-lite#5095]
* * *

name: Feature request
about: Suggest an idea for this project
title: ''Support square brackets in URL detection"
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**

Pads are an useful tool to coordinate between people, where pasting some web application url is common. Some of these web applications (as gitlab) have URLs that contain square brackets. As an example https://gitlab.torproject.org/groups/tpo/core/-/issues?scope=all&utf8=%E2%9C%93&state=opened&label_name[]=For%20Network%20Health%20Team 

While you usually can click in etherpad's auto generated links, this address gets cut in the `[` character, making clicking this link impossible.

**Describe the solution you'd like**

I would like to be able to click such links. `[` and `]` are part of RFC3986 reserved set. There is a test to not allow these characters to be there because they can mess up some markup languages, but the same is the situation with `(` and `)` which are supported.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by webzwo0i** [comment]
+1 I see no reason why not to support this.

**Comment by rhansen** [comment]
Support for square brackets was intentionally removed in PR #2970. My personal preference is to restore support, but I hesitate because someone went to the effort to exclude square brackets and I'm not sure how much undoing that would disrupt users.
