### ISSUE TITLE
MongoDB unusable with Docker image

### ISSUE THREAD

**Issue by laurivosandi** [ether/etherpad-lite#5098]
**Describe the bug**
No way to deploy Etherpad with MongoDB using Docker image

**To Reproduce**
Using Docker image try to deploy Etherpad with MongoDB

**Expected behavior**
Passing `settings.url` from environment variable should be described here https://github.com/ether/etherpad-lite/blob/develop/settings.json.docker#L208

**Screenshots**
```
/opt/etherpad-lite/src/node_modules/ueberdb2/databases/mongodb_db.js:25
    if (!this.settings.url) throw new Error('You must specify a mongodb url');
```

**Comment by rhansen** [comment]
The bug report does not provide enough information. Please file a new bug report with **all** of the information requested in the new bug template.
