### ISSUE TITLE
Frontend tests seem to be cached

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#5100]
Tested with ep_font_size, when I change the contents of frontend test files, I need to restart Etherpad to get a fresh version

**Comment by rhansen** [comment]
I'm able to reproduce if I use the default `minify` and `maxAge` settings (`true` and `21600`, respectively). If I disable minify then it works as expected. Perhaps this is a general (not test-specific) bug in `caching_middleware.js`?

**Comment by webzwo0i** [comment]
OK, I think I'm able to find it then. Will bump if not

**Comment by webzwo0i** [comment]
Bisect identified https://github.com/ether/etherpad-lite/pull/5050/commits/e4f011df760b2eb6cd1142a14a4dbd17c4eed2b6 as the first commit with this behavior.

Before this commit an ETag header was sent and no Cache-Control header. The ETag changed when the test file changed, so the browser receives the most recent version.
Now two things happen:
1. No ETag header is sent anymore, but a Cache-Control header with a max-age based on settings.json's maxAge setting.
2. The file is cached in ./var by caching_middleware.js and files are never updated. Because there is no version string attached in the request, the file is even not updated on restart, unless browser cache is disabled.

**Comment by webzwo0i** [comment]
See https://github.com/ether/etherpad-lite/pull/5102 and https://github.com/ether/etherpad-require-kernel/pull/6
The first is not really helpful, but for clarity (and to save some bytes in browser cache when excessively testing). If you think it's superfluous please reject. :-)
The second is a workaround - it just appends some bytes (based on the date of the request) in case test specs are requested.

**Comment by rhansen** [comment]
What would it take to fix this properly? Fixing this properly would also benefit non-test files too, right?
