### ISSUE TITLE
Problems adding table to pad

### ISSUE THREAD

**Issue by ritesshguptaa** [ether/etherpad-lite#5135]
Hi  @lpagliari , @mjdeslongchamps 
I am facing the same issue, Did you  found any plugin or solution for the same ? 
Please let me know

_Originally posted by @ritesshguptaa in https://github.com/ether/etherpad-lite/issues/3038#issuecomment-888251419_

**Comment by ritesshguptaa** [comment]
https://stackoverflow.com/questions/68558706/sethtml-table-tag-etherpad-lite
 am trying to insert the following HTML using setHTML:

from etherpad_lite import EtherpadLiteClient
import pandas as pd
import numpy as np
import re ,sys, os
dfseg = pd.read_csv("Test.csv")
c = EtherpadLiteClient(base_params={'apikey':'xxxxxxxxxxx'}) #running as service and postgresql


def highlight_cols(s):
    color = 'grey'
    return 'background-color: %s' % color
    
result1= dfseg.to_string()
result = dfseg.to_html()
style1 = dfseg.style.applymap(highlight_cols, subset=pd.IndexSlice[:, ['rep_title', 'cat_title']])
df_html = style1.render()

df_html1 = """<html><head><title>Hello HTML</title> </head><body><p>""" + df_html + """</p></body></html>"""
try:
    c.createPad(padID='TestBFSI26', html=df_html1)
except:
    c.setHTML(padID='TestBFSI26', html=df_html1)
    print("In Except")

I got no errors but when viewing at the pad, I can see all the text that would have been in the table, but the table structure has been stripped out.

BTW I am getting a warning at etherpad console [WARN] console - Ignoring unsupported elements (you might want to install a plugin): style, table, thead, tr, th, tbody, td

Any help would be appreciated.

**Comment by rhansen** [comment]
Etherpad core does not support tables. There are some plugins that attempt to add table support, but I am unfamiliar with them. Please try one of those plugins. If a plugin does not work properly, please file a bug against the plugin.

We are not opposed to improving table support, but none of the Etherpad devs have the time right now to implement it. If you are interested in funding development, let us know.
