### ISSUE TITLE
delete node_module/ep_etherpad-lite and run node src/node/server.js cannot success

### ISSUE THREAD

**Issue by jiutianxuannan** [ether/etherpad-lite#5142]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version:
 - OS: [e.g., Ubuntu 20.04]
 - Node.js version (`node --version`):
 - npm version (`npm --version`):

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by webzwo0i** [comment]
Not sure what your issue is?!
If you remove node_modules/ep_etherpad-lite you need to do `git checkout node_modules/ep_etherpad-lite` afterwards before running `node src/node/server.js`
