### ISSUE TITLE
Notification on existing pads

### ISSUE THREAD

**Issue by tamielbr** [ether/etherpad-lite#5159]
We have to shut down our etherpad service and would like to know if there is a way to notify users of existing pads that the server will shut down and that they need to backup. We modified the initial (new pad) screen, and the welcome message for new pads, but existing pads are a problem. Suggestions of any kind are welcome!

**Comment by webzwo0i** [comment]
Something like https://www.npmjs.com/package/ep_message_all or https://github.com/samirsayyad/ep_custom_header_message ?

**Comment by tamielbr** [comment]
Thanks! The first is very useful, but only seems to work for connected users. It would work if it sent a message to everyone that connects in the future (when someone opens a previous pad). It seems to only work when I manually press the button. I have asked the developer for some pointers of how this might work. The second, I had installed but couldn't see any settings to change or any effect - I have asked in the github page for some instructions.

**Comment by tamielbr** [comment]
Just found how to customize the header message, took a while to pop up. Its on the index.js. Thanks for the tip.
