### ISSUE TITLE
setHTML does not create numbered list correctly

### ISSUE THREAD

**Issue by SVerena** [ether/etherpad-lite#5176]
**Describe the bug**
I am trying to use the setHTML function with numbered lists (`<ol>`) via POST request.
The result is always a list where each line starts with 1, not a sequence. 

**To Reproduce**
try setHTML function with body: 
`<!DOCTYPE HTML><html><body><ol><li>test 1</li><li>test 2</li></ol></body></html>`
or try body (which represents the way that ol is returned when using the getHTML function): 
`<!DOCTYPE HTML><html><body><ol start="1" class="number"><li>test 1</li><li>test 2</li></ol></body></html>`

**Expected behavior**
a numbered list like: 
1. test 1
2. test 2

**Screenshots**
![image](https://user-images.githubusercontent.com/90773676/133438953-33de6fff-0f60-4ef6-9183-1d29c4136bf6.png)
![image](https://user-images.githubusercontent.com/90773676/133439083-804dc56e-10b1-46b4-a966-f3abd1cd62f3.png)
![image](https://user-images.githubusercontent.com/90773676/133439255-7b9b3c87-f9a2-42b2-8a59-32a332062f00.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 93

If you need more information, let me know. 
Thank you!
Verena

**Comment by rhansen** [comment]
Possibly related to #5160. @webzwo0i is our resident list expert. :slightly_smiling_face:

**Comment by JohnMcLear** [comment]
I will look into this, I do think it's a duplicate tho and we have an open PR w/ test coverage

**Comment by SVerena** [comment]
Hello, 
I would like to kindly ask for an update on this bug.
Were you able to work on this already? 
Thank you!

**Comment by JohnMcLear** [comment]
Not yet, thanks for your patience.
