### ISSUE TITLE
Minor style/UX issue: buttons in popups are not discernible

### ISSUE THREAD

**Issue by JustAnotherArchivist** [ether/etherpad-lite#5181]
(From https://github.com/ether/ep_what_have_i_missed/pull/8#issuecomment-921384665, filing here since the style comes from core.)

The popup from that plugin currently looks like this:

![ep_what_have_i_missed_fixed](https://user-images.githubusercontent.com/29556373/133710163-5d1dd055-2db1-4b3c-985a-16032357569f.png)

Here, 'Catch up!' is a clickable button, but that is essentially impossible to see intuitively (e.g. first-time users). My suggestion would be a thin border line and/or a hover background colour change similar to the toolbar.

I only played briefly with a simple `.popup-content button { border: 1px solid; }` rule, which reveals that some margin/padding adjustments would likely also be appropriate:

![ep_what_have_i_missed_border](https://user-images.githubusercontent.com/29556373/133867930-ab0a85f7-e056-4bcf-9255-6a1c4ba48f24.png)

I don't know whether buttons on popups are in use anywhere else nor have I tried other skins.

Etherpad 1.8.14 with `SKIN_VARIANTS='super-dark-toolbar dark-background dark-editor full-width-editor'`, ep_what_have_i_missed 0.0.24, Firefox 92 on Debian Sid

**Comment by JohnMcLear** [comment]
I think this is just a case of adding some CSS for buttons in Core Colibris theme (afaik it's fine in classic), I should be able to handle that.

**Comment by JustAnotherArchivist** [comment]
Another issue bites the dust due to the overzealous stale bot.

As far as I can tell, this hasn't been fixed.

**Comment by rhansen** [comment]
Best way to keep the stale bot from closing an issue is to fix it yourself. :wink:

**Comment by JustAnotherArchivist** [comment]
Or one could avoid using a bot that closes issues simply because they're old, since a bug report being old doesn't mean the bug isn't still present and a problem. Or at least label the ones that have been confirmed so the bot ignores them. 😉
