### ISSUE TITLE
Drag and Drop Files Feature for Etherpad Editor

### ISSUE THREAD

**Issue by kalpna** [ether/etherpad-lite#5185]
* * *

Name: Drag and Drop Files Feature

* * *

**Is your feature request related to a problem? Please describe.**
We require Drag and Drop files feature in Etherpad. The user should be able to drag and drop any type of file like image, video, document etc. We are using etherpad-lite version 1.8.14.

**Describe the solution you'd like**
A plugin/package should add drag and drop feature when user tries to drag and drop any file into the editor.

**Describe alternatives you've considered**
There is no alternative available for this. Please let us know if there is any.

**Plugin?**
An option showing something like 'Drag and Drop your files here' would be great. If not, then dragging and dropping file inside editor should upload the file and display it. 

Please let us know. Thanks!

**Comment by JohnMcLear** [comment]
Please see the available plugins for supporting rich media inc drag and drop.

Visit https://static.etherpad.org/index.html and search for whatever you want to find IE image or video.

**Comment by kalpna** [comment]
![2021-09-23 18_29_43-Etherpad plugins](https://user-images.githubusercontent.com/7778068/134511154-759f905c-d8d9-4bf8-af24-422838a28f58.png)

The plugins here are for **disabling** Drag and Drop. There is no such plugin for file upload. Please let us know. Thanks!

**Comment by JohnMcLear** [comment]
Search for image, or embed, or video

**Comment by kalpna** [comment]
We searched using the keywords mentioned in https://github.com/ether/etherpad-lite/issues/5185#issuecomment-925794892 but there is no such plugin for this. Please share link if you have any. Thanks!

**Comment by JohnMcLear** [comment]
@rhansen are we re-opening this to prompt us to create a hook for drag and drop similar to how we should have a hook for clipboard based events?

**Comment by rhansen** [comment]
I just reopened it because it is a valid plugin request. I'm not sure a new hook is warranted—can't plugins register their own drag and drop event listeners?
