### ISSUE TITLE
Hashtag Feature

### ISSUE THREAD

**Issue by kalpna** [ether/etherpad-lite#5186]
* * *

Name: Hashtag Feature

* * *

**Is your feature request related to a problem? Please describe.**
This request is related to a new feature requirement. When user types hash in editor, it should fetch some JSON/API data and displays list of items. The items list should be like autocomplete, which gets list results based upon user text with hash.

**Describe the solution you'd like**
Similar to somewhat like on github.

**Describe alternatives you've considered**
We checked the package https://github.com/jdittrich/ep_autocomp but its not working. 

**Plugin?**
Yes, plugin will be helpful.

**Comment by JohnMcLear** [comment]
I'd suggest forking https://github.com/jdittrich/ep_autocomp to do what you want.  Currently ep_autocomp looks up against an array of strings, it sounds like you want this array of strings to come from an API.
