### ISSUE TITLE
EmbedMedia - has no issue tab on Github

### ISSUE THREAD

**Issue by lisandi** [ether/etherpad-lite#5192]
The Embedmedia plugin had been moved from https://github.com/redhog/ep_embedmedia to https://github.com/ether/ep_embedmedia but on the later is no issues Tab so that plugin issues could be submitted there.
-  - - 

We installed now a fresh Ubuntu20.04 with all requisites and etherpad-lite and all its requisites.
when installing ep_embedmedia from etherpad/admin/plugins it is installing the plugin
![Screen Shot 2021-09-25 at 20 39 13](https://user-images.githubusercontent.com/1982011/134773690-fca2190a-9b10-4286-816f-6dccd097d94a.png)
and in the frontend it shows up as a left alignment icon

![Screen Shot 2021-09-25 at 20 45 27](https://user-images.githubusercontent.com/1982011/134773725-11dac710-3da0-4208-9290-856418312341.png)
but when clicking on it nothing is working
Not sure how the plugin actually should work as in the description the image shows not even that left alignment icon for the ep_embedmedia.
![Screen Shot 2021-09-25 at 20 40 44](https://user-images.githubusercontent.com/1982011/134773771-810328fb-f80c-43bd-b721-a4d7529823df.png)
Perhaps that House is the embedmedia Icon - not sure what you see in the image

**Comment by JohnMcLear** [comment]
Please don't create plugin issues on core.

**Comment by slel** [comment]
Maybe use the issue tracker at the old Embedmedia repo 

  https://github.com/redhog/ep_embedmedia

until an issue tracker is opened at the new one

  https://github.com/ether/ep_embedmedia

See this issue about improving this situation:

  https://github.com/redhog/ep_embedmedia/issues/12
