### ISSUE TITLE
Underline and clearAuthorship buttons slightly unaligned

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#5193]
After 251cc7ab324d138b3f05d03ee3ef70707321678e the underline and clearauthorship buttons feel like they are slightly misaligned, ie the lower baseline seems to be "below" the baselines of all other icons. The problem is also on beta.etherpad.com. Not sure what's the cause :-(

cc @rhansen

**Comment by JohnMcLear** [comment]
cc @seballot  :)

**Comment by rhansen** [comment]
The culprits:
* underline: https://github.com/ether/etherpad-lite/blob/4637b2b729a480dd5fb8de71546226530de737d5/src/static/css/pad/icons.css#L90
* clear authorship: https://github.com/ether/etherpad-lite/blob/4637b2b729a480dd5fb8de71546226530de737d5/src/static/css/pad/icons.css#L60

Removing the special-case CSS for the clear authorship button looks good to me, but removing the special-case CSS for underline causes the icon to shift too far up. I think it's a flaw in the fontawesome glyph itself.

**Comment by seballot** [comment]
Woops ! didn't saw your PR @rhansen, you are too fast ! removing mine, your's seems okay, thanks ! :)
