### ISSUE TITLE
Etherpad not working on Jitsi IOS App, opening shared document causes endless loading on IPad

### ISSUE THREAD

**Issue by OneTwoBarbecue** [ether/etherpad-lite#5198]
## Description:
When opening a shared document from within the jitsi-meet-app on ipad, the etherpad-interface shows up but results in an endless loading screen without permitting to edit the shared document.
When starting the meeting via safari and opening the meeting via browser everything works fine.
On Android and via PC/laptop/desktop-clients everything works as expected.

This is very likely to be an issue with etherpad since version 1.8.12 is working fine while 1.8.13 shows the issue as well as version 1.8.14.

## Steps to reproduce:
* open Jitsi-meeting inside IOS-app
* try to open shared document
* -> Etherpad shows up with endless loading screen

Expected behavior:
Etherpad should show up allowing edit of shared document

## Actual behavior:
Etherpad loads endlessly

## Server information:
Jitsi Meet version: 2.0.5765
Operating System: Ubuntu 20.04.02
Etherpad version 1.8.13 running on Debian 10 buster
Client information:
Browser / app version: 21.1.0 build 113
Operating System: IOS 14.4.2

## Screenshot
![image](https://user-images.githubusercontent.com/59665779/134814190-e117b026-2f2f-451c-b007-eb769bcbd404.png)

**Comment by rhansen** [comment]
Can you reproduce this directly (without Jitsi)?

**Comment by rhansen** [comment]
Nevermind, you said that it works fine via Safari. I should have read more carefully.

Unfortunately I don't have an iOS device to test this with. Can you use `git bisect` to identify the commit that is causing the problem?

**Comment by OneTwoBarbecue** [comment]
I did trie all versions from 1.8.9 onwards and the issue first occurs when using 1.8.13 .
1.8.12 works fine so the issue is due to the changes in between.

**Comment by JohnMcLear** [comment]
Can you fit bisect to find the offending commit please?  https://mclear.co.uk/2013/04/02/using-git-bisect-to-debug-etherpad-issues/

**Comment by JohnMcLear** [comment]
Bump @OneTwoBarbecue

**Comment by OneTwoBarbecue** [comment]
@JohnMcLear  Thank you very much! I can not bisect this quickly. I am not a developer and I do only use the GitHub web interface. I do my very best to provide you with valuable information.

**Comment by JohnMcLear** [comment]
I understand, please follow the guide step by step and it should be easy enough!

**Comment by OneTwoBarbecue** [comment]
As I only clone repositories and as I‘m not „logged in“ in git on my local vm I am not working on a branch. Additionally it tells me that there are local modifications which would be overwritten so I probably need to use git stash …
So despite your good straight forward tutorial I will learn a bit of git to do so.
I’ll keep that in mind and will do as soon as work and family permits me to.
