### ISSUE TITLE
Admin/Settings - Current Configuration stays blank when rewritten settings.json

### ISSUE THREAD

**Issue by lisandi** [ether/etherpad-lite#5201]
**Describe the bug**
When opening the admin/settings but having set the `--settings /some/path/settings-custom.json` `--credentials /some/path/credentials-custom.json` etc. the settings file does not get displayed in `/admin/settings`.

**To Reproduce**
![Screen Shot 2021-09-27 at 14 29 46](https://user-images.githubusercontent.com/1982011/134877381-7a10f581-ac1c-4e0c-a3ad-6dac4fe01810.png)
**we realized that the `settings.json` file which gets displayed in admin/settings is always the one located in the git/source folder and not the actual one which gets used.**

![Screen Shot 2021-09-27 at 14 26 45](https://user-images.githubusercontent.com/1982011/134877361-4233c6f6-ecc2-4354-836d-5f36c2ce9a0b.png)
**When starting etherpad it shows the folders the settings and the credentials files used are located**

![Screen Shot 2021-09-27 at 14 30 45](https://user-images.githubusercontent.com/1982011/134877386-cf0bdb81-ed72-4085-89a0-f43bf80590c0.png)

**We named the one located in etc/etherpad "Paddy etc"
But when checking in /admin/settings you see "Paddy original" which is the file located in the original location inside the etherpad-lite folder downloaded from GitHub.**

![Screen Shot 2021-09-27 at 14 33 13](https://user-images.githubusercontent.com/1982011/134877391-7a3e0d7b-01e8-42a1-896a-0dc84683a55b.png)

**in the Browser Tab title, you see "Paddy etc" when loading**

![Screen Shot 2021-09-27 at 14 54 56](https://user-images.githubusercontent.com/1982011/134877395-4cde7f59-404e-4ed0-830e-764502793f32.png)

**we counterchecked and changed the Port to 9002 while the Proxy looks for 9001 and the site is gone - or comes back when reenabling 9001 as port - this means it is definitely serving the files shown in the "black" first screenshot and NOT the settings file shown in /admin/settings - all changes you perform there are more or less useless!**

![Screen Shot 2021-09-27 at 15 01 15](https://user-images.githubusercontent.com/1982011/134877401-db3c7671-5844-455d-b949-e5a18e510bad.png)

--

![Screen Shot 2021-09-27 at 15 01 43](https://user-images.githubusercontent.com/1982011/134877403-cf6c07ee-aa9d-43d2-af50-015e909f0058.png)

**Expected behavior**
When opening the admin/settings but having set the --settings /some/path/settings-custom.json --credentials /some/path/credentials-custom.json etc. the settings file should get displayed in admin/settings

**Screenshots**
The admin/settings when using a rewritten settings.json file looks like that:
![Screen Shot 2021-09-28 at 10 43 37](https://user-images.githubusercontent.com/1982011/135023404-5129bd00-fc5c-438c-8f93-ddf9a3d8248f.png)
It stays empty but actually should display the correct settings file so that changes can be made to it from the admin interface.

**Possible Fixes**
Either there is a way to enter the path to the correct settings.json file which then gets displayed in that "Current configuration" window, or the correct file (recommended) gets read automatically and displayed in that area.

**Server (please complete the following information):**
 - Etherpad version: newest updated from git 8.14*
 - OS: [e.g., Ubuntu 20.04]
 - Node.js version (`node --version`):
 - npm version (`npm --version`):

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, OSX]

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS8.1-newest - OSX-newest]

**Additional context**

**Comment by rhansen** [comment]
This should be a simple matter of teaching the admin interface to pay attention to the `--settings` command-line argument. Patches or funding welcome.
