### ISSUE TITLE
underscore-umd.js.map: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by lisandi** [ether/etherpad-lite#5206]
**Describe the bug**
underscore-umd.js.map: Unexpected token < in JSON at position 1

DevTools failed to load source-map: Could not parse content for https://my-domain/pad/p/underscore-umd.js.map: Unexpected token < in JSON at position 1

There seems to be a problem with JSON as it is receiving an Object while looking for JSON

using instead
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify
might be a better way that would eliminate that error.
![Screen Shot 2021-09-29 at 22 41 09](https://user-images.githubusercontent.com/1982011/135302700-29a4b68e-f5f7-4e80-aeee-8ba916837a5b.png)

**Comment by rhansen** [comment]
This will be fixed once we switch to webpack (or similar). See #4820.

This error only appears if you open the developer console. It's also benign.
