### ISSUE TITLE
Capture Selected Text

### ISSUE THREAD

**Issue by ytiwari** [ether/etherpad-lite#5209]
* * *

**Capture selected texts from pad**

* * *

**Is your feature request related to a problem? Please describe.**
I want to capture selected text from the pad and post it using REST API.

**Describe the solution you'd like**
I'm thinking to have an option/button in the toolbar. Once the user selects some text on the pad and clicks the toolbar option.
Once the selected text is captured, I'll call a REST API and will post it.

**Describe alternatives you've considered**
I was looking at this plugin https://www.npmjs.com/package/ep_headings2
In order to find how selected texts are being captured but no success yet.

**Plugin?**
A plugin for this feature can be very helpful

**Comment by webzwo0i** [comment]
`selStart` and `selEnd` of the rep, which you can get with the `ace_getRep` function, gives you the start and end position of selected nodes. So try to search for `selStart` in plugins to find out more.

**Comment by JohnMcLear** [comment]
See ep_define for an example of a plugin that mostly does this.
