### ISSUE TITLE
Plugins from Admin/Plugin list crash sites

### ISSUE THREAD

**Issue by lisandi** [ether/etherpad-lite#5212]
Here is a small list of plugins which do no more exist, show 404 on their repositories or crash the sites completely when installed - like i.e. ep_imageconvert - really no fun! Why are those plugins listed at all?

Empty Repositories
https://github.com/Melody-wu/ep_ice_font_color - This repository is empty.
https://github.com/Melody-wu/ep_ice_font_size - This repository is empty.
https://github.com/Melody-wu/ep_ice_headings - This repository is empty

404 Errors and Hanging up admin/plugins
https://github.com/Melody-wu/ep_dividing_line - 404
https://github.com/Melody-wu/ep_ice_hyperlinks - 404
https://github.com/Melody-wu/ep_ice_image_upload - 404
https://github.com/Melody-wu/ep_ice_insert - 404
https://github.com/Melody-wu/ep_ice_tables - 404
https://www.npmjs.com/package/ep_dividing_line - 404 
https://github.com/JohnMcLear/ep_imageconvert - 404 - hanging up the complete site!

OutDated!
https://www.npmjs.com/package/ep_adminpads

Not a complete list!
There are many more we will test but had to stop because ep_imageconvert caused a major crash here of the etherpads and is not starting anymore. Until we had that one installed the site run normal. - It was the first plugin we tested from the list above to check if they even would install and perhaps have somewhere else a repository in hidden. It downloaded the code but then nothing was working anymore.

I suggest that the List gets completely redone - 
A. taking ALL plugins out and than start listing only those who

1. went through the testing
2. run also on a complete installation with all other plugins which had already been verified as working.
3. plugin authors need to provide a git repository or link to their repository so that the code can be tested and be seen before installation.
4. Authors with empty repositories should no more get listed at all!!!
5. when a plugin hangs up in a site and that gets reported and verified by somebody else should be hidden in that repo list until their problem is again solved.
6. Only plugins which have the standard structure should get listed - i.e. plugins which list templates somewhere else than in the folder templates should not get listed until fixed.
7. Plugins with absolute paths should not get listed until their paths are relative. It took us already days to find many of those.

With a bit more dicipline on the developer site and a bit more sense for building a stable list of plugins that would definitely benefit also etherpad overall.

Here is the list of all plugins we had installed so far without hanging up problems.

Etherpad version
Version number: 1.8.14

Latest available version: 1.8.14

Git sha: d262e31

Installed plugins
ep_aa_file_menu_toolbar
ep_adminpads2
ep_align
ep_announce
ep_author_neat2
ep_author_hover
ep_button_link
ep_author_follow
ep_clear_formatting
ep_comments_page
ep_code_formatting
ep_copy_paste_select_all
ep_custom_inline_toolbar
ep_define
ep_desktop_notifications
ep_embedded_hyperlinks2
ep_embedmedia
ep_etherpad-lite
ep_headings2
ep_font_color
ep_font_family
ep_font_size
ep_image_upload
ep_help_bubbles
ep_markdown
ep_line_spacing
ep_mathjax
ep_padlist2
ep_set_title_on_pad
ep_spellcheck
ep_stats
ep_subscript_and_superscript
ep_table_of_contents
ep_template_content
ep_timestamp
ep_webrtc
ep_workspaces
ep_readonly_guest
Installed parts
ep_readonly_guest/ep_readonly_guest
ep_workspaces/Workspaces
ep_webrtc/ep_webrtc
ep_timestamp/ep_timestamp
ep_template_content/main
ep_table_of_contents/ep_table_of_contents
ep_subscript_and_superscript/main
ep_stats/stats
ep_spellcheck/ep_spellcheck
ep_set_title_on_pad/set_title_on_pad
ep_padlist2/ep_padlist2
ep_mathjax/mathjax
ep_line_spacing/main
ep_markdown/markdown
ep_help_bubbles/help_bubbles
ep_image_upload/ep_image_upload
ep_font_size/main
ep_font_family/main
ep_font_color/main
ep_headings2/main
ep_etherpad-lite/openapi
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/stats
ep_etherpad-lite/express
ep_etherpad-lite/Minify
ep_etherpad-lite/DB
ep_embedmedia/embedmedia
ep_embedded_hyperlinks2/main
ep_desktop_notifications/ep_desktop_notifications
ep_define/ep_define
ep_custom_inline_toolbar/custom_inline_toolbar
ep_copy_paste_select_all/copy_paste_select_all
ep_code_formatting/ep_code_formatting
ep_etherpad-lite/webaccess
ep_comments_page/comments_page
ep_etherpad-lite/static
ep_clear_formatting/clear_formatting
ep_author_follow/ep_author_follow
ep_button_link/button_link
ep_author_hover/ep_author_hover
ep_author_neat2/ep_author_neat2
ep_announce/ep_announce
ep_align/main
ep_adminpads2/ep_adminpads2
ep_aa_file_menu_toolbar/aa_file_menu_toolbar
Installed hooks
Server-side hooks
aceAttribClasses:
ep_font_family:
main:
ep_font_family/index
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/index
asyncLineHTMLForExport:
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/index
authenticate:
ep_readonly_guest:
ep_readonly_guest:
ep_readonly_guest
ccRegisterBlockElements:
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/contentCollection
clientVars:
ep_author_follow:
ep_author_follow:
ep_author_follow/index:clientVars
ep_button_link:
button_link:
ep_comments_page:
comments_page:
ep_comments_page/index
ep_custom_inline_toolbar:
custom_inline_toolbar:
ep_custom_inline_toolbar/index
ep_image_upload:
ep_image_upload:
ep_image_upload/index
ep_readonly_guest:
ep_readonly_guest:
ep_readonly_guest
ep_set_title_on_pad:
set_title_on_pad:
ep_set_title_on_pad/handleMessage
ep_webrtc:
ep_webrtc:
collectContentImage:
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/contentCollection
collectContentPost:
ep_align:
main:
ep_align/static/js/shared
ep_font_color:
main:
ep_font_color/static/js/shared
ep_font_family:
main:
ep_font_family/static/js/shared
ep_headings2:
main:
ep_headings2/static/js/shared
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/contentCollection
ep_mathjax:
mathjax:
ep_mathjax/static/js/shared
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/static/js/shared
collectContentPre:
ep_align:
main:
ep_align/static/js/shared
ep_comments_page:
comments_page:
ep_comments_page/static/js/shared
ep_font_color:
main:
ep_font_color/static/js/shared
ep_font_family:
main:
ep_font_family/static/js/shared
ep_font_size:
main:
ep_font_size/static/js/shared
ep_headings2:
main:
ep_headings2/static/js/shared
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/contentCollection
ep_mathjax:
mathjax:
ep_mathjax/static/js/shared
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/static/js/shared
createServer:
ep_etherpad-lite:
express:
ep_etherpad-lite/node/hooks/express
eejsBlock_adminMenu:
ep_adminpads2:
ep_adminpads2:
ep_adminpads2
eejsBlock_body:
ep_aa_file_menu_toolbar:
aa_file_menu_toolbar:
ep_aa_file_menu_toolbar/eejs
ep_custom_inline_toolbar:
custom_inline_toolbar:
ep_custom_inline_toolbar/index
ep_embedmedia:
embedmedia:
ep_embedmedia/hooks:eejsBlock_body
ep_image_upload:
ep_image_upload:
ep_image_upload/index
ep_set_title_on_pad:
set_title_on_pad:
ep_set_title_on_pad/eejs
ep_stats:
stats:
ep_stats/index
ep_template_content:
main:
ep_template_content/client
eejsBlock_dd_edit:
ep_copy_paste_select_all:
copy_paste_select_all:
ep_copy_paste_select_all/copy_paste_select_all
eejsBlock_dd_format:
ep_clear_formatting:
clear_formatting:
ep_clear_formatting/clear_formatting
ep_font_color:
main:
ep_font_color/index
ep_font_family:
main:
ep_font_family/index
ep_font_size:
main:
ep_font_size/index
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/index
eejsBlock_dd_help:
ep_define:
ep_define:
ep_define/eejs
eejsBlock_dd_view:
ep_spellcheck:
ep_spellcheck:
ep_spellcheck/spellcheck
ep_stats:
stats:
ep_stats/index
ep_table_of_contents:
ep_table_of_contents:
ep_table_of_contents/index
eejsBlock_editbarMenuLeft:
ep_align:
main:
ep_align/index
ep_comments_page:
comments_page:
ep_comments_page/index
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/index
ep_embedmedia:
embedmedia:
ep_embedmedia/hooks:eejsBlock_editbarMenuLeft
ep_font_color:
main:
ep_font_color/index
ep_font_family:
main:
ep_font_family/index
ep_font_size:
main:
ep_font_size/index
ep_headings2:
main:
ep_headings2/index
ep_image_upload:
ep_image_upload:
ep_image_upload/editbar
ep_line_spacing:
main:
ep_line_spacing/index
ep_mathjax:
mathjax:
ep_mathjax/hooks:eejsBlock_editbarMenuLeft
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/index
ep_template_content:
main:
ep_template_content/client
ep_timestamp:
ep_timestamp:
ep_timestamp/timestamp
eejsBlock_editbarMenuRight:
ep_help_bubbles:
help_bubbles:
ep_help_bubbles/static/js/help_bubbles.js:eejsBlock_editbarMenuRight
eejsBlock_editorContainerBox:
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/index
ep_mathjax:
mathjax:
ep_mathjax/hooks:eejsBlock_editorContainerBox
ep_table_of_contents:
ep_table_of_contents:
ep_table_of_contents/index
eejsBlock_exportColumn:
ep_markdown:
markdown:
ep_markdown/index
ep_stats:
stats:
ep_stats/index
eejsBlock_indexWrapper:
ep_padlist2:
ep_padlist2:
ep_padlist2
eejsBlock_mySettings:
ep_author_follow:
ep_author_follow:
ep_author_follow/index
ep_author_hover:
ep_author_hover:
ep_author_hover/index
ep_comments_page:
comments_page:
ep_comments_page/index
ep_custom_inline_toolbar:
custom_inline_toolbar:
ep_custom_inline_toolbar/index
ep_define:
ep_define:
ep_define/eejs
ep_desktop_notifications:
ep_desktop_notifications:
ep_desktop_notifications/desktop_notifications
ep_markdown:
markdown:
ep_markdown/index
ep_set_title_on_pad:
set_title_on_pad:
ep_set_title_on_pad/index
ep_spellcheck:
ep_spellcheck:
ep_spellcheck/spellcheck
ep_stats:
stats:
ep_stats/index
ep_table_of_contents:
ep_table_of_contents:
ep_table_of_contents/index
ep_webrtc:
ep_webrtc:
eejsBlock_permissionDenied:
ep_readonly_guest:
ep_readonly_guest:
ep_readonly_guest
eejsBlock_scripts:
ep_comments_page:
comments_page:
ep_comments_page/index
ep_embedmedia:
embedmedia:
ep_embedmedia/hooks:eejsBlock_scripts
ep_help_bubbles:
help_bubbles:
ep_help_bubbles/static/js/help_bubbles.js:eejsBlock_scripts
ep_markdown:
markdown:
ep_markdown/index
ep_mathjax:
mathjax:
ep_mathjax/hooks:eejsBlock_scripts
ep_stats:
stats:
ep_stats/index
ep_table_of_contents:
ep_table_of_contents:
ep_table_of_contents/index
ep_timestamp:
ep_timestamp:
ep_timestamp/timestamp
eejsBlock_styles:
ep_aa_file_menu_toolbar:
aa_file_menu_toolbar:
ep_aa_file_menu_toolbar/eejs
ep_comments_page:
comments_page:
ep_comments_page/index
ep_custom_inline_toolbar:
custom_inline_toolbar:
ep_custom_inline_toolbar/index
ep_embedmedia:
embedmedia:
ep_embedmedia/hooks:eejsBlock_styles
ep_help_bubbles:
help_bubbles:
ep_help_bubbles/static/js/help_bubbles.js:eejsBlock_styles
ep_image_upload:
ep_image_upload:
ep_image_upload/index
ep_mathjax:
mathjax:
ep_mathjax/hooks:eejsBlock_styles
ep_stats:
stats:
ep_stats/index
ep_table_of_contents:
ep_table_of_contents:
ep_table_of_contents/index
ep_template_content:
main:
ep_template_content/client
ep_timestamp:
ep_timestamp:
ep_timestamp/timestamp
ep_webrtc:
ep_webrtc:
eejsBlock_userlist:
ep_readonly_guest:
ep_readonly_guest:
ep_readonly_guest
exportEtherpadAdditionalContent:
ep_comments_page:
comments_page:
ep_comments_page/index
exportFileName:
ep_set_title_on_pad:
set_title_on_pad:
ep_set_title_on_pad/index
exportHTMLAdditionalContent:
ep_comments_page:
comments_page:
ep_comments_page/exportHTML
exportHtmlAdditionalTags:
ep_font_family:
main:
ep_font_family/index
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/index
exportHtmlAdditionalTagsWithData:
ep_comments_page:
comments_page:
ep_comments_page/exportHTML
ep_font_color:
main:
ep_font_color/exportHTML
ep_font_size:
main:
ep_font_size/exportHTML
expressCloseServer:
ep_etherpad-lite:
socketio:
ep_etherpad-lite/node/hooks/express/socketio
expressConfigure:
ep_etherpad-lite:
webaccess:
ep_etherpad-lite/node/hooks/express/webaccess
ep_image_upload:
ep_image_upload:
ep_image_upload/index
expressCreateServer:
ep_adminpads2:
ep_adminpads2:
ep_adminpads2
ep_comments_page:
comments_page:
ep_comments_page/index
ep_etherpad-lite:
admin:
ep_etherpad-lite/node/hooks/express/admin
adminplugins:
ep_etherpad-lite/node/hooks/express/adminplugins
adminsettings:
ep_etherpad-lite/node/hooks/express/adminsettings
apicalls:
ep_etherpad-lite/node/hooks/express/apicalls
errorhandling:
ep_etherpad-lite/node/hooks/express/errorhandling
i18n:
ep_etherpad-lite/node/hooks/i18n
importexport:
ep_etherpad-lite/node/hooks/express/importexport
openapi:
ep_etherpad-lite/node/hooks/express/openapi
padurlsanitize:
ep_etherpad-lite/node/hooks/express/padurlsanitize
socketio:
ep_etherpad-lite/node/hooks/express/socketio
specialpages:
ep_etherpad-lite/node/hooks/express/specialpages
static:
ep_etherpad-lite/node/hooks/express/static
tests:
ep_etherpad-lite/node/hooks/express/tests
ep_markdown:
markdown:
ep_markdown/express
ep_padlist2:
ep_padlist2:
ep_padlist2
ep_readonly_guest:
ep_readonly_guest:
ep_readonly_guest
ep_stats:
stats:
ep_stats/express
ep_workspaces:
Workspaces:
ep_workspaces/js/express.js
getLineHTMLForExport:
ep_align:
main:
ep_align/index
ep_comments_page:
comments_page:
ep_comments_page/exportHTML
ep_font_color:
main:
ep_font_color/exportHTML
ep_font_family:
main:
ep_font_family/index
ep_font_size:
main:
ep_font_size/exportHTML
ep_headings2:
main:
ep_headings2/index
ep_image_upload:
ep_image_upload:
ep_image_upload/exportHTML
handleMessage:
ep_define:
ep_define:
ep_define/handleMessage
ep_readonly_guest:
ep_readonly_guest:
ep_readonly_guest
ep_set_title_on_pad:
set_title_on_pad:
ep_set_title_on_pad/handleMessage
ep_webrtc:
ep_webrtc:
handleMessageSecurity:
ep_comments_page:
comments_page:
ep_comments_page/index
import:
ep_markdown:
markdown:
ep_markdown/index
loadSettings:
ep_button_link:
button_link:
ep_custom_inline_toolbar:
custom_inline_toolbar:
ep_custom_inline_toolbar/index
ep_image_upload:
ep_image_upload:
ep_image_upload/settings
ep_readonly_guest:
ep_readonly_guest:
ep_readonly_guest
ep_webrtc:
ep_webrtc:
padCopy:
ep_comments_page:
comments_page:
ep_comments_page/index
padCreate:
ep_adminpads2:
ep_adminpads2:
ep_adminpads2
padInitToolbar:
ep_align:
main:
ep_align/index
ep_code_formatting:
ep_code_formatting:
ep_code_formatting/index
ep_comments_page:
comments_page:
ep_comments_page/index
ep_custom_inline_toolbar:
custom_inline_toolbar:
ep_custom_inline_toolbar/index
ep_font_color:
main:
ep_font_color/index
ep_font_size:
main:
ep_font_size/index
ep_line_spacing:
main:
ep_line_spacing/index
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/index
padRemove:
ep_adminpads2:
ep_adminpads2:
ep_adminpads2
ep_comments_page:
comments_page:
ep_comments_page/index
ep_image_upload:
ep_image_upload:
ep_image_upload/index
preAuthorize:
ep_readonly_guest:
ep_readonly_guest:
ep_readonly_guest
restartServer:
ep_etherpad-lite:
express:
ep_etherpad-lite/node/hooks/express
shutdown:
ep_etherpad-lite:
DB:
ep_etherpad-lite/node/db/DB
express:
ep_etherpad-lite/node/hooks/express
Minify:
ep_etherpad-lite/node/utils/Minify
stats:
ep_etherpad-lite/node/stats
socketio:
ep_adminpads2:
ep_adminpads2:
ep_adminpads2
ep_comments_page:
comments_page:
ep_comments_page/index
ep_etherpad-lite:
adminplugins:
ep_etherpad-lite/node/hooks/express/adminplugins
adminsettings:
ep_etherpad-lite/node/hooks/express/adminsettings
socketio:
ep_etherpad-lite/node/handler/PadMessageHandler
ep_webrtc:
ep_webrtc:
:setSocketIO
ep_workspaces:
Workspaces:
ep_workspaces/js/socketio.js
stylesForExport:
ep_font_color:
main:
ep_font_color/exportHTML
ep_font_size:
main:
ep_font_size/exportHTML
ep_headings2:
main:
ep_headings2/index
ep_image_upload:
ep_image_upload:
ep_image_upload/exportHTML
Client-side hooks
aceAttribClasses:
ep_code_formatting:
ep_code_formatting:
ep_code_formatting/static/js/index
ep_font_family:
main:
ep_font_family/static/js/index
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/static/js/index
aceAttribsToClasses:
ep_align:
main:
ep_align/static/js/index
ep_code_formatting:
ep_code_formatting:
ep_code_formatting/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_embedmedia:
embedmedia:
ep_embedmedia/static/js/hooks:aceAttribsToClasses
ep_font_color:
main:
ep_font_color/static/js/index
ep_font_family:
main:
ep_font_family/static/js/index
ep_font_size:
main:
ep_font_size/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/clientHooks
ep_line_spacing:
main:
ep_line_spacing/static/js/index
ep_mathjax:
mathjax:
ep_mathjax/static/js/hooks:aceAttribsToClasses
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/static/js/index
aceCreateDomLine:
ep_code_formatting:
ep_code_formatting:
ep_code_formatting/static/js/index
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_embedmedia:
embedmedia:
ep_embedmedia/static/js/hooks:aceCreateDomLine
ep_font_color:
main:
ep_font_color/static/js/index
ep_font_size:
main:
ep_font_size/static/js/index
ep_mathjax:
mathjax:
ep_mathjax/static/js/hooks:aceCreateDomLine
aceDomLineProcessLineAttributes:
ep_align:
main:
ep_align/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/clientHooks
ep_line_spacing:
main:
ep_line_spacing/static/js/index
aceEditEvent:
ep_align:
main:
ep_align/static/js/index
ep_author_neat2:
ep_author_neat2:
ep_author_neat2/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_font_family:
main:
ep_font_family/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
ep_stats:
stats:
ep_stats/static/js/stats
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/static/js/index
ep_table_of_contents:
ep_table_of_contents:
ep_table_of_contents/static/js/aceEditEvent:aceEditEvent
aceEditorCSS:
ep_code_formatting:
ep_code_formatting:
ep_code_formatting/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_custom_inline_toolbar:
custom_inline_toolbar:
ep_custom_inline_toolbar/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_font_family:
main:
ep_font_family/static/js/index
ep_font_size:
main:
ep_font_size/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/clientHooks
ep_markdown:
markdown:
ep_markdown/static/js/markdown
aceInitialized:
ep_align:
main:
ep_align/static/js/index
ep_button_link:
button_link:
ep_button_link/static/js/main:postAceInit
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_custom_inline_toolbar:
custom_inline_toolbar:
ep_custom_inline_toolbar/static/js/index
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_font_size:
main:
ep_font_size/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/clientHooks
ep_line_spacing:
main:
ep_line_spacing/static/js/index
ep_mathjax:
mathjax:
ep_mathjax/static/js/hooks:aceInitialized
aceInitInnerdocbodyHead:
ep_embedmedia:
embedmedia:
ep_embedmedia/static/js/hooks:aceInitInnerdocbodyHead
ep_mathjax:
mathjax:
ep_mathjax/static/js/hooks:aceInitInnerdocbodyHead
acePostWriteDomLineHTML:
ep_author_neat2:
ep_author_neat2:
ep_author_neat2/static/js/index
aceRegisterBlockElements:
ep_align:
main:
ep_align/static/js/index
ep_font_family:
main:
ep_font_family/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/clientHooks
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/static/js/index
aceSelectionChanged:
ep_code_formatting:
ep_code_formatting:
ep_code_formatting/static/js/index
ep_custom_inline_toolbar:
custom_inline_toolbar:
ep_custom_inline_toolbar/static/js/index
aceSetAuthorStyle:
ep_author_neat2:
ep_author_neat2:
ep_author_neat2/static/js/index
ccRegisterBlockElements:
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/contentCollection
chatNewMessage:
ep_desktop_notifications:
ep_desktop_notifications:
ep_desktop_notifications/static/js/desktop_notifications:chatNewMessage
collectContentImage:
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/contentCollection
collectContentPost:
ep_code_formatting:
ep_code_formatting:
ep_code_formatting/static/js/index
ep_font_family:
main:
ep_font_family/static/js/shared
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/contentCollection
ep_line_spacing:
main:
ep_line_spacing/static/js/shared
ep_mathjax:
mathjax:
ep_mathjax/static/js/shared
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/static/js/shared
collectContentPre:
ep_align:
main:
ep_align/static/js/shared
ep_code_formatting:
ep_code_formatting:
ep_code_formatting/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/shared
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/shared
ep_font_family:
main:
ep_font_family/static/js/shared
ep_font_size:
main:
ep_font_size/static/js/shared
ep_headings2:
main:
ep_headings2/static/js/shared
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/contentCollection
ep_line_spacing:
main:
ep_line_spacing/static/js/shared
ep_mathjax:
mathjax:
ep_mathjax/static/js/shared
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/static/js/shared
handleClientMessage_ACCEPT_COMMIT:
ep_author_follow:
ep_author_follow:
ep_author_follow/static/js/follow:handleClientMessage_ACCEPT_COMMIT
ep_table_of_contents:
ep_table_of_contents:
ep_table_of_contents/static/js/aceEditEvent:aceEditEvent
handleClientMessage_CUSTOM:
ep_define:
ep_define:
ep_define/static/js/index
ep_set_title_on_pad:
set_title_on_pad:
ep_set_title_on_pad/static/js/index
handleClientMessage_NEW_CHANGES:
ep_author_follow:
ep_author_follow:
ep_author_follow/static/js/follow:handleClientMessage_NEW_CHANGES
ep_table_of_contents:
ep_table_of_contents:
ep_table_of_contents/static/js/aceEditEvent:aceEditEvent
handleClientMessage_RTC_MESSAGE:
ep_webrtc:
ep_webrtc:
ep_webrtc/static/js
postAceInit:
ep_aa_file_menu_toolbar:
aa_file_menu_toolbar:
ep_aa_file_menu_toolbar/static/js/index:documentReady
ep_align:
main:
ep_align/static/js/index
ep_announce:
ep_announce:
ep_announce/static/js/announce:announce.postAceInit
ep_author_follow:
ep_author_follow:
ep_author_follow/static/js/follow:postAceInit
ep_author_hover:
ep_author_hover:
ep_author_hover/static/js/index
ep_author_neat2:
ep_author_neat2:
ep_author_neat2/static/js/index
ep_clear_formatting:
clear_formatting:
ep_clear_formatting/static/js/clear_formatting
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_copy_paste_select_all:
copy_paste_select_all:
ep_copy_paste_select_all/static/js/copy_paste_select_all
ep_custom_inline_toolbar:
custom_inline_toolbar:
ep_custom_inline_toolbar/static/js/index
ep_define:
ep_define:
ep_define/static/js/index:postAceInit
ep_desktop_notifications:
ep_desktop_notifications:
ep_desktop_notifications/static/js/desktop_notifications:postAceInit
ep_embedded_hyperlinks2:
main:
ep_embedded_hyperlinks2/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_font_family:
main:
ep_font_family/static/js/index
ep_font_size:
main:
ep_font_size/static/js/index
ep_headings2:
main:
ep_headings2/static/js/index
ep_line_spacing:
main:
ep_line_spacing/static/js/index
ep_markdown:
markdown:
ep_markdown/static/js/markdown
ep_mathjax:
mathjax:
ep_mathjax/static/js/hooks:postAceInit
ep_set_title_on_pad:
set_title_on_pad:
ep_set_title_on_pad/static/js/index:documentReady
ep_spellcheck:
ep_spellcheck:
ep_spellcheck/static/js/spellcheck:postAceInit
ep_stats:
stats:
ep_stats/static/js/stats
ep_subscript_and_superscript:
main:
ep_subscript_and_superscript/static/js/index
ep_table_of_contents:
ep_table_of_contents:
ep_table_of_contents/static/js/postAceInit:postAceInit
ep_template_content:
main:
ep_template_content/static/js/index
ep_timestamp:
ep_timestamp:
ep_timestamp/static/js/postAceInit:postAceInit
ep_webrtc:
ep_webrtc:
ep_webrtc/static/js
postToolbarInit:
ep_align:
main:
ep_align/static/js/index
ep_code_formatting:
ep_code_formatting:
ep_code_formatting/static/js/index
ep_comments_page:
comments_page:
ep_comments_page/static/js/index
ep_custom_inline_toolbar:
custom_inline_toolbar:
ep_custom_inline_toolbar/static/js/index
ep_font_color:
main:
ep_font_color/static/js/index
ep_font_size:
main:
ep_font_size/static/js/index
ep_image_upload:
ep_image_upload:
ep_image_upload/static/js/toolbar
ep_readonly_guest:
ep_readonly_guest:
ep_readonly_guest/static/js/client
userJoinOrUpdate:
ep_announce:
ep_announce:
ep_announce/static/js/announce:announce.userJoinOrUpdate
ep_webrtc:
ep_webrtc:
ep_webrtc/static/js
userLeave:
ep_announce:
ep_announce:
ep_announce/static/js/announce:announce.userLeave
ep_webrtc:
ep_webrtc:
ep_webrtc/static/js

**Comment by JohnMcLear** [comment]
Closing as I directed OP to go through a process of isolating which plugin crashes his instance.

**Comment by webzwo0i** [comment]
@lisandi https://github.com/ether/plugin-loader/issues is the code that generates the file that serves the plugin list

**Comment by lisandi** [comment]
@webzwo0i Danke fuer den Link - sehr hilfreich!
