### ISSUE TITLE
Issue using setHTML

### ISSUE THREAD

**Issue by ytiwari** [ether/etherpad-lite#5218]
**Describe the bug**
I'm trying to add some text boxes using /setHTML but it's not adding. However, I see text etc added but no <input type="text />
`<br /> <strong>` these tags are workign fine.
Is this not allowed or there is any restriction?

Thanks!

**Comment by JohnMcLear** [comment]
Please provide exact steps to replicate.  If you are using an API please provide a demo gist.

**Comment by ytiwari** [comment]
@JohnMcLear 
![image](https://user-images.githubusercontent.com/1473339/135807745-6fdf5d98-33b9-4ebf-8e47-ac8df1de22ed.png)

` html: "<!Doctype html><html lang='en'><head><title>Template</title><meta charset='utf-8'></head><body><strong>Agenda</strong><br /><span>"+projectId+"</span><form name='tfrm'><input type='text' value='input text'/></form><br /><br />Short Description<br /><br /><strong>Data to Review</strong><br /><ul><li>Review item</li><li>Review item</li></ul><br /><strong>Updates Roundtable</strong><br /><ul><li>List update</li><li>List update</li></ul><br /><strong>Discussion Topics</strong><br /><br /><strong>Action Items</strong><br /></body></html>",`

**Comment by JohnMcLear** [comment]
Can you provide a gist or code that can replicate this issue?  Not just the html but the logic for posting to the api too?

For examples you can see the backend test code files.

**Comment by JohnMcLear** [comment]
Also do you see anything in server console?  Afaik we issue a warning for unsupported elements

**Comment by ytiwari** [comment]
No error in server console>>
![image](https://user-images.githubusercontent.com/1473339/135810485-dc1ca732-858b-4ccd-ae3b-59414f306d9e.png)

Etherpad version is>>**1.8.14**
![image](https://user-images.githubusercontent.com/1473339/135811368-92ba36ff-dec4-4f32-b58e-5e423b1aed86.png)

Using this package to call API for Etherpad version 1.8.14 setup
https://www.npmjs.com/package/etherpad-lite-client

**Comment by JohnMcLear** [comment]
Form, input and checkbox are not supported by core.  Checkbox would maybe suit ep_tasklist.  

ol ul li b i s are supported in core.
H1 sub sup et Al are supported by plugins.

So if you want form inputs or checkbox look at plugins but you might find no plugin support for them.  I don't ever recall seeing those three being supported but there are loads of plugins so I might have missed it!
