### ISSUE TITLE
Modifing ep_tables4 plugin so tables could be exported to html, pdf, word, odf

### ISSUE THREAD

**Issue by lauri-aloauri** [ether/etherpad-lite#5236]
Hello 
At the moment in Etherpad Lite its not possible export  correctly etherpad pad if there is inserted tables.

Modifing existing ep_tables4 plugin so tables could be exported to html, pdf, word, odf. I added zipped html file and pdf for example
[testing (8).zip](https://github.com/ether/etherpad-lite/files/7362527/testing.8.zip)
[testing (6).pdf](https://github.com/ether/etherpad-lite/files/7362534/testing.6.pdf)

I think that it useful functionality to be able export pads with tables to other documents escpecially html and pdf

Lauri

**Comment by JohnMcLear** [comment]
Not my plugin.  Please create the issue on the plugin depository.
