### ISSUE TITLE
Cannot change Users Popup HTML from pad.html

### ISSUE THREAD

**Issue by kalpna** [ether/etherpad-lite#5257]
Hi Team,

I need to make some HTML changes to Users Popup. 

etherpad-lite: v1.8.14

In code, it displays its HTML in src\templates\pad.html but there is not impact if I make any HTML change in it and restart start.bat file. 

Please let me know from where it can be accessed to make changes. Thanks!

**Comment by JohnMcLear** [comment]
Hi.  To make changes you should make a plugin.  See other plugins for reference.  Https://static.etherpad.org
