### ISSUE TITLE
Uncaught ReferenceError: require is not defined 

### ISSUE THREAD

**Issue by adamprocter** [ether/etherpad-lite#5259]
A number of my older pads don't load with the following error, I am unsure if it because I had older plug-ins for markdown and such or if I need to do something else ?  Any help appreciated 

This is one that fails

Error: Failed assertion: Invalid changeset (checkRep failed)
at http://etherpad.adamprocter.co.uk:9001/static/js/require-kernel.js?v=92b37a8d line 10 > Function at line 19
ErrorId: 0NpYDBbAB4AwrhdfRqs4
Unhandled Promise rejection
URL: http://etherpad.adamprocter.co.uk:9001/p/3games2018

**Comment by JohnMcLear** [comment]
Please provide required info as per issue template ie version number, os...

**Comment by rhansen** [comment]
Also, please provide the full stack trace. (It should be in your server logs.)
