### ISSUE TITLE
Warning: "DirtyDB is used." although settings.json doesn't declare dirty use.

### ISSUE THREAD

**Issue by schmolmo** [ether/etherpad-lite#5262]
hey there,

i'm geting the following error in every new pad after a fresh install of etherpad 1.8.14: 
`Warning: DirtyDB is used. This is not recommended for production.`
i firstly uncommented, then also deleted the 

```
"dbType": "dirty",
  "dbSettings": {
    "filename": "var/dirty.db"
  },
```

section in the settings.json file. 
do you have any ideas to what i could be doing wrong?

all the best,
schmolmo

**Comment by JohnMcLear** [comment]
Are you sure you are editing ``settings.json`` ?  Are you using MySQL/Postgres etc?  What database are you actually using if not Dirty?

**Comment by schmolmo** [comment]
i’m pretty sure, yes, as all my other changes have effect… i’m using a mysql database :-)

**Comment by JohnMcLear** [comment]
Can you see edits/sessions in your mysql database?

**Comment by schmolmo** [comment]
ahhh... i still had my mysql-settings commented out... everything's working now, thank you for your help!
