### ISSUE TITLE
Timeslider breaks after 1000 revisions on HTML imported pads

### ISSUE THREAD

**Issue by davue** [ether/etherpad-lite#5271]
**Tested on:**
- Etherpad: 1.8.14
- Browsers: Chrome 94.0.4606.81 and Firefox 94.0.1
- Clients: Private instance and rich.etherpad.com
- Node: 12.18.0

**Steps to reproduce:**
1. Create a new pad and fill it with some content
2. Export the pad as HTML
3. Create a second pad and import the HTML from the first pad
4. Create enough changes to make more than 1000 revisions

**What I expected to happen:**
The timeslider would work normally

**What actually happened:**
Revisions after 1000 are working but all revisions < 1000 simply show the content of revision 1000.

**Additional Information**
- Also affects pads which were edited by the `/setHTML` API endpoint (which we internally use for applying templates)
- Most likely related to #5214
- You can see the bug in action here (as long as the pad is kept alive): https://rich.etherpad.com/p/test3

**Comment by JohnMcLear** [comment]
FWIW we have test coverage for this so how this is not functioning boggles me -_- Will try dig up the test coverage..

**Comment by webzwo0i** [comment]
Could you test if applying https://github.com/ether/etherpad-lite/pull/5253 fixes this problem?

**Comment by davue** [comment]
Nope, this sadly does not fix the issue @webzwo0i

**Comment by webzwo0i** [comment]
I tested it and for me it fixes the problem. Can you try and disable minify in the config (setting `minify:false`), go to a timeslider that has this bug, hit play and open the error console to see what exceptions are thrown?

The exception shown here is gone after applying #5253
```
insert@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/timeslider.js?callback=require.define&v=76afa96a:3680:21
(module ep_etherpad-lite/static/js/Changeset.js)/exports.mutateTextLines@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/timeslider.js?callback=require.define&v=76afa96a:3870:13
applyChangeset@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/timeslider.js?callback=require.define&v=76afa96a:5910:15
goToRevision@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/timeslider.js?callback=require.define&v=76afa96a:6002:36
update@http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/timeslider.js?callback=require.define&v=76afa96a:6008:21
```

**Comment by davue** [comment]
Ok you're right, this partially fixed the problem. 👍

At least for imports and the `setHTML` endpoint. I was testing it using the `copyPadWithoutHistory` endpoint which still breaks the timeslider.

**Steps to replicate:**
1. Copy an existing pad into a new one using `copyPadWithoutHistory`
2. Create over 1000 revisions in the new pad
3. Try to use the timeslider for revisions < 1000

**Comment by davue** [comment]
It looks like that `copyPad` works without any issues. Only `copyPadWithoutHistory` seems to be affected by this bug.

Is there another way to clear the history of a pad to have a workaround?

**Comment by SamTV12345** [comment]
@Gared Is creating a fix for that so you can remove the history of a pad and its revisions

**Comment by SamTV12345** [comment]
Gared just checked locally with 25k versions. It seems like this could be caused by a corrupt pad which occurs when Etherpad crashes and hasn't finished writing to the database or the server crashes during a transaction. cc @Gared
