### ISSUE TITLE
Asterisk character (*) gets prepended to the line when the line modified via aceDomLineProcessLineAttributes

### ISSUE THREAD

**Issue by aherle** [ether/etherpad-lite#5281]
I've written an etherpad plugin that does the following job.

1. User selects some text.
2. Clicks on the button (designed in our new plugin).
3. The `h1` tag applies to selected text and also the selected text's color will get changed to red, I am doing it via `aceDomLineProcessLineAttributes` hook function.

The plugin does this job almost perfectly. But when I select and inspect the changed text (text in the `h1` tag) I can see a `*` at the beginning.

I think it is related to the `processMarker`.

Why `*` is prepended to the changed line ?

What are the possible reasons for that ?

**Comment by JohnMcLear** [comment]
Attributes have to be anchored to something in case line contents changes.  We use a hidden * and that is not modified when line contents is modified thus retaining the attributes.  Just hide that character.

**Comment by aherle** [comment]
@JohnMcLear 

> Just hide that character.

Not understood.

Should we hide the asterisk character through `aceDomLineProcessLineAttributes` ?


Can you please it explain little ?

**Comment by JohnMcLear** [comment]
See https://github.com/ether/ep_headings2/blob/master/static/js/index.js#L92 for example.  Note that by passing ``processedMarker`` as ``true`` that's what afaik hides the ``*``

**Comment by aherle** [comment]
@JohnMcLear 

I have already used `processedMarker: true` in the return statement of `aceDomLineProcessLineAttributes`.


i.e. I am currenly using the following return statement.

```

return [
      {
            preHtml: `<h1 style="color: red">`,
            postHtml: `</h1>`,
            processedMarker: true,
      }
]
```

But, when I select that line again and try to apply plugin on that line I see an asterisk character prepended to it.


i.e.

Let's assume we have the following text in the etherpad.

```
Hurray!!! I am finally using the etherpad in a right way.

My Plugin is almost working perfectly.

```

Then I'll apply my plugin on the first line.

Then the first line will get enclosed in an `h1` tag and also it's color will get changed to red.

Now, I will select both the lines and again I try to apply my plugin on both the lines.

Now I see the first line (in the etherpad) as 

```
* Hurray!!! I am finally using the etherpad in a right way.
```

This is what my problem is.

I don't know why the asterisk character is prepended.

**Comment by JohnMcLear** [comment]
Can you push your code somewhere?

**Comment by aherle** [comment]
@JohnMcLear 

Sorry for the late response.

But I can share the code.
