### ISSUE TITLE
Show Tooltip: On mouse click or when Enter key is pressed anywhere in editor.

### ISSUE THREAD

**Issue by ytiwari** [ether/etherpad-lite#5282]
name: Feature request
about: Open a tooltip to show some option e.g. insert an image or insert a table on click event anywhere in the editor.
title: ''
labels: enhancement
assignees:

Is your feature request related to a problem? Please describe.
I want to open a tooltip on click of mouse or on enter. Tooltip to show some action e.g. insert an image or some other action.

Additional context
Is there any plugin?

Thanks!

**Comment by JohnMcLear** [comment]
You mean like a right click event?  We intentionally don't overwrite right click behaviour in core.  They may be a plugin or you can see the inline buttons plugin.

**Comment by ytiwari** [comment]
@JohnMcLear, 
not on right click. When the user left click for typing something. like this >

![image](https://user-images.githubusercontent.com/1473339/142408668-00b6ac5f-d114-4e68-b7cb-7505e1e6c45b.png)

**Comment by JohnMcLear** [comment]
Yeah see the inline toolbar plugin.  Install via admin UI.
