### ISSUE TITLE
Clearing authorship colors fails when no text selected in PAD

### ISSUE THREAD

**Issue by ArcticSnowman** [ether/etherpad-lite#5283]
Clearing authorship colors fails when no text selected in PAD

![image](https://user-images.githubusercontent.com/13837922/142436957-c9614353-94a5-4546-9c93-17365d6d48ee.png)

### Versions
etherpad-lite: 1.8.14

### Plugins:
![image](https://user-images.githubusercontent.com/13837922/142437234-533039e8-f2cb-4e90-a863-7ca8f879c3b7.png)

**Comment by JohnMcLear** [comment]
Can you see if you can replicate in develop?  I'm pretty sure this is fixed we just need to release

Https://etherpad.org for test sites.

**Comment by ArcticSnowman** [comment]
https://video.etherpad.com/p/pr3FAt5r9VBV8fglGm7H - demonstrates the issue..   Based on a etherpad export from our instance

**Comment by JohnMcLear** [comment]
Will take a look when I get to a pc.  Thanks for the report

**Comment by ArcticSnowman** [comment]
I think I've narrowed it down.  We use the ep_headings2 plugin and the first line has a HEADING.  When I make the first line just normal the clear author works.

**Comment by ArcticSnowman** [comment]
Moved to https://github.com/ether/ep_headings2/issues/53

**Comment by rhansen** [comment]
Duplicate of #5128

**Comment by ArcticSnowman** [comment]
@rhansen @JohnMcLear  - is there a copy of the develop branch running under `etherpad.org` that I can confirm this is fixed?

**Comment by rhansen** [comment]
@ArcticSnowman https://rich.etherpad.com/

**Comment by ArcticSnowman** [comment]
@rhansen  - Thanks,   and I can confirm it works.   One thing though I have example export in etherpad format, when I load them in they are auto-deleted as the timestamp of the pad is older than the configured auto-delete you have on those etherpad.org site.
