### ISSUE TITLE
Add table into pad

### ISSUE THREAD

**Issue by ytiwari** [ether/etherpad-lite#5301]
* * *

name: Add Table
about: User should be able to add table
title: ''
labels: Feature
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
Users should be able to add Table for better organization of content.

**Describe the solution you'd like**
There should be an option in the toolbar e.g. Add Table. Users should select options and choose rows n columns and add.

**Describe alternatives you've considered**
I tried following the plugin and all other available plugins which allow adding tables. But all have the same problem. When a user tries to give "space" between two words. It doesn't accept.
https://github.com/ether/ep_table_of_contents

**Additional context**
If there is any solution to fix the problem (not accepting 'spaces') in https://github.com/ether/ep_table_of_contents. Then it should be
best. Not able to put space between words.

![image](https://user-images.githubusercontent.com/1473339/143389517-0e4aeb2c-90a4-4954-8b84-0b8d547100c8.png)

When tried to debug>>
![image](https://user-images.githubusercontent.com/1473339/143390881-35459050-80eb-4428-9066-073d934ac3a7.png)

As per the image above when change **n.inner HTML** to just **innerHTML**  then it allows 'space' between words but then it doesn't save updated content and on-page refresh table content go away.

**Plugin?**
Yes

**Comment by JohnMcLear** [comment]
Please see the plugins for tables that already exist.

**Comment by Vicky-Intelligaia** [comment]
I have checked all the tables plugins and none of them picked space after entering the text inside the table cell.

**Comment by JohnMcLear** [comment]
Create an issue on the plugin repos and link back to this issue :)

**Comment by Vicky-Intelligaia** [comment]
@JohnMcLear the repo (https://github.com/Melody-wu/ep_ice_tables) is not accessible not even the home page of that plugin.

**Comment by eyea** [comment]
> @JohnMcLear the repo (https://github.com/Melody-wu/ep_ice_tables) is not accessible not even the home page of that plugin.

this repo is 404 now :(
