### ISSUE TITLE
Docker images for 1.18.15 and 1.18.16 are missing

### ISSUE THREAD

**Issue by Loki-Afro** [ether/etherpad-lite#5306]
Hey there, the docker images for the last 2 releases are missing. 
Could you please publish them?

Thanks

**Comment by Gared** [comment]
Docker disabled automated builds for free subscripts https://docs.docker.com/docker-hub/builds/
We need to find another way to automatically build those images @JohnMcLear @rhansen

**Comment by Gared** [comment]
Maybe we can use a github action like https://github.com/marketplace/actions/build-and-push-docker-images
Has anyone any experience in this?

**Comment by Loki-Afro** [comment]
@Gared most simple one i came up with was this one

https://github.com/kaffeekrone/mail-drop/blob/main/.github/workflows/main.yml

may need to be adjusted according to your workflow. This does not care about semantic versioning what so ever, tag = tag and thats it :)

**Comment by rhansen** [comment]
#5308 added a GitHub workflow to publish a new Docker image whenever we push a new tag. I triggered it for 1.18.15 and 1.18.16.

**Comment by Gared** [comment]
Awesome, thank you @rhansen
