### ISSUE TITLE
URL regex: closing parenthesis left out

### ISSUE THREAD

**Issue by dcht00** [ether/etherpad-lite#5319]
Etherpad highlighting links written as

- https://en.wikipedia.org/wiki/Software_(disambiguation)
- https://en.wikipedia.org/wiki/Slovenia#Kingdom_of_Serbs,_Croats,_and_Slovenes_(later_the_Kingdom_of_Yugoslavia)

... would cut out the last parenthesis, leading to 

- https://en.wikipedia.org/wiki/Software_(disambiguation
- https://en.wikipedia.org/wiki/Slovenia#Kingdom_of_Serbs,_Croats,_and_Slovenes_(later_the_Kingdom_of_Yugoslavia

I've given Wikipedia examples because they're the ones I notice to do this most often.
Not sure if they are per URL spec ... but this is in common use.

The parenthesis also can't just be simply included, in example: 
- _(Also see https://en.wikipedia.org/wiki/Etherpad)_

Playing a bit with Github's editor here, it seems it includes closing parentheses proportionate to how many have been open, like this:
- https://example.com/test((test()test)))) ← 2 extras

This is the model I would propose to adopt.
It evidently however won't work with URLs such as:
- https://en.wikipedia.org/wiki/Sunn_O)))
- https://example.com/?band=Sunn_O)))

Following https://stackoverflow.com/questions/13225028/is-it-ok-to-have-brackets-or-parenthesis-in-url , first one is not per spec, but the second one is.

**Comment by testman42** [comment]
I would like to resurrect this issue, as it still happens in one of the latest releases, if not the latest.
