### ISSUE TITLE
Bug when accenting letters

### ISSUE THREAD

**Issue by andrefpf** [ether/etherpad-lite#5322]
**Describe the bug**
When I want to put a accent in the first letter of a word the software just removes the space that was before it. 

**To Reproduce**
1. Go to 'https://pad.riseup.net/'
2. Click ok to create a document
3. Write a word
4. Put a space 
5. Press ~ and then a
6. See error

**Expected behavior**
I just expect it to not remove my spaces.

**Screenshots**

![image](https://user-images.githubusercontent.com/48336152/145622472-dfb42b62-4e6a-4207-97fe-7eba597c3b69.png)

![image](https://user-images.githubusercontent.com/48336152/145622549-3b09f20f-fc01-47bd-b161-0c80ecdcba44.png)

**Desktop (please complete the following information):**
 - OS: ManjaroLinux 21.2.0
 - Browser: Firefox

**Comment by webzwo0i** [comment]
Can't reproduce with Firefox 95.0. Can you share a pad where you tried to get the expected behavior, so we can check the changesets? Also what Firefox version do you use?
Is it the same for other accented chars or does it only happen with tilde?

**Comment by andrefpf** [comment]
Hi, 

The problem happened in this document I just created for example:
https://pad.riseup.net/p/F8P64CzhYRt6qW3Ag_vh

I am using Firefox 94.0.2 (64 bits)

Yes, the same happen for other accented chars like "é ê à ã". 

I have just tried to replicate the same on Chromium and that didn't happened. It seems like the bug is related to my Firefox version.

**Comment by JohnMcLear** [comment]
Also can't replicate, FF on Ubuntu

Can you possible record a video of this behaviour?  It's very strange.

**Comment by andrefpf** [comment]
Here is a little demonstration of the bug.
https://youtu.be/HI-YvUF3eOA

 I also think some other infos may be helpfull, like: 
- The language of both my OS and Firefox is Brazilian Portuguese.
- My keyboard layout is ABNT-2.
- Other friends of mine, also portuguese speakers, have the exact same problem.

**Comment by webzwo0i** [comment]
Tried FF 94 and couldn't reproduce.

Looking at your video it bothers me that there is a second character (like `~`) added. Bug is probably in `src/static/js/collab_client.js` or `src/static/js/ace2_inner.js` (search for `[iI]nternationalComposition`). We should add some debug statements and compare the output of running it in Chrome vs Firefox.

@JohnMcLear Do you think we can add debug statements to the instance that's running beta.etherpad.com?

**Comment by JohnMcLear** [comment]
@webzwo0i not easily ;\  It's much easier to debug locally.  

https://codepen.io/bantic/pen/BNgvKa  <-- @andrefpf try replicate the bug here please.

We have quite a big set of deployments in BR PT so I'm supposed we haven't heard of this bug before..  @storybook which used to be maintained by @lpagliari is afaik BR PT??

**Comment by lpagliari** [comment]
Yes, @storytouch has a lot of code in pt-BR, and I don't remember seeing this bug before.

I tried to reproduce it using ABNT2 keyboard settings on a Mac, but could not get weird behaviour neither on https://pad.riseup.net/ nor on https://beta.etherpad.com/.

@joassouza do you remember seeing any issue like that? Or @ingoncalves, maybe...

**Comment by joassouza** [comment]
I don't remember something like that but the majority of our users don't use FF. I tried to replicate the bug here but had no success

**Comment by ingoncalves** [comment]
I also tried to replicate this bug on FF 94, Safari 15, and Chrome 96 using macOS Monterey, but I had no problems as well.

@andrefpf is there any extension installed on your FF?

I've had issues with composed characters in the past (https://github.com/ether/etherpad-lite/issues/4978). I don't believe it's related to the bug you described here, but it's worth checking out.

**Comment by miguelalt786** [comment]
I have the same issue, i tested on my home and work machines, both running Linux, when on Firefox (last version (103) with or without any extension) this problems occurs, but running in chromium or brave this doesn't happen. On my windows machine i cant reproduce the error.
