### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by rhansen** [ether/etherpad-lite#5324]
`Dockerfile` has a line that tells Docker to perform health checks by visiting `/` every 20 seconds: https://github.com/ether/etherpad-lite/blob/1.8.16/Dockerfile#L98 (added in PR #5122). Unfortunately, if `requireAuthentication` is enabled, the health checks spam the log with authentication failure messages (or success messages if ep_readonly_guest is installed). It also seems to create a new express-session record every time.

We should create an endpoint specifically for health checking (perhaps following [this I-D](https://www.ietf.org/archive/id/draft-inadarei-api-health-check-06.html)) that doesn't create express-session state or log anything, then configure Docker to poll that instead.

**Comment by JohnMcLear** [comment]
I'd be inclined to just poll ``/stats/``  https://video.etherpad.com/stats if you want a quick win but I like your idea of having some sort of unified standard endpoint too, just remember to include docs for proxy rewrites :)
