### ISSUE TITLE
Providing SSL information for MySQL conections

### ISSUE THREAD

**Issue by mikesol** [ether/etherpad-lite#5350]
My etherpad instance uses PlanetScale as a MySQL backend and, to connect, it needs SSL information.

I edited `DB.js` like so and it works:

```javascript
const tls = require('tls');
var realSettings = Object.assign(
	{ ssl: { ca: tls.rootCertificates } },
	settings.dbSettings
);

// set database settings
const db = new ueberDB.Database(
	settings.dbType,
	realSettings,
	null,
	log4js.getLogger("ueberDB")
);
```

I'm wondering if this is useful enough to propose as a PR? Maybe by gating it with a setting like `useTSLRootCerts` or something similar?

**Comment by SamTV12345** [comment]
Take a look here: https://www.npmjs.com/package/mysql2. We use this in our code here: https://github.com/ether/ueberDB/blob/main/databases/mysql_db.ts . If you add the required fields in the dbSettings in settings.json that should work without a problem.
