### ISSUE TITLE
 Invalid changeset: multiline insert op does not end with a newline

### ISSUE THREAD

**Issue by JulianOliver** [ether/etherpad-lite#5353]
**Describe the bug**
Our instance was recently upgraded from an older 1.7v to 1.8.16 (142a47c) and since, pads have been randomly failing to load, with the following error presented in the UI. There are hundreds of pads on our instance. The issue hitting pads seems completely random, with a pad being fine one day, then broken the next. 

Chrome/Chromium, Firefox, Safari browsers all report the same error, across multiple different devices.

We are however successfully using the API to extract the contents as HTML.

```
An error occurred

Please press and hold Ctrl and press F5 to reload this page

If the problem persists, please send this error message to your webmaster:
Error: Failed assertion: Invalid changeset: multiline insert op does not end with a newline
at https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function at line 11
ErrorId: sFQe30ux2u9WfvdSrIKs
Unhandled Promise rejection
URL: https://redacted.domain/p/redacted_pad
```

Reported by the running process:

```[2022-01-12 03:57:20.934] [WARN] client - Error: Failed assertion: Invalid changeset: multiline insert op does not end with a newline -- {                                                                                                                                      
  errorId: 'sFQe30ux2u9WfvdSrIKs',
  type: 'Unhandled Promise rejection',
  msg: 'Error: Failed assertion: Invalid changeset: multiline insert op does not end with a newline',
  url: 'https://redacted.domain/p/redacted-pad-name',
  source: 'https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function',
  linenumber: 11,
  userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0',
  stack: 'error@https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function:11:255\n' +
    'assert@https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function:11:309\n' +
    '(module ep_etherpad-lite/static/js/Changeset.js)/exports.checkRep@https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function:11:1933\n' +
    'ne@https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function:3:5404\n' +
    'setDocumentAttributedText@https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function:3:2067\n' +
    'setBaseAttributedText/<@https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function:18:714\n' +
    'withCallbacks/<@https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function:3:2032\n' +
    'Y@https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function:3:4135\n' +
    'X@https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function:3:4567\n' +
    'withCallbacks@https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function:3:2017\n' +
    'setBaseAttributedText@https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function:18:494\n' +
    'Ace2Inner/e.ace_setBaseAttributedText@https://redacted.domain/static/js/require-kernel.js?v=d63f37cb line 1 > Function:3:6547\n' +
    '(module ep_etherpad-lite/static/js/ace.js)/Ace2Editor/this[t]<@https://redacted.domain/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=d63f37cb:19:1508\n' +
    'i@https://redacted.domain/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=d63f37cb:19:1110\n' +
    '(module ep_etherpad-lite/static/js/ace.js)/Ace2Editor/this.init/<@https://redacted.domain/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=d63f37cb:19:4960\n' +
    '(module ep_etherpad-lite/static/js/ace.js)/Ace2Editor/this.init@https://redacted.domain/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=d63f37cb:19:4970\n'
 
 ```

**To Reproduce**
Steps to reproduce are not yet known.

**Expected behavior**
Pads load.

**Screenshots**
![image](https://user-images.githubusercontent.com/153270/149057474-2ef7be5a-b6c4-4bf8-87d9-16576ad47f2f.png)

**Server (please complete the following information):**
 - Etherpad version:
 - OS: Debian Bullseye
 - Node.js version (`v14.18.2`):
 - npm version (` 6.14.15`):
 - Is the server free of plugins:  only de facto  `ep_etherpad-lite` is loaded, though affected pads were created on older Etherpad version with Headings2, Countable and other plugins

**Comment by webzwo0i** [comment]
Is it possible to share a pad that is failing and/or apply the following diff and post the failing changeset?
```
diff --git a/src/static/js/Changeset.js b/src/static/js/Changeset.js
index 53b3f2c8..181765b7 100644
--- a/src/static/js/Changeset.js
+++ b/src/static/js/Changeset.js
@@ -398,7 +398,7 @@ exports.checkRep = (cs) => {
         assert(nlines === o.lines,
             'Invalid changeset: number of newlines in insert op does not match the charBank');
         assert(o.lines === 0 || chars.endsWith('\n'),
-            'Invalid changeset: multiline insert op does not end with a newline');
+            `Invalid changeset: multiline insert op does not end with a newline in ${cs}`);
         charBank = charBank.slice(o.chars);
         calcNewLen += o.chars;
         assert(calcNewLen <= newLen, `${calcNewLen} > ${newLen} in ${cs}`);
```

**Comment by JulianOliver** [comment]
Quite odd, this is returned:

``
Error: Failed assertion: Invalid changeset: multiline insert op does not end with a newline in Z:1>1tza*0*1*2*3+1*4+h*4*5+20*6|1+1*7|1+1*7*1*2*3+1*7|1+v*7+w*8+e*7|1+6*7+h*8+6*7|2+n*7+9*8+8*7|f+ta*7*9+7*7|1+1*7*2*a*3*b+1*7|1+2g*8|9+y5*8+v*7+13*8|a+1ft*8+3j*7+9*8|j+fa*8+2*7|2+2*7*2*a*3*b+1*7|2+u*8*5+20*8|7+r9*8+8*8*5+20*8|8+ji*7|2+2*6|1+1*c*1*2*3+1*c|2+37*c+n*d+6*c|i+ul*c*2*a*3*b+1*c|7+7o*c+2q*e+1e*c+9*e+j*c+g*e+gr*c|b+g5*8|5+p8*8+1z*c+a*8+1*c|3+3*6*1*2*3+1*c|8+6a*c+1z*f|9+pj*f+s*c|4+f*c*2*a*3*b+1*c|1+b*c+6d*g+1j*c|2+2*c*2*a*3*b+1*c|3+6h*c*2*a*3*b+1*c|4+6w*c*2*a*3*b+1*c|1+g*c+5o*g+3b*c|2+2*c*2*a*3*b+1*c|2+3r*c+5x*d|2+2*d+f*g|2+2*d*h+e*d|4+hr*g*9+9*g|1+a*g*9+2*g|1+a*g*9+3*g|1+4*g*9+6*c*9+1*c+1*g+2*c|1+5e*c+x*g|9+bz*g+1p*c|1+1*g*9+8*g|1+9*g*9+4*g|1+a*c*9+5*g+d*c+1*g+l*c+1*g+h*c+1*g|2+3a*c*9+3*g|10+lm*g+s*c|1+1*g|7+32*g*h+h*g|r+rh*g+15*c|2+2*c*1*2*3+1*6|2+2p*6+n*g+e*6|i+12f*6+4y*g+4*6|1+8*6+3i*g|e+10a*g+q*6|2+2*6*i*2*3+1*g|1+z*g*i*2*3+1*g|9+5q*g*j*2*3+1*g|1+d*g*i*2*3+1*g|1+1*g*j*2*3+1*g|a+fy*g*1*2*3+1*g|c+fq*g*i*2*3+1*6|2+1n*6+c*g|1+a*c+29*k+6*6+9*c|4+10*c+m*g|2+2*g*j*2*3+1*g|1+d*g*j*2*3+1*g|1+j*g*i*2*3+1*g|1+1*g*h+1a*g|8+og*g*1*2*3+1*g|1+5*g+2*k+3*g+3h*k|5+3g*k+2*g|1+1*g+4*k+3*g+3l*6|1+1*k|7+6s*g|3+3*l|1+1*m|1+1*m*i*2*3+1*m+b*n+9*m|1+j*m*i*2*3+1*m|2+c*m+e*6+6*m|1+1*m+9*n+1y*m|2+d*m+a*n+d*m|1+1*m+b*n+h*m|3+p*m*j*2*3+1*m|1+d*m*j*2*3+1*m|1+j*m*i*2*3+1*m|1+1*m*h+1a*m|8+og*m*j*2*3+1*m|2+c*m+q*n|1+1*n+6x*m|2+2*m+4*n|g+15b*n+16*m|1+1*n|a+rw*n+4f*o+1*n|1+1*m|1+1*l|1+1*l*i*2*3+1*l+b*p+2*l+p*q|1+1*q*i*2*3+1*l|9+5m*l*j*2*3+1*l|1+d*l*j*2*3+1*l|1+j*l*i*2*3+1*l|1+1*l*h+1a*l|8+og*l*j*2*3+1*l|5+4u*l*2*r*3*b+1*l|1+8x*l*2*r*3*s+1*l|1+cg*l*2*r*3*t+1*l|1+65*l*2*r*3*u+1*l|3+43*l*h+14*l|1+1*l*h+12*l|1+1*l*9+9*l|2+2*l+2t*v|1+1*w|1+1*w*i*2*3+1*x|1+12*x*i*2*3+1*x|1+1*x+9*l+6*x|1+1*x+e*l+5*x|1+1*x+9*l+1p*y+9*x|1+1*x+a*p+d*x|5+1c*x*j*2*3+1*x|2+f*x*i*2*3+1*x|1+1*x*j*2*3+1*x|1+j*x*i*2*3+1*x|1+1*x*h+1a*x|8+og*x*j*2*3+1*x|1+b*x*i*2*3+1*x|4+49*x*2*r*3*b+1*x|1+4q*x*2*r*3*s+1*x|1+6s*x*2*r*3*t+1*x+3o*l|3+56*l+53*z+1*l|2+bm*l+kj*p|1+1*l|g+1wr*p|2+2*p+2t*x|1+1*l|7+ac*l*10*2*3+1*w|1+10*l*j*2*3+1*w+8*v+5*w|1+1*l*j*2*3+1*w|1+f*l*j*2*3+1*w+22*11+7*12+7*w|1+1*l*j*2*3+1*w|1+b*l*j*2*3+1*w|1+b*l*j*2*3+1*w|1+c*l*j*2*3+1*w|2+o*w*j*2*3+1*w|1+e*w*j*2*3+1*w|1+1*w*j*2*3+1*w|1+j*w*h+1a*w|8+og*w*j*2*3+1*w|2+10*w+1*v+3*w+y*v|2+2d*v+2a*11+1*v+5e*13+c*v|1+1f*v+2*w|1+1*w+1*v+3*w+r*v+1f*11+1*v+1*11+1*v+4*11+w*v|1+1*v+2*w|1+1*w+11*v|1+6t*v+6n*v*9+3q*v|2+4b*v+4t*w|1+1*w+1*v|1+6k*v+1*w|1+1*w+2r*v|4+6j*w+1i*11+n*w+u*12|3+20*12+b2*v|h+12y*v+34*w|1+1*v|3+1t*v*i*2*3+1*v+g*14+1*v+8*14+1*v+1*14+1*v|1+7*v+9*15+8*v|2+l*v+8*15|1+1f*15+a*v|5+1t*v*j*2*3+1*v|2+18*v*j*2*3+1*v|1+1*v*j*2*3+1*v|1+j*v*h+1a*v|8+og*v*j*2*3+1*v|1+b*v+j*15+3*v|1+1*v+1*15|8+19*v+9*15|4+v*15+7*v+8*15|2+c*15+4*v|1+1*15+l*v|1+1*v+5*15|1+1*15+a*v|1+1*15|3+1o*v+b*15|3+m*15+7*v|7+1q*15|7+gj*15+t*v|3+2l*v+1*15|4+8t*15+8p*v|4+g*v+c*15|s+3z*15+52*v|1+1*15|1+1*15+39*v|1+1*v*j*2*3+1*v|8+ei*v*j*2*3+1*v+e*15+u*4|2+2*v*i*2*3+1*v|1+z*v+9*16+5*v|1+1*v+j*17+7*v|1+1*v+9*17+1i*v|2+p*v+b*17+c*v|2+o*v*j*2*3+1*v|1+e*v*j*2*3+1*v|1+1*v*j*2*3+1*v|1+j*v*h+1a*v|8+og*v*j*2*3+1*v|1+b*v*9+b*v+1*16|5+6c*16+6c*v|2+12*v+1*16+a*v|3+10*v+1*16+9*v|3+x*v+1*16|1+4*v|2+u*v+1*16+5*v|3+v*v+1*16+3*v|3+w*v+1*16+1*v|6+22*v+1*16+7*v|3+10*v+1*16+c*v|3+i*v+2*16+1*v|1+4*v+8*16|6+9a*16+5a*18|1+1*16|2+3b*16+e*19+11*16+8*19+2a*16+9*19+f*16+9*19+p*16+1*19+29*16|3+57*v|2+s*16|1+27*19+e1*v|1+1*16|5+ls*v+4*v*9+b*v|3+3g*16|6+72*v|1+5*v*j*2*3+1*v|8+ei*v*j*2*3+1*v|2+g*4|2+2*4*i*2*3+1*4|8+6b*4*j*2*3+1*4|1+1*4*j*2*3+1*4|1+e*4*j*2*3+1*4|1+1*4*j*2*3+1*4|1+j*4*h+1a*4|8+og*4*j*2*3+1*4|1+b*4*2*1a*3+1*4|1+u*4+2*4*9+f*4|1+2*4*2*a*3*b+1*4+w*1b|1+1*1b*2*1a*3*b+1*1b+5i*4|1+1*4*2*1a*3*s+1*4|1+34*4*2*1a*3*t+1*4|1+1s*4*2*1a*3*u+1*4|1+1z*4*2*1a*3*1c+1*4+1b*1d|1+s*1d*2*1a*3*1e+1*1d+29*4|1+1*4*2*1a*3*1f+1*4|1+1*4*2*1a*3*1g+1*4|1+5*4*2*1a*3*1h+1*4|1+u*4*2*1a*3*1i+1*4|1+1*4*2*1a*3*1j+1*4|1+5*4*2*1a*3*1k+1*4|1+w*4*2*1a*3*1l+1*4|1+1*4*2*1a*3*1m+1*4|1+7*4*2*1a*3*1n+1*4|1+w*4*2*1a*3*1o+1*4|1+1*4*2*1a*3*1p+1*4|1+b*4*2*1a*3*1q+1*4|1+1v*4*2*1a*3*1r+1*4|1+1*4*2*1a*3*1s+1*4|1+5*4*2*1a*3*1t+1*4|1+u*4*2*1a*3*1u+1*4|1+1*4*2*1a*3*1v+1*4|1+7*4*2*1a*3*1w+1*4|1+q*4*2*1a*3*1x+1*4|1+1*4*2*1a*3*1y+1*4|1+b*4*2*1a*3*1z+1*4|1+x*4*2*1a*3*20+1*4|1+1*4*2*1a*3*21+1*4|1+6*4*2*1a*3*22+1*4|1+1h*4*2*1a*3*23+1*4|1+1*4*2*1a*3*24+1*4|1+7*4*2*1a*3*25+1*4|1+l*4*2*1a*3*26+1*4|1+1*4*2*1a*3*27+1*4|1+7*4*2*1a*3*28+1*4|4+1q*17|1+1*17*2*a*3*b+1*17+x*4|1+1*4*2*1a*3*b+1*1d+3z*4+1*1d|1+1*1d*2*1a*3*s+1*1d+25*4+9*1d+m*4+b*1d+17*4+2*1d|1+1*1d*2*1a*3*t+1*1d+1w*4+u*1d|1+1*1d*2*1a*3*u+1*1d+30*4+v*1d|1+1*1d*2*1a*3*1c+1*1d+22*4+w*1d|1+1*1d*2*1a*3*1e+1*1d+1h*4+2*1d|1+1*1d*2*1a*3*1f+1*1d+2y*4+u*1d|1+1*1d*2*1a*3*1g+1*1d+7k*4+s*1d|1+1*1d*2*1a*3*1h+1*1d+1c*4+1*1d|1+1*1d*2*1a*3*1i+1*1d+15*4+2*1d|1+1*1d*2*1a*3*1j+1*1d+w*4+k*1d+1*4+1*1d|1+1*1d*2*1a*3*1k+1*1d+u*4+z*1d|1+1*1d*2*1a*3*1l+1*1d+1p*4+y*29|1+1*29*2*1a*3*1m+1*29|1+35*29*2*1a*3*1n+1*29+10*4|1+1*4*2*a*3*s+1*1d|1+i*1d*2*1a*3*b+1*1d|1+14*1d*2*1a*3*s+1*1d|1+y*1d*2*1a*3*t+1*1d+x*4|1+1*4*2*1a*3*u+1*4|1+k*1d|1+1*1d*2*a*3*b+1*4|1+o*4*2*a*3*s+1*4|1+17*4*2*a*3*t+1*4|1+11*4*2*a*3*u+1*4|1+2t*4*2*a*3*1c+1*4|1+1*4*2*a*3*1e+1*4+b*17|1+1*4|3+3u*4+40*v|1+1*v+m*4|3+3*4*j*2*3+1*4|8+ei*4*j*2*3+1*4|4+i*4*i*2*3+1*4|3+1z*4+m*17+1m*4+a*17+5*4|6+1p*4*j*2*3+1*4|1+1*4*j*2*3+1*4|1+e*4*j*2*3+1*4|1+1*4*j*2*3+1*4|3+1i*4*j*2*3+1*4|4+2n*4*j*2*3+1*4*9+n*4|1+1*4+4*4*9+3k*4|8+f1*4+3*4*9+d*4|3+m*4+4*4*9+4d*4|j+1ls*4*j*2*3+1*4|1+q*4+2*4*9+4g*4|c+k6*4*9+c*4|1+1*4+4*4*9+y*4|3+1v*4*j*2*3+1*4|8+ei*4*j*2*3+1*4|3+h*4*i*2*3+1*4+h*2a+1*4|1+g*4+9*1d+d*4|1+1*4+e*2b+5*4|1+1*4+m*1d+d*4+1o*2b+6*4|6+5f*4*j*2*3+1*4|1+1*4*j*2*3+1*4|1+e*4*j*2*3+1*4|1+1*4*j*2*3+1*4|3+1i*4*j*2*3+1*4|1+b*2b|1+1*4|1+r*1d|5+lr*1d+6*2c|1+1q*2c+27*1d+j*2c|1+1*1d|2+66*1d+1*4+2g*1d|3+3j*1d+38*2b|1+1*4+2z*1d|3+7c*1d+v*4+9*1d|1+k*1d+4e*4|1+1*1d|a+pj*1d+90*4|1+1*1d|8+b1*1d+1q*4|1+1*4*j*2*3+1*4|1+1*4*j*2*3+1*4|8+ei*4*j*2*3+1*4|1+f*4*j*2*3+1*4|1+1*0|1+1*2d*i*2*3+1*2d+f*4+1*2d|1+j*2d+9*2e+4*4+h*2d|1+1*2d+e*2e+4*2d|1+1*2d+27*4+9*2d|5+1l*2d+b*4+3q*2d|1+1*2d*j*2*3+1*2d|1+1*2d*j*2*3+1*2d|1+e*2d*j*2*3+1*2d|1+1*2d*j*2*3+1*2d|6+mu*2d+5h*2d*5+y*2d|1+1*2d*j*2*3+1*2d|1+1*2d*j*2*3+1*2d|2+c*2d*9+q*2d|1+1*2d*2*a*3*b+1*2d|1+32*2d*2*a*3*s+1*2d+c9*2f|2+n*2f+e*2d|1+2r*4|4+p5*4+r*2f+1*4+1s*2f|1+c*2f+7*2d|5+2c4*4|1+1*2f+4v*4|1+1*2d+kk*2f|4+1l*2f+7*4+1*2f+ce*4|4+9c*4+g*2f+1*4+5w*2f|1+1*4|1+1*4+2m*2f|1+1*4|1+1*2f+33*2e+6*2f|3+6r*4|1+1*2f+4*4|1+18*2f|1+1*4|7+8b*4+9k*2g+7*4|1+9*4+1g*2g+19*4|6+pu*2d*9+o*2d|2+b*2d*j*2*3+1*2d|1+1*2d*j*2*3+1*2d|9+ej*2d*j*2*3+1*2d|1+f*2d*1*2*3+1*2d|1+1*0*1*2*3+1*0|1+1*0*i*2*3+1*0+b*2d+6*4+2*2d+2*0+8*2d+3*0|2+g*0+e*4+b*0|1+1*0+8*2d|1+2e*0|1+9*0+a*2d|1+1*2d+j*0|2+i*0*1*2*3+1*0|1+1*0+b*4+3r*0|4+8*0*1*2*3+1*0|1+d*0*2*a*3+1*0|4+18*0*1*2*3+1*0|1+j*2d|l+iu*2d*9+m*2d|1+1*2d*2*a*3*b+1*2d|1+a*2d*2*1a*3*b+1*2d|1+13*2d*2*1a*3*s+1*2d|1+2f*2d*2*1a*3*t+1*2d|1+12*2d*2*1a*3*u+1*2d|1+m*2d*2*a*3*s+1*2d|1+m*2d*2*1a*3*b+1*2d|1+1l*2d*2*1a*3*s+1*2d|1+j*2d*2*1a*3*t+1*2d|1+1y*2d*2*1a*3*u+1*2d|1+1b*2d*2*1a*3*1c+1*2d+14*0|2+2*0*1*2*3+1*0|2+c*0*9+n*2d|1+1*2d*2*a*3*b+1*2d|1+3e*2d*2*a*3*s+1*2d|1+3g*2d*2*a*3*t+1*2d|1+3e*2d*2*a*3*u+1*2d|1+9g*2d*2*a*3*1c+1*2d|1+26*2d*2*a*3*1e+1*2d|1+1t*2d*2*1a*3*b+1*2d|1+1l*2d*2*a*3*1f+1*2d|1+3d*2d*2*a*3*1g+1*2d|1+1q*2d*2*a*3*1h+1*2d|1+2m*2d*2*1a*3*b+1*2d|1+1l*2d*2*2h*3*b+1*2d|1+d*2d*2*2h*3*s+1*2d|1+g*2d*2*2h*3*t+1*2d|5+2a*0*9+f*0|1+2*0+a*2d|1+2q*2d+3h*0|1+1*0+4*2d|2+2*2d*9+b*4|1+1*4+4*4*9+2*2d*9+12*4|3+14*4+11*2d|1+1*2d*2*a*3*b+1*2d|1+31*2d*2*1a*3*b+1*2d|1+2n*2d*2*1a*3*s+1*2d|1+2r*2d*2*a*3*s+1*2d+8*4+1c*2d|1+1*2d*2*a*3*t+1*2d|1+3x*2d*2*a*3*u+1*2d|1+6a*2d*2*a*3*1c+1*2d|1+1v*2d*2*a*3*1e+1*2d+2w*2c+17*2d|1+1*2d*2*a*3*1f+1*2d+j*2c+4m*2d|1+1*2d*2*a*3*1g+1*2d|1+2c*2d*2*1a*3*b+1*2d|1+16*2d*2*1a*3*s+1*2d|1+1g*2d*2*a*3*1h+1*2d|1+1w*2d*2*1a*3*b+1*2d+1y*4|2+9*4*9+7*2d*9+v*4*9+7*2d|1+5*2d*2*1a*3*b+1*2d+p*4|1+1b*4*2*2h*3*b+1*4|1+1r*4*2*2h*3*s+1*4|1+1k*4*2*2h*3*t+1*4+1*2d|1+1*2d*2*1a*3*s+1*4+m*2d+9*4+2*2d|1+1i*2c|1+1*2c+2d*2d|2+1y*2c+1c*4|1+5y*2c|2+bs*2c+64*2d|7+86*0|1+1*0*1*2*3+1*0|6+dy*0+j*2d|2+2*0|4+4*0*1*2*3+1*0|2+g*0+c*2d|6+7e$*
```

> Also what database backend are you using? Is it mysql with utf8mb4?

Yes, MariaDB with charset utf8mb4

```
MariaDB [etherpad]> show variables like "character_set_database";
+------------------------+---------+
| Variable_name          | Value   |
+------------------------+---------+
| character_set_database | utf8mb4 |
+------------------------+---------+
1 row in set (0.002 sec)
```

**Comment by webzwo0i** [comment]
Can you also post `SHOW VARIABLES LIKE 'character%';`, `SHOW VARIABLES LIKE 'collation%';` and `SHOW FULL COLUMNS FROM store;` please?

The changeset is missing the char bank (the part after $), but as you probably saw, this includes the full text of the pad... I don't have an explanation why it sometimes fails and sometimes not unless the pad content changed. Do pads that fail have something in common like containing emojis?

Can you again apply the following diff 
```
diff --git a/src/static/js/Changeset.js b/src/static/js/Changeset.js
index 53b3f2c8..1684cb2c 100644
--- a/src/static/js/Changeset.js
+++ b/src/static/js/Changeset.js
@@ -398,7 +398,7 @@ exports.checkRep = (cs) => {
         assert(nlines === o.lines,
             'Invalid changeset: number of newlines in insert op does not match the charBank');
         assert(o.lines === 0 || chars.endsWith('\n'),
-            'Invalid changeset: multiline insert op does not end with a newline');
+            `Invalid changeset: multiline insert op does not end with a newline, ${chars}; ${o.chars}; ${charBank.slice(o.chars,10}}`);
         charBank = charBank.slice(o.chars);
         calcNewLen += o.chars;
         assert(calcNewLen <= newLen, `${calcNewLen} > ${newLen} in ${cs}`);
```

and try some failing pads? Then take a look at the part after "with a newline, ". I expect something like the following:
```
This is a
multi
line
paragraph
```
or `this is a single line` followed by the length and followed by 10 additional characters. In the two examples the length is 27 and 21 respectively (including newlines). If you manually count the characters, you won't get the exact length that's displayed after the string. So assume you "count" 27 while `${o.chars}` is 28, you should see a newline immediately at the beginning of the "10 additional characters".
I hope this make sense somehow. Try to find an example where you can easily count the number of characters, don't forget to add +1 for every new line (in case the text is wrapped)

What was the version/commit you upgraded from?

**Comment by JulianOliver** [comment]
```
MariaDB [etherpad]> SHOW VARIABLES LIKE 'character%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.002 sec)
```

```
MariaDB [etherpad]> SHOW VARIABLES LIKE 'collation%';
+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | utf8_general_ci    |
| collation_database   | utf8mb4_general_ci |
| collation_server     | utf8mb4_general_ci |
+----------------------+--------------------+
3 rows in set (0.003 sec)
```

```
MariaDB [etherpad]> SHOW FULL COLUMNS FROM store;
+-------+--------------+-------------+------+-----+---------+-------+---------------------------------+---------+
| Field | Type         | Collation   | Null | Key | Default | Extra | Privileges                      | Comment |
+-------+--------------+-------------+------+-----+---------+-------+---------------------------------+---------+
| key   | varchar(100) | utf8mb4_bin | NO   | PRI | NULL    |       | select,insert,update,references |         |
| value | longtext     | utf8mb4_bin | NO   |     | NULL    |       | select,insert,update,references |         |
+-------+--------------+-------------+------+-----+---------+-------+---------------------------------+---------+
2 rows in set (0.007 sec)
```

I'll apply the diff tomorrow and get back. There are likely emojis and/or _????_ in the failing pads, albeit I just tested with both in a test pad and it continues to load fine. I cannot post excerpts unfortunately, as much of the content is quite sensitive.

**Comment by webzwo0i** [comment]
iirc connection and client encodings are set by ueberdb, so the defaults are probably not used. We should have coverage for this, so you should be able to test your instance's configuration. Need to take a look at our tests. Or simply open a new pad, add some emojis, restart etherpad and see if they are still there.

Regarding `????`: When you count the numbers and you get a paragraph that contains those `????`, the length should be -2 for every occurrence of `????`, ie you get a failed assertion with a paragraph that contains 100 characters including newlines and 3 times `????`. The length that's printed after the paragraph should be 94 or `2m` (in base 36). We need to remove two `?` and the changeset will be okay with it.

**Comment by JulianOliver** [comment]
I have not as yet been able to load an affected pad with the aforementioned patch applied, the given pads do not move past the _Loading..._ indicator. The logs mirror that situation. For the record these are huge pads, 10k+ words is not uncommon. Some pads will have over 100 end points at peak use.

We look forward to remedying the situation but for now I have rolled back to the original **Changeset.js** and am extracting affected pads such that they can be migrated to our community instance of Cryptpad.

Greatly appreciate your assistance.

**Comment by legrex** [comment]
I stumbled in the same problem this evening. I updated to 1.8.16 some days ago and today a user wrote me that his pad is not working. It's the same error as mentioned in the first message from @JulianOliver. I extracted the text from the database to make the content accessible to the user for now, but i'm a little bit lost what to do.

**Comment by pphilippos** [comment]
I had this problem, and in my case the reason was that I used the _mysqldump_ for migrating my database without specifing the encoding ("--default-character-set=utf8mb4"). See [here](https://stackoverflow.com/questions/3583691/mysqldump-and-restore-with-special-characters-%C3%B8%C3%A6%C3%A5%C3%98%C3%86%C3%85) for more details on how to use _mysqldump_.
