### ISSUE TITLE
The npm ci command can only install with an existing package-lock.json

### ISSUE THREAD

**Issue by FredMa01** [ether/etherpad-lite#5357]
node -v -> v14.18.3
npm -v -> v8.3.1
ep_etherpad-lite@1.8.16
I install Etherpad-lite on Debian Buster.
All is ok.
After installing plugins :

`npm install ep_align ep_author_hover ep_comments_page ep_delete_empty_pads ep_font_color ep_font_size ep_hash_auth ep_headings2 ep_horizontal_line ep_image_upload ep_markdown ep_prompt_for_name ep_spellcheck ep_user_fontsize_version_2
`
I have this error when I run ''src/bin/run.sh''

`Error: The `npm ci` command can only install with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate a package-lock.json file, then try again.
`
I try this :
```
npm i -g npm@latest
npm i npm@latest

```
but nothing change...

All thank for help

Fred

**Comment by rhansen** [comment]
Pass `--no-save --legacy-peer-deps` to `npm` when installing plugins.
