### ISSUE TITLE
Custom plugin fails after etherpad change to expressPreSession

### ISSUE THREAD

**Issue by tom-chase** [ether/etherpad-lite#5360]
I have a [small plugin](https://github.com/tom-chase/ep_cors) to implement ['npm cors'](https://www.npmjs.com/package/cors) for api calls from another domain.  Inspired by [ep_helmet](https://github.com/ether/ep_helmet), it hooks 'expressConfigure' and worked until commit #: [649fbdc](https://github.com/ether/etherpad-lite/commit/649fbdc), express: New expressPreSession server-side hook.  (I found it by 'git bisect')  I tried just replacing expressConfigure with expressPreSession in my plugin but that didn't work.  I'm going to stick with the prior commit that works until I can investigate further.  Any thoughts you have would be appreciated.  Thank you!

**Comment by rhansen** [comment]
Does it work if you move to the `expressPreSession` hook?

**Comment by tom-chase** [comment]
> ~Does it work if you move to the `expressPreSession` hook?~ Nevermind, you already said it doesn't.

The code for the trying it with 'expressPreSession' is the 'dev' branch of my plugin.  thanks.

**Comment by rhansen** [comment]
I'm guessing this is a middleware ordering issue. Can you try inserting the following just before [`src/node/hooks/express js` line 210](https://github.com/ether/etherpad-lite/blob/d3984aa621be5b7d20e4233814971e25154ce7c0/src/node/hooks/express.js#L210):

```javascript
  await hooks.aCallAll('temp', {app});
```

and replace `expressConfigure` with `temp` everywhere in your plugin?

**Comment by tom-chase** [comment]
No, that didn't fix it.

**Comment by rhansen** [comment]
When you say it doesn't work, what are the symptoms? Is it doing something incorrectly, or is behaving as if the plugin wasn't installed at all?

If you add `console.error('foo');` inside your hook function, do you see it appear in the logs?

**Comment by tom-chase** [comment]
When working, it adds CORS headers to the to the server response through the 'npm cors' module and the expressConfigure hook.  The error I get in the console is 
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dev.mycopri.org/api/1.2.15/createGroupIfNotExistsFor?apikey=&groupMapper=. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by tom-chase** [comment]
> If you add `console.error('foo');` inside your hook function, do you see it appear in the logs?

Yes, I see the function runs in the log.

**Comment by rhansen** [comment]
It might be more efficient to continue this conversation on Discord: https://discord.gg/daEjfhw
