### ISSUE TITLE
Persist Plugins Between Container Recreation

### ISSUE THREAD

**Issue by dannymate** [ether/etherpad-lite#5394]
* * *

name: Feature request
about: Suggest an idea for this project
title: 'Persist Plugins Between Container Recreation'
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
When rebuilding my container, plugins added in the admin webui are removed.

**Describe the solution you'd like**
I would like to be to reference a plugin folder and link it so it can be saved between container recreations.
Preferably this: https://github.com/ether/etherpad-lite/issues/3593. This way admins can use the UI.
I would also take: https://github.com/ether/etherpad-lite/issues/5338

**Describe alternatives you've considered**
So using the build param isn't really viable and it's not ideal for my use case anyway.

**Additional context**
I am using unraid. I'm setting this up for use for me and brother who is a writer and is very particular about his writing environment. He's been looking around for alternatives to his current setup and not being able to persist plugins is a deal breaker for him sadly.

**Comment by SamTV12345** [comment]
Etherpad 2.x allows this
