### ISSUE TITLE
Private Hosting on Heroku or similar platfroms

### ISSUE THREAD

**Issue by tushar-31093** [ether/etherpad-lite#5403]
Hi Team
I am a entrepreneur and could surely make use of a realtime notetaking web app for my team during meetings. Not a product but something handy and this seems to be useful. 

Could you guide me through on how we can make this work on Heroku or similar platforms? If that is possible?

**Comment by SamTV12345** [comment]
Sorry. I don't have access to Heroku. Otherwise rent a cheap VPS and run etherpad with docker. That is the easiest setup.
