### ISSUE TITLE
HTTP-API checkToken doesn't work as expected

### ISSUE THREAD

**Issue by Alienmaster** [ether/etherpad-lite#5409]
**Describe the bug**
When using the the checkToken HTTP-API Call with a wrong or empty token the result is a HTTP 401. Only if the token is valid the response is like in the [docs](https://etherpad.org/doc/v1.8.16/#index_checktoken)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/11733097/153387905-2ce08437-7fb9-4861-881f-6fb360b6a29a.png)

**Server**
 - Etherpad version: 1.9.0 (4ed436d)
 - OS: Ubuntu 18.04
 - Is the server free of plugins: yes

**Comment by rhansen** [comment]
Does it work in 1.8.16? If so, would you please bisect to figure out which commit broke it?

**Comment by Alienmaster** [comment]
Hi.
Unfortunately this also didn't worked in 1.8.16.
