### ISSUE TITLE
HTTP-API deleteGroup doesn't work

### ISSUE THREAD

**Issue by Alienmaster** [ether/etherpad-lite#5414]
When listing existing groups and trying to delete them i get the error "groupID does not exist"

![grafik](https://user-images.githubusercontent.com/11733097/153473579-4535253f-d3fa-4671-9fe0-cf8a75a4700a.png)

With 1.8.16 this worked fine

**Server:**
 - Etherpad version: 1.9.0 (4ed436d)
 - OS: Ubuntu 18.04
 - Is the server free of plugins: yes

**Comment by ayushkumar63123** [comment]
you used the wrong id name. You used S in place of 5 afterm01LC56nxfjfB and before BA There is no 'S' in real id.

**Comment by ayushkumar63123** [comment]
Please use correct id name by putting 5 in place of S and tell me the result you get.

**Comment by Alienmaster** [comment]
I tried it several times. Everytime i copied the groupID. Both Strings are the same:
![grafik](https://user-images.githubusercontent.com/11733097/153753937-2ffc33bf-01f6-4658-809e-7e31d849f326.png)

There is a 5 in the groupID and it looks different.

**Comment by ayushkumar63123** [comment]
Have you tried removing the "g." from group id? I think it may not be included in id name

**Comment by Alienmaster** [comment]
Like i said it worked with 1.8.16 .
The data type for groupids is written here: https://etherpad.org/doc/v1.8.16/#index_data-types
