### ISSUE TITLE
Installing any plugin on the Windows Prebuilt Package deletes ep_etherpad-lite folder completely. 

### ISSUE THREAD

**Issue by Lxxrxns** [ether/etherpad-lite#5450]
Hi there,

Just started using Etherpad today using the Windows Prebuilt Package. I got everything up and running on Windows Server, but now when I try to install any plugin, the node_modules\ep_etherpad-lite folder is deleted and replaced by a folder for the plugin I installed and an emtpy .bin folder, resulting in a crash because etherpad no longer exists. 

Any ideas on how to fix this and how I can install plugins in a different way? 

I have tried reinstalling the whole thing, to no avail.
Installing any plugin, using either the admin/plugins page or npm install ep_pluginname, all result in the same: ep_etherpad-lite gets renamed to something like ".ep_etherpad-lite" while the plugin gets installed, and once installation is complete, the ep_etherpad-lite folder has disappeared.

Thanks!

Laurens

**Comment by Syrah-NL** [comment]
Actually, installing any plugin deletes all other plugins in the node_modules folder (hence etherpad-lite is being removed). 
It still doesn't make sense to me why etherpad-lite is a plugin of itself?

**Comment by Syrah-NL** [comment]
This is still happening, any comment from Devs?

**Comment by SamTV12345** [comment]
This is fixed

**Comment by Lxxrxns** [comment]
Great! What was the problem? And why was it affecting only me (or very few people)?
