### ISSUE TITLE
Invalid HTML for lists and indentation

### ISSUE THREAD

**Issue by davue** [ether/etherpad-lite#5456]
**Describe the bug**
When using any features which would transform into lists on HTML exports (lists or indentation), the last element in the list will not have a closing tag (`</li>`). It will show fine in most browsers since they are often very tolerant with invalid HTML, but could cause issues if used otherwise.

**To Reproduce**
1. Create a list or indent some text
2. Export pad as HTML
3. Look at HTML source and observe that last element was not closed.

**Expected behavior**
I expected that all `li` tags are closed correctly.

**Server:**
 - Etherpad version: 1.8.17
 - OS: Manjaro 21.2.1
 - Node.js version (`node --version`): 12.18.0
 - npm version (`npm --version`): 6.14.4
 - Is the server free of plugins: Yes

**Desktop:**
 - OS: Manjaro 21.2.1
 - Browser: Chromium
 - Version: 96.0.4664.110

**Comment by cu** [comment]
This is valid, closing tags are optional for many HTML elements:

> A [li](https://dev.w3.org/html5/spec-LC/grouping-content.html#the-li-element) element's end tag may be omitted if the [li](https://dev.w3.org/html5/spec-LC/grouping-content.html#the-li-element) element is immediately followed by another [li](https://dev.w3.org/html5/spec-LC/grouping-content.html#the-li-element) element or if there is no more content in the parent element.

https://dev.w3.org/html5/spec-LC/syntax.html#optional-tags
