### ISSUE TITLE
Authentication via DB

### ISSUE THREAD

**Issue by Nehasoni988** [ether/etherpad-lite#5463]
Hello,

I am serving etherpad on my website's domain like this- my_domain/p/:pad_id.
I am embedding the pad in my application's pages.
Now, I want if any user is already logged in to my application then he can access the pad directly but if he is logged out and tried to access any pad directly from the URL then he needs to log in first. I don't want to save users' names or hashes in files.

The thing is, that I set **requireAuthentication: true** and all I want is to authenticate users via my users DB but the sign-in popup comes always before I send any request.

Can you please help me with how can I ignore this sign-in prompt and authenticate users via my DB?

**Comment by rhansen** [comment]
You may have to implement your own authentication plugin depending on how your authentication scheme works. If your site uses [OpenID Connect](https://openid.net/connect/) you can use the [ep_openid_connect](https://github.com/ether/ep_openid_connect) plugin.
