### ISSUE TITLE
GitHub URL should be https:// not git://

### ISSUE THREAD

**Issue by autonomygaps** [ether/etherpad-lite#5488]
In the instructions for installation, the clone URL generates a failure:

> Move to a folder where you want to install Etherpad. Clone the git repository: git clone --branch master git://github.com/ether/etherpad-lite.git

This should be `git clone --branch master git://github.com/ether/etherpad-lite.git`

**Comment by FredMa01** [comment]
You can add this before the git clone :
`git config --global url."https://".insteadOf git://`
