### ISSUE TITLE
Google Translate extension causes automatic line break when selecting text

### ISSUE THREAD

**Issue by LeaChemoul** [ether/etherpad-lite#5490]
## Behavior

When selecting text with the mouse, automatic line breaks are added at the end of the text.
It only happens: 
- On chrome
- With [Google Translate extension](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb)

This bug is more an incompatibility between Etherpad and Google Translate and may come from the extension.

## Context

**Server:**
* **Etherpad** version: 1.8.17
* **Plugins** : 
```
    "ep_author_follow":  "^0.1.28",
    "ep_image_upload":  "^1.0.64",
    "ep_author_hover":  "^0.3.31",
    "ep_comments_page":  "^0.1.92",
    "ep_disable_change_author_name": "^0.0.24",
    "ep_embedded_hyperlinks2": "^1.2.4",
    "ep_adminpads2": "^2.1.50",
    "ep_spellcheck": "^0.0.39",
    "ep_delete_empty_pads": "^0.0.8"
```

**Desktop:**
* **OS**: Intel Mac OS X 10_14_6
* **Browser** : Mozilla/5.0, Chrome/86.0.4240.198

## Video

https://user-images.githubusercontent.com/34442368/160410050-a5145305-b8c8-416a-82f6-ef39b2a76c6a.mov

https://user-images.githubusercontent.com/34442368/160410070-a2380c0e-4198-4209-8795-a82944cd13ce.mov

## Failure Logs

When opening developer tools : no errors.

## Useful info

This was tested also on this public instance : [https://code.etherpad.com/p/test](https://code.etherpad.com/p/test)

**Comment by rhansen** [comment]
This might get fixed by PR #5253. cc @webzwo0i
