### ISSUE TITLE
set username by REMOTE_USER

### ISSUE THREAD

**Issue by tbeitter** [ether/etherpad-lite#551]
set pad's username by the REMOTE_USER passed threw by http AuthBasic f.e.

Many Pads are running behind a webserver AuthBasic, so it would be nice to not have to set my username everytime I logged in.

**Comment by JohnMcLear** [comment]
Bounty this: https://www.bountysource.com/issues/1371936-set-username-by-remote_user

**Comment by lkraav** [comment]
This never moved forward even with the bounty?

**Comment by JohnMcLear** [comment]
Bounty too small?

----- Reply message -----

**Comment by HoverHell** [comment]
I implemented this for myself back then, but it was not merged.

**Comment by JohnMcLear** [comment]
Closing as plugins are doing this.

**Comment by volter** [comment]
And which ones?

**Comment by JohnMcLear** [comment]
Afaik ep_ldap does it ?

**Comment by volter** [comment]
But this request was a lot more generic than LDAP.

**Comment by JohnMcLear** [comment]
The point is that plugins are doing it and I provided an example that does.  You can copy/page the LDAP logic to whatever Auth mechanism you are using.
