### ISSUE TITLE
How to communicate from the client (browser) with the backend

### ISSUE THREAD

**Issue by braadworst** [ether/etherpad-lite#5543]
I've been building a simple plugin to get a better understanding of how Etherpad works, and most of the docs are pretty clear and self explanatory. I do have a question though how one would go about communicating with the backend. There is the exposed API, for which I was planning to use the `etherpad-lite-client`, but I do not understand where one would install this package in order to use it in my client-side plugin. In general if I create a client-side plugin and would like to use npm packages, where would I install them?

Furthermore, there is a single API key that gets generated on the server, and you would not like to expose that to a client for security reasons. So that makes me think that the API is more for server-to-server communication. Am I supposed to use the websocket (collab_client) when I would like to communicate with the backend? How can I get access to this from any plugin, as we only have hooks to work with and there is no `context` that exposes the websocket. 

Please advice

**Comment by SamTV12345** [comment]
> I've been building a simple plugin to get a better understanding of how Etherpad works, and most of the docs are pretty clear and self explanatory. I do have a question though how one would go about communicating with the backend. There is the exposed API, for which I was planning to use the `etherpad-lite-client`, but I do not understand where one would install this package in order to use it in my client-side plugin. In general if I create a client-side plugin and would like to use npm packages, where would I install them?
> 
> Furthermore, there is a single API key that gets generated on the server, and you would not like to expose that to a client for security reasons. So that makes me think that the API is more for server-to-server communication. Am I supposed to use the websocket (collab_client) when I would like to communicate with the backend? How can I get access to this from any plugin, as we only have hooks to work with and there is no `context` that exposes the websocket.
> 
> Please advice

You create a plugin that houses scripts for backend and frontend. You use socket io for that. So on the client you use .emit to send an event and on the backend you use .on to catch the event and do something with it

https://github.com/ether/etherpad-lite/wiki/Creating-a-plugin
