### ISSUE TITLE
Not possible to delete comments from a pad

### ISSUE THREAD

**Issue by anarchodoc** [ether/etherpad-lite#5547]
When you create a pad, it's possible to add comments to the text. However, I cannot figure out how to delete these comments  (e.g. after they are resolved/discussed by the group) despite extensive searches on the web and through the etherpad documentation. Can this functionality be added?

**Comment by zzkt** [comment]
see also https://github.com/ether/ep_comments_page/issues/201

**Comment by JohnMcLear** [comment]
Plugin issues should go on plugin repos, thanks!
