### ISSUE TITLE
VSCode Launch Files?

### ISSUE THREAD

**Issue by DanielHabenicht** [ether/etherpad-lite#5550]
* * *

name: Add VSCode specific launch files
about: Making it easier to start developing this project.
title: 'Add VSCode specific launch files'
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
I was frustrated the first time I developed for this project because there was no integration to easily start debugging.

**Describe the solution you'd like**
Adding Launch Settings for VSCode would certainly make debugging tests or the application a one-click no brainer, e.g.: 

```jsonc
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Program",
      "program": "${workspaceFolder}/src/node/server.js",
      "request": "launch",
      "skipFiles": ["<node_internals>/**"],
      "type": "node"
    },
    {
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "name": "nodemon",
      "program": "${workspaceFolder}/src/node/server.js",
      "request": "launch",
      "restart": true,
      "env": {
          "NODE_ENV": "production"
      },
      "runtimeExecutable": "nodemon",
      "skipFiles": ["<node_internals>/**"],
      "type": "node"
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Mocha Tests",
      "cwd": "${workspaceFolder}/src",
      "program": "${workspaceFolder}/src/node_modules/mocha/bin/_mocha",
      "args": [
        "--timeout 120000",
        "--recursive tests/backend/specs",
        "../node_modules/ep_*/static/tests/backend/specs",
      ],
      "internalConsoleOptions": "openOnSessionStart",
      "runtimeExecutable": null,
      "skipFiles": [
          "<node_internals>/**"
      ]
    }
  ]
}
```

**Additional context**
Adding IDE specific stuff, certainly leads to other IDEs specific stuff being committed too as one could argue that "you already did it for VSCode!".

**Comment by SamTV12345** [comment]
Can you file a pr for this please? @DanielHabenicht

**Comment by DanielHabenicht** [comment]
Sorry, I do not have the capacity to work on this project any more, but you can add the file from the Issue and see if still works, as it should have 2 years ago. 

Otherwise it is fine to close this issue.

**Comment by SamTV12345** [comment]
> Sorry, I do not have the capacity to work on this project any more, but you can add the file from the Issue and see if still works, as it should have 2 years ago. 
> 
> Otherwise it is fine to close this issue. 

Alright no worries. I don't really use VSCode I'm more of a webstorm user. I'd just leave it like that and if you or other feel the need for a vscode config I'm happy for any pr.
