### ISSUE TITLE
export stopped working after upgrade to 1.8.18

### ISSUE THREAD

**Issue by meskal** [ether/etherpad-lite#5553]
**Describe the bug**
After having upgraded to version 1.8.18 clicking "export -> html" gives ```Internal Server Error``` in the browser and 
```
[ERROR] console - Error: express-rate-limit: req.ip is undefined - are you sure you're using express?
    at Object.keyGenerator (/path/to/etherpad-lite/src/node_modules/express-rate-limit/lib/express-rate-limit.js:22:17)
    at v/etherpad-lite/src/node_modules/express-rate-limit/lib/express-rate-limit.js:69:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
in the console. This worked in the same setup with version 1.8.14.

**To Reproduce**
1. Upgrade to 1.8.18
2. Click on 'export->html'
3. See error "Internal Server Error"

**Expected behavior**
A html export of the pad.

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version: 1.8.18
 - OS: Debian GNU/Linux 10 (buster)
 - Node.js version (`node --version`): v16.15.1
 - npm version (`npm --version`): 8.11.0
 - Is the server free of plugins: yes

**Additional context**

**Comment by JohnMcLear** [comment]
Unable to replicate.

**Comment by meskal** [comment]
I can confirm that the installation that was broken with version 1.8.18 has a fully functional export with version v1.9.6
thanks a lot!
