### ISSUE TITLE
Etherpad does only listen to either IPv6 or IPv4

### ISSUE THREAD

**Issue by dl8dtl** [ether/etherpad-lite#5574]
**Describe the bug**
Etherpad does only listen on either IPv6, or IPv4, not on both.

**To Reproduce**
1. Install Etherpad on a host that is connected to both protocol versions.
2. Use the hostname in the "ip" configuration entry, rather than an IPv4 address
3. Use your system tools to see where it is listening
4. In my case, it was IPv6 only

**Expected behavior**
Listen on both protocol versions if they are available on the host.

**Screenshots**
This is the only network socket in `lsof -p <PID> | grep IPv` output:
```
node    82241 user   32u    IPv6    0xfffff8003f3ceb88      0t0    TCP myhostname:9001 (LISTEN)
```

**Server (please complete the following information):**
 - Etherpad version: git hash 2afb4080fcc9135bf9 of `develop` branch
 - OS: FreeBSD 12.3-STABLE
 - Node.js version (`node --version`): v18.5.0
 - npm version (`npm --version`): 8.13.2
 - Is the server free of plugins: yes, to the best of my knowledge

**Comment by SamTV12345** [comment]
You can make it listen to both IP protocols by going into settings.json => "ip" and set that to :: 

```json
{
...
"ip":"::",
...
}
```

One can test that locally (I don't have an IPv6 home network) with http://[::1]:9001/ and http://127.0.0.1:9001 .
