### ISSUE TITLE
Is there anyway to reduce the mysql database size?

### ISSUE THREAD

**Issue by cenotaph** [ether/etherpad-lite#5576]
Hi,

I help keep etherpad-lite running for a nonprofit organisation who has depended on it for years. Last year the mysql .ibd file was over 26GB and was filling up the VPS, so we decided to install a fresh empty etherpad-lite installation and move the old pads over to an 'archive' server.

Now, less than a year later, the archive server has filled the disk, with the .ibd file now ballooned to 43GB, despite hardly anyone editing any pads. Something is clearly wrong and we are in a difficult situation trying to keep it going. Is there any known way to clean/reduce the number of rows in the table? We would be OK losing the history of many or all of the pads, but I cannot understand how the key-value system works to determine the latest revisions.

Thanks!

**Comment by matthias4217** [comment]
I have noticed that Etherpad seems to be continually adding new sessions to the database. This may be solved in 1.9 according to the [changelog](https://github.com/ether/etherpad-lite/blob/develop/CHANGELOG.md). As for now, you could make a script to clean the sessions in the database, which should hopefully free up some space.

**Comment by cenotaph** [comment]
Any guidance on this? It seems impossible to tell what any of these key-value pairs mean, what is a session, what is an edit, etc? Thanks.

**Comment by webzwo0i** [comment]
It really depends. First you should check if running something like `optimize table` helps: https://dev.mysql.com/doc/refman/8.0/en/optimize-table.html

Do you have any plugins enabled? Plugins like ep_image_upload can cause additional data to be stored in the db.

The `sessionstorage:` prefixes contain the data that can be deleted. Make sure you do a backup first.

**Comment by JohnMcLear** [comment]
Should be fixed in 1.9.0, see how you get on.
