### ISSUE TITLE
Could not import docx even libreoffice already installed in docker

### ISSUE THREAD

**Issue by lindeer** [ether/etherpad-lite#5582]
**Describe the bug**
Enable libreoffice in Dockerfile but still not working

**To Reproduce**
1. `git clone https://github.com/ether/etherpad-lite.git -b 1.8.18`
2. `cd etherpad-lite && docker build --build-arg INSTALL_SOFFICE=true .`
3. `docker tag  91c3fa0e4dcb office`
4. `mkdir etherdata`
5. `docker run -it -p 8888:9001 -e 'DB_USER=wesley' -e 'DB_PASS=mypass' -v etherdata:/opt/etherpad-lite/var  --name pad office`
6. open 'http://0.0.0.0:8888/' in browser and open an editor and upload a local file

**Expected behavior**
Upload selected file and open in editor, but prompt 'upload failed', and console output:
```
[2022-08-14 06:30:56.571] [INFO] Minify - Compress CSS file css/iframe_editor.css.
[2022-08-14 06:31:16.136] [WARN] ImportHandler - Attempt to import non-ASCII file
[2022-08-14 06:33:11.927] [WARN] ImportHandler - Attempt to import non-ASCII file
```

**Screenshots**
![tmp](https://user-images.githubusercontent.com/6064524/184525601-a2794ba7-3c6f-4616-bd16-e94dc3674401.png)

**Server (please complete the following information):**
 - Etherpad version: 1.8.18
 - OS: Feodra 36(5.18.11-200.fc36.x86_64)

**Comment by spychodelics** [comment]
had to add libreoffice-java-common and default-jre to Dockerfile

**Comment by lindeer** [comment]
thanks @spychodelics and @etkecc , but what should I do to make it work? How do I have to change Dockerfile to add 'libreoffice-java-common and default-jre', in which directory?

**Comment by lindeer** [comment]
@etkecc  Great! thanks bro
