### ISSUE TITLE
Running a docker container is (at least) not correctly documented

### ISSUE THREAD

**Issue by wsw70** [ether/etherpad-lite#5584]
How to run a docker container for etherpad is described at https://github.com/ether/etherpad-lite/blob/develop/doc/docker.md

**If I understood the structure of the etherpad folders correctly**, they make running a docker container at least extremely difficult (if at all possible).

- JSON files in `/opt/etherpad-lite` are not recreated when their content is incorrect, so mounting them is not possible. To take the example of `settings.json`, it means
  - either using a volatile `settings.json` (which may be acceptable if all of the settings are available through env variables)
  - or not being able to mount a persistent file because a directory is created if the file `settings.json` exists
- plugins are in a common plugins directory, which means that newly installed plugins are lost after a restart. One would need to manually prepare a plugin path prior (and mount it during the container startup) prior to installing a plugin.

I am sure that I seriously missed something so maybe this is not a bug but at least the documentation as it is today is incorrect.

**Comment by therysin** [comment]
Would also like an update on this, being relatively new to docker. Thanks.

**Comment by therysin** [comment]
Here's a docker compose file that I wrote for this. I'm running on an ARM server, so had to use the development image. My version is reverse proxied with traefik, so feel free to remove those labels (and the network). I don't know how usage of a volume would affect this, but everything is working smoothly so far.

`version: '3.3'

networks:
  traefik:
    external: true
    
services:
  etherpad:
    container_name: etherpad
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: etherpad
      DB_USER: youruser
      DB_PASS: yourpassword
      DEFAULT_PAD_TEXT: your default text
      TITLE: Etherpad
      ADMIN_PASSWORD: yourpassword
    image: etherpad/etherpad:develop
    networks:
      - traefik
    depends_on:
      - etherpad_db
    volumes:
      - etherpad_volume:/opt/etherpad-lite
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notes.rule=Host(`example.com`)"
      - "traefik.http.routers.notes.entrypoints=websecure"
      - "traefik.http.routers.notes.tls.certresolver=yourresolver"
      - "traefik.http.services.notes.loadbalancer.server.port=9001"

  db:
    image: postgres:alpine
    container_name: etherpad_db
    environment:
      POSTGRES_DB: etherpad
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_USER: youruser
    restart: unless-stopped
    volumes:
      - /home/ubuntu/etherpad/db:/var/lib/postgresql/data
    networks:
      - traefik
      
volumes:
  etherpad_volume:`

**Comment by Manumie** [comment]
@therysin wrote :
> I don't know how usage of a volume would affect this

On the one hand, it allows to run a basic image and install plugins from the plugin manager and keep them persistent.

On the other hand, it makes the upgrade process a bit complicated as the volume keeps the files from the previous version so you need to remove the volume before you recreate the container with a new image. (that is after something like `docker pull etherpad:etherpad:develop`)
Assuming you use docker-compose and a generic image (as above) :
```
docker-compose rm -s <etherpad_service>
docker pull etherpad:etherpad:develop
docker-compose up -d --force-recreate <etherpad_service>
```
You'll need to reinstall your plugins manually. 
It would be nice to have a way to restore installed plugins on reinstall. 
I've never succeeded in making a custom image with plugins (using `build_arg ETHERPAD_PLUGINS`) and it seems you can't safely run `npm install` from the container...

**Comment by SamTV12345** [comment]
I guess we can close this one. We have a lot of docs over on docs.etherpad.org.
