### ISSUE TITLE
node v16 & v18 plugin installation via admin fails

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#5609]

**Comment by Gared** [comment]
On node 16 the installation of a plugin worked for me (except the fact, that the translations are missing, but maybe thats another issue...).

**Comment by Gared** [comment]
Would it be helpful to maybe use this npm package instead? https://github.com/davideicardi/live-plugin-manager

**Comment by SamTV12345** [comment]
@Gared Good idea. Can you implement that?
