### ISSUE TITLE
docker tag missing for 1.8.19

### ISSUE THREAD

**Issue by Loki-Afro** [ether/etherpad-lite#5626]
apparently there is no docker image for 1.8.19 , latest with a dedicated version was 1.8.18

seen here https://hub.docker.com/r/etherpad/etherpad/tags

**Comment by Loki-Afro** [comment]
*remind*

**Comment by thmo** [comment]
As the latest released version of etherpad is 1.8.18, why should there be a docker image 1.8.19?

**Comment by Loki-Afro** [comment]
ha! found the original issue on our side

as there was a tag for **1.8.18**  there was no image for **1.8.18**  but there is now (well for a year) :D
