### ISSUE TITLE
Plugin locales do not overwrite core messages

### ISSUE THREAD

**Issue by danielpetri1** [ether/etherpad-lite#5628]
**Describe the bug**
According to [Etherpad's API](https://etherpad.org/doc/v1.8.17/#index_2-create-translate-files-in-the-locales-directory-of-your-plugin), naming conflicts in a plugin's locale should replace the core translation. This, however, does not happen.

**To Reproduce**

1. Navigate to `ep_some-plugin/locales/en.json`
2. Set contents of file to e.g.,

```json
{
    "pad.importExport.import_export": "Export",
    "pad.toolbar.import_export.title": "Export to different file formats"
}

```
4. Restart server
5. Observe locales remain unchanged

**Expected behavior**
Etherpad's core messages overwritten by plugin's locale files.

**Server (please complete the following information):**
 - Etherpad version: 1.8.17
 - OS: Ubuntu 20.04.4 LTS
 - Node.js version: v16.16.0
 - npm version: 8.11.0
 - Is the server free of plugins: no

**Additional context**
- Using `customLocaleString` works as intended
- Deleting core translation and keeping the one in the plugin shows desired locale

**Comment by webzwo0i** [comment]
Thanks. Can you verify if https://github.com/ether/etherpad-lite/pull/5629 fixes your problem?

**Comment by danielpetri1** [comment]
That was fast - your submission fixed the issue. Thanks a lot @webzwo0i!

**Comment by danielpetri1** [comment]
With 1.9.0 released, this issue has been addressed.
