### ISSUE TITLE
Authors of plugin localizations aren't represented in merged locales file

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#5630]
The error is probably in https://github.com/ether/etherpad-lite/blob/develop/src/node/hooks/i18n.js#L60

If plugins contain a localization for a key that is also present in Etherpad's core, the core localization should be overwritten. However, the author field of a localization file overwrites the core authors, too.

**Comment by JohnMcLear** [comment]
Should be fixed in 1.9.0 with your patch.
