### ISSUE TITLE
How to change the pad name?

### ISSUE THREAD

**Issue by kzar79** [ether/etherpad-lite#5634]
**Describe the bug**
If a pad is created with the wrong name, it is impossible to change it.

**To Reproduce**
1. Go to the index page of an etherpad instance.
2. Insert a mistaken name for the pad (e.g. "mypOd")
3. try to change the name to the right one (e.g. "mypad")

**Expected behavior**
There should be somewhere a button to change the name of the pad. A popup should ask the new name, and the program should rename the pad and send the user to the new url.

**Server (please complete the following information):**
- All

**Desktop (please complete the following information):**
 - All

**Comment by weed-** [comment]
Renaming is easy:

- Create the new pad
- Move content from old to new (CTRL+A, CTRL+X, new CTRL+V)

**Comment by kzar79** [comment]
And all the history?

**Comment by weed-** [comment]
Will stay in the pad ("old" pad) as long as you like.

If renaming is essential, search for "Etherpad-admin". Double-Check your backups, Etherpad-admin is going stuff in the database, instead of using the API (which doesn't support renaming).

**Comment by benasocj** [comment]
>instead of using the API (which doesn't support renaming).

Isn't that what the API call [movePad](https://etherpad.org/doc/v1.8.6/#index_movepad_sourceid_destinationid_force_false) is for? For renaming a pad?
