### ISSUE TITLE
Refused to execute script from '' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by roughnecks** [ether/etherpad-lite#5642]
**Describe the bug**
Website is broken: https://i.imgur.com/MBSoUVL.png

Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**To Reproduce**
I've installed etherpad standalone following docs on https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-etherpad.md

`docker images -a`

"etherpad/etherpad 1.8.18 e988a8e2d9cc   6 months ago     481MB"

**Screenshots**
https://i.imgur.com/AMBmZm7.png

**Server (please complete the following information):**
 - Etherpad version: 1.8.18
 - OS: Debian 11
 - Node.js version (`node --version`): v12.22.12
 - npm version (`npm --version`): 7.5.2
 - Is the server free of plugins: yes, no plugins installed

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 up-to-date
 - Browser chrome
 - Version 107.0.5304.107 (Build ufficiale) (a 64 bit)

**Additional context**
admin/ pages are broken too

**Comment by JohnMcLear** [comment]
I'm guessing this isn't an Etherpad problem but a Matrix one or some such
