### ISSUE TITLE
Breakages on Sites That Run Etherpad

### ISSUE THREAD

**Issue by chrisjj** [ether/etherpad-lite#5649]
On https://github.com/ether/etherpad-lite/wiki/Sites-That-Run-Etherpad in latest Chrome broswer, the first three sites are each broken in some way. I didn't bother trying more.

https://analysis.etherpad.com/ 502 Bad Gateway

https://code.etherpad.com/ New text is invisible 
![image](https://user-images.githubusercontent.com/6157073/204092268-bd9f221f-419e-4273-a2ac-d541a5f4dd09.png)

https://collab.etherpad.com/ Prompt is invisible
![image](https://user-images.githubusercontent.com/6157073/204092389-644d9546-3fd0-41a5-85db-f5738e049233.png)

**Comment by JohnMcLear** [comment]
I killed them.  It was time.
