### ISSUE TITLE
Make a piece of text a link

### ISSUE THREAD

**Issue by JohnMcLear** [ether/etherpad-lite#565]
IE make it so a piece of text such as "hello world" is actually a link.

**Comment by JohnMcLear** [comment]
Bounty for this functionality: https://www.bountysource.com/issues/1371935-make-a-piece-of-text-a-link

**Comment by leafcutterant** [comment]
Any progress on this?

**Comment by JohnMcLear** [comment]
Been a thing for a long time: https://www.npmjs.org/package/ep_embedded_hyperlinks2
