### ISSUE TITLE
Bug: CTRL+B failure

### ISSUE THREAD

**Issue by chrisjj** [ether/etherpad-lite#5653]
Using https://rich.etherpad.com/ on latest Google Chrome.

1 Press CTRL+B
2 Type.

Expected*: bold text
Observed: regular text

\* Expected ... though I can find no user documentation of this function.

**Comment by weed-** [comment]
You have to select the text you like to show up bold, before using CTRL+B.

1 Type some text
2 Mark it
3 Press CTRL+B

If text has already been bold'ed, more typing in line with it will also be bold. If you want to type "just" bold, insert a space character, select it (for example by using CTRL+left on LTR systems), bold it (CTRL+B) and type "bold".

**Comment by chrisjj** [comment]
> You have to select the text you like to show up bold, before using CTRL+B.

Thanks for the confirmation of this bug.
