### ISSUE TITLE
Errors while using TimeSlider on text imported from a file

### ISSUE THREAD

**Issue by milossramek** [ether/etherpad-lite#5657]
**Describe the bug**
If text is imported from a file (using soffice or abiword) and  Time slider is used, error message is displayed at the last version prior to file import
**To Reproduce**
1. Do clean install
2. In order to create the settings.json file run EtherPad by bin/run.sh and kill it
3. Enable LibreOffice (or Abiword) and start  EtherPad by bin/run.sh again
4. Create a new document
5. Do some text changes, click the TimeSlider button to see version number (in my case it is 6)
6. Import the test.odt file from the etherpad-lite/src/tests/backend/specs/api/ directory. The existing text is replaced by text from the file.
7. Click the Time Slider button. Version number is now 8.
8. Drag slider slowly left. When version number changes to 6 a red popup with and error message appears:

--- error message start
An error occurred
Please press and hold Ctrl and press F5 to reload this page
If the problem persists, please send this error message to your webmaster:
TypeError: t[s] is undefined
at http://localhost:9001/javascripts/lib/ep_etherpad-lite/static/js/timeslider.js?callback=require.define&v=216e8505 at line 22
ErrorId: TRr3pnVHxJ9QhAgotyRG
Uncaught exception
URL: http://localhost:9001/p/ttt1/timeslider#8
UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0
--- error message end

**Expected behavior**
I expect that no error message is displayed

**Server (please complete the following information):**
 - Etherpad version: 1.8.18 (4b96ff6)
 - OS: Ubuntu 22.10
 - Node.js version (`node --version`): 1.8.18 (4b96ff6)
 - npm version (`npm --version`): 6.14.15
 - Is the server free of plugins:  yes

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari], Firefox
 - Version [e.g. 22] 107

**Additional context**
I've seen the problem also on Debian, other Etherpad versions (1.18.*) and the Chrome browser

**Comment by JohnMcLear** [comment]
Unable to replicate in 1.9.0

Please confirm if you can replicate..  Also node version 1.8?  That doesn't sound right!

I will re-open if you can confirm you can still replicate the bug.
