### ISSUE TITLE
Integrate with decentralized database:  https://github.com/dbpunk-labs/db3

### ISSUE THREAD

**Issue by muraneth** [ether/etherpad-lite#5666]
* * *

name: Feature request
about: Suggest an idea for this project
title: 'Integrate with decentralized database:  https://github.com/dbpunk-labs/db3'
labels: enhancement
assignees:  

* * *

**Is your feature request related to a problem? Please describe.**
No, just think about this

**Describe the solution you'd like**
All personal data will be stored on db3 network and query directly with decentralized network

**Additional context**
Db3 network is an open-sourced ETH layer2 decentralized database focused on user data ownership
**Plugin?**
Not sure about this

**Comment by SamTV12345** [comment]
Feel free to submit a pr over on ueberdb2.
