### ISSUE TITLE
Accept configuration file from standard input

### ISSUE THREAD

**Issue by rassie** [ether/etherpad-lite#568]
In Unix, a general convention is to use `-` as standard input. In `etherpad-lite`, I'd expect `cat /tmp/customSettings.js | node server.js -s -` to work, however, it does not (yet).

Rationale for this is simple: when integrating `etherpad-lite` in other products (in my case, a Django project, using `django-etherpad-lite`), every developer should have his own instance of `etherpad-lite` and it should also integrate with his other settings, like ports, database connections etc. This would become a far more trivial task if settings file were generated instead of hardcoded -- in case of Django `etherpad-lite` could be started by something along the lines of `python manage.py generate_etherpad_configuration | node etherpad/server.js -s -`.

**Comment by JohnMcLear** [comment]
We now accept absolute path for settings file so this should be solved :)  Re-open if not.
