### ISSUE TITLE
Etherpad not working with letsencrypt certs

### ISSUE THREAD

**Issue by iambeingtracked** [ether/etherpad-lite#5689]
**Describe the bug**
I generated lets encrypt certs with Certbot, added them to the "ssl" section in settings.json but when trying to go to the website it says "SSL received a record that exceeded the maximum permissible length."

**To Reproduce**
1. `git clone https://github.com/ether/etherpad-lite`
2. Generate certs with certbot
3. Here's the relevant part of the config: ```
  "ssl" : {
            "key"  : "/home/etherpad/certs/privkey1.pem",
            "cert" : "/home/etherpad/certs/fullchain1.pem",
          },
```

**Expected behavior**
It should work, I should be able to go the etherpad page and use it.

**Server (please complete the following information):**
 - Etherpad version:
 - OS: Alpine 3.16 running as an LXC container on Proxmox
 - Node.js version (`node --version`): v16.17.1
 - npm version (`npm --version`): 6.14.18
 - Is the server free of plugins: I only have ep_guests installed

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser: Firefox
 - Version: 109.0.1

**Additional context**
I can read the certs via the same user that I run etherpad on.

**Comment by JohnMcLear** [comment]
I use certbox for my certs no problem, can you still replicate this issue in 1.9.0?  If so I'll re-open.

**Comment by iambeingtracked** [comment]
No idea. I don't need etherpad anymore
