### ISSUE TITLE
How to install the package offline？

### ISSUE THREAD

**Issue by Milo-shi** [ether/etherpad-lite#5690]
Because the environment I'm deploying to doesn't have a network, can't download packages online

What method should I take to install packages offline？

**Comment by huzhongyuan** [comment]
I also encountered this problem, Have you found a solution?

**Comment by JohnMcLear** [comment]
Download the software.
Run it once.  ``bin/run.sh``
Then go offline
Now run it offline ``bin/fastRun.sh``
