### ISSUE TITLE
New official release hasn't been done in 1 year.

### ISSUE THREAD

**Issue by SamTV12345** [ether/etherpad-lite#5703]
As described a new release hasn't been done in a year. Thus leaving most users with outdated versions which may contain security vulnerabilities through old tools. 

## How to solve

Merge develop into master branch.

**Comment by haywardgb** [comment]
I'm getting security warnings and messages about lockfiles using old versions of NPM.

Has this project been abandoned ?

**Comment by SamTV12345** [comment]
Yes. The dependencies are really outdated. Don't use this project currently. You are opening hackers the door to your servers. socket.io-parser enables placing functions at any place in the docker container. After that you can use any other vulnerability for privilege escalation. 


![image](https://user-images.githubusercontent.com/40429738/229777156-bb9396ca-32e1-45cd-871f-71ffa1bcec2d.png)

**Comment by mwllgr** [comment]
For alternatives right now, I'd suggest looking at e.g. https://github.com/xwiki-labs/cryptpad and https://github.com/hedgedoc/hedgedoc

**Comment by SamTV12345** [comment]
Good idea. I will check out Cryptpad

**Comment by ocdtrekkie** [comment]
Another good option is to run Sandstorm.io. Our security model generally renders app vulnerabilities useless in practice, and we support Etherpad as a core application.

**Comment by SamTV12345** [comment]
Thanks. The most important step would be to update the dependencies and build on a new docker image that also has the latest bug fixes. I'm pretty happy with the current feature scope.

**Comment by sevdh** [comment]
It would indeed be great to have a minor update.

**Comment by GoliathLabs** [comment]
Any updates on this?

**Comment by sevdh** [comment]
Curious!

**Comment by SamTV12345** [comment]
You can forget this project. Went through the different branches. No new commits, nothing that seems to have been taken to bump the versions etc. The only things that trickle in are the translations from people that still have hope in this project.

**Comment by JohnMcLear** [comment]
If you guys want to see more progress on this project you can bump Software Freedom Conservancy and they can allocate some budget to get some folks involved.  We have some funds available but it's tied up with them.

The main reason things went stale is that the core devs (Me/Pita/Nulli & RH) all had other things go on with our lives (real world stuff) that meant we had to take a step back from maintaining the software.

We absolutely 100% welcome contributions and if someone wants to help take lead I'd be all ears :)  Feel free to reach out via email, it's my first name then @ my second name .co.uk

**Comment by SamTV12345** [comment]
> If you guys want to see more progress on this project you can bump Software Freedom Conservancy and they can allocate some budget to get some folks involved.  We have some funds available but it's tied up with them.
> 
> 
> 
> The main reason things went stale is that the core devs (Me/Pita/Nulli & RH) all had other things go on with our lives (real world stuff) that meant we had to take a step back from maintaining the software.
> 
> 
> 
> We absolutely 100% welcome contributions and if someone wants to help take lead I'd be all ears :)  Feel free to reach out via email, it's my first name then @ my second name .co.uk

I wrote you an email.

**Comment by SamTV12345** [comment]
@haywardgg @mwllgr @ocdtrekkie @sevdh We just released 1.9.0 . So most container deprecations should be fixed in a few hours and we are actively working on updating dependencies for now.

**Comment by haivala** [comment]
Can we have docker release too?

**Comment by SamTV12345** [comment]
The problem is that we have a queue of around 100 github action runners. So it might take some hours till it catches up with the master branch push. But it should be automatically triggered once the runners catch up.

**Comment by sevdh** [comment]
Really fantastic Etherpad is moving on!

**Comment by SamTV12345** [comment]
And we dropped by this new release alone 2/3d of the vulnerabilities inside the container.
![image](https://github.com/ether/etherpad-lite/assets/40429738/f43d1383-7efe-4abb-b0db-8988a9b4ea79)
