### ISSUE TITLE
Project GitHub wiki is publicly editable and vulnerable

### ISSUE THREAD

**Issue by finnless** [ether/etherpad-lite#5704]
Some wiki pages have been popping up on the [repo's Wiki](https://github.com/ether/etherpad-lite/wiki/) that are [spammy](https://web.archive.org/web/20221024155119/https://github.com/ether/etherpad-lite/wiki/KAMPANAT/), including a footer that was appearing on every wiki page. I was just able to delete these pages even though I am not currently a contributor.

I believe I also have edit access to the rest of the of the Wiki, including the ability to create and delete all pages. I created [this test page](https://github.com/ether/etherpad-lite/wiki/Test-page/78aa6851ad9ab13b9760966597b42a8a8f4550b2) then deleted it which makes the page [disappear](https://github.com/ether/etherpad-lite/wiki/Test-page/).

I believe anyone with a GitHub account could remove all the wiki pages. Is this the intended configuration? If not, these are the steps for [changing access permissions for wikis](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis).

**Comment by Gared** [comment]
Thank you for sharing these informations. I was not aware of this so I restricted the acess with the option "Restrict editing to users in teams with push access only". If anyone thinks we should change it, let me know
