### ISSUE TITLE
Unable to migrate dirty DB to mysql 

### ISSUE THREAD

**Issue by MKishio** [ether/etherpad-lite#5707]
**Describe the bug**
Using kubernetes to deploy etherpad, version 1.8.18. Had a dirtyDB instance with healthy pads inside. Used migrateDirtyDBtoRealDB in hope for migrating to mysql, however it is stuck after finding the records. Explicitly, giving this command with user etherpad at directory /opt/etherpad-lite:
`node bin/migrateDirtyDBtoRealDB.js `
yields
> [2023-04-06 12:09:56.433] [INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad-lite
[2023-04-06 12:09:56.446] [INFO] settings - settings loaded from: /opt/etherpad-lite/settings.json
[2023-04-06 12:09:56.447] [INFO] settings - No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
[2023-04-06 12:09:56.447] [INFO] settings - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
[2023-04-06 12:09:56.447] [INFO] settings - Session key loaded from: /opt/etherpad-lite/SESSIONKEY.txt
[2023-04-06 12:09:56.448] [INFO] settings - Random string used for versioning assets: af93d0dc
[2023-04-06 12:09:56.489] [INFO] console - Waiting for dirtyDB to parse its file.
[2023-04-06 12:10:03.735] [INFO] console - Found 198059 records, processing now.

and is stuck there for an hour at least, no records inserted into mysql database either.

**To Reproduce**
1. Create a fresh mysql and etherpad instances, use mysql as dbtype.
2. execute migrateDirtyDBtoRealDB.js 

**Expected behavior**
I happened to see a progress status logging in some old issues, expected that output at least. Real expectation is to have a successful migration.

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version: 1.8.18
 - OS: docker container
 - Node.js version (`node --version`):
 - npm version (`npm --version`):
 - Is the server free of plugins: yes

**Additional context**
Before migration, checked that:
- dirty.db file is not corrupt and pads are healthy via checkAllPads
- mysql connection is healthy by creating new pad and visiting webpage

Any help is much appreciated ^^

**Comment by webzwo0i** [comment]
Could you please add the following additional debug statements and post the output of the first few lines, after stripping any sensitive data?
```
diff --git a/src/bin/migrateDirtyDBtoRealDB.js b/src/bin/migrateDirtyDBtoRealDB.js
index 75f6cc67..9f16a324 100644
--- a/src/bin/migrateDirtyDBtoRealDB.js
+++ b/src/bin/migrateDirtyDBtoRealDB.js
@@ -37,10 +37,16 @@ process.on('unhandledRejection', (err) => { throw err; });
   const p = [];
   let numWritten = 0;
   dirty.forEach((key, value) => {
+    console.log(`key: ${key}`);
+    console.log(`value: ${value}`);
     let bcb, wcb;
     p.push(new Promise((resolve, reject) => {
-      bcb = (err) => { if (err != null) return reject(err); };
+      bcb = (err) => {
+        if (err != null) console.log(err);
+        if (err != null) return reject(err);
+      };
       wcb = (err) => {
+        if (err != null) console.log(err);
         if (err != null) return reject(err);
         if (++numWritten % 100 === 0) console.log(`Wrote record ${numWritten} of ${length}`);
         resolve();
```

**Comment by MKishio** [comment]
Thank you for the fast reply, added the log lines into file and run it again. It prints keys as I see them in mysql key columns but values as [object Object]. And then logs nothing. Here is a summary of the output:
```
[INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad-lite
[INFO] settings - settings loaded from: /opt/etherpad-lite/settings.json
[INFO] settings - No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
[INFO] settings - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
[INFO] settings - Session key loaded from: /opt/etherpad-lite/SESSIONKEY.txt
[INFO] settings - Random string used for versioning assets: 2cad7690
[INFO] console - Waiting for dirtyDB to parse its file.
[INFO] console - Found 198059 records, processing now.
[INFO] console - key: sessionstorage:<SOME_SESSION_KEY>
[INFO] console - value: [object Object]
[INFO] console - key: globalAuthor:<AUTHOR_CODE_WAS_HERE>
[INFO] console - value: [object Object]
[INFO] console - key: token2author:<AUTHOR_TOKEN_WAS_HERE>
[INFO] console - value: <AUTHOR_CODE_WAS_HERE>
[INFO] console - key: pad2readonly:<SECRET>
[INFO] console - value: <TOKEN_SECRET>
[INFO] console - key: readonly2pad:<TOKEN_SECRET>
[INFO] console - value: <SECRET>
[INFO] console - key: pad:<SECRET>:revs:0
[INFO] console - value: [object Object]
[INFO] console - key: pad:<SECRET>
[INFO] console - value: [object Object]
[INFO] console - key: pad:<SECRET>:revs:1
[INFO] console - value: [object Object]
[INFO] console - key: pad:<SECRET>:revs:2
[INFO] console - value: [object Object]
[INFO] console - key: pad:<SECRET>:revs:3
[INFO] console - value: [object Object]
[INFO] console - key: pad:<SECRET>:revs:4
[INFO] console - value: [object Object]
[INFO] console - key: pad:<SECRET>:revs:5
[INFO] console - value: [object Object]
[INFO] console - key: pad:<SECRET>:revs:6
[INFO] console - value: [object Object]
[INFO] console - key: sessionstorage:<SOME_SESSION_KEY>
[INFO] console - value: [object Object]
[INFO] console - key: sessionstorage:<SOME_SESSION_KEY>
[INFO] console - value: [object Object]
[INFO] console - key: pad:<SECRET>:revs:7
[INFO] console - value: [object Object]
[INFO] console - key: pad:<SECRET>:revs:8
[INFO] console - value: [object Object]
.
.
.
[INFO] console - key: sessionstorage:<SOME_SESSION_KEY>
[INFO] console - value: [object Object]
[INFO] console - key: sessionstorage:<SOME_SESSION_KEY>
[INFO] console - value: [object Object]
[INFO] console - key: sessionstorage:<SOME_SESSION_KEY>
[INFO] console - value: [object Object]
[INFO] console - key: sessionstorage:<SOME_SESSION_KEY>
[INFO] console - value: [object Object]
```
Seems like it outputs all possible key-value couples.

**Comment by stefanstidlffg** [comment]
hi! i have the same problem. the script shows a lot of key value pairs (after applying the patch above) but not a single record in the database is created

**Comment by JohnMcLear** [comment]
Possibly due to UeberDB version lagging, that's my theory..  It needs further investigation/confirmation to see why it's not writing to MySQL>

**Comment by SamTV12345** [comment]
@MKishio Could you please try again migrating the db. For that to work you need to checkout the develop branch. We upgraded the DB version so it might be worth to give it a try again.

**Comment by SamTV12345** [comment]
Closed due to inactivity
