### ISSUE TITLE
SSL Certificate Expired on Plugin Static Site

### ISSUE THREAD

**Issue by oliverbuehler** [ether/etherpad-lite#5711]
SSL Certificate for **static.etherpad.org** expired on Mon, 01 May 2023 20:06:07 GMT
=> leads to "Can not perform Etherpad update check: Error: certificate has expired" on startup

**Comment by Gared** [comment]
Fixed

**Comment by oliverbuehler** [comment]
Thanks for fixing that quickly :-)
