### ISSUE TITLE
Unable to load HTML that contains tables and images

### ISSUE THREAD

**Issue by dziewonski** [ether/etherpad-lite#5715]
**Describe the bug**
I'm unable to load a file for editing with HTML document that contains tables and images (or basically complex HTML).

**To Reproduce**
1. Call endpoint /setHtml with attached HTM document
2. See document is **not rendered properly**

**Expected behavior**
Expect to see document somehow similar to what web browser renders for given HTML file.

**Screenshots**
[Screenshot](https://github.com/dziewonski/public/blob/main/etherpad-issue.jpg)
[Sample HTML document](https://github.com/dziewonski/public/blob/main/sample%20document.html)

**Server (please complete the following information):**
 - Etherpad version: 1.8.18
 - Is the server free of plugins: disable_chat and tables5 plugins installed

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox, Brave/Chrome

**Comment by dziewonski** [comment]
I couldn't find any documentation on this but maybe there are some limitations on HTML file that can be loaded? Like list of supported tags, size limit, no support for images in base64 or something.
I would be very thankful for any help here. If you know anything about loading HTML please share your experience :pray:

**Comment by JohnMcLear** [comment]
Plugins extend Etherpad, use plugins :)

https://static.etherpad.org/index.html
