### ISSUE TITLE
docker  admin  password not pass

### ISSUE THREAD

**Issue by xxdyu** [ether/etherpad-lite#5751]
docker run --itd --rm  -p 9001:9001 -e ADMIN_PASSWORD=123456  etherpad/etherpad:1.9
![image](https://github.com/ether/etherpad-lite/assets/32918557/77499825-abde-417c-ba58-3a3627a227a0)
username： admin
password：123456
Could you please show me the reason for the incorrect password

**Comment by SamTV12345** [comment]
@JohnMcLear Seems to be a bug. If someone only has a numeric password my theory is that it is internally converted to a number and is thus not valid for the password string. As soon as I enter a letter like t123456 it works. We should maybe document that.

**Comment by JohnMcLear** [comment]
I'd guess a ~``.toString()`` or ``""`` is missing somewhere but I don't have a docker test environment setup nor do I intend to.

**Comment by SamTV12345** [comment]
Closing as this is fixed and will be included in the next release. If you can't wait for the release or you want to test it @xxdyu checkout the docker tag develop.

**Comment by xxdyu** [comment]
thanks
