### ISSUE TITLE
node v14 EOL

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#5761]
Just a reminder that v14 is EOL

**Comment by JohnMcLear** [comment]
Ta, getting deps updated w/ modern node is something I'm working on.

I'm aiming for 18

**Comment by SamTV12345** [comment]
In #5766 I removed all the GitHub actions for Node 14. So in matrix configuration only v16 and v18 is tested. I had to disable Nodev14 as it doesn't support top level async await that is necessary when importing ESM modules => We should think about deprecating CommonJS in favor of ESM which is much more modern.

**Comment by JohnMcLear** [comment]
@SamTV12345 doesn't the vast majority of plugins depend on CommonJS?

**Comment by JohnMcLear** [comment]
Also can this be closed now we require node 16?

**Comment by SamTV12345** [comment]
> Also can this be closed now we require node 16?

I guess so. Can we have a follow up issue that bumps npm to the latest version? Version 6 of npm is quite dated and I'm not sure if it is still supported.

**Comment by SamTV12345** [comment]
> @SamTV12345 doesn't the vast majority of plugins depend on CommonJS?

Somebody wrote a blog post about it. Does the requirements apply to our project? https://adamcoster.com/blog/commonjs-and-esm-importexport-compatibility-examples

**Comment by webzwo0i** [comment]
Let's close this and discuss the ESM question in https://github.com/ether/etherpad-lite/issues/5777 Thanks!
