### ISSUE TITLE
Database Seams Okay - Web Pad Is Empty

### ISSUE THREAD

**Issue by wilkis3** [ether/etherpad-lite#5762]
**Describe the bug**
On the web the pad is empty and the time slider shows also empty pads. All the pad and revisions are still in the postgres database. But I can export the pad.

**To Reproduce**
1. Open the link of the pad
2. Use the current version or use the time slider

**Expected behavior**
* It is empty. No text is in there.
* The time slider know there revision numbers but can't display anything
* The date/time of any revision is the same

**Screenshots**
![Screenshot from 2023-06-24 07-16-09](https://github.com/ether/etherpad-lite/assets/36081959/76995575-a857-44cc-91af-6d435a2b0557)

![Screenshot from 2023-06-24 07-16-22](https://github.com/ether/etherpad-lite/assets/36081959/ecc5dae4-ead5-491b-9458-d61f433605b6)

**Server (please complete the following information):**
 - Etherpad version: 1.9.0
 - OS: Ubuntu 20.04
 - Node.js version (`node --version`): v16.20.0
 - npm version (`npm --version`): 8.19.4
 - Is the server free of plugins: No
   - ep_align
   - ep_author_hover
   - ep_comments_page
   - ep_font_color
   - ep_headings2
   - ep_prompt_for_name

**Additional context**
* I can export the etherpad e.g. .etherpad. The file have a size of 190 MB and I working to upload it now.
* File socket connection between NGINX and Etherpad
* File socket connection between Postgres and Etherpad

**Comment by JohnMcLear** [comment]
On very large pads I remember a bug w/ timeslider where it wouldn't load because it was too much effort to load all prior history/revisions etc.  My thought is that it's related to that..

**Comment by wilkis3** [comment]
If I open the pad with being in the time slider I get the following error:
```
Uncaught ReferenceError: require is not defined
    <anonymous> https://pad.domain.example/javascripts/lib/ep_etherpad-lite/static/js/ace2_inner.js?callback=require.define&v=9f2c609e:1
[ace2_inner.js:1:1](https://pad.domain.example/javascripts/lib/ep_etherpad-lite/static/js/ace2_inner.js?callback=require.define&v=9f2c609e)
    <anonym> https://pad.domain.example/javascripts/lib/ep_etherpad-lite/static/js/ace2_inner.js?callback=require.define&v=9f2c609e:1
```

If I open the time slider, I get the following error/warning:
```
Unexpected error: could not translate element content for key timeslider.toolbar.returnbutton 
<a class="grouped-right" data-l10n-id="timeslider.toolbar.returnbutton">
```

**Comment by wilkis3** [comment]
We have an other pad with ~50.000 revisions and it can be open easily.

**Comment by wilkis3** [comment]
I updated the Etherpad server from 1.8.18 to 1.9.0 one day before we get the report that this pad is broken.

**Comment by wilkis3** [comment]
DEBUG logs from server console:

1. It do all the things with createAuthorIfNotExistsFor, mapper2author, mapper2group, createGroupIfNotExistsFor, createSession, session, group2sessions, author2sessions.
2. GET request
3. 
```
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.115] [DEBUG] http - 200, GET /p/g.GROUPID%24PAD_NAME
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.222] [INFO] Minify - Compress JS file js/basic_error_handler.js.
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.228] [INFO] Minify - Compress CSS file css/pad.css.
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.230] [DEBUG] http - 200, GET /static/js/basic_error_handler.js?v=6a749d6b
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.231] [INFO] Minify - Compress CSS file skins/colibris/pad.css.
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.234] [DEBUG] http - 304, GET /static/plugins/ep_comments_page/static/css/main.css
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.239] [DEBUG] http - 304, GET /static/plugins/ep_comments_page/static/css/comment.css
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.252] [DEBUG] http - 200, GET /javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=6a749d6b
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.252] [DEBUG] http - 200, GET /javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define&v=6a749d6b
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.262] [DEBUG] http - 304, GET /static/plugins/ep_comments_page/static/js/jquery.tmpl.min.js
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.263] [DEBUG] http - 200, GET /static/img/brand.svg
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.294] [DEBUG] http - 200, GET /static/skins/colibris/pad.css?v=6a749d6b
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.294] [INFO] Minify - Compress JS file js/require-kernel.js.
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.297] [DEBUG] http - 200, GET /static/css/pad.css?v=6a749d6b
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.298] [INFO] Minify - Compress JS file skins/colibris/pad.js.
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.300] [DEBUG] http - 200, GET /static/skins/colibris/pad.js?v=6a749d6b
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.358] [DEBUG] http - 200, GET /static/js/require-kernel.js?v=6a749d6b
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.639] [DEBUG] http - 304, GET /static/font/Roboto-Regular.ttf
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.639] [DEBUG] http - 304, GET /static/font/Quicksand-Medium.ttf
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.642] [DEBUG] http - 304, GET /static/font/Quicksand-Bold.ttf
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.856] [DEBUG] http - 304, GET /static/font/fontawesome-etherpad.woff?2
Jun 25 21:34:08 host run.sh[2912775]: [2023-06-25 21:34:08.892] [DEBUG] http - 200, GET /pluginfw/plugin-definitions.json?v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.070] [DEBUG] http - 200, GET /javascripts/lib/ep_prompt_for_name/static/js/index.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.109] [DEBUG] http - 200, GET /javascripts/lib/ep_headings2/static/js/index.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.152] [DEBUG] http - 200, GET /javascripts/lib/ep_headings2/static/js/shared.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.198] [DEBUG] http - 200, GET /javascripts/lib/ep_font_color/static/js/index.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.250] [DEBUG] http - 200, GET /javascripts/lib/ep_font_color/static/js/shared.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.301] [DEBUG] http - 200, GET /javascripts/lib/ep_comments_page/static/js/index.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.353] [DEBUG] http - 200, GET /javascripts/lib/ep_etherpad-lite/static/js/browser.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.405] [DEBUG] http - 200, GET /javascripts/lib/ep_comments_page/static/js/commentBoxes.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.456] [DEBUG] http - 200, GET /javascripts/lib/ep_comments_page/static/js/commentIcons.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.504] [DEBUG] http - 200, GET /javascripts/lib/ep_comments_page/static/js/commentL10n.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.554] [DEBUG] http - 200, GET /javascripts/lib/ep_comments_page/static/js/copyPasteEvents.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.599] [DEBUG] http - 200, GET /javascripts/lib/ep_comments_page/static/js/shared.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.643] [DEBUG] http - 200, GET /javascripts/lib/ep_comments_page/static/js/moment-with-locales.min.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.884] [DEBUG] http - 200, GET /javascripts/lib/ep_comments_page/static/js/newComment.js?callback=require.define&v=6a749d6b
Jun 25 21:34:09 host run.sh[2912775]: [2023-06-25 21:34:09.927] [DEBUG] http - 200, GET /javascripts/lib/ep_comments_page/static/js/preCommentMark.js?callback=require.define&v=6a749d6b
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.014] [DEBUG] http - 200, GET /javascripts/lib/ep_author_hover/static/js/index.js?callback=require.define&v=6a749d6b
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.057] [DEBUG] http - 200, GET /javascripts/lib/ep_align/static/js/index.js?callback=require.define&v=6a749d6b
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.103] [DEBUG] http - 200, GET /javascripts/lib/ep_align/static/js/shared.js?callback=require.define&v=6a749d6b
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.229] [DEBUG] socket.io - Xwl8nyN46ToSAAqzAAAG connected from IP ANONYMOUS
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.342] [DEBUG] socket.io - from Xwl8nyN46ToSAAqzAAAG: {
Jun 25 21:34:10 host run.sh[2912775]:   component: 'pad',
Jun 25 21:34:10 host run.sh[2912775]:   type: 'CLIENT_READY',
Jun 25 21:34:10 host run.sh[2912775]:   padId: 'g.GROUPID%24PAD_NAME',
Jun 25 21:34:10 host run.sh[2912775]:   sessionID: 's.5092c3ba80542e09e99c324553821224',
Jun 25 21:34:10 host run.sh[2912775]:   token: 't.heGO0XL9TiOrrfMeLRlu',
Jun 25 21:34:10 host run.sh[2912775]:   userInfo: { colorId: null, name: null }
Jun 25 21:34:10 host run.sh[2912775]: }
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.347] [DEBUG] ueberDB - GET    - pad2readonly:g.GROUPID%24PAD_NAME - "r.76542154117acedc056aafb2a6edea08" - from database
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.347] [DEBUG] ueberDB - GET    - pad:g.GROUPID%24PAD_NAME - {<CONTEXT REMOVED> - from cache
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.347] [DEBUG] ueberDB - GET    - session:s.5092c3ba80542e09e99c324553821224 - <CONTEXT REMOVED> - from cache
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.347] [DEBUG] ueberDB - GET    - globalAuthor:a.KZeMbZCAwsje1xnN - <CONTEXT REMOVED> - from cache
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.348] [DEBUG] ueberDB - GET    - pad:g.GROUPID%24PAD_NAME:revs:107402 - <CONTEXT REMOVED> - from database
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.348] [DEBUG] ueberDB - GETSUB - pad:g.GROUPID%24PAD_NAME:revs:107402["meta","timestamp"] - 1687673095060
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.348] [DEBUG] ueberDB - GET    - globalAuthor:a.yhZGeN8euHwxpW6J - <CONTEXT REMOVED> - from cache
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.348] [DEBUG] ueberDB - GET    - globalAuthor:a.K865BmHyrvvEE2r6 - <CONTEXT REMOVED> - from cache
Jun 25 21:34:10 host run.sh[2912775]: [2023-06-25 21:34:10.348] [DEBUG] ueberDB - GET    - globalAuthor:a.KZeMbZCAwsje1xnN - <CONTEXT REMOVED> - from cache
```

**Comment by wilkis3** [comment]
Sometimes the pad loads the authors at the time slider.

**Comment by JohnMcLear** [comment]
Any chance you can dump the ``.etherpad`` file using the export function?

**Comment by wilkis3** [comment]
> Any chance you can dump the `.etherpad` file using the export function?

Yes, it takes a few minutes for the download to start.

**Comment by webzwo0i** [comment]
btw log looks sane and the require error is benign. Etherpad has problems with the timeslider - known issue but it should display the pad in editor (and it should be editable of course)

Completely other idea: Did you try clearing the cache, e.g. open browser console->network tab->select "disable cache" and reload the pad?

**Comment by wilkis3** [comment]
> Completely other idea: Did you try clearing the cache, e.g. open browser console->network tab->select "disable cache" and reload the pad?

Yes, I did it and a few users (I didn't know them, may they have different browser and OS) too.

**Comment by wilkis3** [comment]
The problem still exist with 1.9.1.

**Comment by JohnMcLear** [comment]
@wilkis3 if you reimport the .etherpad file into a new Pad does it work then?

Alternatively dump the .etherpad file somewhere that we can grab and debug.

**Comment by SamTV12345** [comment]
@wilkis3 Any update on this one?

**Comment by SamTV12345** [comment]
@wilkis3 1.9.2 didn't change anything?

**Comment by SamTV12345** [comment]
> **Describe the bug** On the web the pad is empty and the time slider shows also empty pads. All the pad and revisions are still in the postgres database. But I can export the pad.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open the link of the pad
> 2. Use the current version or use the time slider
> 
> **Expected behavior**
> 
> * It is empty. No text is in there.
> * The time slider know there revision numbers but can't display anything
> * The date/time of any revision is the same
> 
> **Screenshots** ![Screenshot from 2023-06-24 07-16-09](https://private-user-images.githubusercontent.com/36081959/248444318-76995575-a857-44cc-91af-6d435a2b0557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzODI5NDMsIm5iZiI6MTcyMDM4MjY0MywicGF0aCI6Ii8zNjA4MTk1OS8yNDg0NDQzMTgtNzY5OTU1NzUtYTg1Ny00NGNjLTkxYWYtNmQ0MzVhMmIwNTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDIwMDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MDAwZDI5MGI3YmRhNDlhMWRjMzk3YWE0ZDZmNmI5OThlM2E4ZjMzMDYxZTljMjc2ZTcwMmM4YjAyN2ZlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H8Smk7TDDbhzX6FqJ6AuuL7UEONh4Be0TupbL8Fxcuo)
> 
> ![Screenshot from 2023-06-24 07-16-22](https://private-user-images.githubusercontent.com/36081959/248444321-ecc5dae4-ead5-491b-9458-d61f433605b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzODI5NDMsIm5iZiI6MTcyMDM4MjY0MywicGF0aCI6Ii8zNjA4MTk1OS8yNDg0NDQzMjEtZWNjNWRhZTQtZWFkNS00OTFiLTk0NTgtZDYxZjQzMzYwNWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDIwMDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YmEwYzBiOTEyNjY2OWFiODZjNGNkMzY5ODZlZTBjYTcyZGUzMjkxZTI2MDJlZDYzMTFlZGY1M2I5OTg3MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._6JVmN0wa00Ijdm5LzQyCetBACJtQFI2pZaj-waEdGk)
> 
> **Server (please complete the following information):**
> 
> * Etherpad version: 1.9.0
> * OS: Ubuntu 20.04
> * Node.js version (`node --version`): v16.20.0
> * npm version (`npm --version`): 8.19.4
> * Is the server free of plugins: No
>   
>   * ep_align
>   * ep_author_hover
>   * ep_comments_page
>   * ep_font_color
>   * ep_headings2
>   * ep_prompt_for_name
> 
> **Additional context**
> 
> * I can export the etherpad e.g. .etherpad. The file have a size of 190 MB and I working to upload it now.
> * File socket connection between NGINX and Etherpad
> * File socket connection between Postgres and Etherpad

Found the issue. The maxTransportSize is too low. You can increase it safely to 100 kB or 1MB. Beyond that is not recommended as you can then DOS the server with large fragments

**Comment by wilkis3** [comment]
> Found the issue. The maxTransportSize is too low. You can increase it safely to 100 kB or 1MB. Beyond that is not recommended as you can then DOS the server with large fragments

Thank you @SamTV12345 . I will try it.

**Comment by SamTV12345** [comment]
Let me know if it worked :)
