### ISSUE TITLE
Connection to custom redis host fails (starting from 1.9.1)

### ISSUE THREAD

**Issue by brknkfr** [ether/etherpad-lite#5775]
**Describe the bug**
Starting with version 1.9.1 the connection to a custom redis host with custom prefix doesn't work anymore.

**To Reproduce**
1. Install fresh etherpad-lite version 1.9.1 with nodejs 18.16.1
2. Configure a remote redis server and specify in settings.json
```
  "dbType": "redis",
  "dbSettings": {
    "host": "10.0.9.39",
    "port": 6384,
    "database": 0,
    "client_options": {
      "password": "VERYSECURESECRET",
      "prefix": "daily_"
    }
  },
```
3. Try to start etherpadl-lite. An error is thrown.
```
[2023-06-27 09:20:10.625] [INFO] server - Starting Etherpad...
[2023-06-27 09:20:10.886] [INFO] plugins - npm --version: 6.14.18
[2023-06-27 09:20:10.924] [ERROR] server - Error occurred while starting Etherpad
[2023-06-27 09:20:10.925] [ERROR] server - Metrics at time of fatal error:
{
  "httpStartTime": 0,
  "memoryUsage": 105066496,
  "memoryUsageHeap": 35057848
}
[2023-06-27 09:20:10.926] [ERROR] server - Error: connect ECONNREFUSED ::1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```

**Expected behavior**
Connection to custom redist host schould be still working.

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version: 1.9.1
 - OS: Debian Bullseye
 - Node.js version (`node --version`): 18.16.1
 - npm version (`npm --version`): 9.5.1
 - Is the server free of plugins: -

**Comment by brknkfr** [comment]
It looks like somehoew the values (port, prefix, etc) in settings.json aren't respected anymore ...

**Comment by JohnMcLear** [comment]
Looks like it's possibly due to an ueberdb update yea, ueber is at   "version": "4.0.7", and etherpad uses ^4.0.1",

I thought we had test coverage for settings being passed so I'm kinda surprised by this.  It appears for some reason there is no test config used for redis.. https://github.com/ether/ueberDB/blob/main/test/lib/databases.js#L43

Can anyone stand up a quick remote redis server for me to target to test against?

**Comment by JohnMcLear** [comment]
I can confirm the bug, if I use a hostname that doesn't exist Etherpad is ignoring the settings.json and connecting to localhost.

**Comment by JohnMcLear** [comment]
Note that the docs say to use URL... 
```
The above code connects to localhost on port 6379. To connect to a different host or port, use a connection string in the format redis[s]://[[username][:password]@][host][:port][/db-number]:

createClient({
  url: 'redis://alice:foobared@awesome.redis.server:6380'
});
```

**Comment by JohnMcLear** [comment]
yea the Etherpad docs at https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-Redis are wrong..  Redis expects ``url``... not hostname/port etc.

**Comment by brknkfr** [comment]
And it seems that unfortunately the prefix option isn't available anymore ... https://github.com/redis/node-redis/issues/1657

**Comment by SamTV12345** [comment]
I added a fix for that. You can use the url in the settings.json for adding a redis db. Currently you can try that out on the develop tag.

**Comment by jibon57** [comment]
@SamTV12345, you've added url as an only option but all the settings so far etherpad had always use host, port etc format. I'll recommend you to keep the option to use host, port e.g:
```

{
    socket: {
        host: '<hostname>',
        port: '<port>'
    },
    username: '<username>',
    password: '<password>'
}
```

Also use `url` option too. This way many existing system won't break after upgrade.

**Comment by SamTV12345** [comment]
Something like this?

https://github.com/ether/ueberDB/compare/main...fix/redis-url-different-attributes

**Comment by jibon57** [comment]
@SamTV12345 nice! Some suggestion, when you'll have URL during that time don't need to add username or password as you'll put it with URL directly. Something like:

```
if (this.settings.url) {
  this._client = createClient({url: this.settings.url});
} else if (this.settings.host) {
  const options = {
    socket:{
      host: this.settings.host,
      port: Number(this.settings.port),
    },
  }
  if (this.settings.password){
    options.password = this.settings.password;
  }
  if (this.settings.user){
    options.username = this.settings.user;
  }
  this._client = createClient(options)
}
```

**Comment by SamTV12345** [comment]
Thanks. I added your code snippet to the database configuration. If you want to you can test it on your configuration once the docker image is built.

**Comment by jibon57** [comment]
@SamTV12345 thank you! I've just tested `develop` docker image. Everything is working perfectly now! Waiting for final release.

**Comment by SamTV12345** [comment]
Great. Thanks for the suggestions and testing the fix 😄 .
