### ISSUE TITLE
Rewrite using ESM?

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#5777]
See also https://github.com/ether/etherpad-lite/issues/4820 and https://github.com/ether/etherpad-lite/issues/4714 for related issues.

@SamTV12345 
> > @SamTV12345 doesn't the vast majority of plugins depend on CommonJS?
> 
> Somebody wrote a blog post about it. Does the requirements apply to our project? https://adamcoster.com/blog/commonjs-and-esm-importexport-compatibility-examples

I don't really understand what you mean with requirements? ESM imports can reference CommonJS, see https://nodejs.org/api/esm.html#interoperability-with-commonjs

I don't mind if we break plugins, *but* they should fail gracefully. IE something like "x is deprecated since 6 month" or real backwards-compatible solutions. If we separate the plugin ecosystem into "core" (e.g. plugins published from ether org), "very important" (3rd-party plugins that are in use by a large number of instances) and "less important" (maybe we should reach out to the authors before, though!) and ensure that "core"+"very important" have patches ready to be merged, I'm +1 for doing incompatible changes.

However, note that the current dependency system (e.g. setting peer-dependency, minimal supported version etc.) is not sufficient, e.g. if we want version 2.0 to break the plugin ecosystem how to know if plugin x supports version 2.0? If an instance runs on 1.9, how to find the corresponding plugin version that still supports the old version?

Etherpad wants admins to update their instances and not stick to older releases. We don't backport patches yet. So a situation like "branch develop is on a version I can't install, because I depend on plugin x that does not support develop yet" should be avoided, imho.

**Comment by SamTV12345** [comment]
The blog post mentions that we should be able to import a CommonJS module into an ESM project

>If you are importing into an ESM module, it looks the same whether you're importing a CommonJS or ESM module: you'll use the import defaultStuff, {namedStuff} from './file.js' syntax, and the import will be asynchronous.

So we might be able to do this without any breaking changes. I found [this](https://github.com/wessberg/cjstoesm) tool which automates most of the stuff and I didn't really find a bug when converting parts of etherpad for testing purposes.

**Comment by SamTV12345** [comment]
I ported ueberdb to typescript and esm. We have no compromises to make if we simply export it to commonjs in the end.

**Comment by SamTV12345** [comment]
I don't know why but the typescript branch doesn't work. Somehow the node server starts but after that no routes are added/static is mapped. Can that mechanism be made easier?

**Comment by SamTV12345** [comment]
I guess we can close this for now as it would unfortunately break the hook system
