### ISSUE TITLE
Repair admin frontend tests

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#5785]
At least the uninstall plugin test seems to fail sometimes. Actually, the plugin is successfully uninstalled. Might be some timer running out

**Comment by SamTV12345** [comment]
Can we solve this by increasing the timer? Is the call in the admin.helper function the interval it tests and the timeout function the number of time to wait?

**Comment by webzwo0i** [comment]
Looking into this now. I made the tests more robust, but they still fail sometimes. The test video file seems to indicate it's a real bug, not a flaky test.

However, frontend tests are fragile, too. Saucelabs sometimes returns max run time exceeded errors or other errors for no real reason. :-( Maybe time to switch to Browserstack

**Comment by webzwo0i** [comment]
Also I'm unable to download console.log from Saucelabs that might indicate the cause of (some?) of the errors.

**Comment by SamTV12345** [comment]
Ah. That's a bummer. Maybe we should switch. But I have no idea what their conditions are and if we can get free access to their pipeline tests. But I heard that they are quite popular among the open source community.

**Comment by SamTV12345** [comment]
We can finally close this issue. Everything solved in Etherpad 2
