### ISSUE TITLE
Version check endpoint isn't updated

### ISSUE THREAD

**Issue by SamTV12345** [ether/etherpad-lite#5786]
The [static](https://static.etherpad.org/info.json) endpoint for version checking of etherpad needs to be updated. 

The current admin console is a bit confusing because of this:

![image](https://github.com/ether/etherpad-lite/assets/40429738/9a146147-29d6-4d72-a69b-2b700b4bcfe6)

**Comment by Gared** [comment]
This is a manual process for me right now. The file is hosted on my server and needs to be updated manually. Thought this is maybe better to see if there are any bugs in a new version and changing the version after one or two weeks if we are sure the release is stable. What do you think?

**Comment by SamTV12345** [comment]
Ah alright. Got it. I was wondering why we're not using this [endpoint](https://api.github.com/repos/ether/etherpad-lite/releases/latest) but it makes sense if we want to delay the main rush for the next version. I'm closing this as complete as I now know that there is a one week delay. Sorry if I annoyed you 😅 .
