### ISSUE TITLE
Can I change port 9001 to the default port?

### ISSUE THREAD

**Issue by yendrapriambada** [ether/etherpad-lite#5795]
The port in the first Installed is http://localhost:9001/
Can I change 9001 to 80 or to the default port? so I can access etherpad using this way: http://localhost/

**Comment by SamTV12345** [comment]
That is possible. With Docker you can simply change the left port assignment to the port you please. With a bare metal installation you can change it in the settings.json file. The key is "port"

**Comment by yendrapriambada** [comment]
Is there a way to change the port without using Docker?

**Comment by SamTV12345** [comment]
> That is possible. With Docker you can simply change the left port assignment to the port you please. With a bare metal installation you can change it in the settings.json file. The key is "port"

As mentioned. Change it in the settings.json.

**Comment by yendrapriambada** [comment]
I was try to change "port" in settings.json to 443 like this:
![image](https://github.com/ether/etherpad-lite/assets/73283816/365cc714-588d-4894-9de2-0a08c7d70cb8)

But, when I try to run again, it show an error like this:
![image](https://github.com/ether/etherpad-lite/assets/73283816/0da6bbef-15ad-46da-8a8e-293faef73ae2)

Is there something wrong with the steps I did? Thank you for your help

**Comment by SamTV12345** [comment]
That is normal for Ubuntu. Ubuntu requires root/sudo for binding a port lower than the well known ports. So you need to make an exception for port 443. Running as root is discouraged as it allows a hijacker to take control of the complete system.

**Comment by SamTV12345** [comment]
Did it work? So I can close this issue?
