### ISSUE TITLE
still big, or building / running instructions are not updated?

### ISSUE THREAD

**Issue by f1-outsourcing** [ether/etherpad-lite#5797]
I am doing this:

```
git clone --branch master https://github.com/ether/etherpad-lite.git &&
cd etherpad-lite &&
src/bin/run.sh
```

then it starts downloaden for a while

then my etherpad dir grows from 47MB to 324MB????

```
test2:/tmp/etherpad/src/node_modules# du -s -m * | sort -n | tail -n 40
1       yargs-unparser
1       yeast
1       yocto-queue
2       @eslint
2       @opentelemetry
2       @sinonjs
2       acorn-globals
2       async
2       cassandra-driver
2       eslint-plugin-import
2       etherpad-cli-client
2       har-validator
2       jszip
2       mongodb
2       nise
2       simple-git
2       socket.io-client
2       superagent
3       ajv
3       elasticsearch7
3       jsonminify
3       mocha
3       tedious
3       terser
3       ueberdb2
3       underscore
4       ramda
5       @js-joda
5       @redis
5       es-abstract
5       jsdom
5       lodash
6       @types
6       eslint
6       sinon
9       @typescript-eslint
12      selenium-webdriver
27      @azure
33      npm
65      typescript

```

What is with this redis??? I am definitely not using that. Wtf is 27MB of azure shit? git/diff in production??? cli-client??? Wtf cassandra driver who is using that??? elasticsearch????

Why is all this crap installed when I just do a run?

I already tried to ask this earlier here https://github.com/ether/etherpad-lite/issues/5712#event-9592042924 . 

You do get that wasting resources is bad for the environment? So everyone that initiates an etherpad now uses twice as much all of the world. I think everyone nowadays understands the concept that we should waste less instead of more.

**Comment by webzwo0i** [comment]
Thank you for your feedback. Please keep in mind that this is a project largely run by volunteers. We welcome your feedback and if you use Etherpad in a commercial environment please think about funding it. Also we are happy to review your pull requests.

Etherpad got updated the last days, so most of the dependencies are more recent now. However, this is a ongoing effort. There are alternatives, so if you want other features, you can always use them.

Regarding your questions: Etherpad uses, like most other NodeJS projects, npm/yarn to install its dependencies. At the time of installing them, we don't know how you are going to use the software. E.g. some users use redis as a database backend for ueberdb, which is our database layer while others use postgres.

Users can change settings.json and switch to completely different environments without reinstalling anything. When it comes to cli-client, this might be a bug, as this is used for testing thus be in devDependencies.

**Comment by webzwo0i** [comment]
`cd src && npm ci --omit dev --omit optional`  results in 210 MB

**Comment by f1-outsourcing** [comment]
> `cd src && npm ci --omit dev --omit optional` results in 210 MB

cool thanks, I will try this. If you would revert this, and have in the Dockerfile/home page statements that include modules. Then it is more obvious what can be commented out for someone that is not familiar with npm. There are so many development environments you can't assume any more that users just 'know stuff'. With just a bit of logics you can deduct what needs to be comment out. 

Mostly I am using your etherpad as a test task in the container environment, and it is sort of cute to have this functionality. But if it gets big I might as well create an small images with python -m SimpleHTTPServer $PORT0

**Comment by SamTV12345** [comment]
> > `cd src && npm ci --omit dev --omit optional` results in 210 MB
> 
> cool thanks, I will try this. If you would revert this, and have in the Dockerfile/home page statements that include modules. Then it is more obvious what can be commented out for someone that is not familiar with npm. There are so many development environments you can't assume any more that users just 'know stuff'. With just a bit of logics you can deduct what needs to be comment out.
> 
> Mostly I am using your etherpad as a test task in the container environment, and it is sort of cute to have this functionality. But if it gets big I might as well create an small images with python -m SimpleHTTPServer $PORT0

If you add export NODE_ENV=production it could get even smaller. Other than that you could also fork ueberdb, throw out the tests, dev dependencies and all database drivers that you don't need and then build and publish that to your npm registry.

**Comment by SamTV12345** [comment]
I could make it even smaller. It is now just a 150 MB compressed image which equals 500 MB uncompressed.

**Comment by f1-outsourcing** [comment]
@SamTV12345 

If find it quite complicated trying to remove packages afterwards. Afaik it also requires a build stage in your Dockerfile so you don't copy used space.

I think with 10kk downloads you should rethink, delivering one large blob or make it configurable. The current approach is not maintainable any way in the future. At some point you need to decide when is enough 1GB, 2GB etc. The fact that currently have dev things slipped in there is already a indication of this.

**Comment by JohnMcLear** [comment]
@f1-outsourcing I'd be happy to see a pull request from you with some proposed changes :)

**Comment by f1-outsourcing** [comment]
> @f1-outsourcing I'd be happy to see a pull request from you with some proposed changes :)

This is not something you fix in a simple pull request. This is more like changing the elementary way of approach/thinking of the development team.

**Comment by JohnMcLear** [comment]
@f1-outsourcing see https://github.com/ether/etherpad-lite/pull/5812 - I believe this approach to simplifying our npm dependency will make it much easier to reduce the overall file system footprint of the software for deployments such as your own.

Please try to avoid creating assumptions about the approach/thinking of a community and or advising said community how to operate from the outside without being active in the community.

We welcome positive contributors to the project and try to discourage any and all toxicity.  Thanks!

**Comment by f1-outsourcing** [comment]
> @f1-outsourcing see #5812 - I believe this approach to simplifying our npm dependency will make it much easier to reduce the overall file system footprint of the software for deployments such as your own.

I don't understand what is going on there. I am more having a conceptual contribution.

> Please try to avoid creating assumptions about the approach/thinking of a community and or advising said community how to operate from the outside without being active in the community.
> 

To a certain level I agree with this, hence my reference to that this is an issue for the development team. However it is also not required for a football team coach to have been active in the national team. 
Selecting optional components has been around for decades through things like `./configure `.

> We welcome positive contributors to the project and try to discourage any and all toxicity. Thanks!

Toxicity is just in the eye of the beholder. You can also decide to focus on the more important stuff.

**Comment by SamTV12345** [comment]
> > @f1-outsourcing see #5812 - I believe this approach to simplifying our npm dependency will make it much easier to reduce the overall file system footprint of the software for deployments such as your own.
> 
> I don't understand what is going on there. I am more having a conceptual contribution.
> 
> > Please try to avoid creating assumptions about the approach/thinking of a community and or advising said community how to operate from the outside without being active in the community.
> 
> To a certain level I agree with this, hence my reference to that this is an issue for the development team. However it is also not required for a football team coach to have been active in the national team. Selecting optional components has been around for decades through things like `./configure `.
> 
> > We welcome positive contributors to the project and try to discourage any and all toxicity. Thanks!
> 
> Toxicity is just in the eye of the beholder. You can also decide to focus on the more important stuff.

I don't really understand your motiviation. You create a GitHub issue where you state that node_modules is too big. After John asks you to create a pull request with the content you would update you deny that you don't have any expertise and just do a conceptual contribution. If you have something to contribute then do a pull request, add more information to this issue or close this issue. Thanks.

**Comment by f1-outsourcing** [comment]
The concept contribution is 

you are the manufacturer of a car

currently you sell this car with: 20 layers of paint, 130 chairs in different colours and configurations, 6 different head lights, 40 different wheels, 2 different steering wheels etc.

my contribution:

make a configurator, so you can supply everyone with the one part they want. If you don't your shipped car will soon be a freightliner. 

I think if this contribution concept is clear to everyone, there is no need to ask me anything, not?

**Comment by webzwo0i** [comment]
Do you want to talk about how such a configurator should work or do you just want to propose that someone should write this configurator? I would be +1 for a minimal size version of Etherpad, if the effort is moderate. Thoguh, as storage is cheap, I have other priorities.

For some dependencies it might be straight forward, e.g. publish a ueberDB version that only supports Postgres or Mysql and change package-lock accordingly. But in general this is not the way NodeJS projects work. Search the internet for "node_modules why large size critique" etc. and there is plenty of discussions around the whole topic.

Avoid installing dev dependencies has the largest effect, we probably should make this default, as most users don't want to develop Etherpad.

If you care from an operational standpoint I would rather suggest to use a file system with compression and or de-duplication on the data sets that store the project's files.

As said, I appreciate conceptual contributions, but they should not be too out of scope, e.g. let's not depend on cmake or autotools to prepare our package-lock.json.

**Comment by webzwo0i** [comment]
Btw. for the client code there are plugins like https://github.com/storytouch/ep_webpack that try to reduce the amount of requests/code. I'm not aware of similar approaches to server side code, so if you know another NodeJS project that somehow dynamically builds their dependencies and - more importantly - does not fetch all the unused code from the dependencies, I'd like to know. As JS is a dynamic language, doing this kind of stuff is probably extremely hard.

**Comment by f1-outsourcing** [comment]
> Thoguh, as storage is cheap, 
> 

storage is cheap is such an old fashioned argument and not of this time.

Say your application is on average 2x to big (probably more). So 10kk downloads of docker images, I would think in my small setup container layers are kept for 30 days when the application hops to different hosts. So having 3 or 4 instances on a hot environment is not strange, then having this on redundant 3x replicated storage, add (external) backups. Incidental snapshots of vm's etc. 
Assuming that large cloud environments have their own repositories you could easily extrapolate this to much much more than 100kk. 

With 100kk you already have 15PB of extra storage, maybe 3000 disks running 24/7/365 for nothing at all, which need to be replaced before warranty, which require engineers to go to data centres etc etc. Think of the example you set for others.

This type of thinking is exactly the reason why I think climate actions will fail. There are just to many of you on this globe, thinking like this. And unfortunately you are just the majority. ;)

**Comment by SamTV12345** [comment]
@f1-outsourcing  

Could you please stop offending and blatently attacking other maintainers. We are currently 3 people trying to maintain a project that even went through Google's supervision and contains a lot of code that is not optimized/documented. 

Why didn't even Google do that? They are one of the Fortune 500 companies. If you spend some time and/or money we could find a full time developer that moves this project to a more efficient statically linked binary which would be a lot more efficient in terms of CPU/memory/image size. 

So the bottom line is: Either start throwing hundreds of dollars at this project so that we can find someone that can do this as his/her lifetime or you need to make your hands dirty yourself. Learn Rust/Go and we can talk again how we want to move Etherpad forward. 

Until then we three do our best effort to maintain and support etherpad-lite while paying the power bill for running our dev machines.

**Comment by webzwo0i** [comment]
As you can see in this issue, I tried to help. If you'd open a bug report like "Don't include azure modules by default" or "Large amount of storage on default installations" I'll happily discuss further steps or help you with onboarding to be the next developer. I don't expect Pull Requests or that everybody is a NodeJS developer. I know that people have different skills.
That's why I welcome your thoughts even if I don't put your thoughts on my top priority list.

However, it seems to me that you are not here to help Etherpad or comment on bugs in Etherpad, but because your "cute test task" that you want to show your customers has attracted your attention due to unexpected storage consumption.

If you want more people to listen to your ideas, I'd recommend you work on your communication skills.

**Comment by JohnMcLear** [comment]
A note for future maintainers who hit issues like this; this is a really good example of how you have to call out toxicity quickly and with a unified front.

We can't tolerate toxic or destructive members of the community.  We take their objective feedback, distill it and action that but we don't tolerate abuse or disrespect.

Well done @SamTV12345 and @webzwo0i
