### ISSUE TITLE
express-session: pull in upstream changes

### ISSUE THREAD

**Issue by webzwo0i** [ether/etherpad-lite#5801]
express-session was forked, so we need to either finish work on touch or review upstream changes and pull them into our fork

https://github.com/expressjs/session/compare/master...ether:express-session:main

**Comment by SamTV12345** [comment]
Upstream seems to be dead so it would be best to maintain our fork and update that to the latest upstream commit.

**Comment by SamTV12345** [comment]
I don't seem to have access to that repository.

**Comment by JohnMcLear** [comment]
@SamTV12345 ytou should ahve access now

https://github.com/ether/express-session

**Comment by SamTV12345** [comment]
Perfect. Thanks for granting me access.

**Comment by SamTV12345** [comment]
I cherrypicked the remaining commits. We're now up to date with the upstream master. Somebody needs to create a release on npmjs @JohnMcLear @webzwo0i .

**Comment by JohnMcLear** [comment]
Done

**Comment by SamTV12345** [comment]
Can be closed as the latest express session has been cherry picked, uploaded to npmjs by @JohnMcLear (thanks :) and has been updated in Etherpad Lite
