### ISSUE TITLE
Broken wiki link: Enable import/export functionality with AbiWord

### ISSUE THREAD

**Issue by rgmz** [ether/etherpad-lite#5818]
**Describe the bug**

The link for ["Enable import/export functionality with AbiWord"](https://github.com/ether/etherpad-lite/wiki/How-to-enable-importing-and-exporting-different-file-formats-with-AbiWord) in the "Set-Up" section of the wiki is broken. There is a page with a similar title (["How to enable importing and exporting different file formats in Ubuntu or OpenSuse or SLES with AbiWord"](https://github.com/ether/etherpad-lite/wiki/How-to-enable-importing-and-exporting-different-file-formats-in-Ubuntu-or-OpenSuse-or-SLES-with-AbiWord)) indicating that the page _should_ exist, however, it does not appear to.

Clicking either link redirects to the wiki homepage.

**Comment by JohnMcLear** [comment]
@HairyFotr played with these things...

https://github.com/ether/etherpad-lite/wiki/How-to-enable-importing-and-exporting-different-file-formats-in-Ubuntu-or-OpenSuse-or-SLES-with-AbiWord/afb40c4c239acff8fbcc52c8dc8afa122490e711

Is the last copy of the document.  I have no idea why it was butchered back in 2017!

https://github.com/ether/etherpad-lite/wiki/How-to-enable-importing-and-exporting-different-file-formats-in-Ubuntu-or-OpenSuse-or-SLES-with-AbiWord/_history for history.

Someone will need to remake the docs referring to the old docs I guess?

**Comment by SamTV12345** [comment]
@rgmz I readded the docs and improved the formatting.

**Comment by HairyFotr** [comment]
From the history it looks like the two pages existed with nearly identical content, so I merged content and replaced one with a "Moved to" link to the other page. This page has changes after 2017, and both links should technically work, so I'm not sure what broke, but I apologize if it was broken for this long.

https://github.com/ether/etherpad-lite/wiki/How-to-enable-importing-and-exporting-different-file-formats-in-Ubuntu-or-OpenSuse-or-SLES-with-AbiWord/_history
https://github.com/ether/etherpad-lite/wiki/How-to-enable-importing-and-exporting-different-file-formats-with-AbiWord/_history

**Comment by SamTV12345** [comment]
No worries. It was a fix of maybe 10 minutes. Somehow both pages disappeared and the link was broken, redirecting every unauthorized user to the project wiki root.

**Comment by rgmz** [comment]
Thanks for the quick fix!

I agree that GitHub's behaviour was strange, which likely confused the issue.
