### ISSUE TITLE
Incompatible use with ImTranslator

### ISSUE THREAD

**Issue by chenzhenyao** [ether/etherpad-lite#5825]
### Behavior
When selecting text with the mouse, automatically add a large amount of text to the content.
It only happens:

On chrome
With [ImTranslator](https://chrome.google.com/webstore/detail/imtranslator-translator-d/noaijdpnepcgjemiklgfkcfbkokogabh)
This bug is more an incompatibility between Etherpad andImTranslator and may come from the extension.

ImTranslator is an extension of chrome

### Repro steps

1. Install [ImTranslator](https://chrome.google.com/webstore/detail/imtranslator-translator-d/noaijdpnepcgjemiklgfkcfbkokogabh) in Chrome
2. open [https://etherpad.wikimedia.org/p/xxx](https://etherpad.wikimedia.org/p/xxx)
3. Use the mouse to select any text

**Comment by JohnMcLear** [comment]
There is no way we can support every chrome extension as part of our efforts.

I'm very sorry but you'll need to ask the ImTranslator team to look into this.
