### ISSUE TITLE
Pad creation: "SecurityError: Permission denied to access property removeEventListener"

### ISSUE THREAD

**Issue by LordBeule** [ether/etherpad-lite#5829]
Hi guys,

I installed etherpad-lite (1:1.8.18-1) in Arch. It runs behind nginx (nginx-mainline 1.25.1-1).

As soon as I access a pad, I get the following error message in the log.

```
node[1774314]: [2023-07-14 15:26:58.549] [WARN] client - SecurityError: Permission denied to access property "removeEventListener" on cross-origin object -- {
node[1774314]:   errorId: 'NFGlQJweskBU9QAYXzMs',
node[1774314]:   type: 'Unhandled Promise rejection',
node[1774314]:   msg: 'SecurityError: Permission denied to access property "removeEventListener" on cross-origin object',
node[1774314]:   url: 'https://<FQDN>/blub/p/sdfsdf',
node[1774314]:   source: 'unknown',
node[1774314]:   linenumber: 19,
node[1774314]:   userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0',
node[1774314]:   stack: 's@https://<FQDN>/blub/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=ee725897:19:585\n' +
node[1774314]:     'frameReady@https://<FQDN>/blub/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=ee725897:19:1012\n'
node[1774314]: }
```
Every time I access the pad, the error message appears.

The option "trustProxy: true" has been set.

I don't know if I'm right here. However, I am looking for help in solving the problem.

**Comment by webzwo0i** [comment]
Do you embed Etherpad in a page with another domain? The error looks like it's trying to access removeEventListener on a DOM element that belongs to another domain, that is prohibited by same-origin policy.

Also try running without the nginx proxy first, to find out if this problem is related to your nginx setup. We have nginx documentation in the wiki.

btw the most recent version is 1.9.1

**Comment by JohnMcLear** [comment]
@LordBeule FWIW to do code blocks do three back ticks IE `````````

**Comment by JohnMcLear** [comment]
I'm gonna close as this is an old version of Etherpad and it's probably fine if he installs most recent release.

**Comment by fauust** [comment]
Hi!
I just spent a couple of hours trying to debug this, so putting my findings here just in case someone has the same problem.

Installation method: docker-compose with nginx reverse proxy and ssl termination.
Etherpad version: 1.9.2

When nginx general configuration has `add_header X-Frame-Options DENY always;` then the pad creation fails with the exact same message:

```console
etherpad    | [2023-08-28 12:39:48.525] [WARN] client - SecurityError: Permission denied to access property "removeEventListener" on cross-origin object -- {
etherpad    |   errorId: 'VqiWdE2UukHqWJExPvIc',
etherpad    |   type: 'Unhandled Promise rejection',
etherpad    |   msg: 'SecurityError: Permission denied to access property "removeEventListener" on cross-origin object',
etherpad    |   url: 'https://pad.domain.org/p/Z5AYQzLcLAWqhx1PnpLl',
etherpad    |   source: 'unknown',
etherpad    |   linenumber: 2981,
etherpad    |   userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0',
etherpad    |   stack: 'cleanup@https://pad.domain.org/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=1ce16530:2981:7\n' +
etherpad    |     'frameReady@https://pad.domain.org/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=1ce16530:3007:37\n'
etherpad    | }
```

**Comment by JohnMcLear** [comment]
Thanks for documenting your findings!
