### ISSUE TITLE
WebSocket connection failed error - but service seems running fine

### ISSUE THREAD

**Issue by longtaosha** [ether/etherpad-lite#5834]
**Describe the bug**
I successfully installed Etherpad (1.9.1 (2c77be5)). 
But every time I visit the page, either creating a new pad or visiting an exisiting pad, I will get this error on the Console, no feedbacks at the terminal side:
(But the fuctions seem working just fine, the collabration, the chat, etc. )
(Chrome)
WebSocket connection to 'ws://docs.winteam.tech/socket.io/?padId=test_pad_usingMySQL&EIO=3&transport=websocket&sid=LgS2ur1GEC3ConSzAAAG' failed: index.js:83 

(Firefox)
Firefox can’t establish a connection to the server at ws://docs.winteam.tech/socket.io/?padId=test_pad_usingMySQL&EIO=3&transport=websocket&sid=6EZj8erUaAs5uSuvAAAC. [socket.io.js:8:5939](http://docs.winteam.tech/socket.io/socket.io.js?v=8e8989cf)

**To Reproduce**
1. Go to 'http://docs.winteam.tech/p/test_pad_usingMySQL'
2. Hit button F12
3. Go to tab "Console"

**Expected behavior**
Not sure yet. 

**Screenshots**
![db3d837765aa27c27c38a54006af306](https://github.com/ether/etherpad-lite/assets/4934619/7054b2e8-b23e-4306-a843-b84691a17cb0)
![d525c7ec8b7df35edbe7e1fbe4d9898](https://github.com/ether/etherpad-lite/assets/4934619/656066c8-f51d-41b2-bbab-9df9890c2edb)

**Server :**
 - Etherpad version: (1.9.1 (2c77be5))
 - OS: [CentOS 7.2 64bit]
 - Node.js version (v16.20.1):
 - npm version (8.19.4):
 - Is the server free of plugins: no plugins installed. 

**Desktop **
 - OS: [Win10]
 - Browser [Chrome: Version 114.0.5735.199 (Official Build) (64-bit), Firefox: 115.0.2 (64-bit)]

I'm not sure if it's going to affect the fuctions or not, still trying to find out.

**Comment by SamTV12345** [comment]
How is your content delivered. Http or Https?

**Comment by SamTV12345** [comment]
If it is an internal error. Can you paste the errors of the etherpad instance?

**Comment by longtaosha** [comment]
> How is your content delivered. Http or Https?

I'm using http.

**Comment by longtaosha** [comment]
> If it is an internal error. Can you paste the errors of the etherpad instance?

I don't think there are any errors from the instance - no indicators from the Terminal, if that's what you mean.

**Comment by SamTV12345** [comment]
No problem. It could also be that modern browsers block unsecured websockets. You should add SSL e.g. via Lets Encrypt. Otherwise everything in this pad can be read by an attacker.

**Comment by longtaosha** [comment]
> No problem. It could also be that modern browsers block unsecured websockets. You should add SSL e.g. via Lets Encrypt. Otherwise everything in this pad can be read by an attacker.

Thank you, will do so.

**Comment by longtaosha** [comment]
This issue has been solved. 
Check out here if you need: [Setup Websocket Support on Apache+Nodejs](https://stackoverflow.com/questions/27526281/websockets-and-apache-proxy-how-to-configure-mod-proxy-wstunnel)

**Comment by SamTV12345** [comment]
> This issue has been solved.
> Check out here if you need: [Setup Websocket Support on Apache+Nodejs](https://stackoverflow.com/questions/27526281/websockets-and-apache-proxy-how-to-configure-mod-proxy-wstunnel)

Awesome. I have only used Nginx Proxy Manager. I knew from there that you have to tick Websocket support manually. Great that the issue is resolved.
