### ISSUE TITLE
The timeslider report an error When I upgrade from 1.8.12 to 1.8.18

### ISSUE THREAD

**Issue by TomNewChao** [ether/etherpad-lite#5845]
**Describe the bug**
The timeslider report an error When I upgrade from 1.8.12 to 1.8.18, The more information is detailed blow:
![image](https://github.com/ether/etherpad-lite/assets/50572318/eb6bc4fe-b34b-439c-9984-f3b24510d150)

**To Reproduce**

1.go to timeslider 
2.move the timeslider
3.see the picture about cannot read properties of undefined(reading substring)

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version:
 - OS: [e.g., Ubuntu 20.04]
 - Node.js version (`node --version`):
 - npm version (`npm --version`):
 - Is the server free of plugins: 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SamTV12345** [comment]
Hi @TomNewChao ,

thanks for creating an issue. Could you please upgrade to 1.9.1? We only support the current version as backports to previous versions are not really a thing in this project. After updating could you please report back if everything is working smoothly or that the bug is still present?

**Comment by TomNewChao** [comment]
Thanks for your reply, When i migrate the data in mysql to a new mysql in test environment and start to etherpad(1.8.18) by using migrate mysql.This issue is solved, But find the  other issue in below:
The content add automatic the below content:
![image](https://github.com/ether/etherpad-lite/assets/50572318/818fdeed-6605-491c-a2f9-52d955a918c3)

**Comment by SamTV12345** [comment]
Unfortunately I can't read this language 😅 . So no idea what the pad tries to say.

**Comment by TomNewChao** [comment]
> Unfortunately I can't read this language 😅 . So no idea what the pad tries to say.


This seems to be a translated font in Chinese. I am wondering if these additional and strange fonts are added due to translation

**Comment by TomNewChao** [comment]
When I upgrade to 1.9.1, The all issue is be solved. Thanks.
