### ISSUE TITLE
Grants CORS permission to embed in other domains

### ISSUE THREAD

**Issue by yendrapriambada** [ether/etherpad-lite#5850]
Hi there, I have a problem like this picture:
![image](https://github.com/ether/etherpad-lite/assets/73283816/f5006e13-6e5f-42cd-8342-94b3acbb9bb2)

how do i grant CORS permission to embed in another domain?

**Comment by SamTV12345** [comment]
You can take a look at the sameSite setting in settings.json. This is what the docs say:

> Value of the SameSite cookie property. "Lax" is recommended unless Etherpad will be embedded in an iframe from another site, in which case this must be set to "None". Note: "None" will not work (the browser will not send the cookie to Etherpad) unless https is used to access Etherpad (either directly or via a reverse proxy with "trustProxy" set to true).

So try setting it to None and you need to have SSL.

**Comment by SamTV12345** [comment]
@yendrapriambada Please close this issue if this resolved your issue.
