### ISSUE TITLE
Etherpad-lite version 1.9.2 doesn't work with redis database backend

### ISSUE THREAD

**Issue by brknkfr** [ether/etherpad-lite#5889]
**Describe the bug**

Somehow the connection to the redis database backend doesn't work anymore with etherpad-lite version 1.9.2. Version 1.9.1 still works fine, so I stay a moment longer with the old version.

**To Reproduce**
1. Configure remote redis database
2. Install etherpad-lite on a fresh system (Debian 11 Bullseye with nodejs version 18.17.1 from nodesource)
3. Start etherpad-lite with bin/run.sh

**Expected behavior**
A running etherpad-lite instance ...

**Server (please complete the following information):**
 - Etherpad version: 1.9.2
 - OS: Debian 11.7 
 - Node.js version (`node --version`): 18.17.1
 - npm version (`npm --version`): 9.6.7
 - Is the server free of plugins: no plugins activated

**Configuration**
```
{
  "ip": "0.0.0.0",
  "port": 9005,
  "dbType": "redis",
  "dbSettings": {
    "socket":{
      "host": "10.0.9.39",
      "port": 6384
    },
    "password": "VERYSECUREPASSWORD"
  },
  "users": {
    "superadmin": {
      "is_admin": true,
      "hash": "VERYSECUREPASSWORDHASH"
    }
  },
  "commitRateLimiting": {
    "duration": 1,
    "points": 100
  },
  "loglevel": "DEBUG"
}
```

**Log**
https://paste.momou.ch/?9d5dc5bae685d476#GpRm8M7gk5dyouNGE2oDeJf6htDnKKF7GhKGfxD9B5N3

Probably the relevant part is:

```
[2023-08-28 11:48:56.715] [INFO] console - Your Etherpad version is 1.9.2 (b1c34b5)
[2023-08-28 11:48:56.718] [DEBUG] secret-rotation expressSessionSecrets - new secret rotator (interval 86400000, lifetime: 864000000)
[2023-08-28 11:48:56.719] [DEBUG] secret-rotation expressSessionSecrets - starting secret rotation
[2023-08-28 11:48:56.719] [DEBUG] ueberDB - GET    - expressSessionSecrets:*-null - null - from database 
[2023-08-28 11:48:56.720] [ERROR] server - Error occurred while starting Etherpad
[2023-08-28 11:48:56.720] [ERROR] server - Metrics at time of fatal error:
{
  "httpStartTime": 0,
  "memoryUsage": 153112576,
  "memoryUsageHeap": 57215112,
  "ueberdb_lockAwaits": 0,
  "ueberdb_lockAcquires": 0,
  "ueberdb_lockReleases": 0,
  "ueberdb_reads": 0,
  "ueberdb_readsFailed": 0,
  "ueberdb_readsFinished": 0,
  "ueberdb_readsFromCache": 0,
  "ueberdb_readsFromDb": 0,
  "ueberdb_readsFromDbFailed": 0,
  "ueberdb_readsFromDbFinished": 0,
  "ueberdb_writes": 0,
  "ueberdb_writesFailed": 0,
  "ueberdb_writesFinished": 0,
  "ueberdb_writesObsoleted": 0,
  "ueberdb_writesToDb": 0,
  "ueberdb_writesToDbFailed": 0,
  "ueberdb_writesToDbFinished": 0,
  "ueberdb_writesToDbRetried": 0,
  "totalUsers": 0,
  "activePads": 0
}
[2023-08-28 11:48:56.722] [ERROR] server - TypeError: Cannot read properties of null (reading 'map')
    at SecretRotator._update (/srv/etherpad-lite/src/node/security/SecretRotator.js:169:30)
    at async SecretRotator.start (/srv/etherpad-lite/src/node/security/SecretRotator.js:108:5)
    at async exports.restartServer (/srv/etherpad-lite/src/node/hooks/express.js:186:5)
    at async exports.createServer [as hook_fn] (/srv/etherpad-lite/src/node/hooks/express.js:69:3)
[2023-08-28 11:48:56.723] [INFO] server - Exiting...
[2023-08-28 11:48:56.723] [INFO] server - Waiting for Node.js to exit...
[2023-08-28 11:49:01.723] [ERROR] server - Something that should have been cleaned up during the shutdown hook (such as a timer, worker thread, or open connection) is preventing Node.js from exiting
[2023-08-28 11:49:01.723] [ERROR] server - Enable `dumpOnUncleanExit` setting to get a dump of objects preventing a clean exit
[2023-08-28 11:49:01.723] [ERROR] server - Forcing an unclean exit...
```

**Comment by brknkfr** [comment]
The version runs fine with a dirtyDB backend.

**Comment by brknkfr** [comment]
It seems to be a problem with the session key (rotation).

**Comment by brknkfr** [comment]
After further tries, setting (or disabling) either `keyRotationInterval` or `sessionLifetime` to `null` seems to work, so there must be an error with the new key rotation stuff.
```
{  
  "cookie": {
    "keyRotationInterval": 86400000,
    "sessionLifetime": 86400000,
  }
}
```

**Comment by brknkfr** [comment]
Okey, there is still a problem.

1. Run a etherpad-lite instance 1.9.1 with a redis backend
2. Create a pad and write something.
3. Stop the instance and update the instance to version 1.9.2
4. Apply the Patch: https://github.com/ether/etherpad-lite/commit/efdf9dbe36831f5c536519f5dff56e54e043d1a1
5. Start the instance again.
6. Go to the pad ... It's empty!

Somehow the pad gets deleted or unaccessible with the new sessionkey handling.

**Comment by brknkfr** [comment]
Update: Somehow this new session key handling is not working at all, at least with a redis database. With version 1.9.2 no pads are persistently saved to the redis database. The pads are always gone after restarting the etherpad-lite instance.

1. Install and start an instance of etherpad-lite version 1.9.2 with a redis backend.
2. Create a pad and write something in it.
3. Stop the insance.
4. Restart the instance.
5. Go to the newly created pad and you'll find the default text but none of what you wrote in it before.

**Comment by SamTV12345** [comment]
Confirmed. The redis backend doesn't work. I have no idea why. The other database backends work only redis doesn't.

**Comment by brknkfr** [comment]
Hm. What to do now? Will there be sometime given a bugfix release, or should I consider changing the database backend? Are there migration paths from redis to another database type?

**Comment by SamTV12345** [comment]
I guess I need to take a look at it more thoroughly. Sadly none of the tests did catch that error. @JohnMcLear @webzwo0i Do you have time to take a look at this? The ueberdb tests are all green, so it should write to the database.

**Comment by JohnMcLear** [comment]
Sorry I'm not going to have time to look at this and I know very little about Redis so I'm probably the wrong person!

**Comment by SamTV12345** [comment]
> Hm. What to do now? Will there be sometime given a bugfix release, or should I consider changing the database backend? Are there migration paths from redis to another database type?

Because the dabase is abstracted with ueberdb2 you should be able to migrate without a problem to another database. Neithertheless I try to fix that bug.

**Comment by SamTV12345** [comment]
> Hm. What to do now? Will there be sometime given a bugfix release, or should I consider changing the database backend? Are there migration paths from redis to another database type?

I've got great news @brknkfr . It is not a bug but a feature 😄 . Try with:

```json
 "dbSettings": {
     "url: "redis://10.0.9.39:6384",
}
```
and it will write to the database. I'll fix your syntax so you will also get a connection with above solution. But this won't be available until 1.9.3. So please use the url syntax. That will continue to work throughout the next releases.

**Comment by brknkfr** [comment]
Seems to work! Thank you very much ...

**Comment by SamTV12345** [comment]
Sure no problem. I also found out that you can use the style above but you need to ditch the socket part. If you use host, port etc. directly it will work flawlessly. The above syntax is redis syntax if the driver is used directly which it is not.

**Comment by JohnMcLear** [comment]
Sorry I did document this somewhere but I guess it never got spotted -.-
