### ISSUE TITLE
Abiword not working in container when setting "INSTALL_ABIWORD"

### ISSUE THREAD

**Issue by ppom0** [ether/etherpad-lite#5908]
Using upstream Dockerfile and setting `INSTALL_ABIWORD=true` as build environment variable, abiword is installed.
But abiword-plugin-command isn't, and it is used in https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/Abiword.js#L52 .
```bash
90384a823c4c:/opt/etherpad-lite$ abiword --plugin AbiCommand
Plugin AbiCommand not found or loaded
90384a823c4c:/opt/etherpad-lite$ echo $?
255
```

fixed by pr https://github.com/ether/etherpad-lite/pull/5907

**Comment by SamTV12345** [comment]
Thanks for the issue and the pull request. It indeed fixed the issue. Don't know if you are on the Discord channel. I announced some time ago the next release and gave users a few days to test the new updated Alpine images. If you'd like to you can join the Discord and stay up to date if there is a new change in the images.

**Comment by ppom0** [comment]
Thanks for the proposal!
I'm not really invested in etherpad and don't usually use discord, it was an "easy fix".
We at Picasoft [used](https://gitlab.utc.fr/picasoft/projets/services/etherpad-yearly/) for years our own Dockerfile, then looked at the current one a few days ago. It has improved a lot since a few years ago, and decided to switch to the upstream one to reduce maintenance burden.

**Comment by SamTV12345** [comment]
No problem :D. Don't feel obligated to enter the Discord. I'll try to keep you updated on the release tab. I had a look at the repository. Very cool that you provide such an extensible docker image.  I added your page repository to the third party web sites.
