### ISSUE TITLE
Docker build with ETHERPAD_PLUGINS not working since 1.9

### ISSUE THREAD

**Issue by hillenbrkl** [ether/etherpad-lite#5953]
**Describe the bug**
Since version 1.9 the docker build with --build-arg ETHERPAD_PLUGINS="..." is not working anymore

**To Reproduce**
1. Go to base directory of 1.9.3
2. docker build --build-arg ETHERPAD_PLUGINS="ep_align" --tag my/etherpad:1.9.3 .

**Expected behavior**
A container should have been built.

**Screenshots**
2.394 npm ERR! code EINVAL
2.394 npm ERR! syscall rename
2.394 npm ERR! path /opt/etherpad-lite/node_modules/ep_etherpad-lite
2.394 npm ERR! dest /opt/etherpad-lite/node_modules/.ep_etherpad-lite-Xoizmm1M
2.395 npm ERR! errno -22
2.396 npm ERR! EINVAL: invalid argument, rename '/opt/etherpad-lite/node_modules/ep_etherpad-lite' -> '/opt/etherpad-lite/node_modules/.ep_etherpad-lite-Xoizmm1M'
2.398 
2.398 npm ERR! A complete log of this run can be found in: /home/etherpad/.npm/_logs/2023-09-29T13_48_54_847Z-debug-0.log

**Server (please complete the following information):**
 - Etherpad version: 1.0.3
 - OS: RHEL7.9
- Docker: 24.0.6

**Additional context**
The build worked with 1.8.x

**Comment by SamTV12345** [comment]
I tried your command:
```bash
docker build --build-arg ETHERPAD_PLUGINS="ep_align" --progress=plain --no-cache  --tag my/etherpad:19.3 .
 ```

the output is:
[output.pdf](https://github.com/ether/etherpad-lite/files/12769087/output.pdf)

Docker buildx version is Docker version 24.0.6, build ed223bc

Could you send me your output? Really weird that we get different outputs with Docker which should enable reproducible builds 😄

**Comment by hillenbrkl** [comment]
That's weird. After your successful build, I have tried out building again on another system (user environment is the same because shared via NFS). And there it is working. The only difference that I can see is that the working server is using XFS for /var/lib/docker while the failing server is using BTRFS. I am building dozens of containers each week on this machine, and newer came across such a phenomenon...

As it is working, we can close this issue.

**Comment by SamTV12345** [comment]
Thanks for the reply. Yes it's weird. We switched to Alpine and the latest node version but that should not influence your build. At least as far as I know.
