### ISSUE TITLE
When multiple people are in a pad, all users 

### ISSUE THREAD

**Issue by dlangh** [ether/etherpad-lite#5954]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version:
 - OS: [e.g., Ubuntu 20.04]
 - Node.js version (`node --version`):
 - npm version (`npm --version`):
 - Is the server free of plugins: 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SamTV12345** [comment]
Seems like a duplicate ^^. I'll close this one in favor of #5955
