### ISSUE TITLE
When multiple users goto the same pad, all users "inherit" the username of the first user in the system

### ISSUE THREAD

**Issue by dlangh** [ether/etherpad-lite#5955]
**Describe the bug**
This does not happen when 2 users goto the first pad that they both open, but subsequent pads result in the same username being displayed in the list of users in the pad.

**To Reproduce**
1. Person 1 opens a pad, then shares that url for the pad with Person 2
2. Person 2 goes into pad from step 1, both usernames will display correctly
3. Person 1 goes into another pad, then shares that url with Person 2.
4. Person 2 goes into pad from step 1, only now the username list in Etherpad shows the first username 2x.
5. Any additional pads will exhibit this same problem, only the first pad that is opened works.  To "reset" things it was necessary to clear browser cache otherwise if Person 2 opened a 3rd pad they would still display Person 1 username

**Expected behavior**
Each user should have their username displayed at all times

**Screenshots**
If applicable, add screenshots to help explain your problem
![Screenshot 2023-09-29 at 9 59 14 AM](https://github.com/ether/etherpad-lite/assets/1436671/8f2db7ed-6852-4353-a9f8-e2831851e4cf)
.

**Server (please complete the following information):**
 - Etherpad version: 1.9.2 (this also occurs with V1.9.1)
 - OS: Ubuntu 20.04
 - Node.js version (`node --version`): v16.20.2
 - npm version (`npm --version`): 8.19.4
 - Is the server free of plugins:  Yes, except I need to keep ep_headerauth plugin enabled otherwise could not get user authenticated and the usernames set.  

**Desktop (please complete the following information):**
 - OS: Mac Os Ventura 13.6 for both users
 - Browser: Chrome
 - Version: 117.0.5938.132

**Additional context**

![Screenshot 2023-09-29 at 10 17 12 AM](https://github.com/ether/etherpad-lite/assets/1436671/df9b1d47-549f-4a1b-9623-f99e2cf39dec)
As you can see from the above screenshot the authorID remains correct but the username gets hijacked. 

Users are correctly signed on and their username set as shown with the user briggs, when they goto the first pad "ER-135469" they are identified with the correct username, but when they subsequently goto "dml_test" they "become" dlanghor however their authorId remains correct it's just the username

Finally, I tested this with a larger set of users (4) and the same result occured where Etherpad would display all 4 users as being the same username

**Comment by SamTV12345** [comment]
Hm. I tried it but I can't really find a way to hijack a username. I'll list the visited urls:
1. <host>/p/test, name FirstUser (1)
2. <host>/p/test, name SecondUser (2)
3. <host>/p/test123 (1) |  Only share or also visit for second user? 
4. <host>/p/test, (2)

I still get FirstUser/SecondUser in the output.

Could it be that you used the same browser multiple times? Please try again with multiple browsers. That way you should have different sessions.

**Comment by dlangh** [comment]
Hi, since my company uses SSO SAML auth, it's not possible for me to become another user.  To test this I have to have another person test it with me, which is how I did this.  If I use multiple browsers, I'd still be the same user, just with a different session.

**Comment by SamTV12345** [comment]
Hm. Could it be that the SAML plugin is the issue? Which other plugins are installed on your Etherpad instance?

**Comment by SamTV12345** [comment]
Or you can try to reproduce that on a clean local installation of Etherpad. If the problem persists this is a serious issue otherwise one of the plugins is implemented bad.

**Comment by dlangh** [comment]
I will try this locally, though that will take SAML out of the equation and I'll need use the chrome ModHeader plugin to supply username and then use both Chrome and Chromium so I'll have unique browsers and sessions and use different names.  I suspect it will work just fine though.  I feel like my problem has something to do with my environment, though I am at a loss where to start to try and debug it.

Also for what it's worth the system at my company is a brand new ubuntu 20.04 system that I installed Etherpad 1.9.1 fresh.  It's largely stock, though I did initially install the default node version that comes with Ubuntu which was 14.x which worked with 1.9.1 but crashed when I tried to upgrade to 1.9.2.  Switching to node V16 allowed me to get 1.9.2 working. 
I'm not a node expert and I don't know if some remnant of Node 14 is causing issues. 

Anyway, I'll setup locally using a VM (I'm on a mac so I'd like to test with Ubuntu 20.04 as well to minimize changes)

**Comment by SamTV12345** [comment]
Thanks for the help. Very much appreciated. Node 14 is unfortunately not supported anymore  with new updates that is why we switched to Node16 for the future. The current LTS version 18 is the best for a stable Etherpad instance which will be supported until 30.04.2025 by Node.

I'd suggest starting from scratch, check if you find an issue and then slowly add more production env things like the pads, plugins etc.

**Comment by dlangh** [comment]
> Hm. Could it be that the SAML plugin is the issue? Which other plugins are installed on your Etherpad instance?

I removed all plugins I was using except the SAML plugin.  I had a number installed, but as per the request at top of this issue, I removed them, restarted and tested to take screenshots

**Comment by SamTV12345** [comment]
> > Hm. Could it be that the SAML plugin is the issue? Which other plugins are installed on your Etherpad instance?
> 
> 
> 
> I removed all plugins I was using except the SAML plugin.  I had a number installed, but as per the request at top of this issue, I removed them, restarted and tested to take screenshots

Did you stumble upon the same problem already? Or is there no issue with a clean installation?

**Comment by dlangh** [comment]
Hi, I wanted to let you know that I figured out my problem, it was not Etherpad but my Apache config.
For some background, we have been using Etherpad for years and the current production installation is Etherpad v1.7.5 running in a Docker container on Ubuntu 18.04

I needed to upgrade both the OS and Etherpad to the most recent, in doing this, I ran into problems with the username not being set inside of a Docker container (for this new instance) so I installed Etherpad directly on the server and chucked Docker.  This worked for authentication and everything else as far as I could tell was working.  It wasn't until I was in a pad with another 2 testers that I realized that it was doing the inherit username thing.

So, the problem as it turns out as I said was the Apache config for this site.  I had used the same apache site config from the old v1.7.5 site and that turned out to be a mistake.  Someone else before I got involved with this project had added a bunch of Cache settings which when I finally commented them all out, the inherit name issue went away.

I am including them here in the event someone else runs into this issue, if so my hope is I can save someone else the time I wasted on this problem:

```
  # enable caching for all requests; cache content on local disk
  #CacheEnable disk /
  #CacheRoot /var/cache/apache2/mod_cache_disk/etherpad

  # common caching directives
  #CacheQuickHandler off # move caching to after authentication, very important
  #CacheLock on
  #CacheLockPath /tmp/mod_cache-lock-etherpad
  #CacheLockMaxAge 5
  #CacheHeader On

  # cache control
  #CacheIgnoreNoLastMod On

  # Etherpad sometimes sets Expires in the past which is useless, so remove it
  #Header unset Expires

  # Fix Caching headers on Javascript
  <LocationMatch ".js$">
    # "unset Date" is required because Etherpad sets some weird Date headers in the past which messes with caching
    #Header unset Date
    #Header set Cache-Control "max-age=86400"
  </LocationMatch>

  # Manually set Cache-Control on some things Etherpad doesn't do it on
  <LocationMatch "^/(locales|pluginfw/plugin-definitions\.json|favicon.ico)">
    #Header set Cache-Control "max-age=86400"
  </LocationMatch>

```

Now it may be that only one of these cache settings is in fact causing the issue, my inclination at this point is to not re-add any of these as the situation has changed from Etherpad running in a docker container which was hosting several other sites to a dedicated machine with more CPU and more RAM.

Thanks again for being so responsive, it is appreciated.  I was at the end of my rope!

**Comment by SamTV12345** [comment]
Thanks for the update and posting the solution. Great that this is resolved for you.
