### ISSUE TITLE
Feature: CSS Minification with "build-css" Script

### ISSUE THREAD

**Issue by rishi457** [ether/etherpad-lite#5958]
Feature Idea: Automatic CSS Minification Script

Describe the Solution You'd Like:

The goal of this feature is to introduce an automatic CSS minification script, named "build-css," into the project's build process. This script will optimize CSS files for production use by removing unnecessary whitespace, comments, and formatting while preserving essential styling information.

Implementation Details:

Script Name and Purpose:

Name: "build-css"
Purpose: The script's primary purpose is to minify CSS files and prepare them for production deployment. It will target a designated source CSS file, typically named "src/main.css," and output the minified CSS as "dist/main.min.css."
Dependencies:

Utilize the "clean-css" package as the CSS minification tool within the script. This package is well-maintained, reliable, and widely used in the industry for CSS optimization.
Script Execution:

Developers can execute the "build-css" script via the command line using the following command:
arduino
Copy code
npm run build-css
Running this command will initiate the CSS minification process, and the resulting minified CSS file will be generated within the project's "dist" directory.
Alternatives Considered:

Manual CSS Minification:

Alternative: Instead of automating CSS minification with a dedicated script, developers could manually run a CSS minification command each time they want to optimize the stylesheets.
Drawbacks: Manual minification is error-prone, time-consuming, and may lead to inconsistencies. Automation with a script is more efficient and reduces the risk of human error.
Third-Party Build Tools:

Alternative: Integrate third-party build tools like Grunt or Gulp to handle CSS minification.
Drawbacks: While effective, this approach adds complexity to the project setup, requiring developers to configure and maintain additional build tools. The "build-css" script offers a simpler, more focused solution.
Additional Context:

CSS minification is a crucial step in modern web development. Minified CSS files are smaller in size, leading to faster page load times, reduced bandwidth consumption, and improved user experiences.
The introduction of the "build-css" script aligns with best practices for web development and ensures that stylesheets are optimized for production deployments.
Developers can easily customize the script's source and destination paths to suit the project's structure and requirements.
Plugin Integration (Optional):

If desired, you can extend this feature by integrating it with a build tool or task runner plugin specific to your project. For example, if you are using Webpack as your build tool, you can create a custom Webpack plugin that automatically triggers CSS minification as part of the build process. This provides a seamless integration of the "build-css" script into your existing development workflow.

By implementing this feature, you empower developers to effortlessly optimize CSS files, enhance web application performance, and maintain cleaner and more efficient stylesheets for the "ep_etherpad-lite" project.

**Comment by SamTV12345** [comment]
Don't know what you and your bots try to sneak into Open Source projects. You won't have any success here. Every pull request is tested thoroughly 
![image](https://github.com/ether/etherpad-lite/assets/40429738/6c14d761-5fad-4eed-b4cb-65647f3aa5d9)
