### ISSUE TITLE
pdf export using AbiWord fails due to bad intermediate HTML

### ISSUE THREAD

**Issue by risacher** [ether/etherpad-lite#5985]
**Describe the bug**
In trying to export to PDF using Abiword / AbiCommand, the export fails because the HTML is slightly invalid and Abiword is stupidly picky.

```
$ abiword --plugin AbiCommand
Unable to init server: Could not connect: Connection refused

** (abiword:1325175): WARNING **: 18:22:41.983: clutter failed 0, get a life.
Unable to init server: Could not connect: Connection refused
AbiWord command line plugin: Type "quit" to exit
AbiWord:> convert /tmp/etherpad_export_2796631100.html /tmp/etherpad_export_2796631100.pdf pdf
AbiWord: could not open the file [/tmp/etherpad_export_2796631100.html]
error -1
AbiWord:> quit

$ tidy -xml /tmp/etherpad_export_2796631100.html
line 43 column 1 - Error: unexpected </head> in <meta>
line 125 column 43 - Warning: unescaped & which should be written as &amp;
line 127 column 16 - Warning: unescaped & which should be written as &amp;
line 253 column 6 - Warning: unescaped & which should be written as &amp;
line 374 column 1 - Error: unexpected </body> in <br>
line 375 column 1 - Error: unexpected </html> in <br>
Tidy found 3 warnings and 3 errors!
```

If I edit the HTML and replace `<meta ....>` with `<meta .../>` and change `"& "` to `"&amp; "` and `<br>` with `<br/>`, then AbiWord no longer has issues. 

This is basically the same issue as #3732.  I attached a sample intermediate HTML file to that issue.

**Comment by SamTV12345** [comment]
Can you try samuel19982/etherpad-testing? It contains a fix for the three errors with the meta tags. The other errors are dependent from the content which is a bit harder to fix.

**Comment by risacher** [comment]
I tried to run this, but I think you're referring to a docker image built for arm?  I don't have one of those handy.  Is there a specific branch on github to look at?  I can do that easy enough.  FWIW, I suspect the '&' causes the problems.

**Comment by SamTV12345** [comment]
@risacher Does it work now?

**Comment by risacher** [comment]
Candidly, despite having selfhosted etherpad_lite for over ten years, I'm trying to run the develop branch and it crashes with this error on first pad load: 

[2023-11-13T18:10:43.079] [INFO] settings - [2023-11-13 18:10:43.078] [DEBUG] AbsolutePaths - /home/magnus/temp/etherpad-lite/src/node_modules/ep_etherpad-lite does not end with "src"

As such, I can't answer your question, but I'll verify your fix when I get this other issue sorted.

**Comment by SamTV12345** [comment]
Hi. Thanks for testing this. This error happens either because there is a:
- package.json
- package-lock.json

in the root directory or because you upgraded the package-lock.json to v3 with npm>6

**Comment by risacher** [comment]
Yeh, I forgot about #5827, which Ironically, I also reported.

**Comment by SamTV12345** [comment]
> Yeh, I forgot about #5827, which Ironically, I also reported.

Yes 😃 . What a coincidence lol.

**Comment by risacher** [comment]
For what it's worth, with the current develop branch, the workaround of setting ETHERPAD_PRODUCTION=true and/or setting NODE_ENV=production do not work for me in terms of getting etherpad_lite to run.  I'm getting a crash at first pad load everytime.  I don't have package.json or package-lock.json in the root.  I do have node v16.20.1 and npm v8.19.4.  Since my database is sqlite3 I've been running `cd src; npm install better-sqlite3` before I start, and that's maybe messing up the package-lock.json.

**Comment by risacher** [comment]
As I noted in a comment to #5827, I was able to get HEAD to run in my previous setup by doing `cd src; npx npm@v6 install better-sqlite3`.  And with full-up test, the PDF export with AbiWord works okay for pads that don't contain '&' characters.  

Here's a really odd observation:  a pad that contains `&amp;` renders correctly, by which I mean that the pdf contains the string '&amp;' _not_ the character '&', which is what I speculated would happen.  In fact, further testing indicates that the crash I'm seeing is caused by the two-character sequence '& ', that is, an ampersand followed by a space.   An ampersand followed by something other than a space seems to render okay.  

I created a pad with the following text:

```
Ampersand by itself in the middle of text & following text
Ampersand as an HTML entity &gt; for greater than
Amersand as an HTML entity for itself &amp; but with text after
Amersand at the end of a line &
Foo
```

This how etherpad rendered it in the temporary HTML file that AbiWord was asked to convert: (/tmp/etherpad_export_4067854474.html):

```
<body>
Ampersand by itself in the middle of text & following text<br>
Ampersand as an HTML entity &amp;gt; for greater than<br>
Amersand as an HTML entity for itself &amp;amp; but with text
after<br>
Amersand at the end of a line &<br>
Foo<br>
<br>
```
Interestingly, this is *not the same* as what is generated as a normal HTML export:
```
<body>
Ampersand by itself in the middle of text &amp; following text<br>Ampersand as an HTML entity &amp;gt; for greater than<br>Amersand as an HTML entity for itself &amp;amp; but with text after<br>Amersand at the end of a line &amp;<br>Foo<br><br>
</body>
```

**Comment by risacher** [comment]
So... looking at the actual code in node/handler/ExportHandler.js, it seems that the difference between an HTML export and an AbiWord export is that plain HTML export is generated by exporthtml.getPadHTMLDocument() and returned as the response, but when PDF output is being generated by AbiWord or soffice, 'tidy' is run on the HTML before passing it to the PDF conversion.  If I run the HTML export from my last comment through tidy, it converts it into a form that crashes Abiword. 

I commented out the line in node/handlerExportHandler.js `await TidyHtml.tidy(srcFile);` and the Abiword PDF export worked as it should.  Presumably, if I had never enabled 'tidy' in settings.json, this bug would not have occurred.  

I don't know how y'all core devs want to handle this.  You could remove 'tidy' for Abiword exports, (maybe soffice too), you could document the conflict somewhere.  Honestly, I don't know what value 'tidy' brings and if it's still relevant.

**Comment by SamTV12345** [comment]
Can you setup a sample pad and export that with tidy and without it? At least as far as the documentation states it should reduce errors in the markup, not create new ones.

**Comment by risacher** [comment]
[testtesttest.zip](https://github.com/ether/etherpad-lite/files/13365559/testtesttest.zip)

I combined the files into a .zip because of GitHub file type limitations.

testtesttest.txt is the contents of the pad
testtesttest.html is an HTML export from Etherpad.
testtesttest-tidy.html is that file run through /usr/bin/tidy (HTML Tidy for Linux version 5.6.0) (from Ubuntu 'tidy' package)
testtesttest.pdf is the output of a PDF export from Etherpad using AbiWord backend WITHOUT using tidy.
There is no PDF export USING tidy because `abiword --plugin AbiCommand` crashes on the tidy'd HTML file.

**Comment by SamTV12345** [comment]
Wtf. This tidy package creates invalid html instead of just cleaning it. What a weird package.

**Comment by risacher** [comment]
So... tidy was first written in 1994.  What is considered valid HTML has changed a little bit in the last 30 years. (I'm old enough to remember.) It used to be considered normal - or at least okay - to leave ampersands unquoted if they weren't part of a valid character reference.

I just read the HTML spec on this issue, (https://html.spec.whatwg.org/#character-reference-state) and honestly, I'm still not sure if having a "raw ampersand" that's not part of a character reference is _technically_ valid HTML.  Various online sources say no, but my read is that scanning an ampersand should push the parser into "character reference state" but then scanning anything other than an ASCII alphanumeric or '#' should reconsume in the 'return state' which I think means that it should work...?  But the technicality doesn't matter - it's controversial enough that it shouldn't be done by tidy, (IMHO) and it's breaking PDF export in Etherpad.

There is an open issue in tidy, BTW: https://github.com/htacg/tidy-html5/issues/1079

**Comment by SamTV12345** [comment]
> So... tidy was first written in 1994. What is considered valid HTML has changed a little bit in the last 30 years. (I'm old enough to remember.) It used to be considered normal - or at least okay - to leave ampersands unquoted if they weren't part of a valid character reference.
> 
> I just read the HTML spec on this issue, (https://html.spec.whatwg.org/#character-reference-state) and honestly, I'm still not sure if having a "raw ampersand" that's not part of a character reference is _technically_ valid HTML. Various online sources say no, but my read is that scanning an ampersand should push the parser into "character reference state" but then scanning anything other than an ASCII alphanumeric or '#' should reconsume in the 'return state' which I think means that it should work...? But the technicality doesn't matter - it's controversial enough that it shouldn't be done by tidy, (IMHO) and it's breaking PDF export in Etherpad.
> 
> There is an open issue in tidy, BTW: [htacg/tidy-html5#1079](https://github.com/htacg/tidy-html5/issues/1079)

Thanks for the research. I checked the code it seems like tidy only runs for Abiword and SOffice and that causes more problems than needed. So I don't really see a reason why we should keep tidy as is.

**Comment by SamTV12345** [comment]
@risacher I found this beautifier https://beautifier.io/ . Somehow when I paste the html it makes everything more messy. Can you find a good setting or do we just leave out everything together.
