### ISSUE TITLE
Broken links on etherpad.org

### ISSUE THREAD

**Issue by Rahullkumr** [ether/etherpad-lite#6001]
**Describe the bug**
There are many broken links on the etherpad.org website.

**To Reproduce**
1. Go to https://etherpad.org/
2. Scroll down to headings `Collaborating in really real-time` and `Contribute`
3. Click on **pick** and **get in touch** respectively
4. See error (screenshots attached)

**Expected behavior**
The link should take the user to a valid page on the etherpad.org website.

**Screenshots**

![nw](https://github.com/ether/etherpad-lite/assets/42183055/89d76c34-8ec5-4ec9-b60d-fc7007cae078)
![nww](https://github.com/ether/etherpad-lite/assets/42183055/d9c64ba8-3b76-40ab-86c0-b55006ba4a64)
![getit](https://github.com/ether/etherpad-lite/assets/42183055/1bc6fea4-913a-4e31-924d-a0f3f8996d4d)

**Server (please complete the following information):**
 - Etherpad version: not required
 - OS: [not required]
 - Node.js version (`node --version`): not required
 - npm version (`npm --version`): not required
 - Is the server free of plugins: not required

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Brave]
 - Version [Chromium 118]

**Smartphone (please complete the following information):**
 - Device: [Xiomi Note 5]
 - OS: [android 9]
 - Browser [Brave]
 - Version [118]

**Additional context**
Everything else is working fine.

**Comment by SamTV12345** [comment]
Thanks for the issue. I fixed it on the etherpad website. It now scrolls corretly to the links or contributing section.

**Comment by Rahullkumr** [comment]
very good
