### ISSUE TITLE
Outdated README on docker hub

### ISSUE THREAD

**Issue by Gared** [ether/etherpad-lite#6017]
Our README on https://hub.docker.com/r/etherpad/etherpad is outdated. Docker has an example to use github action to do that: https://docs.docker.com/build/ci/github-actions/update-dockerhub-desc/
Should we add this to our project? Is there a simpler way?

**Comment by SamTV12345** [comment]
That sounds like a great idea. I can then edit the Readme without you giving me the credentials to the DockerHub account. Add it maybe to the docs directory and create an action that only runs when something in that directory changes.
