### ISSUE TITLE
Consider distributing the linux version on Flathub

### ISSUE THREAD

**Issue by Heus-Sueh** [ether/etherpad-lite#6045]
* * *

name: Feature request
about: distribute the linux version on flathub
title: ''Consider distributing the linux version on Flathub"
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
The problem is that downloading programs directly from the website is something that is no longer necessary with the existence of flathub and flatpak

**Describe the solution you'd like**
distribute the linux version on flathub

**Comment by SamTV12345** [comment]
Do you know how the process works? I created a draft pull request [here](https://github.com/flathub/flathub/pull/4719)

**Comment by Heus-Sueh** [comment]
> Do you know how the process works? I created a draft pull request [here](https://github.com/flathub/flathub/pull/4719)

sorry, unfortunately I don't know how, but thank you for accepting my suggestion so quickly

**Comment by SamTV12345** [comment]
No problem. I'll try to find a similar application that uses the same tech stack and take that manifest as a basis.

**Comment by Heus-Sueh** [comment]
> No problem. I'll try to find a similar application that uses the same tech stack and take that manifest as a basis.

Sorry to cause this problem, I thought Etherpad-lite was a client, but it is a server so flatpak is not recommended for this. This pull request can be closed and sorry again for the confusion.

**Comment by SamTV12345** [comment]
Ah yes it's a server and accessible via the browser. No worries.
