### ISSUE TITLE
Log level is not being respected after upgrading to version 1.9.5

### ISSUE THREAD

**Issue by 0x46616c6b** [ether/etherpad-lite#6075]
**Describe the bug**

After upgrading Etherpad to 1.9.5 (from 1.9.4) the setting `loglevel` isn't respected anymore. The default `INFO` is used.

**To Reproduce**

1. Start Etherpad with `"loglevel": "ERROR"`
2. See the output
3. INFO logs are shown

**Expected behavior**

Only `ERROR` logs are shown.

**Server:**
 - Etherpad version: 1.9.5
 - OS: Debian 12
 - Node.js version (`node --version`): v18.13.0
 - npm version (`npm --version`):9.2.0
 - Is the server free of plugins: no

**Comment by SamTV12345** [comment]
Thanks for reporting that issue. Did this really work on v1.9.4? Could you test it In a few minutes on the develop tag and see if it works also in your configuration? It should be fixed.

**Comment by 0x46616c6b** [comment]
Yes, with the fix, the log level is respected.

**Comment by 0x46616c6b** [comment]
And for the sake of completeness, it was also broken on 1.9.4 (I checked that too).

**Comment by SamTV12345** [comment]
Thanks for confirming that this is fixed 😄
