### ISSUE TITLE
Abiword not picked up after installation and permissions

### ISSUE THREAD

**Issue by q2apro** [ether/etherpad-lite#6082]
**Describe the bug**
Etherpad Lite does not import Word files, says Abiword is not installed.

**To Reproduce**
1. Install Etherpad via Docker.
2. Install Abiword according to tutorial: https://github.com/ether/etherpad-lite/wiki/How-to-enable-importing-and-exporting-different-file-formats-with-AbiWord
3. Go to Etherpad and click on import button
4. See the warning message - or try import, does not work.

**Expected behavior**
Import of DOCX file works. No warning message.

**Server (please complete the following information):**
 - Etherpad version: 1.9.6 (latest)
 - OS: Ubuntu 22.04
 - Is the server free of plugins: installed table plugin

**Additional context**

According to the [tutorial](https://github.com/ether/etherpad-lite/wiki/How-to-enable-importing-and-exporting-different-file-formats-with-AbiWord) www-data must be added to the sudoers so it works. I did this and it still does not work.

1. `apt-get install abiword`
2. `which abiword` shows location "/usr/bin/abiword"
3. `nano /etc/sudoers`
4. at end of file insert `www-data ALL = NOPASSWD: /usr/bin/abiword`

After it did not work, I also tried:

	# grant read-write-execute permissions to usergroup www-data
	chgrp www-data /usr/bin/abiword   # make group part of folder
	chmod g+rw /usr/bin/abiword   # change access rights

	ls -l /usr/bin/abiword  # see folder permissions (with "root www-data")

I restarted the server. I restarted Etherpad Docker. 

Still, Etherpad shows import is not possible.

In the pad it prints:

> Error: Abiword does not exist at this path, check your settings file. -- To suppress these warning messages change suppressErrorsInPadText to true in your settings.json

**Comment by SamTV12345** [comment]
Hi thanks for creating an issue. So if I understand you correctly you install Abiword via the host's package manager and use Etherpad in a docker container. The problem is that the Abiword executable and Etherpad are isolated from each other. You need to map that executable into the container or use the containers capabilities to install Abiword. I'll create a guide for you.

**Comment by q2apro** [comment]
Hello and thank you. Now I see.

I thought since Abiword is explicitly mentineed in the settings, there is already a connection somehow for Etherpad to communicate with Abiword installed on the server.

It would be great if you provide information how to set up this connection, so the import also works for the Docker image.

**Comment by SamTV12345** [comment]
You can install Abiword by doing:

```bash
git clone https://github.com/ether/etherpad-lite.git
docker build  --build-arg="INSTALL_ABIWORD=true" -t etherpad/custom-installation .
```

After that replace in your docker-compose etherpad/etherpad in the image section with etherpad/custom-installation.
