### ISSUE TITLE
Etherpad Docker container does not restart after adding custom language Strings to settings.json

### ISSUE THREAD

**Issue by q2apro** [ether/etherpad-lite#6086]
**Describe the bug**

**To Reproduce**
1. Install Etherpad Docker container
2. Go to `/admin/settings`
3. Add the following configuration:

```
  "customLocaleStrings": {
	"de-de": {
		"index.newPad": "Neues Dokument"
	},
	"en-gb": {
		"index.newPad": "New Document"
	}
  },
```

5. Scroll down and click 'Save Settings' and 'Restart Etherpad'
6. Result: Server gets stuck.
7. Checking with `docker ps` it shows `Status: Restart`.
8. When executing `docker container restart etherpad` it does not restart anymore. Stuck with `Up 6 seconds (health: starting)`.

**Expected behavior**
A clean restart of the server.

**Server (please complete the following information):**
 - Etherpad version: latest
 - OS: Ubuntu 22

<hr>

In the JSON log I found in `/var/lib/docker/containers/containerid`:

```
{"log":"\u001b[91m[2023-12-30T07:08:43.495] [ERROR] server - \u001b[39mTypeError: Cannot set properties of undefined (setting 'index.newPad')\n","stream":"stdout","time":"2023-12-30T07:08:43.495919801Z"}
{"log":"    at /opt/etherpad-lite/src/node/hooks/i18n.js:77:32\n","stream":"stdout","time":"2023-12-30T07:08:43.495929896Z"}
{"log":"    at Function.each (/opt/etherpad-lite/src/node_modules/underscore/underscore-node-f.cjs:1328:7)\n","stream":"stdout","time":"2023-12-30T07:08:43.495934403Z"}
{"log":"    at /opt/etherpad-lite/src/node/hooks/i18n.js:75:9\n","stream":"stdout","time":"2023-12-30T07:08:43.495937878Z"}
{"log":"    at Function.each (/opt/etherpad-lite/src/node_modules/underscore/underscore-node-f.cjs:1328:7)\n","stream":"stdout","time":"2023-12-30T07:08:43.495940913Z"}
{"log":"    at getAllLocales (/opt/etherpad-lite/src/node/hooks/i18n.js:73:7)\n","stream":"stdout","time":"2023-12-30T07:08:43.495944178Z"}
{"log":"    at exports.expressPreSession [as hook_fn] (/opt/etherpad-lite/src/node/hooks/i18n.js:107:19)\n","stream":"stdout","time":"2023-12-30T07:08:43.495947343Z"}
{"log":"    at /opt/etherpad-lite/src/static/js/pluginfw/hooks.js:272:18\n","stream":"stdout","time":"2023-12-30T07:08:43.495950698Z"}
{"log":"    at new Promise (\u003canonymous\u003e)\n","stream":"stdout","time":"2023-12-30T07:08:43.495953662Z"}
{"log":"    at callHookFnAsync (/opt/etherpad-lite/src/static/js/pluginfw/hooks.js:235:16)\n","stream":"stdout","time":"2023-12-30T07:08:43.495956747Z"}
{"log":"    at /opt/etherpad-lite/src/static/js/pluginfw/hooks.js:350:54\n","stream":"stdout","time":"2023-12-30T07:08:43.495979881Z"}
{"log":"    at Array.map (\u003canonymous\u003e)\n","stream":"stdout","time":"2023-12-30T07:08:43.495983377Z"}
{"log":"    at exports.aCallAll (/opt/etherpad-lite/src/static/js/pluginfw/hooks.js:350:13)\n","stream":"stdout","time":"2023-12-30T07:08:43.495986501Z"}
{"log":"    at exports.restartServer (/opt/etherpad-lite/src/node/hooks/express.js:231:15)\n","stream":"stdout","time":"2023-12-30T07:08:43.495989546Z"}
{"log":"    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n","stream":"stdout","time":"2023-12-30T07:08:43.495994573Z"}
{"log":"    at async exports.createServer [as hook_fn] (/opt/etherpad-lite/src/node/hooks/express.js:69:3)\n","stream":"stdout","time":"2023-12-30T07:08:43.496001624Z"}
```

> Cannot set properties of undefined (setting 'index.newPad')

<br>

**Main Question:**
Where to find the settings.json and edit the config so the container can start again?! – I am new to Docker and could find the Etherpad settings.json on the server. I have searched in `/var/lib/docker/containers/` without success.

How can I access the settings. I tried:

`docker stop etherpad`
`docker exec -it etherpad /bin/bash`

And I get `Error response from daemon: Container id12345 is not running`. So I cannot execute inside docker: `cat /opt/etherpad-lite/settings.json`

I solved the restart issue with FTP client, going to `/var/lib/docker/overlay2/` sorting them by last modified. Then going into the latest folder, and finding the `settings.json` there:  `/var/lib/docker/overlay2/LONGID/diff/opt/etherpad-lite/settings.json` I changed the faulty config and then I could restart the Etherpad Docker container.

**Comment by SamTV12345** [comment]
Seems like you created a named volume.That will put it into the overlay folder. It is best to use a path on the docker host. That way you can determine where the settings.json should be saved. Concerning the other problem with the i18n strings I'll have a look at it.

**Comment by SamTV12345** [comment]
The other issue is fixed. The language string for German is "de". Unfortunately there was not a safeguard that checked if the locale is even registered. I added a check for the language and it shows now a better error message with even a suggestion for a similar language. So your json works with:

```
  "customLocaleStrings": {
	"de": {
		"index.newPad": "Neues Dokument"
	},
	"en-gb": {
		"index.newPad": "New Document"
	}
  },
  ```
