### ISSUE TITLE
Remove the predefined text from new Pad when user does first input/click/key

### ISSUE THREAD

**Issue by q2apro** [ether/etherpad-lite#6089]
Feature request
title: Remove predefined text when user clicks on it or moves the cursor or on first input/key event
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
Every time a user users creates a new pad, s/he needs to delete the predefined text. This is bad usability.

**Describe the solution you'd like**
Remove predefined text when user clicks on it or moves the cursor or on first input/key event

**Alternative**
Put the hints/tips somewhere else and not into the pad content.

**Plugin?**
Could not find any plugin for this.

**Comment by SamTV12345** [comment]
You can adapt the text via an env variable DEFAULT_PAD_TEXT or in your settings.json with defaultPadText. Leaving it blank will display no text when a pad is created.

**Comment by q2apro** [comment]
I need this text to inform the users what they can do and what they have to be aware of.

So the options that come to my mind:

1. Having the "intro text" as an overlay?!
2. Remove the intro text with first key event.
3. Have the text as a placeholder like with textareas.

How to achieve one of those? - I am using Etherpad docker.

**Comment by q2apro** [comment]
How can I show a simple Javascript alert (with the hints) when the site loads?

It is important to my users. Since they are very young, ,ost of them do not delete the predefined text and just write below it.

**Comment by SamTV12345** [comment]
You should be able to simply add a plugin that shows an alert.

**Comment by q2apro** [comment]
I am running the default Etherpad docker. I do not know how to write a plugin and add it into the docker.

**Comment by SamTV12345** [comment]
> I am running the default Etherpad docker. I do not know how to write a plugin and add it into the docker.

You can find out more how to create a plugin here: https://github.com/ether/etherpad-lite/wiki/Creating-a-plugin and the plugin can then be added when building the image
