### ISSUE TITLE
Change language strings (DE)

### ISSUE THREAD

**Issue by q2apro** [ether/etherpad-lite#6094]
Regarding file: https://github.com/ether/etherpad-lite/blob/develop/src/locales/de.json

In German the correct word for a chat is not `Unterhaltung` but `Chat`. 

To be changed:

```
	"pad.settings.stickychat": "Chat immer anzeigen",
	"pad.settings.chatandusers": "Chat und Benutzer anzeigen",
	"pad.chat": "Chat",
```

**Comment by SamTV12345** [comment]
True. Unterhaltung sounds a bit dated. Chat is the better term.

**Comment by SamTV12345** [comment]
Added in translatewiki
