### ISSUE TITLE
Error building personalized container

### ISSUE THREAD

**Issue by ckmoga** [ether/etherpad-lite#6098]
**Describe the bug**
I am encountering an error when trying to build a personalized container. I am using the dockerfile downloaded from this repository.
I get the following error:

```
#13 [ 9/12] RUN { [ -z "" ] ||       npm install --no-save --legacy-peer-deps ; } &&     src/bin/installDeps.sh &&     rm -rf ~/.npm
#13 0.329 /bin/sh: src/bin/installDeps.sh: not found
#13 ERROR: process "/bin/sh -c { [ -z \"${ETHERPAD_PLUGINS}\" ] ||       npm install --no-save --legacy-peer-deps ${ETHERPAD_PLUGINS}; } &&     src/bin/installDeps.sh &&     rm -rf ~/.npm" did not complete successfully: exit code: 127
------
 > [ 9/12] RUN { [ -z "" ] ||       npm install --no-save --legacy-peer-deps ; } &&     src/bin/installDeps.sh &&     rm -rf ~/.npm:
0.329 /bin/sh: src/bin/installDeps.sh: not found
------
Dockerfile:102
--------------------
 101 |     # rules.
 102 | >>> RUN { [ -z "${ETHERPAD_PLUGINS}" ] || \
 103 | >>>       npm install --no-save --legacy-peer-deps ${ETHERPAD_PLUGINS}; } && \
 104 | >>>     src/bin/installDeps.sh && \
 105 | >>>     rm -rf ~/.npm
 106 |
--------------------
ERROR: failed to solve: process "/bin/sh -c { [ -z \"${ETHERPAD_PLUGINS}\" ] ||       npm install --no-save --legacy-peer-deps ${ETHERPAD_PLUGINS}; } &&     src/bin/installDeps.sh &&     rm -rf ~/.npm" did not complete successfully: exit code: 127
```

**To Reproduce**
1. docker pull etherpad/etherpad
2. docker build --tag myetherpad/etherpad .

**Expected behavior**
A container is built successfully

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
node: v20.10.0
It also fails on ```RUN cd src && npm link```

**Comment by SamTV12345** [comment]
Thank you for creating an issue. I am happy to help you with your docker problem. 

I think I saw the reason why you are facing these errors . You need to do 
1. `git clone https://github.com/ether/etherpad-lite.git`
2. `docker build --tag myetherpad/etherpad .`

That way you download all source files. They are necessary for building etherpad successfully.

**Comment by ckmoga** [comment]
Thanks you very much. That was help
