### ISSUE TITLE
Unable to import files containing a `$` sign in their filename

### ISSUE THREAD

**Issue by ichdasich** [ether/etherpad-lite#6109]
**Describe the bug**
When a user tries to import a file in the form `name.foo$something.etherpad` (apparently default naming for etherpad exports from BigBlueButton), the import fails with a generic error message (`Upload failed, please try again.').

Checking etherpad's logs, i find the message:

```
WARN] ImportHandler - Not allowing unknown file type to be imported: .foo
```

Please note: Depending on what is being matched and what is being (ultimately) parsed, this might be a bypass of the file"type" restrictions in etherpad's import function, i.e., `name.etherpad$something.else` might lead to a `.else` file being imported as a `.etherpad` file. This should receive triage re: security implications.

**To Reproduce**
1. Create etherpad export of existing pad named `test.etherpad`
2. Rename the file to `testfile.test$some_test.etherpad`
3. Try to import the file into a newly created pad

**Expected behavior**
- A more descriptive error message for files denied due to a non-matching file-type
- Escaping of special characters in file-names
- Correct matching of file-suffix

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version: 1.9.6 (b6f1898)
 - OS: Debian 12
 - Node.js version (`node --version`): v18.19.0
 - npm version (`npm --version`): 9.2.0
 - Is the server free of plugins: yes

**Comment by SamTV12345** [comment]
Thanks for the issue. This was actually a big issue and also caused files being imported incorrectly if allow unknown file extension was turned on by accident. Big thanks and it is fixed now on develop.

**Comment by ichdasich** [comment]
As a feedback note: Pushed develop to prod due to this bug; Users reported it works as intended.
