### ISSUE TITLE
Bug: Accept-Language zh-Hant-TW/zh-TW got fallback'd to zh-hans instead of zh-hant

### ISSUE THREAD

**Issue by winstonsung** [ether/etherpad-lite#6129]
Caused by:
* #3882

**Describe the bug**

With Accept-Language `zh-Hant-TW` / `zh-TW`, the UI language should be zh-hant.

However, we got the fallback'd UI language `zh-hans` instead of `zh-hant`.

**To Reproduce**

* Set browser language to "Traditional Chinese" / "Traditional Chinese (Taiwan)"
* Go to https://etherpad.wikimedia.org/p/mwstake-2024-02
* Check the detected UI language in "Settings" > "Language"
* See error: Unexpected language "Simplified Chinese" (中文（简体）)

**Expected behavior**

* Check the detected UI language in "Settings" > "Language"
* Expected language: "Traditional Chinese" (中文（繁體）)

**Screenshots**

Unexpected language:

![Unexpected language "Simplified Chinese" (中文（简体）)](https://github.com/ether/etherpad-lite/assets/52590365/e1e96035-948f-4130-9556-89f7c2f32f2e)

Expected language:

![Expected language "Traditional Chinese" (中文（繁體）)](https://github.com/ether/etherpad-lite/assets/52590365/57ee8234-756c-44b6-9fbf-901398f49dd0)

**Desktop:**
 - OS: Microsoft Windows 10
 - Browser:
   - Google Chrome 121.0 (x64)
   - Mozilla Firefox 122.0 (x64)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy
 - OS: Android 13
 - Browser:
   - Google Chrome 121.0 (Android 13)
   - Mozilla Firefox 122.0 (Android 13)

**Comment by SamTV12345** [comment]
Thanks for the issue. I first need to check where this language descision making is done/performed.

**Comment by winstonsung** [comment]
My suspicion:
https://github.com/ether/etherpad-lite/commit/a471dbeebfb9a1cd6da8b671890d2fbf488cd084

**Comment by winstonsung** [comment]
I created a pull request, any suggestions would be appreciated.

**Comment by SamTV12345** [comment]
Thanks. I'll take a look at it tomorrow. I'm too tired today.
