### ISSUE TITLE
Cannot find module 'busboy'

### ISSUE THREAD

**Issue by c0ldst0rage** [ether/etherpad-lite#6182]
- Install the WinLite version 1.9.7 as per standard instructions.
- Change the settings.json to permit installation of plug-ins via the admin page.
- Login to the admin page.
- Install the plug-in "image_upload"  version 1.0.105.

During installation, there are 3 errors but all of a similar nature:
**[ERROR] settings - Failed to load hook function "D:\Downloads\etherpad-lite-win\plugin_packages\ep_image_upload\index:eejsBlock_body" for plugin "ep_image_upload" part "ep_image_upload" hook set "hooks" hook "eejsBlock_body": Error: Cannot find module 'busboy'`

**Comment by SamTV12345** [comment]
Thanks for the issue. I'll take a look at this. WinLite is simply etherpad-lite running on Windows I guess 😄 . @Gared Could you take a look at that. I'm not really sure if the dependencies are installed correctly with the live-plugin-manager

**Comment by SamTV12345** [comment]
I guess we can finally close this one :). It finally works again with v2
