### ISSUE TITLE
New install : DirtyDB is used instead of Mysql database

### ISSUE THREAD

**Issue by FredMa01** [ether/etherpad-lite#6189]
Hi,
I am changing my etherpad-lite server.
I import and export the database on the new server and complete the settings.json file with the parameters of my database.
No error but I stay in Dirty mode even though it is disabled
I don't instant why....
I am on Debian 12
node -v : v18.19.0
npm -v : 9.2.0
Etherpad version is 1.9.7 (6814aa9)

`
[INFO] settings - settings loaded from: /home/etherpad/settings.json
[INFO] settings - No credentials file found in /home/etherpad/credentials.json. Ignoring.
[INFO] settings - Using skin "colibris" in dir: /home/etherpad/src/static/skins/colibris
[WARN] settings - DirtyDB is used. This is not recommended for production. File location: /home/etherpad/var/dirty.db
[INFO] settings - Random string used for versioning assets: 6d6a2899
[INFO] server - Starting Etherpad...
[INFO] plugins - check installed plugins for migration
[INFO] plugins - Loading plugin ep_etherpad-lite...
[INFO] plugins - Loaded 1 plugins
[INFO] APIHandler - Api key file read from: "/home/etherpad/APIKEY.txt"
[INFO] server - Installed plugins:
[INFO] settings - Report bugs at https://github.com/ether/etherpad-lite/issues
[INFO] settings - Your Etherpad version is 1.9.7 (6814aa9)
[INFO] plugins - npm --version: 6.14.18
[INFO] http - HTTP server listening for connections
```
My settings.json
[](  /*
   * The type of the database.
   *
   * You can choose between many DB drivers, for example: dirty, postgres,
   * sqlite, mysql.
   *
   * You shouldn't use "dirty" for for anything else than testing or
   * development.
   *
   *
   * Database specific settings are dependent on dbType, and go in dbSettings.
   * Remember that since Etherpad 1.6.0 you can also store this information in
   * credentials.json.
   *
   * For a complete list of the supported drivers, please refer to:
   * https://www.npmjs.com/package/ueberdb2
   */

  /*
   * An Example of MySQL Configuration (commented out).
   *
   * See: https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL
   */

  /*
  "dbType" : "mysql",
  "dbSettings" : {
    "user":     "etherpad",
    "host":     "localhost",
    "port":     3306,
    "password": "mypassword",
    "database": "etherpad",
    "charset":  "utf8mb4"
  },
  */
)

**Comment by SamTV12345** [comment]
> Hi, I am changing my etherpad-lite server. I import and export the database on the new server and complete the settings.json file with the parameters of my database. No error but I stay in Dirty mode even though it is disabled I don't instant why.... I am on Debian 12 node -v : v18.19.0 npm -v : 9.2.0 Etherpad version is 1.9.7 ([6814aa9](https://github.com/ether/etherpad-lite/commit/6814aa9a3cbc1c2a65f0eda75ecfad286ef8c7a2))
> 
> ` [INFO] settings - settings loaded from: /home/etherpad/settings.json [INFO] settings - No credentials file found in /home/etherpad/credentials.json. Ignoring. [INFO] settings - Using skin "colibris" in dir: /home/etherpad/src/static/skins/colibris [WARN] settings - DirtyDB is used. This is not recommended for production. File location: /home/etherpad/var/dirty.db [INFO] settings - Random string used for versioning assets: 6d6a2899 [INFO] server - Starting Etherpad... [INFO] plugins - check installed plugins for migration [INFO] plugins - Loading plugin ep_etherpad-lite... [INFO] plugins - Loaded 1 plugins [INFO] APIHandler - Api key file read from: "/home/etherpad/APIKEY.txt" [INFO] server - Installed plugins: [INFO] settings - Report bugs at https://github.com/ether/etherpad-lite/issues [INFO] settings - Your Etherpad version is 1.9.7 ([6814aa9](https://github.com/ether/etherpad-lite/commit/6814aa9a3cbc1c2a65f0eda75ecfad286ef8c7a2)) [INFO] plugins - npm --version: 6.14.18 [INFO] http - HTTP server listening for connections
> 
> ```
> My settings.json
> [](  /*
>    * The type of the database.
>    *
>    * You can choose between many DB drivers, for example: dirty, postgres,
>    * sqlite, mysql.
>    *
>    * You shouldn't use "dirty" for for anything else than testing or
>    * development.
>    *
>    *
>    * Database specific settings are dependent on dbType, and go in dbSettings.
>    * Remember that since Etherpad 1.6.0 you can also store this information in
>    * credentials.json.
>    *
>    * For a complete list of the supported drivers, please refer to:
>    * https://www.npmjs.com/package/ueberdb2
>    */
> 
>   /*
>    * An Example of MySQL Configuration (commented out).
>    *
>    * See: https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL
>    */
> 
>   /*
>   "dbType" : "mysql",
>   "dbSettings" : {
>     "user":     "etherpad",
>     "host":     "localhost",
>     "port":     3306,
>     "password": "mypassword",
>     "database": "etherpad",
>     "charset":  "utf8mb4"
>   },
>   */
> )
> ```

I think your settings.json is formatted incorrectly. Try this:

```json
 {/*
   * The type of the database.
   *
   * You can choose between many DB drivers, for example: dirty, postgres,
   * sqlite, mysql.
   *
   * You shouldn't use "dirty" for for anything else than testing or
   * development.
   *
   *
   * Database specific settings are dependent on dbType, and go in dbSettings.
   * Remember that since Etherpad 1.6.0 you can also store this information in
   * credentials.json.
   *
   * For a complete list of the supported drivers, please refer to:
   * https://www.npmjs.com/package/ueberdb2
   */

  /*
   * An Example of MySQL Configuration (commented out).
   *
   * See: https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL
   */

  /*
  "dbType" : "mysql",
  "dbSettings" : {
    "user":     "etherpad",
    "host":     "localhost",
    "port":     3306,
    "password": "mypassword",
    "database": "etherpad",
    "charset":  "utf8mb4"
  }
}

```

**Comment by SamTV12345** [comment]
> No, the problem does not come from there.
> 
> `cp settings.json.template settings.json`
> 
> `diff settings.json settings.json.template`
> 
> ```
> 213c213
> <     "user":     "etherpad",
> ---
> >     "user":     "etherpaduser",
> 216,217c216,217
> <     "password": "mypassword",
> <     "database": "etherpad",
> ---
> >     "password": "PASSWORD",
> >     "database": "etherpad_lite_db",
> ```

Can you try the develop container? Maybe that fixes the issue.

**Comment by kekePower** [comment]
>   /*
>   "dbType" : "mysql",
>   "dbSettings" : {
>     "user":     "etherpad",
>     "host":     "localhost",
>     "port":     3306,
>     "password": "mypassword",
>     "database": "etherpad",
>     "charset":  "utf8mb4"
>   },
>   */

The problem is that the MySQL section is commented out with /* and */.
Remove those and you should be able to connect to your database.

Also, above the MySQL section you'll find a DirtyDB section that you have to remove or comment using the beforementioned /* and */.
