### ISSUE TITLE
docker build fails with pnpm-lock.yaml missing

### ISSUE THREAD

**Issue by ToeiRei** [ether/etherpad-lite#6238]
**Describe the bug**
I am trying to build the most recent version of etherpad-lite container using this repo and it errors out

```
 ---> 0afebd3f198e
Step 35/48 : COPY --chown=etherpad:etherpad ./src/package.json .npmrc ./src/pnpm-lock.yaml ./src/
COPY failed: file not found in build context or excluded by .dockerignore: stat src/pnpm-lock.yaml: file does not exist
```

file referenced in dockerfile: https://github.com/ether/etherpad-lite/blob/d7869f50140db698186302c774e80fe1ba30097b/Dockerfile#L104C1-L105C1

**To Reproduce**
1. clone the repo
2. cd etherpad-lite && git pull (if not up to date) && cd ..
3. docker build --build-arg ETHERPAD_PLUGINS="ep_adminpads3 ep_markdown ep_disable_chat ep_announce" --tag my/etherpad etherpad-lite-build-with-plugins

**Expected behavior**
I would expect the container to build as it did back then.

**Comment by JannikStreek** [comment]
Yes, same problem. the lock file in src was apparently removed as its not needed anymore. I will create a PR for that. As a workaround, try to remove `./src/pnpm-lock.yaml` from the line in the docker file that you posted.

**Comment by SamTV12345** [comment]
> Yes, same problem. the lock file in src was apparently removed as its not needed anymore. I will create a PR for that. As a workaround, try to remove `./src/pnpm-lock.yaml` from the line in the docker file that you posted.

Thanks for helping me out. I always created the production build which most users want to have. That would be `docker build --target=production .` @ToeiRei
