### ISSUE TITLE
Pinning support when installing plugins

### ISSUE THREAD

**Issue by antoineauger** [ether/etherpad-lite#6253]
**Is your feature request related to a problem? Please describe.**
We are building our own Docker image to also bundle some etherpad plugins.
After upgrading to `etherpad-lite` `v2.0.0`, we cannot pin plugin versions using the [recommended `install-plugins` command](https://github.com/ether/etherpad-lite?tab=readme-ov-file#plugin-installation):

```Dockerfile
FROM etherpad/etherpad:2.0.1
...
# this works but we would like to pin a specific version
RUN pnpm run install-plugins ep_headings2  
```

**Describe the solution you'd like**
We would like to be able to specify a version/pin a plugin:

```Dockerfile
FROM etherpad/etherpad:2.0.1
...
RUN pnpm run install-plugins ep_headings2@0.2.61
```

**Describe alternatives you've considered**
We can directly install the plugin with `pnpm install` but we would then miss any features/checks from the `install-plugins` command:
```Dockerfile
FROM etherpad/etherpad:2.0.1
...
RUN pnpm install -w ep_headings2@0.2.61
```

**Additional context**
Before `etherpad-lite` `v2.0.0`, we were following [these instructions](https://github.com/ether/etherpad-lite/wiki/Available-Plugins#manually-installing-plugins) and it worked quite well:

```Dockerfile
FROM etherpad/etherpad:1.9.6
...
RUN npm install --no-save --legacy-peer-deps ep_headings2@0.2.61
```

**Plugin?**
N/A

/cc @fgreinacher

**Comment by antoineauger** [comment]
Thank you for implementing it so quickly @SamTV12345 🙏🏻 🚀

**Comment by SamTV12345** [comment]
You're welcome :)
