### ISSUE TITLE
How to remove plugins ?

### ISSUE THREAD

**Issue by meaz** [ether/etherpad-lite#6272]
I know that you now need to install plugins with `pnpm run install-plugins ep_plugin-name` with v2.0.1.

How do you remove a plugin now from command line?

**Comment by SamTV12345** [comment]
Good point. We don't have any possibility to remove from command line. You can go to the admin portal and remove it there for the time being.

**Comment by meaz** [comment]
thanks for the quick answer. It would be nice to have it available from cli though ;)

**Comment by SamTV12345** [comment]
Absolutely I add that tomorrow. Should be quite easy :)

**Comment by ger82** [comment]
Hi, do you implemented it?
