### ISSUE TITLE
Support proxy server in plugin installation script

### ISSUE THREAD

**Issue by fgreinacher** [ether/etherpad-lite#6275]
**Is your feature request related to a problem? Please describe.**

We are using a proxy server for all outgoing network requests. We configure our systems with the `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` variables to specify for which requests the proxy server   is needed.

The plugin install script uses `node-fetch` internally and does therefore not support this out of the box and therefore does not work for us:

```
/opt/etherpad-lite/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501
			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
			       ^
FetchError: Failed to get package 'ep_headings2' request to https://registry.npmjs.org/ep_headings2 failed, reason: 
    at ClientRequest.<anonymous> (/opt/etherpad-lite/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:519:28)
    at ClientRequest.emit (node:domain:488:12)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:[82](https://code.siemens.com/core/tools/-/jobs/173129812#L82):21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
```

**Describe the solution you'd like**

The script should consider the system proxy configuration.

**Describe alternatives you've considered**

Using `pnpm install` directly works, but we'd like to stick with the recommended approach.

**Additional context**

n/a

**Plugin?**

No, this needs to be implemented in the script.

**Comment by fgreinacher** [comment]
No, right now we've revert to v1. If you install the plugins via `pnpm` it will try to migrate them and run into the same issue.

There is already an upstream issue at https://github.com/davideicardi/live-plugin-manager/issues/48 that I will look into.

**Comment by Vringe** [comment]
@SamTV12345 This works at build-time, but unfortunately not at run-time.

**Comment by fgreinacher** [comment]
I have submitted https://github.com/davideicardi/live-plugin-manager/pull/85

**Comment by SamTV12345** [comment]
@fgreinacher Feel free to ping me once this is merged. I'll then create a new release for our version of live-plugin-manager

**Comment by fgreinacher** [comment]
@SamTV12345 This is fixed in [`live-plugin-manager@0.19.0`](https://github.com/davideicardi/live-plugin-manager/releases/tag/v0.19.0).

**Comment by fgreinacher** [comment]
Thanks @SamTV12345, this works well with the `develop` version! Eagerly waiting for the next release :)

**Comment by Vringe** [comment]
Works like a charm with `2.0.2`. Thank you guys.
