### ISSUE TITLE
No admin templates  - Etherpad 2.0.1

### ISSUE THREAD

**Issue by FredMa01** [ether/etherpad-lite#6288]
After a new installation today : 
git clone --branch master https://github.com/ether/etherpad-lite.git etherpad

I have this error :
Error: ENOENT: no such file or directory, stat '/home/etherpad/src/templates/admin/index.html

Admin templates disappeared of /scr/templates.
Etherpad version is 2.0.1 (4631e14)
pnpm --version: 8.15.5
Debian 12

**Comment by SamTV12345** [comment]
Thanks for the issue. Is this a bare metal installation? It could be that the files are not created. So for that you just do pnpm i, go to the admin folder in the root directory and do pnpm run build . That should suffice for the templates to be registered.

**Comment by SamTV12345** [comment]
Oh yes the old npm modules will be removed. Pnpm is the fastest package manager currently available.

**Comment by meaz** [comment]
Sorry for posting in a closed issue but as I have the exact same issue that I solved as suggested with  `pnpm run build` I thought that asking my question here would make sense: is that the default behavior that with an new install or an update from older version, users have to run `pnpm run build` ?

**Comment by SamTV12345** [comment]
With the move to React an extra build step is required. I could add that to the installDeps script or is that already present? I could definitely add that to the documentation.

**Comment by meaz** [comment]
adding that to the documentation would be nice. I don't use the installDeps script as I use ansible role to deploy, should I ?

**Comment by SamTV12345** [comment]
It normally covers all build steps but seems like this is not included in it. I'll fix that for the next release.
