### ISSUE TITLE
Update from 1.9.7. to 2.0.1 fails [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/pnpm']

### ISSUE THREAD

**Issue by saschafoerster** [ether/etherpad-lite#6305]
Usually I could update with git checkout and then restarting with service etherpad restart. 
But the upgrade from 1.9.7. to 2.0.1 fails because of pnpm, as it doesn't have rights to write into a folder. 
Etherpad-Lite is under /home/etherpad-lite and the user etherpad has his home-folder under /home/etherpad 
I am using Debian 11. 

**To Reproduce**

1. git checkout v2.0.1
2. service etherpad start 

**Expected behavior**
Etherpad should start. 

**Server (please complete the following information):**
 - Etherpad version: 2.0.1
 - OS: Debian 11node v
 - Node.js version (`node --version`): v20.12.0
 - npm version (`npm --version`): 8.15.1
 - Is the server free of plugins: yes

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]: Safari
 - Version [e.g. 22]: 17.4.1

**Additional context**
Same happens when I go this way: 
1. su etherpad 
2. ./bin/run.sh 

I can start Etherpad successfully, when I start it in root, which I don't want to. 
Just a guess, maybe it is a permission issue with PNPM? https://github.com/pnpm/pnpm/issues/4979

**Comment by SamTV12345** [comment]
pnpm writes into a global store for the current user. So you need to make sure that you can write to the location listed below https://stackoverflow.com/questions/55403775/how-to-get-pnpm-store-directory . Other than that you need to install pnpm. This requires a one time installation of pnpm in the global directory. So if you do sudo npm install -g pnpm that should fix the issue.
