### ISSUE TITLE
API Docs not updated for new OAuth2.0 support

### ISSUE THREAD

**Issue by cboylan** [ether/etherpad-lite#6320]
**Describe the bug**
The 2.0.2 changelog notes that Oauth2.0 support is added. However, it appears that APIKEY.txt usage was also removed (which was not noted), and API documentation has not been updated on how to configure and auth using OAuth2.0/JWT instead.

**To Reproduce**
1. Deploy 2.0.2
2. Attempt to auth using APIKEY.txt
3. Find the file is no longer generated and you cannot auth using this method.

**Expected behavior**
Given the changelog, documentation content, and bug fix point release version bump I would expect the old APIKEY.txt auth method to still be valid and function. It seems that this removal may have been intentional and the changelog is simply missing details. In that case I think it would be good to update the documentation so that we can more easily configure and use the new authentication system instead.

**Server (please complete the following information):**
 - Etherpad version: 2.0.2
 - OS: Debian Bookworm
 - Node.js version (`node --version`): v20.12.1
 - npm version (`npm --version`): 10.5.0
 - Is the server free of plugins: No we install ep_headings. I'm fairly certain this is unrelated to the problem.

**Additional context**
I think some of the bin/ tools for admin tasks like pad deletion still expect an APIKEY.txt file as well and probably need updating too.

**Comment by tommyhlw** [comment]
the missing APIKEY.txt makes [ownpad](https://github.com/otetard/ownpad) for nextcloud useless

**Comment by SamTV12345** [comment]
Can you create an issue over on ownpad? I added everything required so that ownpad works again. I'll have a look at owncloud.

**Comment by tommyhlw** [comment]
just did https://github.com/otetard/ownpad/issues/141

**Comment by tommyhlw** [comment]
saw your completed PR just after I posted this, sorry

**Comment by SamTV12345** [comment]
> saw your completed PR just after I posted this, sorry

No worries :)

**Comment by cboylan** [comment]
Couple of extra notes from what I've found after this update. `client_credentials` is not a valid grant type in v2.0.2 seems we need https://github.com/ether/etherpad-lite/pull/6325/files#diff-f4d0fff1e0ccd5758458dc86b4e0d09c0e006a290032ee4dc2cc931d0cb9b37a from the PR that addresses the documentation issue?

Additionally these doc updates don't actually document the request flow necessary for making this work. It seems like it would be something like:

```
curl --data client_id=client_credentials --data client_secret=client_credentials --data grant_type=client_credentials http://localhost:9001/oidc/token
curl --header "Authorization: $BEARER_TOKEN_FROM_PREVIOUS_RESPONSE" http://localhost:9001/api/1/listPads
```

If that is the case can we get this extra information added to the documentation? The most important piece of info seems to be the token issuance path (`/oidc/token`) I think then its normal client_credentials workflow from there.
