### ISSUE TITLE
stats doesn't report totalUsers on version 2.0.2

### ISSUE THREAD

**Issue by disturbio** [ether/etherpad-lite#6341]
**Describe the bug**

`/stats` endpoint doesn't seem to be report `totalUsers` . 

**To Reproduce**

1. curl  http://127.0.0.1:9001/stats | jq

**Expected behavior**

This data should be present according to `doc/stats.md`

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version: 2.0.2
 - OS: Debian 11.9, 12.5
 - Node.js version: v18.20.2
 - npm version (`npm --version`): pnpm version 9.0.2
 - Is the server free of plugins: yes

**Desktop (please complete the following information):**
not relevant

**Smartphone (please complete the following information):**
not relevant

**Additional context**

To see if this could be a local problem, used the etherpad scanner to locate a public instance which had `/stats/` exposed. found one, no `totalUsers` there either. debug level for logging doesn't provide much information.

```
2024-04-18T18:47:44.495922+00:00 eplite-test etherpad-lite[2013049]: #033[36m[2024-04-18T18:47:44.495] [DEBUG] http - #033[39m200, GET /stats
```

also, thanks for all your work :)

**Comment by SamTV12345** [comment]
It's fixed. Somehow during migration the totalUsers were read from an undefined variable thus it wasn't displayed anymore. You're welcome and thanks for taking the time to create an issue :)
