### ISSUE TITLE
Script error on Ecosia iOS

### ISSUE THREAD

**Issue by nitn3lav** [ether/etherpad-lite#6348]
**Describe the bug**

**To Reproduce**
1. Download [Ecosia iOS](https://apps.apple.com/app/id670881887)
2. Open a pad
3. Refresh page

**Expected behavior**
Etherpad continues to work

**Screenshots**

| after first load | after reloading the page |
|--------|--------|
| ![IMG_9602](https://github.com/ether/etherpad-lite/assets/77448526/20ee89a6-642c-4ea1-b8c6-1065e2b22a49) | ![IMG_9603](https://github.com/ether/etherpad-lite/assets/77448526/a1f7bf8b-d14b-41c7-bd93-94e89ab13d76) | 

**Server (please complete the following information):**
 - Etherpad version:
 - OS: [e.g., Ubuntu 20.04]
 - Node.js version (`node --version`):
 - npm version (`npm --version`):
 - Is the server free of plugins: Not sure

**Smartphone:**
 - Device: iPhone 14 Pro
 - OS: iOS 17.4.1
 - Browser: Ecosia
 - Version: 9.4.0

**Additional context**
- The only way I found to "fix" the issue is by deleting all data & caches
- Ecosia seems to be a fork of Firefox. However, the error des not occur in the latest version of Firefox.

**Comment by SamTV12345** [comment]
This could be more of a compatibility issue. It seems like Ecosia has a bug in its browser. Every other browser works perfectly fine. I'll leave it open for now.

**Comment by nitn3lav** [comment]
I agree. I also reported this to Ecosia so that hopefully they will fix this. Since I just stumbled across this I figured it might make sense to create an issue. Also, this likely only affects a very small number of users (I don’t even actively use the Ecosia app myself)

**Comment by heldersepu** [comment]
@SamTV12345 This issue can be closed as `unsupported browser` ...
We should probably add a "tested browsers" section in the readme. 
No project tests against every obscure browser out in the wild

**Comment by SamTV12345** [comment]
> @SamTV12345 This issue can be closed as `unsupported browser` ... We should probably add a "tested browsers" section in the readme. No project tests against every obscure browser out in the wild

I also tried to contact their support without any luck.
