### ISSUE TITLE
Remember guests' author names and colours between sessions

### ISSUE THREAD

**Issue by jimj316** [ether/etherpad-lite#6372]
* * *

name: Feature request
about: Suggest an idea for this project
title: ''
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
I have a small Etherpad-Lite instance set up for planning projects and events with friends. I don't want to force them to have accounts (as this would raise a big barrier to entry and would make it hard to collaborate with large groups). I like how I can see authors' names, but these names are forgotten (they become "false") whenever they close and re-open the tab. Users often don't notice that this has happened, so quickly everyone's names are "false" which undermines the utility of this feature.

**Describe the solution you'd like**
I am aware of the fact that user settings (e.g. setting the theme) are stored in a cookie, so I would suggest storing the author name and colour in there as well.

**Describe alternatives you've considered**
I'm not sure there really are any alternative solutions beyond ignoring the problem.

**Additional context**
None

**Plugin?**
I've tried looking for a plugin to solve this issue but I couldn't find one, which I was a little surprised by. I also don't really know how Etherpad plugins work or whether they can store data in the session cookie.

**Comment by SamTV12345** [comment]
Hmm. Can you ellaborate how they become false. If I go to https://yopad.eu/p/test, enter any username and send a message via chat and reload the tab I am still the said username or am I missing something. This sounds really like an improvement if I can replicate the behavior

**Comment by jimj316** [comment]
That's weird, I'm not experiencing the issue on that test server, so I suppose it's either a bug, functionality in a later version of Etherpad, or a problem with a plugin.

The steps I'm doing to replicate the issue on my server is:

- Open the pad
- Set the username & colour on the top right
- Make no changes to anything else
- Close the tab
- Re-open the tab, the username is now "null".

My server is on version 1.9.4, although I see now that the newest version is 1.9.7. I'll see if I can update it tonight to see if that helps. I can also send you (or anyone else) a link to my instance if it helps with testing.

**Comment by dcht00** [comment]
@jimj316 I used to have this problem, was solved by #5401 ? Had to change a value in settings.json

**Comment by jimj316** [comment]
@dcht00 Thanks for the help; I've tried the workaround suggested (change padOptions/userName and padOptions/userColour from false to null), and it seems to have resolved the problem. I'm certain I've not edited these options manually, so the 'false' value I think must have been a holdover in the config file from before that change was made.
