### ISSUE TITLE
Incorrect documentation on using MySQL with Unix socket

### ISSUE THREAD

**Issue by lpoujol** [ether/etherpad-lite#6378]
Hi

First of all, thanks for this great project/software :heart: 

**Describe the bug**

Following the [documentation on how to use Etherpad with MySQL](https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL), I've configured it to connect to MySQL using the Unix Socket.
This setting is ignored, and Etherpad seems to fall-back to the default MySQL settings (localhost:3306)

**To Reproduce**

0. Have MySQL to not listen on tcp:localhost:3306

1.  Set the following configuration in the settings.js

```json
"dbType" : "mysql",
"dbSettings" : {
  "user":     "etherpad",
  "port":     "/run/mysqld/mysqld.sock",
  "password": "MySuperSecretPassword",
  "database": "etherpad", 
  "charset":  "utf8mb4" 
},
```

2. Start Etherpad

3. Wait for it to fail

```
May 13 10:00:36 hostname pnpm[2996449]: > ep_etherpad-lite@2.0.3 prod /home/etherpad/etherpad-lite/src
May 13 10:00:36 hostname pnpm[2996449]: > node --import tsx node/server.ts
May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.636] [INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /home/etherpad/etherpad-lite
May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.653] [INFO] settings - settings loaded from: /home/etherpad/etherpad-lite/settings.json
May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.655] [INFO] settings - Rooting is undefined
May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.655] [INFO] settings - No credentials file found in /home/etherpad/etherpad-lite/credentials.json. Ignoring.
May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.657] [INFO] settings - Using skin "no-skin" in dir: /home/etherpad/etherpad-lite/src/static/skins/no-skin
May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.657] [INFO] settings - Session key loaded from: /home/etherpad/etherpad-lite/SESSIONKEY.txt
May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.657] [WARN] settings - The sessionKey setting and /home/etherpad/etherpad-lite/SESSIONKEY.txt file are deprecated; use automatic key rotation inst>
May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.658] [INFO] settings - Random string used for versioning assets: 03c35ee2
May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.690] [INFO] server - Starting Etherpad...
May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.782] [INFO] plugins - pnpm --version: 9.0.5
May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.784] [ERROR] ueberDB - Fatal MySQL error: Error: connect ECONNREFUSED ::1:3306
May 13 10:00:38 hostname pnpm[2996467]:     at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
May 13 10:00:38 hostname pnpm[2996467]:     at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
May 13 10:00:38 hostname pnpm[2996467]:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.784] [ERROR] server - Error occurred while starting Etherpad
May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.785] [ERROR] server - Metrics at time of fatal error:
May 13 10:00:38 hostname pnpm[2996467]: {
May 13 10:00:38 hostname pnpm[2996467]:   "httpStartTime": 0,
May 13 10:00:38 hostname pnpm[2996467]:   "memoryUsage": 238346240,
May 13 10:00:38 hostname pnpm[2996467]:   "memoryUsageHeap": 79826184
May 13 10:00:38 hostname pnpm[2996467]: }
May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.785] [ERROR] server - Error: connect ECONNREFUSED ::1:3306
May 13 10:00:38 hostname pnpm[2996467]:     at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
May 13 10:00:38 hostname pnpm[2996467]:     at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
May 13 10:00:38 hostname pnpm[2996467]:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.786] [INFO] server - Exiting...
May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.786] [INFO] server - Waiting for Node.js to exit...
```

**Expected behavior**

Etherpad uses the Unix socket to connect to MySQL

**Solution** 

Tracking down the dependency of the dependency, I've stumbled on [node-mysql2 docs](https://sidorares.github.io/node-mysql2/docs/) and more precisely the [CreatePool options](https://sidorares.github.io/node-mysql2/docs/examples/connections/create-pool#pooloptions) used by [ueberDB](https://github.com/ether/ueberDB/blob/main/databases/mysql_db.ts#L66)

This specify the configuration option `socketPath` for the path of the Unix Socket to connect to : 

```
  /**
   * The path to a unix domain socket to connect to. When used host and port are ignored
   */
  socketPath?: string;
```

Meaning that the correct configuration is :

```json
"dbType" : "mysql",
"dbSettings" : {
  "user":           "etherpad",
  "socketPath":     "/run/mysqld/mysqld.sock", 
  "password":       "MySuperSecretPassword",
  "database":       "etherpad", 
  "charset":        "utf8mb4" 
},
```

And with this, it works :)

**Server (please complete the following information):**
 - Etherpad version: 2.0.3 (8fa708a)
 - OS: Debian 12 (Bookworm)
 - Node.js version (`node --version`): v18.20.2
 - npm version (`npm --version`): 10.5.0
 - Is the server free of plugins: 

Good day !

**Comment by SamTV12345** [comment]
> Hi
> 
> First of all, thanks for this great project/software ❤️
> 
> **Describe the bug**
> 
> Following the [documentation on how to use Etherpad with MySQL](https://github.com/ether/etherpad-lite/wiki/How-to-use-Etherpad-Lite-with-MySQL), I've configured it to connect to MySQL using the Unix Socket. This setting is ignored, and Etherpad seems to fall-back to the default MySQL settings (localhost:3306)
> 
> **To Reproduce**
> 
> 0. Have MySQL to not listen on tcp:localhost:3306
> 1. Set the following configuration in the settings.js
> 
> ```json
> "dbType" : "mysql",
> "dbSettings" : {
>   "user":     "etherpad",
>   "port":     "/run/mysqld/mysqld.sock",
>   "password": "MySuperSecretPassword",
>   "database": "etherpad", 
>   "charset":  "utf8mb4" 
> },
> ```
> 
> 2. Start Etherpad
> 3. Wait for it to fail
> 
> ```
> May 13 10:00:36 hostname pnpm[2996449]: > ep_etherpad-lite@2.0.3 prod /home/etherpad/etherpad-lite/src
> May 13 10:00:36 hostname pnpm[2996449]: > node --import tsx node/server.ts
> May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.636] [INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /home/etherpad/etherpad-lite
> May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.653] [INFO] settings - settings loaded from: /home/etherpad/etherpad-lite/settings.json
> May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.655] [INFO] settings - Rooting is undefined
> May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.655] [INFO] settings - No credentials file found in /home/etherpad/etherpad-lite/credentials.json. Ignoring.
> May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.657] [INFO] settings - Using skin "no-skin" in dir: /home/etherpad/etherpad-lite/src/static/skins/no-skin
> May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.657] [INFO] settings - Session key loaded from: /home/etherpad/etherpad-lite/SESSIONKEY.txt
> May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.657] [WARN] settings - The sessionKey setting and /home/etherpad/etherpad-lite/SESSIONKEY.txt file are deprecated; use automatic key rotation inst>
> May 13 10:00:37 hostname pnpm[2996467]: [2024-05-13T10:00:37.658] [INFO] settings - Random string used for versioning assets: 03c35ee2
> May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.690] [INFO] server - Starting Etherpad...
> May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.782] [INFO] plugins - pnpm --version: 9.0.5
> May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.784] [ERROR] ueberDB - Fatal MySQL error: Error: connect ECONNREFUSED ::1:3306
> May 13 10:00:38 hostname pnpm[2996467]:     at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
> May 13 10:00:38 hostname pnpm[2996467]:     at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
> May 13 10:00:38 hostname pnpm[2996467]:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
> May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.784] [ERROR] server - Error occurred while starting Etherpad
> May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.785] [ERROR] server - Metrics at time of fatal error:
> May 13 10:00:38 hostname pnpm[2996467]: {
> May 13 10:00:38 hostname pnpm[2996467]:   "httpStartTime": 0,
> May 13 10:00:38 hostname pnpm[2996467]:   "memoryUsage": 238346240,
> May 13 10:00:38 hostname pnpm[2996467]:   "memoryUsageHeap": 79826184
> May 13 10:00:38 hostname pnpm[2996467]: }
> May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.785] [ERROR] server - Error: connect ECONNREFUSED ::1:3306
> May 13 10:00:38 hostname pnpm[2996467]:     at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
> May 13 10:00:38 hostname pnpm[2996467]:     at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
> May 13 10:00:38 hostname pnpm[2996467]:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
> May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.786] [INFO] server - Exiting...
> May 13 10:00:38 hostname pnpm[2996467]: [2024-05-13T10:00:38.786] [INFO] server - Waiting for Node.js to exit...
> ```
> 
> **Expected behavior**
> 
> Etherpad uses the Unix socket to connect to MySQL
> 
> **Solution**
> 
> Tracking down the dependency of the dependency, I've stumbled on [node-mysql2 docs](https://sidorares.github.io/node-mysql2/docs/) and more precisely the [CreatePool options](https://sidorares.github.io/node-mysql2/docs/examples/connections/create-pool#pooloptions) used by [ueberDB](https://github.com/ether/ueberDB/blob/main/databases/mysql_db.ts#L66)
> 
> This specify the configuration option `socketPath` for the path of the Unix Socket to connect to :
> 
> ```
>   /**
>    * The path to a unix domain socket to connect to. When used host and port are ignored
>    */
>   socketPath?: string;
> ```
> 
> Meaning that the correct configuration is :
> 
> ```json
> "dbType" : "mysql",
> "dbSettings" : {
>   "user":           "etherpad",
>   "socketPath":     "/run/mysqld/mysqld.sock", 
>   "password":       "MySuperSecretPassword",
>   "database":       "etherpad", 
>   "charset":        "utf8mb4" 
> },
> ```
> 
> And with this, it works :)
> 
> **Server (please complete the following information):**
> 
> * Etherpad version: 2.0.3 ([8fa708a](https://github.com/ether/etherpad-lite/commit/8fa708a3747ce2c653173abbc1b30f7c10e64754))
> * OS: Debian 12 (Bookworm)
> * Node.js version (`node --version`): v18.20.2
> * npm version (`npm --version`): 10.5.0
> * Is the server free of plugins:
> 
> Good day !

Hi @lpoujol ,

thanks for the nice words :). I try my best to maintain Etherpad. Sorry for the delay in response. There's a lot going on besides my OSS work that is why I may be slow to respond. I took a look at the documentation. It was unfortunately an oversight by me. The old NodeJS mysql package is unmaintained and contained security vulnerabilities due to its age. I migrated to mysql2 package that is updated frequently and also has many more features. Thanks for pointing that out. I fixed that in the docs :)
