### ISSUE TITLE
importSqlFile and other tools don't build by default, docs not helpful

### ISSUE THREAD

**Issue by dronus** [ether/etherpad-lite#6379]
**Describe the bug**
importSqlFile.js and other tools in bin/ mentioned throughout the docs does not exist anymore. They need to be built from .ts files now as it seems, but there is no docs on this, and tsc fails on those files with a lot of errors.

**To Reproduce**
1. try to run `node bin/importSqlFile.js` as supposed by docs

**Expected behavior**
importSqlFile.js shoud run now.  If there are preparations needed, docs should mention those and guide through the process.

**Additional context**
There are a lot of .ts files in bin/ now. But running tsc on them errors out with a lot of problems in dependent packages.

**Comment by SamTV12345** [comment]
It should work if you just do `cd bin; pnpm i; pnpm run importSqlFile $MyFile`
