### ISSUE TITLE
Where can I find the Etherpad SVG logo?

### ISSUE THREAD

**Issue by gabriel-eladi** [ether/etherpad-lite#6383]
Hello!

I would like to add the Etherpad SVG logo to the collection of dashboard icons [https://github.com/walkxcode/dashboard-icons](https://github.com/walkxcode/dashboard-icons), since it currently only has the logo in PNG format.

Could you please share where I can find the project logo in SVG format (if it exists, that is)?

**Comment by SamTV12345** [comment]
There is this logo. You could cut out the text and just have the logo or use the complete logo with image and text https://github.com/ether/ether.github.com/blob/master/src/assets/img/brand.svg . Other than that cool project :)

**Comment by gabriel-eladi** [comment]
Thank you! Time to put my nonexistent Inkscape skills to the test!

**Comment by SamTV12345** [comment]
Awesome. Good luck (I am also no master in Inkscape :))
