### ISSUE TITLE
Pagination not working correctly on admin/pads

### ISSUE THREAD

**Issue by dvandemaele** [ether/etherpad-lite#6384]
**Describe the bug**
There are 12 pads per page. Pages 1, 2 and 3 show the same pads. (first 12 pads) Once you click to the 4th page, then the pads change to page 2.  If you then click to go back a page to page 3, it correctly shows page 3. If you go back to page 4, it shows the pads from page 2 again.

**To Reproduce**
1. You need at least 48 pads to reproduce
2. Go to the admin/pads "Manage Pads" page and ensure it is sorted by Padname (arrow pointing up)
3. Note the pad names on page 1.
4. Click on Next Page and nothing changes except the page number changes to 2.
5. Click on Next Page again and nothing changes except the page number changes to 3.
6. Click on Next Page again and the pads change to the pads of page 2 (but the page number is 4)
7. Click on Previous Page and the pads change to the pads of page 3 (and the page number is correctly shown as 3)

**Expected behavior**
Page 1 should show the first 12 pads, page 2 the next 12 pads, and so on.

**Screenshots**
Included 2 short video clips as it seems like it would take a lot of screenshots.

**Server (please complete the following information):**
 - Etherpad version: 2.0.3
 - OS: Tried it on multiple: Ubuntu 22.04, 24.04, Debian 12.5, Rockylinux 9
 - Node.js version (`node --version`):  v22.0.0
 - npm version (`npm --version`): 10.5.1
 - Is the server free of plugins: yes

**Desktop (please complete the following information):**
 - OS: Windows 10, 11, MacOS Ventura
 - Browser: chrome, firefox, safari (Mac Only) 
 - Version chrome 124, firefox 125, safari 17.4.1

**Additional context**
I have only tried this with mysql server, but suspect it would be the same on other DBs

https://github.com/ether/etherpad-lite/assets/89752746/9171f700-f085-448e-9335-31a0c56cba3c

https://github.com/ether/etherpad-lite/assets/89752746/978c8d53-17ce-4e20-ba8e-cd3b438b76c8

**Comment by SamTV12345** [comment]
Could you please try with the latest develop version?

**Comment by dvandemaele** [comment]
Hello SamTV,

Thanks for the quick fix on this!

I have confirmed that sorting and paging is now working as expected on the 'Padname' column!

However, it is not working properly on the other columns.

I made a video again as it seems it would take a lot of screenshots.

https://github.com/ether/etherpad-lite/assets/89752746/c75795c7-f586-4664-9127-d99b6f693adf

Thanks!

**Comment by heldersepu** [comment]
@SamTV12345 this issue can be closed

**Comment by SamTV12345** [comment]
> @SamTV12345 this issue can be closed, maybe open a new one for the "other" columns

Yes let's close this one
