### ISSUE TITLE
Settings aren't saved in admin UI

### ISSUE THREAD

**Issue by Uatschitchun** [ether/etherpad-lite#6407]
**Describe the bug**
In Admin UI it's possible to edit and save `settings.json` and also to restart etherpad.
When doing changes and save these, the changes to `settings.json` are not saved

**To Reproduce**
1. Go to 'Admin Panel (/admin/plugins)'
2. Click on 'settings'
3. Change something in settings.json
4. Click on 'save settings' 
5. Click on 'restart etherpad'
6. changes are not saved

**Expected behavior**
changes to settings.json should be saved when done in Admin UI

**Server (please complete the following information):**
 - Etherpad version: 2.0.3
 - Is the server free of plugins: yes

**Comment by heldersepu** [comment]
testing with `Etherpad version is 2.0.3` running a fresh clone of the repo
I'm able to reproduce...

I just add some extra comments via the UI, clicking save shows the animation:
![image](https://github.com/ether/etherpad-lite/assets/545474/59b0e978-491c-4ad7-b60d-f394d6c83cfe)
and the success popup
![image](https://github.com/ether/etherpad-lite/assets/545474/1d6be5a7-6a46-4768-810f-56ef365ac6e7)
But when the page reloads my change is not there

troubleshooting some more now ...

**Comment by heldersepu** [comment]
Frontend

https://github.com/ether/etherpad-lite/blob/9d8f1f60cc521eaa255c412f7b5cfb4465a6184f/admin/src/pages/SettingsPage.tsx#L17-L26

Backend

https://github.com/ether/etherpad-lite/blob/9d8f1f60cc521eaa255c412f7b5cfb4465a6184f/src/node/hooks/express/adminsettings.ts#L41-L45

**Comment by SamTV12345** [comment]
> Frontend
> 
> https://github.com/ether/etherpad-lite/blob/9d8f1f60cc521eaa255c412f7b5cfb4465a6184f/admin/src/pages/SettingsPage.tsx#L17-L26
> 
> Backend
> 
> https://github.com/ether/etherpad-lite/blob/9d8f1f60cc521eaa255c412f7b5cfb4465a6184f/src/node/hooks/express/adminsettings.ts#L41-L45

Did you find something? The code looks good so far. The call is correct but the function is not called. Weirdly enough the restartServer  callback is working

**Comment by heldersepu** [comment]
@SamTV12345  nothing significant yet ... same as you all points to the function not been called

not sure why there are no `logger.info(...);` in that adminsettings: 
https://github.com/ether/etherpad-lite/compare/develop...heldersepu:etherpad-lite:develop
Other files do have it is there any reason for that not been here??

**Comment by SamTV12345** [comment]
> @SamTV12345 nothing significant yet ... same as you all points to the function not been called
> 
> not sure why there are no `logger.info(...);` in that adminsettings: [develop...heldersepu:etherpad-lite:develop](https://github.com/ether/etherpad-lite/compare/develop...heldersepu:etherpad-lite:develop) Other files do have it is there any reason for that not been here??

Goo idea. console.log is bound to logger.info but it is probably better to use it.

**Comment by heldersepu** [comment]
I think it has something to do with the size of that settings string ...
![image](https://github.com/ether/etherpad-lite/assets/545474/6d247028-71e7-468f-a7b0-89b5389360b9)
Look there when we remove a few lines from the comments it really does nothing...
but when i try with something smaller:
```
{
  "title": "Etherpad"
}
```
we can see my terminal shows:
`[INFO] adminSettings - Admin request to save settings through a socket on /admin/settings`

**Comment by heldersepu** [comment]
it feels this is caused by:
https://github.com/ether/etherpad-lite/blob/556c3c8e5bc4e1c807dbeac94006d1e178b25872/src/node/utils/Settings.ts#L147-L157

**Comment by heldersepu** [comment]
Yes that is the root cause increasing it to `"maxHttpBufferSize": 50000` took care of the problem...

Now what is the "right" thing to do?
- increasing the default to 50000 will solve the issue now
- look for a technical solution to send smaller payload

**Comment by heldersepu** [comment]
...thinking about how to send a smaller payload
- an easy approach could be to remove the many many comments from the settings, it could be done before we display it in the admin/settings, and add a link there to the template: 
https://github.com/ether/etherpad-lite/blob/develop/settings.json.template  
- another more involved approach, I'm thinking admin users make a small changes and save, what we could do is get a diff and send that to be applied, that should be significantly smaller, this could be helpful: 
https://www.npmjs.com/package/diff-match-patch

**Comment by SamTV12345** [comment]
> Yes that is the root cause increasing it to `"maxHttpBufferSize": 50000` took care of the problem...
> 
> Now what is the "right" thing to do?
> 
> * increasing the default to 50000 will solve the issue now
> * look for a technical solution to send smaller payload
> 
> maybe do both:
> 
> * increase this now and release fix to not carry this bug any longer.
> * then spend some to refactor the  `saveSettings` to send smaller payload, so we don't run into this again when the setting.json grows

Oh damn. I added some things in the settings.json, that added extra bytes to the file, so that the default value cannot be used anymore to save the settings. Do you have some spare time for a permanent solution. The problem with the diff approach would be that it wouldn't work if I paste in the complete settings.json. Also it would add itself a payload for returning the diff.

**Comment by heldersepu** [comment]
> Do you have some spare time for a permanent solution
Sure... What did you have in mind as permanent? removing all comments is the easiest way

**Comment by heldersepu** [comment]
Now let me point ... 
@Uatschitchun if you are following the comments and this is a must have for you 
your options right now are:
- increasing that `maxHttpBufferSize` will do it (unfortunately you need to do that on the server)
- remove all the comments from that setting file to make it smaller

**Comment by Uatschitchun** [comment]
@heldersepu yes, I'm following. It's more of a "if it's there, it should work" than a must have ;)

**Comment by heldersepu** [comment]
Perfect I see the PR was merged...
I also been working on a function to remove the comments that way we reduce the size of what we save

**Comment by SamTV12345** [comment]
> Perfect I see the PR was merged...
> 
> I also been working on a function to remove the comments that way we reduce the size of what we save

Thanks for the help. Really appreciated.

**Comment by heldersepu** [comment]
> Thanks for the help. Really appreciated.

My pleasure!   I've been doing a lot of DevOps lately, mostly Terraform; This is a great way to stay sharp while helping a real world project.
