### ISSUE TITLE
Failed to open plugin management

### ISSUE THREAD

**Issue by yuyongsong** [ether/etherpad-lite#6463]
**Describe the bug**
<img width="671" alt="accc7fdf55435ecb90720bc04f999ca" src="https://github.com/ether/etherpad-lite/assets/48560843/63dbdf11-104b-475b-a6de-8f47a0b5b145">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version:
 - OS: [e.g., Ubuntu 20.04]
 - Node.js version (`node --version`):
 - npm version (`npm --version`):
 - Is the server free of plugins: 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
<img width="671" alt="微信图片_20240619124415" src="https://github.com/ether/etherpad-lite/assets/48560843/38890648-de7f-455b-9ab1-625e6f1f72ca">

**Comment by heldersepu** [comment]
Hard to troubleshoot when all you provide is an image...

Here is one image:
![Kazam_screenshot_00000](https://github.com/ether/etherpad-lite/assets/545474/c937c293-52db-4bc6-95f0-74e8676cfdaf)
As far as I can see it works with the latest version
