### ISSUE TITLE
after 1.9.x to 2.1 upgrade , ep will not run

### ISSUE THREAD

**Issue by robfantini** [ether/etherpad-lite#6492]
**Describe the bug**
after upgrading ep will not start

**To Reproduce**

1. upgrade code with
2. attempt startup with 'systemctl status etherpad.service' 
3. check status: systemctl status etherpad.service
4. Scroll down to '....'
5. See error

**Expected behavior**
that ep will startup and work.
**Screenshots**
n/a
**Server (please complete the following information):**
 - Etherpad version: 21
 - OS: Debian Bookworm
 - Node.js  v18.19.0
   - npm 9.2.0
   - pnpm --version 9.4.0

 - Is the server free of plugins: 

**Desktop (please complete the following information):**
n/a this is a server issue.
 

**Additional context**
`# systemctl status etherpad.service
× etherpad.service - Etherpad-lite, the collaborative editor.
     Loaded: loaded (/etc/systemd/system/etherpad.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-07-04 07:05:30 EDT; 24min ago
   Duration: 116ms
    Process: 45589 ExecStart=/usr/bin/node /opt/etherpad/etherpad-lite/src/node/server.js (code=exited, status=1/FAILURE)
   Main PID: 45589 (code=exited, status=1/FAILURE)
        CPU: 117ms

Jul 04 07:05:30 etherpad node[45589]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
Jul 04 07:05:30 etherpad node[45589]:     at Module._load (node:internal/modules/cjs/loader:975:27)
Jul 04 07:05:30 etherpad node[45589]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
Jul 04 07:05:30 etherpad node[45589]:     at node:internal/main/run_main_module:28:49 {
Jul 04 07:05:30 etherpad node[45589]:   code: 'MODULE_NOT_FOUND',
Jul 04 07:05:30 etherpad node[45589]:   requireStack: []
Jul 04 07:05:30 etherpad node[45589]: }
Jul 04 07:05:30 etherpad node[45589]: Node.js v18.19.0
Jul 04 07:05:30 etherpad systemd[1]: etherpad.service: Main process exited, code=exited, status=1/FAILURE
Jul 04 07:05:30 etherpad systemd[1]: etherpad.service: Failed with result 'exit-code'.
`

normal start up does not work. so after reading /opt/etherpad/etherpad-lite/CHANGELOG.md 
`cd /opt/etherpad/etherpad-lite

export NODE_ENV=production; pnpm run prod
..
[2024-07-04T07:30:42.827] [INFO] server - Etherpad is running
[2024-07-04T07:30:50.187] [ERROR] server - Metrics at time of fatal error:
..
[2024-07-04T07:30:50.188] [ERROR] server - Error: ENOENT: no such file or directory, stat '/opt/etherpad/etherpad-lite/src/templates/admin/index.html'
    at Object.statSync (node:fs:1688:3)
    at <anonymous> (/opt/etherpad/etherpad-lite/src/node/hooks/express/admin.ts:57:14)
    at suppressedCallback (node:fs:267:5)
    at FSReqCallback.oncomplete (node:fs:192:23)`

**Comment by SamTV12345** [comment]
Oh you need to go to the admin folder in the Etherpad root directory, after that pnpm install and then pnpm run build-copy

**Comment by robfantini** [comment]
Hi Sam
 The following is our normal upgrade procedure.   Would I run those two commands after 'git pull origin' ?

`systemctl stop etherpad

su - etherpad
cd /opt/etherpad/etherpad-lite
git pull origin

./bin/installDeps.sh

exit

# as root
systemctl start etherpad.service
`

**Comment by SamTV12345** [comment]
Yes try to do it after git pull. Then the admin panel should be created.

**Comment by robfantini** [comment]
i did these,  ep does not start.   i'll put infor after what i did
`systemctl stop etherpad

su - etherpad
cd /opt/etherpad/etherpad-lite
git pull origin

cd admin

pnpm install

pnpm run build-copy

cd ..
./bin/installDeps.sh
exit

# as root
systemctl start etherpad.service`

`
root@etherpad:[~]:# systemctl start etherpad.service
root@etherpad:[~]:# systemctl status etherpad.service
× etherpad.service - Etherpad-lite, the collaborative editor.
     Loaded: loaded (/etc/systemd/system/etherpad.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-07-04 15:54:39 EDT; 17s ago
   Duration: 120ms
    Process: 8417 ExecStart=/usr/bin/node /opt/etherpad/etherpad-lite/src/node/server.js (code=exited, status=1/FAILURE)
   Main PID: 8417 (code=exited, status=1/FAILURE)
        CPU: 121ms

Jul 04 15:54:39 etherpad node[8417]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
Jul 04 15:54:39 etherpad node[8417]:     at Module._load (node:internal/modules/cjs/loader:975:27)
Jul 04 15:54:39 etherpad node[8417]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
Jul 04 15:54:39 etherpad node[8417]:     at node:internal/main/run_main_module:28:49 {
Jul 04 15:54:39 etherpad node[8417]:   code: 'MODULE_NOT_FOUND',
Jul 04 15:54:39 etherpad node[8417]:   requireStack: []
Jul 04 15:54:39 etherpad node[8417]: }
Jul 04 15:54:39 etherpad node[8417]: Node.js v18.19.0
Jul 04 15:54:39 etherpad systemd[1]: etherpad.service: Main process exited, code=exited, status=1/FAILURE
Jul 04 15:54:39 etherpad systemd[1]: etherpad.service: Failed with result 'exit-code'.
`

**Comment by SamTV12345** [comment]
Oh sorry for not being clear. You need to execute the above two commands only once per git pull. 
 
With 2.x.x we also revised the systemd service:

[Unit]
Description=Etherpad-lite, the collaborative editor.
After=syslog.target network.target

[Service]
Type=simple
User=etherpad
Group=etherpad
WorkingDirectory=/opt/etherpad
Environment=NODE_ENV=production
ExecStart=pnpm run prod
# use mysql plus a complete settings.json to avoid Service hold-off time over, scheduling restart.
Restart=always

[Install]
WantedBy=multi-user.target

StandardOutput=append:/var/log/etherpad/etherpad.log
StandardError=append:/var/log/etherpad/etherpad-error.log

**Comment by robfantini** [comment]
`root@etherpad:[~]:# systemctl status etherpad
× etherpad.service - Etherpad-lite, the collaborative editor.
     Loaded: loaded (/etc/systemd/system/etherpad.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-07-04 16:11:08 EDT; 1s ago
   Duration: 643ms
    Process: 9386 ExecStart=pnpm run prod (code=exited, status=1/FAILURE)
   Main PID: 9386 (code=exited, status=1/FAILURE)
        CPU: 678ms

Jul 04 16:11:07 etherpad systemd[1]: Started etherpad.service - Etherpad-lite, the collaborative editor..
Jul 04 16:11:08 etherpad pnpm[9386]:  ERR_PNPM_NO_IMPORTER_MANIFEST_FOUND  No package.json (or package.yaml, or package.json5) was fou>
Jul 04 16:11:08 etherpad systemd[1]: etherpad.service: Main process exited, code=exited, status=1/FAILURE
Jul 04 16:11:08 etherpad systemd[1]: etherpad.service: Failed with result 'exit-code'.
Jul 04 16:11:10 etherpad systemd[1]: /etc/systemd/system/etherpad.service:18: Unknown key 'StandardOutput' in section [Install], ignor>
Jul 04 16:11:10 etherpad systemd[1]: /etc/systemd/system/etherpad.service:19: Unknown key 'StandardError' in section [Install], ignori>`

**Comment by SamTV12345** [comment]
Hm. Just leave the last two out. Seems like your server is pretty old. Only the new systemd services have the last two lines.

**Comment by robfantini** [comment]
I am using debian bookworm, that should have a new enough systemd?

I made a snapshot,  I'll restore it and start the upgrade over.

if you could look this over  , these are my upgrade steps.

`systemctl stop etherpad
su - etherpad
cd /opt/etherpad/etherpad-lite
git pull origin
cd admin
pnpm install
pnpm run build-copy
cd ..
./bin/installDeps.sh
exit
systemctl start etherpad.service`

**Comment by robfantini** [comment]
`
# apt show systemd

Package: systemd

Version: 252.26-1~deb12u2
`

**Comment by SamTV12345** [comment]
> I am using debian bookworm, that should have a new enough systemd?
> 
> I made a snapshot, I'll restore it and start the upgrade over.
> 
> if you could look this over , these are my upgrade steps.
> 
> ` systemctl stop etherpad
> 
> su - etherpad
> 
> cd /opt/etherpad/etherpad-lite
> 
> git pull origin
> 
> cd admin
> 
> pnpm install
> 
> pnpm run build-copy
> 
> cd ..
> 
> ./bin/installDeps.sh
> 
> exit
> 
> systemctl start etherpad.service`

That should be enough for the upgrade.

**Comment by SamTV12345** [comment]
> StandardOutput

Sorry it was my fault. I appended the values to the wrong section. Try to move the StandardOutput and StandardError lines to the section service. That will hopefully work.

**Comment by robfantini** [comment]
I made the change in the unit file.
note this:   'Jul 04 16:44:07 etherpad (pnpm)[9930]: etherpad.service: Failed at step STDOUT spawning pnpm: No such file or directory

`

systemctl status etherpad
× etherpad.service - Etherpad-lite, the collaborative editor.
     Loaded: loaded (/etc/systemd/system/etherpad.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-07-04 16:44:07 EDT; 3s ago
   Duration: 1ms
    Process: 9930 ExecStart=pnpm run prod (code=exited, status=209/STDOUT)
   Main PID: 9930 (code=exited, status=209/STDOUT)
        CPU: 766us

Jul 04 16:44:07 etherpad (pnpm)[9930]: etherpad.service: Failed at step STDOUT spawning pnpm: No such file or directory
Jul 04 16:44:07 etherpad systemd[1]: Started etherpad.service - Etherpad-lite, the collaborative editor..
Jul 04 16:44:07 etherpad systemd[1]: etherpad.service: Main process exited, code=exited, status=209/STDOUT
Jul 04 16:44:07 etherpad systemd[1]: etherpad.service: Failed with result 'exit-code'.
`

**Comment by SamTV12345** [comment]
> I made the change in the unit file.
> 
> note this:   'Jul 04 16:44:07 etherpad (pnpm)[9930]: etherpad.service: Failed at step STDOUT spawning pnpm: No such file or directory
> 
> 
> 
> `
> 
> 
> 
> systemctl status etherpad
> 
> × etherpad.service - Etherpad-lite, the collaborative editor.
> 
>      Loaded: loaded (/etc/systemd/system/etherpad.service; enabled; preset: enabled)
> 
>      Active: failed (Result: exit-code) since Thu 2024-07-04 16:44:07 EDT; 3s ago
> 
>    Duration: 1ms
> 
>     Process: 9930 ExecStart=pnpm run prod (code=exited, status=209/STDOUT)
> 
>    Main PID: 9930 (code=exited, status=209/STDOUT)
> 
>         CPU: 766us
> 
> 
> 
> Jul 04 16:44:07 etherpad (pnpm)[9930]: etherpad.service: Failed at step STDOUT spawning pnpm: No such file or directory
> 
> Jul 04 16:44:07 etherpad systemd[1]: Started etherpad.service - Etherpad-lite, the collaborative editor..
> 
> Jul 04 16:44:07 etherpad systemd[1]: etherpad.service: Main process exited, code=exited, status=209/STDOUT
> 
> Jul 04 16:44:07 etherpad systemd[1]: etherpad.service: Failed with result 'exit-code'.
> 
> `

Seems like pnpm is not installed. Do npm install -g pnpm You maybe need sudo

**Comment by robfantini** [comment]
I had installed it before.

$ which pnpm
/usr/local/bin/pnpm


I tried using /usr/local/bin/pnpm  in the unit file - incase $PATH was wrong.   same result...

I've got to go soon,    so will start over again after I restore a backup.

**Comment by SamTV12345** [comment]
Maybe you need to set the path explicitly? Does everyone has access to pnpm? Did you come up with a solution yet?

**Comment by robfantini** [comment]
Hello   -   I did try setting the path explicitly .     I should be able to work on this tomorrow morning.

**Comment by robfantini** [comment]
Hello,    I followed the upgrade steps listed above.


unit file - i commented out restart so initial error could be shown
`
[Unit]
Description=Etherpad-lite, the collaborative editor.
After=syslog.target network.target

[Service]
Type=simple
User=etherpad
Group=etherpad
WorkingDirectory=/opt/etherpad
Environment=NODE_ENV=production
ExecStart=/usr/local/bin/pnpm run prod
# use mysql plus a complete settings.json to avoid Service hold-off time over, scheduling restart.
#Restart=always
StandardOutput=append:/var/log/etherpad/etherpad.log
StandardError=append:/var/log/etherpad/etherpad-error.log

[Install]
WantedBy=multi-user.target 
`
`
$systemctl status etherpad.service
× etherpad.service - Etherpad-lite, the collaborative editor.
     Loaded: loaded (/etc/systemd/system/etherpad.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2024-07-07 06:23:32 EDT; 3s ago
   Duration: 867us
    Process: 2165 ExecStart=/usr/local/bin/pnpm run prod (code=exited, status=209/STDOUT)
   Main PID: 2165 (code=exited, status=209/STDOUT)
        CPU: 476us

Jul 07 06:23:32 etherpad-test (pnpm)[2165]: etherpad.service: Failed at step STDOUT spawning /usr/local/bin/pnpm: No such file or directory
Jul 07 06:23:32 etherpad-test systemd[1]: Started etherpad.service - Etherpad-lite, the collaborative editor..
Jul 07 06:23:32 etherpad-test systemd[1]: etherpad.service: Main process exited, code=exited, status=209/STDOUT
Jul 07 06:23:32 etherpad-test systemd[1]: etherpad.service: Failed with result 'exit-code'.
`

the permissions on pnpm look good

I tried change the systemd unit file to use ''User=root"  and had the same result as above.

Still working on this.

**Comment by robfantini** [comment]
the original systemd file had this line:

ExecStart=/usr/bin/node /opt/etherpad/etherpad-lite/src/node/server.js


perhaps '/opt/etherpad/etherpad-lite/src/node/server.js'  is needed on the ExecStart= line?      

I'll get back to this later

**Comment by SamTV12345** [comment]
> the original systemd file had this line:
> 
> 
> 
> ExecStart=/usr/bin/node /opt/etherpad/etherpad-lite/src/node/server.js
> 
> 
> 
> 
> 
> perhaps '/opt/etherpad/etherpad-lite/src/node/server.js'  is needed on the ExecStart= line?      
> 
> 
> 
> I'll get back to this later 

The problem is that this file does not exist in the new version as it has been replaced by Typescript. But to run typescript you need a slightly modified command. Can you try /usr/local/bin/pnpm --version ?

**Comment by robfantini** [comment]
9.4.0

**Comment by SamTV12345** [comment]
> 9.4.0
> 
> 
> 
> I'll be back to this in 8 hours or so.. 
> 
> 
> 
> Also -  I can give you ssh access to this system.     communicate with me directly if you are interested in doing so.

This is quite weird. I mean if you can call pnpm why is it not working with systemd and reported as file not found. Sure that would be helpful maybe I can figure out what is going on. If you have discord you can send the address and username and password there. Otherwise email would be an option too.

**Comment by robfantini** [comment]
Send me your email address

**Comment by SamTV12345** [comment]
> Send me your email address 

Sure samelus1998@outlook.de

**Comment by robfantini** [comment]
with Sam's great help our upgrade succeeded. 

here are some more notes:
`mkdir /var/log/etherpad/
> /var/log/etherpad/etherpad.log
> /var/log/etherpad/etherpad-error.log
chown -R etherpad /var/log/etherpad/
`

final /etc/systemd/system/etherpad.service
`[Unit]
Description=Etherpad-lite, the collaborative editor.
After=syslog.target network.target

[Service]
Type=simple
User=etherpad
Group=etherpad
WorkingDirectory=/opt/etherpad/etherpad-lite
Environment=NODE_ENV=production
ExecStart=/usr/local/bin/pnpm run prod
;Restart=always
StandardOutput=append:/var/log/etherpad/etherpad.log
StandardError=append:/var/log/etherpad/etherpad-error.log

[Install]
WantedBy=multi-user.target 
`
settings.json  , 
Old:  "socketTransportProtocols" : ["xhr-polling", "jsonp-polling", "htmlfile"],
New: "socketTransportProtocols" : ["websocket", "polling"],
