### ISSUE TITLE
Crashes immediately after installing dependencies

### ISSUE THREAD

**Issue by locrianz** [ether/etherpad-lite#6494]
**Describe the bug**
I'm following the "Manual install" guide. After running bin/run.sh, the following text displays in terminal:

```
Installing dependencies...
Installing dev dependencies with pnpm
Scope: all 6 workspace projects
Lockfile is up to date, resolution step is skipped
.                                        | +880 ++++++++++++++++++++++++++++++
Downloading @swc/core-linux-x64-gnu@1.5.7: 16.64 MB/16.64 MB, done
Downloading @swc/core-linux-x64-musl@1.5.7: 20.60 MB/20.60 MB, done
Progress: resolved 880, reused 178, downloaded 14, added 13
Killed
```

**To Reproduce**
1. Install latest nodejs version
2. `git clone --branch master https://github.com/ether/etherpad-lite.git`
3. `cd etherpad-lite`
4. `bin/run.sh`

**Expected behavior**
Program should continue to run after installing dependencies and I should be able to access the instance at 127.0.0.1:9001.

**Server (please complete the following information):**
 - Etherpad version: 2.1.0
 - OS: Ubuntu 24.04
 - Node.js version (`node --version`): 22.4.0
 - npm version (`npm --version`): 10.8.1
 - Is the server free of plugins: Yes

**Comment by SamTV12345** [comment]
> **Describe the bug** I'm following the "Manual install" guide. After running bin/run.sh, the following text displays in terminal:
> 
> ```
> Installing dependencies...
> Installing dev dependencies with pnpm
> Scope: all 6 workspace projects
> Lockfile is up to date, resolution step is skipped
> .                                        | +880 ++++++++++++++++++++++++++++++
> Downloading @swc/core-linux-x64-gnu@1.5.7: 16.64 MB/16.64 MB, done
> Downloading @swc/core-linux-x64-musl@1.5.7: 20.60 MB/20.60 MB, done
> Progress: resolved 880, reused 178, downloaded 14, added 13
> Killed
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install latest nodejs version
> 2. `git clone --branch master https://github.com/ether/etherpad-lite.git`
> 3. `cd etherpad-lite`
> 4. `bin/run.sh`
> 
> **Expected behavior** Program should continue to run after installing dependencies and I should be able to access the instance at 127.0.0.1:9001.
> 
> **Server (please complete the following information):**
> 
> * Etherpad version: 2.1.0
> * OS: Ubuntu 24.04
> * Node.js version (`node --version`): 22.4.0
> * npm version (`npm --version`): 10.8.1
> * Is the server free of plugins: Yes

Hmm. This is weird. Killed normally means you have no memory left and unix did kill the programm. How much RAM do you have?

**Comment by locrianz** [comment]
Ah, I only had 512 MB. I've gone ahead and added more RAM; I didn't even realize that would be an issue but it makes sense. Thanks.

**Comment by SamTV12345** [comment]
> Ah, I only had 512 MB. I've gone ahead and added more RAM; I didn't even realize that would be an issue but it makes sense. Thanks.

Glad that this is fixed. Yeah you weren't even running Etherpad it was already crashing when installing dependencies.
