### ISSUE TITLE
Failed to extract folder because file name is too long 

### ISSUE THREAD

**Issue by Eyion** [ether/etherpad-lite#6501]
**Describe the bug**
The file name may be too long for the destination folder. You can shorten the file name and try again, or try a shorter location. 

**To Reproduce**
1. Extract the folder

**Expected behavior**
Extract folder correctly 

**Screenshots**
![image](https://github.com/ether/etherpad-lite/assets/26318038/74d014d4-96b5-447e-9f38-5cba2ea967a2)

**Server (please complete the following information):**
No

**Desktop (please complete the following information):**
 - OS: Windows 10 IoT LTSC 21H2 19044.4529
 - Browser: chrome 126.0.6478.127

**Smartphone (please complete the following information):**
No

**Additional context**
No

**Comment by SamTV12345** [comment]
> **Describe the bug**
> 
> The file name may be too long for the destination folder. You can shorten the file name and try again, or try a shorter location. 
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Extract the folder
> 
> 
> 
> **Expected behavior**
> 
> Extract folder correctly 
> 
> 
> 
> **Screenshots**
> 
> ![image](https://github.com/ether/etherpad-lite/assets/26318038/74d014d4-96b5-447e-9f38-5cba2ea967a2)
> 
> 
> 
> **Server (please complete the following information):**
> 
> No
> 
> 
> 
> **Desktop (please complete the following information):**
> 
>  - OS: Windows 10 IoT LTSC 21H2 19044.4529
> 
>  - Browser: chrome 126.0.6478.127
> 
> 
> 
> **Smartphone (please complete the following information):**
> 
> No
> 
> 
> 
> **Additional context**
> 
> No
> 
> 

Hi thanks for the issue. Unfortunately I don't really get what the connection to Etherpad should be. Could you shed some light on it?
