### ISSUE TITLE
admin settings hanging in Etherpad 2.1.0 and 2.1.1

### ISSUE THREAD

**Issue by elmatusov** [ether/etherpad-lite#6508]
I cannot access the Etherpad Lite admin settings in versions 2.1.0 and 2.1.1 (https://mydoman:9001/admin/). After I enter my admin password, the page hangs. Other than that, Etherpad works well in both versions.

Interestingly enough, I cannot even access the admin settings using the default setting.json file working with dirty database. However, the problem is different. It says that the password is wrong ("changeme1"). 

I have neither problem in Etherpad version 2.0.1. 

How can I solve this problem? Thanks!

**Comment by SamTV12345** [comment]
Hmm thanks for the bug. Do you use Etherpad bare metal or with Docker? Is there some error in the network tab? The endpoint changed to /admin-auth/. So if you didn't regenerate the admin panel this could be an explanation.

**Comment by elmatusov** [comment]
I'm rather a newbie in Etherpad. I think I'm using Etherpad bare metal (If I understand it correctly). I use it with MySQL via SSL. I'm not sure I even know what Docker is, sorry. However, I use node.js and on your previous advice, I do manual installation of Etherpad: "First do npm install pnpm -g and then do pnpm i in the Etherpad root directory. This should install all dependencies. Then you simply need to do pnpm run prod and Etherpad should start." I think it rebuilt node_modules folder. I didn't do anything else. I hope that helps you diagnose and solve the problem. Thanks!

**Comment by SamTV12345** [comment]
> I'm rather a newbie in Etherpad. I think I'm using Etherpad bare metal (If I understand it correctly). I use it with MySQL via SSL. I'm not sure I even know what Docker is, sorry. However, I use node.js and on your previous advice, I do manual installation of Etherpad: "First do npm install pnpm -g and then do pnpm i in the Etherpad root directory. This should install all dependencies. Then you simply need to do pnpm run prod and Etherpad should start." I think it rebuilt node_modules folder. I didn't do anything else. I hope that helps you diagnose and solve the problem. Thanks!

Oh alright no problem. I guess you did an update. I maybe need to add a root command at some point. You go from the root directory to the admin folder cd admin. There you do pnpm run build-copy . After that stop etherpad and start it again with pnpm run prod

**Comment by elmatusov** [comment]
Thanks, SamTV122345, for your guidelines. The problem is that I do not have an admin folder in the root directory. I downloaded the zip file from https://etherpad.org/. See its structure below. After installing it on my Windows Server 2022, I still do not have an admin folder. How can I solve this problem?

![Etherpad lite 2 1 1 zip](https://github.com/user-attachments/assets/5bce86c5-a93a-48b3-a8be-6351dd687e3e)

> 
> Oh alright no problem. I guess you did an update. I maybe need to add a root command at some point. You go from the root directory to the admin folder cd admin. There you do pnpm run build-copy . After that stop etherpad and start it again with pnpm run prod

**Comment by SamTV12345** [comment]
> Thanks, SamTV122345, for your guidelines. The problem is that I do not have an admin folder in the root directory. I downloaded the zip file from https://etherpad.org/. See its structure below. After installing it on my Windows Server 2022, I still do not have an admin folder. How can I solve this problem?
> 
> 
> 
> ![Etherpad lite 2 1 1 zip](https://github.com/user-attachments/assets/5bce86c5-a93a-48b3-a8be-6351dd687e3e)
> 
> 
> 
> > 
> 
> > Oh alright no problem. I guess you did an update. I maybe need to add a root command at some point. You go from the root directory to the admin folder cd admin. There you do pnpm run build-copy . After that stop etherpad and start it again with pnpm run prod
> 
> 
> 
> 
> 
> 

Oh you're on windows. Normally you should be having the most up to date admin panel. I always build it so it is really just download the zip and install dependencies.

**Comment by elmatusov** [comment]
Thanks, SamTV12345! I solved the problem by reinstalling Etherpad Lite 2.1.1 by running the manual installation for Windows from https://github.com/ether/etherpad-lite#installation :

Manually install on Windows
You'll need Node.js and (optionally, though recommended) git.

Grab the source, either:

1. download https://github.com/ether/etherpad-lite/zipball/master
2. With a "Run as administrator" command prompt execute bin\installOnWindows.bat

From now on, I will do only manual installation of Etherpad on Windows! Thanks A LOT!!!!!! You're my hero! 

PS I think the automatic Windows installation has had systematic problems since version 2.0.0 was introduced.

**Comment by SamTV12345** [comment]
> Thanks, SamTV12345! I solved the problem by reinstalling Etherpad Lite 2.1.1 by running the manual installation for Windows from https://github.com/ether/etherpad-lite#installation :
> 
> Manually install on Windows You'll need Node.js and (optionally, though recommended) git.
> 
> Grab the source, either:
> 
> 1. download https://github.com/ether/etherpad-lite/zipball/master
> 2. With a "Run as administrator" command prompt execute bin\installOnWindows.bat
> 
> From now on, I will do only manual installation of Etherpad on Windows! Thanks A LOT!!!!!! You're my hero!
> 
> PS I think the automatic Windows installation has had systematic problems since version 2.0.0 was introduced.

Alright. Great that this method works :)
