### ISSUE TITLE
The plugin windows cannot be closed

### ISSUE THREAD

**Issue by yEs1do** [ether/etherpad-lite#6519]
**Describe the bug**
I have successfully installed it in the Windows pro version(Windows 10) and it is working fine. However, the plug-in windows cannot be closed in the server version.What software should I install or upgrade to fix it?

**Screenshots**
![Etherpad](https://github.com/user-attachments/assets/59d63f07-7bbc-4110-8b7e-bf34c12b4e9e)

**Server (please complete the following information):**
 - Etherpad version:2.0.2-2.0.3
 - OS: Windows Server 2012
 - Node.js version (`node --version`):v20.14.0
 - npm version (`npm --version`):10.8.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 125

**Comment by SamTV12345** [comment]
> **Describe the bug** I have successfully installed it in the Windows pro version(Windows 10) and it is working fine. However, the plug-in windows cannot be closed in the server version.What software should I install or upgrade to fix it?
> 
> **Screenshots** ![Etherpad](https://private-user-images.githubusercontent.com/25378493/349597797-59d63f07-7bbc-4110-8b7e-bf34c12b4e9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODE0NjksIm5iZiI6MTcyMTI4MTE2OSwicGF0aCI6Ii8yNTM3ODQ5My8zNDk1OTc3OTctNTlkNjNmMDctN2JiYy00MTEwLThiN2UtYmYzNGMxMmI0ZTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA1MzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMmU4YmY5NzU4NThjNzYzN2UwMWZmNTM5NTIwMWZkODA0YjM1NDQ2NjVjYzc5MmNmZjVjMmQ4Mjk0OTA1MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fz4buM4g6qSm-ZuzRSmXQsYoKiwxoOrO2CLqXFGen-Q)
> 
> **Server (please complete the following information):**
> 
> * Etherpad version:2.0.2-2.0.3
> * OS: Windows Server 2012
> * Node.js version (`node --version`):v20.14.0
> * npm version (`npm --version`):10.8.1
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10
> * Browser: Chrome 125

Hi. Thanks for the issue. Can you please give me a reproducible example? It works for me without a problem.

**Comment by yEs1do** [comment]
> > **Describe the bug** I have successfully installed it in the Windows pro version(Windows 10) and it is working fine. However, the plug-in windows cannot be closed in the server version.What software should I install or upgrade to fix it?
> > **Screenshots** ![Etherpad](https://private-user-images.githubusercontent.com/25378493/349597797-59d63f07-7bbc-4110-8b7e-bf34c12b4e9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODE0NjksIm5iZiI6MTcyMTI4MTE2OSwicGF0aCI6Ii8yNTM3ODQ5My8zNDk1OTc3OTctNTlkNjNmMDctN2JiYy00MTEwLThiN2UtYmYzNGMxMmI0ZTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA1MzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMmU4YmY5NzU4NThjNzYzN2UwMWZmNTM5NTIwMWZkODA0YjM1NDQ2NjVjYzc5MmNmZjVjMmQ4Mjk0OTA1MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fz4buM4g6qSm-ZuzRSmXQsYoKiwxoOrO2CLqXFGen-Q)
> > **Server (please complete the following information):**
> > 
> > * Etherpad version:2.0.2-2.0.3
> > * OS: Windows Server 2012
> > * Node.js version (`node --version`):v20.14.0
> > * npm version (`npm --version`):10.8.1
> > 
> > **Desktop (please complete the following information):**
> > 
> > * OS: Windows 10
> > * Browser: Chrome 125
> 
> Hi. Thanks for the issue. Can you please give me a reproducible example? It works for me without a problem.

Of course, I don't encounter this problem when running on my personal computer, only on the server system, and I can't solve it.

**Comment by SamTV12345** [comment]
Sorry not really. If you do not have any plugins installed on the server it shouldn't be any different when deployed on the server.

**Comment by yEs1do** [comment]
> Sorry not really. If you do not have any plugins installed on the server it shouldn't be any different when deployed on the server.

Thank you for your attention, I will continue to troubleshoot the problem and will share my experience if I solve it.
