### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by Ajianxian** [ether/etherpad-lite#6522]
**Describe the bug**
When I use http://localhost:9001/admin/plugins to access the plugin marketplace to install the markdown plugin, the server automatically stops running and reports the following error；
Manual installation with the pnpm command is also abnormal, and remains so after modifying the npm mirror source。

**To Reproduce**
1. Run the project using the default develop branch
2. Go to 'http://localhost:9001/admin/plugins'
3. See error
4. Or use pnpm run plugins i ep_markdown command to install the plugin manually.

**Expected behavior**
The plugin can be installed normally

**Screenshots**
![image](https://github.com/user-attachments/assets/88a528fc-1f3f-478c-bc6e-2577559da379)

![image](https://github.com/user-attachments/assets/80c77e7a-b794-4e47-8b20-8026810abfa4)

**Comment by SamTV12345** [comment]
> **Describe the bug**
> 
> When I use http://localhost:9001/admin/plugins to access the plugin marketplace to install the markdown plugin, the server automatically stops running and reports the following error；
> 
> Manual installation with the pnpm command is also abnormal, and remains so after modifying the npm mirror source。
> 
> 
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Run the project using the default develop branch
> 
> 2. Go to 'http://localhost:9001/admin/plugins'
> 
> 3. See error
> 
> 4. Or use pnpm run plugins i ep_markdown command to install the plugin manually.
> 
> 
> 
> **Expected behavior**
> 
> The plugin can be installed normally
> 
> 
> 
> **Screenshots**
> 
> ![image](https://github.com/user-attachments/assets/88a528fc-1f3f-478c-bc6e-2577559da379)
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/80c77e7a-b794-4e47-8b20-8026810abfa4)
> 
> 

Seems like you can't access the npm registry and it terminates with a connection reset or am I missing something?

**Comment by SamTV12345** [comment]
> **Describe the bug** When I use http://localhost:9001/admin/plugins to access the plugin marketplace to install the markdown plugin, the server automatically stops running and reports the following error； Manual installation with the pnpm command is also abnormal, and remains so after modifying the npm mirror source。
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Run the project using the default develop branch
> 2. Go to 'http://localhost:9001/admin/plugins'
> 3. See error
> 4. Or use pnpm run plugins i ep_markdown command to install the plugin manually.
> 
> **Expected behavior** The plugin can be installed normally
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/49874202/350287793-88a528fc-1f3f-478c-bc6e-2577559da379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDA1ODEsIm5iZiI6MTcyMTY0MDI4MSwicGF0aCI6Ii80OTg3NDIwMi8zNTAyODc3OTMtODhhNTI4ZmMtMWYzZi00NzhjLWJjNmUtMjU3NzU1OWRhMzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA5MjQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZTNhNzJhMmExYTM4MzQzMzJiZGEzZTJjZTNmMWNmMzk0YmQ5MWFmNWQxYmViNzYwOTUwNjliMmUxODU2ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r7lSiblU2XgfpVG1oXfuQMPDp2y4ezY9GYHv2LKeILs)
> 
> ![image](https://private-user-images.githubusercontent.com/49874202/350290318-80c77e7a-b794-4e47-8b20-8026810abfa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDA1ODEsIm5iZiI6MTcyMTY0MDI4MSwicGF0aCI6Ii80OTg3NDIwMi8zNTAyOTAzMTgtODBjNzdlN2EtYjc5NC00ZTQ3LThiMjAtODAyNjgxMGFiZmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA5MjQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NzA3YTZjZDg2NThjNGI2OTc0MWRiOTE0NDA0Yzc2ZDI3OGNmMjAxYTZiOWZhNTQ4YTJhNTIxZDgzYzhkZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D84aBe2lxu8A5c-YgkAptshD21VjxeTk2Jyo6fLvHzY)

And you haven't built the admin interface
