### ISSUE TITLE
image_upload plugin error

### ISSUE THREAD

**Issue by scTomorrow** [ether/etherpad-lite#6531]
Windows 10 run from start.bat

I use the ep_image_upload plugin

   "ep_image_upload":{
    "storage":{
      "type": "local",
      "baseFolder": "/src/images",
      "baseURL": "http://localhost:9001/static/images/"
    },
    "fileTypes": ["jpeg", "jpg", "bmp", "gif","png"],
    "maxFileSize": 5000000
  },

added in settings.json

then the error

TypeError: Uncaught TypeError: Cannot read properties of undefined (reading 'mimeTypes')
at http://localhost:9001/p/test# at line 3
ErrorId: 0mJbmYqu0yzIpgnZjM6r
Uncaught exception
URL: http://localhost:9001/p/test#
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0

Please help me, THX

**Comment by SamTV12345** [comment]
> Windows 10 run from start.bat
> 
> I use the ep_image_upload plugin
> 
> "ep_image_upload":{ "storage":{ "type": "local", "baseFolder": "/src/images", "baseURL": "http://localhost:9001/static/images/" }, "fileTypes": ["jpeg", "jpg", "bmp", "gif","png"], "maxFileSize": 5000000 },
> 
> added in settings.json
> 
> then the error
> 
> TypeError: Uncaught TypeError: Cannot read properties of undefined (reading 'mimeTypes') at http://localhost:9001/p/test# at line 3 ErrorId: 0mJbmYqu0yzIpgnZjM6r Uncaught exception URL: http://localhost:9001/p/test# UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
> 
> Please help me, THX



> Windows 10 run from start.bat
> 
> I use the ep_image_upload plugin
> 
> "ep_image_upload":{ "storage":{ "type": "local", "baseFolder": "/src/images", "baseURL": "http://localhost:9001/static/images/" }, "fileTypes": ["jpeg", "jpg", "bmp", "gif","png"], "maxFileSize": 5000000 },
> 
> added in settings.json
> 
> then the error
> 
> TypeError: Uncaught TypeError: Cannot read properties of undefined (reading 'mimeTypes') at http://localhost:9001/p/test# at line 3 ErrorId: 0mJbmYqu0yzIpgnZjM6r Uncaught exception URL: http://localhost:9001/p/test# UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
> 
> Please help me, THX

Hi. How did you install ep_image_upload? It did work for me when installing from the admin panel.
