### ISSUE TITLE
Very confused to me: Libreoffice do not work in Docker container with latest git clone

### ISSUE THREAD

**Issue by ralfi** [ether/etherpad-lite#6543]
Hi,

trying to install libreoffice in etherpad-lite. A lot oft tries later it does not work. Let me explain the steps:

First of all: Dockerfile:

![image](https://github.com/user-attachments/assets/fac3ad41-352a-41c6-ae61-6695b9b7a8d5)

Second: adapted settings.json.docker

![image](https://github.com/user-attachments/assets/197d7d09-d979-4d2e-af02-9de0163f3761)

Third: my tagged image ...

![image](https://github.com/user-attachments/assets/736c2701-47e0-4170-8fe3-a1f5627a5083)

Okay, but start with docker-compose (clear all related files to avoid cache mistakes) this appears

![image](https://github.com/user-attachments/assets/a90bbc3a-2dc1-44c6-98db-c4fe450eed30)

and inside my container soffice is really installed...

![image](https://github.com/user-attachments/assets/2ca4302c-4f08-4ba9-9290-befda191a05f)

But Etherpad do not recognize this...

![image](https://github.com/user-attachments/assets/c9cb5225-138e-44ea-9263-538ac72ccad5)

What is wrong? 
Why Etherpad does not recognize that soffice is installed?

Thanks a lot for any hints...
Regards!

**Comment by ralfi** [comment]
Wrong context and understand

**Comment by SamTV12345** [comment]
Great that this is also resolved :)
