### ISSUE TITLE
Pagination not working correctly on admin/pads part 2

### ISSUE THREAD

**Issue by dvandemaele** [ether/etherpad-lite#6551]
**Describe the bug**
This is part 2 of Issue #6384 (which fixed sorting and pagination for the Padname column).

This issue is for the other 3 columns in admin/pads: "Pad user count", "Last edited" and "Revision number"

All details of this issue can be found in #6384 

It would be really helpful when you have hundreds of pads to sort and page through these other columns.

Thank You.

**Comment by SamTV12345** [comment]
Thanks for the bug report. I hopefully fixed it this time forever. It now loads only necessary data of the pads into the memory and then goes from there with the comparison

**Comment by dvandemaele** [comment]
Working great!

Thank you.

From: SamTV12345 ***@***.***>
Reply-To: ether/etherpad-lite ***@***.***>
Date: Tuesday, August 6, 2024 at 2:45 PM
To: ether/etherpad-lite ***@***.***>
Cc: Denny VandeMaele ***@***.***>, Author ***@***.***>
Subject: Re: [ether/etherpad-lite] Pagination not working correctly on admin/pads part 2 (Issue #6551)


Feel free to test it out on develop

**Comment by SamTV12345** [comment]
Great :)
