### ISSUE TITLE
Building docker etherpad-lite-app from latest git master branch succeeded but start fails

### ISSUE THREAD

**Issue by ralfi** [ether/etherpad-lite#6555]
**Describe the bug**
My **goal** is to **rebuild etherpad-lite-app with libreoffice and ep_plugins,** also **minimal changes in the default config files** to using docker-compose for setup etherpad-lite with postgres in my environment 

**To Reproduce**
1. **git clone** --branch master ...
2. **cp env.dev.default to .env** and **docker-compose.dev.yml to docker-compose.yml**
3. **modify docker-compose.yml** to rebuild the app with libreoffice and plugins with **env=production**, **see pic**
4. **docker-compose build --no-cache** rebuild app with **success and no errors**
5. **modify settings.json.docker** var **soffice to /usr/bin/soffice**
6. **docker-compose up -d** to start the container 

**Expected behavior**
Starting docker-container for database and etherpad. Database works, Etherpad fails, **see pic**

**Screenshots**

**modified docker-compose.yml**
![image](https://github.com/user-attachments/assets/0a57fba1-105b-463f-a620-0f79a365c85e)

**Errors starting etherpad-lite-app, of course repeated**
![image](https://github.com/user-attachments/assets/38ab1bd5-34ee-453c-99b1-b9a2970107db)

**Server (please complete the following information):**
 - Etherpad version: 2.1.1
 - OS: docker 26.1.4
 - Node.js version (`node --version`): as the buils scripts define (no changes)
 - npm version (`npm --version`): as the buils scripts define (no changes)
 - Is the server free of plugins: 

**Desktop (please complete the following information):**
 - OS: Debian 
 - Browser Chrome
 - Version 126

**Additional context**
Looking around here could it be possible that modules will be overwrite or not installed? What should be modified in the Dockerfile or something else?

Thanks in advance!

**Comment by SamTV12345** [comment]
> **Describe the bug** My **goal** is to **rebuild etherpad-lite-app with libreoffice and ep_plugins,** also **minimal changes in the default config files** to using docker-compose for setup etherpad-lite with postgres in my environment
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. **git clone** --branch master ...
> 2. **cp env.dev.default to .env** and **docker-compose.dev.yml to docker-compose.yml**
> 3. **modify docker-compose.yml** to rebuild the app with libreoffice and plugins with **env=production**, **see pic**
> 4. **docker-compose build --no-cache** rebuild app with **success and no errors**
> 5. **modify settings.json.docker** var **soffice to /usr/bin/soffice**
> 6. **docker-compose up -d** to start the container
> 
> **Expected behavior** Starting docker-container for database and etherpad. Database works, Etherpad fails, **see pic**
> 
> **Screenshots**
> 
> **modified docker-compose.yml** ![image](https://private-user-images.githubusercontent.com/294423/354516729-0a57fba1-105b-463f-a620-0f79a365c85e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDgzMTUsIm5iZiI6MTcyMjcwODAxNSwicGF0aCI6Ii8yOTQ0MjMvMzU0NTE2NzI5LTBhNTdmYmExLTEwNWItNDYzZi1hNjIwLTBmNzlhMzY1Yzg1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxODAwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjFmOGFkOWY2OTMyZjQ2Y2M5NzI0YzZjYmZiNDNjNjc2YWY0OTk2NjBlNzBjZjYxNjRmYzlkNTUwMDE3NzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7Wy2f6qQJVetehcJC_jkH0r5JiSWg87-ta1ERX3xmgk)
> 
> **Errors starting etherpad-lite-app, of course repeated** ![image](https://private-user-images.githubusercontent.com/294423/354515371-38ab1bd5-34ee-453c-99b1-b9a2970107db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDgzMTUsIm5iZiI6MTcyMjcwODAxNSwicGF0aCI6Ii8yOTQ0MjMvMzU0NTE1MzcxLTM4YWIxYmQ1LTM0ZWUtNDUzYy05OWIxLWI5YTI5NzAxMDdkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxODAwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODViOWUzNjA4MjMyYWVlZmFiODNhNmJmYzNjOTYyNzUyOGRkMDg5MjZlODIyMGE2NGY2ZDQ0MmQ5MmNhMzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aNrhPqqLnRfXGpdr4vVFKDveGib2AQX2U3-jU8UhXNQ)
> 
> **Server (please complete the following information):**
> 
> * Etherpad version: 2.1.1
> * OS: docker 26.1.4
> * Node.js version (`node --version`): as the buils scripts define (no changes)
> * npm version (`npm --version`): as the buils scripts define (no changes)
> * Is the server free of plugins:
> 
> **Desktop (please complete the following information):**
> 
> * OS: Debian
> * Browser Chrome
> * Version 126
> 
> **Additional context** Looking around here could it be possible that modules will be overwrite or not installed? What should be modified in the Dockerfile or something else?
> 
> Thanks in advance!

Hi thanks for the issue. I don't know how you can cp docker-compose.dev.yml to docker-compose.yml as there is already a docker compose in there.  In general the docker compose dev is for working with etherpad in a docker environment. So you need to install the dependencies from outside the container with pnpm i in the etherpad root. Then it should hopefully work out.

**Comment by ralfi** [comment]
Thanks a lot, help me to find a solution.

**Important: Apply fixes** from https://github.com/ether/etherpad-lite/commit/8a1a03eca154b1d2516b726bf473dafe69ab706a#diff-cc5a2f170768969f124108ad3be7fdbcbed774c11774d99a87a3a78fef4ab97b


Place the modified config file as you need in **./etherpad-libre/settings.json**

Set the **DEFAULT_PAD_TEXT** var to your favorite string

**Remark** the **SOFFICE** var line in the compose file - dont know why this not work if it set to true

See the working compose file line 3 and 4 for build the image and start the setup ...



![image](https://github.com/user-attachments/assets/302730f4-1783-4dbf-87ec-7362f1dd2b18)
