### ISSUE TITLE
Package.json is missing for local plugin

### ISSUE THREAD

**Issue by ZigzagSecurity** [ether/etherpad-lite#6562]
**Describe the bug**
Hi ! I've been trying to create a custom docker image including some plugins but i'm running into some issues concerning local plugins. 
The image builds successfully if i specify only plugins from NPM registry but as soon as i include a local plugin it fails to find the "package.json" file and exit the build with an error. 

**To Reproduce**
1. Follow the instruction from github repo to create a custom docker image. 
2. Modify the Dockerfile as follow (just adding a local plugin): ```ARG ETHERPAD_LOCAL_PLUGINS="../ep_markdown"```
4. Start the build process with: ```sudo docker build . -t tmp/etherpad```
5. Then get the error with the local plugin

**Expected behavior**
The build should complete successfully and the local plugin should be installed. 

**Screenshots**
The only modification of the Dockerfile:
![image](https://github.com/user-attachments/assets/dc38da34-0704-4dcb-896b-e4c2f3f82242)

The error during the build:
![image](https://github.com/user-attachments/assets/df4d26f0-ce47-485d-8285-c71af95e8ede)

**Server (please complete the following information):**
 - Etherpad version: 2.1.1
 - OS: 
 - Node.js version (`node --version`): node:alpine from docker
 - npm version (`npm --version`): 9.0.4
 - Is the server free of plugins: yes

**Additional context**
I've tried with plugins i've modified myself but also with plugins i've downloaded from npm and put in my local system but the result is the same.

Thanks for reading and your amazing work on Etherpad !

**Comment by SamTV12345** [comment]
> **Describe the bug** Hi ! I've been trying to create a custom docker image including some plugins but i'm running into some issues concerning local plugins. The image builds successfully if i specify only plugins from NPM registry but as soon as i include a local plugin it fails to find the "package.json" file and exit the build with an error.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Follow the instruction from github repo to create a custom docker image.
> 2. Modify the Dockerfile as follow (just adding a local plugin): `ARG ETHERPAD_LOCAL_PLUGINS="../ep_markdown"`
> 3. Start the build process with: `sudo docker build . -t tmp/etherpad`
> 4. Then get the error with the local plugin
> 
> **Expected behavior** The build should complete successfully and the local plugin should be installed.
> 
> **Screenshots** The only modification of the Dockerfile: ![image](https://private-user-images.githubusercontent.com/40743997/355376474-dc38da34-0704-4dcb-896b-e4c2f3f82242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjM1NDIsIm5iZiI6MTcyMjk2MzI0MiwicGF0aCI6Ii80MDc0Mzk5Ny8zNTUzNzY0NzQtZGMzOGRhMzQtMDcwNC00ZGNiLTg5NmItZTRjMmYzZjgyMjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE2NTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2N2E2NTBiNTkyYjg4NjRhNWZkMGFlNWY5YWNmNzE5YTZjNGE0NTM2MDJhMTg3ODQ1NzhhNmY2NmI3MjRhYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lvutyd9fVofDsKS-R609Xmp1FMlAwjlnGzP2ML8d8ps)
> 
> The error during the build: ![image](https://private-user-images.githubusercontent.com/40743997/355376147-df4d26f0-ce47-485d-8285-c71af95e8ede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjM1NDIsIm5iZiI6MTcyMjk2MzI0MiwicGF0aCI6Ii80MDc0Mzk5Ny8zNTUzNzYxNDctZGY0ZDI2ZjAtY2U0Ny00ODVkLTgyODUtYzcxYWY5NWU4ZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE2NTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTAzZWI2NzNkYTVlMTAwYzE1ZTBiMTQ0ZjBjNjU5ZDAxMmRhZTZlZGI0MDg0OGFmMmI2Zjg0NzRlZjVlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWGRZRKnUAUYvCamopQ1erRGSCjYysFHeMcVPXOzP04)
> 
> **Server (please complete the following information):**
> 
> * Etherpad version: 2.1.1
> * OS:
> * Node.js version (`node --version`): node:alpine from docker
> * npm version (`npm --version`): 9.0.4
> * Is the server free of plugins: yes
> 
> **Additional context** I've tried with plugins i've modified myself but also with plugins i've downloaded from npm and put in my local system but the result is the same.
> 
> Thanks for reading and your amazing work on Etherpad !

Hi I had a look at it. It's actually pretty hard to integrate a plugin into the Docker Image. We have the problem that we build now everything in the Dockerfile and Docker does not have access to the host system. @JannikStreek do you have time to take the matter into your hand? I'm not really familiar with the new Docker directives maybe you can there map a local volume

**Comment by JannikStreek** [comment]
> > **Describe the bug** Hi ! I've been trying to create a custom docker image including some plugins but i'm running into some issues concerning local plugins. The image builds successfully if i specify only plugins from NPM registry but as soon as i include a local plugin it fails to find the "package.json" file and exit the build with an error.
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Follow the instruction from github repo to create a custom docker image.
> > 2. Modify the Dockerfile as follow (just adding a local plugin): `ARG ETHERPAD_LOCAL_PLUGINS="../ep_markdown"`
> > 3. Start the build process with: `sudo docker build . -t tmp/etherpad`
> > 4. Then get the error with the local plugin
> > 
> > **Expected behavior** The build should complete successfully and the local plugin should be installed.
> > **Screenshots** The only modification of the Dockerfile: ![image](https://private-user-images.githubusercontent.com/40743997/355376474-dc38da34-0704-4dcb-896b-e4c2f3f82242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjM1NDIsIm5iZiI6MTcyMjk2MzI0MiwicGF0aCI6Ii80MDc0Mzk5Ny8zNTUzNzY0NzQtZGMzOGRhMzQtMDcwNC00ZGNiLTg5NmItZTRjMmYzZjgyMjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE2NTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2N2E2NTBiNTkyYjg4NjRhNWZkMGFlNWY5YWNmNzE5YTZjNGE0NTM2MDJhMTg3ODQ1NzhhNmY2NmI3MjRhYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lvutyd9fVofDsKS-R609Xmp1FMlAwjlnGzP2ML8d8ps)
> > The error during the build: ![image](https://private-user-images.githubusercontent.com/40743997/355376147-df4d26f0-ce47-485d-8285-c71af95e8ede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjM1NDIsIm5iZiI6MTcyMjk2MzI0MiwicGF0aCI6Ii80MDc0Mzk5Ny8zNTUzNzYxNDctZGY0ZDI2ZjAtY2U0Ny00ODVkLTgyODUtYzcxYWY5NWU4ZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE2NTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTAzZWI2NzNkYTVlMTAwYzE1ZTBiMTQ0ZjBjNjU5ZDAxMmRhZTZlZGI0MDg0OGFmMmI2Zjg0NzRlZjVlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWGRZRKnUAUYvCamopQ1erRGSCjYysFHeMcVPXOzP04)
> > **Server (please complete the following information):**
> > 
> > * Etherpad version: 2.1.1
> > * OS:
> > * Node.js version (`node --version`): node:alpine from docker
> > * npm version (`npm --version`): 9.0.4
> > * Is the server free of plugins: yes
> > 
> > **Additional context** I've tried with plugins i've modified myself but also with plugins i've downloaded from npm and put in my local system but the result is the same.
> > Thanks for reading and your amazing work on Etherpad !
> 
> Hi I had a look at it. It's actually pretty hard to integrate a plugin into the Docker Image. We have the problem that we build now everything in the Dockerfile and Docker does not have access to the host system. @JannikStreek do you have time to take the matter into your hand? I'm not really familiar with the new Docker directives maybe you can there map a local volume

I can have a look at it. On first glance, the given plugins are indeed currently not copied into the container so it can't really work.

**Comment by SamTV12345** [comment]
> > > **Describe the bug** Hi ! I've been trying to create a custom docker image including some plugins but i'm running into some issues concerning local plugins. The image builds successfully if i specify only plugins from NPM registry but as soon as i include a local plugin it fails to find the "package.json" file and exit the build with an error.
> > > **To Reproduce** Steps to reproduce the behavior:
> > > 
> > > 1. Follow the instruction from github repo to create a custom docker image.
> > > 2. Modify the Dockerfile as follow (just adding a local plugin): `ARG ETHERPAD_LOCAL_PLUGINS="../ep_markdown"`
> > > 3. Start the build process with: `sudo docker build . -t tmp/etherpad`
> > > 4. Then get the error with the local plugin
> > > 
> > > **Expected behavior** The build should complete successfully and the local plugin should be installed.
> > > **Screenshots** The only modification of the Dockerfile: ![image](https://private-user-images.githubusercontent.com/40743997/355376474-dc38da34-0704-4dcb-896b-e4c2f3f82242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjM1NDIsIm5iZiI6MTcyMjk2MzI0MiwicGF0aCI6Ii80MDc0Mzk5Ny8zNTUzNzY0NzQtZGMzOGRhMzQtMDcwNC00ZGNiLTg5NmItZTRjMmYzZjgyMjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE2NTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2N2E2NTBiNTkyYjg4NjRhNWZkMGFlNWY5YWNmNzE5YTZjNGE0NTM2MDJhMTg3ODQ1NzhhNmY2NmI3MjRhYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lvutyd9fVofDsKS-R609Xmp1FMlAwjlnGzP2ML8d8ps)
> > > The error during the build: ![image](https://private-user-images.githubusercontent.com/40743997/355376147-df4d26f0-ce47-485d-8285-c71af95e8ede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjM1NDIsIm5iZiI6MTcyMjk2MzI0MiwicGF0aCI6Ii80MDc0Mzk5Ny8zNTUzNzYxNDctZGY0ZDI2ZjAtY2U0Ny00ODVkLTgyODUtYzcxYWY5NWU4ZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE2NTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTAzZWI2NzNkYTVlMTAwYzE1ZTBiMTQ0ZjBjNjU5ZDAxMmRhZTZlZGI0MDg0OGFmMmI2Zjg0NzRlZjVlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWGRZRKnUAUYvCamopQ1erRGSCjYysFHeMcVPXOzP04)
> > > **Server (please complete the following information):**
> > > 
> > > * Etherpad version: 2.1.1
> > > * OS:
> > > * Node.js version (`node --version`): node:alpine from docker
> > > * npm version (`npm --version`): 9.0.4
> > > * Is the server free of plugins: yes
> > > 
> > > **Additional context** I've tried with plugins i've modified myself but also with plugins i've downloaded from npm and put in my local system but the result is the same.
> > > Thanks for reading and your amazing work on Etherpad !
> > 
> > 
> > Hi I had a look at it. It's actually pretty hard to integrate a plugin into the Docker Image. We have the problem that we build now everything in the Dockerfile and Docker does not have access to the host system. @JannikStreek do you have time to take the matter into your hand? I'm not really familiar with the new Docker directives maybe you can there map a local volume
> 
> I can have a look at it. On first glance, the given plugins are indeed currently not copied into the container so it can't really work.

Thanks for the help :)

**Comment by JannikStreek** [comment]
@ZigzagSecurity I think the easiest way (which doesn't need any changes in the code base ) would be to mount your local files (e.g. in the docker compose volume section). Lets take the example of "../ep_markdown":
```
    volumes:
      - ../ep_markdown:/opt/ep_markdown
      
```

You can also mount without using docker compose, but its easier to demonstrate it in this case.

With that it should work 🤔 Can you test it?

**Comment by JannikStreek** [comment]
> @ZigzagSecurity I think the easiest way (which doesn't need any changes in the code base ) would be to mount your local files (e.g. in the docker compose volume section). Lets take the example of "../ep_markdown":
> 
> ```
>     volumes:
>       - ../ep_markdown:/opt/ep_markdown
>       
> ```
> 
> You can also mount without using docker compose, but its easier to demonstrate it in this case.
> 
> With that it should work 🤔 Can you test it?

Ah sorry, my bad, that won't work as the mount is too late. Can you add this to your docker file before the install command (`RUN bin/installDeps.sh`) is reached in the Dockerfile and see if it works:

```
COPY --chown=etherpad:etherpad ../ep_markdown ../ep_markdown/
```

Otherwise I will test myself later. We should modify the docker file to copy all plugins given in `ETHERPAD_LOCAL_PLUGINS` to the container during build time before the install command is called.

**Comment by ZigzagSecurity** [comment]
@JannikStreek i tried it but went into the same issue as reported in the first place. 
The instruction you specified did not work as the folder is out of the Docker context and thus can't be reach during the build (from what i could understand after a quick google search). 
![image](https://github.com/user-attachments/assets/2862f54d-d71b-4be2-8c5d-03fe038c19ed)

I changed it to: 
```
COPY --chown=etherpad:etherpad ./ep_markdown ./ep_markdown/
``` 
The plugins seems to be copied to the docker but then an error happens when the dependencies are being installed. 
![image](https://github.com/user-attachments/assets/ab6951bf-089b-4c8f-be89-d9f3248f018b)

![image](https://github.com/user-attachments/assets/abdb89e4-2b2d-4c26-9d52-5ac474a83475)
i also changed the argument for local plugin accordingly: 
```
ARG ETHERPAD_LOCAL_PLUGINS="./ep_markdown"
```

**Comment by SamTV12345** [comment]
> @JannikStreek i tried it but went into the same issue as reported in the first place. The instruction you specified did not work as the folder is out of the Docker context and thus can't be reach during the build (from what i could understand after a quick google search). ![image](https://private-user-images.githubusercontent.com/40743997/363185996-2862f54d-d71b-4be2-8c5d-03fe038c19ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTE2MzYsIm5iZiI6MTcyNjM5MTMzNiwicGF0aCI6Ii80MDc0Mzk5Ny8zNjMxODU5OTYtMjg2MmY1NGQtZDcxYi00YmUyLThjNWQtMDNmZTAzOGMxOWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA5MDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NTk1YzRjMTc2YzQzMTkwZDMzYmNjMmE3Y2I5ODc5ZTIxYWJmOWYyMzAxMzljOWZjMWUxZGUyYzllMTk3MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0EpEfDBFtv3goi58lHQqxSGwBHwZ-A3tI0Ng06uE3-E)
> 
> I changed it to:
> 
> ```
> COPY --chown=etherpad:etherpad ./ep_markdown ./ep_markdown/
> ```
> 
> The plugins seems to be copied to the docker but then an error happens when the dependencies are being installed. ![image](https://private-user-images.githubusercontent.com/40743997/363183328-ab6951bf-089b-4c8f-be89-d9f3248f018b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTE2MzYsIm5iZiI6MTcyNjM5MTMzNiwicGF0aCI6Ii80MDc0Mzk5Ny8zNjMxODMzMjgtYWI2OTUxYmYtMDg5Yi00YzhmLWJlODktZDlmMzI0OGYwMThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA5MDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NzJlZjdiYjdlNWM3ZWEwMDc4ZWJiMzdiMzVhY2YyMTlkODYyZDg4ODM0ZjkyZTUzZTZiMDJjNzIyNWMwNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QYtgjsum7dilqIzaBlSRDfAivl6zY54hCk0WpF0n9MM)
> 
> ![image](https://private-user-images.githubusercontent.com/40743997/363182924-abdb89e4-2b2d-4c26-9d52-5ac474a83475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTE2MzYsIm5iZiI6MTcyNjM5MTMzNiwicGF0aCI6Ii80MDc0Mzk5Ny8zNjMxODI5MjQtYWJkYjg5ZTQtMmIyZC00YzI2LTlkNTItNWFjNDc0YTgzNDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA5MDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ODFkMWY5MjU0OGUzOWFmNTdiNTA3ZjVjMTlkOGQ1YmZhY2U1NjBmN2Y1ZmI2YzRhYTEyYmNhMGQyYTViOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fg-hHakyFdk8-ns0iv7TG0c7R_7xvKL048uHtiihZgA) i also changed the argument for local plugin accordingly:
> 
> ```
> ARG ETHERPAD_LOCAL_PLUGINS="./ep_markdown"
> ```

Yes that should be the solution. It's unfortunate that you can't mount directories at build time. Maybe this will come at some time.
