### ISSUE TITLE
Please make this installable on Windows 11

### ISSUE THREAD

**Issue by Hlafordlaes** [ether/etherpad-lite#6563]
* * *

name: Feature request
about: Windows installation
title: ''Make it installable on Windows 10/11"
labels: 
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**

Cannot install. No matter whether Node.js is installed, or pnpm is installed, start.bat ALWAYS fails with:
```
node:internal/modules/cjs/loader:1148
  throw err;
  ^
Error: Cannot find module 'get-tsconfig'
```

**Describe the solution you'd like**
I really want to use this tool with my team. None can install this software on their Windows 10 or 11 systems. It seems to be tailor made for linux only. This message is our very last ditch effort before moving on to something else. Seemed like such a nice solution; too bad.

**Comment by SamTV12345** [comment]
> name: Feature request about: Windows installation title: ''Make it installable on Windows 10/11" labels: assignees:
> 
> **Is your feature request related to a problem? Please describe.**
> 
> Cannot install. No matter whether Node.js is installed, or pnpm is installed, start.bat ALWAYS fails with:
> 
> ```
> node:internal/modules/cjs/loader:1148
>   throw err;
>   ^
> Error: Cannot find module 'get-tsconfig'
> ```
> 
> **Describe the solution you'd like** I really want to use this tool with my team. None can install this software on their Windows 10 or 11 systems. It seems to be tailor made for linux only. This message is our very last ditch effort before moving on to something else. Seemed like such a nice solution; too bad.

Seems like the dependencies are not installed. You need to first do pnpm i in the root directory of Etherpad and then run `.\start.bat`.

**Comment by SamTV12345** [comment]
> name: Feature request about: Windows installation title: ''Make it installable on Windows 10/11" labels: assignees:
> 
> **Is your feature request related to a problem? Please describe.**
> 
> Cannot install. No matter whether Node.js is installed, or pnpm is installed, start.bat ALWAYS fails with:
> 
> ```
> node:internal/modules/cjs/loader:1148
>   throw err;
>   ^
> Error: Cannot find module 'get-tsconfig'
> ```
> 
> **Describe the solution you'd like** I really want to use this tool with my team. None can install this software on their Windows 10 or 11 systems. It seems to be tailor made for linux only. This message is our very last ditch effort before moving on to something else. Seemed like such a nice solution; too bad.

These are the steps to get Etherpad running on Windows. I develop myself on Windows only so it does work. Etherpad 1.x was a pain to install on Windows.

1. Download the latest Node.js runtime from [nodejs.org](https://nodejs.org/).
2. Install pnpm: `npm install -g pnpm` (Administrator privileges may be required).
3. Clone the repository: `git clone -b master`
4. Run `pnpm i`
5. Run `pnpm run build:etherpad`
6. Run `pnpm run prod`
7. Visit `http://localhost:9001` in your browser.
