### ISSUE TITLE
Admin page: add possibility to sort by last update dates for modules

### ISSUE THREAD

**Issue by meaz** [ether/etherpad-lite#6574]
It would be nice to be able, from the admin page, to sort the modules/plugins by last update dates. I think this was the case in the past. It allows for example to see what recent plugins were created or updated.

**Comment by SamTV12345** [comment]
Feel free to try it out on develop. The columns name, version and last updated should be sortable.

**Comment by meaz** [comment]
Thanks, perfect, it works like a charm.
