### ISSUE TITLE
Download Version 2.2.2 for Windows is inaccessible

### ISSUE THREAD

**Issue by elmatusov** [ether/etherpad-lite#6575]
It looks like Etherpad Lite 2.2.2 was released on August 9, 2024. Two days have passed since, but Download Version 2.2.2 for Windows is still inaccessible on the [Etherpad site](https://etherpad.org/). When I click on the button "Windows", I'm getting the following message: 

>  File not present

>  The GitHub release has been created

> Please wait for up to an hour. If the Windows version is not created after that period. Please create an issue.

> If you want to get started with another etherpad version just click on the other releases button and choose an older release

When will Etherpad Lite 2.2.2 be available for Windows? Thanks!

**Comment by SamTV12345** [comment]
Hi thanks for the report. The link was broken. I fixed it. You can now simply download your desired version again.

**Comment by elmatusov** [comment]
> Hi thanks for the report. The link was broken. I fixed it. You can now simply download your desired version again.

Thanks a lot, SamTV12345! Yes, you definitely resolved the issue.
