### ISSUE TITLE
nginx with Etherpad in a subdirectory

### ISSUE THREAD

**Issue by tgrymatt** [ether/etherpad-lite#6588]
I have the same problem like described in issue https://github.com/ether/etherpad-lite/issues/5359 in the start posting. I am use the "branch master" of etherpad. And configured the nginx described like here:

https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#from-subdirectory-url

But if I then open

http://domain.tld:80/pad/

the static files are missing.
<img width="2558" alt="Bildschirmfoto 2024-08-16 um 11 38 06" src="https://github.com/user-attachments/assets/d236c5ed-a49d-43f5-9c34-1f22a77d2173">

_Originally posted by @tgrymatt in https://github.com/ether/etherpad-lite/issues/5359#issuecomment-2293182167_

**Comment by tgrymatt** [comment]
It seems that it has to do with version 2.2.2 and the current master branch. In version 2.1.1 everything works as it says in the Etherpad documentation.

**Comment by brknkfr** [comment]
I have the same problem with version 2.2.2. As you closed the ticket, what was your solution @tgrymatt?

**Comment by tgrymatt** [comment]
@brknkfr there was no solution with 2.2.2, I installed the 2.1.1 and then it worked. That's enough for my requirement at this moment.
