### ISSUE TITLE
[2.2.4 docker-compose] is unable to pass ETHERPAD_LOCAL_PLUGINS via ARG during build and runtime

### ISSUE THREAD

**Issue by bharath-naik** [ether/etherpad-lite#6640]
**Description**
I am trying to pass local plugins to Etherpad-Lite using the `ETHERPAD_LOCAL_PLUGINS` argument in the `docker-compose.yml` file, but the plugins are not being installed correctly during the Docker build process.

**To Reproduce**
- I am using Etherpad-Lite 2.2.4
-  At the same home location, i have my customPlugins folder.
-  Not changed anything much related to plugin installation in the Dockefile
- Below is my modified `docker-compose.yml` file:
  ```yaml
  services:
    etherpad-2.4:
      build:
        context: ../etherpad-lite-2.2.4/
        dockerfile: Dockerfile
        args:
          ETHERPAD_LOCAL_PLUGINS: "../customPlugins/ep_headings3 ../customPlugins/ep_align"
      tty: true

**Expected behavior**
The local plugins from ../customPlugins/ep_headings3 and ../customPlugins/ep_align should be installed during the build process via pnpm or should be loaded during docker-compose run time.

**Server (please complete the following information):**
Etherpad version: 2.2.2
OS: Ubuntu 22
Node.js version (22):
npm version (10.8):
pnpm version (9.9.0)
Is the server free of plugins: yes

**Comment by SamTV12345** [comment]
Unfortunately Docker does not allow to map a directory at build time. Please try to use COPY ../customPlugins/ep_headings3 ../customPlugins/ep_align in your Dockerfile
