### ISSUE TITLE
index.html for /admin missing after update to 2.2.5

### ISSUE THREAD

**Issue by matthias-mader** [ether/etherpad-lite#6683]
after updating to 2.2.5, the index.html for /admin at /src/templates/admin is missing

**Comment by SamTV12345** [comment]
How did you install Etherpad? Did you execute `pnpm run build:etherpad`?

**Comment by matthias-mader** [comment]
No, after updating I'm only executing `bin/installDeps.sh`. In the past that worked fine on every update.
Running `pnpm run build:etherpad` fixed the problem. I'll update my updating-routing.
