### ISSUE TITLE
Docker runtime does not apply EP__ variables to settings

### ISSUE THREAD

**Issue by misilot** [ether/etherpad-lite#6699]
**Describe the bug**
I am applying
```
      EP__PLUGIN__ep_google_analytics__gaCode: G-NLVFX369BM
      EP__PLUGIN__ep_matomo__matomoSiteId: 43
      EP__PLUGIN__ep_matomo__matomoHostname: webanalytics.lib.k-state.edu
```
or 
```
      EP__ep_google_analytics__gaCode: G-ffasdfadsf
      EP__ep_matomo__matomoSiteId: 43
      EP__ep_matomo__matomoHostname: servername
```
 since the docoumentation isn't clear https://github.com/ether/etherpad-lite/blob/develop/doc/docker.md?plain=1#L223 or is it https://github.com/ether/etherpad-lite/blob/develop/doc/docker.md?plain=1#L237

**To Reproduce**
1. Add env variables
2. login to admin panel, check settings, see nothing for matomo or google analytics present.

**Expected behavior**
Should see variables in the settings, so they can be used.

**Screenshots**

**Server (please complete the following information):**
 - Etherpad version: 2.2.5
 - OS: [e.g., Ubuntu 20.04]: see container
 - Node.js version (`node --version`): see container
 - npm version (`npm --version`): see container
 - Is the server free of plugins:  no ...

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 131

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SamTV12345** [comment]
> **Describe the bug** I am applying
> 
> ```
>       EP__PLUGIN__ep_google_analytics__gaCode: G-NLVFX369BM
>       EP__PLUGIN__ep_matomo__matomoSiteId: 43
>       EP__PLUGIN__ep_matomo__matomoHostname: webanalytics.lib.k-state.edu
> ```
> 
> or
> 
> ```
>       EP__ep_google_analytics__gaCode: G-ffasdfadsf
>       EP__ep_matomo__matomoSiteId: 43
>       EP__ep_matomo__matomoHostname: servername
> ```
> 
> since the docoumentation isn't clear https://github.com/ether/etherpad-lite/blob/develop/doc/docker.md?plain=1#L223 or is it https://github.com/ether/etherpad-lite/blob/develop/doc/docker.md?plain=1#L237
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Add env variables
> 2. login to admin panel, check settings, see nothing for matomo or google analytics present.
> 
> **Expected behavior** Should see variables in the settings, so they can be used.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Server (please complete the following information):**
> 
> * Etherpad version: 2.2.5
> * OS: [e.g., Ubuntu 20.04]: see container
> * Node.js version (`node --version`): see container
> * npm version (`npm --version`): see container
> * Is the server free of plugins:  no ...
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS] MacOS
> * Browser [e.g. chrome, safari] Firefox
> * Version [e.g. 22] 131
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

Oh I see the confusion. It should be the second one. PLUGIN was simply the replacement for an actual plugin. With the second one the settings are correctly applied. That is actually a usability problem. The admin panel simply shows the file so what is contained in your settings.json file laying around. It does not contain the env variables. The reason is that you couldn't edit them anyways.

**Comment by SamTV12345** [comment]
> Ok, thanks! I wasn't sure if it was taking the values and rendering the settings.json at runtime.
> 
> Should I need to do anything besides setting these environment variables to enable the plugins?
> 
> ```
>       EP__ep_google_analytics__gaCode: G-ffasdfadsf
>       EP__ep_matomo__matomoSiteId: 43
>       EP__ep_matomo__matomoHostname: servername
> ```

You're welcome :) . This should be everything. The plugins are third party so not managed by the Etherpad foundation directly. ep_google_analytics has seen the last update 12 years ago. I don't know if it still works. But give it a try.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
