### ISSUE TITLE
Can't authenticate for using HTTP API

### ISSUE THREAD

**Issue by sibas129** [ether/etherpad-lite#6727]
I'm trying to authenticate via an OAuth token to start using API. But I get an error invalid_redirect_uri. I'm using default client id and secret from settings.json. Could you explain, what is the problem? Or what other ways to get token?
![image](https://github.com/user-attachments/assets/f6efbfbe-b568-4fb4-8883-2995775b0934)
![image](https://github.com/user-attachments/assets/2dafe050-f294-4b62-bc05-b8e2f267f5dc)

**Comment by SamTV12345** [comment]
How did you try to authenticate? You normally add this information to e.g. Postman and have no problem.

**Comment by sibas129** [comment]
I tried to send a GET request to postman at /oidc/auth using information from setting.json. I fixed the uri problem, but now I'm getting an error with PKCE. Error text:

>   allow_redirect: true,
>   error: 'invalid_request',
>   status: 400,
>   statusCode: 400,
>   expose: true,
>   error_description: 'Authorization Server policy requires PKCE to be used for this request',
>   error_detail: undefined

**Comment by SamTV12345** [comment]
> I tried to send a GET request to postman at /oidc/auth using information from setting.json. I fixed the uri problem, but now I'm getting an error with PKCE. Error text:
> 
> 
> 
> >   allow_redirect: true,
> 
> >   error: 'invalid_request',
> 
> >   status: 400,
> 
> >   statusCode: 400,
> 
> >   expose: true,
> 
> >   error_description: 'Authorization Server policy requires PKCE to be used for this request',
> 
> >   error_detail: undefined

There's a switch in Postman Authorization Code and Authorzation Code with PKCE. You need the last one.

**Comment by SamTV12345** [comment]
![image](https://github.com/user-attachments/assets/79fa576e-a0b3-46fc-8cb1-1b3ebeacebcb)

This is an example for retrieving a token
