### ISSUE TITLE
Can't find documentation on how to update/upgrade ep-lite to new version

### ISSUE THREAD

**Issue by ajformation** [ether/etherpad-lite#6728]
* * *

name: Doc on upgrade process

* * *

**Is your feature request related to a problem? Please describe.**
I can't find easily documentation on update/upgrade process

**Describe the solution you'd like**
A documentation in the wiki page on how to upgrade etherpad-lite

**Comment by ajformation** [comment]
For example something simple as that is ok :

```shell
# As etherpad-user
$ which node
/opt/etherpad/.nvm/versions/node/v23.1.0/bin/node
$ cd <etherpad-lite-path>
$ git checkout v2.2.5 
$ git switch -c v2.2.5
$ ./bin/run.sh
...
```

It's simple

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by SamTV12345** [comment]
> For example something simple as that is ok :
> 
> 
> 
> ```shell
> 
> # As etherpad-user
> 
> $ which node
> 
> /opt/etherpad/.nvm/versions/node/v23.1.0/bin/node
> 
> $ cd <etherpad-lite-path>
> 
> $ git checkout v2.2.5 
> 
> $ git switch -c v2.2.5
> 
> $ ./bin/run.sh
> 
> ...
> 
> ```
> 
> 
> 
> It's simple

Good idea. That would be a solution. If you'd like to you can file a pr.

**Comment by ajformation** [comment]
PR Created

Thanks for review it

**Comment by SamTV12345** [comment]
Thanks for the pr :)
