### ISSUE TITLE
Start.bat won't run

### ISSUE THREAD

**Issue by Wass89** [ether/etherpad-lite#6764]
Premise: I am a new Etherpad user and as such I'm still very inexperient.

I am trying to install Etherpad lite on my PC, which runs on Windows 10 Home. I followed instructions on the Etherpad website, installed the latest Node.js runtime and attempted to execute start.bat as administrator. However, when I do that, the console windows shuts itself down immediately, and I cannot proceed with the installation.

I realize this may be a very simple issue, but I have looked for an answer and haven't been able to find it. Apologies in advance if I have overlooked something. Any help would be appreciated.

1. Download Windows Version 2.2.6 from Etherpad website
2. Extract all files from WinRar archive
3. Right-click on start.bat and choose run as administrator

**Expected behavior**
Console window ought to open and, through browser, allow me to reach localhost and set up server.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Firefox 132.0.2 (64-bit)
 - Version: Etherpad Lite 2.2.6

**Comment by SamTV12345** [comment]
It could be that some part of the website is outdated.  There is an up to date readme in the github description. You just do the following:


Download the latest Node.js runtime from [nodejs.org](https://nodejs.org/).
Install pnpm: npm install -g pnpm (Administrator privileges may be required).
Clone the repository: git clone -b master
Run pnpm i
Run pnpm run build:etherpad
Run pnpm run prod
Visit http://localhost:9001 in your browser.
