### ISSUE TITLE
Ability to add anchors

### ISSUE THREAD

**Issue by Fujnky** [ether/etherpad-lite#750]
I think it would be good to have anchors in pads, so you could just link to a specific point in the text (e.g.http://beta.etherpad.org/p/test#foo). Linking specific lines would also be a possibility, but too static for vividly edited pads.

Edit: Just found out this is also on the TODO list in the wiki, but that doesn't matter, does it? :)

**Comment by PhilLAL** [comment]
Hi, it seems interesting but it seems to me it does not solve the problem if we write some lines before the target anchor.
Example : 
line 1:  part 1
line 2: blabla
line 3: part 2

The link will be linked to line 3.

If we then create a part 1.1 like this : 
line 1:  part 1
line 2: blabla
line 3: part 1.1
line 4: part 2

The link will point to part 1.1 and not point to part 2.

Do you know a solution to do this?

**Comment by lpagliari** [comment]
@PhilLAL you would need some kind of "named anchors", so "part 2" would always be found, no matter which line it is. You can use a `line attribute` to mark line with "part 2", and would need a way to know what it the name of that link. But as far as something already implemented, I don't know any.

**Comment by PhilLAL** [comment]
Thank you. for your answer.

**Comment by PhilLAL** [comment]
I found ep_scrolltoanchor (https://www.npmjs.org/package/ep_scrolltoanchor
It seems to be a viable solution...

**Comment by lpagliari** [comment]
Thanks, @PhilLAL
