### ISSUE TITLE
Set author name from HTTP auth data

### ISSUE THREAD

**Issue by rcarmo** [ether/etherpad-lite#759]
I've been looking for an easy way to set the author name automatically from HTTP auth data. Either this is a documentation issue and the auth settings aren't supposed to work in this way, or this is a missing (trivial?) feature.

It would be excellent if the author name was automatically set either from the HTTP REMOTE_USER environment variable or from an (admin-specified) HTTP header (or callback function).

**Comment by volter** [comment]
I guess this should read https://github.com/ether/etherpad-lite/issues/551
