### ISSUE TITLE
validUntil should almost certainly be validFor

### ISSUE THREAD

**Issue by MarkTraceur** [ether/etherpad-lite#781]
The createSession API call takes a UNIX timestamp in seconds, which is nice, but using a number of seconds, from creation, would definitely be even better--especially since system time on the client side might be in a strange time zone or somehow modified.

Just a thought :)

**Comment by JohnMcLear** [comment]
Bounty: https://www.bountysource.com/issues/1371871-validuntil-should-almost-certainly-be-validfor
