### ISSUE TITLE
Allow special characters in pad names

### ISSUE THREAD

**Issue by MarkTraceur** [ether/etherpad-lite#785]
I'm not sure if there are any, or very many, barriers to this one, but as noted earlier today in issue #779, "/p/Testing:1234" redirects to "Testing_1234", which might not be expected. I'd like to allow colons in the URL if possible.

I'm also not sure whether unicode characters get removed, but if they are, it would be great to leave them in.

Thanks!

**Comment by JohnMcLear** [comment]
I'm not sure this is still an issue?

**Comment by elijh** [comment]
beta does not replace ; with _

the wiki has correct instructions for utf8 setup for mysql.

**Comment by JohnMcLear** [comment]
Good to close this then :D  Only took 5 years for me to read this comment...
