### ISSUE TITLE
Incorrect report of HTTP 405

### ISSUE THREAD

**Issue by MarkTraceur** [ether/etherpad-lite#796]
From Wikipedia:

> 405 Method Not Allowed - A request was made of a resource using a request method not supported by that resource; for example, using GET on a form which requires data to be presented via POST, or using PUT on a read-only resource.

However, I just got a 405 for POSTing to /api//1/createAuthorIfNotExistsFor. It's correct to error on that, but the _method_ isn't the problem, the _path_ is. 404 is the correct error for that.

I don't know how routing is done, so this may be an upstream bug. If so, I can submit it, just direct me.

**Comment by JohnMcLear** [comment]
Closing as APi has changed significantly.
