### ISSUE TITLE
Allow the word 'Pad' to be customized / configurable / abstracted

### ISSUE THREAD

**Issue by tohir** [ether/etherpad-lite#884]
Currently, the word 'pad' is hardcoded like: <h1>Pad settings</h1>

Having pad as abstracted (though default to 'pad') allows implementations to refer to etherpad as is appropriate per context. 'Document Settings', 'Wiki Settings', 'Doc settings', 'Note-taker settings', 'Meeting Notes settings', etc.

This would also come in handy when enabling multilingual interfaces

**Comment by JohnMcLear** [comment]
I don't want to dilute the brand any further.  We do enough.
