### ISSUE TITLE
Requesting an "Introduction to the source"

### ISSUE THREAD

**Issue by marcelklehr** [ether/etherpad-lite#953]
Many people have difficulties with diving into the source and joining in with development.

I think this is due to the complexity of the source code. In order to resolve the first problem, I suggest that someone, who has a thorough understanding of the code base writes an "Introduction to the source".

I believe, this could lower the learning curve of joining in with development, and should make it easier for potential contributors to get started with Etherpad lite development.

**Comment by JohnMcLear** [comment]
We can fund this here: https://www.bountysource.com/issues/1371920-requesting-an-introduction-to-the-source

**Comment by marcelklehr** [comment]
See https://github.com/ether/etherpad-lite/wiki/Introduction-to-the-source for a start

**Comment by JohnMcLear** [comment]
Closing as developers seem comfortable with Wiki as it stands.  Yea a whole developer friendly page would be nice but it will be an ongoing effort and doesn't necessarily need to be kept open as an issue.
